### ISSUE TITLE
Can't change host email in Dnn 9

### ISSUE THREAD

**Issue by valadas** [dnnsoftware/Dnn.Platform#2050]
In previous versions of Dnn, there was a setting in Host Settings to set the host email. This email was used when testing the SMTP server settings. So when testing the emails, users do not receive the email since they don't have access to host@change.me (the default on new installations)

Also, some modules may use that email address to notify the host, so people changing their email and not having control over this, stop receiving those notifications.

I think this could be added in Settings -> Server Settings -> SMTP Server

In the database, this is stored in HostSettings Table with a SettingName of HostEmail

**Comment by bdukes** [comment]
I'm not necessarily opposed to putting this back, and I don't know the original rationale (if any) around leaving it out.  However, one downside of having the host email is that it's rarely used and an easy setting to miss, so it can cause these important host-only emails to be missed.  Would it make more sense to default the host email to the email of the administrator of the host portal?

**Comment by valadas** [comment]
@bdukes Agreed, but where would the smtp configuration test email on the host level setting be sent? On the admin email of the currently logged in portal administrator email? 

I am talking about a situation where the host and admin would be 2 different persons. For instance, I would have a host account with host@somewebsite.com and my customer would be an admin with an email of admin@designerwebsite.com, then I would not be able to verify the smtp settings are working (by actually receiving the message) at host@clientdomain.com right. So I would have to contact the admin to know if it worked...

Also, module developers may have implemented some things that send notifications only to the host and not the admins for let's say debugging or some other use case.

**Comment by bdukes** [comment]
In my proposed solution above, the test email would be sent to the email address of the administrator account for the host portal.  If that's troublesome, you could re-assign the administrator account during the test (but I can certainly see how that would be undesirable and/or hard to figure out).

For the SMTP test, should you just be able to specify the email?

For new sites, I think combining the host email and the host portal's admin email simplifies things, but migrating an existing site where those are different becomes tricky.

The simple solution is just to add back the host email setting (where would this go?), does anyone in the @dnnsoftware/tag have other thoughts or considerations to add?

**Comment by valadas** [comment]
I think just adding the host email in the SMTP config screen would do it. That could simply map to the existing hostemail field in the hostsettings table and we are done.

**Comment by birksy89** [comment]
We just had the same issue when working on a client site. All of our sites start from a "template install" where we have our preferred settings for DNN.

Sometimes the client wants all user notifications etc to some from their branded email account. So we swap out the SMTP settings and historically changed the "host email" at this point.

We also had to do this via the DB - But we would vote to have this reintroduced

**Comment by valadas** [comment]
I am closing this issue because I moved it to https://github.com/dnnsoftware/Dnn.AdminExperience.Library/issues/160
I will be submitting a pull request there in a few minutes.
