### ISSUE TITLE
Cant clone repository due to ClientDependency submodule

### ISSUE THREAD

**Issue by valadas** [dnnsoftware/Dnn.Platform#2051]
I could not clone the repository because the ClientDependency submodule had a url of:
git@github.com:dnnsoftware/ClientDependency.git

Replacing it with:
https://github.com/dnnsoftware/ClientDependency.git seams to fix the issue, but I don't know if git@githumb.com was used for some other reason, I am sending a pull request but feel free to comment if this may break something else...

**Comment by tpluscode** [comment]
`git@` repository link should work just fine. Could you share the error you were getting?
