### ISSUE TITLE
Opening up certain methods in LocalizationProvider that are useful for others.

### ISSUE THREAD

**Issue by donker** [dnnsoftware/Dnn.Platform#2058]
Most of the code to access resource files is hidden because the methods are private. The public code revolves around retrieval of a localized resource and getting a "Compiled Resource File" meaning a dictionary of entries with best effort translated values for a given combination of resource file and locale.

I'd like to see the following methods become public:

1. ```Dictionary<string, string> GetResourceFile(string resourceFile)```
This is one of the most basic methods in this class. It loads a given file and returns it as a dictionary.

2. ```GetResourceFilename```
Currently there are 2 overloads. I'd like to see the most complete one public. And the current ones are missing the "ResourceType" parameter which would tell it whether it should be a Host/Portal/None file. We should have a single complete entry point where any developer can get the correct resource file name given all parameters. So a new overload that takes ```string resourceFileRoot, string language, PortalSettings portalSettings, CustomizedLocale resourceType``` as parameters.

The use case: in several cases I've run into this when creating translation tools for DNN. It is frustrating to have to recreate the entire class because methods have been made private that were necessary for me to access.

**Comment by sleupold** [comment]
I agree, for creating a translation tool, those methods should be public,
But maybe we should add a comment, not to use this in other modules for presenting translations, which should rely on the compiled resource file and not try to load specific resource files (system, host, portal) itself.

**Comment by sleupold** [comment]
There is still the idea, to pull all resource files during install into a database table. which would make retrieval much easier and better chime in into an overall multilingual experience.

**Comment by donker** [comment]
True. We had that discussion. I guess that discussion is in limbo while we discuss the bigger .net core issue. It is also a much bigger change. What I'd propose is to make these changes in the current library which ultimately gets replaced in the more distant future for a new approach if we decide to go that way.
