### ISSUE TITLE
Client Dependency Reference is BLOCKING any local development

### ISSUE THREAD

**Issue by ahoefling** [dnnsoftware/Dnn.Platform#2061]
The ClientDependency.Core reference in the DNN_Platform.sln is breaking and blocking any local development on the platform. This was originally setup as a git submodule but has been causing lots of issues for several developers.

I have been speaking with the team in DNN TAG and we have a proposed solution:

* Add a nuget on the DNN MyGet for the Client Dependency project [https://github.com/dnnsoftware/ClientDependency](https://github.com/dnnsoftware/ClientDependency)
* Update the platform code to reference via NuGet

**Comment by ahoefling** [comment]
I created a fork that is compiling right now with the ClientDependency.Core submodule removed. Once we get the forked repo building and producing a nuget file I will update the branch I have and submit a Pull Request

**Comment by ahoefling** [comment]
@tpluscode Yes, I just need to be given access to the DNN Company on github and access to that repository so I can create the necessary builds in AppVeyor. 

This isn't really a complicated setup process at all, it is just a matter of getting access and then I can setup the builds and submit a PR

**Comment by bdukes** [comment]
What I usually do when setting up AppVeyor on someone else's repo is to set it up for my fork, and then create a PR for the final `appveyor.yml` file, which they can then merge in.  The turning on AppVeyor on their end is just clicking one button.

I think it would be good for a handful of folks from the DNN TAG to have more access in the _dnnsoftware_ organization on GitHub, but I also don't want to wait for that to get decided and acted upon before this can get moving.

**Comment by tpluscode** [comment]
It's enough for me to add ClientDependency to Appveyor and set it up for running pull requests which is pretty much the default behaviour. I will do it as soon as @ashishpd adds the admin team to the repo. Currently it doesn't show up on AppVeyor for me. When it's done you will be able to submit a PR with the `appveyor.yml` definition, @ahoefling.

Once it builds fine I will merge and set up environment deployment to NuGet/MyGet.

> I think it would be good for a handful of folks from the DNN TAG to have more access in the dnnsoftware organization on GitHub

I do agree, @bdukes. As per the above, this itself is not a blocker to proceed with the issue at hand though. Let's discuss adding more people on GH at the TAG meeting?

**Comment by ahoefling** [comment]
@tpluscode I just created a Pull Request for the dnnsoftware fork of ClientDependency and I linked all the commits/PRs back to this parent issue. There were some issues with the default build script in our dnn fork so I commented out stuff that we are not using in the Dnn Platform.

I don't know if we got a clear direction in our NuGet feeds so the build currently produces the .nukpg and it should be dropping those packages into the appveyor project feed at [https://ci.appveyor.com/nuget/clientdependency-dnn](https://ci.appveyor.com/nuget/clientdependency-dnn)

Once we get this changed merged into the dnnsoftware fork we can address how we want to deliver this to the platform project, we have lots of options.

**Comment by ahoefling** [comment]
This issue should **NOT** be closed until we have a pull request merged into Dnn platform that resolves the local development scenario. I just opened a new linked issue in the CD project regarding the MyGet server

dnnsoftware/ClientDependency#6

**Comment by ahoefling** [comment]
@tpluscode once we finish reviewing #2065 and merge that PR we can close this issue

**Comment by tpluscode** [comment]
Ofc. It was closed via your commit, mind you ;)

**Comment by chrisvesco** [comment]
Why is this closed? I can't build DNN Platform because Dnn.ClientDependency can't be found..

**Comment by mitchelsellers** [comment]
@chrisvesco This was closed due to the merged PR back in May of 2018.  Be sure to get the latest, as a local compile is successful.

**Comment by chrisvesco** [comment]
I downloaded the source from https://www.dnnsoftware.com/community/download just now, unzip it try to build, and I get the Dnn.ClientDependency is missing.

FYI I went to your site and wanted to check out the DotNetNuke performance presentation and the link is broken.

**Comment by mitchelsellers** [comment]
We don’t have easy control on those links. If you can download the source from the Releases tab here on GitHub that should work.  

Thanks on the other link ill address tomorrow

**Comment by chrisvesco** [comment]
Yep thanks Mitchell if I get the 9.3.2 release from GitHub it works fine. I'm also starting to understand how MVC fits into DNN by checking out the code

**Comment by chrisvesco** [comment]
Off topic: Say Mitchel where do I get your Module Professional Development book?

**Comment by mitchelsellers** [comment]
Looks like it is still available on Amazon. Sadly though it is a bit out of date at this point as MVC etc wasn’t around yet. 

Professional DotNetNuke Module Programming https://www.amazon.com/dp/0470171162/ref=cm_sw_r_cp_api_i_O1FhDbDE7D42R
