### ISSUE TITLE
DNN Error. Because the Xcillion folder doesn't have subfolders, all the files are under Xcillion folder.

### ISSUE THREAD

**Issue by abukres** [dnnsoftware/Dnn.Platform#2064]
After doing an installation from the 9.2 release, I get a 'DNN Error' message. After some debugging, I noticed that I am getting an exception :{"Could not find a part of the path 'C:\\inetpub\\wwwroot\\Dnn.Platform\\Website\\Portals\\_default\\Skins\\Xcillion\\Common\\AddFiles.ascx

I don't have a Common subfolder. I installed another instance using nvQuickSite and noticed it has several subfolder under Xcillion whereas the DNN installation from the source had all the files from these subfolders under the Xcillion and none of the subfolders are present.

So what's the deal? Does the source install in a certain way?

**Comment by tpluscode** [comment]
Hello @abukres. I understand that you tried building and installing directly from sources?

**Comment by abukres** [comment]
Yes.

**Comment by nvisionative** [comment]
That is a valid path/filename for the Xcillion theme.  That file loads all the CSS and JS using the CDF.

**Comment by nvisionative** [comment]
I have confirmed.  That is a valid path from the INSTALL package and therefore should be a part of the SOURCE package as well.

**Comment by tpluscode** [comment]
I'm confused now. Are we talking about sources zip package or sources cloned from GitHub?

**Comment by abukres** [comment]
The cloned one doesn't have the subfolders under Xcillion. The source from the zip file doesn't have the Xcillion folder at all.

**Comment by valadas** [comment]
In the spirit of trying to cleanup duplicated issues, I am closing this one in favor of #2120 which I think is pretty much complete and just needs documentation to build the project.
