### ISSUE TITLE
Post DNN 9.1.1 Upgrade- Persona Bar not available fro Android or iOS

### ISSUE THREAD

**Issue by iMercerTalentTeam** [dnnsoftware/Dnn.Platform#2066]
Post DNN 9.1.1 Upgrade- Persona Bar not available for Android or iOS

Is this something DNN 9 has made changes to or are we missing some setting?

**Comment by mitchelsellers** [comment]
At this time mobile editing is not supported with the PersonaBar.  I hope that in the future we can address this, but it is a known limitation currently.

**Comment by valadas** [comment]
Issue moved to [dnnsoftware/Dnn.AdminExperience #1034](https://github.com/dnnsoftware/Dnn.AdminExperience/issues/1034) via [**ZenHub**](https://www.zenhub.com/)
