### ISSUE TITLE
Copy permissions to child tabs not available anymore

### ISSUE THREAD

**Issue by ufoloko** [dnnsoftware/Dnn.Platform#2072]
From version 9.0, there is not option to copy permissions to child tabs anymore, please include back that option

**Comment by valadas** [comment]
It is there in 9.1.1 and 9.2.0 at least, on which 9 version are you?

**Comment by zyhfish** [comment]
this function available in 9.0.0 as well, when you edit the page settings which have child pages, switch to permissions panel, you will see a "Copy Permissions to Descendant Pages" button, click that will copy permission to child pages.

**Comment by OllyHodgson** [comment]
Can this issue be closed now?

**Comment by ufoloko** [comment]
Yes, it was my mistake

Thanks
