### ISSUE TITLE
Url.Action on PartialView generate wrong Url 

### ISSUE THREAD

**Issue by kttary** [dnnsoftware/Dnn.Platform#2073]
Url.Action on PartialView  generate a wrong url.  For example from fullview it generates: 

> http://myserver/mypage/moduleId/549/itemName/myitemname/controller/Item/action/Detail

 but from PartialView it generate 

> http://myserver/moduleId/549/itemName/myitemname/controller/Item/action/Detail

Somehow it miss page name from url. Thank U

**Comment by valadas** [comment]
Any MVC guy out there can confirm and maybe attach a small code sample to make it happen ? This issue has been here for like 3 years without any activity, I'd like to do something about it but I don't have anything MVC...

**Comment by valadas** [comment]
I am closing this issue due to lack of response. I'll be glad to reopen if we get something to make this actionable.
