### ISSUE TITLE
It is impossible to get the cloned 9.2 repo to be used to install and get a working DNN website up and running

### ISSUE THREAD

**Issue by abukres** [dnnsoftware/Dnn.Platform#2077]
I have ran into several issues and I am unable to get a working website to work. I keep getting DNN Error and it's one issue after. The current repo is missing several parts and is incomplete in its current form or if there are certain step to make a site work, then the instructions or documentation is severly lacking.

- The Xcillion folder structure is not complete. I opened an issue about this early.
- Database is not pointing to the new personbar. I had to execute: Update HostSettings SET HostSettings.ControlPanel = ‘DesktopModules/Admin/Dnn.PersonaBar/UserControls/PersonaBarContainer.ascx’ WHERE HostSettings.SettingName = ‘ControlPanel’; 
- Dnn.PersonaBar & Dnn.EditFolder are mising under the admin subfolder
- There are probably a host of other issues yet to be discovered.

This 9.2 repo is in a non working condition. There are no instructions on the home page of the repo on how to build the whole solution and get a working site going.

**Comment by tpluscode** [comment]
Hello @abukres. We are aware of this. Dnn.PersonaBar and Dnn.EditBar come from builds from separate repositories and there is no simple way to run a complete DNN Platform from the source code. We are working on fixing this

**Comment by valadas** [comment]
There should also be a presentation at DnnConnect this week, that I hope will provide some more information on this. I can't wait to see it. What puzzles me is that there are pull requests being submitted and merged and tested every day, so I guess some people know how to actually build the solution no?

**Comment by abukres** [comment]
I am guessing those people had an earlier version repo that worked and they just kept doing pulls from that point. However people who are starting fresh from this repo are just going to go through all kinds of issues. I spent a few hours on this and it was a waste of time. I going to wait until the people from dnnsoftware actually fix it. What they should have been doing is to test released repos by doing a fresh clone and make sure everything works *and* put some decent instructions on how to get this repo with dependency repos all working together. 

To have someone have a special representation in a conference on how to compile and get a DNN site just show up is telling of how problematic the issue is. It really shouldn't be.

**Comment by tpluscode** [comment]
> so I guess some people know how to actually build the solution no?

Building the solution is one thing. But actually running a complete application is something else entirely. It's been long (ie. predating the current team) the accepted practice to run a CI-built package and replace with locally compiled DLLs for debugging.

**Comment by zyhfish** [comment]
You can download the full source package from release page, it contains all the source code of platform, persona bar, edit bar:
https://github.com/dnnsoftware/Dnn.Platform/releases/tag/v9.2.0

**Comment by abukres** [comment]
@zyhfish Was it fixed after I posted this post and did you read tpluscode's response? If not, then it's still broken because it can't be used to get a working DNN site running.

**Comment by zyhfish** [comment]
HI @abukres , what i did is:
1. download DNN_Platform_9.2.0.366-777_Source.zip and exact to a folder;
2. open Dnn.Platform\DNN_Platform.sln and build in release mode(should restore nuget packages first);
3. after build complete. right click on the DotNetNuke.Website project and select "view in chrome" menu item, then complete the install wizard and everythinh works fine.

if you need more guide then i can try to do a screencast to show you what i did, thx.

**Comment by abukres** [comment]
The site is showing up now. Maybe I forgot to switch to Release mode first. Can the solution be already in Release mode instead of making some of us fall into this trap?

**Comment by valadas** [comment]
In the spirit of cleaning up duplicate issues, I am closing this one in favor of #2120
