### ISSUE TITLE
DNN 8.0.3.5 jQuery 1.9.1 Security Issue

### ISSUE THREAD

**Issue by IrishChieftain** [dnnsoftware/Dnn.Platform#2082]
Hopefully I'm posting this to the right place. Am new to DNN and am mainly a server-side coder.

We are currently failing a security audit due to the following:
https://github.com/jquery/jquery/issues/2432

Looking at the following folder structure of our install, it seems that jQuery v1.9.1 is installed out of the box:
\Resources\Libraries\jQuery\01_09_01

It would also seem that there is no set way to upgrade the version of jQuery. We must upgrade to v3.0.0 or better. I used [this guide](http://www.willstrohl.com/Blog/PostId/308/Upgrading-DotNetNuke-to-Use-the-Latest-jQuery-Ver) to get around the upgrade problem. Unfortunately this breaks the admin with jQuery versions v3.3.1 and v3.0.0 - browser scrolling stopped working as well as pop-ups. For example, cannot uninstall/install an extension.

Can someone suggest a solution?

**Comment by mitchelsellers** [comment]
Right now the best solution is to upgrade to 9.2.0 where the default version of jQuery was updated to version 3.1.  It isn't easily possible to upgrade to a higher version on a later version of DNN.

**Comment by IrishChieftain** [comment]
"Buy the new version" is not an acceptable solution to a problem that shouldn't have appeared in the first place. It would seem this is the mantra coming from DNN every time any problem crops up. Thanks for your feedback Mitchell.

**Comment by mitchelsellers** [comment]
Upgrading versions of jQuery in the prior versions of the platform is just not something that has been supported by the platform, due to the tight ties into the rest of the platform and solution.

In the future, I hope that as a community we can find a way to possibly change that.  But at the current point, with the processes that we have in place now, it is the only answer.  I agree that it would be better to upgrade, it just isn't technically possible, without impacting your environment.

You can for sure attempt an upgrade, it is just not a supported pathway.

But I do completely understand the need for interim support/upgrades to older versions.

**Comment by IrishChieftain** [comment]
Really, I'm just looking at the scenario where I am. There are many business modules deployed and many of these use different libraries, which in turn use different versions of jQuery. To me, it would seem like an obvious property subject to change and different requirements over time... not to mention the overriding security implications. This is one of two sites we have and is the free version. Our other site is the paid version (9.2), so if the same security issue arises there, would they seriously expect us to fork out money to upgrade? For something that should not have been baked in from the get-go? Seems pretty lame tbh.

**Comment by bdukes** [comment]
The integration with jQuery is implemented as a JavaScript Library in DNN, so you _can_ upgrade it (e.g. install the package from https://github.com/EngageSoftware/DNN-JavaScript-Libraries/releases/tag/jQuery_3.2.1_fix).  

However, if using the newer version of jQuery breaks other components, those other components will need to have fixes applied.  You can look at https://github.com/dnnsoftware/Dnn.Platform/pull/1658/files to see (some of) the changes that were made in the core as part of upgrading to jQuery 3 in DNN 9.2

**Comment by IrishChieftain** [comment]
Thanks for that info Brian. Please note that we are having this issue with version 8.0.3.5. I've contacted the DNN security team and am waiting to hear back from them.

**Comment by mitchelsellers** [comment]
Again, you can use the hosted option to change the included URL, but the same limitation applies regarding compatibility

**Comment by IrishChieftain** [comment]
Thanks for the heads-up on that Mitch. Could you tell me exactly which DB fields need to be set? 
I changed jQueryHosted field to "Y", jQueryUIUrl and jQueryUrl fields to CDN Urls but it didn't work. I ran "console.log(jQuery.fn.jquery);" in the browser console and I'm still getting jQuery showing version 1.9.1 (I cleared the cache)...

**Comment by mitchelsellers** [comment]
If you change this, you will need to restart the app.

**Comment by bdukes** [comment]
I don't think those host settings are used anymore, you would need to update the JavaScript Library for jQuery, through the Extensions module, if you want to update the CDN URL.  And then you need to turn on the _Use Javascript Libraries CDN_ setting in Host Settings.

**Comment by bdukes** [comment]
However, the simpler approach is just to install a JavaScript library for a newer version of jQuery (e.g. the 3.2.1 package I linked to above).

The issue, with any_ of these options for upgrading jQuery, is that some of the modules may break due to changes in jQuery between 1.9.1 and 3.x.

**Comment by IrishChieftain** [comment]
Thanks guys!
