### ISSUE TITLE
'Too many redirects' Error

### ISSUE THREAD

**Issue by tomepoh** [dnnsoftware/Dnn.Platform#2086]
After upgrading 9.1.1 to this version the site shows a blank page with 'Too many redirects' error. Any suggestions?

**Comment by OllyHodgson** [comment]
This isn't really a support form. You're likely better off asking in [Community Forum](http://www.dnnsoftware.com/forums) or [Answers](http://www.dnnsoftware.com/answers) on the DNN site.

With that said, have a look at DNN's error logs. On the webserver, find the DNN folder (e.g. `c:\websites\dnndev.me` and look under `Portals\_default\Logs`. The most recent file ought to point you in roughly the right direction.

**Comment by sleupold** [comment]
questions should be posed on www.dnnsoftware.com and this issue should be closed

**Comment by ohine** [comment]
9.2 includes some breaking changes, you might have a module which isn't compatible yet with 9.2. I'm going to close this as an invalid issue. If you find more information, feel free to either start a discussion on dnnsoftware.com or start a new issue with more information to help troubleshoot this.
