### ISSUE TITLE
Handling underscores and spaces in property names

### ISSUE THREAD

**Issue by tpluscode** [dnnsoftware/Dnn.Platform#2096]
## Description

We've identified some issues with regard to how profile properties are handled:

1. Property name cannot contain spaces because they are [replaced with underscores][adapter] and the profile page tries to find a property which doesn't exist
1. There cannot be two properties which differ only in spaces vs underscores (`"Hire date" ~ "Hire_date"`) because they will generate the same web control identifiers on profile page\

[adapter]: https://github.com/dnnsoftware/Dnn.Platform/blob/development/DNN%20Platform/Library/UI/WebControls/PropertyEditor/Adapters/CollectionEditorInfoAdapter.cs#L276

## Steps to reproduce

- Log in
- Go to Persona Bar > Settings > Site Settings > Site Behavior > User Profiles > + Add Field
- Set Field Name* to : **HireDate**
- Set Data Type* to : **Date**
- Set Property Category* to : **Date**
- Set Read-Only to **true/enabled**
- Set Visible to **true/enabled**
- Set Default Visibility to : **All Users**
- Press Next
- If you have Content Localization enabled, for each Language you must set the name of the field again. I only have English so for Localized Content, I set the field name to : **HireDate**
- Next, repeat the steps above but instead of HireDate, add a new field called **Hire Date** and save.
- You should now have two new User Profile Fields: **HireDate** and **Hire Date**
- Next, go to Persona Bar > Manage > Users > Add User > create a user with the default settings
- On the Users list click the Ellipsis menu (... Menu) to the right of the user you created
- Click Login as User
- From the top-right corner of the screen, click on your user name > **Edit Profile**
- Expand the new user profile field category you created (in my case **Date** category)
- You will see that HireDate is read-only as and works as intended
- You will see that Hire Date is not read-only although we set it as such and can be edited

## Proposed solution

Short of changing how those names are handled within C# code and passed around we came up with another solution to limit how the profile can be used:

### Treat properties as equal but stripping underscores and replacing with spaces

| name given | name saved |
| ------------- | ------------- |
| "Hire date" | "Hire date" |
| "Hire_date" | "Hire date" |
| "   Hire date  " | "Hire date" |
| "&#95;Hire date&#95;" | "Hire date" |

This means that if there already is a property called `Hire date` then attempting to add `_Hire_date_` would replace it and not create a new one, as it now happens when names are 100% equal. 

**NOTE** I find this behaviour kind of surprising and it should warn the user about what is happening but it's a separate discussion.

**Comment by tpluscode** [comment]
@dnnsoftware/tag please see here and the linked PR

**Comment by sleupold** [comment]
no, the property NAME should not allow special characters or spaces and should not start with a digit.
This does not apply to the caption, which may be provided per language.

**Comment by ricardodiasc** [comment]
@sleupold, you are right. I was confusing the property name with its caption. From what I saw from the code, it was trying to replace spaces with underscores so the user can type as a normal and it would show property name as property caption. But I think it is an improvement that has to be thought carefully.

**Comment by valadas** [comment]
As far as I can read, it looks like this is resolved by the two linked PRs so I am closing this issue.
