### ISSUE TITLE
Pages > Page that has never been published should return a 401 (not a 404)

### ISSUE THREAD

**Issue by tpluscode** [dnnsoftware/Dnn.Platform#2101]
## Description 

Pages > Page that has never been published (that have only one version pending to be published) should return a 401 (not a 404) for non-editor users.

Note: even if the registered user has view permission on the created page, as the page has not been published yet the view permission does not apply until the page is published.

## Steps to reproduce

- Log in as CM
- Go to Persona Bar Pages
- Create a Page marking the permission to be visible to registred user
- Add a module
- Do not publish the page
- Log in as Registered User
- Surf the URL of the created page

## Current result

- 404 is returned

## Expected result

- To be consisten with how platform works and Engage module + Publisher we should return a Access Denied error (401 http status)

## Affected version

* [x] 8.0.0, 
* [x] 8.1.0
* [x] 8.2.0

**Comment by bdukes** [comment]
I don't have real strong opinions on this one, so if it fixes a specific problem in Engage/Publisher, I'm not going to argue.  

However, conceptually, it seems that an end user without permissions shouldn't get a different response between querying a page that doesn't exist and a page that hasn't been published.  There's an information leakage there.

But, again, I'm okay with this theoretical/conceptual issue if there's a practical issue being solved. (Any differing thoughts from the rest of @dnnsoftware/tag?)

**Comment by mitchelsellers** [comment]
I'm with @bdukes on this. Personally, traditionally  I would expect a page that doesn't exist (IE non published) should be returning a 404, as that is the traditional sense of the issue.

If there is a specific reason that a "pending publish" page should show a 401 otherwise, I'm ok with it.

**Comment by mitchelsellers** [comment]
Upon further review, this issue was actually fixed back in March, closing this issue for now.  If we don't like this behavior, we will have to remove/reconfigure.

**Comment by tpluscode** [comment]
That's right @mitchelsellers. I've been back-filling issues which have been completed since 9.2 release so that we're clear on the scope for 9.2.1
