### ISSUE TITLE
Cannot create new user with email address as username

### ISSUE THREAD

**Issue by tpluscode** [dnnsoftware/Dnn.Platform#2115]
## Description

Going to Persona Bar > Security > Member Accounts tab > Registration Settings, and marking Use Email Address as Username, will generate an error upon login, displaying message "A critical error has occurred. Please check the Event Viewer for further details."

## Steps to reproduce

1. Set up a clean DNN 9.2 install. 
2. Go to Persona Bar > Manage > Users. 
3. Click the "Add User" button. 
4. Fill details for new user, setting an email address as the username. 
5. Click "Save" button. 
6. An error message is displayed saying: "The username specified is invalid. Please specify a valid username." 

## Current result

After upgrading to DNN 9.2, customer is no longer able to add user with their email addresses as username. The following Error Message is displayed: "The username specified is invalid. Please specify a valid username."

## Expected result

Being able to add email address as a valid user name in the default user creation form.

## Affected version

* [x] 9.2

**Comment by tpluscode** [comment]
This has been fixed in PR #2070 and has been caused by #1972

**Comment by tpluscode** [comment]
There is also a companion PR dnnsoftware/Dnn.AdminExperience.Extensions#537 which applies the same fix in Persona Bar and removes some code duplication

**Comment by nickcrisp** [comment]
Still occurs in 9.3.2

**Comment by valadas** [comment]
@nickcrisp I cannot reproduce in 9.3.2 using the above steps to reproduce...

**Comment by Tychodewaard** [comment]
I can not reproduce either. @valadas Close?

**Comment by valadas** [comment]
Actually, this one IS closed :) @nickcrisp can you please open a new issue with new steps to reproduce if you can still make it happen on 9.3.2 Thanks.
