### ISSUE TITLE
New feature: Package dependency on database version

### ISSUE THREAD

**Issue by bdukes** [dnnsoftware/Dnn.Platform#2116]
A package should be able to indicate that it requires a particular version of SQL Server.  Currently, packages can specify dependencies in their manifest. This suggestion is to add a new type of dependency.

The most straightforward would be to add `<dependency type="SqlServer">2016</dependency>`.  Because DNN's data provider is abstract with multiple possible implementations, it may make sense to be less SQL Server specific.  Perhaps a better approach would look more like `<dependency type="database" version="2016">SqlDataProvider</dependency>`.

Open questions:
 * What should the name of the dependency be?
 * How should the version be specified (e.g. 2017 or 14.0.1000.169)?
 * Does this need to be an additional feature that any data provider could implement (e.g. would an `OracleDataProvider` be able to provide an implementation which determined the database version)?
 * Do we want to handle this in a specific way during the installation and upgrade wizards (e.g. allow skipping packages whose dependencies aren't met, show warnings, etc.)?

**Comment by sleupold** [comment]
we should not request a specific version of SQL server, but a compatibility level for the database, which determines the language features available, see http://www.sqlmvp.org/sql-server-database-compatibility-level-performance/
Note: the compatibility level may be modified by SQL, Turbo Scripts always sets it to max value supported by the server, but this requires DBOwner permission.
