### ISSUE TITLE
Add multiple issue templates

### ISSUE THREAD

**Issue by bdukes** [dnnsoftware/Dnn.Platform#2117]
GitHub supports multiple issues templates for a repository (see https://blog.github.com/2018-05-02-issue-template-improvements/).  Currently, the issue template is geared towards reporting bugs.  

I suggest that we add a separate issue template for suggesting features.  It could have areas to document:
  * if related work is required in the Persona Bar or other related projects
  * what considerations have been made with regards to performance, multi-lingual support, backwards compatibility, etc.
  * expected testing strategy
  * anything required to be documented for the ESW QA team

Or it could just be a description field, if we want to avoid overwhelming folks who want to suggest improvements to the platform

**Comment by bdukes** [comment]
I don't think that's possible.  Someone with permissions in the repo needs to label the issue, they don't want folks being able to label their own issues.  Perhaps it would be possible to have some automation which labelled issues based on something from the template, but it's probably intended to be done by a human.

What labels would you expect?  Just _bug_ or _enhancement_?

**Comment by EPTamminga** [comment]
I would expect auto labels like, bug, enhacement, feature request, but I understand this is a manual process atm.

**Comment by ohine** [comment]
I will work on getting those labels added as part of my daily issue triage session. I setup a project board too on the project to help out a bit but the automation tools are a bit weak there too.

**Comment by sleupold** [comment]
AFAIK the templates have been added and this issue may be closed

**Comment by sleupold** [comment]
@nvisionative 
I noticed duplicate "## Additional context" in feature request template for DNN Platform, do I need to open a new issue for it?

**Comment by nvisionative** [comment]
Good catch @sleupold - that would be great.  I think the first instance of the **Additional context** section should be removed.

**Comment by sleupold** [comment]
@nvisionative done (#2389)

**Comment by valadas** [comment]
I am closing this issue since we now have multiple issue templates
