### ISSUE TITLE
Missing DotNetNuke.Web.Client 9.2.0.366 on NuGet 

### ISSUE THREAD

**Issue by doraair** [dnnsoftware/Dnn.Platform#2123]
I tried to upgrade my module to 9.2.0 today but cannot find DotNetNuke.Web.Client v 9.2.0.366 on the Nuget.  
![image](https://user-images.githubusercontent.com/17276007/41596093-5bfb57a0-73f3-11e8-9e6f-dba88c1e2e4a.png)

**Comment by ohine** [comment]
Duplicate Issue #2080
