### ISSUE TITLE
CreateUser method uses oAuth specified state parameter

### ISSUE THREAD

**Issue by PascalIcatt** [dnnsoftware/Dnn.Platform#2124]
(this bug was previously submitted in JIRA:
https://dnntracker.atlassian.net/browse/DNN-7444 )

## Description 
In version 7.2.1 issue   DNN-4133 CLOSED  is fixed in an inappropiate manner.

If the AspNetMembershipProvider CreateUser method happens to find a parameter named 'state' in the Request.Params object, it bluntly takes over the user.UserName passed to the CreateUser method and replaces it  with whatever it finds in the 'state' parameter, prefixed to the user.Email.

The code is intended to fix a specific (LiveID) OAuth issue, but does not check whether it is excecuted within OAuth context.
Even within OAuth context, it is not correct to make any assumptions about the contents of the 'state' parameter and its suitability for use in the UserName,

A quote from The state parameter according to the Google Oauth 2.0 docs:
_[state] Indicates any state which may be useful to your application upon receipt of the response. The Google Authorization Server roundtrips this parameter, so your application receives the same value it sent. Possible uses include redirecting the user to the correct resource in your site, nonces, and cross-site-request-forgery mitigations._

Please remove this fix. Consider fixing the specific OAuth issue outside of the generic AspNetMembershipProvider.CreateUser method - if your OAuth implementation needs a different UserName, i.m.h.o. it should pass in a different UserName to the CreateUser call.

## Affected version
* [x] 9.2
* [x] 9.1.1
* [x] 9.1
* [x] 9.0

## Affected browser
* [x] Chrome
* [x] Firefox
* [x] Safari
* [x] Internet Explorer
* [x] Edge

**Comment by valadas** [comment]
@dnnsoftware/tag any opinions on this ?

**Comment by valadas** [comment]
@PascalIcatt since there was no reply to this issue, I am closing it. I honestly don't know enough about this subject to have a opinion on it. If this is still an issue on current versions, please open a more detailed issue with a code sample or steps to reproduce, etc. @dnnsoftware/tag if you guys have an opinion on this and want to continue this issue and assign it to a milestone, please reopen.
