### ISSUE TITLE
Bring back a way to set small and large icons for a page

### ISSUE THREAD

**Issue by valadas** [dnnsoftware/Dnn.Platform#2128]
## Description 
When the persona bar was implemented, the ability to set a small and large icon to a page was removed, it would be nice to bring this back.

## Steps to reproduce
Try to assign a small and a big page icon (image to any page)

## Current result
There is no interface to upload and set those files

## Expected result
There should be a way to do it in the UI, probably a drag-and-drop image uploader with preview. Can probably reuse the component used in for the site logo and the site favicon.
* Both the small and large icons should be implemented, not just one of the two
* There should also be a preview of the selected image.
* Testing should be done for a use case of an older Dnn relese (lets say 8.0.4) that had icons set, to make sure nothing breaks for upgraded sites.
* A default folder for the page icons should be set for the drag-and-drop scenario so users dont need to select the upload location, but that folder should be chosen in a way that would not override existing images by error, so probably not save them in the portal root, but maybe in Portals/portalid_system/page-icons, what are your thoughts on this?
* Users also need to be able to select an existing file in any portal folder, just like for the site logo.

## Affected version

* [x] 9.2
* [x] 9.1.1
* [x] 9.1
* [x] 9.0

## Affected browser

* [x] Chrome
* [x] Firefox
* [x] Safari
* [x] Internet Explorer
* [x] Edge

This being a feature that was actually removed, ie: not a new feature, I think it should be implemented quickly to allow the users that are currently using page icons to be able to upgrade. In other words, I don't consider this a new feature or enhancement, but a bug fix. (Any chances of this happening in 9.2.1 or am my over-optimistic here ?).

**Comment by rudgr** [comment]
+1; for me!

**Comment by OllyHodgson** [comment]
> Portals/portalid_system/page-icons

This seems like a good default.

**Comment by sleupold** [comment]
Does this include the icons for TabModules, which are lacking a UI in DNN 9 as well - or should this be logged as separate issue?

**Comment by TopCat6** [comment]
Yes, please!

**Comment by valadas** [comment]
This is done, closing
