### ISSUE TITLE
Bring back a basic Google Analytics UI

### ISSUE THREAD

**Issue by valadas** [dnnsoftware/Dnn.Platform#2129]
## Description 
Previously, Dnn had a module to configure google analytics tracking code. I _think_ all the necessary code is still in place and that it is just a matter of writing the code in a config file to have it working. I _think_ this would just be missing the UI to actually set the google analytics tracking account id.

## Steps to reproduce
Try to enter the google analytics tracking account id.

## Current result
There is no UI to do it

## Expected result
Users should be able to enter their tracking id and have basic google analytics working on their site.
Currently, they need to resort to injecting javascript or using a third party module.

## Affected version

* [x] 9.2
* [x] 9.1.1
* [x] 9.1
* [x] 9.0

## Affected browser

* [x] Chrome
* [x] Firefox
* [x] Safari
* [x] Internet Explorer
* [x] Edge

This I think should be implemented with just the basic account id, nothing more than what was provided in older versions because commercial editions have more advanced google analytics management.

**Comment by bdukes** [comment]
This should be implemented using the new Connector framework.  @ashishpd, I thought that originally the Evoq GA connector was planning to come down to platform, is the current plan for it to stay in Evoq?

**Comment by bdukes** [comment]
From discussion in @dnnsoftware/tag today, the Evoq connector has additional functionality that requires Azure, so it will not be coming to Platform.

**Comment by valadas** [comment]
Any idea if bringing back a basic Analytics feature into the platform (what is already built-in but has no UI) would interfere with the Evoq implementation of Analytics? Should this be made into a module instead and be installed only by those who want that basic feature? What are thoughts on this...

**Comment by bdukes** [comment]
My opinion is that Evoq is free to replace any component in the Platform during their installation.  We shouldn't need to worry about whether there's an Evoq connector or not.

**Comment by nvisionative** [comment]
I agree that a basic Google Analytics UI would be great and should really have never been removed.  While we are at it, shouldn't we consider supporting Universal Analytics and Google Tag Manager as well - at least at an minimal viable product level?  If it is better to take one step at a time, that's fine, but I thought I would at least put it on the table for consideration anyway.

**Comment by hismightiness** [comment]
Are there any examples of how to build a Connector?

**Comment by mikesmeltzer** [comment]
I will be submitting a pull request for review on this later today or tomorrow. 

The proposed solution I've implemented consists of a new Connector extension added to the platform. The extension displays in the Persona Bar > Settings > Connector screen and exposes the same fields that were available in DNN 8.04 (using the current underlying analytics providers, etc. with no changes).  Validation has been added to the tracking code field to ensure it matches Google's tracking code format. All sites that used the previous core Google Analytics solution from DNN 7 / DNN 8 will continue to work with this approach in DNN 9.3 (proposed release version).

This solution should suffice to bring the functionality back for current and new users while we move the discussion forward on analytics, connectors and similar functionality at a core level longer term.

Will:  I've started a video, blog post and a sample module for how to create a connector that I'll post soon. It gives an overview of my findings on the connectors API, what it can and can't currently do, and walking through a sample module I'll be posting on GitHub.

**Comment by mikesmeltzer** [comment]
Brian,

I feel the lack of validation is an issue too :) I'm ok with removing it though if we want to match the previous functionality.

The engine is very flexible and you could use this for other non-ga scripts if someone edited the core scripts. But given that we call the current provider the Google Analytics provider and there was a module for Google Analytics (which this ultimately replaces), do we want to be flexible for this? I'm under the impression that if we are advertising it as a Google Analytics provider then we shouldn't necessarily try to account for someone modifying the core files.

If we are looking for a more generic solution longer-term, I suggest we revist the entire GA provider and come up with something a bit more generic and configurable from the UI.

Thoughts?

**Comment by bdukes** [comment]
My thought is that the current goal should be to match the existing functionality, so that no one is stuck, unable to use the feature how the previously did.  Once we have UA and GTM connectors and/or a generic tracking script connector, I think adding validation is fine (though I'm still a _little_ wary that it'll change in the future and then folks can't setup their GA accounts, but that probably also comes with a script change).

**Comment by mikesmeltzer** [comment]
I'll go ahead and remove the validation.

I agree. Whether it is the GA script, the GA tracking code or any other dependency - if we include it in the Platform then we are responsible for keeping it updated.
