### ISSUE TITLE
Email as Username - Error creating new user & Error login in.

### ISSUE THREAD

**Issue by arminrahimian** [dnnsoftware/Dnn.Platform#2130]
## Description 

Test done on new fresh install of DNN9.2.0.366-777

1 - Set "Use Email Address as Username" in Security > Member Accounts > Registration Settings.
2 - Creating a new user using an email address for the username field & Email address gives the following error.
"The username specified is invalid. Please specify a valid username."
3 - Unable to log back into site with either Super User username or Super User email address.

## Affected version

Reported in Build: 9.2.0.366-777

* [x] 9.2
* [ ] 9.1.1
* [ ] 9.1
* [ ] 9.0

## Affected browser

* [ ] Chrome
* [ ] Firefox
* [ ] Safari
* [ ] Internet Explorer
* [ ] Edge

**Comment by tpluscode** [comment]
Hello @arminrahimian. Thank you reporting those problems.

The registration part has been identified and is being tracked as #2115 

Don't know about the log in problem. It could be unrelated

**Comment by Tychodewaard** [comment]
Tested and was not able to replicate. All works as expected. @valadas close?

**Comment by valadas** [comment]
Yes, since this was reported for 9.2.0 and there was a related fix in 9.2.1, let's close this @arminrahimian if you can still reproduce after upgrading, please open a new issue. Thanks.
