### ISSUE TITLE
JWT ExtendToken: passing RenewToken (rtoken) has no use

### ISSUE THREAD

**Issue by erw13n** [dnnsoftware/Dnn.Platform#2133]
## Description 
I check the source code of JWT ExtendToken, and it seem sent any renewalToken will just pass-in and return with exact same value.
## Steps to reproduce
Call API of JWT ExtendToken, and pass any data on rtoken
## Current result
It return accessToken and the exact same word we type on RenewalToken

![image](https://user-images.githubusercontent.com/792847/41873926-a1322e50-78f0-11e8-9f21-d3e72c824c4c.png)

**Comment by Behnam-Emamian** [comment]
I am fixing it.

**Comment by Behnam-Emamian** [comment]
waiting for more approvals for merging to master

**Comment by contact2adil** [comment]
is it fixed yet? I am facing the same issue but no solution yet.

**Comment by valadas** [comment]
It looks like it was merged in the 9.3.0 milestone, you can give it a try (only on a non production environment) using the release candidate available at https://github.com/dnnsoftware/Dnn.Platform/releases 

But keep in mind:
- This release is not production ready yet
- There are known issues with RC0 (mainly UI issues with some persona bar components)
- If you see RC1 is out (should be very shortly, try that instead).

**Comment by valadas** [comment]
I am assuming this is now fixed and closing, if not, please open a new issue.
