### ISSUE TITLE
JQMigrate warnings in the devtools console

### ISSUE THREAD

**Issue by OllyHodgson** [dnnsoftware/Dnn.Platform#2136]
## Description 

There are several JQMigrate warnings visible in the browser developer tools console on a fresh installation of DNN 9.2.0.

## Steps to reproduce

Open the Chrome developer tools and browse to a fresh, blank installation of DNN 9.2.0.

## Current result

A variety of JQMigrate warnings are output to the console, including:

`JQMIGRATE: jQuery.expr[":"] is now jQuery.expr.pseudos` and `JQMIGRATE: jQuery.expr.filters is now jQuery.expr.pseudos` - in /Resources/libraries/jQuery-UI/01_12_01/jquery-ui.js

`JQMIGRATE: jQuery.fn.bind() is deprecated` - in /Resources/libraries/Knockout/03_03_00/knockout.js

`JQMIGRATE: jQuery.fn.delegate() is deprecated` - in /Portals/_default/Skins/Xcillion/js/jquery.smartmenus.js

## Expected result

No JQMigrate warnings appear in the devtools console.

## Affected version

Platform 9.2.0 and Evoq 9.2.0

## Affected browser

Tested in latest Chrome and Firefox on Windows Server 2012 R2.

**Comment by mitchelsellers** [comment]
Closing this as other issues are working to track upgrading of javascript dependencies
