### ISSUE TITLE
SSL Offloading Issue with Modals after Save

### ISSUE THREAD

**Issue by box86rowh** [dnnsoftware/Dnn.Platform#2141]
## Description 
Mixed content errors after update settings on modal windows

## Steps to reproduce
Setup dnn with ssl offloading and set all pages to secure and ssl enforced site wide.

Go into module settings for any module, hit Update

## Current result
Update is done, but frame never reloads as it tries to load it over http

## Expected result
Frame should reload after save

## Affected version

* [x] 9.2
* [x] 9.1.1
* [ ] 9.1
* [ ] 9.0

## Affected browser

* [x] Chrome
* [x] Firefox
* [x] Safari
* [x] Internet Explorer
* [x] Edge

**Comment by box86rowh** [comment]
Bump!

**Comment by valadas** [comment]
@dnnsoftware/tag Anyone has a testbed to try this out, I have no clue how to setup ssl offloading...

**Comment by valadas** [comment]
It appears there has been a change in 9.3.2 that should resolve this, I am closing this issue for that reason.
