### ISSUE TITLE
Language Resource Files unescaping "&amp;"

### ISSUE THREAD

**Issue by tpluscode** [dnnsoftware/Dnn.Platform#2145]
## Description 

The issue is due to the ampersands being unescaped which results in an invalid entity for the XML. For example in DNN 9.1.1 if one wants to use `&nbsp;` in a resource file, one would need to go `&amp;nbsp;` which stores without errors; however, in 9.2 Due to the change to use HTML Entities (one of the latest PR for this feature), it ends up unescaping the ampersand which results in `&nbsp;` and either the files doesn't save or it breaks.

## Steps to reproduce

1. Go to `Settings > Site Settings > Languages`, and the resource files for one of the languages (en-US) 
2. From the file drop-down select the GlobalResources file, see screenshot. 
3. Make a small value change and attempt to save the file. 

## Current result

The file will not save and you will receive a 500

## Expected result

The file should save the changes without issues.

## Affected version

* [x] 9.2
* [ ] 9.1.1
* [ ] 9.1
* [ ] 9.0

**Comment by tpluscode** [comment]
This precisely caused by Dnn.AdminExperience.Extensions#139. This function is the reason this happens.

```c#
private bool IsHtmlEncoded(string text)
{
    return HttpUtility.HtmlDecode(text) != text;
}
```

This is not precise in case of partially-encoded strings such as `<span> </span>`. Decoding will turn   into actual space and thus the resulting value would be different from the original. Which does not mean that the original was fully encoded. Hence the XML doesn't accept it.

**Comment by sleupold** [comment]
This is an important issue for all translators, but also for all users, who want to modify any email text or terms of use. this should be fixed asap.

**Comment by sleupold** [comment]
We should never test, whether text is html encoded or not, but need to rely on encoding levels, e.g. if we know, the text is encoding before being saved, htmldecode should be applied. If htmlencode is applied twice, the text needs to be decoded twice as well.

**Comment by sleupold** [comment]
btw. this affect DNN 9.1.0 and 9.1.1 as well.

**Comment by tpluscode** [comment]
I think the problematic code was committed after 9.1.1. It "fixed" another, similar problem which indeed existed prior. Do see https://dnntracker.atlassian.net/browse/DNN-9535

**Comment by tpluscode** [comment]
I think the actual issue here is using `InnerXml`. I think that instead we should use `InnerText` or a `CDATA` node to have the XML library ensure values get properly escaped.

See this SO question for reference: https://stackoverflow.com/questions/4679543/how-to-write-cdata-in-xml

**Comment by sleupold** [comment]
you mean DNN-9535 was fixed and broken again immediately after?

**Comment by sleupold** [comment]
We never used CData before (nor does the resource editor in VS), and the issue occurred when the editor was moved to the PB extension.

**Comment by valadas** [comment]
I can help testing this as soon as fixed and in a nightly build, my language packs all have strange stuff in them since Dnn 9. So I will probably go thought pretty much all keys rebuilding that.

**Comment by sleupold** [comment]
@valadas please note that this will not fix broken resource files, but make sure, they won't get broken when saved in the editor. You may use a working resource file from DNN 8 and save in resource editor. When you open it again, it should not display any weird (html encoded) content.

**Comment by valadas** [comment]
@sleupold Yeah, that was kind of my plan :)

**Comment by Mohtshum** [comment]
This code has lots of dependency, not easily refactor-able for unittest

**Comment by tpluscode** [comment]
> you mean DNN-9535 was fixed and broken again immediately after?

Kind of, yes.

Please see the PR. `InnerText` works great as I watched live on @Mohtshum's machine.

**Comment by tpluscode** [comment]
@dnnsoftware/tag with this merged into 1.6.1 of Dnn.AdminExperience.Extensions, we would get this fixed in 9.2.2. Do we want to put this in 9.2.1 or can this fix wait for next release?

**Comment by sleupold** [comment]
@tpluscode as this is a really annoying issue and functional defect, breaking site functions as registration and password retrieval, I would really love to get this included in DNN 9.2.1 - and I am sure, a number of users as well.

**Comment by valadas** [comment]
I would also really love to see this in 9.2.1 if possible, proper localization is really important for everyone who has to maintain sites that is not only English.

**Comment by bdukes** [comment]
Let's merge it into 1.6.0 (for DNN 9.2.1)

**Comment by tpluscode** [comment]
Please see dnnsoftware/Dnn.AdminExperience.Extensions#588 @dnnsoftware/tag

**Comment by tpluscode** [comment]
Done @bdukes
