### ISSUE TITLE
Broswer form fill suggestions hide the country and region suggestions

### ISSUE THREAD

**Issue by valadas** [dnnsoftware/Dnn.Platform#2146]
## Description 
When trying to enter a country and region, the browser may offer suggestions from previous addresses, this hides the Dnn suggested countries and regions and without dismissing the browser behaviour and not noticing the issue, it is not possible to save the value.

## Steps to reproduce
- Use some saved auto-fill addresses in Chrome
- Create a Dnn user
- Try to edit the user profile region and country
- Notice the suggestions are hidden by the browser suggestions menu

## Current result
Dnn suggestions are hidden by browser suggestions

## Expected result
Setting the fields attribute autocomplete="off" would probably bypass this behaviour and show only the Dnn suggestions.

## Affected version

* [x] 9.2
* [x] 9.1.1
* [?] 9.1
* [?] 9.0

## Affected browser

* [x] Chrome
* [?] Firefox
* [?] Safari
* [?] Internet Explorer
* [?] Edge

**Comment by valadas** [comment]
Also, since the country selection populates the region selector, I think the country should appear before the region.

Also, if you type the beginning of a country name and then try to go through the dropdown using the keyboard (arrow down), instead of going through the options of the dropdown, the field just show numbers (I guess the various country Ids).

**Comment by sleupold** [comment]
+1
