### ISSUE TITLE
Power forms Extension dosen't work

### ISSUE THREAD

**Issue by inkanelly** [dnnsoftware/Dnn.Platform#2147]
## Description 
When i try to install a new extension in Dnn 9.2, powerforms 08.02.01 i get error text:
Failure Installation Failed - ResourceFile

What can i do?
![screen shot 2018-07-06 at 11 07 42](https://user-images.githubusercontent.com/40886280/42370357-d79f17d6-810c-11e8-9629-0db1b7fe0823.png)

## Steps to reproduce
Tried to download PF 07.09.02 same resulte

## Current result
None

## Expected result
That i get Powerforms to work

## Affected version
Dosent work

* [x] 9.2
* [ ] 9.1.1
* [ ] 9.1
* [ ] 9.0

## Affected browser

* [x ] Chrome
* [x ] Firefox
* [x ] Safari
* [ x] Internet Explorer
* [x ] Edge

**Comment by bdukes** [comment]
Are you able to install other extensions?  My initial thought would be that there's an issue with the file permissions, and DNN can't write the new files.

**Comment by Inka2015** [comment]
A get the same error eny solution?

**Comment by bdukes** [comment]
If you are getting the same error when you try to install anything, you need to make sure that your website's file permissions are set correctly.  You may want to read http://www.dnnsoftware.com/community-blog/cid/135031/permissions-permissions-permissions for some details on how to find and set the permissions correctly.

**Comment by moorecreative** [comment]
Hi inkanelly, why don't  you connect with the community such as DNNConnect on Facebook, SouthernFried DNN or Toronto Area DNN User Group... we'll be glad to help troubleshoot your DNN instance, help with training and to get you going!

**Comment by valadas** [comment]
I think this can be closes @mitchelsellers or @ohine or @donker
