### ISSUE TITLE
Enforcing HTTPS for /login when no tab/page is set as default login page (default login ctl)

### ISSUE THREAD

**Issue by moorecreative** [dnnsoftware/Dnn.Platform#2148]
## Description 
If no Login page is specified in the Page Defaults of Site Settings, DNN uses the core (ctl login state(?)),  to show the account login. By this method, it will allow that login state to display as http even if the rest of the site and pages are set as https. It seems that, in this scenario, the login page falls through the cracks and is not enforced as https.

To clarify, if you have a tab/page with a login module on the page where that tab is set to IsSecure, and within Site Settings that tab is specified as the Login page for the site, then DNN will properly load the http://www.domainname.com/login URL enforced over to https://www.domainname.com/login on page load.

However, if you do not have an actual page set in the SiteSettings, it must be that there is nothing to clarify the IsSecure status and it therefore shows the login state as http.

I feel that if the Site Settings have SSL Enabled and Enforced, then this default view of login should be loaded as https.

## Steps to reproduce
- In a Portal in which Site Settings have SSL Enabled & SSL Enforced
- Within Site Settings > Site Behavior > Default Pages: clear or set the Login Page settings to <None Specified>
- Clear cache for good measure
- load http://www.domainname.com/login

## Current result
http://www.domainname.com/login will load as http even if the Site Settings SSL Settings are set to Enabled & Enforced

## Expected result
If there is no specific Login page specified AND Site SSL Settings are set to Enabled & Enforced, the ctl=login state should load as https

## Affected version
I have confirmed it affecting 9.1.1, it may affect previous, can test further and confirm...

* [x] 9.2
* [x] 9.1.1
* [ ] 9.1
* [ ] 9.0

## Affected browser
All (browser inspecific)

* [X] Chrome
* [X] Firefox
* [X] Safari
* [X] Internet Explorer
* [X] Edge

**Comment by hismightiness** [comment]
For anyone reading this, a viable workaround can be to create a custom login page.  Instructions on how to do this can be extracted from the wiki article below.

http://www.dnnsoftware.com/wiki/how-to-ensure-ssl-for-all-authenticated-sessions

**Comment by moorecreative** [comment]
Right-o Will! The solution for users setting up their DNN Portals is to make sure that they set each one up with an actual Login page. This is something that we got in the habit of back in the day to help with all the duplicate pages that would get crawled and indexed relating to the
- login control
- legal text/page control
- privacy text/page control
and so we'd setup a page for each manually when setting up every new portal. That, of course, helps in this situation too.

However, for sites where other editors and admin are in charge of adding portals and content, they have an assumption that if they've set and enforced SSL within portal settings, that now the portal will behave by enforcing https in all situations, especially one like the Login screen/control.

My recommendation is that the core needs to be updated so that it can be aware of the setting and serve up the login control according to the portal ssl settings.

**Comment by moorecreative** [comment]
Peter Donker has suggested a change to the way that the HTTPS settings in DNN might control the whole of page settings... this might help with this issue

https://github.com/dnnsoftware/Dnn.Platform/issues/2808

**Comment by valadas** [comment]
In the spirit of cleaning up the backlog and since #2808 looks like the solution to this, I am closing this issue so we have only one to manage for the same problem.
