### ISSUE TITLE
Search for Umlauts, accents and other special characters

### ISSUE THREAD

**Issue by MaiklT** [dnnsoftware/Dnn.Platform#2154]
## Description

Search does not work for words that contain special characters like ä, ö, ß etc.

## Steps to reproduce

In an HTML module, put a phrase like "Die Stadt, in der ich wohne, betreut viele Kindergärten". Make sure, that the index is up-to date, and then search for "Kinderg" - you will see a result link, but as soon as you add "ä" to it, the result ist gone.

## Current result

No search result, when the search word contains special characters.

## Expected result

Search result should be available.

## Affected version

* [x] 9.2
* [x] 9.1.1
* [x] 9.1
* [x] 9.0

## Affected browser

* [X] Chrome
* [X] Firefox
* [X] Safari
* [X] Internet Explorer
* [X] Edge

This is NOT a browser issue.

**Comment by sleupold** [comment]
this might be an issue of the Lucene search index not to be language aware.

**Comment by MaiklT** [comment]
Sorry, Sebastian, this answer is not helpful :-)

I think the problem is that the text is stored HTML-encoded, and that could be "Kinderg&auml;rten" or "Kinderg&#228;rten" depending on the method used in the module and/or HTML provider - so the indexed content should be HTML-decoded to get results.

**Comment by sleupold** [comment]
Michael,
of course the content of HTML table needs to be html decoded by the API before passing it to the indexer and I just tested on a 7,4,2 site that this worked as expected before (using HTML or AF module). Did you check, whether umlauts in other modules are not indexed as well?

**Comment by MaiklT** [comment]
I know it has been working before. I just tried that using an HTML module now with 7.4.2 and 8.0.4 - it did not work there either. I created a ticket about that in Jira when DNN 9.0.0 was released, but this ticket did not make it to here, therefore I created this one here as well.

**Comment by sleupold** [comment]
hm, it works on my site with DNN 7.4.2, but not on yours with same version - strange? You made sure the indexer is executed properly?

**Comment by sleupold** [comment]
@MaiklT would you mind to check again with DNN 9.2.2, AFAIK there have been fixes applied by ESW.

**Comment by MaiklT** [comment]
@sleupold It works now!
