### ISSUE TITLE
Cannot edit Subcribers role, should not be automatic in terms of the GDPR

### ISSUE THREAD

**Issue by MaiklT** [dnnsoftware/Dnn.Platform#2155]
## Description 

Trying to edit the Subscribers role does not work as all the input fields are disabled. The subscribers role should not be automatically assigned in terms of the GDPR (opt-in only, and to be true, a subscription should be confirmed by an email link as well - maybe we can provide a subscription module for the Subscribers role!)

## Steps to reproduce

Login as host or site administrator. Got Manage >> Roles, and click the edit pencil. It is not possible to change any af the role settings.

## Current result

No editing possible

## Expected result

Editing should be possible

## Affected version

* [x] 9.2
* [ ] 9.1.1 (did not check)
* [ ] 9.1 (did not check)
* [ ] 9.0 (did not check)

## Affected browser

* [X] Chrome
* [X] Firefox
* [X] Safari
* [X] Internet Explorer
* [X] Edge

This is NOT a browser issue,
![subscribers_editing](https://user-images.githubusercontent.com/7458140/42619948-c317351c-85b9-11e8-9720-229fb1fc063c.PNG)

**Comment by sleupold** [comment]
Subscriber role has always been included in DNN Website Templates, but just as a sample, therefore it should **not** be marked as "System", preventing update of rename, role group assignment and other options.

**Comment by MaiklT** [comment]
Sebastian, I completely agree. But this would only be the first step to solve the overall problem. To meet the GDPR regulations, it is necessary to find an opt-in mechanism, ideally one that needs a confirmation.
And the question is: Is it necessary that a user registers just to receive a newsletter subscription? Or should we undock this, providing a mechanism that allows both registered and unregistered users to subscribe?

**Comment by MaiklT** [comment]
I am ready... see if I find some time slots :-)

**Comment by valadas** [comment]
>  I agree that a simple newsletter module with subscription option would be nice to be included in DNN, but that would be a separate item and requires community contribution.

For what it's worth, the old core newsletter module still works, if improving that one is a viable option, you are welcome to contribute at https://github.com/DNNCommunity/DNN.Newsletter @MaiklT

**Comment by nvisionative** [comment]
I realize this is a bit tangential conversation, but the removal of the old newsletter module from the core was a very good change in my opinion.  Clients were also getting their web server "in trouble" (blacklists, mixing web/mail server purposes, etc.) There are much better tools for the job.  The needs are much better met through other modules, or better yet, systems outside of the web application (e.g., MailChimp, etc.).

**Comment by mitchelsellers** [comment]
I think for right now, the best course of review would be to determine if there is any required reason for the "Subscriber" role to be marked as System and included by default.  This would solidify the immediate need.  I agree that future considerations are needed for "opt-in" and similar.

However, the key concern, if I understand right now, is preventing anything from being automatic and un-editable.

**Comment by valadas** [comment]
I think we should also have a way of removing all users from any group. It is very common on old sites when company ownership changes to have a request such as remove all admins and add only these 3 users.

**Comment by sleupold** [comment]
@valadas Daniel, thank you for maintaining the newsletter module and I know, there are a number of sites still using it. It is not a replacement for external services, but for sites with a small or medium size membership (just a few hundreds or thousands) it is an easy option to inform the members of the site or specific groups. Adding a subscription module for other users shouldn't be too hard, if there is enough interest.

**Comment by sleupold** [comment]
@mitchelsellers, you are right, to be able to edit or delete the "Subscribers" role is the subject of this single item and it is not necessarily related to bulkmail module. We might consider as well removing it from default website template as its use case is not obvious atm.

**Comment by sleupold** [comment]
@valadas the option to remove all users from a role should be available to superusers ("host") only for security reasons - otherwise an admin could lock out himself from site editing. Maybe it would be a nice option for Prompt. please feel free to log your enhancement suggestion.

**Comment by MaiklT** [comment]
@mitchelsellers

> However, the key concern, if I understand right now, is preventing anything from being automatic and un-editable.

+1 (except the "Registered Users" group maybe...)

@valadas 

> I think we should also have a way of removing all users from any group. It is very common on old sites when company ownership changes to have a request such as remove all admins and add only these 3 users.

Another good idea. But if an admin does it with the admin group, at least himself should not be removed. And I fear this idea gets lost, because it has nothing to do with this issue...

**Comment by sleupold** [comment]
Subscribers was originally added as a sample for a public role and admins should be able to edit and remove it.

**Comment by valadas** [comment]
So I guess right now we could without making this a breaking change, just make that role not system (editable) and no longer include it in the default templates. It would not change behaviour on upgrades other that allowing editing it and would be absent going forward.

**Comment by MaiklT** [comment]
This is still an issue.

**Comment by sleupold** [comment]
still an issue

**Comment by MaiklT** [comment]
Still an issue - please re-open, thanks!

**Comment by sleupold** [comment]
this would be still a task to fix in site template
