### ISSUE TITLE
Managing version numbers

### ISSUE THREAD

**Issue by tpluscode** [dnnsoftware/Dnn.Platform#2158]
## Description 

Currently every time a new release is prepared a bunch one files must be manually modified. For example the commit for 9.2.1 was 961ba3b. It changes a bunch of `*.dnn` files and adds an extra `.sqldataprovider`.

This is tedious and can be complete unnecessary. We will be submitting a PR for the 9.2.2 but going forward this could and should be automated:

1. Version numbers in manifests should be updated automatically on CI during build
1. The SQL script could be avoided by having each individual module set its correct version based on what it have in the manifest.

**Comment by ohine** [comment]
This is about 85% complete with the new VSTS CI pipeline.

**Comment by valadas** [comment]
I think this is now done @ohine right? I am closing but if I am wrong, please reopen.
