### ISSUE TITLE
Contents are moved from panels automatically if i add more modules

### ISSUE THREAD

**Issue by ufoloko** [dnnsoftware/Dnn.Platform#2163]
## Description 

I have a tab with some modules, 2 or 3, but if i try to add a new module, sometimes modules are relocated to content pane automatically. this happens often

## Steps to reproduce

I Created a tab, with some modules in panes other than ContentPane. Try to add more modules to any other pane.

## Current result

Sometimes modules are moved between panes, or basically are moved to Content Pane automatically

## Expected result

To keep location for each module

## Affected version

* [x] 9.2
* [x] 9.1.1

## Affected browser

* [X] Chrome
* [X] Firefox
* [X] Safari
* [X] Internet Explorer
* [X] Edge

**Comment by valadas** [comment]
This is pretty much the same issue as #2289 , I am closing this one in favor of that one which has more discussions and clear steps to reproduce. @ufoloko please follow on the other issue.
