### ISSUE TITLE
Can't assign a domain name to a page

### ISSUE THREAD

**Issue by valadas** [dnnsoftware/Dnn.Platform#2169]
## Description 
It used to be possible to assign a domain name to a page in Dnn. I cannot do it anymore.

## Steps to reproduce
1. Create a site and give it an alias such as www.localtest.me
2. Add a site alias such as docs.localtest.me
3. Create a page named something like documents
4. On the documents page settings, SEO tab, try to add docs.localtest.me without entering anything in the URL Path

## Current result
An error shows:
```
The submitted URL is not available. If you wish to accept the suggested alternative, please click Save.
```

## Expected result
It should save and navigating to doc.localtest.me should show that page.

- The same behaviour happens with canonical, redirect or none for the portal alias mapping.
- The same behaviour happens with or without ssl.
- The TabUrls table does not have the url anywhere in use for another page.
- Adding something in the URL Path makes it work. My _guess_ is that the code that checks for duplicates only checks the URL Path and not the Site Alias combined with the URL Path when checking for duplicates, but I am not sure.

## Affected version
* [x] 9.2
* [x] 9.1.1
* [?] 9.1 (untested)
* [?] 9.0 (untested)

## Affected browser
Not browser related

**Comment by bdukes** [comment]
Like @mitchelsellers, I was surprised to hear that this ever worked.

**Comment by valadas** [comment]
I used to be able to do it this way:  http://www.ifinity.com.au/Products/Support_Forums/forumid/8/postid/11937/scope/posts

And if memory serves me good it also used to work with the built in functionality in dnn 8.0.4 and with the X3 url management module, let me try with these two so I can add this here how it worked before the persona bar...

**Comment by valadas** [comment]
Ok, Dnn 8 community edition did not have those tools available (only commercial editions), but using the X3.DnnUrlManagement module it does work under Dnn8, which I _think_ means that the underlying code should support this in the platform and it is _probably_ a UI issues since the persona bar since the feature worked before. I am testing an upgrade too so see how this gets in the database.

**Comment by valadas** [comment]
My plan right now is to build a Dnn8 with that module and the pages working as it should, then upgrade that and see first if it keeps working and second how it is in the database. My first guess is what it is only a UI issue, whatever code validates if the path is already takes maybe ignores the domain name or requires the path to have more than 1 char or something without concatenating the domain name before the check. But I may be wront too. Let me test an upgrade and see.

**Comment by valadas** [comment]
I am getting different behaviours on sites with and without localization enabled, let me properly document this, I will get back to this issue with a more details steps on how it works and how it does not work...

**Comment by valadas** [comment]
Well, I was getting a different behaviour on localized vs unlocalized sites because there was another part in the url , I can not make it work, I thought I had it working on Dnn 8 just before, it was fine in the menus and links, but once clicking the link it showed the home page instead of the actual page.

So, for my immediate needs, I will just do what I need in SiteUrls.config.

As for this issue, close it if you think implementing this would cause other issues elsewhere or leave it open if you think it could be a nice enhancement.
