### ISSUE TITLE
user registration will clear whole site's cache and cause performance issue

### ISSUE THREAD

**Issue by tpluscode** [dnnsoftware/Dnn.Platform#2178]
## Description 

ScreenCast: https://www.screencast.com/t/THxBHveOXipy

Compare to a default installation which have little pages: 

https://www.screencast.com/t/UuWWIeV5WmK

Reported by a large client (website contains more than 6K pages). When this running in production environment, it have much performance issue as their conitnue to have new user registration, so it cause cache always been clear.

## Steps to reproduce

1. install 9.2.0 latest version; 
2. create thousands of pages; 
3. change the user registration mode to Public. 
4. click register button and register a new user.

## Current result

you will see the page load slower in the first time then will back to normal speed. but if you register a new user again, the whole site's cache will be clear again, page will slow load again.

## Expected result

the page load speed won't impacted by register new user action.

## Affected version

* [x] 9.2
* [ ] 9.1.1
* [ ] 9.1
* [ ] 9.0

## Affected browser

* [ ] Chrome
* [ ] Firefox
* [ ] Safari
* [ ] Internet Explorer
* [ ] Edge

**Comment by tpluscode** [comment]
@zyhfish I only checked 9.2. Does this also affect older versions, do you know?

**Comment by tpluscode** [comment]
@dnnsoftware/tag we probably want these changes in 9.2.1, right?

**Comment by mitchelsellers** [comment]
@tpluscode At this point in time we are well beyond code freeze for 9.2.1.  These will all be there for 9.2.2

**Comment by tpluscode** [comment]
All merged. Closing
