### ISSUE TITLE
Unable to Disable "Default" authentication provider

### ISSUE THREAD

**Issue by mitchelsellers** [dnnsoftware/Dnn.Platform#2184]
## Description 
Once a secondary authentication provider has been added to the system it should be possible to disable the "Default" authentication system to allow the new provider to be the only enabled provider.  Attempts to update the settings for the default DNN Provider result in an HTTP 400 Bad Request error and nothing is updated.

## Steps to reproduce
1. Install a new authentication provider to the system.  (I can provide one if needed)
2. Validate that login shows both providers, should see two tabs
3. Login as a host user and from the persona bar do the following
    *  Select "Extensions"
    *  Filter the list to "Authentication Systems"
    *  Select "Edit" next to the Default Authentication option
    *  Under "Extension Settings" try turning the 'Enabled' field to false and save

## Current result
Nothing happens in the browser after clicking save.  Looking at Developer Tools we can see that we are getting an HTTP 400 Bad Request response from https://{SiteUrl}/API/PersonaBar/Extensions/SavePackageSettings

## Expected result
Settings should be updated and you should now only see 1 login provider on the login page.

## Affected version
* [X] 9.2
* [X] 9.1.1
* [X] 9.1
* [X] 9.0

## Affected browser
Consistent behavior in all browsers

## Temporary Workaround
As a workaround, the following SQL Script will disable the DNN Provider

```
UPDATE Authentication
SET IsEnabled = 0
WHERE AuthenticationType = 'DNN'
```

Then clear the cache of DNN.

**Comment by valadas** [comment]
@mitchelsellers so, in your authentication provider presentation you could disable the default provider, was this fixed somehow or do your instructions just use the suggested workaround ?

**Comment by mitchelsellers** [comment]
I need to retest.

**Comment by kiranpjadhav** [comment]
Hi @mitchelsellers, I have installed your external authentication module and I am still facing this issue. 
I have applied the SQL script as well still issue is unresolved.  
I am using the DNN version 9.4.1.

**Comment by valadas** [comment]
Tested this on 9.10.0 and it looks like this got fixed somehow as it works now.
