### ISSUE TITLE
Page Management: Unable to drag page to child destination Or select new Parent Page DNN9.2.1

### ISSUE THREAD

**Issue by pjkruger** [dnnsoftware/Dnn.Platform#2186]
## Description 
In v. 09.02.01 (532) I am unable to create a child page or change locations of a child page by dragging it onto another page.
You can only drag it up to the "main" level.

On any page you are unable to select a new Parent Page from the Parent Page drop down.

I believe these two issues are related.

## Steps to reproduce
Try moving a page by dragging it onto another page or selecting a new destination from the Parent Page drop down list.

I tested it in Chrome and Firefox.

## Affected version
v. 09.02.01 (532)

* [ ] 9.2
* [ ] 9.1.1
* [ ] 9.1
* [ ] 9.0

## Affected browser

* [x ] Chrome
* [x ] Firefox
* [ ] Safari
* [ ] Internet Explorer
* [ ] Edge

**Comment by tpluscode** [comment]
I believe this is same as the problem reported here: dnnsoftware/Dnn.AdminExperience.Extensions#581.

**Comment by tpluscode** [comment]
This has eventually been fixed in final 9.2.1 release
