### ISSUE TITLE
GDPR Cookie Policy Consent Compliance

### ISSUE THREAD

**Issue by thabaum** [dnnsoftware/Dnn.Platform#2188]
## Description 
I noticed most all sites that are used in EU have to have a cookie consent form added to the site.  I am wondering if DNN is going to add that like it has privacy policy and ToS pages.

## Current result
No cookie consent message

## Expected result
A message and page that makes website portals compliant with GDPR Cookie regulatory rules

## Affected version

* [x] 9.2
* [x] 9.1.1
* [ ] 9.1
* [ ] 9.0

## Affected browser

* [ ] Chrome
* [ ] Firefox
* [ ] Safari
* [ ] Internet Explorer
* [ ] Edge

**Comment by sleupold** [comment]
we have set up a team for GDPR enhancements of DNN - please read http://www.dnnsoftware.com/community-blog/cid/155590/gdpr-compliance-looking-for-volunteers . From my experience, Cookie Consent is currently subject of discussion within EU site owners, and there is no real clear regulation from the EU atm, as ePrivacy directive - which should clarify, how to implement appropriate solutions, has not yet been released by the EU.

**Comment by sleupold** [comment]
there is a new issue and PR for this.

**Comment by nvisionative** [comment]
The new issue is #2361 and the associated PRs are #2369 and dnnsoftware/Dnn.AdminExperience#100

**Comment by ohine** [comment]
Closing as the PRs were merged.
