### ISSUE TITLE
Ability to use Email and Username for logins

### ISSUE THREAD

**Issue by thabaum** [dnnsoftware/Dnn.Platform#2189]
## Description 
It would be nice to be able to allow users to use a username or email address to login.  I have seen this option on some DNN sites but no option in the community edition to do so.

## Current result
Options to allow users to log in using a username or email address only but not both as options.

## Expected result
An admin or host option that allows the selection of using Username, Email Address or both as a way to sign into DNN community edition.

## Affected version

* [x] 9.2
* [x] 9.1.1
* [ ] 9.1
* [ ] 9.0

## Affected browser

* [ ] Chrome
* [ ] Firefox
* [ ] Safari
* [ ] Internet Explorer
* [ ] Edge

**Comment by tpluscode** [comment]
Thank you @thabaum. This is getting fixed in 9.2.1. Please see #2115

**Comment by thabaum** [comment]
I think this issue was confused.  I was actually thinking of being able to enter a username or email address or phone number or any other field you wish that is created and made required desired.

Generally, a phone number, email, or username is used to log into a website.  

Instead of just "Enter Username"
The field instructs the user to `Enter Username, Email Address or Phone Number"

This should not have been closed. Can we please reopen this issue?  Thank you.

**Comment by valadas** [comment]
It is possible for emails or phone numbers to not be unique, this could not work universally or be a huge security issue.
