### ISSUE TITLE
On Module Controls is partially visible the Source folder and Source file items

### ISSUE THREAD

**Issue by Scippy** [dnnsoftware/Dnn.Platform#2190]
I need to edit a module controls through host user in this way:
Settings ->  Extension -> click edit for the Module I nedd to modify -> Extension Settings ->click edit  
on the module definition I need to modify -> click edit on Module Controls I need to modify
Now I should be able to change the  Source folder and Source file for the selected module control but the problem is that all items are listed in a dropbox with truncated text and not completely visible.
In DNN9 version these dropdown are width50% and little or nothing is visible of their contents and it is impossible to use.

## Affected version
[x] 9.2
[x] 9.1.1
[x] 9.1
[x] 9.0

## Affected browser
[x] Chrome
[x] Firefox
[x] Safari
[x] Internet Explorer
[x] Edge

**Comment by mitchelsellers** [comment]
@dnnsoftware/tag this is technically a Persona Bar issue, should we duplicate this issue in that Repo?

**Comment by valadas** [comment]
Issue moved to [dnnsoftware/Dnn.AdminExperience #1036](https://github.com/dnnsoftware/Dnn.AdminExperience/issues/1036) via [**ZenHub**](https://www.zenhub.com/)
