### ISSUE TITLE
Export/Import Issues with module permissions

### ISSUE THREAD

**Issue by juanpfac** [dnnsoftware/Dnn.Platform#2193]
Description 
When importing a site as child, the modules that do not share the same permissions as the page does not import.

Steps to reproduce
Create a site
Add a Page (View for All Users)
Add Different modules to that page
Change modules permissions (view to Registered users and Unverified Users)

Current Result
All modules set to View as Registered Users

Expected Result

Modules should keep the View Permissions.

Affected version
9.1.1

* [x] 9.1.1

Affected browser
All

* [x] Chrome
* [x] Firefox
* [x] Safari
* [x] Internet Explorer
* [x] Edge

**Comment by valadas** [comment]
I was not able to reproduce using 9.4.0 RC @juanpfac if you are still able to reproduce on latest release, please open a new issue.
