### ISSUE TITLE
Connectors Lack Descriptive Information

### ISSUE THREAD

**Issue by hismightiness** [dnnsoftware/Dnn.Platform#2194]
## Description 
When viewing connectors out-of-the-box (checked DNN 9.2.1 RC only), there isn't any helpful information to know what the connector does.  See below...

![image](https://user-images.githubusercontent.com/938023/43485553-641fa03c-94c6-11e8-8309-7d758b01e89b.png)

![image](https://user-images.githubusercontent.com/938023/43485652-a3cd9608-94c6-11e8-98af-9bfa960b9197.png)

## Affected version

* [x] 9.2.1 RC
* [ ] 9.2.0 RC
* [ ] 9.1.1
* [ ] 9.1
* [ ] 9.0

## Affected browser

* [X] Chrome
* [X] Firefox
* [X] Safari
* [X] Internet Explorer
* [X] Edge

**Comment by nvisionative** [comment]
This is confusing to so many people.  Thank you for posting the issue!

**Comment by birksy89** [comment]
Is it possible to get more connectors, such as the Google Analytics one:
![unnamed](https://user-images.githubusercontent.com/4971630/44087230-0f7edf10-9fb7-11e8-8513-56f15e1f33a1.jpg)

If it is possible, it should be clear that you installed them (as extensions - I'm guessing?)

**Comment by valadas** [comment]
More descriptive titles have been added on some PR but not linked to this issue, closing it.

![image](https://user-images.githubusercontent.com/6371568/61992168-c9a93200-b028-11e9-9c15-6eec171bd93f.png)
