### ISSUE TITLE
Improve search times when searching images

### ISSUE THREAD

**Issue by tpluscode** [dnnsoftware/Dnn.Platform#2201]
## Description 

...when portal has thousands of folders/files.

## Steps to reproduce

1. install engage 9.2.0 and login as host; 
2. add a new page and edit the default html module, open images dialog; 
3. type something in the search box.

Screencast: https://www.screencast.com/t/d4A2NQOmKAm

## Current result

the search will be very slow to response.

## Expected result

search result should be display quickly.

## Affected version

* [x] 9.2
* [ ] 9.1.1
* [ ] 9.1
* [ ] 9.0

**Comment by sleupold** [comment]
@tpluscode sorry, I missed the underlying issue (use case) for the change.
IMO we should consider using DNN search index for this situation or extend the stored procedure GetFiles with an additional parameter "Search Term" to return just the matching files. Out of these alternatives, only Lucene will be well performing unless we add a fulltext index to the DNN database.

**Comment by tpluscode** [comment]
Would you consider this a new enhancement? Either solution would require a bit more change. I think we should create a new issue and discuss how to proceed

**Comment by sleupold** [comment]
@tpluscode I agree. I'll have a look into the code and create a new issue.

**Comment by sleupold** [comment]
@tpluscode I just noticed, search for images in the editor seem to be an Evoq exclusive feature, you may discuss inside your corp.
