### ISSUE TITLE
Incomplete NuGet packages

### ISSUE THREAD

**Issue by tpluscode** [dnnsoftware/Dnn.Platform#2203]
## Description 

We're just discovering the hard way, while implementing tests MS Fakes, that some packages published to nuget do not include the necessary dependencies or binaries. This is a problem because MS Fakes try to process the assemblies and attempt to load the missing dlls

These give us trouble:

1. **DotNetNuke.Core**
* `dotnetnuke.dll` references `DotNetNuke.Services.Syndication.dll` but it is not included in the package nor has its dedicated package
* `dotnetnuke.dll` references `PetaPoco.dll 5.0.1.17400`. This one is weird because I do not find a matching version in official packages. It's [committed](https://github.com/dnnsoftware/Dnn.Platform/blob/development/DNN%20Platform/Components/PetaPoco/bin/PetaPoco.dll) to the repository though.
* also references
   * SchwabenCode.QuickIO
   * Lucene.Net.Contrib.FastVectorHighlighter
   * Lucene.Net
   * DotNetNuke.Web.Client
   * DotNetNuke.WebUtility (version 4.2.1.783!)
   * CountryListBox
   * DotNetNuke.Instrumentation
   * DotNetNuke.WebControls
   * ICSharpCode.SharpZipLib
   * a bunch of System.* assemblies
1. **DotNetNuke.Web.Client**
* `DotNetNuke.Web.Client.dll` references `ClientDependency.Core`
* also references `DotNetNuke.Instrumentation`

## Affected version

any and all

**Comment by tpluscode** [comment]
Initially I thought it would be enough to 

1. add `DotNetNuke.Services.Syndication.dll` and `PetaPoco.dll` to the core package
1. add `DotNetNuke.Instrumentation reference to DotNetNuke.Core
1. add `DotNetNuke.Instrumentation` and `Dnn.ClientDependency` reference to DotNetNuke.Web.Client
1. also publish `Dnn.ClientDependency`to nuget.org - currently it's only on myget

Unfortunately looks I'm actually uncovering a bigger problem, especially in the case of the core library. I'm super surprised that it directly references zip, lucent and web packages.

**Comment by mitchelsellers** [comment]
Another issue has addressed this issue with updated packages as part of 9.3.2 and later
