### ISSUE TITLE
Strange behaviour with Request.CreateResponse in DnnApiController/Service Framework

### ISSUE THREAD

**Issue by improwise** [dnnsoftware/Dnn.Platform#2208]
## Affected version

* [x] 9.2

We have noticed a strange problem which we are not sure if it is because of problems in the DNN WebAPI/Service framework or in .NET. 

    public class TestController : DnnApiController
    {

        [AllowAnonymous]
        [HttpGet]
        public HttpResponseMessage TestResponse()
        {
            try
            {

                //return Request.CreateResponse(HttpStatusCode.Unauthorized, "HttpStatusCode.Unauthorized");

                return Request.CreateResponse(HttpStatusCode.Unauthorized);
            }
            catch (System.Exception ex)
            {
                //Log to DotNetNuke and reply with Error
                Exceptions.LogException(ex);
                return Request.CreateErrorResponse(HttpStatusCode.InternalServerError, ex.Message);
            }
        }
}

If we use:

`return Request.CreateResponse(HttpStatusCode.Unauthorized, "HttpStatusCode.Unauthorized");`

everything will work find and we will get a response with the correct status (401) and content ("HttpStatusCode.Unauthorized"). 

However, if we instead use it without the message like:

`return Request.CreateResponse(HttpStatusCode.Unauthorized);`

We will instead get a response with statuscode OK (200) but where the content is 401 (Unauthorized) which is of course all wrong. It should be status 401 as before. 

Is this a bug with DNN or .NET? Or are we doing something wrong? 

 //ImproWise

**Comment by bdukes** [comment]
Depending on which Microsoft documentation you find, this may or may not be the intended behavior.  I think this probably relates to the specific versions of libraries are being compiled against as to whether it's interpreted as the value or the status code.  The newer APIs don't accept the status code as the only argument, so to be safe, I would pass the value as `null` if you don't have one.
