### ISSUE TITLE
Improve String Comparison Performance & Consistency

### ISSUE THREAD

**Issue by mitchelsellers** [dnnsoftware/Dnn.Platform#2215]
## Description 
Following [Microsoft Best Practices](https://docs.microsoft.com/en-us/dotnet/standard/base-types/best-practices-strings) documentation there are a number of locations inside of the DNN Platform API's that use ToUpper, ToUpperInvariant, ToLower, ToLowerInvariant and other string comparisons that are against the best practices reccomendations.

These methods should be standardized and the use should be moved to consistently use StringComparison.InvariantCultureIgnoreCase and String.Comparison.OrdinalIgnoreCase (for internal items).

## Steps to reproduce
The impacts of this behavior can only be seen with a Memory Profiler or similar tool.

## Current result
The existing code results in multiple objects being created adding to the number of items that need to be Garbage Collected when we can simplifiy and optimize the comparisons, resulting in less memory churn which will result in faster performance.

## Expected result
When monitoring memory consumption the same string should not be seen as initilaized repeatedly and immediate garbage collected.

## Affected version
* [x] 9.2.1
* [x] 9.2
* [x] 9.1.1
* [x] 9.1
* [x] 9.0

## Affected browser
N/A

**Comment by bdukes** [comment]
I believe `StringComparison.InvariantCulture` and `StringComparison.InvariantCultureIgnoreCase` are recommended against in the vast majority of use cases.  You pretty much always want `Ordinal` or `OrdinalIgnoreCase` if you don't want to use the current culture.

Overall, I'm a big fan of this change 👍

**Comment by mitchelsellers** [comment]
You are correct here, but in the interest of limiting breaking changes if it was a ToLowerInvariant, I keep the Invariant, otherwise doing Ordnial for performance
