### ISSUE TITLE
Remove Site Settings - Site Logo fails

### ISSUE THREAD

**Issue by liffeyd** [dnnsoftware/Dnn.Platform#2218]
## Description 
Attempting to remove the Site Settings > Site Logo fails

## Steps to reproduce

Fresh DNN 9.2.1 install
On PersonaBar select Site Settings, click left icon in Site Logo area. Area changes to two drop downs Folder and File. Select "None Specified" in File drop down. Press ENTER or click [ENTER]

## Current result
The logo should be removed but is not.

Click the Save button results in "Could not update settings. Please try later.

Fiddler shows:
POST /API/PersonaBar/SiteSettings/UpdatePortalSettings

JSON
-LogoFile
--fileID=(null)
--fileName=(null)
--folderPath=Images/

Fail
HTTP Result: 500 

## Expected result
The logo should be removed.

Adding a new logo works fine.
The logo should be updated and is updated as expected.

POST /API/PersonaBar/SiteSettings/UpdatePortalSettings

JSON
-LogoFile
--fileID=155
--fileName=logo.png
--folderPath=Images/

HTTP Result: 200
Success

## Affected version

ONLY 9.2 tested
* [x] 9.2
* [] 9.1.1
* [ ] 9.1
* [ ] 9.0

## Affected browser

Only tried browsers marked.

* [X ] Chrome
* [X ] Firefox
* [ ] Safari
* [ ] Internet Explorer
* [X ] Edge

**Comment by valadas** [comment]
Issue moved to [dnnsoftware/Dnn.AdminExperience #1037](https://github.com/dnnsoftware/Dnn.AdminExperience/issues/1037) via [**ZenHub**](https://www.zenhub.com/)
