### ISSUE TITLE
Unable to make Facebook Authentication Provider work

### ISSUE THREAD

**Issue by thabaum** [dnnsoftware/Dnn.Platform#2219]
## Description 
Facebook Authentication Errors no matter how many different ways I set it. I have been trying for months now and put in other requests.  I dont see any documentation on how to use the authentication provider with current details and settings to make it function.

I keep getting this error when I feel I am the closest to having it work, I know I had it working in the past as I have registered facebook users but since 9.0 things have died out entirely.

Message:Object reference not set to an instance of an object.

StackTrace:

InnerMessage:Object reference not set to an instance of an object.

InnerStackTrace:

at DotNetNuke.Authentication.Facebook.Login.AddCustomProperties(NameValueCollection properties) at DotNetNuke.Services.Authentication.OAuth.OAuthClientBase.AuthenticateUser(UserData user, PortalSettings settings, String IPAddress, Action`1 addCustomProperties, Action`1 onAuthenticated) at DotNetNuke.Services.Authentication.OAuth.OAuthLoginBase.OnLoad(EventArgs e) at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)

## Steps to reproduce
Create a website and add authentication providers for login and registering.
Create facebook app credentials, add app domain and facebook login settings which I dont see any articles to reproduce what you currently see today.

## Current result

Error redirecting to this page when trying to use the authentication provider service: 
Default.aspx?tabid=257&error=An%20unexpected%20error%20has%20occurred&content=0#_=_

## Expected result
User grants access to application on registration creating an account and is able to login using facebook button.

## Affected version

* [x] 9.2
* [x] 9.1.1
* [ x] 9.1
* [x ] 9.0

## Affected browser

* [x] Chrome
* [x] Firefox
* [x] Safari
* [x] Internet Explorer
* [x] Edge

**Comment by thabaum** [comment]
August of 2017 is the last time a user was able to use Facebook Login, or any login provider.

I just tried twitter login and get a similar error... after trying for a long time again to make this work not sure if anyone else has this working?  

Do any developers here try to run a community on the DNN CE out of curiousity?  Try to do a start up with this and you are hurting for long long time.

Does the paid version of DNN work like this?  Because the CE is barebone product, the social additions are lacking since version 6.2 no real major updates or features added for the social or community side.  

Is this a known issue with the authentication providers or do I have a bugged up DNN installation?

**Comment by vincentparrett** [comment]
I'm not able to make the facebook provider work either - currently seeing this bug - https://dnntracker.atlassian.net/browse/DNN-10818 which was reported in May.

**Comment by thabaum** [comment]
https://github.com/dnnsoftware/Dnn.Platform/issues/2257

It has not worked for me for over 1 year.  I figured it was due to email registration issue potentially but the RC of 9.2.2 I still have the same issue.   So I believe it has to do with supporting OAuth version 3.  I made a post here so maybe it will help someone with understanding of the Authentication system to patch.

**Comment by Tychodewaard** [comment]
Is #2302 related? There seems a fix in #2301

**Comment by valadas** [comment]
Since there was no further comments after the previous comment, I am assuming this is now fixed, if not, please open a new issue.

**Comment by thabaum** [comment]
I was never able to get any providers to work however I will test again... no comments because I simply gave up on this being fixed and removed all authentication providers from my sites.  I lost all my facebook/twitter users anyhow as they could not log in or register for years now.

After I test I will put a new ticket up again... maybe it works now?!  Has anyone made any of the authentication providers work?   This is the question I have been asking since August 2017 when everything broke on my site after version 9 upgrade.

**Comment by valadas** [comment]
@dnnsoftware/tag anyone uses those providers and can chime in on this ?

**Comment by Tychodewaard** [comment]
https://github.com/jbrinkman/Auth0-Provider/releases is new since yesterday. If this works (not tried myself yet) you can hook Fb on it
