### ISSUE TITLE
DNN Journal Word Wrap turn off/on

### ISSUE THREAD

**Issue by thabaum** [dnnsoftware/Dnn.Platform#2225]
## Description 
I am reading half of a word and having to scroll to next line to finish reading it.
## Steps to reproduce
Put a journal post long enough to make a word go to next line
## Current result
half the word is on one line the other half is on the other
## Expected result
Easier to read if you can see the entire word, otherwise you feel like your in elementary school learning how to read.
## Affected version

* [x] 9.2
* [x] 9.1.1
* [ ] 9.1
* [ ] 9.0

## Affected browser

* [ ] Chrome
* [ ] Firefox
* [ ] Safari
* [ ] Internet Explorer
* [ ] Edge

**Comment by Tychodewaard** [comment]
If you add to the css:

.journalitem .dnnClear {
word-break: initial;
}

It is fixed. 
But I don't know if this is the right approach.
