### ISSUE TITLE
testing SMTP settings for a portal as administrator email popup message states it came FROM hostSMTPaddress@domain1.com TO portalSMTPaddress@domain2.com

### ISSUE THREAD

**Issue by thabaum** [dnnsoftware/Dnn.Platform#2227]
## Description 
testing SMTP settings for a portal as administrator email popup message states it came FROM **hostSMTPaddress@domain1.com** TO **portalSMTPaddress@domain2.com**
## Steps to reproduce

1. create a dnn host website
2.  set and test HOST SMTP SETTINGS
3. crreate a website for another administrator
4. set SMTP Server Mode: Portal (not global, basic smtp authentication with SSL enabled)
5. test SMTP settings

## Current result
popup message states it came FROM **hostSMTPaddress@domain1.com** TO **portalSMTPaddress@domain2.com**

## Expected result
popup message stating a message FROM **portalSMTPaddress@domain2.com** TO **adminUserEmailAddresst@domain2.com**

The test message is the message that should be for the portal settings not for host settings.  Host email settings should not be used in any messages when configuring PORTAL specific SMTP settings.
## Affected version

* [x] 9.2
* [x] 9.1.1
* [ ] 9.1
* [ ] 9.0

## Affected browser

* [ ] Chrome
* [ ] Firefox
* [ ] Safari
* [ ] Internet Explorer
* [ ] Edge

**Comment by mortezakermani** [comment]
I couldn't find any  place to update host settings then I executed following query in SQL:

update hostsettings set settingvalue = 'xxxxxx@domain.com' where settingvalue = 'host@change.me'

**Comment by valadas** [comment]
The option to change the host email has been added in https://github.com/dnnsoftware/Dnn.AdminExperience/pull/39 but i agree that when sending the test email from the admin settings (and not the host settings) the test email should come from the admin email because the admin smtp server may refuse sending that using the host email.

**Comment by thabaum** [comment]
This was fixed in #3237 I believe so I will close.  Thank you.
