### ISSUE TITLE
Update pinned repos on the DNNSoftware github page

### ISSUE THREAD

**Issue by OllyHodgson** [dnnsoftware/Dnn.Platform#2233]
## Description 

Now all the PersonaBar (etc) repositories have been combined into Dnn.AdminExperience, the pinned repositories on the home page need to be updated to reflect that. It'll make it easier for new contributors to understand how everything hangs together.

## Steps to reproduce

Visit https://github.com/dnnsoftware/

## Current result

![image](https://user-images.githubusercontent.com/437224/44100264-97f86ab2-9fdc-11e8-834c-ddbbf3ffd267.png)

## Expected result

Only Dnn.Platform and Dnn.AdminExperience repositories are pinned.

**Comment by nvisionative** [comment]
**Dnn.React.Common** is still valid to be pinned.

**Comment by OllyHodgson** [comment]
Seems to be done now :smile:
