### ISSUE TITLE
VSTS Unit Tests Failing when using Sql CE as Data Provider

### ISSUE THREAD

**Issue by mtrutledge** [dnnsoftware/Dnn.Platform#2234]
## Description 
The current VSTS build fails when testing the DataContext and using the PetaPoco connection strings because the VSTS sytem cannot find the System.Data.SqlServerCe.4.0 data provider.

## Steps to reproduce
Build with Unit Tests on in VSTS

## Current result
DataContext tests fail

## Expected result
All tests should pass

## Affected version
9.2.2.66

* [ ] 9.2.1
* [ ] 9.2.0
* [ ] 9.1.1
* [ ] 9.1
* [ ] 9.0

## Affected browser

* [ ] Chrome
* [ ] Firefox
* [ ] Safari
* [ ] Internet Explorer
* [ ] Edge

**Comment by ohine** [comment]
#2291 fixed a few more of these.

**Comment by valadas** [comment]
I am closing this assuming it is either solved because of the two merged PRs or invalid since we now use Azure Devops, if I am mistaken, please reopen
