### ISSUE TITLE
When packaged, install modules have invalid names

### ISSUE THREAD

**Issue by tpluscode** [dnnsoftware/Dnn.Platform#2239]
## Description 

VSTS installation package comes with wrongly named extension. 

## Steps to reproduce

* Get 9.2.2.64 from VSTS
* extract the install.zip
* go to `Install/Module`

## Current result

Extensions have weird names like 

`DNNCE_SocialGroups_9.ToString('00').2.ToString('00').2.ToString('00')_Install` 

instead of

 `DNNCE_SocialGroups_09.02.02_Install`

![image](https://user-images.githubusercontent.com/588128/44194330-f3c65480-a135-11e8-96aa-ec96a7c10f88.png)

String format leaked into the names. Besides, is the leading zero even necessary? @zyhfish @ashishpd @galatrash 

## Affected version

* [x] 9.2.2

**Comment by ohine** [comment]
Thanks @tpluscode, we will get this fixed today.

**Comment by ohine** [comment]
Fixed in build v9.2.2.74. Closing issue.
