### ISSUE TITLE
Still Can't Register Users using Email Address SQL Error

### ISSUE THREAD

**Issue by thabaum** [dnnsoftware/Dnn.Platform#2243]
## Description 
unable to register new accounts now 6 months.... guess i should of just switched to username as password, I wish you guys would of said your not fixing this for a year to me somewhere...  Authentications providers down just really put wrench in my spokes I lost all momentum on my sites using DNN CE.  So many good fixes but this makes me want to vent a little sorry...  This isnt helping your sales for me buying your paid products either in fact it is doing the opposite.  I was hoping to have engage by now, looks like lost hope here.  I need to see priority fixes done here asap. Is there a fix for this I am missing or is this just a project that will forever plague me with problems?  PLEASE let me know now I will rebuild on another platform.   If there is something here I am missing please let me know as there is just no real community support, just diverted answers to my questions. You cant imagine the amount of time I spent on this project and I bill my clients up to $100/hr so trust me I know it can cost.  I just need to justify spending or getting sucked into an ecosystem that will cost me annually.  This has cost me more than what your evoq is worth and it is getting close to time for making a major descision here.

I suppose I could set it to username instead of email as I did for some other sites I just really wanted only an email for them to remember/use to log into a series of sites.  Tight budget for this project if DNN CE functioned as it suppose to I would of grown.  I grow my site up and you kill it for me.

Thank you!

## Current result
Check
08/16/2018 10:22:09
Page Load Exception

AbsoluteURL /Default.aspx DefaultDataProvider DotNetNuke.Data.SqlDataProvi 

AbsoluteURL:/Default.aspx

DefaultDataProvider:DotNetNuke.Data.SqlDataProvider, DotNetNuke

ExceptionGUID:46a417eb-c681-4169-ac47-f359536a3b29

AssemblyVersion:9.2.1

PortalId:2

UserId:-1

TabId:257

Referrer:

UserAgent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36 Edge/17.17134

ExceptionHash:sIfJdI0jJK8hb1ujOD/SKl4oAH8=

Message:Object reference not set to an instance of an object.

StackTrace:

InnerMessage:Object reference not set to an instance of an object.

InnerStackTrace:

at DotNetNuke.Entities.Users.UserController.IsValidUserName(String userName) at DotNetNuke.Modules.Admin.Users.Register.Validate() at DotNetNuke.Modules.Admin.Users.Register.registerButton_Click(Object sender, EventArgs e) at System.Web.UI.WebControls.LinkButton.OnClick(EventArgs e) at System.Web.UI.WebControls.LinkButton.RaisePostBackEvent(String eventArgument) at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)

Source:

FileName:

FileLineNumber:0

FileColumnNumber:0

Method
## Affected version

* [x ] 9.2.1
* [ ] 9.2.0
* [ ] 9.1.1
* [ ] 9.1
* [ ] 9.0

## Affected browser

* [ ] Chrome
* [ ] Firefox
* [ ] Safari
* [ ] Internet Explorer
* [ ] Edge

**Comment by mitchelsellers** [comment]
What are you using for the username at this point in time?

**Comment by thabaum** [comment]
email address.
9.2 
could not log in using email address.
9.2.1
Now I can manually create a user and log in using email address but I still cannot register.
Not sure if this has to do with Authentication not allowing FB and Twitter to register/login

The sites I changed from using email address to using username for login seemed to allow login in 9.2 so those sites I will be testing here soon the registration and authentication.  Too many fires trying to put out at once here with such little time to do it :)

I am going to test the twitter and fb authentication on a site using username for username next to see if I can get anywhere further on that.

**Comment by mitchelsellers** [comment]
Sorry, let me be more specific, is the email address that you are using one that might have different values than normal.

**Comment by thabaum** [comment]
advertising@domain.com

**Comment by thabaum** [comment]
the page does nothing but that error is produced in admin logs.

Page is created using the registration module on a fresh page (So i can make it ssl)

**Comment by thabaum** [comment]
OK yet another issue I am tired of filling out forms on this can I please just keep them all here...

When I enter the security code... it always fails the first time, second time it works.

**Comment by thabaum** [comment]
and on that same instance yet again registration using email as username fails.   The page goes no where does not show errors.

I can't image how frustrated my business clients have gotten trying to use a few of my sites, and it totally shows because those sites are 100% for 1 year now.  All that work for nothing and I have been patient as possible trying to get responses here on this issue.

Thanks for at least replying...

**Comment by mitchelsellers** [comment]
If you can, email me directly at msellers@Iowacomputergurus.com and I'll see if I can help you.

This feature/function has been tested and is working on multiple installations, we need to figure out what is different with your installation to cause the issues.

**Comment by thabaum** [comment]
OK...

Default.aspx?tabid=21&error=An%20unexpected%20error%20has%20occurred#_=_

I get this error as well when using facebook authentication on any installation seems the same.  

This is an updated version of DNN and not clean installation of 9.2.1

I have not tested 9.2.1 as a clean installation so maybe it was something that didnt get fixed during upgrade processes potentially.

I will put a fresh installation together to test as well I suppose if you say it is working and send you an email with my environment.

Message:Object reference not set to an instance of an object.

StackTrace:

InnerMessage:Object reference not set to an instance of an object.

InnerStackTrace:

at DotNetNuke.Services.Authentication.OAuth.OAuthClientBase.ExecuteWebRequest(HttpMethod method, Uri uri, String parameters, String authHeader) at DotNetNuke.Services.Authentication.OAuth.OAuthClientBase.ExchangeCodeForToken() at DotNetNuke.Services.Authentication.OAuth.OAuthClientBase.AuthorizeV2() at DotNetNuke.Services.Authentication.OAuth.OAuthLoginBase.OnLoad(EventArgs e) at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)

Source:

FileName:

FileLineNumber:0

FileColumnNumber:0

**Comment by thabaum** [comment]
Just went through version logs and one starts at 8.04 version and the other the issues started after 8.04 when I upgraded to 9.0

This shows how long it has been an issue for me as I could see by the users that registered last was prior to the date of the 9.0 update.

**Comment by thabaum** [comment]
https://github.com/thabaum/Dnn.Platform/blob/development/Website/DesktopModules/Admin/Security/User.ascx.cs

I made the change here I believe this should be true instead of false.  Is this correct and if so how do I make a pull request? 

     // make sure username is set in UseEmailAsUserName" mode
            if (PortalController.GetPortalSettingAsBoolean("Registration_UseEmailAsUserName", PortalId, true))
            {
                user.Username = User.Email;
                User.Username = User.Email;
}

**Comment by thabaum** [comment]
Thank you I will get on this now!

**Comment by thabaum** [comment]
welp was a good try I did get a better understanding of PortalController.GetPortalSEttingsAsBoolean as the false sets a default setting if none exists.  Thanks for clearing that up as creating users does work when using the admin panel so that makes much more sense now.

**Comment by thabaum** [comment]
Line 	583	        **var valid = UserController.Instance.IsValidUserName(name);** 
when using this function from https://github.com/dnnsoftware/Dnn.Platform/blob/5be4d592ec1803dca5ac81ce7d9ec346decf0b1f/Website/DesktopModules/Admin/Security/Register.ascx.cs

Is the statement above calling the function below and if so should the variable used actually be named userName for it to function right or can you call it whatever you like?  Im trying to break the rust off my brain here and get use to .NET along with DNN classes so help here is much appreciated.

line 564   **public bool IsValidUserName(string userName)**

From

https://github.com/dnnsoftware/Dnn.Platform/blob/5be4d592ec1803dca5ac81ce7d9ec346decf0b1f/DNN%20Platform/Library/Entities/Users/UserController.cs

**Comment by thabaum** [comment]
https://github.com/dnnsoftware/Dnn.Platform/pull/2212

I just seen this pull reqeuest approved and merged with 9.2.2 5 days ago...

Maybe this is fixed?  I am not testing on this development build as I do not know how to build this yet.  And if it has been fixed I am wasting more time :(

Can I add this file to the module directory as a aspx.cs file where the aspx file is, restart the app pool and it run the .cs file?

php so much easier to edit on the fly I am trying to catch up here.  Taking virtual classes from MVA only goes so far, actually working with this project can really make your head spin asking stupid questions and feeling dumb while doing so...

**Comment by mitchelsellers** [comment]
It looks like this is the case, that 2212 fixes this issue.

After some investigation I found that something I was doing in my testing allowed my installs to work, that was different than platform, and I had been testing on a 9.2.2 build.  I didn't realize that this issue was merged into 9.2.2.

The RC for 9.2.2 comes out Monday, this should resolve it.
