### ISSUE TITLE
There are references to www.dotnetnuke.com in text

### ISSUE THREAD

**Issue by EPTamminga** [dnnsoftware/Dnn.Platform#2249]
## Description 
The descriptions in various .resx text and SQLdataprovider files are referencing www.dotnetnuke.com. That site does not exist anymore

## Steps to reproduce
Text search *.resx and for www.dotnetnuke.com

## Current result
> Installwizard.aspx.nl-NL.resx
> Installwizard.aspx.it-IT.resx
> Installwizard.aspx.fr-FR.resx
> Installwizard.aspx.es-ES.resx
> Installwizard.aspx.de-DE.resx
> Installwizard.aspx.resx
> GlobalResources.resx
> 08.00.00.28.SqlDataProvider
> 07.02.02.SqlDataProvider
> 07.02.01.SqlDataProvider
> 07.02.00.SqlDataProvider
> 07.00.03.SqlDataProvider
> 07.00.01.SqlDataProvider
> 07.00.00.SqlDataProvider
> 06.00.00.SqlDataProvider
> 05.06.02.SqlDataProvider
> 05.02.00.SqlDataProvider
> 03.01.00.SqlDataProvider
> 01.00.05.SqlDataProvider
> 01.00.00.SqlDataProvider
> 

## Expected result
No references to www.dotnetnuke.com but to www.dnnsoftware.com

## Affected version

* [x] 9.2.1
* [x] 9.2.0
* [x] 9.1.1
* [x] 9.1
* [x] 9.0

## Affected browser

* [x] Chrome
* [x] Firefox
* [x] Safari
* [x] Internet Explorer
* [x] Edge

**Comment by thabaum** [comment]
Dnn.Platform/Website/DesktopModules/Admin/Security/Users.ascx.cs

has refrences here as well.

**Comment by VashJuan** [comment]
I've made a LOT of changes from DotNetNuke to DNN, primarily in the Copyright Comments at the head of files, but also in licenses and some URL's. Conceivably these could break a few tests, but I don't see much else that would RELY of the old URLs.

I'll be submitting this Pull Request in a few minutes.

I did NOT change any of the SQLDataProvider files though as I don't understand how they work very well. Don't a whole chain of them run one after the other, to bring the database step by step to the present? I worry that changing something in the DNN6 to DNN7 script for instance would break things possibly for the next (DNN7 to DNN 8) script possibly. I can also give it a wack -- in a separate Pull Request -- and debate the consequences there?

**Comment by VashJuan** [comment]
I didn't note any (non-namespace) references to dotnetnuke in 
Github.com\Dnn.Platform\Website\DesktopModules\Admin\Security\Users.ascx.cs

**Comment by VashJuan** [comment]
It seems files like 
Installwizard.aspx.fr-FR.resx
Installwizard.aspx.es-ES.resx
Installwizard.aspx.de-DE.resx
are not in the source tree, but perhaps generated by the build?

I did modify Installwizard.aspx.resx, so hopefully that fixes the other language resource files...

**Comment by VashJuan** [comment]
I just submitted a commit & pull request for these *.SqlDataProvider files,

**Comment by valadas** [comment]
@VashJuan the other languages get pulled live from a webservice I believe, so we would not have control over that right now. I did not do a full review on the status of this so leaving it open and assigning it to the 9.4.1 milestone, please update progress and let us know when ready to close.

**Comment by valadas** [comment]
I can still find a lot of references to www.dotnetnuke.com in the source code header comments, what should this be replaced for? dnncommunity.org ? Just removed ? Something else?

**Comment by david-poindexter** [comment]
Now that we have the language packs being managed more effectively, I think this issue can be closed.  Thanks, and let us know if you believe this needs to be re-opened.

**Comment by sleupold** [comment]
@david-poindexter 
there is no English Language pack - Installwizard.aspx.resx and GlobalResources.resx need to be handled by the team, according to this item

**Comment by david-poindexter** [comment]
@sleupold I am aware.  As mentioned previously in this issue, a pull request was submitted already for those.  Therefore, only the other LP changes are needed.  Thus, this issue can be closed.  Am I missing something?  If so, just let me know.  Thanks.
