### ISSUE TITLE
Password Fields are above Email and Display Name fields during registration

### ISSUE THREAD

**Issue by thabaum** [dnnsoftware/Dnn.Platform#2250]
## Description 
Password Fields are above Email and DispalyName fields during registration
## Steps to reproduce
Click Register to view fields for registering
## Current result
password fields are above display name and email addressf fields
## Expected result
Password fields at the bottom
## Affected version

* [ x] 9.2.1
* [ ] 9.2.0
* [ ] 9.1.1
* [ ] 9.1
* [ ] 9.0

## Affected browser

* [ ] Chrome
* [ ] Firefox
* [ ] Safari
* [ ] Internet Explorer
* [ ] Edge

**Comment by valadas** [comment]
I am closing this issue since it does not describe any problem, there as been no further conversation for some time and there are ways to make your own custom registration form easily.
