### ISSUE TITLE
defaultCKEditor gives no option to add text to links

### ISSUE THREAD

**Issue by Cambridgeport90** [dnnsoftware/Dnn.Platform#2252]
## Affected version

* [ ] 9.2.1
* [ ] 9.2.0
* [ ] 9.1.1
* [ ] 9.1
* [ ] 9.0

## Affected browser

* [ ] Chrome
* [ ] Firefox
* [ ] Safari
* [ ] Inter
At least in version 9.0.0, the default CKEditor provider fails to allow text to be added to links, to links look like raw URLs instead of text that fits into the rest of the article. am I missing something? has this been fixed already?

**Comment by Cambridgeport90** [comment]
I’ll do that … if it keeps up. Interestingly enough, the one who was working on this discovered that deselecting and reselecting it will bring up the option she needed. Then again, she wasn’t using the keyboard shortcut for it, so that could have contributed.

**Comment by Tychodewaard** [comment]
@valadas I think this one can be closed.
