### ISSUE TITLE
* [ ] Chrome

### ISSUE THREAD

**Issue by zzelle6767** [dnnsoftware/Dnn.Platform#2255]
## Affected version

* [ ] 9.2.1
* [ ] 9.2.0
* [ ] 9.1.1
* [ ] 9.1
* [ ] 9.0

## Affected browser

* [ ] Chrome
* [ ] Firefox
* [ ] Safari
* [ ] Internet Explorer
* [ ] Edge

**Comment by tpluscode** [comment]
Hi @zzelle6767. Please provide some details for your issue. Feel free to reopen whenever that's done
