### ISSUE TITLE
On new site creation, the country field should be above the region field in the profile

### ISSUE THREAD

**Issue by valadas** [dnnsoftware/Dnn.Platform#2259]
## Description 
Follow up on #2146 
After more testing when creating a new site, the country is still under the region field which causes the region entry to be cleared when selecting the country after the region.

## Steps to reproduce
Create a site, notice the region comes before the country

## Current result
Region is above country

## Expected result
Country should be above region

## Affected version
* [x] 9.2.1
* [x] 9.2.0
* [x] 9.1.1
* [x] 9.1
* [x] 9.0

## Affected browser
Not browser related

## Additional information
In my original pull request, I tought the new site creation would respect the order of the fields in the site template selected, apparently the profile fields order is defined in the database script.

**Comment by sleupold** [comment]
as a future enhancement, I would even want to put "Country" on top of the address fields, this would allow to use country specific address format and add a default country code for phone numbers (this would, of course, require countries to be moved to a dedicated table.

**Comment by valadas** [comment]
The linked pull request was merged and the issue references, so I am not sure why it did not close this issue. I am closing it but if it needs to stay open for some reason, just let me know.

**Comment by thabaum** [comment]
This works on new sites and the 
![image](https://user-images.githubusercontent.com/13577556/68254506-8a06c480-ffdf-11e9-9a1e-7f6c4908ce7c.png)

is turned to multi-lined I noticed but I need to go through all the prior portals to set country and bio right.

**Comment by valadas** [comment]
Yes, this will only affect new sites.
