### ISSUE TITLE
Video walkthrough to submit pull requests

### ISSUE THREAD

**Issue by valadas** [dnnsoftware/Dnn.Platform#2261]
## Description 
A video walkthrough on how to build the projects, modules, persona bar and submitting pull requesta has been made at https://www.youtube.com/playlist?list=PLIx1M8IdVvqZ0bnODGqJyxvONNPj5BzMP we need to link that in the project documentation

**Comment by thabaum** [comment]
https://github.com/dnnsoftware/Dnn.Platform

it would be nice here as well I am watching it now thank you!

**Comment by valadas** [comment]
A pull request is submitted to include that in the contributing.md file
