### ISSUE TITLE
Redirect after login

### ISSUE THREAD

**Issue by wbonekamp** [dnnsoftware/Dnn.Platform#2267]
## Description of bug
When having more than one language activated the redirect after login doesn't work

## Steps to reproduce
List the steps to reproduce the behavior:
1. Go to security;
2. Set a redirect after login page;
3. Go to language;
4. Enable a second language, for example dutch;
5. login with a registered user;
6. You wil see it doesn't redirect to the page but goes to the homepage;
7. Deactivate the second language;
8. You will see the redirect does work again

## Current result
After login with a registered user it doesn't redirect to the redirect page

## Expected result
It should redirect to the page set under security - redirect after login page

## Error log
no errors in the log

## Affected version
* [x] 9.2.1

## Affected browser
All browsers:
* [ ] Chrome
* [ ] Firefox
* [ ] Safari
* [ ] Internet Explorer
* [ ] Edge

**Comment by mitchelsellers** [comment]
@wbonekamp This issue will be included in the 9.3.0 release

**Comment by Mhtshum** [comment]
@mitchelsellers, @ohine , @sleupold
When we are on home page and using login popup, then this feature redirect us to page set in "Redirect After Login" setting. 
When logging into the application via URL in browser either {siteurl}/login or {siteurl}/login.aspx then what should be the behavior of the application, currently it is redirecting to home page

**Comment by sleupold** [comment]
@Mhtshum 
IMO, if a page is set for "Redirect after Login", the user should always be redirected to this page unless another page is specified in URL as returnURL. Note: page set in site setting "Redirect After Login" is language specific, i.e. it depends on the language used after login, which page gets displayed in ML sites.

**Comment by sleupold** [comment]
@mitchelsellers 
I agree that this should not be different whether using popup or not.
However, the page after login should be overridable via an URL parameter, there are a number of use cases for this.
