### ISSUE TITLE
DEFER and ASYNC Options for Loading JS/CSS via CDF

### ISSUE THREAD

**Issue by ohine** [dnnsoftware/Dnn.Platform#2273]
Extend the default CDF provider to enable defer and async options for both js and css assets.

**Comment by nvisionative** [comment]
I am super curious to hear how this one is coming along.  @ohine is this still going to make it into 9.3.0?

**Comment by nvisionative** [comment]
@ohine I am happy to test this as soon something is available to test.

**Comment by zyhfish** [comment]
should this only available when composite files enabled? or it can set up for each special asset?

**Comment by mitchelsellers** [comment]
@zyhfish I believe this would be done on a resource-by-resource basis, even if composite files is not enabled

**Comment by zyhfish** [comment]
thanks, @mitchelsellers , what I'm thinking is if file A and B are both render in the header, A set to defer but B is not, then enable composite files, A and B will be combined into one script tag, but how to decide whether this tag use or not use defer property?

**Comment by bdukes** [comment]
I think that scenario would need to result in two script tags in the head, one with the combined files that don't use `defer` and one with `defer`.  In practice, this may mean that scripts using `defer` and `async` don't often take part in combination.

**Comment by mikebigun** [comment]
Team, can you share your vision from where `defer/async` attributes should be taken.
As you know, `enable composite` files is a global setting and is set on a portal/host level. It is applicable to all scripts. But it is not really clear the source of the `defer/async` configuration, especially if we want to have it on resource-by-resource basis. Do we want to have kind of additional config file with a list of scripts and their defer setting value or should we somehow parse this value from the scripts itself?

CC: @daguiler

**Comment by mitchelsellers** [comment]
@mikebigun The implementation discussion would be when an individual uses the API's to add the scripts, it would be an optional configuration item to identify which method is supported.  Most likely an enum style selection of; Synchronous (Default), Async, Deferred

**Comment by sleupold** [comment]
this seems to be still a valid discussion

**Comment by valadas** [comment]
I think this now works using AttributesAsHtml right?

**Comment by david-poindexter** [comment]
@valadas I think you are correct - I seem to remember @bdukes showing how this can work.  

@bdukes would that be something that could be contributed to https://github.com/DNNCommunity/dnndocs?  

I'll go ahead and close this issue for now, but let us know if this needs to be re-opened.

**Comment by bdukes** [comment]
I've [contributed a Client Resources article](https://github.com/DNNCommunity/DNNDocs/pull/521) that includes this info.

**Comment by david-poindexter** [comment]
Awesome @bdukes - thank you sir!
