### ISSUE TITLE
Add page to the 'admin' page in multilanguage setting creates 2 pages in persona bar

### ISSUE THREAD

**Issue by trouble2** [dnnsoftware/Dnn.Platform#2283]
## Description of bug
I follow this blog entry to add a page to the persona bar:
http://www.dnnsoftware.com/community-blog/cid/155470/custom-admin-entries-in-persona-bar-the-easy-way 
On my multilanguage dnn 9.2.1 installation, and got 2 entries in the personabar

## Steps to reproduce
List the steps to reproduce the behavior:
1) make sure you have DNN 9.2.1 with multiple languages active (in my case dutch and english-us)
2) go to pages and click the "Add Multiple Pages" button
3) select "admin" as the parent page
4) create a new page with a name like 'test123'
5) check the new entries in the personabar it will show the test123 page twice, once for each language

## Current result
See here:
![image](https://user-images.githubusercontent.com/1827559/44955989-e7275780-aebc-11e8-860d-017745d7cb1f.png)

## Expected result
I would expect only 1 page to show up

## Affected version

* [?] 9.2.2
* [x] 9.2.1
* [?] 9.2
* [?] 9.1.1
* [ ] 9.1
* [ ] 9.0

**Comment by valadas** [comment]
@dnnsoftware/tag what is the feeling on this.

A. The concept of admin and host pages is legacy and was only implemented to not break upgrades and to support the fact that the DAM is still webforms. That being the case we close this issue as a wont fix.

B. We are keeping the concept of admin and host pages moving forward and keep this issue as a bug.

**Comment by sleupold** [comment]
@valadas Admin and Host pages are "neutral" (not language specific) pages by definition and should always been added once without a language code.

**Comment by bdukes** [comment]
🅱️ for me, since third party modules can and do create admin pages, in addition to the DAM

**Comment by valadas** [comment]
How to you make that B ?

**Comment by bdukes** [comment]
`:b:`

**Comment by valadas** [comment]
Nice, thanks!

**Comment by valadas** [comment]
As per @sleupold , this makes sense. Having admin and host page links in the persona bar is kinda supported but yes those should be neutral. Before the persona bar the admin and host pages worked like that too, localized pages where only supported in the actual site pages. For that reason I am closing this issue. If someone really wants to make this supported, please open a new issue indicating you would work on that.
