### ISSUE TITLE
Twitter Auth Provider - Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by vincentparrett** [dnnsoftware/Dnn.Platform#2286]
## Description of bug
Attempting to login using twitter auth

## Steps to reproduce
Configure and enable twitter auth provider

## Current result
Exception 

## Expected result
Logged in

## Error log
AbsoluteURL:/Default.aspx
DefaultDataProvider:DotNetNuke.Data.SqlDataProvider, DotNetNuke
ExceptionGUID:d82e9a70-2a21-41ca-bab3-2a1e31eb65c0
AssemblyVersion:9.2.2
PortalId:0
UserId:-1
TabId:211
RawUrl:/log-in?returnurl=%2fsupport%2fforums
Referrer:https://www.zzzzzz.com/log-in?returnurl=%2fsupport%2fforums
UserAgent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36
ExceptionHash:av2LMC1VsfaL9ibD2Sk/n2939vY=
Message:Object reference not set to an instance of an object.
StackTrace:
InnerMessage:Object reference not set to an instance of an object.
InnerStackTrace:
at DotNetNuke.Services.Authentication.OAuth.OAuthClientBase.AuthorizeV1() at DotNetNuke.Authentication.Twitter.Login.loginButton_Click(Object sender, EventArgs e) at System.Web.UI.WebControls.LinkButton.OnClick(EventArgs e) at System.Web.UI.WebControls.LinkButton.RaisePostBackEvent(String eventArgument) at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
Source:
FileName:
FileLineNumber:0
FileColumnNumber:0
Method:
Server Name: WEB01

## Affected version
* [x] 9.2.2
Using 9.2.2 RC - not tested with other versions. 

## Affected browser
* [x] Chrome
* [x] Firefox
* [?] Safari
* [?] Internet Explorer
* [x] Edge

**Comment by thabaum** [comment]
https://github.com/dnnsoftware/Dnn.Platform/issues/2257 

Should relate to the issue with the OAuth which also breaks facebook login.

It did work in DNN 8 I believe but I have not tested it in that version recently.  

I have not had any of the authentication providers working in dnn 9 yet.

**Comment by daguiler** [comment]
https://github.com/dnnsoftware/Dnn.Platform/pull/2479 fixes this issue.

**Comment by valadas** [comment]
Closing this as fixed by #2257 or should be handled with #2257, just trying to remove duplicated issues for the same problem. Please reopen or comment if my assessment is wrong on this.
