### ISSUE TITLE
After export with Content Localization site language flags disappears from pages

### ISSUE THREAD

**Issue by tpluscode** [dnnsoftware/Dnn.Platform#2294]
## Description of bug

After export with Content Localization site language flags disappears from pages

## Steps to reproduce

1. Install a site 
2. Create a page with an html module 
3. Enable 3 languages: en-US, fr-FR, it-IT 
4. Enable content localization 
5. Enable and mark all pages as translatable 
6. User can see flags on the top left and change page language using those 
7. Perform a full export of the site 
8. Create a new site# 
9. Enable 3 languages: en-US, fr-FR, it-IT 
10. Enable content localization 
11. Enable and mark all pages as translatable 
12. Import export package

## Current result

flags gone and user cannot longer see translated pages 
as workaround admin must disable and re-enabled content localization making again all pages as translatable

## Expected result

flags still works, user can see the new page added and navigate to that in different languages

## Additional context
Add any other context about the bug that may be helpful for resolution.

## Affected version

* [x] 9.2.2
* [x] 9.2.1
* [x] 9.2
* [x] 9.1.1
* [ ] 9.1
* [ ] 9.0

ESW issue DNN-20856

**Comment by valadas** [comment]
Closing since PR got merged
