### ISSUE TITLE
SMTP Server Settings per portal inoperable

### ISSUE THREAD

**Issue by RockSolidSW** [dnnsoftware/Dnn.Platform#2298]
## Description of bug
Hi Everyone, this is a carry over from an old Atlassian item that got closed (https://dnntracker.atlassian.net/browse/DNN-8768).  We are unable to get the SMTP Server Settings per portal feature (which came in DNN 7.x.x) to work properly (Admin, Site Settings, Advanced Settings, SMTP Server Settings). We have 10s of customers in one DNN instance, some of which need to utilize their own specific SMTP settings for registration notifications, etc.
All of the respective fields are in the UI and can be populated properly/saved to the PortalSettings table. We have verified that the SMTP Server Settings area in Host Settings works as it always has, however those global settings will not work for our customer base.
We have performed this additional test with no success:
Created a specific account in each customer's portal and made that user a member of the Administrators role. This account also has the same email address that we are supplying to the SMTP Server Settings area in Admin, Site Settings, Advanced Settings, SMTP Server Settings.
Set that account as the administrator in Admin, Site Settings, Advanced Settings, Security Settings.
Unfortunately the SMTP Server Settings section of Advanced Settings does not appear to be available to individual portal administrator level accounts vs. being logged into the respective portal as host level account (to try the Test SMTP Settings button while logged in as the actual portal's admin user). However, a quick new user registration test with all of these settings in place still fails while of course not logged in as any existing user.
I suspect that both the test and live smtp calls are continuing to use the host users email address from the original host level feature's code base, which is causing an authentication/relay scenario that gets properly rejected by each customer's email/smtp server.
We ideally need a fix for this immediately if at all possible. I believe this may be an issue that's lingered since the introduction of the new feature. Thanks! Todd

## Steps to reproduce
List the steps to reproduce the behavior:
1. Build a DNN instance with multiple portals/sites
2. Go into one of the portals/sites as a host level account
3. Click Settings, Servers
4. Click on the Server Settings tab
5. Click on the SMTP Server option
6. Change the SMTP Server Mode file value to the portal/site you are in (vs. Global)
7. Configure SMTP settings for that customer's specific mailbox (i.e. with their specific domain)
8. Click the Save button and then subsequently the Test SMTP Settings button

## Current result
You will notice that the SMTP test will fail because the DNN instance's superuser/host user has an email address that is part of your 1st portal site (which we tend to just leave in place as a "parent" to the instance).  The test failure ties to the SMTP credentials/settings specified for each site try to send the test email to the superuser/host account's email, or tries to relay for that domain (which is not the customer's domain).

## Expected result
The SMTP per site settings need to be reviewed and tweaked just a little bit to be truly tied to the specific portal/site, vs. referencing some pieces and parts from the original SMTP setup in DNN that was based on the host settings.

## Screenshots
If applicable, provide screenshots to help explain your problem.

## Error log
Paste the error log that is related to this issue.

## Additional context
This has been outstanding for a few years now.  We are happy to work with a developer to run through things and test if it can be addressed quicker.  This is an important feature as we have to do a workaround at the moment and send emails from specific portals/sites using a generic mailbox from our domain (which the customer's visitors are not familiar with).  Thanks!

## Affected version

* [x] 9.2.2
* [x] 9.2.1
* [x] 9.2
* [x] 9.1.1
* [x ] 9.1
* [x ] 9.0

## Affected browser

* [x ] Chrome
* [x ] Firefox
* [x ] Safari
* [x ] Internet Explorer
* [x ] Edge

**Comment by RockSolidSW** [comment]
Hi Sebastian, yep we did a fresh test on a brand new instance of 9.2.1 this morning.  We can update that instance to 9.2.2 soon, but my gut feeling is that the same issue will be there.  In addition to configuring the SMTP settings for the portal itself, we just created an admin user in the portal with an email address on the same domain as the SMTP settings, and then set that user as the Primary Administrator in Settings, Security off the persona bar.  We then cleared cache, reset the app pool, and did the SMTP test again.  It still shows that it's sending as the superuser/host account's email address.  Will try some additional tests a bit later today, but wanted to reply with a quick update.  Thanks!

**Comment by sleupold** [comment]
RSS,
which exact messages did you test?
Please note that 3rd party modules may still use host configuration, ignoring the new feature in DNN 7+

**Comment by RockSolidSW** [comment]
In the initial case we are just doing the Test SMTP Settings button in Settings, Server where you configure the SMTP either for Global or per site.  Will try a registration type change.  As far as our custom modules go, we are creating a new platform now for a new project and will probably capture the email address as a setting that we can then use with the sendmail method (and hopefully that will then use the per portal/site SMTP settings).

**Comment by bdukes** [comment]
The issue that the site-specific SMTP test comes from the host email is documented as #2227, can you test other scenarios (such as user registration) to verify that they are coming from the wrong address, as well?

**Comment by RockSolidSW** [comment]
Sure thing guys, we'll do a couple of tests outside of the Test SMTP Settings button.  Guessing that some 3rd party modules rely on the same email (pretty sure at least the DNNGo modules do), but we will try normal DNN items and our own modules.

**Comment by RockSolidSW** [comment]
Did a quick "Send Password Reset Link" test from the Users area guys, and that seems to have used the portal SMTP settings and the site default admin's email, so that's looking good so far!  We'll look at adding an option to our custom modules to capture a Send From email address setting to pass along with the sendmail method.  Is it possible that other 3rd party modules are possible just using the same call as the Test SMTP Settings button which then results in the same issue for them?

**Comment by RockSolidSW** [comment]
Hi guys, we did another quick test with one our newest custom modules this afternoon and it looks like things are working well with the standard sendmail method call.  We will avoid the Test SMTP Settings button for now, thanks!

**Comment by VashJuan** [comment]
OK to close this?

**Comment by Tychodewaard** [comment]
@valadas Seems good one to close.

**Comment by valadas** [comment]
Cool, closing
