### ISSUE TITLE
Journal error during upgrade to 9.2.2 RC

### ISSUE THREAD

**Issue by rmanjoney** [dnnsoftware/Dnn.Platform#2299]
1. Clean install of 9.1.0 on Azure Websites with new SQL Azure DB.
2. Extract 9.2.2 RC upgrade zip over site and attempt in-place upgrade
3. All succeeds, with the exception of DNN Journal, which reports "Error", but nothing seems to be in Admin Log.

Post-upgrade, checked DNN Journal module, and still reports that version 9.1.0 is installed.

**Comment by mitchelsellers** [comment]
Can you check in the /Portals/_default/logs folder for an installer log file and check it for errors?

**Comment by rmanjoney** [comment]
1)	**09/07/2018 13:03:07 [INFO] DotNetNuke.Services.Upgrade.Upgrade Start InstallPackage:D:\home\site\wwwroot\Install\Module\DNNCE_Journal_09.02.02_Install.zip**
Is the only reference to “journal” in the log file

2)	there is no text string match on the word “error” in the log file.

**Comment by sleupold** [comment]
does this issue still persist in release version of DNN 9.2.2?

**Comment by valadas** [comment]
Since there was no reply to @sleupold comment since october I am assuming this got fixed with the recent improvements with sql install scripts and closing this issue for now.
