### ISSUE TITLE
GDPR: Add Privacy Tab in Site Setings

### ISSUE THREAD

**Issue by sleupold** [dnnsoftware/Dnn.Platform#2307]
## Description of problem
GDPR and similar regulations put a lot of requirements on the shoulders of Site owners. There are a number of site settings, that might need to be reviewed to make sure the site is meeting the legislative requirements. 

## Description of solution
DNN platform should get an additional item in Site Settings "Privacy", where all aspects are described verbally (or with pictures) and external links to current documents. These texts should also contain links to the settings in the various places, making it easy for the admin to configure the site according to his needs.

## Description of alternatives considered
the alternative would be duplicating all respective settings, which would clutter the Settings UI.

## Additional context
This might be part of the GDPR initiative for DNN.

## Affected version

* [x] 9.3.0

## Affected browser

* [x] Chrome
* [x] Firefox
* [x] Safari
* [x] Internet Explorer
* [x] Edge

**Comment by valadas** [comment]
This is now implemented, closing this issue for that reason
