### ISSUE TITLE
Wrong Redirect after login for multilingual site

### ISSUE THREAD

**Issue by Mohtshum** [dnnsoftware/Dnn.Platform#2308]
## Description of bug
Wrong Redirect after login for multilingual site

## Steps to reproduce
Redirect After Login Fails (Settings ->Security ->Basic Login Setting -> Redirect After Login)
No errors reported in Event Viewer.
Two language site.
It should redirect to our Statistics page.
The Statistics page is still appears set in the "Redirect After Login;"
The Table Number appears correct in dbo.PortalSeetings->Redirect_AfterLogin

## Current result
Currently it is redirecting to home page

## Expected result
It should redirect to statistics page

## Affected version
* [x] 9.2.2
* [x] 9.2.1

**Comment by skamphuis** [comment]
I believe this is a duplicate from issue #2267 which is fixed in pullrequest #2275
