### ISSUE TITLE
EventLog: delete orphaned exeptions

### ISSUE THREAD

**Issue by sleupold** [dnnsoftware/Dnn.Platform#2310]
## Description of problem
When EventLog entries are deleted, referenced exceptions may get orphaned and remain in exceptions table, which is growing constantly and may affect size of the database as well as performance.

## Description of solution
after deleting EventLog entries in PurgeEventLog stored procedure, delete any orphaned exceptions (which shall delete the rows from exceptionevents as well.

## Description of alternatives considered
buy more database space and a faster SQL Server?

## Additional context
log tables remain small and fast.

## Affected version

* [x] 9.2.2
* [x] 9.2.1
* [x] 9.2
* [x] 9.1.1
* [x] 9.1
* [x] 9.0

## Affected browser

* [x] Chrome
* [x] Firefox
* [x] Safari
* [x] Internet Explorer
* [x] Edge

**Comment by ohine** [comment]
@donker is there any update on getting a UI for this additional table?

**Comment by sleupold** [comment]
@ohine there is no UI, the data in this table is included in vw_eventlog and displayed inside the Event Viewer module/PB extension.

**Comment by ohine** [comment]
@sleupold Thanks, I know. When the feature was first added @donker mentioned he wanted to change the UI around so we could group exceptions by number of occurrences plus a few other things. I'm wondering if this is still in the works or if we should just remove this table completely from the platform. Without being able to really make use of the data without going directly to SQL it doesn't serve much benefit.
