### ISSUE TITLE
Links to Portal Pages are being rendered as Absolute URLs when SSL is enabled.

### ISSUE THREAD

**Issue by dpuffenberger** [dnnsoftware/Dnn.Platform#2317]
## Description of bug
If the site is protected by a security certificate and accessed using the HTTPS protocol, adding links to portal pages using the default text editor inserts Absolute URLs (example: "https://www.change.me/about") rather than Relative URLs (example: "/about"). 

The function can work as expected but ONLY if the site is access using the non-secure HTTP protocol.

## Steps to reproduce
1. Protect the site with a security certificate and ensure your connected using "https."
2. Sign In then Open up a Text Editor
3. Add or select text then click on the "Add Link" button
4. Change "Link Type" to "Portal Page"
5. Select Portal Page from Dropdown 
6. Click OK.
7. View Source. The "a" tag's "href" will have an Absolute URL.

Or alternatively:
1. Protect the site with a security certificate and ensure your connected using "https."
2. Sign In then Open up a Text Editor
3. Add or select text then click on the "Add Link" button
4. Click on "Browse Server"
5. Select the "Page Link" Tab 
6. Select A Page
7. The Relative URL Radio Button will show an Absolute URL.

## Current result
Links to internal portal pages are being added with Absolute URL's when edits are made over the HTTPS protocol.

## Expected result
Links to internal portal pages being added with Relative URL's when edits are made over the HTTPS protocol.

## Screenshots
![capture6](https://user-images.githubusercontent.com/6980119/45575436-834c4980-b841-11e8-86c8-2617e9e578c1.PNG)
![capture7](https://user-images.githubusercontent.com/6980119/45575437-834c4980-b841-11e8-8bcb-f220d9d1c01f.PNG)
![capture8](https://user-images.githubusercontent.com/6980119/45575438-834c4980-b841-11e8-9d20-10872631fa22.PNG)

## Error log
Paste the error log that is related to this issue.

## Additional context
After some digging, the issue appears to be with the DNN Link Handler. Changing HTML Editor Settings does not effect the way the URLs are inserted.

## Affected version

* [x] 9.2.2
* [x] 9.2.1
* [x] 9.2
* [ ] 9.1.1
* [ ] 9.1
* [ ] 9.0

## Affected browser

* [x] Chrome
* [x] Firefox
* [x] Safari
* [x] Internet Explorer
* [x] Edge

**Comment by sleupold** [comment]
this sounds like a bug in CKEditor provider (repository: https://github.com/DNN-Connect/CKEditorProvider)

**Comment by valadas** [comment]
Correct, this needs to be handled in the other repository. Closing for that reason
