### ISSUE TITLE
DateEditControl corrupts date values by mixing local culture and culture-invariant parsing

### ISSUE THREAD

**Issue by jsboige** [dnnsoftware/Dnn.Platform#2318]
## Description of bug

I believe the issue is in the DateValue property (but maybe in other places too). It uses `Convert.ToString(Value),` which for DateTime values accounts for the local culture in the default formatting, and then tries to parse the result with `DateTime.TryParse(dteString, CultureInfo.InvariantCulture ... `, which expects an invariant format.

This is faulty in French for instance, the default format of which inverts day number and month number as compared to English/invariant: As a result, day and month numbers get inverted, and if day nb is more than 12, date value returns null and nothing is displayed.

## Steps to reproduce

List the steps to reproduce the behavior:
1. Set Portal Locale to French
2. Set up a property editor with a property mapped to a DateEditControl or equivalently a DateTimeEditControl (default for a DateTime property). I'm not sure whether the profile Editor is impacted. As it relies on strings, rather than actual datetime values, it might be unaffected. Simply instantiating a regular PropertyEditor control data bound to a Datasource consisting of an arbitrary object with a DateTime property should suffice.
3. Set the corresponding property to a date with day nb>12
4. The corresponding control should remain empty.

## Current result
Day and month were inverted, but since day nb>12, the date could not be parsed and the resulting value is empty.

## Expected result
Date value should be properly accounted for, regardless of the culture.
If the choice to use Convert.ToString() was made to account for fact the value type is unknown and thus cannot make use of culture-aware serialization, a fix could consist for instance  of testing whether the value type implements IConvertible (which Datetime does), and accordingly use the ToString method that takes an IFormatProvider argument to pass the Invariant culture parameter.

## Additional context
This is not the first time this kind of bug is reported. I understand they are hard to anticipate for English speaking developers, but they are also pretty hard to figure out for non English speakers, since usually they don't quite break the software (took me several hours to understand what was happening).
I believe it would be beneficial and not to hard to preventivally make a batch review of all uses of Culture-based string manipulation (finding global usage of those methods in VS), and make sure they remain consistent by properly using the invariant versions in some cases (which is perfectly fine for pure data manipulation) and the culsture-aware ones in other cases (e.g. for user interaction).

## Affected version

* [x] 9.2.2
* [x] 9.2.1
* [x] 9.2
* [x] 9.1.1
* [x] 9.1
* [x] 9.0

**Comment by sleupold** [comment]
this seems to be a development subject, are you able to provide a source code file demoing the issue?

**Comment by valadas** [comment]
I agree with @sleupold and there was no reply for quite some time from original submitter, closing this one to clean the backlog a bit.
