### ISSUE TITLE
Empty Sitemap generated.

### ISSUE THREAD

**Issue by vincentparrett** [dnnsoftware/Dnn.Platform#2319]
## Description of bug
The generated sitemap xml does not list any pages.

## Steps to reproduce
List the steps to reproduce the behavior:
1. Go to yoursite/sitemap.aspx

## Current result
A valid sitemap xml document is returned, however it lists no pages

## Expected result
Pages marked for indexing should be listed. 

## Error log
No errors are reported

## Affected version

* [x] 9.2.2 RC

## Affected browser

All

Now to the kicker. I too the source on github as of last week (13/9), extracted SitemapProvider to a new assembly (with a new name and some debug logging), replaced the coreSitemapProvider with mine and it made no difference, the provider did not appear to be called. Then I replaced the sitemap handler and sitemapbuilder with my own copies (no changes other than to get my handler to call my builder) and the sitemap worked as expected. I can't explain why it works, since my code is identical to what is on github, but it does.

**Comment by mitchelsellers** [comment]
Did this by chance change behavior after the site was searched?  Or after an app Restart?

**Comment by Tychodewaard** [comment]
What I just noticed:
- In the sitemap settings (DNN 9.3.2) the default value for : "Exclude URLs With a Priority Lower Than" is set on 1
- The default value (according to the help text) for a new page is 0.5

I guess this would result in an empty sitemap.
@vincentparrett If you would set the threshold on 0.4 (or 0) in the sitemap settings, do you have a sitemap after that?

**Comment by Tychodewaard** [comment]
If there is still no sitemap, the default value is 0 as logged on https://github.com/dnnsoftware/Dnn.Platform/issues/2602

**Comment by vincentparrett** [comment]
> @vincentparrett If you would set the threshold on 0.4 (or 0) in the sitemap settings, do you have a sitemap after that?

My live site is using my sitemap generate assembly, which is just a straight copy of the one on github, I made no modifications to it whatsoever, so this doesn't explain why that made it work. I'm not able to test this right now sorry and not willing to mess with the live site (still running 9.2.2). I'll check this when we upgrade DNN again (in the next few months).

**Comment by valadas** [comment]
@vincentparrett I think you might be experiencing this issue https://github.com/dnnsoftware/Dnn.AdminExperience/issues/223 which was solved in 9.3.2

**Comment by valadas** [comment]
And if that is the case, you would need to update first then save the settings you want again after the upgrade

**Comment by vincentparrett** [comment]
Thanks, I'll test with default sitemap generate when we upgrade... don't have time to do the upgrade right now.

**Comment by valadas** [comment]
Sounds good, please update this issue when when done. As long as you take a backup first to be extra careful, upgrading 9.2.2 to 9.3.2 should be a breeze.

**Comment by valadas** [comment]
@vincentparrett in order to clean the backlog I am closing this issue as not reproducible on current versions, if you can still reproduce after you got some time to try the upgrade, please open a new issue. Thanks.

**Comment by vincentparrett** [comment]
I updated my site to 9.4.1 over the weekend and this is still happening with the default sitemap generator. Switched back to my own sitemap generator and it works.

**Comment by valadas** [comment]
@vincentparrett why 9.4.1? 9.4.2 is the latest, can you reopen a new issue with steps to get to this state, as far as I know this is not reproducible with a clean 9.4.2 install or with an upgrade from pre-9.3.x to 9.4.2, if you can write clear steps with your upgrade path it would make this issue more actionable if developers have a clear way to reproduce.

**Comment by vincentparrett** [comment]
@valadas because 9.4.2 breaks our blogs (friendly url issues). 

This is a DNN install that started on DNN 4 or 5 (long time ago) and been progressively upgraded so it's quite possible there is debris in the db or web.config. In this case I upgraded from 9.2.2 to 9.4.1 directly. I am going to try and debug this locally again, just need to figure out how first (it;s been a while since I looked at this). It's just odd that my sitemap generator is direct copy of the dnn one (which I used to try and debug the issue before, but then couldn't reproduce under the debugger!).

**Comment by valadas** [comment]
9.4.3 is now out with the friendly url bug fix if you want to try it out

**Comment by vincentparrett** [comment]
Upgraded to 9.4.3 and switched to the dnn sitemap provider, same result, empty sitemap. Switched back to mine, same result, sitemap works.

**Comment by valadas** [comment]
Well, can you open an issue with steps to reproduce this situation, right now I am not sure what is happening, either there are wrong values in the database or something... Did you try re-saving the settings after the upgrade, etc...
