### ISSUE TITLE
Languages: "Users May Choose Interface Language" not working

### ISSUE THREAD

**Issue by sleupold** [dnnsoftware/Dnn.Platform#2321]
## Description of bug
In Site Settings > Languages there is a setting "Users May Choose Interface Language" which should allow admins and page editors to choose the UI language. if you enable the option, a list of flags (one for each enabled language) is displayed in the upper right corner. But clicking any of the flags has no effect on the UI language, even after reloading the page.

## Steps to reproduce
List the steps to reproduce the behavior:
1. install DNN and at least one additional language pack
2. in PersonaBar go to Settings > Site Settings > Languages.
3. enable "Users May Choose Interface Language"
4. (reload page)
5. click any flag on top right corner of PB

## Current result
none of the texts displayed in PersonaBar or Edit Bar does get switched to selected language

## Expected result
UI is switched to selected language, .

## Additional context
This feature is needed, when an admin or author, who is not capable of the content language (but the other language) to edit the content and settings. I just got exactly this request from a community member in the German User Group forum (http://www.dnn-usergroup.de/Community/Forum/tabid/72/aff/13/aft/15160/afv/topic/Default.aspx#25420)

## Affected version

* [x] 9.2.2
* [x] 9.2.1
* [x] 9.2
* [x] 9.1.1
* [x] 9.1
* [ ] 9.0

## Affected browser

* [ ] Chrome
* [ ] Firefox
* [ ] Safari
* [ ] Internet Explorer
* [x] Edge (tested, should apply to other browsers as well).

**Comment by valadas** [comment]
I am closing this one in favor of the duplicate one that had more comments and also moved it to AdminExprerience.
