### ISSUE TITLE
jQuery Migrate: jQuery.data() produces error "string.replace is not a function"

### ISSUE THREAD

**Issue by wael101** [dnnsoftware/Dnn.Platform#2322]
## Description of bug
There's an issue with jQuery Migrate v3.0.0 which was included since DNN 9.2, it does break many JS libraries including AngularJS when using $.data with an object as a second argument.

## Example error
[https://jsfiddle.net/Ltswm0v6](https://jsfiddle.net/Ltswm0v6/)

## Current result
JS error: string.replace is not a function

## Expected result
jQuery.data() should work with no issues

## Affected version
* [x] 9.2.2
* [x] 9.2.1
* [x] 9.2
* [ ] 9.1.1
* [ ] 9.1
* [ ] 9.0

## Affected browser
* [x] Chrome
* [x] Firefox
* [x] Safari
* [x] Internet Explorer
* [x] Edge

## Solution
While removing jQuery Migrate could not be an option at the moment upgrading it to [v3.0.1](https://cdnjs.cloudflare.com/ajax/libs/jquery-migrate/3.0.1/jquery-migrate.js) will fix this error, more info can be found in these reported issues:
[https://github.com/jquery/jquery-migrate/issues/267](https://github.com/jquery/jquery-migrate/issues/267)
[https://github.com/jquery/jquery-migrate/issues/198](https://github.com/jquery/jquery-migrate/issues/198)

**Comment by Tychodewaard** [comment]
I think it is what broke one of my clients older themes. The slider doesn't work anymore. Dev tools says 'Bootstrap's JavaScript requires jQuery version 1.9.1 or higher, but lower than version 3'

**Comment by david-poindexter** [comment]
It appears this has been resolved now that jQuery.Migrate is 3.2.0.

https://github.com/dnnsoftware/Dnn.Platform/blob/80710193ee730450de4389fc449d00e56e5dae93/DNN%20Platform/JavaScript%20Libraries/jQueryMigrate/jQueryMigrate.dnn#L24 

Closing this issue.
