### ISSUE TITLE
Incorrect behaviour while adding the new user to the folder permission

### ISSUE THREAD

**Issue by tpluscode** [dnnsoftware/Dnn.Platform#2325]
## Description of bug
On adding new user to the folder of site assets then
1. Default Permission Value should be "View Folder" when user is added.
2. After saving the Newly added user. That user should persist in the application.

## Steps to reproduce
1. Login as a Superuser.
2. Go to Site Assets. 
3. Click on Edit button in the folder. 
4. Go to the permission tab. 
5. Type first two letters of User. 
6. Click on Add button 
7. Click on Save Button. 
8. Go to Home Page. 
9. Again Search the permissions of same folder. 

## Current result
1. No Default Permission Value is selected for newly added user. 
2. After saving the Newly added user, again if we check the permission tab then newly added user is not present in the application. 

## Expected result
1. Default Permission Value should be "View Folder" when user is added. 
2. After saving the Newly added user. That user should persist in the application.

**Comment by valadas** [comment]
I cannot reproduce in 9.4.0 RC, @tpluscode if you can still reproduce on latest release, please open a new issue with the Dnn version, thanks.
