### ISSUE TITLE
jquery.smartmenus.js in Xcillion theme causes Jquery Migrate warnings

### ISSUE THREAD

**Issue by OllyHodgson** [dnnsoftware/Dnn.Platform#2327]
## Description of bug
The jQuery Migrate library puts loads of warnings into the devtools console (see  #2136). One of them is caused by the jquery smartmenus plugin:

`JQMIGRATE: jQuery.fn.delegate() is deprecated`

It's not immediately clear which smartmenus plugin is used, but it appears to be this one:
https://github.com/vadikom/smartmenus

I suggest we upgrade to a newer version.

## Steps to reproduce
List the steps to reproduce the behavior:
1. Create a new site using the default or blank website templates
2. Visit the site
3. Open the browser's developer tools console

## Current result
JQMigrate warnings in the devtools console, relating to jquery.smartmenus.js.

## Expected result
No JQMigrate warnings in the devtools console, relating to jquery.smartmenus.js.

## Screenshots
![image](https://user-images.githubusercontent.com/437224/45868512-d3fdfe00-bd7d-11e8-90ce-dc15e059195d.png)

## Error log
Paste the error log that is related to this issue.

## Additional context
Add any other context about the bug that may be helpful for resolution.

## Affected version

* [x] 9.2.2 (RC1)
* [x] 9.2.1
* [x] 9.2

## Affected browser
All browsers.

**Comment by valadas** [comment]
I can no longer reproduce in 9.6.2 closing this issue but feel free to comment if I am wrong.
