### ISSUE TITLE
Add overload for GetModule that takes no TabId

### ISSUE THREAD

**Issue by valadas** [dnnsoftware/Dnn.Platform#2328]
## Description of problem
DotNetNuke.Entities.Modules.ModuleController.GetModule currently requires ModuleId, TabId and IgnoreCache. But TabId can be replaced by Null to return the first found instance instead of a specific one.

When replacing deprecated API calls in old modules, it is not obvious for developers to know that TabId can be a null.

## Description of solution
I suggest adding an overload method without TabId with a comment on the side effects of using that overload (it returns the first found instance instead of a specific one) so TabId, TabModuleId and ModuleOrder will be of the first found one.

## Description of alternatives considered
None, still works fine providing Null.NullInteger to the exiting method, just makes it more obvious for developers.

## Affected version

* [?] 9.2.2
* [x] 9.2.1
* [x] 9.2
* [x] 9.1.1
* [x] 9.1
* [x] 9.0
* [x] 8.x.x

## Affected browser
Not browser related

**Comment by sleupold** [comment]
this doesn't require any change in a stored procedure, right?

**Comment by mitchelsellers** [comment]
@sleupold Correct, this is a simple API structure change that would not require changes at the DB Layer

**Comment by sleupold** [comment]
@mitchelsellers thanks, I just wanted to make sure.

**Comment by valadas** [comment]
Yeah, it already supports passing null for the TabId as is. It just would make it more obvious on developers that need to use the method without having access to TabId, that it can be used that way. Basically it could be just an overload that simply calls the original method with null for the TabId. Very simple.

**Comment by valadas** [comment]
This is still on my long long todo list. But if anyone is looking for an easy PR, this would just be one additional overload.

**Comment by sleupold** [comment]
planned for DNN 10 ?

**Comment by valadas** [comment]
Yeah, not a high priority thing but would be nice when someone or me has time for it.

**Comment by sleupold** [comment]
still on the list for DNN10

**Comment by valadas** [comment]
Looks like this was done somehow after this issue was created.
