### ISSUE TITLE
"# / hash" in Browser URL Blocks Edit/Close mode of Pages

### ISSUE THREAD

**Issue by tpluscode** [dnnsoftware/Dnn.Platform#2330]
## Description of bug

If you have 7 different modules in one page and you want users to visit a URL where to point to the last one of the page or the one in the middle instead of scrolling down, so they use `#` then the div ID of the dedicated module (explained in the video) but the problem is that if you have `#` in your URL, then you won't be able to close or open the edit mode of the page

Video link: https://www.useloom.com/share/384b102106fc4cb799299d37572cca6f 

Workaround for now: Manual refresh of browser (if there are changes and the appropriate action is taken, the changes are saved)

## Steps to reproduce

1.	As an Admin user, go to a page and append “#sectionId” to the url 
2.	Click on the pencil icon in the Admin bar to enter edit mode 
3.	Try to close edit mode by clicking on a button (i.e. Close)

## Current behavior

Edit mode does not close 

## Expected behavior

Edit mode is closed

**Comment by OllyHodgson** [comment]
Appears to be a duplicate of https://github.com/dnnsoftware/Dnn.AdminExperience/issues/56

**Comment by tpluscode** [comment]
Indeed @OllyHodgson. Closing this one
