### ISSUE TITLE
Add User  - username validation problem

### ISSUE THREAD

**Issue by wbonekamp** [dnnsoftware/Dnn.Platform#2334]
## Description of bug
When creating a username with less than 5 characters the validation message:
"The username specified is invalid. Please specify a valid username"

Looks like a good validation rule. 

But It's a problem when you upgraded from an older version and you already have users with username names that have less than 5 characters, You can't update these users anymore.

## Steps to reproduce
List the steps to reproduce the behavior:
1. Go to 'Manage'- 'Users';
2. Click on 'Account Settings" of a user with a username less than 5 characters;
3. Click "Save".

## Current result
Validation message: "The username specified is invalid. Please specify a valid username"

## Expected result
There should be no validation on "old" users that have a username of less than 5 characters.

There should be a setting to enable/disable this validation.

Length of the minimal required characters for username should be a setting.

## Screenshots

![image](https://user-images.githubusercontent.com/7567981/45948078-ecc51880-bff6-11e8-80e1-08fbee6b6858.png)

## Affected version
* [x] 9.2.2
* [x] 9.2.1
* [x] 9.2

## Affected browser

* [x ] Chrome
* [x ] Firefox
* [ x] Safari
* [ x] Internet Explorer
* [x ] Edge

**Comment by allanedk** [comment]
I agree that the minimum length should be a setting and not hardcoded to a specific value! Just realized that a hardcoded minimum length was introduced in 9.2 after researching error messages in the event log ("The username specified is invalid...").
