### ISSUE TITLE
Member Directory

### ISSUE THREAD

**Issue by dkeister1961** [dnnsoftware/Dnn.Platform#2350]
Have to roles setup one for members and on for associate members.
create a page for member directory and a page for associate member directory.
Also added a profile for company name.
Install module on associate page, modify template to show Company Name.
Under Member Directory setting - Filter and Sorting
Filter By: Group
Associate Member
Everything seems to work fine at this point.
No Login shows company name and member name.
after login  it shows phone and email.
Just what I want 
But then I install on member page 
Under member directory settings
Filter By: Member
no login just shows member name no company name on sume members but shows on a couple of members.
after login every thing seems to be ok.
![memberdirectory1](https://user-images.githubusercontent.com/24285690/46249577-7d399980-c3f9-11e8-85e5-0ba88f0f00d2.png)
![memberdirectory2](https://user-images.githubusercontent.com/24285690/46249584-80cd2080-c3f9-11e8-88dc-d73503e0c34d.png)

Ver
 9.2.2

**Comment by valadas** [comment]
I agree with previous comment and closing this issue since there was no further comments from original submitter for some time.
