### ISSUE TITLE
Ability to specify Terms and Privacy pages just like other default pages

### ISSUE THREAD

**Issue by donker** [dnnsoftware/Dnn.Platform#2357]
## Description of problem
We can specify login, registration, 404 etc pages, but not "terms of use" or "privacy statement". It is no longer sufficient to keep these texts in resx files for sites that need to comply with GDPR. In these cases you need to have much more tailored texts. Instead of making an editor for the resource text, it's preferable to be able to manage this as an entire page.

## Description of solution
Provide two new default pages in the site settings and read that in the skin objects. If not specified the site behaves as before.

**Comment by valadas** [comment]
We also need to consider upgrades. Maybe the simplest would be to use the resx key if no page is specified, if a page is specified than use that... If we go with this approach, then explaining this in the label help text would be nice.

**Comment by valadas** [comment]
Oh, as I see the pull request, it looks it was implemented that way.

**Comment by ohine** [comment]
Closing since PR was merged.
