### ISSUE TITLE
Removal of methods marked obsolete in v11.0.0

### ISSUE THREAD

**Issue by ohine** [dnnsoftware/Dnn.Platform#2359]
## Summary
This issue is to document the removal of methods targeting the v11.0.0 release. 

[DotNetNuke.Services.Upgrade](https://github.com/dnnsoftware/Dnn.Platform/blob/development/DNN%20Platform/Library/Services/Upgrade/Upgrade.cs)
-  public static int AddPortal(XmlNode node, bool status, int indent)

**Comment by sleupold** [comment]
this is still valid
