### ISSUE TITLE
Switch UserProfile Biography field to plain text

### ISSUE THREAD

**Issue by ohine** [dnnsoftware/Dnn.Platform#2360]
## Description of problem
The current default configuration has the biography field as rich text, the security analyzer marks this as a failure. We shouldn't by default fail our own security check. 

## Description of solution
Update the configuration for clean installations and new portals to use a plain text field for the user biography profile property.

**Comment by sleupold** [comment]
IMO there is no need to switch the data type of the field, rich text is best in closed communities and displays the options of DNN. We may consider using a different editor though (e.g. inline editor instead of CKEditor)
