### ISSUE TITLE
Cookie consent

### ISSUE THREAD

**Issue by donker** [dnnsoftware/Dnn.Platform#2361]
## Description of problem
Cookie consent has become a standard in many parts of the world. Althought 3rd party solutions exist, it behooves us that DNN has support for this out of the box. It would also allow us to centralize the options for this in the admin UI.

## Description of solution
I propose to use [cookie consent from insites](https://cookieconsent.insites.com) which is quite popular and well featured.

There are 3 sets of settings that can come from separate places:

1. Configurable by admin: Learn More Link.
2. Texts that can come from resource files: Message, Dismiss Text, Deny Text, Link text
3. Layout/UI related settings. These can be taken as default but overridden by a skin designer in their skin.

## Additional context
The proposed solution uses a js file of 21 Kb and a css file of 4Kb. If not activated these would not be loaded and DNN behavior is identical to what it is now.

A skin designer can create an object in window scope called "cookieconsentoptions" and if present our code will pick it up and merge it with the admin settings and initialize the component with that. If not the default settings for the consent popup would be used. This solution allows for the maximum freedom of skin designers.

Note that this does not impede users from using a 3rd party solution.

**Comment by nvisionative** [comment]
@donker this looks like a fantastic solution to me.  Thanks for the work on this!

**Comment by sleupold** [comment]
FYI: this DNN skin object already incorporates (a previous version of) the insites script https://github.com/dnnconsulting/DnnC.CookieConsent

**Comment by donker** [comment]
Yes, and we're going to include a similar solution in the platform now.

**Comment by sleupold** [comment]
please close, this has been superceeded

**Comment by nvisionative** [comment]
@sleupold this is an open issue with PRs pending review, so it should not be closed.

**Comment by sleupold** [comment]
@nvisionative sorry, mixed it up with a previous reported issue

**Comment by ohine** [comment]
Closing as the PRs were merged. If I'm wrong, please reopen and tag v9.4.0.
