### ISSUE TITLE
Increase Role Name Length

### ISSUE THREAD

**Issue by josey-baker** [dnnsoftware/Dnn.Platform#2363]
## Description of problem
Increase the length of the Role Name field.  It is currently set to a max length of 50.

## Description of solution
Update the Roles table and make the RoleName column a nvarchar(150) or higher

## Additional context
We use Roles a lot to associate DNN users to Industries or Departments and with a length of only 50 we have to abbreviate or utilize naming conventions.

## Affected version
* [x] 9.2.2
* [x] 9.2.1
* [x] 9.2
* [x] 9.1.1
* [x] 9.1
* [x] 9.0

## Solution
We have performed this on several sites by completing the following.
Update the following SQL table:
ALTER TABLE [Roles]
ALTER COLUMN [RoleName] NVARCHAR(250) NOT NULL

Updating the RoleName parameter to a NVARCHAR(150) or higher in the following stored procedures:
[dbo].[AddRole]
[dbo].[Export_RoleIdByName]
[dbo].[GetNonExpiredUsersByRoleName]
[dbo].[GetUserRolesByUsername]
[dbo].[GetUsersByRolename]
[dbo].[UpdateRole]

Update the \DesktopModules\Admin\Dnn.PersonaBar\Modules\Dnn.Roles\scripts\bundles\roles-bundle.js file so that the MaxLength on the Name field is 150 or higher.

**Comment by sleupold** [comment]
I agree, 50 might be a bit too small, but considering nested roles in the future, we should not make them too large, which would prevent us from creating and indexing role paths.

**Comment by moorecreative** [comment]
I was going to weigh in that 50 seemed about right... certainly for the "Name" of something in the system. 100 or 150 characters would be too long to display in many of the dropdown/checkbox selection areas where you currently assign permissions.

One question I'd have is whether you are using the Description field? That would seem more applicable to a length of text that describes a role. Perhaps, instead of making the Role Name field longer, would it help to have a tooltip or similar action to display the Description?

**Comment by mitchelsellers** [comment]
Also there could be an issue with multiple roles and storage. I would be a fan if nothing more than 100 for many reasons

**Comment by sleupold** [comment]
the AD provider creates roles and might get issues with role names, as they are created as "domain\AD_RoleName", therefore it might make sense to increase length of this property (still not above 100 chars), but I wouldn't increase space for it in tables and forms.

**Comment by josey-baker** [comment]
> I agree, 50 might be a bit too small, but considering nested roles in the future, we should not make them too large, which would prevent us from creating and indexing role paths. Wouldn't 100 characters be sufficient for you as well?

100 characters would certainly help and would solve our issue in most cases.

**Comment by valadas** [comment]
I am putting this for 9.4.1, correct me if I am wrong, but I don't think this would be a breaking change right?
