### ISSUE TITLE
CKEditor file browse page throw exception

### ISSUE THREAD

**Issue by zyhfish** [dnnsoftware/Dnn.Platform#2374]
1. install platform latest build and login as host;
2. edit one of the html module on home page;
3. enter the full edit window, click the Image button, then click "Browse Server" button.

Expected Result:
the file browse page works correctly.

Actually Result:
![image](https://user-images.githubusercontent.com/3364448/46594489-0b063a80-cb06-11e8-9ef6-7ae796ade960.png)

**Comment by tpluscode** [comment]
This would have been caused by #2197 where previously the `GetFiles` method explicitly cast to the interface: https://github.com/dnnsoftware/Dnn.Platform/pull/2197/files#diff-d4ef45fd14b01c62a6bbda018f71910fL624

**Comment by daguiler** [comment]
I wasn't able to reproduce on latest 9.3.0 beta.

**Comment by valadas** [comment]
A few other people have tried and where not able to reproduce, @zyhfish if you are still able to reproduce after the 9.3.0 release, please open a new issue. Thanks.
