### ISSUE TITLE
Google Analytics does not work

### ISSUE THREAD

**Issue by tpluscode** [dnnsoftware/Dnn.Platform#2378]
## Description of bug
The new Analytics UI (#2129 / #2288) does not appear to be working correctly

## Steps to reproduce

1. Log in
1. Open connectors in PB
1. Click connect 

## Current result
The connector panel is empty.

Chrome displays error in console (See below)
Safari does not show that error until it reloads the page

## Expected result
Should show the UI

## Screenshots
<img width="935" alt="screen shot 2018-10-08 at 16 15 57" src="https://user-images.githubusercontent.com/588128/46614585-81ab3400-cb16-11e8-806e-7391c2e4b6e8.png">

## Error log
Here's what Chrome show

```
Uncaught SyntaxError: Octal literals are not allowed in strict mode.
Uncaught TypeError: Cannot read property 'init' of undefined
    at Connectors.js?cdv=54:174
    at Connectors.js?cdv=54:580
    at Object.success (sf.js?cdv=54:51)
    at i (jquery.js?cdv=54:3)
    at Object.fireWith [as resolveWith] (jquery.js?cdv=54:3)
    at A (jquery.js?cdv=54:11)
    at XMLHttpRequest.<anonymous> (jquery.js?cdv=54:11)
```

And Safari does this, right before reloading the page

```
Error: Load timeout for modules: rootPath/DesktopModules/Connectors/GoogleAnalytics/scripts/connector
http://requirejs.org/docs/errors.html#timeout
	onError (main.js:48)
	onError (require.js:549)
	checkLoaded (require.js:700)
	(anonymous function) (require.js:719)
```

## Additional context
Add any other context about the bug that may be helpful for resolution.

## Affected version

* [x] 9.3.0

## Affected browser

* [x] Chrome
* [ ] Firefox
* [x] Safari
* [ ] Internet Explorer
* [ ] Edge

**Comment by mikesmeltzer** [comment]
Oliver brought this to my attention (I built this connector) earlier today.

It's a silly fix that I will submit tomorrow to be fixed.

Thanks for recording this issue.
