### ISSUE TITLE
DAM: Size of create folder popup too small in foreign languages

### ISSUE THREAD

**Issue by sleupold** [dnnsoftware/Dnn.Platform#2383]
## Description of bug
Position of controls in "Create Folder" popup is distorted, most likely due to size of the popup window to slow in foreign languages

## Steps to reproduce
List the steps to reproduce the behavior:
1. install German language pack and activate this language for a portal
2. switch to this language and enter DAM (PB > Manage > Assets
3. Select a folder on the left right click and select "create folder"
4. see the popup
![scr_dam_createfolder de-de](https://user-images.githubusercontent.com/6377509/46693125-43427180-cc09-11e8-9bf4-244179033ea7.png)

## Current result
see above

## Expected result
properly ordered controls

## Screenshots
If applicable, provide screenshots to help explain your problem.

## Affected version

* [x] 9.2.2
* [x] 9.2.1
* [x] 9.2
* [x] 9.1.1
* [ ] 9.1
* [ ] 9.0

## Affected browser

* [ ] Chrome
* [ ] Firefox
* [ ] Safari
* [ ] Internet Explorer
* [x] Edge

**Comment by valadas** [comment]
I am closing this issue for now since we have plans to totally rebuild a new DAM. I will be working on that front and we also had this problem with french so I will make sure to have enough room in there for longer words...
