### ISSUE TITLE
Disable Sending Registration Emails still sends email to Primary Administrator

### ISSUE THREAD

**Issue by Mhtshum** [dnnsoftware/Dnn.Platform#2387]
## Description of bug
Go to Settings > Security > Member Accounts > User Registration settings > Uncheck Receive User Registration Notification. 
Set User Registration Settings to Private. 
Register a new user 

## Steps to reproduce
Go to Settings > Security > Member Accounts > User Registration settings > Uncheck Receive User Registration Notification. 
Set User Registration Settings to Private. 
Register a new user 

## Current result
Primary administrator and SuperUsers still get emails after a new user registers 

## Expected result
Primary administrators should not be receiving emails. There should be an option for superusers as well. 

## Affected version

* [x] 9.2.2
* [x] 9.2.1
* [x] 9.2
* [x] 9.1.1
* [x] 9.1
* [x] 9.0

**Comment by sleupold** [comment]
Background: option "Receive User Registration Notification" has been added (in DNN 5.x, AFAIR), to notify administrators about a new user on public or verified registration, where no notification was sent before. For private registration, there was always admin notification, because the account needs to be authorized manually.

**Comment by sleupold** [comment]
We might consider creating a specific role for User Administration, as there are organizations, where are dedicated employees to manage users, who should not gain access to site settings. However, this would be a separate enhancement request.

**Comment by sleupold** [comment]
Superusers are not site members - there are plans to improve this. 
Currently, superusers don't have a site account. You may try to make a superuser an ordinary site user, add to "administrators" role and make the user superuser again.

**Comment by valadas** [comment]
Closing this as it is expected behaviour, like the idea of being able to decide who gets those notifications too but yeah, that would be another issue.
