### ISSUE TITLE
HTML Editor Manager not loading saved settings

### ISSUE THREAD

**Issue by gcdigital** [dnnsoftware/Dnn.Platform#2395]
## Description of bug
After saving editor settings, when revisiting the HTML Editor manager in PB the settings doesn't show up

## Steps to reproduce
List the steps to reproduce the behavior:
1. Go to 'HTML Editor Manager'
2. Make some changes(e.g. select editor skins from black to moono) and save
3. After the save success notification refresh the whole page and go to "HTML Editor Manager" again
4. Changes are not made on the form(?)

## Current result
It does save the settings when I check it while editing content however if i revisit the "HTML Editor Manager" again it doesn't load up the settings on the settings form which makes confusing.

## Expected result
The form in "HTML Editor Manager" should load the saved settings

## Error log
No error shown on Event Log/Console

## Additional context
On 9.2.1 when I save settings and reload the HTML Editor Manager page again sometimes I can't get into the settings page and when editing content the editor turns black (Black skin) so not too sure if it was related with the bug #2295 before... 

## Affected version
* [x] 9.2.2

## Affected browser
I don't think it's a browser issue but I did test with the following browsers...

* [x] Chrome
* [x] Firefox
* [ ] Safari
* [ ] Internet Explorer
* [x] Edge

**Comment by cgentryls** [comment]
Hi, I can verify this is an issue. It has happened to me in 9.21 and 9.2.2. Thanks for reporting this issue! I would also request that it be fixed. Thanks, Craig

**Comment by gcdigital** [comment]
Tested on 9.3.0 RC0/RC1 looked like it has been fixed.
