### ISSUE TITLE
Page type of URL does not open link in new window when specified to

### ISSUE THREAD

**Issue by pjones235** [dnnsoftware/Dnn.Platform#2397]
## Description of bug
When creating a page, if you select a Page Type of URL, provide an external URL, and then tick "Open Link in New Window", the page will not open in a new window.

## Steps to reproduce
List the steps to reproduce the behavior:
1. Go to Pages
2. Click on Add Page
3. Select URL for Page Type
4. Enter an external URL
5. Turn on the switch for Open Link in New Window
6. Save the new page

## Current result
The page is not opening in a new window

## Expected result
I expect it would apply a target attribute to the menu item for the page, with a value of "_blank".

## Error log
No errors are generated for this issue.

## Additional context
This feature worked in 9.1.1, but upon installing 9.2 it no longer works.

## Affected version

* [x] 9.2
* [ ] 9.1.1
* [ ] 9.1
* [ ] 9.0

## Affected browser

* [x] Chrome
* [x] Safari
* [x] Firefox
* [x] Internet Explorer
* [x] Edge

**Comment by cklenk** [comment]
We are experiencing this same issue. Thank you!

**Comment by pjones235** [comment]
Is anybody able to look into this?

**Comment by ohine** [comment]
Testing under the current development version (v09.03.00.51), this appears to work correctly. The rendered HTML is as follows. 

```
<li class="menuItem ">
   <a href="https://news.google.com/" target="_blank"><span>Test New Window</span> </a>
</li>
```

It could be an issue with the skin or custom menu.

**Comment by pjones235** [comment]
Is there something different with the menu in 9.2 than in 9.1 and 9.3?

Nothing in the skin would prevent it from adding the target attribute.

**Comment by bdukes** [comment]
Most themes include their own menu template, and that template may or may not include support for the `target` attribute

**Comment by valadas** [comment]
I was unable to reproduce on Dnn 9.2.2 and 9.3.0.33
@pjones235 and @cklenk are you guys using the default skin or another one? Can you share a link to where we can see that?
