### ISSUE TITLE
Possible to send email via SMTP implicit SSL? 

### ISSUE THREAD

**Issue by ExperimentalKat** [dnnsoftware/Dnn.Platform#2398]
I am using DNN v7.3.3. I've tried successfully the following server and port combinations to send emails:

smtp.sendgrid.net:587
smtp.sendgrid.net:25 (or without port)

It looks like using "colon" between server and port works for me. 

However, it did not work when I point to port 465. Sorry if I didn't explain myself well about the implicit SSL. Referring to MSDN, it seems that the SmtpClient class from System.Net.Mail only supports the SMTP Service Extension for Secure SMTP over Transport Layer Security as defined in RFC 3207.

Comparatively, an alternate connection method is where an SSL session is established up front before any protocol commands are sent. This connection method is sometimes called SMTP/SSL, SMTP over SSL, or SMTPS and by default uses port 465. This alternate connection method using SSL is not currently supported. (referring this alternate connection as implicit SSL)

Here is a link I found on MSDN with more details:

https://docs.microsoft.com/en-us/dotnet/api/system.net.mail.smtpclient.enablessl?view=netframework-4.7.2

Is it possible to use the alternate connection (implicit SSL) in DNN? 
Here is a post on DNN forum https://www.dnnsoftware.com/forums/forumid/108/threadid/543567/scope/posts

**Comment by valadas** [comment]
@dnnsoftware/tag is there anybody interested in adding the feature ?

**Comment by mitchelsellers** [comment]
As we continue to work towards .NET Core compatibility and managing the footprint of DNN, we need to support the features/functions that are supported by the underlying .NET Architecture.  If a community member wants to try and address this via a PR it will be reviewed, however, the methods to do this require extensive code additions and creates an undue burden for support within the platform when other methods exist for workarounds.
