### ISSUE TITLE
Possible to see changes to security roles in Admin Log?

### ISSUE THREAD

**Issue by improwise** [dnnsoftware/Dnn.Platform#2409]
Hi,

When we did changes to security roles, or rather who belonged to them, we could not see anything about this in the Admin Log. We could also not find any disabled Log types that seemed to do this. Is it not something that exist in DNN 9.2 (free version)?

**Comment by sleupold** [comment]
not all EventLog types are listed by default. 
In my Turbo Scripts package (https://github.com/dnnwerk/dnnScript/releases) you will find file AdjustDNNEventLogTypes922.sql. You may run it from SQL console in Persona Bar and it will add log types USER_ROLE_CREATED, USER_ROLE_DELETED and USER_ROLE_UPDATED, you may configure to be logged as you like.

**Comment by improwise** [comment]
Thanks. Will look into that. But shouldn't this perhaps be part of the standard package?

**Comment by sleupold** [comment]
You may click add, select the missing type from the drop down and configure it.
I know, it is not intuitive, that's why I created my script.

**Comment by valadas** [comment]
Closing this issue since it was more of a question than something we have to change.
