### ISSUE TITLE
Release notes could do with a link to upgrade instructions

### ISSUE THREAD

**Issue by OllyHodgson** [dnnsoftware/Dnn.Platform#2412]
## Description of problem
Our [release notes](https://github.com/dnnsoftware/Dnn.Platform/releases/tag/v9.2.2) do not link to any install or upgrade instructions.

## Description of solution
Provide links to a set of simple instructions explaining how to install and upgrade DNN to the latest version.

## Description of alternatives considered
You could include a simple set of upgrade instructions in the notes?

## Additional context
One of my colleagues pointed this gap out when I sent them a link to the latest release - they had to google to find out how to upgrade their install.

## Affected version
* [x] 9.2.2

**Comment by sleupold** [comment]
I suggest using a link, which can easily been redirected.

**Comment by bdukes** [comment]
I would assume that dnn.ly is just an alias for bit.ly, which doesn't allow changing URLs after creating them.  What about just dnnsoftware.com/upgrade, which could be a page on the site that is setup as a redirect?

**Comment by OllyHodgson** [comment]
> I would assume that dnn.ly is just an alias for bit.ly

You would be correct.

> What about just dnnsoftware.com/upgrade

Could @CBPSC arrange such a thing for us?

**Comment by CBPSC** [comment]
I can definitely create a /upgrade page. Are you wanting it to redirect to the wiki/upgrading-dotnetnuke page?

**Comment by ohine** [comment]
We added these into the RC and they’ll be including going forward with each release.
