### ISSUE TITLE
Install packages don't have alphabetically file-lists on nas system

### ISSUE THREAD

**Issue by zyhfish** [dnnsoftware/Dnn.Platform#2419]
## Description
website files hosted on a some certain nas system, which will cause Directory.GetFiles not return alphabetically file-lists.

## Steps to reproduce
install the website which files hosted on a special nas system.

## Current result
the packages install order will be randomly but not in alphabetically order.

## Expected result
packages should install with in alphabetically order.

## Affected version
* [x] All Versions

**Comment by tpluscode** [comment]
An interesting edge case. I'm curious however how this is impacting us. Why is the order important?

**Comment by bdukes** [comment]
Some of the packages need to be installed in a certain order, especially for Evoq, e.g. Platform before Evoq Content, so that Evoq Content can override the HTML module and other components.  The prefix used to differentiate the types of packages maintains that order.

**Comment by tpluscode** [comment]
> The prefix used to differentiate the types of packages maintains that order.

That is pure horror. The order should be based on dependencies and not prefixes :)

**Comment by bdukes** [comment]
🙀
