### ISSUE TITLE
Password Expiration issue

### ISSUE THREAD

**Issue by sclemmons** [dnnsoftware/Dnn.Platform#2422]
When users login, they are receiving an expiration alert 5 days before the password actually expires and the system does not allow the user to enter the site. 
When a user clicks the Proceed Anyway button, the system displays an alert that the password expires on 4/1/1 and that the password was last changed on 1/1/1. 

![password-expiration-1](https://user-images.githubusercontent.com/2228142/47292972-5290ca00-d5ce-11e8-8919-53d37fce8a7a.jpg)

![password-expiration-2](https://user-images.githubusercontent.com/2228142/47293007-6f2d0200-d5ce-11e8-8626-25d71624ebfd.jpg)

**Comment by skamphuis** [comment]
@sclemmons Do you have more information on how to reproduce this? I tried it on DNN 9.2.2 and couldn't reproduce it. It worked just fine for me.

It would be really helpful if you could follow [this template](https://github.com/dnnsoftware/Dnn.Platform/issues/new?template=bug-report.md).

**Comment by valadas** [comment]
Closing this issue due to lack of response and age of last comment
