### ISSUE TITLE
Add Site Template Support

### ISSUE THREAD

**Issue by bdukes** [dnnsoftware/Dnn.Platform#2432]
## Description of problem
When the functionality for Site Import/Export (which users a SQL Lite database) was introduced, it replaced the old Site Template functionality (which uses an XML file).  However, when creating a new site, the new site is populated using the old XML template.  This leaves site admins unable to create templates to use when creating new sites.

## Description of solution
I propose that SQL Lite templates be used when creating new sites, rather than XML templates.

## Description of alternatives considered
We could also consider re-introducing the ability to create XML site templates.

## Affected version

* [x] 9.2.2
* [x] 9.2.1
* [x] 9.2
* [x] 9.1.1
* [x] 9.1
* [ ] 9.0

**Comment by sleupold** [comment]
most likely, the old export format has not been removed. However, if we re-add the UI for it, we will need to maintain both formats. This would be easy, if just the storage interfaces were different, however it looks to me that the whole process has been implemented again (in the context of the module) and we would need to maintain two independent export engines, which doesn't make sense. 
IMO we should review both export formats and engines and try to elaborate the best of both. This should be implemented as DNN API in the core and the PB module providing a User Interface for it.

**Comment by mitchelsellers** [comment]
@bdukes Do you have any idea of the time involved for this?

**Comment by bdukes** [comment]
No, I haven't looked into those APIs.  I would imagine it might take a couple of full days to re-use the site import for a new site.

**Comment by tmaler** [comment]
Ouch this is still not fixed. Its been almost a year and i desperately need it this feature.

**Comment by tmaler** [comment]
Does anyone know of a 3rd party import / export module?

**Comment by schotman** [comment]
> Does anyone know of a 3rd party import / export module?

@tmaler  This is a Request For Comments, imo there is nothing broken here, what feature are you talking about?

**Comment by tmaler** [comment]
Hi @schotman, i cannot get the site template to export in DNN 9.1.1+. I go to the Import / Export screen, select my portal from the dropdown, click export, select which pages i want to export, and click Begin Export. It creates the task but thats about it. I also go into schedule task under "Site Import/Export" and click Run Now. Nothing happens.

![Screen Shot 2019-05-06 at 2 12 28 PM](https://user-images.githubusercontent.com/583408/57245499-01e03c00-7009-11e9-889d-e3287c93f194.png)
![Screen Shot 2019-05-06 at 1 33 00 PM](https://user-images.githubusercontent.com/583408/57245507-06a4f000-7009-11e9-9208-6b7ffc1e1d85.png)

**Comment by tmaler** [comment]
i just figured out the issue. For whatever reason server name had "COMPUTERNAME" as a value. I removed it and it started to work. I apologize for posting my comments.

**Comment by schotman** [comment]
@tmaler please delete them (and upgrade to the latest version ;)  )

**Comment by donker** [comment]
I have done more research on this. The _Template_ generation code is still there but no longer called from the front end. It would probably not require a lot of work to reimplement site template generation. I'm thinking less than a day.

As to the Import/Export format: the logic is

1. more robust (it is done through a scheduled task to avoid nasty timeout for larger tasks and it is even designed to survive scheduler timeouts)
2. supports/designed for upgrades/migration tasks
3. your module's code depends less on the quirky Microsoft XML patterns (used in IPortable) and can *probably* be more terse

So the latter looks like a more future-bound approach. But @schotman is right in that it is not human editable and this was a real strength of the old templates.

For now I think these systems will live side-by-side as ripping out templates would have a huge repercussion and the import/export stuff is just an add-on to DNN. We should make sure we can export templates again. I'm going to take a stab at this.

**Comment by valadas** [comment]
Cool, I think that Import/Export and creating a template could live side by side for some time. I hate that there is a lot of duplication in the two solutions but I prefer that than breaking IPortable :)

**Comment by schotman** [comment]
@donker if you need a tester, happy to help out

**Comment by jgong2014** [comment]
Any updates?

**Comment by sleupold** [comment]
still a valid issue

**Comment by schotman** [comment]
still valid...

**Comment by valadas** [comment]
Is anyone planning on implementing this?

**Comment by thabaum** [comment]
I just successfully imported/exported a site in 9.6.  Everything worked successfully would this be ok to close then?

Is there a way to create page templates or only "Site" templates and select the pages you want to put in the template?

**Comment by valadas** [comment]
Yeah, I would say overall this is brought back now. By original design the site templates customizations would have to be in the actual export manually. I gonna go ahead and mark this done, if other people want to add some sort of UI to customize the export, please do open a new issue. As for the vocabularies I think this might be worth a new issue if you have some steps to reproduce that kinda explain what worked and what did'nt
