### ISSUE TITLE
RFC: Workflow Management UI (Not Implemented)

### ISSUE THREAD

**Issue by mikesmeltzer** [dnnsoftware/Dnn.Platform#2434]
## Description of problem
Currently, there is a Workflow API that has been in the platform since v7.4 but it does not have an API to  manage (create, read, update and delete) workflows.

Given that this API has been around for a few years, there could be people using it in there solutions today as the workflows can be added from either the API or directly into the database.

## Description of solution
1. From the Persona Bar, we should have a Persona Bar Extension that allows the CRUD of workflows to occur.

2. Prompt commands could be implemented to mange the workflows (probably should be even if the UI is created to keep feature parity)

3. The Core HTML Module uses it's own workflow implementation.  This module should be migrated to using the core workflow implementation and provided as an example to other module developers on how to use this functionality.

## Description of alternatives considered
Before investing in this work we should determine:

- Do we want to have workflows at a core level going forward?
- Is the current implementation of workflow satisfactory? If not, why not?

## Additional context
I created a sample module that implements content workflow at:  
https://github.com/mikesmeltzer/DnnWorkflowExampleModule

## Affected version

* [x] 7.4 +

## Affected browser

N/A

**Comment by OllyHodgson** [comment]
I agree it'd be great to see a UI in the Persona Bar to handle workflow. 

In addition to CRUD of workflows, it'd great to be able to manage workflow tasks there (e.g. show what workflow tasks are outstanding, etc).

Page-level workflow would also be extrememly useful, e.g. Being able to work on modifications to a page and its content over several days without publishing it.

As an aside, publishing workflow seems to be one of the things which sets Evoq apart from Platform. Hopefully ESW won't mind too much if we do this :smile:

**Comment by mitchelsellers** [comment]
This workflow is being used by a large number of people, I think it would be fantastic to build out an administration interface for this API to help it better be leveraged by the community.

**Comment by sleupold** [comment]
IMO the workflow engine, we got thrown over the fence from DNN Corp. has a couple of limitations (like not supporting workflow changes and ad hoc workflows) and I would prefer to fix these conceptual limitations first.

**Comment by nvisionative** [comment]
@mikesmeltzer great idea!  It would be awesome to have a UI to better leverage this powerful API.  Further improvement of the API should follow.  😉

**Comment by mikesmeltzer** [comment]
I think a quick option to start would be to implement the basic CRUD using prompt which will give us all of the backend logic needed to connect a Persona Bar extension to it. I can turn that work into an individual issue and work on this.  This will let us get something out of the door quicker and incrementally build up to a complete solution.

@OllyHodgson This is a good addition. Can you document what you'd like to see on such a screen? Page workflows and versioning are in the platform but require modules to implement the feature.  The challenge is that since few modules support those features you end up with a disjointed experience. A page that has versioning but only 1 of the modules out of 10 (for example) on the page support it. I think a good first step is to get content item level workflow/versioning exposed. There could be benefits in Implementing this as a prompt extension first, keeping the logic separated so it can be shared with a Persona Bar extension front-end after.

@sleupold Do you want to document the API limitations with your proposed solution? I think that is a good one to also be planned out because if there are issues then we would want to know what they are and plan for them in any type of API refactor or rebuild in future versions of DNN.

**Comment by nvisionative** [comment]
@mikesmeltzer I am happy to help with any Prompt commands needed.  I wrote several of the commands currently in the core and I have created many custom ones.

**Comment by mikesmeltzer** [comment]
@nvisionative Awesome! I haven't built any before so I'd like to take a stab at a couple too. Let's connect this week, come up with a plan and divide and conquer.

**Comment by nvisionative** [comment]
@mikesmeltzer perfect - just ping me on Slack when you want to have a planning chat.

**Comment by nvisionative** [comment]
Thanks for the meeting @mikesmeltzer - looking forward to this endeavor!

**Comment by mikesmeltzer** [comment]
Issue #2480 was created to start the initial work of creating an admin interface via Prompt for the management of the workflows

**Comment by mitchelsellers** [comment]
Given that an issue has been created with a direction of actually implementing this feature I am going to close this RFC.

**Comment by KenTombs** [comment]
The addition of workflow within DNN either as an extension or as a core feature only enhances the choice of DNN for a new compliance service.  Using what may be available now helps with the next steps for the business.

So for example, creating a series of forms that are prompted for use by a business process workflow would be most useful. 

Achieving this by linking forms together (do A, then B, pass C to D on the logic of answers) makes it inflexible long term, when wanting to rapidly adapt to a specific customer's situation.  I have attached a typical process journey as an example (BPMN2 format) from our big brother application.
[Digital Trust Journey.pdf](https://github.com/dnnsoftware/Dnn.Platform/files/3116970/Digital.Trust.Journey.pdf)

If there is someone who could give me an idea of (or a pointer to), what CRUD or IMO might offer now would be helpful? This is an area where we could contribute to getting BPMN2 into the scheme of things.

Any suggestions most helpful?
