### ISSUE TITLE
Add Module Dialog Floating Too Far Down

### ISSUE THREAD

**Issue by pjones235** [dnnsoftware/Dnn.Platform#2437]
## Description of bug
When adding a module, the Add Module Dialog is towards the bottom of a page, often times requiring users to scroll when using a standard resolution monitor (1920x1080px). This is new in version 9.2.

## Current result
Currently the Add Module Dialog is not immediately visible as users must scroll down in order to see it. Once you click to add a module, it is left floating under the last pane on the page, also requiring users to scroll to the bottom of the document in order to see it. This isn't practical for a skin that has several panes.

## Expected result
When clicking 'Add Module', I'd expect to immediately be able to see the Add Module Dialog. Similarly, when I select a module, I'd expect to see it immediately as well without having to scroll to the bottom of the page.

## Affected version

* [x] 9.2.2
* [x] 9.2.1
* [x] 9.2
* [ ] 9.1.1
* [ ] 9.1
* [ ] 9.0

## Affected browser

* [x] Chrome
* [x] Firefox
* [x] Safari
* [x] Internet Explorer
* [x] Edge

**Comment by pjones235** [comment]
Is anybody else facing this issue? I'm facing it on multiple skins/installs.

**Comment by valadas** [comment]
I think it is probably skin related, I noticed that issue on some sites have have not originally built but never saw the issue with the standard skin and in-house built skins. Some skin css or js must mess with that because of a name collision or something along those lines.

If it only happens with some third party skins, then I suggest you take a looks at the css positioning on the default skin and compare that with the skin that makes it happen and compare to spot the difference.

If it does happen on the standard skin Xcillion then I suggest duplicating the page and then start removing modules until it works fine, the last removed module would probably be the one creating the problem...

Keep us posted.

**Comment by pjones235** [comment]
I'm looking into it, but I know the math is somehow being thrown off on my custom skins. When it calculates where the dialog should appear, the dialog appears immediately under the current view regardless of how far down a page I've scrolled. In some cases, the top value is calculated to nearly 50% more than it should be. I'll look into this when I've got time.

**Comment by valadas** [comment]
@pjones235 
Can you check if your skin has something similar to:

```css
 .DnnModule{
  position:relative!important;
}
```

I just ran into a skin that was that way and it broke the positioning of that.

Or if your site is public, please give me the url and I can take a quick look...

**Comment by pjones235** [comment]
@valadas 
It doesn't seem to matter. I have the same skin on multiple portals, and it happens on some but not all. 

Also related, I found that when I have the Add Module dialog open and I scroll all the way to the bottom of the dialog, it jumps down further on the screen.

Sorry for being vague. I need to find time to look into this more.

**Comment by valadas** [comment]
Could you have on that portal some script that is not on the other ones in the site settings or the page settings or in a module header or footer

**Comment by pjones235** [comment]
There aren't any scripts interfering. I did the math, and I found that the Add Module Dialog's top value is calculated using `$(window).height()`, which is equivalent to the height of the document. Therefore, if a page is long enough to require scrolling, the dialog is loading below the middle of the screen. If I use `window.innerHeight` instead, to get the necessary top value, the dialog will load in the correct position.

This doesn't solve the floating module's location, but it's something. Thoughts?

**Comment by pjones235** [comment]
@valadas  It was the same issue with the floating module as well. `window.innerHeight` should be used as opposed to `$(window).height()` in ModuleDialog.js. My issues are resolved with this route.

**Comment by zyhfish** [comment]
probably your skin doesn't have the doctype definition, please set the doctype to html5 and then verify again: https://www.dnnsoftware.com/wiki/set-the-doctype-of-your-skin-to-xhtml

**Comment by valadas** [comment]
@zyhfish that could very well be. I had issues with that on some sites.

**Comment by pjones235** [comment]
@zyhfish Good call. Seems cumbersome to need to add that, but it does solve the problem. Thanks for the help guys.
