### ISSUE TITLE
Update obsoleted warnings for removal in v11.0.0

### ISSUE THREAD

**Issue by ohine** [dnnsoftware/Dnn.Platform#2438]
We want to continue to clean up the API, in order to remove API methods at the earliest opportunity (v11) we need to get them labeled correctly in v9.3. 

Search for "[Obsolete(" in the solution. You should find ~420 matches in the Platform solution. 

These all need to be updated to include the verbiage "scheduled removal in v11.0.0."

In additional, it would be great if each item could be added into #2359 so we can have an issue in the v11 release notes to link to which will contain all methods removed from the platform.

**Comment by skamphuis** [comment]
I did a quick regex search and replace, @ohine. See pull #2440. Does that help?

**Comment by ohine** [comment]
@skamphuis It does for sure! Thank you for handling that so quick!!

**Comment by ohine** [comment]
This was fixed with #2440. Closing issue now.
