### ISSUE TITLE
Missing UI elements

### ISSUE THREAD

**Issue by liffeyd** [dnnsoftware/Dnn.Platform#2442]
## Description of problem
The UI for Redirects after login, registration and logout are missing.

Portal Settings > Redirect_AfterLogin
Portal Settings > Redirect_AfterLogout
Portal Settings > Redirect_AfterRegistration

## Description of solution
Add options to select a page to re-direct to after login, registration and logout.

## Description of alternatives considered
In my opinion prompt is not an option to solve this problem.

## Screenshots
N/A

## Additional context
None

## Affected version

Missing in 9.1 and 9.2.2. Other versions not checked.

* [x] 9.2.2
* [x] 9.2.1
* [x] 9.2
* [x] 9.1.1
* [x] 9.1
* [x] 9.0

## Affected browser
Not applicable
* [x] Chrome
* [x] Firefox
* [ ] Safari
* [ ] Internet Explorer
* [ ] Edge

**Comment by Timo-Breumelhof** [comment]
@skamphuis

**Comment by liffeyd** [comment]
I have found the "missing" UI for Redirect after login and logout on the Security tab.

Redirect after registration remains illusive.

**Comment by liffeyd** [comment]
And redirect after registration turns up on Security > Member Accounts :)
