### ISSUE TITLE
Can't install modules via manifest DNN version 9.2.1

### ISSUE THREAD

**Issue by davidCarpinteiro** [dnnsoftware/Dnn.Platform#2445]
Hi,

Since I upgraded to DNN version 9.2.1 I'm no longer able to install custom modules via manifest.
Steps -> Extensions -> Create New Module -> Create new module from: Manifest -> Module Folder: select my module -> Resource: select the manifest.
When I click install receive an error saying "**An Unknown error has occured. Please check the admin logs for more information.**"
I check the Admin logs and nothing there, also log files nothing. Using prefix no error is captured, the only information I get is in Fiddler.

Request:
POST http://myaddress/API/PersonaBar/Extensions/CreateModule HTTP/1.1
...
{"type":2,"moduleFolder":"FEP","ownerFolder":"","addPage":false,"fileName":"FEP.dnn","moduleName":"","description":""}

Response:
HTTP/1.1 400 Bad Request
...
{"Success":false,"PackageInfo":null,"NewPageUrl":"","Error":"MissingManifest"}

Please help with this, has I'm also struggling with creating installation package in Release mode, since it doesn't compile referring that all Dnn dlls can't be found ( In debug, no problem when building)

Thanks in advance,

Regards,

David

**Comment by Marco-Envision** [comment]
Hi David, did you end up finding a resolution for this? I'm getting the same error. Many thanks.

**Comment by davidCarpinteiro** [comment]
Hi Marco,

No, unfortunately nothing so far. It's a big headache for me since the build in release mode stop working with Visual studio 2017, and this was the only option i was having for my custom modules.
So far only alternative is creating by hand using the extensions -> Create New Module in DNN and then doing a small update in SQL for the MVC modules.

Regards,

David

**Comment by Marco-Envision** [comment]
Gotcha, I found this as well, but haven't yet tried: https://www.dnnsoftware.com/forums/forumid/203/threadid/535890/scope/posts  I am also creating the module manually by adding each control.

**Comment by davidCarpinteiro** [comment]
Hi Marco,

Know that one and tried the solution at the time with success, but was for a previous version of DNN 9.0.1 and a different situation. It got solved in version 9.1.0 or 9.1.1 not sure which one.
This appears to be a new situation and another user already reported here (https://www.dnnsoftware.com/forums/forumid/200/postid/543800/scope/posts#543800) and so far no success.

Regards,

David

**Comment by davidCarpinteiro** [comment]
That is great.
Which version of DNN you have?
This issue could be a regression, solved in another version, but got back with this last one.

**Comment by davidCarpinteiro** [comment]
It also worked for me, it's the same issue since 9.0.1 but with a different message. 
In Jira there's a ticket for it, and it's a open case for more than 2 years now (https://dnntracker.atlassian.net/browse/DNN-9608).
For anyone that gets this issue the solution provided by Alex Paula (https://www.dnnsoftware.com/forums/forumid/203/threadid/535890/scope/posts) solves this problem, just with a minor change, the PersonaBar project is no longer inside the DNN source but in a different repository, DNN.AdminExperience (https://github.com/dnnsoftware/Dnn.AdminExperience).
Hopes this solves a lot of headaches.
 
Regards,

David

**Comment by valadas** [comment]
Can this issue be moved to AdminExperience please @mitchelsellers or @ohine, it should be pretty straightforward, the fix is in the link
