### ISSUE TITLE
DNN on Mono / Linux

### ISSUE THREAD

**Issue by Gaulomatic** [dnnsoftware/Dnn.Platform#2448]
Is there anyone out there who managed to get DNN started on Mono / Linux? I am just curious if that's possible by any means. I am tired of Windows and would like to preserve some legacy websites if possible. Thanks for any (non-official) tips.

**Comment by mitchelsellers** [comment]
I tried it a long time ago on Mono and wasn't successful.  I'm not aware of any recent attempts.

**Comment by mitchelsellers** [comment]
This isn't a supported feature for DNN at this time, closing this issue.  If further discussion is needed on this, we can use the Forums or StackOverflow for discussion
