### ISSUE TITLE
RFC: Improve Code Quality to Address C# 7 Feature Usage

### ISSUE THREAD

**Issue by mitchelsellers** [dnnsoftware/Dnn.Platform#2454]
## Description of the issue
Currently when building the Visual Studio solution for DNN.Platform more than 675 warnings are triggered.  These warnings are for various levels of feature usage, or lack thereof, of C# 7 language features.  

Technically, these features are syntax sugar, and do not require the usage of .NET 4.6.2, but would require that we utilize VS 2017 (Which is essentially required now.)

## Proposed Solution

The proposed solution would be to make edits to resolve these build warnings.  A single pull request for each major category of build warning to ensure ease of code review would be completed.

### Benefits of Change

By resolving these issues we would be able to limit the number of logged warnings during the compilation of the project, allowing easier focus to other potential important warnings.  Additionally, by reducing the number of build warnings it would be possible to improve the build time for the solution.

### Risk of Change

This change would require Visual Studio 2017 to compile the DNN Platform project.  It would NOT enforce any change requirements on downstream consumers, nor would it increase the .NET Framework version on any assemblies.

This risk is very minimal, and the documentation is "light" as it is today regarding developer environment.  A single reference to "minimums" for development environment is reflected here: https://www.dnnsoftware.com/docs/developers/requirements.html which notes that DNN Platform requires VS 2015, but that for Modules you can still use older or newer VS.

## Build Warning Detail

For the purposes of this discussion, we would be implementing Microsoft standards to improve code quality.  Specifically the following rules.

* IDE0018  C# Variable declaration can be inlined - Results in more readable code with out variables
* IDE0019  C# Use pattern matching - Results in streamlined code when doing as object comparisons
* IDE0044  C# Make field readonly - Helps to solidify items that are currently readonly just not flagged this way (Manual review will be needed)
* IDE0016  C# Null check can be simplified - Removes overly complex and redundant code
* IDE0017  C# Object initialization can be simplified - Prefers the object initializer process for more readable code
* IDE0028 C# Collection initialization can be simplified - Similar to the above, but for collections
* IDE1005  C# Delegate invocation can be simplified. - Simplifies code to improve readability

## Requested Timing for Change

Assuming that these changes are acceptable, a discussion of when to make this change is needed.  This is not a breaking change for other modules, installation, or deployment.  However, for any developer looking to compile the C# source for DNN.Platform it would require an update to VS 2017 if they are not already there.  (Community Build Environments and Core Contributors are already on VS 2017.)

Is this acceptable for inclusion in 9.3 or 9.4?  Or due to the change do we bump this to 10.x?  My preference is that 9.3 is acceptable.

**Comment by OllyHodgson** [comment]
> would require that we utilize VS 2017 (Which is essentially required now.)

Here's that big D word again: Documentation :smile: Where are developer requirements documented? Can you ensure updating that documentation is made part of this change / a related issue?

Otherwise, go for it!

**Comment by ohine** [comment]
I'd also like to get StyleCop or something similar configured after we clean up the warnings we currently have.

**Comment by mitchelsellers** [comment]
@ohine My long-term desire would be to drop that in as well.  These warnings are all IDE only warnings that are not part of StyleCop, it would be great to clear them before.

@OllyHodgson I'd agree, we don't have anywhere right now that we truly document what is required to build DNN.

**Comment by EPTamminga** [comment]
I support the principle that a build should be totally warming free.

**Comment by mitchelsellers** [comment]
@OllyHodgson @EPTamminga I updated the posting a bit with a question regarding the timing & version # for this change

**Comment by mtrutledge** [comment]
I think making the latest version of Visual Studio a requirement is good. Are you targeting a specific version of C# 7 or just "Latest"?  Visual Studio 2017 also has some new features for enforcing styles. I believe they can be distributed with a ".editorconfig" file in the project. The Roslyn Compiler project uses a ".editorconfig" file to enforce their styles. Here is a post talking about the built-in options with Visual Studio 2017: https://cmatskas.com/applying-consistent-code-styles-with-visual-studio-2017/ These options may be good enough where you don't actually need something as heavy-handed as StyleCop.

**Comment by mitchelsellers** [comment]
@mtrutledge Current target with this is just the base C#7 items that do not require upping the language standard from 4.5.

These recommendations right now, are all from the basic style recommendation thus the warnings, but I will work to put a file out for consistency as well.

**Comment by valadas** [comment]
Well, I agree since everything works with VS 2017 free, I see no issue with that.

**Comment by EPTamminga** [comment]
VS2017 should not be a problem. 
All warnings gone could be for V10, since it could take away valuable resources that we might need for other things in v9.x.

**Comment by kurtwilbies** [comment]
I myself prefer warning free and asp, so 9.3.

**Comment by valadas** [comment]
In my opinion, although I totally agree with fixing this, I dot not think this should be a priority when we still have a backlog larger than I like of things that are probably more important for users right now. I would push this to a future release and try to get as much bugs/enhancements into 9.3 before the code freeze instead. So I vote like @EPTamminga to push that to v10.

**Comment by mitchelsellers** [comment]
Closing this RFC and will be opening additional Issues for this

**Comment by ahoefling** [comment]
@mitchelsellers did we ever create an issue to address support C# 7.0?

**Comment by mitchelsellers** [comment]
No, but we should. It should be supported in all projects.

**Comment by ahoefling** [comment]
I'll create an issue and submit a PR today. This is something that I want to implement as part of Razor Pages
