### ISSUE TITLE
RFC: Security Analyser

### ISSUE THREAD

**Issue by valadas** [dnnsoftware/Dnn.Platform#2459]
There are currently 2 editions of the Security Analyser, one that was built in the Dnn7 era and that can be installed in Dnn 7, 8 and 9. That one "for simplicity, let's call it the old one" has it's repository at https://github.com/DNNCommunity/DNN.SecurityAnalyzer 

The new one is part of the platform and is a tab within the Security Persona Bar Module at https://github.com/dnnsoftware/Dnn.AdminExperience/tree/development/Extensions/Settings/Dnn.PersonaBar.Security 

## Issues
[ ] We cannot maintain both, so the old one needs to get a final release that mentions it is no longer valid and that users should upgrade to the latest Dnn release, see and discuss on: https://github.com/DNNCommunity/DNN.SecurityAnalyzer/pull/41
[ ] There is a know upgrade issue, read https://www.dnnsoftware.com/community-blog/cid/155438/new-release-of-dnn-security-analyzer we need to document everywhere possible how to get around that.
[ ] The old one has many open issues, some of witch may need to move to the new one, some just need closing, see https://github.com/DNNCommunity/DNN.SecurityAnalyzer/issues
[ ] When all this is done, we need to make it clear that the older one is no longer to be used on new Dnn releases and that the new one is in the Persona Bar.

### Related RFC
Lets discuss here in general (we reach more people) and discuss what is specific to the old one on this related RFC: https://github.com/DNNCommunity/DNN.SecurityAnalyzer/issues/42

**Comment by EPTamminga** [comment]
Can we make the SA more dynamic so that it gets relevant updated info online without the need for a module install/update? Similar to an anti-virus program?

**Comment by EPTamminga** [comment]
Change code of the old SA so that it does not work on v9 and displays a massage to use the PB version?

**Comment by sleupold** [comment]
AFAIK we already agreed to include a warning into SA module that DNN 9 is not supported and an upgrade is necessary, which in fact sunsets development of SA module. 
AFAIK, @valadas already took care of most issues.
IMO this RFC might be closed.

**Comment by valadas** [comment]
The main goal of this rfc is fulfilled, closing this one and improvement issues can be opened in Admin Experience if needed
