### ISSUE TITLE
DNN Uploading non allowed file types 

### ISSUE THREAD

**Issue by dasoit** [dnnsoftware/Dnn.Platform#2461]
## Summary
How can I get this file type to work .xltm

## Extended description
I went to security and more security settings and added the extension .xltm and I am still unable to upload the file. 
## Steps to reproduce (if necessary)
List the steps to reproduce the behavior:
I cleared the cache, restarted application.  Went to the server recycled application pool 
1. Go to site assets 
2. Click on  upload file icon
3. error file extension not allowed 

## Screenshots (if necessary)
![exterror](https://user-images.githubusercontent.com/28652740/48161588-e9d16f00-e2a8-11e8-8c84-920b9aaa95cd.png)

Thanks

**Comment by dasoit** [comment]
Hello I am using DNN 9.1.  I have cleared the cache, restarted the website in DNN and on the server.  I just used a comma.  When I look in the database is they are still there

[cid:image001.png@01D47817.9B569270]

Thanks

Sheila Harrell
Infrastructure Specialist 3
Office of Information Technology
DAS Applications and IT Services
614-914-4188
oit.hostingmanager@das.ohio.gov<mailto:oit.hostingmanager@das.ohio.gov>
Customer Service Center
614.644.6860  csc@ohio.gov<mailto:csc@ohio.gov>


[cid:image002.png@01D1AC62.CD5690F0]<http://das.ohio.gov/>

   How are we doing?
   Please take our brief customer
   service survey by clicking here.<https://www.surveymonkey.com/r/LCJ5M58>

**Comment by sleupold** [comment]
please do not reply including all the previous discussion, thank you

**Comment by sleupold** [comment]
I just created a blank test.xltm file, added the extension to the allowed file types list and uploaded my file without issues. Please make sure, you don't have a typo in your file type list.

**Comment by dasoit** [comment]
Good Morning,

I have not changed anything and its working now.  Even though I cleared the cache several times, restated the application several times and I recycled the application pool on the server several times this took days to work.  This is like a serious caching issue or something.  I had a few people testing this as well and we all got the same error.  Is there something anybody can point me to regarding our servers on the software we are using that can cause this.

I appreciate you all looking into this, but it just does not make sense to me that now its working and nothing has been changed.

Thanks

Sheila Harrell
Infrastructure Specialist 3
Office of Information Technology
DAS Applications and IT Services
614-914-4188
oit.hostingmanager@das.ohio.gov<mailto:oit.hostingmanager@das.ohio.gov>
Customer Service Center
614.644.6860  csc@ohio.gov<mailto:csc@ohio.gov>


[cid:image002.png@01D1AC62.CD5690F0]<http://das.ohio.gov/>

   How are we doing?
   Please take our brief customer
   service survey by clicking here.<https://www.surveymonkey.com/r/LCJ5M58>

**Comment by Tychodewaard** [comment]
@valadas this one can be closed
