### ISSUE TITLE
Encrypt Web.Config

### ISSUE THREAD

**Issue by valadas** [dnnsoftware/Dnn.Platform#2463]
This issue was originally opened by @moorecreative in the old Security Analyzer repo here https://github.com/DNNCommunity/DNN.SecurityAnalyzer/issues/6

I am moving it here to cleanup the old repository.

**Comment by moorecreative** [comment]
If anyone would like to see what it did, or how it did it, we do have it running on some older sites, I could pull up if that's helpful to learn more about what/how it worked previously... I beleive that it used standard asp.net encrypting of the web.config and mainly encrypted sections of the web.config file, not the whole thing... so connection strings, smtp settings, they were all encrypted but the rest of the text content remained manually readable/editable.

**Comment by ahoefling** [comment]
What part of the web.config are we thinking about encrypting? 

* Connection Strings? 
* Encryption keys?

I have done this in other projects and we should be able to implement a solution. My question would be what kind of encryption algorithms are we looking to use for this.

kind of related as far as web.config security. I have been working on an extension that uses tools such as Azure Key Vault to remove app settings and connection string from the web.config. Right now I am not planning to include it in the platform, but it may be useful to people looking at this thread.

https://github.com/hoeflingsoftware/dnn.keymaster

**Comment by moorecreative** [comment]
In the past, with the old Shancer Encrypt Web.Config module/dashboard control it encrypted 

*	the two spots of connection strings
*	the email smtp information

that’s changed in modern DNN’s web.config, so I’d say it should encrypt the portions that are important to obfuscate… primarily any connection strings

**Comment by ahoefling** [comment]
The question I have, should this be something we implement in the platform or is it best handled as a third party extension.

**Comment by sleupold** [comment]
IMO, encrypting connection strings and encryptionkeys would enhance security of DNN and should be included in DNN Platform
