### ISSUE TITLE
Hovering in some apps doesn't work in DNN 922

### ISSUE THREAD

**Issue by NumberCrunchy** [dnnsoftware/Dnn.Platform#2467]
Hovering in Superfish Menu (and maybe other apps too?) doesn't work properly since DNN 922.

Reason: 
Some js-files of the menu are deprecated, but also the deprecated 'jquery.hoverIntent.min.js' in the DNN core structure prevents hovering in logged in mode:

- \DesktopModules\Admin\Dnn.PersonaBar\scripts\contrib\
- \Resources\Shared\scripts\jquery\

Solution:
Please update with newer versions (1.9.0 instead of 1.5.1):
https://github.com/briancherne/jquery-hoverIntent

**Comment by sleupold** [comment]
DNN 9.2 includes a new version of jQuery, which might not be compatible with older versions of Superfish. Did you update Superfish to latest version?

**Comment by NumberCrunchy** [comment]
Yes, I did. But it solves the problem only in the logged out view.
If you are logged in, the old 'jquery.hoverIntent.min.js' prevents hovering additionally.

**Comment by sleupold** [comment]
did you check, whether there is a newer version of jquery.hoverIntent, which should be included?

**Comment by david-poindexter** [comment]
Is this still an issue?

**Comment by NumberCrunchy** [comment]
No. The Superfish menu has been working properly again since DNN 9.6.0, although 'jquery.hoverIntent.min.js' is still version 1.5.1
