### ISSUE TITLE
RFC: Support for W3C recommendations such as ActivityPub and Webmention

### ISSUE THREAD

**Issue by Cambridgeport90** [dnnsoftware/Dnn.Platform#2468]
## Description of problem
This is a suggested method to implement in order to help people get their sites across to the wider world; competing content management systems already have plugins for these standards, so DNN ought to as well. If I were skilled enough, I'd have already submitted them as pull requests, 
## Description of solution
With access to these particular protocols, sites all across the business and personal sectors could gain a lot of organic recognition, from actual, real people. 
## Description of alternatives considered
I don't see any alternatives here, other than for these to be built as custom modules. Then again, that could get interesting, for developers would have to choose which of the modules they would integrate with. 
## Screenshots
If applicable, provide screenshots to help explain your problem and/or feature.

## Additional context
ActivityPub documentation is [here](https://www.w3.org/TR/activitypub/)
## Affected version

* [x] 9.2.2
* [x] 9.2.1
* [x] 9.2
* [x] 9.1.1
* [ ] 9.1
* [ ] 9.0

## Affected browser

* [ ] Chrome
* [ ] Firefox
* [ ] Safari
* [ ] Internet Explorer
* [ ] Edge

**Comment by Accuraty** [comment]
Seems like we need to get "RFC: " added to the Title of this issue?

**Comment by Cambridgeport90** [comment]
There are lots of examples, actually. Mastodon uses it for communication, Hubzilla supports it via extensions, Wordpress supports it via plugins. I think so does Django. Nothing at all in the .NET world, though. Seems like we got forgotten in all the excitement. Not sure how simple or not would be to implement. I'm also suggesting a broader scope for this issue, as well; IndieWeb support. The indieWeb encompasses a lot of newer standards, actually. You can find their wiki [here](https://indieweb.org).

**Comment by mitchelsellers** [comment]
Looking at this solution in more detail, I don't believe we have the current resources on the core team to make this a priority, however, Pull Requests would be accepted for any solutions that implement this functionality.

**Comment by Cambridgeport90** [comment]
I plan on discussing this with some of my team members who are .NET oriented. It might have to be a whole module with the way DNN is architected, though who knows. I’ll be keeping a hazel eye out, though.
