### ISSUE TITLE
Superfish hover not functioning in later versions of DNN

### ISSUE THREAD

**Issue by ScottRJones** [dnnsoftware/Dnn.Platform#2481]
## Description of bug
The Superfish menu provider within DNN does not function properly in most recent versions of the platform. 

As outlined by the 4th and 5th posts within the following thread, we have a resolution from Manfred Makosch which Daniel Valadas has now requested that we raise as an issue so that it can be put into the main release. 

https://www.dnnsoftware.com/forums/forumid/200/threadid/543403/scope/posts

The fix is as follows:

> Replace old superfish.js and supersubs.js in your Superfish/js folder with newer ones (1.7.10) from here:
> 
> https://github.com/joeldbirch/superfish/tree/master/dist/js
> 
> If you also want the hovereffect in Edit mode after login, you must replace old versions (1.5.1) of "jquery.hoverIntent.min.js" with newer ones (1.9.0):
> - \DesktopModules\Admin\Dnn.PersonaBar\scripts\contrib\
> - \Resources\Shared\scripts\jquery\
> 
> from here: https://github.com/briancherne/jquery-hoverIntent
> 

Many Thanks

Scott Jones

**Comment by valadas** [comment]
This duplicates #2467, please follow that one as I am closing this one.
