### ISSUE TITLE
JS loading optimization

### ISSUE THREAD

**Issue by Timo-Breumelhof** [dnnsoftware/Dnn.Platform#2485]
## Description of problem
DNN loads a lot of scripts even when they are not used or needed.
Examples are jquery.min.js, jquery-migrate.min.js etc.

## Description of solution
These scripts should IMO not be loaded by default, but only on request by components that really need them (we have such a nice mechanism for that :-)
Now when you create an empty skin and are not logged in, DNN loads a lot of unneeded scripts.

## Additional context
This is an improvement to score better in online speed and optimization tests.

## Affected version

* [x] 9.2.2
* [x] 9.2.1
* [x] 9.2
* [x] 9.1.1
* [ ] 9.1
* [ ] 9.0

**Comment by Timo-Breumelhof** [comment]
Hmm, I see now that in DNN 9 when popups are switched off (through the database as there's no interface for it in the persona bar) jQuery is not loaded.

**Comment by valadas** [comment]
I guess bringing back the option to show popups or not in the UI could be easy. Any reason why that was removed? Any opinions on bringing back that switch in the site settings?

**Comment by sleupold** [comment]
is there still a need for different UI - IMO this option requires more testing and doesn't provide real benefit. I suggest deprecating it and meanwhile always return true . Additionally we need to investigate, where the setting is still use and remove the dependency.

**Comment by Timo-Breumelhof** [comment]
@valadas not sure why it was removed, but it's the first thing I do, switch off the popups.

**Comment by valadas** [comment]
Yeah, and as far as I know the only reason to load up all of jquery and all of jquery is for a very simple dialog, we use maybe 5% of that code which is riduculously simply to do in plain javascript. I might have an improvement for this comming up for Dnn 10.

**Comment by Timo-Breumelhof** [comment]
@valadas do you have an idea if "bring back pop-up setting" is logged already? :-)

**Comment by valadas** [comment]
Yes, it is logged here https://github.com/dnnsoftware/Dnn.AdminExperience/issues/434

**Comment by valadas** [comment]
Hey Stalebot, please keep this one, I have that on my long long long todo list ;)

**Comment by Timo-Breumelhof** [comment]
@valadas 90 days pass by quickly right? :-)

**Comment by valadas** [comment]
True that

**Comment by Timo-Breumelhof** [comment]
@valadas and 180 too ;-)
