### ISSUE TITLE
[NuGet] DNN 9.2.2 packages missing

### ISSUE THREAD

**Issue by kp-xcess** [dnnsoftware/Dnn.Platform#2486]
Although DNN 9.2.2 has been around for almost 2 months already, Packages for it's DLL's are still missing on NuGet. It would be great if you guys will still add them! :)

**Comment by nvisionative** [comment]
I can’t remember the details but I think @ohine has been working to get the ability to do that.

**Comment by ohine** [comment]
We didn't have Azure Devops configured to generate nuget packages at the time v9.2.2 was released. We have everything setup for the upcoming v9.3.0 release to get these published automatically. I'll have to manually generate the v9.2.2 packages and get them posted. Thanks for the reporting the issue @kp-xcess!

**Comment by kp-xcess** [comment]
No problem, thanks in advance for the quick fix!

**Comment by bbasarich** [comment]
Is this why I'm getting the error:

"NuGet Package restore failed for project DotNetNuke.Web: Unable to find version '1.9.2.7' of package 'Dnn.ClientDependency'."

**Comment by 0Petya** [comment]
@ohine any progress on this?

**Comment by mitchelsellers** [comment]
@cutzer243 @0Petya The 9.2.2 release did not include any fundamental API changes that would restrict access.  To avoid the possibility of an improperly built package by doing it manually we are skipping the release of the 9.2.2 packages.

Starting with 9.3.0 and later the packages are built by the CI processes and will be readily available for all releases.
