### ISSUE TITLE
Search results count varies on different pages

### ISSUE THREAD

**Issue by daguiler** [dnnsoftware/Dnn.Platform#2490]
## Description of bug
Search results count varies on different pages

## Steps to reproduce
1. As a Registered User, do a search that will return multi-paged results. (i.e. Total: 50 results) 
2. Then navigate to page 2 of the search results.
3. Pick anyone of the results in page 2 (for step 5)
4. Logout. 
5. Log in as an Admin/Content Owner and make the item in #3 inaccessible to registered users.
6. Logout.
7. Log back in as a Registered User. Try to search again for the same keyword.

## Current result
At page 1, Total Results will be 50. On page 2, Total results will instead be 49. On page 3, Total Results will be 50 again.

## Expected result
Search results count should not vary.

## Additional context
Related to: https://dnntracker.atlassian.net/browse/DNN-9442
Search results count should be calculated at the beginning of the search, considering the security restrictions for the user in order to avoid changes in the total result count.

## Affected version

* [x] 9.2.2
* [x] 9.2.1
* [x] 9.2
* [x] 9.1.1
* [ ] 9.1
* [ ] 9.0

**Comment by valadas** [comment]
Closing since PR got merged
