### ISSUE TITLE
DNN Upgrade Cannot Process on Azure WebApps on S1 Instance

### ISSUE THREAD

**Issue by ZenSoftware** [dnnsoftware/Dnn.Platform#2496]
## Description of bug
I see the following error when upgrading from 9.2.0 to 9.2.2.
`50% ERROR occured - Installing Library - Dnn.EditBar.UI_01.06.01_Install.zip`
My DNN site is hosted on Azure.  Though when I duplicate my site on my local machine and attempt to upgrade it, it succeeds in upgrading just fine.  It is my live site on Azure that seems to always fail when it begins to process the module Dnn.EditBar.UI_01.06.01_Install.zip when upgrading.

## Affected version

* [x] 9.2.2
* [x] 9.2

**Comment by mitchelsellers** [comment]
Are you using Azure App Service?  Or an Azure VM?

What size of Azure environment are you in?

**Comment by ZenSoftware** [comment]
I am using Azure App Service of size "Standard: 1 Small".

Do let me know if you need any other information.

**Comment by ZenSoftware** [comment]
@mitchelsellers It upgraded just fine when i scaled up to S2.  Thanks for the tip!

**Comment by mitchelsellers** [comment]
@ZenSoftware Awesome, I've updated the title of your issue, as I want to track this so we can look at the install process and optimize it more.

**Comment by valadas** [comment]
There was some improvements recently in 9.3.something and more improvements in 9.4.0 which I am 99% sure solves this issue, if you can still reproduce after testing 9.4.0, please open a new issue. Warning 9.4.0 is at this time in RC state, so be careful not to use it in production yet, you can copy the site and try it or wait for the official release and report back.
