### ISSUE TITLE
Feature Request for Evoq Content Publisher

### ISSUE THREAD

**Issue by lewiswhill** [dnnsoftware/Dnn.Platform#2502]
## Description of problem
Is your feature request related to a problem? 
There is a requirement for using the Evoq Content Publisher Module.
We currently are posting blogs (news) using SunBlog and WordPress and plan to move this to Evoq Content. We will be posting 10 or 12 post per month. Over a few years there could be hundreds of posts. 

## Description of solution
This feature request is to add a date module to the Publisher Module based on Month and Year. Display 12 month and older post would be grouped be year.

## Description of alternatives considered
A way to display hundreds of news articles in the Publisher Module

## Screenshots
See attached

## Additional context
Add any other context about the feature that may be helpful with implementation.

## Affected version
Evoq Content 9.2
* [x] 9.2.1

## Attached Screenshot
![orderbydate](https://user-images.githubusercontent.com/45609039/49473911-29b44500-f7c8-11e8-907e-21bb79c4955b.jpg)

## Affected browser 
* [x ] Chrome
* [x] Firefox
* [x ] Safari
* [x ] Internet Explorer
* [x ] Edge

**Comment by sleupold** [comment]
Please submit feature request to Evoq specific modules (which are not (Open Source) directly to support at DNN Corp. thank you.

**Comment by lewiswhill** [comment]
Thanks for your message. DNN Support directed me to post this feature request on this site?

**Comment by sleupold** [comment]
sorry, but this tracker is exclusively for issues of DNN platform (Evoq is relying on as well).
Please tell DNN support that they should take care of issues on their own private extensions, we don't have access to.

**Comment by mitchelsellers** [comment]
@ashishpd @daguiler How do you want these to be addressed?  This is an issue with the Publisher Evoq module, not anything that we have tracked here on the DNN Platform repository.

I don't want to lose sight of this for @lewiswhill

**Comment by valadas** [comment]
Well there was no reply to this from @ashishpd or @daguiler , I am closing this issue since we do not even have the code to fulfill this request even with best intentions. This being Evoq specific and not open source, there is not much we can do here. @lewiswhill I am sorry but it looks like you got directed wrong. Maybe try emailing them a link to this issue?
