### ISSUE TITLE
DNN 7.4.2 necessary to post on Github

### ISSUE THREAD

**Issue by moorecreative** [dnnsoftware/Dnn.Platform#2505]
## Summary
It appears that final(?) top version in the 7x series 7.4.2 is missing from the GitHub repository.

## Extended description
I needed the upgrade file for DNN 7.4.2 recently while away from my computer. I went searching and could not find it here in the GitHub repository. I think that we need to have it posted.

**Comment by nvisionative** [comment]
@moorecreative you will find all 7.x files [HERE](
https://github.com/dnnsoftware/Dnn.Releases.Archive.7x).  There are other archive repos for every major release.  If you find anything missing let me know and we can fill the gap.  This was a [huge effort a while back](
https://www.dnnsoftware.com/community-blog/cid/155512/dnn-archive-releases-oss-and-answering-the-cal) lto obtain them all from the CodePlex Archive and make more readily available on GitHub.

**Comment by ohine** [comment]
Should we maybe update the suggested upgrade document to include links to each archival repo?

**Comment by valadas** [comment]
I just updated all the links at https://www.dnnsoftware.com/wiki/suggested-upgrade-path , closing this issue.

**Comment by david-poindexter** [comment]
I just updated the Wiki to no longer point to the CodePlex archive, but rather the archive repos on [GitHub](https://github.com/dnnsoftware?utf8=%E2%9C%93&q=archive&type=&language=)
