### ISSUE TITLE
Allow indexing turned off by default

### ISSUE THREAD

**Issue by Tychodewaard** [dnnsoftware/Dnn.Platform#2506]
# Description of problem
Every instance of DNN I set up, I always forget to turn off 'allow indexing' for Activity feed and its children. This is not perfect for SEO.

## Description of solution
Is it possible to have the radio button for Allow indexing turned off by default, just for these pages? 

## Affected version

* [x] 9.2.2
* [x] 9.2.1
* [x] 9.2
* [x] 9.1.1
* [ ] 9.1
* [ ] 9.0

**Comment by sleupold** [comment]
you would need to modify the default website template.

**Comment by valadas** [comment]
It looks to me like this is a matter of site owner preference and it can be easily modified in the default template in a multi-site setup, etc. I am closing this issue but if there is a general feeling that the default should be changed, or if someone was about to offer a PR for this, feel free to comment.
