### ISSUE TITLE
Replace keyed hash algorithm used for exceptions with keyless hash

### ISSUE THREAD

**Issue by donker** [dnnsoftware/Dnn.Platform#2507]
## Description of bug
In 2016 DNN Corp replaced the old MD5 Hash for exceptions with HMACSHA1. But this hash is not there for security but for identification. I.e. it's used to compare two exceptions. The crypto algorithm used should be keyless or else two invocations used on the same data will produce different results (which is exactly what we don't want here). HMACSHA1 is a keyed algorithm. It should have been SHA1CryptoServiceProvider.

* [x] 9.2.2
* [x] 9.2.1
* [x] 9.2
* [x] 9.1.1
* [x] 9.1
* [x] 9.0

This comes out of RFC https://github.com/dnnsoftware/Dnn.Platform/issues/2406

**Comment by ohine** [comment]
Closing since the pull request was merged.
