### ISSUE TITLE
DNN handlers prevent incoming POST 

### ISSUE THREAD

**Issue by bt777** [dnnsoftware/Dnn.Platform#2516]
-	DNN with 2 portals ID = 0 and 1
-	Add handler SSO.ashx for SSO implementation
-	Submit POST to SSO.ashx with URL for portal 0
-	In SSO.ashx Login user to portal id=1, assuming user belongs to portal 1. Then redirect to portal 1 URL,  Request returns .DOTNETNUKE cookie to browser
-	Close browser or not – not important
-	Submit another similar POST request to SSO.ashx with URL for portal 0
Problem: 2nd  POST request is not coming to  SSO.ashx because (likely) DNN handlers redirect with GET, and request GET coming to SSO.ashx.
This request clears .DOTNETNUKE cookie, so next 3rd POST will be successful and so on.
If POST submitted to portal 1, i.e. no portals switch, everything works properly

**Comment by bdukes** [comment]
Have you tried adding `SSO.ashx` to any of the URL regex settings?  Or putting `SSO.ashx` inside a folder within `DesktopModules`?

**Comment by bt777** [comment]
Yes,
Location and URL based on … DesktopModules\SSO\Redirector.ashx
But copying to root folder makes no diffrerence

**Comment by valadas** [comment]
If I am not mistaken, the authentication cookie is valid for the authenticated portal alias. I think the proper way for this use case is to setup portal groups and then you get a single authentication domain for multiple portals. Unfortunately, there is currently no UI to manage portal groups. @SCullman has built such a module and it works in Dnn 9 too (although not integrated in the persona bar) I have that module working fine on an old site upgraded to 9.3.2. There is also an old forum post about this at https://www.dnnsoftware.com/forums/threadid/536762/scope/posts/sso-using-site-group-editor I am closing this issue and recommend discussing this special case in the new forums https://dnncommunity.org/forums if discussions end up to being a bug in the platform please open a new issue with very clear steps and/or code sample to reproduce.
