### ISSUE TITLE
Unable to logout using Persona Bar link

### ISSUE THREAD

**Issue by haseebtirur** [dnnsoftware/Dnn.Platform#2519]
## Summary
Logout is not working using the link on Persona Bar

## Extended description
Our website was upgraded from DNN 8 to DNN 9.2. Everything was working. We migrated this website to an SSL environment. Now, everything works except the 'Logout' link on Persona Bar. It shows this error in console: 
"Mixed Content: The page at 'https://tempstage.thefastpark.com/' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://tempstage.thefastpark.com/Home/ctl/Logoff'. This request has been blocked; the content must be served over HTTPS."

This same functionality is working when this website is hosted on a non-SSL server.

## Steps to reproduce (if necessary)
List the steps to reproduce the behavior:
1. Go to 'Persona Bar'
2. Click on 'Logout'
3. Scroll down to 'Developer Console'

## Affected version

* [x] 9.2.2

## Affected browser

* [x] Chrome
* [x] Firefox
* [x] Safari
* [x] Internet Explorer
* [x] Edge

**Comment by revez-dominic** [comment]
Hi @haseebtirur, I am also facing the same problem but using an earlier version of DNN (v9.0), can I ask what was your solution?
