### ISSUE TITLE
Unable to see messages or notifications count without the ability to style badges

### ISSUE THREAD

**Issue by thabaum** [dnnsoftware/Dnn.Platform#2526]
## Description of bug
Unable to see the number of items for messages and notifications in the account header area.

## Steps to reproduce
List the steps to reproduce the behavior:
1. Log into DNN CE site with an account that has messages or notifications
2. In the header area where the account skin object shows the notifications and messages icons the number of items in each category are very hard to see or make out what the number is and I do not see or know of any way to style the objects.

## Current result
Unable to clearly see the total number of messages/notifications

## Expected result
Ability to view the number of unchecked messages/notifications in a skin object.

## Affected version

* [x] 9.3.0
* [x] 9.2.2
* [x] 9.2.1
* [x] 9.2
* [x] 9.1.1
* [ ] 9.1
* [ ] 9.0

## Affected browser

* [ ] Chrome
* [ ] Firefox
* [ ] Safari
* [ ] Internet Explorer
* [ ] Edge

**Comment by valadas** [comment]
I agree, the default skin should be improved for this, anything more than 1 digit gets over the icon, the font is also a bit small:

![image](https://user-images.githubusercontent.com/6371568/62003914-43eeba80-b0ec-11e9-9071-bef1bbea3856.png)
