### ISSUE TITLE
Random Passwords could work a lot better ...

### ISSUE THREAD

**Issue by jncraig** [dnnsoftware/Dnn.Platform#2529]
## Description of problem
This describes some issues with using random passwords for registration

## Description of solution
Random Passwords

DNN has the ability to generate random passwords for user registration.

IMHO, there are two problems with this process.

1. Sometimes the random password doesn't meet the site's requirements for password complexity. This results in a failure to create the user, and a message to use a different password.  I submitted a bug report about this.

2. As most sites should be using hashed passwords, There is no way for the user to know his password, so he has to be smart enough to click the Reset Password link. DNN should be smart enough to automatically take the user to the password reset automatically. In my case, I'm using the Verified method, so DNN knows the user's email address, and should send this automatically or ... take him to the Change Password function without the requirement to specify an old password.

I'm using random passwords and verified registration.

After the user clicks the verification link in his email, he gets to a page that confirms verification.and then asks him to log in.  He doesn't know his password, so he has to be smart enough to know that he needs to get a reset password link.  So, he now has another password and link to handle.

If we are using hashed passwords, then a first login or completion of verification should just go to the reset password place.  There's no need to send an email (it was just verified), so just send the link, put a message on the screen and be done with it!  

Simplifying the process, eliminating steps, etc. makes for happy users and fewer needs for an admin to deal with a confused or unhappy user.

## Description of alternatives considered
Of course this can all be rectified by not using random passwords, but that's not the point.  The customer wants random passwords!  (So he gets them ...)

## Screenshots
If applicable, provide screenshots to help explain your problem and/or feature.

## Additional context
Add any other context about the feature that may be helpful with implementation.

## Affected version

I suspect that this relates to all versions of DNN, but I'm using 9.2.2.

* [x] 9.3.0
* [x] 9.2.2
* [x] 9.2.1
* [x] 9.2
* [x] 9.1.1
* [ ] 9.1
* [ ] 9.0

## Affected browser

Not a browser issue.

* [ ] Chrome
* [ ] Firefox
* [ ] Safari
* [ ] Internet Explorer
* [ ] Edge

**Comment by moorecreative** [comment]
I've encountered the same issue before... we've counseled the website administrators to help talk them through customer support issues when the random is unknown and they have to do the reset steps, however having DNN be smart about it would be fantastsic

**Comment by roman-yagodin** [comment]
#2528
