### ISSUE TITLE
Need function to remove, anonymize or pseudonomize deleted users (in terms of GDPR)

### ISSUE THREAD

**Issue by MaiklT** [dnnsoftware/Dnn.Platform#2540]
## Description of problem
In DNN 8 there was a function to remove all deleted and/or unauthorized users, these functions are missing.

## Description of solution
The function should come back, but in terms of GDPR it should also be possible to anonymize or pseudonomize deleted users.

Anonymize: overwite the first name, last name, email address etc. with random values.
Pseudonomize: Anonymize + provide a list to the admin with the UserId + original values that is NOT stored in the database (e.g. CSV to download by memory stream, not stored on the server).

## Description of alternatives considered
For pseudonomization it could also be possible to provide the download before anonimization, as the admin should be able to restart the process if anything goes wrong during the download.
It would also be great to have these functions available via Prompt.

## Screenshots
![usermanagement](https://user-images.githubusercontent.com/7458140/51373041-5960a780-1aff-11e9-9cda-0c27a05dcfca.png)
Function in DNN8

## Additional context
This would be a great improvement, also in terms of the GDPR.

## Affected version

* [x] 9.3.0
* [x] 9.2.2
* [x] 9.2.1
* [x] 9.2
* [x] 9.1.1
* [x] 9.1
* [x] 9.0

## Affected browser

Not a browser issue.

**Comment by ohine** [comment]
It’s in a very weird place. They moved the delete users action to the recycling bin I believe. When I’m at my desk I’ll triple check.

**Comment by MaiklT** [comment]
Thank you Oliver, I would not have expected it there... ;-)

Anyway, we should also provide the other two possibilities.

**Comment by sleupold** [comment]
For GDPR, there needs to be an option, whether to use the recycle bin or not (hard delete). At least in the second case, the option should be in User module of PB.

**Comment by MaiklT** [comment]
Sebastian, thanks for your comment. I also think so, but hard deleting might cause problems on some sites (e.g. when there is a forum etc...). Therefore, anonymization and pseudonomization should be provided as well, to give the owner of the web site the choice that fits best to his needs.

**Comment by trouble2** [comment]
I believe @donker has a solution for this in DNN 9.4, so I would say this item is obsolete now...

**Comment by MaiklT** [comment]
@trouble2 Partly. Anonymization and pseudonymization are not realized (yet) - but I think this could also be a slot for 3rd party vendors. What @donker has done for 9.4.0 is great stuff, just to take the chance to say "Thank you..."

**Comment by valadas** [comment]
Yeah, great work @donker 
I guess for this it would involve some methods in the core APIs + some UI.
As for the UI, I would have liked to have selection checkboxes in the list of users and a select all, invert selection, etc. Then a dropdown "with selected" => some actions as delete, force change password, authorize, anonymise and so on...

**Comment by valadas** [comment]
If I remember correctly this is not handled by the multipe PRs regarding GDPR, if I am wrong, feel free to reopen or comment
