### ISSUE TITLE
Layout of buttons is broken in Html Module

### ISSUE THREAD

**Issue by SCullman** [dnnsoftware/Dnn.Platform#2544]
## Description of bug
Layout of buttons is broken in Html Module

## Steps to reproduce
Edit some content with Html Editor
## Current result
![image](https://user-images.githubusercontent.com/5693190/51442068-03475c00-1cd9-11e9-8422-1ffd6f906ac5.png)

## Expected result

![image](https://user-images.githubusercontent.com/5693190/51442073-15c19580-1cd9-11e9-9ab8-ebaa3a094e84.png)

## Affected version

* [x] 9.3.0 rc0

## Affected browser

* [x ] Chrome

**Comment by valadas** [comment]
I cannot reproduce, is that with the default skin? Did you disable versioning?

**Comment by SCullman** [comment]
Stupid me, while I tested also themes before, I did setup a weird container/skin combination.
It works as expected with default skin.
