### ISSUE TITLE
css files called but missing 

### ISSUE THREAD

**Issue by worldheadquarters** [dnnsoftware/Dnn.Platform#2546]
## Description of bug
Provide a clear and concise description of what the bug is.

## Steps to reproduce
List the steps to reproduce the behavior:
1. Click the edit Icon on any page
2. Using browser developer tools - select style editor
3. Message appears indicating that the requested style sheet cannot be loaded
 (/DesktopModules/Admin/dnn.editbar/css.ExitEditMode.css?cd=51

## Current result
In the installation, the file exists, but with a length of 0.  But the whole sub folder structure for dnn.editbar is missing in both the install and source  download versions.

## Expected result
CSS file with appropriate content should exist in the folder

## Affected version

 [x] 9.2.2
## Affected browser

Not browser related

**Comment by valadas** [comment]
I cannot reproduce this issue on 9.4.0 RC, either that got fixed somehow or the installation had some issues.

@worldheadquarters some files are added during the installation of those modules and it could be normal to not see files in some folders before the site install has happened. If this is still an issue after upgrading to a current version, please open a new issue. Thanks.
