### ISSUE TITLE
SEO: Meta tag names are non-compliant

### ISSUE THREAD

**Issue by mtrutledge** [dnnsoftware/Dnn.Platform#2547]
## Description of bug
Currently in Default.aspx the name of all the meta tags are in uppercase. For example, the meta description tag is named `DESCRIPTION` instead of `description` it appears that SEO tools and google will not properly read the meta tags if they are not lowercase.

## Steps to reproduce
1. Add a description to any page
2. Inspect the element and look at the head tag of the page
3. See that all meta tags are rendered uppercase

## Expected result
The meta tag names should be lowercase
## Affected version
* [x] 9.3.0
* [x] 9.2.2
* [x] 9.2.1
* [x] 9.2
* [x] 9.1.1
* [x] 9.1
* [x] 9.0

## Affected browser
* [x] Chrome
* [x] Firefox
* [x] Safari
* [x] Internet Explorer
* [x] Edge

**Comment by EPTamminga** [comment]
I am not so sure that this is a problem. 

Google can read both HTML and XHTML-style meta tags, regardless of the code used on the page.
With the exception of verify, case is generally not important in meta tags.

**Comment by bdukes** [comment]
I think we might as well make the change and avoid the validation errors, but the [specs](https://www.w3.org/TR/2017/REC-html52-20171214/document-metadata.html#standard-metadata-names) [state](https://html.spec.whatwg.org/multipage/semantics.html#standard-metadata-names):
>Names are case-insensitive, and must be compared in an ASCII case-insensitive manner.
