### ISSUE TITLE
DNN Platform > Both the Flag icons are active when multiple languages are enable

### ISSUE THREAD

**Issue by Mhtshum** [dnnsoftware/Dnn.Platform#2553]
## Description of bug
DNN Platform > Both the Flag icons are active when multiple languages are enable

## Steps to reproduce
Login into the application 
Check the flag icons present at the top of the page 

## Current result
All flags are enabled

## Expected result
Only selected language flag should be enabled

## Screenshots
![image](https://user-images.githubusercontent.com/43787378/51728884-00af8280-209c-11e9-8e9a-e78bdc74779d.png)

## Additional context
Add the second language and user enabled the second language 

## Affected version
* [x] 9.3.0
* [x] 9.2.2
* [x] 9.2.1
* [x] 9.2
* [x] 9.1.1

**Comment by Mhtshum** [comment]
Actually its not about hiding the other flags but to just fade them, to have a difference between the selected language and available languages.

**Comment by valadas** [comment]
Oh I get it. I usually apply some sort of highlight to the active one or hide it.

**Comment by sleupold** [comment]
@valadas I agree, the current effect is frequently irritating my clients.

**Comment by Tychodewaard** [comment]
One could also say this is not core related. Whether you can actually click a language or not is already like it should. 

If you like to have a different look for the active language, this is styling in the theme. You ca verify this by adding some code in the custom css (Persona bar):

`.Language.selected {
   display: block;
    background: rgba(0, 0, 0, .6);
}`

I'm not saying this is the best look, but it shows you can manipulate the selected language.

**Comment by valadas** [comment]
For me, having it semi-transparent makes it appear like it is disabled, so I guess the functionality is fine as per @sleupold and the style is an opinion and easy to customize as @Tychodewaard points out, for these reasons, I am closing this issue.
