### ISSUE TITLE
HttpPost actions Fail Authorization when placed in a public partial class

### ISSUE THREAD

**Issue by kingjordan** [dnnsoftware/Dnn.Platform#2558]
## Description of bug
This is my first submitted issue so I hope I did it correctly.
In an attempt to clean up some very large controller files in my project, I tried to refactor the large controller.cs into numerous partial classes in different files. This way the actions maintain the same web.api endpoint URL because the class name is shared.  This worked for HttpGet actions.

**Problem**: [HttpPost] action with a [DnnAuthorize] and [ValidateAntiForgeyToken] return unauthorized if that method is defined in the "child" or secondary public partial class.  HttpGet requests verify and work correctly in partial class.

## Steps to reproduce
List the steps to reproduce the behavior:
1. Create a simple dnn web api project with a single controller in a MyAppController.cs file :
public partial class MyAppController: DnnApiController  {  add http get and http post actions}
2. create a second file MyAppController2.cs that is also a partial class:
  public partial class SignServicesController
  {

    [HttpPost]
    [ActionName("postMyAction")]
    [ValidateAntiForgeryToken]
    [DnnAuthorize]
    public IHttpActionResult postMyAction([FromBody]String stringPost)
    {
      .. do stuff and return Ok(result);
    }

## Current result
The web api will always return 401 authorization error for HttpPost in public partial class.
If all I do is copy the MyPostAction into the primary controller class, the authorization works.
The namespace and everything else matches, just the name of the file is different.

## Expected result
The HttpPost should verify the same as if in the main class file.

## Screenshots
If applicable, provide screenshots to help explain your problem.

## Error log
Paste the error log that is related to this issue.

## Additional context
This applies to users who are not Admin or Super Users.  If either of those roles are the logged in user, then the authorization works fine.  But any other role, and custom roles, will get an authorization error if trying to access a post method in a public partial class of the controller.

I was able to reproduce this issue 100 with multiple different public partial controller classes in my project.  I did not test with another project.

## Affected version

* [x] 9.2.2 only tested on 9.2.2

**Comment by valadas** [comment]
@dnnsoftware/tag is this a bug or by design ?

**Comment by mitchelsellers** [comment]
Looking at the same included there are two controllers created, not a single with a partial class. 

This is a non issue as an API will work if a true partial class is used.
