### ISSUE TITLE
Platform build fails on multi-core Visual Studio

### ISSUE THREAD

**Issue by daguiler** [dnnsoftware/Dnn.Platform#2561]
## Description of bug
DNN_Platform.sln does not build correctly from scratch on multi-core Visual Studio configurations. Multi-core computers enable Visual Studio to build solution projects in parallel, which reduces build time. Right now, when number of parallel processes is 8 or higher, build crashes.

## Steps to reproduce
1. Open Visual Studio
2. Open Tools > Options > Projects and Solutions > Build and Run
3. Set **64** as the **maximum number of parallel project builds**
4. Exit Visual Studio
5. Change to DNN_Platform.sln directory (git workspace)
6. Make sure to reset any modified files and pull latest changes from development branch
7. Run `git clean -fdx`
8. Open DNN_Platform.sln in Visual Studio
9. Build the solution (F6 or Ctrl+Shift+B)

## Current result
Solution doesn't build correctly. Many projects cannot find metadata of upstream projects.

## Expected result
Solution should build correctly and leverage multi-core configurations to reduce build time.

## Additional context
Parallel build requires project dependencies to be correctly setup. This is automatically enforced when projects reference each other, but DNN_Platform.sln often uses binary references instead of project references. In such cases, project dependencies need to be enforced at solution level.
Solution build order is not currently being enforced correctly by Visual Studio because some project GUIDs are wrong. In particular:

* There are many references to **DotNetNuke.Library** as D391550C-7107-49B2-A6AC-8627C8B06ADC, but correct GUID is 6b29aded-7b56-4484-bea5-c0e09079535b

* There are many references to **DotNetNuke.Web** as 8DA31B98-5E8E-4243-8967-D4CF7DC622CB, but correct GUID is ee1329fe-fd88-4e1a-968c-345e394ef080

Also, there is one missing dependency in the solution file, between **DotNetNuke.Tests.Urls** and **DotNetNuke.HttpModules**.

Looking in git history, these errors go back to years ago, so this must only be affecting parallel build configuration.

## Affected version
* [x] 9.3.0

**Comment by valadas** [comment]
Closing since PR got merged
