### ISSUE TITLE
RFC: Improve permissions in DNN Platform by using dynamic mapping

### ISSUE THREAD

**Issue by sleupold** [dnnsoftware/Dnn.Platform#2564]
## Description of Problem
Permission system of DNN Platform is limited in actions: for system items (pages, modules and folders) there is just view and edit (and browse for folders). In many cases, this is not sufficient for dedicated roles like Editors, Reviewers etc.

## Proposed Solution Option 1
mimic Evoq Advanced Permissions. Unfortunately, DNN Corp, implemented a couple of hard coded assignements in DNN platform (especially PersonaBar and EditBar). This might be a bit too advanced for a couple of users, having simple sites with one or a few contributors.

## Proposed Solution Option 2 (If Needed, repeat for more)
A better solution would be a dynamic mapping, where there are many granular permissions (e.g. enter module settings, module permissions, edit display options, move module, …), which are by default mapped just to the exposed permissions View and Edit, but could be kept individually or grouped in subsets. in the easiest proper implementation, this just requires an additional column for one database table (and an index) as well as adoption of a few sprocs. Ideally, this would include a UI for mapping - while still being 100% backwards compatible. PersonaBar and EditBar permissions should be aligned properly - this is just fixing bugs and improving the current system. 

## Alternatives Researched
The permission system of DNN is not very efficient, there is for sure room for improvement (including hierarchical roles with inheritance), but this would be subject for DNN.vNext

## Affected version

* [x] 9.3.0
* [x] 9.2.2
* [x] 9.2.1
* [x] 9.2
* [x] 9.1.1
* [x] 9.1
* [x] 9.0
* [x] 8.x
* [x] 7.x
* [x] 6.x
* [x] 5.x

**Comment by mitchelsellers** [comment]
@sleupold My apologies for missing this one, it came in when I was away with the birth of my daughter.

I would LOVE to see a community contribution of an enhanced permissions provider.  I know that others have implemented something similar to this in the past.  So for the purposes of this, I 100% agree that a new model would be an improvement, especially additions such as moving "Delete" to be separate permission from "Edit" as well as an "Add Module" style permission.

For consideration/implementation I would simply request that we get a new issue created that outlines the proposed specification and the changes necessary, with an analysis of any breaking changes for implementation.  Any submission would be something we could easily accept for inclusion within version 10.x slated for this fall.

And again, my apologies for not processing this sooner.
