### ISSUE TITLE
include a simple fallback skin and container

### ISSUE THREAD

**Issue by sleupold** [dnnsoftware/Dnn.Platform#2565]
## Description of Problem
DNN includes a nice default theme package, which exposes many great features of DNN 8 f. This package consists of several skins and containers. As the default theme is used as well as fallback theme, if a skin or container fails to load, it cannot be deleted. as a result, all skin and container variants are always listed, when a user has the option to apply a theme to an individual page or a container to a page or module. 

## Proposed Solution Option 1
keep the current situation and ignore complaints.

## Proposed Solution Option 2
no default skin - don't care about a site to break.

## Proposed Solution Option 3
provide a minimalistic fallback skin (just with login, logo (, menu) and content pane) and container (title and contentPane) for emergency cases. they should be named default.skin and default.container and not be listed in dropdowns.

## Approved Solution
Please see the following comment. https://github.com/dnnsoftware/Dnn.Platform/issues/2565#issuecomment-479171171

## Affected version
* [x] 9.3.0
* [x] 9.2.2
* [x] 9.2.1
* [x] 9.2
* [x] 9.1.1
* [x] 9.1
* [x] 9.0

**Comment by kurtwilbies** [comment]
Option 3. Thats the way to go.

**Comment by EPTamminga** [comment]
Nice RFC. 
My core goes to option 3.

**Comment by valadas** [comment]
I thought it was the purpose of this one https://github.com/dnnsoftware/Dnn.Platform/blob/development/Website/Portals/_default/Skins/_default/No%20Skin.ascx

**Comment by mitchelsellers** [comment]
Option 3 is a great idea

**Comment by ohine** [comment]
Option 3 for sure, however before we start to add additional skins into the system we should address the poor performance related to having multiple skins available. I’ll create an RFC which highlights the issues with the skin packages.

**Comment by ohine** [comment]
At the @dnnsoftware/approvers meeting today we all like the idea of creating a failback skin. We are switching this from an RFC to a help wanted request. 

We are looking for a new failure skin to be submitted, plus reproducible steps to trigger a failure in the main skin, and in addition a failure in the failback skin. 

This way we can test for no failures, a failure in the  main skin which triggers the failback skin to render successfully, and a failure in the failback skin which would then trigger the no skin failure.

**Comment by trouble2** [comment]
I believe in DNN 8, there used to be some entries in the hostsettings:
- DefaultPortalContainer
- DefaultPortalSkin
- DefaultAdminContainer
- DefaultAdminSkin
Which kind of worked as a fallback.

And then ofcourse if all failed there was indeed:
\Portals\_default\Skins\_default\No Skin.ascx
And
\Portals\_default\Containers\_default\No Container.ascx
Which are about as minimal as you can get....
And because of the '_' in the folder name, they could not be seen from within DNN I believe.
So perhaps they can still be used. Though they could do with some styling so they look at least a bit better...

**Comment by valadas** [comment]
I kinda agree with @trouble2 I think the fallback is already in place, I think we could just style that a bit but stay very minimal.

**Comment by sleupold** [comment]
IMO this is still an issue

**Comment by Timo-Breumelhof** [comment]
I would prefer adding a skin setting "show in PB", that would fix this and could be useful in other scenarios.

**Comment by thabaum** [comment]
took me a while to think about this.  Option 3 seems to be favorite here and I like to go with the flow but was trying to play devils advocate.

I am trying to fully understand the issue and the proposed solution given all the recent developments.   What solution would be acceptable so I can think if it is something I can work on if no one else can get around to this anytime soon.  Seems like minor changes potentially, however I may not be fully aware of what all is being asked to perform to be satisfied for a solution.

From what I understand is you can or cannot uninstall Xcillion or lets say the theme was modified and fails to load.  This theme is the only theme on your installation and you need to get it up and running again.  What happens then?

Am I correct so far?

If so then the current fallback theme files for DNN would be 
**\Portals_default\Skins_default\No Skin.ascx**
and 
**\Portals_default\Containers_default\No Container.ascx**

So are these the files that need Tuned?  And if so how, what is missing or needs adjusted to make a solution work?

**Comment by thabaum** [comment]
```
<%@ Control Language="C#" CodeBehind="~/DesktopModules/Skins/skin.cs" AutoEventWireup="false" Inherits="DotNetNuke.UI.Skins.Skin" %>
<div runat="server" id="ContentPane" />
```

Very simple skin here so anything that is needed?  I am not sure the container needs tuned as it probably is just fine.

**Comment by thabaum** [comment]
> At the @dnnsoftware/approvers meeting today we all like the idea of creating a failback skin. We are switching this from an `RFC` to a `help wanted` request.
> 
> We are looking for a new failure skin to be submitted, plus reproducible steps to trigger a failure in the main skin, and in addition a failure in the failback skin.
> 
> This way we can test for no failures, a failure in the main skin which triggers the failback skin to render successfully, and a failure in the failback skin which would then trigger the no skin failure.

So when a skin fails it needs to catch the error and then load a fallback skin which would be in these two files mentioned above?

And I like asking for more details on what are any known triggers for the failures so they can be tested.

**Comment by thabaum** [comment]
A failure in the failback skin should go to the two files above am I right?

And the primary failback skin possibly should be able to get set by an admin but use a default one or  a skin that no one sees?

I think removing all skins to see what the current failback might give some results to build on.  Other than that something would have to be done to catch the error of the skin and then send it to the next skin, then to the next skin until the page finally loads putting an error in the admin logs.

**Comment by Timo-Breumelhof** [comment]
Not sure if everybody realizes this but the "error skin" is set in dotnetnuke.config.
When you change this to a another skin you can uninstall xcillion

```
  <skinningdefaults>
      <skininfo folder="/Xcillion/" default="Inner.ascx" admindefault="Admin.ascx" />
      <containerinfo folder="/Xcillion/" default="Title_h2.ascx" admindefault="Title_h2.ascx" />
  </skinningdefaults>
```

IMO users should never edit the default skin, they should always make a copy and edit that, as the default skin could be overwritten on upgrade and all changes lost.
So IMO it's a minor issue as there are other issues in this area that are way more important TBH.

**Comment by valadas** [comment]
Editing the default skin in place is a big no no for sure, very bad practice, no core files should be edited by users since they can get ovewritten by upgrades.

I am not 100% sure about this, but I think dotnetnuke.config is only used upon installation, what allows uninstalling Xcillion is to not have it mapped to any page in the database. I might be wrong though.

**Comment by Timo-Breumelhof** [comment]
OK I'll explain how it works: https://www.youtube.com/watch?v=hwyLRXM28ds :-)

**Comment by Timo-Breumelhof** [comment]
As a reference, you can trigger a skin error by including this: 
<dnn:error runat="server"  />

(the word error can be anything else as long ad there's no reference at the top of the page)

**Comment by valadas** [comment]
Thanks for double-checking that @Timo-Breumelhof so yeah, I was wrong and this applies not only during installation. Thanks.

**Comment by Timo-Breumelhof** [comment]
Is there still a need for this?

**Comment by zyhfish** [comment]
default skin info is saved in DotNetNuke.config file under the site root folder.

**Comment by sleupold** [comment]
IMO yes

**Comment by sleupold** [comment]
still an issue
