### ISSUE TITLE
Remove branded icon logic from build process

### ISSUE THREAD

**Issue by donker** [dnnsoftware/Dnn.Platform#2566]
## Description of bug
There are 9 lines of legacy code in the packaging build process that are remnants of the commercial build process. It fiddles with the logos under Website/images/Branded and their readonly status (which is how I stumbled on this because it prevented copying).

## Critique
We should clean up DNN and its build process and remove all remnants that have no place here.

## Affected version
* [x] 9.3.0
* [x] 9.2.2
etc

**Comment by valadas** [comment]
@dnnsoftware/approvers This is merged, please close this issue.
