### ISSUE TITLE
RFC: Extension Integration with DNNstore

### ISSUE THREAD

**Issue by slaterjsharp** [dnnsoftware/Dnn.Platform#2570]
## Description of problem
The Extension module only shows extensions already installed, or built-in extensions that are included with the Dnn platform install. To look for other extensions, one must search separately on DNNstore or other locations on the Internet.

## Description of solution
Integration within the Extensions module to the DNNstore would make it easier, especially for DNN n00b's, to enhance DNN's overal functionality. Perhaps a separate button labeled "DNNStore" could list all the choices available there, including "New" and "Top Selling". Integration with DNNstore could include immediate download and install of the extension within the site.

A host, web.config or SQL-based switch to turn this option off could be desirable, to prevent more cautious organizations from cluttering their installs.

## Description of alternatives considered
At the very least a link to DNNstore in the Extensions module could be considered.

## Additional context
This idea is based on observations of other CMS, this one in particular has the initials "W" and "P". It was suggested that this be an RFC.

**Comment by VashJuan** [comment]
I like this idea, and think it makes the store more discoverable.

**Comment by andyduo** [comment]
Being able to one click install hot fixes and updates of modules from within the Extensions page would also be a great addition.

**Comment by mitchelsellers** [comment]
At this point in time I will be closing this RFC.  We do not yet have a commitment, or details, from ESW regarding the future direction of the DNN Store and how, if any, integrations would be considered.  Given that a change to the store is known, we do not want to deploy a change at this time that may no longer function after an adjustment on the DNN Store side.

Various other efforts are potentially underway in the community that could change this determination but are not yet fully verified nor able to be shared publicly.
