### ISSUE TITLE
RFC: Migrate Issue tracker

### ISSUE THREAD

**Issue by ohine** [dnnsoftware/Dnn.Platform#2571]
## Description of Problem
Currently issues are splintered across multiple repositories owned by multiple people and organizations. This wasn't an issue when ESW maintained a public tracker, since it provided a single source to research and report any issues within Dnn. However, after they migrated to an internal private tracker we made the quick and poorly thought out decision to use github for issue tracking. After utilizing github for our issues for 8 months, it's apparent that it lacks features we require as a team to operate efficiently. 

## Proposed Solution Option 1
Move back to JIRA and apply for an open source license.

## Proposed Solution Option 2
Move to Azure  DevOPS through our .net foundation sponsorship.

## Proposed Solution Option 3
Create a new repository for only issue tracking in Github. 

## Proposed Solution Option 4
Migrate to another issue tracker that isn't Jira/Devops or Github. 

## Alternatives Researched
Migrating all of our repositories into one isn't possible due to the complexity of our platform. We will always have multiple repositories since this is an open source project which utilizes other open source projects either in their entirety or we have forked them for customizing to better work within our platform.

**Comment by EPTamminga** [comment]
Is an additional add-on for GitHub issue tracking another possible solution? 
E.g. an integration of GitHub issues and Jira:  https://github.com/marketplace/jira-software-github

**Comment by ohine** [comment]
Of course! Anything is an option! I added a few of the common configs I’m familiar with to jumpstart the conversation.

**Comment by mitchelsellers** [comment]
@ohine Do you have any experience with any of these options and how they integrate into the Pull Request Processes using GitHub?  IE, the ability to tag a pull request as closing/fixing an issue and it creating a proper automatic link like what we get today?

I've only had limited experience with JIRA and this and wasn't sure if you had any more

**Comment by donker** [comment]
GH is currently the industry standard in open source. So we need a good reason to move away from this. DevOps looks like it could become the new hotness. But will this mean non-MS-devs will shun our project because they prefer to stay in the GH silo? Difficult to tell.

Option 5
Use just one repo for issues and redirect from the others.

**Comment by ohine** [comment]
> Do you have any experience with any of these options and how they integrate into the Pull Request Processes using GitHub? IE, the ability to tag a pull request as closing/fixing an issue and it creating a proper automatic link like what we get today?

@mitchelsellers I haven't used it in a project, but from their documentation it appears it would work the same way. They have smart comments, which would hook up via a webhook and allow issues to be linked, closed, etc automatically.



> GH is currently the industry standard in open source. So we need a good reason to move away from this. DevOps looks like it could become the new hotness. But will this mean non-MS-devs will shun our project because they prefer to stay in the GH silo? Difficult to tell.

> Use just one repo for issues and redirect from the others.

@donker Option 3 is suggested which is the same as your Option 5. I really don't think which issue tracker we use (except for DevOps) would really shun people away from reporting issues in our project. I think what will shun people away is when they report issues and nothing happens as a result. We need better ways to filter, organize, report, and create a new team to triage these issues without granting them full write access to the source code. We shouldn't have to write our own application to accomplish this, and we shouldn't be required to use a 3rd party plugin because GH lacks these features. We also shouldn't let Dnn suffer because of our issue tracker. 

------
The most important feature we're currently lacking is the ability to setup a team to help organize and tag issues without granting them full access to the source code.

The second issue we are running into, is the lack of any ability to define fields to gather and report on later. One large text field isn't a great way of handling the amount of issues being reported. 

I can keep listing the issues that GH is lacking which I think would really benefit the platform if we could resolve.

**Comment by valadas** [comment]
Well, my biggest issue is more about the multiple repositories and issues being open at the wrong place, needing to be moved, references to other repos, etc. Other than that I am happy with github issues and they work great to link to PRs, people are familiar with Github.

I have used the recent versions of Jira and although it is very powerful and customizable, it is way harder to setup than it was. There is a github integration, but then people need to be familiar with 2 things instead of one.

So, my opinion is that we should merge the repositories. As for issue triage, the plan was to give a try to issue.sh, I offered my help to test it out, just need someone with write access to let me know and I am ready for testing.

**Comment by ohine** [comment]
Disabling issue tracking on all of the repositories and redirecting to a new combined repository just for issue management is a valid solution. It doesn't solve the issue around advanced reporting and custom fields we could really benefit from, however any improvements in our issue management solution would help the platform quite a bit.

While issue.sh would solve some of these problems, it doesn't solve them all. If we want to try that route, we can configure it. I thought @mitchelsellers was going to grant you write access after our last meeting as well which defeats the purpose of integrating Issue.sh.

**Comment by mitchelsellers** [comment]
For the current time we are going to continue to operate under the permissions and setup that we are using.  I am working to get full ownership of the GitHub account which will allow permissions to be adjusted to support more granular management.  Until items stabilize I would like to limit the addition of even more third-party solutions.
