### ISSUE TITLE
Azure connector needs some basic help text

### ISSUE THREAD

**Issue by valadas** [dnnsoftware/Dnn.Platform#2572]
## Description of problem
The azure connector needs some basic info in the UI to explain what it does and what keys to get where.

## Description of solution
The UI needs to be to updated to add some basic hints to set it up.
I do not use Azure so not sure about this, but I think the field names might not match exactly the names of the corresponding Azure fields to enter there???

## Additional context
This is partially to try and help with https://github.com/DNNCommunity/DNN.Blog/issues/130

## Affected version

* [x] 9.3.0
* [x] 9.2.2

**Comment by ahoefling** [comment]
This connector should *NOT* be called `Azure` as it is only used to connect to the Azure Storage Containers.

`Azure Storage Connector` or `Azure Storage` would be a more appropriate name. 

As far as the parameters go it should read:

* Storage Account Name
* Storage Account Key

Those names match what you see in Azure

**Comment by ohine** [comment]
Then, to actually start to utilize the provider after the initial configuration. One must navigate over to `Site Assets`, create a new folder and select the `Azure` folder type when creating the folder.
