### ISSUE TITLE
If ScheduleHIstory log gets big the login/register control dissappears on homepage

### ISSUE THREAD

**Issue by thabaum** [dnnsoftware/Dnn.Platform#2575]
## Description of bug
I had an issue with my login UI controls not being presented on my designated homepage.  All other pages it displayed and after a login it displayed the account links.

I had a huge Eventlog file which I truncated... but still was hitting this issue.  After truncate ScheduleHIstory log the controls for logging in on the homepage appeared again.

## Steps to reproduce
List the steps to reproduce the behavior:
1. Create a HUGE ScheduleHistory set of logs
2. Go to homepage while not logged in
3. Controls for login dissappear

## Error log
Purge ScheduleHistory error in site admin log file

## Additional context
I have had two issues with my site.  Not sure if I cured both yet I will post more on this if I find any other issues.

It would be nice to have controls that actually can clear these event logs for ScheduleHistory and EventLog.   The current setup times out when using admin controls.

If ScheduleHistory Log gets too big it creates EventLog errors repeatedly... if you leave the site alone for some time and come back to it both these files will be too large and create all kinds of errors in eventlog making it even bigger.

This I believe created the login register links to dissappear on homepage for some odd reason.  It wasn't until I cleared ScheduleHistory did they come back.

## Affected version

* [x] 9.3.0
* [x] 9.2.2
* [x] 9.2.1
* [x] 9.2
* [x] 9.1.1
* [ ] 9.1
* [ ] 9.0

## Affected browser

* [ ] Chrome
* [ ] Firefox
* [ ] Safari
* [ ] Internet Explorer
* [ ] Edge

**Comment by mitchelsellers** [comment]
What kind of hosting environment is this in?  How large did the table get?

This can be assisted with a more frequent execution of the PurgeScheduleHistory task.  It is a larger issue for sites that have many frequently running tasks as the daily cleanup job by default might not be soon enough to allow the query to execute.  (This can be exaggerated in certain hosting environments.)

**Comment by thabaum** [comment]
SQL 2014 with IIS 8 windows 2012 server.

Table had to be 100k entries as my admin log was this huge.   I will take a look at a backup see what it had when I have time.  I had a number of bots going to pages that didnt exist along with some modules that had scheduler errors I turned off for now creating a huge log file quickly.

**Comment by valadas** [comment]
The way I read this, the real problem here is how huge the scheduler history and event log got. This can be solved by adjusting the schedules and adjusting the admin log settings. I think this boils down to more of a maintenance issue than a bug unless we have a look at why it grew so much which might be related to some third party extension or something specific with this site.

For that reason I am closing this issue since I don't say a straightforward way to make this an actionable item.

**Comment by thabaum** [comment]
I thought DNN would do all of this... this issue causes much pain why does DNN not handle it?

https://dnncommunity.org/forums/afv/post/aft/532/aff/4

more pain from oversized log I believe... and then I posted another issue recently. Just thought it could get looked into as DB"s are getting HUGE.

https://github.com/dnnsoftware/Dnn.Platform/issues/3205

It just feels like these issues should be avoided without issue if possible... maybe not possible but something to think about.
