### ISSUE TITLE
RFC: Do we need to create a source zip in a release?

### ISSUE THREAD

**Issue by EPTamminga** [dnnsoftware/Dnn.Platform#2576]
## Description of Problem
In a release, several artefacts are created, including a source .zip file, e.g. "DNN_Platform_9.2.2.178_Source.zip".
 Is this still needed? GitHub creates a sources.zip automatically on a release, the repo contains the complete source anyway.

## Proposed Solution Option 1
Remove the generation of the source .zip file for every release.

## Affected version

* [x] 9.3.0
* [x] 9.2.2
* [x] 9.2.1
* [x] 9.2
* [x] 9.1.1
* [ ] 9.1
* [ ] 9.0

**Comment by mitchelsellers** [comment]
@ohine Can you correct me if I'm wrong, but the generated source zip includes more than what is just in a GitHub download correct?

**Comment by bdukes** [comment]
The source package is an installable website package, not just a zip of source.  So long as it still works and isn't causing problems, I think it's a helpful learning and debugging tool

**Comment by donker** [comment]
I appreciate a "finished" source product which freezes a release. The automated GH download does not include external source packages, nor does it "know" how our project runs or is organized. If we can preserve it, I'd love to see it carried forward.

**Comment by ohine** [comment]
The source zip does contain the external extensions which are part of the default Dnn Platform distribution, and as @bdukes mentioned also an installable website package. We can easily adjust what's in the zip, maybe include some basic documentation as well to help people understand what's what. Happy to adjust it if necessary.

**Comment by valadas** [comment]
I agree we should keep it, at least for now.

**Comment by mitchelsellers** [comment]
Given that we have build processes that support this creation, and it archives other elements as well closing this for now as it doesn't introduce a burden.  

A suggestion to the documentation team has been made as well to improve the documentation
