### ISSUE TITLE
Personabar no users menu

### ISSUE THREAD

**Issue by meffj00** [dnnsoftware/Dnn.Platform#2582]
I installed the latest DNN Platform RC but in the personabar there is no menu Users.

**Comment by DinKumar** [comment]
Hello @meffj00, I could see Users menu in latest DNN Platform RC. 

![latest-platform-users](https://user-images.githubusercontent.com/40901826/52506042-45e2c100-2c13-11e9-82f2-fc68282503fb.png)

**Comment by meffj00** [comment]
Thanks. Fortunately, I will reinstall this release and hope to see the menu users!

**Comment by Tychodewaard** [comment]
@meffj00 Hope things worked out for you. Did reinstallling / upgrading do the trick? If so, we'll close this issue

**Comment by valadas** [comment]
I am closing this issue since it dates back from February and could not reproduce. @meffj00 If this is still an issue please open a new one with the version number too. Thanks.
