### ISSUE TITLE
Issue with connect to update service URL while accessing security bulletins

### ISSUE THREAD

**Issue by managedcom** [dnnsoftware/Dnn.Platform#2584]
## Description of bug
While using the persona bar going to the Settings Gear > Security > Security Bulletins you are presented with the following error:

Could Not Connect To http://update.dotnetnuke.com/security.aspx?type=Framework&name=DNNCORP.CE&version=090300. You Should Verify The Source Address Is Valid And That Your Hosting Provider Has Configured Their Proxy Server Settings Correctly.

## Steps to reproduce

From Persona Bar, go to Settings Gear > Security > Security Bulletins

## Current result
Could Not Connect To http://update.dotnetnuke.com/security.aspx?type=Framework&name=DNNCORP.CE&version=090300. You Should Verify The Source Address Is Valid And That Your Hosting Provider Has Configured Their Proxy Server Settings Correctly.

## Expected result
Load the security bulletins, instead of an error.

## Error log
None generated

## Additional context
It appears that when you go to this section of the persona bar that it wants to use HTTP but if you browse the URL in question it redirects to HTTPS automatically. DNN appears to not notice the HTTP to HTTPS redirect even after updating the service URL in the web.config to HTTPS://update.dotnetnuke.com

## Affected version

* [x] 9.3.0

## Affected browser

* [X] Chrome
* [X] Firefox
* [ ] Safari
* [ ] Internet Explorer
* [ ] Edge

OS: Windows 2016
SQL Version: SQL Server Express 2016
DNN Version(s): 9.3

**Comment by Tychodewaard** [comment]
@managedcom I can not reproduce this in 9.3.2.
Can this one be closed?

**Comment by valadas** [comment]
I agree, I have used this in multiple versions without problems, maybe it was just at that time the service was down or something...
