### ISSUE TITLE
500.19 When Visiting New Page Named Test

### ISSUE THREAD

**Issue by managedcom** [dnnsoftware/Dnn.Platform#2585]
## Description of bug
Creating a page named Test in either the DNN Prompt or Page Management throws a 500.19 when viewed. Cannot read configuration file as IIS is trying to visit a /test/ directory.

## Steps to reproduce
Create a page named test from the DNN Prompt or through Page Management. Attempt to view the page.

## Current result
Viewing the 'Test' page results in a 500.19.

## Expected result
Expected it to load a new default page.

## Error log
Detailed Error Information:
Module	IIS Web Core
Notification	BeginRequest
Handler	Not yet determined
Error Code	0x80070003
Config Error	Cannot read configuration file
Config File	\\?\C:\Inetpub\vhosts\game.joshcain.ga\httpdocs\test\web.config
Requested URL	http://game.joshcain.ga:80/Test
Physical Path	C:\Inetpub\vhosts\game.joshcain.ga\httpdocs\test
Logon Method	Not yet determined
Logon User	Not yet determined

## Additional context
This appears to only be an issue if you name a page "Test" any other name works as intended.

## Affected version

* [x] 9.3.0

## Affected browser

* [x] Chrome
* [x] Firefox
* [ ] Safari
* [ ] Internet Explorer
* [ ] Edge

OS: Microsoft Windows Server 2012 R2
IIS: IIS 8+
SQL Version: MSSQL Server 2016 Express
DNN Version(s): DNN 9.3 Fresh Install

**Comment by bdukes** [comment]
It looks like your file system has `/test/web.config` in the website folder, which is not a standard file.  Is that something that the hosting environment is creating?  Did a child/directory alias get created using the name `test`?

**Comment by managedcom** [comment]
> It looks like your file system has `/test/web.config` in the website folder, which is not a standard file. Is that something that the hosting environment is creating? Did a child/directory alias get created using the name `test`?

Hi bdukes,

The path/file does not exist in the file system, and the Test page was created with default settings (so not pointing to a file location). We have found that on most of our servers it functions as above, but we have since found a couple with the same setup where it is working. Something is causing Test to be ignored in the Advanced URL rewrite (going to Test.aspx works).

That all said, it doesn't appear to be a DNN 9.3 issue - something specific in the way most of our servers are currently set.

**Comment by managedcom** [comment]
We determined that this was due to virtual directory paths being created on most of the servers via Plesk. The physical folders are removed when new content is loaded to the webspace, but the virtual directory was being left behind.

So, not a DNN issue. Thanks!
