### ISSUE TITLE
RFC: HTTP/2 Support

### ISSUE THREAD

**Issue by bdukes** [dnnsoftware/Dnn.Platform#2587]
## Description of Problem
IIS 10 (Windows 10 & Windows Server 2016+) [supports HTTP/2](https://docs.microsoft.com/en-us/iis/get-started/whats-new-in-iis-10/http2-on-iis) out-of-the-box for HTTPS without any changes (e.g. dnnsoftware.com is being served over HTTP/2).  Most of its benefits are available without any changes, however there are a few changes to consider.

## Server Push
HTTP/2 supports the idea of the web server telling the client early about requests that it promises will be made later.  In ASP.NET, this is implemented via the [`Response.PushPromise` method](https://docs.microsoft.com/en-us/dotnet/api/system.web.httpresponse.pushpromise), available starting in .NET 4.6.  The API allows the server to specify a path, and if the request is served over HTTP/2 it includes that path in the response, to tell the client to request it (the call is just silently ignored when the site is served over HTTP/1.1 or otherwise not supported).

### Proposal
DNN is currently compiled against .NET 4.5, and so cannot take advantage of this API.  In DNN 10, the Client Resource Manager should be upgraded to send a server push for each requested URL.  More instances of known resources to request should be studied, and this API applied.

## Remove/Reduce HTTP/1.1 optimizations
Some optimizations for HTTP/1.1 are no longer recommended when serving a site over HTTP/2.  These include domain sharding, inlining resources, and possibly combining requests.

### Proposal
A study should be done to determine how client resource combination affects the performance of sites, and whether it should be disabled on HTTP/2.  Likewise, instances of inlining content should be replaced with a call to the `PushPromise` API mentioned above.

**Comment by sleupold** [comment]
Has this and the associated item be fied already in DNN 9.4.x?

**Comment by valadas** [comment]
I am not sure, I know we now target .Net 4.7.2 but I think this issue is about more than this. That being said, this is an RFC and other that @bdukes, nobody commented on it... Should we close this or split it up into more granular issues ?

**Comment by mitchelsellers** [comment]
I think that this should at a minimum be split to an issue for the CDF provider to send a PushPromise for all files

**Comment by thabaum** [comment]
I just setup environment to fully support HTTP/2 so I am very concerned on how DNN CE can harness this power.

I would love to see the template load first and each module load as a separate piece as you scroll only when you need it such as loading a video to play on hover.

This is right along the lines of moving to a .NET Core solution.  And HTTP/2 is the now, not the future.

I am in on this discussion as I keep thinking of how much faster DNN Should and could be.

I will poke around see what I can find out for .NET HTTP/2 converting old projects and what to expect for pitfalls maybe this can happen fairly easily with some good logic.

**Comment by sleupold** [comment]
this is still subject for DNN 10

**Comment by thabaum** [comment]
I agree

**Comment by sleupold** [comment]
still an issue

**Comment by sleupold** [comment]
AFAIK this is still an (important) issue and should remain on the to-do list.
