### ISSUE TITLE
Uninstall does not remove files

### ISSUE THREAD

**Issue by hismightiness** [dnnsoftware/Dnn.Platform#2589]
## Description of bug
If you choose to uninstall a module, it leaves the files behind, despite checking the "Remove Files" checkbox.  It also doesn't display the module version.

## Steps to reproduce
List the steps to reproduce the behavior:
1. Install DNN 9.2.2
2. Install any third-party module.
3. Choose to uninstall the module you just installed.
4. First step, you don't see the version number, but instead version 0.0.0 selected.
5. Check the "Remove Files" checkbox.
6. Click the "Delete" button.

## Current result
The module is uninstalled, but the uninstall view didn't know the module number, and the files in the respective `DesktopModules` folder are not deleted as expected.  No errors are logged.  The SQL uninstall script is run and the `bin` files are both executed as expected.

## Expected result
The `DesktopModules` folder should also have been cleared of the files that need to be deleted, if the checkbox was checked.

## Affected version

* [x] 9.3.0
* [x] 9.2.2
* [x] 9.2.1
* [x] 9.2
* [x] 9.1.1
* [ ] 9.1
* [ ] 9.0

## Affected browser

* [x] Chrome
* [x] Firefox
* [x] Safari
* [x] Internet Explorer
* [x] Edge

**Comment by pjones235** [comment]
Similar problem I've had with my themes (installed as extensions), however the only files that are remaining are skin files.

**Comment by hismightiness** [comment]
This will always be true of themes that aren't correctly installed and upgraded over time.  Other extensions keep a manifest and log of the files that are part of the installation (except anything that might be FTP-d at some point).  

In the case of themes, some people exclusively use FTP for all or part of the process, so DNN will never be aware of those changes.  Thus, the experience you've had.   :(

**Comment by valadas** [comment]
I can reproduce the issue in Dnn 9.4.0 RC with the survey core module.
Additional info:
The files in the root module folder do get deleted but not the subfolders and not the root folder

**Comment by valadas** [comment]
This may be resolved by https://github.com/dnnsoftware/Dnn.Platform/pull/2950/files just noting it here is someone has time to test and report back, this issue could be closed.

**Comment by david-poindexter** [comment]
@hismightiness @pjones235 - is this still a valid issue in 9.6.1?

**Comment by valadas** [comment]
@david-poindexter I can no longer reproduce using the same Survey module in Dnn 9.6.1

**Comment by hismightiness** [comment]
I haven't tested this since creating the issue.

**Comment by david-poindexter** [comment]
Okay, thanks @valadas and @hismightiness - it seems we can go ahead and close this issue, but if it is determined to be an issue, we can re-open.
