### ISSUE TITLE
Ad hoc resource names don't connect with JS libraries

### ISSUE THREAD

**Issue by bdukes** [dnnsoftware/Dnn.Platform#2592]
## Description of bug
When registering JS file requests with the client resource manager, a name and version can be specified, which is used to de-duplicate requests.  However, this feature is not used by JavaScript Library packages, so the de-duplication is not as complete as it should be.

## Steps to reproduce
1. Request a JS file with a name, e.g. `<dnn:DnnJsInclude runat="server" FilePath="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" Name="html5shiv" Version="3.7.2" ForceProvider="DnnPageHeadProvider" />`
2. Request the JS library version of that file, e.g. `<dnn:JavaScriptLibraryInclude runat="server" Name="html5shiv" />`

## Current result
Two requests are made for html5shiv JS files.

## Expected result
One request is made for the library JS file

## Affected version

* [x] 9.3.0
* [x] 9.2.2
* [x] 9.2.1
* [x] 9.2
* [x] 9.1.1
* [x] 9.1
* [x] 9.0

**Comment by valadas** [comment]
@dnnsoftware/approvers This is merged, please close this issue.
