### ISSUE TITLE
Exception thrown when native assembly is in assemblies component in extension manifest

### ISSUE THREAD

**Issue by bdukes** [dnnsoftware/Dnn.Platform#2595]
## Description of bug
The `AssemblyInstaller` reads version information from provided assemblies to create a binding redirect for any strong-named assemblies.  The code that does this does not have error handling when there are errors reading that information, such as when the assembly file is a native assembly, rather than a .Net assembly.

## Steps to reproduce
1. Create an extension that packages a native assembly, e.g. [bad-assembly-image-demo.zip](https://github.com/dnnsoftware/Dnn.Platform/files/2903010/bad-assembly-image-demo.zip)
2. Install the extension via the Persona Bar, click through the wizard steps

## Current result
An error in the installation log
>Could not load file or assembly 'Microsoft.DiaSymReader.Native.amd64.dll' or one of its dependencies. The module was expected to contain an assembly manifest.

## Expected result
The assembly is installed without any error

## Screenshots
![error message screenshot](https://user-images.githubusercontent.com/59507/53374819-2344ed80-391f-11e9-92a7-ad9a505e3046.png)

## Error log
>17:01:44.382-06:00 [etg63][D:4][T:37][ERROR] DotNetNuke.Services.Installer.Log.Logger - Exception - Could not load file or assembly 'Microsoft.DiaSymReader.Native.amd64.dll' or one of its dependencies. The module was expected to contain an assembly manifest

## Affected version

* [x] 9.3.0
* [x] 9.2.2
* [x] 9.2.1
* [x] 9.2
* [x] 9.1.1
* [x] 9.1
* [x] 9.0

**Comment by valadas** [comment]
@dnnsoftware/approvers This is merged, please close this issue.
