### ISSUE TITLE
Sitemap priority 0 when adding a single page

### ISSUE THREAD

**Issue by schotman** [dnnsoftware/Dnn.Platform#2602]
## Description of bug
When using the add a new page function in the pages dialog the SiteMapPriority is not set in the dialog and defaults to 0 in the database

## Steps to reproduce
List the steps to reproduce the behavior:
1. Go to pages 
2. Click on add page
3. add pagename and
4. click the add page button

## Current result
SiteMapPriority = 0

## Expected result
SiteMapPriority defaults to 0.5 (as it is when you add multiple pages)

## Screenshots
seems clear

## Error log
no error

## Affected version
* [x] 9.2.2

## Affected browser
not dependant of browser

* [x] Chrome
* [x] Firefox

**Comment by sleupold** [comment]
IMO this should be fixed in DNN API code, not the database default value.

**Comment by Timo-Breumelhof** [comment]
@skamphuis

**Comment by Timo-Breumelhof** [comment]
workaround:

UPDATE TABS SET SiteMapPriority = 0.5 WHERE TABID IN (SELECT   TabID
FROM     Tabs
WHERE   (PortalID = 0) AND (SiteMapPriority = 0) and (IsSystem = 0))

**Comment by schotman** [comment]
> IMO this should be fixed in DNN API code, not the database default value.

Yes, it should

**Comment by valadas** [comment]
Issue moved to [dnnsoftware/Dnn.AdminExperience #422](https://github.com/dnnsoftware/Dnn.AdminExperience/issues/422) via [**ZenHub**](https://www.zenhub.com/)

**Comment by valadas** [comment]
By mistake this issue was copied instead of moved, closing it since this needs a fix in AdminExperience
