### ISSUE TITLE
Where's the branch for 9.2.2?

### ISSUE THREAD

**Issue by abukres** [dnnsoftware/Dnn.Platform#2605]
There's a 9.2.2 release but I don't see the code branch for it.

**Comment by ohine** [comment]
There is a tag for it, we have started to delete the release branch after the RC turns to the final release.

**Comment by ohine** [comment]
https://github.com/dnnsoftware/Dnn.Platform/tree/v9.2.2

**Comment by mikesmeltzer** [comment]
@abukres does the link above resolve this for you? If so, please close the issue. Thanks.
