### ISSUE TITLE
Globals.GetCultureCode will not work when call from scheduler

### ISSUE THREAD

**Issue by zyhfish** [dnnsoftware/Dnn.Platform#2606]
## Description of bug
when Globals.GetCultureCode called from scheduler, it will throw out null reference exception, this caused by commit #9ab22767, PortalController.Instance.GetCurrentPortalSettings() doesn't exist in sub thread. i think the code need change to:
`var portalSettings = PortalController.Instance.GetCurrentPortalSettings();
cultureCode = portalSettings?.DefaultLanguage ?? Thread.CurrentThread.CurrentCulture.Name;`

## Affected version
* [x] 9.3.0

**Comment by valadas** [comment]
Closing since PR got merged
