### ISSUE TITLE
RFC: Package extensions via NuGet

### ISSUE THREAD

**Issue by bdukes** [dnnsoftware/Dnn.Platform#2614]
In the discussion of #2599, I mentioned the idea of using NuGet to package extensions to DNN, as an alternative to the current `zip` file upload.  Using NuGet for packaging brings along some benefits that I think make it worth considering.

## Benefits

* NuGet contains the idea of **dependencies**, so that one package can depend upon another.  The current DNN manifest already has the idea of [dependencies](https://dnndocs.com/content/developers/extensions/dnn-manifest-schema/index.html#dependencies) on a type, package, or DNN version.  However, NuGet's [version ranges](https://docs.microsoft.com/en-us/nuget/reference/package-versioning#version-ranges-and-wildcards) and [target frameworks](https://docs.microsoft.com/en-us/nuget/reference/target-frameworks), along with the ability to depend upon _any_ NuGet package may unlock some interesting possibilities, especially as we work to migrate to .NET Standard and, eventually, .NET Core.
* There are [many simple options for **hosting** NuGet packages](https://docs.microsoft.com/en-us/nuget/hosting-packages/overview), which would easily allow the community to restart the DNN Forge, as well as allow 3rd parties to add their own internally or externally hosted suite of extensions.
* Using NuGet packages would make it easier to **retrieve required dependencies during the installation process**.  If DNN allowed managing a list of NuGet hosts, an extension package could indicate that it depends on another extension, or a standard NuGet library, and that dependency would be seamlessly retrieved during installation.
* Using NuGet gives us a **standard tool familiar to .NET developers**, and removes the need to find and understand any of the various more-or-less automated packaging systems that the community has created over the years.

## Alternatives Considered
The community can wait for DNN Corp to rebuild the DNN Store and its update service, and use that as a platform to host extensions and then update DNN's extension installer to make use of that platform and service during the installation process.

* Pros: May better support non-free extensions
* Cons: Does not solve the need for richer dependencies or simpler packaging.  Implementation of package retrieval during installation will likely be more work if not based on an existing framework/tool

**Comment by mitchelsellers** [comment]
I for one, see this as a huge win-win for the community.  Not sure if it should be a "required" model or only a supported model, but packaging/deployment/installation could be greatly simplified given the built-in support for the creation of NuGet packages in VS.

**Comment by ahoefling** [comment]
I was thinking about this idea more and this could be a way to easily standup a community repository of extensions. Since NuGet already supports an API for download packages we could then build that into platform. 

Consider this:
When you go to the extensions page in DNN you select repositories, just like you would in Visual Studio for package source (we could add some custom header to certify it is a DNN NuGet Repository). Then the user can search through the NuGet (extensions) and select which one they want. The server would be able to download it and then install it automatically. 

The thing I really like about this approach is how the repository won't be hard coded into the platform and an admin can customize to use no repositories or as many as they want.


@mitchelsellers @bdukes what do you guys think?

**Comment by bdukes** [comment]
Yeah, I was hoping that we'd be able to do something like that

**Comment by ohine** [comment]
Here is another alternative. We don't wait for Dnn to rebuild the store. We take it on ourselves. We take over the upgrade service and make it actually useful connected to a storefront we manage and funds raised through sales could go towards helping to pay for supporting the platform. We provide a curated list of forge extensions. We enable 1-click upgrades of all extensions.

While on the surface nuget packages sound nice for extensions, I really don't think it's a wise decision. While other .net stuff might work as-is in dnn, dnn stuff will not work as-is outside of dnn. We already took quite a bit of flax for our non-standard usage of nuget, and this just seems like another non-standard usage which might hurt our reputation even more.

**Comment by ohine** [comment]
If we do add support for nuget packages, we should make our internal manifest format obsolete. Having two vastly different methods to package and install extensions isn't something I think we want to add into the platform. We need one method that's rock solid and properly documented.

**Comment by valadas** [comment]
I am all for our own update service (and 1 click install and 1 click updates) and will be starting work on revamping the forge soon which I hope could become the single source of truth for information on community extensions that other systems can plug into. I was thinking that each extension could provide it's own enpoint that could report the latest stable version, that way the update link would work with the forge, the store and any other developer who would provide his own.

For the idea of rebuilding the store ourselves, I like it but I do not think it is our decision to take... 

I am against removing the current installer, this would be a massive breaking change! I am all for improving it though. We need to keep supporting having modules in the install folder automatically install, we need to support offline installations, etc. I am not sure Nuget could be a good replacement, maybe an addition, but not a replacement. We need to keep in mind that the installer is extensible and can locate unknown installers by reflection using the extension type string to do anything a developer need as far as installation (this is how it works now for the Persona Bar Modules, there is no code in the platform to install those, it locates the installer from the persona bar dnn when it sees the type is not anything known in the platform and fires up that code.

**Comment by valadas** [comment]
Any progress in this matter, are there plans to make this happen in Dnn 10, 11 or should we move this discussion to the forums until we have an actionable issue? I for one was planning on revamping the forge but some priorities have changed and I wont be working on that for Dnn 10 for sure.

**Comment by mitchelsellers** [comment]
I think this is still an active discussion, I think this is one that we can leave in an RFC status, until we get closer to an actionable state.
