### ISSUE TITLE
User Management screen is blank

### ISSUE THREAD

**Issue by bct01** [dnnsoftware/Dnn.Platform#2620]
## Description of bug
User Management screen is blank. Nothing is displayed on the screen.

## Steps to reproduce
List the steps to reproduce the behavior:
1. Download and install v9.3.0-rc2 : https://github.com/dnnsoftware/Dnn.Platform/releases/download/v9.3.0-rc2/DNN_Platform_9.3.0.0-rc2_Deploy.zip 
2. After Installation, Login as Host 
3. Click on the Manage button. Select Users. 
4. The screen is empty

## Current result
The screen appears empty.

## Expected result
The screen should have a grid of User's list

## Screenshots
If applicable, provide screenshots to help explain your problem.

## Error log
Paste the error log that is related to this issue.

## Additional context
Add any other context about the bug that may be helpful for resolution.

## Affected version

* [x] 9.3.0 rc2

## Affected browser

* [x] Microsoft Edge
* [ ] Chrome
* [ ] Firefox
![Blank Manage Users screen - MS Edge](https://user-images.githubusercontent.com/48443361/54130433-bd5c6980-43e6-11e9-89c0-a3fb3bf76b06.png)

* [ ] Safari
* [ ] Internet Explorer
* [ ] Edge

**Comment by mikebigun** [comment]
I guess this is already fixed with the following PR:

https://github.com/dnnsoftware/Dnn.AdminExperience/pull/425

**Comment by bct01** [comment]
OK thanks.
