### ISSUE TITLE
dead loop occured in vocabularies

### ISSUE THREAD

**Issue by zyhfish** [dnnsoftware/Dnn.Platform#2626]
## Description of bug
special name for terms will cause dead loop, this is caused by code:
https://github.com/dnnsoftware/Dnn.Platform/blob/development/DNN%20Platform/Library/Entities/Content/Taxonomy/Term.cs#L181

## Steps to reproduce
List the steps to reproduce the behavior:
1. install 9.2.2 and login as host; 
2. goto Settings > Vocabularies, open Tags panel, try to add a new term named "&test;".

## Current result
the request will never complete.

## Expected result
the name should able add.

## Screenshots
![image](https://user-images.githubusercontent.com/3364448/54272446-af614100-45be-11e9-9bf5-772bb930238b.png)

## Affected version
* [x] 9.3.0
* [x] 9.2.2

**Comment by valadas** [comment]
I can reproduce in 9.4.0 RC

**Comment by engineering87** [comment]
It works on v. 09.04.01 (22)

**Comment by valadas** [comment]
I kinda remember there was a PR to fix this, maybe the issue was not tagged on that PR, I am closing this as fixed in 9.4.1, if it is not the case feel free to comment or reopen.
