### ISSUE TITLE
imported modules don't keep in order if the tabmodules index broken

### ISSUE THREAD

**Issue by zyhfish** [dnnsoftware/Dnn.Platform#2627]
## Description of bug
we should not trust the sql index as it maybe broken in some scenarios, need order the export tab modules in codebase to make sure it in correct order.

## Steps to reproduce
1. install 9.2.2 and login as host; 
2. create a new page and add 5 html modules into same pane.(add some special text for them so that we can know the order, such as: test 1, test 2...) 
3. re-order the modules, such as 1-5-4-3-2; 
4. open the website db in SSMS, disable index IX_TabModules_ModuleOrder for TabModules table; 
5. run full export job, create a new empty child site, and import the package; 
6. compare the order between main site and child site.

## Current result
the modules is imported in wrong order.

## Expected result
modules should keep order after imported.

## Affected version

* [x] 9.3.0
* [x] 9.2.2
* [x] 9.2.1

**Comment by valadas** [comment]
@dnnsoftware/approvers PR is merged, please close this issue.
