### ISSUE TITLE
Upgrade To 9.3.0 fails from 9.2.2

### ISSUE THREAD

**Issue by james7342** [dnnsoftware/Dnn.Platform#2631]
## Description of bug
Upgrade failing from DNN 9.2.2 to 9.3.0

## Steps to reproduce
Extract DNN 9.3.0 Upgrade files in to IIS DNN folder
Issue /Install/Install.aspx?mode=upgrade
Try to access site after prompt of upgrade was successful.

## Current result
Upgrade Fails

## Expected result
Upgrade successful and site is accessible

## Screenshots
<img width="822" alt="screenshot_829" src="https://user-images.githubusercontent.com/27960723/54699332-09499580-4aee-11e9-922b-d67aa3acb237.png">
<img width="788" alt="screenshot_831" src="https://user-images.githubusercontent.com/27960723/54699359-16668480-4aee-11e9-808f-6fd818640b58.png">

## Error log
[InstallerLog20190320.txt](https://github.com/dnnsoftware/Dnn.Platform/files/2989039/InstallerLog20190320.txt)

## Affected version

* [x] 9.3.0
* [x] 9.2.2
* [ ] 9.2.1
* [ ] 9.2
* [ ] 9.1.1
* [ ] 9.1
* [ ] 9.0

**Comment by sleupold** [comment]
Did you try restarting the app pool and clearing local browser cache?

**Comment by james7342** [comment]
After 2nd attempt and sitting on the upgrade successful page for a little while to make sure everything is complete i received the below error message.
<img width="999" alt="screenshot_830" src="https://user-images.githubusercontent.com/27960723/54699548-75c49480-4aee-11e9-9ca4-ace5b0405723.png">
And see this in the log
[2019.03.20.log.txt](https://github.com/dnnsoftware/Dnn.Platform/files/2989049/2019.03.20.log.txt)

Looking at the log it appears it appears DNN thinks an upgrade is still in progress.

2019-03-20 08:52:39,697 [DESKTOP-ITGOR02][Thread:14][ERROR] DotNetNuke.Services.Exceptions.Exceptions - DotNetNuke.Services.Exceptions.PageLoadException: The site was accessed while an installation/upgrade was in progress. ---> System.Web.HttpException: The site was accessed while an installation/upgrade was in progress.

**Comment by james7342** [comment]
> Did you try restarting the app pool and clearing local browser cache?

Yes. Recycled App Pool , Stop/Started Site in IIS. Restarted VM. Restored VM from snapshot and attempted upgrade a 2nd time with same result.

**Comment by valadas** [comment]
I did two upgrades today that went fine.
Shot in the dark but could it be a permissions issue, does the worker process have full permissions on the site folder? Maybe it cannot delete the installBlocker.lock at the end but has all other permissions except delete?? Just a guess. If you delete that installBlocker.lock, does the site start?

**Comment by james7342** [comment]
> I did two upgrades today that went fine.
> Shot in the dark but could it be a permissions issue, does the worker process have full permissions on the site folder? Maybe it cannot delete the installBlocker.lock at the end but has all other permissions except delete?? Just a guess. If you delete that installBlocker.lock, does the site start?

Anything is possible and I'd have to check, but this is a basic sanity check DNN instance. It doesn't even have 3rd part modules installed. If I'm not mistaken it started out as a 9.0 site and has been upgraded to the various releases up to 9.2.2. I'm questioning the installation to a certain degree. I don't have an install log from a successful upgrade, but it seems weird that it indicates it's completed after the GoogleAnalyticsConnector_09.03.00_Install.zip install. Is that the last module to updated/installed are part of the upgrade on a successful upgrade? Just seem to be missing a few steps and abruptly ends.

It's pretty easy to attempt another upgrade. I'll see if deleting the .lock file helps at all. If you have a successfully install.log that you can share I'd be interested in seeing it to compare.

**Comment by james7342** [comment]
Well, I guess 3rd time is a charm. I just ran the upgraded again and it indicated it was completed after the GoogleAnalytics Module again. This time though it appears to have worked as the site is upgrade to 9.3.0. I'll play with it some more, but if all seems to be working I'll close this issue out.

**Comment by mitchelsellers** [comment]
@james7342 One question - Do you by chance have an active virus scanner monitoring the directory?

**Comment by james7342** [comment]
> @james7342 One question - Do you by chance have an active virus scanner monitoring the directory?

Now that mention it I'm sure I do. This is test box is nothing more than a Windows work station that more than likely has MS Defender installed. I'm going to try it now on my Manged.com public test/dev site to see how it goes. I'm suspecting now it was something on my side and not a DNN upgrade issue specifically.

**Comment by james7342** [comment]
I'm going to go ahead and close this out. I've upgraded 2 sites now without issue. Did run into a new issues with CKeditor and browsing server for images on both sites. Will open new issues for it.

**Comment by SimoneBueno** [comment]
I know this is closed but I was lucky to run into it and the comment from @valadas suggesting to delete the installBlocker.lock worked for me perfectly. Thanks.
