### ISSUE TITLE
DNN 9.3.0 DNNConnect.CKE unable to browse server for Images

### ISSUE THREAD

**Issue by james7342** [dnnsoftware/Dnn.Platform#2632]
## Description of bug
When trying to browse server for image receive error
"Unable to cast object of type 'System.Collections.Generic.List`1[DotNetNuke.Services.FileSystem.FileInfo]' to type 'System.Collections.Generic.List`1[DotNetNuke.Services.FileSystem.IFileInfo]'."

## Steps to reproduce
Assume DNN CKE is the default editor.
1. Edit Module on page
2. Click the Add Image Icon.
3. Click Browse Server button
4. Pop-up tries to load but receive Application Server Error.

## Current result
Unable to browse server and receive error

## Expected result
Provide a clear and concise description of what you expected to happen.

## Screenshots
<img width="1513" alt="screenshot_832" src="https://user-images.githubusercontent.com/27960723/54722139-04520980-4b21-11e9-8488-816db7733ba1.png">

## Error log
[2019.03.20.log.txt](https://github.com/dnnsoftware/Dnn.Platform/files/2990286/2019.03.20.log.txt)

## Additional context
Able to duplicate on 2 different sites. One local dnndev.me site and another Hosted Public available test/dev site.

## Affected version
* [x] 9.3.0
* [ ] 9.2.2
* [ ] 9.2.1
* [ ] 9.2
* [ ] 9.1.1
* [ ] 9.1
* [ ] 9.0

## Affected browser
Only tested with the below
* [ ] Chrome
* [ ] Firefox
* [x] Safari
* [ ] Internet Explorer
* [x ] Edge

**Comment by james7342** [comment]
Restored Public Test/Dev site back to 9.2.2 and can now browse server again with the editor.

**Comment by valadas** [comment]
I can reproduce that it does not work too, but don't get that much details for the error, probably a setting to prevent showing them when not local.

**Comment by james7342** [comment]
> I can reproduce that it does not work too, but don't get that much details for the error, probably a setting to prevent showing them when not local.

Yeah, on my public test/dev site the error message is the pretty basic one telling you to modify the web.conf etc. The one I provided is from my other site and is a local PC and has all the error displaying turned on. No one else but me is looking at it anyway. Plus it's a virtual machine that is off the majority of time. Makes this sort of testing easy. Take a snapshot and roll back if it breaks.

**Comment by valadas** [comment]
It also only affects upgrades in my case, clean install looks fine. I am starting over a clean upgrade and clean new install to compare what is different

**Comment by james7342** [comment]
Something is a little wonky with these last 2 builds as I'm sure RC testers would have found this type of stuff.

**Comment by james7342** [comment]
> @james7342. We’d love additional help with testing the RCs. It’s a community effort, and every additional set of eyes can help the project tremendously.

@ohine , I'm more than willing to help out when and where I can as. My comment above was not any kind of dig at Beta and RC testers. I'm sure something just got missed and will be resolved quickly. I've been using DNN for about 5 years now and have just started to participate in the community efforts.

**Comment by ohine** [comment]
I know it wasn't a dig at all, and no worries I didn't take it like that. We welcome any and all testing that anyone can contribute back. This issue honestly should of been caught during the painfully long multiple RC releases for v9.3.0, but it wasn't. If you have the bandwidth to test upgrades for v9.3.1 RC, that would be incredibly helpful!

**Comment by garyfrater** [comment]
Not sure how helpful but installed fresh 9.2.2 and upgraded to 9.3.1-alpha.3.11507 (from Release-340) and error still occurs, is this the latest build to test against?

**Comment by valadas** [comment]
The way I "quick-fixed" this is I bumped the version number in the manifests of DNNConnect.CKEditorProvider and DNNCE_FolderProviders and reinstalled those two packages manually. It fixed the issue for me.

**Comment by james7342** [comment]
Just installed 9.3.1RC0 and it appears this is fixed in the build. CKEditor Provider is now version 1.0.5.

**Comment by valadas** [comment]
I think this has been resolved after the RC stage and cannot reproduce in 9.4.0 RC. If this is still an issue with recent releases, please feel free to comment and we will reopen the issue for further investigation on specific upgrades.

**Comment by johnhill2424** [comment]
Getting this same error in 9.4.03 and 9.4.04
