### ISSUE TITLE
Trying to find Group Privacy Settings

### ISSUE THREAD

**Issue by james7342** [dnnsoftware/Dnn.Platform#2633]
## Summary
I've upgraded 2 sites to 9.3.0 and trying to find the Privacy tab as noted in the release notes.
Group Privacy Settings in Site Settings in a new tab. Thanks @donker [#99](https://github.com/dnnsoftware/Dnn.AdminExperience/issues/99)

## Steps to reproduce (if necessary)
Upgraded from 9.2.2 to 9.3.0 and trying to find the new privacy tab under site settings. Not there on the 2 sites I've upgraded.

## Screenshots (if necessary)
<img width="849" alt="screenshot_833" src="https://user-images.githubusercontent.com/27960723/54723367-9871a000-4b24-11e9-9f17-46abd54d6800.png">

## Affected version

* [x] 9.3.0
* [ ] 9.2.2
* [ ] 9.2.1
* [ ] 9.2
* [ ] 9.1.1
* [ ] 9.1
* [ ] 9.0

**Comment by james7342** [comment]
Looking at the feature it supposed to look like this.
![51511413-38ce7100-1dcf-11e9-817a-6e44eb7b5483](https://user-images.githubusercontent.com/27960723/54723531-19309c00-4b25-11e9-844d-43a93d804587.png)

**Comment by james7342** [comment]
Looking at this more. I'm not seeing any of the Persona Bar updates that are noted in the release notes.

Either I'm doing something wrong or they're not there at least on the 2 sites I've upgraded.
Missing:
Added UI for Small and Large Page Icons back into Page Settings.
Added UI for Host Email setting under SMTP Configuration.
Added Cookie consent and configuration settings for Terms and Privacy pages - This is related to the overall issue.

Did something get missed on upgrades? Maybe new installs have it.
<img width="849" alt="screenshot_833" src="https://user-images.githubusercontent.com/27960723/54726684-6adf2380-4b31-11e9-9dc7-4e16c6514b15.png">
![screenshot_834](https://user-images.githubusercontent.com/27960723/54726687-6dda1400-4b31-11e9-9bed-499cf3515f3a.png)
![screenshot_835](https://user-images.githubusercontent.com/27960723/54726696-74688b80-4b31-11e9-9f21-d7aeae261e1d.png)
![screenshot_836](https://user-images.githubusercontent.com/27960723/54726701-79c5d600-4b31-11e9-88e9-412b003a8d9f.png)

**Comment by valadas** [comment]
Looks like there was a build issue that affected upgrades only (the modules versions where not applied during final packaging so the installer skipped them), the upgrade package has been replaced in the same release with correct versions.

Ideally, I would suggest rolling back to 9.2.2 and redoing the upgrade to be 100% safe. 

However on 2 sites that I just upgraded this morning to the previous package, I just put the new package files over the old ones and navigated to http://www.yoursitename.com/Install/install.aspx?mode=InstallResources to force the modules to install. After a 15 minutes test around the features, it looks fine now.

**Comment by james7342** [comment]
I've already rolled on site back and can my other one pretty easily also.  Think that will fix the CKeditor issue also?
https://github.com/dnnsoftware/Dnn.Platform/issues/2632

**Comment by valadas** [comment]
It looks like that is a different problem, not sure why... But I can reproduce too

**Comment by james7342** [comment]
Daniel,

Works like a charm now.  Comparing the new to old install logs it looks much better now. This was what I was commenting about earlier on my upgrade issue I opened. The log just didn't seem like a normal upgrade log I've seen in the past.


[InstallerLog20190320-New.txt](https://github.com/dnnsoftware/Dnn.Platform/files/2990744/InstallerLog20190320-New.txt)
[InstallerLog20190320-Old.txt](https://github.com/dnnsoftware/Dnn.Platform/files/2990745/InstallerLog20190320-Old.txt)

I'll close this issue out also. 

FYI: It didn't resolve issue #2632

**Comment by james7342** [comment]
> It looks like that is a different problem, not sure why... But I can reproduce too

Good. So it's not just me..
