### ISSUE TITLE
Migrate WebRequestCachingProvider to open source

### ISSUE THREAD

**Issue by zyhfish** [dnnsoftware/Dnn.Platform#2634]
Migrate WebRequestCachingProvider to open source.
Migrate web monitor scheduled task as well.

**Comment by valadas** [comment]
@zyhfish @ashishpd @daguiler is this still planned or should we close this issue ? If still planned, can we assume to have this in Dnn 10 ?

**Comment by sleupold** [comment]
this would be a great improvement of DNN Platform

**Comment by valadas** [comment]
This issue was created in march, I asked 3 persons for an update and did not get any replies. I am closing this issue to clean the backlog, @ashishpd if this project is still on the table, feel free to comment or reopen.
