### ISSUE TITLE
Error when importing the site, if this is multi-language

### ISSUE THREAD

**Issue by luishdezortega** [dnnsoftware/Dnn.Platform#2640]
## Description of bug
If you try to import a site with multi-language, the task passes without problems from the state of "submit" to "in progress", but remains in that state. If you go to the schedules you can see that the task is executed, but in the "admin logs" two exceptions are observed due to the execution of this task.

## Steps to reproduce
List the steps to reproduce the behavior:
1. Export a site multi-language using the "import / export" option.
2. Generates a new blank site or with the default template. If you want you can enable more languages or not.
3. Go to the "import" option and select the site you are going to import, remember to add it previously to the App_Data / ExportImport folder
4. Click in Continue.
5. Go to "Admin Logs" and note the generated exceptions.

## Current result
The site continues with its initial status and does not perform any import

## Expected result
That the site successfully perform the import and show immediately.

## Screenshots
![Error #1](https://user-images.githubusercontent.com/33293943/54832607-7b56e180-4c8a-11e9-99d5-ff872bfe4b5a.PNG)
![Error #2](https://user-images.githubusercontent.com/33293943/54832613-7eea6880-4c8a-11e9-9c09-6565d8a43427.PNG)

## Affected version

* [x] 9.3.0
* [x] 9.2.2
* [x] 9.2.1
* [x] 9.2
* [x] 9.1.1
* [x] 9.1
* [ ] 9.0
In these versions I have tried to carry out this import process

**Comment by valadas** [comment]
#2882 has multiple fixes for import/export, I did not do a full review and test, but just noting it here in case when it is merged it fixes this issue too.

**Comment by sleupold** [comment]
did anyone validate this issue on latest platform release?

**Comment by david-poindexter** [comment]
Closing this issue due to a lack of verification.  Let us know if this needs to be re-opened.
