### ISSUE TITLE
What are the DEPLOY files for?

### ISSUE THREAD

**Issue by fsiler** [dnnsoftware/Dnn.Platform#2641]
## Summary
I'm trying to [Dockerize DNN](https://github.com/fsiler/dotnetnuke-docker), and in a perfect world I'd be able to just have the site come up running out of the box rather than coming up with the installation screen.

## Extended description
What does the DEPLOY file do?  If I set up web.config with the appropriate connection strings, will it just run the installation or something?

**Comment by valadas** [comment]
I was told that they where for Web Platform Installer, but I have never used them...

**Comment by fsiler** [comment]
That’s interesting and it looks like webPI is at least somewhat configurable using DSC. I’m already using DSC (courtesy @solthoth @kenmaglio) to configure IIS, so I wonder if this could be extended.

**Comment by Tychodewaard** [comment]
@fsiler I have a feeling, this is not 'issue ready'. May I sugggest we close this issue and start a discussion on https://dnncommunity.org/forums? Hopefully, you'll find more insights from others and/or come up with ideas this request should meet

**Comment by valadas** [comment]
I agree, closing this until we can make it an actionable issue.
