### ISSUE TITLE
Add SQL Server version dependency to the manifest

### ISSUE THREAD

**Issue by MaiklT** [dnnsoftware/Dnn.Platform#2642]
## Description of problem
It is not possible to add the SQL Server version (e.g. "2016" or "13.0.1601.5") as a dependency in a manifest.

## Description of solution
A dependency should be added, something like

`<dependency type="SqlServerVersion">13.0.1601.5</dependency>`

## Affected version

* [x] 9.3.0
* [x] 9.2.2
* [x] 9.2.1
* [x] 9.2
* [x] 9.1.1
* [x] 9.1
* [x] 9.0

## Affected browser

* [x] Chrome
* [x] Firefox
* [x] Safari
* [x] Internet Explorer
* [x] Edge

**Comment by sleupold** [comment]
IMO it would be sufficient to check for Database compatibility level. This is mire relevant for the features to be use in SQL Server code.

**Comment by MaiklT** [comment]
No, or at least not always. When you have SQL Server 2016 installed and a database in compatibility level 120 (SQL Server 2014) you may still use commands like

`DROP VIEW IF EXISTS v_MyUnnecessaryView`

even if this leads to an error in SQL Server 2014. Therefore the information about the SQL Server version is more important than the compatibility level in this case.

**Comment by valadas** [comment]
I am closing this issue since it duplicated #2116
