### ISSUE TITLE
Saving Site Settings For Different Sites Saves To All Site Portals Same Setting 9.3.1

### ISSUE THREAD

**Issue by thabaum** [dnnsoftware/Dnn.Platform#2652]
## Description of bug
Installed 9.2.2, upgraded to 9.3.1 RC0, Created second portal website and looked at settings noticed they had blank description after creating one while creating the new site portal.  Created a second website and the website settings description saved to all the website portal settings as in each site had the same name, description.... 

## Steps to reproduce
List the steps to reproduce the behavior:
1. Create a second portal website
2. Edit the portal site settings description or title, click save.
3. Go to site settings and it will be the same as the host first site setup settings
4. You will see you are Editing Site "Site Name" and the Title/description will be the same as the last one saved on any of the sites you create and install.  The last site settings saved overwrites the others... including site alias's....
5. Go To MANAGE > SITES

On any of the site portals websites to manage the sites.

the updates are applied correctly to each site however you will see the last updated site settings for all portals. If you go to Site Settings things get a little more interesting behavior... also not displaying site settings correctly except when you first visit the site ??

## Affected version

* [x] 9.3.1

**Comment by thabaum** [comment]
Go To MANAGE > SITES

On any of the site portals websites to manage the sites.

the updates are applied correctly to each site however you will see the last updated site settings for all portals.  If you go to Site Settings things get a little more interesting behavior... also not displaying site settings correctly except when you first visit the site  ??

**Comment by thabaum** [comment]
figured out the confusion was when I click on the gear in MANAGE > SITES On the persona bar for a certain site/portal it would take me to site settings admin panel but the choice at the top would have the last site selected settings.

I was expected to see my site settings for the site I clicked on the gear for.

**Comment by thabaum** [comment]
I just installed the latest release, when I update the Site Alias it updates for all the website portals I created.  I will test on more instances however seems to be if I change the SITE selected in site settings all the websites display the same inforamtion after I update one of them.

The website I am on is the site alias information being displayed and updated on all portals as I switch between them.  Or at least it appears that way... it might be different in the database itself I will check.

**Comment by thabaum** [comment]
OK this is confirmed, opened up the other website portal and the same thing is happening.  No matter what portal I choose it shows the portal I have currently logged into information.

When you switch between portals you see the same information displayed 
Site Settings > SIte Behavior > Site Aliases

None of other tabs or settings pages have this behavior I have seen or tested.

**Comment by thabaum** [comment]
Two seperate instances issue confirmed.  Switching between sites while viewing site alias will only display the portal alias settings for the portal you are logged into.

**Comment by bdukes** [comment]
![https://imgur.com/bDlEzCC](https://i.imgur.com/0oyj3q9.gif)

I've verified that switching sites does not refresh the alias list, but does refresh everything else. Switching between tabs fixes the alias list.

**Comment by thabaum** [comment]
correct, in the previous version there was an issue with all the pages, now just the alias seems to not function, you have to log into the portal to see the changes and you only see the settings for the portal you are using.

**Comment by lanthonyneville** [comment]
This issue is still present in DNN 9.3.2

**Comment by valadas** [comment]
This is still the case with 9.4.0 RC, I am closing this issue in favor of a duplicate in AdminExperience https://github.com/dnnsoftware/Dnn.AdminExperience/issues/1052 since it needs to be fixed there.
