### ISSUE TITLE
RC 9.3.1 Site and global assets open in now window with overlay

### ISSUE THREAD

**Issue by iJungleboy** [dnnsoftware/Dnn.Platform#2655]
## Description of bug
When opening the site assets or global assets from the sidebar, they 

1. open in a new window (unexpected)
1. once the window loaded, the admin-overlay covers it again (unexpected)

## Steps to reproduce
List the steps to reproduce the behavior:
1. Log on, in sidebar, select X-Tools, Site assets

## Expected result
Should open in the same window (unless shift-clicked), and the admin-panel should then stay hidden by default, until needed again. 

## Affected version

* [x] 9.3.1

**Comment by sleupold** [comment]
this modules still lacks migration to PersonaBar extension.
However, if a PersonaBar item  is a page, the PersonaBar should stay away from opening.

**Comment by valadas** [comment]
As part of #2439 this module will undergo a rebuild and will no longe be webforms based and will be able to live properly in both a page or as a real persona bar module, for that reason I am closing this issue.
