### ISSUE TITLE
RC 9.3.1 Site Theme Change not really applied, probably bug in site-template

### ISSUE THREAD

**Issue by iJungleboy** [dnnsoftware/Dnn.Platform#2656]
## Description of bug
When I switch to another theme, I don't see the changes

## Steps to reproduce
1. Install new 9.3.1 with default theme
2. optionally add some pages (to see full effect)
3. Go to home
4. Open sidebar > X-Tools > Themes, 
5. Install new theme like [Bootstrap 4 Instant](https://github.com/2sic/dnn-theme-bootstrap4-instant)
6. Once installed, select the theme

## Current result
At first impression (because we're on home) - nothing changed. If we go to other pages, they seem to be changed. if you translated the site first, then on the translated copies the same thing happens, home doesn't change, the rest seem to be ok. 

## Cause
I believe the reason is that the template site hard-wired the theme of the initial page, so it's in the settings. As there is no way to "reset" this on any page, this page will never follow the site theme. 

## Affected version

* [x] 9.3.0
* [x] probably previous ones are the same

**Comment by valadas** [comment]
The default theme has a layout for the home page and another layout for internal pages. So it sets the site one to the internal layout but needs to set the home page to the home layout. As far as I can see, this would not be a bug but something required by the default theme. 

I would love for a new default theme and template and this situation should be accounted for if that happens, but I think that should be a different issue title and description if someone decides to do so ( I may submit something for Dnn 10 in that regards time allowing) But as far as this issue goes I am closing it in favor maybe on a default theme change instead.
