### ISSUE TITLE
Remove ObjectQualifier from installer dialog

### ISSUE THREAD

**Issue by iJungleboy** [dnnsoftware/Dnn.Platform#2657]
## Description of problem
The Object Qualifier is an old feature which leads to issues. I would like to remove it from the installer dialog. I would also do it, if the consensus is that we'll do this. 

## Description of solution
The ObjectQualifier was an old trick to "share" an SQL DB for multiple, standalone sites. There is no justification for it today, but when people use it (because they think they should put their name in that field) it can cause trouble down the road, for example with modules that don't support this. I would either

1. put a big warning on it
2. remove it from the UI (my preference)

## Description of alternatives considered
Provide a clear and concise description of any alternative solutions or features you have considered.

## Please Post your Preference
...below, so I know if this is something the rest of the community would want, and which version.

**Comment by ohine** [comment]
At the @dnnsoftware/approvers meeting today, we agree that removing this option from the installer would be great. Switching this from an RFC to a help wanted request.

**Comment by iJungleboy** [comment]
Awesome - I'll try to get a pull request in within the next 10 days.

**Comment by ohine** [comment]
@iJungleboy I just submitted PR #2719 to fix this and the annoying banner issue in one go.
