### ISSUE TITLE
When using the Cacheable attribute on models in custom modules, how long are items cached for?

### ISSUE THREAD

**Issue by shanewalker1595** [dnnsoftware/Dnn.Platform#2660]
## Summary
The Cacheable attribute that may be applied to models in custom module developments contains a parameter for `CacheTimeOut`. How is this parameter used to calculate cache expiration time?

## Extended description
https://github.com/dnnsoftware/Dnn.Platform/blob/584b0f54bd6b6d237594dd9f96053f14db0b1a53/DNN%20Platform/Library/ComponentModel/DataAnnotations/CacheableAttribute.cs#L81 states that the `CacheTimeOut` parameter is multiplied by the "Host Performance Setting to determine the actual timeout value" - Where is the "Host Performance Setting" that this is referencing? What are the corresponding times used to calculate Sliding expiration in seconds, milliseconds or other time-based values?

## Affected version

* [x] 9.3.0
* [x] 9.2.2
* [x] 9.2.1
* [x] 9.2
* [x] 9.1.1
* [ ] 9.1
* [ ] 9.0

**Comment by valadas** [comment]
I am following this because I also have the same question, would be nice to add the details of how this works in the new Dnn Docs when we know the details.

**Comment by ohine** [comment]
The `CacheTimeOut` parameter is multiplied by the `PerformanceSetting`

```
public enum PerformanceSettings
{
    /// <summary>
    /// No Caching
    /// </summary>
    NoCaching = 0,
    /// <summary>
    /// Caching for a short time
    /// </summary>
    LightCaching = 1,
    /// <summary>
    /// Caching for moderate
    /// </summary>
    ModerateCaching = 3,
    /// <summary>
    /// Caching for a long time
    /// </summary>
    HeavyCaching = 6
}
```

The default value for `CacheTimeOut` is 20. Lets say you have `HeavyCaching` enabled. This would cache _most_ objects for 2hrs (120minutes). However, some core objects use non-default `CacheTimeOut` values. 

For example, portal aliases are have an initial value of 200 (so 20hrs cached in `HeavyCaching`). On the shorter side of things, Captcha tokens have a `CacheTimeOut` value of 2 (6mins in `HeavyCaching`). You should be able to sit on a page for 5 minutes in that configuration and the Captcha token would still be valid, however if you waited 7 minutes it should fail.

**Comment by shanewalker1595** [comment]
Thanks @ohine! This answered my question.

**Comment by ohine** [comment]
Anytime! I’m going to close this issue. If you have any other issues related, feel free to reopen it.
