### ISSUE TITLE
NuGet packages for v9.3.1

### ISSUE THREAD

**Issue by GerardSmit** [dnnsoftware/Dnn.Platform#2664]
9 days ago the tag `v9.3.1` was created but all the packages on NuGet are still on version 9.3.0. In the issue https://github.com/dnnsoftware/Dnn.Platform/issues/2486#issuecomment-456150895 there was a comment saying

> Starting with 9.3.0 and later the packages are built by the CI processes and will be readily available for all releases.

Is this not working yet?

**Comment by GerardSmit** [comment]
I'll close this issue because of my understanding from issue https://github.com/dnnsoftware/Dnn.Platform/issues/2663 is that v9.3.1 not released yet.

**Comment by brianafinney** [comment]
I've just downloaded 9.3.2 and am receiving same issue. Any update?

**Comment by valadas** [comment]
I see them here, any specific package you are looking for and not finding?

![image](https://user-images.githubusercontent.com/6371568/61003316-a34d7c00-a331-11e9-84ff-5423bc1851cd.png)

**Comment by valadas** [comment]
I see the bundle one too with all it's dependencies being >= 9.3.2
![image](https://user-images.githubusercontent.com/6371568/61003423-ec9dcb80-a331-11e9-994f-527ff530d01f.png)

**Comment by brianafinney** [comment]
I've downloaded the release in the first response and receive the same missing dependency. Do I need a new URL to be looking for this dependency? I've run the Install-Package and received this message. Any advice?

[cid:46472d1d-2e88-4427-9009-19d6ed7bac5c]
________________________________

**Comment by valadas** [comment]
Oh, could you have your local machine setup to use MyGet instead of NuGet by any chance ?
