### ISSUE TITLE
RFC: Update System.Web.WebPages Base Page

### ISSUE THREAD

**Issue by ahoefling** [dnnsoftware/Dnn.Platform#2672]
Part of: #2637 
Follow up: #2638 

## Description of problem
After the PR was merged I discovered that there is a web.config entry that specifies the base page the System.Web.WebPages. This has a dependency on DotNetNuke.Web.Razor which needs to be updated to the new standard so it is implied.

## Current Config
```
<system.web.webPages.razor>
  <pages pageBaseType="DotNetNuke.Web.Razor.DotNetNukeWebPage">
    <namespaces>
      <add namespace="WebMatrix.Data" />
      <add namespace="Microsoft.Web.Helpers" />
    </namespaces>
  </pages>
</system.web.webPages.razor>
```

# Proposed Config
Remove the node completely for now.

Once Razor Pages (See #2599) is implemented we will re-add this in.

# Potential Breaking Change
This change will have potential breaking changes and may need investigation or discussion. 

*speculation* 
Once we remove that node all Razor Templates will no longer automatically inherit from `DotNetNuke.Web.Razor.DotNetNukeWebPage` and they will inherit from the `System.Web.WebPages`. 

If this speculation is true then this will cause a breaking change. 

If not then it is safe to remove this.

# Real World Usages
In my inquiry to community members many specify their inherit at the top of the razor file explicitly so this may have a low impact.

Looking for feedback before proceeding :
@mitchelsellers @bdukes @ohine

**Comment by mitchelsellers** [comment]
FWIW the default documentation does encourage the use of a proper @inherit tag

**Comment by ahoefling** [comment]
Yes, but there is a feature that allows us to specify it in the web.config. I spent a few hours digging through what DNN does and what a small scale project can do with these overrides. I was able to swap out the inherited base class via the web.config. Unfortunately this is a very complex scenario in DNN. The top level web.config has 2 `<pages>` nodes which conflict with each other.

## Razor
```xml
<system.web.webPages.razor>
  <pages pageBaseType="DotNetNuke.Web.Razor.DotNetNukeWebPage">
    <namespaces>
      <add namespace="WebMatrix.Data" />
      <add namespace="Microsoft.Web.Helpers" />
    </namespaces>
  </pages>
</system.web.webPages.razor>
```

## Pages
```xml
<pages validateRequest="false" enableViewStateMac="true" enableEventValidation="true" viewStateEncryptionMode="Always">
  <namespaces>
    <add namespace="System.ComponentModel" />
    <add namespace="System.Data" />
    <add namespace="System.Data.SqlClient" />
    <add namespace="System.Drawing" />
    <add namespace="Microsoft.VisualBasic" />
    <add namespace="System.Globalization" />
    <add namespace="DotNetNuke.Services.Localization" />
    <add namespace="DotNetNuke.Entities.Users" />
    <add namespace="DotNetNuke" />
    <add namespace="DotNetNuke.Common" />
    <add namespace="DotNetNuke.Data" />
    <add namespace="DotNetNuke.Framework" />
    <add namespace="DotNetNuke.Modules" />
    <add namespace="DotNetNuke.Security" />
    <add namespace="DotNetNuke.Services" />
    <add namespace="DotNetNuke.UI" />
    <add namespace="DotNetNuke.Entities.Portals" />
    <add namespace="DotNetNuke.Common.Utilities" />
    <add namespace="DotNetNuke.Services.Exceptions" />
    <add namespace="DotNetNuke.Entities.Tabs" />
  </namespaces>
  <controls></controls>
</pages>
```

If I delete `<pages>` from the Top Level web.config my baseType inheritance works. So I believe that there is some conflict going on between these 2 nodes. The Razor documents state we can place a web.config in the `~/Views/` directory. The closest thing I could find is:

* `~/Portals/Web.config`
* `~/DesktopModules/MVC/web.config`

Unfortunately these web.configs don't appear to work.

I think we are close but we need to figure out how to get these nodes to work in harmony, this will remove the need for the `@inherit` directive which will simplify the razor

**Comment by ahoefling** [comment]
I updated this to an RFC as there are a lot of unknowns with this. I spent a couple days trying to get those web.config entries to work correctly but with no luck. There is some configuration going on between the different Razor Implementations we have (MVC, Razor 3, etc.). I just couldn't figure out exactly how to configure it.

Maybe @cnurse has some insights on how this all works

**Comment by valadas** [comment]
Is there any news on this issue, do we expect this for Dnn 10, does it need to stay as an RFC for now ?

**Comment by ahoefling** [comment]
I think this should stay as a RFC. In my initial testing I found it very difficult to update the base page and would be interested to hear from others on this.

**Comment by valadas** [comment]
This is a bit over my head, but just commenting so stalebot does not close it. This is still good to keep right @ahoefling ?

**Comment by sleupold** [comment]
this needs more input and investigation IMO, but is still valid for the move to .Net Core

**Comment by sleupold** [comment]
@ahoefling 
is this still needed to be kept open?

**Comment by ahoefling** [comment]
There could be some short-term benefits if we get this right, but I don't think it is necessary to implement anymore.
