### ISSUE TITLE
Unable to verify accounts on website portal

### ISSUE THREAD

**Issue by thabaum** [dnnsoftware/Dnn.Platform#2674]
## Description of bug
Provide a clear and concise description of what the bug is.

## Steps to reproduce
List the steps to reproduce the behavior:
1. Register User
2. Click on verification email link to verify account
3. Invalid verification code. message displayed

## Current result
Unable to verify account with link provided in verification email sent by DNN.

## Expected result
ability to verify account and complete registration process.

## Screenshots
If applicable, provide screenshots to help explain your problem.

## Error log
Paste the error log that is related to this issue.

## Additional context
I am having issues logging into one portal, I created a new user, was able to log in but I cannot verify it from email.

Another account did a password reset, recieved a message saying the following:

You have requested a Password Reset Token from Website, but Your account is pending approval.

Password can be reset after account is approved.

> No way to really resend verification links, and password reset does not do this for you although if they get a link to the email address with a link to reset the password you would think this would be enough to verify the user has access to that email account and can serve as a dual purpose email.  If not verified, verify the user when password reset token is used.

Also it seems the portals that have Username for Username work fine, this one portal I cannot log into anymore or verify accounts with uses "Email as Username"

I am getting pretty shy of the email as username function, and I may have switched this one portal back and forth potentially in the past which I understand could do some odd things.

Also having portals with different settings for username, couple with Username and a couple using Email as username with the option of Unique Email false... ? 

If a user with the same email account joins all 4 of the portals, maybe something to do with another issue...

## Affected version

* [x] 9.3.1.2

**Comment by thabaum** [comment]
https://www.dnnsoftware.com/answers/why-invalid-verification-code-when-clicking-link-in-user-verification-email-on-dnn-070301/?page=1

Found this as a solution.

Under SETTINGS > SEO

I turned OFF "Convert URLs to lowercase"  AND "Redirect Mixed Case URLs" which I had set to ON previously.

I was able to verify user accounts after switching these settings to OFF.  

I think both may be an issue however not sure which one exactly as I switch both to off and was able to verify accounts again on that portal.

So I would thing this would be a bug, if you have these set to ON the email verification system does not function.

**Comment by thabaum** [comment]
A portal on the same DNN instance has the redirect mixed case and conver to lowercase urls set to ON and I can verify accounts.

**Comment by mitchelsellers** [comment]
@thabaum Just confirming with your comments you mention that the workaround "fixed" one installation, but another installation with the same setting didn't fix?

**Comment by valadas** [comment]
I just tried the 4 combinations of those 2 settings (lowercase urls and redirect mixed case) and all 4 verifications worked in 9.4.0 RC. @thabaum if you can still reproduce the issue in 9.4 please open a new issue.
