### ISSUE TITLE
Make installation of dependency possible from the manifest

### ISSUE THREAD

**Issue by MaiklT** [dnnsoftware/Dnn.Platform#2676]
## Description of problem
When a package is dependent from another package there are two possibilities at the monent.

1. Add a dependency  
`<dependency type="Package">chartjs</dependency>`  
If the package is not installed the installation would fail with a more or less cryptic error message.

2. Include the full package in the manifest.

## Description of solution
A cleaner way would be the possibility to include a link to the installation package in the manifest, something like

`<dependency type="Package">`
`   <name>chartjs</name>`
`   <url>https://github.com/EngageSoftware/DNN-JavaScript-Libraries/releases/download/chart.js_2.7.3/chart.js_2.7.3.zip</url>`
`</dependency>`

When the download is not possible (e.g. in an Intranet server) the error message could display the link as well and give some explanation about it (e.g. "Please download the package chartjs from https://github.com/EngageSoftware/DNN-JavaScript-Libraries/releases/download/chart.js_2.7.3/chart.js_2.7.3.zip prior to installing this package.")

**Comment by valadas** [comment]
I am closing this issue in favor of #2614 which covers this use case and is a more discussed RFC that would solve this issue.
