### ISSUE TITLE
HTML/Text module: ntext should be changed to nvarchar(max)

### ISSUE THREAD

**Issue by MaiklT** [dnnsoftware/Dnn.Platform#2685]
## Description of Problem
The table HtmlText still uses ntext in 2 columns - this might cause performance issues

## Proposed Solution Option 1
Change ntext to nvarchar(max)

## Affected version

* [x] 9.3.0
* [x] 9.2.2
* [x] 9.2.1
* [x] 9.2
* [x] 9.1.1
* [x] 9.1
* [x] 9.0

## Possible Issues
Just altering the type of the columns does not help. ntext is stored in the BLOB space of SQL Server, as nvarchar(max) is stored in the data space. Just altering the type of the column leaves the data in the BLOB space as long as it is not updated. New records will be written to the data space.

The solution is either to run a script like

`UPDATE {databaseOwner}{objectQualifier}HtmlText SET Content = Content, Summary = Summary`

after altering the type, or create a temporary table, copy the data from the original table, delete the original table and rename the temporary table. Constraints and indexes have to be rebuilt.
There are also two stored procedures that are affected, these have to be altered as well.
I did that in the attached file. Feel free to use it.

[Module_HtmlText_Change_ntext_to_nvvarcharmax.SqlDataProvider.txt](https://github.com/dnnsoftware/Dnn.Platform/files/3062176/Module_HtmlText_Change_ntext_to_nvvarcharmax.SqlDataProvider.txt)

**Comment by sleupold** [comment]
IMO to update inplace is much easier or just use new columns and drop the old ones within the table.

**Comment by sleupold** [comment]
Did you check the datatypes in DNN library, if a type change is necessary?

**Comment by sleupold** [comment]
PS: performance should not be a real problem here, as we are typically reading and writing a single record in an indexed table.

**Comment by MaiklT** [comment]
1) a matter of taste, but sure, this is less code. The way I suggested has a positve side effect, as tables which are in use for a long time and have had lots of CRUD operations get defragmented this way.
2) No, what is the DNN Library Project and where can I check it? But normally strings are strings.
PS: Performance could be an issue on big sites with a lot of HTML modules, as reading from the BLOB space is slower than reading from the data pages. And finally: yes, ntext and text are "bad old style", and therefore we should change to "good new style" after 14 years ;-)

**Comment by sleupold** [comment]
this does not only affect HTML modules, there are a few columns still using this old data type.

**Comment by MaiklT** [comment]
Still an issue...

**Comment by MaiklT** [comment]
Still an issue...

**Comment by sleupold** [comment]
still a valid issue (for a few other columns as well)

**Comment by sleupold** [comment]
please assign to me,

**Comment by sleupold** [comment]
still on my plate

**Comment by sleupold** [comment]
reopen
please re-open, I still plan to submit a PR

**Comment by valadas** [comment]
Done

**Comment by sleupold** [comment]
@valadas thank you!

**Comment by sleupold** [comment]
still on my list...
