### ISSUE TITLE
OAuth2 Custom Providers: Thread Aborts With No Reason

### ISSUE THREAD

**Issue by ahoefling** [dnnsoftware/Dnn.Platform#2687]
## Description of bug
When building an OAuth2 Authorization Provider, during the login phase `OAuthClient.Authorize()` an exception is captured and is ignored that states the thread is aborted.

```
{"Thread was being aborted."}
    Data: {System.Collections.ListDictionaryInternal}
    ExceptionState: Unable to evaluate expression because the code is optimized or a native frame is on top of the call stack.
    HResult: -2146233040
    HelpLink: null
    InnerException: null
    Message: "Thread was being aborted."
    Source: "mscorlib"
    StackTrace: "   at System.Threading.Thread.AbortInternal()\r\n   at System.Threading.Thread.Abort(Object stateInfo)\r\n   at DotNetNuke.Services.Authentication.OAuth.OAuthClientBase.AuthorizeV2() ... <omitted stack> ..."
    TargetSite: {Void AbortInternal()}
```

## Steps to reproduce
List the steps to reproduce the behavior:
1. Create OAuth Authorization Provider
2. Install module
3. Login

## Details of problem
The OAuth `Authorize` workflow lives in the `OAuthClient` class of the `DotNetNuke.Library`. This is the class that is used to create custom OAuth Provider Modules. The Module will manually invoke
```var result = OAuthClient.Authorize();```

(Code Truncated for brevity)
```
public virtual AuthorisationResult Authorize()
{
    if (OAuthVersion == "1.0")
    {
        return AuthorizeV1();
    }
    return AuthorizeV2();
}

private AuthorisationResult AuthorizeV2()
{
    string errorReason = HttpContext.Current.Request.Params["error_reason"];
    bool userDenied = (errorReason != null);
    if (userDenied)
    {
        return AuthorisationResult.Denied;
    }

    if (!HaveVerificationCode())
    {
        var parameters = new List<QueryParameter>
                                {
                                    new QueryParameter("scope", Scope),
                                    new QueryParameter(OAuthClientIdKey, APIKey),
                                    new QueryParameter(OAuthRedirectUriKey, HttpContext.Current.Server.UrlEncode(CallbackUri.ToString())),
                                    new QueryParameter("state", Service),
                                    new QueryParameter("response_type", "code")
                                };

        HttpContext.Current.Response.Redirect(AuthorizationEndpoint + "?" + parameters.ToNormalizedString(), true);
        return AuthorisationResult.RequestingCode;
    }

    ExchangeCodeForToken();

    return String.IsNullOrEmpty(AuthToken) ? AuthorisationResult.Denied : AuthorisationResult.Authorized;
}
```

The problem has to deal with the following line of code:
```
HttpContext.Current.Response.Redirect(AuthorizationEndpoint + "?" + parameters.ToNormalizedString(), true);
```

The parameter request if the thread aborts or not and we are passing in `true`. If we update this code to `false` the thread will not abort.

### My Thoughts
Aborting the thread or continuing doesn't really matter for an OAuth2 integration, but it makes it **VERY** confusing to a module developer on what is happening when the error just reads the Thread was aborted. I think we should allow the thread to continue along and finish processing any logic that may exist in the custom module.

## Screenshots
N/A

## Error log
N/A

## Additional context
N/A

## Affected version

* [x] 9.3.0
* [x] 9.2.2
* [x] 9.2.1
* [x] 9.2
* [x] 9.1.1
* [x] 9.1
* [x] 9.0

## Affected browser

* [x] Chrome
* [x] Firefox
* [x] Safari
* [x] Internet Explorer
* [x] Edge

**Comment by mitchelsellers** [comment]
I believe that the value of true is used to stop processing of anything else that might be loading on the page (modules, skin objects, etc.)  Not sure if there is any real harm though in reverting to the default behavior.

@ohine @bdukes either of you have any experience on this one?

**Comment by ahoefling** [comment]
@mitchelsellers that makes sense and I really don't know all the deployment models and use cases of why this was implemented this way. 

If the intended behavior here is to stop processing because other modules/skins/etc could be processing I think we should re-write this function to make that clear.

Another option is simply add XML Docs to the `Authorize` function to describe possible exceptions so it is more clear to a module developer if they run into this scenario

**Comment by bdukes** [comment]
I wouldn't think it would be a problem to pass `endResponse: false` and avoid the `ThreadAbortException` here.

**Comment by ahoefling** [comment]
When interacting with the `Authorize` code if you immediately get back the status code of `AuthorisationResult.RequestingCode` it will be clear you will need to use something else such as `OnUserAuthenticated()`

@mitchelsellers @ohine any thoughts on this? If not I can go ahead and make the change and submit the PR

**Comment by valadas** [comment]
I am assuming this would not be a breaking change and could be handled in 9.4.1, but correct me if I am wrong with that assumption.

**Comment by ahoefling** [comment]
I don't believe this to be a breaking change, but there could be side-effects with it. We should really test this scenario before merging any PRs that fix this.

As of right now I am not going to have time to work on this for 9.4.1, so you can mark it up for grabs or help wanted. If someone completes a PR for this, I would be more than happy to review the code

**Comment by valadas** [comment]
Merged
