### ISSUE TITLE
Homepage Register Login User Controls not visible on some portals on few DNN instances

### ISSUE THREAD

**Issue by thabaum** [dnnsoftware/Dnn.Platform#2690]
## Description of bug
This has been a long time issue I am now convinced might be a bug.

On the homepage of most of my portals but not all I do not see the Register Login Account UI at the top of the webpage.  I can use any theme same result.  I go to another page on the website the user controls appear on all other pages except the homepage.  I think it has something to do with pages with the name "Home".  I can change the homepage in settings and still when I visit a page named Home user account controls do not appear in the header.

I have more than one portal and it seems sometimes it comes back for a while then dissaapears.  However most all the time it is missing from the header of most sites on more than one DNN instance.

Has anyone else experienced this issue or know of a way to resolve?

* [x] 9.3.0
* [x] 9.2.2
* [x] 9.2.1
* [x] 9.2
* [x] 9.1.1
* [ ] 9.1
* [ ] 9.0

## Affected browser

* [ ] Chrome
* [ ] Firefox
* [ ] Safari
* [ ] Internet Explorer
* [ ] Edge

**Comment by ohine** [comment]
Is your 404 page configured as your homepage?

**Comment by thabaum** [comment]
Why yes it is...   In this settings page same area the cookie consent settings, although it does fit under privacy, it does control site behavior default pages and relates to the same type of settings set in this location.

I set the error pages to 404 and 500 pages and it seems to work again.  Thanks for the help!

**Comment by thabaum** [comment]
Under SEO > Url Management > General Settings I also see setting for 404 pages which is a bit confusing as to which to set and what results you get by setting them.

**Comment by valadas** [comment]
Themes can have a special 404 layout and the default theme 404 layout does not have the login and register controls, there was some reason for that and I cannot remember now, but it was a wanted behaviour for some reason. A workaround if you do need this would be to edit the 404 layout and add those in.
