### ISSUE TITLE
Add Update Service checkbox to Installer

### ISSUE THREAD

**Issue by hismightiness** [dnnsoftware/Dnn.Platform#2694]
## Description of problem
When you install DNN, the installer containers an opt-in for sending usage statistics to DNN Corp, but the same option is not included for the update service.  Every new website is opted into this automatically without being prompted first.  This is now against GDPR standards as well.

## Description of solution
Add another checkbox and description above/below the usage message and update the text for both to be concise and specific about what each does.  Both checkboxes need to be unchecked by default.  When checked, the normal logic that is performed today shall continue to be run.  When unchecked, the update service will not be used.

## Description of alternatives considered
None at this time.  An update service is necessary to learn more about which technologies to support now and in the future, and when to update those dependencies.  (Though, this information should be more anonymous in the future.)  The update service will also help to run the extensions updates.

## Affected version

* [x] 9.3.1
* [x] 9.3.0
* [x] 9.2.2
* [x] 9.2.1
* [x] 9.2
* [x] 9.1.1
* [x] 9.1
* [x] 9.0

## Affected browser

* [x] Chrome
* [x] Firefox
* [x] Safari
* [x] Internet Explorer
* [x] Edge

**Comment by nvisionative** [comment]
I implemented the unchecked by default in a previous release, but it appears it has been reverted somehow.  🤔

**Comment by bdukes** [comment]
Do we need a separate issue to change the default URL to https://dnnplatform.io, per https://www.dnnsoftware.com/community-blog/cid/156713/dnn-platform-update-service?

**Comment by mitchelsellers** [comment]
Yes, but ideally I want to do this for 10.x once the dnnplatform.io is in its final home

**Comment by valadas** [comment]
Hey stalebot, this is still good to keep.
