### ISSUE TITLE
Digital Assets: Azure folders are slow to open

### ISSUE THREAD

**Issue by mikebigun** [dnnsoftware/Dnn.Platform#2697]
## Description of bug
It takes a lot of time to get Azure directory listing. On a customer environment it takes around 25-30 seconds to get folder opened when navigating from one directory to another one.

## Steps to reproduce
1. Go to PB `Settings` -> `Connectors`
2. Add `Azure connector`, enter valid account name and token
3. Go to `Manage` -> `Site Assets`
4. Synchronize Azure folder and all subfolders
5. Navigate from one folder to another one

## Current result
Currently, it takes a while (up to 30 secs) to see content of azure directories.  

## Expected result
Azure folders should open fast without huge delay.

## Screenshots

![image](https://user-images.githubusercontent.com/22524011/56230965-fe026f00-6085-11e9-9cdb-a3edb99f88a1.png)

## Affected version

* [x] 9.3.0
* [x] 9.2.2
* [x] 9.2.1
* [x] 9.2
* [x] 9.1.1
* [ ] 9.1
* [ ] 9.0

**Comment by valadas** [comment]
@dnnsoftware/approvers PR is merged, please close this issue.
