### ISSUE TITLE
RFC: Make Default Module Action Menu Configurable

### ISSUE THREAD

**Issue by mikesmeltzer** [dnnsoftware/Dnn.Platform#2700]
## Description of Problem

Currently, the path to the default Module Action menu control (/admin/Menus/ModuleActions/ModuleActions.ascx) is hardcoded within the C# in the Container base class and does not allow a developer to configure the site to use a different action menu control by default on a per site basis. 

The default action menu can be overridden on a per module basis by using a container that uses it's own action menu control. However, it would be ideal if we could define the action menu at a portal level and override the default action menu regardless of the container being used across the site, unless the container supplied it's own action menu as you can today.

## Proposed Solution

Add a new Portal Setting called DefaultActionMenu, similar to how the default skin path, container path, etc. are stored.

Have the setting defaulted to the existing action menu path and allow users to swap this behaviour out by changing the setting value to point to an action menu control of their choosing.

This change would include the SQL to include the new portal setting in the DB, change the container base class to read from the portal setting instead of the hardcoded path, and changes to the Portal Settings and Portal Settings Controller to add the new setting into the API.

## Requested Feedback

Does anyone have other ideas on how to do this? 

Is there something I'm missing or not accounting for? 

Are there any specific areas for testing that should be called out other than testing the behaviour of changing the module action menus? Since it's a new Portal Setting, should areas like the site import/export be doubled checked, etc. ?

**Comment by mitchelsellers** [comment]
@mikesmeltzer Overall I'm all for this, however, I'm curious regarding options that we have available with the potential future of .NET Core.

We will be switching the skinning engine, at some point, to Razor and will no longer be able to support inclusion of .ascx files.  Creating this as an extension point will add to the possible breaking changes and code that has to be updated for .NET Core.

But that is in the future.  Any thoughts on how to minimize that impact?

**Comment by mikesmeltzer** [comment]
Thanks for the feedback, Mitch.

I believe the impact should be no greater than it would be without making this change since the ability to override the action menu already exists today by overriding it at the container level. It isn't really making a new extension point as it is just giving a more global way of doing the same thing that exists today but without having to update the code on each container that is being used.

I'm assuming the methodology of having a skin, a container, a module remains the same (or very closely aligned to what we do today) when razor is used for skinning.  In that case, I'm guessing that the current core ascx based module action menus would just end up being a .cshtml that is injected as a RenderPartial or similar when the container is being loaded. In that case, the existing module action menu and any custom ones (in both the existing container level override and this new global method) should work as expected with obviously requiring developers to upgrade their action menus from ascx to cshtml (and the database record recording the .ascx path). This would need to happen regardless unless we dropping the existing support for custom action menus at the container level. 

If we are talking about using action menus, containers, etc. differently in the future of skinning than we do today (minus just the razor change) then that is a different discussion which I need to have more info on first :)

**Comment by mitchelsellers** [comment]
@mikesmeltzer You are most likely correct, the change isn't expected to be huge, but it would still be a change, but given the other extension point it isn't much additional burden.

I'd be all for a contribution with this included

**Comment by mikesmeltzer** [comment]
I completely understand that it is still a change and we will need to account for it going forward.  Given that is identical to current functionality, albeit at a level higher up, then whatever the solution to account for the container level action menu should also work for this too causing minimal impact.

Sounds good. I will leave this open for a few more days in case there is other feedback.  If nothing comes in then I will close this, create an issue and submit a PR for review shortly after. 

Would this be something that would be appropriate to include in 9.4 (assuming all is well with the code, etc.) or would we have to wait for a later verison to include?

**Comment by mitchelsellers** [comment]
Yes, I don't see any concern with this being included in 9.4 assuming it comes in prior to the code-freeze date.

**Comment by mikesmeltzer** [comment]
Closing this RFC and will complete the work under an issue that links to this RFC.
