### ISSUE TITLE
Missing Dnn.ClientDependency package restoring

### ISSUE THREAD

**Issue by RD-Processa** [dnnsoftware/Dnn.Platform#2702]
## Description of bug
Restoring package fails on "DNN_Platform_9.3.1.2_Source.zip".

## Steps to reproduce
1. Download source package (DNN_Platform_9.3.1.2_Source.zip) from [github.com] (https://github.com/dnnsoftware/Dnn.Platform/releases/tag/v9.3.1)
2. Unzip all files
3. Open DNN_Platform.sln using Visual Studio 2017
4. Try to restore nuget packages for solution.... (nuget.exe restore 'Path\To\DNN_Platform.sln'

## Current result
Unable to find version '1.9.2.7' of package 'Dnn.ClientDependency'.

## Expected result
All packages were restored.

## Affected version
* [x] 9.3.1

**Comment by valadas** [comment]
@dnnsoftware/tag are the source packages still a valid way to build from source or this issue boils down to removing the source packages and documenting how to clone and build the solution locally ?

**Comment by david-poindexter** [comment]
@valadas I would be in favor of removing the Source packages from releases moving forward.  It is definitely not the preferred local build method and I am not sure it has worked in a really long time.  That said, there may be some that still prefer to use this page for debug purposes.  That said, I still think this is not the best method giving the tooling we have now.  What say others?  /cc @dnnsoftware/approvers

**Comment by mitchelsellers** [comment]
This process has already been changed starting with 9.4.0 and later.

We are no longer publishing the source package, the source download that is available is auto-generated by GitHub now based on the tag for the release
