### ISSUE TITLE
HTML Editor with FontAwesome Icons visible while editing in WYSIWYG editor

### ISSUE THREAD

**Issue by thabaum** [dnnsoftware/Dnn.Platform#2704]
Feature request with the ability to see fontawesome icons and possibly even choose them from a list sort of like emogi's.

Maybe you click an icon to enter an icon and you enter the "fas fa-comments" for example and it shows up in the editor to help describe a section.

Also shortcodes built into the editor that display the content accurately would be a nice bonus that use things such as bootstrap and fontawesome icons to help create common content rapidly.

**Comment by valadas** [comment]
This would have to be a plugin to the CKEditor and should be done in this repository https://github.com/DNN-Connect/CKEditorProvider However I would advice discussing this before submitting an issue to make sure someone is actually interested in developing such plugin. In fact, maybe there is already such plugin that would just need adapting to use with the dnn provider wrapper to CKEditor...
