### ISSUE TITLE
Connect the HTML editor or Site Assets to public domain content

### ISSUE THREAD

**Issue by thabaum** [dnnsoftware/Dnn.Platform#2705]
It would be pretty special to see a way to easily connect to not only open source projects for DNN but also sources for content that DNN can search for to help you create a site with fun content that relates to your project such as videos, photos, music and more offered for commercial or private use in the public domain.

We could collaberate some great sources and get them connected to DNN users easily.  Possibly an image crop/resizer ability when downloading from sources could be a feature within that would be helpful.

**Comment by valadas** [comment]
I am closing this issue since nobody commented for some months and I am assuming nobody is currently willing to pick this up. @thabaum if I am wrong and there is interest from someone in developing this, just comment about it and I will be happy to reopen it.
