### ISSUE TITLE
Ability to Save Shortcodes or code as templates in HTML Editor

### ISSUE THREAD

**Issue by thabaum** [dnnsoftware/Dnn.Platform#2706]
Feature request to have the ability to save shortcode that has been created for a site by a content manager(s) that use the DNN HTML Editor may get access to reused on other pages.  Maybe a repository system people can create shortcodes to be used in DNN available on github downloads that DNN can access.

User can select from list of available shortcode examples by category or types defined when creating the template code file with the shortcode and injects it where the curser is while editing in code editor view.

Most all options are greyed out during code view, it would be nice to see some appear.

Also some ways to access some common dnn objects with an intellesense designed to help access dnn resources.  This could also be added to the module designer if it does not already have intellisense of some type.

Suppose Im full of ideas today going to take a pause them now as maybe this stuff is a bit far fetched for DNN right now.  Just thought it was something to think about if it is not in focus right now.

**Comment by valadas** [comment]
@thabaum sorry for closing so many of your issues, I am just trying to clean the backlog of stale issues that are not yet actionable or had not much conversation towards making them actionable. If you see there is interest from someone to develop such feature, then the proper repository for this one would be https://github.com/DNN-Connect/CKEditorProvider
