### ISSUE TITLE
Member directory filtering by list field type

### ISSUE THREAD

**Issue by cerullo** [dnnsoftware/Dnn.Platform#2707]
## Description of problem
In the filter settings of the member directory, it doesn't allow the use of "List" fields as a filtering option. This module will only allow fields that are either one of these types to be used as filters:

- Text
- Region
- Country
We actually dig into DNN code to find that and here is what we see:

if (definition.DataType == textType.EntryID || definition.DataType == regionType.EntryID || definition.DataType == countryType.EntryID)

It only allows types of - Text, Region and Country.

## Description of solution
Provide the ability to filter by the List field type. 

## Description of alternatives considered
We would have to make clients manually type in data into a text field and risk typos in order to search the data. 

## Affected version
I know the ones below are effected for sure. I have not tried others. 

* [x] 9.2.2
* [x] 9.2.1
* [x] 9.2
* [x] 9.1.1

## Affected browser
all browsers

**Comment by sleupold** [comment]
please be aware that the underlying stored procedure, contained in the core, does not support filtering by data type list.

**Comment by valadas** [comment]
Give the current code and the underlying stored procedure, this appears to be by design. Is someone interested in developing this change in let's say within the next year?

**Comment by cerullo** [comment]
Yes this is still a problem for a number of my clients. They have very detailed member directories and need the search to work properly
