### ISSUE TITLE
GetNETFrameworkVersion displays an incorrect value

### ISSUE THREAD

**Issue by ohine** [dnnsoftware/Dnn.Platform#2710]
## Description of bug
We need to update the `GetNETFrameworkVersion` function to support the display of runtime versions above 4.6. We should also remove the checks for anything below 4.7.2 as it's impossible for the application to even load.

https://github.com/dnnsoftware/Dnn.Platform/blob/584b0f54bd6b6d237594dd9f96053f14db0b1a53/DNN%20Platform/Library/Common/Initialize.cs#L151-L203

![image](https://user-images.githubusercontent.com/1687117/56402878-27a9ca80-622d-11e9-998a-35eeda2a2bd3.png)

**Comment by ohine** [comment]
Related issue #2615

**Comment by mitchelsellers** [comment]
Working on this right now
