### ISSUE TITLE
Custom role user can not upload a file inside CKEditor despite having Edit, Manage permission to Role for HTML Module & HTML Editor Manager

### ISSUE THREAD

**Issue by Mhtshum** [dnnsoftware/Dnn.Platform#2711]
## Description of bug
Custom role user can not upload a file inside CKEditor despite having Edit, Manage permission to Role for HTML Module & HTML Editor Manager

## Steps to reproduce
Login as host
1. Create custom role namely "test"
2. Create a user namely "testuser1", and assign it role "test"
3. Create a page "test-file-upload", with permission to role "test" to view & edit. In advanced tab, Under "Modules on Page" go in setting of HTML Module. In settings give "Edit Module" permission as well to role "test"
4. Go to PB > Settings > Extensions > Modules and edit the HTML Module. In the Site Settings tab you'll find a way to grant the CAN DEPLOY permission to desired roles.
5. Go to PB > Site Settings > Site Behavior > More> Click on "Open HTML Editor Manager", Select the "File Browser Settings". In "Allowed Roles", check on "test" role, also set the "Upload File Limit" for test role
6. In other different browser logged-in as "testuser1", browser to "test-file-upload" page and click on "pencil" on right, open page in edit mode.
7. Hover on HTML Module. Click on Edit content. Then CKEditor will be loaded, click on Image as shown in screenshot namely "image-icon".

## Current result
 Then in pop-up no "Upload" tab shown (which does show up when HOST user) check screenshot "No-Upload-tab"
When click on "Browser Server" inside Image Info tab, then another pop-up appear with File-upload disabled.

## Expected result
 Ist Pop-up should show "Upload" tab. 
When click on "Browser Server" inside Image Info tab, then another pop-up should appear with File-upload icon  Enabled.

## Screenshots
![image-icon](https://user-images.githubusercontent.com/43787378/56420065-f0cbc700-62b5-11e9-8595-1db831f1b209.png)
![No-upload-tab](https://user-images.githubusercontent.com/43787378/56420241-a434bb80-62b6-11e9-9c91-3654cba3028e.png)
![Browser-Server](https://user-images.githubusercontent.com/43787378/56420367-1b6a4f80-62b7-11e9-9a3b-9e875d3e7de5.png)
![File-Upload-Disable](https://user-images.githubusercontent.com/43787378/56420397-4785d080-62b7-11e9-911a-0b65b86ef3da.png)

## Affected version
* [x] 9.3.2
* [x] 9.3.1
* [x] 9.2.2
* [x] 9.2.1
* [x] 9.2
* [x] 9.1.1
* [x] 9.0
* [x] 8.5

**Comment by sleupold** [comment]
please make sure, you granted "write" permission to the user (or one of the roles he is member of) for the upload folder in PB >Manage > Website Files

**Comment by Mhtshum** [comment]
Thnx alot @sleupold.  Closing this as it is achievable.
