### ISSUE TITLE
Removal of AT.MSBuild.Tasks

### ISSUE THREAD

**Issue by valadas** [dnnsoftware/Dnn.Platform#2720]
It looks like we are importing AT.MSBuild.Tasks but not doing anything with that. Can this be safely removed or is there something I am not aware of about this ?

Here is what I find when searching the repository: https://github.com/dnnsoftware/Dnn.Platform/search?q=at.msbuild&unscoped_q=at.msbuild

Tried to search google about what this is, but google has a hard time with searches with a dot in them.

**Comment by nvisionative** [comment]
AT may stand for **AllTextFiles**, which is used in **ItemName** within **FindUnderFiles**.  I didn't have time to search the project for this but wanted to post here since it may help lead you down the right path.

Example:
```
<ItemGroup>
    <MyFiles Include="*.txt" />
</ItemGroup>
<FindUnderPath Path="$(OutDir)" Files="@(MyFiles)">
    <Output TaskParameter="InPath" ItemName="AllTxtFiles" />         
</FindUnderPath>
```

**Comment by valadas** [comment]
I do not think that is it, there is an actual library by that name in the build folder but it does not appear to be used anywhere.

**Comment by mitchelsellers** [comment]
@ohine Any ideas?

**Comment by valadas** [comment]
Well, I guess let's try to remove it and see what happens...

**Comment by david-poindexter** [comment]
@valadas is this still a valid issue or has it already been addressed?

**Comment by valadas** [comment]
I do not see it anymore, my guess is @donker handled that in the build reorganization, let's close this... One less issue :)
