### ISSUE TITLE
Removal of Castle.Core

### ISSUE THREAD

**Issue by valadas** [dnnsoftware/Dnn.Platform#2721]
It looks like we get the Castle.Core package but are not doing anything with it, can this be safely removed or is it used somewhere I am not aware of?

See this search https://github.com/dnnsoftware/Dnn.Platform/search?q=castle.core&unscoped_q=castle.core

**Comment by mitchelsellers** [comment]
This is required by NSubstitute, which is required by NTestDataBuilder.  So currently is used by proxy

**Comment by valadas** [comment]
Thanks @mitchelsellers is there a trick to find out what needs what or you just happened to know ?

**Comment by bdukes** [comment]
@valadas You can see what, for example, NTestDataBuilder depends on at https://www.fuget.org/packages/NTestDataBuilder/1.0.2, or what depends on Castle.Core at https://www.fuget.org/packages/Castle.Core/dependents

**Comment by valadas** [comment]
Nice, good to know!
