### ISSUE TITLE
Removal of DotNetZip

### ISSUE THREAD

**Issue by valadas** [dnnsoftware/Dnn.Platform#2723]
DotNetZip is a dependency in here https://github.com/dnnsoftware/Dnn.Platform/search?q=dotnetzip&unscoped_q=dotnetzip

It looks like this is used here in the ZipManager ExtractZip method https://github.com/dnnsoftware/Dnn.Platform/search?q=ionic.zip&unscoped_q=ionic.zip

But then it appears that nothing calls ZipManager.ExtractZip https://github.com/dnnsoftware/Dnn.Platform/search?q=ExtractZip&unscoped_q=ExtractZip

Can be safely removed or do we need this denpendency around for some reason I might not know ? As far as I know we use SharpZipLib only or framework methods, but correct me if I am wrong.

**Comment by mitchelsellers** [comment]
It looks like this is used internally to the test projects, this could be removed
