### ISSUE TITLE
Removal of Effority Ealo support in DDRMenu

### ISSUE THREAD

**Issue by valadas** [dnnsoftware/Dnn.Platform#2724]
DDRMenu used to support some third party localization modules. Localization has been part of the core for quite some years now. Can we safely remove support for Effority Ealo in the DDRMenu, do we need to deprecate this and remove it later?

See https://github.com/dnnsoftware/Dnn.Platform/blob/development/DNN%20Platform/Modules/DDRMenu/Localisation/Ealo.cs

**Comment by sleupold** [comment]
AFAIK EALO hasn't been updated since DNN 5

**Comment by mitchelsellers** [comment]
I did some digging on this, and two of the providers in this are for extensions that are no longer supported.  Additionally we have confirmed posts in the forum that the implementations do not work on 9.x.  

As such, I've submitted a Pull Request to flag these as Obsolete, and special removal to be included in version 10.x unless we have a major concern against this.
