### ISSUE TITLE
Removal of json2.js

### ISSUE THREAD

**Issue by valadas** [dnnsoftware/Dnn.Platform#2725]
We have json2.js file here https://github.com/dnnsoftware/Dnn.Platform/blob/development/Website/Resources/Shared/scripts/json2.js but I do not see that we use it anywhere. This was used for very old browsers that did not support json serialization and deserialization (IE7 and bellow). 

Can this be safely removed or do you see any risk in removing that ?

**Comment by mitchelsellers** [comment]
This sure seems like it could be easily removed.

@bdukes or @ohine any idea

**Comment by bdukes** [comment]
It's used in https://github.com/dnnsoftware/Dnn.Platform/blob/03990b51e4c6f078a774401afbaf305676faf41f/DNN%20Platform/Modules/Journal/View.ascx.cs#L62, but since it's only for IE < 8, I have no problem removing it (just also remove that reference)
