### ISSUE TITLE
Removal of NSubstitute

### ISSUE THREAD

**Issue by valadas** [dnnsoftware/Dnn.Platform#2727]
We are importing NSubstitute from Nuget but I do not see it used anywhere. Can this be safely removed or does anyone have a reason not to?

**Comment by mitchelsellers** [comment]
Best way to test this would be to uninstall the package and see what happens

**Comment by valadas** [comment]
Cool, will do. Mainly wanted to log these to not forget to come back to them I thought I would ask at the same time.

**Comment by mitchelsellers** [comment]
Actually, I just dug into this one.  This item IS Used, it comes in as part of the NTestDataBuilder package, and cannot be removed

**Comment by valadas** [comment]
Ha ok, thanks
