### ISSUE TITLE
9.3.2 RC0 timeout during clean installation

### ISSUE THREAD

**Issue by valadas** [dnnsoftware/Dnn.Platform#2743]
## Description of bug
During clean installation, sql scripts still timeout on less than basic servers.

## Steps to reproduce
List the steps to reproduce the behavior:
Try to do a clean 9.3.2 RC0 install, notice timeout error

## Current result
I got a timeout in the DotNetNuke.Data.SqlDataProvider in the section where it tries to insert more than 5000 rows in the Lists table.

## Expected result
Installation should run fine

## Error log
Huge error log, but basically a timeout during creation of the data that goes into the Lists table for the countries and regions (more than 5000 records in one go).

## Additional context
This is on a not so low spec server, dual xeon physical server, 2 sockets x 8 cores, 16 GB RAM about half used. raid5 array of spinners, not near full at all. There was already a PR for adding more GO statetements on some sql scripts, maybe we also need more here, maybe run this part in two 2500 rows batches (cut it in half)...

## Affected version

* [x] 9.3.2
* [ ] 9.3.1
* [ ] 9.2.2
* [ ] 9.2.1
* [ ] 9.2
* [ ] 9.1.1
* [ ] 9.1
* [ ] 9.0

## Affected browser
Not browser related

**Comment by OllyHodgson** [comment]
I can verify 9.3.2 fixed this issue for me. It installed fine on the lowest spec Azure free trial app service + sql server.
