### ISSUE TITLE
several issues in export/import area

### ISSUE THREAD

**Issue by zyhfish** [dnnsoftware/Dnn.Platform#2747]
## Description of the bug
I found several bugs around the export/import area in some scenarios.

## Steps to reproduce
1. install evoq 9.3.0 and login as host; 
2. enable version/workflow in portal level but disable some specific pages' version and workflow settings; 
3. set some modules expired on the page; 
4. try to export the site and import it to a new site. 

## Current result
1. the version/workflow will be disabled in portal level, some of the pages will not be published after import; 
2. the expired modules will not expire in imported site; 
3. in some situations the LocalizeVerionGuid will be duplicated as this value is not unique, it will cause import missing some pages.

## Expected result
Import should work fine in the described situations.

## Affected version
* [x] 9.3.2
* [x] 9.3.1
* [x] 9.2.2

**Comment by ohine** [comment]
Closing issue as PR was merged.
