### ISSUE TITLE
Upgrading to 9.3.1 loses custom login module

### ISSUE THREAD

**Issue by doodlleus** [dnnsoftware/Dnn.Platform#2749]
upgrading from 9.2.2 to 9.3.1
All of a sudden our custom authentication service (based on the AuthenticationServiceBase class does not render in the UI. The code behind still fires but not a single UI element renders until we swap the enabled suth back to default in the Authentication table in the database.

Looking in the DOM, nothing is being hidden, it is simply not rendered

**Comment by doodlleus** [comment]
Ok have done some research on this and it seems that to enable a custom authentication module you still have to leave IsEnabled=True on the Authentication DB table for the DNN provider (effectively meaning that both rows would be set to true). Then, in order to "disable" the DNN provider, you set the portal setting, DNN_Enabled to False. the second part was always the case but the requirement to leave the default provider enabled even if you don't want to use it is a new issue that i believe is a bug

**Comment by mitchelsellers** [comment]
This is an interesting one, I'll try to dig into this should not be the case.

**Comment by mitchelsellers** [comment]
Did some digging in this, it was an inadvertent change introduced with this commit https://github.com/dnnsoftware/Dnn.Platform/commit/6ae6f179b476220738e8ed4b4279ebf020d0d4b9#diff-2ef869097cab8668927ce9c3408adaee

**Comment by valadas** [comment]
Closing, PR merged
