### ISSUE TITLE
9.3.1 Cannot Edit Log Settings in Admin Log

### ISSUE THREAD

**Issue by tpperlman** [dnnsoftware/Dnn.Platform#2752]
## Description of bug
After upgrading to the latest DNN v9.3.1 release, I cannot edit any of the individual log settings in the Log Settings tab of the Admin Log.

## Steps to reproduce
1. Login as an admin, and click on "Admin Logs" on the persona bar.
2. Click on the "Log Settings" tab.
3. Click the pencil icon next to any of the log settings and notice that the box highlights in blue but the settings window does not appear below it as it does in previous releases.

## Current result
The setting panel to make changes to the log does not appear.

## Expected result
The setting panel should appear below the selected log.

## Screenshots
![Annotation 2019-05-01 161244](https://user-images.githubusercontent.com/1871915/57039932-046b1c00-6c2c-11e9-8020-f324f6ef8986.jpg)

## Affected version
* [x] 9.3.1

## Affected browser
* [X] Chrome
* [X] Firefox
* [ ] Safari
* [ ] Internet Explorer
* [X] Edge

**Comment by sleupold** [comment]
I suggest upgrading to DNN 9.3.2, which has been released today and test again.

**Comment by tpperlman** [comment]
Thank you, I will review and follow up. On a separate note it is strange how releases are no longer announced on the Community Blog or even DNN Blog. I had no idea v9.3.2 was going to be released so quickly after v9.3.1.

**Comment by valadas** [comment]
It literally just got released today :) I guess the announcements are coming soon.

**Comment by mitchelsellers** [comment]
@tpperlman We need to continue to improve on the release notes aspect of things.  GitHub is the final source of truth for releases.

But we do keep the Roadmap page updated with the current plan for releases: https://www.dnnsoftware.com/community/learn/roadmap

**Comment by tpperlman** [comment]
Thank you all for your prompt replies and dedication to DNN. I am happy to report that the issue has been resolved by upgrading two of my affected DNN v9.3.1 sites to v9.3.2.
