### ISSUE TITLE
Pages are serving 404s because of 'hasbeenpublished' not being marked as '1' if tab permissions already exist during page creation

### ISSUE THREAD

**Issue by Creech99** [dnnsoftware/Dnn.Platform#2756]
## Description of bug
When users are copying existing DNN pages, end users have found they are unable to view pages and get a 404 without logging into the DNN CMS with an elevated account, even with "all users" have view permissions on the page. 
Upon further investigation we found that 'hasbeenpublished' was set to a value of '0' in the tabs table for the pages where this was an issue. The resolution so far when finding this problem has been setting 'hasbeenpublished' value from '0' to '1' in the tabs table.

Our developers have taken a look at the code and found that the step for page creation goes as follows:
1.) Add Tab to the DB
2.) Save permissions
3.) Mark as published

It is currently not making it to step 3 because if the permission already exists in the permissions table, a duplicate key error will occur and it will never get to step 3 to mark the page as "published"

A workaround that we've used is modifying the "AddTabPermission" storedProc to check if the permissions exist in the tabpermission table first and if it does to not try to insert the permission. Since making that change we have yet to have the 'hasbeenpublished' problem. 

We would like this problem either resolved or the change incorporated into the build so that we don't have to maintain this change.

## Steps to reproduce

1. Go to pages 
2. Click on page to be copied and click "..." -> Duplicate
3. After page is copied, modify page as needed
4. Navigate to the page without being logged in
5. Page serves a 404

## Current result
Page serves a 404 until 'hasbeenpublished' is set to '1' in the tabs table for the page

## Expected result
Page should serve a 200 with content without logging into the CMS

## Error log
Message="System.Data.SqlClient.SqlException (0x80131904): Cannot insert duplicate key row in object 'dbo.TabPermission' with unique index 'IX_TabPermission_Tabs'. The duplicate key value is (23969, 3, 1099, <NULL>).
The statement has been terminated.
at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)

## Additional context
We are running 700+ DNN websites and have modified the stored proc to resolve this issue, but would like this fixed or incorporated into the build so we don't have to maintain the change after every upgrade.

## Affected version
DNN Platform
* [x] 9.2.2

## Affected browser

* [X ] Chrome
* [X ] Firefox
* [ X] Internet Explorer

**Comment by valadas** [comment]
@Creech99 is there something more to make this happen, I use that feature in multiple versions of Dnn including 9.2.2, could also not reproduce in 9.4.0 ? Could this be an Evoq install or a previous Evoq or Professional edition migrated to Platform ? Are you able to reproduce the issue on a clean 9.3.2 install ?

**Comment by valadas** [comment]
Closing this issue due to lack of response from original submitter.
