### ISSUE TITLE
When changing language, keep the remanting url intact instead of reverting to page url

### ISSUE THREAD

**Issue by eXistenZe** [dnnsoftware/Dnn.Platform#2760]
## Description of problem
Not sure if this is the right place to suggest these things, but if it isn't, please point me to the right one.

When changing language in the top icons, any additional query strings, params, etc get removed and the url reverts to page default. For example:
If I'm viewing:
https://site.com/en-us/research/current_page/stats/seedetails=2
and I change the language, it will revert to:
https://site.com/fr-fr/research/current_page
since it's the page url.

## Description of solution
https://site.com/en-us/research/current_page/stats/seedetails=2
should change to:
https://site.com/fr-fr/research/current_page/stats/seedetails=2

## Description of alternatives considered
None that I think of.

## Affected version
all

## Affected browser
all

**Comment by donker** [comment]
Should be fixed in 9.4.0

**Comment by eXistenZe** [comment]
This was never fixed for me. Specially in 2sxc apps where views pick the url from added /something. When changing language, it will revert to the page url, removing any added parameters.
