### ISSUE TITLE
Extension Installation Fails on Azure 

### ISSUE THREAD

**Issue by meetmandeep** [dnnsoftware/Dnn.Platform#2766]
Extension packages with large amount of files fail installation on Azure with following error message:

Info Creating backup of previous version - **Filename**
Failure Installation Failed - ResourceFile

@mitchelsellers Let me know if you need any further information. Thanks

**Comment by mitchelsellers** [comment]
The same error as this is being reported: https://dnntracker.atlassian.net/browse/DNN-9838
