### ISSUE TITLE
Removal of SolPart from Distribution

### ISSUE THREAD

**Issue by mitchelsellers** [dnnsoftware/Dnn.Platform#2767]
## Description of problem
DNN is still distributing the SolPartMenu component, however it doesn't work in the current versions of DNN.

This needs to be removed.  However, it impacts the \Admin\Skins\Nav.ascx control that has a dependency on the SOlPart menu for rendering.

## Description of solution
Removal is needed, however, this could be a breaking change.  Should "Nav.ascx" be removed?

## Affected version

* [x] 9.3.2
* [x] 9.3.1
* [x] 9.2.2
* [x] 9.2.1
* [x] 9.2
* [x] 9.1.1
* [x] 9.1
* [x] 9.0

@dnnsoftware/tag any suggestions on how/when to do this?

**Comment by ohine** [comment]
I think we're safe removing it. I guess the question comes down to do we want to also remove it on upgrades or just let it be and provide some guidance in a blog on manual removal?

**Comment by mitchelsellers** [comment]
I guess the question is what do we do with Nav.ascx

If we need to remove it, we need to remove it from upgrades, but it will be breaking

**Comment by mtrutledge** [comment]
Can we remove it from 10, but in the meantime put out a blog post for manual removal or a simple module package someone can manually install?

**Comment by valadas** [comment]
I don't think a blog post is very good, we need to collect breaking changes in a single document to publish, something like the past Dnn x.x.x Developer quick start series, maybe something on the docs site I think would be great and they we can link to that in the release notes.

**Comment by valadas** [comment]
@mitchelsellers was this part of your cleanup PR for 10 or do we need to keep this issue around still ?

**Comment by mitchelsellers** [comment]
Yes, this one can be closed as we flagged it as obsolete
