### ISSUE TITLE
How do we achieve version control for values of the database.

### ISSUE THREAD

**Issue by patelmitesh** [dnnsoftware/Dnn.Platform#2773]
## Subject
How do we achieve version control for values of the DNNdatabase updated through "Admin panel".

## Issue Description
In normal scenario when a user is logged in using their login credential and click on save/publish button after modifying any existing page setting or theme/template name or inserted/deleted any page then database directly gets updated. 

But we are looking a way to rollback any of unwanted changes or accidental changes that have been made by such user. 

Currently we are using GitHub to version control the front end.

Is there any way by which i can version control the database.?

I am looking for any functionality that allows me to showcase before and after scenario of data values.

I have looked through much resources but none did help!

Any insights are much appreciated!

Thanks,

## Affected version

* [x] 9.2.2

**Comment by mitchelsellers** [comment]
GitHub issues are only to be used for issues/feature requests.  For this item I would suggest a posting on the DNNSoftware forums or StackOverflow.  Some of what you are looking for exists with the recycle bin, but not all of it.
