### ISSUE TITLE
DNN Installation Fails on Azure

### ISSUE THREAD

**Issue by meetmandeep** [dnnsoftware/Dnn.Platform#2775]
Unable to install latest CI build of DNN 9.4.0 on Azure. 

_0:51 Minutes   |   18% ERROR occured - System.Data.SqlClient.SqlException (0x80131904): Execution Timeout Expired. The timeout period elapsed prior to completion of the operation or the server is not responding.
 Add 1 row to dbo.[Languages]
 Add 5126 rows to dbo.[Lists]_ 

## Steps to reproduce
Download the latest CI build from https://dotnet.visualstudio.com/DNN/_release?view=mine&definitionId=1

1. Provision a new web app (P1v2) and database (tried with S0, S1, and S2) 
2. Proceed with installation. Schema SQL is executed. Data SQL is timed out. 

## Current result
Installation Fails

## Expected result
Successful Installation

## Screenshots
See: https://snag.gy/jail95.jpg

## Affected version
9.4.0.138
9.4.0.137

**Comment by ohine** [comment]
Thanks for reporting this @meetmandeep! We didn't sync the final fixes (which was for this Azure issue) back down to development post v9.3.2. The [next build](https://dev.azure.com/dotnet/DNN/_build/results?buildId=16966) should work for you. If you still run into issues, let me know!

**Comment by meetmandeep** [comment]
Thanks @ohine I was able to install [this build](https://dev.azure.com/dotnet/DNN/_build/results?buildId=16966)

**Comment by valadas** [comment]
Closing this as resolved
