### ISSUE TITLE
Extract `GetLocalResourceFile` from `ModuleControlPipeline`

### ISSUE THREAD

**Issue by bdukes** [dnnsoftware/Dnn.Platform#2780]
PR #2774 rearranged the code which creates modules, and highlighted to me that the logic to generate the `LocalResourceFile` value for a module differs based on the type of module.

Original code:
https://github.com/dnnsoftware/Dnn.Platform/blob/2a4c9f1cd06d8209668be4e3271bfaa7b01d462b/DNN%20Platform/Library/UI/Modules/ModuleControlFactory.cs#L179-L202

Updated code:
https://github.com/dnnsoftware/Dnn.Platform/blob/1414a469f077274f713ae9162f336019084d5c72/DNN%20Platform/DotNetNuke.ModulePipeline/ModuleControlPipeline.cs#L168-L191

I'm proposing that this logic be moved into the `IModuleControlFactory` interface, so that the `ModuleControlPipeline` doesn't need to have as much specific knowledge of different module patterns.  It would be nice to create an abstract base class to move that common logic into, which can be overridden by the `MvcModuleControlFactory`, but there may not be a reasonable place for that base class to exist that can be referenced by all of the implementations.  Also, adding a member to an existing interface is a breaking change, so it may not be worth it.

**Comment by bdukes** [comment]
Originally discussed in https://github.com/dnnsoftware/Dnn.Platform/pull/2774/files#r283375569

**Comment by ahoefling** [comment]
I think this is a great idea. I'll make the change and queue up a follow-up PR once we get #2774 merged

**Comment by ahoefling** [comment]
@bdukes Can you take a look at this commit https://github.com/ahoefling/Dnn.Platform/commit/d07bbc96dfa11a33178f3e8db7638289d06a980b

I am thinking of submitting the PR for this when the other one is merged. Everything appears to work, but would love to get some feedback before submitting the PR

**Comment by bdukes** [comment]
That looks great.  I was originally thinking that this was an extension point and folks could create their own `IModuleControlFactory` implementations, so adding a member would be a breaking change.  But I see now that we don't load those implementations dynamically, so there's no issue with this change.  Thanks!

**Comment by ahoefling** [comment]
I will submit the PR.

Should we be adding custom module pipeline extension points? Is this something that warrants a RFC?

**Comment by bdukes** [comment]
My opinion would be that extending the module pipeline isn't an important feature to prioritize anytime soon.  Maybe something to consider as we move to .NET Core
