### ISSUE TITLE
Potentially unintentional difference in module pipeline

### ISSUE THREAD

**Issue by bdukes** [dnnsoftware/Dnn.Platform#2781]
While reviewing #2774, I noticed that `ModuleControlFactory` (replaced by `ModuleControlPipeline` in that PR) replaces `.` with `-` in the control path when setting the `ID` of the module control, but only for a settings control.

`ModuleControlFactory.LoadSettingsControl`
https://github.com/dnnsoftware/Dnn.Platform/blob/2a4c9f1cd06d8209668be4e3271bfaa7b01d462b/DNN%20Platform/Library/UI/Modules/ModuleControlFactory.cs#L151-L157

`ModuleControlPipeline.LoadSettingsControl`
https://github.com/dnnsoftware/Dnn.Platform/blob/1414a469f077274f713ae9162f336019084d5c72/DNN%20Platform/DotNetNuke.ModulePipeline/ModuleControlPipeline.cs#L142-L146

The main code to load a control **doesn't** do this replacement:

`ModuleControlFactory.LoadModuleControl`
https://github.com/dnnsoftware/Dnn.Platform/blob/2a4c9f1cd06d8209668be4e3271bfaa7b01d462b/DNN%20Platform/Library/UI/Modules/ModuleControlFactory.cs#L121

`ModuleControlPipeline.LoadModuleControl`
https://github.com/dnnsoftware/Dnn.Platform/blob/1414a469f077274f713ae9162f336019084d5c72/DNN%20Platform/DotNetNuke.ModulePipeline/ModuleControlPipeline.cs#L110

It seems that if there's a reason to do the replacement in one place, there's a reason to do it in another.  Can anyone confirm a reason for the replacement, and/or a reason it would only apply to settings controls?

_Original discussion at https://github.com/dnnsoftware/Dnn.Platform/pull/2774/files#r283374051_

**Comment by valadas** [comment]
@ahoefling comments on this ?
