### ISSUE TITLE
RFC: Remove Display DNN Copyright Functionality

### ISSUE THREAD

**Issue by mikesmeltzer** [dnnsoftware/Dnn.Platform#2783]
## Description of Problem

This is a follow-up to discussion on issue  #940 from the Admin Experience repository where it was noted that there are duplicate Persona Bar options to toggle the injection of the DNN Corporation copyright into all pages as an HTML comment.

Do we find value in having the option to inject the DNN Corp. copyright into pages? Is there any tangible benefit in having this in HTML comments?

## Proposed Solution Option 1

- Remove the  Host.DisplayCopyright setting, the code with in the default page that injects the copyright and the subsequent options within the PersonaBar (see #940 in Admin repo.).

## Proposed Solution Option 2 

- Leave as is but update the copyright to reflect the community copyright 

## Affected version

This would depend upon when the functionality was deprecated and targeted for removal.

**Comment by valadas** [comment]
At am totally for removing this feature and the related UI.

The related issue in AE is https://github.com/dnnsoftware/Dnn.AdminExperience/issues/940

**Comment by mitchelsellers** [comment]
Remove it, period full-stop.
There is a good performance gain on every page load if we do. Among other benefits

**Comment by mikesmeltzer** [comment]
Between this RFC and the other thread in the Admin repo. there is more than enough consensus on this one.  

I'll close out this RFC and create another issue to remove the Platform code and database entry. The Persona Bar work can be resolved in the existing issue  at  dnnsoftware/Dnn.AdminExperience#940.
