### ISSUE TITLE
Bump Visual Studio Requirement to 2017 or 2019

### ISSUE THREAD

**Issue by ohine** [dnnsoftware/Dnn.Platform#2784]
## Description of bug
After merging #2774 and [#649](https://github.com/dnnsoftware/Dnn.AdminExperience/pull/649) we can no longer compile the Platform or AdminExperience in Visual Studio 2015. 

The current requirements for the Platform are VS2015 and for Extensions 2013 or 2015. 

https://www.dnnsoftware.com/docs/developers/requirements.html
https://dnndocs.com/content/administrators/requirements/index.html#dnn-requirements

## Suggested Solution
Upgrade our required version of Visual Studio to 2017 or 2019 with the Platform v9.4 release.

**Comment by ahoefling** [comment]
@ohine I agree that #2774 made the problem visible, I believe #2758 caused the problem as that enforced all platform code to compile under C# 7.0. There were many projects in the platform that were still targeting C# 6.0. #2774 used some features that are not available in C# 6.0.

I think we need to create a issue in the Admin Experience project to get everything on C# 7.0 if it isn't already there

**Comment by ohine** [comment]
Good catch @ahoefling, I totally forgot about the C# 7.0 bump. 

As for AE, yes we need to get it on C#7 and .net 4.7.2. It would be nice to do the same with CDF and CK if someone has the time to submit those PRs before Friday.

**Comment by ahoefling** [comment]
PR Submitted dnnsoftware/Dnn.AdminExperience#948

**Comment by valadas** [comment]
Duplicates #2786
