### ISSUE TITLE
Bump Requirement for .NET version to v4.7.2

### ISSUE THREAD

**Issue by ohine** [dnnsoftware/Dnn.Platform#2786]
## Summary

The current documented requirement for the Platform are .NET Framework v4.5+, the v9.4.0 release this has changed to v4.7.2+. We need to update the documentation to state the correct requirements for the v9.4.0 release. 

https://www.dnnsoftware.com/docs/developers/requirements.html
https://dnndocs.com/content/administrators/requirements/index.html#dnn-requirements

Related: #2644

**Comment by mitchelsellers** [comment]
PR Submitted to DNN Docs: https://github.com/DNNCommunity/DNNDocs/pull/296

**Comment by ahoefling** [comment]
cc: @bdukes @ohine @mitchelsellers 

Did we ever determine if we made the necessary changes to upgrade script for the web.config so it updates the entries for target framework .NET 4.5 -> .NET 4.7..2? I know we updated the Debug.config and Release.config. This may be something we need to test.

Should I create a new issue for this?

**Comment by ahoefling** [comment]
created #2788

**Comment by valadas** [comment]
@ashishpd Can you update the requirements or redirect to the docs site please...

**Comment by zyhfish** [comment]
the dnn doc site updated.

**Comment by zyhfish** [comment]
updated in dnn docs site.

**Comment by mitchelsellers** [comment]
All changes are done for this
