### ISSUE TITLE
Remove Display DNN Copyright Functionality

### ISSUE THREAD

**Issue by mikesmeltzer** [dnnsoftware/Dnn.Platform#2791]
Follow-up to RFC #2783 and dnnsoftware/Dnn.AdminExperience#940.

## Description of problem 

The Platform provides a mechanism to inject a DNN Platform identifier, DNN meta keywords, a DNN Corp. copyright and a DNN generator meta tag into every page of the site. 

This is currently providing little value and is adding unnecessary bloat to every page when enabled. 

## Description of solution

Note:  Should this be deprecated first and then removed in a later version incase developers are piggy backing on this field?

- Remove the copyright HTML comment, the DNN keywords and the meta generator injection from default.cs (search Host.DisplayCopyright in file to find references)
- Remove the DisplayCopyright property from the HostSettings classes
- Include a SQL script to remove the Copyright setting from the HostSettings table

## Additional context

Ensure to align the deployment of this change with the deployment of dnnsoftware/Dnn.AdminExperience#940.

## Affected version

TBD

**Comment by ohine** [comment]
I'd say we remove the rendered output and ability to toggle the setting in v9.4 and then tag any properties as obsolete and removed in v11.

**Comment by ohine** [comment]
Basically.... 

In v9.4
- Remove the copyright HTML comment, the DNN keywords and the meta generator injection from default.cs (search Host.DisplayCopyright in file to find references)
- Add Obsolete tag to HostSetting properties calling out full removal in v11.0.0. 



Then in v11.0
- Remove the DisplayCopyright property from the HostSettings classes
- Include a SQL script to remove the Copyright setting from the HostSettings table

If we can't get this adjusted for v9.4, we'd need to update the removal string to call out v12.0 as the target version for full removal.

**Comment by valadas** [comment]
Sounds like a plan

**Comment by mikesmeltzer** [comment]
I have some cycles that I can do this one before the 9.4 code freeze but not for the removal of the Person Bar fields. Could someone help with that before the 9.4 code freeze under the other issue?

**Comment by valadas** [comment]
@mikesmeltzer I will try, got some Visual Studio updates to do, but should be able...

**Comment by mikesmeltzer** [comment]
Thanks @valadas.  I'll tackle this end in the next couple of days. If you don't get to it, no biggy, we can roll it into the next version.

**Comment by sleupold** [comment]
We could remove the HostSettings record from the database now as well and always return false for the DisplayCopyright property (and ignore calls to set it)

**Comment by valadas** [comment]
Yeah, I tried to start but ran into some build issues @mikesmeltzer I am no longer sure to be able to do it for this friday... Maybe over the weekend if lucky.

**Comment by mikesmeltzer** [comment]
Daniel,

No rush, I haven't started this on my end either.  

Let's hold this change off until v10.

Mike

**Comment by mikesmeltzer** [comment]
@sleupold What about developers that might be using that setting in their own solutions? By following the deprecation guidelines we can give them a heads up just in case.

**Comment by valadas** [comment]
Yeah, it is a public property of  Host entity. I guess we need to change it to return false and mark it obsolete to cover that.

**Comment by mikesmeltzer** [comment]
@valadas Maybe I'm missing something? 

If we mark the property obsolete and also change the behaviour of it (always returning false) then we could be overridding someones custom code (if they are using that setting in a module or a skin to toggle something else besides the HTML comment injection) without giving them warning that we will be doing this.

**Comment by valadas** [comment]
Well, this was made and labeled to show Dnn Copyright. So it should have not been used by modules really. In my opinion...

**Comment by mikesmeltzer** [comment]
@bdukes I don't believe this should be closed yet.  This issue is to remove the items from the core and @valadas work was to remove it from the PersonaBar.

**Comment by bdukes** [comment]
Thanks @mikesmeltzer, this was auto-closed when I merged #993, but it shouldn't have been.

**Comment by valadas** [comment]
Opps, I did not think just mentioning it would close it... I guess "resolves" does the same as "closes"

**Comment by bdukes** [comment]
I think you can say _For #2791_ instead of _Resolves_ if you just want a link

**Comment by valadas** [comment]
Ok, so @mikesmeltzer just noticed... PB 993 only removed the setting from the site settings UI but this setting also exists in the security module, it was a duplicate setting.

So we need to remove this from the security module UI and from the core to really complete this issue.

**Comment by mikesmeltzer** [comment]
The PR I'm going to submit only removes the copyright code from the default.cs file, stopping the comments, metadata, etc. being injected.

The other original mentions in the issue of removing the host copyright setting altogether I did not do as the setting is used in other parts of the platform such as the deprecated ribbonbar and a skin copyright file.

**Comment by mikesmeltzer** [comment]
I've resolved this in Pull Request #3524.
