### ISSUE TITLE
CDF - Remove Injected HTML Comments

### ISSUE THREAD

**Issue by mikesmeltzer** [dnnsoftware/Dnn.Platform#2792]
## Background

The Client Dependency Framework will inject an HTML comment identifying that it is loading the requested resource (js or css).

This functionality can be turned off per file request at a developers discretion by setting the AddTag property to false in their module, skin, container, etc. code.

This functionality, if a developer set AddTag to false, can also be overridden by putting the site into debug mode.

Additionally, the JavaScriptLibraryInclude also injects the comments but this control does not allow an override.

## Description of Problem

Using the AddTag property to not allow the comments to be injected into the page doesn't appear to have had widespread adoption by module developers and isn't used with the Platform itself.

The ramification of this, and the addition of the JS Library Include comment injection, is that sites may end up with large amounts of comments in the HTML resulting in unnecessary bloat to the page size.

Outside of potentially some debugging scenarios (even then I don't see large value in the comments), which is covered by the existing setting toggle, I cannot see where the injection of the comments has much benefit (see considerations and questions below for an update on where this is being used).

## Proposed Solution Option 1

- Remove the AddTag functionality from the CDF controls

- Remove the AddTag flag from the comment injection 

- Remove the AddTag property from any controls that are being used internally in the Platform

- Remove the comment injection from the JavascriptLibraryInclude.ascx control

Note:  See considerations and questions for a potential blocker

## Proposed Solution Option 2

- Do the proposed option 1

- Remove the remaining flag for debugging and the comment injection all together

Note:  See considerations and questions for a potential blocker

## Some Considerations and Questions

The CDF comments appear to be used within DotNetNuke.UI.Modules.ModuleHost for restoring client resource registrations that originated in module code. If the module is cached then it cannot tell the page to register the dependency so it is parsing the cached HTML for CDF comments and then reregistering it.

If module caching requires the CDF comments then why can they be optionally removed in some cases via AddTag = false? 

If this should remain should be refactor the controls to ignore AddTag = false if module caching is enabled?

Is there a more optimal way for cached modules to reload dependencies? Maybe by storing the registrations in the data cache on a per module basis (if possible without major refactoring) instead of inline comments and using regex searches?

## Affected version

TBD

**Comment by ohine** [comment]
Related: #324

Basically, if module caching is enabled. Any JS files included will only be registered for the initial non-cached request. All cached requests will be missing any required JS files from that extension. 

I'd love to see this switched to only output these comments WHEN caching is enabled on that specific module. I'd also love to see this offloaded somewhere else besides the rendered html.

**Comment by mikesmeltzer** [comment]
@ohine If we offloaded the registrations elsewhere besides the rendered HTML do you foresee any reason to still have the commenting functionality?

**Comment by ohine** [comment]
Nope, not at all. I'd love for it to go away. I think if at all possible (granted it's a huge change). I see it as a manifest setting which is defined at installation time per module control ideally I think.

**Comment by valadas** [comment]
I like whenever possible to have source-maps files and the minified field to be as lean as possible (no comments). But I have not investigated this using CDF, would be awesome though.

**Comment by ohine** [comment]
@valadas I completely agree, however these are slightly different. They are injected into the html body with the path, provider type, and registration order (priority) of each script registered by the CDF API's. I've attached an image to help visualize the markup. This is from the homepage on the default install of v9.4.0-alpha

![image](https://user-images.githubusercontent.com/1687117/57825045-2f488a80-776b-11e9-94df-40f850713cfb.png)

**Comment by valadas** [comment]
Yep, right now it injects what is bundled as comments so you know what is part of the bundle right. My idea would be to serve the bundle with one handler and a sourcemap from another handler. The bundler (or CDF) would need to generate source mappings for that but we would know what is in the bundle and have nice debugging experience without adding bloat (soucemaps only load with developer panel open). It would be great but maybe beyond this RFC...

**Comment by valadas** [comment]
I am digressing from the main subject, I think we all agree to remove the comments unless we are in debug mode, I gonna assign this to Dnn10 for now but nothing is set in stone.

As a related sidenote, I am wondering how much of a performance difference we would see between using the cdf to bundle those files in one big request vs directly serving each file pre-minified one by one with their accompanying sourcemap (that only loads when debugging in the browser) on a site that uses ssl and http/2 that uses concurrent streams, see https://www.httpvshttps.com/

**Comment by distor-sil3nt** [comment]
This is still an issue and should be fixed. The source code get's unreadable and messed up with these comments. Can someone please fix this?

**Comment by bdukes** [comment]
The comments are necessary to support caching. An alternative approach would need to be put in place before these comments can be removed.
