### ISSUE TITLE
Make Service Locator ONLY Accessible to WebForms Modules

### ISSUE THREAD

**Issue by ahoefling** [dnnsoftware/Dnn.Platform#2794]
## Description of problem
#2774 added Dependency Injection into the platform and due to a limitation of how Dependency Injection works in the Web Forms Controls we were not able to add constructor injection. The Web Forms modules are the ONLY module pattern that requires the Service Locator pattern to access services in the container.

Providing this API as a globally accessible property means it is governed by the same deprecation rules as any other API in DNN. This property is intended to only be used with Web Forms Modules in a very specific scope of use. It will be very easy to abuse the Service Locator and use it where it should not be used.

## Proposed Solution
Since the Service Locator pattern is only required for Web Forms, the `Globals.Common.DependencyProvider` should be marked Internal and have a local instance on every base class for Web Forms modules. This provides Dependency Injection for Web Forms modules but prevents the Service Locator pattern being used anywhere else in the platform.

The Service Locator Pattern is commonly referred to as an Anti-Pattern and should be avoided at all costs. Adding this limitation forces the lifetime of the Service Locator to be coupled to the lifetime of the Web Forms Module pattern which is where it is needed.

### New API Usage
All base classes used by module developers in Web Forms Modules will require a new protected property `DependencyProvider`. This gives the Web Forms Module developers an extension point to use the Service Locator but only in the context of Web Forms modules.

Base Classes
* `PortalModuleBase`
* `ModuleSettingsBase`

```C#
public partial class MyView : PortalModuleBase
{
    protected IMessageService MessageService { get; }

    public MyView()
    {
        MessageService = DependencyProvider.GetService<IMessageService>();
    }        
}
```

### Old API Usage
```C#
public partial class MyView : PortalModuleBase
{
    protected IMessageService MessageService { get; }

    public MyView()
    {
        MessageService = Globals.Common.DependencyProvider.GetService<IMessageService>();
    }        
}
```

cc: @mitchelsellers @bdukes @mtrutledge

**Comment by mitchelsellers** [comment]
Thanks, @ahoefling for documenting this.  As we discussed on the phone I think that this is a great workaround to provide the functionality needed, but not to limit us with API deprecation.

This should be added as a property to;

*  PortalModuleBase
*  ModuleSettingsBase
*  AuthenticationConfigBase
*  AuthenticationLogoffBase
*  AuthenticationLoginBase
*  Module Control Base (**Might fix the first two **)

**Comment by ahoefling** [comment]
Just saw your comment after submitting my PR. I will take a look at the classes you mentioned and take the discussion over the PR
