### ISSUE TITLE
Removal of methods marked for removal in v10.0.0

### ISSUE THREAD

**Issue by mitchelsellers** [dnnsoftware/Dnn.Platform#2800]
This is a place holder for the removal of all methods marked for removal in version 10.0.0.

I will be submitting a Pull Request shortly after the "Development" branch is updated to build 10.0 releases that remove all of these items.

I will then coordinate with @ohine to publish an alpha build & blog post thereafter.

**Comment by sleupold** [comment]
this is still valid
