### ISSUE TITLE
RFC: DNN & Log4Net

### ISSUE THREAD

**Issue by mitchelsellers** [dnnsoftware/Dnn.Platform#2801]
Currently, the DNN Platform is using Log4Net as the backend logging provider, this provider is used to write the log files to the /Portals/_default/logs directory.  Users can customize the configuration of this using a configuration file.

## Description of Problem
There are a number of concerns with the current Log4Net implementation:

* It is a fork, and an older fork at that, of the Log4Net project and has not been maintained
* There is a bug in the file provider, whereby log files are not cleaned up automatically.  This resulted in various "fun" solutions outside of DNN to clean up the directories.

## Proposed Solution Option 1
Update the fork to be current with the Log4Net implementation as it is today.

I'm not a fan of this, as the management of forks is hard on the community and takes a lot of effort to manage.

## Proposed Solution Option 2
Replace the `DotNetNuke.Log4Net` with a NuGet reference to the actual Log4Net project.  It appears that the actual code included in this project is nothing more than a direct copy/paste, including namespaces, so the level of effort here is NIL and the benefit would be better management of assets.

This is a much better option, however, looking at .NET Core future the Log4Net solution doesn't fully adhere to the new .NET Core items such as configuration.

## Proposed Solution Option 3
Replace Log4Net with another logging solution, such as [SeriLog](https://serilog.net/).  This library is licensed under the same license as the Log4Net solution but has a large number of appenders that allow data to be shipped to other locations with minimal effort.  Including Email, File, Database, Azure Blob Storage, Application Insights, and more.

This solution also has the benefit of better supporting .NET Core standards for configuration loading etc.  

## Alternatives Researched
We can leave it "as is" but eventually have to fix this for the future.

**Comment by mitchelsellers** [comment]
My personal recommendation would be to leverage option 3.  I don't believe that this would be a breaking change for users, as the usage of the Log4Net library is all internal to DNN.  But the added bonus features that we get with SeriLog would outweigh the differences.

We have been using this product for a number of years on our .NET Core projects and I will not create a new project without it.  The flexibility has been amazing.

**Comment by liffeyd** [comment]
Usage of Log4Net is not only internal to DNN. I, and I am sure others, also use it in development.

**Comment by valadas** [comment]
Yes, I did use log4net in some modules. If I remember correctly there is a dnn wrapper around that logging maybe we could update the wrapper to use the new solution? Or announce it in advance and document how to update if you where using it...

**Comment by mitchelsellers** [comment]
To my knowledge logging is used by the DotNetNuke.Instrumentation library. There would no no changes there.

**Comment by mitchelsellers** [comment]
There shouldn’t be any direct calls to log4net at least from what I can tell

**Comment by bdukes** [comment]
It would be a breaking change in terms of configuration for anyone who has customized `DotNetNuke.Log4Net.config` (e.g. added App Insights logging), but otherwise it should be a fairly painless transition.  

There was a time when `DotNetNuke.Log4Net.dll` was included before `DotNetNuke.Instrumentation` existed, so some folks have direct dependencies.  Not sure how many of those are still out in the wild.  Is that your scenario @liffeyd or @valadas?

**Comment by liffeyd** [comment]
No, no longer referencing Log4Net directly. Currently using DotNetNuke.Instrumentation.

**Comment by valadas** [comment]
@bdukes no, I always used DotNetNuke.Instrumentation, so as long as we either keep that as a wrapper for logging, I see no problem. If DotNetNuke.Instrumentation needs to be deprecated, then we need to go by our deprecation rules IMO. But I am guessing we can keep it and just replace the implementation details? That way it would not be a breaking change in my opinion. If people used Log4Net directly, then I would guess we can just document the change, as a quick fix, those people could just backup the dll and put it back as a quick fix?

**Comment by mitchelsellers** [comment]
My idea either way would be updates hidden inside of instrumentation. Non breaking if you use that pathway.

**Comment by valadas** [comment]
Would this be ready to move out of RFC state? If so are we aiming for 9.4.1 or 10 ?

**Comment by mitchelsellers** [comment]
There was a PR to update Log4Net that was procesed

**Comment by valadas** [comment]
Cool, it was not linked to this issue, so closing this right?
