### ISSUE TITLE
Password change not working

### ISSUE THREAD

**Issue by digitalsigi** [dnnsoftware/Dnn.Platform#2805]
## Description of bug
As Admin I want to change the password for a user.
Whatever I enter here I always get the message "Your new password was not accepted for security reasons. Please enter a password that you haven't used before and is long and complex enough to meet the site's password complexity requirements."
How can I fix this?

## Steps to reproduce
List the steps to reproduce the behavior:
1. Login as Admin
2. goto Users->Click on the ... -> Change Password
3. Enter a password e.g. "aldo1234+#"

## Current result
Error Message

## Expected result
Password ist changed

## Affected version

* [x] 9.3.2
* [ ] 9.3.1 (not installed)
* [ ] 9.2.2
* [x] 9.2.1 (previous version)
* [ ] 9.2
* [x] 9.1.1 (happend already here)
* [ ] 9.1
* [ ] 9.0

## Affected browser

* [x] Chrome
* [ ] Firefox
* [ ] Safari
* [ ] Internet Explorer
* [x] Edge

**Comment by valadas** [comment]
If you go into Settings -> Security -> Member Accounts -> Registration Settings, you will see the currently configured password requirements, such as minimum lenght, minimum amount of special characters, etc. Did you check if your password matches those requirements?

**Comment by digitalsigi** [comment]
Oh yeah, this and in web.config, here ist the screen shot.
Surprisingly, when creating a new user I get info about password strength, which again does not follow the rules in screen shot. I was required to enter at least a numeric character.
I know its not best strength but for some reason I need characters only.
![image](https://user-images.githubusercontent.com/5047081/57985603-864fa780-7a6a-11e9-9bd1-cddb736d13b6.png)

Here snippet of web.config:
```xml
<add name="AspNetSqlMembershipProvider" type="System.Web.Security.SqlMembershipProvider" connectionStringName="SiteSqlServer" enablePasswordRetrieval="false" enablePasswordReset="false" requiresQuestionAndAnswer="false" minRequiredPasswordLength="7" minRequiredNonalphanumericCharacters="0" requiresUniqueEmail="false" passwordFormat="Hashed" applicationName="DotNetNuke" description="Stores and retrieves membership data from the local Microsoft SQL Server database" />
```

**Comment by valadas** [comment]
Do you have anything in the event log, the browser console or in the Portals/_default/logs folder that might provide some hints about what is happening...

**Comment by digitalsigi** [comment]
Yes, here it is:
`2019-05-20 09:52:05,351 [ha01s017-wh][Thread:49][ERROR] Dnn.PersonaBar.Users.Services.UsersController - System.Configuration.ConfigurationErrorsException: Password Reset is not enabled
   at DotNetNuke.Entities.Users.UserController.ResetPassword(UserInfo user, String passwordAnswer)
   at DotNetNuke.Entities.Users.UserController.ResetAndChangePassword(UserInfo user, String newPassword)
   at Dnn.PersonaBar.Users.Components.UsersController.ChangePassword(Int32 portalId, Int32 userId, String newPassword)
2019-05-20 09:52:05,351 [ha01s017-wh][Thread:49][ERROR] Dnn.PersonaBar.Users.Services.UsersController - System.Exception: Your new password was not accepted for security reasons.  Please enter a password that you haven't used before and is long and complex enough to meet the site's password complexity requirements.
   at Dnn.PersonaBar.Users.Components.UsersController.ChangePassword(Int32 portalId, Int32 userId, String newPassword)
   at Dnn.PersonaBar.Users.Services.UsersController.ChangePassword(ChangePasswordDto changePasswordDto))
`

I'm pretty shure that the password in question hasn't been used for this user so far. 

here is what I found in Browser Console (Chrome):
`[Deprecation] The keyword 'caret' for -webkit-appearance CSS property is deprecated and will be removed in M75, around June 2019. See https://www.chromestatus.com/features/5075579829223424 for more details.
dnnapi.com/beacon?h=xfxT5nZ3UhW%2fX8NjvgKsDNmi0xzpRWBC844rAhSGuTI%3d&p=Nt5dCrs%2f4yuXuo4TyWq4tC35PFulO%2b0Iqz7zXNqRs8k%3d&a=vb2GuyBFhYPwrWOtdFXRqh8mDnD8rby3n2x1zoTy1P4%3d&u=CaihYXZmqWRBO80kYPgeb073senhl5mF51mZlgKwh%2bU%3d&r=31&n=3H2fD99Tst8I52hmAoEP1BrPh%2b3uxNcZLGuIC7D9KNA%3d&v=HPO%2bFGH%2fEVz3Ov1yH0clwgpYN4XVT3DhnvEMaiVpyWU%3d&f=Users:1 GET https://dnnapi.com/beacon?h=xfxT5nZ3UhW%2fX8NjvgKsDNmi0xzpRWBC844rAhSGuTI%3d&p=Nt5dCrs%2f4yuXuo4TyWq4tC35PFulO%2b0Iqz7zXNqRs8k%3d&a=vb2GuyBFhYPwrWOtdFXRqh8mDnD8rby3n2x1zoTy1P4%3d&u=CaihYXZmqWRBO80kYPgeb073senhl5mF51mZlgKwh%2bU%3d&r=31&n=3H2fD99Tst8I52hmAoEP1BrPh%2b3uxNcZLGuIC7D9KNA%3d&v=HPO%2bFGH%2fEVz3Ov1yH0clwgpYN4XVT3DhnvEMaiVpyWU%3d&f=Users net::ERR_BLOCKED_BY_CLIENT
Image (async)
injectBeacon @ util.js?cdv=209:53
loadTempl @ util.js?cdv=209:47
loadTemplate @ util.js?cdv=209:73
handleShowSelectedPanel @ main.js?cdv=209:322
d.complete @ jquery.js?cdv=209:6
i @ jquery.js?cdv=209:3
fireWith @ jquery.js?cdv=209:3
i @ jquery.js?cdv=209:6
r.fx.tick @ jquery.js?cdv=209:6
eb @ jquery.js?cdv=209:6
requestAnimationFrame (async)
eb @ jquery.js?cdv=209:6
requestAnimationFrame (async)
eb @ jquery.js?cdv=209:6
requestAnimationFrame (async)
eb @ jquery.js?cdv=209:6
requestAnimationFrame (async)
eb @ jquery.js?cdv=209:6
requestAnimationFrame (async)
eb @ jquery.js?cdv=209:6
requestAnimationFrame (async)
eb @ jquery.js?cdv=209:6
requestAnimationFrame (async)
eb @ jquery.js?cdv=209:6
requestAnimationFrame (async)
eb @ jquery.js?cdv=209:6
requestAnimationFrame (async)
eb @ jquery.js?cdv=209:6
requestAnimationFrame (async)
eb @ jquery.js?cdv=209:6
requestAnimationFrame (async)
eb @ jquery.js?cdv=209:6
requestAnimationFrame (async)
eb @ jquery.js?cdv=209:6
requestAnimationFrame (async)
eb @ jquery.js?cdv=209:6
requestAnimationFrame (async)
eb @ jquery.js?cdv=209:6
requestAnimationFrame (async)
eb @ jquery.js?cdv=209:6
requestAnimationFrame (async)
eb @ jquery.js?cdv=209:6
requestAnimationFrame (async)
eb @ jquery.js?cdv=209:6
requestAnimationFrame (async)
eb @ jquery.js?cdv=209:6
requestAnimationFrame (async)
eb @ jquery.js?cdv=209:6
requestAnimationFrame (async)
eb @ jquery.js?cdv=209:6
requestAnimationFrame (async)
eb @ jquery.js?cdv=209:6
requestAnimationFrame (async)
eb @ jquery.js?cdv=209:6
requestAnimationFrame (async)
eb @ jquery.js?cdv=209:6
r.fx.start @ jquery.js?cdv=209:6
r.fx.timer @ jquery.js?cdv=209:6
kb @ jquery.js?cdv=209:6
g @ jquery.js?cdv=209:6
dequeue @ jquery.js?cdv=209:6
(anonymous) @ jquery.js?cdv=209:6
each @ jquery.js?cdv=209:3
each @ jquery.js?cdv=209:3
queue @ jquery.js?cdv=209:6
animate @ jquery.js?cdv=209:6
r.fn.<computed> @ jquery.js?cdv=209:6
handleLoadPanel @ main.js?cdv=209:316
handleClickOnHoverMenuItem @ main.js?cdv=209:893
dispatch @ jquery.js?cdv=209:6
q.handle @ jquery.js?cdv=209:6
jquery.js?cdv=209:11 POST https://www.burckhardia.at/en-us/API/PersonaBar/Users/ChangePassword 500
send @ jquery.js?cdv=209:11
ajax @ jquery.js?cdv=209:11
rawCall @ sf.js?cdv=209:89
call @ sf.js?cdv=209:100
post @ sf.js?cdv=209:104
value @ VM472:20
(anonymous) @ VM472:20
(anonymous) @ export-bundle.js?cdv=209:98
value @ VM472:20
(anonymous) @ export-bundle.js?cdv=209:90
_ @ export-bundle.js?cdv=209:90
(anonymous) @ export-bundle.js?cdv=209:90
E @ export-bundle.js?cdv=209:90
O @ export-bundle.js?cdv=209:90
k @ export-bundle.js?cdv=209:90
L @ export-bundle.js?cdv=209:90
wn @ export-bundle.js?cdv=209:90
Bi @ export-bundle.js?cdv=209:90
Ye @ export-bundle.js?cdv=209:90
On @ export-bundle.js?cdv=209:90
Ri @ export-bundle.js?cdv=209:90
Cn @ export-bundle.js?cdv=209:90`

**Comment by valadas** [comment]
So, I looked at the differences between your settings and my settings and the only different one is Enable Password Reset, so I tried that and then was able to reproduce. So this is an issue with this setting. As a temporary workaround you can go in the web.config, search for enablePasswordReset and change the value to true....

**Comment by digitalsigi** [comment]
Upgraded from 9.3.2 to 9.4.1, now password change throws an error, see attached file.
[errorlog.zip](https://github.com/dnnsoftware/Dnn.Platform/files/3801527/errorlog.zip)

Btw. this seems to be the same error as here: https://github.com/hismightiness/dnnextensions/issues/177

**Comment by valadas** [comment]
@digitalsigi this error looks like is unrelated, it comes from the Repository module search indexer.

Di you try changing the reset password setting?

**Comment by digitalsigi** [comment]
Thanks for looking into this.
Yes, I tried the password change, but no success. Passwort reset is off at my site.
I hope 4.9.2 is ready soon :-)

**Comment by valadas** [comment]
Yes, 9.4.2 is in RC stage in a few hours, but that will not change anything until we can reproduce this issue and build a fix for it. For now I was not able to reproduce it unless the password reset setting was disabled.

**Comment by engineering87** [comment]
Maybe it is better to change the behavior of the **ResetAndChangePassword** based on the role of the user who is resetting the password. If he is an administrator the setting _PasswordResetEnabled_ will be ignored and proceed with the reset anyway. 
I can quickly prepare a pull request in this direction, what do you think?

**Comment by mitchelsellers** [comment]
I think this needs a bigger discussion with the technology group. Ignoring a feature that disables password reset by design seems to not be a great idea.

**Comment by digitalsigi** [comment]
> Maybe it is better to change the behavior of the **ResetAndChangePassword** based on the role of the user who is resetting the password. If he is an administrator the setting _PasswordResetEnabled_ will be ignored and proceed with the reset anyway.
> I can quickly prepare a pull request in this direction, what do you think?

Oh oh oh, you are going to bypass the problem. 
The issue is not behavior, but functionality. In out case we cannot, for good reasons, allow the users to change the password themselves, but admin must be able to reset it it rare cases. This should work. 
However, I observed, that even a normal user has trouble with that. So it is a bug from my perspective.

**Comment by mitchelsellers** [comment]
I have researched this as far as I can, without completely bypassing ASP.NET Memberships underpinnings we cannot address this issue in a safe manner as it is against the intended API structure.

**Comment by digitalsigi** [comment]
@mitchelsellers Aha. Honestly I have no idea about the ASP.NET Memberships. I any event I will try with newest version.

But what is your recommendation in our case?

**Comment by mitchelsellers** [comment]
The only real workaround is to turn reset on, make the change then take it off.

But that will restart the app two times
