### ISSUE TITLE
RFC: Simplify HTTPS/SSL settings

### ISSUE THREAD

**Issue by donker** [dnnsoftware/Dnn.Platform#2808]
## Description of Problem
The way an administrator currently manages whether a site is secure is confusing at best. There is "SSL Enabled" and "SSL Enforced" on the portal/site settings and for each tab/page there is a IsSecure setting. This allowed for a "mixed use" scenario where for instance only a login page would be secure while the rest of the site was not.

The current situation is the result of organic growth of this feature as years ago a secure page would take considerably more processing time and would hence slow down a site.

We believe this is no longer an issue and the case for a "mixed use" site has evaporated. This is further compounded by the fact that more and more browsers clamp down on non-secure sites/pages.

## Proposed Solution
Replace the current functionality with a single setting which switches the entire site to secure. All non-secure requests are redirected to secure urls. No non-secure requests will be accepted.

## Further enhancement
Enhance the install experience to include a (by default on) secure setting. This would prompt new installations to be secure by default.

## Alternative solution
Keep current settings but create a single button that does all the necessary work to set the existing settings so as to switch the site to secure only.

## Affected version
All previous

**Comment by Icidis** [comment]
I like this proposed solution and would gladly welcome it

**Comment by moorecreative** [comment]
@donker  Peter, thanks! That would help, and would be the solution needed for the issues I posted last year. Can you read through and help make sure that a solution would also cover the dynamically generated page types too?

https://github.com/dnnsoftware/Dnn.Platform/issues/2402
Creating New Pages as SSL Enabled (IsSecure) When Portal Settings Dictate

https://github.com/dnnsoftware/Dnn.Platform/issues/2148
Enforcing HTTPS for /login when no tab/page is set as default login page (default login ctl)

**Comment by thabaum** [comment]
I agree with it all being a bit confusiong along with the HTTPS SSL login and new page issues however I would like to point out some modules/features of some sites require the site page to be NON-SSL to be viewed properly.  I know in the past I have had this issue with images being shown non ssl displaying unsecure site warnings in the browser which is not desired.

Keeping a switch for SSL or Non-SSL sites and pages should still be an option.  I feel a default site switch along with page control switch should be enough.  If site is set to SSL then it is enforced unless you want to disable it on certain pages.

**Comment by donker** [comment]
> I would like to point out some modules/features of some sites require the site page to be NON-SSL to be viewed properly. I know in the past I have had this issue with images being shown non ssl disp

Can you name some examples? I'm curious as to why some system requires *non-secure* pages. It helps us make an informed decision on whether we should support mixed scenarios.

**Comment by mitchelsellers** [comment]
@thabaum As with Peter I would love to get examples.

Additionally, if a third-party solution I would encourage you, or any other user that is experiencing something similar to pressure the vendor to support HTTPS.  There are multiple recommendations at this point that ALL sites should be secured with HTTPS.  [Google](https://support.google.com/webmasters/answer/6073543?hl=en )recommends it.  And really if you look at the standards that are being put in place to warn users of insecure sites across all browsers, it is important for reputation and trust to support it as well.

**Comment by bdukes** [comment]
We've certainly run into scenarios where a service we depended on wasn't available over HTTPS yet, and that required using an HTTP page for a JS or iframe embed.  While we've worked to then migrate to a solution that supported HTTPS, having the flexibility to exclude one page has been useful in the past.

Specific examples include:
* a client finding an embeddable map, e.g. https://makeaclickablemap.com/, which did not support HTTPS at the time (we then found a better alternative, but had something usable in the meantime)
* a module includes an HTTP script reference, and we can allow that page to continue working after switching the site to HTTPS, while we wait for the vendor to release a fix
* a client has a branded/whitelabelled service that comes from their domain, e.g. embedding clicks.example.com onto www.example.com, and they want it to work while we are helping them install the certificate to secure that domain

**Comment by bigelowd** [comment]
Another scenario that requires an HTTP page to exist on an otherwise HTTPS website is when the page in question interacts with LAN-based devices such as a NAS, IP-Camera, FTP-Server in a Router, etc. Of course, these devices can be configured to use an SSL cert. Nevertheless, one should not be forced into doing so by an unaccommodating CMS.

**Comment by thabaum** [comment]
Stale bot strikes again

**Comment by ahoefling** [comment]
I was setting up a new site for SSL today and came across this old jira ticket that mentioned some interesting rules in DNN for SSL that are **by design**.

* [DNN-8167](https://dnntracker.atlassian.net/browse/DNN-8167)

I like the idea of having a single toggle that can be used to turn SSL on for the whole site. It will really simplify forcing SSL which can be difficult if you aren't familiar with how it works
