### ISSUE TITLE
RFC - Modify artifice of Floating Module Add action

### ISSUE THREAD

**Issue by moorecreative** [dnnsoftware/Dnn.Platform#2813]
## Description of Problem
If we are going to bother having the artifice of the whole "floating module icon when adding a new module to a page" Can we please have the module display:none when it is actually added to the page and then removed?

See an example on this video:
https://www.loom.com/share/f3035b938b0e4408800d8974bdec6c66

When you add a new module to a page, it is actually added to the Content Pane briefly, then it is hidden, then the floating icon thing appears (and in many cases, you put it right back in the content pane that it was in to begin with!)

This is especially evident when it is seen in: 
- A new Add Module in which the Module has content that displays on screen in the module before it is setup (such as XMod Pro's "getting started" information)
- An addition of an Existing Module from another page where that module has content that displays for a flash of a second before being hidden to display the floating thing

## Proposed Solution Option 1
Make the module display:none property earlier in the process, when it is first added to the page

## Affected version

* [ ] 9.3.2
* [ ] 9.3.1
* [x] 9.2.2 confirmed still present
* [x] 9.2.1
* [x] 9.2
* [x] 9.1.1
* [ ] 9.1
* [ ] 9.0

**Comment by valadas** [comment]
Additionally, each pane has hidden buttons on it to add a new or existing module to itself. This is true even in platform but hidden away by css. My vote would be to not hide those controls, that way you can just put the page in edit mode and click the button in the pane to add your module in it.

**Comment by moorecreative** [comment]
> Additionally, each pane has hidden buttons on it to add a new or existing module to itself. This is true even in platform but hidden away by css. My vote would be to not hide those controls, that way you can just put the page in edit mode and click the button in the pane to add your module in it.

OH, YES, PLEASE... just clicking to add into the pane directly would be much more intuitive for users when first training them

**Comment by valadas** [comment]
Took a second look at this, the add new module button is still there but hidden, the add existing module icon is missing, but the html for it is there. When clicked it fires up the insertion dialog but it just acts as normal, so you still need to click to select your module and then drag it into the pane you want... Did not have time yet to dig into the details but maybe we could just select the module and it goes directly to the page where the person clicked the button...

**Comment by Timo-Breumelhof** [comment]
@valadas I noticed the same, it does not respect the pane you clicked it in
