### ISSUE TITLE
File Management does not properly sync my files

### ISSUE THREAD

**Issue by eXistenZe** [dnnsoftware/Dnn.Platform#2816]
## Description of bug
Even after syncing all folders and subfolders and refreshing, file manager does not show all the files and folders existing in my portals/1/ folder for example.
 
## Steps to reproduce
Persona bar -> site assets
It opens the File Management module.

## Current result
Some show, others don't. I can't pinpoint the differences between the ones that do and the ones that don't. Permissions are the same.

## Expected result
All files and folders should show after syncing.

## Error log
None.

## Affected version

* [x] 9.3.2

## Affected browser
* [ X ] Chrome
* [ X ] Firefox

**Comment by sleupold** [comment]
please be aware that only files of allowed types are synced.

**Comment by eXistenZe** [comment]
Ok. It also seem that sync this folder only syncs the new files and not the new folders (for that you need to sync the folder and all subfolders - way slower when syncing a bit dir).
Also what's the purpose of having two option for file manager - site and global assets?
Why not having a site file manger for admin level managing (file types protected, only assess /Portals/x) and other for host access (all files and folders in the site, no restrictions)?

**Comment by sleupold** [comment]
"Global" assets are files and folders inside shared /portals/_default directory.
