### ISSUE TITLE
Portal Level Robots.txt File

### ISSUE THREAD

**Issue by mikesmeltzer** [dnnsoftware/Dnn.Platform#2820]
Originated from discussion in #2045. Could also potentially eliminate need for #2534. 

## Description of problem
The robots.txt file is currently a global application file that is served to all sites within a DNN instance. This causes challenges since different sites may have different robots.txt requirements.

## Description of solution
Utilize an HTTP Handler to serve a site specific robots.txt file if it exists within the portal root folder. Fallback to the default global robots.txt file if the portal level file does not exist.

HTTP Handler

- New HTTP Handler for /robots.txt
- Check if robots.txt exists at the root of the portal
- If it exists, serve this file to requests
- If it doesn't exist, serve the application root robots.txt file

URL Rewriting

- Ensure that the appropriate rules are in place to allow this new 'virtual URL' to work properly and not be rewritten or evaluated by the DNN URL Rewriter

## Affected version

* [x] 10

**Comment by sleupold** [comment]
thank you!

**Comment by mikesmeltzer** [comment]
This item is still active and I will be looking to contribute it for v10.

**Comment by sleupold** [comment]
AFAIK, @mikesmeltzer  is working on it

**Comment by stetard** [comment]
I'm wondering if this new feature is completely done for the v10.
If not, it might be interesting to do it.

**Comment by bdukes** [comment]
AFAIK this enhancement has not yet been contributed

**Comment by WillStrohl** [comment]
This comment is only for random people who may come across this post and not realize that portal-level support exists. 😎 
https://dnncommunity.org/blogs/Post/9315/DNN-Summit-Session-Multi-Site-DNN-Instances-and-Robots-txt
