### ISSUE TITLE
3rd party Auth providers (Azure/Google) create user account when User Registration set to None

### ISSUE THREAD

**Issue by iiminov** [dnnsoftware/Dnn.Platform#2825]
## Description of Problem
I have a few installs running DNN 7.4.2 (216) where users log in using Azure or Google authentication provider.

[Wes Tatters](https://www.dnnsoftware.com/answers/external-user-model) highlighted in one of his answers to user related question mentioned that DNN creates a new user account in the background whenever someone tries to log in with 3rd party login provider.

As a result, I end up with additional user accounts whenever users change email addresses. Which is fine from a technical perspective. But the problem is that logic doesn't seem to respect the **User Registration** setting of **None** set in **Site Settings**.

## Steps to reproduce
1. Setup DNN with Azure and/or Google authentication
2. Set User Registration to **None** in Site Settings
3. Attempt to sign in with Azure or Google (user must not exist in the database)
4. Check if a new user account/record is created

## Current result
A new user account is created whenever the user tries to login with Azure or Google.

## Expected result
If **User Registration** is set to **None** and the user does not match existing account report login error (user registration disabled contact site admin or something similar) instead of creating a new user account.

## Additional context
Not entirely sure if this is something that is affecting these few installs as these are very old sites which lived through many upgrades over the years. Or something that is affecting all versions of DNN. I would have to test this a bit more.

I've done a bit of digging into the DNN in an attempt to identify where in the code the accounts getting created. I assume it would go through **AddUser** stored procedure but I can't seem to find any link back to registration.

I have found a bit of code that automatically approves user accounts during login (user validation) [AspNetMembershipProvider.cs#L1886](https://github.com/dnnsoftware/Dnn.Platform/blob/51f4b1709fae8f6c6f026714159ecaa158031059/DNN%20Platform/Library/Security/Membership/AspNetMembershipProvider.cs#L1886).

I got confused why the **else** block does not check **(int)Globals.PortalRegistrationType.PublicRegistration** same way it is done in the **if** block. Regardless, at this point in the code, it is too late to intervene as a new user account is already created.

Does anyone know where to find the code that calls **AddUser** (or similar) in the user registration loop? I want to see if there are any checks performed prior to creating new records.

## Affected version

* [x] 7.4.2 (216)

**Comment by iiminov** [comment]
Looks like now I am completely lost trying to trace how the login/registration process works.

Looking into Google auth provider I find a call to [OAuthClient.Authorize](https://github.com/dnnsoftware/Dnn.Platform/blob/51f4b1709fae8f6c6f026714159ecaa158031059/DNN%20Platform/Providers/AuthenticationProviders/DotNetNuke.Authentication.Google/Login.ascx.cs#L70) in the code behind file for login (button).

So when a user clicks on the login button a call is made to [Authorize()](https://github.com/dnnsoftware/Dnn.Platform/blob/51f4b1709fae8f6c6f026714159ecaa158031059/DNN%20Platform/Library/Services/Authentication/OAuth/OAuthClientBase.cs#L732) function found in OAuthClientBase. Which in turn calls [AuthorizeV1()] for standard DNN login (username and password) and [AuthorizeV2()] for Google in this case (and similar 3rd party login providers).

Looking into [AuthorizeV2](https://github.com/dnnsoftware/Dnn.Platform/blob/51f4b1709fae8f6c6f026714159ecaa158031059/DNN%20Platform/Library/Services/Authentication/OAuth/OAuthClientBase.cs#L224) we find three logical blocks.
1. to report an [error in the event of failure with 3rd party](https://github.com/dnnsoftware/Dnn.Platform/blob/51f4b1709fae8f6c6f026714159ecaa158031059/DNN%20Platform/Library/Services/Authentication/OAuth/OAuthClientBase.cs#L228) (or similar)
2. [request code](https://github.com/dnnsoftware/Dnn.Platform/blob/51f4b1709fae8f6c6f026714159ecaa158031059/DNN%20Platform/Library/Services/Authentication/OAuth/OAuthClientBase.cs#L233)
3. excahnge the said code for token
4. report if user can or cannot be singed in

Assuming all goes well and the code is successfully exchanged for token i.e. [access_token](https://github.com/dnnsoftware/Dnn.Platform/blob/51f4b1709fae8f6c6f026714159ecaa158031059/DNN%20Platform/Providers/AuthenticationProviders/DotNetNuke.Authentication.Google/Components/GoogleClient.cs#L73). DNN should have access to user credentials which would allow for a new user record to be created in the database.

But I still fail to find code block that would make this happen.

And there is a [AuthenticateUser](https://github.com/dnnsoftware/Dnn.Platform/blob/51f4b1709fae8f6c6f026714159ecaa158031059/DNN%20Platform/Library/Services/Authentication/OAuth/OAuthClientBase.cs#L628) which I assume is invoked by [OnLoad](https://github.com/dnnsoftware/Dnn.Platform/blob/51f4b1709fae8f6c6f026714159ecaa158031059/DNN%20Platform/Library/Services/Authentication/OAuth/OAuthLoginBase.cs#L75) in OAuthLoginBase which kicks of the login process and sure enough if User Registration is set to Public user get automatically approved.

Can someone shed a bit of light on the process for me? I feel like I got some grasp on how it works but at the same time, I am none the wiser.

**Comment by bdukes** [comment]
It's pretty twisty, good job getting as far as you did @iiminov.  [`OAuthLoginBase`](https://github.com/dnnsoftware/Dnn.Platform/blob/584b0f54bd6b6d237594dd9f96053f14db0b1a53/DNN%20Platform/Library/Services/Authentication/OAuth/OAuthLoginBase.cs#L75) passes [`OnUserAuthenticated`](https://github.com/dnnsoftware/Dnn.Platform/blob/584b0f54bd6b6d237594dd9f96053f14db0b1a53/DNN%20Platform/Library/Services/Authentication/AuthenticationLoginBase.cs#L107-L113) to [`OAuthClientBase.AuthenticateUser`](https://github.com/dnnsoftware/Dnn.Platform/blob/51f4b1709fae8f6c6f026714159ecaa158031059/DNN%20Platform/Library/Services/Authentication/OAuth/OAuthClientBase.cs#L628-L730).  [`Login.ascx.cs`](https://github.com/dnnsoftware/Dnn.Platform/blob/a977d93170b6f5285fc6b753577b248fd88af522/Website/DesktopModules/Admin/Authentication/Login.ascx.cs#L532) registers [`UserAuthenticated`](https://github.com/dnnsoftware/Dnn.Platform/blob/a977d93170b6f5285fc6b753577b248fd88af522/Website/DesktopModules/Admin/Authentication/Login.ascx.cs#L1331-L1341) to handle that event (which has `AutoRegister` set to `true`), and that's where the user gets created.

Hope it helps!

**Comment by iiminov** [comment]
Hi @bdukes it helps a lot.

I noticed that [AuthenticateUser](https://github.com/dnnsoftware/Dnn.Platform/blob/51f4b1709fae8f6c6f026714159ecaa158031059/DNN%20Platform/Library/Services/Authentication/OAuth/OAuthClientBase.cs#L628) was getting called from [OAuthLoginBase](https://github.com/dnnsoftware/Dnn.Platform/blob/584b0f54bd6b6d237594dd9f96053f14db0b1a53/DNN%20Platform/Library/Services/Authentication/OAuth/OAuthLoginBase.cs#L75). But I couldn't see the forest for the trees; that is figure it out and I failed to realise that if a base class for ``Login`` exists there must be something that uses it.

Now I know what [AutoRegister](https://github.com/dnnsoftware/Dnn.Platform/blob/51f4b1709fae8f6c6f026714159ecaa158031059/DNN%20Platform/Library/Services/Authentication/OAuth/OAuthClientBase.cs#L660) does and where it's used; **Login.ascx.cs** [L1331](https://github.com/dnnsoftware/Dnn.Platform/blob/a977d93170b6f5285fc6b753577b248fd88af522/Website/DesktopModules/Admin/Authentication/Login.ascx.cs#L1331) and [L558](https://github.com/dnnsoftware/Dnn.Platform/blob/a977d93170b6f5285fc6b753577b248fd88af522/Website/DesktopModules/Admin/Authentication/Login.ascx.cs#L558) for account registration.

But what is interesting is that the value is hard coded as ``true``:
```
//Raise UserAuthenticated Event - DNN 7.4.2
var eventArgs = new UserAuthenticatedEventArgs(objUserInfo, userName, loginStatus, Service)
{
    //AutoRegister = true,
    AutoRegister = PortalController.Instance.GetCurrentPortalSettings().UserRegistration != (int)Globals.PortalRegistrationType.NoRegistration,
};
```

By setting the ``AutoRegister`` to check for inequality I basically disable automatic user registration and force remaining logic to respect ``User Registration`` set to ``None`` in ``Site Settings``.

But there is a problem with assigning ``false`` to ``AutoRegister``. During testing I found that it causes ``Azure`` provider to get stuck in an endless (redirection) loop of what looks like trying to [exchange code for token](https://github.com/dnnsoftware/Dnn.Platform/blob/51f4b1709fae8f6c6f026714159ecaa158031059/DNN%20Platform/Library/Services/Authentication/OAuth/OAuthClientBase.cs#L248) instead of just redirecting to [Access Denied](https://github.com/dnnsoftware/Dnn.Platform/blob/a977d93170b6f5285fc6b753577b248fd88af522/Website/DesktopModules/Admin/Authentication/Login.ascx.cs#L543) page.

I am not 100% sure if that is where the issue happens but I manage to stop an endless loop and get to expected ``Access Denied`` page if I encapsulate a call to ``ExchangeCodeForToken`` like so:
```
// OAuthClientBase class
protected bool codeExchangeAttempted
{
    get
    {
        bool val = false;
        if (HttpContext.Current.Request.Params["my_param"] != null)
        {
            bool.TryParse(HttpContext.Current.Request.Params["my_param"], out val);
        }
        return val;
    }
 }
```
```
// AuthorizeV2
if (codeExchangeAttempted)
{
    ExchangeCodeForToken();
}
```
```
// ExchangeCodeForToken
// here we depend on this parameter to actually return from the login authority (Azure/Google in my case)
parameters.Add(new QueryParameter("my_param", HttpContext.Current.Server.UrlEncode(codeExchangeAttempted.ToString())));
```

Which basically has the effect of checking if code has not been exchanged before then execute ``ExchangeCodeForToken`` otherwise return ``AuthorisationResult.Denied`` or ``AuthorisationResult.Authorized``.

Although I am not sure how this will affect the operation DNN at the moment but it seems to work (for testing purposes). Now I can add another path to handle ``NoRegistration`` to display a more user-friendly message.

I am sure that the way I interpreted the exchange code for token is incorrect. Instead, a better place to prevent getting stuck in the permanent loop would be to interrupt it in the [ExchangeCodeForToken](https://github.com/dnnsoftware/Dnn.Platform/blob/51f4b1709fae8f6c6f026714159ecaa158031059/DNN%20Platform/Library/Services/Authentication/OAuth/OAuthClientBase.cs#L271) or in the [ExecuteWebRequest](https://github.com/dnnsoftware/Dnn.Platform/blob/51f4b1709fae8f6c6f026714159ecaa158031059/DNN%20Platform/Library/Services/Authentication/OAuth/OAuthClientBase.cs#L360).

So far that's what I ended up with. Now a bit more dudling and a lot of testing and just might come to some sort of a solution for future versions of DNN.

**Comment by iiminov** [comment]
Fixing my own fix (bug).

In the code I posted above I obviously was not paying attention and created a issue in:

```
// check if "my_param" exists
if (HttpContext.Current.Request.Params["my_param"] != null)
{
    // and return boolean equivalent (if possible)
    bool.TryParse(HttpContext.Current.Request.Params["my_param"], out val);
}
```

related to:

```
parameters.Add(new QueryParameter("my_param", HttpContext.Current.Server.UrlEncode(codeExchangeAttempted.ToString())));
```

As a result code below always evaluates to false code does not get exchanged:

```
if (codeExchangeAttempted)
{
    ExchangeCodeForToken();
}
```

Should you follow my code example change one of the following lines as per below:

```
// just check if "my_param" exists regardsless of its value
if (HttpContext.Current.Request.Params["my_param"] != null)
{
    return true;
}
```

or

```
// send true as "my_param" value so that we can check at later stage
parameters.Add(new QueryParameter("my_param", HttpContext.Current.Server.UrlEncode(true.ToString())));
```

For clarity, here I am assuming that underlying 3rd party api will return my dummy (my_param) back to us when ``ExchangeCodeForToken`` is done. If it doesn't then we're back to square one.

**Comment by valadas** [comment]
I do not use authentication providers right now on any site, can someone confirm if this is still the case in recent versions like 9.3.2 or 9.4.0 RC ? Also I am guessing since this fix could be an unexpected behaviour change, we would do this in Dnn 10 ?

**Comment by iiminov** [comment]
@valadas As far as I am aware the issue only affected 3rd party login providers. Can't remember what version of API I was looking at back in May but I can say that the logic that I needed to change was the same. And I can't imagine this is something that is going to change in DNN 10 (hope to be proven wrong).

Anyways, the logic for standard ``DNN`` login provider (i.e. username+password) goes through the original code flow. Whenever ``GetUserByUserName(portalId, username)`` returns null ``UserInfo`` object the user should just get an error message on the screen corresponding to ``UserLoginStatus.LOGIN_FAILURE`` (or similar). After that, the flow should depend on what value is set for ``UserRegistration`` in each portal.

Hope this helps.

**Comment by valadas** [comment]
@iiminov as for my earlier question, where you also able to reproduce the issue in Dnn 9.3.2 or the 9.4.0 RC that got recently posted. For the RC, it is a prerelease, so not meant for production use, but could you at least reproduce in 9.3.2 ?

**Comment by iiminov** [comment]
@valadas when I was comparing the code between 7.4.2 and 9.3.2 (back in May) everything was the same. The logic hasn't changed in years.

With a move to .net core there is hope that the auth logic would get reworked.

How does this affect your installs? You said you're not using any 3rd party login providers.

**Comment by valadas** [comment]
It would not affect my installs, just asking others with more experience in this area if they see this as a potential breaking change that needs to go in a major release or not and it could be a simple bugfix.

**Comment by iiminov** [comment]
I hear you @valadas. Fingers crossed the move to .net core will prompt someone to take a look at the current auth workflow.
