### ISSUE TITLE
Google Analytics check for data consent is wrong

### ISSUE THREAD

**Issue by valadas** [dnnsoftware/Dnn.Platform#2828]
## Description of bug
When going to the Google Analytics connector config, the checkbox for IP Anonymisation is checked and disabled with a message saying it is required because data consent is active, but that is not the case, data consent is off.

## Steps to reproduce
List the steps to reproduce the behavior:
1. Go to Google Analytics Connector config screen and notice this
![image](https://user-images.githubusercontent.com/6371568/58607742-c84cca80-826e-11e9-8dd4-115a333d1545.png)

2. Notice Data Consent if off in the site settings
![image](https://user-images.githubusercontent.com/6371568/58607785-f3371e80-826e-11e9-83aa-cc39b8ddd4f8.png)

## Affected version

* [x] 9.4.0
* [ ] 9.3.2
* [ ] 9.3.1
* [ ] 9.2.2
* [ ] 9.2.1
* [ ] 9.2
* [ ] 9.1.1
* [ ] 9.1
* [ ] 9.0

I only tested in 9.4.0 since this feature was introduced in 9.4.0

## Affected browser

* [x] Chrome
* [ ] Firefox
* [ ] Safari
* [ ] Internet Explorer
* [ ] Edge
Probably not browser related, tested only Chrome

**Comment by ohine** [comment]
Moved to platform as the connector lives in this repo.

**Comment by valadas** [comment]
> Moved to platform as the connector lives in this repo.

Sorry heh, did not thing about it... You are right

**Comment by valadas** [comment]
I think I found the issue here, knockout handles strings such that any string coalesces to true and an empty string coalesces to false, in the api we are feeding it "false" or "true which always evaluates as true... I am now trying to fix this...

**Comment by ohine** [comment]
This was fixed with #2877, closing this issue now.
