### ISSUE TITLE
Aspect ratio of images on i-Phone

### ISSUE THREAD

**Issue by hansonrf** [dnnsoftware/Dnn.Platform#2830]
## Summary
Summarize your question in one sentence.:  

**On iPhone and narrow screens the aspect ratio of images gets "squished" ; height does not scale as width scales and gets smaller**

## Expected result (if necessary)
Provide a clear and concise description of what you expected to happen.:  

**Height scales with width, particularly on 'locked' images.**

## Screenshots (if necessary)
If applicable, provide screenshots to help explain your problem.:

![image](https://user-images.githubusercontent.com/51268409/58751245-33162580-846a-11e9-9e1d-76c4e72cec0a.png)

![image](https://user-images.githubusercontent.com/51268409/58751249-3b6e6080-846a-11e9-848f-d9b0a67a8808.png)

**Comment by valadas** [comment]
That does not look like a Dnn issue but something with either a module or the html content. Would you have an url we can take a look at ?

**Comment by hansonrf** [comment]
indianlake-pa.us

This, I thought, was the DNN HTML comment area; at least that was where I thought I was at the time...  Definitely module related.  Can try another module...

**Comment by valadas** [comment]
I took a look and this is not Dnn specific. The image has a fixed width and height and the CSS has a max-width: 100%

This means the image width has a max but it's height is always the same, thus creating that squeezing. If you remove the fixed width and height in the html then it will be responsive.

**Comment by hansonrf** [comment]
It took me a while but I resized the images, then edited the HTML using basic text editor, and...

 

You rock!!

 

Bob H.
