### ISSUE TITLE
Cant edit HTML Contents when update from 8.0.4 to sugested 9.1.1

### ISSUE THREAD

**Issue by ufoloko** [dnnsoftware/Dnn.Platform#2831]
## Description of bug
Initially i had version 8.0.4 for Dotnetnuke.
I tried to update to sugested path 9.1.1 and log shows error just for htmlmodule.

Site worked fine but when i tried to edit some html content, im not able to save changes. 

## Steps to reproduce
Install version 8.0.4 for dotnetnuke and then just try to update to version 9.1.1. You can try to just html module too for 9.1.1

## Current result
Is not possible to save changes in HTML module. If you check html module version, is still 8.0.4

## Expected result
You should be able to save changes in HTML module

## Error log
Error when try to install just html module is 

Failure Como resultado de la ejecución SQL, surgieron las siguientes excepciones: 
 System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'DesktopHtml'.
 Invalid column name 'DesktopSummary'.
 Invalid column name 'CreatedByUser'.
 Invalid column name 'CreatedDate'.
 en System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
 en System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
 en System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
 en System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
 en System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
 en System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
 en System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
 en DotNetNuke.Data.SqlDatabaseConnectionProvider.ExecuteNonQuery(String connectionString, CommandType commandType, Int32 commandTimeout, String query)
 en DotNetNuke.Data.SqlDataProvider.ExecuteScriptInternal(String connectionString, String script, Int32 timeoutSec)
 ClientConnectionId:ad2c06ce-28f4-42e1-965c-54283029d91b
 Error Number:207,State:1,Class:16
 
 /** Create Stored Procedures **/
 
 create procedure dbo.AddHtmlText
 
 @ModuleId int,
 @DesktopHtml ntext,
 @DesktopSummary ntext,
 @UserID int
 
 as
 
 insert into HtmlText (
 ModuleId,
 DesktopHtml,
 DesktopSummary,
 CreatedByUser,
 CreatedDate
 ) 
 values (
 @ModuleId,
 @DesktopHtml,
 @DesktopSummary,
 @UserID,
 getdate()
 )
 
 System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'DesktopHtml'.
 Invalid column name 'DesktopSummary'.
 Invalid column name 'CreatedByUser'.
 Invalid column name 'CreatedDate'.
 en System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
 en System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
 en System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
 en System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
 en System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
 en System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
 en System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
 en DotNetNuke.Data.SqlDatabaseConnectionProvider.ExecuteNonQuery(String connectionString, CommandType commandType, Int32 commandTimeout, String query)
 en DotNetNuke.Data.SqlDataProvider.ExecuteScriptInternal(String connectionString, String script, Int32 timeoutSec)
 ClientConnectionId:ad2c06ce-28f4-42e1-965c-54283029d91b
 Error Number:207,State:1,Class:16
 
 create procedure dbo.UpdateHtmlText
 
 @ModuleId int,
 @DesktopHtml ntext,
 @DesktopSummary ntext,
 @UserID int
 
 as
 
 update HtmlText
 set DesktopHtml = @DesktopHtml,
 DesktopSummary = @DesktopSummary,
 CreatedByUser = @UserID,
 CreatedDate = getdate()
 where ModuleId = @ModuleId

## Affected version

* [x] 9.3.2
* [x] 9.3.1
* [x] 9.2.2
* [x] 9.2.1
* [x] 9.2
* [x] 9.1.1
* [ ] 9.1
* [ ] 9.0

## Affected browser
All browsers

**Comment by sleupold** [comment]
Most likely, the HTML table hasn't properly been upgraded during DNN upgrade. Did you move the database, use Evoq before or applied my TurboScripts before?

**Comment by ufoloko** [comment]
Site in mention was a site installed initially in version 8.0.4. and just tried to upgrade to version 9.1.1

Database was always in same server, is CE version and I never applied your TurboScripts.

FYI, just for try, I generated script for html module dependencies, uninstalled HTML module and installed version 9.3.2, then i run backup scripts and information was restored and is working now.

Anyway, I have this problem with some sites when try to upgrade from 8.0.4 to 9.1.1. Is like html table don´t have correct fields for scripts when generate stored procedures.

Any other idea ?

**Comment by bdukes** [comment]
Is there any unusual database configuration?   What version of SQL Server are you running?

**Comment by ufoloko** [comment]
NO, database configuration is just normal, problem is for sites with initial 8.0.4 version installed, SQL Version is 2014

**Comment by sleupold** [comment]
The missing columns should get added during DNN upgrades, they are not enclosed in the module SQL scripts, AFAIR. please make sure in your database options, to use highest compatibility level available.

**Comment by ufoloko** [comment]
I just get installation logs and you are right, sites were upgraded from version 7.1.2 to 8.0.4 and after that when try to upgrade to 9.1.1 problem started.

Sebastian, maybe if i run turboscripts before upgrade can the problem be solved ?

Please confirm

**Comment by sleupold** [comment]
The intention of Turbo Scripts was not really to prevent upgrade errors - but it fixes a number of inconsistencies. Did you check the log files from upgrade (inside /portals/_default/logs folder) for errors during the upgrades?

**Comment by ufoloko** [comment]
Just for additional information, Yesterday i have tested upgrade from 7.4.2 version to 9.3.2, and worked perfectly.

Problem is present if initially you installed version 8.0.4, then upgrade have problems with html module.

**Comment by valadas** [comment]
So I am assuming this got fixed somehow after 9.1.1 and will be closing this issue.
