### ISSUE TITLE
Profile picture not loaded in Chrome

### ISSUE THREAD

**Issue by Tychodewaard** [dnnsoftware/Dnn.Platform#2836]
## Description of bug
If you use Chrome and go to your profile (logged in), you get an empty spot where you're profile pic should be. Even though it should be there.
So, if you adjust other things and hit the save button, you have cleared your profile pic

## Steps to reproduce
List the steps to reproduce the behavior:
1. Login
2. Profile
3. Edit profile
4. See the empty spot in Chrome even if you have put an image before
5. save

## Current result
The picture is not loaded and when the profile has been saved, the picture is as well

## Expected result
If I previously have put in an image in my profile, I expect the image still there when I want to edit.

* [x] 9.3.2
* [x] 9.3.1
Maybe more

## Affected browser
* [x] Chrome

**Comment by valadas** [comment]
I was not able to reproduce in 9.3.2 and in 9.4.0 RC
@Tychodewaard is there some other special circumstances you would see are out of the ordinary on this site that could cause this ?

Anyone else can try to reproduce this please.

**Comment by Tychodewaard** [comment]
Sorry, @valadas I did not see your comment earlier...Just tested in 9.4.1 and it is resolved.

**Comment by Tychodewaard** [comment]
FYI It might be skin related. the community site has the buggy behaviour as described. But a vanille setup, same version but using xcillion works as expected.
