### ISSUE TITLE
ReadOnlyColumn not being included in select

### ISSUE THREAD

**Issue by miguelvaz78** [dnnsoftware/Dnn.Platform#2839]
## Summary
I am trying to use the ReadOnlyColumn attribute in a module but the Select Statement generated to get an item does not include the column.

## Extended description
I have created a model with some columns (small version here):
[TableName("ALGO_File")]
    [PrimaryKey("Id", AutoIncrement = true)]
public class AlgoFile
    {
        public int Id { get; set; }
        public string FileName { get; set; }
        public string ContentType { get; set; }

        [ReadOnlyColumn]
        public string FileSize { get; set; }
}

When I use the repository.GetById(Id); to fetch the item, the FileSize never gets populated.
After inspecting the generated SQL statement I am able to see that it does not contain the FileSize column. 
In the ALGO_File table the FileSize column is Calculated and Persisted.

After checking the code and loking for answers I came across the petapoco documentation stating that:
"Note: By default, ResultColumns are not included in auto-generated SQL. To read a ResultColumn from the database, you must either specify IncludeInAutoSelect.Yes when applying the attribute, or build the SELECT statement yourself and specify the columns you want."
(in https://github.com/CollaboratingPlatypus/PetaPoco/wiki/Mapping-Pocos)
I think this new attributes are a recent change in the petapoco columninfo.
(https://github.com/CollaboratingPlatypus/PetaPoco/blob/master/PetaPoco/Core/ColumnInfo.cs)

By inspecting the DNN mapper function I dont see this IncludeInAutoSelect being set.
ci.ResultColumn = (pocoProperty.GetCustomAttributes(typeof(ReadOnlyColumnAttribute), true).Length > 0);
(in https://github.com/dnnsoftware/Dnn.Platform/blob/f4b22f6f7e712723297039af6a39efec6bd74635/DNN%20Platform/Library/Data/PetaPoco/PetaPocoMapper.cs)

##My question:
Could this be the reason why I am not getting the values populated from the SQL database?
Does anyone else had problems with this?

## Affected version

* [x] 9.2

**Comment by valadas** [comment]
@dnnsoftware/tag thoughts on this, should we update the mapper to support this ? Could this be a breaking change ?

**Comment by mitchelsellers** [comment]
Looking at the documentation, the best recommendation would be to utilitize the methods suggested.  

1.) Add the` [ResultColumn] `Attribute to your method
2.) Since adding this globally would have a negative and breaking change you would also add the `IncludeInAutoSelect.Yes` value on the attribute as an option.

NOTE: This needed attribute is `[ResultColumn]` which is different than the issues submitted `[ReadOnlyColumn]` attribute which would NOT work with PetaPoco.

**Comment by miguelvaz78** [comment]
Adding the [ResultClumn] to my property alone does not work and the value keeps being null after a select (using repository.GetById(Id);). As sugested in the 2.) it must be included in the select (I have inspected the SQL statement sent to SQL server and the column does not get included by default, as expected). 

My issue now is that I cannot find the IncludeInAutoSelect.Yes in the ResultColumn attribute. 
Can anyone help me with a working example?

**Comment by mitchelsellers** [comment]
@miguelvaz78 if you read the documentation you need to include the attribute and ADDITIONALLY set a property of the attribute to tell it that it needs to be added. 

Your entire attribute would look like this `[ResultColumn(IncludeInAutoSelect.Yes)]`

**Comment by mitchelsellers** [comment]
However, I'm not 100% sure what release of PetaPoco this was included in

**Comment by miguelvaz78** [comment]
Thank you @mitchelsellers for the help here. In the version that I'm currently working on of the DNN platform 9.2, running version 5.0.1 of petapoco, there the IncludeInAutoSelect is not available. I Will check it in the new versions.

Also, when I use the attribute ResultColumn, and try to create or update the model, I'm getting an error "The column "FileSize" cannot be modified because it is either a computed column or is the result of a UNION operator."

I will upgrade the platform and try this again with a fresh set of eyes soon.
Cheers!
