### ISSUE TITLE
Email message formatting

### ISSUE THREAD

**Issue by jncraig** [dnnsoftware/Dnn.Platform#2840]
## Description of bug
Email message formatting needs to be cleaned up:  Password Reset Message

## Steps to reproduce
Click the password reset link on the login page

## Current result
I get a message like this:

Dear Joe Craig, You have requested a Password Reset Token from DNN Open Source Community. Please login using the following information: Website Address: dnnsoftware.org
Username: jncraig Link to reset password: https://dnnsoftware.org?ctl=PasswordReset&resetToken=57e12270-0ee8-4398-a0ec-9151e26e358d Sincerely, DNN Open Source Community *Note: If you did not request a Password Reset Token, please tell us immediately in the forums: https://dnncommunity.org/forums/aff/13 

## Expected result

Dear Joe Craig, 

You have requested a Password Reset Token from DNN Open Source Community. 

Please login using the following information: 
Website Address: dnnsoftware.org
Username: jncraig 
Link to reset password: https://dnnsoftware.org?ctl=PasswordReset&resetToken=57e12270-0ee8-4398-a0ec-9151e26e358d 

Sincerely, 
DNN Open Source Community 

*Note: If you did not request a Password Reset Token, please tell us immediately in the forums: https://dnncommunity.org/forums/aff/13 

## Screenshots
If applicable, provide screenshots to help explain your problem.

## Error log
Paste the error log that is related to this issue.

## Additional context

A few days ago I responded to a message over on Aderson's Open Help Slack about a similar problem.  So, this probably needs fixing in the DNN source, too.

Also, probably all email messages need to be reviewed and cleaned up.

## Affected version

* [x] 9.3.2  or whatever version dnnsoftware.org is running.

## Affected browser
Not a browser issue.

**Comment by markandcurry** [comment]
Did anything happen with this? I'm experiencing the same issue.

**Comment by valadas** [comment]
@markandcurry not yet no, should be a simple fix though, just editing the resource file I guess... As a workaround, it can be edited in the localization resource files. I _think_ it is in global resources, if you search for email you should see a few keys that are the email templates...

**Comment by sleupold** [comment]
This should be an issue with the ressource key on dnnsorftware.com, it has not been reported as issue on DNN platform itself.
Info should be forwarded to DNN Corp, who is maintaining dnnsoftware.com (and closed here)

**Comment by valadas** [comment]
Actually it is reported as dnnsoftware.ORG, le me try an install here...

**Comment by valadas** [comment]
@sleupold is right, this is a content issue, not the platform. It works fine with a clean install here. Let me see if I can move this to the right place...

**Comment by valadas** [comment]
Since this is content, I have created this forum post, I am closing this and the discussion can continue at:

https://dnncommunity.org/forums/aft/148

**Comment by Tychodewaard** [comment]
I just tested locally (9.3.2, nvquicksite) and I see the following (below) in globalresources.resx. As there is no html, it explaines why this is not displaying properly in the mailclient. If you reopen the issue, I'll create a PR.

Dear [User:DisplayName],

You have requested a Password Reset Token from [Portal:PortalName].

Please login using the following information:

Website Address: [Portal:URL]
Username:   [User:Username]

Link to reset password: [Portal:PASSWORDREMINDERURL]?ctl=PasswordReset&resetToken=[Membership:PasswordResetToken]

Sincerely,
[Portal:PortalName]

*Note: If you did not request a Password Reset Token, please disregard this Message.

**Comment by sleupold** [comment]
@Tychodewaard 
If there are no html tags, the email should be sent as plain text with the current formattion. It is important to check, why either line breaks are eliminated or the mail is unexpectedly sent as HTML.

**Comment by valadas** [comment]
I reopened this for further testing, but @sleupold is right though. Could this be that it is email client specific or some token that is replaced contains html ? @jncraig

**Comment by markandcurry** [comment]
I was able to get around this by encoding the messages as ASCII HMTL entities and updating the relevant files in their respective .resx files. Kind of a hack, but it solved the problem for the time being.

**Comment by valadas** [comment]
@markandcurry can you let us know which email client you are using please, wanna see if the plain-text vs html format is related to some specific clients or what... Thanks.

**Comment by Tychodewaard** [comment]
I use Office 365 (outlook.office.com)
I have no breaks unless I add it in the globalresources.resx. And the reset link is not a link either.

**Comment by sleupold** [comment]
@Tychodewaard 
the issue on dnnsoftware.org might have been caused by by the SMTP server (Sendgrid) which adds a hidden image to the end, i.e. it turns the plain text mail into an HTML mail but does not convert the line breaks to br tokens.

**Comment by valadas** [comment]
Oh, that makes sense. So I guess it would be nice to modify the default text to actually be html, right?

**Comment by valadas** [comment]
Just double-checking we do have an agreement to make the default template html? I don't believe there are much mail clients that don't support html these days right?

**Comment by hismightiness** [comment]
I'm running into a similar issue with a client, but with the social messaging.  In our case, I think that the messages sent from the profiles are being identified as not containing HTML and incorrectly sending them as plain text, instead of e-mail.  Is anyone else running into this?

https://github.com/dnnsoftware/Dnn.Platform/blob/develop/DNN%20Platform/Library/Services/Mail/Mail.cs#L62

**Comment by hismightiness** [comment]
Example message text:
```text
Hello!

What's up?

Is this on a new line, or what?
<br /><br /><br />
What about this one?
\n\n\n
And this one?
```
Result: 
![image](https://user-images.githubusercontent.com/938023/95635994-d9047780-0a42-11eb-9064-a9e2a5d55a9f.png)

**Comment by hismightiness** [comment]
Yeah... This maybe should be a separate bug, I think...?  🤔

Example without HTML in it:  
```text
Geez!

Not everything was on a new line, huh? 

This try is without any HTML in it.
```
Result:
![image](https://user-images.githubusercontent.com/938023/95636445-069df080-0a44-11eb-8497-47a89c988195.png)

**Comment by sleupold** [comment]
AFAIR, there is a very simply "IsHTML" check, looking for a "<p>" tag inside the message content or sth like this.

**Comment by hismightiness** [comment]
No... I dug into this more.  It's more involved than that.  I have a new issue created and most of the code written already.  

https://github.com/dnnsoftware/Dnn.Platform/issues/4166
