### ISSUE TITLE
PortalAlias Settings Not Correctly Observed

### ISSUE THREAD

**Issue by hismightiness** [dnnsoftware/Dnn.Platform#2841]
## Description of bug
We just experienced this on the dnncommunity.org website.  Basically, we installed under one URL, upgraded a couple of times, then added a new URL as primary and the original URL was still being used.  From what I could tell, the first URL in the database was being used, despite a different domain name being specified as `IsPrimary` and Site Alias Mapping Mode being set to Redirect.

**IMPORTANT:**  If this is indeed a bug, it could have massive impacts on the ecosystem.  Websites may be incorrectly serving out the wrong domain names and the website owners may not have any clue that it's happening.

## Steps to reproduce
List the steps to reproduce the behavior:
1. Install DNN 9.1.1 and use a specific URL (e.g., domain1.org, and www.domain1.org)
2. Upgrade to DNN 9.2.2
3. Upgrade to DNN 9.3.2
4. Add another domain, and set it to be the primary site alias now (e.g., domain2.org (primary), and www.domain2.org)
5. View the website using the new URL/portal alias

## Current result
Originally, it was redirecting to the correct primary URL, but a lot of time, it doesn't.

## Expected result
The primary URL should be used when the setting exists and a HTTP 301 redirect should be performed is Redirect is the mapping mode.

## Additional context
We managed to fix this by deleting the original primary alias (that was no longer primary) and adding it to the end.

## Screenshots
![image](https://user-images.githubusercontent.com/938023/59397915-25eb1780-8d43-11e9-8009-a9cc1d20c22d.png)

## Affected version

* [x] 9.3.2
* [x] 9.3.1
* [x] 9.2.2
* [x] 9.2.1
* [x] 9.2
* [x] 9.1.1
* [ ] 9.1
* [ ] 9.0

## Affected browser

* [x] Chrome
* [x] Firefox
* [x] Safari
* [x] Internet Explorer
* [x] Edge

**Comment by mitchelsellers** [comment]
Do you have a portalSetting value for DefaultPortalAlias

**Comment by hismightiness** [comment]
D'oh! That nasty little bugger. Yes, and now it's changed.  Shouldn't that get updated if the portal alias is updated?

**Comment by mitchelsellers** [comment]
Yes it should, but was curious to see if that plays in. Honestly I think that setting can just go away

**Comment by hismightiness** [comment]
I'd agree with that.  I don't recall why that separate setting was added to begin with... Isn't legacy before the `IsPrimary` column was added to the `PortalAlias` table?

**Comment by mitchelsellers** [comment]
Yup. It dates back to 3.x

**Comment by hismightiness** [comment]
Makes sense.... I vote to put it on "the chopping block"  :D

**Comment by sleupold** [comment]
AFAIK, PortalDefaultAliasis not used for UrlFormat = "Advanced"

**Comment by valadas** [comment]
So do we mark the property deprecated in 9.4.1 and remove this in 11 ?

**Comment by sleupold** [comment]
do we still support other UrlFormats?

**Comment by valadas** [comment]
I think it still works, but I would not see any reason to not use Advanced

**Comment by sleupold** [comment]
In general, sites should use AdvancedURLs, but I'm having a big client with a large site, containing thousands of DNN pages with offers and they are using the tabid in the url to navigate the client on the phone.

**Comment by Mhtshum** [comment]
@sleupold , @mitchelsellers , @daguiler , @valadas 
Please help me to understand why portalalias is working well but when adding new language and enable contention localization it start redirecting to Primary alias whether mode is canonical or none

Is this not bug or what am I missing here?

**Comment by Mhtshum** [comment]
May be I should log above issue as bug?

**Comment by leedavi** [comment]
![image](https://user-images.githubusercontent.com/5583141/73370416-7c966900-42b4-11ea-8cb2-c410c6b218a4.png)

**Comment by sleupold** [comment]
@leedavi 
the last one should be marked as primary as well. Login using the other alias and edit the French one to be primary.

**Comment by leedavi** [comment]
Sorry,, I got disturbed and missed the description.  The problem is I cannot change it.  I had to do it form the DB.

I thought it might be related to this issue, but I see now this issue is closed.

**Comment by sleupold** [comment]
@leedavi 
you cannot edit the alias, you are currently using
you should be able to edit it while browsing using another alias (en-GB)

**Comment by leedavi** [comment]
Ok thx Seb, you're right it could be linked to that.  There was issues about missing portal alias, which caused this situation.  Best we let this one rest until I re-create the issue with proof.  The portal alias stuff  is always a little odd in DNN9.

**Comment by Timo-Breumelhof** [comment]
@hismightiness are you sure this was fixed? I have the same issue on an installation. I deleted the default alias in portalsettings (which was set to an old non existing alias) and the portal still serves both the www and non www alias, while being in redirect mode

**Comment by hismightiness** [comment]
@Timo-Breumelhof Not that I'm aware of.

**Comment by valadas** [comment]
Many hosting control panels have a built-in feature to redirect www versions, could this be the case?

**Comment by leedavi** [comment]
The PortalAlias functionality is very weak in DNN.  It works, but is awkward to get your head around and often goes wrong.  PortalAlias is the first thing to check when thing do point to the right place, And more often than not I fix it in the DB.  It's difficult to pin down problems with the UI, but I certainly wouldn't be surprised if there is more than 1 bug, in certain situations when multiple langauges are used.

Is there any definitive documentation on how the portal alias should be setup for multiple languages and multiple urls?

**Comment by Timo-Breumelhof** [comment]
> 
> 
> Many hosting control panels have a built-in feature to redirect www versions, could this be the case?

No, this is on a pure windows server, no CP involved.
I "fixed" it by removing the portalalias and re-adding it

**Comment by Timo-Breumelhof** [comment]
Ok, DNN seems to have lost the redirect again, I now resolved to adding a redirect in web.config, but there's definitely something wrong here.

**Comment by Timo-Breumelhof** [comment]
FYI I also noticed this on the Evoq installation of a client

**Comment by Timo-Breumelhof** [comment]
@skamphuis this one

**Comment by Timo-Breumelhof** [comment]
@valadas we have been able to reproduce the issue on a local installation and we think we found a fix for it.

**Comment by skamphuis** [comment]
Thanks. I'll be trying to do some more testing and submit a pull request this friday.

**Comment by valadas** [comment]
@Timo-Breumelhof @skamphuis  when you say a fix, do you mean something environmental or something Dnn related, should we reopen this and expect a Dnn related PR to come in?

**Comment by Timo-Breumelhof** [comment]
DNN related. I'll ping you when we have a PR.

**Comment by skamphuis** [comment]
> 
> 
> @Timo-Breumelhof @skamphuis when you say a fix, do you mean something environmental or something Dnn related, should we reopen this and expect a Dnn related PR to come in?

I have the changes is my fork, [here](https://github.com/skamphuis/Dnn.Platform/commit/10c74e5172fac3a5000dce529d105621a864d0b4).
I didn't get to do much testing yet, which is why I didn't submit a PR yet.

**Comment by skamphuis** [comment]
@valadas  I have submitted PR #3832 . Please let me know if there's anything I need to do.
