### ISSUE TITLE
Correct help texts

### ISSUE THREAD

**Issue by MaiklT** [dnnsoftware/Dnn.Platform#2844]
## Description of bug
The help texts in the profile for social media contacts are misleading.

## Steps to reproduce
1. Go to 'Edit profile'
2. Open the 'Contact' panel
3. See the help texts, e.g. for Facebook: *"A link to your Facebook profile with a format beginning with facebook.com/"*
4. Enter "facebook.com/your.user.id.here" (as the help text suggests)
5. Click 'Update'
6. Go to your profile.
7. Click on the profile link.

## Current result
A new window (or tab) is opened with the URL [https://dnncommunity.org/Activity-Feed/userId/facebook.com/your.user.id.here](https://dnncommunity.org/Activity-Feed/userId/facebook.com/your.user.id.here), this leads to a 404 error page.

## Expected result
A new window should be opened wih the URL [https://facebook.com/your.user.id.here](https://facebook.com/your.user.id.here).

## Additional context
Either change the help text to *"A link to your Facebook profile with a format beginning with https://facebook.com/"*, or create this link by adding "https://" at the beginning for the case it is missing (which would be the better solution in my eyes, as it would allow to enter the full Url as well as leaving the protocol part out).
The same also for *LinkedIn* and *Twitter*.

## Affected version

* [x] 9.3.2
* [x] 9.3.1
* [x] 9.2.2
* [x] 9.2.1
* [x] 9.2
* [x] 9.1.1
* [x] 9.1
* [x] 9.0

## Affected browser

* [x] Chrome
* [x] Firefox
* [x] Safari
* [x] Internet Explorer
* [x] Edge
* [x] All others, as this is not a browser issue.

**Comment by valadas** [comment]
Was this tested on a clean site. As far as I can see the default profile template does not include this field at all and if people have created their own templates, then changing this behaviour would break all those templates...
