### ISSUE TITLE
RFC: Don't expose file last modifed date/time via cachebusted URLs

### ISSUE THREAD

**Issue by roman-yagodin** [dnnsoftware/Dnn.Platform#2850]
## Description of problem

Currently raw file last modifed date/time is used to produce cachebusted file URLs, like `http://mysite.com/myfile.pdf?ver=2018-04-20-144725-343`. I thinks there are cases then we do not want the information about file modification date/time to be exposed in public. Just a sample case - the site owner delayed publishing some important document, but still want it to look just like it is published in time.

## Description of solution

Just use some hash string instead of raw file last modifed date/time, something like this: `http://mysite.com/myfile.pdf?ver=MjAxOC0wNC0yMC0x`.

## Affected version
* [x] 9.3.2
* [x] 9.3.1
* [x] 9.2.2
* [x] 9.2.1
* [x] 9.2
* [x] 9.1.1
* [x] 9.1
* [x] 9.0

**Comment by roman-yagodin** [comment]
This will require minor code modification of `StandardFolderProvider.GetFileUrl()` method and also correcting doc comment for `PortalSettings.AddCachebusterToResourceUris()`.

## Possible implementations:

### 1. Use shortened string representation of timestamp (w/o dashes):

```C#
public override string GetFileUrl(IFileInfo file)
{
...
    // Does site management want the cachebuster parameter?
    if (portalSettings.AddCachebusterToResourceUris)
    {
        return TestableGlobals.Instance.ResolveUrl(fullPath + "?ver="
        + UrlUtils.EncryptParameter(file.LastModificationTime.ToString("yyyyMMddHHmmssfff")));
     }
...
}
```

### 2. Use DateTime.GetHashCode():

```C#
public override string GetFileUrl(IFileInfo file)
{
...
    // Does site management want the cachebuster parameter?
    if (portalSettings.AddCachebusterToResourceUris)
    {
        return TestableGlobals.Instance.ResolveUrl(fullPath + "?ver="
        +  UrlUtils.EncryptParameter(file.LastModificationTime.GetHashCode().ToString()));
     }
...
}

**Comment by sleupold** [comment]
sounds useful to me, unless the client would use the current date time to calculate cache time.

**Comment by mitchelsellers** [comment]
Given that this is a process to bust cache only, and not anything used for calculation we just need to be assured that it is different for all edits.  

I'm a big fan of option 2 above, as that is the shortest URL and a simple change.

Feel free to submit a Pull Request for this.

**Comment by valadas** [comment]
I like the shortest url too.

**Comment by valadas** [comment]
Assigning this to 10 but if you want it in 9.4.1 and can submit a PR, that would be fine too I thing, that would not be any breaking change I assume?

**Comment by roman-yagodin** [comment]
Please don't close!

**Comment by sleupold** [comment]
Is anyone planning to provide a PR?

**Comment by roman-yagodin** [comment]
It would be me. Please don't close.
