### ISSUE TITLE
View.html file is not rendered via Module Creator update

### ISSUE THREAD

**Issue by mikebigun** [dnnsoftware/Dnn.Platform#2853]
## Description of bug
When creating Html Web module via `Module Creator`, content of `View.html` file is not rendered to the page.

## Steps to reproduce

1. Login as superuser
2. Add `Test` page
3. Go to `Edit` mode
4. Click to add module -> Select `Module Creator`
5. Provide `Owner Name`, `Module Name`, select `Web` language and `Module - HTML` template
6. Create Module
7. Go to `Module Settings -> Develop`
8. Modify `View.html`

## Current result
`View.html` template is not rendered to the page. 

## Expected result
Html content of `View.html` file should be rendered to the page.

## Demo
See reproduction demo [HERE](https://drive.google.com/file/d/1ouuzxqeUF5PXBuXraJDGJC8AlhUOu3Vs/view?usp=sharing)

## Affected version

* [x] 9.3.2
* [x] 9.3.1
* [x] 9.2.2
* [x] 9.2.1
* [x] 9.2
* [x] 9.1.1
* [ ] 9.1
* [ ] 9.0

**Comment by valadas** [comment]
Closing since PR merged

**Comment by david-poindexter** [comment]
Closing per @valadas comment on Jun 25.
