### ISSUE TITLE
DNN 9.2.2. Low performance folders en files

### ISSUE THREAD

**Issue by meffj00** [dnnsoftware/Dnn.Platform#2856]
We started with DotNetNuke 3.1 Now we are using (since 01-03-2019) a big DNN platform 9.2.2, a main site with 11 subsites. 
The main site contains hundreds of folders, thousands of files and a lots of roles (<75) and permissions. 
To read an image from this structure with the CK-editor takes about thick 1 minute. The second time it goes much faster (about 15 seconds). We use Chrome instead of Edge (not Chromium).  In both cases it takes about 5 seconds to select the file.  After uploading the file hasn't got the focus, another 5 seconds! I found out how to disable paging, so no more extra seconds for that! The subsites are not effected because they contains a far fewer folders, files, roles and permissions. Previously with the old editor never suffered. 
We have cleaned all user folders in our main site and many permissions, but unfortunately without results! The developer of the CK editor says it is not the editor, but DNN itself. 
As it said, our users have been suffering for more than 3 months now and they are absolutely not happy with this situation! 
Can someone help me with this problem! Thanks a lot!

**Comment by mitchelsellers** [comment]
This is a known issue, for our purposes of trying to help solve could you note row counts in the following tables

Folders
Files
FolderPermission

Also, do you do any regular database management such as rebuilding indexes or anything of that nature?

**Comment by sleupold** [comment]
Which CK_Editor are you using -  the one included with DNN or the original one from Ingo (https://github.com/w8tcha/dnnckeditor) - AFAIK, Ingo improved his package recently in this area.
Besides, I included several enhancements in my TurboScripts (https://github.com/dnnwerk/dnnScript/), which should especially improve handling of many users, tabs and files.

**Comment by meffj00** [comment]
Thanks, first of all thank you for picking up this problem. 
The results of the row counts all portals:
- 11013 folders
- 99396 files
- 97466 folder permissions
We don't do any regular database management such as rebuilding indexes. Should we do this, and if so, how will it go?

**Comment by meffj00** [comment]
In GitHub read I did indeed see improvements in new versions. Can I install these versions without problems in my current DNN 9.2.2 version? Furthermore, after consulting Stefan Kamp House of 40-Fingers, I want to look seriously at the effect of your new Turbo Scripts. Thanks for thinking up!

**Comment by sleupold** [comment]
You should be able to install the watcha.net CKEditor provider side by side with the dnn-connect editor provider - it might not take over the settings though. You may simply switch between both editors using persona bar > settings > website > other > editor settings

**Comment by sleupold** [comment]
you could use sp_blitz from https://www.brentozar.com/blitz/ for sql server maintenance.

**Comment by mitchelsellers** [comment]
> Thanks, first of all thank you for picking up this problem.
> The results of the row counts all portals:
> 
> * 11013 folders
> * 99396 files
> * 97466 folder permissions
>   We don't do any regular database management such as rebuilding indexes. Should we do this, and if so, how will it go?

Regular rebuild/reindex processes that are standard for SQL can easily be used, such as https://www.mssqltips.com/sqlservertip/1367/sql-server-script-to-rebuild-all-indexes-for-all-tables-and-all-databases/ 

It SHOULD improve performance, but the actual results are not 100% sure.

**Comment by skamphuis** [comment]
I'm familiar with the installation @meffj00 is speaking about, but unfortunately, since it's an internal site, I can't have a quick look either. (Not even via Teamviewer or sth like that)
We did maintenance of database indexes before, but that didn't have a noticable effect. I did a profile on the database then, and if I recall well, it wasn't so much that queries took too much time, but more that it used a LOT of queries.
Another thing is that it seems to take the browser a long time to build the tree once the data has been downloaded.

**Comment by sleupold** [comment]
there had been an improvement in DNN 9.3.0 (if I remember correctly), which for exports substitutes multiple calls per folder by a single call, including all files in subfolders. Maybe this could help for CKEditor as well. 
But this issue existed for the original CKEditor provider from W8tcha.net as well and Ingo fixed it in latest version.

**Comment by valadas** [comment]
I am closing this issue as I think there was improvements in 9.3.0 and and the rest would be with the editor. If I am wrong in closing this issue to soon, please comment and I will be glad to reopen it.

**Comment by meffj00** [comment]
We are running DNN 9.2.2. After about nine months does anybody now of this problem is fixed? Thanks for your answers.

**Comment by meffj00** [comment]
We are running 9.2.2. After nine months can someone tell me of this problem is solved? Thanks.

**Comment by meffj00** [comment]
We want to upgrade to the latest release!

**Comment by mitchelsellers** [comment]
Performance of Files & Folders is better on the latest versions.
