### ISSUE TITLE
Unable to remove Page Icon or Page Large Icon

### ISSUE THREAD

**Issue by Timo-Breumelhof** [dnnsoftware/Dnn.Platform#2857]
## Description of bug
It's great that https://github.com/dnnsoftware/Dnn.Platform/issues/2128 was added to DNN 9 by @valadas .
But I noticed that  after setting a page Icon or Page Large icon, one cannot remove it any more.

## Steps to reproduce
List the steps to reproduce the behavior:
1. Open Page settings
2. Add a page Icon
3. [SAVE]
4. Refresh the page
5. On the added Icon, Click the "Browse Filesystem" icon
6. Select "< None Specified >"

## Current result
The [SAVE[ button does not get active and even after changing other page settings, the icon is not "empty"

## Expected result
Should be able to remove a page (large) icon

## Affected version

* [x] 9.3.2

**Comment by valadas** [comment]
I am closing this issue since it duplicated https://github.com/dnnsoftware/Dnn.AdminExperience/issues/1037 and the other one is in the repository that needs the fix
