### ISSUE TITLE
Some site settings issues that would make everyone's life a little better

### ISSUE THREAD

**Issue by trouble2** [dnnsoftware/Dnn.Platform#2858]
## Description of problem
Some issues in the site settings that we run into every time in a new install

## Description of solution
- default keywords should be removed
- default copyright statement could do without the 'by DNN Corp'
- styling issue on the fields

## Screenshots
![Naamloos](https://user-images.githubusercontent.com/1827559/59907272-fe631180-940a-11e9-9732-0cf8f8d8c118.png)

## Affected version

* [x] 9.3.2
* [x] 9.3.1
* [x] 9.2.2
* [x] 9.2.1
* [x] 9.2

**Comment by sleupold** [comment]
AFAIK this needs to be tweaked in the default DNN install template.

**Comment by sleupold** [comment]
this is still an issue

**Comment by sleupold** [comment]
planned for DNN 10

**Comment by sleupold** [comment]
AFAIK, at least the Copyright is being handled by another issue.
