### ISSUE TITLE
Default site settings on the 'security' tab should be optimized

### ISSUE THREAD

**Issue by trouble2** [dnnsoftware/Dnn.Platform#2860]
## Description of problem
On a new DNN installation these settings are not 'optimal' in my (and I believe a lot of other peoples) opinion.

## Description of solution
- by default switch off the upgrade check. 
-- It's a nice and good feauture ofcourse but it is not necesarry to check this every time an admin /host logs in. The extra call will be made for the check. So from an optimisation standpoint, it would be better to switch it off.

- by default switch off the copyright notice
-- it is actually exposing that this site is using DNN, so this will give hackers extra information about which system is in use so it actually is a security risk.
-- Furthermore, it adds (some) extra code which goes over the wire every time so from an optimisation standpoint it is also an improvement to switch it off.

- By default switch off the 'Participate in DNN Improvement Program', if people want to do that, they can always switch it on, but it should not be on by default. - I think from a optimisation perspective, it would make less calls. Also it might send sensitive information (?) so from a security perspective, or even judicial (GDPR) it would be better to switch it off by default.

## Description of alternatives considered
Perhaps the upgrade check from a security perspective is a good thing to do every once in a while (however, not every single request done by an admin), so a scheduled task might be better for this ?!?

## Screenshots
![Naamloos2](https://user-images.githubusercontent.com/1827559/59908267-4e42d800-940d-11e9-849b-618a4cc6964d.png)

## Affected version

* [x] 9.3.2
* [x] 9.3.1
* [x] 9.2.2
* [x] 9.2.1
* [x] 9.2
* [x] 9.1.1

**Comment by sleupold** [comment]
- "check for upgrades" might be turned on, to be able to inform users about new versions and warn for security vulnarabilities.
- "Display Copyright" was promotional, and I agree, it should be turned off by default (though the feature might be kept for demo sites
-  The "Improvement Program" might be modified in DNN 10

**Comment by trouble2** [comment]
I agree 'check for upgrades' is a good and important way to warn about security issues, but I don't think it is necessary to include in 'every' request. Like I said, perhaps a better solutions would be though the scheduler or something...

**Comment by sleupold** [comment]
anyways, the implementation of "check for upgrades" would be a separate issues. not a UI problem in PersonaBar.

**Comment by mitchelsellers** [comment]
There are multiple other issues that have been logged with regards to this and work in in progress for this on the 10.x pipeline.

* Upgrade Check - This process ONLY is done if a host user visits the "Extensions" page, so the performance hit is very minimal.  As we switch over to the new upgrade service starting with 10.x there will be other benefits of leaving this setting on.

* Display Copyright - There are efforts to remove this feature entirely in 10.x

* Improvement Program - This is already off by default, and must be opted-in during the installation process.
