### ISSUE TITLE
Default settings 'assume' that people are allowed to register

### ISSUE THREAD

**Issue by trouble2** [dnnsoftware/Dnn.Platform#2861]
## Description of bug
On a clean DNN installation, under the Security options > Member Accounts > Registration setting, the default setting for 'User Registration' is set to 'Private'.
So this kind of makes an assumption that people are allowed to register on the website.
So by default, people can create an account (even though the accounts still must be verified).

I think this is a wrong assumption, and even a possible security risk because you never know what will be changed to the installation in the future, which theoretically might allow some kind of access for this user account.

The default should be set to none.

## Screenshots
![Naamloos4](https://user-images.githubusercontent.com/1827559/59913552-a206ee80-9418-11e9-8950-dbfaffaa2bd3.png)

## Affected version

* [x] 9.3.2
* [x] 9.3.1
* [x] 9.2.2
* [x] 9.2.1
* [x] 9.2
* [x] 9.1.1

**Comment by sleupold** [comment]
it is always a challenge to demo features of the system versus hiding it for security. 
However, in this case, security impact should be low, as "private" requires the user to be acknowledged by an admit to gain additional permission within the site.

**Comment by trouble2** [comment]
Yes, but I think a default CMS installation should not be used to 'demo' the features.
If I create a new installation I would like it to be configured in the 'most' appropriate way for the 'average' use. So I don't have to switch and configure 20 different things which in most cases I'm not using anyway. Just because it gives a nice 'demo' would not be a good argument for me.

**Comment by mitchelsellers** [comment]
This has been discussed in the past, the default behavior here ensures that the Register & Login links are still valid, and the common use-case does support additional user accounts. 

If this is "none" by default the behavior doesn't fit as large of a target audience and can restrict access to things for those with new installations.

If there is broad support for a change, we can discuss, which I will add this to the TAG agenda for discussion.

**Comment by valadas** [comment]
Since nobody else has voiced they want this badly, I am closing this issue in the spirit of cleaning the backlog.

**Comment by valadas** [comment]
We re-discussed this and we could default to none on new installs actually.

**Comment by sleupold** [comment]
still an issue

**Comment by jeremy-farrance** [comment]
Still needed.

**Comment by trouble2** [comment]
'None' seems to be default now in DNN 9.11.0.
So I think this can be closed...
