### ISSUE TITLE
Verification link not working with lowered url casing

### ISSUE THREAD

**Issue by trouble2** [dnnsoftware/Dnn.Platform#2862]
## Description of bug
Don't know if this is already solved in a specific version but I came accross this, so I thought I would at least add it here...

When you set up DNN to allow for 'Verified' registrations, people get an e-mail with a link with a verification code, so they can 'verify' their account. The verification code consists of lower and uppercase characters.
However, DNN has a setting under SEO > Url Management > General settings, which is called
'Convert URLs to Lowercase' 

So this will convert a verification code of let's say 'Aa4Gh3bJ' to 'aa4gh3bj', and then the verification code is not valid anymore, and people cannot login with their newly created account.

## Current result
People cannot verify their account with the verification code

## Expected result
Even in the case where the Convert URLs to lowercase is set ON, people should still be able to use the verification code in the URL

**Comment by mitchelsellers** [comment]
I can confirm that this is an issue on the current version of DNN.  

The process that verifies an account should be changed to a case-insensitive search. 

Tagging this for inclusion in 10.x

**Comment by thabaum** [comment]
I had reported a similar issue in the past, glad to see it is on the list of fixes.  I was having this issue but came up with a work around.

> I turned OFF "Convert URLs to lowercase" AND "Redirect Mixed Case URLs" which I had set to ON 


https://github.com/dnnsoftware/Dnn.Platform/issues/2674

**Comment by sleupold** [comment]
are we able to validate in latest release?

**Comment by Navilois** [comment]
Still an issue in 9.4.4

**Comment by valadas** [comment]
I know there was some fix about url casing redirects as part of 9.5.0, I am not sure if it also solves this issue. If you are able to test 9.5.0 RC on a non production evironment, the download would be here https://github.com/dnnsoftware/Dnn.Platform/releases/tag/v9.5.0-rc1

**Comment by thabaum** [comment]
I will try to test this on the 9.5.1 RC this week.

**Comment by valadas** [comment]
Was this tried again by anyone recently?

**Comment by coretoco** [comment]
This is still the case on DNN 9.06.02.
A workaround is to disable url casing for urls containing "verificationcode"
SEO > Expressions > Prevent Lowercase URL Regular Expression
Add the following regex
`\bverificationcode\b`

**Comment by mitchelsellers** [comment]
I'll work on this for 9.8.1
