### ISSUE TITLE
'About page should not be an advertisement for Evoq

### ISSUE THREAD

**Issue by trouble2** [dnnsoftware/Dnn.Platform#2865]
## Description of problem
When going to the 'About' page, it mainly shows information about Evoq (and 1 link to the documentation center which should be updated to the new documentation site)

I would expect it to show some usefull information about DNN.
Instead it shows:
- Evoq licenses 
- Check out Evoq 
- Upgrade to Evoq
- Documentation center (should be using the new Documentation center links)

## Screenshots
![Naamloos6](https://user-images.githubusercontent.com/1827559/59918731-e77de880-9425-11e9-9807-4ddf090dd9df.png)

## Affected version

* [x] 9.3.2
* [x] 9.3.1
* [x] 9.2.2
* [x] 9.2.1
* [x] 9.2
* [x] 9.1.1

**Comment by mitchelsellers** [comment]
You have suggested information to show here?  My thoughts are as follows.

* GitHub - Report issues
* DNNCommunity.org - Get Help
* DNN Docs - Read Documentation

Possibly also include version information?

**Comment by trouble2** [comment]
Yes, something like that...
What would other CMS sytems do?

- something about the history
- showcase
- store
- hall of fame
- ...

**Comment by mikesmeltzer** [comment]
I think this issue should be moved to the Admin repository. There is an RFC already created on this topic there with some previous discussion that may be helpful. You can find it at https://github.com/dnnsoftware/Dnn.AdminExperience/issues/81. 

I'm wondering if we should even have this screen.  When you hover over the logo there is some brief info.  Would adding a  link to the community site, which would probably have the same or similar info on it, work? You could possibly have a list of a few links to parts of the community site. There is already one to to the documentation site (which goes to the Corp doc site *) so a few more such as the ones listed above could be options.  I think this could be a quick way to update some of the info and remove a persona bar extension that needs to be maintained.

**Comment by valadas** [comment]
Closing this one as it duplicates the one in AdminExperience where this needs to be modified.
