### ISSUE TITLE
ModuleController.Instance.UpdateModuleSetting Not Updating

### ISSUE THREAD

**Issue by mitchelsellers** [dnnsoftware/Dnn.Platform#2868]
## Description of the bug
When working with the ModuleController object and attempting to update a module setting the setting can be initially set, but subsequent calls to UpdateModuleSetting does not result in the value being changed

Example Code:

ModuleController.Instance.UpdateModuleSetting(moduleId, "MyName", "MyValue");

## Steps to reproduce
1.  Have a module settings action, or otherwise, that will set a value for a Module Setting using the above snippet.
2. After updating validate that the database has the proper value in the ModuleSettings table
3. Try to update the setting value with a new value

## Current result
The value in the DNN Database contains the older value, with the older timestamp.  It is not possible to overwrite the setting value.

## Expected result
The value in the database, and exposed to the code, should be the new value set.  With the timestamp of when the last action was completed.

## Additional context
This appears to only impact ModuleSettings, TabModuleSettings appear to be working as desired.

## Affected version
* [x] 9.3.2
* [x] 9.3.1
* [x] 9.2.2
* [x] 9.2.1

Earlier versions were not verified

**Comment by valadas** [comment]
Is this always the case or only under some conditions, I am surprised this was not noticed earlier...

**Comment by mitchelsellers** [comment]
I have tested both an MVC module and a WebForms module and the behavior is consistent.

**Comment by david-poindexter** [comment]
Closing per #3360
