### ISSUE TITLE
Scheduler UX is incorrectly fix the height too small.

### ISSUE THREAD

**Issue by mathisjay** [dnnsoftware/Dnn.Platform#2872]
![Capture](https://user-images.githubusercontent.com/1585717/60229488-1223d300-9864-11e9-8590-52ecd2f47533.JPG)
![Capture](https://user-images.githubusercontent.com/1585717/60229704-31226500-9864-11e9-94f2-55e549a21fba.JPG)

**Comment by mathisjay** [comment]
The skin is nvQuickTheme.  BootStrap4 based.

**Comment by Tychodewaard** [comment]
@mathisjay Are you sure, the theme is NVQuicktheme? What you described, I can reproduce with bs3 but not with bs4 (also nvquicktheme btw)

**Comment by Timo-Breumelhof** [comment]
I cannot reproduce this in my own Bootstrap4 skin.

**Comment by mathisjay** [comment]
@david-poindexter pointed out that it actually should not be relevant to the skin at all since this is a PersonaBar item and the PB runs in a IFRAME outside of the skin's CSS.

**Comment by Timo-Breumelhof** [comment]
@mathisjay  That seems logical. But as I posted I don't see it using my own custom skin.
Also the height is set to "auto" when the sliding animation is done, so it's weird that it's cut off

**Comment by mathisjay** [comment]
Ya, I don't understand why it is being fixed to 497px... I have to use Chrome Inspector to comment out that CSS rule so I can click the Save button...

**Comment by valadas** [comment]
I _think_ the height is calculated using javascript then injected inline by the code. So this may be browser related. Can you please add Dnn version and browser/os used so we can test this @mathisjay

**Comment by valadas** [comment]
Also, I gonna move this issue to AdminExperience since the fix probably needs to be done there

**Comment by valadas** [comment]
Issue moved to [dnnsoftware/Dnn.AdminExperience #1024](https://github.com/dnnsoftware/Dnn.AdminExperience/issues/1024) via [**ZenHub**](https://www.zenhub.com/)
