### ISSUE TITLE
Portal settings not saving "IsSecure" column on database

### ISSUE THREAD

**Issue by davidjrh** [dnnsoftware/Dnn.Platform#2874]
## Description of bug
When updating a portal setting by using the method signature
`		public static void UpdatePortalSetting(int portalID, string settingName, string settingValue, bool clearCache, string cultureCode, bool isSecure)
`
the setting is encrypted on the database but the IsSecure column is not updated, so when the value is recovered, is not decrypted.

## Steps to reproduce
List the steps to reproduce the behavior:
1. On a DNN instance, by using server side code, execute this line of code:
`DotNetNuke.Entities.Portals.PortalController.UpdatePortalSetting(0, "MySettingName", "MySettingValue", true, Null.NullString, true)`

2. Check the PortalSettings table on the database, and check the last column value "IsSecure", that is not being stored. There is a bug in the UpdatePortalSetting stored procedure, that is storing the "IsSecure" value.

## Current result
The "IsSecure" setting is not being stored, so settings updated as secure, causes a decryption error

## Expected result
After updating a secure setting, when obtaining the setting later it should appear as initially saved.

## Affected version
* [x] 9.3.2
* [x] 9.3.1
* [x] 9.2.2
* [x] 9.2.1
* [x] 9.2
* [x] 9.1.1
* [x] 9.1
* [x] 9.0

**Comment by sleupold** [comment]
isSecure parameter has been introduced in DNN 9.2.0 - prior versions are not affected.

**Comment by valadas** [comment]
This can be confirmed in 9.4.0 RC by the portal level smtp settings that are stored encrypted but the IsSecure is 0
