### ISSUE TITLE
Azure connector save button is not localizable

### ISSUE THREAD

**Issue by valadas** [dnnsoftware/Dnn.Platform#2876]
## Description of bug
The Save button text in the azure connector is hardcoded and not localizable, I just noticed this fixing something else but it would be worth check the rest of this module for localization too.

Testes 9.4.0 alpha, but probably the case in previous releases too.

This screenshot highlights the difference, left is Azure connector, right is Google Analytics connector:

![image](https://user-images.githubusercontent.com/6371568/60505045-df794080-9c90-11e9-88e7-1352fb788d61.png)

**Comment by valadas** [comment]
This is still on my todo list for some day...

**Comment by sleupold** [comment]
has this been fixed meanwhile?

**Comment by sleupold** [comment]
this should be re-opened, until it is fixed
