### ISSUE TITLE
When editing user and error occurs then the current cached user still gets edited

### ISSUE THREAD

**Issue by donker** [dnnsoftware/Dnn.Platform#2878]
## Description of bug
When you edit your own details and during update the editing logic throws an error, the user appears to be updated but in fact it hasn't.

## Steps to reproduce
1. Set to "unique display name" in security settings
2. Log in as user X
3. Fill in display name of user Y
4. See error at top of screen in red (display name must be unique)
5. Refresh screen/navigate away
6. See you have user Y's display name (looks like it has successfully updated the user after all)
7. Clear cache
8. Back to user X (oh, DNN didn't update after all)

## Research
For this specific scenario (Unique DisplayName) the error is generated in line 502 of EditUser.ascx.cs. It looks like we need to have code there that reverts the DisplayName back to what it is. That or empty the cached user.

## Affected version

* [x] 9.4.0 RC

**Comment by valadas** [comment]
@donker can you shed some light, from the description I am thinking this is expected behaviour... You cannot set the same display name already in use by another user and when I change it to a new one it saves... Not sure I understand the issue...

**Comment by donker** [comment]
@valadas It's caching a failed edit. So the cached user is reflecting bad data.

**Comment by valadas** [comment]
I can no longer reproduce in current develop branch, I think this might have been fixed together with #4041
