### ISSUE TITLE
Install multiple DesktopModules in a single Package

### ISSUE THREAD

**Issue by kestasjk** [dnnsoftware/Dnn.Platform#2885]
**Creating an issue so that I can submit a pull request for an existing patch**

## Description of problem
I am making functionality customizations to an intranet which all share the same database connection, entities and business logic, using MVC, and it makes no sense to create lots of Packages / ModuleDefinitions each with their own assemblies, data folders, etc when MVC can cleanly host large modular projects.

The obvious use is to be able to have a DesktopModule per Controller in a project

## Description of solution
When uploading a package which has multiple <component type="Module"> DesktopModule definitions allow the DesktopModule to have its own <friendlyName> and <description>.

These are **already set up** in the DNN DesktopModule database structure / entity structure, but at the moment each DesktopModule in a Package takes the FriendlyName and Description of the package. This results in a "Key already exists" dictionary error.

Note that the change will not break compatibility with any existing packages / modules; if a DesktopModule does not specify a FriendlyName / Description itself the Package FriendlyName / Description will be used, which is the current behavior.

## Description of alternatives considered
Create a package for each controller by changing the build scripts, and try to fudge it so that both packages use the same assemblies and folders. But that would be messy and this is a very simple patch.

**Comment by valadas** [comment]
Merged

**Comment by mitchelsellers** [comment]
Due to branching changes, we will replay this against the release 10 branch once it is created, No action needed by submitter at this time.

**Comment by bdukes** [comment]
@dnnsoftware/approvers this change doesn't appear to be breaking to me, would we want to include it in 9.10.2?

**Comment by mitchelsellers** [comment]
I'm all for this one as early as we can get it

**Comment by david-poindexter** [comment]
Good with me @bdukes 🎉
