### ISSUE TITLE
Unable to Hide DNN Default Authentication Provider 

### ISSUE THREAD

**Issue by Mhtshum** [dnnsoftware/Dnn.Platform#2888]
## Description of bug
Default authentication provider is not hideable any more since 9.3.0

## Steps to reproduce
1. Install DNN Platform 9.3.1 
2. Login to the site as Superuser 
3. Add 3rd party module by installing the installable zip file 
4. Go to the Authentication table and set the IsEnable for the DNN auth provider to "False" 
5. Go to Settings > Servers > clear cache & restart the application or  Recycle the IIS AppPool  
6. Go to the site login page again

## Current result
It is blank

## Expected result
It should show newly installed provider and hide the default authentication provider
## Affected version
* [x] 9.2.2
* [x] 9.2.1
* [x] 9.2
* [x] 9.1.1

**Comment by mitchelsellers** [comment]
This was already fixed in #2814 and will be included in the 9.4.0 release, closing this item.
