### ISSUE TITLE
No user notification when programmatically adding a role

### ISSUE THREAD

**Issue by mjboggs1** [dnnsoftware/Dnn.Platform#2896]
## Description of bug
When adding a role programatically using RoleController.AddUserRole, there is a parameter for notifying the user.  When this parameter is set to 'true', the notification is still not sent to the user.

## Steps to reproduce
List the steps to reproduce the behavior:
1. Code a module using the RoleController.AddUserRole method with the notify boolean set to 'true'.
2. Add the module to a page.
3. Enter DNN as a super user.
4. Go to the page with the module.
5. Access the option coded to add the role.

## Current result
Role is added correctly, but no notification is received by a user.

## Expected result
Role is added correctly and the standard 'added role' notification message is received by the user.

## Affected version
* [x] 9.2.2
* [x] 9.2.1
* [x] 9.2
* [x] 9.1.1
* [x] 8.0.4

## Affected browser
* [x] Chrome
* [x] Safari
* [x] Internet Explorer
* [x] Edge

**Comment by valadas** [comment]
Is that module something you can share here by any chance, it would speed up testing and fixing if that is something that is possible.
