### ISSUE TITLE
Module Settings > Added to Pages pager does not work

### ISSUE THREAD

**Issue by msant7** [dnnsoftware/Dnn.Platform#2897]
## Description of bug
In Module Settings > Added to Pages section, the pager does not work when there is a large number of pages.

## Steps to reproduce
List the steps to reproduce the behavior:
1. Go a DNN Site that has > 20 pages
2. Add an HTML module, and choose the option to "Display Module on All Pages"
3. Click the pager to go to page 2
4. Page doesn't advance

## Current result
Grid does not advance to other rpages

## Expected result
Grid should advance to other pages

## Additional context
The PR does the following:
1. Wires up the PageIndexChange event
2. Updates the styling on the Pager

I also looked at other locations where GridView is used and Digital Assets Manager is the only other location currently that uses paging, and it has the proper events to do paging

## Affected version
* [x] 9.3.2

https://github.com/dnnsoftware/Dnn.Platform/pull/2898

**Comment by soheilkheiri** [comment]
This is a very critical problem. Please solve in milestone 9.4.3

**Comment by valadas** [comment]
The pull request was merged into the 9.4.x branch 10 days ago which means it will be included in 9.4.3 and this issue should have been closes when merged. The release candidate is available and providing there is no major regression issue or showstopper discovered, it should get officially released in a few days. Of course testing the RC on non-production sites is very welcome if you want to give it a try.
