### ISSUE TITLE
DotNetNuke.Services.Mail::sendMail doesn't use bodyEncoding for alternative view in multipart message

### ISSUE THREAD

**Issue by tingung** [dnnsoftware/Dnn.Platform#2899]
## Description of bug
DotNetNuke.Services.Mail::sendMail doesn't use bodyEncoding for alternative view in multipart message. Emails are sent as ASCII but whenever a special character such as \n or \r is included the content type becomes UTF-8.

## Steps to reproduce
List the steps to reproduce the behavior:
Create a Simple Email module 
1. Go to a page > Add Module > Module Creator 
2. For the View.ascx.cs, put in the sendmail method with ASCII encoding in the button event.
3. ` Mail.SendMail("from@local.me", "", "test@local.me", "", 0, "", 0, Encoding.ASCII, "body\n", "", "", "", "", "");`
4. Save the module. Save the field to send email and observe the email received. Check the email's Content-Type. 
5. Change the the "body\n" to "body". Save the module. Save the field to send email and observe the email received. Check the email's Content-Type.

## Current result
Email with body - "body\n" Content-Type received is text/plain; charset=utf-8
Email with body - "body" Content-Type received is text/plain; charset=us-ascii

## Expected result
Email's Content-Type charset should always consistent with encoding. If encoding is set to Encoding.ASCII, then charset should always ascii in 
regardless the body content

## Screenshots
https://www.loom.com/share/b9ebd96afcbf4070be17c063e7326752 - video recording

## Error log
Nope

## Additional context
https://github.com/dnnsoftware/Dnn.Platform/blob/584b0f54bd6b6d237594dd9f96053f14db0b1a53/DNN%20Platform/Library/Services/Mail/Mail.cs#L109 - the problem is 
the encoding is  set to null. We shall set the encoding with the bodyEncoding

## Affected version

* [x] 9.3.2
* [x] 9.3.1
* [x] 9.2.2
* [x] 9.2.1
* [x] 9.2
* [x] 9.1.1
* [x] 9.1
* [x] 9.0

## Affected browser

Browser independent issue
* [x] Chrome
* [x] Firefox
* [x] Safari
* [x] Internet Explorer
* [x] Edge

**Comment by mitchelsellers** [comment]
Due to branching changes, this change needs to be re-evaluated to see if it is needed for the 10.x release.  If so, the changes from PR #2900 will need to be replayed against the new 10.x branch.
