### ISSUE TITLE
Update jquery migrate and minify

### ISSUE THREAD

**Issue by mathisjay** [dnnsoftware/Dnn.Platform#2901]
## Description of problem
The default DNN installation ships with an unminified version on jquery-migrate 3.0.0.  There are several bugs in this version that can often be seen in console.  Plus, the js file is unminified which throws warnings up to systems like SEMRush that are measuring speed and performance.

## Description of solution
Upgrade to the latest 3.1.0 minified version.
https://code.jquery.com/jquery-migrate-3.1.0.min.js

## Affected version

* [x] 9.3.2

**Comment by mitchelsellers** [comment]
Usage of CDF to minify is a temporary workaround for the minification

**Comment by thabaum** [comment]
I just had to turn off minifyJS on a site to get it to load again.  I have it turned on for other sites... suppose I need to turn if off?
