### ISSUE TITLE
Module missing after import data into site

### ISSUE THREAD

**Issue by tingung** [dnnsoftware/Dnn.Platform#2910]
## Description of bug
When exporting site with option"Include Deletions", TabModules.IsDeleted = 1 (true) is included as part of export data. Then, import the data into the site with existing Modules will cause Modules.IsDeleted updated to 1 (true). Therefore, subsequent export the site without "Include Deletions" will not contain the Modules and TabModules which cause the module missing after import into the new site. Refer to steps to reproduce to see the impact to the user. 

## Steps to reproduce
List the steps to reproduce the behavior:
1. Create a new page, add HTML module A and HTML module B into the page; 
3. Delete module A; 
4. Go to Settings > Export/Import, export the website in Full Mode, make sure include deletion is enabled; 
5. Import the exported package into the same site; 
6. Go to Content > Recycle bin, restore the deleted module; 
7. Edit the new page, at this time the 2 modules should both display on the page, publish the page; 
8. export the website in full mode again, named it as "V2"; 
9. create a new child empty site, import with V2 package; 
10. navigate to the new page in child site.

## Current result
Module A is missing in the imported site.

## Expected result
Module A should appear in the imported site.

## Screenshots
The recording is based on Evoq but it is the same for DNN.Platform. Issue is reproducible for all modules. I have tested with normal HTML module. 
https://www.screencast.com/t/uM0NLi2W

## Error log
Paste the error log that is related to this issue.

## Additional context
Found the root cause - https://github.com/dnnsoftware/Dnn.Platform/blob/development/DNN%20Platform/Modules/DnnExportImport/Components/Services/PagesExportService.cs#L900

ModuleInfo.IsDeleted is shared by both TabModules and Modules table. Modules.IsDeleted should based on ExportModule.IsDeleted and TabModules.IsDeleted should based on ExportTabModule.isDeleted. However, ModuleInfo.IsDeleted is only set to ExportTabModule.isDeleted value.

When import data to the same site, Modules.IsDeleted value is updated to be same as ExportModule.IsDeleted. After restored the TabModules, TabModules.IsDeleted is changed to false but Modules.IsDeleted is remains as true. When exporting the site without included deletions, Modules is not exported because Modules.IsDeleted is remains as true.

To resolve the issue, we should update Modules.IsDeleted with ExportModule.IsDeleted value.
```
                                local.IsDeleted = otherModule.IsDeleted; // set as ExportModule.IsDeleted value
                                _moduleController.UpdateModule(local); // update Modules
                                local.IsDeleted = other.IsDeleted; // set back to ExportTabModule.IsDeleted value
```

## Affected version

* [x] 9.3.2
* [x] 9.3.1
* [x] 9.2.2
* [x] 9.2.1
* [x] 9.2
* [x] 9.1.1
* [x] 9.1
* [x] 9.0

## Affected browser

* [x] Chrome
* [x] Firefox
* [x] Safari
* [x] Internet Explorer
* [x] Edge

**Comment by valadas** [comment]
Merged, thanks.
