### ISSUE TITLE
Deleted page can still be selected as parent page

### ISSUE THREAD

**Issue by berkarslan-xo** [dnnsoftware/Dnn.Platform#2919]
## Description of bug
There is a bug in the Pages screen when selecting a parent page. 

The deleted page is found inside the Recycle Bin. Behavior changes when the deleted page in Recycle Bin is deleted. Delete page is no longer visible in the Parent Page dropdown.

Note: Only deleted page that has a parent page can still be selected as a parent page. The deleted page that does not have parent page, once deleted is not visible in the Parent Page dropdown.

## Steps to reproduce
1. Create a page called "PAGETODELETE" and select a parent page for it. 
2. After creation, delete PAGETODELETE. 
3. Click Add Page, in the new page form, go to Parent Page dropdown 

## Current result
In Pages screen, you are still able to see PAGETODELETE page.

## Expected result
In Pages screen, you should not be able to see PAGETODELETE page.

## Screenshots
![image](https://user-images.githubusercontent.com/45750757/62232041-f5803b00-b3cd-11e9-9d91-0f281ff6c64e.png)

## Error log
Paste the error log that is related to this issue.

## Additional context
Add any other context about the bug that may be helpful for resolution.

## Affected version

* [x] 9.3.2 latest supported release
* [x] 9.2.2 latest supported release

## Affected browser

* [x] Chrome
* [x] Firefox
* [x] Safari
* [x] Internet Explorer
* [x] Edge

**Comment by valadas** [comment]
I can reproduce in 9.4.0 RC

**Comment by valadas** [comment]
Closing, all PRs merged now
