### ISSUE TITLE
RFC: Update notification emails

### ISSUE THREAD

**Issue by valadas** [dnnsoftware/Dnn.Platform#2921]
## Description of Problem
We keep talking about the importance of updating and I was thinking that if you manage multiple installation, you kinda need to manually keep track of versions running or login to each installation to check what version it is. This is true for both Dnn and installed extensions. Dnn has an update notification already and an extension feed, but you need to login to see it.

Additionally we do not have any way to notify all Dnn hosts because we do not request email addresses in order to download or install Dnn.

This idea comes from emails I get from my VoIP system and my NAS,  which have something similar that regularly check for new versions, but it actually emails me about available updates.

## Proposed Solution Option 1
Build a scheduled task that fires up the existing upgrade check for Dnn and for the installed modules and emails the host about available updates.
From the UI side of things, we would just need to add one fieldd only visible when "check for updates" is enabled:
- Notify Host (No, Daily, Weekly, Monthly)

The minimum email could just list the currently installed version and available version for Dnn and each installed module. Further down the line we could improve this to add links to more details or where to download.

Thoughts?

**Comment by EPTamminga** [comment]
I am not a fan of emails with just this info. Suppose you have to manage 500 sites, think about the # of emails arriving.
It is not only about updates, getting an inventory list of all components (in XML format?) with possible updates would help to get an overview/state of a complete DNN installation. And if you are really into managing a large # of sites, not an email, but webservices (RESTapi) call providing the info to a central DNN site would provide options for system management?

**Comment by valadas** [comment]
Yes, that is a good idea too, but this specific idea is to allow (optionally, id would be off by default) to get notified when there are updates available... Thinking about the guy who has 1-5 installations that he rarely logs into, that way he would at lest know, oh well this module that I use has updates, let me go check what's new, oh there is a new Dnn release, let me go check that out...

**Comment by EPTamminga** [comment]
Email is useful in that scenario (a few sites). The make it more worthwhile, include the place (URL) to get the update, attach an XML  with the info, in addition to text in the email?

**Comment by valadas** [comment]
Yeah, I would see this as 2 separate things though, emails for people and a API (secured) for some other integrations...
