### ISSUE TITLE
Support to allow all (*) IP Address in IPFilter when creating a new filter

### ISSUE THREAD

**Issue by tingung** [dnnsoftware/Dnn.Platform#2922]
## Description of Problem
The default value for IPFilter is allow all IP Address with value First IP (table IPFilter.IPAddress) set as *. However, user is not allowed to create a new filter with First IP (IPAddress) set as * because both UI validation and server side validation is ensuring the First IP (IPAddress) as valid IP Address.

## Proposed Solution Option 1
Should allow  user to create IPFilter with * as First IP(IPAddress)

## Proposed Solution Option 2 (If Needed, repeat for more)
Another proposed solution to the problem

## Alternatives Researched
This is the changes which blocking the IP Address as * - https://github.com/dnnsoftware/Dnn.Platform/commit/d8815830c5ff467e1a5631e236eb37bd1afec815#diff-3ba5f3f4fffdba1d1cbdaadfd62ce1daR76

## Affected version

* [x] 10.0.0 nightly build
* [x] 9.4.1 nightly build
* [x] 9.4.0 release candidate
* [x] 9.3.2 latest supported release

**Comment by valadas** [comment]
Copied to AdminExperience too since this will need 2 PRs to fix

**Comment by valadas** [comment]
@tingung This issue is still valid after your other PR in Admin Experience right?

**Comment by tingung** [comment]
Yes. it is still valid. This issue is to create IP filter with (*) as first IP. The earlier PR is to resolve the IP Address UI problem.

**Comment by valadas** [comment]
Cool, thanks @tingung

**Comment by valadas** [comment]
@tingung I _think_ this was resolved and I am closing the issue, if I am wrong, please comment
