### ISSUE TITLE
Superhost is not allowed to login if the host IPAddress is not allowed in IPFilter

### ISSUE THREAD

**Issue by tingung** [dnnsoftware/Dnn.Platform#2923]
## Description of Problem
Enable IP Filter and restrict the IP Address to particular IP. Try to login with superhost user. Login is denied. 

## Proposed Solution Option 1
Superhost user should supersede IP Filter restriction.

## Affected version

* [x] 10.0.0 nightly build
* [x] 9.4.1 nightly build
* [ ] 9.4.0 release candidate
* [ ] 9.3.2 latest supported release

**Comment by valadas** [comment]
I am pretty sure this is by design and is a security feature, if I am wrong @dnnsoftware/tag please comment.
