### ISSUE TITLE
Export data tier application in Azure not possible (DNN database)

### ISSUE THREAD

**Issue by nisipop** [dnnsoftware/Dnn.Platform#2924]
## Current result
Try to make backup of the DNN database created as Azure SQL database.
1. In SQL Server Management Studio click on Export data tier application (generate backup, BACPAK file).

## Expected result
BACPAK generation can be done successfully.

## Error log
TITLE: Microsoft SQL Server Management Studio
------------------------------

One or more unsupported elements were found in the schema used as part of a data package.
Error SQL46010: Procedure: [dbo].[AddTab] contains a statement that is not supported on Microsoft Azure SQL Database v12. The specific error is: Incorrect syntax near Url.
Error SQL46010: Procedure: [dbo].[UpdateTab] contains a statement that is not supported on Microsoft Azure SQL Database v12. The specific error is: Incorrect syntax near Url.
Error SQL46010: Procedure: [dbo].[DeleteUrlTracking] contains a statement that is not supported on Microsoft Azure SQL Database v12. The specific error is: Incorrect syntax near Url.
Error SQL46010: Procedure: [dbo].[DeleteUrl] contains a statement that is not supported on Microsoft Azure SQL Database v12. The specific error is: Incorrect syntax near Url.
Error SQL46010: Procedure: [dbo].[AddSiteLog] contains a statement that is not supported on Microsoft Azure SQL Database v12. The specific error is: Incorrect syntax near Url.
Error SQL46010: Procedure: [dbo].[GetUrlTracking] contains a statement that is not supported on Microsoft Azure SQL Database v12. The specific error is: Incorrect syntax near Url.
Error SQL46010: Procedure: [dbo].[GetUrls] contains a statement that is not supported on Microsoft Azure SQL Database v12. The specific error is: Incorrect syntax near Url.
Error SQL46010: Procedure: [dbo].[GetUrl] contains a statement that is not supported on Microsoft Azure SQL Database v12. The specific error is: Incorrect syntax near Url.
Error SQL46010: Procedure: [dbo].[SaveTabUrl] contains a statement that is not supported on Microsoft Azure SQL Database v12. The specific error is: Incorrect syntax near Url.
Error SQL46010: Procedure: [dbo].[UpdateUrlTrackingStats] contains a statement that is not supported on Microsoft Azure SQL Database v12. The specific error is: Incorrect syntax near Url.
Error SQL46010: Procedure: [dbo].[AddUrlTracking] contains a statement that is not supported on Microsoft Azure SQL Database v12. The specific error is: Incorrect syntax near Url.
Error SQL46010: Procedure: [dbo].[UpdateUrlTracking] contains a statement that is not supported on Microsoft Azure SQL Database v12. The specific error is: Incorrect syntax near Url.
Error SQL46010: Procedure: [dbo].[AddUrl] contains a statement that is not supported on Microsoft Azure SQL Database v12. The specific error is: Incorrect syntax near Url.
Error SQL46010: Procedure: [dbo].[GetTabUrls] contains a statement that is not supported on Microsoft Azure SQL Database v12. The specific error is: Incorrect syntax near Url.
Error SQL46010: Procedure: [dbo].[UpdateServer] contains a statement that is not supported on Microsoft Azure SQL Database v12. The specific error is: Incorrect syntax near URL.
Error SQL46010: Procedure: [dbo].[AddPackage] contains a statement that is not supported on Microsoft Azure SQL Database v12. The specific error is: Incorrect syntax near Url.
Error SQL46010: Procedure: [dbo].[dnnLinks_UpdateLink] contains a statement that is not supported on Microsoft Azure SQL Database v12. The specific error is: Incorrect syntax near Url.
Error SQL46010: Procedure: [dbo].[dnnLinks_GetLinks] contains a statement that is not supported on Microsoft Azure SQL Database v12. The specific error is: Incorrect syntax near URL.
Error SQL46010: Procedure: [dbo].[UpdatePackage] contains a statement that is not supported on Microsoft Azure SQL Database v12. The specific error is: Incorrect syntax near Url.
Error SQL46010: Procedure: [dbo].[dnnLinks_GetLink] contains a statement that is not supported on Microsoft Azure SQL Database v12. The specific error is: Incorrect syntax near URL.
Error SQL46010: Procedure: [dbo].[dnnLinks_AddLink] contains a statement that is not supported on Microsoft Azure SQL Database v12. The specific error is: Incorrect syntax near Url.
Error SQL46010: View: [dbo].[vw_Tabs] contains a statement that is not supported on Microsoft Azure SQL Database v12. The specific error is: Incorrect syntax near Url.
 (Microsoft.SqlServer.Dac)

## Additional context
The issues can be fixed in the stored procedures and views by putting "url" reference column into brackets => [url]

## Affected version
9.3.2

**Comment by mitchelsellers** [comment]
Was this an upgraded installation?  We have hundreds of DNN Installations that are on Azure DB's successfully.

**Comment by davidjrh** [comment]
Hi, I have verified the issue by running a local 9.3.2 vanilla installation **on a local server**. The problem is caused when **using the SSMS 18.2** version. 

WORKAROUND: use **SSMS 17.9.1** to export the bacpac

Anyway, the final solution should be to change those stored procedures to be fully compatible with the new SSMS versions.

**Comment by valadas** [comment]
What needs to be done here, is this something to fix in Dnn or a bug with SSMS? If something to fix in Dnn, do we want to make that happen in 10 ?

**Comment by noahbast** [comment]
I just ran into this issue trying to create a BACPAC of a 9.3.2 site on Azure.  Thankfully a coworker still had the old version of SSMS installed, so we were able to backup the site.  Initial searches for an SSMS v17.9.1 installer were unsuccessful.

**Comment by mitchelsellers** [comment]
@valadas I believe it is the name "Url" for a column that isn't properly escaped

**Comment by valadas** [comment]
Ok, so assigning this as a bug, but I do not have a testbed for this here.

**Comment by KenTombs** [comment]
I have an Azure SQL backpac (DNN9.3.2) that we may be forced to move to a VM. Is this issue likely to affect that in some way?

**Comment by krynn1** [comment]
@mitchelsellers I have upgraded from 7.03.02 to 9.04.04 version of DNN and am trying to use the Data Migration Assistant. I have the same issues. Is there an issue with upgrading versions of DNN and  moving to Azure Managed Database?

**Comment by mitchelsellers** [comment]
I'll be working on this later this week

**Comment by krynn1** [comment]
I've upgraded from 7.3? to 9.4 and had this same problem. I tried to change url to  [url] where shown but that broke the site, specifically tabs and css. I'm not sure where to go from here.

**Comment by mitchelsellers** [comment]
Right now the workaround would be to use the older version of SSMS.  Its actually a bug in SSMS not DNN as it is "acceptable" to have queries with this structure now.

**Comment by noahbast** [comment]
FYI, you can download the compatible version of SSMS here: https://docs.microsoft.com/en-us/sql/ssms/release-notes-ssms?view=sql-server-2017#download-ssms-1791

I ran into this issue again and had to go find the installer for the old version to make a backup.

**Comment by valadas** [comment]
Sooo should we close this issue because it is not Dnn related @mitchelsellers @noahbast

**Comment by mitchelsellers** [comment]
@valadas No, I'm going to try to put a fix for the core in for 9.5.0. 

Its a simple fix for us to Play "nice" and we might as well as it really is the true SQL Standard

**Comment by krynn1** [comment]
Yes I got it to work using the old version of SSMS, just as an fyi
Microsoft Data Migration assistant throws the same errors as the new SSMS

**Comment by valadas** [comment]
@mitchelsellers cool, triaged accordingly
