### ISSUE TITLE
Losing PortalSettings and UserInfo objects during runtime

### ISSUE THREAD

**Issue by iiminov** [dnnsoftware/Dnn.Platform#2926]
## Summary
Losing access to ``PortalSettings`` and ``UserInfo`` objects as provided by ``DnnApiController`` in a service endpoint.

## Extended description
I have web service endpoint for a module. The endpoint makes a request to MicrosoftGraph API (multiple times) to re-create a folder structure in users OneDrive. But just before the job is finished I lose access to the objects ``PortalSettings`` and ``UserInfo``. I only need to access ``PortalSettings.PortalId`` and ``UserInfo.UserID``.

I know that I should probably assign both values to a local variable(s) which would solve the problem. But this strange issue seems to affect so far 3 of 6 installs where I tried this code. 

Has anyone come across this issue before? Or have I forgot something? Any clarification on this issue is welcome.

## Steps to reproduce (if necessary)
List the steps to reproduce the behavior:
1. Create service endpoint that makes repeated calls to ``/me/drive/items`` to create a folder structure in users OneDrive (example below)

```
[HttpPost]
[ValidateAntiForgeryToken]
public async Task<HttpResponseMessage> MyService()
{
    HttpClient httpClient = new HttpClient();
    /* i can always access PortalSettings.PortalId and UserInfo.UserID here */
    /* int portaId = PortalSettings.PortalId; // solves the problem */
    /* int userId = UserInfo.UserID; // solves the problem */
    ...
    // example of a request to create folder in users OneDrive
    var response = await httpClient.PostAsync(string.Format("https://graph.microsoft.com/v1.0/me/drive/items/{0}/children", parentFolderId), formContentForNewFolder);
    ...
    /* but i lose access to PortalSettings.PortalId and UserInfo.UserID here */
    // make a few more nested folders in similar manner
    ...
    return Request.CreateResponse(HttpStatusCode.OK, new { message = "job finished" });
}
```

## Error log (if necessary)
Object reference not set to an instance of an object when I try to access either ``PortalSettings.PortalId`` or ``UserInfo.UserID``.

## Additional context
Between the affected installs and none affected installs, I checked HostSettings, PortalSettings,  .dlls in bin folder, web.config file, iis pools and folder permissions. But nothing had jumped out at me as suspicious.

## Affected version

* [x] 7.4.2 (a relic but not all installs are affected by exactly the same code and i don't understand why)

## Affected browser

* [x] Chrome
* [x] Firefox
* [x] Edge

**Comment by iiminov** [comment]
I guess to answer my own question the issue turned out to be in the web.config file.

```
<add key="aspnet:UseTaskFriendlySynchronizationContext" value="true" />
```

Didn't give this much thought until someone else pointed it out.


> If this key value is set to false [default], asynchronous code paths in ASP.NET 4.5 behave as they did in ASP.NET 4.0. If this key value is set to true, ASP.NET 4.5 uses code paths that are optimized for Task-returning APIs. Setting this compatibility switch is mandatory for WebSockets-enabled applications, for using Task-based asynchrony in Web Forms pages, and for certain other asynchronous behaviors.

[reference](https://docs.microsoft.com/en-us/previous-versions/aspnet/hh975440(v=vs.120)) page

**Comment by bdukes** [comment]
@donker @mitchelsellers I wonder if this affects/fixes our issue with setting `Async="true"` on multi-lingual sites… Do you still have that test site available, @donker?

**Comment by mitchelsellers** [comment]
Oh boy, I bet it does

**Comment by bdukes** [comment]
@mitchelsellers @donker I just did a quick test, and adding `Async=true` in `Default.aspx` while leaving `aspnet:UseTaskFriendlySynchronizationContext` set to `true` resulted in URLs that always default to en-us` despite the current language.  Switching `aspnet:UseTaskFriendlySynchronizationContext` to `false` fixed the language issue.  However, as mentioned above, that will end up causing other issues so I don't know that this is usable solution.  I wonder if it's possible to get anyone from the ASP.NET team to take a look and help us evaluate our options…

Related to #2089

**Comment by mitchelsellers** [comment]
@bdukes Circling back on this issue, do we have a quick way we can document this oddity so I can get it to Microsoft?

**Comment by bdukes** [comment]
I would imagine that we could create a simple reproduction using an `aspx` page with `Async=true` and a `web.config` with `aspnet:UseTaskFriendlySynchronizationContext` set to `true`, and outputting the `CultureInfo.CurrentCulture` from various components.  But we'd need to dig a little bit and figure out what's triggering the switch to a different context.

**Comment by mitchelsellers** [comment]
@bdukes ok, lets try to coordinate on this, I have the right people to reach out to

**Comment by bdukes** [comment]
@mitchelsellers it's surprisingly trivial to reproduce: https://gist.github.com/bdukes/30c4f01c938c173f988149a4df63645b

Most of that gist is just code to make it easier to switch back and forth.  The simplest reproduction includes the following:

* `web.config`
  * `aspnet:UseTaskFriendlySynchronizationContext` set to `true`
  * `httpRuntime` with `targetFramework` set to `4.8` (it works correctly with `4.5`, shows incorrect value starting at `4.6`)
* `aspx` page
  * `Async=true`
  * `Thread.CurrentThread.CurrentCulture` set to something other than the default of `en-US`
  * When you output `CultureInfo.CurrentCulture`, it'll show `en-US` instead of the value you set

**Comment by mitchelsellers** [comment]
Well I got it off to the various folks, they pointed me to this thread: https://stackoverflow.com/questions/43057536/thread-culture-not-being-honored-in-embedded-code-blocks

Which basically means that our example might not be a great example, but still digging!

**Comment by bdukes** [comment]
No, I don't think that's the issue.  That should just affect formatting of values, but I'm outputting the culture, which shouldn't be affected by the format provider.  And that doesn't explain why changing `Async` or `aspnet:UseTaskFriendlySynchronizationContext` or `targetFramework` causes it to start displaying the expected value.

**Comment by bdukes** [comment]
I've updated [that gist](https://gist.github.com/bdukes/30c4f01c938c173f988149a4df63645b) with more variations, including direct `Response.Write` calls.

![Example page output with en-US output, except during Init](https://user-images.githubusercontent.com/59507/87598168-a69fe400-c6b8-11ea-85ba-c7930f8fcf9b.png)
