### ISSUE TITLE
Blank Name is accepted as Group name

### ISSUE THREAD

**Issue by sergeydryomin** [dnnsoftware/Dnn.Platform#2927]
## Description of bug
Blank Name (with only spaces or tabs) is accepted as Group name

## Steps to reproduce
1. Login with superuser
2. PB > Roles > Create New role
3. Enter a Role name
4. From the Role Group dropdown > Select New group
5. Enter Blank name (Enter Space)
6. Hit tab button (It should move to Description field but it doesn't)
7. Add blank description
8. Click Save

## Current result
System accepts Blank Group Name.

## Expected result
Blank group name should not be accepted.

## Screenshots
![DNN-18333](https://user-images.githubusercontent.com/33347470/62623854-8608cf00-b92a-11e9-913f-18244d531d6e.png)

## Affected version
* [x] 9.4.0 release candidate
* [x] 9.3.0

## Affected browser
* [x] Chrome
* [x] Firefox
* [x] Safari
* [x] Internet Explorer
* [x] Edge

**Comment by valadas** [comment]
This was resolved in the UI but let's keep this issue to fix it in the platform too. See https://github.com/dnnsoftware/Dnn.AdminExperience/pull/1089

**Comment by valadas** [comment]
Merged

**Comment by youngcaseho** [comment]
> 
> 
> This was resolved in the UI but let's keep this issue to fix it in the platform too. See [dnnsoftware/Dnn.AdminExperience#1089](https://github.com/dnnsoftware/Dnn.AdminExperience/pull/1089)

Which release would you like the fix in platform to target.

**Comment by youngcaseho** [comment]
Also, the proposed changes would be to add a new method to Require.cs (NotNullOrHasNoWhiteSpace) and replace the changes made in [dnnsoftware/Dnn.AdminExperience#1089](https://github.com/dnnsoftware/Dnn.AdminExperience/pull/1089) with a call to the new method.....?

**Comment by valadas** [comment]
Anything that is not a breaking change can go into the release/9.4.x branch and is periodically merged back into development. I did not dig into how it is validated now, but I guess a simple !variableName.IsNullOrWhiteSpace() would do... Or what appears to make sense in that code...
