### ISSUE TITLE
When delete MVC module, the mvc [HTTPPOST] action will be invoked.

### ISSUE THREAD

**Issue by cxdone** [dnnsoftware/Dnn.Platform#2930]
I created a MVC module, the module have 1 controller and 2 action, one of the aciton for HTTP POST,  when i delete the module from exist page, the HTTP POST filterd action was be invoked.

**Comment by valadas** [comment]
This is a very vague issue, can you share some code that would allow us to reproduce this issue ?

**Comment by valadas** [comment]
Closing this issue due to lack of response
