### ISSUE TITLE
Links in repository readme should be updated to the dnncommunity.org site

### ISSUE THREAD

**Issue by valadas** [dnnsoftware/Dnn.Platform#2933]
There are a couple links on the readme that should be updated to point to the new community site forums and blog, etc.

**Comment by david-poindexter** [comment]
@valadas are you referring to the **Quick Links** section in general or are there specific links you had in mind?  I'll be happy to take this one on by the way.

**Comment by valadas** [comment]
Yes the main readmy quick links, some items that could have a better destination:

Questions & Answers, Showcase, Forums, etc.

**Comment by david-poindexter** [comment]
Okay, thanks @valadas!

**Comment by valadas** [comment]
Merged
