### ISSUE TITLE
Attack Signalr to module in dnn9

### ISSUE THREAD

**Issue by tvmodvn** [dnnsoftware/Dnn.Platform#2934]
Help me?
Code Signalr microsoft with module dnn (version 9.3.2) importan err script 
<script src="~/signalr/hubs"></script>
Version js me:
jquery.signalR-2.4.1.min.js
jquery-2.2.4.min.js
modernizr-2.8.3.js
contact: tvmodvn@gmail.com. Thanks you

**Comment by valadas** [comment]
I do not understand the issue, can you explain in more details, does this come from a third party module? If so which one ?

**Comment by tvmodvn** [comment]
> I do not understand the issue, can you explain in more details, does this come from a third party module? If so which one ?


I want to incorporate the Signalr of microsft into my module. So how will it do? ^^

**Comment by bdukes** [comment]
See this post for information: https://www.dnnsoftware.com/community-blog/cid/151246/using-signalr-with-dotnetnuke-modules

**Comment by valadas** [comment]
Hi @tvmodvn if the link provided by @bdukes does not answer your question, then I would recommend posting in the forums at https://dnncommunity.org/forums

Github issues are for issues with the platform and this is more of a development question. Thanks.
