### ISSUE TITLE
DNN menu shows non-translated pages

### ISSUE THREAD

**Issue by eXistenZe** [dnnsoftware/Dnn.Platform#2936]
## Description of bug
In multi language sites, DNN is showing all translated pages in the current language in the main menu, plus the untranslated ones in the default language.

## Steps to reproduce
1. Activate at least two languages
2. Activate content localization
3. Translate some pages and leave other untranslated

## Current result
DNN is showing the menu with all translated paged in the current language, plus the untranslated ones in the default language

## Expected result
Untranslated pages should be hidden by default.

## Affected version
I think this is recent, perhaps 9.3.2

**Comment by valadas** [comment]
@eXistenZe it is normal that they show for administrators, hosts and members of the translation group. If you are able to see them in other situations then this would be a bug and I would suggest opening a new issue with more steps to reproduce including the user accounts involved and the specific version affected. I am closing this issue for now and please open a new more detailed one if that is the case.
