### ISSUE TITLE
CheckDefaultPage failed in 9.4.0 RC

### ISSUE THREAD

**Issue by zyhfish** [dnnsoftware/Dnn.Platform#2942]
## Description of bug
CheckDefaultPage failed in 9.4.0 RC

## Steps to reproduce
List the steps to reproduce the behavior:
1. install Dnn Platform 9.4.0 RC and login as host;
2. navigate to Setting > Security > Security Analyzer in Persona bar.

## Current result
the CheckDefaultPage step failed.

## Expected result
all steps should pass the check.

## Screenshots
![image](https://user-images.githubusercontent.com/3364448/63079219-6730bb00-bf70-11e9-8873-f7d6826f2f54.png)

## Affected version
* [ *] 9.4.0 release candidate

**Comment by mitchelsellers** [comment]
This is expected, we do not yet have updated checksums

**Comment by valadas** [comment]
I am closing this issues since we already have one to handle this in AdminExperience
