### ISSUE TITLE
cache WebResource.axd and ScriptResource.axd parameters

### ISSUE THREAD

**Issue by jac69** [dnnsoftware/Dnn.Platform#2946]
WebResource.axd and ScriptResource.axd files generated by minify options have a No Cache parameter that forces no cache at users browsers or cdn.

This is not good on a performance perspective. Is it possible to change this so we can control it?

**Comment by valadas** [comment]
From what I can see, they are cached:
![image](https://user-images.githubusercontent.com/6371568/63148797-4d26c500-bfd0-11e9-85e9-6dfc9e91de1a.png)

They should not be cached if the site is in debug mode though. Please check if you web.config is in debug mode. If this is still an issue after this check, please open a new issue by following the issue template including Dnn version, browser used, etc. Thanks.
