### ISSUE TITLE
Host / Admin menu showing nav_ as prefix

### ISSUE THREAD

**Issue by DNNUser** [dnnsoftware/Dnn.Platform#2948]
After changing the default language of a portal from US to EN (or any other language)
The Host and Admin menu are having a prefix of "nav_" 
any idea why?
any work around to hide the US language? 

Many thanks
A

**Comment by DNNUser** [comment]
Some image to show the issue
![menu with nav_](https://user-images.githubusercontent.com/54165653/63145381-9f9ccb80-c03a-11e9-9852-7bae0a77758b.png)
![site lang](https://user-images.githubusercontent.com/54165653/63145382-9f9ccb80-c03a-11e9-93cc-7477f21e371e.png)

**Comment by mvanlaar** [comment]
The language packs are not installed. You can install them from extensions.

**Comment by DNNUser** [comment]
Thank you for the speedy response, I am after en_GB but I can not find it in the extensions list,
any other place to get it from? 
![lang](https://user-images.githubusercontent.com/54165653/63146246-b1cc3900-c03d-11e9-9ab3-85075ce561e2.png)

**Comment by EPTamminga** [comment]
The language packs that you see are the only "official" LP's distributed and maintained by DNN Corp (in the past)and the DNN COmmunity (ATM).
Community members have created LP's for DNN core and various modules in various languages. DNN-Connect.org (the DNN community in EU) has collected these LP's. They can be found here: https://www.dnn-connect.org/community/translations

**Comment by DNNUser** [comment]
Thank you EPTamminga, All I am after is setting the language from en-US to en-GB, but when I do , all the menu get missed, as image shows.

Many thanks
a

**Comment by valadas** [comment]
To add to this discussion languages also have a fallback option

![image](https://user-images.githubusercontent.com/6371568/63146694-d8e92300-bfc9-11e9-9f06-04e996ea9221.png)

So if the current language is missing some (or in this case all) the keys, it will fallback to the values in the fallback language selected in that language options. It is often enough for regions that have the same language (in my case en-US is goof for use in en-CA). In your case I am not sure if it does the job or if some different spellings are important (like color vs colour or some such)...

Can you check if you have a fallback language selected there that is one of the core ones (like en-US) or System default.

**Comment by DNNUser** [comment]
I think this is happening in DNN 9.3.2, I have done this many times with no problems, like dnn 7 aand dnn 9.1, I add a language from the top menu , select the language as a site default, it works. but this is only happening in DNN 9.3.2,  if I put any language in the Site default ,all menus will shows nav_.. (like image above) , when I change the Site default to US menu re appear correctly with no nav_.
 Wondering if there is any work around or any other way to make the  Site Default English united kingdom. 
All I need is to Hide the US flag and show UK in the site language selector.

Many thanks 
A

**Comment by sleupold** [comment]
did you by accident enable "Content Localization"?

**Comment by valadas** [comment]
That is odd I did it often similar to you but for en-CA I will give it a try in 9.3.2 and see what comes up. Just to reproduce in a similar setup than yours, was this an upgrade or a clean install?

**Comment by DNNUser** [comment]
@sleupold , I have enabled it , but disabled it again
@valadas, its a clean new copy.

Many thanks
Anmar

**Comment by DNNUser** [comment]
All working fine now, 
What I did
Downloaded the US pack, change it to en-GB then re upload , --> select  UK as default. all working 
now.
I use to do this by selecting UK as default language and DNN will create all resources for en-GB.

Many thanks for the Support,   @valadas  and @sleupold .

A

**Comment by valadas** [comment]
Can anyone else reproduce this issue on 9.3.2 ? I could not reproduce and we need to check if it is a widespread issue or something special about this one installation...

**Comment by valadas** [comment]
I am assuming this was not reproducible by others and it has to do with some special circumstances with some language packs. If I am wrong, please open a new issue with clear steps to reproduce.
