### ISSUE TITLE
Startup code can fail loading all dependencies if a single type fails

### ISSUE THREAD

**Issue by valadas** [dnnsoftware/Dnn.Platform#2952]
## Description of bug
The startup code tries to get types safely but if a single type fails for any reason, all the types in that assembly are ignored, this can cause very odd and hard to troubleshoot bugs.

## Steps to reproduce
List the steps to reproduce the behavior:
1. Create a basic module with EF6
2. Forget to put the EF6 assemblies in the bin folder
3. Add a webapi to the module
4. Notice the webapi does not work, no errors are logged even with highest levels of logging.

* [ ] 10.0.0 nightly build
* [ ] 9.4.1 nightly build
* [x] 9.4.0 release candidate
* [ ] 9.3.2 latest supported release

**Comment by mitchelsellers** [comment]
Just to add a bit to this, this is an issue that has been around a LONG time that has resulted in all kinds of questionable behaviors for developers, primarily since the start of developing MVC modules.

**Comment by valadas** [comment]
Merged
