### ISSUE TITLE
Validate Reflection Usage with Regards to IsAssignableFrom

### ISSUE THREAD

**Issue by mitchelsellers** [dnnsoftware/Dnn.Platform#2954]
Currently when finding and registering the Controllers for DnnApiController implementations we are using an IsAssignableFrom check via Reflection.  ([Found here](https://github.com/dnnsoftware/Dnn.Platform/blob/cb5c2d05e3f0d54ebc0dd68a03b8ff708bae4c46/DNN%20Platform/DotNetNuke.Web/Api/Extensions/StartupExtensions.cs))

This behavior works, but semantically, IsSubclassOf is slightly better to ensure we capture the right behaviors.  

However, I'm not 100% sure of the need/benefit of a change I think this should be researched.  Performance isn't a huge concern, maintainability and proper behavior is better as this only occurs once per application start.

For Reference, t[his article discusses](https://theburningmonk.com/2011/03/type-issubclssof-and-type-isassignablefrom/) the two options a bit more. 
## Affected version

* [x] 10.0.0 nightly build
* [x] 9.4.1 nightly build
* [x] 9.4.0 release candidate
* [ ] 9.3.2 latest supported release

**Comment by valadas** [comment]
I am assigning this to 10.0.0 for now, change it if this should go in another version.

**Comment by mitchelsellers** [comment]
This will be tackled as part of the 10.x release.  Keeping this open
