### ISSUE TITLE
Infinite loop occurs in vocabularies

### ISSUE THREAD

**Issue by berkarslan-xo** [dnnsoftware/Dnn.Platform#2955]
## Description of bug
Page hangs infinitely when a sort of special characters are entered into Tag Add page.

## Steps to reproduce
List the steps to reproduce the behavior:
1. Install 9.2.2 (or use 9.4.x branch) and login as host; 
2. Go to Settings > Vocabularies
3. Open Tags panel
4. Try to add a new term named "&test;". 

## Current result
The request will never complete.

## Expected result
The name should able added.

## Affected version

* [x] 9.4.0 release candidate

## Affected browser

* [x] Chrome
* [x] Firefox
* [x] Safari
* [x] Internet Explorer
* [x] Edge

**Comment by valadas** [comment]
Merged
