### ISSUE TITLE
Asset Manager activity wheel constantly spins

### ISSUE THREAD

**Issue by berkarslan-xo** [dnnsoftware/Dnn.Platform#2958]
## Description of bug
Asset manager file browsing doesn't work for a specific folder.

## Steps to reproduce
1. Use the customer's environment
2. Login to the site 
3. Browse to http://som.dnndev.me/182/School_Finance_Upload?folderId=43673&view=gridview&pageSize=10 
4. Start browsing through the folders and you will see the spinning wheel

OR

1. Login to the site 
2. Add a Digital Assets module in a page
3. Add a folder named exactly the same as your uppermost parent folder name into your uppermost parent folder. For example, like the following directory structure:
-Root
--Folder_1
---Folder_1_1
----TextFile.txt
--**Root**
4. Use "Sync this folder & subfolders"
5. Try browsing the folders inside Folder_1

## Current result
The wheel keeps spinning and the folder content doesn't load.

## Expected result
The folder content should load and the wheel should stop spinning.

## Screenshots
https://www.loom.com/share/9bed5e20ae534a54ab1088fa05798ceb

## Affected version

* [x] 9.4.0 release candidate

## Affected browser

* [x] Chrome
* [x] Firefox
* [x] Safari
* [x] Internet Explorer
* [x] Edge

**Comment by valadas** [comment]
Merged
