### ISSUE TITLE
duplicated assembly exists in ck editor install package

### ISSUE THREAD

**Issue by zyhfish** [dnnsoftware/Dnn.Platform#2962]
## Description of bug
duplicated assembly exists in ck editor install package and it will cause install error in some environments with DFS enabled.

## Screenshots
![image](https://user-images.githubusercontent.com/3364448/63734089-79cebc80-c8ad-11e9-9d53-2884f3c80bc5.png)

## Error log
System.UnauthorizedAccessException: Access to the path '\\dnn.local\DNNDFS\dnnsftwre\Install\Temp\wezni42l\bin\DNNConnect.CKEditorProvider.dll' is denied.

## Additional context
Workaround: modify the install package and delete one of the duplicated files, then can install successfully.

## Affected version
* [ ] 10.0.0 nightly build
* [ ] 9.4.1 nightly build
* [ ] 9.4.0 release candidate
* [ ] 9.3.2 latest supported release

**Comment by WHairstonLOI** [comment]
@zyhfish Thanks for reporting/posting this! I just upgraded a client's site (hosted on a VPS at Managed.com, formerly PowerDNN) from v9.1.1 to v9.3.2 and encountered this. The upgrade wizard stopped at 64% and it took me a while to detect the same issue you reported. I just wasn't sure how to resolve it until I found this post.

Would like to suggest a new/corrected download (v9.3.3?) be posted immediately, or at least have the release notes updated to reflect this issue, as it was a showstopper for me.

**Comment by valadas** [comment]
As a quick fix to not delay 9.4.0 release, we are manually removing this duplicate file in the actual release zip for now. We are keeping this issue to do a better fix as part of 9.4.1

**Comment by david-poindexter** [comment]
@valadas should we move this issue to the 9.4.1 milestone?

**Comment by valadas** [comment]
I just isolated this to the CkEditor repository, moving this issue there and I am working on it.

**Comment by valadas** [comment]
Merged
