### ISSUE TITLE
Pages not loading in Page Editor

### ISSUE THREAD

**Issue by AlwaysVbNet** [dnnsoftware/Dnn.Platform#2963]
## Description of bug
Provide a clear and concise description of what the bug is.

## Steps to reproduce
List the steps to reproduce the behavior:
1. Login as admin
2. , go to Pages in Persona bar
3. See error

## Current result
Pages do not load

## Expected result
All pages load

## Screenshots
If applicable, provide screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/19957917/63757812-62023300-c8c3-11e9-8b86-68ac4f14a0f7.png)

## Affected version 
9.4.x

* [ ] 10.0.0 nightly build
* [x] 9.4.1 nightly build
* [x] 9.4.0 release candidate
* [ ] 9.3.2 latest supported release

## Affected browser

* [x] Chrome
* [x] Firefox
* [x] Safari
* [x] Internet Explorer
* [x] Edge

**Comment by AlwaysVbNet** [comment]
Hi @mitchelsellers @valadas it was an upgrade (for sure) from v. 09.03.02 (24)
I attached the log file.

[2019.08.28.txt](https://github.com/dnnsoftware/Dnn.Platform/files/3548696/2019.08.28.txt)

**Comment by AlwaysVbNet** [comment]
Both Azure and local windows installations. I upgraded both versions independently and for both the result was the same.

**Comment by valadas** [comment]
I had a similar strange issue, but kinda the opposite.
In Dnn 9.3.2 and before each persona bar module had it's own dll.
In Dnn 9.4.0 all the persona bar extensions server-side code was merged into the Dnn.PersonaBar.Extensions.dll

So during upgrade it should remove all the single persona bar modules dlls and replace by this single one. In my case, the removal was not working.

Can you check if your bin folder has Dnn.PersonaBar.Extensions.dll and not all the individual ones like this image:
![image](https://user-images.githubusercontent.com/6371568/64640470-0a41ec80-d3d8-11e9-8192-84c71b049f86.png)

Also , the Dnn.PersonaBar.Extensions.dll should be about 1Mb and not a few Kb...

Also if you can access the extensions module, look for the number of persona bar extensions listed and their version.

You should only see in there Dnn.PersonaBar.Extensions 3.0.0 in theory.

**Comment by valadas** [comment]
Closing this issue due to lack of response
