### ISSUE TITLE
Possible null reference exception in StandardFolderProvider.GetFileUrl method

### ISSUE THREAD

**Issue by zyhfish** [dnnsoftware/Dnn.Platform#2967]
https://github.com/dnnsoftware/Dnn.Platform/blob/development/DNN%20Platform/Library/Services/FileSystem/Providers/StandardFolderProvider.cs#L206
this code will call to Globals.LinkClick method:
https://github.com/dnnsoftware/Dnn.Platform/blob/development/DNN%20Platform/Library/Common/Globals.cs#L3359
here it doesn't check the portal settings value, if the code called in a schedule, it will throw out an null reference exception.

**Comment by valadas** [comment]
Merged
