### ISSUE TITLE
PetaPoco.Compiled from nuget breaks old code.

### ISSUE THREAD

**Issue by SCullman** [dnnsoftware/Dnn.Platform#2969]
## Description of bug

The Field `autoIncrement` within the PrimaryKey attribute is now pascalcase ( `AutoIncrement`)

## Steps to reproduce
Old code, which is compiled against the former library is now broken and has to be recompiled.

## Additional context
I am using PetaPoco instead of DAL2 a lot on internal projects. The benefit is that my assemblies and data logic can also be used from other clients, eg. a simple console.

As PetaPoco is not directly official API, I can accept that. However, you should be aware of this maybe accidential *breaking change*.
The change happend because the project uses now `PetaPoco.Compiled`, which is a different beast than the former library.

## Affected version

* [x ] 9.4.0 release candidate

**Comment by SCullman** [comment]
In addition, it is now impossible for me to target older DNN versions and 9.4.0 with one build.

**Comment by mitchelsellers** [comment]
The suggested model for working with the DNN API's, including DAL2, is to utilize the DNN References only, and not leverage any underlying third-party dependencies that DNN may rely upon, such as PetaPoco.

The use of a direct PetaPoco library is not supported or recommended and could cause breaking changes such as this.

**Comment by SCullman** [comment]
Copy that. This just should not happen by accident.

**Comment by ahoefling** [comment]
@SCullman I just created a new issue #2978 which may or may not be related to what you were doing.

**Comment by SCullman** [comment]
@ahoefling,  it is related, yes. 
After referencing the nuget package in my projects I got directly errors at compile time. A lot of good things happened to PetaPoco (Compiled.) I remember a few workarounds fighting issues with DAL2/Petapoco which would have been easier with an updated version, for example combined keys.
I copy Mitch that Petapoco is not part of the public API.  However I consider that move potential harmful and was expecting issues like yours.
