### ISSUE TITLE
Admin Logs not HTML encoded

### ISSUE THREAD

**Issue by bdukes** [dnnsoftware/Dnn.Platform#2972]
## Description of bug
When viewing the admin logs, the exception content is not HTML encoded.  For example, if an exception's stack trace includes a generic type or method (e.g. `List<string>`), then the generic type inside the brackets is interpreted as an HTML element instead of text.

## Steps to reproduce
List the steps to reproduce the behavior:
1. Install 
[Engage.GenericsError_1.0.0_Install.zip](https://github.com/dnnsoftware/Dnn.Platform/files/3570013/Engage.GenericsError_1.0.0_Install.zip)
2. Add module to page
3. View _Admin Logs_

## Current result
A _Module Load Exception_ is present in the logs with the message
>error CS1061: '`List`' does not contain a definition for '`DoSomethingFun`' and no accessible extension method '`DoSomethingFun`' accepting a first argument of type '`List`' could be found (are you missing a using directive or an assembly reference?)

## Expected result
A _Module Load Exception_ is present in the logs with the message
>error CS1061: '`List<char>`' does not contain a definition for '`DoSomethingFun`' and no accessible extension method '`DoSomethingFun`' accepting a first argument of type '`List<char>`' could be found (are you missing a using directive or an assembly reference?)

## Screenshots
![Log message with missing generic types](https://user-images.githubusercontent.com/59507/64182195-6d0e1380-ce2d-11e9-8be0-9214997b0541.png)

## Affected version

* [ ] 10.0.0 nightly build
* [ ] 9.4.1 nightly build
* [x] 9.4.0 release candidate
* [x] 9.3.2 latest supported release

**Comment by valadas** [comment]
Merged
