### ISSUE TITLE
Last Modified Column Date Are All 01/01/0001 00:00

### ISSUE THREAD

**Issue by yukirivero** [dnnsoftware/Dnn.Platform#2974]
Hi,

When I add a folder in the Digital Assets Module, the "Last Modified" column shows the right date and time but when I upload files, it shows "01/01/0001 00:00" as the date.

What causes this?

I attached a screenshot of the problem.

Thanks,
Ron
![date](https://user-images.githubusercontent.com/7507146/64199876-e6eddd80-cebd-11e9-8fe9-e34bbc5c3eda.PNG)

**Comment by valadas** [comment]
I cannot reproduce and there was no Dnn version provided. If this is still the case on current version please open a new issue with more details. Thanks.
