### ISSUE TITLE
Password Reset allows account verification

### ISSUE THREAD

**Issue by thabaum** [dnnsoftware/Dnn.Platform#2975]
## Description of problem
No link was sent to my email

![image](https://user-images.githubusercontent.com/13577556/64212471-4ddbaa00-ce5e-11e9-938b-233d03ae2256.png)

If you try to reset your password you get the following email:  

You have requested a Password Reset Token from DNN Open Source Community, but Your account is pending approval.
Password can be reset after account is approved.
Sincerely, DNN Open Source Community
*Note: If you did not request a Password Reset Token, please tell us immediately in the forums: https://dnncommunity.org/forums/aff/13
**no way to post in forums...**

## Description of solution
Resend verification email link in the message

Or by resetting your password the email sent to you can confirm your address just the same, if they click on the password reset link in the email it should allow them to get verified.

I am unable to post in forums, talk to admins, I have no clue what to do but post here on the bug report.  I am not sure why but I get all other emails but the verification email.

dnncommunity.org is setup I can see people registering and logging in... I get other emails from the website about me updating my profile and to reset my password, just randomly some users wont get the verification email I believe.

## Description of alternatives considered
Provide a clear and concise description of any alternative solutions or features you have considered.

## Screenshots
If applicable, provide screenshots to help explain your problem and/or feature.

## Additional context
Add any other context about the feature that may be helpful with implementation.

## Affected browser

* [ ] Chrome
* [ ] Firefox
* [ ] Safari
* [ ] Internet Explorer
* [ ] Edge

**Comment by mitchelsellers** [comment]
Cody - shoot me an email and I'll get you in touch with the right people.

msellers@iowacomputergurus.com
