### ISSUE TITLE
New Feature Request::  Language Edit Mode

### ISSUE THREAD

**Issue by thabaum** [dnnsoftware/Dnn.Platform#2976]
## Description of problem
Finding the right place in language packs to edit the proper fields to change language settings.  Trying to find all the "register" or "login" places takes digging into every file to find it and I still can't get "register" to change to "join".  I used to be able to but now there is an issue.

## Description of solution
Language Edit Mode so when you click on the pencil in peronona bar you have an option to enter laguange edit mode and edit any language words set and it highlights anything in a language pack allowing you to click on it and edit it while on the page with the issue rather than trying to dig it up in some hidden location hard to find.

**Comment by valadas** [comment]
This would be nice but would also very complex to implement in all module pipelines, I am not even sure if it would be possible to implement.

Anybody has ideas on this and anybody is interesting in implementing this?

**Comment by valadas** [comment]
I will close this issue since it would be a massive undertaking to build this into all the module pipelines. #3235 is a more manageable task that solves the same root problem as this issue.

**Comment by sleupold** [comment]
this would be difficult to implement, because resources may come from at least 6 different files (system, host and portal for local file and shared resources) and it would be difficult to auto-select the proper one.
