### ISSUE TITLE
Can dnn experts confirm, this is an bug or an expected behavior and explain why?

### ISSUE THREAD

**Issue by johnngoit** [dnnsoftware/Dnn.Platform#2977]
## Description of bug
our team may found a defect when create a folder in File Manager with a DNN Custom Folder Provider.  It will  create 2 folders: 1 in the custom folder and 1 in the root or default folder.  If this is an expected behavior, please let us know why?

## Steps to reproduce
List the steps to reproduce the behavior
1. Select a custom folder provider Azure or any.
2. Build project DotNetNuke.Library in the DNN_Platform solution.
3. Go to the code: DNN Platform\Library\Services\FileSystem\FolderManager.cs
4. Set debugger on line 497 - create the custom folder --- FolderProvider.Instance(folderMapping.FolderProviderType).AddFolder(folderPath, folderMapping, mappedPath);
5. Set debugger on line 506 - create the root folder ---- CreateFolderInFileSystem(PathUtils.Instance.GetPhysicalPath(folderMapping.PortalID, folderPath));
6. In the File Manager, create a new folder.  You will be able to verify the create folder invoke twice and two folders are created.

## Current result
Will create 2 folders: 1 in the custom folder provider and 1 in the default folder(c:/..../instanceweb//Portals/_default or c:/..../instanceweb/Portals/0)

## Expected result
Should only create 1 folder in the custom folder provider only.

## Screenshots
create folder: j1
![image](https://user-images.githubusercontent.com/13056272/64295265-bb9ed900-cf25-11e9-9260-4940af3f5524.png)

## Additional context
If this is an expect behavior, then please let our team know why?

## Affected version
7 and up

## Affected browser
All

**Comment by valadas** [comment]
@dnnsoftware/tag any input on this. I have no experience with folder providers?

**Comment by sleupold** [comment]
the default folder provider entry might act as a stub, preventing duplicate file paths. Does this makes sense to you?

**Comment by mitchelsellers** [comment]
@sleupold Is correct on this one, it is by design with the current implementation.
