### ISSUE TITLE
Journal Comment Scroll Bar Display Issue

### ISSUE THREAD

**Issue by thabaum** [dnnsoftware/Dnn.Platform#2981]
## Description of bug
Text in the Journal Module disp
layed is not all together as a s
ingle word.

## Steps to reproduce
List the steps to reproduce the behavior:
1. Go to Journal Module
2. Make a post
3. Comment that post 

## Current result
The comment area is not as wide as the journal.

## Screenshots
If applicable, provide screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/13577556/64478641-db214600-d15f-11e9-8971-f4cb06aa0a58.png)

**Comment by thabaum** [comment]
![image](https://user-images.githubusercontent.com/13577556/69025479-0902e200-097c-11ea-8ab4-7a80ea3c15a3.png)

This tells me it may be related to the content being created in the links possibly.  The field says width 100%, it is being stopped from doing it in that area.

**Comment by thabaum** [comment]
![image](https://user-images.githubusercontent.com/13577556/69025690-e2917680-097c-11ea-9f97-65cb3063f495.png)
I also see this in the inspector debugger, pauses on this exception

`Paused on exception
SyntaxError: '.actionMenu:visible' is not a valid selector`

**Comment by valadas** [comment]
> '.actionMenu:visible'

The error message is correct, the :visible part is not a valid selector, it is a state, would have to dig higher to find what brings this string into the selector but that is wrong yeah.
