### ISSUE TITLE
Inconsistent language edit

### ISSUE THREAD

**Issue by EPTamminga** [dnnsoftware/Dnn.Platform#2983]
## Description of bug
The editing of language elements is inconsistent. Editing a text element is not saved until you explicitly press the save button

## Steps to reproduce
List the steps to reproduce the behaviour:
1. Go to Host/Site Settings/Language/Edit text
2. Select a source file (.resx file)
3. The individual text elements can be edited by pressing the Pencil at the right side of the text
4. After editing the text in a pop-up text box, you click Save at the bottom of the popup

## Current result
The new text is NOT saved

Only if you scroll back to the top and press Save Translations, the changes are saved.
This is not expected, especially if you edit text elements in a large .resx file and are at the bottom of the list. 

## Expected result
Save a text should save a text?

## Screenshots
![image](https://user-images.githubusercontent.com/5859855/64518233-16537e80-d2f2-11e9-9956-bd88b4e41269.png)

## Affected version

* [X] 10.0.0 nightly build
* [X] 9.4.1 nightly build
* [X] 9.4.0 release candidate
* [X] 9.3.2 latest supported release

## Affected browser

* [X] Chrome
* [X] Firefox
* [X] Safari
* [X] Internet Explorer
* [X] Edge

**Comment by sleupold** [comment]
still an issue
