### ISSUE TITLE
Dropdownlist folder type & Mode not working in Module Settings

### ISSUE THREAD

**Issue by kurtwilbies** [dnnsoftware/Dnn.Platform#2984]
## Description of bug
Default folder type & Mode in the Basic Settings section cannot be clicked (ddl not populating) and you cannot choose another folder type or mode.

## Steps to reproduce
List the steps to reproduce the behavior:
1. Add a DAM module to a new page
2. Go to module 'Setting' 
3. Click on the ddl of 'Default folder type'
4. Nothing ...

## Current result
Choose only default type (Standard) and mode (Normal)

## Expected result
Choose a secure/database type ...

* [ ] 10.0.0 nightly build
* [ ] 9.4.1 nightly build
* [x] 9.4.0 release candidate
* [ ] 9.3.2 latest supported release

## Affected browser
* [x] Chrome
* [x] Firefox
* [ ] Safari
* [ ] Internet Explorer
* [x] Edge

**Comment by valadas** [comment]
This should now be fixed in 9.4.1 by another issue relating to selectize.js. The 9.4.1 RC is coming up very soon, if you still have an issue after 9.4.1 please comment or open a new issue.
