### ISSUE TITLE
Failed Azure backups of Web Service

### ISSUE THREAD

**Issue by KenTombs** [dnnsoftware/Dnn.Platform#2989]
This is more of a warning/research notice, in that there is a perfect combination of events to wipe out a web Service DNN application on Azure (not a VM).  The sequence of events is:

1. You use the Azure installer for DNN (9.1) fine onto Azure and then upgrade to 9.3.2 with the upgrade zip file.

2. Then start Azure automated backups, and all looks good. 

3. Automated backups show  'partially complete'.

4. Then a single backup shows 'successful'.

5. You then raise a support ticket on why partial backups, which takes a week to escalate to capable people.

6. Meanwhile, auto backups keep making partial (and now known unusable backups).

7. While investigating these backups you open the backup panel/blade, starting a restore automatically to the last known 'only' good backup file, in this case an empty original DNN install.

8. Support helped to use the separate 'snapshots feature which run all the time but are not usable by entry level subscriptions. Restoring SnapShots to fresh App slots of the production site, similarly fail.  I had to pay for that subscription upgrade!

9. In practice nothing works to restore from a snapshot or a backup.  Its back to square one.

10. MS has no solution to this chain of events other than a fresh installation.

The issue is the Azure backup feature does not flag the log files, only MS has that ability. 

The reason simply, DNN locks some files to prevent conflicts.  If Azure backups up and sees any locked files, it cannot complete and you have an unusable backup file. 

However, the snapshot feature also did  not work, it seemed stuck to cloning only the original now empty site.  Or possibly its incrementing against the only viable backup file (?).

The only clear route is to start again with three weeks of extension loading and content.

## Steps to reproduce
List the steps to reproduce the behavior:

## Current result
Explain what the current result is.

## Expected result
Provide a clear and concise description of what you expected to happen.

## Screenshots
If applicable, provide screenshots to help explain your problem.

## Error log
Paste the error log that is related to this issue.

## Additional context
Add any other context about the bug that may be helpful for resolution.

## Affected version

* [ ] 10.0.0 nightly build
* [ ] 9.4.1 nightly build
* [ ] 9.4.0 latest supported release

## Affected browser

* [ ] Chrome
* [ ] Firefox
* [ ] Safari
* [ ] Internet Explorer
* [ ] Edge

**Comment by KenTombs** [comment]
Thanks for the blog.  Does this mean that a failed backup on Azure that tried o included locked files is unusable?
Can what looks by size to be a complete backup, though is shown as partial, be restored?  According to Azure, not so?

**Comment by mitchelsellers** [comment]
Typically the backup is still totally fine and could be restore without a question.
