### ISSUE TITLE
Upgrade to DNN 9.4 - Could not load file or assembly 'netstandard, Version=2.0.0.0

### ISSUE THREAD

**Issue by moorecreative** [dnnsoftware/Dnn.Platform#2990]
## Description of bug
While upgrading a site from DNN 9.1 to 9.4, encountered a .net error message 
"Could not load file or assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified."

## Details
Understanding that DNN 9.4 has a requirements change for ASP.NET 4.7.2, I checked with the host to make sure that 4.7.2 was installed/available. Confirmed that ASP.NET 4.5 was in place, so they updated and restarted the server. However the error message remains after.

The Error message, or asp.net error is encountered in the initial upgrade actions on the /Install/Install.aspx?mode=upgrade step

## Affected version

[X ] 9.4.0 latest supported release

**Comment by micahsdad1402** [comment]
I also had this.
Upgrade to .Net 4.7.2 resolved. it.

However, it should be really easy to detect this and give a much more elegant message, ie you are trying to upgrade and you need to install .Net 4.7.2 before proceeding.... just saying.

**Comment by valadas** [comment]
It would be a nice enhancement to do some basic checks and warn during the upgrade wizard, keeping this issue for later...

**Comment by valadas** [comment]
Merged

**Comment by Tychodewaard** [comment]
I just upgraded from 9.3.2 to 9.4.1 and got error as in attachment.
- Unzip the file
- Copy files to server
- go to upgrade url and...boom...

![image](https://user-images.githubusercontent.com/9091997/66845677-bf843900-ef70-11e9-94df-7760e9e3dfd0.png)

**Comment by bdukes** [comment]
What URL did you go to @Tychodewaard?  `/Install/UpgradeWizard.aspx` or `/Install/Install.aspx?mode=upgrade` or something else?

**Comment by Tychodewaard** [comment]
Yup, that’s the one

Outlook voor iOS<https://aka.ms/o0ukef> downloaden
________________________________
Van: Brian Dukes <notifications@github.com>
Verzonden: Tuesday, October 15, 2019 5:37:17 PM
Aan: dnnsoftware/Dnn.Platform <Dnn.Platform@noreply.github.com>
CC: Tycho de Waard <info@tjeps.com>; Mention <mention@noreply.github.com>
Onderwerp: Re: [dnnsoftware/Dnn.Platform] Upgrade to DNN 9.4 - Could not load file or assembly 'netstandard, Version=2.0.0.0 (#2990)


What URL did you go to @Tychodewaard<https://github.com/Tychodewaard>? /Install/UpgradeWizard.aspx or /Install/Install.aspx?mode=upgrade or something else?

**Comment by bdukes** [comment]
It's actually the two ;-)

Did you use the first URL, `/Install/UpgradeWizard.aspx`?
Or did you use the second URL, `/Install/Install.aspx?mode=upgrade`?

Thanks!

**Comment by Tychodewaard** [comment]
Sorry, the ?mode=upgrade as adviced in the wiki

Outlook voor iOS<https://aka.ms/o0ukef> downloaden
________________________________
Van: Brian Dukes <notifications@github.com>
Verzonden: Tuesday, October 15, 2019 5:54:29 PM
Aan: dnnsoftware/Dnn.Platform <Dnn.Platform@noreply.github.com>
CC: Tycho de Waard <info@tjeps.com>; Mention <mention@noreply.github.com>
Onderwerp: Re: [dnnsoftware/Dnn.Platform] Upgrade to DNN 9.4 - Could not load file or assembly 'netstandard, Version=2.0.0.0 (#2990)


It's actually the two ;-)

Did you use the first URL, /Install/UpgradeWizard.aspx?
Or did you use the second URL, /Install/Install.aspx?mode=upgrade?

Thanks!

**Comment by valadas** [comment]
And did you get latest windows updates, you can check in the registery to make sure you have .Net Framework 4.7.2 or more, here is an article describing how to check it https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/how-to-determine-which-versions-are-installed

**Comment by Tychodewaard** [comment]
I’m adding 4.7.2 tonight. The comment was meant as feedback that I did not get a warning, it immediately threw the error

Outlook voor iOS<https://aka.ms/o0ukef> downloaden
________________________________
Van: Daniel Valadas <notifications@github.com>
Verzonden: Tuesday, October 15, 2019 7:52:39 PM
Aan: dnnsoftware/Dnn.Platform <Dnn.Platform@noreply.github.com>
CC: Tycho de Waard <info@tjeps.com>; Mention <mention@noreply.github.com>
Onderwerp: Re: [dnnsoftware/Dnn.Platform] Upgrade to DNN 9.4 - Could not load file or assembly 'netstandard, Version=2.0.0.0 (#2990)


And did you get latest windows updates, you can check in the registery to make sure you have .Net Framework 4.7.2 or more, here is an article describing how to check it https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/how-to-determine-which-versions-are-installed

**Comment by valadas** [comment]
#3025 was merged into 9.4.1 to put a warning about it in the installer before performing the upgrade. From my understanding of past error reports, users have reported that the upgrade went fine and had this error after the upgrade was done.

Sooo, if I understand correctly you would have got this warning only using the wizard, using the url you used, there would not be a wizard to actually show that message, right @bdukes ?

**Comment by bdukes** [comment]
I think there must have been a change between when we initially added this into 9.4.1 and the 9.4.1 release, because I'm now immediately getting the _Could not load file or assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified._ error upon unzipping the upgrade package (even when directly navigating to `/Install/UpgradeWizard.aspx`).  So, it looks like our core pipeline code is now using .NET 4.7.2, so we can't load the error message saying its required.

The stack trace is coming from [`DotNetNuke.Web.Startup.Configure`](https://github.com/dnnsoftware/Dnn.Platform/blob/685071420b39283763dd3b0c008cc685f8c6588d/DNN%20Platform/DotNetNuke.Web/Startup.cs#L21-L26), called by [`DotNetNukeHttpApplication.Application_Start`](https://github.com/dnnsoftware/Dnn.Platform/blob/685071420b39283763dd3b0c008cc685f8c6588d/DNN%20Platform/DotNetNuke.Web/Common/DotNetNukeHttpApplication.cs#L79).  It's possible that we could avoid some of the initialization for upgrade and/or install, but that might have unpredictable downstream effects.

**Comment by valadas** [comment]
I confirm this
