### ISSUE TITLE
Vocabularies Disappearing

### ISSUE THREAD

**Issue by BrianBakewell** [dnnsoftware/Dnn.Platform#2991]
## Description of bug
After upgrading to DNN 9.2.2 when we edit a vocabulary and change the name of the vocabulary slightly, depending on how the name was changed the vocabulary will disappear out of the tree. 

Looking at the database and I can see the record has changed with the same Parent Term but the TermLeft and TermRight fields are no longer within the TermLeft and TermRight fields of the Parent Term which is used for the display.

## Steps to reproduce
List the steps to reproduce the behavior:
1. Go to Vocabularies
2. Click on a collection that uses a Tree structure
3. Under Terms go to a Term a few levels down the tree structure and click on the pencil (edit) symbol
4. Change the name slightly (for example changing Terms to Term) and click on Update
5. Close the Browser
6. Open the Site after closing the browser (Refreshes the page)
7. Go back in Vocabularies and into the collect.
8. The Term will have disapeared from the tree.

## Current result
The Term is no longer showing in the tree structure

## Expected result
The Term should still be showing within the Parent Term

## Screenshots
N/A

## Error log
N/A

## Additional context
If I get the procedure UpdateHeirarchicalTerm to run twice to update the Term, first by adding a few zzzzzz to the begining of the name which affectivly puts it to the end of the terms in the tree and then running again with the correct name this does seem to fix the issue, but is a bit messy and not a correct solution.

## Affected version

Only know about this version
* 9.2.2 

## Affected browser

* [ x ] Chrome
* [ x ] Firefox
* [ ] Safari (we haven't tried Safari)
* [ x ] Internet Explorer
* [ x ] Edge

**Comment by sleupold** [comment]
Thank you.

**Comment by valadas** [comment]
I was able to reproduce in 9.4.0

**Comment by valadas** [comment]
I can no longer reproduce in 9.6.2, if this is still reproducible, please comment and I will reopen
