### ISSUE TITLE
DNN 9.4 upgrade => View website button links to the upgrade aspx

### ISSUE THREAD

**Issue by eXistenZe** [dnnsoftware/Dnn.Platform#2992]
## Description of bug
DNN 9.4 upgrade => View website button links to the upgrade aspx

## Steps to reproduce
1. Upgrade to 9.4
2. After finishing there is a button "View website". Click it.
3. The link goes to the upgrade aspx (https://investigar.pt/Install/UpgradeWizard.aspx?complete)
4. A server error is shown:
```
Server Error in '/' Application.
The resource cannot be found.
Description: HTTP 404. The resource you are looking for (or one of its dependencies) could have been removed, had its name changed, or is temporarily unavailable.  Please review the following URL and make sure that it is spelled correctly.

Requested URL: /Install/UpgradeWizard.aspx

Version Information: Microsoft .NET Framework Version:4.0.30319; ASP.NET Version:4.8.3928.0 
```

## Expected result
View website links to the root page /

**Comment by sleupold** [comment]
Which version did you upgrade from?
which 3rd party extensions did you install before and did you make sure to user latest version?

**Comment by eXistenZe** [comment]
From 9.3.2.
Updated 2sxc to 10.05 before.
Besides that I only use porto theme.

**Comment by thabaum** [comment]
Seems like there has been an issue with the "View Website" button after upgrades.

It works I believe for standard installations but upgrades has been an issue I may have made an issue report similar to this in the past a while back...

**Comment by thabaum** [comment]
I have upgraded a site with "Porto" installed  and the button pretty much did nothing to visit the website after the installation successfully upgraded 9.3.2 to 9.4.0

I will test another website out without Porto installed soon.

**Comment by thabaum** [comment]
I just completed my upgrade with a test site without Porto theme installed.  It worked ok.

Put a support ticket to get it resolved with the theme developer.

I will do the same.

**Comment by valadas** [comment]
Closing this since it appears to be theme related.
