### ISSUE TITLE
How can I install the project?

### ISSUE THREAD

**Issue by Shuisen** [dnnsoftware/Dnn.Platform#2995]
## Description of bug
Can not find the stored procedure 'dbo.AuthCookies_Update' When I install it

## Steps to reproduce
List the steps to reproduce the behavior:
1. Go to clone this project in visual studio.
2. Create a datebase on sql server.
3. Click the run in visual studio.
4. Fill the message.
5.See the Error!

**Comment by sleupold** [comment]
To install DNN you don't need VS (a blank database is useful though). 
Just unblock the install package (downloaded from releases) and unzip the files contained to your IIS website folder.  Run the application and follow the install wizard.

**Comment by david-poindexter** [comment]
@Shuisen - you may also find nvQuickSite (https://www.nvquicksite.com) helpful for installation of DNN.

**Comment by mitchelsellers** [comment]
If you want to build the project this is listed: https://github.com/dnnsoftware/Dnn.Platform/blob/development/.github/BUILD.md

If you are looking to install locally @david-poindexter has an option there is also the DNN Community Site.
