### ISSUE TITLE
Dependency Injection in Razor 3 modules breaks the Razor 3 menu system

### ISSUE THREAD

**Issue by david-poindexter** [dnnsoftware/Dnn.Platform#2997]
## Description of bug
Using the base theme in [nvQuickTheme](https://www.nvquicktheme.com), which uses the Razor 3 menu system, DNN will not render the menu.  Using the text/token version still works as expected.

## Steps to reproduce
1. Install DNN 09.04.00
2. Install nvQuickTheme 2.1.0
3. Apply theme
4. Menu does not render

## Current result
Menu does not render.

## Expected result
Menu should render.

## Screenshots
![ScreenCapture_ 2019-09-16 06 28 PM _2489](https://user-images.githubusercontent.com/4568451/64997837-e1c26280-d8af-11e9-9161-110d4e19c059.jpg)

## Error log
![image (7)](https://user-images.githubusercontent.com/4568451/64997567-213c7f00-d8af-11e9-96f8-6146dbdcfe6e.png)

## Additional context
@ahoefling will provide additional details when submitting a PR to resolve this issue.

## Affected version
* [ ] 10.0.0 nightly build
* [ ] 9.4.1 nightly build
* [x] 9.4.0 latest supported release

## Affected browser
* [x] Chrome
* [x] Firefox
* [x] Safari
* [x] Internet Explorer
* [x] Edge

**Comment by valadas** [comment]
Merged
