### ISSUE TITLE
dnn.FileUpload.js referenced to deprecated jquery methods

### ISSUE THREAD

**Issue by zyhfish** [dnnsoftware/Dnn.Platform#2999]
https://github.com/dnnsoftware/Dnn.Platform/blob/development/Website/Resources/Shared/components/FileUpload/dnn.FileUpload.js#L349 referenced to $.browser which has been deprecated in the latest jquery version, so error will thrown when code reach to this condition.

**Comment by valadas** [comment]
Merged
