### ISSUE TITLE
Calendar on Module Start Date & End Date - Error

### ISSUE THREAD

**Issue by kaneluong** [dnnsoftware/Dnn.Platform#3002]
## Description of bug
After a clean install of 9.4, when I tried to edit a module start date and end date. The calendar popup does not show. Instead, there are multiple errors that showed up on the console of the developer tool.

## Steps to reproduce
List the steps to reproduce the behavior:
1. Click on Start Date or End Date Field when editing a module.
2. Open up developer tools inspector.

## Current result
Nothing happens, but errors on console.

Error: 
- Selectize: Dependency MicroPlugin is missing
- Make sure you either: (1) are using the "standalone" version of Selectize, or (2) require MicroPlugin before you load Selectize.
- Uncaught TypeError: w.define is not a function
- Uncaught ReferenceError: Selectize is not defined
- Uncaught TypeError: $(...).dnnComboBox is not a function

## Affected version
* [ ] 10.0.0 nightly build
* [ ] 9.4.1 nightly build
* [x] 9.4.0 latest supported release

## Affected browser
* [x] Chrome
* [ ] Firefox
* [ ] Safari
* [ ] Internet Explorer
* [X] Edge

**Comment by bdukes** [comment]
Ugh.  I updated Selectize from 0.12.4 to 0.12.6 (01f890ab2c746ad6e2ae27dfcffd26be5e4858dc), but apparently didn't use the standalone version that was used previously.  It's easy enough to fix for 9.4.1, but it creates an upgrade issue (the updated package won't get installed during a 9.4.0 to 9.4.1 upgrade, because it's the same version number).  @mitchelsellers, @donker, @valadas, do any of y'all know of an easy way to force a same-version package install when upgrading the Platform?

**Comment by bdukes** [comment]
By the way, thanks @kaneluong for the detailed bug report, it pointed me right to the underlying issue.

**Comment by kaneluong** [comment]
No Worries. @bdukes . Is it something that users should hold off on installing/upgrading 9.4.0 until 9.4.1 gets released? or is there a easy fix for a fresh install of 9.4.0 on this bug?

**Comment by bdukes** [comment]
I would probably recommend waiting for 9.4.1 at this point.  If you're already upgraded, the workaround is to fix the Selectize script.  Save https://raw.githubusercontent.com/dnnsoftware/Dnn.Platform/da491cb606d62460f50bfcc53a6674fd50ca08b7/DNN%20Platform/JavaScript%20Libraries/Selectize/selectize.min.js to `Resources\Libraries\Selectize\00_12_06\selectize.min.js`

**Comment by valadas** [comment]
Closing issue since the PR got merged, 9.4.1 RC1 will be out very soon if you want to test and 9.4.1 official release very shortly after that
