### ISSUE TITLE
Social Groups created through the Persona Bar do not appear in the Social Groups

### ISSUE THREAD

**Issue by sergeydryomin** [dnnsoftware/Dnn.Platform#3007]
## Description of bug
Social Groups created through the Persona Bar do not appear in the Social Groups

## Steps to reproduce
1. I'm logged in as an administrator.
2. I go to Manage -> Roles, Create New Role.
3. I've added a name under Role Name.
4. Under Role Group, I've selected "Global Role".
5. Under Security Mode, I've tried to use "Social Group" and I've also tried using "Both" (Neither seems to work).
6. Under Status, I've selected "Approved".
7. I've turned "On" the Public setting.
8. Click Save

## Current result
The Role is created in the Manage Roles IU interface, but when I go to my Community Group Directory this Role does not show up at all. I believe this is because in the process for the Manage Roles UI, the Role settings are not generated.

## Expected result
Provide a clear and concise description of what you expected to happen.

## Screenshots
https://www.screencast.com/t/rIItYLjtJ

## Additional context
To solve it, need to automatically add these steps:
1) Create the role with Security Mode = Social Group, Status = Approved, Public
2) Use Persona Bar > Settings > SQL Console to retrieve the RoleID:
select RoleID from Roles where RoleName = '<put the role name here>'
(or get it from created role)
3) Open Persona Bar > Content > Assets, click the site name, click Groups and then Add Folder. Set the folder name equal to RoleID.(Create Groups folder if it doesn't exists)
4) Add creator as owner to the Social Group(role)

All these steps are already implemented - adding these to create PR

## Affected version

* [X] 10.0.0 nightly build
* [X] 9.4.1 nightly build
* [X] 9.4.0 latest supported release

## Affected browser

* [X] Chrome
* [X] Firefox
* [X] Safari
* [X] Internet Explorer
* [X] Edge

**Comment by valadas** [comment]
Merged
