### ISSUE TITLE
Verify SMTP uses STARTTLS for making connections to mail servers that are TLS enabled.

### ISSUE THREAD

**Issue by thabaum** [dnnsoftware/Dnn.Platform#3008]
## Description of bug
A way to check and be sure that even if SSL is disabled, STARTTLS is still pushed to the SMTP mail server to start a TLS connection.  Mail servers allow unsecured connections to then become secured using the STARTTLS command.

## Steps to reproduce
According to the article by Microsoft it 

> The SmtpClient class only supports the SMTP Service Extension for Secure SMTP over Transport  Layer Security as defined in RFC 3207. In this mode, the SMTP session begins on an unencrypted channel, then a STARTTLS command is issued by the client to the server to switch to secure communication using SSL. See RFC 3207 published by the Internet Engineering Task Force (IETF) for more information. 

## Current result
I am unable to verify STARTTLS is being used when SSL is disabled.  I wish to verify a TLS connection is being created.
## Expected result
TLS enabled mail smtp connections sending emails to members.

## Additional context
https://docs.microsoft.com/en-us/dotnet/api/system.net.mail.smtpclient.enablessl?redirectedfrom=MSDN&view=netframework-4.8#System_Net_Mail_SmtpClient_EnableSsl

*Possibly*use a command like:  
sw.WriteLine("STARTTLS ");
in the smtpClient.Send method prior to sending mail even if smtpEnableSSL is false to start TLS communication with SMTP server.

smtpClient.EnableSsl   = smtpEnableSSL;

https://www.emailarchitect.net/easendmail/ex/c/2.aspx
This link shows some interesting information about TLS SSL and .NET along with example codes maybe something can help for reference.

Maybe TLS is working properly in DNN? I just wish to verify things are up to date looking to the future.   Seems like 587 is the port to be used for TLS.  This should be considered default port today I believe.

**Comment by thabaum** [comment]
> 			else if (m_authentication == SmtpAuthentication.Ntlm)
			{
				// Perform integrated authentication (NTLM)
				smtpClient.Credentials = System.Net.CredentialCache.DefaultNetworkCredentials;
			}
This does not look right.  This looks like what you use for authentication before sending which is missing.  I need to authenticate before sending this is an issue I have been fighting.

https://docs.microsoft.com/en-us/dotnet/api/system.net.mail.smtpclient.servicepoint?view=netframework-4.8

If I am reading this right 
![image](https://user-images.githubusercontent.com/13577556/66262976-b391bd80-e79f-11e9-8d52-35a56d551554.png)

I am also trying to look at Log4Net which is used in .NET which has an issue with TLS logged but was suppose to have been patched.

Pretty much SSL should be called TLS as it is the standard.  Port 587 TLS is best practice, 465 is outdated SSL along with 25 if I am understanding things right.

My server only allows TLS 1.3 and nothing lower.  

https://issues.apache.org/jira/browse/LOG4NET-116

This is another good reference for the topic.

**Comment by mitchelsellers** [comment]
For the sake of clarity, I am going to close this issue in favor of continuing discussion on #3120 which is more inline with the request.
