### ISSUE TITLE
SEO Setting "Redirect Mixed Case URLs" should not lowercase QueryString

### ISSUE THREAD

**Issue by davidjrh** [dnnsoftware/Dnn.Platform#3011]
## Description of Problem
When enabling the SEO Setting "Redirect Mixed Case URLs" on a portal ('AUM_RedirectMixedCase' on the PortalSettings table), the logic is taking into account the QueryString. If a query string parameter is UpperCase, the redirection is done. This is a problem when "case sensitive parameters", such as Auth Exchange tokens are used on the query string, since Auth providers such as Azure AD are case sensitive (check https://github.com/davidjrh/dnn.azureadprovider/issues/22 for more background)

## Proposed Solution Option 1
* When checking if a URL is mixed case, only check the host and path, but not the query string. 
* Never change the query string
* Check the case when the DNN URL Friendly provider change parameters into "folders" in the URL.

## Alternatives Researched
None. 

## Affected version

* [X] 10.0.0 nightly build
* [X] 9.4.1 nightly build
* [X] 9.4.0 latest supported release
* [X] 9.* latest supported release

**Comment by david-poindexter** [comment]
I agree and have run into issues with this in the past.

**Comment by thabaum** [comment]
makes sense would fix the dnn token issue for registering users when this setting is set as well.

**Comment by bdukes** [comment]
The "officially supported" workaround for this scenario is to use the _Prevent Lowercase URL Regular Expression_ setting (_SEO_ Persona Bar extension, _URL Management_ tab, _Expressions_ sub-tab), but that's certainly tricky to do from an extension, rather than as an admin.

I'm not opposed to the change, but it might confuse people who expect lowercase URLs and don't think it's working in their scenario.  We can probably adjust the help text on the _Redirect Mixed Case URLs_ setting to help clarify.

**Comment by sleupold** [comment]
this seems to be an important issue, especially for MVC modules

**Comment by sleupold** [comment]
is this still an issue?

**Comment by davidjrh** [comment]
Yes it is still an issue. I have just got crazy trying to find again the problem on the Azure AD module, and the problem was the setting "AUM_ForceLowerCase" redirecting to the lowercase page. I needed to disable

**Comment by davidjrh** [comment]
How can I reopen this?

**Comment by Timo-Breumelhof** [comment]
I also ran into issues with this today.. :-(
Would be nice if this could be fixed / changed.

**Comment by Timo-Breumelhof** [comment]
BTW, what if we would add an exception rule for Azure by default as that seems to be a common use case.
(not for the login page but for the QS parameter used)
