### ISSUE TITLE
Menu disappears for Contra Theme - DNN 9.4.0

### ISSUE THREAD

**Issue by skarpik** [dnnsoftware/Dnn.Platform#3012]
## Description of bug
DNN Contra (v1.0.3) theme works perfectly for DNN 9.3.2. For DNN 9.4.0, the menu bar is not visible.

## Steps to reproduce
List the steps to reproduce the behavior:
1. Created DNN 9.3.2 "out of the box" website.
2. Installed DNN Contra theme (v1.0.3) and created a new page with this theme. All OK.
3. Created DNN 9.4.0 "out of the box" website.
4 Installed DNN Contra theme (v1.0.3) and created a new page with this theme.  Cannot see menu bar.

## Current result
Since the DNN Contra theme works perfectly with DNN v9.3.2, it appears that there is a breaking change in DNN v9.4.0. Alternatively, DNN Contra uses an unsupported feature of DNN.

## Expected result
Since the DNN Contra theme worked for DNN v9.3.2, it shoud work for DNN v9.4.0.

## Screenshots
DNN v9.3.2 Website with DNN Contra theme
![DNN v9 3 2 - Contra Theme](https://user-images.githubusercontent.com/3846223/65393689-f12f2900-dd51-11e9-8cff-a0f6d09acb87.jpg)

DNN v9.4.0 Website with DNN Contra theme (no menu bar)
![DNN v9 4 0 - Contra Theme](https://user-images.githubusercontent.com/3846223/65393690-f12f2900-dd51-11e9-83ad-814cb4d39556.jpg)

## Error log
n/a

## Affected version

* [ ] 10.0.0 nightly build
* [ ] 9.4.1 nightly build
* [x] 9.4.0 latest supported release

## Affected browser

* [x] Chrome
* [x] Firefox
* [ ] Safari
* [ ] Internet Explorer
* [x] Edge

**Comment by david-poindexter** [comment]
This theme uses Razor for the DDR Menu.  This is a known bug in DNN 09.04.00 and has been resolved by #2998 - therefore, closing this issue.
