### ISSUE TITLE
Content lock

### ISSUE THREAD

**Issue by Tychodewaard** [dnnsoftware/Dnn.Platform#3013]
## Description of problem
In most tenders people ask for content lock. If this is not present, there is a risk that more than 1 person is working on the same item and overwriting each others work. This results in frustration (I have top do my work again) or confusion (the system doesn't work) because they don't understand what happened

## Description of solution
Content lock simply means that if I am working on content, someone else either can not open it to edit (with alert why) or can open it but with warning 'user x is also working on this'. 

In order to prevent this feature request becoming a huge task, I suggest that we implement this for the HTML module first. Or create the feature in a generic way and have the HTML module be the first that works with it. Main prupose is that we have:

1. a feature that people can tick off
2. a feature that applies to a lot of usecases

I would not implement it in this stage for other scenarios like changing the role of a user. Or changing page settings etc. Keep it simple :-)

**Comment by mitchelsellers** [comment]
This is a good feature, but one that has a lot of very tricky scenarios that result in issues.  Items to consider when architecting the solution.

* User navigates away from the editing content (Internal to the site)
* User navigates away from the editing content (External to the site)
* User switches tabs in a browser (Can impact the tracking mechanism)
* User edits the site in multiple tabs
* User session expires
* User logs out

I think that this needs a very detailed proposed implementation plan.  A great feature, just one that has many what-if situations

**Comment by Tychodewaard** [comment]
User navigates away from the editing content (Internal to the site): the content is not saved, so this should unlock the content. 

User navigates away from the editing content (External to the site): the content is not saved, so this should unlock the content. 

User switches tabs in a browser (Can impact the tracking mechanism): if the content is still open in the other tab, it's still active, so it should still be locked,

User edits the site in multiple tabs: if the content is still open in the other tab, it's still active, so it should still be locked,

User session expires: the content is not saved, so this should unlock the content. 

User logs out: the content is not saved, so this should unlock the content. 

------------
If this gets complicated / messy, I can also live with a scenario where the lock is inactive after 4 hours. In that case, it would be awesome if there was a toaster or something telling the editor that the edit session has expired.

**Comment by valadas** [comment]
This makes sense but from a developer perspective, those events are hard to track because of the stateless nature of the web... The only solution I would see here is a constant probe from the client to the server to say "hey I am still editing" every 15 seconds or so, then if the server does not see that for let's say 1 minute in a row, it assumes the user went away and unlocks.

I think I would prefer a generic way to detect a user presence and expose that as an API for any module to know about it. Any issues with this and GDPR ? Any performance issues expected with a 15 seconds yes/no probe for just logged-in users ?

**Comment by Tychodewaard** [comment]
Live Articles and Live HTML from Mandeeps have a content lock. In fact, you can choose whether to have it activated or not. Would it be valuable to run the scenarios by that module?

**Comment by valadas** [comment]
Yeah, well, I mainly manage sites that have 1-3 editors and very often will not touche the same thing. Sooo, I am not too strong one way or another but I feel like this should be either.

1. A "I am still here API" in the core that modules can use.
2. Just make this whole thing a per-module thing and not bother making a general core API for it.

The only thing I am trying to do here is to see if first we have some motivated contributor to write that and 2: do we keep this issue in here it goes to the HtmlEditor provider repo... Just trying to do some triage :)

**Comment by valadas** [comment]
Soooo is anyone willing to implement this ?

**Comment by valadas** [comment]
I am closing this issue since there was no reply to anybody interested in implementing the feature.

**Comment by Tychodewaard** [comment]
When it's closed, we'll never find it again. I suggest we keep this open until David Poindexter has finished his issue management strategy. I hope this strategy will allow a place for ideas, even if they are not ready to implement in the next few weeks.

**Comment by valadas** [comment]
@Tychodewaard I was chatting with @david-poindexter when I was closing this issue, we have a big problem of managing actionable items, this github repository is full of great huge ideas that are just pending for months (and it was years before the first round of initial cleanup). We are trying to keep here what is currently actionable or has at least some indication that someone will be implementing the features/improvement. Our goal ultimately is to have a specific area for those ideas  but for now I would recommend keepting idea discussions in forums or other channels until we have an actionable item and some indication that a contribution will eventually come in. I asked 45 days ago if anyone was willing to implement this, but nobody answered, this is why I closed the issue. Yes, it would be nice to have but if nobody will write it, it just clutters the backlog.

**Comment by david-poindexter** [comment]
> When it's closed, we'll never find it again. I suggest we keep this open until David Poindexter has finished his issue management strategy. I hope this strategy will allow a place for ideas, even if they are not ready to implement in the next few weeks.

We are indeed working on a whole new system and process for funneling ideas into actionable items.  Unfortunately, it is not an overnight process and it will take time.  I will be publishing a follow-up blog shortly to explain the recent Phase I implementation for the new **Issue Management** strategy.
