### ISSUE TITLE
Link checker

### ISSUE THREAD

**Issue by Tychodewaard** [dnnsoftware/Dnn.Platform#3014]
## Description of problem
Working with content and linking to other pages (internally or externally) is part of the job. But it's not so easy to track whether your links are still valid. 
Non working links are bad for your business but also creates a penalty in Google as you obviously are not taking proper care of your website.

## Description of solution
I would suggest:
- In the scheduler a routine that somehow checks links. With a max of 5 times for instance. And purges results
- In the SEO section a tab 'link checker'
- A dropdown with the last 5 times it was checked
- Columns: Pagename with link, linked word, destination link, result (like 404)

## Description of alternatives considered
You can put a repeating activity in you calendar with a link to a online broke link checker but that's an extra step, it is forgotten every time a web editor is replaced and often these tools are limited to a couple of hundered pages.
If there is a way to use something external that's already awesome and just create a connector, that would be fine too. 

## Additional context
We have to be aware of the risk of eating all CPU. Like too many crawls in too little time. Or links getting in a loop (login failed, reset password etc)

**Comment by mitchelsellers** [comment]
@Tychodewaard Are you thinking of something like a crawler to manage this? Or would this be something looking at ONLY HTML content, or only menu items?

**Comment by Tychodewaard** [comment]
@mitchelsellers I'm thinking like a crawler yes. For my manual labour I always use https://www.brokenlinkcheck.com/

It is intended to verify my content so the target is HTML content. I trust the menu items to always be correct (unless you have created a page which is actually a redirect)

**Comment by valadas** [comment]
I my opinion this is something better handled by an external tool for performance reasons and accurate results including non-dnn links, etc.

**Comment by valadas** [comment]
Is anyone interesting in developing this solution?

**Comment by Tychodewaard** [comment]
@valadas is it an idea to add a topic in the manage-part of the persona bar where one can add 'favourites'? That way we could add a link to a broken link checker. But also other links that are important to editors like Google page speed, color schemes, WCAG checker etc. This way it would be:
- a simple solution (I think)
- a generic solution (as the host can add links any way he/she likes)
-  no risk on CPU load

Of course this would be a different feature request. If you think this might be a way forward, I'd be more than happy to sketch a wire on how I think it would be awesome for webmasters to maintain and editors to use.

**Comment by valadas** [comment]
I don't dislike the idea and I don't have a very strong opinion for or against it, but:

1. If it's just shortcuts and we don't provide a default set of links, then this already exists in the browser, and from the looks of it, it would be generic stuff that is not Dnn specific, so might just want those shortcuts not inside Dnn. We already have Dnn specific shortcuts to docs, github and community site, sooo...
2. If we do provide a default set of links, it has a potential be be pretty opinionated and might take more time deciding on than implementing :)
3. I know I wont be building that, nothing personal, but I have much higher priority items and no real use for this, if someone does submit a PR for that, I would not be against it though.

**Comment by valadas** [comment]
I am closing this issues in the spirit of clean-up, but if anyone is interested in contributing a solution, feel free to comment or reopen.
