### ISSUE TITLE
Search results page can not add module

### ISSUE THREAD

**Issue by Tychodewaard** [dnnsoftware/Dnn.Platform#3015]
## Description of bug
I can not add a module to the search results page

## Steps to reproduce
- Vanilla 4.0
- Type a word in the search bar
- enter (click on the icon doesn't work but that's theme related I guess)
- when you're on the results page try to add a module

## Current result
It's not doing anything
In inspect element there are some issues

10:28:31.605 selectize.min.js?cdv=33:3 Selectize: Dependency MicroPlugin is missing
c.explanation @ selectize.min.js?cdv=33:3
(anonymous) @ selectize.min.js?cdv=33:3
(anonymous) @ selectize.min.js?cdv=33:3
(anonymous) @ selectize.min.js?cdv=33:3
10:28:31.606 selectize.min.js?cdv=33:3 console.group
10:28:31.607 selectize.min.js?cdv=33:3 Make sure you either: (1) are using the "standalone" version of Selectize, or (2) require MicroPlugin before you load Selectize.
c.explanation @ selectize.min.js?cdv=33:3
(anonymous) @ selectize.min.js?cdv=33:3
(anonymous) @ selectize.min.js?cdv=33:3
(anonymous) @ selectize.min.js?cdv=33:3
10:28:31.613 selectize.min.js?cdv=33:4 Uncaught TypeError: w.define is not a function
    at selectize.min.js?cdv=33:4
    at selectize.min.js?cdv=33:3
    at selectize.min.js?cdv=33:3
(anonymous) @ selectize.min.js?cdv=33:4
(anonymous) @ selectize.min.js?cdv=33:3
(anonymous) @ selectize.min.js?cdv=33:3
10:28:31.835 dnn.combobox.js?cdv=33:4 Uncaught ReferenceError: Selectize is not defined
    at dnn.combobox.js?cdv=33:4
    at dnn.combobox.js?cdv=33:172
(anonymous) @ dnn.combobox.js?cdv=33:4
(anonymous) @ dnn.combobox.js?cdv=33:172
10:28:31.933 Search-Results?Search=leren:229 GET http://dnnn94.localhost/DnnImageHandler.ashx?mode=profilepic&userId=1&h=32&w=32 500 (Internal Server Error)
10:28:32.110 Search-Results?Search=leren:830 Uncaught TypeError: $(...).dnnComboBox is not a function
    at Search-Results?Search=leren:830
(anonymous) @ Search-Results?Search=leren:830
10:28:32.529 dnn.searchResult.js?cdv=33:559 Uncaught TypeError: Cannot read property 'get_items' of undefined
    at HTMLAnchorElement.<anonymous> (dnn.searchResult.js?cdv=33:559)
    at HTMLAnchorElement.dispatch (jquery.js?cdv=33:5206)
    at HTMLAnchorElement.elemData.handle (jquery.js?cdv=33:5014)
    at Object.trigger (jquery.js?cdv=33:8201)
    at HTMLAnchorElement.<anonymous> (jquery.js?cdv=33:8269)
    at Function.each (jquery.js?cdv=33:362)
    at jQuery.fn.init.each (jquery.js?cdv=33:157)
    at jQuery.fn.init.trigger (jquery.js?cdv=33:8268)
    at dnn.searchResult.js?cdv=33:683
(anonymous) @ dnn.searchResult.js?cdv=33:559
dispatch @ jquery.js?cdv=33:5206
elemData.handle @ jquery.js?cdv=33:5014
trigger @ jquery.js?cdv=33:8201
(anonymous) @ jquery.js?cdv=33:8269
each @ jquery.js?cdv=33:362
each @ jquery.js?cdv=33:157
trigger @ jquery.js?cdv=33:8268
(anonymous) @ dnn.searchResult.js?cdv=33:683
setTimeout (async)
dnn.searchResult.init @ dnn.searchResult.js?cdv=33:683
(anonymous) @ Search-Results?Search=leren:677
mightThrow @ jquery.js?cdv=33:3583
process @ jquery.js?cdv=33:3651
setTimeout (async)
(anonymous) @ jquery.js?cdv=33:3689
fire @ jquery.js?cdv=33:3317
fireWith @ jquery.js?cdv=33:3447
fire @ jquery.js?cdv=33:3455
fire @ jquery.js?cdv=33:3317
fireWith @ jquery.js?cdv=33:3447
ready @ jquery.js?cdv=33:3920
completed @ jquery.js?cdv=33:3930
10:28:34.173 ModuleDialog.js?cdv=33:342 Uncaught TypeError: Cannot read property 'title' of undefined
    at dnn.dnnModuleDialog._generateLayout (ModuleDialog.js?cdv=33:342)
    at dnn.dnnModuleDialog.init (ModuleDialog.js?cdv=33:28)
    at new dnn.dnnModuleDialog (ModuleDialog.js?cdv=33:20)
    at Object.dnn.ContentEditorManager.getModuleDialog (ModuleManager.js?cdv=33:21)
    at handleNewModuleFromCookie (ContentEditor.js?cdv=33:321)
_generateLayout @ ModuleDialog.js?cdv=33:342
init @ ModuleDialog.js?cdv=33:28
dnn.dnnModuleDialog @ ModuleDialog.js?cdv=33:20
dnn.ContentEditorManager.getModuleDialog @ ModuleManager.js?cdv=33:21
handleNewModuleFromCookie @ ContentEditor.js?cdv=33:321
setTimeout (async)
handlerNewModuleFromCookie @ ContentEditor.js?cdv=33:346
dispatch @ jquery.js?cdv=33:5206
elemData.handle @ jquery.js?cdv=33:5014
load (async)
add @ jquery.js?cdv=33:5062
(anonymous) @ jquery.js?cdv=33:4962
each @ jquery.js?cdv=33:362
each @ jquery.js?cdv=33:157
on @ jquery.js?cdv=33:4961
on @ jquery.js?cdv=33:5570
(anonymous) @ bootstrap.min.js?cdv=33:6
(anonymous) @ bootstrap.min.js?cdv=33:6

**Comment by bdukes** [comment]
The root of this issue is the same as #3002, which has a pending fix in #3003. There's a workaround discussed in https://github.com/dnnsoftware/Dnn.Platform/issues/3002#issuecomment-532394865

**Comment by valadas** [comment]
@Tychodewaard Did you try using Dnn 9.4.1, I think what @bdukes mentioned solves this...

**Comment by Tychodewaard** [comment]
I tried 9.4.1.
If I try to add a module to the search results page, the module hoovers above the page and I get the question 'Do you want to reload the page". If I say 'no', the add module action is terminated. If I say 'yes', the page reloads, the module hoovers above the page, I get the question if I want to reload the page etc...

**Comment by lanthonyneville** [comment]
I am still seeing this issue under 9.4.3. For example, when using a combobox on the Digital Asset Management Settings tab, the following JS errors occur:

Selectize: Dependency MicroPlugin is missing
c.explanation @ selectize.min.js?cdv=427:3
selectize.min.js?cdv=427:3 console.group
selectize.min.js?cdv=427:3 Make sure you either: (1) are using the "standalone" version of Selectize, or (2) require MicroPlugin before you load Selectize.
c.explanation @ selectize.min.js?cdv=427:3
selectize.min.js?cdv=427:4 Uncaught TypeError: w.define is not a function
    at selectize.min.js?cdv=427:4
    at selectize.min.js?cdv=427:3
    at selectize.min.js?cdv=427:3
dnn.combobox.js?cdv=427:4 Uncaught ReferenceError: Selectize is not defined
    at dnn.combobox.js?cdv=427:4
    at dnn.combobox.js?cdv=427:172
400?ReturnURL=/Files/folderId/11634/view/gridview/pageSize/10&popUp=true:1328 Uncaught TypeError: $(...).dnnComboBox is not a function
    at 400?ReturnURL=/Files/folderId/11634/view/gridview/pageSize/10&popUp=true:1328
400?ReturnURL=/Files/folderId/11634/view/gridview/pageSize/10&popUp=true:1355 Uncaught TypeError: $(...).dnnComboBox is not a function
    at 400?ReturnURL=/Files/folderId/11634/view/gridview/pageSize/10&popUp=true:1355

**Comment by bdukes** [comment]
@lanthonyneville it looks like you got stuck with a bad version of the Selectize JS library.  Can you try doing a repair install of that package?  In the 9.4.3 upgrade package, find the `Install/JavaScriptLibrary/Selectize_00.12.06_Install.zip` package and install it through the _Extensions_ persona bar page.  It should let you do a repair installation of it (since the broken version of it was installed 9.4.0), and then you'll get the right script loaded by the Digital Assets Manager.  Let me know if that has any effect.

**Comment by lanthonyneville** [comment]
@bdukes I did the repair install as you described, and it worked. In the next release can you do something to force through this "repair"? Advancing the version number for the package is not really appropriate ... is there some other way?

**Comment by bdukes** [comment]
In our testing, the JS library package had automatically repaired during the upgrade process, so I'm not sure if there was a problem with our testing, or if there's an environmental problem that's stopping the repair from happening as it ought…

**Comment by lanthonyneville** [comment]
Well if Selectize package 00.12.06 was distributed with DNN 9.4.0 (containing the 'bad' script) and then the package was distributed again (with the same 00.12.06 number) with DNN 9.4.3 (but now with the 'good' script), on upgrading DNN would not install it given it had the same number ..... right?

**Comment by lanthonyneville** [comment]
Just tried doing an upgrade of a 2nd 9.4.1 site to 9.4.3 and the issue was still present after the upgrade. I then did the repair install of the Selectize 00.12.06 package as suggested by @bdukes and this resolved the issue again.

**Comment by valadas** [comment]
>DNN would not install it given it had the same number ..... right?

This is true for modules but not for libraries (well in theory at least)...

**Comment by Tychodewaard** [comment]
Tested in 9.5 and is ok now. Thnx!
Can be closed as far as I'm concerned
