### ISSUE TITLE
Create DNN extension for Identity Server 4.0.

### ISSUE THREAD

**Issue by lucky85008** [dnnsoftware/Dnn.Platform#3018]
I am requesting a feature to Create DNN extension for Identity Server 4.0. So many people are looking this integration

Similar to DNN Extension for FACEBook, Google, Twitter.
There can be an Identity Server 4.0  extension for DNN
like Windows Live
https://github.com/dnnsoftware/Dnn.Platform/tree/release/9.3.2/DNN%20Platform/Providers/AuthenticationProviders

 Identity Server 4.0 is supported by Microsoft , we need more support for it from DNN.

Thanks.
Lucky

**Comment by valadas** [comment]
Is there someone willing to implement this ?

**Comment by valadas** [comment]
I am closing this issue in the spirit of cleaning the backlog, if anyone is interested in developing this, please comment or reopen.
