### ISSUE TITLE
Unable to locate TabID in Pages Admin

### ISSUE THREAD

**Issue by brewadmin** [dnnsoftware/Dnn.Platform#3026]
## Description of bug
Unable to Find TabID in Pages section
I need to use the TabID / PageID for the DDR Menu

## Steps to reproduce
List the steps to reproduce the behavior:

## Current result
Explain what the current result is.

## Expected result
Provide a clear and concise description of what you expected to happen.

## Screenshots
If applicable, provide screenshots to help explain your problem.

## Error log
Paste the error log that is related to this issue.

## Additional context
Add any other context about the bug that may be helpful for resolution.

## Affected version

* [ ] 10.0.0 nightly build
* [ ] 9.4.1 nightly build
* [ ] 9.4.0 latest supported release

## Affected browser

* [ ] Chrome
* [ ] Firefox
* [ ] Safari
* [ ] Internet Explorer
* [ ] Edge

**Comment by valadas** [comment]
This is something I would like to implement when I get some time unless someone picks it up first, but a simple tooltip over the page title or some such would be enough or a small Id:xxx somewhere, should not be to hard to implement...

**Comment by brewadmin** [comment]
Thank you.

**Comment by sleupold** [comment]
still relevant :)
