### ISSUE TITLE
[DependencyInjection] Unable to Inject IServiceProvider

### ISSUE THREAD

**Issue by ahoefling** [dnnsoftware/Dnn.Platform#3028]
## Description of bug
The `IServiceProvider` is not added to the Dependency Injection container and doesn't allow developers to resolve using constructor injection

## Steps to reproduce
List the steps to reproduce the behavior:
1. Create a MVC (or any module) 
2. Add `IServiceProvider` to the constructor for injection
3. Execute module

## Current result
`IServiceProvider` is not injected

## Expected result
`IServiceProvider` should be injected so the code can resolve dependencies at runtime.

## Screenshots
Not Applicable

## Code Snippet
```c#
public class HomeController : DnnController
{
  IServiceProvider _serviceProvider;
  public HomeController(IServiceProvider serviceProvider)
  {
    _serviceProvider = serviceProvider;
  }
}
```

The scenario above will not work since the `IServiceProvider` is not added to the container at Application Startup

## Error log
Not Applicable

## Additional context
Add any other context about the bug that may be helpful for resolution.

## Affected version

* [x] 10.0.0 nightly build
* [x] 9.4.1 nightly build
* [x] 9.4.0 latest supported release

## Affected browser
Not Applicable

**Comment by ahoefling** [comment]
I did some more research on this item and it appears the `Microsoft.Extensions.DependencyInjection` automatically registers the `IServiceProvider`. This bug was created after analyzing the platform code and speaking with @mitchelsellers.

I ran some more thorough tests and injecting the `IServiceProvider` works as expected

**Comment by constantine-ketskalo-netls** [comment]
I've currently stumbled upon a situation that dependency injection of the `IServiceProvider` stopped working for a custom SitemapProviders, which inherit the DNN's `SitemapProvider` class. It has been working previously, but then stopped working and I'm not sure what has caused it.
In my case it's in DNN v 9.10.02. So I've been thinking of testing newer versions, but seems like you've had the same issue on the latest version.
So what did you do to fix it, @SkyeHoefling?
