### ISSUE TITLE
Navigation Location of file is forgotten in Language Translator

### ISSUE THREAD

**Issue by thabaum** [dnnsoftware/Dnn.Platform#3034]
## Description of bug
Navigation Location of file is forgotten in Language Translator after you save the file.  You have to navigate to get to the same drop down as the file that is currently selected

## Steps to reproduce
List the steps to reproduce the behavior:
1. Go to language translator
2. navigate to a resource file
3. click save after making a change
4. Click on the drop down list and the drill down to the file selected is unavailable.  
## Current result
You need to navigate back through the drop down every time you want to select a new file.

## Expected result
The drop down list would show all folders that previously had been expanded to get to the current file selected.

## Screenshots
If applicable, provide screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/13577556/65811766-6c3d7880-e172-11e9-833f-1b55c370213c.png)

## Error log
Paste the error log that is related to this issue.

## Additional context
It is nice to be able to see what places you have already visited as well as go to a file in the same language translation resource type by having all previously expanded or closed shown at all times.  Otherwise can be a real mind game.

## Affected version

* [ ] 10.0.0 nightly build
* [ x] 9.4.1 nightly build
* [x] 9.4.0 latest supported release

## Affected browser

* [ x] Chrome
* [x ] Firefox
* [x ] Safari
* [ x] Internet Explorer
* [ x] Edge

**Comment by sleupold** [comment]
this is an important issue for translators, I noticed as well recently and should be reopened.

**Comment by sleupold** [comment]
please check also #3468
The DDL misses to close itself after selecting a file, but it also forgets after saving the file, to open the path of the file in the tree view.

**Comment by sleupold** [comment]
still an issue
