### ISSUE TITLE
Journal: A post created in Social Groups will not create a back link and store ItemData Url & Title.

### ISSUE THREAD

**Issue by thabaum** [dnnsoftware/Dnn.Platform#3035]
## Description of bug
A post on a community wall needs to have an identity so visitors can connect to the message being posted more than just reading the text.

## Steps to reproduce
List the steps to reproduce the behavior:
1. Go to a social group and make a post
2. Go to an activity feed for the website and it shows up without a link to the social group to identify where it came from or what it is in relation to.

## Current result
No back link going to the place of origin if it is from a social group.

## Expected result
A link to the social group activity page.

## Screenshots
If applicable, provide screenshots to help explain your problem.

## Error log
Paste the error log that is related to this issue.

## Additional context
It would be great to be able to set default permissions for group views so that the group creator would be the moderator that can set the privacy for the group and private group messages are not posted to the world but everyone can see them in the group.  Group view permissions override the user view permissions.  It would be nice to have a few lite features like this to manage groups and an easy way to extend group module features from that first nice example.

## Affected version

* [ ] 10.0.0 nightly build
* [ ] 9.4.1 nightly build
* [ ] 9.4.0 latest supported release

## Affected browser

* [ ] Chrome
* [ ] Firefox
* [ ] Safari
* [ ] Internet Explorer
* [ ] Edge

**Comment by thabaum** [comment]
I am still digging into all the journal files see how I can improve things such as this issue.  I went stale a few weeks but this issue and other with the journal data items for 'link' types is currently not saving the http url to the journal. #3308 

I have read the entire module code a few times so it will start to flow in my mind hopefully soon.

**Comment by thabaum** [comment]
still on my back burner but if someone else dives in please be my guest ;)  I will be making another go of things in the next couple weeks see what I can get done to help here and on a few other things related to this area.  Thank you.

**Comment by thabaum** [comment]
Maybe two weeks I can take a look at this along with the other journal issues.  I will be looking for DNN Docs to give me some love on the topic :)

**Comment by thabaum** [comment]
Coming alive!  My next upcoming challenge after https://github.com/dnnsoftware/Dnn.Platform/issues/2314 and https://github.com/dnnsoftware/Dnn.Platform/issues/3308 are fixed.

**Comment by thabaum** [comment]
OK, for a recap here.

Visit a social group and post something inside the **social group's page "journal module"** no back link is created.
The challenge is...
- The back link bread crumb needs to only be displayed on pages (like the activity feed page) that do not have a social group module configured on it.

**Comment by thabaum** [comment]
P.S. can I have this re-opened?  Thank you!

**Comment by valadas** [comment]
Issue reopened @thabaum I am afraid I can't be of much help on the Journal as I did not use it much, but will be glad to review PRs about it.

**Comment by Tychodewaard** [comment]
@Timo-Breumelhof Tomorrow a quick call to discuss this?

**Comment by Timo-Breumelhof** [comment]
@Tychodewaard sure

**Comment by Timo-Breumelhof** [comment]
@thabaum 
I had a look at the issue and I agree it's an issue.
Responding to point 5, I would prefer:

User Display Name posted in: Group Name Link
Message

What if you would use static localization for this message (with tokens)?

`[User:DisplayName] posted in: <a href="[GroupLink]">[Groupname]</a>`

That way one can change the message as needed..

**Comment by Tychodewaard** [comment]
@thabaum Adding 2cents to what @Timo-Breumelhof said: it would be nice if we can see :
- whether the journal post derives from a forum post or a blog (or something els)
- the forum category a post or reply resides
- the social group if applicable.
![image](https://user-images.githubusercontent.com/9091997/145585511-125d4fad-3cb7-4edd-a9a0-92e040f2878a.png)
I think a basic version could look like this.

**Comment by thabaum** [comment]
Thank you @Timo-Breumelhof and @Tychodewaard for your much appreciated feedback.  I agree what is said and will follow these suggestions as I can.  

I like the idea of displaying the group title and forum category.  After reviewing your suggestions @Tychodewaard I would probably like to do it something like the following:
![image](https://user-images.githubusercontent.com/13577556/145617185-a4b0f8f5-24be-4b64-95eb-617f052f1207.png)

There is an added challenge now as I would need to possibly make a group item in the `itemData` field in the database and logic to hold the extra information of a two more Urls and Title's AND edit the DNN forum and DNN Blog projects to pass this information of a as well as all modules that want to display this information would need to add the ability.  

This would be better to put into another PR down the road as it is a little more complex to implement.  With work currently with what is readily available in DNN to remove any confusion while using the system just shooting for @Timo-Breumelhof suggestion will suffice for now.  The backlink to the messages in the forum is at least being created.  A social group journal post does not get a back link.

I am trying currently to see if I can put the logic into a resx file without breaking things and having it work.  @valadas @bdukes maybe can help me answer this.  I just really need a syntax example of how an `if (){}` statement would look inside a resx file for this module.  The variables I am after is `GroupID` from the page if it has one... dont show the group post backlink.  Seems simple enough to solve the that part of this upcoming solution.

Then I just need to also add to the logic for when a post is made inside a group to also add the `itemData` such as url,title,summary...

If I make any adjustments to adding new urls to the resx templates I will add/test solutions on the DNN Blog, DNN Forums and DNN Events modules to share the same information.  So that would be a multi-PR mission.

I will possibly also migrate one of these modules to the next generation if I can find the time to learn about and do it.

If any of the current templates for posts going into journal need adjusted, I will be happy to do this as well to keep things looking uniform default.

Keep the ideas rolling here, but I need to stick to the main purpose of this PR unless it is something broken.  I think if you are using the social modules, so am I.  The long-term plan here will include all the ideas and features possible and that make logical sense to be included.


> @thabaum I had a look at the issue, and I agree it's an issue. Responding to point 5, I would prefer:
> 
> User Display Name posted in group: Group Name Link Message
> 
> What if you would use static localization for this message (with tokens)?
> 
> `[User:DisplayName] posted in: <a href="[GroupLink]">[Groupname]</a>`
> 
> That way one can change the message as needed.

These templates are currently located in the Journal Resx file which means you can edit them. 
![image](https://user-images.githubusercontent.com/13577556/145621124-5deb8467-afba-4b5e-9443-3688926a7ae6.png)

This is where I want to put the if statement to show or not show the group backlink depending on if there is a groupID on the page or not.

Then the next trick is to get the journal to post url and message title to `itemData` field.  The `Title` database field does not get used except by creating groups logic.  I will have to see how blog and forums use this by installing those mods.  Title otherwise gets stuck in the Title section of a url.  Maybe I need to make a category field in the db.

We will keep this open for discussion as I do want to improve the modules as desired by the community as I can.  We will need to open up another issue regarding adding new fields to the journal posts displaying extra backlinks.  The first step is to get the journal group posts to show as desired.

Bottom line unless there is an objection, I think I will move forward with 'User Display Name posted in group: Group Name Link Message'.  

I think the others should say `posted in forum: ` and `posted in blog: ` but these again could be another PR, however we could fix this in this PR.  You can edit this template now in your language files.  Just understand the tokens only work on pages that have the module running if I am not mistaken.  The tokens you see in the template are created by the Journal Module so you dont get the ones imported in from the forums or blog unless you are on a page that has those mods running.  I may be wrong here let me know!  Before you get too excited throwing down all the tokens created in modules and wonder why they are not working I just wanted to give a heads up.  I get what you are both saying, and we are on track for it.

I will install the blog, events and forum module and test these out to make them all look uniform as a cherry on top of this PR if I have time.  

Thanks again for the input, thumbs ups and all that for what has been shared.  This helps clear some fog!

**Comment by thabaum** [comment]
To answer while asking my own question @valadas and @bdukes if I am correct, I can use [javascript](https://www.javatpoint.com/how-to-add-javascript-to-html) in the resx file I am hoping?

**Comment by valadas** [comment]
I would not recommend including javascript in resource files:
1. It makes maintaining that code very hard
2. It opens the door to all sorts of bugs and/or security issues

**Comment by thabaum** [comment]
Thanks @valadas that was also part of my concerns with using JavaScript here which is why I had to ask.  

Then the switch will be done in the backend to another template file by using a new journal type id for posts created in a group and direct the new logic to switch the views.  Show two different templates, the default `journal_status.Text` resx template showing while in group (could also make a `journal_groupstatus.Text` template) and a `journal_grouppost.Text` resx template showing up for activity feeds (when `GroupId` not set on a page).

Is this going to be legal to do here or maybe a better way to approach this in general?  Trying get to work on this heading in the right general direction.

**Comment by sleupold** [comment]
I agree with @valadas and would make it more difficult for the translators.

**Comment by thabaum** [comment]
@david-poindexter  I see a lot of documentation needed for elements that could clear up some build noise.  [https://docs.dnncommunity.org/api/](https://docs.dnncommunity.org/api/)

Is this where it needs to get documented?  What is the process for documenting an element?   I would like to try to help clean up some build noise from the easier stuff like documenting elements while I am working an area so we can see the more complex jobs to do like helping migrate obsolete items.

**Comment by thabaum** [comment]
It looks like we would need to get into the `Journal_Types` of the journal database and create a new one called `groupstatus`
![image](https://user-images.githubusercontent.com/13577556/145647287-bdd598c5-4c3f-498d-b414-e6ee0a223c0b.png)

```
            var journalTypeId = 1;  // "status" ?
            switch (postData.JournalType)
            {
                case "link":
                    journalTypeId = 2;
                    break;
                case "photo":
                    journalTypeId = 3;
                    break;
                case "file":
                    journalTypeId = 4;
                    break;
            }            
else
                {
                    rowTemplate = this.GetJournalTemplate(ji.JournalType, ji);
                }
```

In the DotNetnuke.Modules.Groups file GroupUtilities.cs I found this one method:

```            
    public class GroupUtilities
    {
        public static void CreateJournalEntry(RoleInfo roleInfo, UserInfo createdBy)
        {
            var journalController = JournalController.Instance;
            var journalItem = new JournalItem();

            string url = string.Empty;

            if (roleInfo.Settings.ContainsKey("URL"))
            {
                url = roleInfo.Settings["URL"];
            }

            journalItem.PortalId = roleInfo.PortalID;
            journalItem.ProfileId = createdBy.UserID;
            journalItem.UserId = createdBy.UserID;
            journalItem.Title = roleInfo.RoleName;
            journalItem.ItemData = new ItemData { Url = url };
            journalItem.SocialGroupId = roleInfo.RoleID;
            journalItem.Summary = roleInfo.Description;
            journalItem.Body = null;
            journalItem.JournalTypeId = journalController.GetJournalType("groupcreate").JournalTypeId;
            journalItem.ObjectKey = string.Format("groupcreate:{0}:{1}", roleInfo.RoleID.ToString(CultureInfo.InvariantCulture), createdBy.UserID.ToString(CultureInfo.InvariantCulture));

            if (journalController.GetJournalItemByKey(roleInfo.PortalID, journalItem.ObjectKey) != null)
            {
                journalController.DeleteJournalItemByKey(roleInfo.PortalID, journalItem.ObjectKey);
            }

            journalItem.SecuritySet = string.Empty;

            if (roleInfo.IsPublic)
            {
                journalItem.SecuritySet += "E,";
            }

            journalController.SaveJournalItem(journalItem, null);
        }
    }
}
```
The line I see is `journalItem.JournalTypeId = journalController.GetJournalType("groupcreate").JournalTypeId;` with `groupcreate` used for a journal type to let the journal know to create an entry.

**Comment by thabaum** [comment]
Status update: 

I did get a version of the above code to work for switching the group message on and off to a newly created `journal_groupstatus` in the resx file.

I just need to have the group posts that already set the id, also insert the same logic the database now while posting so that the group url and title information is connected to the post.  I am not passing the objectkey or am I?  I am making it work without it.  I just set the Title and set the same journal item data that was in the group that was created.  Seems to work good, this should be done soon :)

**Comment by thabaum** [comment]
For a recap:

- `DotNetNuke.Modules.Journal.SharedResources.rex` file a resx I added an entry with the name `journal_groupstatus.Text` with the same template information as `journal_groupcreated.Text`. modified as described agreed upon earlier by community members.
- `DotNetNuke.Modules.Journal.JournalParser.cs` 
-- modified the if statement line 136
```            foreach (JournalItem ji in journalList)
            {
                string replacement = this.GetStringReplacement(ji);

                string rowTemplate;
                if ((ji.JournalType == "status") && (this.SocialGroupId < 1) && (ji.SocialGroupId > 1))
                {
                    rowTemplate = groupstatusTemplate;
                    rowTemplate = TemplateRegex.Replace(rowTemplate, replacement);
                }
                else if (ji.JournalType == "status")
                {
                    rowTemplate = statusTemplate;
                    rowTemplate = TemplateRegex.Replace(rowTemplate, replacement);
                }
                else if (ji.JournalType == "link")
                {
                    rowTemplate = linkTemplate;
                    rowTemplate = TemplateRegex.Replace(rowTemplate, replacement);
                }
                else if (ji.JournalType == "photo")
                {
                    rowTemplate = photoTemplate;
                    rowTemplate = TemplateRegex.Replace(rowTemplate, replacement);
                }
                else if (ji.JournalType == "file")
                {
                    rowTemplate = fileTemplate;
                    rowTemplate = TemplateRegex.Replace(rowTemplate, replacement);
                }
                else
                {
                    rowTemplate = this.GetJournalTemplate(ji.JournalType, ji);
                }
```
and on line 95 about I added 2 lines for `groupstatusTemplate` as shown below.
```
            string statusTemplate = Localization.GetString("journal_status", ResxPath);
            string linkTemplate = Localization.GetString("journal_link", ResxPath);
            string photoTemplate = Localization.GetString("journal_photo", ResxPath);
            string fileTemplate = Localization.GetString("journal_file", ResxPath);
            string groupstatusTemplate = Localization.GetString("journal_groupstatus", ResxPath);

            statusTemplate = BaseUrlRegex.Replace(statusTemplate, this.url);
            linkTemplate = BaseUrlRegex.Replace(linkTemplate, this.url);
            photoTemplate = BaseUrlRegex.Replace(photoTemplate, this.url);
            fileTemplate = BaseUrlRegex.Replace(fileTemplate, this.url);
            groupstatusTemplate = BaseUrlRegex.Replace(groupstatusTemplate, this.url);
```

To test I simply did the following:
1. created a group.
2. created a post inside a group (notice the groupid is set for the journal item in the database)
3. copied the group created journal database `ItemData` and `Title` information to the post made in step 2 (the GroupID is set in the post already, that is how the magic works in the if statement for running the two different templates)

I will now work on the part that a journal inserting number 3.  Make sense yet?

**Comment by thabaum** [comment]
This is a bit of a task to pull off here for everyone, I really hope to make time for it soon.  I am working hard to make time soon.  I want to enhance this part of DNN until satisfied then move into other parts of it.  I am just not sure I can make it by 10.3 as a few things with work pushing me back.  I can't wait :) This will be a fun PR for me.  I will be sure to get all the fixes in one so the latest two PR's can hold on if desired I submitted, however it maybe version 9.11 before I get the time it takes to get done for everyone.  It is on my radar, and I will share my results when I work on it as a contribution.  When it's done, I will post here as I feel I have enough to move forward with for now as far as community details.  I have a feeling my first attempt with PR will fail in sense there are a couple ways I can handle this, and with failure comes success as I am sure someone from the community will point out the better direction, which was probably close to my other way I am thinking of handling things.  I am confident by v10 for sure!

I guess my ONE question now that would me sleep better on it is should I create the new types in the database or hard code them into the Journal source code?  

A. Use the database templates called by `typeID` for `journal_groupstatus`, `journal_grouplink`, `journal_groupfile`, and `journal_groupphoto` templates with the backlink.  I may need to make `group_forumpost` `group_blogpost` `group_event` and even a general `group_post` so then maybe I make `group_status` and `group_link` 'group_file`?  I will create all that are needed to make this thing future proof and fit everyone's needs for posting things in a group, please I will give this time to marinate.

B. Set the source code to make the switch similar to how it uses the default templates and not worry about other use cases, just journal posts inside a group module.  For other cases I think existing templates can add the newly created in this PR second `Url2:` and `Title2:` passed through JSON if it exists in the template file create it, if it is blank, so is the text for the link.  You generally are never on the journal page and a forum at the same time.  So then the above A is overkill.

C. Do something else that involves the switch in another way?

Hope some of that makes sense I know it is a lot to read, let alone write for input.  I am just about to dump some serious time into this at some point, I want to be ready to rock when I do!

Another idea I have been passing around but not fully thought through yet originally was using a second template that gets included with all templates that gets parsed when a group module is not present producing a backlink for group posts (Or even a shopping cart item someone purchased back link to what they bought?!). which can point to a group at the top or bottom of a post and displayed only if it is not in a group, a product or whatever you feel that link is going to be with the title.  

Bottom line is I want to enhance the module best I can with my abilities.  I have some future stuff in mind but this is to start it all off and get a real understanding of what makes this thing tic.

I figure A is probably going to pass all critiques the best, but B would fly too potentially.

Sounds like I will be setting a second `Url2:` and `Title2` in JSON, I am not sure what problems that will bring towards already existing modules with input already.  I have some testing there to check things out more.  Any special ways anyone wants that named I suppose talk now, or after PR is submitted.

I can make the switch case for it all and then point either or, however these would need created along with sql provider to help get those in place for use.  The switch will change templates with the code I submitted above if I remember correctly.  Besides "How" you do it, there is a choice here, and the community along with the developers should choose.  It is more work to add to SQL, but if that is THE way, that is the way I will do it.  If community is ok with it switching inside the source code to the resx template.

Food for thought!

Thank you all for helping support the DNN Project! <3
