### ISSUE TITLE
DNN Platform Search Not Recognizing Quotes in Search Phrases

### ISSUE THREAD

**Issue by poweredbywsi** [dnnsoftware/Dnn.Platform#3043]
Screencast: https://www.screencast.com/t/orTXnhyCmQB1 

## Description of bug
When using DNN search and trying to search for something that has more than one term and using quotes, the results ignore the quotes and bring back individual term results.

## Steps to reproduce
List the steps to reproduce the behavior:
1. Go to https://www.heartland.bank
2. Click on the search box at the top of the page and enter "apple pay" as an example search term.
3. You can see the one result for "Apple Pay" in the view but when you click on the more results you see several other results with just "pay" being highlighted
4. Because you searched for "apple pay" the ONLY results that should show are those that have the term "apple pay" in the copy

## Current result
When results are are returned the request to search for only set terms in quotes are ignored.

## Expected result
You should only see results that match the search phrase requested in the search box with the quotes around the term.

## Screenshots
https://www.screencast.com/t/orTXnhyCmQB1 is a video capture of an example for reference.

## Error log
N/A

## Additional context
The Screencast should show it clearly.

## Affected version
Tested this on 8.00.04 and higher versions have been confirmed this is an issue.

* [ ] 10.0.0 nightly build
* [ ] 9.4.1 nightly build
* [ ] 9.4.0 latest supported release

## Affected browser
This issue does not appear to be browser dependent.

* [x ] Chrome
* [x ] Firefox
* [x ] Safari
* [x ] Internet Explorer
* [x ] Edge

**Comment by valadas** [comment]
I can replicate on 9.4.1. 

A good way to test this with the steps above but with content from a new blank site using the default template is to search for "suit your", it returns a single result with the words "suit" and "your" together in the list, then when clicking "more results" it gives this:

![image](https://user-images.githubusercontent.com/6371568/66115473-e751c500-e59e-11e9-909c-48d9cc38fdc0.png)

**Comment by poweredbywsi** [comment]
Thanks for further validation! Hope this gets fixed soon. Should be an obvious issue.

**Comment by sleupold** [comment]
AFAIK still an issue

**Comment by valadas** [comment]
There was some fixes to search unrelated directly to this issue, but it looks like those fixes resolved this one:

![image](https://user-images.githubusercontent.com/6371568/98695273-7273c180-2340-11eb-8af4-f8ffbf3660c6.png)

Can we please use Stalebot closing issue to at least remind us to re-test and not reopen stale issues without at least a re-test for bugs or some intention to implement for new features/improvements.

The purpose of stalebot is to cleanup the backlog by removing stale issue (issue open and not discussed on for a long time). If people just keep reopening them without further actions, it kinda defeats stalebot purpose.
