### ISSUE TITLE
Home page gets automatically translated if name is "Home"

### ISSUE THREAD

**Issue by dieterdtx** [dnnsoftware/Dnn.Platform#3044]
## Description of bug / unwanted feature
Home page gets automatically translated if name is "Home"

## Steps to reproduce (not all steps are needed, but are added info)
1. Install clean DNN9.4
2. Add a language pack, eg. nl-NL
3. Enable Content Localization
4. Setting nl-NL as default language
4. When checking the Page Settings - Localization, you can see the Page names: Home and Home (en-US) for instance.

## Current result
When checking the live home page is says Home for English and Thuis for Dutch

## Expected result
When checking the live home page is says Home (en-US) for English and Home for Dutch, as this is what it says in "Page Settings - Localization"

## Additional context
As soon as you rename the Home page to Homa or Homes, the forces translation isn't applied. As soon as you rename it back to Home, it is "Thuis" again. 
This forced script is absolutely unnecessary. As it is I don't know how to have the Home page called Home in every language (without changing the language pack, which is kind of weird to do).

## Affected version
* [x] 9.4.0 latest supported release

**Comment by bdukes** [comment]
I believe this is happening because the pages in the default template include translations in the global resource file: https://github.com/dnnsoftware/Dnn.Platform/blob/35acaf57f6b06c2341732787a489642636eb71f4/Website/App_GlobalResources/GlobalResources.resx#L1013-L1015

If you go into the language editor, you should be able to edit the text of that key for the Dutch language.

Hope it helps!

**Comment by dieterdtx** [comment]
I know, but it should use the language file to translate the name of a page. The language packs are for interface translations, not for translating content.

**Comment by bdukes** [comment]
@donker @EPTamminga @sleupold any thoughts?  should these resource keys be removed?

**Comment by sleupold** [comment]
This is by design, from times where we didn't have ML templates.
I agree, we need a better strategy to handle "semi static" elements.

**Comment by EPTamminga** [comment]
If we do a clean up, it should be done thoroughly. Solution for now is to correct globaal and share resources (ehich I have done among other corrections, but I can not put them in the distrbution  pack, no access)

**Comment by donker** [comment]
I use this feature. So I'm not a big fan of removing it. Deprecating this means that any page that needs to show different names for different locales will need to be "Content Localized", i.e. copied. Given how much overhead this creates it is silly if all you want is a different page name. 

My use case is an app where portals are created on-the-fly with a bunch of pages and any number of languages active. The modules are multilingual so they adapt to the current locale. All I need is to have the page name correct. If I need to go full content localization the mangement of the portals will become a nightmare (I allow for adding and deleting active locales) plus I'll have many many more records in various tables.

The "proper" fix would be to properly allow pages to have localized names without creating a bunch of pages. But I'm sure that would meet with new resistance.

**Comment by valadas** [comment]
I am with @donker here. I would rather support a solution that does not remove current behavior where possible.

**Comment by dieterdtx** [comment]
@donker 

You say: "Deprecating this means that any page that needs to show different names for different locales will need to be "Content Localized", i.e. copied." But this is just about the default tabs, like Home and About-Us, in a default installation, how is this suddenly about "any page"?

And, the resx file should not overwrite the content localization setting, should it? 

So, I agree that the functionality shouldn't disappear, I'm suggesting that perhaps this should not be included in a default installation. And, above all, should not overwrite the content localization translation.

**Comment by donker** [comment]
> But this is just about the default tabs, like Home and About-Us, in a default installation, how is this suddenly about "any page"?

You can edit the resx file to include your own pages. I work on a vertical solution where I use this using a GlobalResources.fr-FR.Host.resx for instance. This adds the specific pages of our app and doesn't get overwritten on upgrade.

> So, I agree that the functionality shouldn't disappear, I'm suggesting that perhaps this (Home, About-Us translations) should not be included in a default "blank" installation.

I can live with that. I understand the logic and it could be a good compromise here.

**Comment by sleupold** [comment]
> So, I agree that the functionality shouldn't disappear, I'm suggesting that perhaps this (Home, About-Us translations) should not be included in a default "blank" installation. 
this is not possible, as the keys are included in GlobalRsources.resx, which needs to be the same for all new and upgraded DNN installations and language packs.

**Comment by valadas** [comment]
Yeah, keeping it on the Default template but removing it on the Blank template, for me looks like a good compromise here and quick to implement.

**Comment by sleupold** [comment]
@valadas this is NOT a template subject - even, if you remove the page from default template, the resource translating the name will still be part of GlobalResources.resx and translate the page name.
Removing the item from the resource file is also not an option, as it would break many existing sites.

**Comment by valadas** [comment]
Ooohhh, right...

**Comment by dieterdtx** [comment]
While letting this issue rest a bit, I can see the approach taken about having this in a default DNN installation.

However, the main issue about this is that the resx setting overrides the content localization setting.

I think this is more important than whether or not this is resx file or not.

**Comment by sleupold** [comment]
@dieterdtx 
DNN Content Localization (aka Language Specific Pages) does not touch page names, it just creates language specific clones of each page (except pages marked as "neutral", i.e. same for all languages).
The old approach for Home etc. just takes the page path and checks GlobalResources.resx for a key with same name, I am not a fan of increasing complexity of retrieving page names to fix an edge case with an existing work-around. IMO we need to improve localizability of neutral pages, which would supersede the old resx based localization.

**Comment by dieterdtx** [comment]
@sleupold 
I understand that you don't want to make things more complex. And sorry for going on about this, perhaps I am missing your point. I am sure you all have thought more about localization than me.

But consider this scenario: 
I want to use DNN content localization to localize all the pages on your website:

en: Home / Search / Working / About us / Our Products
de: Home / Suche / Arbeiten / Unsere Firma / Unsere Produkte

I can translate the German version of [Search] and [Working] in Page settings, but I have to edit [Home], [About us] and [Our Products] in the resx files? This is because //Home.String, //AboutUs.String and //OurProducts.String are in the language packs. And again, I understand that they are there, but I don't understand why they overwrite my localization setting.

The combination of having "Home" as a home page for all language and using DNN Localization is not an edge case.

**Comment by valadas** [comment]
I did not have time to try yet, but I was thinking that the resx only applied to neutral language pages... IE, if you make the home page localizable and generate each for it's language, then it takes the name you give it for each language... But I am not 100% sure, needs a test.

**Comment by dieterdtx** [comment]
@valadas 
This is not the case, I think that's the main issue I am having. I haven't tried all scenarios, but please also test with not having en-US as the default language.

**Comment by valadas** [comment]
Will do thanks.
