### ISSUE TITLE
Update to a newer version of Moment.js

### ISSUE THREAD

**Issue by OllyHodgson** [dnnsoftware/Dnn.Platform#3048]
## Description 

The PersonaBar includes moment.js v2.8.1 (Dnn.AdminExperience/Library/Dnn.PersonaBar.UI/admin/personaBar/scripts/contrib/moment.js). 

Suggest we upgrade to a newer version. Current version is 2.22.2.

## Affected version

* [x] 9.2.1

**Comment by valadas** [comment]
This is still a valid issue to take care of Stalebot

**Comment by david-poindexter** [comment]
I recently discovered a much more lightweight potential replacement for moment.js called `dayjs`.  It's API is similar to `moment` so unless we are using some peculiar feature within `moment` we should be able to convert to `dayjs` and have a bit of a performance boost.  The gain would be approximately from 18.2 KB to 2 KB. 🎯 

I'll create a new issue to look into this.

Also, looking at [THIS SEARCH](https://github.com/dnnsoftware/Dnn.Platform/search?l=JSON&q=moment%28) it looks like we are at least at v2.15.x for all the PB modules - some v2.22.x and one v2.23.x.

**Comment by valadas** [comment]
Moment.js was declared no longer maintained. For that reason I am closing this issue in favor of #3875
