### ISSUE TITLE
The icons in the PersonaBar are not labelled

### ISSUE THREAD

**Issue by OllyHodgson** [dnnsoftware/Dnn.Platform#3049]
## Description of problem

As described in issue dnnsoftware/Dnn.AdminExperience#21 the icons in the PersonaBar have no alternative text. This means they're effectively invisible to a blind user trying to administer the site using assistive technology.

## Description of solution

The icons are inline SVGs. Add a `<title>` element to the SVG file as alternative text. Due to browser bugs, also add a unique `id` attribute to `<title>` and an `aria-labellledby` attribute to the `<svg>` element, as per the advice in https://css-tricks.com/accessible-svgs/#article-header-id-6

## Description of alternatives considered

An alternative to making the SVGs accessible would be to add an aria-label attribute directly to the SVG's parent `<li>` element.

Another option is to add clear text labels with the icons. I think this should be considered as part of a larger project to improve the UX of the PersonaBar.

## Additional context

This should be fixable using `data-bind` attributes in https://github.com/dnnsoftware/Dnn.AdminExperience/blob/development/Library/Dnn.PersonaBar.UI/admin/personaBar/index.html

## Affected version

* [x] 9.2.1
* [x] 9.2
* [x] 9.1.1
* [x] 9.1
* [x] 9.0

## Affected browser

All browsers and users of assistive technology.

**Comment by sleupold** [comment]
AFAIK this has not been fixed and is an accessibility issue.
