### ISSUE TITLE
Update references to support@dotnetnuke.com to support@dnnsoftware.com

### ISSUE THREAD

**Issue by EPTamminga** [dnnsoftware/Dnn.Platform#3054]
## Description 
The text support@dotnetnuke.com and www.dotnernuke.com should reference dnnsoftware.com i.s.o. dotnetnuke.com

## Steps to reproduce
Nothing special,  just search for the references dotnetnuke.com

## Current result
Multiple locations in multiple files

## Expected result
None

## Affected version

* [x] 9.2.1
* [x] 9.2.0
* [x] 9.1.1
* [x] 9.1
* [x] 9.0

**Comment by valadas** [comment]
PR merged, feel free to reopen if that PR did not cover it all or open new issue with more specifics.
