### ISSUE TITLE
Security Analyzer Default Page check fails post upgrade to 9.4.1

### ISSUE THREAD

**Issue by james7342** [dnnsoftware/Dnn.Platform#3055]
## Description of bug
Post upgrade to 9.4.1 Security Analyzer fails on Check Default Page indicating a page has been modified.

## Steps to reproduce
List the steps to reproduce the behavior:
1. Upgrade to DNN 9.4.1
2. PersonaBar/Security/Security Analyzer
3. Scroll down to CheckDefaultPage
4. Notice "Fail" with Note: There is no data available about your current installation, please upgrade this module to it's latest version.

## Screenshots
![screenshot_961](https://user-images.githubusercontent.com/27960723/66034198-a46bf080-e4bd-11e9-8924-5227b25d7748.png)
![screenshot_962](https://user-images.githubusercontent.com/27960723/66034250-c06f9200-e4bd-11e9-9f7c-cb36c435d2e0.png)

* [X] 9.4.1 latest supported release

## Affected browser
* [ ] Chrome
* [X] Firefox
* [X] Safari
* [ ] Internet Explorer
* [ ] Edge

**Comment by mitchelsellers** [comment]
@james7342 Thanks for reporting this, it is a false positive at the moment.  We will resolve it with 9.4.2

**Comment by mitchelsellers** [comment]
@valadas lets discuss this process as well as we work to finalize CI/CD

**Comment by valadas** [comment]
We where just chatting about this and came up with an idea to automate this process. We only need the checksums for the current version, so we could use the GitVersion build step to automate that process on the build.
