### ISSUE TITLE
Not able to use '_' (Underscore) while updating the password

### ISSUE THREAD

**Issue by tingung** [dnnsoftware/Dnn.Platform#3058]
## Description of bug
Changing the password with _ is not allowed when minRequiredNonalphanumericCharacters is set to "1"

## Steps to reproduce
List the steps to reproduce the behavior:
1. Edit web.config. Set minRequiredNonalphanumericCharacters="1"
2. Create a new user.  
3. Change the password of the new user to password with underscore. 

## Current result
Change password failed even the password contains _ (underscore) which is non alphanumeric character and meets the length requirement. 

## Expected result
'_' underscore should consider as non alphanumeric. 

## Screenshots
If applicable, provide screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/22523590/66053339-b9e82580-e564-11e9-9d97-8f0ca0f7c9c2.png)

## Error log
Paste the error log that is related to this issue.

## Additional context
Add any other context about the bug that may be helpful for resolution.
- The root cause of the issue is the regex expression to check non alphanumeric character is wrong. Glolabs::InvalidCharacters regex is  "[^A-Za-z0-9_-]" which consider both _ and - as alphanumeric. 
## Affected version

* [x] 10.0.0 nightly build
* [x] 9.4.1 nightly build
* [x] 9.4.0 latest supported release

## Affected browser

* [x] Chrome
* [x] Firefox
* [x] Safari
* [x] Internet Explorer
* [x] Edge

**Comment by valadas** [comment]
PR Merged
