### ISSUE TITLE
Tut / docs on how to build all the projects

### ISSUE THREAD

**Issue by kurtwilbies** [dnnsoftware/Dnn.Platform#3062]
I love to see a detailed paper on how to build the various components (.NET + React) into an 'install' asset. I also prefer VIDEO (YouTube). This would greatly empower the community. Please share your ideas ...

**Comment by mitchelsellers** [comment]
@kurtwilbies This is documented here: https://github.com/dnnsoftware/Dnn.Platform/blob/development/.github/BUILD.md

There is a SLIGHT change after last night, but the notes in that article will still work.

In the end it is a single command now.

**Comment by valadas** [comment]
We are also working next on improving the debug experience and will update the documentation when that improves, closing this issue for now since we already have that on our todo list.
