### ISSUE TITLE
Security Analyzer : Extra checks on host users

### ISSUE THREAD

**Issue by valadas** [dnnsoftware/Dnn.Platform#3070]
Moved here from https://github.com/DNNCommunity/DNN.SecurityAnalyzer/issues/15

Originally submitted by @Timo-Breumelhof and extra suggestion from @sleupold

1. Add a check for host with default credentials (probably out of scope now since there is no longer a default... New installations ask for a SuperUser user name and password)
2. Warning if there is a user account named **host**, the warning could suggest to use another username because host was previously very common for the SuperUser
3. Same as 2 but for the user name **admin**

**Comment by Timo-Breumelhof** [comment]
Still a valid change?

**Comment by sleupold** [comment]
IMO yes!
