### ISSUE TITLE
Security Analyzer : evaluate module header/footer

### ISSUE THREAD

**Issue by valadas** [dnnsoftware/Dnn.Platform#3071]
Moved from: https://github.com/DNNCommunity/DNN.SecurityAnalyzer/issues/20

Originally submitted by @moorecreative

We have many DNN instances, especially older 4x and 5x versions that have upgraded over time, where the Module Header/Footer has been used to wrap a module within a DIV or to place extra BR breaks after a module.

example:

TabId: 280, Module Id: 716
Header: <div style="height:200px; text-align:center;">
Footer: </div>< br />
These are harmless, intended uses of the module header/footer block of content but they show up as records in the Security Analyzer for review. And rightly so!

I wonder if there could be a slight enhancement to the way the module returns values here and either:

only returns if it finds certain potentially hack-used code such as: iframe, script, js, css, etc.
or, if it is best to have it return everything like it does now, to have it highlight in yellow any of the records which have those type of code elements within the content. That way, they're quick to see/find within the full list.
The other enhancement I would recommend is that the "TabID: 280, Module Id; 716" Be turned into a link that you can use to load that page of the site. Not only for efficient review/clicking, but mainly because it does not display which portal that module comes from, so in a multi portal DNN instance of 25+ portals, you're left guessing which that might be. Even though you'd likely make repairs directly in the database, it would be helpful to click and see the portal.

**Comment by mitchelsellers** [comment]
From a security standpoint, I do NOT recommend that we try to "analyze" the good/bad of an item, as ANYTHING could be a defacement, even stuff that looks not harmful.

However, I would agree that linking to the page would be a great feature add.

**Comment by valadas** [comment]
Closing this one in favour of #3073
