### ISSUE TITLE
If Site Import/Export fails, the status on the Import/Export pane does not update accordingly

### ISSUE THREAD

**Issue by OllyHodgson** [dnnsoftware/Dnn.Platform#3075]
## Description of bug
If the user submits a Site Import or Export and it fails for any reason, that failure is never reported back to the Site Import Export screen.

For example, if you're on an Azure installation and the server name has changed but the scheduled task still has the original server name in the Servers box it will fail. But the status on Site Import Export screen will remain as "Submitted" or "In Progress". It never goes to an "Error" state.

## Steps to reproduce
List the steps to reproduce the behavior:
1. Visit the Scheduler and edit the Site Import task
2. Put a non-existent server name into the Servers box and save your changes
3. Vist Settings > Import/Export and start a site export
4. Note that it appears on the ImportExport screen with a state of Submitted
5. Wait forever. Note that this never, ever changes

## Current result
If an error occurs, the user is not informed. 

## Expected result
If an error occurs, it should be reported on this screen, so that the user can see it.

## Screenshots
![image](https://user-images.githubusercontent.com/437224/49022078-ee909100-f18b-11e8-823c-5236bef174ce.png)

## Additional context
Related to https://github.com/dnnsoftware/Dnn.Platform/issues/2489

## Affected version

* [x] 9.2.2
* [ ] 9.2.1
* [ ] 9.2
* [ ] 9.1.1
* [ ] 9.1
* [ ] 9.0

I haven't tested older versions.

## Affected browser
n/a

**Comment by leedavi** [comment]
This was not 100% fixed on v9.4.1.  

I think this relates to a non existent server being assigned to the scheduler task.  This can happen when the website is moved from 1 server to another.  The original server is saved to the DB.

I've just had this issue with v9.4.1 and I cleared the DB using SQL and the scheduler then worked.

SQL below:  (Change the SchedulerID to the required id.)

  update [dbo].[Schedule] set Servers = null where ScheduleID = XXXX

**Comment by leedavi** [comment]
Don't close.

**Comment by leedavi** [comment]
Oh!!! sorry, I've jump to the wrong issue.   My thought is this could be turned to low priority.

**Comment by leedavi** [comment]
I don't have any reason to not close this apart from it is not fixed.
