### ISSUE TITLE
Add body css classes for PersonaBar and EditBar

### ISSUE THREAD

**Issue by valadas** [dnnsoftware/Dnn.Platform#3079]
## Description of problem
Currently, the persona bar, when present pushes the site body by 80px but does not add a class, it is an inline style. When the page is in edit mode, the .dnnEditState class gets added to the body. That is useful for skin and module developers to do different css if in edit mode or not. 

But, there is no difference when using any Dnn version, so if you have a module or something in the skin that is absolutelly positioned on the bottom, it may get hidden when opening the edit bar. One solution to this is to add some padding to that element if in edit mode (relying on .dnnEditState) but that also existed before the Editbar, so the content would then get that margin even if there is no editbar.

## Description of solution
The persona bar could add a .dnnPersonaBarVisible class and the stylesheet could do the push instead of having it inline.
The edit bar could add a .dnnEditBarOpen class to the body in addition to the .dnnEditState so that things can be styled differently depending if it is used on Dnn before or after 9.

## Description of alternatives considered
Some javascript could be used instead, but a css only solution would be nicer for designer and easier for developers.

## Additional context
I had this issue on a custom module that will be used on both Dnn8 and Dnn9, it shows a call to action on the lower right corner of the window. On Dnn 8, no issue since there is nothing on the bottom, on Dnn 9 the edit bar hides it. Changing the z-index would make that cover the close button. So I added a css rule to push it up if in edit mode. That is ok, but it also pushes it up on Dnn 8 which is not required.

## Affected version

* [x] 9.3.0 RC2
* [x] 9.2.2
* [x] 9.2.1
* [x] 9.2
* [x] 9.1.1
* [x] 9.1
* [x] 9.0

**Comment by sleupold** [comment]
IMO this is still an issue

**Comment by valadas** [comment]
Cool, reopened and triaged

**Comment by sleupold** [comment]
stll an issue
