### ISSUE TITLE
Sitemap priority 0 when adding a single page

### ISSUE THREAD

**Issue by valadas** [dnnsoftware/Dnn.Platform#3081]
@schotman commented on [Fri Mar 01 2019](https://github.com/dnnsoftware/Dnn.Platform/issues/2602)

## Description of bug
When using the add a new page function in the pages dialog the SiteMapPriority is not set in the dialog and defaults to 0 in the database

## Steps to reproduce
List the steps to reproduce the behavior:
1. Go to pages 
2. Click on add page
3. add pagename and
4. click the add page button

## Current result
SiteMapPriority = 0

## Expected result
SiteMapPriority defaults to 0.5 (as it is when you add multiple pages)

## Screenshots
seems clear

## Error log
no error

## Affected version
* [x] 9.2.2

## Affected browser
not dependant of browser

* [x] Chrome
* [x] Firefox

---

@sleupold commented on [Fri Mar 01 2019](https://github.com/dnnsoftware/Dnn.Platform/issues/2602#issuecomment-468612435)

IMO this should be fixed in DNN API code, not the database default value.

---

@Timo-Breumelhof commented on [Fri Mar 01 2019](https://github.com/dnnsoftware/Dnn.Platform/issues/2602#issuecomment-468627463)

@skamphuis 

---

@Timo-Breumelhof commented on [Fri Mar 01 2019](https://github.com/dnnsoftware/Dnn.Platform/issues/2602#issuecomment-468627882)

workaround:

UPDATE TABS SET SiteMapPriority = 0.5 WHERE TABID IN (SELECT   TabID
FROM     Tabs
WHERE   (PortalID = 0) AND (SiteMapPriority = 0) and (IsSystem = 0)) 

---

@schotman commented on [Fri Mar 01 2019](https://github.com/dnnsoftware/Dnn.Platform/issues/2602#issuecomment-468642932)

> IMO this should be fixed in DNN API code, not the database default value.

Yes, it should

**Comment by Timo-Breumelhof** [comment]
Still an issue in 9.8.0

**Comment by Tychodewaard** [comment]
I can imagine that this is difficult to fix in API. If it is easier to fix it (at least temporarely) in the database, that would do. To explain the magnitude of the issue:
There have been several major projects where people did everything right (meta tags, content, Google search console etc) But everything was useless because the sitemappriority is 0. Even when it says 0.5 in the UI.
