### ISSUE TITLE
Unable to Create Page After Emptying Recycle Bin for Page with Same Name

### ISSUE THREAD

**Issue by ahoefling** [dnnsoftware/Dnn.Platform#3082]
## Description of bug
When creating a new page, if it exists in the recycle bin after I clear the recycle bin and navigate back to the new page dialogue I need to force a full refresh to create the page.

## Steps to reproduce
List the steps to reproduce the behavior:
1. Log in as host admin
2. Navigate to Content Pages
3. Create new page called 'HelloWorld'
4. Save new page
5. Delete page (so it is in the recycle bin)
6. Create new page called 'HelloWorld'. An error should display warning you it exists in the recycle bin
7. Navigate to the Recycle Bin and delete 'HelloWorld'
8. Navigate back to Content->Pages and you should still be in the 'HelloWorld' page creation

## Current result
The 'Add Page' button is disabled and you are not able to save the page. To enable saving the page at this stage you have to make an additional edit to the page.

## Expected result
The 'Add Page' should be enabled if you follow the steps exactly as the old page is no longer in the recycle bin. 

## Screenshots
![image](https://user-images.githubusercontent.com/17751436/53932545-08355480-4068-11e9-8100-73bc41c60dfa.png)

## Error log
Not Applicable

## Additional context
Not Applicable

## Affected version
I have only tested this in version 9.2.0

* [x] 9.2

## Affected browser

* [x] Chrome
* [x] Firefox
* [ ] Safari (not tested)
* [ ] Internet Explorer (not tested)
* [x] Edge

**Comment by valadas** [comment]
I cannot reproduce in 9.6.2, if this is still an issue after upgrading, please comment again.
