### ISSUE TITLE
Bring back a Show Popups checkbox on site settings

### ISSUE THREAD

**Issue by valadas** [dnnsoftware/Dnn.Platform#3083]
## Description of problem
There is an option to show controls in popups or not in the database and code but this setting is not exposed in the UI.

## Description of solution
Add a checkbox named "Show Popups" in the site settings UI.

## Description of alternatives considered
Can be modified in database as explained here https://www.dnnsoftware.com/answers/tun-off-popups-in-dnn-9 and it works, we just need to expose it in the UI.

## Affected version

* [x[ 9.3.0 RC2
* [x] 9.2.2
* [x] 9.2.1
* [x] 9.2
* [x] 9.1.1
* [x] 9.1
* [x] 9.0

**Comment by leedavi** [comment]
I find it VERY surprising this feature hasn't found itself back into the UI before now!!!

This is a basic essential requirement for a lot of site.  The changing of the DB works for me, but it's not ideal for most of people.

**Comment by leedavi** [comment]
Just a thought for speed, but could this be done easier from "DNN Prompt" ?

I'm not sure I like my suggestion, because it opens excuses to not create UI.  And hence people will be told to always use prompt.   But the the speed gains form using prompt for this kind of thing might be good for quick progress.

**Comment by valadas** [comment]
I don't think it would take more or less time :) It is just one of those issues that people search for a workaround (sql) and it is just not picked up by contributors due to more difficult to workaround issues :)

**Comment by hismightiness** [comment]
Personally, I'd like instead to remove the popup setting paradigm entirely.  :)  It's the first thing we turn off on most new DNN instances.

**Comment by jeremy-farrance** [comment]
I don't mind the option staying, but at the very least **the default should be change to off** as soon as possible.

**Comment by david-poindexter** [comment]
The problem I see with getting rid of, or defaulting popups as disabled, is that tons of custom and third-party themes are not loading jQuery, but they need/use it.  Rather, they are relying on popups (without even realizing it in many cases) being turned on to ensure jQuery is loaded.  Thus, turning it off by default will break many sites.

**Comment by hismightiness** [comment]
It's a good point, even though we shouldn't need to account for this (and yet should).  From this perspective, it's a breaking change either way.  :(

**Comment by david-poindexter** [comment]
@hismightiness we applied the `Future: Major` milestone to this task for this reason, but I agree we shouldn't really have to account for this.  In the best interest of client sites though...it is what it is.  ;-)

**Comment by parasdaryanani** [comment]
It's shocking to learn that there are themes out there that blindly rely on DNN pop-ups to load jQuery for them...

**Comment by donker** [comment]
![Screenshot 2020-12-23 at 10 33 19](https://user-images.githubusercontent.com/3319692/102982329-a0851d80-450a-11eb-892b-825c9d965641.png)

**Comment by valadas** [comment]
This has been implemented
