### ISSUE TITLE
Switch to @babel/core package instead of babel-core

### ISSUE THREAD

**Issue by ohine** [dnnsoftware/Dnn.Platform#3087]
These [6 files](https://github.com/dnnsoftware/Dnn.AdminExperience/pull/925/files) should be looked at and updated to use @babel/core 7 package instead of babel-core. They changed namespaces when they moved to babel 7

_Originally posted by @mtrutledge in https://github.com/dnnsoftware/Dnn.AdminExperience/pull/925#issuecomment-490518081_

**Comment by david-poindexter** [comment]
This appears to still be an issue - see [these search results](https://github.com/dnnsoftware/Dnn.Platform/search?q=babel-core&unscoped_q=babel-core) - I just added the appropriate labels and moved this through the Issue Triage project.  Hopefully, we can get these updated soon.

**Comment by valadas** [comment]
Merged
