### ISSUE TITLE
security holding package

### ISSUE THREAD

**Issue by DanielRuf** [dnnsoftware/Dnn.Platform#3091]
Hi,

it seems you have accidentally added `fs` but this is not a package on npmjs, `fs` is an internal NodeJS module.

https://github.com/dnnsoftware/Dnn.AdminExperience/blob/development/Extensions/Content/Dnn.PersonaBar.Extensions/WebApps/Users.Web/src/_exportables/package.json#L30

See https://nodejs.org/api/fs.html

You might want to remove it using `npm uninstall fs`.

**Comment by valadas** [comment]
Merged
