### ISSUE TITLE
Remove Site Settings - Site Logo fails

### ISSUE THREAD

**Issue by valadas** [dnnsoftware/Dnn.Platform#3095]
@liffeyd commented on [Thu Aug 09 2018](https://github.com/dnnsoftware/Dnn.Platform/issues/2218)

## Description 
Attempting to remove the Site Settings > Site Logo fails

## Steps to reproduce

Fresh DNN 9.2.1 install
On PersonaBar select Site Settings, click left icon in Site Logo area. Area changes to two drop downs Folder and File. Select "None Specified" in File drop down. Press ENTER or click [ENTER]

## Current result
The logo should be removed but is not.

Click the Save button results in "Could not update settings. Please try later.

Fiddler shows:
POST /API/PersonaBar/SiteSettings/UpdatePortalSettings

JSON
-LogoFile
--fileID=(null)
--fileName=(null)
--folderPath=Images/

Fail
HTTP Result: 500 

## Expected result
The logo should be removed.

Adding a new logo works fine.
The logo should be updated and is updated as expected.

POST /API/PersonaBar/SiteSettings/UpdatePortalSettings

JSON
-LogoFile
--fileID=155
--fileName=logo.png
--folderPath=Images/

HTTP Result: 200
Success

## Affected version

ONLY 9.2 tested
* [x] 9.2
* [] 9.1.1
* [ ] 9.1
* [ ] 9.0

## Affected browser

Only tried browsers marked.

* [X ] Chrome
* [X ] Firefox
* [ ] Safari
* [ ] Internet Explorer
* [X ] Edge

**Comment by youngcaseho** [comment]
Which release branch should the fix for this issue target?

**Comment by sleupold** [comment]
please target release/9.4.x

**Comment by valadas** [comment]
Merged
