### ISSUE TITLE
Please restore "Replace Page From a Template" functionality

### ISSUE THREAD

**Issue by jncraig** [dnnsoftware/Dnn.Platform#3101]
## Description of problem
In DNN 8 this was an option under the Pages admin menu.  It allowed you to replace an existing page using a template.  I think that this has disappeared in DNN 9.  I wasn't able to find it in DNN 9.2.1.

## Description of solution
I'd like the old functionality to return

## Description of alternatives considered
Can always delete a page and re-create it from a template, but that doesn't include all of the possibilities available before.  And, the old way was very easy to do.

## Additional context
Old functionality

## Affected version

* [x] 9.2.2
* [x] 9.2.1
* [x] 9.2
* [x] 9.1.1
* [x] 9.1
* [x] 9.0

## Affected browser
It's not a browser issue.

* [ ] Chrome
* [ ] Firefox
* [ ] Safari
* [ ] Internet Explorer
* [ ] Edge

**Comment by adam-j-mclellan** [comment]
Our client relied on this functionality to move pages between environments. I suspect many others did as well. Sadly, we didn't realize it was gone until after we upgraded! 😓

**Comment by jncraig** [comment]
This is still an issue that deserves some work.
