### ISSUE TITLE
Recycle Bin - Sorting by any column

### ISSUE THREAD

**Issue by Marco-Envision** [dnnsoftware/Dnn.Platform#3105]
## Description of problem
We run into many issues with folks deleting content and us not being able to see what else was deleted at that given time period.

## Description of solution
Provide a deleted date column in the recycle bin. 

## Description of alternatives considered
- None that we can tell, aside from manually looking through recycle bin and seeing what other content was on that page and then figuring out whether it was deleted in error or before-hand on purpose. 

## Screenshots
- Clear-cut, no screenshots needed. 

## Additional context
- Clear-cut, none needed. 

## Affected version

* [ ] 9.3.0
* [x] 9.2.2
* [x] 9.2.1
* [x] 9.2
* [x] 9.1.1
* [ ] 9.1
* [ ] 9.0

## Affected browser

* [x ] Chrome
* [x ] Firefox
* [x ] Safari
* [x ] Internet Explorer
* [x ] Edge

**Comment by sleupold** [comment]
although sorting might be useful, we should not add paging (especially in the database). Users should no abuse the recycle bin as a store for elements, they might need back in the future. This might affect performance.

**Comment by valadas** [comment]
Why would paging affect performance? This would not be something hammered by tons of concurrent requests, mainly just admins wanting to filter/sort cleanup items they can safely delete no? Ultimately it would help cleaning up... Right now you can't even see everything and you often just have to resort to empty the whole bin.

**Comment by Marco-Envision** [comment]
Agreed Valadas, it would mean we automatically use this as a large dumping ground for old content, it would be more useful for me to address an issue where a client deleted multiple pieces of content and I need to restore all things deleted in that time period and not miss something. But I understand we don't want this not being emptied for huge amounts of time.

**Comment by sleupold** [comment]
I was just talking about paging in the database requests

**Comment by valadas** [comment]
I was thinking about using what is in place in the core API to get pages (because it is cached) then in the webapi we do the paging and return x results with a count and the frontend can then request next pages based on what it already has and the count. Sounds good?

**Comment by sleupold** [comment]
@valadas
that sound fine and shoud work well for the smaller number of items expected.

**Comment by sleupold** [comment]
IMO, this is still a desired feature.

**Comment by sleupold** [comment]
IMO, this is still a desired feature.

**Comment by EPTamminga** [comment]
Still an issue
