### ISSUE TITLE
Portal alias settings not available in multisite

### ISSUE THREAD

**Issue by Tychodewaard** [dnnsoftware/Dnn.Platform#3107]
## Description of bug
If you have multiple sties within 1 DNN host, you can not access site alias settings of other sites than the one you're in.

## Steps to reproduce
List the steps to reproduce the behavior:
1. Have more than 1 site
2. Login as host in portal 0
3. Manage - sites
4. Try to add an alias to another site than the one, you're logged in. 
I think the second or third icon should give access to functionality like site aliasses and import / export but neither of the buttons work.

## Expected result
Provide a clear and concise description of what you expected to happen.

## Error log
Paste the error log that is related to this issue.

## Additional context
Add any other context about the bug that may be helpful for resolution.

## Affected version
* [x] 9.2.2

## Affected browser
* [ ] Chrome
* [ ] Edge
Other versions not tested

**Comment by valadas** [comment]
I can no longer reproduce in 9.6.2, if it is still an issue after upgrade, please comment again
