### ISSUE TITLE
Update alert to refer to "Admin Logs" vs "Event Viewer"

### ISSUE THREAD

**Issue by moorecreative** [dnnsoftware/Dnn.Platform#3108]
## Description of Problem
Within the updated DNN 9x Persona Bar Menu, the previously called "Event Viewer" is now found under a menu item called "Admin Logs". The alerts within error actions, however, still display the message, "A critical error has occurred. Please check the Event Viewer for further details."

## Proposed Solution
Consider rephrasing the text to read "A critical error has occurred. Please check the Admin Logs for further details."

## Affected version

* [x] 9.3.2
* [x] 9.3.1
* [x] 9.2.2
* [x] 9.2.1
* [x] 9.2
* [x] 9.1.1
* [x ] 9.1
* [x ] 9.0

**Comment by sleupold** [comment]
IMO we shoud restore the old Name, there are other logs for admins (like install and upgrade logs) located in different menu items.

**Comment by valadas** [comment]
I don't disagree but I think if we re-change the name we will have a lot of documentation to rewrite and introduce again more confusion.

**Comment by valadas** [comment]
Merged
