### ISSUE TITLE
Permissions are missing when copying modules between different localizations

### ISSUE THREAD

**Issue by mikebigun** [dnnsoftware/Dnn.Platform#3122]
## Description of bug
When copying modules between different localization's it does not make permissions copied.  

## Steps to reproduce
1. Login as super user
2. Add multiple languages, mark all pages as translatable 
3. Add HTML Pro module to any page
4. Go to `Module Settings` -> `Permissions` -> add new role with a view permission (i.e. Community Manager role)
5. Go to current `Page Settings` -> `Localization Tab`
6. Mark `Copy Module` checkbox
7. Click on `Update Localization`

## Current result
Go to translated version of the page and go to module settings -> permissions. Role that was added for original version of module has not been copied to its translated version. 

## Expected result
Permissions should be also copied when copying modules between different localization's.

## Screenshots

![image](https://user-images.githubusercontent.com/22524011/66313199-81986c80-e901-11e9-86a4-19b2ffe90d57.png)

## Affected version

* [x] 10.0.0 nightly build
* [x] 9.4.1 nightly build
* [x] 9.4.0 latest supported release

**Comment by mikebigun** [comment]
@mitchelsellers @valadas @bdukes 

Dear community, let me know please if you see any problems or risks to have permissions copied.

**Comment by sleupold** [comment]
how do we handle permissions for the special "Translators" roles? A translator should b granted permission to his language only (unless granted by a differnt role or individually).

**Comment by mikebigun** [comment]
Right, for the special "Translators" there is a host setting `DefaultTranslatorRoles-{culture}` with a list of roles which we want to add automatically when module is localized to a particular locale. By default we add `Administrators` and `TranslatorRole-{culture}`. 

But still it is not clear if I assigned i.e. `Moderators` and granted them view permissions for my original module. Then I copied module to another locale and found Moderators role is missing there.
So, is this expected behavior? Do we expect users to re-add missing roles manually to a newly copied modules? Or do we expect them to include roles to a `DefaultTranslatorRoles-{culture}` host setting to add them automatically on localization?

To me, this looks like we need to copy all roles from a source module, including `Moderators` (in my case). On top of that, "Translators" will be added.

**Comment by sleupold** [comment]
I would expect, other permissions should be copied as well (except for any translators role) and respective translator role for new language being added explicitely.
Instead of the template, I would prefer the actual translator role being stored in PortalLanguages or PortalLocalization table (new column translatorRoleID int Null)

**Comment by valadas** [comment]
Fixed by #3162
