### ISSUE TITLE
Custom registration issue

### ISSUE THREAD

**Issue by markandcurry** [dnnsoftware/Dnn.Platform#3130]
## Summary
Custom registration field blocks registration

## Extended description
I've added an additional custom field to registration, but when I try to register it doesn't go through. The console gives me this error:
Uncaught Sys.WebForms.PageRequestManagerServerErrorException: Sys.WebForms.PageRequestManagerServerErrorException: Object reference not set to an instance of an object.

## Steps to reproduce (if necessary)
List the steps to reproduce the behavior:
1. Add reg field
2. Attempt to register

## Current result (if necessary)
Registration not processing

## Expected result (if necessary)
Registration process

## Error log (if necessary)
Uncaught Sys.WebForms.PageRequestManagerServerErrorException: Sys.WebForms.PageRequestManagerServerErrorException: Object reference not set to an instance of an object.

## Additional context
Add any other context that may be helpful.

## Affected version
9.2.1

* [ ] 10.0.0 nightly build
* [ ] 9.4.1 nightly build
* [ ] 9.4.0 latest supported release

## Affected browser

* [x] Chrome
* [ ] Firefox
* [ ] Safari
* [ ] Internet Explorer
* [ ] Edge

**Comment by valadas** [comment]
@markandcurry we need a few more details to make this actionable as it will be hard to reproduce without those details.

First thing first, I would advice to update Dnn and check if the issue is maybe already resolved, a lot has changed from 9.2.1 to now.

Then can you add detailed steps to make the issue happen, the field name, the type of field, etc.

Thanks

**Comment by sleupold** [comment]
please specify also, how the registration form is built. are you just using default or a custom list of properties?

**Comment by markandcurry** [comment]
Hi Guys,

Thanks for your response. This was using the default with one custom field (list). Just as @valadas recommended, updating the version of DNN solved the problem. Regards, Mark
