### ISSUE TITLE
Login and registration pages selection in site settings does not take localization in mind

### ISSUE THREAD

**Issue by eXistenZe** [dnnsoftware/Dnn.Platform#3133]
## Description of bug
In site settings, when we select the pages for login and registration, we can only select one page for all languages.

## Current result
When using the skin objects, it will link to that language, no matter what your current selected language is.

## Affected version
* [X ] 9.3.2

**Comment by valadas** [comment]
I cannot reproduce in 9.4.1, I would suggest starting with updating and opening a new issue with more steps to reproduce if it is still the case in current version.

Things to note:
That list of pages goes by the selected language in the persona bar corner and will only show pages that have a login module on them (or registration depending which dropdown).

**Comment by eXistenZe** [comment]
Sorry. I'll try separating this into smaller and clear issues.
I can't test 9.4.1 right now  until 2sxc is fixed for dynamic apis.

**Comment by sleupold** [comment]
I haven't noticed this issue in DNN 9.3.2
Please make sure, you switch to each anguage and set the pages appropriately.
