### ISSUE TITLE
Multi Language URL Handling

### ISSUE THREAD

**Issue by ehsanshahrokhabadi** [dnnsoftware/Dnn.Platform#3135]
## Description of bug
We Can't Make a Simple Url For 3 or 4 Languages
For Example 
domain.com/en-us/contactus
domain.com/fa-ir/contactus
domain.com/ar-ae/contactus
 
It's so easy to test

just do it and see the result in Table TabUrls

![7](https://user-images.githubusercontent.com/24796341/66503940-08517300-ead5-11e9-9b27-bf0a52fd173a.png)

**Comment by valadas** [comment]
Actually, can you elaborate, from a quick look, it does not look like you have localization enabled. How did you manage to get multiple tabs with the same url and same culture?
