### ISSUE TITLE
prefilled tag in search result

### ISSUE THREAD

**Issue by Tychodewaard** [dnnsoftware/Dnn.Platform#3138]
Currently there is no out-of-the-box solution to display a list of links to articles with a certain tag.

## Description of solution
Extend the search results module with a field 'prefilled tag' and a text field.
The results list should be populated like http://sitname/Search-Results?Search=[prefill]

The functionality of search results by tags already exists, so this would seem a small feature with great benefits...

## Description of alternatives considered
Build a seperate module that pulls data from database etc. But that sounds way to complex and we don't need that...

**Comment by valadas** [comment]
This would need to be on the specific module level, I have created custom search items for ecommerce modules, the system supports creating your own search categories per module, but this would be something that articles module would need to implement. If I did not understand the issue correctly feel free to comment with more details...

**Comment by Tychodewaard** [comment]
Ok, I'll try to explain in a different way.
1. The aim is to create pages with links that are related to a certain topic. In this case 'Brexit'. Of course, there is an option to add a link module but that would be handwork and not desirable. 
2. An easy solution is to use tags. The editor can create a vocabulary and add the tags to pages or modules. A way to have a page with links related to brexit would be http://dnndemo.tjeps.com/Search-Results?tag=brexit 
So, just a page with a search results module where a predefined tag is added to the url. 
3. Now, for editors to have control, they would need a field that allows them to add a tag.
![image](https://user-images.githubusercontent.com/9091997/69136715-a3b60a80-0abb-11ea-8de8-90ba7e464437.png)

The change would only be in the search results module. 

Does this clarify things?

**Comment by zyhfish** [comment]
this can be done by adding some rewrite rules, for example:
1. you create a page /search/pages, and put the search results module on the page;
2. add some rewrite rules in web.config, to redirect the requests such as:
    /search/pages/{tag}-> /search/pages?tag={tag}

then when request /search/pages/brexit, it will display the search result module with tag "brexit" defined, it will only display results which have the tag.  for rewrite rules, you can reference to https://docs.microsoft.com/en-us/iis/extensions/url-rewrite-module/creating-rewrite-rules-for-the-url-rewrite-module to get more information.

**Comment by Tychodewaard** [comment]
I guess that could work... But I rather won't have to hand over the keys to the web.config to editors...

BTW: working with the editor in mind, I tried to create a 'page' that redirects to the same page with ?tag={tag} but the results in 'too manu redirections. Which makes sense of course.

**Comment by zyhfish** [comment]
you don't have to list all the keys in web.config, the {tag} can be an expression to match all the keys, so one rule should be good enough to redirect all the keys.

**Comment by Tychodewaard** [comment]
@zyhfish as I am not as familiar with these kind of expressions, could you help out?
The default page of the search results is /Search-Results
So, how would the code snippet look like in the web.config?
Just: 
<rewrite>
  <rules>
    <rule name="Rewrite to tagged search results">
      <match url="/search-results/{tag}" />
      <action type="Rewrite" url=/search-results?tag={tag}" />
    </rule>
  </rules>
</rewrite>

??
I bet there is more to it :-)
