### ISSUE TITLE
Create User Error when Password Question enabled within Web.Config

### ISSUE THREAD

**Issue by moorecreative** [dnnsoftware/Dnn.Platform#3141]
## Description of bug
When the PasswordQuestion field is enabled within the web.config, neither the Admin nor Host level user can create a new user account within the persona bar Users screen. The simple set of initial questions for creating the user account do not include the PasswordQuestion or PasswordQuestionAnswer fields and therefore the saving action displays an error message "The question specified is invalid. Please specify a valid question."

## Steps to reproduce
List the steps to reproduce the behavior:
1. Within the web.config, set the value for the AspNetSqlMembershipProvider to include requiresQuestionAndAnswer="true" 
2. restart the DNN instance
3. Ensure that you are showing the core DNN user registration, confirm that the form shows the PasswordQuestion and PasswordAnswer as required fields. This shows that the user can create this themselves
4. As an Admin, load the persona bar Users screen and attempt to create a new user
5. The user error message / alert will appear when clicking to save

## Current result
Admin cannot create a new user because they cannot specify or avoid specifying a Password Question

## Expected result
There are other issues here... previous posts around the topic:
https://www.dnnsoftware.com/forums/threadid/522217/scope/posts/how-to-reset-user-39s-password-answer
have talked about the Admin user being able to see and/or change the person's answer too... 
I would say that the expected result would be that the Admin could create a question and answer for the user just as they can set a password for the user.

## Error log
There is no error generated within the Event Viewer / Log because the validation stops the admin from creating a record.

## Affected version

* [ ] 10.0.0 nightly build
* [ ] 9.4.1 nightly build
* [ ] 9.4.0 latest supported release
* [X] 9.3.0 latest supported release

**Comment by valadas** [comment]
this appears to work fine in 9.6.2, closing the issue.

![image](https://user-images.githubusercontent.com/6371568/88739181-eda1c680-d107-11ea-9075-6f6980ad86c8.png)
