### ISSUE TITLE
.Net Framework 4.8 DataCache bug

### ISSUE THREAD

**Issue by thienvc** [dnnsoftware/Dnn.Platform#3143]
After upgrade windows 10, and upgrade .Net Framework to 4.8, DNN auto clear cache alway when user logged on.
I find https://github.com/microsoft/dotnet-framework-early-access/issues/61

**Comment by valadas** [comment]
Soooo, is there something to do in this codebase?

**Comment by mitchelsellers** [comment]
Looking at this, it is a Windows 10 bug, that has a fix with a future update or feature installation, and not something that we can address within the DNN Platform.

If there is a specific DNN Platform item that needs to be addressed, please update this issue with details and we can reopen.
