### ISSUE TITLE
Update Dependency Injection Library to 3.0.0

### ISSUE THREAD

**Issue by ahoefling** [dnnsoftware/Dnn.Platform#3145]
## Description of bug
The AspNetCore Dependency Injection library we added for 9.4.0 is at version 2.1.1. With the release of AspNetCore 3.0 this has been upgraded to 3.0.0. We should update this to the latest version for 10.x of DNN

## Screenshots
N/A

## Error log
N/A

## Additional context
I don't believe there are any breaking changes, but since there have been many issues being created around this space since 9.4.0 I think it would be best to merge this into the `development` branch targeting the 10.0 release

## Affected version

* [x] 10.0.0 nightly build
* [ ] 9.4.1 nightly build
* [ ] 9.4.0 latest supported release

## Affected browser
N/A

**Comment by mitchelsellers** [comment]
Although technically I would agree that it would be better to wait until 10.x, there is a question regarding support.

Technically .NET Core 2.2.0 becomes end of life per Microsoft Support Policy on 12/23/2019.

For this reason, I believe it should target 9.4.x for inclusion in 9.4.2.

**Comment by ahoefling** [comment]
I made a mistake we are actually on 2.1.1, I have updated the documentation at the top

@mitchelsellers 
Once we work through the PR for #3147 I can submit a follow up PR that just updates the DI libs since that PR contains some additional changes related to TargetFrameworks and project cleanup
