### ISSUE TITLE
Page Header Tags issue when no HTML element is used

### ISSUE THREAD

**Issue by Timo-Breumelhof** [dnnsoftware/Dnn.Platform#3148]
## Description of Problem
I recently had one page on a site that had a strange extra distance somewhere in the page. (fixed header offset actually). After a long search I found that the admin had added tags to the "Page Header Tags".
But only text noting else, apparently he misunderstood the term "tags". 
This meant that plain text was injected in the head, which lead to the rendering issue.

## Proposed Solution Option 1
I suggest to add a regex validator to the input filed to make sure anything inserted is valid.?

## Proposed Solution Option 2 (If Needed, repeat for more)
Strip out all content that's not inside an html element on render?

## Alternatives Researched
Documentation of any other items researched for resolution.

## Affected version

* [ ] 10.0.0 nightly build
* [x] 9.4.1 nightly build
* [x] 9.4.0 latest supported release

**Comment by Timo-Breumelhof** [comment]
...

**Comment by valadas** [comment]
To prevent stalebot to keep closing this since nobody picked up this feature-request yet, I am moving this to the feature-request discussions.

Thanks.
