### ISSUE TITLE
[RFC] Updates to gitignore

### ISSUE THREAD

**Issue by ahoefling** [dnnsoftware/Dnn.Platform#3149]
## Description of Problem
When working on a platform change to DNN an execution of the build generates updates to all of the DNN manifest files throughout the solution. When you go to commit changes this adds A LOT of noise to your pending changes. This amount of noise adds unnecessary confusion to a first time contributor on what is important to commit and what is not.

![image](https://user-images.githubusercontent.com/17751436/66846242-88e1fa80-ef3f-11e9-92b5-aeca02e51a4d.png)

## Proposed Solution Option 1
If we add the `.dnn` extension to the gitignore file they will no longer show up in the pending changes commit history. The currently committed files will remain and we can still make changes to it. If we need to update a file that is ignored there is a git command to force it.

The trade-off here is these files need to be in source control, but ignoring them simplifies normal contributor workflows. It makes more advanced scenarios harder since the contributor will need to force add it.

My List of Items to Ignore:
- `.dnn` DNN Manifest Files
- `SolutionInfo.cs`

## Proposed Solution Option 2 (If Needed, repeat for more)
I'm not sure of an alternative to this, and would love to hear what other people think we can do to make the first-time contributor workflow easier

## Alternatives Researched
N/A

## Affected version

* [x] 10.0.0 nightly build
* [x] 9.4.1 nightly build
* [x] 9.4.0 latest supported release

**Comment by bdukes** [comment]
I believe #3137 addresses this issue (by backing up and automatically restoring the manifest files after the build)

**Comment by ahoefling** [comment]
Didn't realize that was going to take care of this, I'll close this RFC then.

Thanks
