### ISSUE TITLE
bring the code in SiteAnalytics.config up to date

### ISSUE THREAD

**Issue by dieterdtx** [dnnsoftware/Dnn.Platform#3155]
## Description of problem
The GA code in SiteAnalytics.config is using ga.js, which is Legacy code.
https://developers.google.com/analytics/devguides/collection/gajs

## Description of solution (edited on 21 oct, input David Poindexter)
Change the code to analytics.js
https://developers.google.com/analytics/devguides/collection/analyticsjs

## Additional context (edited to new solution)
It would perhaps be useful to also include 'anonymize_ip' as a default setting, as this is suggested for GDPR compliance by "various" sources. Feel free to scout around for validness of this suggestion.
https://developers.google.com/analytics/devguides/collection/analyticsjs/ip-anonymization

**Comment by EPTamminga** [comment]
This to be a good enhancement for a GA default.
Any Google Analytics specialists around who can comment?

**Comment by david-poindexter** [comment]
Google Analytics (GA) and Google Tag Manager (GTM) are two separate methods.  The newer version of GA is actually documented [HERE](https://developers.google.com/analytics/devguides/collection/analyticsjs/).

**Comment by dieterdtx** [comment]
@david-poindexter You're absolutely right, I even have used that one, I'm not sure why I so blindly took the wrong script, my fault.

I will edit my original post.

**Comment by dieterdtx** [comment]
It appears my original post wasn't so wrong after all...
https://developers.google.com/analytics/devguides/collection/gtagjs/migration

**Comment by EPTamminga** [comment]
@dieterdtx If I understand this correctly, it is possible to replace the GA code with the gtag code and specify to measure Page Views?

**Comment by dieterdtx** [comment]
@EPTamminga That's how I am reading it. As I see it gtag is more prepared to use for other features but can track simple page views just as well.

**Comment by david-poindexter** [comment]
End the end, there are several ways to implement Google Analytics or Google Tag Manager.  We need to make clear distinctions between these methods.  We also need to take into consideration some of the differences in privacy, especially as it relates to GDPR.  My vote would be to provide multiple connectors  (one for each implementation method) or update the one we have to give the admin a choice as to which method they prefer to use.  CC @mikesmeltzer (what are your thoughts on this?)

**Comment by bdukes** [comment]
I agree, in general, with @david-poindexter, but think it would end up being confusing to have multiple GA connectors.  I think adding options to the GA connector would be an easier experience for the administrator, and then having a second connector for GTM would be provide an easier choice to consider.

**Comment by david-poindexter** [comment]
I would lean on towards this approach as well @bdukes - much clearer to the admin.

**Comment by mikesmeltzer** [comment]
We could simplify this even further and future proof ourselves by building a really basic implementation that wasn't a GA or GTM connector but simply a Universal Analytics Connector. 

Behind the scenes it could be virtually identical to what we have today just without pulling from the file and from a Portal Setting (this would prevent the current issue of all portals doing the same thing). 

It could have simply a multi-line textbox that lets you put the code that you want. 

I'm thinking from a pragmatic standpoint that this would satisfy a lot use cases, be a minimal feature to add and stop the various workarounds of manually editing files, etc.

Thoughts?

**Comment by bdukes** [comment]
I like this approach (one caution I considered mentioning with the other approach is making sure we continue to allow customizing the script).

My only concern is that, for instance, Google Tag Manager requests that you add a script block to the head and a `<noscript>` to the body.  Would we want to introduce the complexity of having multiple inputs that can be injected into multiple places within the markup of the site?

**Comment by mikesmeltzer** [comment]
Good point, Brian. There would have to be a fine balance on that as you wouldn't want scope to creep which I could see happening easily. Two fields, InjectInBody and InjectInHeader, would work but you are opening up the door to misuse (which I believe the SiteAnalytics.config is misused today too) by potentially having non-analytics things injected.

If we are looking at the ability to change between Google codes, etc. then we are probably getting into modifying the SiteAnalytics.config file, etc. in code (in the current state) which may open up other challenges like potentially over writing someones custom modifications, etc. unless we change the way it's built or do some tricky business.

Some food for thought... Are we even aware of any extensions (commercial or OSS) that implement a site analytics engine bedsides the Platform itself? I've never come across one, could be an opportunity to deprecate that functionality and do it a bit differently.

I'm not sure where the "happy spot" is. If we continue to include Google specific snippets in the Platform then we need a solution to keep them up to date and something that gives a tracking code that works for as many as possible (there is lots of GA questions on DNN online, people wanting to add specific things, etc..) vs. just giving someone the ability to add whatever code they want from a central location.

My believe is that the user is going to log into GA/GTM anyway to get their tracking ID which is usually in the same screen (or very close) as the complete tracking snippet they tell you to inject in your site.. 

Other thoughts?

**Comment by thenotandy** [comment]
This is the modified file that I am currently using for GTM. It works well, so far. https://pastebin.com/e8qqBnVg

**Comment by Tychodewaard** [comment]
@skamphuis and I created a GTM connector (David already linked). Use cases for me:
1. DNN instance that supports GA on portal 1 and supports GTM on portal 2. 
2. The snippet has multiple parts so you can  not just add it in the site settings like Hotjar. My customers need something really simple like just pasting the GTM-code not the entire snippet
3. If people search for GTM, they will type 'GTM'. Not 'GA with option to behave like GTM' :-) So, it is marketing for DNN as well.  

Now for the versions of the snippet.
What if we load a stable/current/suppoorted version but we offer to  change that? I know it might be quite a bit of work but this way we offer a version that works but allow innovators to use newer versions.
![image](https://user-images.githubusercontent.com/9091997/97467022-0e1a3080-1944-11eb-92e4-b097401a0478.png)
