### ISSUE TITLE
class & span not being saved in HTML module

### ISSUE THREAD

**Issue by cmdigitaluk** [dnnsoftware/Dnn.Platform#3156]
## Description of bug
I tried to add a class to a h2 tag and also add a span within a p tag. When I saved the HTML Module it seemed to save correctly but when I went back into the HTML Module I couldn't see the h2 class or the span. When I inspected the code using DevTools the h2 class and the span were visible. However when I went into the HTML module again to edit the text and saved the code 

## Expected result
span and classes should be saved in the HTML Module

## Screenshots
![Bug1](https://user-images.githubusercontent.com/56639615/66923148-3298b880-f020-11e9-893e-1d70fd4f711d.png)
![Bug2](https://user-images.githubusercontent.com/56639615/66923147-3298b880-f020-11e9-8a49-faf18f2a3878.png)
![Bug3](https://user-images.githubusercontent.com/56639615/66923151-33314f00-f020-11e9-9c0b-b3bb6ba15585.png)
![Bug4](https://user-images.githubusercontent.com/56639615/66923150-33314f00-f020-11e9-97ee-5452105e81c6.png)
![Bug5](https://user-images.githubusercontent.com/56639615/66923149-33314f00-f020-11e9-9c36-5597ba262f8a.png)

## Error log
Paste the error log that is related to this issue.

## Additional context
Add any other context about the bug that may be helpful for resolution.

## Affected version

* [ x] 9.4.1 - showed as latest version

## Affected browser

* [x ] Chrome
* [ ] Firefox
* [ ] Safari
* [ ] Internet Explorer
* [ ] Edge
Windows

**Comment by valadas** [comment]
This is not something we can fix in this repository @cmdigitaluk 
This would depend on the actual html editor provider, if you are using the default CkEditor provider, the correct repository to create this issues would be at https://github.com/DNN-Connect/CKEditorProvider

Thanks.
