### ISSUE TITLE
Registration: Users are unable to register when Display Name Format setting is set

### ISSUE THREAD

**Issue by KrystofZeman** [dnnsoftware/Dnn.Platform#3157]
## Description of bug
When user tries to register, they receive error: "The Display Name is invalid."

## Steps to reproduce
1. In the Registration Settings (PersonaBar: Settings -> Security -> Member Accounts -> Registration Settings) set **Display Name Format** field to [FIRSTNAME] [LASTNAME]
2. Log out
3. Click on Register link.
3. Try to register as different user
4. You will receive error: "The Display Name is invalid."

## Current result
So problem is, that users can not register themselves on the web, when Display Name Format setting is set. No matter what setting is Registration Form Type (Standard or Custom).
Workaround is to show Display name in registration form and clear Display Name Format setting, but it is a bit user aggressive.

## Expected result
Provide a clear and concise description of what you expected to happen.

## Screenshots
![image](https://user-images.githubusercontent.com/56371600/66947260-def39280-f052-11e9-9c79-1f1ddb639c31.png)

## Additional context
I also noticed that when the registration form type is set to Custom the setting Use Email Address as Username disappear, but affects the system. I would expect Email Address as Username  setting to be visible no matter what registration form type.

## Affected version
This problem occurs after upgrade to 9.4.1 release version.

**Comment by hamed743** [comment]
+1

**Comment by thabaum** [comment]
I am having a hard time making my settings save like this in 9.4.2 beta.  I keep getting a red error in the registration fields.

I did verify that the Email Address as username disappears and by your settings maybe your site is set with this on to help reproduce.  Mine is currently set like this on one portal.  I will check another soon.

**Comment by daguiler** [comment]
I can confirm this happens also when you don't include `DisplayName` in the custom registration form. Apparently it is not being derived from FirstName LastName anymore? And I can also confirm this didn't happen on 9.3.2.

**Comment by james7342** [comment]
Just ran into this issue today with a user trying to create a account with 9.4.4. I've attached a image of my my site settings. I can confirm this is happen on my production and test/dev site.

![screenshot_1099](https://user-images.githubusercontent.com/27960723/71771286-80211500-2eed-11ea-9812-a2b415a791df.png)

**Comment by Navilois** [comment]
Is there any update or even fix on this? I was unaware of this bug and recently upgraded to 9.4.4 - this is a major issue for my site and I'm not happy with the workaround.

**Comment by valadas** [comment]
Unfortunately no pull request was submitted for it yet.

**Comment by SCullman** [comment]
Anyone aware of which change broke the feature? Is anyone working on this issue already?

**Comment by kingjordan** [comment]
exact same error on my site too.  I had a custom list of fields for my registration form and had to add display name so that users can now register for my site again.

**Comment by Navilois** [comment]
Thank you @SCullman!
