### ISSUE TITLE
Default home page out-of-the-box install gives wrong impression

### ISSUE THREAD

**Issue by EPTamminga** [dnnsoftware/Dnn.Platform#3163]
## Description of problem
When you install DNN with a default template, you get a home page that moves you in a wrong direction: all links point to DNNSoftware.com, there is no clear instruction what to do next, there is no link to the extension overview, there is no link to the DNN Docs site, etc.

## Description of solution
A new default home page.

## Description of alternatives considered
Change links; a completely new template; multiple templates

## Screenshots
![image](https://user-images.githubusercontent.com/5859855/67092372-53dbdf00-f1af-11e9-9b32-44eb80ec2f60.png)
.

## Additional context
A new template should be made available in other languages as well

## Affected browser

* [x] Chrome
* [x] Firefox
* [x] Safari
* [x] Internet Explorer
* [x] Edge

## Affected DNN Versions

* [x] DNN941 and earlier

**Comment by ahoefling** [comment]
I agree 100% the community edition should be community focus and the current template is more focused towards evoq. As a path of least resistance maybe we can identify the new links that should be listed and update it accordingly. Creating a new theme may be a lot to do:

- DNN Docs
- DNN Community Site
  - Forums
  - Blogs
  - Resources
- GitHub Page
- Maybe have links to DNN Community Extensions on GitHub. I believe @david-poindexter worked on an algorithm for nvQuickPulse that returns all repos that have `Dnn` and `DotNetNuke` in the tags or readme

I'm in support of multiple themes, but I'm a fan of taking small steps first to resolve the misguided messaging that exists today

**Comment by EPTamminga** [comment]
Small steps indeed. If we have about 8 new images and links to the community site and the docs site, we make a big step forward.
The default site template should be a available in a DNNPlatform repo

**Comment by kurtwilbies** [comment]
Besides that, the frontpage look like something from the '90 (1994 beginning of internet v2). Can somebody design  something ...

**Comment by mitchelsellers** [comment]
FYI - The default template is in this repo

**Comment by bdukes** [comment]
See https://github.com/dnnsoftware/Dnn.Platform/blob/685071420b39283763dd3b0c008cc685f8c6588d/DNN%20Platform/Website/Templates/Default%20Website.template#L553-L600 and other files in https://github.com/dnnsoftware/Dnn.Platform/tree/v9.4.1/DNN%20Platform/Website/Templates

**Comment by david-poindexter** [comment]
Is anyone actively working on a pull request to address this?  If not, this is probably something I can sink my teeth into.

**Comment by EPTamminga** [comment]
@bdukes @mitchelsellers Only the en-US template versions are in the repo. Not the other standard 

@david-poindexter AFAIK, no one is working on this. I am happy to test and work together to get a better version...

**Comment by ahoefling** [comment]
The first Pull Request for this should be content focused, and perhaps getting localized content as @EPTamminga pointed out the repo only contains the en-US template.

@david-poindexter if you need any help let me know

**Comment by sleupold** [comment]
please be aware that this affects translated templates as well, AFAIR atm there is a special format for resource files to translate site templates.

**Comment by david-poindexter** [comment]
Okay, I am a bit confused now as to whether or not additional research, acquisition of tooling, location of non en-US versions of the template, etc. are needed prior to moving forward.  Can someone please advise prior to any work on this?

**Comment by EPTamminga** [comment]
For me: Just make a new EN-US version. Of that is ready, we will find a way to create versions for other languages. 
Having at least 1 up to date version asap would be a real step forward.

**Comment by valadas** [comment]
If we create a branch for this and you let me know when the english one is final, I am volunteering to do the french version. I am sure we can get people in the community to translate the other languages and when we have them all, we merge that whole branch...

**Comment by EPTamminga** [comment]
@david-poindexter : If you need any help for the new en-US version, just ping me. I can do the nl-NL version when the en-US version is ready.

**Comment by EPTamminga** [comment]
@david-poindexter : How about using nvQuickTheme to create an additional theme package to be included in the distribution?

**Comment by david-poindexter** [comment]
Just posting a note that this is still in the works but we are awaiting a few pieces of the puzzle to proceed.
