### ISSUE TITLE
Icon for page broken since upgrading to 9.4.1

### ISSUE THREAD

**Issue by improwise** [dnnsoftware/Dnn.Platform#3164]
After upgrading from 9.1 to 9.4.1 the "small icons" for pages in the menu system no longer works, even though the file itself is ok and is placed where it should be (upgrade). 

It seems like if you edit the page and select a new icon, it is added with the wrong path

https://upgrade.mysite.com/Portals/0//Portals/0/email.jpg?ver=2017-06-21-121921-430

(The Portals/0 part is added twice). 

Even entering the correct URL as a custom url cause the same error. 

Could probably be fixed manually by entering the correct URL in the DB. 

The correct icon is actually shown in the "edit page" dialog, but when actually in the meny system, the url is wrong and the image cant load.

**Comment by improwise** [comment]
The URL in the database is actually correct it seems so this is probably a code error.

**Comment by valadas** [comment]
And where is that displayed? Is it in a custom skin? In a menu system? I don't believe Dnn with the default theme even displays the small Icon...

**Comment by improwise** [comment]
DNN has built in functionality for displaying icons along with menu items.

**Comment by OllyHodgson** [comment]
@improwise How is the icon being displayed - is it using the DDRMenu module? If so it might well be skin related. Please can you post the code for an example menu which fails to show the icon?

**Comment by valadas** [comment]
Ok, I just doublechecked https://github.com/dnnsoftware/Dnn.Platform/blob/development/DNN%20Platform/Skins/Xcillion/Skin/Menus/MainMenu/MainMenu.txt

The default skin does not show those icons, so you need to have that implemented in the skin. I have sites running with this feature and had no issues (with custom skins), closing this issue for that reason.

**Comment by improwise** [comment]
Yes, this was actually a thought error from my side. There used to be a function to set icons for pages in DNN but for some unknown reason it has been removed https://dnntracker.atlassian.net/browse/DNN-9760.

**Comment by valadas** [comment]
@improwise I have brought that feature back in 9.3.x somewhere, you can set both the small and large icon in the page settings.
