### ISSUE TITLE
Update bug report issue template to no longer reference "nightly" builds

### ISSUE THREAD

**Issue by david-poindexter** [dnnsoftware/Dnn.Platform#3172]
## Summary
The bug report issue template currently references the following:

* [ ] 10.0.0 nightly build
* [ ] 9.4.1 nightly build
* [ ] 9.4.0 latest supported release

It needs to be updated to no longer use the phrase "nightly build".  This is confusing and misleading since builds are generated for every new pull request or manually triggered build.  I am proposing using the term "non-release build" instead.

**Comment by valadas** [comment]
Alpha maybe?

**Comment by valadas** [comment]
Wikipedia defines alpha as:

Alpha software is software that is not thoroughly tested by the developer before it is released to customers. Alpha software may contain serious errors, and any resulting instability could cause crashes or data loss.[2] Alpha software may not contain all of the features that are planned for the final version.

**Comment by mitchelsellers** [comment]
I would support the use of Alpha, as it is more absolute in naming rather than non-release

**Comment by david-poindexter** [comment]
Thanks @valadas and @mitchelsellers - I agree and will update the PR accordingly.

**Comment by mitchelsellers** [comment]
@david-poindexter For ease of builds, and review, please do these as single PR's in the future

**Comment by david-poindexter** [comment]
My apologies @mitchelsellers - due to computer issues at the time, I had to do these on a device that made this impossible for me.
