### ISSUE TITLE
'No search results' text shown although no search was performed.

### ISSUE THREAD

**Issue by dinesh-jain-aurea** [dnnsoftware/Dnn.Platform#3184]
## Description of bug
'No search results' message was shown although no search was performed. When a 'Search Module' is added to a page, the message 'No search results' is shown every time that page is loaded even though there is no search performed.

## Steps to reproduce
List the steps to reproduce the behavior:
1. Add the Search Module to the home page.
2. After the page reloads by itself, the text 'No search results' is shown when no search was performed.
3. At any time the home page loads, the text 'No search results' will be shown.

## Current result
'No search results' message was shown although no search was performed.

## Expected result
No message should be shown unless a search is performed. As per current behavior we do not perform search if the search query is less than 2 characters.

## Screenshots
Screenshots after the fix and showing all conditions

No message shown when no search performed.
![NoMessageWhenNoSearchPerformed](https://user-images.githubusercontent.com/25166031/67177539-90e0e500-f3ec-11e9-95ae-159ba5d9ddfa.png)

Valid Search Shown when search performed
![ValidSearchresults](https://user-images.githubusercontent.com/25166031/67177549-9f2f0100-f3ec-11e9-8d70-06c33c101a0a.png)

Message shown when Invalid search is performed
![MessageWhenInvalidSearch](https://user-images.githubusercontent.com/25166031/67177557-ac4bf000-f3ec-11e9-8589-34ed23d7aa3a.png)

## Affected version
* [X] 10.0.0 alpha build
* [X] 9.4.1 alpha build
* [X] 9.4.0 latest supported release

**Comment by valadas** [comment]
Merged
