### ISSUE TITLE
Data Consent checkbox click handler fails on custom logon page

### ISSUE THREAD

**Issue by DNNMonster** [dnnsoftware/Dnn.Platform#3193]
## Description of bug
Data consent check box does not trigger the removal of the disabled attribute from the submit button when the login control is placed on custom logon page.  

## Steps to reproduce
1. Create a new page called logon.
2. Add the Login Control
3. Set the sites default login to the the new page
4. Enable the Data Consent feature in the site privacy settings.
5. Log in as any regular user & you cannot proceed past the agree checkbox stage.

## Current result
User logs in but can't enable the submit button after agreeing to the terms.

## Expected result
User logs in and checks the box to agree to the Data Consent terms which should enable the submit.  Log in proceeds & user gets access.

## Error log
No js error shows in the developer console

## Additional context
It seems the browser is not executing this script found at the bottom of the  DesktopModules\Admin\Security\DataConsent.ascx control.  Tested placing an alert after the opening js script tag and before the click handlers but it is not executing.  Not seeing why..??  Tested a few different themes which should eliminate that as a possible cause.

## Affected version
9.4.1

## Affected browser
* [ ] Chrome

**Comment by valadas** [comment]
I can reproduce in 9.4.2, the Submit button is not enabled by checking the checkbox

**Comment by sleupold** [comment]
is there anyone, who wants to submit a fix?

**Comment by DNNMonster** [comment]
https://github.com/dnnsoftware/Dnn.Platform/pull/3586
