### ISSUE TITLE
Client Ressource Management throw exceptions when path not correct (even in default.css)

### ISSUE THREAD

**Issue by allanedk** [dnnsoftware/Dnn.Platform#3195]
## Description of bug
After upgrading from DNN8 to DNN9.4.1 the following has been observed when using "Composite Files" in Client Resources Management. The problem did not occur in DNN8.

Incorrect paths in an CSS `@import` statement will cause a fatal errors to be added in the log files ("/portals/_default/logs") on every pageview. The error is not visible in the persona bar admin logs. Adding approx. 1 kb to the log file on every pageview can be a problem on heavy traffic sites. 

This happens even if the `@import` statement has been commented out, which is the case with the _default.css_ currently shipped with DNN in _"/ressources/shared/stylesheets/dnndefault/8.0.0/"_ :

`Line 2: /* @import "01/correct4dnn7.css";*/`

## Steps to reproduce
List the steps to reproduce the behavior:
1. Use clean install or existing DNN 9.4.1 site
2. Enable Composite Files
3. Add this to your skin file (or any other CSS file that includes an invalid import path) :
`<dnn:DnnCssExclude runat="server" Name="dnndefault" />
<dnn:DnnCssInclude runat="server"
    FilePath="~/resources/shared/stylesheets/dnndefault/8.0.0/default.css"
    Priority="1"
    Name="dnndefault"
    Version="8.0.0" />`

4. Click Increment Version under Client Ressource Management
5. Open website e.g. home page
6. See error in log file ("/portals/_default/logs")

To verify the problem:
1. Remove line 2 of default.css (the commented import statement)
2. Click Increment Version under Client Ressource Management
3. Open website and refresh a couple of times. No errors will be added to logfile

## Current result
The following is added to logfile:
`2019-10-23 11:28:03.364+02:00 [SERVERNAME][D:4][T:46][FATAL] DotNetNuke.Web.Common.Internal.DotNetNukeHttpApplication - System.Web.HttpException (0x80004005): Path not found
   at ClientDependency.Core.CompositeFiles.CompositeDependencyHandler.ProcessRequestInternal(HttpContextBase context, String fileset, ClientDependencyType type, Int32 version, Byte[] outputBytes, OutputCachedPage page)
   at ClientDependency.Core.CompositeFiles.CompositeDependencyHandler.System.Web.IHttpHandler.ProcessRequest(HttpContext context)
   at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step)
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)`

## Expected result
DNN should ignore the import statement and continue parsing the rest of the CSS, as a believe DNN8 did. Or at least add a log entry in the regular admin logs, making it more visible to the admin. The error should include name of the affected file to make debugging easier.

And either way the commented line of default.css should be removed from DNN install package.

## Affected version

* [?] 10.0.0 alpha build
* [x] 9.4.1 alpha build
* [?] 9.4.0 latest supported release

**Comment by mitchelsellers** [comment]
There was an update to the actual CDF component that is used.  There should be an error logged if a file cannot be found, but comments should be respected.

**Comment by valadas** [comment]
Looks like this a known issue with ClientDependency... https://github.com/Shazwazza/ClientDependency/issues/117

A workaround would unfortunately just by to not comment imports :)
Since there is nothing actionable on our side of things, I am closing this issue in favor of the other repository where it would need a fix.

**Comment by allanedk** [comment]
Ok. It's easy enough to avoid commenting inputs in your own code :)

But I still think that the commented line should be removed in ~/resources/shared/stylesheets/dnndefault/8.0.0/default.cs.

That file currently ships with DNN and will cause errors for anybody using it until CD is fixed.

`/* @import "01/correct4dnn7.css";*/`

**Comment by valadas** [comment]
Yeah, but it is unused as it had issues and the default reverted back to the version 7.0.0.default.css for both Dnn8 and Dnn9... I am working a new default.css for Dnn10 which will remove a lot of old stuff and move some specific css that does not belong in default into it's appropriate place.
