### ISSUE TITLE
Ability to style notification and message(s) count for user (Add Badges)

### ISSUE THREAD

**Issue by thabaum** [dnnsoftware/Dnn.Platform#3196]
## Summary
I have been trying to find an easy way to style the numbers for the notifications and messages as you cannot see them no matter what you do.  It looks horrible and I would love make them look appealing and easy to read.

## Extended description
How do you style the notification and message count so that it will be displayed with a bootstrap badge

![image](https://user-images.githubusercontent.com/13577556/67410630-3b821080-f571-11e9-98c6-6c773b1adc68.png)

* [x ] Chrome
* [x ] Firefox
* [x ] Safari
* [ x] Internet Explorer
* [x ] Edge

**Comment by mikesmeltzer** [comment]
Are you referring to the icons in the header of the default Xcillion skin or are these somewhere else?

**Comment by david-poindexter** [comment]
This is possible within the theme already.  With enough specificity, these can be easily styled in the context of the theme.  We will go ahead and close this issue, but you may want to post a question on the [DNN Community Forums](https://dnncommunity.org/forums) if you need some help.

**Comment by thabaum** [comment]
Is there any documentation on this... seems like a little dnndocs.com material.

**Comment by valadas** [comment]
Yeah, it would be nice to add more documention in https://dnndocs.com/content/features/themes/index.html

Basically that page is missing the details of the skinobjects, @Timo-Breumelhof published an old pdf http://test.timo-design.nl/dnn/skindoc/DotNetNuke%205%20Skin%20Objects%20Beta%20Doc%204.pdf which is mostly ok but very old, referencing this and the current code at https://github.com/dnnsoftware/Dnn.Platform/tree/release/9.4.x/DNN%20Platform/Website/admin/Skins it would be a nice project to revamp that documentation.

**Comment by Timo-Breumelhof** [comment]
@valadas Actually it's no my list to move my old document into the documentation. (and correct them) :-)

@thabaum

The control used is the users skin / theme object.
\admin\Skins\user.ascx

Used like this:

`<dnn:User runat="server" id="dnnUser" LegacyMode="false" />`

It essentially renders this (if you set LegacyMode = false)


```
<div class="registerGroup" runat="server" id="registerGroup">
    <ul class="buttonGroup">
        <li class="userMessages alpha" runat="server" ID="messageGroup"><asp:HyperLink ID="messageLink" runat="server"/></li>
        <li class="userNotifications omega" runat="server" ID="notificationGroup"><asp:HyperLink ID="notificationLink" runat="server"/></li>
    	<li class="userDisplayName"><asp:HyperLink ID="enhancedRegisterLink" runat="server" rel="nofollow"/></li>
        <li class="userProfileImg" runat="server" ID="avatarGroup"><asp:HyperLink ID="avatar" runat="server"/></li>                                       
    </ul>
</div>
```
BTW, you should never change that ASCX file as it will be overwritten on upgrade!

The individual texts come from:

\admin\Skins\App_LocalResources\User.ascx.resx

Of which you can create your own version including any text / icon you want.
(again don't edit the file itself, it will be overwritten on upgrade).

Not sure this falls in my "easy"  category  but it's doable. ;-)

HTH

**Comment by valadas** [comment]
@Timo-Breumelhof 

> Actually it's no my list to move my old document into the documentation.
It's no my list or it's on my list ?

**Comment by Timo-Breumelhof** [comment]
@valadas not sure what you mean.. ;-)

**Comment by valadas** [comment]
Yeah, I guess I just had dyslexia :P
