### ISSUE TITLE
Servers Log Viewer Does Not Render White Space

### ISSUE THREAD

**Issue by bdukes** [dnnsoftware/Dnn.Platform#3197]
## Description of bug
In the _Servers_ Persona Bar extension, there's a place to view the log files.  Those log files are displayed without rendering their whitespace, which makes them difficult to read.

## Current result
All of the lines in the log file are displayed mixed together
![screenshot with text jumbled](https://user-images.githubusercontent.com/59507/67434429-d699db00-f5af-11e9-8de0-de7f7f9b6f3c.png)

## Expected result
Log file is displayed with each log line on a different line
![screenshot with text on each line](https://user-images.githubusercontent.com/59507/67434406-c7b32880-f5af-11e9-8e57-f8ae202525bd.png)

## Affected version

* [ ] 10.0.0 alpha build
* [x] 9.4.2 alpha build
* [ ] 9.4.1 latest supported release

## Affected browser

* [x] Chrome
* [x] Firefox
* [x] Safari
* [x] Internet Explorer
* [x] Edge

**Comment by valadas** [comment]
Merged
