### ISSUE TITLE
How to build by MSBuild 16.x? 

### ISSUE THREAD

**Issue by mnouraei** [dnnsoftware/Dnn.Platform#3206]
I using visual studio 2019 (last version). How to build dnn installed package by MSBuild 16.x?

**Comment by david-poindexter** [comment]
@mnouraei please check out [our build guide](https://github.com/dnnsoftware/Dnn.Platform/blob/development/.github/BUILD.md).  I am going to go ahead and close this issue, but feel free to re-open if you experience any actionable issues.  Thanks!
