### ISSUE TITLE
Couldn't find Dnn.AdminExperience in tree v9.4.1

### ISSUE THREAD

**Issue by mnouraei** [dnnsoftware/Dnn.Platform#3209]
i try to find [Dnn.AdminExperience](https://github.com/dnnsoftware/Dnn.Platform/tree/development/Dnn.AdminExperience) in [this link](https://github.com/dnnsoftware/Dnn.Platform/tree/v9.4.1) but it's not exist there, please help me.

**Comment by valadas** [comment]
Up to 9.4.1 it was not merged yet, you will find it here for 9.4.1 https://github.com/dnnsoftware/Dnn.AdminExperience/tree/release/3.0.x
