### ISSUE TITLE
VS2019 Azure webapp Publish errors on BuildScripts\Package.Targets DDRMenu & CoreMessaging

### ISSUE THREAD

**Issue by vdenduluri** [dnnsoftware/Dnn.Platform#3210]
Hi Team,

Using Visual studio 2019, when I am trying to publish to Azure web app (fresh install) using source code from branch release/9.4.x, I am getting following build errors.

12>  DotNetNuke.Modules.DDRMenu -> C:\VSO2019\Dnn.Platform\DNN Platform\Modules\DDRMenu\bin\DotNetNuke.Web.DDRMenu.dll
12>C:\VSO2019\Dnn.Platform\Build\BuildScripts\Package.Targets(15,5): error MSB4018: The "ExtensionPackager" task failed unexpectedly.
12>C:\VSO2019\Dnn.Platform\Build\BuildScripts\Package.Targets(15,5): error MSB4018: System.NullReferenceException: Object reference not set to an instance of an object.
12>C:\VSO2019\Dnn.Platform\Build\BuildScripts\Package.Targets(15,5): error MSB4018:    at DotNetNuke.MSBuild.Tasks.ExtensionPackager.<Execute>b__0(XElement package)
12>C:\VSO2019\Dnn.Platform\Build\BuildScripts\Package.Targets(15,5): error MSB4018:    at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
12>C:\VSO2019\Dnn.Platform\Build\BuildScripts\Package.Targets(15,5): error MSB4018:    at DotNetNuke.MSBuild.Tasks.ExtensionPackager.Execute()
12>C:\VSO2019\Dnn.Platform\Build\BuildScripts\Package.Targets(15,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
12>C:\VSO2019\Dnn.Platform\Build\BuildScripts\Package.Targets(15,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()

16>  DotNetNuke.Modules.CoreMessaging -> C:\VSO2019\Dnn.Platform\DNN Platform\Modules\CoreMessaging\bin\DotNetNuke.Modules.CoreMessaging.dll
16>C:\VSO2019\Dnn.Platform\Build\BuildScripts\Package.Targets(15,5): error MSB4018: The "ExtensionPackager" task failed unexpectedly.
16>C:\VSO2019\Dnn.Platform\Build\BuildScripts\Package.Targets(15,5): error MSB4018: System.NullReferenceException: Object reference not set to an instance of an object.
16>C:\VSO2019\Dnn.Platform\Build\BuildScripts\Package.Targets(15,5): error MSB4018:    at DotNetNuke.MSBuild.Tasks.ExtensionPackager.<Execute>b__0(XElement package)
16>C:\VSO2019\Dnn.Platform\Build\BuildScripts\Package.Targets(15,5): error MSB4018:    at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
16>C:\VSO2019\Dnn.Platform\Build\BuildScripts\Package.Targets(15,5): error MSB4018:    at DotNetNuke.MSBuild.Tasks.ExtensionPackager.Execute()
16>C:\VSO2019\Dnn.Platform\Build\BuildScripts\Package.Targets(15,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
16>C:\VSO2019\Dnn.Platform\Build\BuildScripts\Package.Targets(15,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()

## Screenshots
![image](https://user-images.githubusercontent.com/49203019/67720796-33233e80-f992-11e9-99cf-6436ac9001ec.png)

![image](https://user-images.githubusercontent.com/49203019/67720638-b85a2380-f991-11e9-92af-ef4ea08adaae.png)

## Affected version
* [ ] 10.0.0 alpha build
* [ ] 9.4.2 alpha build
* [X ] 9.4.1 latest supported release

**Comment by valadas** [comment]
The source code is not meant for publishing as a webapp, you need to download the install package from https://github.com/dnnsoftware/Dnn.Platform/releases

Building only works from within a cloned repository to produce that same install.zip
