### ISSUE TITLE
platform can't recognize ipv6 address

### ISSUE THREAD

**Issue by zyhfish** [dnnsoftware/Dnn.Platform#3214]
## Description of bug
platform can't recognize ipv6 address

## Steps to reproduce
1. install DNN latest release with a domain which pointed to an ipv6 address;
2. browse to the website and login as host.

## Current result
1. the IP Filter not able to add an IPv6 address;
2. the event log can't recognize IPv6 address.

## Expected result
the IPv6 address should be recognized in DNN.

## Screenshots
![image](https://user-images.githubusercontent.com/3364448/67743513-de4afb00-fa59-11e9-9b51-22468cacab9c.png)
![image](https://user-images.githubusercontent.com/3364448/67743530-e99e2680-fa59-11e9-92f2-7d4f8661e1cc.png)

**Comment by sleupold** [comment]
this seems to be still an issue

**Comment by sleupold** [comment]
this seems to be still an issue
