### ISSUE TITLE
Users Persona Bar Page Procedure or function Error 'Personabar_GetUsersBySearchTerm' expects parameter '@HasAgreedToTerms', which was not supplied.

### ISSUE THREAD

**Issue by thabaum** [dnnsoftware/Dnn.Platform#3215]
## Description of bug
Trying to view users and receive error when selecting Users in the persona bar menu.

## Steps to reproduce
List the steps to reproduce the behavior:
1. persona bar MANAGE > USERS
2. Page Error

## Current result
Procedure or function 'Personabar_GetUsersBySearchTerm' expects parameter '@HasAgreedToTerms', which was not supplied.

## Expected result
ability to manage users from persona bar

## Screenshots

![image](https://user-images.githubusercontent.com/13577556/67804557-60342780-fa4c-11e9-8ec8-f1f750f31882.png)
## Error log
no error in log

## Additional context
i have tried switching the user consent on and off to see if that helped but had no effect.

I will look at the db see if something is out of ordinary.  Error came out of no where really as things worked prior.  Only thing different was creating a couple new accounts possibly manually.

User Consent switch is on for two sites but not for all sites and there are about 4 with half on/off.

## Affected version

* [ ] 10.0.0 alpha build
* [ ] 9.4.2 alpha build
* [x ] 9.4.1 latest supported release

## Affected browser

* [ ] Chrome
* [ ] Firefox
* [ ] Safari
* [ ] Internet Explorer
* [ ] Edge

**Comment by valadas** [comment]
Can you check the version of the users module in extensions => Persona Bar Modules

Also check if you have many of them listed in there. I cannot reproduce this issue and I am thinking this might be an upgrade issue. Can you also check if there is anything of interest in the install logs at /Portals/_default/logs

**Comment by thabaum** [comment]
**Dnn.PersonaBar.Extensions 9.4.1 is the only extension available.**

I am also now experiencing error loading MANAGE > USERS and CONTENT > PAGES

Pages just shows an error at the top and nothing in the admin log.
![image](https://user-images.githubusercontent.com/13577556/68085892-b1e90300-fdfa-11e9-8541-fe998d6398d6.png)

Two errors in log files:

Many of this first one repeating throughout the day-

>  System.Web.HttpException (0x80004005): Session state can only be used when enableSessionState is set to true, either in a configuration file or in the Page directive. Please also make sure that System.Web.SessionStateModule or a custom session state module is included in the <configuration>\<system.web>\<httpModules> section in the application configuration.
>    at System.Web.UI.Page.get_Session()
>    at DotNetNuke.Framework.CachePageStatePersister.Save()
>    at System.Web.UI.Page.SaveAllState()
>    at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)

And these go off when I try to view users page -
> 2019-11-03 05:26:25.627-08:00 [SERVER][D:4][T:98][ERROR] DotNetNuke.Data.PetaPoco.PetaPocoHelper - [3] Error executing SQL: ;Exec dbo.Personabar_GetUsersBySearchTerm @0, @1, @2, @3, @4, @5, @6, @7, @8
> Procedure or function 'Personabar_GetUsersBySearchTerm' expects parameter '@HasAgreedToTerms', which was not supplied.
> 
> 2019-11-03 05:26:25.627-08:00 [ERVER][D:4][T:98][ERROR] Dnn.PersonaBar.Users.Services.UsersController - System.Data.SqlClient.SqlException (0x80131904): Procedure or function 'Personabar_GetUsersBySearchTerm' expects parameter '@HasAgreedToTerms', which was not supplied.
>    at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
>    at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
>    at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
>    at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
>    at System.Data.SqlClient.SqlDataReader.get_MetaData()
>    at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
>    at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
>    at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
>    at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
>    at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)
>    at DotNetNuke.Data.PetaPoco.PetaPocoExt.ExecuteReader(Database database, String sql, Object[] args)
>    at DotNetNuke.Data.PetaPoco.PetaPocoHelper.ExecuteReader(String connectionString, CommandType type, Int32 timeoutSec, String sql, Object[] args)
>    at DotNetNuke.Data.SqlDataProvider.ExecuteReader(String procedureName, Object[] commandParameters)
>    at Dnn.PersonaBar.Users.Components.UsersController.CallGetUsersBySearchTerm(GetUsersContract usersContract, Nullable`1 includeAuthorized, Nullable`1 includeDeleted, Nullable`1 includeSuperUsers)
>    at Dnn.PersonaBar.Users.Components.UsersController.GetUsers(GetUsersContract usersContract, Nullable`1 includeAuthorized, Nullable`1 includeDeleted, Nullable`1 includeSuperUsers, Int32& totalRecords)
>    at Dnn.PersonaBar.Users.Components.UsersController.GetUsersFromDb(GetUsersContract usersContract, Boolean isSuperUser, Int32& totalRecords)
>    at Dnn.PersonaBar.Users.Components.UsersController.GetUsers(GetUsersContract usersContract, Boolean isSuperUser, Int32& totalRecords)
>    at Dnn.PersonaBar.Users.Services.UsersController.GetUsers(String searchText, UserFilters filter, Int32 pageIndex, Int32 pageSize, String sortColumn, Boolean sortAscending)
> Error Number:201,State:4,Class:16

I don't think I seen one for the Pages not loading but maybe it is related.

I looked in the database UserPortals one of the rows for HasAgreedToTerms column is set to NULL

I did notice VanityUrl column having only a few users set to NULL and all the others are blank.  I was thinking of making them all NULL or Blank if you suggest maybe I should or does it matter.

**Comment by valadas** [comment]
The procedure is fine and it supports null, 0 and 1, the problem is whatever code calls it is not passing on that parameter.

If you go to the bin folder and right-click on Dnn.PersonaBar.Library.dll and then in the details tab you should see the version number, make sure that is 9.4.1 and maybe do the same for the other Dnn.PersonaBar.*.dll files and maybe DotNetNuke.dll too just to be sure. If any of those does not have 9.4.1 version, then something must have gone wrong with the upgrade and I would recopy those over from a clean 9.4.1 install.

Also, all persona bar dlls should have been replaced by a single Dnn.PersonaBar.Extensions.dll library, so if you see Dnn.PersonaBar.Users.dll, that should not be there and if it is I would compare that bin folder to a clean install bin folder and remove all Dnn.PersonaBar.[modulename].dll files you see in there.

**Comment by thabaum** [comment]
Thank you @valadas this was the solution.  I found many personabar dll files in the bin folder removed them all except the latest version which was 3 files.  I used a newer installation for reference and things are working again.

**Comment by valadas** [comment]
Awesome!

**Comment by brewadmin** [comment]
I am getting this same error on a brand new install of 9.4.4 ie no upgrade from previous versions.

**Comment by brewadmin** [comment]
As you can see I have a pile of personabar dlls

![image](https://user-images.githubusercontent.com/13762791/75119483-ddcf1380-568b-11ea-932f-1c9acf9b3f61.png)

**Comment by brewadmin** [comment]
So this happened in a clean install of 9.4.4

**Comment by brewadmin** [comment]
removing all the extra personabar dlls worked

**Comment by thabaum** [comment]
Thank you.  Looks like another issue just happened as well similar to this one I referenced this issue to that one.
