### ISSUE TITLE
how to build Dnn.AdminExperience

### ISSUE THREAD

**Issue by mnouraei** [dnnsoftware/Dnn.Platform#3218]
How to build [Dnn.AdminExperience](https://github.com/dnnsoftware/Dnn.AdminExperience) for dnn v9.4.1?

**Comment by mitchelsellers** [comment]
Admin Experience has been merged into the primary repo.  The build process is documented here: https://github.com/dnnsoftware/Dnn.Platform/blob/development/.github/BUILD.md
