### ISSUE TITLE
Persona Bar > Manage > Themes empty after renaming layout ascx file

### ISSUE THREAD

**Issue by Timo-Breumelhof** [dnnsoftware/Dnn.Platform#3224]
## Description of bug
When you rename the ascx file that is set as the site theme, the themes part of the PB "crashes".
Although this might not be a very common scenario on production site, it is when developing theme's
Fixable through the database, but annoying non the less.

## Steps to reproduce
List the steps to reproduce the behavior:
1. Choose a site theme layout for your portal
2. Through the file system, rename the ascx you just assigned
3. Go to PB > manage > Theme's
4. This part of the PB stays empty.

There's an error in the browser console: TypeError: e.currentTheme.SiteLayout is null

## Current result
You cannot set the theme for the site any more

## Expected result
PB should at least render the Theme selector IMO

## Error log
Browser console: TypeError: e.currentTheme.SiteLayout is null

## Affected version

* [ ] 10.0.0 alpha build
* [ ] 9.4.2 alpha build
* [x] 9.4.1 latest supported release

## Affected browser

Not relevant

**Comment by valadas** [comment]
I think this is pretty much a edge case that cannot be produced using the Dnn UI. Deleting a file that is needed is pretty "edge case" and a developer would be doing this and know how to fix it. For that reason I am closing this issue. But if anyone has the intention to work on this, please do comment and I will be glad to reopen.

**Comment by Timo-Breumelhof** [comment]
FYI, this happens also when you base a site on a portal template and the assigned skin in the portal template is not available on the installation.

**Comment by Timo-Breumelhof** [comment]
+ edge case or not IMO it's ridiculous that the PB "crashes" only if there's a file that it cannot find whatever the cause for that is..
