### ISSUE TITLE
Insert new page "in place" as "it used to be"

### ISSUE THREAD

**Issue by Timo-Breumelhof** [dnnsoftware/Dnn.Platform#3225]
## Description of problem
Before DNN9 a new page was injected on the same level as the current page.
In the PB, this is not the case and TBH, I'm so used to it that I have to go back and correct the location every time. Not a big issue for an individual page, but when building a new website, it's sub-optimal IMO.

## Description of solution
When clicking the "Add (multiple) Page(s)" button, use the currently selected page's parent in the Parent drop-down in the "add page(s)" view. (I would suggest to use what's selected, not the page that's currently visible).

## Steps to reproduce
List the precise steps to reproduce the bug:
1. Open the Persona Bar
2. Make sure you select a child page (on level 2)
3. Click the [Add Page] button on the top right.

## Current behavior
Notice that the newly injected page has no "Parent Page" set, so the new page will be injected in the root of the menu.

## Expected behavior
The newly injected page should have the same "Parent Page" as the currently selected page IMO.
BTW, when you click the ... next to a page and choose [Add Page] the behavior is "correct".

## Description of alternatives considered
do nothing ;-)

## Affected browser

* [x] Chrome
* [x] Firefox
* [x] Safari
* [x] Internet Explorer
* [x] Edge

**Comment by Timo-Breumelhof** [comment]
would be nice if this could be fixed

**Comment by david-poindexter** [comment]
@Timo-Breumelhof this issue is missing pertinent information from the issue template.  For instance, what version of DNN does this apply?  What are the steps to reproduce?  Etc.  

Would you mind updating the issue and following the appropriate Bug/Enhancement issue template format?  Thanks!

**Comment by Timo-Breumelhof** [comment]
@david-poindexter ok, FYI I logged it as an enhancement and then these are (kind of) the options that you get by default
