### ISSUE TITLE
How to build a stable release?

### ISSUE THREAD

**Issue by mnouraei** [dnnsoftware/Dnn.Platform#3226]
I'm making a Persian version.
To do this, I created a branch of [`v9.4.1 tag`](https://github.com/dnnsoftware/Dnn.Platform/tree/v9.4.1) Branch and made changes to its code, I need to create a stable version for the release.
To do this, I use the following command.
`.\build.ps1 -Target BuildAll -ScriptArgs '--CkBranch="development"','--CdfBranch="dnn"','--CpBranch="release/3.0.x"'`
But the 9.4.2 Alpha version is created. 
Please give me a guide.

**The steps in my work are as follows:**
Step1:
I created a new fork.
Step2:
I created a new branch from Ali, as follows:
`git checkout -b v9.4.1-persian v9.4.1`
Step3:
Applying changes in some classes for Persian-building.
Step4:
Run build command:
`.\build.ps1 -Target BuildAll -ScriptArgs '--CkBranch="development"','--CdfBranch="dnn"','--CpBranch="release/3.0.x"'`

Result is: `DNN_Platform_9.4.2_Install.zip` (Aplha version)

**Comment by valadas** [comment]
The version is set by GitVersion, that means it is based on the current branch and tags. To build a stable release (without alpha or beta) you need to have a version tag and you need to be on the master branch. The version tag should be preceded by the letter v as in v9.4.2

That all being said, you don't need to rebuild Dnn for localization, you can just translate the resource files and generate a language pack that can be installed on the normal Dnn release. To do so :
1. Go to site settings and add your language
2. Translate the resource files as needed using the global mode
3. Back on the languages main screen you can use the "Create Language Pack" with the core option and just install that language pack on the sites you need using the regular Dnn release.

**Comment by mnouraei** [comment]
@valadas I know the method of localization.
But I need some changes in the code for my organization.
Steps to create a stable version

**Comment by valadas** [comment]
Then you would have to fork Dnn and do the changes under your repository. Right now to build a stable release (not alpha or beta) you need to be on a tagged commit (right now the v.9.4.1 tag on the release/9.4.x branch), now if you do any change after that tag in the history, it should default to the version set in the gitVersion.yml file next-version. But it will be beta until you have a tag on your current commit after your changes. Modifying the core code is not a recommendation as it could prevent from upgrading or cause rewriting your changes on updates, so then would have to produce your own next versions too to maintain that on your side.

I am curious with all Dnn extension points why you would need to rewrite the core code...
