### ISSUE TITLE
Add support for wildcards in manifest cleanup component type

### ISSUE THREAD

**Issue by valadas** [dnnsoftware/Dnn.Platform#3227]
## Description of problem
The manifest has a cleanup component type to delete old files upon module upgrades, this is useful to get rid of unused files after some architectural change in modules. It currently supports specifying each file one by one in multiple "file" nodes or specifying a cleanup text file that lists all files one per line. Directories can also be deleted by specifying the directory name.

Problem 1: You cannot delete a directory unless it is empty, so you need to delete all files it contains before you can delete the directory. Some times, you may not know all the possible files that this folder can contain, for instance some javascript build systems use checksums in filenames for multiple reasons and that can be hard to track and keep a list of for all versions.

Problem 2: You may want to delete all files of a certain file type (example license files), so for old modules (and even for Dnn itself) it is very hard to know all the previous files that could be there but a wildcard could do the trick, such as /DesktopModules/MyModule/Licenses/*.txt then the manifest would put just the files for this version in there.

## Description of solution
Adding support for wildcards in filenames would solve both problems.
Problem 1:
```
DesktopModules\MyModule\Resources\*.*
DesktopModules\MyModule\Resources\
```
Would make sure, no mater what, that we can actually delete the folder.

Problem 2:
```
DesktopModules\MyModule\Resources\Scripts\*.js
```
Would get rid of any old javascript to be replaced by the new scripts during the module install.

## Description of alternatives considered
Alternative 1: We could add a new package type just to support wildcards, but I think the proposed solution is simpler.

Alternative 2: We could add a property to the cleanup called let's say "ForceDelete" that would force the deletion of a folder even if it contains files, but that would only solve one problem and not the ability to delete all files matching a certain pattern only.

## Additional context
My idea would be to rewrite the file deletion logic, instead of looping through one filepath at a time, that logic would get the folder path of the specified file, then do a Directory.EnumerateFiles on it and then loop through that result and delete each found file that matches. This would not break a normal file path and name but would simply add support for wildcards with not much code change.

Also for this to work (deleting a folder and then replacing it with a new one), we need to ensure that the cleanup task always runs before the files installation. I _think_ this is already the case, but if not, that would have to be done together with this change for it to work.

Any thoughts on this? I would be willing to submit a PR as part of 9.4.x for this...

**Comment by valadas** [comment]
After reading a bit in the installer code, the packages are installed in the order they are declared and then inside each package, all the component types support an `installOrder` and an `uninstallOrder` property to define what should happen in which order. This solves the concern about order of operations and is flexible.

**Comment by bdukes** [comment]
@valadas regarding problem 1, you _can_ specify a folder with a trailing slash (as in your example), and DNN will delete the folder.

Regarding problem 2, if that's a real problem developers have, I'm fine with adding wildcard support.  Are you envisioning that the wildcards would work by passing them as the `searchPattern` of [`Directory.EnumerateFiles`](https://docs.microsoft.com/en-us/dotnet/api/system.io.directory.enumeratefiles?view=netframework-4.8#System_IO_Directory_EnumerateFiles_System_String_System_String_), meaning that `scripts\*.js` would be supported but not `scripts\**\*.js`?

**Comment by mitchelsellers** [comment]
I think that wildcard support would be great as well, as we have had this issue in the past and it would make cleanup easier when transitioning from WebForms to MVC for example by supporting *.aspx as deletion criteria.

My $0.02 would be that we ONLY support it as a search pattern, and we also do not support it at the root for obvious reasons.

**Comment by valadas** [comment]
Well, I was thinking to just use the searchPattern in Directory.EnumerateFiles, I think developers have a bit of a better knowledge of possible folders and the issue is mainly files.

But there is a Microsoft.Extensions.FileSystem.Globbing that would allow using glob patterns like most node tools that many people are familiar with. That package requires .NETStandard 2.0, so this would work on .NetFramework 4.7.2 and in .NET Core right?

**Comment by valadas** [comment]
Forgot to link to it, here it is https://www.nuget.org/packages/Microsoft.Extensions.FileSystemGlobbing

**Comment by bdukes** [comment]
If we're going to do it, we might as well use the globbing package, right?

**Comment by valadas** [comment]
Would certainly be nice to support globs, or why not both...

The windows way is \ and when we see that we use the normal windows patterns, if we see / then we use globs (/ is a requirement for globs I far as I know)

**Comment by Timo-Breumelhof** [comment]
FYI, somewhat related to https://github.com/dnnsoftware/Dnn.Platform/pull/5090
