### ISSUE TITLE
Update the File Manager to allow extensions

### ISSUE THREAD

**Issue by thabaum** [dnnsoftware/Dnn.Platform#3229]
## Description of problem
File Manager needs to be re-worked for a modern UI workflow and to allow future development of features such as image photo editors.

## Description of solution
Discuss best possible solutions to allow features to be added or updated as individual objects in the file manager allowing developers to create solutions as extensions for common website file tasks such as editing photos.

## Description of alternatives considered
Anything that includes a way for photo editor.  This feature request is in part due to the following issue:  https://github.com/dnnsoftware/Dnn.Platform/issues/3040#issuecomment-549066902

## Additional context
Much more discussion on the file manager is needed it sounds like to start moving forward on it.

**Comment by mitchelsellers** [comment]
This is already being tracked at a higher level from architecture.  For clarity closing this ticket to keep clutter down.

If you want to participate in the discussions @valadas is leading this effort right now

**Comment by thabaum** [comment]
sounds good thanks for the update.
