### ISSUE TITLE
Change default localization in installation

### ISSUE THREAD

**Issue by mnouraei** [dnnsoftware/Dnn.Platform#3231]
How do I change localization on install to fa-IR, as if the installation is finished localization is fa-IR ?
I don't want to be done after installing this.

**Comment by valadas** [comment]
If I understand the question correctly, you are trying to make Dnn install in fa-IR. This is not required and most people just install it in english and then install language packs and change or create sites from there in that language.

That being said, if your question is about making all this happen during install, here is what I would try, but I did not try it, just my thoughs on how I believe this process works.

During installation, the available languages showing in the drowdowns are these ones https://github.com/dnnsoftware/Dnn.Platform/blob/development/Website/Install/App_LocalResources/Locales.xml
Those languages are currently downloaded from a web service unless English is selected.

Also, I am 99% sure you could drop the language pack zip into the \Install\Language folder before firing up the installation and it would get installed (although not activated).

I am pretty sure that everything gets installed before the portals are created, so maybe (I have not tried this yet), you could edit https://github.com/dnnsoftware/Dnn.Platform/tree/development/DNN%20Platform/Website/Templates and indicate it.

I am writing this and digging into the install code at the same time, so yeah, just found this https://github.com/dnnsoftware/Dnn.Platform/blob/6e346c8e0ab1b765abf7ab0caf98bcd7558d92be/DNN%20Platform/Library/Services/Upgrade/Internals/Steps/InstallSiteStep.cs#L124 During the site (portal) creation, it will look for a file \Install\language\installlanguage.resources file, but as far as I know, this is downloaded from the upgrade service https://github.com/dnnsoftware/Dnn.Platform/blob/6e346c8e0ab1b765abf7ab0caf98bcd7558d92be/DNN%20Platform/Library/Services/Upgrade/Internals/UpdateService.cs

Sooo, not sure 100% if it is even possible to do in the current state of things. I know there is work being done regarding localization packs, maybe someone working on that front can comment...

**Comment by valadas** [comment]
I am closing this issue since it is more of a question than an actual issue. You can keep commenting on it though.
