### ISSUE TITLE
Language Resource File Search Autofill and set translations, save all at once.

### ISSUE THREAD

**Issue by thabaum** [dnnsoftware/Dnn.Platform#3235]
## Description of problem
Changing every location you find the word Login or Register can take some time but is very common.  It takes a lot of time to "Save Translation" and wait for DNN to restart. Then browse every category, sub category and file inside to find these two files.

In if you did this search you would think the two most common fields set alone would be in two locations but in fact you find them in all the locations below:
**Local Resources => Admin => Skins => Login.ascx.resx**
+
**Local Resources => Admin => Skins=> Login.Host.ascx.resx**
![image](https://user-images.githubusercontent.com/13577556/68099119-a4bd2a00-fe75-11e9-92d0-58258a7e9c0b.png)
+
**Local Resources => Admin => Skins=> User.ascx.resx**
+
**Local Resources => Admin => Skins=> UserandLogin.ascx.resx**
![image](https://user-images.githubusercontent.com/13577556/68099362-f3b78f00-fe76-11e9-9a1c-a252d06e0ce4.png)
and at the bottom a register.text location.
+
**Local Resources => DesktopModules => AuthenticationServices => Dnn+FB+Google+Twitter =>Login.ascx.resx files**
+
**Local Resources => DesktopModules => Admin => Authentication => Login.ascx.resx**
![image](https://user-images.githubusercontent.com/13577556/68098654-bcdf7a00-fe72-11e9-9625-957a1b010353.png)
and if you scroll lower on that same long file
![image](https://user-images.githubusercontent.com/13577556/68098677-e26c8380-fe72-11e9-834b-5eedf2f26332.png)

**Local Resources => DesktopModules => Admin => Security => Register.ascx**
![image](https://user-images.githubusercontent.com/13577556/68099913-054e6600-fe7a-11e9-9656-6ffe8c734936.png)

About 7 different language files give or take a few... Each time having to save and locate...

## Description of solution
A search box that once you start typing characters it starts to autocomplete any of the defined language files with the Resource name carrying more weight than the Localized value but displaying both in results so you can easily locate anything that can be edited.

At the same time allow you to search and continue searching making all the changes to all the different files prior to saving all the the changes to the files. Possibly caching changes in the browser so that you dont lose any work but nothing is saved until you apply the changes.  Maybe have it so it auto updates the fields but just doesn't apply it until you hit apply.  This way you can edit away at each and every language file field you want and save them all at once.

## Description of alternatives considered
Drink more coffee.

## Screenshots
see above

## Additional context
It sure would make life easier to locate, edit and save all the resource files related to a keyword search at once stopping the website just the one time.

I have a vision that in the screenshot below that the current search area would allow me to enter text keyword and where it shows the resource name and default value areas for showing the resource files selected a list of language resources would populate related to that keyword allowing you to easily find anything available in the drop down tree navigation.

Currently it only searches the file you have selected.  I am proposing it search the entire collection of language resources.

![image](https://user-images.githubusercontent.com/13577556/68131102-4faf0180-fed1-11e9-9b02-daeeb726abec.png)

## Affected browser

* [ ] Chrome
* [ ] Firefox
* [ ] Safari
* [ ] Internet Explorer
* [ ] Edge

**Comment by mitchelsellers** [comment]
This is an awesome idea!  This will for sure take some development efforts as currently these files are dynamically loaded and larger installations can have thousands of these files.  But this would help end a lot of hassle for users.

**Comment by valadas** [comment]
I agree, I think performance in this area is not a huge concern, it's not like users would suffer from a search here taking a few seconds and it would certainly be way faster than going to find those strings using another tool.

**Comment by thabaum** [comment]
Users would suffer more from many restarts caused by so many saves.

**Comment by valadas** [comment]
Editing the resource files does not cause a site restart.

@thabaum this would involve many changes, I did not check it all but probably:
some in the core localization APIs somewhere around https://github.com/dnnsoftware/Dnn.Platform/tree/development/DNN%20Platform/Library/Services/Localization
Then some for the web APIs, probably somewhere around https://github.com/dnnsoftware/Dnn.Platform/tree/development/Dnn.AdminExperience/Extensions/Content/Dnn.PersonaBar.Extensions/Components/SiteSettings and maybe in https://github.com/dnnsoftware/Dnn.Platform/blob/development/Dnn.AdminExperience/Library/Dnn.PersonaBar.Library/Controllers/LocalizationController.cs maybe in https://github.com/dnnsoftware/Dnn.Platform/blob/development/Dnn.AdminExperience/Library/Dnn.PersonaBar.Library/DTO/Localization.cs
and some in the SiteSettings module around here https://github.com/dnnsoftware/Dnn.Platform/tree/development/Dnn.AdminExperience/Extensions/Content/Dnn.PersonaBar.Extensions/WebApps/SiteSettings.Web/src probably in the store and reducers and services and the language settings components about here https://github.com/dnnsoftware/Dnn.Platform/tree/development/Dnn.AdminExperience/Extensions/Content/Dnn.PersonaBar.Extensions/WebApps/SiteSettings.Web/src/components/languageSettings

**Comment by sleupold** [comment]
The best solution would be moving localization into the database. Upon DNN install, update and module install/upgrades, the resx files would be read and the content per key loaded into a dedicated table (with optimized indexes). Instead of reading multiple files, each request will just be a database call, returning the necessary keys. Searching specific words or phrases would be super simple and this would also provide support for semi-static content like role names, page names etc. while eliminating the current workarounds for countries, regions and profile properties.

**Comment by thabaum** [comment]
@valadas some reason after I hit save for a resource file I have to wait for the cache to rebuild or something before the site works again.  There is a very noticeable amount of downtime.

I love the idea to things to the database.  This would simplify working with things as you can use SQL Studio Management to edit the language resources as well.

If things move to the database the ability to import resx files to the database when installing modules would be needed.  Along with a way to import resx files to the database from within DNN.  A button along with a call that modules can make on installation that can allow DNN Can search all resx files for any changes and update the database with any new language items not found for each category.

Would adding a second method to allow first creating database versions of language items.  First check the resource files, then update using the database if the same field exists use the one from the database.  Would this allow a transitional period potentially if thought out right and possibly a way to have them co-exist until they fade out.

**Comment by thabaum** [comment]
I like the way this is setup in Manage => Roles

![image](https://user-images.githubusercontent.com/13577556/68270964-fbf90100-0013-11ea-8d3d-ebe908719640.png)

**Comment by sleupold** [comment]
@EPTamminga  
of course, moving translation to the database require a couple of intelligent ideas to solve all use cases, but I am sure, it would solve a lot of headaches with current workaround and add numerous missing features.
