### ISSUE TITLE
RC releases zip files should be named accordingly

### ISSUE THREAD

**Issue by valadas** [dnnsoftware/Dnn.Platform#3238]
## Description of bug
During release packaging GitVersion is used to set the zip files names. Currently RC releases are named as the official releases. We currently download the zip files and manually rename them when publishing RCs. It would be easy to use SemVer instead of MajorMinorPatch returned from GitVersion for the zip file name in order to save that manual step and ensure we have a unique file name for each RC release without manual intervention.

![image](https://user-images.githubusercontent.com/6371568/68186202-8d636700-ff71-11e9-95f4-b819bb0faede.png)

**Comment by donker** [comment]
Fxied by #3285
