### ISSUE TITLE
Dnn modules should follow Dnn version

### ISSUE THREAD

**Issue by valadas** [dnnsoftware/Dnn.Platform#3239]
We have had issues in the past where a version number was not bumped and it caused upgrade issues since packages with the same version as the installed one are skipped. We use GitVersion to set the versions in manifest files for most modules but some are not auto-managed and get the last manually set version.

In 9.4.2-rc1, the following modules have version 9.3.2 instead of 9.4.2, which could cause issues if they have changes when upgrading from 9.3.2, 9.4.0, 9.4.1, I suggest we fix this before 9.4.2 official release to prevent issues with those upgrades.

## Modules
* Authentication
* Registration
* Search Results
* Users and Roles
* ViewProfile

## Authentication Systems
* Default Authentication

## Providers
* DotNetNuke Client Capability Provider

## Skin Objects
* All the skin objects

## Others
Those have never historically been always matching the Dnn version but I think they should (open to opinions though)
* Xcillion Skin and Containers
* Default theme and containers

## Unkowns
I am not sure on the purpose of delivering these Libraries, can someone explain their purpose and why we deliver 3 versions when we require .Net Framework 4.7.2 ?
* Microsoft CodeDom .Net Compiler (1.0.1)
* Microsoft CodeDom .Net Compiler for .NET 4.5 (2.0.1)
* Microsoft CodeDom .Net Compiler for .NET 4.6+ (2.0.1)

**Comment by EPTamminga** [comment]
I support the suggestion that all standard components follow the main version #.

**Comment by valadas** [comment]
@bdukes Those packages allow the usage of new C# features in ASCX files

But they are not installed, so if someone would want to use those new features, they would have to install it and then use that correct?

And it is safe to get rid of the older ones and just keep the latest right?

**Comment by bdukes** [comment]
Yes, it's an optional install because it comes with `csc.exe`, and there are some hosting environments (I think GoDaddy was the main one) which don't allow deploying `exe` files.  So a package which used those new C# features would need to take a dependency on that package to ensure it was installed first.

**Comment by bdukes** [comment]
And yes, it is safe to get rid of older ones.

**Comment by valadas** [comment]
Cool, @donker already has most of this as part of #3254 and we discussed this is not a showstopper for 9.4.2 so moving the milestone for 9.4.3

**Comment by valadas** [comment]
Merged
