### ISSUE TITLE
Cannot create new folder in DAM 

### ISSUE THREAD

**Issue by digitalsigi** [dnnsoftware/Dnn.Platform#3240]
## Description of bug
Save button does not react on add new folder

## Steps to reproduce
List the steps to reproduce the behavior:
1. Add a DAM Module to a Page
2. Click on Add Folder
3. Enter a name for the folder
4. Press save
5. Nothing happens (Browser console shows error 500, see attached log)

## Current result
The folder is not created, the popup window remains open

## Expected result
Folder is created an popup window is close

## Screenshots
No screenshots available

## Error log
jquery-migrate.js?cdv=209:18 JQMIGRATE: Migrate is installed with logging active, version 3.0.0
jquery-migrate.js?cdv=209:62 JQMIGRATE: jQuery.expr[":"] is now jQuery.expr.pseudos
migrateWarn @ jquery-migrate.js?cdv=209:62
jquery-migrate.js?cdv=209:64 console.trace
migrateWarn @ jquery-migrate.js?cdv=209:64
jquery-migrate.js?cdv=209:62 JQMIGRATE: jQuery.expr.filters is now jQuery.expr.pseudos
migrateWarn @ jquery-migrate.js?cdv=209:62
jquery-migrate.js?cdv=209:64 console.trace
migrateWarn @ jquery-migrate.js?cdv=209:64
jquery.fancybox-1.3.4.pack.js:18 Uncaught TypeError: Cannot read property 'msie' of undefined
    at jquery.fancybox-1.3.4.pack.js:18
    at jquery.fancybox-1.3.4.pack.js:46
jquery-migrate.js?cdv=209:62 JQMIGRATE: jQuery.unique is deprecated, use jQuery.uniqueSort
migrateWarn @ jquery-migrate.js?cdv=209:62
jquery-migrate.js?cdv=209:64 console.trace
migrateWarn @ jquery-migrate.js?cdv=209:64
jquery.js?cdv=209:3869 Uncaught TypeError: jQuery(...).fancybox is not a function
    at HTMLDocument.<anonymous> (VM2495 Archiv-160-161:1057)
    at mightThrow (jquery.js?cdv=209:3583)
    at process (jquery.js?cdv=209:3651)
jquery-migrate.js?cdv=209:62 JQMIGRATE: jQuery.fn.bind() is deprecated
migrateWarn @ jquery-migrate.js?cdv=209:62
jquery-migrate.js?cdv=209:64 console.trace
migrateWarn @ jquery-migrate.js?cdv=209:64
jquery.js?cdv=209:9455 [Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
send @ jquery.js?cdv=209:9455
ajax @ jquery.js?cdv=209:9173
jQuery.ajax @ jquery-migrate.js?cdv=209:191
saveNewFolder @ dnn.DigitalAssets.js?cdv=209:2345
click @ dnn.DigitalAssets.js?cdv=209:2241
(anonymous) @ jquery-ui.js?cdv=209:12181
dispatch @ jquery.js?cdv=209:5206
elemData.handle @ jquery.js?cdv=209:5014
jquery.js?cdv=209:9566 POST https://www.burckhardia.at/API/DigitalAssets/ContentService/CreateNewFolder 500
send @ jquery.js?cdv=209:9566
ajax @ jquery.js?cdv=209:9173
jQuery.ajax @ jquery-migrate.js?cdv=209:191
saveNewFolder @ dnn.DigitalAssets.js?cdv=209:2345
click @ dnn.DigitalAssets.js?cdv=209:2241
(anonymous) @ jquery-ui.js?cdv=209:12181
dispatch @ jquery.js?cdv=209:5206
elemData.handle @ jquery.js?cdv=209:5014
**jquery.js?cdv=209:9566 POST https://www.burckhardia.at/API/DigitalAssets/ContentService/CreateNewFolder 500**
send @ jquery.js?cdv=209:9566
ajax @ jquery.js?cdv=209:9173
jQuery.ajax @ jquery-migrate.js?cdv=209:191
saveNewFolder @ dnn.DigitalAssets.js?cdv=209:2345
click @ dnn.DigitalAssets.js?cdv=209:2241
(anonymous) @ jquery-ui.js?cdv=209:12181
dispatch @ jquery.js?cdv=209:5206
elemData.handle @ jquery.js?cdv=209:5014

## Affected version

* [ ] 10.0.0 alpha build
* [ ] 9.4.2 alpha build
* [X] 9.4.1 latest supported release

## Affected browser

* [X] Chrome
* [ ] Firefox
* [ ] Safari
* [ ] Internet Explorer
* [X] Edge

**Comment by valadas** [comment]
I was not able to reproduce, this is an issue on the server-side and the browser logs here are not helpful. Can you check the log files in the /Portals/_default/logs folder of the site and look if there is anything there that could give some clues.

**Comment by digitalsigi** [comment]
This for the quick reply. Indeed in log ist more info: User not authorized. Sorry...
However, a better message would be helpful. 
I'll fix this and close the case.
