### ISSUE TITLE
Don't work localization file in Dnn.TaskScheduler

### ISSUE THREAD

**Issue by mnouraei** [dnnsoftware/Dnn.Platform#3241]
When I change the language of the site to Persian, in the `Dnn.TaskScheduler`, the localization file is `TaskScheduler.FA-IR.resx` is not invoked.
Also, Persian date is not displayed.
![Untitled](https://user-images.githubusercontent.com/9780304/68208620-cf7ac000-ffe6-11e9-9b40-d573c4775731.png)

## Affected version
* [x] 9.4.2-rc
* [x] 9.4.1

**Comment by valadas** [comment]
Do we have anyone with knowledge about Persian calendar that can help here?
