### ISSUE TITLE
Unique Email should be per Portal not the entire DNN instance.

### ISSUE THREAD

**Issue by thabaum** [dnnsoftware/Dnn.Platform#3245]
## Description of bug
If you have 10 sites running and a user registers for one site, the other sites a user will not be able to register or log into, or know to log into using the email they use.

If you allow many accounts per same email address on same portal you get a lot of spam user accounts.  This helps limit that however unable to keep the limit on a per portal basis and allow a user with the same email to register once per portal with the same email.

## Steps to reproduce
List the steps to reproduce the behavior:
1. Create two sites on the same DNN instance
2. Set Unique Email Required in web config
3. Try to register on both websites
4. Email is already in use error trying to register one time on the second portal.

## Current result
Users can only register on one portal with unique email address per instance.

## Expected result
User can register each portal once with an email address

**Comment by valadas** [comment]
This is a known limitation for supporting portal groups as discussed here https://github.com/dnnsoftware/Dnn.Platform/issues/2745 users are instance-wide and will just be mapped or not to each portal, this is how it is possible to have portal groups and being able to use the same account. I highly suggest to not use multitenant unless you really have a need for it. I am closing this issue in favor of the linked one which as a lot of dixcussion that relate to this.
