### ISSUE TITLE
Ability to see what groups a user is a member of.

### ISSUE THREAD

**Issue by thabaum** [dnnsoftware/Dnn.Platform#3247]
## Description of problem
While browsing users in the Persona Bar, when you find a user and you wish to find out more on what DNN security or site user group roles they might be a part of you have to switch between each role.

## Description of solution
Create a way to allow viewing all of the DNN security groups a user is a member of and manage group membership for that user while using the Manage => Users feature in the Persona Bar
## Description of alternatives considered
Keep searching roles for any that a specific user is a part of, drink more coffee.

## Screenshots
If applicable, provide screenshots to help explain your problem and/or feature.
![image](https://user-images.githubusercontent.com/13577556/68269571-1b415f80-000f-11ea-9b96-4d57988e0b11.png)

## Additional context
Add any other context about the feature that may be helpful with implementation.

## Affected browser

* [ ] Chrome
* [ ] Firefox
* [ ] Safari
* [ ] Internet Explorer
* [ ] Edge

**Comment by mitchelsellers** [comment]
This is available today with the "Roles" option that you can select from the list of users.  (What role are you in as? )

**Comment by valadas** [comment]
Yes, you should have a shield icon that then displays all the roles like this:
![image](https://user-images.githubusercontent.com/6371568/68270810-a8df7800-002c-11ea-8cd6-69ed81f203b1.png)

From what I can see, those are host (superusers) and they are considered to be part of every role in code, this is why they do not have the shield icon. If that is not the case, please comment by adding how to reproduce on current versions.
