### ISSUE TITLE
Not able to delete custom roles if their associated social group folder isn't empty

### ISSUE THREAD

**Issue by berkarslan-xo** [dnnsoftware/Dnn.Platform#3248]
## Description of bug
When trying to delete the Role which is associated with a Social Group, it throws Internal Server Error 500.

## Steps to reproduce
List the steps to reproduce the behavior:
1. Create a Social Group
2. Note the Social Group ID
3. Upload nested folder and files under Portals\0\Groups\<GROUPID>
4. Attempt to delete the Custom Role associated with the Social Group

Reproduction video: https://drive.google.com/file/d/1tTEJreF3SdKrKdK13tYH0R7vlKpMgKJC/view?usp=sharing

## Current result
1. General exception error caught in the Admin Logs with "Message:The directory is not empty."
2. 500 API error caught in the browser's Dev Tools under the Network Tab
3. The Custom Role doesn't get deleted.

## Expected result
The Custom Role gets deleted.

## Screenshots
If applicable, provide screenshots to help explain your problem.

## Error log
Paste the error log that is related to this issue.

## Additional context
Add any other context about the bug that may be helpful for resolution.

## Affected version

* [x] 9.4.x build

## Affected browser

* [x] Chrome
* [x] Firefox
* [x] Safari
* [x] Internet Explorer
* [x] Edge

**Comment by berkarslan-xo** [comment]
I closed it by mistake so that I reopened it now.

**Comment by valadas** [comment]
Merged
