### ISSUE TITLE
Two-Factor Authentication

### ISSUE THREAD

**Issue by thabaum** [dnnsoftware/Dnn.Platform#3252]
## Description of problem
DNN CE needs a two-factor authentication solution.

## Description of solution
Create two factor authentication that uses Email is a great start.  Allow extensions to be created for different SMS providers down the road.  The feature will be capable of remembering device browsers from the remember me controls.

- Add a switch for an admin to turn on two-factor authentication with email (Phone if SMS is setup)
-- Database entry for setting PortalSettings.TwoFactorEnabled
--  Database entry for setting PortalSetting.TwoFactorRememberEnabled for remember me (remember login) setting already available.  So I think this would be enabled if that is enabled but might need a way not to have remember me have two-factor.  Device browser cache will store this information.
-- Database entry for setting PortalSetting.TwoFactorEmailEnabled  (Later on with SMS enabled)
-- Database entry for setting PortalSetting.TwoFactorSMSEnabled  (Later on...)
-- Database entry for setting PortalSetting.TwoFactorSMSProviderID  (Later on...)
- Add ability to configure settings (For SMS provider configurations only, later on...)
- Create two-factor authentication solution that work with DNN Login. (Email first)
- A simple link a user can click on below a number they can enter to authenticate the browser session.
- Remember Login will remember browser and could be used for this  purpose when Two-Factor is enabled.

## Additional context
Molding these DNN Files to allow two-factor authentication:
https://github.com/dnnsoftware/Dnn.Platform/blob/release/9.4.x/DNN%20Platform/Website/DesktopModules/Admin/Authentication/Login.ascx
Documentation for the proposed feature.
https://docs.microsoft.com/en-us/aspnet/identity/overview/features-api/two-factor-authentication-using-sms-and-email-with-aspnet-identity

and this for reference as well:

https://docs.microsoft.com/en-us/aspnet/identity/overview/features-api/two-factor-authentication-using-sms-and-email-with-aspnet-identity
https://docs.microsoft.com/en-us/aspnet/mvc/overview/security/aspnet-mvc-5-app-with-sms-and-email-two-factor-authentication
https://www.twilio.com/docs/authy/quickstart/dotnet-core-csharp-two-factor-authentication

SMS is another feature but I will put that in another issue so a pr can be made for both if needed as email verification system is enough to make me happy with SMS a bonus feature.  It may need a separate discussion, however while working on this piece maybe it is best to go ahead and include it.  And I believe it will happen sometime after this first PR is added to the platform.  I have looked into this already I feel confident this will happen possibly next on my list of personal todo's once I know the SMTP issues are smoothed out enough.

@sleupold I may be asking some help here soon from you as the man with the db plan to make sure I can do things with best practices for DNN and .NET along with SQL.  Sie der Mann mit der Datenbanks!

I am thinking @valadas is the current Jedi UI Master so when I put some ideas up please help me get in the right direction with a little example.   Thank you for all the awesome support and insights. I will be your test subject on ways to help improve documentation and tutorials for someone that has intermediate to advanced programming skills in different areas of the programming world wanting to learn how to help or even use DNN CE.

@bdukes and @david-poindexter  you seem to be helping me out a lot with the logic and keeping the projects setup properly I really thank you two for all of that help.

@mitchelsellers it feels like you help glue it all together and I am feeling out everyone's role thanks to your help here.  And getting answers to best practices for the solutions which is a great help.  THank you as well!

@zyhfish you fixed the email verification resend issue would this be something you would understand easier?  Thanks for fixing that issue it bugged me for a long long time ;)

You will see my pitfalls and I will notice them as well.  When I feel I know things fairly fluent here I can then help contribute to documentation to help people out like me as well.  One thing that makes any open source project SUPER AWESOME is great documentation and a community motivated to endorse and support it.  It has to be easy not just for the programmers... but for the end users.  I wish to make documentation that can be used for the users in DNN not just the administrators.  Generic documentation that can be added to any sites knowledge base that shows how to use the account area and allows you or a mod developer to add more documentation. This is getting further from the issue but relates still. One thing at a time i see getting the system designed the way it will be for a long period of time so the documentation system can be super clear and staying current changing with the changes as a goal and a priority.  

This will pretty much get me to where I am hoping DNN will be and I will probably go dormant for a while after these are done :)

Links above are what need to be done, now I like to hear anything that relates to these articles and DNN that may help.

This will move to my top priority and I will begin now if no one is working on this currently to see what I can drum up.

https://github.com/dnnsoftware/Dnn.Platform/blob/release/9.4.x/DNN%20Platform/Website/DesktopModules/Admin/Authentication/Login.ascx

This needs to allow two-factor emails to help control logins.  A Two-Factor: "Send Request" is made, the user can then click on the link or "Enter Code" with the remember 

LOGIN
- Username: 
- Password::  
- Two-Factor: Send Request
- Enter-Code: 
- Captcha
- Register | Login buttons

**Special Notes from Documentation:**
The 2FA codes are generated using Time-based One-time Password Algorithm and codes are valid for six minutes. If you take more than six minutes to enter the code, you'll get an Invalid code error message.

Clicking on the Remember this browser check box will exempt you from needing to use 2FA to log on with that computer and browser. Enabling 2FA and clicking on the Remember this browser will provide you with strong 2FA protection from malicious users trying to access your account, as long as they don't have access to your computer. You can do this on any private machine you regularly use. By setting Remember this browser, you get the added security of 2FA from computers you don't regularly use, and you get the convenience on not having to go through 2FA on your own computers.

With code changes, you can change your security profile (for example, by changing the state of Two Factor Enabled) and you will be logged out in 5 seconds when the SecurityStampValidator.OnValidateIdentity method fails. Remove the return line in the SignInAsync method, make another security profile change and you will not be logged out. The SignInAsync method generates a new security cookie.

**Comment by thabaum** [comment]
@donker looks like you the person on the job here working the code.  I am going to submit some code here possibly see if it might help make this happen and if anyone can help fill in the gaps the world would love you!

**Comment by thabaum** [comment]
2FA vs FIDO any thoughts?

**Comment by valadas** [comment]
I am no expert but I believe 2FA is a generic term for 2 factor authentication, FIDO2 is one implementation of 2FA...

**Comment by thabaum** [comment]
so what is the free one?  I have read that two-factor authentication or 2FA is easy to phish.

So everyone backed FIDO2 for a current solution.

**Comment by valadas** [comment]
Like I said, i don't know enough about it to even have an opinion, implementing it would required someone who knows this good and will maintain it in the future. Unless we have someone that want to build and maintain such a solution, I think this should be a third party module maybe.

**Comment by thabaum** [comment]
I think third parties probably do support these type of features.

I will do a bit more research and play with it a little see if I can make or break it one way or another for my own personal interests, but after watching videos... I am looking at toturials for FIDO2 maybe if i can some how hack it together with dnn i will share it.  2fA I just think might be something more but still risky due to phishing which is really a major issue to me.

The more you know the more there is to know, that is life.  So I will keep this dialog going until I give up and close or submit a PR.  This issue topic is now evolving which I don't like... but it is for the better.  I am requesting stuff that is irrelevant really.
