### ISSUE TITLE
Remember Login is below Login Button referenced in issue #2471

### ISSUE THREAD

**Issue by thabaum** [dnnsoftware/Dnn.Platform#3255]
## Description of bug
Placement of Remember Login on login form

## Current result
Below Login Button

## Expected result
Above Login Button

## Screenshots
If applicable, provide screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/13577556/68357472-505eb800-00ca-11ea-85e2-527959965578.png)

## Additional context
in reference to issue # 4 on list for issue #2471

**Comment by valadas** [comment]
Merged
