### ISSUE TITLE
Translation Task Scheduler page in PersonaBar

### ISSUE THREAD

**Issue by mnouraei** [dnnsoftware/Dnn.Platform#3262]
## Description of bug
When translating the PersonaBar Task Scheduler page in a Multilanguage platform, the FREQUENCY column is not included and NEXT START column date is not Persian date (fa-IR).

## Screenshots
![68208620-cf7ac000-ffe6-11e9-9b40-d573c4775731](https://user-images.githubusercontent.com/9780304/68414315-347c1480-01a5-11ea-9409-a950dbd5967e.png)

## Affected version
9.4.1

**Comment by valadas** [comment]
For the column names I cannot reproduce I see them in the language of the language pack I have, this is something that would need to be handled on the Persian language pack. For the dates I did not have an suitable environment to test right now...
