### ISSUE TITLE
How to find export-bundle.js source code?

### ISSUE THREAD

**Issue by mnouraei** [dnnsoftware/Dnn.Platform#3267]
How to find export-bundle.js source code?

**Comment by valadas** [comment]
That would be here https://github.com/dnnsoftware/Dnn.Platform/tree/development/Dnn.AdminExperience/Library/Dnn.PersonaBar.UI/admin/personaBar/Bundle.Web

**Comment by mnouraei** [comment]
I am looking for the `isRtl` object, but it's not in the file. Where is this object created?

**Comment by valadas** [comment]
You can search for it in the github search on the repository like so https://github.com/search?q=org%3Adnnsoftware+isRtl&type=Code

From the looks of it either from pikaday or jQuery.timepicker ...

**Comment by mnouraei** [comment]
In the  `export-bundle.js` (http://localhost/DesktopModules/admin/Dnn.PersonaBar/scripts/exports/export-bundle.js) file I've seen this variable, is this the same?

**Comment by valadas** [comment]
It could also be a dependency of a dependency of a dependency :)

**Comment by valadas** [comment]
Pikaday is a dependency on that project, so maybe... But it is difficult to debug from the bundle itself, I would rather run that project using webpack and then debug from the non-minified code, you will need to adjust whatever load that file to use the liveserver url instead of the minified file and it really helps troubleshooting from there.

**Comment by mnouraei** [comment]
I need to use moment-Jalaali to convert the date.
To do this, I must find whether the system is in RTL mode.
Can you help me?

**Comment by valadas** [comment]
I have absolutely no experience with RTL languages unfortunately... Maybe the folks at https://github.com/moment/moment/ have some guidance or code samples for that...
