### ISSUE TITLE
Add link to https://dodnn.work/ in help area.

### ISSUE THREAD

**Issue by thabaum** [dnnsoftware/Dnn.Platform#3271]
## Description of problem
Needing easy access help getting things configured or customized for the DNN platform.  Also a place easy to find for those wish to support.

## Description of solution 
https://dodnn.work/  description and link in the About page in the admin persona bar.

## Description of alternatives considered

This can get linked to projects community would like that have a funding goal to push features through.  Possibly a way the first PR to come to light as a best solution wins a community contributed fund for the PR.  Some transparent way to allow features to get produced that actually support that development of DNN open source project.

## Screenshots
![image](https://user-images.githubusercontent.com/13577556/68548910-c3a44a80-03a6-11ea-9f7c-730239988846.png)

## Additional context

I put a reference to this RFC here:  [dnncommunity.org forum topic](https://dnncommunity.org/forums/aft/527)

Somewhere here there should be a place for dodnn.work along with a link to another site if not dodnn.work or dnncommunity.org that is connected with GitHub Issues that can get supported using those registered in dodnn.work.  It feels like a missing link to an open source and open funded project.  It would be nice to be able to use that DNN image handler to show off how it can display goals created for different projects that the community can contribute to, but if it does not get done and goes stale as an issue the money is refunded or can be allowed to be diverted to another project.  Or community piles up money resources and votes on which projects should be prioritized and used based on funds available, and go with the flow unless you can sponsor it as a group.  And a way to donate knowing you will get notified how your funds helped out the project when they get used.  Plus a badge or whatever to show you supported for your profile if you like.  Maybe this is not possibly but it sure feels like all the handcuffs are off it is up to the community now.  It is time to bridge DNN to .NET Core, we need support in many ways to accomplish this in the best way that will have minimal impact on the community.  Let alone the current issues and features desired for the current release.

**Comment by valadas** [comment]
I am of the opinion that we already have a link to the community site and that site has a link to dodnn.work Also, I don't believe that is under the community control (not sure)... Opinions ?

**Comment by Timo-Breumelhof** [comment]
Agreed, I would prefer to add a link to the community forums THB (get help).
Or to https://dnncommunity.org/community/agencies (which should be the community controlled dodnn) 
Actually I think Dodnn was founded because there was no place for this on the "old website".

**Comment by thabaum** [comment]
https://dnncommunity.org/forums/aft/527

**Comment by thabaum** [comment]
I am personally all for supporting those who are looking to make a buck.  I only wish to help those looking to support and needing help here.

I figured dodnn.work is a good place to register everyone that wishes to use this as a tool to attact customers.  It should get tuned up for the community however maybe a 100% community solution is needed here.  Possibly a link to both the page and dodnn.work.

I just feel in my opinion the modules, module store and the people doing support should be easy to get to... this is one part of an issue I believe I see for the community organization.

**Comment by Timo-Breumelhof** [comment]
The store in under control of DNN Corp, AFAIK the earnings goto them.

**Comment by mitchelsellers** [comment]
This is part of a very, very, very long-standing argument/discussion in the community.

The stance, right or wrong, has been that we are only linking & promoting in the distribution the assets that we have at least some control over.  Once we do a release we cannot change these links, thus the support for only the official community-controlled items.  (Docs, Community Site, & GitHub).
