### ISSUE TITLE
Add Ability to style more objects in the Registration form. 

### ISSUE THREAD

**Issue by thabaum** [dnnsoftware/Dnn.Platform#3274]
## Description of problem
Unable to style all objects in the registration form.

## Description of solution
Create additional CSS classes to allow independence between objects and classes available in DNN.

**Comment by Timo-Breumelhof** [comment]
@thabaum can you be more specific? What is there you cannot style right now?

**Comment by thabaum** [comment]
For example the help icon. 

And I am really looking towards making things more up to standard, I don't believe using ID's is best.  This was just to make things more I suppose able to get specifically with a CSS every possible spot with just a single CSS class or by a group with a single css class.

I put up an RFC with my real concerns, I was trying to see ways to help improve making it easier to style, not just having the ability to style.

**Comment by thabaum** [comment]
Issue #3278 3278

A deeper discussion is here

**Comment by valadas** [comment]
Ok, so the registration form can vary and the fields are an extension point, so we cannot hardcode a class name on the items that do not exist for everyone. The field id is part of the control id so the ids are predictable, then each element has it's classes like .dnnLabel, .dnnFormRequired, .dnnTooltip and so on.

We also have a root id of #dnn_ctr_Register_RegistrationForm and then a parent of .dnnForm and then each collection of label, required, help and filed has it's own .dnnFormItem and .dnnFormShort, what more classes can we possibly add ? What can't you style with all this available?

**Comment by valadas** [comment]
I am closing this in favor of #3278 to prevent cross-talk into multiple issues/PRs I still don't know that there is an actual problem and we have multiple issues and prs relating to this same thing...
