### ISSUE TITLE
how to build Dnn.React.Common?

### ISSUE THREAD

**Issue by mnouraei** [dnnsoftware/Dnn.Platform#3276]
How to build [`Dnn.React.Common`](https://github.com/dnnsoftware/Dnn.Platform/tree/development/Dnn.AdminExperience/Dnn.React.Common) and use in [`WebApps`](https://github.com/dnnsoftware/Dnn.Platform/tree/development/Dnn.AdminExperience/Extensions/Content/Dnn.PersonaBar.Extensions/WebApps)?
Now this [`path`](https://www.myget.org/F/dnn-software-public/npm/@dnnsoftware/dnn-react-common/-/@dnnsoftware/dnn-react-common-2.1.2.tgz) is received and used

**Comment by valadas** [comment]
The multiple WebApps parts are part of a lerna workspace that maps local packages directly to their source folder, so in theory you should just have to run yarn install then yarn webpack for development or yarn build for production. What are the steps you did and what happened?

**Comment by mnouraei** [comment]
I have to customize the [datePicker](https://github.com/dnnsoftware/Dnn.Platform/tree/development/Dnn.AdminExperience/Dnn.React.Common/src/DatePicker). It is located in [Dnn.React.Common](https://github.com/dnnsoftware/Dnn.Platform/tree/development/Dnn.AdminExperience/Dnn.React.Common)

**Comment by valadas** [comment]
Ok, but that does not answer the question. Did you run yarn install then yarn build or yarn webpack, what happened ? Do you have experience with node modules and webpack and react debugging. I do not understand the problem so it is hard to help...

**Comment by mnouraei** [comment]
You're right, I write bad English. Let me translate and re-issue the problem.

**Comment by valadas** [comment]
I am closing this issue if favor of #3272 which is the same problem as here, we need to bump the version to allow proper debuggin on all projects when building them just one instead of the whole workspace.

**Comment by mnouraei** [comment]
I need to customize DatePicker for Persian calendar.
Right now, version 2.1.2 of this library can be downloaded by webPack from https://www.myget.org/F/dnn-software-public/npm/@dnnsoftware/dnn-react-common/-/@dnnsoftware/dnn-react-common-2.1.2.tgz . Modification of this version is not allowed.

In Dnn.Platform\Dnn.AdminExperience\Dnn.React.Common path of Dnn.AdminExperience, there exist a version which can be customized and I want to use this version for development based on React.
How can I use this in a project powered by React like Roles.Web ?

**Comment by valadas** [comment]
The data picker common components wrap react-day-picker component as in here https://github.com/dnnsoftware/Dnn.Platform/blob/83ee0001477f570e65b3883300199a81288769b8/Dnn.AdminExperience/Dnn.React.Common/src/DatePicker/index.jsx#L412 But they do not appear to implement moment.js localization, we already have a dependency on moment.js so maybe I would try to do something like this: http://react-day-picker.js.org/docs/localization#moment

I don't know enough about the Persian calendar to know if that works propertly but how does this look here: https://codesandbox.io/s/p6qs4
