### ISSUE TITLE
RFC: CSS Class Naming Convention for upcoming version

### ISSUE THREAD

**Issue by thabaum** [dnnsoftware/Dnn.Platform#3278]
**REQUEST FOR COMMENTS**

## Description of Problem
CSS Classes are currently not standard in any way.  Some use cssClass others cssclass and others css-class or even Class throughout the different modules and areas of the platform.  The current CSS class naming convention is out-of-date.

## Proposed Solution Option 1
Add an additional class to all the classes that lays out how things should be done for Dnn.Next but put them into version 10 to allow a transition version.

The entire hierarchy of how and when to create css classes maybe should get documented at www.dnndocs.com first in a Dnn.Next reference area.

Current CSS web standards should be applied here to new additional classes to be applied, it will bloat files for version 10 but things will thin back out for version 11 is what I am suggesting. 

Please any thoughts or ideas for how to approach this I can begin adding them now as planned here.  
I will also reference this topic in this [DNN community forum post.](https://dnncommunity.org/forums/aft/471#2006)

Here is the [CSS Class Naming Convention GitHub RFC ](https://dnncommunity.org/forums/aft/526)thread for the dnncommunity.org forum topic.

**Comment by valadas** [comment]
This is the third time I am putting the same comment about css classes. Any removal or change will break existing themes, we can surely add new classes, but we need to think that every time we add new class, we have to keep it forever to not break themes. Adding a new class should be only done when absolutelly necessary when there is no way to style an element using some parent class and css specificity.

For instance if we have:
```
<div class="some-container">
<label>Nane:</label>
<input type="text"></input>
</div>
```
We have no need to add classes to each element, we can access them individually using `.some-container label` and `.some-container input` without locking into new class names forever.

In the other hand if we have something like:
```
<div class="some-container">
<label>First Name:</label>
<input type="text"></input>
<label>Last Name:</label>
<input type="text"></input>
</div>
```

This could  be something to consider because it is hard to select one or the other input. But I have not seen such situation so far in the platform and I do not believe we have a need to add more classes unless this situation exists somewhere.

It is very easy to add classes to everything, but:
1. This bloats the page (css being static files have better caching than html)
2. It is very easy to add classes, but very hard to remove them in the future without making it a breaking change
3. We currently have no situation where it is needed because we cannot style some specific element (if there is, then I would suggest opening an issue about those specific cases for reconsideration).

**Comment by valadas** [comment]
Oh, I just noticed this was probably posted as an RFC following some PRs, I am reopening for now to gather thoughts, but would really like for people to indicate an actual styling problem that exists before commenting about it.

**Comment by thabaum** [comment]
> This is the third time I am putting the same comment about css classes. Any removal or change will break existing themes, we can surely add new classes, but we need to think that every time we add new class, we have to keep it forever to not break themes. Adding a new class should be only done when absolutelly necessary when there is no way to style an element using some parent class and css specificity.

Each time you have said this I have replied that the version that would be excluding the old would be version 11 possibly with adding the new classes to version 9 having them ready for version 10.  Maybe I am just not clear when talking but I have mentioned ALL current classes will still exist for version 9 and 10.  **ALL**.

So let me try to clear this up some if I may:
1.  All current classes need to stay and I never planed to change any of them in the current version or even 10.
2.  Version 10 I would like to have a new class naming convention on everything so it will be in fact "Bloated" for that version.
3.  Version 11 remove the old classes as obsolete and have a message in version 10 explaining they need changed.
4. Use an all lowercase with-a-dash between words with a common way to shorten common things and remove dnn from all of them to help shorten them.
5.  Then changing the CSS in all default module skins for a mobile first approach both for both admins and users in version 10.

Doesn't have to be anything fancy, simple as can be but a good start for anyone trying to get something basic but with modern usability up and working right out of the box.

**Comment by valadas** [comment]
> great tutorial stuff man we need to document these examples shared somehow

Well this is basic css specificity, nothing fancy and nothing platform specific, it is just css and we can't possibly document common knowledge as css and html....

The proposed changes do not make sense to me unless there is a real existing problem styling. using pascalCase or CamelCase or kebab-case for classnames is an opiniated decision and nothing worth changing just for changing, this would bloat Dnn10 and then create breaking changes for themes in Dnn11 without any need for it other than going to a prefered casing style or naming convention. This will just cause trouble without solving anything...

Do you have a specific case where you could not select a specific element to style it, if not, IMO there is nothing to solve here. It is the 5th time I am asking this same question, I do not believe there is a problem to solve right now with the given information...

**Comment by Timo-Breumelhof** [comment]
Actually, I agree with the both of you.
I agree that DNN is using a multitude of CSS class naming styles and one should realize that for a CSS developer this feels like c# where all the variable names use different naming conventions.
It works but looks unprofessional.. When it comes to c# there tends to be more room for these kind of restructuring in DNN, but that does not influence the functioning of the component as it's compiled code.
It would be good if we would say "we use this naming convention".
On the other hand, historically, almost any change made to a css class in the past has lead to issues for skinners and they were not happy (me included).
This for me this falls in the same category as switching the DNN UI to Bootstrap 4.
Nice idea at first, but it will break a lot of websites and make a lot of existing DNN users unhappy.

**Comment by Timo-Breumelhof** [comment]
BTW, I agree that the general consensus is that id's are not for styling but for JS.

**Comment by david-poindexter** [comment]
I understand the desire for a standardized CSS naming convention, but I do not agree with breaking changes for this reason alone.

I could make the same argument for namespaces, database table names, method naming conventions, variable nomenclature, coding styles, knockout vs react, etc.

**Comment by Timo-Breumelhof** [comment]
@thabaum I really appreciate the fact that you want to make DNN easier to style.
I have not seen any html yet that I could not style in DNN, but you really need to know what to look for.
I do think we could improve the documentation though as some might miss for instance the predefined module classes we have.

**Comment by valadas** [comment]
Well, sure documentation would be nice, but for anyone familiar with html/css, just inspecting the page html is pretty much self-documenting...

**Comment by Timo-Breumelhof** [comment]
That's what you would expect, but I noticed that not everybody finds their way in for instance this:

```
<div id="dnn_ContentPane" class="ContentPane Pane">
<div class="DnnModule DnnModule-40FingersPortalList DnnModule-379"><a name="379"></a>
	<div class="cContainer cBase">
		<header class="Container ClearAfter">
			<h1 class="cTitle">
				<span id="dnn_ctr379_dnnTitle_titleLabel" class="Title">Portals</span>
			</h1>
		</header>
		<section class="Container ClearAfter">
			<div id="dnn_ctr379_ContentPane" class="Normal cContentpane">
			<!-- Start_Module_379 -->
			<div id="dnn_ctr379_ModuleContent" class="DNNModuleContent Mod40FingersPortalListC">
```
A DNN module is wrapped in a lot of HTML, but most of these classes are really useful and I have seen a lot weird CSS while these classes were the better option (to for instance style a module of a certain type like all HTML modules)

**Comment by thabaum** [comment]
> I do think it's good to think about this for Dnn.Next and make the switch for that version not before, as it will most likely have a new skinning engine


it wont break anything the way I am proposing for 2 version 9 and 10 and 11 if it is not Dnn.Next which is where I propose removing the old classes

**Comment by thabaum** [comment]
i know it is bloat and for a C# dev it is easy to follow no problem.  But this is not acceptable by any way in todays developer world I dont believe if you created an app with current naming convention for a big client they would tell you to redo it.  At least I would

`<div id="dnn_ContentPane" class="ContentPane Pane">`
 
could be class="content-pain pain"

This is how the world thinks today, just like using .NET Core this is the new world we live in.

**Comment by thabaum** [comment]
> I could make the same argument for namespaces, database table names, method naming conventions, variable nomenclature, coding styles, knockout vs react, etc.

Not everyone that is a "basic user" is going to even know or see those.  But I agree something for all of those should be in DNN Docs as a guideline to follow for future development that everyone working with those can refer to.... I am thinking by version .NET Core these things should be 100% thought of and documented.

CSS classes are huge today to bring in NEW people that dont get confused as easy...  CSS Developers will be absolutely turned off by DNN... I know my cousin is one of them and she is awesome but wont touch DNN as it is just a mess to deal with.  Take too much time using all these different naming conventions.. uh-oh i forget a cap..  oh man what naming convention was used again... slowing down progress and costing more to develop a theme. for an end user.

**Comment by thabaum** [comment]
There is a lot missing from many modules and areas that would make it simpler.  And give DNN a modern look when reviewing it's skin  code.  

Personally I HATE skinning DNN and working with these name classes as a person with a learning curve I read tutorials that show me nothing like what I am looking at.   So I have been confused in the past as to if I am even looking at a css class because ALL tutorials show this-type-of-naming.  The other way looks like it is code and makes me more scared to play with it.

I am no business selling development software but I am a big time user of DNN. The CSS has bugged me forever... so yes I am ready for the change.

**Comment by mitchelsellers** [comment]
Again, I'm all for change here, but I think that it is very important that if we are going to go down this road that it be done in a controlled manner and look at the whole scope of the changes.  As there a a huge landmine of work involved here and potential impacts.

1. What feature/functions are we actually looking to fix.  This started with the Login module, but you have reference into skinning-engine items, which are much harder to actually change.
2. What is the problem that we are actually solving by doing this
3. What is the benefit to the platform in the process
4. What is the transition path for existing sites & upgraded sites

Once we go down a road with some of this, it can really be a "fixed" road for quite a while so I want to be sure that we have documented facts/issues/goals before anything is proposed/changed.  As getting out of under one of these things can be hard.  (For example the now defunct, mostly, form patterns.)

**Comment by thabaum** [comment]
I am in agreement with all of you @mitchelsellers @valadas and @Timo-Breumelhof 

I just feel anything that needs to get addressed for .NET Core to make DNN 100% and future work can rely on not causing issues down the road.

1 and 1/2 versions to work through to get this done.  I am all in on helping out here but I need direction from the community on what I can do that will actually be accepted as PR's in the future.

This is a really deep conversation and I have been enlightened.  I own many modules I have paid a 1000's for over the years... I know how breaking changes can affect a mod developer and I really want to put them first here, however the ultimate goal should be the easy of understanding for anyone using and working with the DNN platform.

1.  I dont think it is a feature fix here but a CSS fix.  However one thing that might be able to get addressed along the way is making mobile friendly Login/Registration pages.  Even my paid modules I still have issues with... and I am paying "pros" but the work to be done seems it should be easy that I could do but even Timo found something in Journal he could not adjust.

So this would be fixing the naming class convention to a DNN standard that is something everyone would expect today. It can be adjusted here but anything missing to make it easy to modify the styles of all the user areas.  

2.  Adding any missing classes if needed and adding a naming convention that is to be a DNN standard going forward.

3.  More people will accept it as a "Modern" web app instead of something from 10 years ago... and people like me can more fully understand the layout and CSS going on.   Going through all this also will bring up other issues I am sure that will need to be talked about.

4.  -New DNN Standardized classes can then be introduced in Version 9
- completed prior to Version 10 and most all if not all included for anyone worried about it
- then removed during 11 PR's.  One batch at a time... per version increment.

This feels like a pretty safe direction to allow DNN to go.  I don't wish to break any of my sites now as I will need to make adjustments as well.  The removal can be in version 12 even if people are not ready yet and too much is going on from issues of the new changes 11 brings.

Some work I am willing to help contribute.

I keep hearing add Bootstrap but isn't the site theme controlling what boostrap version these forms use... and if not why not? Would declaring this twice cause issues and version problems?

**Comment by mitchelsellers** [comment]
We do not want to introduce additional framework requirements (bootstrap etc) within the core of DNN as the second we do this we introduce all kinds of breaking changes, and we set a new standard for security management of releases etc.

**Comment by thabaum** [comment]
I understand so this bootstrap solution keeps getting thrown out as a way to make things work well but it is not the answer here.

I like the idea of the skin theme itself controlling these types of things.

**Comment by mitchelsellers** [comment]
You can do this today, which many designers are doing with good success.

For cases where you want to really change there is an ability to create a custom provider to make it even more succinct, which we have had to do for a few sites.  But again, I'm trying to find the exact "what isn't working" piece, which I still don't have, in all of these discussion points.

Not trying to be negative here, just trying to manage time/effort/energy.

**Comment by thabaum** [comment]
never said it didnt work... posted a couple articles to read maybe that shines light on what I am at odds with here.

**Comment by thabaum** [comment]
![image](https://user-images.githubusercontent.com/13577556/68704494-3e08d200-0541-11ea-83ab-94d1a1634dd9.png)

**Comment by thabaum** [comment]
that "keep consistent" part DNN is far away from like i said it is like the city of Seattle where two roadmaps developed got merged together causing chaos and confusion for those driving the roads.

**Comment by thabaum** [comment]
https://www.freecodecamp.org/news/css-naming-conventions-that-will-save-you-hours-of-debugging-35cea737d849/

**Comment by thabaum** [comment]
![image](https://user-images.githubusercontent.com/13577556/68707046-dbfe9b80-0545-11ea-9fab-12f3962134e9.png)

This is a pro job... years after it has been developed this is still what it looks like.  if it was easy to style those icons would be next to the fields... they are all over.  Maybe it is more form issues, but this is an example of something that you can select with a bunch of css thought:

![image](https://user-images.githubusercontent.com/13577556/68707322-5cbd9780-0546-11ea-956a-54be9fc8eea3.png)

look at those help icons, the forms for the login and registration need help as well but I am not trying to talk about, just the naming convention.  Although it currently works and I am fine with it if everyone else is... 

Please let me know how to move these next to the labels...

**Comment by thabaum** [comment]
So for the time/effort/energy I am thinking about the long haul, not near term so much.  I personally want to see a road to normalization path but I understand there are only so much resources going around as far as people willing to devote time here.

So I am for whatever you all agree upon.

**Comment by valadas** [comment]
> Please let me know how to move these next to the labels...

Well each set of label/help has a containing .dnnLabel class. The default theme (default.css actually) uses float because well, it was written a long time ago. On my new themes I prefer to use flexbox for stuff that involves one axis and css grid for stuff that involves 2 axes. 

For instance, you could do:
```
.dnnLabel {display: flex; justify-content: flex-start;}
```

This will make all childs of .dnnLabel stack horizontally and to the left. Of course then you may want to add some padding to a thing or another, like you could do:
```
.dnnLabe label {margin-right: 1em;}
```
or some such

**Comment by thabaum** [comment]
`The default theme (default.css actually) uses float because well, it was written a long time ago.`

I suppose this is part of my issue here which is why I was hoping to maybe make some changes now and see about putting best practices in the DNN default.css

Flex and Grid is what I have been reading about trying to figure out how to improve here.

It sounds like no one wants to do anything here and I can feel a version 11 I told you so coming :)

**Comment by mitchelsellers** [comment]
Any change to default.css is a breaking change and must be reserved for a major version as it will break skins without a question.  (See 6.0, 7.0, 8.0, 9.0, and 9.2 for some examples of varying severity)

We are ALL for cleanup, but it has to be with a clear mission that improves globally etc.

**Comment by thabaum** [comment]
default.css I didnt want to touch other than possibly for version 10 and 11.  Which may introduce a new default.css added to the old but you can still use the old one.  maybe by removing the commenting around it potentially?

**Comment by thabaum** [comment]
Is this something that can be discussed with the advisory teams as well?  Maybe see what kind of resolution would work best to accomplish this task and goal that fits the bill.  Let me know I am happy to help.  Any other suggestions or comments regarding css changes as well as naming convention standards to "try" to follow going forward and how to navigate towards normalizing things to today's world between now and 11.  I know it is a bit of a mess to talk about.  I just would like to hear something concrete come out of this in the near future.  Even if it is not handled version 9 or 10...  it still needs dealt with if possible.  I see a version change coming and wish to move things if possible if I can help.  If this goes on for months it will be possibly too late for a version 9 to begin and have to wait for version 10 to begin... we are talking 5 years + down the road then to remove the old classes.

**Comment by thabaum** [comment]
> A DNN module is wrapped in a lot of HTML, but most of these classes are really useful and I have seen a lot weird CSS while these classes were the better option (to for instance style a module of a certain type like all HTML modules)

This is the issue for me... it seems every module developer has funky colors and things that dont work with the skin that is installed... **thumbs up if you had this problem!**

I always get the "you can do it here or there" for an answer but really us users just want it all to work right out the box.  Install DNN and Install Modules... skins look like they belong together.  DNN Mod developers and DNN need to work together so this is no longer an issue and mod developers follow a golden set of rules to help limit these bummer of issues.   I still have pink buttons on a site because that is what the modder wanted to use... and there is no reason there should not be in my mind a standard so that what I create a module I can put a simple set of classes into it and it will style easily with the rest of the website.

**Comment by thabaum** [comment]
Again sorry for being a little pushy here I just wish to take advantage of the 9-10 release anywhere I feel I can for a very nice clean looking version 11.  

> 
> 
> BTW, I agree that the general consensus is that id's are not for styling but for JS.

This is what I keep reading about but I know ID's can be used but are not the best practice, however I am not sure how to really handle this in this discussion as hardly a leg to stand on here... I just started looking around at adding a few classes. good idea at first like you said but it opened up this bag of worms... I just felt there is an opportunity here to start addressing naming conventions to a standard that we all can agree to follow.  And then make the changes as seen fit from our discussions that are also agreed on.  However I see a lot of RFC's just being RFC's and not go anywhere.   To get this ball rolling so we dont have to wait a decade like I have already for some changes... here I am stepping up to the plate to take some swings here best I can.  I might strike out on a few PR's, but it took 1000 tries to make a light bulb, everyone one of those tries are successful at showing how NOT to make a light bulb.  Give me something I can chew on here :)

**Comment by mitchelsellers** [comment]
> > A DNN module is wrapped in a lot of HTML, but most of these classes are really useful and I have seen a lot weird CSS while these classes were the better option (to for instance style a module of a certain type like all HTML modules)
> 
> This is the issue for me... it seems every module developer has funky colors and things that dont work with the skin that is installed... **thumbs up if you had this problem!**
> 
> I always get the "you can do it here or there" for an answer but really us users just want it all to work right out the box. Install DNN and Install Modules... skins look like they belong together. DNN Mod developers and DNN need to work together so this is no longer an issue and mod developers follow a golden set of rules to help limit these bummer of issues. I still have pink buttons on a site because that is what the modder wanted to use... and there is no reason there should not be in my mind a standard so that what I create a module I can put a simple set of classes into it and it will style easily with the rest of the website.

This is one area, that as much as I'd love to agree, I don't think that will ever happen.  It was tried in the past, that is how the DNN 6.x form patterns came about, but nothing ever really happened for them to be adopted.  Now, we are at a point where all of the module vendors have adopted their own styles and now they are just as entrenched as we are with the monumental shift.

I agree, 100%, that we should keep DNN itself clear and provide some guidance, but expectation wise I don't think we will get the vendors to shift to follow our new pattern if we create one anyway.  I've discussed this process with a number of them already and confirmed some of that.

@Timo-Breumelhof I know you have been thinking about default.css and the standard styles for years now, maybe you and @thabaum should chat a bit to see if we can direct Cody to a place that will be practical and usable?

**Comment by david-poindexter** [comment]
@thabaum I’d really like to schedule a meeting with you.  Would you mind sending me an email with some times you are available to chat? You can use the first letter of my first name, my last name, at the domain associated with my GitHub profile.  Thanks and I look forward to speaking with you.

**Comment by thabaum** [comment]
sounds good I will email you tomorrow after I give it some thought, thanks!

**Comment by thabaum** [comment]
I would love to see DNN get Discord and Gitter for helping collaberate like this.  Discord similar to TeamSpeak which is great for meetings and controlling speaking.

You all should seriously look into it as I could not believe Discord was on the Microsoft community as a channel they use... awesome tool!

**Comment by thabaum** [comment]
went ahead sent you the email just now @david-poindexter, thanks!

**Comment by Timo-Breumelhof** [comment]
@mitchelsellers as this "issue" seem to cover a lot, I think it would be best to first make a list of things that could be improved, order them by importance and then see what we can do with a little impact as possible for a major version. 

For DNN 10 my first goal would be to clean up default.css. Not remove it as some suggest (I would love that, but it would break too many sites I think), but at least remove the useless stuff from the past as a first step. 

I think that if you want to do that the right way, including testing and documentation (so DNN admins know what the "risks" are) that's already a bit of work.

Another valuable addition IMO would be to make login, search box etc. templatable.
It would make life for skinners much easier and DNN more flexible.
And you could request the "legacy" of the "modern" of "your own" template.

**Comment by david-poindexter** [comment]
> went ahead sent you the email just now @david-poindexter, thanks!

I unfortunately I have not received an email.  If you don’t mind, please resend via contact on nvisionative.com.

**Comment by thabaum** [comment]
I think we can come up with a solid solution that allows the old and the new to exist and allows an administrator to choose.  Then they can put in requests to a mod developer to make the changes for the new setting in an upcoming release but run things as normal until they make the changes.

All this should be noted and pushed to be done, if they don't do it, it should be on them not us as a community to suffer drawbacks.  Version 9 should be rock solid here by 10.   Everyone can stay here for a while or a long while if they like and things work well for them as is.

Version 10 and 11 expect some changes and announce them as soon as they are known.

I am almost feeling that a new module needs made for these features to just leave the old intact and introduce new MVC or SPA modules for everything that gets used for is for adding to sites.  These new modules can have the new class naming convention.   And any other classes possibly can be modified in DNN platform with the added classes however modules that are going to get replaced anyhow maybe skip working on those.

**Comment by thabaum** [comment]
the default.css file is another topic that relates... I almost feel there can be two default css classes and you can choose which one you want to use. Modern or legacy.  Later get rid of legacy in 11.

**Comment by Accuraty** [comment]
A late mention in the discussion. I have worked on projects recently using BEM Naming and completely fallen in love. Its quick/easy to learn, easy to follow, and VERY helpful after the fact (months later after you forget what you did and why).
[BEM Naming](http://getbem.com/naming/)

**Comment by thabaum** [comment]
I have been looking at BEM naming.  It is one of them I feel works well as well.  Never late here every little bit of discussion helps IMO anytime!

**Comment by Timo-Breumelhof** [comment]
> 
> 
> the default.css file is another topic that relates... I almost feel there can be two default css classes and you can choose which one you want to use. Modern or legacy or even both for transition... Later get rid of legacy in 11. Maybe call the it core.css or default-core.css

DNN already has functionality for "CSS versioning". I'm not sure anybody is using it but AFAIK you can  load the DNN7 default.css in DNN9 if you want . @donker added this for DNN8 I think

**Comment by roman-yagodin** [comment]
> 
> could be class="content-pain pain"
> 

Cool typo! :+1:

I'm not sure about the details, but some standardization is needed for sure. I think I could live with mix of old and new classes for some time, especially in new rules are carefully worked out and documented, and transition path is clear. I also think this way you will give new rules some time to settle down.

**Comment by valadas** [comment]
And on a sidenote, I have work in progress reducing default.css and moving stuff that is not needed globally into it's more appropriate location.

**Comment by thabaum** [comment]
good explanation of BEM Methodology [ here](https://www.toptal.com/css/introduction-to-bem-methodology)

I think it is a bit long winded CSS but it serves a purpose for a large project with a community team.  

@Accuraty seems like BEM.  I can get use to it, and it seems like it fits the project.

If some other naming style is preferred over BEM please speak now maybe we can hold a survey on the community site?  Or if we can all agree here now just put a thumbs up for BEM and move forward with how and when to do it in more detail.

**Comment by valadas** [comment]
> hold a survey on the community site
Any decisions on this matter would need to be approved by the Technology Advisory Group, even though this is CSS only it has a potential for huge breaking changes with everything of hours and of third parties. Again if we just add classes without any real good purpose and we strip the old ones in Dnn11 again with no other purpose than following some opinionated class name convention. I would vote against that and depend my point tooth and claws. There is some stuff we take the general public opinion on but this has too much implications IMO and needs to be decided by the ones that will be dealing with broken stuff and complaints and maintenance. And all that just for a naming style which is just a preference, I don't see a problem that needs to be fixed here.

> such as getting all the mod vendors on board
This will not happen, never did, never will. Been there, done that.

>Personally current DNN css names irritate me... things are all over the place and just not what you learn to do today
The current class names are not invalid, they respect all standards, there are enough in there to select anything you may need to select. BEM is a style, a convention on some opinion of what class names should be, it is just a preference. I see no purpose in making huge breaking changes (I don't even care in which Dnn version) just for matching a coding style. For every good article about BEM, you will find a matching bad article that says GPS is better https://medium.com/@jescalan/bem-is-terrible-f421495d093a , in the end this is an opinion.

We try really hard to not make breaking changes unless they are unavoidable, this is not the case.

**Comment by Accuraty** [comment]
Daniel V, I fully support your position. In, I think future DNN output, components, etc. need a serious "less is more" approach moving forward. I really think DNN should only output for functionality and keep the HTML/CSS as raw and standards (best practices) as possible. As an example, I do also feel that supporting a framework like Bootstrap can help that goal in the short term, but for the long term, Bootstrap could be a huge legacy debt. I really like where DNN is headed, I wish I could help more, for now though I am just a low-level fan with occasional opinions. Keep up the great work, thanks!

**Comment by thabaum** [comment]
Looking at these they have a page called "Coding Standards".

When I look up the different CMS for examples of what they use I get pages like the following:

[UMBRACO](https://our.umbraco.com/documentation/Development-Guidelines/Coding-Standards/)
[Drupal](https://www.drupal.org/docs/develop/standards/coding-standards)

and then do a search for DNN and pretty soon this topic is going to be what is getting hit on by search engine visitors.

I think this boils deeper into the root of DNN and really what defines it as an organized community team.  Disarray in respect to CSS and some other naming methodologies.

I like the rule of keeping the same one on each file at least.  Whatever is used stick with it.  and then we can add what is missing and leave what is there, fine tune a few things.  This leaves it very flexible but not easy to follow unless you are use to seeing all of them in many different ways.

Looking at the coding standards of those other two CMS systems that work with similar teams they pretty much give you two ways to do it.  lowerCamelCase for ID's and class-with-a-dash.

I think these are just fine for me.   This is what I was expecting to be honest and I would love to see what I am use to being used more accross the board.   The BEM and GPS like @valadas said is really a preference it will be hard to convince one or the other.

Maybe some of the stuff that really needs to stay classic dnn can simply stay but develop future with a coding standard we can all follow.

It's the wild west currently... community needs to agree for not just CSS but get the MOD devs that seem to dictate what happens in this area to come up with a nice solution for the community and soon.  I want to write code, i want to know how to and without asking...
