### ISSUE TITLE
Any plans to allow package upgrade from module itself

### ISSUE THREAD

**Issue by lisaied** [dnnsoftware/Dnn.Platform#3280]
## Description of problem
Is your feature request related to a problem? Provide a clear and concise description of the problem.

## Description of solution
Provide a clear and concise description of what you want to happen.

## Description of alternatives considered
Provide a clear and concise description of any alternative solutions or features you have considered.

## Screenshots
If applicable, provide screenshots to help explain your problem and/or feature.

## Additional context
Add any other context about the feature that may be helpful with implementation.

## Affected browser

* [ ] Chrome
* [ ] Firefox
* [ ] Safari
* [ ] Internet Explorer
* [ ] Edge

**Comment by mitchelsellers** [comment]
This is a place for issue reporting, please utilize the community forums for questions/help.

**Comment by lisaied** [comment]
I know there is no such a feature in latest DNN, Its a Feature request.
