### ISSUE TITLE
Remove Cancel from User Login

### ISSUE THREAD

**Issue by thabaum** [dnnsoftware/Dnn.Platform#3281]
does anyone use the cancel button and how do you remove it if you don't want to see it?

**Comment by valadas** [comment]
It is useful for when the login is in a dialog.

**Comment by thabaum** [comment]
so how do you remove it?  If in a dialog you mean a popup?  If I remove it from the skin it fails.

All modern sites I see have just a sign in... this is what I want.  Popups you either click an X or click off the logon box and it closes.

I see no need for Cancel button

![image](https://user-images.githubusercontent.com/13577556/68717122-c051c000-055a-11ea-9f90-4d34e011fdd8.png)

I can bring up all of them I can find no cancel buttons. So how do I do it?  Is there a way to turn it off?  If not there should be IMO.  This is stopping everyone from not being able to have a modern looking login, unless you can tell me how to remove it easily without massive work or breaking changes.

**Comment by valadas** [comment]
Simple css selector with a display:none; would hide it. What I am scared about is that the login experience is extensible and third party extensions might rely on that cancel button which could make it a breaking change.

```
a#dnn_ctr_Login_Login_DNN_cancelLink {
    display: none;
}
```
