### ISSUE TITLE
update.dotnetnuke.com 503 Service Unavailable

### ISSUE THREAD

**Issue by soheilkheiri** [dnnsoftware/Dnn.Platform#3284]
## update.dotnetnuke.com 503 Service Unavailable

The service is experiencing problems in the following sections :

**Extensions** > Upgrade? Incorrect link shows

**Security** > Security Bulletins > Error

**error :** 
Could Not Connect To http://update.dotnetnuke.com/security.aspx?type=Framework&name=DNNCORP.CE&version=090401. You Should Verify The Source Address Is Valid And That Your Hosting Provider Has Configured Their Proxy Server Settings Correctly.

**Comment by mitchelsellers** [comment]
This is a known issue that DNN Corp is working on.

In version 9.4.3 we will be switching this to the new Community driven one.

**Comment by soheilkheiri** [comment]
Until the new version makes these changes. Please also enable this previous service so that we have at least enough time to update our sites

**Comment by mitchelsellers** [comment]
They are working on it.

However, it should be noted that this does not have any impact on your ability to manage/update the sites.

**Comment by valadas** [comment]
I am closing this issue since it is a network issue and nothing we can fix in this repository. If I am wrong about closing it, feel free to reopen or comment...
