### ISSUE TITLE
Misspelled Class - in UserControls / PersonaBarContainer.ascx

### ISSUE THREAD

**Issue by jeremy-farrance** [dnnsoftware/Dnn.Platform#3288]
## Description of bug
Someone else noticed an odd typo/misspelling and hopefully it is a simple fix. Maybe not?
 
See the image below, See the extra `L` on 'persona-Bar' ? Someone accidentally typed 'personal'

## Screenshots
![image](https://user-images.githubusercontent.com/653301/68814598-dcc72880-063e-11ea-92d8-47180d1ee6cc.png)

Here is a [direct link to the file](https://github.com/dnnsoftware/Dnn.Platform/blob/development/Dnn.AdminExperience/Library/Dnn.PersonaBar.UI/admin/personaBar/UserControls/PersonaBarContainer.ascx)

## Additional context
Note that Daniel Valadas took a brief look at it and seemed to quickly determine that this *IS* a breaking change. Hopefully he will comment?

## Affected version
* [x] 9.4.2 alpha build
* [x] 9.4.1 latest supported release

## Affected browser
- browser is not relevant

**Comment by thabaum** [comment]
sounds like a personal issue to me :)

**Comment by valadas** [comment]
As much as it is a type and should be corrected, it could be a breaking change for third parties relying on that wrong spelling. In my opinion we could add the correct spelling on top of keeping the wrong one pretty much any time and then remove the wrong spelling after at least one full version. Like add the correct one now and remove the wrong one in Dnn10... Thoughts?

**Comment by bdukes** [comment]
Yes, let's add the corrected `class` now, and later remove the typo `class`

**Comment by thabaum** [comment]
We are discussing new naming class convention... could this wait?  Maybe it can follow the new community guidelines if we can agree on one.

**Comment by valadas** [comment]
Well, I am not picky on class names, but yeah if there is some sort of standard agreed upon I don't mind, this is just a typo so nothing rush.

**Comment by thabaum** [comment]
I think stick to the way the page is putting the correct one first... might look funny for a while... say 3-4versions probably before someone removes it potentially :)

I would like to see a Coding Standards for anything made in the future that can be held to it.

**Comment by thabaum** [comment]
Do you think putting a comment above it to use the new class in the file as well to help avoid someone thinking they can use it?

**Comment by valadas** [comment]
I think we just need to document this as a breaking change in the release notes of the first version that introduces the new class name and the first version that removes the old class name... Module developers should follow the release notes of the platform they are building their solutions on... Honestly I think there might only be a handful of modules affected by this change, but just to err on the safe side.
