### ISSUE TITLE
Persona Bar Modules might not uninstall when the Persona Bar Group Package is installed

### ISSUE THREAD

**Issue by thabaum** [dnnsoftware/Dnn.Platform#3292]
https://user-images.githubusercontent.com/13577556/68883676-5c4c0a80-06c6-11ea-86c0-6d05129dfb31.png

Trying to remove all of these took a lot of time yesterday, DNN has to restart or something as i have to wait about 5 minutes between each uninstall... and then there is the one without the trash can.

**Comment by thabaum** [comment]
![image](https://user-images.githubusercontent.com/13577556/68886003-16de0c00-06cb-11ea-9d8c-b0d8a8538062.png)

**Comment by thabaum** [comment]
I think Brian had a fix for it here: https://github.com/dnnsoftware/Dnn.Platform/issues/2993

I was hoping to get a "Known Issues" on something like dnndocs.com to help build awareness of the issue and know how to resolve it...   I keep referring to this for all my installs when I find them... a lot of time digging around I could spend not putting this issue up...

**Comment by valadas** [comment]
What is the upgrade history? This was an issue in an RC that got resolved at some point before the official release. Do you have some steps to reproduce this issue not involving an RC?

**Comment by thabaum** [comment]
It is one of my older installs... version 7.0

**Comment by thabaum** [comment]
For version 9 upgrades :

9
901
902
910
911
920
921
922
930
931
932
940
941
942

I could of possibly put a beta package on it sometime in the 9's

**Comment by valadas** [comment]
Yeah, for beta packages (RCs) it is not recommended for production use and if there was any RC in that upgrade path, this is the reason, I remember there was this issue in an RC. If you can replicate using an upgrade path that does not use RCs, then please open a new issue with the upgrade steps to reproduce. Thanks.

**Comment by thabaum** [comment]
I was told RC's and versions should match and work with the upgrade paths from @mitchelsellers   I guess this is wrong assessment currently.

I am not saying I did a RC on it but I might have...  I do have some other sites I can test with that are still back a few version...

**Comment by thabaum** [comment]
Is it ok to down the version in the database and then run an upgrade to make sure everything is up to par?

**Comment by sleupold** [comment]
@thabaum 
it is likely, but there is no guarantee, as it hasn't been tested.
