### ISSUE TITLE
DDR Menu & No TabID in 9.4.x

### ISSUE THREAD

**Issue by brewadmin** [dnnsoftware/Dnn.Platform#3299]
## In the latest verison of DNN 9.4.1 there is no way to find the TabID in the pages admin area

Problem: You need the TabID to locate the Node for the DDR to create vertical menus in Mandeeps Tahoe skin. (And we use these extensively - great feature)

## Steps to reproduce
List the steps to reproduce the behavior:

## Current result
Explain what the current result is.

## Expected result
Provide a clear and concise description of what you expected to happen.

## Screenshots
If applicable, provide screenshots to help explain your problem.

## Error log
Paste the error log that is related to this issue.

## Additional context
Add any other context about the bug that may be helpful for resolution.

## Affected version

* [ ] 10.0.0 alpha build
* [ ] 9.4.2 alpha build
* [ ] 9.4.1 latest supported release

## Affected browser

* [ ] Chrome
* [ ] Firefox
* [ ] Safari
* [ ] Internet Explorer
* [ ] Edge

**Comment by valadas** [comment]
This is already logged by yourself as #3026
