### ISSUE TITLE
Build produces NuGet warning NU5048

### ISSUE THREAD

**Issue by bdukes** [dnnsoftware/Dnn.Platform#3303]
## Description of bug
The build process produces NuGet warnings when building the NuGet packages

## Steps to reproduce
List the steps to reproduce the behavior:
1. `./build.ps1`

## Current result
NU5048

## Expected result
No NuGet warnings

## Additional context
The `iconUrl` property of the nuspec file is deprecated, it's recommended
to add an `icon` property, which points to a file within the package,
while also retaining the `iconUrl` property for older clients.
See https://docs.microsoft.com/en-us/nuget/reference/nuspec#iconurl

**Comment by valadas** [comment]
Merged
