### ISSUE TITLE
Cloning modules breaks page module positioning

### ISSUE THREAD

**Issue by leedavi** [dnnsoftware/Dnn.Platform#3309]
## Description of bug
When cloning a module from another page the other modules on the page, of the same type, are also moved into the pane that the new clone is added to.

## Steps to reproduce

1. Clear page.
2. Add a html module.
3. Create another page.
4. Add a html modules to the top pane.
5. Add an "Existing module", select the first page and first module.  Then position into the content pane.

* When selecting a module to clone, ensure you have unchecked "copy module"

## Current result
The module in the top pane and the new clone are BOTH added to the content pane.  i.e the top pane module is moved from the top pane to the content pane.

## Expected result
Only the newly add clone should be in the content pane.

## Additional context
We're not sure if it's related, but the import of a page with modules (previously exported) also seems to break the page.

## Affected version
v9.4.1 release

**Comment by valadas** [comment]
Duplicates #2289

**Comment by leedavi** [comment]
I still get this issue in DNN9.4.1 ??

**Comment by Timo-Breumelhof** [comment]
@leedavi  it's closed because it was already logged see #2289

**Comment by leedavi** [comment]
@Timo-Breumelhof  Ah! yes, I saw the "Close" on 2289 at the bottom and wrongly assumed it had been closed, it'as actually been reopened.
