### ISSUE TITLE
Switching between sites and saving custom CSS

### ISSUE THREAD

**Issue by thabaum** [dnnsoftware/Dnn.Platform#3310]
## Description of bug
The CSS stylsheet is saved across all sites potentially for one site, and this site you are on might not be the default site in focus that is first selected so you have to switch to the site.

## Steps to reproduce
List the steps to reproduce the behavior:
1. Go to CustomCSS
2. Edit CSS for a different site
3. CSS is saved for both sites

## Current result
Odd behavior with selecting the site to edit css and saving the custom css.

## Additional context
I see changes happening to both css for two sites.  I have not tested with a 3 site instance yet.  Something to look for and be aware of not sure if it is just me...

## Affected version

* [ ] 10.0.0 alpha build
* [ x] 9.4.2 alpha build
* [ ] 9.4.1 latest supported release

## Affected browser

* [ ] Chrome
* [ ] Firefox
* [ ] Safari
* [ ] Internet Explorer
* [ ] Edge

**Comment by sleupold** [comment]
did you verify by checking the file dates of portal.css files in the root folder if each website?

**Comment by thabaum** [comment]
I will take a closer look at this one, just seems like when I go to edit the css of the site I am on which is the first site I created, the second site is the CSS file I am editing.

If i switch and save it, it ends up saving to both files, or it is just showing me the one file for both sites?! but I think it changes.  Just some odd behavior I need to play with it more.  It may just be a combo of me and the file of the site not being the site I edit first.  I have to switch it.  I will also test on more installations.

**Comment by thabaum** [comment]
I suppose the issue is here that the Custom CSS file that is selected first is by alphabetical order instead of selecting the portal you are currently using first, or the last selected Custom CSS site file which would be nice.  I just have to remember to look at which one is selected each time and not assume it will be either of those I would expect from a user point of view.  This can be open/closed as it is on my todo list now no worries.   I need to know how to fix this type of stuff...  I can always create the issue when I have the fix.  If someone can do this easily please do it as I have some other things to work on first.

**Steps To Reproduce:**

1. Create two website portals with your primary first portal you create being something that starts with a letter last in the alphabet such as ZebraZooAnimals.com or Z-Domain.com and this is your primary portal you like to log into as host.
2.  Create a second website and name it AlphaOmegaSoup.com or A-Domain.com if not then a domain name that starts with a letter that comes before then letter Z when you sing the alphabet song.
3.  Hover your mouse over the gear in the persona bar to bring up settings.
4.  Point and click your mouse arrow over the Custom CSS settings persona bar option.
5.  In the Custom CSS form you should see that the domain you just created in step 2 of this procedure is presented for editing the css of the site.

**Expected Results**
A.  The site you are currently working on is presented first option in the dropdown. 
B.   If you have just edited and saved a site's Custom CSS remember which site was edited and keep that one selected.  

It works as it is, just would be nice if A or B or A + B was happening IMO.  You can close it as it is just something I will need to get used to until someone forks out a fix.

**Comment by thabaum** [comment]
I believe the same issue is happening to Site Settings when changing sites.  Sometimes when you change sites or revisit the page the settings shown or the CSS shown is for the first site even if you have a different site selected.  It is just a bit strange behavior I think they may be related.  I will run more testing on changing through the site settings when you have more than one portal on an installation as this is where things get a buggy feeling.

For example I was on a newly created site in site settings and the alias shown was for the first portal in the list no matter what I changed it to.  I had to do a few refreshes changing the sites in site settings to finally get the site I was working on settings to show up.  Just a little more info on the issue I think they relate to how the refreshing of items happens when selecting different sites.  I will create another issue once I confirm this however something to look into.

On another note I use Firefox a lot so that maybe a cause of the issue if it is browser related I will test more next week.   I have a lot of work to do in this area so I will be able to test on production installations.

**Comment by valadas** [comment]
It happens in a couple places where there is either a sites or languages selector, if you switch tabs, change site, then come back to the other tab, it is my usual "workaround", but yeah, this is a bug, changing sites should invalidate the currently displayed data.

**Comment by thabaum** [comment]
https://github.com/dnnsoftware/Dnn.Platform/pull/3515

I seen when I went to site settings similar issue happening where the default portal settings was in the site settings fields viewable when the persona bar page opened but the "Editing Site" was on the site I was logged into which was not the default portal.  I have to be sure to switch around off and back on the site then the fields populate with the correct domain.

Maybe these are related issues here with something similar needed for a solution to cure this as well?

**Comment by tingung** [comment]
Hi @thabaum ,

Yes. The first click of "Site Settings" always load the current site instead of the select site. It is a bug which #3515 is trying to resolve. The current workaround is to change the site and back to the original site to ensure it is loading the correct site information.

**Comment by valadas** [comment]
@thabaum do you have some time to test this issue using this build https://dev.azure.com/dotnet/DNN/_build/results?buildId=27585&view=results and let us know if it solves this issue too...

**Comment by thabaum** [comment]
Sorry missed the chance to test the build you sent. 

Switching between sites issue is resolved in 9.6.

The first click of "Custom CSS" selects the first site in alphabetical order instead of the site you are logged into.

This can be considered an issue however saving CSS This is a different issue than what is being reported here.  This current ticket issue has been resolved.  

I will close this for now maybe open new one later.
