### ISSUE TITLE
Unable to save changed schedules (Version 9.3.2)

### ISSUE THREAD

**Issue by KenTombs** [dnnsoftware/Dnn.Platform#3313]
##Description of bug
Provide a clear and concise description of what the bug is.

Making a settings change to the portal scheduler tasks can be saved (apparently).  A different time, enable/disable etc. 

## Steps to reproduce
List the steps to reproduce the behavior:

1. Log in as host.
2. From Persona bar go to scheduler panel.
3. from TaskQueue/scheduler/history go to scheduler.
4. go down the page to the desired Task Name.
5. click on edit
6. make desired change to settings. 
7. There is no 'save' panel shown and attempts to move away ask to lose current changes yes/.no.
8. Unable to find a mechanism to save changes.

Have repeated same with scheduler stopped, same result.

## Current result
Explain what the current result is.

Unable to saved changes to a scheduled task or suspend it.

## Expected result

Save changes to a scheduled task name or suspend it.

## Screenshots
If applicable, provide screenshots to help explain your problem.

![image](https://user-images.githubusercontent.com/46649875/69129772-65b2e980-0aaf-11ea-892f-b23f8a4f2717.png)

## Error log
Paste the error log that is related to this issue.

## Additional context
Add any other context about the bug that may be helpful for resolution.

## Affected version
9.3.2 in production with Azure SQL.

## Affected browser
Chrome/Edge

**Comment by valadas** [comment]
I cannot reproduce on 9.4.0 and 9.4.2 instances, I would suggest to upgrade to begin with I remember there was a fix for the wrong height of expandable panels that may be what you are experiencing.

**Comment by sleupold** [comment]
AFAIK this problem had been solved meanwhile (DNN 9.4.x and up)
