### ISSUE TITLE
Visualizer - Asset source embeds absolute path instead of relative path

### ISSUE THREAD

**Issue by kletendre** [dnnsoftware/Dnn.Platform#3317]
## Description of bug
When you create a visualizer which has the ability to upload image assets it uploads images using the full url. Example:  dev.websitename.ca/images/image.jpg .
The issue occurs when your site is no longer in development and modify your domain so that it is now https://www.websitename/images/image.jpg.
The location of the asset stays the same as when it was uploaded, which results in the image or document not being displayed. If you upload a new image it will be displayed because it is uploaded using the current path.
[Header Image - with  Search (2).zip](https://github.com/dnnsoftware/Dnn.Platform/files/3865092/Header.Image.-.with.Search.2.zip)
(https://user-images.githubusercontent.com/57957944/69168420-a36e3d00-0ac4-11ea-9742-69b8c1ae7475.png)

In this example the image displays properly as it has been uploaded on this domain. However please note in my example that the full path is being included.

## Steps to reproduce
List the steps to reproduce the behavior:
1. Go to '.the header image visualizer  and install within your dnn instance we are 9.3.7.'
2. Add a new image,put in an images title,then click on upload image, upload an image from your computer , publish
3. image will be displayed
![image]
4.Go to site settings add a new site aliases , remove the old alias.
5. Go back to page which is displaying your visualizer content. Image source will be using the full path which was originally used to upload the file instead of the relative path.
![image](https://user-images.githubusercontent.com/57957944/69169238-07453580-0ac6-11ea-876c-fdf4b4191a7f.png)

## Current result
Image source will be using the full path which was originally used to upload the file instead of the relative path.

## Expected result
image source should use relative path...example
/image/image.jpg

## Screenshots
If applicable, provide screenshots to help explain your problem.

## Error log
no error...

## Additional context
Add any other context about the bug that may be helpful for resolution.

## Affected version
We were on 9.3.0 have since upgraded to 9.3.7
EVOQ CONTENT
v. 09.03.07 (1)
4.6
.NET FRAMEWORK

* [ ] 10.0.0 alpha build
* [ ] 9.4.2 alpha build
* [ ] 9.4.1 latest supported release

## Affected browser

* [ ] Chrome
* [ ] Firefox
* [ ] Safari
* [ ] Internet Explorer
* [ ] Edge

**Comment by bdukes** [comment]
Please report issues with Evoq to https://www.dnnsoftware.com/services/customer-support.  If there is a related bug in DNN Platform, please document the steps to trigger the issue without using Evoq.  Thanks!
