### ISSUE TITLE
Google Analytics TrackingID is stored in lowercase

### ISSUE THREAD

**Issue by coretoco** [dnnsoftware/Dnn.Platform#3318]
## Description of bug
When adding the analytics tracking code in analytics connector, it will be stored in lowercase. This makes analytics not tracking anything.

## Steps to reproduce
List the steps to reproduce the behavior:
1. Go to 'Settings' --> 'Connectors'
2. Click on 'Google Analytics' --> Edit
3. Enter Google TrackingID (eg UA-123456789-0)
4. Click 'Save'

## Current result
The 'SiteAnalytics.config' in website root directory will contain the TrackingID in lowercase: (ua-123456789-0)

## Expected result
The 'SiteAnalytics.config' in website root directory should contain the TrackingID in an unchanged form: (UA-123456789-0)

## Affected version
* [x] 9.4.2 latest supported release

## Affected browser
* [x] All Browsers

**Comment by coretoco** [comment]
I will provide a fix and a pull request today

**Comment by david-poindexter** [comment]
@coretoco - I just worked with @mikesmeltzer (the original developer of the GA connector) and here is what I wanted to clarify.  The connector will respect the entered case for the TrackingID and save it accordingly.  This was done in case Google changes their requirements in the future.  

After some testing, it seems having the TrackingID saved as lowercase still allows Realtime analytics tracking, but fixing the casing to uppercase allows full feature.

Great find!  Will review the PR now.

**Comment by valadas** [comment]
Merged

**Comment by valadas** [comment]
@david-poindexter soooo, did I close this too soon or the PR that got merged is ok to resolve this issue?
