### ISSUE TITLE
Upgrade issue with Site Settings->Site Info and Site Settings->Site Behavior

### ISSUE THREAD

**Issue by mathisjay** [dnnsoftware/Dnn.Platform#3323]
I noticed this issue when upgrading a site from 7.4.2 to 9.4.1, but I suspect the root issue came from before 7.4.2

The symptom is the both Site Settings->Site Info and Site Settings->Site Behavior will continously be trying to load a resource---forever.    Inspecting the Network traffic, you can see the same HTTP request over and over again.

The cause seems to be that PortalLocalization.CultureCode is not formatted in the correct case.

In my instance, we were upgrading from a old DNN version (like 4 or 5 originally).

CultureCode was set to 'en-us'.  This seemed to work just fine up until 7.4.2 (possibly 8?), but not in 9.4.1.

This is easily reproduced with a clean install of 9.4.1.  Simply change PortalLocalization.CultureCode from 'en-US' to 'en-us' and watch the fun ensue when trying to load Site Settings.

I'd suggest some kind of script  on upgrade that makes sure the CultureCode value is properly cased.

**Comment by valadas** [comment]
There was another issue for this bug and I could not reproduce it in 9.6.2. If this is still a problem after upgrading, please comment and I will reopen.
