### ISSUE TITLE
users-bundle.js does not exist but called for in Users.js

### ISSUE THREAD

**Issue by thabaum** [dnnsoftware/Dnn.Platform#3327]
## Description of bug
users-bundle.js is called to load in users.js but does not exist in solution

`        util.loadBundleScript('modules/dnn.users/scripts/bundles/users-bundle.js');
`

## Screenshots
If applicable, provide screenshots to help explain your problem.

![image](https://user-images.githubusercontent.com/13577556/69375970-4d350180-0c5e-11ea-998b-951511ff4cc6.png)

plus the other files showing in explorer are missing, not showing in solution online or in my local project such as UsersCommon.  It looks true for all of the modules.  So if they do not exist should they be used in all the feature.js files for personaBar features?  Is this by design?
**MISSING JS FILES**
Licensing
Prompt
Roles
Security
Sites
SiteSettings
TaskScheduler
Themes
Users
Vocabularies
**HAVE ALL JS FILES:**
SqlConsole
RecycleBin
Pages
Extensions
CSSEditor
Connectors
Config Console 
AdminBar

**Comment by bdukes** [comment]
Have you run `./build.ps1`?

**Comment by thabaum** [comment]
I dont see them online in github,  I can try it, is that what I am missing here?

**Comment by thabaum** [comment]
when i pulled up 9.4.x branch those files do not exist, but maybe I am missing something here.  Thanks

**Comment by bdukes** [comment]
Yeah, those files are dynamically generated

**Comment by thabaum** [comment]
ok I figured that might be the case, it has been many moons since I did this.  I will close.  I figured they would exist in GitHub to view as well.  Live and learn my friend.

**Comment by thabaum** [comment]
![image](https://user-images.githubusercontent.com/13577556/69377673-a0f51a00-0c61-11ea-9203-43e71475d920.png)
I have ran these but I need to understand where to run that command

**Comment by bdukes** [comment]
You'll need to open PowerShell, get to the folder where you've cloned the repo (e.g. `cd C:\repos\Dnn.Platform`) and then run the build script, `./build.ps1`

**Comment by thabaum** [comment]
i was thinking PS, i use a lot of that no problem.  i was looking that up seen discussions on PS just now so that verifies to me what to do.  Thanks saved me some time there 👍

**Comment by valadas** [comment]
FYI the build documentation is at https://github.com/dnnsoftware/Dnn.Platform/blob/development/.github/BUILD.md it is something that is constrantly evolving and we might get to a point where we can just build in release or debug inside visual studio one day.
