### ISSUE TITLE
[Dependency Injection] Unable to create instance of PersonaBarContainer

### ISSUE THREAD

**Issue by daguiler** [dnnsoftware/Dnn.Platform#3328]
## Description of bug
Evoq calls `PersonaBarContainer.SetInstace(IPersonaBarContainer, bool)` to override the default Persona Bar at application startup. The passed in `IPersonaBarContainer` argument is an instance of a class that derives from `PersonaBarContainer`.
Since 697a54e36808850e13c9149fde79985ae4646293, `PersonaBarContainer`'s constructor requires a `INavigationManager` argument (which is a breaking change for Evoq).
Creating an instance of `INavigationManager` during application start up is not possible, because:
1) The app startup event is not a DI friendly context
2) `Globals.DependencyProvider` is internal to core DotNetNuke assemblies only, so I can't call `Globals.DependencyProvider.GetRequiredService<INavigationMananger>()` from there.
The alternative is to create and register our derived PB container instance using the recommended `IDnnStartup` method, but then it would be ignored by `PersonaBarContainer.Instance` property.

## Steps to reproduce
1) Create a project with references to core DotNetNuke assemblies
2) Add a class that implements `IAppEvents`
3) Implement `ApplicationBegin()` method
4) Invoke PersonaBarContainer.SetInstance(IPersonaBarContainer, bool) from there

## Current result
In order to call above method, an instance of `INavigatorManager` is required, which cannot be obtained from DI.

## Expected result
There should be a way to derive from `PersonaBarContainer` and call the base constructor, or `PersonaBarContainer.Instance` should get the object from DI.

## Affected version

* [X] 10.0.0 alpha build
* [X] 9.4.3 beta build
* [X] 9.4.1 latest supported release

**Comment by donker** [comment]
Merged
