### ISSUE TITLE
[Dependency Injection] Reliably override default instances through DI

### ISSUE THREAD

**Issue by daguiler** [dnnsoftware/Dnn.Platform#3335]
## Description of problem
The IAppStartup pattern gives 3rd party vendors a means to register types and instances with the DI framework. This poses the following question:

#### What happens when more than one instance is registered under the same contract (interface)?

1. Is the new registration overriding any existing instance under same contract?
1.1 If so, how to reliably override a platform instance without running the risk of a race condition? The race condition exists because the winning instance is the one registered the last, but no registration order or priority is defined or enforced by DNN.

2. Is the new registration appended to other existing instances under the same contract?
2.1 If so, which instance is then returned at runtime? Is it a LIFO scheme? If it is, then in practical terms it's the same as overriding.

## Description of solution
Maybe the solution is to ensure all DNN built-in types are registered first.

## Description of alternatives considered
Other alternatives include using named instances and then retrieving instances by name, but this is discouraged by most DI frameworks and I'm not sure if this would actually solve the problem.
Maybe a priority scheme where built-in DNN instances are registered with a certain priority and then 3rd party instances can choose a higher priority.

## Additional context
A case for this is overriding the Persona Bar container. This was explained here: https://github.com/dnnsoftware/Dnn.Platform/issues/3328

**Comment by ahoefling** [comment]
Ensuring the DNN `IDnnStartup` implementations are registered first is something that needs to be done to ensure proper extensibility with Dependency Injection. @daguiler and I spoke about this yesterday and came to the conclusion there is a potential race-condition where a vendor `IDnnStartup` will execute prior to DNN. As far as I know it is ran by the order it is loaded into the AppDomain which is alphabetically.

@daguiler
> Other alternatives include using named instances and then retrieving instances by name

This is a great idea, and if we can come up with a way that follows `IServiceProvider` implementations for named constructor injection I would be all for supporting this. This is really worth researching for a 10.0 release and not right now.

**Comment by bdukes** [comment]
I'd like to find time to contribute this fix.
