### ISSUE TITLE
Test emails + Portal Creation Notifications use [Host:HostTitle] which is unable to be set in UI ( DNN Corp is default value)

### ISSUE THREAD

**Issue by thabaum** [dnnsoftware/Dnn.Platform#3345]
## Description of bug
Test emails use [Host:HostTitle] along some other email notifications.

## Steps to reproduce
List the steps to reproduce the behavior:
1. Go to test portal email smtp configuration
2. Send a test mail and it does not state it is coming from any site but a host title which happens to be DNN Corp

## Current result
The [Host:HostTitle] is used, and if using a host name there should be a UI place to set this possibly next to the host email in Server Settings?

## Expected result
Test emails and other email notifications are sent using something that can be set.  There are other templates currently use HOST:HOSTTITLE

## Screenshots
If applicable, provide screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/13577556/69655931-71149080-102c-11ea-919e-f9a8cde679a6.png)

![image](https://user-images.githubusercontent.com/13577556/69656031-a0c39880-102c-11ea-9ef6-db00f8b39f86.png)

## Error log
Paste the error log that is related to this issue.

## Additional context
The default HostTitle is DNN Corp.   So when sending notifications out for new website hosting portals and for SMTP configuration tests they use DNN Corp instead of a setting that can be set without having to manually set it in the database.

## Affected version

* [ ] 10.0.0 alpha build
* [x ] 9.4.2 alpha build
* [ x] 9.4.1 latest supported release

## Affected browser

* [x ] Chrome
* [ x] Firefox
* [ x] Safari
* [ x] Internet Explorer
* [ x] Edge

**Comment by david-poindexter** [comment]
@thabaum great issue and I concur 100% - this is an issue that needs a fix.  I’d recommend we surface that field and allow it to be edited in the UI.

**Comment by valadas** [comment]
Should also not be Dnn Corp as default, I think just Dnn would be better as it makes it seam it comes from corp which is not the case.

**Comment by sleupold** [comment]
@valadas 
the default values for HostTitle and HostURL needs to be fixed in DNN template file (/install/DotNetNuke.install.config.resources)

**Comment by thabaum** [comment]
I changed to [Portal:PortalName] so it just used the portal name I was testing as you can see in the screenshot.

We should be able to set all of the host configurations.  I think they all need to be on their own tab under server.  Host Title, Host Email, Host Url, Host Header... anything that is related to the Host and not to a site/portal.

Also under persona bar Server would be a good place to add two tabs one for Host Settings and another for Site Groups.

**Comment by thabaum** [comment]
`I changed to [Portal:PortalName] so it just used the portal name I was testing as you can see in the screenshot.`

This could be another pull request to update the language file to use the portal name that is being tested to use the host/portal SMTP settings.  Any thoughts?

I went ahead made some changes for that file thanks @sleupold maybe @valadas can take a look make adjustments if needed.  I referenced DNNDocs and DNNCommunity.org in the file to replace help and host url.  Just trying to lighten the load a little and help... not a showstopper here...

**Comment by valadas** [comment]
Pr merged, thanks @thabaum , would you be able to submit another one to use [Portal:PortalName], I think this solution makes sense. There is always a portal, so I think that solution makes sense to me.
