### ISSUE TITLE
Send email to user after email verification is completed

### ISSUE THREAD

**Issue by vmasanas** [dnnsoftware/Dnn.Platform#3347]
## Description of problem
Currently, when you setup a portal to use Verified Registration, it means the user will be sent an email with a link they need to click in order to have their user fully active on the portal.

The problem is that most often than not you'd like to send a full welcome message maybe with extra information details to the user once he has verified his account. This cannot be done on the initial email, since the user has not yet verified the email and so is not yet a "valid" user on the site.

So it makes sense to have a second email to be sent when the user verifies his email.

## Description of solution
When using verified registration, send a confirmation email to the user after the email has been verified by using the link that the user has received on the initial registration email.

A new email template should be defined for this scenario as a means of confirming that the user has been approved.

## Description of alternatives considered
None

## Screenshots
Not applicable

## Additional context
Not applicable

## Affected browser
All

**Comment by sleupold** [comment]
Subject and Body may come from a resource key. If either or is empty, the message should not be sent.

**Comment by valadas** [comment]
@sleupold do you mean that this behaviour is already existing but the keys may be empty or is this a suggestion on how it should be implemented ?

**Comment by sleupold** [comment]
@valadas these are my ideas, how it should be implemented.

**Comment by valadas** [comment]
Cool, thanks, I'll tag that as an enhancement then...

**Comment by thabaum** [comment]
I like the ideas as well.  I will see if I can work this out sometime soon as I would love to have this feature added.  I have a few projects to hopefully move off my plate and that should free up some time to focus here a bit more and I will put this on my to do list unless someone can please beat me to it :)  It would be nice to work with a resx file along with an email to send.  I can actually visualize this process so maybe I can contribute here with a little time and luck!
