### ISSUE TITLE
Redirect after login doesn't work

### ISSUE THREAD

**Issue by wbonekamp** [dnnsoftware/Dnn.Platform#3348]
Redirect after login doesn't work when you select en specific page

## Steps to reproduce
List the steps to reproduce the behavior:
1. Go to Security
2. Click on Login Settings
3. Select page in list Redirect after login
4. Logout
5. Login

## Current result
Doesn't redirect to the selected page

## Expected result
Should go to the selected page after login

## Error log
No error in log

## Affected version
* [ ] 9.4.2 
* [ ] 9.4.1 

## Affected browser
All

**Comment by valadas** [comment]
I cannot reproduce this issue in 9.4.2

@wbonekamp which version of Dnn are you using? Are there other thing about this site that is out of the default install such as localization, authentication providers, third party modules, is this Evoq, etc ? Are you able to reproduce in a clean Platform 9.4.2 installation?

**Comment by bdukes** [comment]
I don't remember the exact details, but we've run into an issue with _redirect after login_ when there's a login module on all of the pages.  For some reason DNN was always ignoring that setting when it saw the login module.  Does that apply for your situation?

**Comment by wbonekamp** [comment]
No not on all pages, but we have selected a custom login page with the login module.

**Comment by wbonekamp** [comment]
We also had problems with the SEO setting url to uppercase/lowercase so maybe this is related to the issue... or the fact that the website is multilanguage dutch (nl-NL) english (en-US)...

**Comment by donker** [comment]
Superceded by #3661 ?

**Comment by valadas** [comment]
I am closing this issue in favor of #3661 because I think there might be a bit more details to reproduce the issue...
