### ISSUE TITLE
Unable to edit Module settings after moving Module to another page

### ISSUE THREAD

**Issue by aelibyary** [dnnsoftware/Dnn.Platform#3351]
## Description of bug
DNN Platform/Library/Entities/Modules/ModuleController.cs MoveModule only updates the tabid for TabModules table but not updating the tabid for ContentItems table for the same module

## Steps to reproduce
List the steps to reproduce the behavior:
1. From DB, find the latest module on the system 
`select top 1 ModuleID from Modules order by 1 desc`
2. Then, select the TabModules and the ContentItems based on that moduleID
```
select TabID from TabModules where moduleID = {moduleID from step 1}
select TabID from ContentItems where moduleID = {moduleID from step 1}
```
3. execute DNN Platform/Library/Entities/Modules/ModuleController.cs >MoveModule function giving it the moduleID, the TabID found on step 2, the new tabID , and the pane name of the new tabID
4. select Step 2 again and notice the returned TabID

## Current result
TabID of the TabModules has been updated while TabID of the ContentItems has not been updated.

## Expected result
both tables should have been updated by this function.

## Error log
[ERROR] DotNetNuke.Services.Exceptions.Exceptions - System.InvalidOperationException: This module does not belong to the page. Please move to the master page to change the module. at DotNetNuke.Entities.Tabs.TabChangeTracker.TrackModuleModification(ModuleInfo module, Int32 moduleVersion, Int32 userId)

## Additional context
Add any other context about the bug that may be helpful for resolution.

## Affected version

* [ ] 10.0.0 alpha build
* [ ] 9.4.2 alpha build
* [ ] 9.4.1 latest supported release

## Affected browser

* [ ] Chrome
* [ ] Firefox
* [ ] Safari
* [ ] Internet Explorer
* [ ] Edge

**Comment by valadas** [comment]
For context, this is described with an Evoq specific set of steps to reproduce, but the actual issue is with the content items tabId not being updated when moving modules to a new tab, which is part of the platform.
