### ISSUE TITLE
Editing Security related Email Messages

### ISSUE THREAD

**Issue by Timo-Breumelhof** [dnnsoftware/Dnn.Platform#3354]
#3319  Description of Problem
I have a client that manages a small community site (user are added manually in this case).
They would like to edit the messages that are sent out to users. While theoretically they could edit these messages, in practice it's a very cumbersome process IMO.
The localization editor is not a usable way for an Admin to edit the Message sent out on for instance, user registration, it's slow, complex and it's very difficult to find where the key is located.  (TBH I never use it myself and always go straight o the server to edit the resx files.)
I know there are alternative modules for registrations, but I think it would be good if at least this part would be easier to manage using DNN platform.

FYI, I would like to prevent this to become a (endless ;-) discussion on the localization editor and focus on a this  task and find a better solution for it. :-)

## Proposed Solution Option 1
I think it would be an improvement if we would add a "messaging" tab to  Security >Member Accounts where all user related messaging can be edited by an administrator.

Feedback?

## Affected version
* [ ] 10.0.0 alpha build
* [] 9.4.1 alpha build
* [x] 9.4.0 latest supported release

Example:
![image](https://user-images.githubusercontent.com/8999382/69897819-9c132300-1351-11ea-8479-8fb7f98c2e31.png)

**Comment by b-creative** [comment]
If one would change the registration settings... do you suggest changing the Messaging values back to default/deleting them, with a warning? Or leave them as they are? I ask this because the mails that get send out are based on this variable...

**Comment by Timo-Breumelhof** [comment]
I would suggest 
A. Add all message in this tab grouped by registration type and not switch any on or off depending on your settings
B. Add a warning to the location were you switch the registration setting sto check the messaging tab

**Comment by valadas** [comment]
Don't forget this is localizable text, it should just expose/save what is in the language resource files and have a language picker to edit the other languages...

**Comment by valadas** [comment]
Also, localization has scopes and fallbacks, I believe if the intention here is to easily change those messages for the site, it should live in Site Settings instead of Security so that we automatically have the site picker and language picker. Actually there is already a Messaging section, I believe adding it there is what makes the most sense:

![image](https://user-images.githubusercontent.com/6371568/70514721-1f770600-1b02-11ea-9c32-3bf50bff9353.png)

**Comment by Timo-Breumelhof** [comment]
@valadas hmm, that's an option too

**Comment by valadas** [comment]
Given all comments above about localization and fallbacks, i think this would be a massive task. I am closing this issue but if anyone intends to work on making this happen, please do comment and I will be happy to reopen.
