### ISSUE TITLE
Friendlyurl does unnecessary 301 for url that does not change

### ISSUE THREAD

**Issue by vincentparrett** [dnnsoftware/Dnn.Platform#3357]
## Description of bug
The AdvancedUrlRewriter performs an unnecessary 301 redirect when the eventual url does not change. 

## Steps to reproduce
Observe the network tab of a request with query strings when friendly url's are turn off and on. See screenshots below.  

## Current behavior
In my case, I have query params that I do not want rewritten as they are passed to an MVC module on a page, which expects the query params. I added those query params to the "Keep in Querystring Regular Expression", and that works, the resulting url is correct 

## Expected behavior
If the resulting url is the same as the original, no redirect should be done.   

## Screenshots
With Friendly Urls turned off :
![NoFriendly](https://user-images.githubusercontent.com/1037262/69921877-f398c680-14ea-11ea-93e6-a82899e9a6b9.png)

With Friendly Urls turned on
![WithFriendly](https://user-images.githubusercontent.com/1037262/69922201-5fc8f980-14ee-11ea-9ce9-231a345a66e2.png)

## Error information

In this case, it's causing an error on the page with the mvc module not loading, I haven't narrowed down what that error is yet (I will log a separate issue for that when I have more info).  I guess that error is a side effect of the 301, but in any event the 301 should not be happening.

## Additional context
This is occurring with my single sign on setup for discourse forums to DNN - it's been working well but something changed recently, not sure what but I have narrowed down the cause to the advanced friendly url feature causing a 301 during the login process.

## Affected version
* [x]  10.0.0 alpha build
* [x] 9.4.3 alpha build
* [x] 9.4.2 latest supported release 
* [x] 9.4.1 using this as 9.4.2 has a breaking change for some other modules we use.

## Affected browser
* [x] Chrome
* [x] Firefox
* [x] Safari
* [x] Internet Explorer
* [x] Edge

**Comment by vincentparrett** [comment]
I have found a work around for this, adding the page to the "Do Not Redirect URL Regular Expression" setting seems to have fixed the redirect and 500 error I was seeing. 

It still seems odd that a url that doesn't change during the rewrite process would result in a 301.

**Comment by dieterdtx** [comment]
I only just now found this thread, I was the one posting this on the Google Forum (since GSC does not have a real support). I will update my question there with the remark about file extension.

Thank you @EPTamminga for the rewrite solution.

**Comment by thabaum** [comment]
Something to possibly add to troubleshooting docs in dnndocs.com ?
