### ISSUE TITLE
Can't change password after enablePasswordReset="false"

### ISSUE THREAD

**Issue by wbonekamp** [dnnsoftware/Dnn.Platform#3364]
## Description of bug
We like to hide the reset password button on the login module.
So we found the solution: open web.config and set enablePasswordReset="false".
The reset button ins't visible anymore, great!

When you change this setting you also can't change the password of a DNN user (persona bar - users). It shows the alert: doesn't meet the security requirement of a password.

## Steps to reproduce
List the precise steps to reproduce the bug:
1. Open the web.config;
2. Set enablePasswordReset="false";
3. Open persona bar;
4. Open users;
5. Edit a user;
6. Change password;
7. Can't change: doesn't meet the security requirement of a password.

## Affected version
* [ ] 9.4.2 
* [ ] 9.4.1 
* [ ] 9.4.0 
* [ ] 9.3.2

## Affected browser
All

**Comment by mitchelsellers** [comment]
This is expected behavior or limitation of the MembershipProvider.  If this is set to false, you cannot reset the passwords.

We might want to find a workaround for this
