### ISSUE TITLE
Module Creator crashes

### ISSUE THREAD

**Issue by daguiler** [dnnsoftware/Dnn.Platform#3367]
## Description of bug
Module Creator crashes when added to a page.

## Steps to reproduce
1. Install DNN 9.4.3
2. Create a page
3. Add a Module Creator to the page

## Current behavior
Module crashes showing an error in the page.

## Expected behavior
Module should be created and added to the page without issues.

## Screenshots
![image](https://user-images.githubusercontent.com/30123437/70084072-676ec800-15ec-11ea-8b3c-d99d1785190a.png)

## Error information
```
DotNetNuke.Services.Exceptions.ModuleLoadException: The file '/DesktopModules/Admin/ModuleCreator/CreateModule.ascx' does not exist. ---&gt; System.Web.HttpException: The file '/DesktopModules/Admin/ModuleCreator/CreateModule.ascx' does not exist.
   at System.Web.UI.Util.CheckVirtualFileExists(VirtualPath virtualPath)
   at System.Web.Compilation.BuildManager.GetVPathBuildResultInternal(VirtualPath virtualPath, Boolean noBuild, Boolean allowCrossApp, Boolean allowBuildInPrecompile, Boolean throwIfNotFound, Boolean ensureIsUpToDate)
   at System.Web.Compilation.BuildManager.GetVPathBuildResultWithNoAssert(HttpContext context, VirtualPath virtualPath, Boolean noBuild, Boolean allowCrossApp, Boolean allowBuildInPrecompile, Boolean throwIfNotFound, Boolean ensureIsUpToDate)
   at System.Web.UI.TemplateControl.LoadControl(VirtualPath virtualPath)
   at DotNetNuke.UI.ControlUtilities.LoadControl[T](TemplateControl containerControl, String ControlSrc)
   at DotNetNuke.ModulePipeline.ModuleControlPipeline.LoadModuleControl(TemplateControl containerControl, ModuleInfo moduleConfiguration)
   at DotNetNuke.UI.Modules.ModuleHost.LoadModuleControl()
   --- End of inner exception stack trace ---
```

## Affected version
* [X] 10.0.0 alpha build
* [X] 9.4.3

**Comment by david-poindexter** [comment]
Per an offline conversation about the Console module, this seems to be related use of Install.aspx vs InstallWizard.aspx.  I just wanted to make that note here for reference.  @daguiler can probably provide more details if necessary.

**Comment by daguiler** [comment]
It would be great if someone was able to confirm that invoking /install/install.aspx results in an instance where both Console and Module Creator extensions are missing (both of which live in the /DesktopModules/Admin folder). And then installing via /install/InstallWizard.aspx (even with default options) you get an instance with both extensions correctly installed.

**Comment by bdukes** [comment]
Confirmed, installation via `/install/install.aspx?mode=install` is missing `/DesktopModules/Admin/Console` and `/DesktopModules/Admin/ModuleCreator` (and `bin` is missing `Dnn.Modules.Console.dll` and `Dnn.Modules.ModuleCreator.dll`).
[InstallerLog20200123 (via install.aspx, missing modules).txt](https://github.com/dnnsoftware/Dnn.Platform/files/4104684/InstallerLog20200123.via.install.aspx.missing.modules.txt)
[InstallerLog20200123 (via installwizard.aspx, modules working).txt](https://github.com/dnnsoftware/Dnn.Platform/files/4104690/InstallerLog20200123.via.installwizard.aspx.modules.working.txt)

**Comment by daguiler** [comment]
Ok, after a long, painful and exhausting (but successful) experience debugging the install process (perhaps only comparable to debugging Dnn.React.Common 😄), I finally got to the cause of this problem: #3287.
What I found is that this stored procedure is only executed by the /install/install.aspx process. The wizard does not run this step. So I wonder if this was of any use.
@donker can you verify this please?
Also, I don't think bumping the versions during the upgrade process was a smart idea. We now have one version number in the database and other version number in the zip files?

**Comment by daguiler** [comment]
I should probably explain why this created a problem with Console and Module Creator.
The thing is that by the time the install process reaches the part where the extensions are installed (and only in the /install/install.aspx scenario), the versions in the `Packages` table were already bumped by the `SetCorePackageVersions` stored procedure, so the install process decides that there is no need to install the module because it's already up-to-date.

**Comment by daguiler** [comment]
If I comment [this line](https://github.com/dnnsoftware/Dnn.Platform/blob/b69724450c84fa5176cff8fe399997462ae72b1d/DNN%20Platform/Library/Services/Upgrade/Upgrade.cs#L5863) out, the install process finishes successfully and both modules are installed.

**Comment by sleupold** [comment]
> Ok, after a long, painful and exhausting (but successful) experience debugging the install process (perhaps only comparable to debugging Dnn.React.Common 😄), I finally got to the cause of this problem: #3287.
> What I found is that this stored procedure is only executed by the /install/install.aspx process. The wizard does not run this step. So I wonder if this was of any use.
> @donker can you verify this please?
> Also, I don't think bumping the versions during the upgrade process was a smart idea. We now have one version number in the database and other version number in the zip files?

SetCorePackageVersions should not affect any component packed separately. IMO Console and ModuleCreator should be excluded from the sproc. AFAIK the other components are included in the Platform package and don't have an individual install process. 
Anyways, upgrading should work identically, using install.ascx or upgrade wizard.

**Comment by bdukes** [comment]
I agree with @sleupold, the intention of that stored procedure was to manage the version for extensions that aren't packaged.

@daguiler did you see a good reason why the two processes are so different?  Is there a simple change we could make to combine those two code paths?

**Comment by daguiler** [comment]
I don't see any good reason. AFAICT, deep down, they end up invoking the same code, but the sequence is different (notably, the extensions are installed earlier by the wizard). The wizard seems better implemented IMO. I think we should get rid of the current implementation behind Install.aspx and invoke the wizard steps instead.
