### ISSUE TITLE
Opening html module to edit removes data-plug-options

### ISSUE THREAD

**Issue by thabaum** [dnnsoftware/Dnn.Platform#3370]
## Description of bug
HTML module instance with content that includes `data-plugin-options="{'items': 1, 'margin': 10, 'animateOut': 'fadeOut'}"` will save the first time and all is well.  After you open it to edit again the editor removes that line inside a `<div>`

## Steps to reproduce
List the steps to reproduce the behavior:
1. Add an HTML Module to a page and put some div's inside the content source mode
2. Add `data-plugin-options="{'items': 1, 'margin': 10, 'animateOut': 'fadeOut'}"` and save
3. Edit the HTML module and view source
4. `data-plugin-options="{'items': 1, 'margin': 10, 'animateOut': 'fadeOut'}"` is missing and will not be saved the next time.
## Current result
`data-plugin-options="{'items': 1, 'margin': 10, 'animateOut': 'fadeOut'}"` is removed after you click edit on a HTML module instance.

## Expected result
`data-plugin-options="{'items': 1, 'margin': 10, 'animateOut': 'fadeOut'}"` is not deleted ever unless deleted intentionally.

## Screenshots
If applicable, provide screenshots to help explain your problem.

## Error log
Paste the error log that is related to this issue.

## Additional context
You have to re-apply the missing options with each edit/save of the html module

## Affected version

* [ ] 10.0.0 alpha build
* [x ] 9.4.3 alpha build
* [ x] 9.4.2 latest supported release

## Affected browser

* [x] Chrome
* [ x] Firefox
* [x] Safari
* [x] Internet Explorer
* [x] Edge

**Comment by mitchelsellers** [comment]
Sadly, this is a behavior of the CKEditor and not a behavior that we can change.  It is part of when/how it goes between the different modes.  It detects certain scripts and removes them.

**Comment by thabaum** [comment]
what version of CK editor is it?

**Comment by mitchelsellers** [comment]
This is managed in this repo: https://github.com/DNN-Connect/CKEditorProvider

I'd have to go digging to determine the CKEditor version

**Comment by thabaum** [comment]
I see a mention of this https://github.com/w8tcha/dnnckeditor/releases
which is not supported any longer and uses a newer version.  I see @bdukes there is some concern over version

**Comment by mikesmeltzer** [comment]
The default behaviour can be changed by modified the HTML Editor settings on a per site (or installation) basis can it not. The following blog post may help you with this.

https://dnncommunity.org/blogs/Post/2841/Help-DNN-CKEditor-is-cleaning-my-HTML
