### ISSUE TITLE
Email is below password fields on registration form

### ISSUE THREAD

**Issue by thabaum** [dnnsoftware/Dnn.Platform#3371]
## Description of bug
Provide a clear and concise description of what the bug is.

## Steps to reproduce
List the steps to reproduce the behavior:
1. Go to registration form
2. view order and see email is below the password fields.

## Current result
If you have to retype a captcha you might need to scroll up to re-enter passwords each time the code does not work.

## Expected result
Fields you may have to re-enter are close to the submit button.

## Screenshots
If applicable, provide screenshots to help explain your problem.

## Error log
Paste the error log that is related to this issue.

## Additional context
It would be nice to group the help icon and label together so they stick together if it is put on top of the text area.

## Affected version

* [ ] 10.0.0 alpha build
* [ ] 9.4.3 alpha build
* [ ] 9.4.2 latest supported release

## Affected browser

* [ ] Chrome
* [ ] Firefox
* [ ] Safari
* [ ] Internet Explorer
* [ ] Edge

**Comment by valadas** [comment]
PR merged
