### ISSUE TITLE
Upgrade from 9.4.1 to 9.4.3 - Persona bar unavailable

### ISSUE THREAD

**Issue by morelR** [dnnsoftware/Dnn.Platform#3377]
## Description of bug
Following upgrade from  9.4.1 to 9.4.3 the persona bar is not opening.  

## Steps to reproduce
List the precise steps to reproduce the bug:
1. Upgrade (I removed the Skin folder in the Install folder of the upgrade)
2.Install upgrade success
3.log as admin

## Current behavior
On mouse over / click nothing appear. Can't acces to the persona bar menu / can't see icons / nothing to be displayed

## Expected behavior
Links to page management / setting / ... appears. On mouse over of the DNN persona bar I can see version and other info.

## Affected version
 [X] 9.4.3 latest supported release

## Affected browser
 [X] Chrome
 [X] Firefox

**Comment by Timo-Breumelhof** [comment]
There are some suggestions in thread you could try:
https://dnncommunity.org/forums/aft/636

I would start with: "Sometimes deleting the resources files from the folder /DesktopModules/Admin/Dnn.PersonaBar/Resources helps"

**Comment by valadas** [comment]
@morelR I believe this was discussed in the forum thread and was resolved, if not feel free to reopen a new issue many of us have performed many of these upgrades without issues and most issues where because of some third party modules not really following best practices.
