### ISSUE TITLE
The required anti-forgery cookie "__RequestVerificationToken" is not present

### ISSUE THREAD

**Issue by meetmandeep** [dnnsoftware/Dnn.Platform#3380]
## Description of bug
The event viewer is flooded with hundreds even thousands of error messages indicating required anti-forgery cookie is not present. 

## Steps to reproduce
1. Create a simple Web API GET Method that has the [ValidateAntiForgeryToken] attribute. 
2. Disable cookies in your browser and hit this method to reproduce the error. 

## Current behavior
The request is denied which is the expected behavior; however, the error is logged in the Event Viewer. This is a huge problem because BOTS (such as Google) index sites several times every week and DO NOT have cookies enabled. This results in thousands of errors in event viewer. 

## Expected behavior
Deny the request since an anti-forgery cookie is not present; but do not log the error in Event Viewer. 

## Additional context
This issue appeared with DNN 9.x. In 8.x, the error is thrown but not logged in event viewer. 

## Affected version
* [x] 9.4.3 latest supported release
* [X] 9.4.2 latest supported release
* [X] 9.4.1 latest supported release
* [X] 9.4.0 latest supported release
* [X] 9.3.2 latest supported release

**Comment by thabaum** [comment]
I can confirm this issue.

**Comment by mitchelsellers** [comment]
Does anyone have a stack trace of this exception that they can provide?  And can we confirm that the behavior is the same in 9.4.3, where we have the fix for the Memory Leak that applies to WebAPI Modules?

Tracking the code for ValidateAntiForgeryToken itself, we don't log the error, there hasn't been much of change that impacts this.

Realistically, this is/should be logged as an error in some regard, as it could be flagging malicious usage.  (Yes bots will cause this, but it could be a far more malicious user)  Possibly we need to throttle etc.  

Just trying to find the root cause on this.

**Comment by thabaum** [comment]
> Realistically, this is/should be logged as an error in some regard, as it could be flagging malicious usage. 

I agree here I am sure they are malicious attempts.  When I see these logged it is from very strange bots that are not your normal google or bing bots.  And along with them I see attempts to connect to pages that are more related to wordpress admin pages.  I would like to use this as a way to detect them and block or ban them from using the site if possible.  I see pages such as domain.com/wp-admin.

For example on my test site I just got this error:
`12/05/2019 20:25:50
HTTP Error Code 404 Page Not Found
 
TabId PortalAlias www.d.com OriginalUrl /user/login Referer http://d 

TabId:

PortalAlias:www.d.com

OriginalUrl:/user/login

Referer:http://d.com/user/login

Url:http://www.d.com/user/login

UserAgent:Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:62.0) Gecko/20100101 Firefox/62.0

HostAddress:125.212.207.103

HostName:125.212.207.103`

**Following this page load exception:**

`Check
12/05/2019 20:25:50
Page Load Exception
 
AbsoluteURL /user/login DefaultDataProvider DotNetNuke.Data.SqlDataProvide 

AbsoluteURL:/user/login

DefaultDataProvider:DotNetNuke.Data.SqlDataProvider, DotNetNuke

ExceptionGUID:ce48f0d5-a0fe-4ed8-a1a7-82a892acafc3

ExceptionHash:c8MISMtxDOjV3GcK3XU0sg8tbxc=

Message:Session state can only be used when enableSessionState is set to true, either in a configuration file or in the Page directive. Please also make sure that System.Web.SessionStateModule or a custom session state module is included in the <configuration>\<system.web>\<httpModules> section in the application configuration.

StackTrace:

InnerMessage:Session state can only be used when enableSessionState is set to true, either in a configuration file or in the Page directive. Please also make sure that System.Web.SessionStateModule or a custom session state module is included in the <configuration>\<system.web>\<httpModules> section in the application configuration.

InnerStackTrace:

   at System.Web.UI.Page.get_Session()
   at DotNetNuke.Framework.CachePageStatePersister.Save()
   at System.Web.UI.Page.SaveAllState()
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)`

**Comment by meetmandeep** [comment]
> Realistically, this is/should be logged as an error in some regard, as it could be flagging malicious usage. (Yes bots will cause this, but it could be a far more malicious user) Possibly we need to throttle etc.

I totally agree; however, any malicious usage is almost impossible to identify among a sea of unnecessary and legitimate calls by BOTS. We have several clients with thousands of these calls by Google BOT. 

**Consider the following example:** 
Let's say we use a Web API call to increment a view of a blog post. This happens via a JavaScript call when a user views the page. Google BOT now follows JS; so it makes the call to API but results in the error since it doesn't have cookies enabled. 

I don't have a GREAT solution for this issue. Here are my thoughts: 

- Go back to 8.x logic. Throw the error but don't log it. 

- Log this as a separate event type so at least admins have the ability to turn the logging off. Right now it's basically spamming the Event Viewer

- Ideally, if we can identify if cookies are available for a user agent. If so, then the error should be logged; otherwise, it shouldn't be. But then, malicious users can use this (turn off cookies) to bypass the logging. Same goes if were to identify the User Agent as a BOT. Like I said, I can't think of a great solution. 

Perhaps, we need to implement something at Client Side (within our modules) to check for cookies. If cookies are not enabled then we shouldn't use Web API (with validate anti forgery token)

> Does anyone have a stack trace of this exception that they can provide?

Here you go:

Message:The required anti-forgery cookie "__RequestVerificationToken" is not present.

StackTrace:

   at DotNetNuke.Web.Api.ValidateAntiForgeryTokenAttribute.OnActionExecuting(HttpActionContext actionContext)

   at System.Web.Http.Filters.ActionFilterAttribute.OnActionExecutingAsync(HttpActionContext actionContext, CancellationToken cancellationToken)

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at System.Web.Http.Tracing.Tracers.ActionFilterAttributeTracer.<>c__DisplayClassd.<<OnActionExecutingAsyncCore>b__a>d__f.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at System.Web.Http.Tracing.ITraceWriterExtensions.<TraceBeginEndAsyncCore>d__24.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__0.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__2.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__2.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__2.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__2.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()

**Comment by mitchelsellers** [comment]
Ok, we need to look at this a bit, there wasn't any intended behavior change here, I'm wondering if the swap to 4.7.2 changed the .NET Framework handling.

**Comment by mitchelsellers** [comment]
@thabaum Your post is exactly why logging is important, you can blog them.  Google, not doing it is a bit surprising and I'd venture it might not be them.

**Comment by valadas** [comment]
One thing to note here (not sure if this is the case), bots (well legitimate ones) will follow links but will not click buttons. Very often I see links used to fire up actions which is wrong. Buttons should be used for actions and links well to link to another url... I am not sure if this has play in this situation here. But let's say you have a blog list and the link to get to the detail fires up an action and an api call from javascript instead of redirecting to the url of the detail page...

Disregard if it is not the case, just wanted to point that out in case :)

**Comment by meetmandeep** [comment]
Thanks Daniel. We're not using a button or a link. My understanding is that we have a call to increment the view of the page wrapped in a jQuery Document Ready method. So the call goes out on every page and Google's BOT is now executing JavaScript.

**Comment by valadas** [comment]
Yeah, that would kind of explain it. Does the code that executes in that event grab the token and adds it to the request headers, that should technically work...

**Comment by meetmandeep** [comment]
Daniel, there's no problem with the code. It works fine. We pass in the anti forgery token. 

The problem is that when a Google Bot visits the page. It has no support for cookies and hence no anti-forgery token which results in an exception; thousands of them.

**Comment by valadas** [comment]
I don't know enough about how the attributes work, I see we throw an exception but we don't log it, is the logging coming from the actual module try-catch block... If so, maybe catching that specific one and log it as a warning instead of an error? I am not sure just throwing ideas as the wall to look at what sticks :)

**Comment by valadas** [comment]
From a quick look at it and I did not try it, I think the [DnnApiController] has the [DnnExceptionFilter] attribute on it, it decides what to respond upon some type of exceptions, then it logs it, but that should be in Log4Net, not the event log. I am still unsure what brings this into the event log...

**Comment by bdukes** [comment]
@valadas it's getting logged into the event log at https://github.com/dnnsoftware/Dnn.Platform/blob/46c17ffcbf8f8b2a562e3b97496748d4369cb4f4/DNN%20Platform/DotNetNuke.Web/Api/DnnExceptionAttribute.cs#L81

**Comment by valadas** [comment]
Oh right, I read that, but looks like I misread that, I though it was only logging to Log4Net...  Hmm. Disabling that logging based on the user agent would be bad for security, So I guess the solution might need to be on the API endpoint to maybe ignore bots or add that path to the robots.txt maybe? At any rate for this use case, bots should not be counted as a view right...

**Comment by meetmandeep** [comment]
> At any rate for this use case, bots should not be counted as a view right...

Correct. Robots.txt sounds like a great way to address this. Only if all bots actually honored robots.txt. But so far, this is the best solution. 

Checking the User Agent at logging or even at API endpoint will have a performance hit.

**Comment by valadas** [comment]
>Checking the User Agent at logging or even at API endpoint will have a performance hit.
And could be a way to circumvent security by spoofing the user agent...

**Comment by marietteknap** [comment]
Adding exceptions to robots.txt did not clear this issue

**Comment by valadas** [comment]
I does not solve the underlying issue, but for this use case only, bots should not count as a view, so maybe a workaround could be to filter for bots (user-agent) in that javascript code before calling the API that counts views, bots should not count as a view anyway.

Also, there are times when crooks try to impersonate google bot, are you able to do a reverse IP lookup on those bot requests, just to make sure we are really dealing with google. See https://support.google.com/webmasters/answer/80553?hl=en

**Comment by marietteknap** [comment]
DNN sites who have this issue are probably on Cloudflare or any other proxy. I use CF but I turned all CF functionality off, it only does DNS now and proxy is turned off. The problem did no longer occur in the last 24 hours. What does this tell us? If CF proxy changing cookies or what?

**Comment by marietteknap** [comment]
I have been testing this for the last 3 days and the issue also occurs without CF

**Comment by marietteknap** [comment]
We have the same issue on dnncommunity.org, see screenshot
![05-01-2020-14 42 31 00](https://user-images.githubusercontent.com/5551768/71780992-d1063b80-2fc9-11ea-936a-abdb385b4729.png)

**Comment by valadas** [comment]
So I guess the "less worst" solution would be as suggested:

>Log this as a separate event type so at least admins have the ability to turn the logging off. Right now it's basically spamming the Event Viewer

I gonna triage this as an enhancement for 9.5.0, just to triage it, we can adjust as needed.

**Comment by marietteknap** [comment]
Well, turning off error messages that are security related is not the best approach IMHO.

**Comment by mitchelsellers** [comment]
@marietteknap As long as we don't turn them off by default I don't think there is any real concern here with being able to turn these off.  We have other items that are security related that can be turned off.  (User Login, Password change, SQL Statements Executed, etc.)

The error message, upon further looking is in fact a valid error.  The page WAS submitted without a proper Anti Forgery Token - But the reality is that we don't really care, the system protected itself like it should, so it is a bit complicated.

**Comment by marietteknap** [comment]
OK, that is good but it remains for me a problem that I don't understand why this happens and whether or not there is a code defect somewhere.

**Comment by marietteknap** [comment]
In addition to this I see also another error related to this I think:
`Message:The provided anti-forgery token was meant for user "w***w@p***ol*gy.us", but the current user is "".`

**Comment by mitchelsellers** [comment]
Ther error that is happening is when something is submitting a page with an invalid or missing anti forgery token. The generic error is in fact a valid thing, however it appears in the past it wasn’t getting logged for an unknown reason. 

This can happen from bots, scripting tools, or malicious users. 

Your second one, which is user specific, is more indicative of either a coding issue (missing the token) or a malicious actor.

**Comment by SCullman** [comment]
Currently a `UnauthorizedAccessException` [is raised](UnauthorizedAccessException) if the token is missing.  
What would be a better exception? [HttpAntiForgeryException ](https://docs.microsoft.com/en-us/dotnet/api/system.web.mvc.httpantiforgeryexception?redirectedfrom=MSDN&view=aspnet-webpages-3.2) or a custom one?

**Comment by mitchelsellers** [comment]
We need to look at what .net does. But I believe it should be unauthorized only

**Comment by SCullman** [comment]
@mitchelsellers Link was wrong in my post. DNN doesn't take [care on what .Net does](https://github.com/dnnsoftware/Dnn.Platform/blob/c35fdc7fb75db0438f3b872ce4e279e3ea73e7c2/DNN%20Platform/DotNetNuke.Web/Api/ValidateAntiForgeryTokenAttribute.cs#L44).

**Comment by SCullman** [comment]
> The problem is that when a Google Bot visits the page. It has no support for cookies and hence no anti-forgery token which results in an exception; thousands of them.

That statement is wrong. The anti-forgery token is **not** part of the cookie. The anti-forgery token is injected in the hidden form field `__RequestVerificationToken`, and then [submitted ](https://github.com/dnnsoftware/Dnn.Platform/blob/dbeb24c99d9f84b4d4cf69546e7c43b3100f6bc1/DNN%20Platform/Website/js/Debug/dnn.servicesframework.js#L30)as HttpRequestHeaders as part of the request.
Anyway, I see the same entries in logs of my servers.

**Comment by marietteknap** [comment]
Can we get this fixed in 9.5.0?

**Comment by mitchelsellers** [comment]
Right, but I believe that is the same response that .net does for API responses. I’ll go looking

**Comment by marietteknap** [comment]
My logs are filling up with these messages and so does https://dnncommunity.org/ a bit

**Comment by marietteknap** [comment]
Can somebody with the same issue confirm that changing

> <pages validateRequest="**false**" enableViewStateMac="true" enableEventValidation="true" viewStateEncryptionMode="Always">
to

> <pages validateRequest="**true**" enableViewStateMac="true" enableEventValidation="true" viewStateEncryptionMode="Always">

solves this issue?

**Comment by mitchelsellers** [comment]
@marietteknap that would most likely be a huge breaking change, granted a good one most likely.

@bdukes thoughts?  Or even @ahoefling possibly?

**Comment by marietteknap** [comment]
I have my site running with that setting for 'true' now for a week and I hardly see the issue again. When I see it I can confirm that it is some hack attempt but bots no longer cause the issue. I am a bit confused by some remarks I found about this setting. Some even say that it makes a DNN site read only which is definitely not the cause for me

**Comment by bdukes** [comment]
It would definitely be a breaking change, we'd need to run a few major modules through their paces and see what breaks.

**Comment by bdukes** [comment]
But with the move from WebForms to Web APIs, this may not run into as many issues as it would have years ago.

**Comment by mitchelsellers** [comment]
@marietteknap I'll send you a message with some details, this has security implications

**Comment by arminrahimian** [comment]
Is this Exception Log related with this issue or not?

Message:RequestVerificationToken not present

StackTrace:

   at DotNetNuke.Web.Api.ValidateAntiForgeryTokenAttribute.OnActionExecuting(HttpActionContext actionContext)
   at System.Web.Http.Filters.ActionFilterAttribute.OnActionExecutingAsync(HttpActionContext actionContext, CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Tracing.Tracers.ActionFilterAttributeTracer.<>c__DisplayClassd.<<OnActionExecutingAsyncCore>b__a>d__f.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Tracing.ITraceWriterExtensions.<TraceBeginEndAsyncCore>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---

and more.........

we could not fix it on DNN 9.7.0

**Comment by mortezakermani** [comment]
I had a same issue and I found out it was because SSL was enabled and forced in site settings how ever ssl was not enabled on the pages. so enabling SSL on tabs will fix the issue.

**Comment by marietteknap** [comment]
> I had a same issue and I found out it was because SSL was enabled and forced in site settings how ever ssl was not enabled on the pages. so enabling SSL on tabs will fix the issue.

Thanks for that. I did not have it set to Enforced in Site Settings but I have changed that setting now.

**Comment by WillStrohl** [comment]
I'm seeing this on a 9.11.0 site, and it occurs every time an authorized superuser tries to use any link in the persona bar.

**Comment by WillStrohl** [comment]
> I'm seeing this on a 9.11.0 site, and it occurs every time an authorized superuser tries to use any link in the persona bar.
> 
> UPDATE Technically, it's not "any link," but rather, any action that performs a verified GET or POST to the DNN API. It otherwise appears to be working as expected.

Never mind...  Someone had slipped in a domain restraint in the cookies that I was unaware of.  Once that was updated to         match the `dev` domain, it's working as expected again.
