### ISSUE TITLE
RFC: Allow to easy reference additional assets shipped with DNN javascript library

### ISSUE THREAD

**Issue by roman-yagodin** [dnnsoftware/Dnn.Platform#3382]
## Description of problem

It's hard to reference additional assets shipped along with DNN javascript library package, e.g. CSS, images, fonts, non-main scripts, etc. Currently we need to re-implement (or borrow) non-public parts of `DotNetNuke.Framework.JavaScriptLibraries` code to do this.

### Option 1 (partial solution)

Just make [Javascript.GetHighestVersionLibrary()](https://github.com/dnnsoftware/Dnn.Platform/blob/ba4584834ddfb35601eee4669839cd1e7a8701b9/DNN%20Platform/Library/Framework/JavaScriptLibraries/JavaScript.cs#L291) method public.

This will allow reference additional assets (see example below), but only from highest library version:

```C#
JavaScript.RequestRegistration ("JSLibrary");
var jsl = JavaScript.GetHighestVersionLibrary ("JSLibrary");
if (jsl != null) {
    ClientResourceManager.RegisterStyleSheet (Page, "/Resources/Libraries/JSLibrary/"
        + Globals.FormatVersion (jsl.Version, "00", 3, "_")
        + "/css/stylesheet.min.css",
        (int) FileOrder.Css.SkinCss,
        "DnnPageHeaderProvider",
        "js-library",
         jsl.Version.ToString ()
    );
}
```

### Option 2 (more general solution)

Make the `Javascript.GetHighestVersionLibrary()` method public **and** also introduce following public methods:

```C#
public static JavaScriptLibrary GetLibrary (string jsname, Version version, SpecificVersion specific);
public static Version GetHighestVersion (string jsname);
public static Version GetVersion (string jsname, Version version, SpecificVersion specific);
```

**Comment by bdukes** [comment]
This looks great to me.

In addition, I'd think it would help to either be able to request a resource relative to a library, or to get the path of a library.

It could look something like this:
```
var jsl = JavaScript.GetHighestVersion("JSLibrary");
var path = jsl.GetAssetPath("css/stylesheet.min.css");
ClientResourceManager.RegisterStyleSheet(Page, path);
```

Or like this:
```
var jsl = JavaScript.GetHighestVersion("JSLibrary");
ClientResourceManager.RegisterStyleSheet(Page, jsl, "css/stylesheet.min.css");
```

**Comment by roman-yagodin** [comment]
Please don't close!

**Comment by sleupold** [comment]
anyone to submit a PR, @roman-yagodin ?

**Comment by roman-yagodin** [comment]
Well, maybe. Probably will take quite some time, though.

**Comment by roman-yagodin** [comment]
Bump!
