### ISSUE TITLE
Canonical and None URL mappings don't work correctly on localized sites

### ISSUE THREAD

**Issue by daguiler** [dnnsoftware/Dnn.Platform#3395]
## Description of bug
Canonical and None URL mappings don't work correctly on localized sites. This is pretty much what #3017 is about, but steps to reproduce are more precise.

## Steps to reproduce
1. Set up a new IIS web site for DNN 9.4.3. Name it `platform-9-4-3.dnndev.me`.
2. Install DNN 9.4.3 with default settings (as in `/install.aspx`).
3. Add non primary alias `www-platform-9-4-3.dnndev.me` (and corresponding IIS binding)
4. Ensure URL Mapping is set to `Canonical`
5. Add French as a second language
6. Enable content localization, create localized pages, mark all as translated, activate French pages, publish all French pages.
7. Create additional non-primary aliases:
7.a) `www-platform-9-4-3.dnndev.me/en-us` for English
7.b) `www-platform-9-4-3.dnndev.me/fr-fr` for French
7. Navigate to `www-platform-9-4-3.dnndev.me/fr-fr/`

## Current behavior
DNN redirects to `platform-9-4-3.dnndev.me/fr-fr` (the primary alias)

## Expected behavior
Given URL mapping is set to canonical, no redirection should be performed.

## Additional context
Some pitfalls with Chrome:
* Chrome hides "www." prefix from the URL, which can be very confusing. That's why I used "www-" (with a dash) to avoid this.
* Keep the Dev Tools panel open at all times with the cache disabled. This will get rid of confusing caching issues.

## Affected version
* [X] 10.0.0 alpha build
* [X] 9.5.0 alpha build
* [X] 9.4.x latest supported release
* [X] 9.3.x latest supported release
(not sure about older versions)

## Affected browser
N/A

**Comment by valadas** [comment]
@daguiler is this exactly the same as #3017 ? Should we add these steps to the existing issue instead of duplicating it ?

**Comment by daguiler** [comment]
Hi @valadas, yes, same issue. Since there is no discussion yet on #3017, I thought maybe it would be cleaner to start from scratch, but I'll leave it up to you. I'm about to submit a PR about this.

**Comment by valadas** [comment]
Would this also solve #2841 @daguiler ?
