### ISSUE TITLE
Add the option to block certain Email addresses from registering

### ISSUE THREAD

**Issue by Timo-Breumelhof** [dnnsoftware/Dnn.Platform#3398]
## Description of problem
On the DNN Community site we currently have an issue with spam forum posts.
90% of the used users is created using the same email address pattern.
It would be really nice if we could block certain email addresses or domains from the DNN CP.

## Description of solution
Add a (wildcard) Exclude Emails field to "Security > Member Accounts".
This could be used to block individual emails or known spam domains.

This would allow an admin to at least block a part of the spam users manually.

## Description of alternatives considered
In theory one could also use the email validation field for this but IMO that's way to complex for the average admin user as that's based on a regex.

## Screenshots
If applicable, provide screenshots to help explain the problem and/or enhancement.
![image](https://user-images.githubusercontent.com/8999382/70548342-a95eb780-1b72-11ea-901b-338bb9e66299.png)

## Affected browser

* [ ] Chrome
* [ ] Firefox
* [ ] Safari
* [ ] Internet Explorer
* [ ] Edge

**Comment by valadas** [comment]
I don't know how this could be useful other than the current regex. I get that right now that spam matches some pattern but that spammer could just change the pattern right after. With the amount of free email services available I don't see how this could be any good spam protection. We already have IP blocking available which is a better option IMO. I gonna close this issue for now to clean the backlog but if anyone intends to provide a PR for it, please comment and I will be happy to reopen.
