### ISSUE TITLE
HTML5 Validator Warnings for JavaScripts Script Type Attribute - Old ClientDependency Module

### ISSUE THREAD

**Issue by Andy9999** [dnnsoftware/Dnn.Platform#3400]
Hi!

It seems DNN includes an old version of the ClientDependency module (1.9.2.7) that is causing a warning if validating pages for HTML5, for example using this tool: https://validator.w3.org

The warnings look like this one for example:
Warning: The type attribute is unnecessary for JavaScript resources.
From line 9, column 456; to line 9, column 555
lesheet"/><script src="/DependencyHandler.axd/2e7a51ba21508d187e1972e0fb7d9199/267/js" type="text/javascript"></scri

Here is a link to the issue: https://github.com/Shazwazza/ClientDependency/issues/134

Newer up-to-date versions support a web.config setting to render HTML5 instead of HTML4.

I checked the packages.config of DotNetNuke.Web and it seems the trunk still references 1.9.2.7.

With a newer version of the module, one can set 
`<clientDependency htmlCompatibility="HTML5">` in web.config and it will not set the type attribute anymore.

Why is the DLL's version 1.9.2.7?  If I build version 1.9.2 of the DNN/ClientDependency repo I get a DLL versioned as 1.9.2.0.

Am confused. Is 1.9.2.7 a 1.9.2 + security fixes? Unfortunately I cannot find the source code for it. :(

Maybe I have to use reflector to patch the HTML5 problem.

Andy

**Comment by Timo-Breumelhof** [comment]
I think fixing these kind of HTML5 errors would be very helpful, as now the HTML issues caused by a custom skin or modules are buried in a pile of DNN warnings in the console. It makes "debugging" difficult at times.

**Comment by valadas** [comment]
Because we cannot know the doctype of every theme, this is something we cannot enforce unless we also enforce html5. Also this is not a validation error but a warning and causes no issue at all. I just says you don't **need** to specify it since html5.  It would be an error with any other doctype though, so we would be creating an error on some themes to save a warning on some other themes.

**Comment by Timo-Breumelhof** [comment]
@valadas AFAIK when Client Depencency would be upgraded it would be possible to not render them for a HTML 5 doctype only.

**Comment by Andy9999** [comment]
And knowing how to build the ClientDependency binary included with DNN would be nice as well.  Is 1.9.2.7 a 1.9.2 + security fixes? Such a version does not exist in ClientDependency's repo, at least I couldn't find it. Thanks in advance for any clarification.

**Comment by valadas** [comment]
If there is a know way to do this properly, maybe, I am not sure. If there is some plan that can work please do explain how this could be done and I would be glad to re-open.

**Comment by Timo-Breumelhof** [comment]
So this would mean that 
https://github.com/dnnsoftware/ClientDependency
and 
https://github.com/Shazwazza/ClientDependency/releases/tag/v1.9.10
Would have to be merged, right?

**Comment by Timo-Breumelhof** [comment]
BTW, it also looks like the original repo now supports @import statements, which is also an issue of the current DNN implementation AFAIK

**Comment by bdukes** [comment]
DNN 9.10.1 includes Dnn.ClientDependency 1.9.10, which includes the latest changes from https://github.com/Shazwazza/ClientDependency

**Comment by Timo-Breumelhof** [comment]
@bdukes I didn't know that.. thanks for letting me know.

**Comment by Timo-Breumelhof** [comment]
So the next step would be to set htmlCompatibility="HTML5" depending on the DocTyp of the Theme..

**Comment by bdukes** [comment]
Do we need this to be dependency on the doctype of the theme? The simple solution would be to add `htmlCompatibility="HTML5"` to the `web.config` by default and be done with it.

**Comment by Timo-Breumelhof** [comment]
@bdukes that would be fine with me but I guess @valadas does not agree?

**Comment by valadas** [comment]
I have no strong opinion on that, we just need test it does not break anything. I _think_ this would only be browser console warnings/erros but I am not sure what could possibly happen with older webforms controls. Just needs good testing is what I am saying...

**Comment by Timo-Breumelhof** [comment]
As a reference for others:

`<clientDependency version="0" fileDependencyExtensions=".js,.css" htmlCompatibility="HTML5">`

In web.config
