### ISSUE TITLE
Add Existing Module sharing bug

### ISSUE THREAD

**Issue by marcovisual** [dnnsoftware/Dnn.Platform#3404]
Hi all,
I use DNN 9.3.1 and now 9,4.4. 
When i insert an existing module shared (without copy) all other module (present on page) change position and they are positioned under the shared module.
This specialy on default language.

Thanks
Marco

**Comment by Timo-Breumelhof** [comment]
This is already logged here: https://github.com/dnnsoftware/Dnn.Platform/issues/2289

**Comment by valadas** [comment]
Closing this as it duplicated #2289
