### ISSUE TITLE
Documentation/Readme.txt content is out of date

### ISSUE THREAD

**Issue by Timo-Breumelhof** [dnnsoftware/Dnn.Platform#3405]
## Description of bug
A new DNN user reported DNN install issues. 
These were caused by the fact that he followed the  readme.txt in the documentation folder.
The info in there is not up to date. I had not expected a user to read that but apparently they do.. :-)

## Steps to reproduce
Open the file: https://github.com/dnnsoftware/Dnn.Platform/blob/develop/DNN%20Platform/Website/Documentation/Readme.txt

## Current behavior
Text is no up to date

## Expected behavior
Replace the text with links to the documentation guide

## Affected version

* [ ] 10.0.0 alpha build
* [ ] 9.5.0 alpha build
* [x] 9.4.3 latest supported release

**Comment by valadas** [comment]
Yeah, in my opinion the whole Documentation folder is very old and I would delete the folder altogether in favour of github and the docs site.

**Comment by Timo-Breumelhof** [comment]
@valadas That's why I replaced the txt file with two links, but my PR was a bit of a mess, I'll create a new one
