### ISSUE TITLE
JS error on ModuleAction.js

### ISSUE THREAD

**Issue by leedavi** [dnnsoftware/Dnn.Platform#3407]
## Description of bug
JS error on ModuleAction.js

## Steps to reproduce

Difficult to recreate, it seems to be if the module is using cache.
1. Go into edit module. - 5 module on the page, all editable.
2. Move to another page.  
3. Then return to the page 
4. Go into edit mode and only the first 2 modules are editable. (the other do not have a action menu)
5. Clear cahe all start to work normally.

I cannot recreate with the html module, I presume it's not cached.

If I disable cache on my module, it all works correctly?

## Error information
Error:

ModuleActions.js?cdv=35:235 Uncaught TypeError: Cannot read property 'replace' of undefined
    at buildMoveMenu (ModuleActions.js?cdv=35:235)
    at jQuery.fn.init.$.fn.dnnModuleActions (ModuleActions.js?cdv=35:385)
    at setUpActions ((index):530)
    at (index):640
    at dispatch (jquery.js?cdv=35:5206)
    at elemData.handle (jquery.js?cdv=35:5014)

Cod ethrowingthe error.

            function buildMoveMenu(root, rootText, rootClass, rootIcon) {
            var parent = buildMenuRoot(root, rootText, rootClass, rootIcon);
            var modulePane = $(".DnnModule-" + moduleId).parent();
            var paneName = modulePane.attr("id").replace("dnn_", "");

## Additional context

It seems one of the modulePanes does not have a "attr('id')".

It sounds like it could be the html format, but why does it work if not cached?  So I assume the html format is correct?  And it could be the PB edit bar manipulating the html.  I can not see anything obvious.

Does anyone know why/how this could happen?

And even though it's not a major issue, it could be causing issues with other areas?

## Affected version
v 9.4.1

**Comment by valadas** [comment]
Most of the time I have seen this, it was due to some other bad javascript crashing the rest of the execution. Did you try the same with the default theme? Where you able to reproduce on current releases (ie 9.4.4) ? Does it happen with a third party module on the page or with the platform provided ones?

**Comment by leedavi** [comment]
It's was on the default theme. 

Thye odd thing here is that is works perfect for most situation, just the move to another page, return and then edit mode will cause the problem.  And only wheh cache is active on the module, if I remove the module cache it works.

It certainly looks to be a thrid party modules, the html module doesn't do it.

No other JS error, 

There is some other JS injected into the page, I'll try removing that and see if I can find the cause.

**Comment by leedavi** [comment]
OK I've traced this back to a 3rd party module, inocrrectly not injecting a closing div when cached.

Sorry, this should never have been reported.  I missed this before. But thx for your help.  At least it's no longer a ghost in the machine.

**Comment by david-poindexter** [comment]
@leedavi I ran into a similar situation and it ultimately was due to a malformed template in a 3rd part module.
