### ISSUE TITLE
9.4.4 Broken Image Manager

### ISSUE THREAD

**Issue by andyduo** [dnnsoftware/Dnn.Platform#3409]
## Description of bug

After upgrading to 9.4.4 the image manager in the HTML module no longer correctly shows the folder structure or any images in the image browser window. Doing a folder sync in Asset Manager fixed the folder tree but still no images are displayed in the root folder. 

Images in sub folders of the root are shown normally however. Also, I can still upload an image to the root folder but cannot see it. File manager via link manger shows everything correctly so it just seems to be the image manager.

This is on a previously working install on 2 sites and affects all portals within the install.

To test this I have made a clean install of DNN 9.1 which worked correctly then upgraded it to 9.4.4 and the issues occurs. I cannot see any errors in admin logs or in browser console. Have cleared cache and restarted app pool, restarted iss but i suspect it's related to the actual image manager.

Also tested different browsers.

Note: I have an install that I am happy to let a dev log into to test if that helps at all. Just let me know and I'll organise a link and login details.

## Steps to reproduce
List the precise steps to reproduce the bug:
1. after upgrading to DNN 9.4.4 open Image Manager in any HTML module
2. Click on browse server

## Current behavior

The image manager shouild display withpout any images in the image browser window.

## Expected behavior
The image manager should list all folders within the root and images in the image pane to the user.

## Screenshots
If applicable, provide screenshots to help explain the bug.

## Error information
Provide any error information (console errors, error logs, etc.) related to this bug.

## Additional context
Provide any additional context that may be helpful in understanding and/or resolving the bug.

Issue on Community Forums: 
[https://dnncommunity.org/forums/aft/658](https://dnncommunity.org/forums/aft/658)

## Affected version

* [X] 9.4.4 latest supported release

## Affected browser

* [ X] Chrome
* [ X] Firefox
* [ X] Safari
* [X ] Internet Explorer
* [ X] Edge

**Comment by johnhill2424** [comment]
I second this. I am seeing the same issue with both 9.4.3 and 9.4.4

**Comment by valadas** [comment]
Closing this issue as it duplicates #3004
