### ISSUE TITLE
Module settings PortalSecurity.Decrypt error inside WebApi controller

### ISSUE THREAD

**Issue by DNNMonster** [dnnsoftware/Dnn.Platform#3410]
## Description of bug
If you use PortalSecurity.Encrypt to encrypt a module setting it works great.

If you then try to access those settings from a DNN WebApi controller I'm finding that the DNN WebApi's PortalSecurity.Decrypt function has a different signature than when it is used within the Settings control of the module that is issuing the request.  The WebApi controller's attempt to decrypt using the same passphrase throws an error "Bad Data".

## Steps to reproduce
1. Create a module with a text input that gets encrypted via PortalSecurity.Encrypt
2. Create a WebApi controller with an DNNAuthorize attribute that can receive a request from that module.
3. Attempt to decrypt the module setting via PortalSecurity.Decrypt inside the WebApi controller

## Current behavior
Module settings encrypted via PortalSecurity generates cannot be retrieved within the WebApi controller without generating a "Bad Data" error.

## Expected behavior
Module settings encrypted via PortalSecurity namespace should decrypt within a DNN WebApi controller. 

## Error information
ps.DecryptString(settings["DemoApiKey"].ToString(), passPhrase)' threw an exception of type 'System.Security.Cryptography.CryptographicException'
    Data: {System.Collections.ListDictionaryInternal}
    HResult: -2146893819
    HelpLink: null
    InnerException: null
    Message: "Bad Data.\r\n"
    Source: "mscorlib"
    StackTrace: "   at System.Security.Cryptography.CryptographicException.ThrowCryptographicException(Int32 hr)\r\n   at System.Security.Cryptography.Utils._DecryptData(SafeKeyHandle hKey, Byte[] data, Int32 ib, Int32 cb, Byte[]& outputBuffer, Int32 outputOffset, PaddingMode PaddingMode, Boolean fDone)\r\n   at System.Security.Cryptography.CryptoAPITransform.TransformFinalBlock(Byte[] inputBuffer, Int32 inputOffset, Int32 inputCount)\r\n   at DotNetNuke.Services.Cryptography.CoreCryptographyProvider.DecryptString(String message, String passphrase)"
    TargetSite: {Void ThrowCryptographicException(Int32)}

## Additional context
In the module settings the signature for PortalSecurity Decrypt method is ([string key], [string data]).

In the WebApi controller the signature for the PortalSecurity Decrypt method is ([string msg], [string passphrase]).

The different method signatures makes me think there is something going on that I'm not understanding.

This still could be environmental or code based however I'll submit this.  

## Affected version

* 9.04.01 (22)

## Affected browser

* [X] Chrome
* [X] Firefox
* [X] Safari
* [X] Internet Explorer
* [X] Edge

**Comment by bdukes** [comment]
`PortalSecurity` exposes two pairs of methods for encryption/decryption https://github.com/dnnsoftware/Dnn.Platform/blob/c35fdc7fb75db0438f3b872ce4e279e3ea73e7c2/DNN%20Platform/Library/Security/PortalSecurity.cs#L426-L444

So there's `Decrypt(string strKey, string strData)` which pairs with `Encrypt(string key, string data)`, and there's `DecryptString(string message, string passphrase)` which pairs with `EncryptString(string message, string passphrase)`.  It looks like perhaps you're mixing those between your module and your API?

**Comment by DNNMonster** [comment]
You are exactly right.  Thanks for the super fast resolution.
