### ISSUE TITLE
javascript CDN path used wrong protocol under ssl offloading environment

### ISSUE THREAD

**Issue by zyhfish** [dnnsoftware/Dnn.Platform#3422]
in javascript libraries definition, the cdn path will use "//domain.." to fit the protocol, but in ClientDependency.Core project, ClientDependency.Core\FileRegistration\Providers\BaseFileRegistrationProvider.cs line 223:
`               if (f.FilePath.StartsWith("//"))
                {
                    f.FilePath = Regex.Replace(f.FilePath, @"^\/\/", http.Request.Url.GetLeftPart(UriPartial.Scheme));
                }`

if the website running under ssl offloading environment, the protocol will changed to wrong value, and caused mixed content warning in the browser.

**Comment by david-poindexter** [comment]
Closing per #3423 - in the future @zyhfish take a look at [this documentation](https://help.github.com/en/github/managing-your-work-on-github/closing-issues-using-keywords) on how to ensure issues referenced in pull requests are auto-closed.  Thanks!
