### ISSUE TITLE
Remove Telerik denpendency from the File Manager

### ISSUE THREAD

**Issue by valadas** [dnnsoftware/Dnn.Platform#3439]
## Description of problem
As per discussions in the #2439 RFC, the current file manager has a dependency on Telerik controls.

## Description of solution
We need at a bare minimum to remove this dependency by replacing those controls with standard asp.net controls for now.

## Description of alternatives considered
Ideally this module would be totally rewritten to not depend on webforms but this will be a larger task and we do want a quick removal of the Telerik dependencies in the platform.

## Additional context
After some looking around, it looks like it is only a UI dependency.

**Comment by kurtwilbies** [comment]
@valadas I prefer the following steps: 1) remove telerik components from the module settings,  2) remove telerik from other (non dam) modules, 3) remove them from dam module. Why? The idea is that people can unistall dam and then by that they remove teleriks overhead (module). Another suggesting is to ask the community, dankel or peter or even dnncorp, to donate some of their code (solution); this opens the door to asp.net 5.

**Comment by valadas** [comment]
Well, I don't think we gonna have much contribution from corp on this. So we just need to get away from Telerik dependencies. I started working on this issue for DAM.

**Comment by kurtwilbies** [comment]
@valadas Can you share your (partial) solution. This would speed up the dev process.

**Comment by valadas** [comment]
I have replaced the dropdown in settings for a plain asp.net one, right now I am just replacing the telerik components by plain asp.net ones so we can quickly get rid of the Telerik dependency. As a step 2 it would be nice to rewrite it without webforms but for a step1 this is the plan as decided by the group for a quicker fix. I had a couple rushes but should sumit a PR hopefully this week.

**Comment by mitchelsellers** [comment]
@kurtwilbies This has been discussed at length, with DNN Corp, all the way up to Andy T.  We are not getting any contribution from them to get this done at this time.  I believe the ONLY areas that we are missing is in the file manager, which is what this ticket is for. 

The goal, with this is to make the removal of Telerik optional for 9.5.x and mandatory for 10.0.x.

If you have any questions/concerns feel free to email me directly on this as well.

**Comment by kurtwilbies** [comment]
Is this still work in progress?

**Comment by sleupold** [comment]
this is on halt, while we are currently evaluating the Repository module donated by DNN Corp.

**Comment by valadas** [comment]
Just to put some more info, it currently live on a feature branch at https://github.com/dnnsoftware/Dnn.Platform/tree/feature/resource-manager
I say it has maybe 80% feature parity and does not rely on Telerik, it has some things we need to fix/adapt/update but so far this is a good starter, I gonna try next week to work on it a bit.

**Comment by mitchelsellers** [comment]
For those following along we know for sure right now that we will have to do the following to the contribution before it an be used.

* Update Dependencies
* Resolve integration issue with 9.6.0 security changes
* Add ability to manage folder permissions
* Add ability to manage folder types
* Add ability to Copy/Move files

It is a GREAT starting point but will take a bit of time to validate anything else and add the missing feature parity items

**Comment by kurtwilbies** [comment]
@mitchelsellers concerning your points:
Update Dependencies -> this seems trivial. I am planning to work on this issue.
Resolve integration issue with 9.6.0 security changes -> which sec changes?
Add ability to manage folder permissions -> the api already exist (dam module)! Is this true? Todo: Only UI.
Add ability to manage folder types -> the api already exist (dam module)! Is this true? Todo: Only UI.
Add ability to Copy/Move files -> the api already exist (dam module)! Is this true? Todo: Only UI.

**Comment by mitchelsellers** [comment]
It isn’t quite this clear cut yet. Just let us fix some stuff. First before we get more cooks in the kitchen. 

Give us a week. It isn’t at a point to accept others working it yet

**Comment by kurtwilbies** [comment]
I mean most or all the api id present in the DigitalAssetController. Let us know whether  we can contribute. I could not compile the project, because of a weird dnn-react-common error; yarn related.

**Comment by kurtwilbies** [comment]
Any progress?

**Comment by mitchelsellers** [comment]
We are making progress, we have to make a switch over to the new React.Common, which a few are working on.

**Comment by kurtwilbies** [comment]
@mitchelsellers thanks. I would love to help: test or review code.

**Comment by valadas** [comment]
Closing this issue as since then we have a new non-telerik based file manager which is coming for 9.8.0
