### ISSUE TITLE
403.error outdated

### ISSUE THREAD

**Issue by sleupold** [dnnsoftware/Dnn.Platform#3457]
## Description of bug
Key "403.Error" in file \App_GlobalResources\GlobalResources.resx contains outdated technical details and needs to be updated

## Steps to reproduce
List the precise steps to reproduce the bug:
- Go to PB > Site Settings > Languages
- Enter language editor and choose file \App_GlobalResources\GlobalResources.resx
- Scroll to '403.Error'
- See the text, referring to Windows XP and Windows Server 2003

## Current behavior
displays outdated details.

## Expected behavior
should be uo2date

## Affected version

* [ ] 10.0.0 alpha build
* [ ] 9.5.0 alpha build
* [xxx] 9.4.4 latest supported release

## Affected browser

* [x] any

**Comment by sleupold** [comment]
I'll submit a PR to fix thix

**Comment by valadas** [comment]
It no longer refers to XP or Server 2003 in Dnn 9.6.2, closing the issue...
