### ISSUE TITLE
9.4.4 Upgrade from 9.3.1 CONTENT > PAGES There was an error retrieving your content. Please check your internet connection

### ISSUE THREAD

**Issue by mnouraei** [dnnsoftware/Dnn.Platform#3458]
## Description of bug
After upgrading from 9.3.1 I am unable to edit CONTENT > PAGES as there are no pages shown and Settings > Site Setting as there are no setting shown and I get the following error:
There was an error retrieving your content. Please check your internet connection

## Steps to reproduce
1. Upgrade from 9.3.1 to 9.4.4
2. Click on persona bar and try to view pages and site settings
3. There was an error retrieving your content. Please check your internet connection
4. No pages displayed, unable to edit pages on website using persona bar. No site settings displayed.

## Affected version
* [x] 9.4.4

## Affected browser
* [x] Chrome
* [x] Firefox
* [x] Safari
* [x] Internet Explorer
* [x] Edge

**Comment by valadas** [comment]
Hi @mnouraei can you check:
1. If you have any interesting logs in the /portals/_default/logs folder
2. What extensions do you see if you go to Extensions and select the Persona Bar Extensions in the filter dropdown, it should only show Dnn.PersonaBar.Extensions with version 9.4.4
3. In the /bin folder you should have only 3 dlls that start with Dnn.PersonaBar, do you have more than 3 and if so, which ones.
4. Does the worker process have full permissions on the folder?

**Comment by mnouraei** [comment]
Hi @valadas, I've reviewed your solutions.

1. No errors registered
2. There are only last versions in extensions (Dnn.PersonaBar.Extensions 9.4.4)
![2](https://user-images.githubusercontent.com/9780304/72043798-5f7b0580-32c7-11ea-941d-824532c9b5e4.png)

3. There was 3 files in the bin folder
![3](https://user-images.githubusercontent.com/9780304/72043810-67d34080-32c7-11ea-88a0-cf801a21d3d7.png)

4. Folders have full access
![4](https://user-images.githubusercontent.com/9780304/72043813-6b66c780-32c7-11ea-9f6c-b3408a0606f0.png)

**Comment by mnouraei** [comment]
This file is an error registered in the console:
[192.168.53.13-1578552153909.log](https://github.com/dnnsoftware/Dnn.Platform/files/4038993/192.168.53.13-1578552153909.log)

**Comment by mnouraei** [comment]
I found the cause of the problem.
DNNSharp modules incompatible with this release.

**Comment by valadas** [comment]
Haaaa, thanks for letting use know. Did you also contact DnnSharp with those details, hopefully they can update their modules.
