### ISSUE TITLE
Module can't be untranslated and linked on several pages

### ISSUE THREAD

**Issue by jacoch** [dnnsoftware/Dnn.Platform#3459]
## Description of bug
On a web site with content localization enabled, if a module is linked on several pages (using Add existing module with copy option unchecked), it can't be untranslated on other pages.

## Steps to reproduce
1. Use a web site with content localization enabled and at least two active languages.
2. Add a module to any page.
3. Go to page localization settings and copy the module to other language.
4. Click the blue link icon to make it untranslated. Everything is fine. Module appears on both languages with same content.
5. Add a new page.
6. Add an existing module, uncheck the option to copy content, and select the module created on first page. Module is added properly.
7. Go to the new page localization settings and copy the module to other language.
8. Try to make the module untranslated. It's not possible. The blue link icon is disabled.

## Current behavior
A linked module cannot be untranslated.

## Expected behavior
The linked module should be untranslatable on all pages where it is added. The problem also occurs if the module is not linked manually but using the Display on all pages module setting.

## Affected version
* [ ] 10.0.0 alpha build
* [ ] 9.5.0 alpha build
* [ x ] 9.4.4 latest supported release

## Affected browser
* [ x ] Chrome
* [ x ] Firefox
* [ x ] Safari
* [ x ] Internet Explorer
* [ x ] Edge

**Comment by jacoch** [comment]
Seems I'm the only one facing this issue. In the meantime, as the module I wrote is supposed to be untranslated on all pages, I'm checking on load if the page is not in default language and module is translated. In that case, I'm calling DeLocalizeModule function.

As expected, this function deletes the localized module when done, which then deletes the content item. Unfortunately, function DeleteContentItem tries to delete content item without checking if it's in use by another module. When that's true, it's causing an exception from DB that is not caught by the function.

**Comment by valadas** [comment]
@jacoch Thanks for this bug report, unfortunately I did not have time to test this yet, but I put it in triage :)
