### ISSUE TITLE
GlobalResources key "Licence.text" outdated

### ISSUE THREAD

**Issue by sleupold** [dnnsoftware/Dnn.Platform#3460]
## Description of bug
key "license.text" in file "\App_GlobalResources\GlobalResources.resx" contains outdated license (referring to DotNetNuke Corp etc)

## Steps to reproduce
1. open file in Language Editor and check yourself

## Current behavior
old text

## Expected behavior
current licence text

## Affected version

* [ ] 10.0.0 alpha build
* [ ] 9.5.0 alpha build
* [x] 9.4.4 latest supported release

## Affected browser
* [x] any

**Comment by sleupold** [comment]
I'll submit a PR

**Comment by valadas** [comment]
This was done in commit 6bb74ce. For properly auto-closing an issue, a comment needs to live on the PR instead of a commit. I am manually closing this issue.
