### ISSUE TITLE
DNN 9.4.4 upgrade users procedure or function in personabar

### ISSUE THREAD

**Issue by prwebandprint** [dnnsoftware/Dnn.Platform#3461]
Error in Users when upgrading from DNN7.0.4 to DNN9.4.4 using correct upgrade in DNNDOCs path.
Error reads:
Procedure or function 'Personabar_GetUsersBySearchTerm' expects parameter '@HasAgreedToTerms', which was not supplied.

**Comment by valadas** [comment]
So this was 7.0.4 > 7.4.2 > 9.1.1 > 9.4.4 ?

**Comment by prwebandprint** [comment]
Yes follow each step

**Comment by prwebandprint** [comment]
steps were 08.0.0.04 - 09.01.01 - 09.03.02 - 09.04.04

**Comment by valadas** [comment]
Sorry I skipped 8... Can you try to skip the 9.3.2 step or was that done already in the past and you need to upgrade from 9.3.2?

**Comment by prwebandprint** [comment]
No I have already upgraded due to security issues but have not been able to fix user issue

**Comment by valadas** [comment]
Does this help here: https://github.com/dnnsoftware/Dnn.Platform/issues/3215

**Comment by valadas** [comment]
As far as I know this was fixed by #2829 in Dnn 9.4.0
