### ISSUE TITLE
Language Editor: close file select DDL, after selecting a file

### ISSUE THREAD

**Issue by sleupold** [dnnsoftware/Dnn.Platform#3468]
## Description of bug
After selecting a file in the DDL of the language editor, the list should close automatically (though remembering current position).

## Steps to reproduce
List the precise steps to reproduce the bug:
1. Go to Language Editor
2. Click on 'Language File', to select a file
3. select a file
4. See DDL remains opened

## Current behavior
DDL remains opened

## Expected behavior
DDL closes

## Aditional Information
this sounds like a small issue, but as a translator, you might need to select hundreds of files - that's when it starts to be really annoying

## Affected version
* [ ] 10.0.0 alpha build
* [ ] 9.5.0 alpha build
* [X] 9.4.4 latest supported release

## Affected browser
* [X] Chrome
* [X] Firefox
* [?] Safari 
* [X] Internet Explorer 11
* [X] Edge Classic
* [X] Edge Chromium

**Comment by valadas** [comment]
Is this issue different then the one you commented on earlier?

**Comment by valadas** [comment]
Oh, yeah it looks like #3034 I reopened it, I triaged it and then forgot to reopen. Closing this one since we already have the other one triaged (and now reopened)

**Comment by sleupold** [comment]
@valadas no, this is an addon-issue.
The DDL misses to close itself after selecting a file, but it also forgets after saving the file, to open the path of the file in the tree view.

**Comment by valadas** [comment]
Oh ok reopening then

**Comment by valadas** [comment]
I should take care of this one of these days, it's on my list for when I get some time for it.
