### ISSUE TITLE
TextEditor control causes postback when page is invalid

### ISSUE THREAD

**Issue by edisfera** [dnnsoftware/Dnn.Platform#3469]
## Description of bug
When a form contains a TextEditor control, the validation state of the page is ignored and the form is posted. This is caused by the code added to the WebForm_OnSubmit function that in one case (page is invalid) does not return false, thus causing the postingback of the page.

## Steps to reproduce
Just open in edit an HTML/Text module and check the page source code received by the webserver.
The following code appears in my case for the WebForm_OnSubmit and therefore might slightly differ from the one of the HTML/Text. Nevertheless the line with the return without a value (true or false) is the same.

function WebForm_OnSubmit() {
	if (CKEDITOR && CKEDITOR.instances && CKEDITOR.instances.dnn_ctr642_Edit_Description_Description) 
	{ 
		CKEDITOR.instances.dnn_ctr642_Edit_Description_Description.updateElement();  
		**if (typeof Page_IsValid !== 'undefined' && !Page_IsValid) return;** 
		CKEDITOR.instances.dnn_ctr642_Edit_Description_Description.destroy(); 
	};
		
	if (typeof(ValidatorOnSubmit) == "function" && ValidatorOnSubmit() == false) return false;
	return true;
}

## Current behavior
When the page is invalid, by not returning false causes the postingback of the page.

## Expected behavior
The page should not postback as the client validation is failing.

## Error information
I am not sure if the above code is added by DNN or by the CKEDITOR itself. I failed to find the code in both but something is puting it there. In fact if TextEditor is removed from the page the WebForm_OnSubmit is different.

## Affected version
* [ ] 10.0.0 alpha build
* [ ] 9.5.0 alpha build
* [ X] 9.4.4 latest supported release

## Affected browser
* [ X] Chrome
* [ X] Firefox
* [ ] Safari
* [ ] Internet Explorer 11
* [ X] Microsoft Edge (Classic)
* [ ] Microsoft Edge Chromium

**Comment by valadas** [comment]
I am not sure I understand the issues, what do you mean by validation, other fields in other modules of the page? Can you give a clear non-developer example of the issue with what should happen and what happens instead.

**Comment by edisfera** [comment]
Hi sorry for not being clear.

What I mean is that in a webform with fields validated with validators (such as RequiredFieldValidator) if I add a TextEditor (CKEDITOR) to the page, when I press the button to submit the form, the form is sent to the server even if the page is not valid. If I remove the TextEditor the validation works as expected, that is, it is not sent to the server until the validation succeed.
Looking at the .net validation process I found out that the postback of the page happens if the following condition happens: 

function __doPostBack(eventTarget, eventArgument) {
    if (!theForm.onsubmit || (**theForm.onsubmit() != false**)) {
        theForm.__EVENTTARGET.value = eventTarget;
        theForm.__EVENTARGUMENT.value = eventArgument;
        theForm.submit();
    }
}
The highlighted instruction calls the code I wrote in my original post. Because the page is invalid, the mentioned code returns "undefined" that is != false and the postback happens instead of being stopped as it should do.

I hope this clarifies the problem, even if, as I said, I am not sure if it depends on DNN or on CKEDITOR itself… I was not able to find out who writes the code that appears in the WebForm_OnSubmit function when the TextEditor control is added to the form.

**Comment by valadas** [comment]
Hmm, do you use CkEditor directly or do you use the provided webforms control here https://github.com/dnnsoftware/Dnn.Platform/blob/develop/DNN%20Platform/Website/controls/texteditor.ascx

**Comment by valadas** [comment]
Because the html editor is a provider, this would be the way to consume the configured html editor provider and unfortunately will need some custom validation logic because it is not a simple control but an html snipped with a label and a text field and then javascript that manipulates the fake content of that text field...

**Comment by edisfera** [comment]
Hi Valadas, I am using the TextEditor control that appears in the following path of a DNN installation: /controls/texteditor.ascx (I believe is the same as the one pointed by you in GitHub). I succesfully managed to add a required fields validator for that control (it took some time to understand how it works, but I then achieved the expected result). Unfortunately it is ignored togheter with other required fields validator because of that return without a true or a false. By removing the TextEditor control from the page, the "offending" extra CKEDITOR code appearing in the WebForm_OnSubmit goes away and magically all the others required field validator start to work. Re-adding the TextEditor control compromises the functionality of validation once again as already explained.
To fix this bug we have to find out who is adding the CKEDITOR code to the WebForm_OnSubmit and then ask him/her to change "return;" in "return false;".

**Comment by valadas** [comment]
Oh, ok, if I understand correctly the problem is not with validating this control but all others on that same page correct?

**Comment by edisfera** [comment]
Yes you are correct
