### ISSUE TITLE
Typo in TaskScheduler.resx

### ISSUE THREAD

**Issue by sleupold** [dnnsoftware/Dnn.Platform#3484]
#3319  Description of bug
File \DesktopModules\Admin\Dnn.PersonaBar\Modules\Dnn.TaskScheduler\App_LocalResources\TaskScheduler.resx contains type FreindlyName multiple times (in Prompt help texts)

## Steps to reproduce
List the precise steps to reproduce the bug:
1. open source file
2. search for "Freindly"

## Current behavior
found

## Expected behavior
not found.

## Affected version
* [ ] 10.0.0 alpha build
* [ ] 9.5.0 alpha build
* [x ] 9.4.4 latest supported release

## Affected browser
* [X] Chrome
* [X] Firefox
* [X] Safari
* [X] Internet Explorer 11
* [X] Microsoft Edge (Classic)
* [X] Microsoft Edge Chromium

**Comment by valadas** [comment]
Merged
