### ISSUE TITLE
Non-translatable resource text 

### ISSUE THREAD

**Issue by sleupold** [dnnsoftware/Dnn.Platform#3486]
## Description of bug
Prompt_AddRoles_NotFound.Text in \DesktopModules\Admin\Dnn.PersonaBar\Modules\Dnn.Users\App_LocalResources\Users.resx cannot be properly translated into other languages:

## Steps to reproduce
List the precise steps to reproduce the bug:
1. open the file and search for the key
2. the value is "Cannot find role{0} '{1}'. --roles parameter only accepts existent roles."
3. parameter {0} is used to append an "s" to "role", if multiple roles are speified
4. This doesn't work in other languages, as the plural is not always created by appending an "s" to the singular word - e.g. in German the plural of "Rolle" is "Rollen".

## Current behavior
creates  wrong plural in other languages.

## Expected behavior
should either use "Role(s)" with no param or 2 individual resource keys

## Additional context
I noticed the same issue in other resource files for Prompt as well with different words.

##Workaround for Translators
ignore the {0} parameter and hardcode plural alternative, e.g. "Rolle(n)" in German.

## Affected version
* [ ] 10.0.0 alpha build
* [X] 9.5.0 alpha build
* [X] 9.4.4 latest supported release

## Affected browser
* [X] Chrome
* [X] Firefox
* [X] Safari
* [X] Internet Explorer 11
* [X] Microsoft Edge (Classic)
* [X] Microsoft Edge Chromium

**Comment by david-poindexter** [comment]
This seems like an issue with fairly hefty ramifications.  It appears business logic was built on certain assumptions, based on the English language.  This may, in fact, impact much more than just the Users area.  Perhaps @dnndev can chime and collaborate on recommendations for this?

**Comment by dnndev** [comment]
Unfortunately, after my contribution, DNN Corp converted my HTML-based docs system to the localized version found in Prompt today so I can't speak directly to changes/fixes authoritatively.

**Comment by valadas** [comment]
"This doesn't work in other languages, as the plural is not always created by appending an "s" to the singular word

English too actually 😛 
Foot - Feet
Passerby - Passersby
Millenium - Millenia
one fish - two fish

I think no matter the language it should always be 2 keys for singular and plurals in sentences.

**Comment by sleupold** [comment]
there are a number of other words in English - Child, People, Luck ...
However, I am sure, if we look at languages like Hebrew, Arab or Chinese, we will notice totally different rules (see http://mylanguages.org/chinese_plural.php) and should always be aware, not to construct sentences like it is common in English language.

**Comment by sleupold** [comment]
still an issue

**Comment by valadas** [comment]
This should be somehow a trivial change, can you submit a PR @sleupold
