### ISSUE TITLE
Link in \Install\App_LocalResources\Installwizard.aspx.resx, key IntroDetail.Text targets outdated content

### ISSUE THREAD

**Issue by sleupold** [dnnsoftware/Dnn.Platform#3490]
## Description of bug
when clicking link IntroDetail.Text in Installwizard, it opens https://www.dnnsoftware.com/community/learn/video-library/view-video/video/515/view/details/dnn-7-0-installation-part-1-file-system-configuration, which posesses historic value only

## Affected version

* [ ] 10.0.0 alpha build
* [X] 9.5.0 alpha build
* [X] 9.4.4 latest supported release

## Affected browser
* [X] any

**Comment by valadas** [comment]
This has been changed already to point to the community website.
