### ISSUE TITLE
referrer url is incorrect when requesting update service

### ISSUE THREAD

**Issue by zyhfish** [dnnsoftware/Dnn.Platform#3496]
https://github.com/dnnsoftware/Dnn.Platform/blob/fe7fc7a84e012f7c5d52c47475489a92eaaf84aa/Dnn.AdminExperience/Library/Dnn.PersonaBar.UI/Services/ServerSummaryController.cs#L117

the referrer url is not an absolute url so will cause incorrect behavior in the update service.

**Comment by mitchelsellers** [comment]
I DO NOT recommend resolving this issue due to data privacy
