### ISSUE TITLE
Console Enhancement

### ISSUE THREAD

**Issue by robfleischmann** [dnnsoftware/Dnn.Platform#3499]
My company will be utilizing the Console extension for pages within the CMS app and one of our users noticed that for pages of type URL, when they specify Open in New Window, the Console's link still opens in the same page. I reviewed the code and it doesn't seem to be looking at the TabSettings table (and thus if there is a LinkNewWindow setting and of type true, the code doesn't build the target="_blank"). I feel this would be a great enhancement to the Console Extension so I wanted to mention it here.

**Comment by sleupold** [comment]
great idea, but it requires someone from the community to catch up the task.

**Comment by valadas** [comment]
By console, you mean the Dnn Prompt? @robfleischmann .

If you could also list clear steps to reproduce for people (like me) that do not use the console that often :)

1. Create a page named xxxx
2. Run the prompt command list pages something something
3. Click the link in the reply and notice it does not open in a new tab.

**Comment by bdukes** [comment]
No, I believe they're referring to the module used on the Admin and Host pages by default, which provides a list of the child pages.

**Comment by robfleischmann** [comment]
@bdukes is correct, and I apologize for not being clearer. I am referring to the Admin Console module:
DesktopModules\Admin\Console

For example, say you have a page called Employee Center and it has child pages. Some are standard page types, but some are URLs. For the ones that are URLs the user specified to open in a New Window. That setting I found to be in a table called TabSettings table, SettingName=LinkNewWindow. It would be great if the codebehind of the module would also query TabSettings to check if the URL's LinkNewWindow=True, and if so append a target="_blank" to the a href.

I hope that makes things clearer, thank you for your time!

**Comment by valadas** [comment]
Haaa, thanks for the clarification, I was able to reproduce and triaging accordingly.

On a sidenote, or as a workaround while this get's resolved, do you know about the DDRMenu that has way more options. It is more complex to setup but has more possibilities too:

https://dnndocs.com/content/tutorials/themes/theme-objects/ddrmenu/index.html#ddrmenu-overview

**Comment by robfleischmann** [comment]
> Haaa, thanks for the clarification, I was able to reproduce and triaging accordingly.
> 
> On a sidenote, or as a workaround while this get's resolved, do you know about the DDRMenu that has way more options. It is more complex to setup but has more possibilities too:
> 
> https://dnndocs.com/content/tutorials/themes/theme-objects/ddrmenu/index.html#ddrmenu-overview

Thank you!!

**Comment by valadas** [comment]
Just for reference if a newcomer pick this issue up we are talking about this module here: https://github.com/dnnsoftware/Dnn.Platform/tree/develop/DNN%20Platform/Admin%20Modules/Dnn.Modules.Console
