### ISSUE TITLE
Getting nuget.targets not found issue on DNN 9.3.2 Source code

### ISSUE THREAD

**Issue by dhrumit001** [dnnsoftware/Dnn.Platform#3509]
Hello sir,
i downloaded DNN 9.3.2 source code version but it's getting me error like .nuget\nuget.targets not found in VS 2017
please help

![image](https://user-images.githubusercontent.com/11158042/72719902-cc7f7c80-3b9e-11ea-9f43-2ea293eb79c7.png)

**Comment by mitchelsellers** [comment]
Although the Source Package is provided, we suggest using the "Source Code (zip)" link at the bottom.  As that is an un-modified version of the source.  Future releases we will be removing the _source.zip.

**Comment by dhrumit001** [comment]
Thanks for reply
yes i already download zip file and it give me error like 'PortalSetting is null'
please help .

**Comment by valadas** [comment]
After following these steps if you still have issues, feel free to comment even if the issue is close we will still get notified about comments...

**Comment by dhrumit001** [comment]
okay thanks for your valuable replay 
i will check it .
