### ISSUE TITLE
Roadmap is not up-to-date

### ISSUE THREAD

**Issue by kurtwilbies** [dnnsoftware/Dnn.Platform#3523]
Roadmap, see https://dnncommunity.org/road-map, is not up to date. When is the release date of 9.5? And 10.0? And is there more info about the project Vanjaro? We love to hear more!

**Comment by valadas** [comment]
I have just updated the RoadMap, keep in mind it is approximative and can change anytime.

As far as Vanjaro goes, this is not a project here. It is partially based on Dnn but asking about it here would be like asking your butcher when your favorite restaurant will change their menu.
