### ISSUE TITLE
Deprecate DisplayCopyright Host Setting

### ISSUE THREAD

**Issue by mikesmeltzer** [dnnsoftware/Dnn.Platform#3526]
## Description of problem
The DisplayCopyright host setting is now no longer in active use for it's intended purpose. However, the deprecated RibbonBar project and an older skin object still reference the setting.

## Description of solution
Deprecate the property (and skin object) to be removed in v11.

## Additional Context
This is a follow-up to PR #3524 .

The skin object in question, for reference, is "/Admin/Skins/DotNetNuke.ascx". This is used to display the DNN product copyright in a Skin, is not referenced or used within platform anymore.

**Comment by sleupold** [comment]
wouldn't it make sense to keep it for the Copyright skin object to display site copyright term within the Theme applied to the site?

**Comment by mikesmeltzer** [comment]
I don't think so. This skin object is used for displaying the DNN product copyright and not used within the platform or core skin. Not to be confused with something that shows your particular website copyright, that's a different skin object.

The skin object in question, for reference, is  "/Admin/Skins/DotNetNuke.ascx".

**Comment by EPTamminga** [comment]
Still valid

**Comment by mikesmeltzer** [comment]
Still valid, keep open.

**Comment by valadas** [comment]
I thought this was done already, did you double-check @mikesmeltzer

**Comment by mikesmeltzer** [comment]
Yes, the file still exists.

**Comment by sleupold** [comment]
would deleting the skin object not break existing 3rd party skins containing it?
In this case, it could only be removed aver next but one major version after it being marked as deprecated.

**Comment by valadas** [comment]
> would deleting the skin object not break existing 3rd party skins containing it.

Yes it would, we need to deprecate the property for removal in v11. (If a PR comes in to deprecate this in v9).

**Comment by mikesmeltzer** [comment]
@valadas how do we deprecate a skin object since it's an ascx control? Just mark it as such on it's corresponding code behind file?

**Comment by valadas** [comment]
Yeah, as skin developers don't really compile, they won't get much of a warning about it, it's not perfect for sure.... But we can at least mention it in release notes...

**Comment by mikesmeltzer** [comment]
Makes sense. I'll make a PR for it to mark it as deprecated in v11 on the C# side and submit that in a bit.

This is minimal risk; I think few would embed the actual DNN Copyright into their skin.
