### ISSUE TITLE
Module Actions Menus Are Not Accessible

### ISSUE THREAD

**Issue by mikesmeltzer** [dnnsoftware/Dnn.Platform#3527]
## Description of problem
The current module action menus are not accessible, preventing some groups of users from being able to effectively use the platform.

## Description of solution
Users should be able to use the action menus with the assistance of a screen reader. Utilize aria labels and adjust the html where necessary.

## Additional context
See #2433 for more information.

## Affected versions

All

**Comment by Cambridgeport90** [comment]
I will be following this one, and will be here to test at every step of the way. I want this to work out for all of us. Having DNN CMS as yet another platform available, it will level the playing field for quite a few individuals. We can bring that 750 thousand sites to a million, including personal sites. Half joking, but it would bring more availability to more of the population.

**Comment by valadas** [comment]
I set the 9.5.1 milestone because it could be a non-breaking change, but this is not set in stone...
