### ISSUE TITLE
Re-install module with skin causes install failure 

### ISSUE THREAD

**Issue by leedavi** [dnnsoftware/Dnn.Platform#3536]
#3319  Description of bug
Re-installing a module that installs a skin fails, with an error message the skin already exists,

## Steps to reproduce

1. Install OpenStore  https://github.com/openstore-ecommerce/OpenStore/releases
2. re-install OpenStore.

## Current behavior
1. Works
2. Failes with skin error.

## Expected behavior
Both installs should work.

## Error information
Not got it.. but Fails with duplicate name or something like that.

## Affected version
* [ ] 10.0.0 alpha build
* [ ] 9.5.0 alpha build
* [X ] 9.4.4 latest supported release

**Comment by valadas** [comment]
We are talking about a repair install like all the packages have the same version? Or is this a new version and if so did all the packages version had their versions bumped?

**Comment by leedavi** [comment]
It's only on repair installs.   If you remove the "Skin" from the DNN manifesto, the repair works OK.

**Comment by leedavi** [comment]
My Statement before was wring.  This is for ANY install repair or now.  If the skin is already there DNN will NOT install the module.

**Comment by leedavi** [comment]
This is still active AFIK.  I have had to create 2 install packages, to overcome the problem.

**Comment by leedavi** [comment]
This is still active AFIK. I have had to create 2 install packages, to overcome the problem.

**Comment by leedavi** [comment]
This is still active AFIK. I have had to create 2 install packages, to overcome the problem.

**Comment by leedavi** [comment]
Still active.  but I doubt it will ever be fixed.  Maybe it should be closed to concentrate of more important things.

**Comment by valadas** [comment]
Well, the purpose of stalebot is to close issues that have no progress due to nobody caring hard enough to even keep the conversation rolling. But every time someone comments "still and issue" or similar without anything to help the issue get some possible code contribution, well it's just stale longer :) I gonna close it but if anyone has the intention to work on this, just comment and I'll reopen.
