### ISSUE TITLE
CoreMessaging Notifications: bad database performance

### ISSUE THREAD

**Issue by sleupold** [dnnsoftware/Dnn.Platform#3539]
## Description of problem
on large sites with many users (> 1M) and using DNN messaging system with notifications, performance is submarin and processing notifications is cut off due to timeouts

## Description of solution
improve index and use of it in SPs

## Description of alternatives considered
we tried historically proven options like horse back riding messengers, but thy didn't show up as valuable alternatives to emails.

## Screenshots
sorry, the horses passes by too quickly.

## Additional context
signal posts, being used in 19th century, turned out having issues transmitting images

## Affected browser
* [ ] any (except Lynx)

**Comment by valadas** [comment]
PR Merged
