### ISSUE TITLE
Page description leaves to blank is showing Site Description

### ISSUE THREAD

**Issue by tingung** [dnnsoftware/Dnn.Platform#3541]
## Description of bug
Provide a clear and concise description of the bug.
Page description leaves to blank is showing Site Description
## Steps to reproduce
List the precise steps to reproduce the bug:
1. Open Persona Bar > Site Settings
2. Enter "My Website Description" in Site Description text box and save the settings
3. Open Persona Bar > Pages
4. Create a new Pages with Name: page1 and leave all other field to blank or default
5. Open Persona Bar > Pages
6. Click page1
7. Observe the page description

## Current behavior
Explain the current behavior.
page description is showing "My Website Description" which is the site description

## Expected behavior
Provide a clear and concise description of the expected behavior.
page description should show blank

## Screenshots
If applicable, provide screenshots to help explain the bug.

## Error information
Provide any error information (console errors, error logs, etc.) related to this bug.

## Additional context
Provide any additional context that may be helpful in understanding and/or resolving the bug.
It seems the code written so here - https://github.com/dnnsoftware/Dnn.Platform/blob/80e48fcde4694d70960253d401a8fcd6851608eb/Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Components/Pages/Converters.cs#L104
However, it creating confusion to the user especially during site export / import because the page description changed after import to the next site (both site have different site description)

## Affected version

* [x] 10.0.0 alpha build
* [x] 9.5.0 alpha build
* [x] 9.4.4 latest supported release

## Affected browser

* [ ] Chrome
* [ ] Firefox
* [ ] Safari
* [ ] Internet Explorer 11
* [ ] Microsoft Edge (Classic)
* [ ] Microsoft Edge Chromium

**Comment by tingung** [comment]
@valadas ,

Do you think this is a bug or it is expected? There is an internal ESW defect reported but it seems intended. I am not very sure.

**Comment by valadas** [comment]
This would be by design the site settings have been a fallback for missing values on individual pages. Now if this affects import/export, I believe a workaround in that section would be in order. Does that make sense?

**Comment by sleupold** [comment]
do not close

**Comment by valadas** [comment]
@sleupold Can you elaborate, is this not by design?

**Comment by EPTamminga** [comment]
AFAIK, this is by design

**Comment by sleupold** [comment]
AFAIK it is by design, but I fear, having same description on all pages might result in bad ranking by any Search Engine, which uses this metadata. I'd prefer a checkbox setting, whether it should be blank.

**Comment by mitchelsellers** [comment]
@sleupold You are correct, it was done before to ensure that all pages have a description.  I think with current times, if a description was omitted we should omit the description element
