### ISSUE TITLE
Modules without manifests get wrong version number

### ISSUE THREAD

**Issue by valadas** [dnnsoftware/Dnn.Platform#3542]
## Description of bug
An sql script was created to ensure that those modules that have no manifest get their version updated to the latest on upgrades/installs, for some reason this appears to not be working properly on upgrades

## Steps to reproduce
List the precise steps to reproduce the bug:
1. Install Dnn 9.4.4
2. Upgrade to Dnn 9.5.0

## Current behavior
Some build-in modules do not have version 9.5.0

## Expected behavior
Built-in modules should have version 9.5.0

## Screenshots
If applicable, provide screenshots to help explain the bug.
![image](https://user-images.githubusercontent.com/6371568/73823223-ca840300-47c5-11ea-92b9-16ce93b9b1b8.png)
This screenshot came from @marietteknap I believe this was originally 9.3.2 => 9.4.4 => 9.5.0 but in any case it should show the current Dnn version.

## Additional context
This should already be fixed, must not be firing up for some reason.

## Affected version

* [ ] 10.0.0 alpha build
* [x] 9.5.0 alpha build
* [x] 9.4.4 latest supported release

**Comment by OllyHodgson** [comment]
I can reproduce. I installed a completely clean 9.4.4, then upgraded it to 9.5.0-rc1. In my case, they're showing as version 9.3.2, and an upgrade to version 9.5.0 is available:

![image](https://user-images.githubusercontent.com/437224/73875512-64c66400-4823-11ea-97a5-198c03acd3e0.png)

Clicking on 9.5.0 takes me to the new update service, which says:

> # Upgrade Details Unknown
> The extension you have selected has an upgrade available, however, the vendor has not informed the upgrade service of the suggested location to acquire the upgrade for the component. Please contact the vendor for assistance.
> DNN Platform Update Service Version 1.0.11

**Comment by Timo-Breumelhof** [comment]
Hmm, my upgrade to 9.6 failed because one of the Desktopmodules entries had a NULL value, could this be related?

**Comment by valadas** [comment]
@Timo-Breumelhof do you have the steps to reproduce where you get a null, as far as I know I never saw a null in any upgrade path, just wrong versions...

**Comment by Timo-Breumelhof** [comment]
> 
> 
> @Timo-Breumelhof do you have the steps to reproduce where you get a null, as far as I know I never saw a null in any upgrade path, just wrong versions...

Not really, I found it in one install that once started in DNN 4, the "Template" module had version null
