### ISSUE TITLE
Thread locale doesn't pervade to data backend using WebAPI

### ISSUE THREAD

**Issue by donker** [dnnsoftware/Dnn.Platform#3545]
# Description of bug
When going through WebAPI the thread locale is set correctly when I get to the handler. But once I retrieve data through DAL2 I find that in those methods the thread locale has been reset to en-US (system default).

## Steps to reproduce
1. Create new site and enable multiple languages in your portal.
2. Install test module and instantiate on a page: [https://github.com/donker/testmodule/releases/tag/0.0.1](https://github.com/donker/testmodule/releases/tag/0.0.1)
3. Switch to a non en-US/non portal default locale

There are two tables listing tabs. The object that is being used retrieves the thread locale when being created from data retrieval. The first table is done directly in MVC. The second is done through WebAPI.

## Current behavior
The first table shows the correct environment locale, the second does not in the last column.

## Expected behavior
Both tables should show the same.

## Affected version
* [ ] 10.0.0 alpha build
* [x] 9.5.0 alpha build
* [x] 9.4.4 latest supported release

**Comment by donker** [comment]
[TestModule_00.00.01_Install.zip](https://github.com/dnnsoftware/Dnn.Platform/files/4162198/TestModule_00.00.01_Install.zip)

**Comment by donker** [comment]
My suggestion is to lump this in with the thread locale issue we discovered when we wanted to go to async. The best solution I can think of right now is to add the locale to the request items like we do with portal settings and then draw them out again in a similar manner.

**Comment by leedavi** [comment]
I'm getting the en-US always being used if a url has paramater.

The url may be fr-fr, but the data is en-us.

This makes DNN unworkable for multiple languages.

**Comment by leedavi** [comment]
My issues with DNN9.4 langauges seem to have been solved in DNN9.5.  

Maybe this bug was fixed in the DNN9.5 release, but I'm unsure if this issue is related to the problems we had.

Maybe Peter has a better idea if this has been solved.

**Comment by donker** [comment]
Closing for now. I believe it is no longer relevant. It had to do with the way DI was implemented which has since been changed.

**Comment by thienvc** [comment]
This problem still appears on DNN 9.8, has someone found out and fixed this problem?
This is a serious problem for multilingual websites.

**Comment by thienvc** [comment]
I found has many response language cookie many times:

Date: Sun, 15 Nov 2020 12:28:30 GMT
Set-Cookie: app_IsMobile=False; path=/; HttpOnly
**Set-Cookie: language=vi-VN; path=/; HttpOnly**
Set-Cookie: app_IsMobile=False; path=/; HttpOnly
**Set-Cookie: language=en-US; path=/; HttpOnly**
Vary: Accept-Encoding
X-Frame-Options: SAMEORIGIN
X-UA-Compatible: IE=edge

**Comment by valadas** [comment]
Now I did not even know it was possible to have 2 cookies with the same name but different values, that is surprising to me...

**Comment by donker** [comment]
It will be fixed in 9.8.1.
