### ISSUE TITLE
Personabar is missing after installing dnnsharp AF

### ISSUE THREAD

**Issue by schotman** [dnnsoftware/Dnn.Platform#3549]
## Description of bug
Provide a clear and concise description of the bug.

## Steps to reproduce
List the precise steps to reproduce the bug:
1. start with a dnn804 install
2. upgraded to dnn950rc1
3. looks fine, can add content, install open content module, add pages: No problems
4. install AF DnnSharp.ActionForm-05.01.03-Install.Hotfixes. 

After this installation the personabar was no longer visible with the following errors: 

![image](https://user-images.githubusercontent.com/2582737/74032730-fdd8b480-49b4-11ea-9972-c747b9727fa2.png)
 

## Affected version

* [X ] 9.5.0 rc1 build

## Affected browser
* [x ] Chrome

**Comment by bdukes** [comment]
@bogdan-litescu @dimarobert Do you have a version of Action Form available that @schotman can test on the DNN 9.5.0 RC1?  Or, @dimarobert, does #3544 need to land before DNN Sharp modules can work?

**Comment by schotman** [comment]
Tested an internal build of AF against the nightly build of DNNplatform. 
This worked, that is, some basic tested showed no problems with the module (apart from a package install error, IIS, see screenshot). 
The nightly build contains the pull request from @dimarobert which made it work I suppose.
![image](https://user-images.githubusercontent.com/2582737/74851702-e21dc880-533b-11ea-803c-05dfa26076d5.png)

**Comment by sleupold** [comment]
@schotman 
DNN 9.5.0 has been released yesterday, please test against this version.

**Comment by schotman** [comment]
solved
