### ISSUE TITLE
Could not find stored procedure 'dbo.GetEventLogType'.

### ISSUE THREAD

**Issue by Mncool** [dnnsoftware/Dnn.Platform#3553]
Fresh install of Dnn 9.4.4, log file reports the error: "Could not find stored procedure 'dbo.GetEventLogType'." 

Code is trying to call it before SQL scripts run to setup DB.

**Comment by valadas** [comment]
Stange, I installed multiple Dnn 9.4.4 without his issue. Do you have any other information that could help. Tell us a bit about the environment, windows and sql versions, Anything else logged in the files at /Portal/_default/logs ?
