### ISSUE TITLE
Client resource management  - Enable Composite Files disables personabar

### ISSUE THREAD

**Issue by schotman** [dnnsoftware/Dnn.Platform#3557]
## Description of bug
When Enable Composite Files is enabled the personabar is no longer functioning

(so reverting can only be done through directly accessing the database)

## Steps to reproduce
List the precise steps to reproduce the bug:
1. Go to servers -> server settings -> performance
2. change the switch: Enable Composite Files to ON
3. Hit Save
4. After save, increment the version
5. when version is incremented, click "clear cache"
6. reload the page or browse to another page
7. See the error: the personabar is no longer on the right side, but on the top with only the top section visible

Skin Xcillion, but happens in other skins as well

## Current behavior
personabar styling is no longer working correctly

## Expected behavior
personabar works like before
## Affected version
* [x] 9.3.2 latest supported release

## Affected browser
* [x ] Chrome
![image](https://user-images.githubusercontent.com/2582737/74336484-9fd61380-4d9e-11ea-809c-bb05599488e9.png)

**Comment by valadas** [comment]
Have you tried upgrading, there has been a lot of bug fixes since 9.3.2

**Comment by schotman** [comment]
Yes, just tried it on a fresh 950rc1 install. In this version the personabar works fine. So let's close it.

**Comment by valadas** [comment]
Cool!
