### ISSUE TITLE
Parse AllowUserUICulture and EnableBrowserLanguage values from portal templates

### ISSUE THREAD

**Issue by davidjrh** [dnnsoftware/Dnn.Platform#3558]
## Description of bug
Currently the AllowUserUICulture portal setting can't be specified on portal templates because there is no code to import that setting.

## Steps to reproduce
List the precise steps to reproduce the bug:
1. Edit the file system on /Portals/_default/Blank Website.template 
2. Add an XML node under `<portals><settings>`
`<allowuseruiculture>True</allowuseruiculture>`
3. Create a new Portal using the Blank Website template
4. Using the persona bar, go to Settings > Site Settings > Languages. The setting "Users May Choose Interface Language" is False and should be True.

## Current behavior
After reproducing the steps, the setting "Users May Choose Interface Language" is False. **The same happens with the setting "EnableBrowserLanguage".**

## Expected behavior
After reproducing the steps, the setting "Users May Choose Interface Language" should be True

## Affected version

* [X] 10.0.0 alpha build
* [X] 9.5.0 alpha build
* [X] 9.4.4 latest supported release

**Comment by davidjrh** [comment]
Added PR #3561

**Comment by valadas** [comment]
PR merged, closing.
