### ISSUE TITLE
Site Groups - Unverified Users - when user login in a different portal than the one was created

### ISSUE THREAD

**Issue by ortomind** [dnnsoftware/Dnn.Platform#3565]
## Description of bug
In a Site Groups activated scenario in main portal the user remain Unverified User role when the user was created and verified with link form secondary portal.

## Steps to reproduce
List the precise steps to reproduce the bug:
1. Create a PortalGroupID set to 1
2. MasterPortalID 0 of PortalA
3. AuthenticationDomain portalA.com
4. set in Portals PortalGroupID to 1 for both PortalA and PortalB
5. register a user in PortalB
6. click the verified user link you get form PortalB
7. log in in PortalA with the credentials created in PortalB
8. you can see the notification that is an Unverified User in PortalB and the CLICK link is not active

## Current behavior
When in a Site Group an User is a verified User in a PortalB it is not automatic a Verified User in PortalA and no way to get an activation link form PortalA

## Expected behavior
Within a Site Group an User should be verified in all portals one it gets verified in one and Unverified User role should be removed for all portals.

## Affected version
9.4.4

## Affected browser
I have testes in Microsoft Edge Chromium

**Comment by thabaum** [comment]
There are a few issues that need ironed out at the same time related to site groups, users and possibly site grouping security roles.

If we can site group sites with roles we can cure this verification issue by adding the user to the registered users role as @ortomind mentioned.   Feels like 9.6 is the next milestone that may be reasonable to expect a fix for both adding the UI and the verification issue.  You should just verify on one site or unregister on any site and it carry out whatever it takes to add/remove security roles.  I believe really after thinking long and hard about this topic that some security groups but prossibly not all need to be linked to each site in a group.  

Similar to sharing a module with a page, the core groups should be shared from DNN and an option to share other groups created to be site only or site group with only the main security administrator being able to create site groups and possible a permission setup for allowing other administrators or users create and manage site security groups.  

A bit much but after getting the site groups UI fixed this issue needs dealt with as well with the verification.  And I think the sharing of security groups with options to turn that on and off for different environments and to keep it from being a "breaking" change.  These options can be turned off to share security roles with site groups but ability to switch them on in the site group panel would be sweetness so they are shared.

Also if a site is not a part of a site group and has users, if you join that site would it import those users into the master site user?  This would be super nice to get dialed in right.  I am almost done with a big project and I can help again once I am more caught up here.  I will dive a little deeper here in the conversation if we can polish this part of DNN out it would be amazing to finally see it all come to light.
