### ISSUE TITLE
Delete files in file browser not working

### ISSUE THREAD

**Issue by m1k3p** [dnnsoftware/Dnn.Platform#3566]
**Environment**
DNN 9.4.4 Virgin install using .net 4.7.2 on IIS / SQL Server 2016.
**Steps to reproduce**
When trying to delete files or folders in the file system (dnn.DigitalAssets.js) there is no confirmation dialog, and the delete fails. There are no console errors.
**Expected**
User is asked to confirm, and file / folder is deleted upon acceptance.

**Comment by m1k3p** [comment]
This also seems to affect the deletion of modules from the dropdown menu..

**Comment by valadas** [comment]
Did you check that the worker process has full permissions on the folder, I had no issues deleting...

**Comment by m1k3p** [comment]
Investigating now..

**Comment by m1k3p** [comment]
The IIS App Pool has full control - This is happening for me on 2 separate servers with DNN 9.4.4 on IIS 10.0.14393 .Net 4.7.2 and .Net 4.8

**Comment by m1k3p** [comment]
This can be closed - Apologies it's the SKIN causing the JS issue..

**Comment by valadas** [comment]
Cool
