### ISSUE TITLE
Data Consent Active unable to consent during login.

### ISSUE THREAD

**Issue by james7342** [dnnsoftware/Dnn.Platform#3580]
## Description of bug
Was playing the the Data Consent option on my test site. When turned on and using custom login page. When placing a check in the check box to accept the terms the submit button remains inactive.

## Steps to reproduce
List the precise steps to reproduce the bug:
Setup create a custom login page and add the Account Login Module. In site settings set the login page to new custom page.

1. Settings/Site Settings/Privacy/Data Consent Active - On
2. Logout
3. Login with valid user account
4. Place check box in "Accept the terms"
5. Submit button never changes to active.

## Current behavior
Submit never changes to active and user cannot proceed.

## Expected behavior
Submit button becomes active and user can login. 

## Screenshots
![screenshot_1169](https://user-images.githubusercontent.com/27960723/74798453-9f4bea00-5282-11ea-9d5b-ed37f103e129.png)

## Error information
As you can seen in the image. The class changes when the box is checked versus unchecked.
When the class is checked the button disabled="disabled" never changes.
![screenshot_1170](https://user-images.githubusercontent.com/27960723/74798990-2c437300-5284-11ea-8832-bce218c3d1ce.png)

## Additional context
Only way to login is with a host account to disable the Data Consent Active - Off

## Affected version
Tested with 9.4.4 and 9.5.0 sites.
* [ ] 10.0.0 alpha build
* [X] 9.5.0 alpha build
* [X] 9.4.4 latest supported release

## Affected browser
Only tested with the below browsers
* [ ] Chrome
* [X] Firefox
* [X] Safari
* [ ] Internet Explorer 11
* [ ] Microsoft Edge (Classic)
* [ ] Microsoft Edge Chromium

Note: Wasn't able to duplicate on another test using the default login behavior.

**Comment by DNNMonster** [comment]
Reported here #3193

**Comment by james7342** [comment]
@DNNMonster Thanks. I'll go ahead and close this as it's a duplicate.
