### ISSUE TITLE
The Sitemaps.aspx is not updated correctly

### ISSUE THREAD

**Issue by marcoburlando** [dnnsoftware/Dnn.Platform#3589]
## Description of bug
Sitemaps.aspx does not update with new pages. 
And also, if disable cache file the sitemaps become empty. even if you reset the cache.

## Steps to reproduce
List the precise steps to reproduce the bug:
1. Go to Personal Bar -> SEO
2. Go to Sitemap Settings
3. Click on sitemap URL and see the content
4. Select "Days to Cache Sitemap For" = Disable Caching and save
5. Reload the sitemap URL and see empty content
6. Reset the "Days to Cache Sitemap For" to 1 Day and save.

## Current behavior
The sitemap become empty. Same problem to see the new page on sitemaps. 
The sitemap is not updated correctly.

## Expected behavior
Update the sitemap.xml with correct pages.

## Affected version

* [ ] 10.0.0 alpha build
* [ ] 9.5.0 alpha build
* [x ] 9.4.4 latest supported release

**Comment by EPTamminga** [comment]
The sitemap is sitemap.aspx, not sitemap.xml?

**Comment by marcoburlando** [comment]
Yes sorry, I correct. 
I try other test and I found a solution. 
The coreSitemapProvider wasn't setting to priority = 1.
After this the sitemaps work correctly.
I close the bug.
