### ISSUE TITLE
Additional concerns around #2846

### ISSUE THREAD

**Issue by dbacher** [dnnsoftware/Dnn.Platform#3598]
It won't let me comment on #2846 so I'm posting additional comments related to this:
I had a couple things I missed I thought of this morning when I read the time out mail, also.
When you're setting up Google, Facebook, Microsoft, Twitter, or other OAUTH authentication - you likely receive a different user identifier based on the ID the website provides to the server.  And so if the authentication database is shared, these identifiers need to be global or all login needs to be managed by a single domain name.
If the user is using a password manager - 1Password, LastPass, Keepass, etc. - you really need the logon page to be on a single domain; that helps with phishing concerns as well.  And so if you're going to share the information between domains or subdomains that have separate authentication cookies, then you're going to want to address that as well.
Similarly, if someone wanted to use WebAuthn, etc., with a hardware token as either a primary or secondary factor, since those tie to the domain name you'd have issues as well.
And so ideally, you'd want to deal with that as well.
Which means if you **are** sharing login details between portals running on the same server, you most likely want a single, branded login page and not a separate login page per site, since that encourages terrible password practices and leads to password managers offering up wrong passwords without additional configuration.

**Comment by valadas** [comment]
I was able to comment on #2846 please try that again to avoid duplication I will close this issue in favor of 2846
