### ISSUE TITLE
Support Dependency Injection from Scheduler

### ISSUE THREAD

**Issue by bdukes** [dnnsoftware/Dnn.Platform#3602]
## Description of problem
There is no way to access services in the Dependency Injection container from a scheduler client.

## Description of solution
When DNN creates a scheduler client, it needs to use the DI container.

## Additional context
Based in a discussion at https://dnncommunity.org/forums/aft/890 and via https://dnntag.slack.com/

**Comment by valadas** [comment]
I am not an expert at DI and I did not build code samples to test this so just asking questions :)

I was under the impression that we use Microsoft one unaltered so that something like:
```
public class MyScheduler : SchedulerClient
{
    protected IPortalController PortalController { get; }

    public MyScheduler(IPortalController portalController)
    {
        this.PortalController = portalController;
    }
}
```
would just work out of the box... Right?

Now for the forum post at hand, the major issue (which is not new) is that the scheduler has no HTTP Context and one needs to use another way to obtain the portalId (configuration, settings, etc.) to get a PortalInfo object manually from code.

**Comment by bdukes** [comment]
DNN currently supports constructor injection in :one: Web API controllers, :two: MVC controllers, :three: Razor models, and it supports "service location" in WebForms via `PortalModuleBase.DependencyProvider`.  

Anywhere else that DNN is creating new instances of classes, dependency injection (neither constructor injection nor service location) is not yet supported.  In this particular case, creating a `SchedulerClient` involves explicitly calling the constructor which takes a single `ScheduleHistoryItem` https://github.com/dnnsoftware/Dnn.Platform/blob/c35fdc7fb75db0438f3b872ce4e279e3ea73e7c2/DNN%20Platform/Library/Services/Scheduling/ProcessGroup.cs#L157-L173

**Comment by mitchelsellers** [comment]
This one could be a bit interesting since we have an architecture requirement with the first parameter being the ScheduleHistoryItem.  It is possible that we might have to do something different for this to support DI.

**Comment by dimarobert** [comment]
You could use [`ActivatorUtilities.CreateInstance(IServiceProvider, Type, Object[])`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.dependencyinjection.activatorutilities.createinstance?view=dotnet-plat-ext-3.1) or `ActivatorUtilities.CreateInstance<T>(IServiceProvider, Object[])`. The third parameter is for additional constructor parameters that cannot be resolved from the ServiceProvider. In your case the `ScheduleHistoryItem`.

Another note, to preserve the lifetime of scoped services resolved in this manner ([see details about the pitfalls of MS DI](https://github.com/dnnsoftware/Dnn.Platform/pull/3520#issuecomment-578186734)) you should open a scope from the `Globals.DependencyProvider` for each execution of the scheduler and resolve from it. You will also need to dispose it accordingly to avoid memory leaks. _A good example of a scoped service would be the DbContext of EntityFramework._
