### ISSUE TITLE
When using Basic Auth or JWT Auth I get an invalid cast exception

### ISSUE THREAD

**Issue by lawred2** [dnnsoftware/Dnn.Platform#3603]
## Description of bug
Can't make requests with JWT token or Basic Auth

## Steps to reproduce
List the precise steps to reproduce the bug:
1. Create jwt token
2. Try to make request with Authorization: Bearer <jwt> set
3. Exception

1. Try to make request with Basic Auth
2. Exception

## Current behavior
Exception when attempting to make any request with either an acquired jwt token or basic creds

## Expected behavior
Should be able to use basic auth or jwt auth as per documentation when making api requests

## Error information
2020-03-02 23:16:23.293+00:00 [DESKTOP-9602N1D][D:3][T:19][ERROR] DotNetNuke.HttpModules.Membership.MembershipModule - System.InvalidCastException: Unable to cast object of type 'System.Security.Principal.GenericIdentity' to type 'System.Web.Security.FormsIdentity'.
   at DotNetNuke.HttpModules.Membership.MembershipModule.RequireLogout(HttpContextBase context, UserInfo user)

## Additional context
Provide any additional context that may be helpful in understanding and/or resolving the bug.

## Affected version

* [ ] 10.0.0 alpha build
* [ ] 9.5.0 alpha build
* [x] 9.4.4 latest supported release

## Affected browser
Api clients

For what it's worth - it's easy to see where the exception is

DNN Platform/HttpModules/Membership/MembershipModule.cs

Line 264 ->` var issueDate = ((FormsIdentity)context.User.Identity)?.Ticket.IssueDate;`

Looks like in the case of an API client - it's a GenericIdentity type and not a FormsIdentity type.

Hope you can help.

**Comment by DNNMonster** [comment]
Your error may not be related but I don't believe you can use both the JWT and DNNAuthorize attributes at the same time.  Looks like you might be working with both so it's worth knowing even if it's not the root cause here.

https://www.dnnsoftware.com/answers/use-multiple-auth-handlers
