### ISSUE TITLE
Missing objectQualifier in 9.5.0 SQL migration script.

### ISSUE THREAD

**Issue by dimarobert** [dnnsoftware/Dnn.Platform#3604]
## Description of bug
The SQL migration script for 9.5.0 is not fully tokenized. The `CoreMessaging_GetNextMessagesForDigestDispatch` stored procedure doesn't have the objectQualifier set.

Introduced in #3540.

## Steps to reproduce
Install/Upgrade to 9.5.0

## Current behavior
Errors will be logged by the Scheduler in Admin Logs.

## Expected behavior
No error logs.

## Affected version

* [ ] 10.0.0 alpha build
* [x] 9.5.0 build
* [ ] 9.4.4 latest supported release

## Affected browser

* [ ] Chrome
* [ ] Firefox
* [ ] Safari
* [ ] Internet Explorer 11
* [ ] Microsoft Edge (Classic)
* [ ] Microsoft Edge Chromium

**Comment by valadas** [comment]
Thanks @dimarobert as an additional note, the steps to reproduce would be valid for an upgrade on an instance that uses an objectQualifier and/or a custom databaseOwner
