### ISSUE TITLE
Exception on DNN 9.5 when same MVC module inserted several times on a page

### ISSUE THREAD

**Issue by jacoch** [dnnsoftware/Dnn.Platform#3608]
## Description of bug
An MVC module working properly on DNN 9.2 to 9.4 returns an exception when inserted several times on a page. DNN returns following exception:

DotNetNuke.Services.Exceptions.ModuleLoadException: A single instance of controller 'Dnn.Modules.MyModuleName.Controllers.MyController' cannot be used to handle multiple requests. If a custom controller factory is in use, make sure that it creates a new instance of the controller for each request. ---> System.InvalidOperationException: A single instance of controller 'Dnn.Modules.MyModuleName.Controllers.MyController' cannot be used to handle multiple requests. If a custom controller factory is in use, make sure that it creates a new instance of the controller for each request. at System.Web.Mvc.ControllerBase.VerifyExecuteCalledOnce() at System.Web.Mvc.ControllerBase.Execute(RequestContext requestContext) at DotNetNuke.Web.Mvc.Framework.Modules.ModuleApplication.ExecuteRequest(ModuleRequestContext context) at DotNetNuke.Web.Mvc.MvcHostControl.ExecuteModule().

As the same module works fine for year on different versions of DNN, I have not spent much time on trials. Wanted to get your feedback first to learn if something can be changed in module code to fix this.

## Steps to reproduce
List the precise steps to reproduce the bug:
1. Place an MVC module several times on a page.
2. Display the page.
3. The exception above is returns on second module. First module is displayed properly.

## Current behavior
Only the first module is displayed properly. The other ones on the same page return the exception above.

## Expected behavior
All modules should work properly as they did on previous version.

## Affected version

* [ * ]  9.5.0 latest supported release
* [ ]  9.4.4 and prior work fine

## Affected browser
Does not depend on browser.

**Comment by mitchelsellers** [comment]
Can you confirm that this does still occur in 9.5.0?  Just want to confirm first as there were changes in 9.5.0 that could improve and your notes say that 9.4 is the issue

**Comment by jacoch** [comment]
Hi. No. I'm saying the opposite. The module was developed on DNN 9.2 and upgrade to latest 9.4.4 without issue. Problem only occurs on 9.5.0 after upgrading the web site.

**Comment by valadas** [comment]
I tried with the attached module in 9.5.0 and 9.5.1, I was able to reproduce only on 9.5.0 and not in 9.5.1 using the attached module. So I would start by upgrading, if that does not fix it, please report back and I will be glad to reopen the issue.
[TestModule_00.00.01.00_Install (1).zip](https://github.com/dnnsoftware/Dnn.Platform/files/4283745/TestModule_00.00.01.00_Install.1.zip)

**Comment by jacoch** [comment]
Thanks for prompt reply. Tested some minutes ago on 9.5.1rc1. The test module still returns the same error. I suppose the fix is not yet applied to release.

Error returned :  DotNetNuke.Services.Exceptions.ModuleLoadException: A single instance of controller 'Wingman.FPF.Modules.TestModule.Controllers.DefaultController' cannot be used to handle multiple requests. If a custom controller factory is in use, make sure that it creates a new instance of the controller for each request.

**Comment by valadas** [comment]
Strange... @jacoch let's continue this on #3634 as it has a possible solution path in there...
