### ISSUE TITLE
All User Edit mode option

### ISSUE THREAD

**Issue by garyfrater** [dnnsoftware/Dnn.Platform#3617]
## Description of problem
Having used DNN for quite a few years now one of the main issues we've always had with users that have permissions to edit tab permissions and/or module permissions is the accidental setting of the All Users/Edit permission, especially with the 3 states of the checkbox. This tends to only get noticed when someone has deleted a module or page (thankfully the recycle bin is there).

## Description of solution
Is there ever a need for all users to be able to edit tabs/modules? Would it be possible to remove this option from both tabs and modules?

**Comment by thabaum** [comment]
I could see a page child level permissions being able to do certain things such as give or remove add/delete pages, add/delete modules and other permissions specific to more a content creator type of roll.  

And also in each module instance settings have similar type of permissions that can be set.  

And if they create it they get certain permissions and a way to limit what modules a role with these permissions can use.   

And possibly a way to set these to a default setting for whoever uses them for a first time on a page.

I like the idea!

**Comment by sleupold** [comment]
In DNN 7and 8 there used to be a check to prevent granting Edit permission for a page to "all users" or "registered Users" role

**Comment by schotman** [comment]
I can confirm this. 
Allthough the personabar is not visible, this seems to me a serious issue. I suppose the best way to prevent this, is to have code preventing to be able to check the "Edit" checkbox for all users (at least).

**Comment by valadas** [comment]
I agree this should go away, there is no good reason for ever having all users being able to edit.
