### ISSUE TITLE
9.5.0 Not Showing start/end date icons in User Roles

### ISSUE THREAD

**Issue by james7342** [dnnsoftware/Dnn.Platform#3619]
## Description of bug
DNN 9.5.0 not showing Start/End date icons when editing user role

## Steps to reproduce
1. Select user to edit
2. Click the "Shield" - Users Role Icon.
3. Highlight role and notice to the left there is no icons available. Just text [objectModule]

## Current behavior
Click the text still allows start/end date selection. Just missing icon that was there in 9.4.4

## Expected behavior
Icon displayed and not [ObejctModule] Text

## Screenshots
![screenshot_1181](https://user-images.githubusercontent.com/27960723/76169925-62b13700-613a-11ea-8161-818d3fae2fdd.png)

## Error information
None

## Affected version

* [ ] 10.0.0 alpha build
* [ ]  9.5.1 alpha build
* [X]  9.5.0 latest supported release
* [ ]  9.4.4 

## Affected browser
Only Tested with Safari Suspect not browser related.
* [ ] Chrome
* [ ] Firefox
* [X] Safari
* [ ] Internet Explorer 11
* [ ] Microsoft Edge (Classic)
* [ ] Microsoft Edge Chromium

**Comment by james7342** [comment]
Was able to duplicate on 2 installations.

**Comment by v-karbovnichy** [comment]
I can confirm this:

![image](https://user-images.githubusercontent.com/7301634/76782533-d81ba800-67c9-11ea-9551-cd52e928af7e.png)

![image](https://user-images.githubusercontent.com/7301634/76782552-e10c7980-67c9-11ea-9794-348691d6cec3.png)

**Comment by valadas** [comment]
Confirmed in 9.5.1 also

**Comment by daguiler** [comment]
I have a PR ready to fix this
