### ISSUE TITLE
Source Code download for Dnn 9.5.0 still has version 9.4.4 on solutioninfo file

### ISSUE THREAD

**Issue by Mncool** [dnnsoftware/Dnn.Platform#3622]
Just downloaded the source code for Dnn 9.5.0 and noticed that it was building 9.4.4 version. Did it just missed the update to the new version number, or is this the actual 9.4.4 version and the link for Dnn 9.5.0 is incorrect.

**Comment by valadas** [comment]
Upon build, the version get's set by the build scripts. We went from hard coded versions to fully automated versions to a hybrid solution. Right now whatever version is in the source code would get replaced at build time for the correct one, but we plan on improving the process so the source code at least matches the last or next release number or some such. This is still a work in progress and there is another issue on the plate for this. But right now, if you read the build documentation, it is automated for releases and for people needing to specify the version manually, you can create a local settings file for it also. See https://github.com/dnnsoftware/Dnn.Platform/blob/develop/.github/BUILD.md
