### ISSUE TITLE
Outdated Libraries identified from Blackduck scans

### ISSUE THREAD

**Issue by wengkin** [dnnsoftware/Dnn.Platform#3623]
## Description of problem
The following runtime assemblies have identified newer versions available.
- Microsoft.AspNet.WebPages.Data (3.1.1) at bin\WebMatrix.Data.dll
- Microsoft.AspNet.WebPages.WebData (3.1.2) at bin\WebMatrix.WebData.dll
- LiteDB (3.1.1) at bin\LiteDB.dll
- Knockout.Validation (unknown) at DesktopModules\Admin\Dnn.PersonaBar\scripts\contrib\knockout.validation.min.js
- Knockout.Validation (unknown) at DesktopModules\Admin\Dnn.EditBar\scripts\contrib\knockout.validation.min.js

## Description of solution
Replace the runtime assemblies with the newest versions.
- Microsoft.AspNet.WebPages.Data (3.2.7)
- Microsoft.AspNet.WebPages.WebData (3.2.7)
- LiteDB (5.0.3) 
- Knockout.Validation (2.0.4)

## Description of alternatives considered
No available recommendations.

## Additional context
The findings were identified during a blackduck scan with the above recommended newer versions.

**Comment by valadas** [comment]
If I am not mistaken we have NDepend setup to track dependencies updates and we will soon re-enable dependabot for javascript. Correct @dnnsoftware/approvers ?

Sometimes the reasons why some are not updated quick is because of breaking changes affecting third parties and we have to wait for a major release to bump them.

**Comment by mitchelsellers** [comment]
We have nothing for .net dependencies 

We need to setup dependabot

**Comment by valadas** [comment]
Haaa, so what is NDepend for ?

**Comment by sleupold** [comment]
still an issue?
