### ISSUE TITLE
Truncate module title .dnn_menu_label

### ISSUE THREAD

**Issue by 10PoundGorilla-ChrisBehling** [dnnsoftware/Dnn.Platform#3626]
## Description of problem
The module label displayed in .dnn_menu_label pulls from the module title. If the module title becomes lengthy it can cause an overflow onto other modules or extend the page length in unintended ways. Long module display labels add to visual clutter that can be controlled or standardized. 

While you can go and update the title in the module settings, we can't expect the end user to do this. Having some sort of truncate would be great. Some modules (2sxc in this example) pull the contents "favorite" input control to display in the .dnn_menu_label. 

## Description of solution
- Implement a standard truncate limit of 15 characters for displaying in the .dnn_menu_label.
- Create a definition that can be managed in DNN to set the truncate limit for maximum flexibility.

## Description of alternatives considered
- Implement css to achieve truncate with the following markup
(found here: /admin/menus/ModuleActions/ModuleActions.css:185)
`
.div.actionMenu ul.dnn_mact li.dnn_menu_label > div{ 
    max-height: 120px;
    white-space: nowrap;
    overflow: hidden;
    text-overflow: ellipsis;
}
`
This markup uses the height parameter to determine the length of the truncate but would not provide customization like a DNN definition could. 

## Screenshots
[Current View](https://www.dropbox.com/s/olaqrgl8nfohohd/current-view.png?dl=0)
[Proposed View](https://www.dropbox.com/s/lcobo973ta6mxou/proposed-view.png?dl=0)

## Affected browser

* [x] Chrome
* [x] Firefox
* [x] Safari
* [x] Internet Explorer
* [x] Edge

**Comment by valadas** [comment]
I for one find the vertical label ridiculous, we do have room in the dotted drag bar to have it horizontal.

**Comment by 10PoundGorilla-ChrisBehling** [comment]
> I for one find the vertical label ridiculous, we do have room in the dotted drag bar to have it horizontal.

That sounds like an even better solution than a truncate.
