### ISSUE TITLE
Testing Emails Does Not Currently Use Site Administrator

### ISSUE THREAD

**Issue by thabaum** [dnnsoftware/Dnn.Platform#3629]
## Description of bug
Provide a clear and concise description of the bug.

## Steps to reproduce
List the precise steps to reproduce the bug:
1. Create a site with Administrator using a gmail account
2. Setup account using Hotmail account SMTP settings
3. Mail is tested sending the SMTP settings
4. Mail will get refused from Hotmail because DNN will send using Administrators gmail email account for username instead of the account set in the SMTP Portal settings.

## Current behavior
Testing emails from the set account information will work however it is testing using the SMTP address and not the Site Administrator account I don't believe.

## Expected behavior
Administrator account is for "Receiving" notifications not for sending SMTP settings.  

These should be independent of each other.

This results in complications trying to troubleshoot email issues.

## Screenshots
If applicable, provide screenshots to help explain the bug.

## Error information
Provide any error information (console errors, error logs, etc.) related to this bug.

## Additional context
I will see if I can work this out as desired for community.  I had to create new accounts for each portal with a new administrator because if you just use Host accounts for administration it will try to send using that host email instead of the email set in SMTP settings.

The account information supplied in SMTP settings should be the only ones you need to worry about to setup email communication for registrations.

I use a noreply address or one that is not being listened to so it is crucial to have this setup right.

I do believe an email should be "sent" to the administration account but do NOT use the email for SMTP account settings.

I am pretty familiar with this area but if someone beats me to it that is cool :)

## Affected version

* [ ] 10.0.0 alpha build
* [ ]  9.5.1 alpha build
* [ ]  9.5.0 latest supported release
* [ ]  9.4.4 

## Affected browser

* [ ] Chrome
* [ ] Firefox
* [ ] Safari
* [ ] Internet Explorer 11
* [ ] Microsoft Edge (Classic)
* [ ] Microsoft Edge Chromium

**Comment by valadas** [comment]
I am not sure I understand the issue, the stmp settings don't include and email address. There is a host email address and then each site will use the site owner (primary administrator) email address. 

In the steps to reproduce, can you explain a bit more the from and to emails and the host vs site level smtp settings and who is logged in while testing.

My expectation is that if a host is logged in and is testing the host level smtp settings, it should be from and to the host email.

If a host is logged in and is testing a site level smtp settings, it should be from the site owner to the host. 

If and admin is text it should be from and to the admin.

**Comment by sleupold** [comment]
@valadas 
if using host configuration for SMTP, testing config should use host email address as sender and recipient.
if using sIte (portal) specific SMTP settings, email address should be taken from user account, specified as (primary) site admin in website settings.

**Comment by thabaum** [comment]
That is correct.  

Issue is if your have an admin that is not set with an account that can authenticate using the SMTP settings for portal or host.  The address must come from the domain that the account is setup for.  gmail is google so you could not use a gmail account to get notifications. 

I suppose I am suggesting something similar to the "host email' that you can set but one for using for sending emails rather than one attached to an account.  This way it may or may not be the administrators email that can be used for sending and actually authenticate.  And if you change administrators anytime the email can move with it and not have to worry to change SMTP server settings or visa versa to ensure things work.

Another example is you want to send everything using "no-reply" address but you still want to get notifications of users getting created to your actual account you use about things happening from that same no-reply address.

**Comment by thabaum** [comment]
I am just going to close this issue for now.
