### ISSUE TITLE
Exception on DNN 9.5.1 when same MVC module inserted several times on a page 

### ISSUE THREAD

**Issue by DaveMartinSE** [dnnsoftware/Dnn.Platform#3634]
## Description of bug

MVC Module when inserted multiple times on a page results in exception:

```
Error: Contact List Mvc is currently unavailable. DotNetNuke.Services.Exceptions.ModuleLoadException: A single instance of controller 'Dnn.ContactList.Mvc.Controllers.ContactController' cannot be used to handle multiple requests. If a custom controller factory is in use, make sure that it creates a new instance of the controller for each request. ---> System.InvalidOperationException: A single instance of controller 'Dnn.ContactList.Mvc.Controllers.ContactController' cannot be used to handle multiple requests. If a custom controller factory is in use, make sure that it creates a new instance of the controller for each request. at System.Web.Mvc.ControllerBase.VerifyExecuteCalledOnce() at System.Web.Mvc.ControllerBase.Execute(RequestContext requestContext) at DotNetNuke.Web.Mvc.Framework.Modules.ModuleApplication.ExecuteRequest(ModuleRequestContext context) at DotNetNuke.Web.Mvc.MvcHostControl.ExecuteModule() --- End of inner exception stack trace ---
```

Module used to test:
https://github.com/dnnsoftware/Dnn.Platform.Samples.Mvc/blob/master/Website/Install/Module/DNN_ContactList_Mvc_01.00.01_Install.zip

Related Issue Previously Reported: https://github.com/dnnsoftware/Dnn.Platform/issues/3608

## Steps to reproduce
List the precise steps to reproduce the bug:
1. Place MVC Module on the page twice
2. Display page
3. Exception shows in the second module. First module loads correctly.

## Current behavior
First module loads correctly. Second fails to load due to exception.

## Expected behavior
Both modules should load without exception.

## Screenshots
If applicable, provide screenshots to help explain the bug.
![image](https://user-images.githubusercontent.com/36711544/77178330-52377f80-6a9d-11ea-8341-ce610f204abb.png)

## Error information
Looks related to changes in 9.5.0 and continued in 9.5.1 to use Scoped instancing for IDNNControllers. 

Exceptions occurs here:

https://github.com/dnnsoftware/Dnn.Platform/blob/release/9.5.1/DNN%20Platform/DotNetNuke.Web.Mvc/Framework/Modules/ModuleApplication.cs#L127

Current workaround is to change TryAddScoped to TryAddTransient in the mvc load extension here:

https://github.com/dnnsoftware/Dnn.Platform/blob/release/9.5.1/DNN%20Platform/DotNetNuke.Web.Mvc/Extensions/StartupExtensions.cs#L25

## Affected version
* [ ] 10.0.0 alpha build
* [X]  9.5.1 alpha build
* [X]  9.5.0 latest supported release
* [ ]  9.4.4 

## Affected browser
Browser independent

**Comment by bdukes** [comment]
That workaround looks like the right answer.  I'm going to setup a test environment and verify, then I'll submit a PR.  Thanks!
