### ISSUE TITLE
PersonaBar Users Send Password Reset Link Error

### ISSUE THREAD

**Issue by thabaum** [dnnsoftware/Dnn.Platform#3637]
## Description of bug
PersonaBar Users Send Password Reset Link Error

## Steps to reproduce
List the precise steps to reproduce the bug:
1. Create multiple portals
2. Set Host settings SMTP
3. Set different Portal Settings SMTP that is "suppose" to use administrator account to send
4. Log in with the super user account into a portal with a different administrator account
5. Send password reset link will result in error.   
## Current behavior
If logged in as another administrator with an email account different from the one setup for portal settings it will use your current users email address to send instead of PortalSettings.Email

## Expected behavior
Use the Portal Administrator account to send the email so that the SMTP server uses that email address for authorization of the email to be sent.  Most SMTP servers must have a local user email account so if you send while using a different account you get this error.

## Screenshots
![image](https://user-images.githubusercontent.com/13577556/77231888-ee738c00-6b5a-11ea-923d-408713aa061c.png)

If applicable, provide screenshots to help explain the bug.

## Error information

> 

> AbsoluteURL:/API/PersonaBar/Users/SendPasswordResetLink
> 
> Message:User not local; please try a different path. The server response was: Sender address is not valid for your login. Check your email program settings.
> 
> StackTrace:
> 
>    at System.Net.Mail.MailCommand.CheckResponse(SmtpStatusCode statusCode, String response)
>    at System.Net.Mail.MailCommand.Send(SmtpConnection conn, Byte[] command, MailAddress from, Boolean allowUnicode)
>    at System.Net.Mail.SmtpTransport.SendMail(MailAddress sender, MailAddressCollection recipients, String deliveryNotify, Boolean allowUnicode, SmtpFailedRecipientException& exception)
>    at System.Net.Mail.SmtpClient.Send(MailMessage message)
>    at DotNetNuke.Services.Mail.Mail.SendMailInternal(MailMessage mailMessage, String subject, String body, MailPriority priority, MailFormat bodyFormat, Encoding bodyEncoding, IEnumerable`1 attachments, String smtpServer, String smtpAuthentication, String smtpUsername, String smtpPassword, Boolean smtpEnableSSL)
 
 ## Additional context 

Documentation at least can be updated to show how to properly manage a site for sending out notificitions that you must be logged in using the administrator account with the assigned email address for SMTP settings to function properly.

or fix the SMTP settings to use only the HOST email settings or PORTAL email address assigned settings

I believe these notifications of different classes could also be something that is set in "Communications" tab of site settings to allow setting the different email addresses for different use cases such as notifications, accounts, billing, shopping and support.

I believe I will try to at least document this so that it is known to use the multi-portals with care in respect to sending out messages while logged in a host user instead of the assigned administrator account for SMTP to work if you have Email as Username.

A switch to ONLY use the portal SMTP account settings as email address as the ONLY from address unless overridden by modules would be nice as well so then you can set anything.

Thing work but only if you understand the issue at hand here.  I don't think it is working 100% as intended as it should be using the host administrator account for default account to send from instead of the user logged in sending it.   Which is why I believe this is a bug that can get ironed out.

## Affected version

> * [ ] 10.0.0 alpha build
> * [ ]  9.5.1 alpha build
> * [ ]  9.5.0 latest supported release
> * [ ]  9.4.4 
> 
> ## Affected browser
> 
> * [ ] Chrome
> * [ ] Firefox
> * [ ] Safari
> * [ ] Internet Explorer 11
> * [ ] Microsoft Edge (Classic)
> * [ ] Microsoft Edge Chromium
>

**Comment by thabaum** [comment]
Found my issue I believe I had wrong administrator account assigned to the portal.  I am reviewing settings more.

**Comment by thabaum** [comment]
on another note, Primary Administrator should be able to have any email account such as GMail but for mail servers like mine you need to authenticate prior to sending and you can only send using that account provided as sender.

Primary Administrator message should also include this is the email used for "Portal SMTP Settings" for sending emails from the system such as verification emails and notifications.

I believe there needs to be a second account created for each purpose again so Gmail administrators can get the emails sent by the system notifications.  They should both get emails from the "Send From Only" possibly setting being made so DNN uses only the Username provided or a certain email address as things can be configured both ways for different purposes or projects desired results.

![image](https://user-images.githubusercontent.com/13577556/77232855-b1aa9380-6b60-11ea-9d96-cd71ff851cbc.png)

**Comment by valadas** [comment]
I would not disagree to add a site email in addition to the primary administrator email. The admin email would receive most stuff and the site email can be a noreply@something.com or some such. We could make the site email fallback to the primary admin if it is unset. This solution we can probably do inside platform, now nothing says all third party modules would implement it any soon... But yeah, I would not find that a bad idea.
