### ISSUE TITLE
Potential bug in dnn.DigitalAssets.js

### ISSUE THREAD

**Issue by roman-yagodin** [dnnsoftware/Dnn.Platform#3646]
I think I've found a bug in the `dnn.DigitalAssets.js` code at https://github.com/dnnsoftware/Dnn.Platform/blob/a6bfc01e5697d6fba2761853fef6d9450905712d/DNN%20Platform/Modules/DigitalAssets/ClientScripts/dnn.DigitalAssets.js#L1454

Original code:

```JavaScript
function loadFolderCurrentPage(folderId) {
  internalResetGridComponents();
  loadFolder(folderId, grid.get_currentPageIndex(), grid.get_pageSize(), null);
}
```

Judging by other calls to `loadFolder()` and similar methods, there `startIndex` is calculated as `grid.get_currentPageIndex() * pageSize`, I think this should be more like that:

```JavaScript
function loadFolderCurrentPage(folderId) {
  internalResetGridComponents();
  var pageSize = grid.get_pageSize();
  var startIndex = grid.get_currentPageIndex() * pageSize;
  loadFolder(folderId, startIndex, pageSize, null);
}
```

Do not know how important this could be - for me DAM module works the same with or without the fix, but I think the difference in code is obvious.

**Comment by mikesmeltzer** [comment]
There is a new feature to replace the DAM module with a module called Resource Manager. Once that is implemented this issue could be closed I'm guessing.

See #3708 for more details.

**Comment by valadas** [comment]
Yes, we are working out the final kinks in the new module so I am closing this issue in favor of the new Resource Manager module in progress.
