### ISSUE TITLE
Using both the JWT and DNNAuthorize attributes at the same time doesn't work

### ISSUE THREAD

**Issue by dehghani-mehdi** [dnnsoftware/Dnn.Platform#3647]
Is there any way to use both the `JWT` and `DNNAuthorize` attributes at the same time?

I tried following but doesn't work.
```
[DnnAuthorize(AuthTypes="DNN,JWT")]
```
And
```
[DnnAuthorize(AuthTypes="Basic,JWT")]
```

## Affected version
* [x]  9.4.4

**Comment by mitchelsellers** [comment]
In the current implementation, this is not supported

**Comment by dehghani-mehdi** [comment]
.

**Comment by mitchelsellers** [comment]
Looking at the way this works in other platforms supporting both seems to be something that would open a possibility for mixed or unintended security.
