### ISSUE TITLE
Membership Directory does not localize countries

### ISSUE THREAD

**Issue by MaiklT** [dnnsoftware/Dnn.Platform#3650]
## Description of bug
When using the Membership Directory module, the country in the address is not localized

## Steps to reproduce
List the precise steps to reproduce the bug:
1. Add a Membership directory module on a non-English page
2. Make sure there is a resource file for that language (GlobalResources/List_Country.resx)
3. See the country name

## Current behavior
The module pulls the name of the country from the Lists table and not from the resource file. In the UserProfile table, you can find the ID from the list (e.g. 13 for Austria).

## Expected behavior
Localized value from the resource file.

## Affected version

* [X]  9.5.0 latest supported release
* [X]  9.4.4 

## Affected browser

not a browser issue

**Comment by MaiklT** [comment]
Still an issue.

**Comment by sleupold** [comment]
Still an issue

**Comment by MaiklT** [comment]
Please re-open. This is still an issue, and important for the image as an "international" product.

**Comment by valadas** [comment]
@donker this is already supported right by the Lists localization. So this would be probably the specific language pack used not having that included ?

**Comment by donker** [comment]
Should be fixed in 9.8.1
