### ISSUE TITLE
Users can't log in to child portals when username is email

### ISSUE THREAD

**Issue by donker** [dnnsoftware/Dnn.Platform#3660]
##  Description of bug
This concerns the master/child portal structure that can exist in DNN. If you have a master portal for a child portal, then during login using email the user is looked up in the child portal and not the master portal as it should.

## Steps to reproduce
In an installation with a master/child portal structure
1. Switch child portal to use email as username
2. Log out
3. Try to log in as any user

## Current behavior
Can't log in

## Expected behavior
Log in

## Affected version
* [? ] 10.0.0 alpha build
* [ x]  9.5.1 alpha build
* [ x]  9.5.0 latest supported release
* [ x]  9.4.4 

## Affected browser
n/a

**Comment by thabaum** [comment]
Is this a "Site Group"  I have not yet played with that feature much, and "child portals" features vanished version 9.  Although I may not know where they are in the PersonaBar.
It is good to see you going through the "email as username" bugs.  I know it has me in the back of my mind saying "stay away" although each time I look at the feature it is very tempting to turn on.

**Comment by donker** [comment]
Fixed by #3659
