### ISSUE TITLE
Redirect after login not working if Login page has a different name than login

### ISSUE THREAD

**Issue by edisfera** [dnnsoftware/Dnn.Platform#3661]
## Description of bug
If a page to be redirected after login is set in Settings > Security tab Login settings but the login page name is called different from Login (i.e. Enter) the redirect page is ignored.

## Steps to reproduce
1. Create a login page not named Login (buy the way this is trapped by DNN and one cannot create a page called Login!) and insert the login module in it. Then set that page to be the login page of the portal.
2. Set a page to be redirected to after login
3. Then try to login 

## Current behavior
The user is redirected to the home page instead of the intended page (the redirect after login page)

## Expected behavior
The user should be directed to the redirect after login page

## Error information
N/A

## Additional context
The error is caused by the following function in this source file Dnn.Platform-9.5.0\DNN Platform\Website\DesktopModules\Admin\Authentication\Login.ascx.cs at line 256:

private bool IsRedirectingFromLoginUrl()
{
      return Request.UrlReferrer != null &&
                Request.UrlReferrer.LocalPath.ToLowerInvariant().EndsWith(LOGIN_PATH);
}
because LOGIN_PATH is declared as follows
private const string LOGIN_PATH = "/login";
If the page is called Enter the LocalPath will be something like "/en-Us/Enter" and of course will never end with "/Login" thus returning always false if the login page is not called Login.

## Affected version
* [x]  9.5.0 latest supported release

**Comment by edisfera** [comment]
a possible fix could be the following (don't forget to comment out the declaration of LOGIN_PATH that is no longer needed):
        private string GetTabName(int tabId)
        {
            if (tabId == Null.NullInteger)
            {
                return "";
            }
            else
            {
                var tab = TabController.Instance.GetTab(tabId, PortalId);
                return tab != null ? tab.TabName : "";
            }
        }

        private bool IsRedirectingFromLoginUrl()
        {
            return Request.UrlReferrer != null &&
                //Request.UrlReferrer.LocalPath.ToLowerInvariant().EndsWith(LOGIN_PATH);
                Request.UrlReferrer.LocalPath.ToLowerInvariant().EndsWith("/" + GetTabName(PortalSettings.LoginTabId).ToLowerInvariant());
        }

**Comment by moorecreative** [comment]
I believe we are experiencing the same thing, however, the redirect does not work in 9.5 (where it did work before 9.4 and earlier) regardless of the Login page name/type.

In our scenario, 
- the Login page is called "Login" and is a page within DNN pages, 
- this page is set as the Login page within Site Settings
- if you call a page which has roles requiring Registered Users for view permission, requesting the page loads correctly sitename.com/Login?returnurl=%2fName-Of-Page 
- however, after successful login, it remains on the /Login page and does not redirect to the ReturnURL path specified in the query string.

**Comment by kmuralidaran** [comment]
@edisfera I am not sure whether my below observation is simplified version of reported bug or another bug
1. Login to DNN
2. Set a page to be redirected to after login (PostLogin)
3. Navigate to a page (Page1)
4. Logout
5. Login to DNN from current page (Page1)

Current behavior : Current page retained and no redirection happened, Redirection to PostLogin happens only if the current page is the home page

Expected behavior : The user should be redirected to the PostLogin page
