### ISSUE TITLE
Droplists showing value not text

### ISSUE THREAD

**Issue by LeoMrozek1895** [dnnsoftware/Dnn.Platform#3671]
## Description of bug
When using a control that is using type-a-ahead (like Country or Region) if you start to type the first three letters and use an arrow key to select from the list, the droplist displays the items value and not the text (i.e. enter "Uni" for united states and then hit the down arrow to select from list and it will show a number (I assume the items value from the database)

## Steps to reproduce
List the precise steps to reproduce the bug:
1. Open a page like registration that is including the Country lookup/listbox.
2. Start typing a country (i.e. "Uni" for United States)
3. A list will appear below the entered text with a list of countries.
4. Attempt to use the down arrow to select a country. The cursor stays in the text box which I assume is ok, but as you hit the down arrow, it cycles through item values (177, 242, etc) not the names of the countries you are looking for.

## Current behavior
See above

## Expected behavior
Would cycle through names of countries as you scroll through the list of names, not their value in the database.

## Screenshots
![bug-before](https://user-images.githubusercontent.com/63420482/78927495-a0202180-7a64-11ea-88ab-2de3994829cb.png)
![bug-after](https://user-images.githubusercontent.com/63420482/78927502-a2827b80-7a64-11ea-977d-23917e3c5ea2.gif)

## Error information
No errors displayed in any browser

## Additional context
Provide any additional context that may be helpful in understanding and/or resolving the bug.

## Affected version

* [ ] 10.0.0 alpha build
* [ ]  9.5.1 alpha build
* [X ]  9.5.0 latest supported release
* [ ]  9.4.4 

## Affected browser
Only ones I tried it in.
* [ x] Chrome
* [x ] Firefox
* [ ] Safari
* [ ] Internet Explorer 11
* [x ] Microsoft Edge (Classic)
* [ ] Microsoft Edge Chromium

**Comment by david-poindexter** [comment]
This issue was auto-closed by mistake due to an incorrect reference.  Reopening.

**Comment by valadas** [comment]
I cannot find it, but this may duplicate an existing issue, I could swear I logged this issue. Oh well, let's keep this one if we don't find the other one.

**Comment by sleupold** [comment]
still an issue?

**Comment by valadas** [comment]
Yeah, I believe so.
