### ISSUE TITLE
Gibberish Links at top of popup

### ISSUE THREAD

**Issue by LeoMrozek1895** [dnnsoftware/Dnn.Platform#3679]
![2020-04-14_12-17-53](https://user-images.githubusercontent.com/63420482/79254858-fae1c080-7e4a-11ea-899d-e5d1b91f5cf6.png)

## Description of bug
Open any item in Languages to change the text of an item (i.e. //AboutUs.String and click the pencil to open the editor and a bunch of links that are stacked on each other are at the top of the textarea where editing is to occur.

## Steps to reproduce
List the precise steps to reproduce the bug:
1. Go to Site Settings > Languages > and click on the Translations icon to bring up the list of items that can be edited.  
2. Select GlobalResources.resx from the Resource file list and select "GlobalResources" from the drop list
3. Select the pencil icon for any item displayed and you will see a bunch of links stacked across the top of the text area to be edited. See attached image.

## Current behavior
See Steps Above

## Expected behavior
Not sure what the links are supposed to be. Cannot read or want to risk clicking something I don't know what it is.

## Screenshots
See attached.

## Error information
No error, just unknown links at top of contro;

## Additional context
Provide any additional context that may be helpful in understanding and/or resolving the bug.

## Affected version

* [ ] 10.0.0 alpha build
* [ ]  9.5.1 alpha build
* [X ]  9.5.0 latest supported release
* [ ]  9.4.4 

## Affected browser

* [ X] Chrome
* [X ] Firefox
* [ ] Safari
* [ ] Internet Explorer 11
* [X ] Microsoft Edge (Classic)
* [ ] Microsoft Edge Chromium

**Comment by sleupold** [comment]
do you observe this as well, when using default skin and container?

**Comment by LeoMrozek1895** [comment]
I believe so. I recently installed as a default website and did nothing to change the skin (I think it is called XCillion or something like that).

**Comment by moorecreative** [comment]
I can confirm the same display in a DNN 9.0 instance that has been upgraded to DNN 9.5. This includes language sections that do not have tokens involved... standard text content. I am including a screen of the Global Resources > File Upload languages file text content.
![image](https://user-images.githubusercontent.com/5497943/79266894-4ce40f80-7e66-11ea-8e71-def593e37d67.png)

**Comment by valadas** [comment]
I was able to reproduce in 9.6.0 RC1 also, triaging

**Comment by valadas** [comment]
Can no longer reproduce in 9.6.2

![image](https://user-images.githubusercontent.com/6371568/88709633-72c6b480-d0e3-11ea-95ed-47760dd9fd6e.png)

**Comment by valadas** [comment]
![image](https://user-images.githubusercontent.com/6371568/88709684-83772a80-d0e3-11ea-9000-c312d19fd971.png)
