### ISSUE TITLE
Template field for profile limited to 2000 chars

### ISSUE THREAD

**Issue by MaiklT** [dnnsoftware/Dnn.Platform#3682]
## Description of bug
A profile template is limited to 2000 chars (file /DesktopModules/Admin/ViewProfile/Settings.ascx)

## Steps to reproduce
Try to add two or more profile properties, like Cell etc. The template is not saved correcty as it exceeds the length of 2000 chars.

## Expected behavior
Should be longer. Workaround ist to change line 10 in the file from

    <asp:TextBox ID="txtTemplate" Columns="60" TextMode="MultiLine" Rows="25" MaxLength="2000" runat="server" Width="300px" />

to

    <asp:TextBox ID="txtTemplate" Columns="60" TextMode="MultiLine" Rows="25" MaxLength="4000" runat="server" Width="300px" />

or deleting the MaxLength property, but this should be done in the product (otherwise you have to change this after every upgrade).

* [X] 10.0.0 alpha build
* [X]  9.5.1 alpha build
* [X]  9.5.0 latest supported release
* [X]  9.4.4

**Comment by sleupold** [comment]
did you check the value of "length" in profile property definition?
I fear, the value (default = 0: unlimited) is not taken into account by the UI

**Comment by MaiklT** [comment]
The problem is definitely the MaxLength attribute in the control. The value cannot be taken into account as it is hard-coded in the file.
