### ISSUE TITLE
Missing objectQualifier in 9.5.0-DotNetNuke.Services.Social.Messaging.Scheduler.CoreMessagingScheduler.

### ISSUE THREAD

**Issue by edisfera** [dnnsoftware/Dnn.Platform#3687]
## Description of bug
The DotNetNuke.Services.Social.Messaging.Scheduler.CoreMessagingScheduler calls vw_MessagesForDispatch without the objectQualifier even if the installation uses objectQualifier.

## Steps to reproduce
Install/Upgrade to 9.5.0 on an instance that uses objectQualifier.

## Current behavior
Errors will be logged by the Scheduler in Admin Logs.

## Expected behavior
No error logs.

## Affected version

* [ ] 10.0.0 alpha build
* [ ]  9.5.1 alpha build
* [X]  9.5.0 latest supported release
* [ ]  9.4.4 

## Affected browser

* [ ] Chrome
* [ ] Firefox
* [ ] Safari
* [ ] Internet Explorer 11
* [ ] Microsoft Edge (Classic)
* [ ] Microsoft Edge Chromium

**Comment by sleupold** [comment]
this issue had already been reported and the fix is included in DNN 9.6.0 (RC state atm)

**Comment by edisfera** [comment]
Are you referring to #3540 and #3539? In those two I only see the stored procedure problem not the view... or there is going to be an overall check for the whole functionality?

**Comment by sleupold** [comment]
see the fix in https://github.com/dnnsoftware/Dnn.Platform/pull/3606/files
it includes the  stored procedure with missing OQ, called by the scheduler.

**Comment by edisfera** [comment]
Hi Leupold, that's right, but I am experiencing a call to a view called vw_MessagesForDispatch which has been correctly created with the objectQualifier in the database but the code (DotNetNuke.Services.Social.Messaging.Scheduler.CoreMessagingScheduler) seems to call it without the objectQualifier (I get this error in the event log: 'Invalid object name 'dbo.vw_MessagesForDispatch'... it should call for dbo**.LF_**vw_MessagesForDispatch as it is in the database).

**Comment by valadas** [comment]
It is a stored procedure (CoreMessaging_GetNextMessagesForDigestDispatch) that calls that view from a quick look at the code, the fix in #3606 should be fine. You can try 9.6.0 release candidate (on a non-production environment) if you want to make absolutely sure. It is available here: https://github.com/dnnsoftware/Dnn.Platform/releases/tag/v9.6.0-rc1

I will close this issue since it should be fixed already, but this does not lock it, feel free to comment again if you notice there is a problem not already handled.

**Comment by sleupold** [comment]
You may just run the file I mentioned before in your PersonaBar > Manage > SQL Console and restart your app. The scheduler should stop throwing errors immediately.
