### ISSUE TITLE
Has 9.5.1 been cancelled in favor of 9.6?

### ISSUE THREAD

**Issue by PromontoryProtean** [dnnsoftware/Dnn.Platform#3688]
Looking through milestones it appears the milestone for 9.5.1 is gone. And under releases 9.6 is marked as RC. Is 9.5.1 still planned to be released? Or has 9.5.1 been punted in favor of 9.6? We have been waiting for the first point release of 9.5.x before upgrading a number of our clients. Just looking for guidance and possible time frames if anything is available. Apologies for posting here, but I have not been able to find a definitive answer by searching anywhere else.

**Comment by bdukes** [comment]
Yes, 9.5.1 was abandoned and 9.6.0 will be released soon (currently in RC phase). See #3678
