### ISSUE TITLE
Weird shorting in PersonaBar in Title

### ISSUE THREAD

**Issue by SCullman** [dnnsoftware/Dnn.Platform#3690]
## Description of bug
![image](https://user-images.githubusercontent.com/5693190/79561543-ccadec00-80a9-11ea-873f-2fe22b1e4cf6.png)

The German word for website settings (_Website-Einstellungen_) gets "shorted" to the even longer string _Website-Einstellunge..._

## Steps to reproduce
Open Web Settings with German Language Pack

## Affected version

* [ ] 10.0.0 alpha build
* [ x]  9.6.0 rc2 build
* [ ]  9.5.0 latest supported release
* [ ]  9.4.4

**Comment by valadas** [comment]
We now have the language packs as repositorys, oddly, I cannot move the issue there https://github.com/dnnsoftware/Language-Pack-DE-DE

@SCullman could you copy it over there and I will close this one here. Thanks.

**Comment by valadas** [comment]
Oh, sorry I completely misunderstood the issue, reopeneing.

**Comment by sleupold** [comment]
thank you!

**Comment by valadas** [comment]
Basically if the number of "too many chars" is less than 3, we should not shorten it and add 3 chars. Even better we could just not even hard-shorten stuff at all, just let it flow.

**Comment by sleupold** [comment]
I agree!
