### ISSUE TITLE
Raise dependencies of Microsoft.AspNet.WebApi.*

### ISSUE THREAD

**Issue by SCullman** [dnnsoftware/Dnn.Platform#3691]
## Description of problem
Please lift the dependency of 

- Microsoft.AspNet.WebApi
- and Microsoft.AspNet.WebApi.Client

to a current version, at least 5.2.4, as best 5.2.7

The current 5.2.3 is the last version which does not support .Net Standard.

**Comment by jeremy-farrance** [comment]
Still needed.
