### ISSUE TITLE
MVC style Settings control doesn't work

### ISSUE THREAD

**Issue by donker** [dnnsoftware/Dnn.Platform#3692]
## Description of bug
Using a settings razor file and settingscontroller as per the MVC style of doing things does not persist settings to the database. The cause being that DNN insists of storing cached settings at the end of the update process, reverting previous changes.

## Steps to reproduce
Settings class in module:

``` cs
    public class ModuleSettings
    {
        [ModuleSetting]
        public string Foo { get; set; } = "Bar";

        public static ModuleSettings GetSettings(ModuleInfo module)
        {
            var repo = new ModuleSettingsRepository();
            return repo.GetSettings(module);
        }

        public void SaveSettings(ModuleInfo module)
        {
            var repo = new ModuleSettingsRepository();
            repo.SaveSettings(module, this);
        }
    }
    public class ModuleSettingsRepository : SettingsRepository<ModuleSettings>
    {
    }
```

Settings logic in SettingsController:

``` cs
        [HttpPost]
        [ValidateInput(false)]
        [DotNetNuke.Web.Mvc.Framework.ActionFilters.ValidateAntiForgeryToken]
        public ActionResult Settings(ModuleSettings settings)
        {
            settings.SaveSettings(ModuleContext.Configuration);
            return RedirectToDefaultRoute();
        }
```

## Current behavior
The above code runs and changes the values in the ModuleSettings database. But when the update logic completes those changes are reverted again.

## Error information
In the class MvcSettingsControl we see the following code:

``` cs
        public void UpdateSettings()
        {
            ExecuteModule();

            ModuleController.Instance.UpdateModule(ModuleContext.Configuration);
        }
```

The first line calls the update code in the settings controller of my module. The second line reverts this as the ModuleContext.Configuration still has the old ModuleSettings and writes them to the database.

The line where this happens is here: https://github.com/dnnsoftware/Dnn.Platform/blob/develop/DNN%20Platform/Library/Entities/Modules/ModuleController.cs#L1966

Examining the code in the ModuleSettings control what strikes me is that there we already pass through the UpdateModule logic here:

https://github.com/dnnsoftware/Dnn.Platform/blob/develop/DNN%20Platform/Website/admin/Modules/Modulesettings.ascx.cs#L648

So there is no need to pass through it again in the MvcSettingsControl which kicks off a couple of lines below in UpdateSettings.

My proposal is to remove the extra UpdateModule in MvcSettingsControl.UpdateSettings.

## Affected version
* [x ]  9.4.4

**Comment by donker** [comment]
OK, this is totally screwed up. The example code by DNN has you write to the module context's module settings to update the module:

https://github.com/dnnsoftware/Dnn.Platform.Samples.Mvc/blob/master/src/Dnn.ContactList.Mvc/Controllers/SettingsController.cs

This makes the use of our neat and concise module settings pattern impossible. From a coding standards perspective the above code is horrendous. 

So the removal of the duplicate UpdateModule would disable the above code.

**Comment by bdukes** [comment]
Could we add an `IsDirty` check (do we have anything to do that check with)?  So only if the settings are changed do we call `UpdateModule`?

**Comment by donker** [comment]
It could be a solution. But IMHO we'd be adding yet more code to a problem that doesn't need to be. 

UpdateModule does a whole bunch of other stuff as well. You could, for instance, change the module title in your code and it would overwrite what the user filled in in the UI. I just don't understand the logic of going through UpdateModule twice.
