### ISSUE TITLE
Edit schedule item height issue (buttons not visible)

### ISSUE THREAD

**Issue by trouble2** [dnnsoftware/Dnn.Platform#3701]
## Description of bug
I wanted to edit a scheduler item (persona bar > Scheduler > Second tab > Click on edit button
I see the specific scheduler item panel expand, however the height is not enough to show the buttons for this item

## Screenshots
![image](https://user-images.githubusercontent.com/1827559/80191133-90ccd680-8615-11ea-98c6-2d4d9f488ea0.png)

## Affected version
* [x]  9.5.0 latest supported release

## Affected browser
* [x] Chrome

**Comment by mitchelsellers** [comment]
What resolution is your display?

**Comment by trouble2** [comment]
Crap could it be that simple...

**Comment by mitchelsellers** [comment]
I'm going to make a note that we should establish a "minimum" recommendation for display resolution

**Comment by valadas** [comment]
Meh, well as I will work on those modules in the future, I would really like them to be properly responsive, but well that is what we have and it is a massive undertaking to rewrite it all. But yeah right now this was not build to be used on smaller screens :(
