### ISSUE TITLE
Search Results distorted

### ISSUE THREAD

**Issue by sleupold** [dnnsoftware/Dnn.Platform#3712]
## Description of bug
Search Results module look distorted

## Steps to reproduce
List the precise steps to reproduce the bug:
1. Install DNN 9.6.0 
2. enter a search term and submit
3. select "show more results"

## Current behavior
Explain the current behavior.

## Expected behavior
should look like before.

## Screenshots
![image](https://user-images.githubusercontent.com/6377509/80589397-5c448a80-8a1a-11ea-97e5-cda834ef20dd.png)

## Error information
none

## Additional context
Might be caused by switch to JQuery 3.5.0

## Affected version

* [ ] 10.0.0 alpha build
* [ ]  9.5.1 alpha build
* [X]  9.6.0 latest supported release
* [ ]  9.5.0 

## Affected browser

* [ ] Chrome
* [ ] Firefox
* [ ] Safari
* [ ] Internet Explorer 11
* [ ] Microsoft Edge (Classic)
* [X] Microsoft Edge Chromium

**Comment by valadas** [comment]
Yeah, that is probably jQuery related, it was fine in the earlier RCs but like this on the latest now.
