### ISSUE TITLE
Site Groups - Tooltip Being Cut Off

### ISSUE THREAD

**Issue by mikesmeltzer** [dnnsoftware/Dnn.Platform#3713]
## Description of bug

Tooltips in the Site Groups extension are being cut off in the Persona Bar by other UI elements,

## Steps to reproduce
1. Open Site Groups from Manage > Site Groups
2. Hover over the Master Site or Authentication Domain tooltip icons
3. Notice the tooltip opening but most of it is being covered by another UI element. 

## Expected behavior

The tooltips should be visible to users.

## Screenshots
![image](https://user-images.githubusercontent.com/39993943/80595340-f399e580-89fa-11ea-9913-c48ecc3ea691.png)

## Affected version
* [x ]  9.6.0 latest supported release

## Affected browser
Tested on:
* [x ] Microsoft Edge Chromium

**Comment by sleupold** [comment]
still an issue in DNN 9.6.2

**Comment by mikesmeltzer** [comment]
still an issue as of DNN 9.8 RC1
