### ISSUE TITLE
/API/personaBar/localization/gettable (General Exception)

### ISSUE THREAD

**Issue by rthoeni** [dnnsoftware/Dnn.Platform#3716]
## Description of bug
from a new installation or from an upgrade there is this error
The DNN basic installation is in German and has a Let's Encrypt certificate.

## Steps to reproduce
List the precise steps to reproduce the bug:
1. Go to 'new site'
2. Click on 'add module'
3. 'Page takes a long time to load'
AbsoluteURL:/API/personaBar/localization/gettable
DefaultDataProvider:DotNetNuke.Data.SqlDataProvider, DotNetNuke
ExceptionGUID:903c1036-5d72-44ec-aa58-48f10e1e84b7
AssemblyVersion:
PortalId:-1
UserId:-1
TabId:-1
RawUrl:
Referrer:
UserAgent:
ExceptionHash:MDX4XAOWSci4B5oZ5fIdWtHU1Oo=
Message:Eine Aufgabe wurde abgebrochen.
StackTrace:
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei System.Web.Http.Tracing.ITraceWriterExtensions.<TraceBeginEndAsyncCore>d__18`1.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei System.Web.Http.Tracing.ITraceWriterExtensions.<TraceBeginEndAsyncCore>d__18`1.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__2.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()
InnerMessage:
InnerStackTrace:
Source:mscorlib
FileName:
FileLineNumber:0
FileColumnNumber:0
Method:
Server Name: vps74

## Current behavior
There are many entries in the admin logs and the function clear log no longer works
How to shorten your DNN event log table> https://support.winhost.com/kb/a1617/how-to-truncate-your-dnn-event-log-table.aspx then it goes again

## Affected version

* [X ]  9.6.0
* [x ]  9.5.0 
* [x ]  9.4.4 

## Affected browser
* [ ] Chrome
* [ ] Firefox
* [x ] Safari
* [ ] Internet Explorer 11
* [ ] Microsoft Edge (Classic)
* [ ] Microsoft Edge Chromium

**Comment by valadas** [comment]
@rthoeni is the the language pack that just comes with Dnn or another one ?

@sleupold can you reproduce this issue?

**Comment by rthoeni** [comment]
It is the language pack which is included in the installation file / upgrade file 
(DNN Core Deutsch (Deutschland) 9.2.0)

**Comment by sleupold** [comment]
for clearing the event log, I published a script at https://github.com/dnnwerk/truncateEventlog

**Comment by sleupold** [comment]
has this issue been fixed on your web site after truncating the eventlog?

**Comment by rthoeni** [comment]
sorry for my late reply
So I have now created a web server based on 2019 with Microsoft Azure today.
The MS Server and SQL version is in English and without SSL certificate.

I get the same error message when I install the DNN in German.
So far I have noticed when I create a new page.
I hope this helps for now.

**Comment by Orrouk** [comment]
To reproduce the bug, go in Settings, change the site default language from one to another each morning when you start working. Install HCC, Liveform and 2Sxc extensions, but not all the same day. Work for a while.
