### ISSUE TITLE
Logo and Favicon can not change and save. 

### ISSUE THREAD

**Issue by rthoeni** [dnnsoftware/Dnn.Platform#3722]
## Description of bug
Drag and drop .png/.ico a file or choose from Portal 0 as an option not function.

## Steps to reproduce
List the precise steps to reproduce the bug:
1. Go to 'Website info'
2. Go to 'Logo and symbols'
3. 'drag and drop or choose from file... Logo.png/Favicon.ico'
4. can not click on save

## Screenshots
<img width="785" alt="Bildschirmfoto 2020-05-01 um 23 34 40" src="https://user-images.githubusercontent.com/12658708/80843689-37603b00-8c05-11ea-9f56-37276a37f340.png">

## Affected version
* [X]  9.6.0

## Affected browser
* [ ] Chrome
* [X ] Firefox 75.0
* [ X] Safari 13.1
* [ ] Internet Explorer 11
* [ ] Microsoft Edge (Classic)
* [ ] Microsoft Edge Chromium

**Comment by mitchelsellers** [comment]
Which language package are you using?  Are there any logs in the /portals/_default/logs folder

**Comment by rthoeni** [comment]
I use the German language pack
[DNN_9.6.0_Error.pdf](https://github.com/dnnsoftware/Dnn.Platform/files/4566452/DNN_9.6.0_Error.pdf)

**Comment by valadas** [comment]
I can confirm that the drag and drop is not working. As a temporary workaround, you can use the Site Assets to upload your .ico file and then pick it in the list in site settings.

**Comment by gbulicanu** [comment]
@valadas I can confirm that it is reproducible with any language, and not only drag an drop but with 'Upload a File' hover link, the problem is that somehow validation codes are not transmitted correctly and we get bad request from APIs
