### ISSUE TITLE
Bootstrap v4.4.1 collapse doesn't work with jQuery v3.5.0

### ISSUE THREAD

**Issue by micahsdad1402** [dnnsoftware/Dnn.Platform#3725]
It is related to[ https://github.com/twbs/bootstrap/issues/30553]( https://github.com/twbs/bootstrap/issues/30553)
This is a problem with DNN 9.6. 
Because there is no way to update jQuery (I think an update to 3.5.1 might fix it) with DNN (or none I could find), I went back and am using DNN9.5

## Steps to reproduce

1. Access website in responsive mode
2. Clicking on toggle button doesn't open the menu and produces the following error:

bootstrap.min.js?cdv=35:6 Uncaught TypeError: Cannot convert object to primitive value
    at RegExp.test (<anonymous>)
    at HTMLDivElement.<anonymous> (bootstrap.min.js?cdv=35:6)
    at Function.each (jquery.js?cdv=35:2)
    at s.fn.init.each (jquery.js?cdv=35:2)
    at s.fn.init.a._jQueryInterface [as collapse] (bootstrap.min.js?cdv=35:6)
    at HTMLDivElement.<anonymous> (bootstrap.min.js?cdv=35:6)
    at Function.each (jquery.js?cdv=35:2)
    at s.fn.init.each (jquery.js?cdv=35:2)
    at HTMLButtonElement.<anonymous> (bootstrap.min.js?cdv=35:6)
    at HTMLDocument.dispatch (jquery.js?cdv=35:2)
`

  | (anonymous) | @ | bootstrap.min.js?cdv=35:6
-- | -- | -- | --
  | each | @ | jquery.js?cdv=35:2
  | each | @ | jquery.js?cdv=35:2
  | a._jQueryInterface | @ | bootstrap.min.js?cdv=35:6
  | (anonymous) | @ | bootstrap.min.js?cdv=35:6
  | each | @ | jquery.js?cdv=35:2
  | each | @ | jquery.js?cdv=35:2
  | (anonymous) | @ | bootstrap.min.js?cdv=35:6
  | dispatch | @ | jquery.js?cdv=35:2
  | v.handle | @ | jquery.js?cdv=35:2

`

## Current behavior
Toggle menu doesn't work

## Expected behavior
Toggle menu should work. This works in 9.5 I tested this with the Xcillion theme, so it's not theme related.

## Error information
See above

## Affected version
* [ x]  9.6.0 latest supported release

## Affected browser
All

**Comment by valadas** [comment]
jQuery 3.5.0 is the latest release, unfortunately bootstrap will need to adapt to it due to a breaking change in jQuery. It looks like it is on the Bootstrap 4.4.2 roadmap here https://github.com/twbs/bootstrap/pull/30559 and we can update it when that is released.

**Comment by david-poindexter** [comment]
A bit more insight can be found here too:
https://github.com/twbs/bootstrap/issues/30553

**Comment by david-poindexter** [comment]
@micahsdad1402 thanks for reporting this.  Since this is related to Bootstrap support for jQuery 3.5.0 and not DNN directly, we’ll go ahead and close this issue.
