### ISSUE TITLE
Clicking on 'Privacy' link gives /Privacy page with html

### ISSUE THREAD

**Issue by trouble2** [dnnsoftware/Dnn.Platform#3730]
## Description of bug
On a new dnn 9.6.0 I click on the 'Privacy' link and I go to the /privacy page where I can see:
![image](https://user-images.githubusercontent.com/1827559/81074789-c9a85d80-8ee9-11ea-834a-dab2df1ee887.png)

## Steps to reproduce
1. Install a fresh DNN 9.6.0
2. Click on the privacy link in the footer
3. See error

## Current behavior
The text shows html tags

## Expected behavior
A nicely formated text

## Screenshots
See above

## Affected version
* [x]  9.6.0 

## Affected browser
* [x] Chrome

**Comment by sleupold** [comment]
please check the language pack applied, there was an issue in earlier versions of DNN 9, where the language tool encoded twice, when saving HTML content entered (and only decodes once, when rendering the content)

**Comment by trouble2** [comment]
Yes, looks like it is a bug in the GlobalResources.nl-NL.resx
So the dutch language pack.

**Comment by sleupold** [comment]
@trouble2 Marnix,
there is a Repo for the Dutch LP at https://github.com/DNNCommunity.
Please log the issue over there.
