### ISSUE TITLE
Clicking on 'Terms' link gives /Terms page with html 

### ISSUE THREAD

**Issue by trouble2** [dnnsoftware/Dnn.Platform#3731]
## Description of bug
On a new DNN 9.6.0 installation when I click on the Terms link in the footer I go to /Terms and see html tags on the page:
![image](https://user-images.githubusercontent.com/1827559/81075328-7e427f00-8eea-11ea-804a-7b5047c8ee82.png)

## Steps to reproduce
List the precise steps to reproduce the bug:
1. Go to a brand new DNN 9.6.0 installation 
2. Click on Terms in the footer
3. See error

## Current behavior
I can see HTML

## Expected behavior
I expected to see a nicely formated page

## Screenshots
See above 

## Affected version
* [x]  9.6.0 

## Affected browser
* [x] Chrome

**Comment by sleupold** [comment]
please check the language pack applied, there was an issue in earlier versions of DNN 9, where the language tool encoded twice, when saving HTML content entered (and only decodes once, when rendering the content)

**Comment by trouble2** [comment]
Yes, looks like it is a bug in the GlobalResources.nl-NL.resx
So the dutch language pack.
