### ISSUE TITLE
Update CKEditor from 4.5.3 to 4.14.0

### ISSUE THREAD

**Issue by rthoeni** [dnnsoftware/Dnn.Platform#3744]
## Description of solution
Update to the latest Version CKEditor 4.14.0
The current version is almost 5 years old.

## Description of alternatives considered
Provide a clear and concise description of any alternative solutions considered.

## Screenshots
If applicable, provide screenshots to help explain the problem and/or enhancement.

## Affected browser
* [ ] Chrome
* [X] Firefox
* [X] Safari
* [ ] Internet Explorer
* [ ] Edge

**Comment by sleupold** [comment]
thank you, Roland
but this has already been logged by @bdukes at https://github.com/DNN-Connect/CKEditorProvider/issues/87
