### ISSUE TITLE
Core language packs missing in installation and site settings

### ISSUE THREAD

**Issue by Valeria-B** [dnnsoftware/Dnn.Platform#3749]
## Description of bug
Core language packs missing in installation and site settings

## Steps to reproduce
List the precise steps to reproduce the bug:

1. Download and install v. 9.6.0
2. During installation, select a language that is not English
3. After installation, go to Site settings > Languages, Add new language, enable it and set it as site default

## Current behavior
1. During installation, there is only English as language option

2. After adding new language as site default in the site settings, everything stays in English even with the following settings 

3. clicking on "verify language resource files" shows 211 files missing for all languages

4. In site settings > Extensions, Core language packs are not visible neither in the installed nor in the available extensions

## Expected behavior
1. Ability to select a different language during installation
2. Ability to add and set as site default a different language
3. Language resource files shouldn't be missing
4. View and manage Core Language Packs in the Extensions settings

## Screenshots
![Screenshot 2020-05-08 at 12 09 33](https://user-images.githubusercontent.com/6912412/81396021-eed4e000-9124-11ea-828d-b568eea4acf4.png)

![Screenshot 2020-05-08 at 12 13 31](https://user-images.githubusercontent.com/6912412/81396336-85090600-9125-11ea-8b6c-07fb641d9a6d.png)

## Error information
No relevant errors in the log

## Affected version

* [ ] 10.00.00 alpha build
* [x] 09.06.00 latest supported release

## Affected browser

N/A

**Comment by sleupold** [comment]
Please note: add language will add the language record, but not install the language packs.
Those need to be installed in Manage Extension.

**Comment by Valeria-B** [comment]
I thought it was a bug since we neve had to download it separately and the removal of languages is not mentioned in the changelog.

Here https://www.dnnsoftware.com/community/download/language-packs i see packs only up to 9.2, is it ok for 9.6 too?

Another question, will upgrading other portals from 9.4.4 to 9.6 affect the languages already installed and set as default?

**Comment by sleupold** [comment]
Language packs are currently updated by our various translators and will be offered for download, as soon as they are completed and verified.
There should be a new app settings key UpdateServiceUrl in your web.config, pointing to https://dnnplatform.io
Upgrading will not affect languages configured - but as well not update language packs automatically, You should check for new LPs on "Available Extensions" tab and install updates latest.

**Comment by Valeria-B** [comment]
Thank you for the reply.

> You should check for new LPs on "Available Extensions" tab and install updates latest

That was also part of the issue (n.4 under "current behavior"), there are no LPs on the available extensions tab, while i can see them in 9.4.4, that's one of the reasons why I thought it was ok to notify it here

**Comment by sleupold** [comment]
DNN 9.6.0 looks at a different endpoint for the language packs, which had been transferred from DNN Corp. to DNN community recently. Not all LPs might be uploaded there atm.

**Comment by valadas** [comment]
Correct me if I am wrong here @mitchelsellers but I think this is now fixed and we at least have the latest maintained language pack distributed for the core supported languages right? I am closing the issue for that reason.
