### ISSUE TITLE
Select primary site alias by default when adding a new page url

### ISSUE THREAD

**Issue by schotman** [dnnsoftware/Dnn.Platform#3750]
## Description of problem
This isssue and (related pull request) makes life easier for a content manager and prevents problems. 
When a content manager wants to ad a custom url for a page, he must select the site alias and enter the new custom url. Selecting a site alias, is usually not something he/she is accustomed to (they may even be unaware of the concept).
When there are multiple site aliasses and the first site alias is not (one of) the active/live alias(ses), then adding a new 200 page url can lead to a situation that the page can no longer be visisted (when the content manager forgets to select the proper site alias) because the custom 200 url links to the wrong site alias and results in a 404. 

## Description of solution
Currently the UI defaults to the first alias from the portal alias table (if the alias with id=1 is no longer there, the box is empty). Better would be if the primary alias would be selected. This can be achieved by a small change in the react code.
The advantage of this aproach is that the content manager is less likely to make a mistake

## Description of alternatives considered
Keep current, which works fine in most simple cases

## Screenshots
localhost is the first site alias
![image](https://user-images.githubusercontent.com/2582737/81442163-62054300-9173-11ea-8459-3736fcaec404.png)

first alias no longer exists
![image](https://user-images.githubusercontent.com/2582737/81442179-6893ba80-9173-11ea-8258-b597e7ac4ccf.png)

new code in editurl.jsx
![image](https://user-images.githubusercontent.com/2582737/81442190-6e899b80-9173-11ea-9f6e-49b46f283841.png)

## Affected browser
not relevant, all browsers

**Comment by david-poindexter** [comment]
Closing per #3751
