### ISSUE TITLE
Incorrect text for cookie help

### ISSUE THREAD

**Issue by vmasanas** [dnnsoftware/Dnn.Platform#3752]
The help text for the cookies consent on SiteSettings.resx, Key = plCookieMoreLink.Help says:

"In the cookie consent popup a link is shown to explain about cookies to users. If you wish to override this link (by default it points to cookiesandme.com) it will link to this url."

I just tried this domain and does not exist.
This should be corrected to point to a valid page.

Not sure if the error is just on the help text of the system actually links to that page.

**Comment by valadas** [comment]
What about https://en.wikipedia.org/wiki/HTTP_cookie instead? Opinions?

**Comment by vmasanas** [comment]
Looks good to me. Did you check if the keys is actually used somewhere on the code?

**Comment by sleupold** [comment]
sounds like an option, and should be adopted by site admins anyways

**Comment by bdukes** [comment]
Is it supposed to be https://www.cookiesandyou.com/?

**Comment by sleupold** [comment]
@bdukes  but that's available in English language only, right?

**Comment by vmasanas** [comment]
I'd suggest not linking to a website that is not publicly recognized a good source of info.
This site belongs to a company (Osano) that I'd suggest we should not depend on. Better us wikipedia if I had to choose.

**Comment by bdukes** [comment]
:+1: works for me

**Comment by valadas** [comment]
Yeah and wikipedia should have that in most languages too

**Comment by sleupold** [comment]
still an issue. I'll try to submit a PR
