### ISSUE TITLE
Incorrect Module setting text and help

### ISSUE THREAD

**Issue by vmasanas** [dnnsoftware/Dnn.Platform#3763]
On the module settings we have an option with the following text and help:
Text: Hide Admin Border
Help: Check this box to hide the red border that shows around the module when it is only visible to Administrators.

In DNN 9 there's no such thing as a red border.
Instead the system displays a message notification on top of the module with the text "Visible by Administrators only."

I suggest changing the text and help to:

Text: Hide Admin Only Visibility Message:
Help: Check this box to hide the message notification that is displayed on top of the module when it is only visible to Administrators.

**Comment by valadas** [comment]
This has been reworded as "Admin message" instead of "Admin border" somewhere between the time this issue was open and Dnn 9.6.2 was out. Closing this issues.
