### ISSUE TITLE
Better meta tag support

### ISSUE THREAD

**Issue by trouble2** [dnnsoftware/Dnn.Platform#3766]
## Description of problem
When I look at some other cmsystems I can clearly see some better options to include more modern meta tags and other more modern web standards information.
It looks like DNN could do with some improvements on this point.
The world has moved on beyond adding a title, description and keywords...
.
## Description of solution
At this point I user some combination of 40fingers to add additional tags to the skin and some tools like https://realfavicongenerator.net/ and https://www.pwabuilder.com/ for example. Which can even generate some default scripts for you like: https://www.pwabuilder.com/?url=https://dnncommunity.org/)
But I have this feeling it would be better to have something built in to DNN.

This is more of a normal header nowadays:
```
<title>WELL YOU KNOW, THE TITLE...</title>
<meta id="MetaDescription" name="DESCRIPTION" content="[PAGE/PORTALDESCRIPTION]" />
<meta id="MetaKeywords" name="KEYWORDS" content="[PAGE/PORTALKEYWORDS]" />
<meta property="og:title" content="[PORTALNAME/TITLE]" />
<meta property="og:description" content="[PORTALORPAGEDESCRIPTION]" />
<meta property="og:url" content="[PORTALALIAS]" />
<meta property="og:locale" content="[PORTALLOCALE]" />
<link rel="alternate" href="[OTHERLOCALES]" hreflang="en" />
<meta property="og:image:secure_url" content="[DEFAULTPORTALLOGOORTABIMAGE] />
<meta property="og:image" content="[DEFAULTPORTALLOGOORTABIMAGE]" />
<meta property="og:site_name" content="[SITENAMEORTITLE]" />
<link rel="apple-touch-icon" sizes="57x57" href="/apple-icon-57x57.png">
<link rel="apple-touch-icon" sizes="60x60" href="/apple-icon-60x60.png">
<link rel="apple-touch-icon" sizes="72x72" href="/apple-icon-72x72.png">
<link rel="apple-touch-icon" sizes="76x76" href="/apple-icon-76x76.png">
<link rel="apple-touch-icon" sizes="114x114" href="/apple-icon-114x114.png">
<link rel="apple-touch-icon" sizes="120x120" href="/apple-icon-120x120.png">
<link rel="apple-touch-icon" sizes="144x144" href="/apple-icon-144x144.png">
<link rel="apple-touch-icon" sizes="152x152" href="/apple-icon-152x152.png">
<link rel="apple-touch-icon" sizes="180x180" href="/apple-icon-180x180.png">
<link rel="icon" type="image/png" sizes="192x192"  href="/android-icon-192x192.png">
<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="96x96" href="/favicon-96x96.png">
<link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
<link rel="manifest" href="/manifest.json">
<meta name="msapplication-TileColor" content="#ffffff">
<meta name="msapplication-TileImage" content="/ms-icon-144x144.png">
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
```

Now, I know this is --kind of-- possible using the meta tags text box, or some skinobjects, but it isn't a real out of the box feature of DNN.
Other CMSystems (I won't mention them...don't worry) have these beautiful seo plugins which even help you with recommendations for description length etc.
So I think this is an area where DNN can make a difference if stuff like this is built in...

**Comment by mitchelsellers** [comment]
I think this is a great discussion, but I'd like to look at things in two buckets if we can.

**Things to add to Site Settings**

These would be things that should be managed for the full site.  (Favicon etc)

**Things to add to Page Settings**

These would be page specific items, such as URL, etc?

**Comment by sleupold** [comment]
@mitchelsellers 
IMO we should keep this together, as a couple of settings might be per page, (optionally) defaulting to Site settings. 
My suggestion: adding a page setting (bool) "default to site settings" for title, description, keywords,  logo and favicon.

But besides, this feature request is 
a) about supporting multiple formats for favIcon
b) defining meta tags for pages (defaulting to site, if enabled) depending on existing of specific settings.

**Comment by trouble2** [comment]
Well, I think DNN always does a great job at kind of inheriting setttings.
If there are no page specific settings, then it will use portal settings, if there are no portal settings then use host settings, etc.

Some things, like favicon's indeed would be more a portal-wide setting, however, for meta description, and open graph kind of stuff might be more page specific. Some examples:

![0623decf-fb5b-454b-b915-43a0e69133a4](https://user-images.githubusercontent.com/1827559/82022447-fe0bde80-968c-11ea-9b26-889ee71a176f.png)

![meta-description-4](https://user-images.githubusercontent.com/1827559/82022475-082ddd00-968d-11ea-9c68-4ad5d87220d1.jpg)

![635645368781161382_example1gif](https://user-images.githubusercontent.com/1827559/82022492-0d8b2780-968d-11ea-8809-a3cc7df21c12.gif)

**Comment by trouble2** [comment]
And just like the sitemap generator for each site. Perhaps it is possible to also include something like a webmanifest.json creator for each portal which produces something like this in the portal folder"

{
	"name" : "[SITENAME]",
	"short_name" : "[SITENAME]",
	"description" : "[SITEDESCRIPTION]",
	"icons" : [
		{
			"src": "[URLTOBIG FAVICON]",
			"sizes": "192x192"
		},
		{
			"src": "[URLTOEVENBIGGER FAVICON]",
			"sizes": "512x512"
		}],
	"theme_color" : "#ffffff",
	"background_color" : "#ffffff",
	"display" : "standalone",
	"start_url" : "[HOMEURL]",
	"url" : "[PORTALALIAS],
	"lang" : "",
	"screenshots" : [],
	"orientation" : "",
	"generated" : ""
}

**Comment by Tychodewaard** [comment]
Reopen? If it is a small thing to do...

**Comment by valadas** [comment]
Well, I don't know that it is a small thing lol... Anyone planning on tackling this ?
