### ISSUE TITLE
Issue after upgrade from 7.04.00

### ISSUE THREAD

**Issue by mitchew** [dnnsoftware/Dnn.Platform#3767]
I've upgraded from 7.04.00 to 9.5.0
All went well aside from one issue with the Security > Login Settings > Basic Login Settings menu stating "There was an error retrieving your content. Please check your internet connection."

How do I being to troubleshoot this issue?

**Comment by sleupold** [comment]
did you upgrade directly or follow suggested upgrade path?

**Comment by mitchew** [comment]
I followed this
https://dnndocs.com/content/getting-started/setup/upgrades/suggested-upgrade-path/index.html
and this
https://dnndocs.com/content/getting-started/setup/upgrades/index.html

**Comment by valadas** [comment]
I would start by looking for errors in the browser console (F12 in Chrome).

Then in the Event Log in the persona bar.

Then in the filesystem /Portal/_default/logs you will see log files per date, take a look in those to see if there are any clues.

**Comment by mitchew** [comment]
Console has no error.

"Admin Logs" has a General Exception but it was there before I navigated to the Security section.

AbsoluteURL:/API/InternalServices/FileUpload/loadimage
DefaultDataProvider:DotNetNuke.Data.SqlDataProvider, DotNetNuke
ExceptionGUID:9222f777-55da-4f44-b0e0-8d95777633fd
AssemblyVersion:
PortalId:-1
UserId:-1
TabId:-1
RawUrl:
Referrer:
UserAgent:
ExceptionHash:
Message:Description
StackTrace:
   at System.Data.ProviderBase.FieldNameLookup.GetOrdinal(String fieldName)
   at System.Data.SqlClient.SqlDataReader.GetOrdinal(String name)
   at System.Data.SqlClient.SqlDataReader.get_Item(String name)
   at DotNetNuke.Services.FileSystem.FileInfo.Fill(IDataReader dr)
   at DotNetNuke.Common.Utilities.CBO.FillObjectFromReader(Object objObject, IDataReader dr)
InnerMessage:
InnerStackTrace:
Source:System.Data
FileName:
FileLineNumber:0
FileColumnNumber:0
Method:

**Comment by sleupold** [comment]
did you unblock downloaded upgrade packeges (at the bottom of 1st tab in file properties), prior to unzipping the files contained, and copying them to overwrite existing files?

**Comment by mitchew** [comment]
Yes. All zip files were unblocked before extracting the files.

**Comment by mitchew** [comment]
I am receiving "Hint 'noexpand' on object 'dbo.vw_UserRoles' is invalid." in my log file. How can I fix this?

**Comment by sleupold** [comment]
did you apply my TurboScripts (if you don't know, check for HostSettings named "Turbo..."

**Comment by mitchew** [comment]
Is that in the web.config? I've inherited this server and I'm brand new to DNN.

Thanks for any assistance you can provide.

**Comment by sleupold** [comment]
no, it is in the database:
SELECT * From dbo.HostSettings WHERE SettingName Like N'Turbo%'

**Comment by mitchew** [comment]
Hmm, it looks like there are Turbo settings. I did not know this prior to my initial upgrade from 7.04.00. Looks like I'll have to restore the first backup, uninstall the TurboScritps and run the upgrade gamut again. Is that correct?

TurboDNN_Version	907	0	-1	2015-04-15 15:44:29.550	-1	2015-04-15 15:44:29.550
TurboSchema_Version	907	0	-1	2015-04-15 15:45:21.063	-1	2015-04-15 15:45:21.063

**Comment by sleupold** [comment]
yes, restore latest database and files from before DNN upgrade.
run TurboUnSchema.sql and perform upgrae again.
You should re-apply TurboDNN.sql and TurboSchema again afterwards, but I am still working on a release for DNN 9.4.0 and above, planned to be released next week.

**Comment by valadas** [comment]
I am closing this issue since it is not actionable as something to fix in this project. However this does not mean you can't keep discussing and people involved will keep getting notifications.

**Comment by mitchew** [comment]
Thank you for all of your assistance.

**Comment by sleupold** [comment]
if you need any support for my TurboScripts, please use options at https://github.com/dnnwerk/dnnScript
