### ISSUE TITLE
Feedback module 6.6.2 Captcha not showing

### ISSUE THREAD

**Issue by EdwardGraham** [dnnsoftware/Dnn.Platform#3774]
Using DNN 9.6.1  and module Feedback 6.6.2 and Microsoft Edge as a browser.
On the feedback for settings I have captcha enabled, with medium selected for both settings.
The problem is the actual captcha generated letters are not displayed on the screen.  Instead you get a broken graphic icon.  This worked in DNN 9.4 I believe.  No backup to try.  Anyone else got the problem?  Thank you, DaleGraham

**Comment by mitchelsellers** [comment]
This is an issue that will need to be addressed by the Feedback Module itself and not the platform.  I don't have an ability to move this issue to that Repository but you can enter the issue here: https://github.com/DNNCommunity/DNN.Feedback
