### ISSUE TITLE
Missing the test of missing translations

### ISSUE THREAD

**Issue by MaiklT** [dnnsoftware/Dnn.Platform#3775]
## Description of problem
The Resource File Verification is a good tool to find out what work has to be done. But compared to older DNN versions I am missing the test of missing translations, i.e. if an entry is not there in an existing file. The "Files older than system default" is not helpful in this case, as most of them did not change for years (and still are valid).

## Description of solution
There should be a test for this. Language files are vital for the DNN worldwide success, and every tool given to those who create them helps that more language files are available.

**Comment by sleupold** [comment]
confirm, this is really needed for using the translation editor properly

**Comment by sleupold** [comment]
AFAIK still an issue and needed

**Comment by MaiklT** [comment]
It is still an issue, and it is really important for localizers and translators. It should not be triaged, and it shot not be defined as a minor issue imho.

**Comment by MaiklT** [comment]
How can we re-open this?
