### ISSUE TITLE
ModuleSettings: remove unused resource key "lblCachedItemCount.Text"

### ISSUE THREAD

**Issue by sleupold** [dnnsoftware/Dnn.Platform#3781]
## Description of bug
key lblCachedItemCount.Text is not used anymore
## Steps to reproduce
List the precise steps to reproduce the bug:
1. Go to settings of any module on any page
2. take your magnifier out of your pocket and check every pixel on any part of the settings dialogue for occurrence of text "Current Cache Count: {0} item(s) for this tab module." with any value for placeholder {0}

## Current behavior
not found

## Expected behavior
key should not exist, as it puts on unnecessary burden on translators

## Screenshots
see the text on the screen:

## Additional context
catched during validation of translation

## Affected version

* [ ] 10.00.00 alpha build
* [X] 09.06.01 release 

## Affected browser
* [x] any

**Comment by valadas** [comment]
I confirm it is not used, there is a same key in another resource file for pages instead of tabModules that is used, but this one key is not used anywhere.

**Comment by sleupold** [comment]
same applies to cmdClearTabModuleCache.Text abd cmdClearAllTabModuleCache.Text
