### ISSUE TITLE
InstallWizard: adjust requirements

### ISSUE THREAD

**Issue by sleupold** [dnnsoftware/Dnn.Platform#3791]
## Description of bug
InstallWizard.resx states in key "IsValidDotNetVersion.Text":
"DNN requires .net 4.0 or higher to work"
According to DNNDocs, it requires version 4.7.2

InstallWizard.resx states in key "IsValidSqlServerVersionCheck.Text":
"Checking database version is SQL 2008 (express or full product) or higher to work" and 
"DNN requires SQL 2008 (express or full product) to work" (key "IsValidDotNetVersion.Text")
According to DNNDocs, it requires version 2008R2 or above

Installwizard.resx states in key "FileAndFolderPermissionCheckFailed.Text" a list of outdated Windows versions

## Current behavior
outdated requirements

## Expected behavior
update messages to current DNN requirements

## Affected version
* [x] 10.00.00 alpha build (in development)
* [x] 09.06.01 latest supported release

## Affected browser
* [x] any

**Comment by sleupold** [comment]
I noticed, IsValidDotNetVersion.Text is not used anymore and the key needs to be removed.

**Comment by valadas** [comment]
Yeah, I created a check for 4.7.2 and never noticed there was even a key for IsValidDotnetVersion.Text, I would have updated that one if I knew it existed :) I guess that can go out now.
