### ISSUE TITLE
InstallWizard: Outdated Links

### ISSUE THREAD

**Issue by sleupold** [dnnsoftware/Dnn.Platform#3792]
## Description of bug
install/InstallWizard.resx contains outdated links to install video for DNN 7 (https://www.dnnsoftware.com/Resources/Training/Training-Videos/Installation.aspx) and DNN improvement programm (http://www.dnnsoftware.com/dnn-improvement-program)

## Steps to reproduce
List the precise steps to reproduce the bug:
check the files

## Current behavior
outdated content

## Expected behavior
should be updated

## Affected version
* [x] 10.00.00 alpha build (in development)
* [x] 09.06.01 latest supported release

## Affected browser
* [x] any

**Comment by gbulicanu** [comment]
@sleupold, @david-poindexter can you please explain how "DNN improvement program" is outdated, is it new page for this program? or this program is discontinued and this should be removed at all from install wizard?

please advice

**Comment by mitchelsellers** [comment]
I think this should be a discussion point for the Technology Group this week.  The Improvement program should really be removed.

@david-poindexter Will you be on the meeting this week?

**Comment by sleupold** [comment]
@gbulicanu 
I am working to overhaul the install wizard, making it more user friendly. your PR will be included.
