### ISSUE TITLE
Lock contention and CPU spikes related to PurgeScheduleHistory SP when there are big amount of items

### ISSUE THREAD

**Issue by eugene-sea** [dnnsoftware/Dnn.Platform#3796]
# Description of bug
PurgeScheduleHistory SP is executed twice per hour. In the current implementation, it tries to delete at most 5000 outdated schedule history items. Thus if schedule history items are created with a rate higher than 10 000 per hour they start to accumulate and PurgeScheduleHistory SP becomes slower and slower. E.g. on target DB there are 205K outdated schedule history items (of 270K in total).

## Steps to reproduce
N/A

## Current behavior
SP is executed in near 85 seconds, causing big lock contention and CPU spikes.

## Expected behavior
SP deletes all unneeded items, as quickly as possible with minimum lock contention.

## Screenshots
N/A

## Error information
N/A

## Additional context
N/A

## Affected version
* [ ] 10.00.00 alpha build (in development)
* [x] 09.06.01 latest supported release

## Affected browser
N/A

**Comment by sleupold** [comment]
Usually, schedulehistory table will only grow, if settings are modified with large numbers to keep.

**Comment by mitchelsellers** [comment]
With a number of modules/features adding more and more jobs with higher frequencies, such as every minute etc this is becoming more of a problem again.

I think it might be worth looking at the default schedule time.

(@eugene-sea for now though you could adjust the frequency after a manual execution)

**Comment by sleupold** [comment]
@mitchelsellers 
ok, my suggestions would be 4 improvements:
1. use an improved sproc
2. increase default frequency from once per day to every hour (retry after 30 mins)
3. add a "PurgeHistory_BatchSize" record in HostSettings table with default 5000 - allowing admins to increase if necessary. (This will provide flexibility for slower or faster servers)
4. provide guidance in DnnDocs admin section

**Comment by eugene-sea** [comment]
@mitchelsellers, @sleupold In my case, SP is executed twice per hour and this is not enough. The SP itself is highly inefficient — this is the second problem. It cannot be run 10 times per hour as even with the current frequency it creates performance problems for the whole SQL Server.

@sleupold your plan is good for me. Thank you.
