### ISSUE TITLE
Remove Telerik Controls in HTML Editor

### ISSUE THREAD

**Issue by ahoefling** [dnnsoftware/Dnn.Platform#3800]
# Description of problem
In v10.0 of DNN the platform will be removing all instances of Telerik controls including the `Telerik.Web.UI.dll` from the bin directory. The HTML Editor takes a hard dependency on these controls through the deprecated web project which leverages the Telerik Controls. The entire Inline Editing toolbar for the HTML Editor module uses telerik controls. Those are not part of the CKEditor but Telerik. 

The view code for inline editing
https://github.com/dnnsoftware/Dnn.Platform/blob/8e172097c733654512be334d10a936f75e0ed27b/DNN%20Platform/Modules/HTML/HtmlModule.ascx#L8-L21

The class definition for `DnnToolBarButton
https://github.com/dnnsoftware/Dnn.Platform/blob/8e172097c733654512be334d10a936f75e0ed27b/DNN%20Platform/DotNetNuke.Web.Deprecated/UI/WebControls/DnnToolBarButton.cs#L13

**If these controls are not refactored prior to the v10 release inline editing will not function on any HTML Editor. Even if you use a custom HTML Editor Provider, the telerik controls are built right in to the view.**

## Description of solution
Remove all instances of telerik controls that are used in the HTML Editor Module

## Description of alternatives considered
N/A

## Screenshots
N/A

## Additional context
N/A

## Affected browser

* [x] Chrome
* [x] Firefox
* [x] Safari
* [x] Internet Explorer
* [x] Edge

**Comment by sleupold** [comment]
One option to solve this would be using CKEditor 4 in inline mode

**Comment by cklenk** [comment]
Would this potentially fix the issue I have with #3999?

**Comment by ahoefling** [comment]
I don't think it would fix that. Your error message in #3999 cites a 404 error loading a js page. That appears to be an issue isolated to the Client Dependency Framework which minimizes the files and combines it into 1 js/css file

**Comment by valadas** [comment]
So interestingly `InlineEditorEnabled` is set to true by default on a clean install but inline editing does not show up, soooo what would be the plan here ? Do we simply kill the inline editing all together or what ?

**Comment by bdukes** [comment]
I'm not seeing this on my test site.  I looked at this in #4142, and wasn't able to reproduce an issue.  I just removed Telerik DLLs from my local and I still get working inline editing.

![Inline editing on default home page template](https://user-images.githubusercontent.com/59507/95341191-9f354480-087b-11eb-93e8-70f9a4761fb1.png)

Am I missing something?

**Comment by bdukes** [comment]
Those controls in the HTML module are from `DotNetNuke.WebControls`, not `DotNetNuke.Web.Deprecated`
https://github.com/dnnsoftware/Dnn.Platform/blob/ed13b3579cc0e7310f7a40ae9c4d241d7fe32cf4/DNN%20Platform/Modules/HTML/HtmlModule.ascx#L2

Which is apparently [just a binary without source](https://github.com/dnnsoftware/Dnn.Platform/blob/develop/DNN%20Platform/Controls/DotNetNuke.WebControls/bin/DotNetNuke.WebControls.dll). 🤷🏻‍♂️

**Comment by ahoefling** [comment]
I really don't remember much about my research on this, it was quite some time ago. Looks like it is something we can close as it appears what I thought was being used is not being used.

**Comment by valadas** [comment]
@bdukes I am curious, how do you get inline editing working on current version ?

**Comment by bdukes** [comment]
Nothing special, I just go into edit mode, and then when I mouse over the module content there's a pencil floating on the top left.
![Default DNN home page in edit mode with pencil icon at top left of module](https://user-images.githubusercontent.com/59507/95505761-865c8a00-0974-11eb-995d-1377dd6ed0e2.png)

**Comment by valadas** [comment]
Oh, I kinda feel dumb now, I never used that lol. I thought it was only for the module title lol...

**Comment by bdukes** [comment]
😃 

There is also one for the module title (if your container uses the title).  It's a lot more useful for editing the title.  Since editing the content uses `contenteditable`, there's a lot you can't control markup-wise.  It's once of those nice features that can also cause you a lot of trouble.
