### ISSUE TITLE
Security Audit Checks for SQL Server Extra Permission fail

### ISSUE THREAD

**Issue by sleupold** [dnnsoftware/Dnn.Platform#3817]
## Description of bug
DNN Security Audit includes checks for extended permission of the SQL account.
This check for xp_dirtree always fails, even if the sql user is granted to use it

## Steps to reproduce
1. Make sure, the SQL User is granted to use xp_dirtree
2. perform DNN Security Audit from PersonaBar > Security
3. check sitelog

## Current behavior
error is logged, check is not performed. 

## Expected behavior
should return proper result and no error logged.

## Screenshots
If applicable, provide screenshots to help explain the bug.

## Error information
[ERROR] DotNetNuke.Data.PetaPoco.PetaPocoHelper - [3] Error executing SQL: DECLARE @Output TABLE(Data NVARCHAR(255), Depth INT) INSERT INTO @Output EXEC sys.xp_dirtree 'D:\WEB\TG-COM' SELECT @@ROWCOUNT Parameter '@Output' specified but none of the passed arguments have a property with this name (in 'DECLARE @Output TABLE(Data NVARCHAR(255), Depth INT) INSERT INTO @Output EXEC sys.xp_dirtree 'D:\WEB\TG-COM' SELECT @@ROWCOUNT ') 2020-06-06 16:03:02.279+02:00 [vps74][D:13][T:20][ERROR] DotNetNuke.Data.SqlDataProvider - System.ArgumentException: Parameter '@Output' specified but none of the passed arguments have a property with this name (in 'DECLARE @Output TABLE(Data NVARCHAR(255), Depth INT) INSERT INTO @Output EXEC sys.xp_dirtree 'D:\WEB\TG-COM' SELECT @@ROWCOUNT ') bei PetaPoco.Internal.ParametersHelper.<>c__DisplayClass5_0. b__0(Match m) bei System.Text.RegularExpressions.RegexReplacement.Replace(MatchEvaluator evaluator, Regex regex, String input, Int32 count, Int32 startat) bei System.Text.RegularExpressions.Regex.Replace(String input, MatchEvaluator evaluator) bei PetaPoco.Database.CreateCommand(IDbConnection connection, CommandType commandType, String sql, Object[] args) bei DotNetNuke.Data.PetaPoco.PetaPocoExt.ExecuteReader(Database database, String sql, Object[] args) bei DotNetNuke.Data.PetaPoco.PetaPocoHelper.ExecuteReader(String connectionString, CommandType type, Int32 timeoutSec, String sql, Object[] args) bei DotNetNuke.Data.SqlDataProvider.ExecuteSQLInternal(String connectionString, String sql, Int32 timeoutSec, String& errorMessage) 2020-06-06 16:03:02.287+02:00 [vps74][D:13][T:20][ERROR] DotNetNuke.Data.PetaPoco.PetaPocoHelper - [3] Error executing SQL: DECLARE @OS VARCHAR(1000) EXECUTE xp_regread 'HKEY_LOCAL_MACHINE', 'SOFTWARE\Microsoft\Windows NT\CurrentVersion', 'ProductName', @OS OUTPUT SELECT 1 Parameter '@OS' specified but none of the passed arguments have a property with this name (in 'DECLARE @OS VARCHAR(1000) EXECUTE xp_regread 'HKEY_LOCAL_MACHINE', 'SOFTWARE\Microsoft\Windows NT\CurrentVersion', 'ProductName', @OS OUTPUT SELECT 1') 2020-06-06 16:03:02.288+02:00 [vps74][D:13][T:20][ERROR] DotNetNuke.Data.SqlDataProvider - System.ArgumentException: Parameter '@OS' specified but none of the passed arguments have a property with this name (in 'DECLARE @OS VARCHAR(1000) EXECUTE xp_regread 'HKEY_LOCAL_MACHINE', 'SOFTWARE\Microsoft\Windows NT\CurrentVersion', 'ProductName', @OS OUTPUT SELECT 1') bei PetaPoco.Internal.ParametersHelper.<>c__DisplayClass5_0. b__0(Match m) bei System.Text.RegularExpressions.RegexReplacement.Replace(MatchEvaluator evaluator, Regex regex, String input, Int32 count, Int32 startat) bei System.Text.RegularExpressions.Regex.Replace(String input, MatchEvaluator evaluator) bei PetaPoco.Database.CreateCommand(IDbConnection connection, CommandType commandType, String sql, Object[] args) bei DotNetNuke.Data.PetaPoco.PetaPocoExt.ExecuteReader(Database database, String sql, Object[] args) bei DotNetNuke.Data.PetaPoco.PetaPocoHelper.ExecuteReader(String connectionString, CommandType type, Int32 timeoutSec, String sql, Object[] args) bei DotNetNuke.Data.SqlDataProvider.ExecuteSQLInternal(String connectionString, String sql, Int32 timeoutSec, String& errorMessage)

## Additional context
SQL statement will fails as well, when the command is executed in DNN SQL Console, I assume an issue in PetaPoco.ExecuterReader()

## Affected version
* [X] 10.00.00 alpha build (in development)
* [X] 09.06.01 latest supported release

## Affected browser
* [X] any

**Comment by sleupold** [comment]
Note: same applies with Registry access check:
DECLARE @OS VARCHAR(1000)
EXECUTE xp_regread 'HKEY_LOCAL_MACHINE', 'SOFTWARE\Microsoft\Windows NT\CurrentVersion', 'ProductName', @OS OUTPUT

**Comment by BiswaRath** [comment]
I see exactly the same issue when run some random checks in Security Audit Checks page. I did not see any error in UI but when i checked log file I see exactly the same sequence of issues as mentioned above. No idea what could be the issue. Please let us know if we need to make any changes in our site.
