### ISSUE TITLE
Ability to replace the built-in token replacement provider

### ISSUE THREAD

**Issue by bogdan-litescu** [dnnsoftware/Dnn.Platform#3819]
The current implementation does not allow for a 3rd party provider to do the token replacement. In My Tokens, we had to do various hacks and APIs to patch the modules to support it. 

The TokenProvider is provided via web.config, same as any other provider.

  ```
 <tokens defaultProvider="CoreTokenProvider">
      <providers>
        <clear />
        <add name="CoreTokenProvider" type="DotNetNuke.Services.Tokens.CoreTokenProvider, DotNetNuke" />
      </providers>
    </tokens>
```

This opens the platform to 3rd party token providers supporting various syntax.

For My Tokens, we'll update it to look like this:

```
  <tokens defaultProvider="MyTokenProvider">
      <providers>
        <clear />
        <add name="MyTokenProvider" type="avt.MyTokens.Providers.MyTokensProvider, avt.MyTokens.Providers" />
        <add name="CoreTokenProvider" type="DotNetNuke.Services.Tokens.CoreTokenProvider, DotNetNuke" />
      </providers>
    </tokens>
```

Ideally, this would also be exposed as a service to be used with DI.

**Comment by valadas** [comment]
closing since it is merged
