### ISSUE TITLE
Make unique indexes unique

### ISSUE THREAD

**Issue by sleupold** [dnnsoftware/Dnn.Platform#3825]
## Description of problem
Updated indexes in DNN 9.6.2 should be marked as "UNIQUE" to avoid SQL Server to add an unnecessary ID

## Description of solution
CREATE UNIQUE NonClustered INDEX

## Description of alternatives considered
none

## Additional context
https://blog.sqlauthority.com/2019/07/24/sql-server-performance-impact-of-unique-index/

## Affected browser
* [x] any

**Comment by sleupold** [comment]
I am going to submit a PR

**Comment by thabaum** [comment]
you simply ROCK man!

**Comment by sleupold** [comment]
still an issue, will submit a PR

**Comment by sleupold** [comment]
still on my plate

**Comment by sleupold** [comment]
this is still on my plate
