### ISSUE TITLE
Drop outdated and unused Stored Procedure "IsUserInRole" 

### ISSUE THREAD

**Issue by sleupold** [dnnsoftware/Dnn.Platform#3826]
## Description of bug
Stored Procedure "IsUserInRole" is not used anymore and should be dropped from the database

## Steps to reproduce
1. In SSMS, check dependencies of the sproc: None
2. In VS, check for use of "IsUserInRole": None

## Affected version
* [x] 10.00.00 alpha build (in development)
* [x] 09.06.01 latest supported release

## Affected browser
* [X] any

**Comment by sleupold** [comment]
I'll submit a PR

**Comment by sleupold** [comment]
I'll submit a PR

**Comment by valadas** [comment]
Awesome, thanks

**Comment by sleupold** [comment]
I still need to submit the PR

**Comment by sleupold** [comment]
please reopen, I plan to submit a fix

**Comment by bdukes** [comment]
reopened

**Comment by sleupold** [comment]
@bdukes thank you!

**Comment by sleupold** [comment]
still on my list
