### ISSUE TITLE
Modules can't be added to page when debug=true in web.config.

### ISSUE THREAD

**Issue by Constantine-Ketskalo** [dnnsoftware/Dnn.Platform#3833]
## Description of bug
In version 9.6.1 of DNN if you set `debug=true` in web.config, you can't add modules to pages any more until you set it to false again.

## Steps to reproduce
List the precise steps to reproduce the bug:
1. Edit web.config and change "false" to "true" for debug at line `<compilation debug="false" strict="false" targetFramework="4.7.2">`
2. Go to any page at your DNN website.
3. Click "edit page" (pencil sign)
4. Click "Add Module"
5. See empty list of modules to add, no scrolling, no searching by name
6. Click close in this modal window
7. See that modal window is frozen and doesn't disappear

## Current behavior
Can't add module to page while debug is set to true in web.config.

## Expected behavior
Adding modules to pages should always work.

## Screenshots
![chrome_Tnb3W8waEm](https://user-images.githubusercontent.com/21691213/84312553-cb5ee400-ab6d-11ea-90b8-9163324321b7.png)

## Error information
Logs don't contain any errors related to this bug.

## Affected version

* [ ] 10.00.00 alpha build (in development)
* [X] 09.06.01 latest supported release

## Affected browser

* [X] Chrome Version 83.0.4103.97 (Official Build) (64-bit)
* [ ] Firefox
* [ ] Safari
* [ ] Internet Explorer 11
* [ ] Microsoft Edge (Classic)
* [ ] Microsoft Edge Chromium

OS: Windows 10 x64

**Comment by Constantine-Ketskalo** [comment]
Just noticed, that in the same conditions in debug mode I can't even go to "Edit module" or "Settings" for module. It's just not clickable. But in release mode it works just fine.

**Comment by valadas** [comment]
I cannot reproduce, do you have any errors in the browser console (F12 in Chrome), or do you have logs in the Admin logs or in the /Portals/_default/logs folder that might help pinpoint the issue?

Also, if not using the default theme, can you reproduce the issue if you switch to the default Xcillion theme?

Also maybe try a new empty page to rule out a module interfering or some such...

**Comment by Constantine-Ketskalo** [comment]
> I cannot reproduce, do you have any errors in the browser console (F12 in Chrome), or do you have logs in the Admin logs or in the /Portals/_default/logs folder that might help pinpoint the issue?
> 
> Also, if not using the default theme, can you reproduce the issue if you switch to the default Xcillion theme?
> 
> Also maybe try a new empty page to rule out a module interfering or some such...

Yes, Valadas, I wasn't using default theme, but when I switched to default one I had the same error.

Neither the Admin logs nor the /Portals/_default/logs contain any errors.

But browser console has multiple errors. Here are all the errors in browser console, when I just load freshly created page, using Xcillion theme's Home page style:
![chrome_V7fXAsofW5](https://user-images.githubusercontent.com/21691213/84880012-abab4c80-b094-11ea-9e82-e423e6871d13.png)

When I click "Add module" one more error appears in the browser console:
![chrome_J9A8B3nBg1](https://user-images.githubusercontent.com/21691213/84880142-d4cbdd00-b094-11ea-93c1-716eb7528d68.png)

This page, which I have just created, contains already one HTML module. And when I click "Edit Module", "Settings" or "Develop" appears another error in the console:
![chrome_aut1N7m69T](https://user-images.githubusercontent.com/21691213/84880589-5facd780-b095-11ea-9988-ce9a565b5946.png)

**Comment by bdukes** [comment]
You're getting 404 responses for a couple of scripts.  Can you check if those scripts exist (`/js/Debug/dnn.modalpopup.js`, `/js/Debug/dnn.servicesframework.js`, and `/js/Debug/dnncore.js`)?

They're all coming from the `/js/Debug` folder, so perhaps that folder is missing.  If the site is not running in debug mode, it will use scripts from `/js` instead of `/js/Debug`, so that could be the culprit here.  As to _why_ that `Debug` folder might be missing, I don't have any specific theories (I have verified that those scripts are present in the 9.6.1 install and upgrade packages).  

That said, I feel like I've run into this before, but I don't remember the specifics.  I assume a client had a backup that excluded that `Debug` folder by default or something like that.

**Comment by Constantine-Ketskalo** [comment]
Thanks a lot, bdukes. You are totally right. folder `js/Debug` was missing, because it was ignored by git.

**Comment by Constantine-Ketskalo** [comment]
> You're getting 404 responses for a couple of scripts. Can you check if those scripts exist (`/js/Debug/dnn.modalpopup.js`, `/js/Debug/dnn.servicesframework.js`, and `/js/Debug/dnncore.js`)?
> 
> They're all coming from the `/js/Debug` folder, so perhaps that folder is missing. If the site is not running in debug mode, it will use scripts from `/js` instead of `/js/Debug`, so that could be the culprit here. As to _why_ that `Debug` folder might be missing, I don't have any specific theories (I have verified that those scripts are present in the 9.6.1 install and upgrade packages).
> 
> That said, I feel like I've run into this before, but I don't remember the specifics. I assume a client had a backup that excluded that `Debug` folder by default or something like that.

bdukes, can it be considered by DNN developers to rename that folder? I mean it's pretty common to add `Debug` folder to gitignore, which might lead to same issue again for many developers in future.

**Comment by bdukes** [comment]
We've talked over the years about better managing those scripts.  Ideally we'd only ship minified scripts with source maps, and those minified scripts would be generated as part of the build process.  However, no one has volunteered to take on that task, so for now it's just an idea.
