### ISSUE TITLE
Messages: Body shows "</div></fieldset>"

### ISSUE THREAD

**Issue by MaiklT** [dnnsoftware/Dnn.Platform#3835]
## Description of bug
When composing a message to another user, either by clicking on "Send message" from the user's profile/Activity Feed or from the Member Directory module, the message text body is filled with "&lt;/div&gt;&lt;/fieldset&gt;".

## Steps to reproduce
List the precise steps to reproduce the bug:
1. Go to another user's Activity Feed
2. Click on 'Send message'
3. See the text body

## Expected behavior
An empty text box

## Screenshots
<img width="509" alt="DNN_Messages" src="https://user-images.githubusercontent.com/7458140/84352346-72b73780-abbd-11ea-91a2-e800461d1045.png">

## Additional context
After some investigation, I found that the form is generated by a JavaScript (\Resources\Shared\components\ComposeMessage\ComposeMessage.js).

Changing the line (line number 18) that generates the textbox from

    html += "[...]<textarea rows='2' cols='20' id='bodytext' name='bodytext'/></div>";

to

    html += "[...]<textarea rows='2' cols='20' id='bodytext' name='bodytext'></textarea></div>";

solves the problem.

But this works only when "Enable Composite Files" (Settings >> Servers >> Server Settings >> Performance) is off. Switching it back to "on" again brings back the mess.

## Affected version

* [ ] 10.00.00 alpha build (in development)
* [X] 09.06.01 latest supported release
* [X] 09.06.00

## Affected browser

* [X] Chrome
* [X] Firefox
* [?] Safari
* [X] Internet Explorer 11
* [?] Microsoft Edge (Classic)
* [X] Microsoft Edge Chromium

**Comment by bdukes** [comment]
This looks like an issue coming from the jQuery 3.5 upgrade (in DNN 9.6.x).  I think your fix is correct.  I would guess the issue with composite files is related to caching (it didn't pick up your change), rather than the fix being incorrect or incomplete.  Would you be willing to submit a PR with that change?

**Comment by MaiklT** [comment]
Brian,
I tried to restart the app pool, but that did not help (with the composite files), and of course the browser cache as well. So I don't know if it has something to do with caching...
Sure, I'll try to make a pull request...

**Comment by bdukes** [comment]
I sometimes have to update the Client Dependency Version, and then Clear Cache (and maybe <kbd>Ctrl</kbd>+<kbd>F5</kbd> after that)
