### ISSUE TITLE
SqlDataProvider.IsConnectionValid leaks connections, exhausts pool

### ISSUE THREAD

**Issue by jeremyZX** [dnnsoftware/Dnn.Platform#3840]
## Description of bug
Our production instance has been having issues with the NumberOfReclaimedConnections performance metric increasing. There appears to be a strong correlation between the NumberOfReclaimedConnections metric increasing and the number of times SqlDataProvider.IsConnectionValid is accessed.

This appears to be because a datareader created in https://github.com/dnnsoftware/Dnn.Platform/blob/future/10/DNN%20Platform/Library/Data/SqlDataProvider.cs#L64 is not being properly disposed.

## Steps to reproduce
List the precise steps to reproduce the bug:
1. Execute any code which directly or indirectly calls SqlDataProvider.IsConnectionValid

## Current behavior
The number of active connections in the connection pool increases with each access of IsConnectionValid, and the NumberOfReclaimedConnections metric increases once a high enough gen GC is triggered to finalize the undisposed datareaders.

## Expected behavior
The number of active connections in the connection pool remains constant and the NumberOfReclaimedConnections metric remains 0.

## Screenshots
If applicable, provide screenshots to help explain the bug.
![image](https://user-images.githubusercontent.com/634106/84680623-f8f6b500-af00-11ea-90dc-434535601f52.png)

![image](https://user-images.githubusercontent.com/634106/84680673-0b70ee80-af01-11ea-985f-6563e5652b9d.png)

## Affected version
DNN 9.5.0, but the behavior appears to be present in master as well as in 10-alpha source code.

* [x] 10.00.00 alpha build (in development)
* [x] 09.06.01 latest supported release

**Comment by bdukes** [comment]
👍 looks like a bug to me.  are you planning to submit a pull request to fix?

**Comment by valadas** [comment]
This may explain some random issues I have been experiencing here and there...

**Comment by sleupold** [comment]
PR #4258 pending
