### ISSUE TITLE
Is DNN Security HotFix 2017.1 still needed?

### ISSUE THREAD

**Issue by improwise** [dnnsoftware/Dnn.Platform#3841]
Upgrading a DNN site from 9.2.0 to 9.6.1 we also uninstalled the "DNN Security HotFix 2017.1" assuming it was not needed any more (at least not as a stand alone installation). After doing so we got this error message in the Security Analyzer:

"The Telerik component vulnerability has not been patched, please go to https://www.dnnsoftware.com/community-blog/cid/155449/critical-security-update--september2017 for detailed information and to download the patch."

Do we still need to have that patch installed even several years later or can we just ignore the error message (this is the Security Analyzer in the persona bar). We still have not upgraded the actual production site so it begs the question if we should then let that extension be installed still? 

Thanks. 

For reference, https://www.dnnsoftware.com/community-blog/cid/155449/critical-security-update--september2017

**Comment by bdukes** [comment]
Are you looking in the Security Analyzer module, or the Security Analyzer tab in the Persona Bar?  The module has been deprecated.  Here's the Telerik check that would give that error message: [`CheckTelerikVulnerability.cs`](https://github.com/dnnsoftware/Dnn.Platform/blob/cc61549005ab5ea1c66fa91670931642a62893e4/Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Components/Security/Checks/CheckTelerikVulnerability.cs).

It's checking for a patched version of `Telerik.Web.UI` or a newer version, and it's ensuring that three app settings in the `web.config` are present.  Uninstalling the hot fix shouldn't have affected any of those, as far as I know.

**Comment by improwise** [comment]
In the persona bar. 

It's actually quite weird as we have removed the Telerik DLLs althogheter (believing that they had already been deprecated in DNN) which according to code in CheckTelerikVulnerability.cs should mean that we should get another error instead:

`            if (File.Exists(filePath))
            {
                ...
            }
            else
            {
                result.Notes.Add("Telerik component is not installed in this site.");
            }`

But main question here is more if the "DNN Security HotFix 2017.1" is still needed or not.

**Comment by bdukes** [comment]
Are you seeing any notes in the leftmost column, or just the failure message?

No, the HotFix package should not need to remain after it's been installed.

That code definitely seems to indicate that you shouldn't see that failure message if `Telerik.Web.UI.dll` isn't in the `bin` folder…

We have been recommending the removal of the Security Analyzer module, however #2525 has pointed out that the uninstall of the module removes a stored procedure that the Persona Bar extension uses.  So I would either manually recreate that stored procedure, or wait until that issue is resolved.  It shouldn't hurt anything to leave it, other than potentially being confusing.

**Comment by improwise** [comment]
This is interesting as we have uninstalled the old Security Analyzer but have not seen any obvious problems affecting the new one, even though the SpP SecurityAnalyzer_GetModulesHasHeaderFooter is indeed missing. Might have to look more into detail in the error logs though, but nothing obvious. 

Here is the full error message (have tried to format it a bit)

_CheckTelerikVulnerability : Check if Telerik component has vulnerability. 

FAIL
The Telerik component vulnerability has not been patched, please go to https://www.dnnsoftware.com/community-blog/cid/155449/critical-security-update--september2017 for detailed information and to download the patch.
 
App Setting "Telerik.AsyncUpload.ConfigurationEncryptionKey" doesn't exist in web.config.,App Setting "Telerik.Web.UI.DialogParametersEncryptionKey" doesn't exist in web.config._

Note that the message about is correct in itself, that seem to have been commented out by a previous DNN upgrade (around DNN 9.2 it seems based on source control). 

Correction, we noticed that the Telerik DLLs are infact in the bin folder. We removed them thinking they were not needed but can see now that the DNN 9.6.1 upgrade seems to have put them back into bin. That explains the error message (path in code).

**Comment by bdukes** [comment]
So, at this point we're good to close this issue, right?  Any remaining mysteries?

**Comment by improwise** [comment]
Yes and no. If we have confirmed that the DNN Security HotFix 2017.1 is not needed anymore, there is still the matter of the warning being generated despite the Telerik DLLs being the ones included with the latest DNN release. The warning seem to trigger on the web.config app setting, but as it is the DNN installation that has commented out that setting AFAIK, I would guess that the same warning is probably triggered for other users as well. 

Is the warning still releant with the latest Telerik DLLS? If so, maybe this ticket should be closed but perhaps another one should be created instead regarding that.

**Comment by bdukes** [comment]
AFAIK the warning about the missing values in the `web.config` is still valid, but I'm not aware of anything in DNN Platform that would have commented those out (am I forgetting anything @mitchelsellers)?

**Comment by improwise** [comment]
We don't really know what changed it but since we are not using Telerik ourselves, we assumed it was during some kind of DNN upgrade, or maybe the installation of the Security Patch. But that would seem a bit strange if the same action lead to the error message. 

If the DNN Security HotFix 2017.1 is not needed anymore, perhaps it should be uninstalled during upgrade?

**Comment by mitchelsellers** [comment]
There is nothing in DNN Platform that would have commented out those values, in fact, we don't actually have support really for commenting out values in the appSettings section.

If the Telerik DLL is still in place, all mitigations should remain. And, if manually removed, upgrades could re-introduce the risk points
