### ISSUE TITLE
SSL offloading support broken since 9.5.0

### ISSUE THREAD

**Issue by daguiler** [dnnsoftware/Dnn.Platform#3847]
## Description of bug
DNN no longer works correctly behind an SSL offloading load balancer.

## Steps to reproduce
1. Install DNN 9.6.1
2. Create a web farm (with ARR for example) with SSL offloading enabled. Make sure to set the `SSL Offload Header Value` security setting to `X-ARR-SSL`
3. Navigate to the site under HTTPS. So far so good, you'll get a secure site.
4. Click on "Home" page link

## Current behavior
The site reloads under HTTP.

## Expected behavior
Site should stay under HTTPS.

## Additional context
This is a regression caused by #3453, so it seems this has been happening since 9.5.0.

But wait, there is a confusing twist to this:
I can confirm that reverting #3453 fixes the SSL offloading problem, and my expectation was that it would also revive #3452. Well this was not the case. After reverting the commit in my dev environment, I am not able to reproduce #3452. Creating page A and then creating page B to redirect to page A works as expected for me under SSL offloading. So I don't know, maybe more steps are required to reproduce #3452.

## Affected version
* [X] 10.00.00 alpha build (in development)
* [X] 09.06.01 latest supported release
* [X] 09.06.00
* [X] 09.05.00

**Comment by thabaum** [comment]
I have read the code and I see what was trying to be done, and what you are trying to do.  The situation here maybe that there are a number of ways to do SSL offloading and DNN does not cover all the different approaches, only one.

**Comment by daguiler** [comment]
In my view, #3453 was a regression that needed reversal because previous to that change, DNN would return HTTPS links on SSL offloaded scenarios, not HTTP links.
I understand there are ways to convert HTTP back to HTTPS by intercepting the generated response, but that is not how it was working before, and it was not the intent of that change either. Such breaking change should be discussed and approved first.
Reversal is the way to go here IMO.

**Comment by thabaum** [comment]
That is fine with a reversal, some use a local certificates to encrypt the backend with a public in the front-end.  

IMO it should have both and like you said kept the old way as well as it does break things if you are not running https.  I won't stand in the way of it.   

Anyone that began using it with SSL should be also informed it will break for them as well.  I think this will lock some users into version for a while until there is a solution for both situations.
