### ISSUE TITLE
Captcha image not showing on login page when using Internet Explorer 11

### ISSUE THREAD

**Issue by dsjak-shie** [dnnsoftware/Dnn.Platform#3849]
## Description of bug
The default DNN authentication provides you the ability to show a CAPTCHA control on the login page.
It has come to our attention that the CAPTCHA image is not shown in Internet Explorer 11 when the **X-Content-Type-Options: nosniff** header is used. The CAPTCHA control works normally in:

- Chrome
- Firefox
- Edge (legacy)
- Edge (chromium)

## Steps to reproduce
1. Enable CAPTCHA for login.
2. Enable the **X-Content-Type-Options: nosniff** header.
3. Navigate to the login page.
4. The CAPTCHA image is not displayed

## Current behavior
The CAPTCHA image is not displayed

## Expected behavior
The CAPTCHA image is displayed.

## Affected version
* [ ] 10.00.00 alpha build (in development)
* [x] 09.06.01 latest supported release
---
* [ ] Chrome
* [ ] Firefox
* [ ] Safari
* [x] Internet Explorer 11
* [ ] Microsoft Edge (Classic)
* [ ] Microsoft Edge Chromium

**Comment by valadas** [comment]
A couple of small notes.

We no longer actively test for Internet Explorer as their is no good reason for anyone using this browser in this day and age. That being said, if a PR with a fix comes in that does not interfere with other modern browsers, we would be glad to accept it, but my question is: Is anyone willing to invest time in digging into this issue and submitting a fix?

Also, do we know it is a Dnn issue or rather an IE issue?

I will put this issue in "Pending Verification" to see if anyone has more context on an intention to work on this..

**Comment by bdukes** [comment]
The CAPTCHA handler appears to just write a JPEG to the output stream without any headers or anything https://github.com/dnnsoftware/Dnn.Platform/blob/cc61549005ab5ea1c66fa91670931642a62893e4/DNN%20Platform/Library/UI/WebControls/CaptchaHandler.cs#L33-L43

I'm kind of surprised that this works on newer browsers, `nosniff` should prevent them from display content without a content type as an image.  I think we just need to set a content-type header and that would make things better.

**Comment by dsjak-shie** [comment]
I added the content type. Seems to be working in IE 11 locally now. Will submit a PR soon.

**Comment by dsjak-shie** [comment]
Thanks @bdukes for pointing me in the right direction and @donker a.k.a. StayAtHomeDNNer for the fantastic youtube playlist explaining how to build DNN.
