### ISSUE TITLE
Edit mode causes viewstate to be lost

### ISSUE THREAD

**Issue by stephen-lim** [dnnsoftware/Dnn.Platform#3864]
## Description of bug
This is a known issue but never got fixed and continue to affect DNN 9.6.1. See old discussion from [DNN-10523 - Webform postback in Edit mode loosing viewstate of the GridView](https://dnntracker.atlassian.net/browse/DNN-10523?focusedCommentId=144020&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel)

When in Edit page mode, DNN dynamically injects a new UpdatePanel between the pane and the controls. I believe this causes the ViewState to be broken on postback -- probably due to the ViewState manager unable to match back with the control IDs since it shifted by a level??

Furthermore, if you have a module that dynamically loads other controls that contains UpdatePanels, it would break badly with a yellow page error message:

**Cannot unregister UpdatePanel with ID 'XXX' since it was not registered with the ScriptManager. This might occur if the UpdatePanel was removed from the control tree and later added again, which is not supported**. 

I saw many people have reported it on the forum but never knew it's due to this dynamic injection of the UpdatePanel between controls:

https://www.dnnsoftware.com/forums/threadid/539307/scope/posts/problems-by-using-of-updatepanel-in-dnn9
https://www.dnnsoftware.com/forums/threadid/542352/scope/posts/updatepanel-exception-when-in-edit-mode
https://www.dnnsoftware.com/forums/threadid/540864/scope/posts/unable-to-edit-pages-after-upgrading-to-911
https://github.com/DNN-Connect/IdentitySwitcher/issues/22

## Steps to reproduce
In our simple example, we have a MultiView control that switches between two different Views depending on the state. After a button postback, the MultiView does not retain the last selected active view when submitting in Edit mode. We also saw in the case of a GridView, it would be empty after postback.

In another example, create a module control that dynamically loads a 2nd control inside the Page_Init (i.e. call the LoadControl(...) method). The 2nd control contains an UpdatePanel. You will get the error message **"Cannot unregister UpdatePanel..."** just by loading the page in Edit mode.

The same controls all works fine in View page mode.

## Expected behavior
The MultiView control should retain the last active view on postback. The GridView should retain its values.

Dynamically loaded control with an UpdatePanel should not break the page.

## Additional context
I believe there was an attempt to fix this part of the problem, but i don't think the fix got merged in.

https://github.com/dnnsoftware/Dnn.EditBar/issues/23

## Affected version
* [x] 09.06.01 latest supported release
* [x] 09.01.01

## Affected browser
* [x] Chrome
* [x] Firefox
* [x] Safari
* [x] Internet Explorer 11
* [x] Microsoft Edge (Classic)
* [x] Microsoft Edge Chromium

**Comment by mitchelsellers** [comment]
I believe this is related to the SupportsPartialRendering flag on a module control.  If you are dynamically doing things this should NOT be set to true.

**Comment by stephen-lim** [comment]
Hi @mitchelsellers, I don't think it will make a difference. 

The root cause is in the **CreateChildControls()** implementation of the **Dnn.EditBar.UI.Controllers.ContentEditorManager.cs** file.  It injects its own UpdatePanel in between the tree hierarchy at runtime, which I think is a risky code to begin with. Due to the unwanted side effects, it then tries to compensate by attaching an unload event to the existing UpdatePanels and use reflection to force the ScriptManager to re-register the child UpdatePanels. I believe due to the the timing of the page life cycle, if you have dynamically loaded controls, this event would not get attached and therefore will break with the **Cannot unregister UpdatePanel with ID 'XXX' since it was not registered with the ScriptManager** error. In addition, it appears it can break the ViewState as well under some circumstances.

Correct me if I'm wrong but I didn't find anywhere that would make a difference in the code if SupportsPartialRendering would bypass this injected UpdatePanel.

Thank you

**Comment by mitchelsellers** [comment]
EditBar is no longer used

**Comment by stephen-lim** [comment]
The original author in JIRA [DNN-10523](https://dnntracker.atlassian.net/browse/DNN-10523?focusedCommentId=144020&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel) mentioned the CreateChildControls() in the EditBar. I simply referred to it. 

I think somewhere else in the DNN code is doing the similar UpdatePanel injection breaking the modules. I don't know where exactly but if I do a find for "updatePanel = new UpdatePanel", I found 2 more places where this is potential happening?:

**DotNetNuke.Framework.Ajax.cs - WrapUpdatePanelControl(Control objControl, bool blnIncludeProgress)
DotNetNuke.UI.Modules.ModuleHost.cs - LoadUpdatePanel()**

**Comment by mitchelsellers** [comment]
Right but it is ONLY wrapped if you opt in. Not by default.

**Comment by stephen-lim** [comment]
I just checked the module is already set to supportsPartialRendering=false in the manifest and correctly registered as disabled in the DNN Extension, yet the problem is happening in Edit mode.

**Comment by stephen-lim** [comment]
In DNN 9.6.1 when in Edit mode, the **Dnn.EditBar.UI.Controllers.ContentEditorManager.CreateChildControls()** definitely gets called. I was able to step through the lines in the Visual Studio debugger and I see the UpdatePanel line gets injected along with the reflection call trying to re-register with ScriptManager despite the supportsPartialRendering being false. I notice if a module has loads controls dynamically, the GetUpdatePanelsInPane(pane) won't find it so it wasn't able to re-register correctly leading the error.

**Comment by mitchelsellers** [comment]
Weird, I have multiple modules that work totally fine. Do you have a simple module example you could share?  Also was this a clean installation or an upgrade?

**Comment by stephen-lim** [comment]
Sure. I created 2 simple modules to show the 2 different errors.

[Dnn.UP.zip](https://github.com/dnnsoftware/Dnn.Platform/files/4842951/Dnn.UP.zip) - The control has a 2 level nested child control (View.ascx loads Child.ascx dynamically, which in turn references Child2.ascx statically). Both child controls have UpdatePanels.

Notice in Edit mode, you get the **Cannot unregister UpdatePanel** error message. In debugging, I found the recursive GetUpdatePanelsInPane(pane) method did not find all the child UpdatePanel controls even though I can clearly see they exists in the object viewer (after drilling down the Controls hierarchy many times). So the issue might not be due to the dynamic loading nature of the child controls, but rather the bug is in the recursive method incorrectly skipping over some deep nested controls.

[Dnn.UP2.zip](https://github.com/dnnsoftware/Dnn.Platform/files/4842952/Dnn.UP2.zip) - The View.ascx loads the Child.ascx dynamically.

Child.ascx has a MultiView control that is initialized to **"View 2"** on Page_Load by default (note the IsPostBack check condition). After you submit the button, it should stay on **"View 2"** if ViewState is preserved. This works fine in View mode. Notice in Edit mode, the MultiView is reset to none after submit. Is the ViewState lost?

Let me know if you have any questions. Thank you

**Comment by stephen-lim** [comment]
I forgot to attach the source code. The previous 2 zip files are the compiled modules. Here are their sources:

[Dnn.UP.Source.zip](https://github.com/dnnsoftware/Dnn.Platform/files/4842965/Dnn.UP.Source.zip)


[Dnn.UP2.Source.zip](https://github.com/dnnsoftware/Dnn.Platform/files/4842964/Dnn.UP2.Source.zip)

**Comment by stephen-lim** [comment]
If i make the correction to the recursive code, I'm able to fix the first error.

![image](https://user-images.githubusercontent.com/10053534/85957869-00857780-b95f-11ea-9a4b-729b31e4af13.png)

But I still haven't figured out what causes the ViewState lost though.

**Comment by valadas** [comment]
The above recursive code is Dnn code or your module code. If you found a solution, a pull request would be nice so we can quickly understand what the change is...

**Comment by stephen-lim** [comment]
The highlighted part in blue is my code fixing the error in the DNN recursive code. I haven't figured out the other problem (there are 2 issues here).

**Comment by stephen-lim** [comment]
We're still working on it, but we're still stuck on the 2nd issue not working. I would appreciate any help or feedback here.
