### ISSUE TITLE
Broken images and "The handle is Invalid" error on web farm

### ISSUE THREAD

**Issue by daguiler** [dnnsoftware/Dnn.Platform#3872]
## Description of bug
`DnnImageHandler` generates an exception while serving images when the nodes of a farm use a shared network folder as the web root.

## Steps to reproduce
1. Set up a simple web farm with ARR where all nodes share a common physical path in the network
2. Clear the ~\App_Data\_imagecache folder
3. Navigate to the home page and log in (the user avatar is shown correctly)
5. Press F5 to refresh

## Current behavior
The user avatar is broken.
There is an HTTP 500 error in the browser console related to DnnImageHandler.ashx.

## Expected behavior
The user avatar should be displayed correctly.

## Screenshots
![image](https://user-images.githubusercontent.com/30123437/85958032-de90f280-b968-11ea-96c5-4d162255912d.png)

![image](https://user-images.githubusercontent.com/30123437/85957770-9bce1b00-b966-11ea-8114-4d8ad4878984.png)

## Error information
```
The handle is invalid. (Exception from HRESULT: 0x80070006 (E_HANDLE))

Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code.

Exception Details: System.Runtime.InteropServices.COMException: The handle is invalid. (Exception from HRESULT: 0x80070006 (E_HANDLE))

Source Error:
An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.

Stack Trace:
[COMException (0x80070006): The handle is invalid. (Exception from HRESULT: 0x80070006 (E_HANDLE))]

[HttpException (0x80004005): An error occurred while communicating with the remote host. The error code is 0x80070006.]
   System.Web.Hosting.IIS7WorkerRequest.RaiseCommunicationError(Int32 result, Boolean throwOnDisconnect) +4478821
   System.Web.Hosting.IIS7WorkerRequest.FlushCore(Boolean keepConnected, Int32 numBodyFragments, IntPtr[] bodyFragments, Int32[] bodyFragmentLengths, Int32[] bodyFragmentTypes) +11941829
   System.Web.Hosting.IIS7WorkerRequest.FlushCachedResponse(Boolean isFinal) +743
   System.Web.HttpResponse.UpdateNativeResponse(Boolean sendHeaders) +1330
   System.Web.HttpRuntime.FinishRequestNotification(IIS7WorkerRequest wr, HttpContext context, RequestNotificationStatus& status) +182
```

## Affected version
* [X] 10.00.00 alpha build (in development)
* [X] 09.06.01 latest supported release
(and this probably goes back all the way to initial versions)

## Affected browser
* [X] Chrome
* [X] Firefox
(I didn't try on other browsers)

**Comment by valadas** [comment]
Merged
