### ISSUE TITLE
Update http:// to https:// where applicable in text and references

### ISSUE THREAD

**Issue by EPTamminga** [dnnsoftware/Dnn.Platform#3879]
## Description of problem
Current text elements sometimes reference URLs as http:// i.s.o. https://.

## Description of solution
Change URL.

## Description of alternatives considered
No change.

**Comment by sleupold** [comment]
@EPTamminga: please note that in any playe using TokenReplace, you may now use the new token [Portal:FULLURL]. which includes the protocol.

**Comment by EPTamminga** [comment]
@sleupold The changes I made had no relationship with TokenReplace, they where the w3.org references or links to sites in text, e.g. links to http://www.dnnsoftware.com or http://www.google.com
