### ISSUE TITLE
Extensions "Upgrade?" shows unreleased version info

### ISSUE THREAD

**Issue by brentil** [dnnsoftware/Dnn.Platform#3886]
## Description of bug
After upgrading 4 different DNN installs to 9.6.1 the Extensions -> Installed Extensions -> Upgrade? column began showing version info but for unreleased versions of DNN.  They all show versions 10.0.x which is I'm guessing for the upcoming DNN 10 release but it's not out yet.  I upgraded systems from 9.2.2 -> 9.3.2 -> 9.6.1 as well as 9.4.4 -> 9.6.1 and experience this on all of them.

## Steps to reproduce
List the precise steps to reproduce the bug:
1. Upgrade DNN install to 9.6.1
2. Open Extensions -> Installed Extensions 
3. See Upgrade? show version 10.0.x numbers

## Current behavior
Shows the release info for versions not released making a user think they're out of date when they're not.

## Expected behavior
Should show that 9.6.1 is the latest and then 9.6.2 when released instead of version info of unreleased editions.

## Screenshots
![image](https://user-images.githubusercontent.com/309174/86270483-4b8acf00-bb99-11ea-966e-f6e7ba794857.png)

## Affected version
* [ ] 10.00.00 alpha build (in development)
* [X] 09.06.01 latest supported release

**Comment by valadas** [comment]
This information comes back from the upgrade service, we are aware of the situation and we are discussing options, but it is nothing we can fix in the platform itself. For that reason I am closing this issue but please know we are working on improving this soon.
