### ISSUE TITLE
"Redirect After Login" not working for "Account Login" Module

### ISSUE THREAD

**Issue by BeniFreitag** [dnnsoftware/Dnn.Platform#3895]
## Description of bug
Setting _Redirect After Login_ only works for the standard Login-Module but not on the "Account Login" Module.

## Steps to reproduce
1. Create a new page [Custom-Login-Page]
2. Add the _Account Login_ Module to that page
3. Configure Settings > Security > _Redirect After Login_ > Set to [my-welcome-page]
3. Open [Custom-Login-Page] as unauthenticated User and login. Redirect will not work. The user stays on the [Custom-Login-Page] after successful login.

## Current behavior
After a successful Login, the user stays on the Page containing the [Account Login] Module.

## Expected behavior
After a successful Login, the user should be redirected to the page specified in _Redirect After Login_-Setting

## Screenshots
![Redirect After Login](https://user-images.githubusercontent.com/6669093/86618910-f9431700-bfb9-11ea-8e11-86e8ba70eb75.gif)

## Additional context
The redirect is prevented in [Login.ascx.cs](https://github.com/dnnsoftware/Dnn.Platform/blob/dbeb24c99d9f84b4d4cf69546e7c43b3100f6bc1/DNN%20Platform/Website/DesktopModules/Admin/Authentication/Login.ascx.cs#L220) by `(isDefaultPage || IsRedirectingFromLoginUrl())`

![Error-Cause](https://user-images.githubusercontent.com/6669093/86619143-4fb05580-bfba-11ea-9d43-80dd18277a2d.png)

## Affected version

* [x] 09.06.01 latest supported release
* [ ] 07.04.02 **not** affected

## Affected browser

* [x] Chrome
* [x] Any / Browser is not relevant

**Comment by mitchelsellers** [comment]
This is already documented in #3348 and #3661 closing this ticket in favor of the existing tickets that are open

**Comment by BeniFreitag** [comment]
As a workaround I added the following code into Login.ascx which sets a returnurl-cookie having the desired URL:

```C#
<script runat="server">
    protected override void OnLoad(EventArgs e)
    {
        // Workaround for Redirect-Issue https://github.com/dnnsoftware/Dnn.Platform/issues/3348 and https://github.com/dnnsoftware/Dnn.Platform/issues/3661
        // Set a cookie with the return-url for the current page
        var redirectAfterLogin = Convert.ToInt32(GetSetting(PortalId, "Redirect_AfterLogin"));
        if (redirectAfterLogin != Null.NullInteger)
        {
            HttpContext.Current.Response.Cookies.Set(new HttpCookie("returnurl", DotNetNuke.Common.Globals.NavigateURL(redirectAfterLogin))
            {
                Expires = DateTime.Now.AddDays(1),
                Path = Request.RawUrl
            });
        }

        base.OnLoad(e);
    }
</script>
```

**Comment by mitchelsellers** [comment]
@BeniFreitag  There are security concerns with regards to this process, I would suggest a review of this process
