### ISSUE TITLE
Visualizer not able to change settings in shared pages

### ISSUE THREAD

**Issue by berkarslan-xo** [dnnsoftware/Dnn.Platform#3911]
## Description of bug
An unhandled error message pops up about can't saving the settings when trying to update a shared module from non-master page.

## Steps to reproduce
1. install engage 9.3.1 and login as host;
2. enable content library, create 2 content items of "Person " type;
3. add 2 new pages A and B;
3. edit page A, put a visualizer module on the page, and set it to "show on all pages";
4. edit page B, edit the shared visualizer module, click "Manage Content", select another content item then try to save.

## Current behavior
An unhandled error message pops up about can't saving the settings.

## Expected behavior
A message to user should be shown that this is a shared module, need to go to the master page to do changes, similar to the HTML pro module..

## Screenshots
Reproduction Video: https://www.screencast.com/t/g4kjRA7Cos

## Error information
The popups shows "Error occurred when request service 'Set'."

## Affected version
* [x] 10.00.00 alpha build
* [x] 09.06.02 release candidate
* [ ] 09.06.01 latest supported release

## Affected browser
* [x] Chrome
* [ ] Firefox
* [ ] Safari
* [ ] Internet Explorer 11
* [ ] Microsoft Edge (Classic)
* [ ] Microsoft Edge Chromium

**Comment by sleupold** [comment]
are you using DNN Platform or Evoq?

**Comment by valadas** [comment]
Well this is an Evoq feature, are you reporting it because there is some fix to do in platform that you will provide a PR for or are we just reporting the issue? We cannot obviously reproduce this issue in Platform...

**Comment by berkarslan-xo** [comment]
Hi, there is something that needs to be changed in Platform also. There will be 2 PRs; one in Platform, another in Evoq side.
