### ISSUE TITLE
Accept License Checkbox in Installer Display Quirk

### ISSUE THREAD

**Issue by hismightiness** [dnnsoftware/Dnn.Platform#3912]
## Description of bug
When installing an extension, there is a step where you must accept a license (if it exists).  At first page load, this checkbox is positioned in a way that is expected.  However, once you check this checkbox, it repositions itself to the left.  This is a poor first impression for new users.  

## Steps to reproduce
List the precise steps to reproduce the bug:
1. Login as a superuser.
2. Hover over the Manage menu in the persona bar and choose Extensions.
3. Click the Install Extension button.  
4. Choose and attempt to install any DNN extension.
5. Proceed to the license step and check the checkbox to accept the license.

## Current behavior
When checked, the checkbox repositions itself to the left, far away from its label.  

## Expected behavior
The checkbox should appear checked and not move.  

## Error information
No errors.  

## Additional context
N-A

## Affected version

* [ ] 10.00.00 alpha build
* [x] 09.06.02 release candidate
* [x] 09.06.01 latest supported release

## Affected browser

* [x] Chrome
* [x] Firefox
* [x] Safari
* [x] Internet Explorer 11
* [x] Microsoft Edge (Classic)
* [x] Microsoft Edge Chromium

**Comment by david-poindexter** [comment]
@hismightiness thank you for documenting this bug that has been annoying the crap out of me for a while now!  😆   If you are not planning to submit a PR to fix it, I'll gladly take this one on.

**Comment by hismightiness** [comment]
@david-poindexter I wasn't planning on fixing it any time soon, so feel free.  I'm just pushing a lot of updates right now and it's also annoying the heck out of me.  😆

**Comment by david-poindexter** [comment]
Okay, thanks for the confirmation.  I'll add this one to my list.  I just kept forgetting to log an issue for this, so I am glad you did!

**Comment by thabaum** [comment]
I was just about to dive into this, glad I am not the only one.  I should find time again here soon I will dial in a few more issues, if I don't see a PR for this one by then I will tackle it as well.

**Comment by david-poindexter** [comment]
@thabaum this one is already assigned to me and on my list after the next release (which is soon). Thanks.
