### ISSUE TITLE
typo in pages.resx - "copy to descendant pages"

### ISSUE THREAD

**Issue by sergeydryomin** [dnnsoftware/Dnn.Platform#3913]
## Description of bug
typo in confirmation popup. In pages.resx - "copy to descendant pages"

## Steps to reproduce
List the precise steps to reproduce the bug:
1) open the Persona bar > Content > Pages menu
2) select a page with child pages
3a) on Permissions tab, select "Copy permissions to descendant pages"
3b) on Advanced tab > Appearance tab, select "Copy appearance to descendant pages"
-------

## Current behavior
The system message texts are:
Permissions have been copy to descendant pages successfully
Appearance has been copy to descendant pages successfully

## Expected behavior
The system message texts should be:
Permissions have been copied to descendant pages successfully
Appearance has been copied to descendant pages successfully

## Screenshots
https://drive.google.com/file/d/1pl8D3Q2Ntw4o80g1D5SvdRS3recqy7wK/view

## Error information
The relevant messages are in DesktopModules\Admin\Dnn.PersonaBar\Modules\Dnn.Pages\App_LocalResources\Pages.resx
as
CopyPermissionsToDescendantPagesSuccess.Text and
CopyAppearanceToDescendantPagesSuccess.Text

## Additional context
Solution already found - creating fork to commit

## Affected version

* [X] 10.00.00 alpha build
* [X] 09.06.02 release candidate
* [X] 09.06.01 latest supported release

## Affected browser

* [X] Chrome
* [X] Firefox
* [X] Safari
* [X] Internet Explorer 11
* [X] Microsoft Edge (Classic)
* [X] Microsoft Edge Chromium

**Comment by valadas** [comment]
Copy that! :)

**Comment by sergeydryomin** [comment]
https://github.com/dnnsoftware/Dnn.Platform/pull/3914 fix
