### ISSUE TITLE
Removed - security issues not to be disclosed 

### ISSUE THREAD

**Issue by atkh007** [dnnsoftware/Dnn.Platform#3921]
Per the security policy of this project security related concerns are NOT to be disclosed here. I removed this content. 

Please feel free to follow process and email security@dnnsoftware.com. 

We appreciate everyone’s adherence to this policy.

**Comment by mitchelsellers** [comment]
Closing per policy as noted

**Comment by atkh007** [comment]
should i mail this report ???? to security@dnnsoftware.com. 
??

**Comment by mitchelsellers** [comment]
As noted above, and in the documentation yes that is the policy. 

We do not discuss security issues here

**Comment by atkh007** [comment]
alright Thanks .
