### ISSUE TITLE
HTML module removes domain from URL's on save

### ISSUE THREAD

**Issue by jpalhinhas** [dnnsoftware/Dnn.Platform#3928]
## Description of bug
After saving, the HTML module will remove the https://www.yourdomain.com from the URL. The issue is particularly bad when you have URL's with domains different from the domain from your DNN installation.

## Steps to reproduce
List the precise steps to reproduce the bug:
1. Go to 'Edit HTML module content'
2. Select from the drag and drop 'Basic Text Box'
3. Select from the Render Mode either 'text or HTML'  
**NOTE - When you select the Render mode "Raw" the domain will not be removed from the URL's**
4. Save the edits and the module will remove the domain from the URL's leaving only the relative path.

## Current behavior
After saving, the HTML module removes the domain from the URL's leaving only the relative path and breaks the link to URL's that have domains different from the one in the installation.

## Expected behavior
HTML module shouldn't change or remove the domain from the URL's after saving.

## Additional context
In the **Basic Text Box** mode when you select the Render mode **Raw** the domain will not be removed from the URL's and the issue will not happen.

## Affected version
* [ ] 10.00.00 alpha build
* [x] 09.06.02 release candidate
* [x] 09.06.01 latest supported release

## Affected browser
* [x] Chrome
* [x] Firefox
* [x] Safari
* [x] Internet Explorer 11
* [x] Microsoft Edge (Classic)
* [x] Microsoft Edge Chromium

**Comment by mitchelsellers** [comment]
Can you confirm some details regarding the installation this was observed in.

* What version of DNN was it using
* Was it a clean installation?  If not, what version was it upgraded from
* Did you customize the configuration of the Html Editor

There is an option that can allow the editor to behave in this manner, but it is not the default.

**Comment by jpalhinhas** [comment]
v. 09.03.02 (24)

It's not a clean installation and no changes were done to the HTML Editor. 

It started doing this out of the blue!
