### ISSUE TITLE
Prevent uninstalling DDR Module

### ISSUE THREAD

**Issue by jncraig** [dnnsoftware/Dnn.Platform#3942]
## Description of problem
The DDR Module can be uninstalled from the Extensions page.  If that is done, the DDN skin object won't work.

## Description of solution
Mark the DDR Module as one that cannot be uninstalled

## Description of alternatives considered
none

**Comment by mitchelsellers** [comment]
This one is quite interesting reallybnas there are times and places that it can be removed.

We only have a “system” flag. And I guess this would meet that standard.  

@david-poindexter thoughts?

**Comment by jncraig** [comment]
The reason behind the suggestion is that somebody did it an posted on the DNN Community Forums.

Besides when your skin doesn't use DDR, what are the "other times and places"?

**Comment by Timo-Breumelhof** [comment]
I think marking it as system would be fine, it's not clear right now that it's in use as it's a module and a SKO

**Comment by david-poindexter** [comment]
There are cases when it is not used at all and can be uninstalled.  I could understand the argument of making it uninstallable though.  It is like anything else that provides functionality in other contexts.  A super user should know what they are doing when they uninstall something like this.  So we want the platform to be more "dummy proof", we could go this route.  😉

**Comment by Timo-Breumelhof** [comment]
Well as we mark some skins as System and as I guess 90% of the skins (the DNN GO skins excluded) are using DDR menu, I think marking it as system is good.Especially because it looks like a module that's not in use unless you know it's also a skin object.
And I wonder how many users really know that..

**Comment by david-poindexter** [comment]
Excellent points @Timo-Breumelhof
