### ISSUE TITLE
Password reset email not being sent

### ISSUE THREAD

**Issue by rmanjoney** [dnnsoftware/Dnn.Platform#3946]
## Description of bug
When users attempt to reset password via the Login form's "Reset" button, no password reset email is sent.

## Steps to reproduce
1. Navigate to site's homepage.
2. Click the "login" link
3. Click "Reset Password" to attempt to reset a forgotten password.
4. Enter the correct/valid email address for a registered user
5. Dialog indicates that email will be sent if details entered were correct (which they were).

## Current behavior
No email is sent/received, error is logged in Admin Logs

## Expected behavior
Email with password reset link should have been sent to the user, but it was not.

## Error information
An error is logged in the Admin Log:

07/30/2020 13:34:56
Password Sent Failure
 
The Lake Club, Inc. 
Cause If the details entered were correct you should receive an email mess 
Cause:If the details entered were correct, you should receive an email message shortly with a link to reset your password.

IP:

Server Name: RD00155D64CA21

## Additional context
The SMTP server settings for this site are correct, SMTP config settings pass. All other automated system emails send correctly/normally (i.e., the SMTP Test, New user registrations, etc.) - it's seemingly only this Password Reset email that's having problems. 

## Affected version
* [ ] 10.00.00 alpha build
* [X] 09.06.02 current release 
* [X] 09.06.01 

## Affected browser
* [X] Chrome
* [ ] Firefox
* [ ] Safari
* [ ] Internet Explorer 11
* [ ] Microsoft Edge (Classic)
* [X] Microsoft Edge Chromium

![Screenshot 2020-07-30 134239](https://user-images.githubusercontent.com/13399992/88955899-923c1980-d26a-11ea-9bea-95675878c75a.png)

**Comment by gopherboy38138** [comment]
I'm having the same issue.  DNN 9.8.1.  Can someone please help me?

**Comment by socialmagicau** [comment]
I am having the same problem but I get no errors. SMTP test works fine. The requireUniqueEmail is set to "true". Still not sure what is causing this issue.

DNN 9.10.0
.net 4.8

**Comment by bdmarvin** [comment]
I am having the same issue on one website, but not another. Note: The two websites are housed on the same server, same version, but different URLs.
