### ISSUE TITLE
"Test a Page URL" doesn't work for non-default portal

### ISSUE THREAD

**Issue by sergeydryomin** [dnnsoftware/Dnn.Platform#3947]
## Description of bug
Provide a clear and concise description of the bug.

## Steps to reproduce
List the precise steps to reproduce the bug:
1. Create a new site
2. Access the new site
3. Access the "Test a Page URL" feature through "Persona Bar >> Setting >> S.E.O >> Test URL
4. Try to "Test a Page URL" by trying to choose a page to test

## Current behavior
Unable to select any pages available for the non-default portal causing this feature to not work at all for non-default portal.

## Expected behavior
Able to select any pages available to test its URL.

## Video steps
https://drive.google.com/file/d/1XruTq5clwrB1lb2h8MSRtPW3AsL5iaqq/view?usp=sharing

## Additional context
Issue already fixed - creating PR now

## Affected version

* [X] 10.00.00 alpha build
* [X] 09.06.02 release candidate
* [X] 09.06.01 latest supported release

## Affected browser

* [X] Chrome
* [X] Firefox
* [X] Safari
* [X] Internet Explorer 11
* [X] Microsoft Edge (Classic)
* [X] Microsoft Edge Chromium

**Comment by donker** [comment]
Problem is here:

https://github.com/dnnsoftware/Dnn.Platform/blob/develop/Dnn.AdminExperience/ClientSide/Seo.Web/src/components/testUrl/index.jsx#L89

The roles parameter should have the Admin Role ID as value. Not "0" (which is the portal admin role id for portal 0).
