### ISSUE TITLE
Pencil icon is not shown for non-published pages

### ISSUE THREAD

**Issue by tauqeer-haider** [dnnsoftware/Dnn.Platform#3960]
## Description of bug
Pencil icon is not shown for non-published pages

## Steps to reproduce
1. Login as host user
2. Navigate to CONTENT > Pages
3. Click on Add Page at the top
4. Fill page name with any
5. Click on "Add Page" at the bottom
6. Click on the "A" icon in the CONTENTPANE section
7. Enter any text into HTML editor
8. Navigate to CONTENT > Pages

## Current behavior
The pencil icon is not visible near the page name in the tree

## Expected behavior
The pencil icon is visible near the page name in the tree

## Screenshots
If applicable, provide screenshots to help explain the bug.

## Error information
Provide any error information (console errors, error logs, etc.) related to this bug.

## Additional context
Provide any additional context that may be helpful in understanding and/or resolving the bug.

## Affected version

* [x] 10.00.00 alpha build
* [x] 09.06.02 release candidate
* [x] 09.06.01 latest supported release

## Affected browser

* [x] Chrome
* [x] Firefox
* [x] Safari
* [x] Internet Explorer 11
* [x] Microsoft Edge (Classic)
* [x] Microsoft Edge Chromium

**Comment by valadas** [comment]
I do not understand this issue, which pencil icon are you expecting to see and what is the "A" icon you are referring to ? Can you add a screenshot of what your are expecting?

**Comment by tauqeer-haider** [comment]
> I do not understand this issue, which pencil icon are you expecting to see and what is the "A" icon you are referring to ? Can you add a screenshot of what your are expecting?

Here is the expected output.
![expected](https://user-images.githubusercontent.com/22594255/89457399-dccf0180-d754-11ea-8605-4edeb8aae8e9.png)

The "A" icon is a symbol to include text editor module on page.

**Comment by bdukes** [comment]
Ah that's an Evoq feature, DNN Platform doesn't have the three "quick add" options for empty panes.

**Comment by valadas** [comment]
haaa, ok, well we do need to think a little bit regarding this. I remember there was a PR to make the page titles longer, it was frankly pretty much unusable on any 2-3 level nestings with very normal page name lenghts. IMO there is simply not enough room to put icons together with the page title and my preference would be to leave this as it is and for Evoq to move those icons elsewhere like in the ... menu or some such...

**Comment by EPTamminga** [comment]
@valadas It is mentioned here: https://github.com/dnnsoftware/Dnn.Platform/pull/3961
