### ISSUE TITLE
upgrade lucene.net component to 4.8.0

### ISSUE THREAD

**Issue by zyhfish** [dnnsoftware/Dnn.Platform#3977]
## Description of problem
lucene.net component is out-to-date.

## Description of solution
upgrade lucene.net component to 4.8.0

**Comment by sleupold** [comment]
AFAIK still an open task.

**Comment by valadas** [comment]
A PR was create for this and there was a discussion about that change. 4.8.0 is still a beta, which means they could still introduce any breaking changes before release. In the current state the approvers did not want to put a dependency on beta packages as more breaking changes can still occur.

Also, this upgrade includes breaking changes that would require proper adjustments/testing after the package is out of Beta.

So to be able to make this an actionable issue we need:
- Lucene.Net package to be out of Beta
- Planning this upgrade at the very least for a minor release if we have proper wrappers so it's not a breaking change for 3rd party Dnn developers
- Planning this upgrade for a major release if we also need to introduce a breaking change.

4.8.0 has been in beta for like 2 years. I will close this issue in the spirit of cleaning the backlog so it does not hang here for too long. If anyone want's to proceed with more analysis/discussions just ping me up and I'll be glad to move it to a discussion instead until this is actionable.
