### ISSUE TITLE
Update Cake Build to use dotnet CLI

### ISSUE THREAD

**Issue by ahoefling** [dnnsoftware/Dnn.Platform#3987]
## Description of problem
Cake Build has recently started recommending using the dotnet cli instead of bash/powershell scripts. The new usage depends on the .NET Core CLI installed, but it works with .NET Framework, mono, .NET Core, etc.

usage:
```
dotnet cake
```

or specifying a "Build" Target
```
dotnet cake --Target=Build
```

## Description of solution
Remove build.ps1 script, and add support for cake's dotnet CLI integration. 
- [Cake Docs](https://cakebuild.net/docs/getting-started/setting-up-a-new-project)

Once this is completed, we will need to update any build steps in Azure Pipelines

## Description of alternatives considered
It is perfectly okay to keep the cake build the way it is. This would just be a nice enhancement for the dotnet cli integration.

## Screenshots
N/A

## Additional context
N/A

## Affected browser
N/A

**Comment by ahoefling** [comment]
I looked into this a little bit and the .NET Core CLI usage with cake isn't compatible with the way our build scripts work. If we find a way to run our build scripts without the Powershell addin we could make this update. The powershell addin for cake currently is not compatible with the .NET Core. (0.4.8)

I'll let a maintainer review this item and decide if we should proceed with more research. I think we can close this out and maybe re-visit this in the future. I am using the .NET Core CLI with cake on personal projects and it is really convenient to use

**Comment by bdukes** [comment]
In #4322 we switched to Cake.Frosting, which uses a `csproj` for the build system.  There's a `build.ps1` still, but it basically just downloads the .NET SDK if it's missing and then calls `dotnet run --project build/build.csproj`.
