### ISSUE TITLE
Splash Page functionality does not work for all browsers

### ISSUE THREAD

**Issue by mayaco** [dnnsoftware/Dnn.Platform#3991]
On an upgraded version of DNN 9.6.2 (from DNN 9.3.2) we noticed using the Splash Page feature does not work for all browsers. Visiting the website URL, http://www.domain.com, should take you to the Splash Page, http://www.domain.com/Welcome. 

Using Microsoft Edge (v 84.0.522.59) and Safari (iOS) a visitor is taken to Home Page and not the Splash Page. 

In Firefox (v 79.0) and Chrome (v 84.0.4147.125) a visitor to the website is taken to the Splash Page first.

![github-Settings-Site-Behavior-Default-Pages](https://user-images.githubusercontent.com/21064803/90434204-e2481800-e081-11ea-934d-90559b696e85.png)

**Comment by bdukes** [comment]
Here's the code that handles the splash page:
https://github.com/dnnsoftware/Dnn.Platform/blob/80b6b2c56c06a058a8995196f8fa8375a28c9508/DNN%20Platform/Library/Entities/Urls/RewriteController.cs#L1623-L1633

It appears that the only logic around it has to do with whether the browser has a particular cookie set or not.  Are you sure you're using new sessions on these tests?  On Edge and Safari, does it work when you use a Private window?

**Comment by mayaco** [comment]
Yes. I've tested all four browsers (Edge, Safari, Firefox and Chrome) in Private windows and only Firefox and Chrome worked as designed.
