### ISSUE TITLE
Newtonsoft.json Conflicts

### ISSUE THREAD

**Issue by meetmandeep** [dnnsoftware/Dnn.Platform#3994]
## Description of bug
Referencing DotNetNuke.Web dll results in following build warning:

Warning		Found conflicts between different versions of the same dependent assembly. In Visual Studio, double-click this warning (or select it and press Enter) to fix the conflicts; otherwise, add the following binding redirects to the "runtime" node in the application configuration file: <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1"><dependentAssembly><assemblyIdentity name="Newtonsoft.Json" culture="neutral" publicKeyToken="30ad4fe6b2a6aeed" /><bindingRedirect oldVersion="0.0.0.0-10.0.0.0" newVersion="10.0.0.0" /></dependentAssembly></assemblyBinding>

## Steps to reproduce
Create a new project and reference the DotNetNuke.dll and DotNetNuke.Web.dll. 

## Current behavior
Build warning is generated as soon as you reference the DotNetNuke.Web.dll

## Expected behavior
No Warnings. 

## Error information
DotNetNuke.Web is internally referring to Newtonsoft.Json.dll 6.0.0 instead of the latest 10.0.0

**Comment by bdukes** [comment]
[The `Newtonsoft.Json` reference in `DotNetNuke.Web`](https://github.com/dnnsoftware/Dnn.Platform/blob/0bd8b22b997d953a0e59bd1d313314b0453d4e5f/DNN%20Platform/DotNetNuke.Web/DotNetNuke.Web.csproj#L108-L111) is pointing to 10.0.3, as is [the reference in `DotNetNuke.dll`](https://github.com/dnnsoftware/Dnn.Platform/blob/0bd8b22b997d953a0e59bd1d313314b0453d4e5f/DNN%20Platform/Library/DotNetNuke.Library.csproj#L137-L141).

It looks like Newtonsoft.Json was updated from 7 to 10 in fcb64c641abdf89290e605795b27851d9720cc4c.  Do you have any thoughts on where this 6.x reference is?

**Comment by bdukes** [comment]
The Dnn.EditBar.Library project is still referencing Newtonsoft.Json 6:
https://github.com/dnnsoftware/Dnn.Platform/blob/76fc4bec4c53f3d66fef9a2aafb8fbdfb9c65de1/Dnn.AdminExperience/EditBar/Dnn.EditBar.Library/Dnn.EditBar.Library.csproj#L40-L43

The other Persona Bar projects have weird references, but ultimately builds against Newtonsoft.Json 10.x:
https://github.com/dnnsoftware/Dnn.Platform/blob/76fc4bec4c53f3d66fef9a2aafb8fbdfb9c65de1/Dnn.AdminExperience/EditBar/Dnn.EditBar.UI/Dnn.EditBar.UI.csproj#L241-L244
https://github.com/dnnsoftware/Dnn.Platform/blob/f1397aa562499242dd6d25c41803941f2801f217/Dnn.AdminExperience/Library/Dnn.PersonaBar.UI/Dnn.PersonaBar.UI.csproj#L58-L61
https://github.com/dnnsoftware/Dnn.Platform/blob/63ea5cdb51c114129358b217effd141299016776/Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Dnn.PersonaBar.Extensions.csproj#L703-L706

**Comment by meetmandeep** [comment]
> It looks like Newtonsoft.Json was updated from 7 to 10 in [fcb64c6]

Great. I wasn't testing on the latest 9.7.0 RC2; that resolves this issue. 

I suppose we can keep this issue open for DNN.PersonaBar references.
