### ISSUE TITLE
Page Output Caching conflicts with Anti-Forgery Token

### ISSUE THREAD

**Issue by bdukes** [dnnsoftware/Dnn.Platform#4005]
## Description of bug
I just ran across an issue I hadn't experienced before, and wanted to see if y'all thought there was a solution worth investing in.  A client had turned on page output caching on a number of pages that had public-facing forms (you don't need to be logged in to submit the form).  The form is using a Web API endpoint that's protected with the `[ValidateAntiForgeryToken]` attribute, and the form itself calls `DotNetNuke.Framework.ServicesFramework.Instance.RequestAjaxAntiForgerySupport()`.  However, when the page was served from the cache, the `__RequestVerificationToken` cookie wasn't being sent with the request.  This led to all of the requests returning a 401 response and the browser showing its built-in auth dialog.

## Current behavior
Requests from cached page fail.

## Expected behavior
Requests from cached page do not fail.

### Option 1
The caching mechanism has some way to know that an anti-forgery token was requested and saves that information with the cached page.

### Option 2
The caching mechanism always requests an anti-forgery token b/c why not.

### Option 3
Since we only serve cached pages to folks who aren't logged in (need to verify this), and a cross-site request forgery isn't possible with someone who's not logged in (need to verify this), we could decide that all unauthenticated requests pass the anti-forgery token check.

### Option 4
This is too hard to get right, it's just an unsupported configuration.

**Comment by mitchelsellers** [comment]
Option 4 was the initial intention of the functionality, and what I have always educated people on.

Option 2 could be possible, but the performance hit could negate some of the gains, as you would have to parse & replace the anti-forgery token on every request.
