### ISSUE TITLE
DNN9 remove class from HTML

### ISSUE THREAD

**Issue by Scippy** [dnnsoftware/Dnn.Platform#4008]
On DNN9 with HTML module if I add some code like

`<small class="myclass">TEST</small>`

and save it all work fine but when I edit it I can't no more found the class for that tag because it was removed

`<small>TEST</small>`

Is it a bug for DNN?

**Comment by valadas** [comment]
Well, it would be more about the HTML editor here https://github.com/DNN-Connect/CKEditorProvider

That being said, it is kind of a known issue, the html editor won't allow any code you could not have generated using the UI controls by default. There are ways around this using some CkEditor configs and flags and some such, try searching the issues here and in the linked repository, some people had some workarounds.
