### ISSUE TITLE
Cookie consent

### ISSUE THREAD

**Issue by MaiklT** [dnnsoftware/Dnn.Platform#4014]
For better matching the GDPR requirements it should be possible that

- the cookie consent appears in a light box that can only be closed by clicking the accept button
- a decline button that sends the user to "about:blank" or whatever

Maybe it is possible that this can be implemented as an option for the portal settings, something like "normal" or "strict".

**Comment by Tychodewaard** [comment]
When hit decline the cookies must be ignored/not set. So, not just a redirect :-)

**Comment by MaiklT** [comment]
@Tychodewaard You're right, of course. But a lot of things won't work without cookies (language, dnn_IsMobile... etc.), except you use more or less complicated query strings.
The correct way could be that DNN provides some sort of API that may declare a cookie as "functional", and others as "conveniant", "commercial", etc. and let the user decide what kind of cookies he accepts and which he refuses, letting no option to refuse the functional cookies. But before that, the user must not have any possibility to navigate on the site, and if he refuses any cookies, there should be a mechanism that tells him that the site is not available without the functional cookies.
Extensions should be forced to use this API, so the thing would be clean in my eyes.
