### ISSUE TITLE
Sitegroups doesn't allow sharing modules

### ISSUE THREAD

**Issue by jncraig** [dnnsoftware/Dnn.Platform#4023]
## Description of bug
The sitegroups functionality doesn't allow existing modules to be added from other sites.  There is no dropdown in the Add Existing Module panel to select the site.

## Steps to reproduce

1. Create a sitegroup and add sites
2. Go to a site 
3. In Edit Mode, click Add Existing Module
4. There is no way to select a site and page from which to add a module.  Only same site modules can be added

## Current behavior
There is no way to select the site from which an existing module is to be added tot the current site.

## Expected behavior
There should be a way to select the site and the page

## Screenshots
If applicable, provide screenshots to help explain the bug.

## Error information
It's really missing functionality rather than a bug.

## Additional context
Provide any additional context that may be helpful in understanding and/or resolving the bug.

## Affected version

* [ ] 10.00.00 alpha build
* [x ] 09.07.01 release candidate
* [ ] 09.07.00 latest supported release

Also 9.6.1.

## Affected browser
N/A
* [ ] Chrome
* [ ] Firefox
* [ ] Safari
* [ ] Internet Explorer 11
* [ ] Microsoft Edge (Classic)
* [ ] Microsoft Edge Chromium

**Comment by thabaum** [comment]
is this a feature that should be discussed to be added?

**Comment by valadas** [comment]
Well IMO, this does not really need discussing, we just need to update the dropdown to be able to select modules from other portals in the group if the settings allow it...

**Comment by jncraig** [comment]
Still is important to me!

**Comment by david-poindexter** [comment]
Upon a cursory check, this one is going to be JS world (not React).  Here is the Existing Module Dialog code.
 https://github.com/dnnsoftware/Dnn.Platform/blob/714db32390f800ea2336bb0fd2d54fc589256e6b/Dnn.AdminExperience/EditBar/Dnn.EditBar.UI/editBar/resources/ContentEditorManager/Js/ExistingModuleDialog.js

@jncraig I'll see if I can dig into this a bit more after DNN Summit.  Right now is last-minute-scramble time!  😱

**Comment by jncraig** [comment]
Yes, I’m working on presentation, too!

I’m going to do Feature Maker.

**Comment by david-poindexter** [comment]
Closing per PR #4597
