### ISSUE TITLE
Version # of DNN Standard Extensions do not match DNN version

### ISSUE THREAD

**Issue by EPTamminga** [dnnsoftware/Dnn.Platform#4027]
## Description of bug
Version # of standard platform core extensions to not match DNN Platform version

## Steps to reproduce
List the precise steps to reproduce the bug:
1. Install DNN97x
2. Log in as HOST
3. Goto Extensions

## Current behavior
Wrong version shown.

## Expected behavior
Version # in line with DNN version.
Wrong #'s are shown for:
* Authentication
* Registration
* Search Results
* Users and Roles
* View Profile
* Default Authentication
* Skin objects

## Screenshots

![image](https://user-images.githubusercontent.com/5859855/91835604-e6f7f900-ec49-11ea-83c2-a8f707f5653e.png)

![image](https://user-images.githubusercontent.com/5859855/91836163-b19fdb00-ec4a-11ea-97f0-1e671714dc92.png)

![image](https://user-images.githubusercontent.com/5859855/91836275-d85e1180-ec4a-11ea-8209-7f9492b61f58.png)

## Error information
-

## Additional context
Tested on DNN971-RC1, but problem also exists in DNN970

## Affected version

* [ ] 10.00.00 alpha build
* [X] 09.07.01 release candidate
* [X] 09.07.00 latest supported release

## Affected browser

* [X] Chrome
* [X] Firefox
* [X] Safari
* [X] Internet Explorer 11
* [X] Microsoft Edge (Classic)
* [X] Microsoft Edge Chromium

**Comment by mitchelsellers** [comment]
Was this an upgrade?

**Comment by sleupold** [comment]
I noticed the same in a new install

**Comment by EPTamminga** [comment]
@mitchelsellers: this was a clean new install

**Comment by valadas** [comment]
duplicates #3542 There was a PR to update those verisons but I think the way it was implemented only did it once, we need to do something that will do it on all releases...
