### ISSUE TITLE
Checkbox "Accept License" during Extension Install incorrectly located

### ISSUE THREAD

**Issue by EPTamminga** [dnnsoftware/Dnn.Platform#4028]
## Description of bug
The checkbox is located left, the text in the center

## Steps to reproduce
List the precise steps to reproduce the bug:
1. Install Extension
2. Select any type of extension to install
3. Click to the screen to Accept the license, checkbox is misplaced (see screenshot)
4. If the misplacement is not there, check/uncheck the checkbox

## Current behavior
Misplaced checkbox

## Expected behavior
Correctly postioned.

## Screenshots
![image](https://user-images.githubusercontent.com/5859855/91854284-c9378d80-ec63-11ea-8850-1b062fff1e55.png)

## Error information
-

## Additional context
-

## Affected version

* [ ] 10.00.00 alpha build
* [X] 09.07.01 release candidate
* [X] 09.07.00 latest supported release

## Affected browser

* [x] Chrome
* [x] Firefox
* [x] Safari
* [x] Internet Explorer 11
* [x] Microsoft Edge (Classic)
* [x] Microsoft Edge Chromium

**Comment by valadas** [comment]
Duplicates #3912
