### ISSUE TITLE
Persona Bar not showing admin pages for Administrators

### ISSUE THREAD

**Issue by stephen-lim** [dnnsoftware/Dnn.Platform#4031]
## Description of bug
After you created a new page under the Admin page, only superusers are shown the menu item in the Persona Bar. Administrators cannot see the new page.

## Steps to reproduce
From Persona Bar:
1. Add a new page (e.g "Test"), select "Admin" as your **Parent Page**, enable the **Display in menu** and **Save**.
2. Login as Host user. You will see the "Test" menu appear under the Manage section in the Persona Bar.
3. Login as Administrator and the "Test" menu does not appear even after forcing a hard refresh.

## Current behavior
Page created under Admin parent page are not showing in the Persona Bar for Administrators.

## Expected behavior
Any page created under Admin parent page with show in menu should appear for Administrators.

## Screenshots
New page created under Admin parent page with Display in menu.

![image](https://user-images.githubusercontent.com/10053534/91886922-0ac23b80-ec58-11ea-8cdd-220177e796c5.png)

This is what you see as Administrator

![image](https://user-images.githubusercontent.com/10053534/91886986-23325600-ec58-11ea-9d24-cc70600da059.png)

This is what you see as Host. Notice the Test menu item shows up.

![image](https://user-images.githubusercontent.com/10053534/91887270-920faf00-ec58-11ea-8dcc-d47f9f8da846.png)

## Additional context
I found similar issue discussed in the old JIRA [DNN-10608](https://dnntracker.atlassian.net/browse/DNN-10608) and is unresolved.

## Affected version
This tested in DNN 9.2 and 9.6.
* [x] 09.02.02
* [x] 09.06.01

## Affected browser
* [x] Chrome
* [x] Firefox
* [x] Safari

**Comment by renderfarmer** [comment]
Issue ist still existing in DNN 9.10.2, so this should be re-opened.

**Comment by stephen-lim** [comment]
Agree. I was able to confirm the problem still exists in in DNN 9.9.1

**Comment by b-creative** [comment]
> Issue ist still existing in DNN 9.10.2, so this should be re-opened.

Confirmed

**Comment by renderfarmer** [comment]
This shouldn't be closed before it's resolved...

**Comment by DigitalTrading** [comment]
Please can we have an update on this issue, is it even being looked at? Otherwise, this thread will just keep closing.
Is there an update on the horizon or is it just NOT been considered?
