### ISSUE TITLE
Treat Warnings as Build Errors - DotNetNuke.Abstractions

### ISSUE THREAD

**Issue by ahoefling** [dnnsoftware/Dnn.Platform#4040]
## Description of problem
DNN has many build warnings riddled throughout the entire solution which are usually indicators of issues with the code. Be it legacy code that has not been cleaned up or wasted memory footprints when allocating data that is never used. We should be treating all build warnings as errors to ensure a high level of code quality.

This is a massive undertaking with the size of DNN, I recommend we do this for the `DotNetNuke.Abstractions` project as it is the newest project and smallest project.

## Description of solution
- Update `.csproj` to treat build warnings as erros
- Update code to remove all build errors

## Description of alternatives considered
N/A

## Screenshots
N/A

## Additional context
Code Quality Enhancement

## Affected browser
N/A

**Comment by bdukes** [comment]
We could also do this for `DotNetNuke.DependencyInjection`

**Comment by bdukes** [comment]
I expect it'll be a while before we're ready to turn this on for any other projects, so I'm not sure how helpful that top-level task would be (it'll probably just get closed after getting stale)

**Comment by bdukes** [comment]
See [the SA0001 documentation](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA0001.md).  We need to turn on generation of the XML doc file for the project for StyleCop to check the validity of the comments.

**Comment by ahoefling** [comment]
That helped, now I Just need to remove the warnings 👍

**Comment by valadas** [comment]
I agree on turning that on on small new projects like this, but yeah we still have a lot of work to do before even thinking about turning that on elsewhere 😬
