### ISSUE TITLE
Cookie uses dnn_IsMobile with term "dnn"

### ISSUE THREAD

**Issue by thabaum** [dnnsoftware/Dnn.Platform#4044]
## Description of bug
Not really a bug but a preference, I would like to see less references to the platform as possible and I believe changing the cookie used for `dnn_IsMobile` could be changed to something else less revealing

## Steps to reproduce
List the precise steps to reproduce the bug:
1. Go to a dnn site 
2. Click on security lock to view cookies used in browser
3. Scroll to `dnn_IsMobile`

## Current behavior
cookie uses `dnn_IsMobile`

## Expected behavior
something more generic that is less revealing used instead of terms like "dnn" in cookie.

## Screenshots
If applicable, provide screenshots to help explain the bug.
![image](https://user-images.githubusercontent.com/13577556/92175785-134e7980-edf2-11ea-8556-8ea3d2969053.png)

## Additional context
I will create a PR using `app_IsMobile` for a more generic cookie name

## Affected version

* [x ] 10.00.00 alpha build
* [x ] 09.07.01 release candidate
* [x ] 09.07.00 latest supported release

## Affected browser

* [x ] Chrome
* [ ] Firefox
* [ ] Safari
* [ ] Internet Explorer 11
* [ ] Microsoft Edge (Classic)
* [x ] Microsoft Edge Chromium

**Comment by bdukes** [comment]
Folks do have configurations and documentation making use of that name, so just changing the name would be a breaking change for some people.  Making the name configurable would not be a breaking change, and it much more likely to get accepted.  Hope it helps!

**Comment by thabaum** [comment]
Looking into a web.config solution as proposed here would it be something like adding the following:

`  <appSettings>  
    <add key="MobileViewSiteCookieName" value="dnn_IsMobile"/>  
    <add key="DisableMobileViewCookieName" value="dnn_NoMobile"/>  
  </appSettings>
`

Then in FriendlyUrlController.cs file:

`
        private const string MobileViewSiteCookieName = ConfigurationManager.AppSettings["MobileViewSiteCookieName"];
        private const string DisableMobileViewCookieName = ConfigurationManager.AppSettings["DisableMobileViewSiteCookieName"];
`
Settings in app settings could change or maybe it needs to be in `<dotnetnuke>` web.config settings?

**Comment by thabaum** [comment]
I am not into adding work potentially to any folks workloads.  I would like to create the solution as you described which was my first go to fix, but thought maybe the simple fix would be good to go... 

Looking into a web.config solution as proposed here would it be something like adding the following:

`<appSettings>`
`<add key="MobileViewSiteCookieName" value="dnn_IsMobile"/>`
`<add key="DisableMobileViewCookieName" value="dnn_NoMobile"/>`  
`</appSettings>`

Then in FriendlyUrlController.cs file edit to select these keys.  ( DNN Platform/Library/Entities/Urls/FriendlyUrlController.cs line 34 about )

After adding `using System.Configuration` to the top of the file I could change the lines of code as shown and things should work am I correct?

` private readonly string MobileViewSiteCookieName = ConfigurationManager.AppSettings[name: "MobileViewSiteCookieName"];`
 `private readonly string DisableMobileViewCookieName = ConfigurationManager.AppSettings[name: "DisableMobileViewSiteCookieName"];`

I got this far with VS not yelling at me except to make the first letter lowercase in the `readonly` string which I had to change from `const`...  which then of coarse I would change it throughout the class if I do this.

I know this isnt 100% correct I am just putting down some ideas here... bare with me sorry :(
Settings in app settings could change or maybe it needs to be in `<dotnetnuke>` web.config settings?

If so how do I go about making sure the new app setting is added to everyones web configs?

Am I heading in the right direction here?  

Thanks again for the support assisting me with this issue!

**Comment by bdukes** [comment]
One thing you should probably do is default to the old value, and then you don't need to add it to existing `web.config` files.  It could look like this:
```c#
private readonly string MobileViewSiteCookieName = ConfigurationManager.AppSettings[name: "MobileViewSiteCookieName"] ?? "dnn_IsMobile";
private readonly string DisableMobileViewCookieName = ConfigurationManager.AppSettings[name: "DisableMobileViewSiteCookieName"] ?? "dnn_NoMobile";
```

You can also see [`09.08.00.config`](https://github.com/dnnsoftware/Dnn.Platform/pull/3969/files#diff-518cc92a834687e51bd4ec125085e75b) from #3969 for an example of adding new elements to the `web.config`

**Comment by thabaum** [comment]
I will try to have this done up today, I was hoping to work on the PR last night...
