### ISSUE TITLE
Use request scope in PortalModuleBase

### ISSUE THREAD

**Issue by GerardSmit** [dnnsoftware/Dnn.Platform#4046]
## Description of problem
In the class `PortalModuleBase` it is possible to resolve services through the property `DependencyProvider`. 

In PR https://github.com/dnnsoftware/Dnn.Platform/pull/3930 the implementation changed which causes every control to have its own scope:

https://github.com/dnnsoftware/Dnn.Platform/blob/8bb34af67f456699cfba62a150f77b1055edec64/DNN%20Platform/Library/Entities/Modules/PortalModuleBase.cs#L46

Which is an improvement of the previous implementation (using the global scope) however it comes with a drawback:

Let's say I've registered a scoped service that uses a database connection and stores cache in a field.

- When I resolve the service in control A, the instance is created and the data is cached.
- When I resolve the same service in control B, it's creating a new instance because it's a different scope. The service retrieves the same data again.

## Description of solution
In https://github.com/dnnsoftware/Dnn.Platform/pull/3520 @dimarobert created `HttpContext.Current.GetScope()`. I would suggest to use the same scope in `PortalModuleBase` and if the HTTP Context doesn't exists, then it would create a new scope.

## Additional context
In ASP.Net Core, scoped services are created per request (see https://docs.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection#request-services). So I assumed this was also the case in DotNetNuke.

## Workaround
It's possible to use `Context.GetScope().ServiceProvider` instead of `DependencyProvider` to use the request scope.

**Comment by bdukes** [comment]
Agreed, we need to be using request scope where it's available.  Would you like to submit a PR with that change?

**Comment by GerardSmit** [comment]
I've created a PR (https://github.com/dnnsoftware/Dnn.Platform/pull/4053).
