### ISSUE TITLE
IHostSettingsService Convert Dictionary -> IDictionary

### ISSUE THREAD

**Issue by ahoefling** [dnnsoftware/Dnn.Platform#4051]
## Description of bug
We recently added `IHostSettingsService` in the 9.7.1 release. I was looking through the code and we have a couple APIs using `Dicitonary<string, string>` and variations of the `Dicitonary<>` implementation. I think this was an oversight during the code review and it should be updated to `IDictionary<>`.

Here are the identified APIs to update
```c#
Dictionary<string, IConfigurationSetting> GetSettings();
Dictionary<string, string> GetSettingsDictionary();
void Update(Dictionary<string, string> settings);
```

Since this was just added in 9.7.1 is there any advice on how to solve this? Based on our current deprecation guidelines we would need to deprecate the new APIs in the abstraction project.

cc: @mitchelsellers @bdukes

**Comment by mitchelsellers** [comment]
We are stil in RC - Let's get a fix in @valadas

**Comment by ahoefling** [comment]
Okay, I'll submit the PR in a few minutes. This isn't a lot of code to update

**Comment by ahoefling** [comment]
The PR was merged, I am going to close this issue
