### ISSUE TITLE
9.7.0 upgrade script does not fire when going from before 9.7.0 to 9.7.1

### ISSUE THREAD

**Issue by valadas** [dnnsoftware/Dnn.Platform#4075]
## Description of bug
When upgrading from earlier than 9.7.0 to 9.7.1, the config merge script for 9.7.0 does not fire. This is probably caused by the lack of a 09.07.00.SqlDataProvider because that version did not have sql changes.

### If you are doing a clean 9.7.1 install
No workaround needed, the normal install works fine.

### If you are upgrading from 9.7.0 to 9.7.1
Nothing special is needed, this upgrade path will work.

### If you are upgrading from any version before 9.7.0
- Unzip the upgrade zip and add an empty text file named `09.07.00.SqlDataProvider` in the `Providers\DataProviders\SqlDataProvider` folder.
- Continue the upgrade as usual

### If you have already upgraded to 9.7.1 before encountering this issue
- Find the web.config file that is located in the root folder of the installation.
- Create a copy of this file as a backup just in case.
- Open the original web.config file that is in the root files of the installation in any text editor.
- In the `<sectionGroup name="dotnetnuke">` section add the following line:
```xml
<section name="tokens" requirePermission="false" type="DotNetNuke.Framework.Providers.ProviderConfigurationHandler, DotNetNuke" />
```
- In the `<dotnetnuke>` section, add the following lines :
```xml
<tokens defaultProvider="CoreTokenProvider">
  <providers>
    <clear />
    <add name="CoreTokenProvider" type="DotNetNuke.Services.Tokens.CoreTokenProvider, DotNetNuke" />
  </providers>
</tokens>
```

### Additional information
Token replace providers are a recent feature (Dnn 9.7.0) and is probably not yet used by many 3rd party modules. But if you do see other configured providers for tokens, you may want to consult with the 3rd party module vendor for instructions on how to best merge this config with theirs.

## Affected version

* [ ] 10.00.00 alpha build
* [x] 09.07.01 release candidate
* [ ] 09.07.00 latest supported release

**Comment by david-poindexter** [comment]
Thank you for figuring this out and documenting the workaround @valadas 🎉

**Comment by valadas** [comment]
You are welcome, the PR is in too

**Comment by hismightiness** [comment]
Is there a test for this?  🤣

**Comment by mitchelsellers** [comment]
@hismightiness  This one is a bit sticky...it was the cause of a prior issue rather than an issue with actual 9.7.1 releases.

Upgrade testing scenarios should/would have caught it

**Comment by hismightiness** [comment]
Oh, I know.  I was giving David and Daniel a hard time based on a conversation we had from last night.  😉
