### ISSUE TITLE
ERROR:Could not find stored procedure dbo.AuthCookies_Update

### ISSUE THREAD

**Issue by kbratuysuz** [dnnsoftware/Dnn.Platform#4079]
Maybe its not an bug but Im trying to run DNN 9.4.1 from Visual Studio.

And Im gettin the following error;

**"progress":54,"details":"ERROR:Could not find stored procedure dbo.AuthCookies_Update"**

Firstly Ive created dnndev.me database and Ive checked and completed the permissions.

Ive created an app pool on iis named dnndev.me and Ive set the path like **...\Dnn.Platform-9.4.1\Website**

Ive checked the folder permissions.

After that Ive run the project from Visual Studio.

In the first step Ive filled Account Informations properly.

In the second step when creating stored procedures, dbo.AuthCookies_Update couldnt be created

![error](https://user-images.githubusercontent.com/42495278/92754902-fc7cc980-f393-11ea-8b0d-237ba0b45d1b.png)

The way Ive tried to solve the error but I couldnt success is;

Ive created a new database with the same name (dnndev.me) and the same permissions

Ive created an app pool with the same name and the same path with controling folder permissions

And I've commented the lines following on the Visual Studio

**( ...\Dnn.Platform-9.4.1\Website\Providers\DataProviders\SqlDataProvider --> 09.02.00.SqlProvider file)**

![1](https://user-images.githubusercontent.com/42495278/92754983-11f1f380-f394-11ea-95e7-e023d7ccf456.png)

Before running project on Visual Studio I've create that procedure on SSMS and it has been created successfully

![2](https://user-images.githubusercontent.com/42495278/92755025-1cac8880-f394-11ea-858f-854d4ef3e715.png)

Then when I run the project Ive got the same error and when I checked the database I couldnt see dbo.AuthCookies_Update on the Stored Procedure files

Ive checked out about this error, its a common error I guess.

**Comment by bdukes** [comment]
Please review the [Build documentation](https://github.com/dnnsoftware/Dnn.Platform/blob/develop/.github/BUILD.md), which details the steps to run the site locally from source.  The first step is running `build.ps1` from a PowerShell terminal.  This will ensure all of the pieces for the installation are in the right place.

Hope it helps!

**Comment by valadas** [comment]
Exactly, website folder in the source code is not meant for running the site, but rather a staging area for the build process. You should run `./build.ps1` on the root of the souce code to first generate a first build, then follow the link above to find the workflow that suits you depending on what workflow suits your need. I am closing this issue because it is not an actionable item from a development perspective, but rest assured you can keep commenting on the issue and we will still get notified and able to help if you encounter and issues with the documented build process.

**Comment by sleupold** [comment]
Please note:
To run DNN or even to develop extensions like modules or skins, you do not need to build DNN yourself. Instead you should use the install package and follow setup instructions.
