### ISSUE TITLE
Changing Module Friendly Name in package extention doesn't reflect new name in Add Module dialog

### ISSUE THREAD

**Issue by tauqeer-haider** [dnnsoftware/Dnn.Platform#4081]
## Description of bug
Changing Module Friendly Name through the "Extension" menu change it in Packages table but it doesn't reflect new name in Add Module menu when adding that module in page.

## Steps to reproduce
1. Go to Persona Bar > Settings > Extensions
2. Scroll to "Html" module and click "Edit" (pencil) icon 
3. Modify the Friendly Name and click "Save"
4. Create/edit a page
5. Click "Add Module" in edit bar at the bottom
6. "Add Module" dialog opens

## Current behavior
"Html" module still shows old friendly name. 

## Expected behavior
"Html" module should show modified friendly name

## Screenshots
If applicable, provide screenshots to help explain the bug.

## Error information
Provide any error information (console errors, error logs, etc.) related to this bug.

## Additional context
Provide any additional context that may be helpful in understanding and/or resolving the bug.

## Affected version

* [x] 10.00.00 alpha build
* [x] 09.07.02 release candidate
* [x] 09.07.01 latest supported release

## Affected browser

* [x] Chrome
* [x] Firefox
* [x] Safari
* [x] Internet Explorer 11
* [x] Microsoft Edge (Classic)
* [x] Microsoft Edge Chromium

**Comment by mitchelsellers** [comment]
Can you try to clear the cache, or restart the site.  Does it change then?

**Comment by tauqeer-haider** [comment]
> Can you try to clear the cache, or restart the site. Does it change then?

It doesn't. Raised a PR to fix this.
