### ISSUE TITLE
Create new interface for SerializaitonController for Dependency Injection

### ISSUE THREAD

**Issue by ahoefling** [dnnsoftware/Dnn.Platform#4086]
## Description of problem
The `SerializaitonController` should be an interface implementation and support dependency injection.

## Description of solution
Add support for dependency injection by creating an interface in the abstractions project and having the current `SerializationController` implement that interface.

## Description of alternatives considered
N/A

## Screenshots
N/A

## Additional context
N/A

## Affected browser
N/A

**Comment by thabaum** [comment]
I was putting around in this area trying to resolve issues like 
![image](https://user-images.githubusercontent.com/13577556/93273982-088ad180-f76e-11ea-872f-cd4a5c8155e6.png)

Says to use other so I try but no cigar, are these still in the works?  If I can learn what to do I can hunt this stuff down and clean it up as I go when I can.

Sorry to be a bit off topic I am trying to follow things a bit.

**Comment by ahoefling** [comment]
Can you create a discussion thread and we can discuss it there. This is off topic for the issue, but I do want to help 👍
