### ISSUE TITLE
Dependency Injection in WebForms

### ISSUE THREAD

**Issue by GerardSmit** [dnnsoftware/Dnn.Platform#4097]
## Description of problem
With the release of .NET Framework 4.7.2, Dependency Injection was introduced for WebForms. Since DNN targets .NET Framework 4.7.2 we can use this feature.

## Description of solution
Register a service provider in `HttpRuntime.WebObjectActivator` to enable Dependency Injection

## Additional context
See https://devblogs.microsoft.com/dotnet/announcing-the-net-framework-4-7-2/#asp-net-dependency-injection-in-webforms for more information about Dependency Injection in .NET Framework 4.7.2.

_This issue was created because I'm making a PR for this enhancement._

**Comment by bdukes** [comment]
If you're able to get this working, that'd be great.  I think @ahoefling ran into issues with the site failing when trying to use this feature.

**Comment by mitchelsellers** [comment]
Awesome! Looking forward to this!

**Comment by valadas** [comment]
@dnnsoftware/approvers This is done right, can we close it ?

**Comment by bdukes** [comment]
yes, this is merged into the release/10.0.0 branch
