### ISSUE TITLE
CKEditorProvider settings are not cleared on portal deletion

### ISSUE THREAD

**Issue by valadas** [dnnsoftware/Dnn.Platform#4099]
## Description of bug
Full detail here: https://dnntracker.atlassian.net/browse/DNN-8810 but wanted to log here for clarity

Originally open at https://github.com/DNN-Connect/CKEditorProvider/issues/71 by @mitchelsellers I am moving it here with the move of CKEditor to the main repository so we can track it here, I was able to reproduce with Dnn 9.7.1

## Steps to reproduce
List the precise steps to reproduce the bug:
1. Create a new portal and switch to it
2. Edit some HTML Editor settings and save
3. Switch to another portal and then delete the one created in step 1
4. Check the CKE_Settings table and notice all the settings for the deleted portal still exist.

## Current behavior
Table has leftover unused data that bloats it.

## Expected behavior
Deleting a portal should clear those now unused settings.

## Affected version

* [x] 10.00.00 alpha build
* [x] 09.07.02 release candidate
* [x] 09.07.01 latest supported release

**Comment by sleupold** [comment]
needs to be tested, wether it has been fixed by DNN-8810

**Comment by sleupold** [comment]
please assign this item to me

**Comment by sleupold** [comment]
Just for documentation:
CKE settings table in the database is using proprietary combined text key (instead of columns with FK referencing portals, tabs or modules, which could be used for cascading delete.

**Comment by sleupold** [comment]
still an issue
