### ISSUE TITLE
Update CKEditor version

### ISSUE THREAD

**Issue by valadas** [dnnsoftware/Dnn.Platform#4101]
Referencing https://github.com/DNN-Connect/CKEditorProvider/issues/87

This issue is about updating CKEditor version. Moving it here since we are merging https://github.com/DNN-Connect/CKEditorProvider in the main repository here.

I leave it to be triaged until we can discuss this more or someone picks up this task :)

**Comment by skamphuis** [comment]
I might have a need to contribute the upgrade of CK-editor to DNN. Does anyone have a rough idea of the effort involved? I don't need an exact number of hours, but are we talking about a day of work or will it be a week?

**Comment by bdukes** [comment]
I would hope it would be closer to a day of work

**Comment by sleupold** [comment]
Ingo used to do it frequently for his original provide., I assume, the bigger task would be finding out the necessary steps than actually executing them. A documentation would be very helpful for subsequent upgrades :)

**Comment by valadas** [comment]
@skamphuis It takes 7 hours 32 minutes and 10 seconds to replace... Just kidding

It is hard to know in the software world how much time it takes to do such thing, because, well doing it is the only way to know how much time it takes to do it. And if it was properly estimated, then it would be done already 😄 

That being said, I tend to guess it would be closer to a day or two than to a whole week.

**Comment by skamphuis** [comment]
Thanks guys, those where the kind of answers I was looking for.

**Comment by moorecreative** [comment]
@valadas I was thinking about the CK Editor just last night and how we needed to update it!

I never install a DNN instance without directly after, upgrading the CK Editor version to this one
        https://github.com/w8tcha/dnnckeditor
        CKEditor-Provider_02.01.27_Install_DNN93.zip
which is updated to CKEditor 4.12.1

Otherwise, with the default core, I have untold issues with code or formatting changes, etc.

For a start, could we see about just integrating this version in with the default?

@skamphuis in the meantime, you might want to check out this installer, it does the trick for most CKEditor issues that we run into.

**Comment by Timo-Breumelhof** [comment]
@moorecreative I don't think switching to the @w8tcha repo one is an option any more, we will have to upgrade this one.
FYI: We used to use Ingos version but stopped using it when he archived the project, but now we need one of the later CK options for a client.
The major difference between the should be the CkEditor itself.
It might be that the code cleanup configuration of Ingos version was less strict, but you can also change that the dnn-connect version and from a security point of view, having the editor strip unknown HTML by default is better IMO.

https://dnncommunity.org/blogs/Post/2841/Help-DNN-CKEditor-is-cleaning-my-HTML

Or do you think there are other differences?
