### ISSUE TITLE
CKEditor re-writes HTML when switching wysiwyg mode

### ISSUE THREAD

**Issue by valadas** [dnnsoftware/Dnn.Platform#4102]
## Description of problem
Moving https://github.com/DNN-Connect/CKEditorProvider/issues/102 here as we are moving this project here.

## Description of solution
I won't copy-past all the old discussion here but it is linked above.

## Steps to reproduce
1. In the html editor, enter `<a href="#"><div>Something</div></a>`
2. Save
3. Open the editor again and go to the souce
4. Notice the html content is now <div><a href="#">Something</a></div>`

## Description of alternatives considered
I know this was discussed a bit in various issues and meetings. One discussion was that by design CKEditor (not our provider but the actual CKEditor) is made so it won't allow html that you could not generate using the UI. This would be a security feature to prevent non admins to do things they are not allowed to do.

Other discussions in the above thread mention workaround configs to allow such usage.
This issue is moved here so we can discuss and take some decision on what to do. It may be related to upgrading CKEditor for proper html5 support maybe, see #4101

**Comment by in8dna** [comment]
This is still an issue. I'd like to know the setting to open the editor in source mode with RAW selected. Working in source and raw prevents the editor from deleting manually coded HTML styles, mobile formatting, etc.
