### ISSUE TITLE
Dashboard Functionality Removed - API's Not Updated

### ISSUE THREAD

**Issue by mitchelsellers** [dnnsoftware/Dnn.Platform#4114]
## Description of bug
When DNN Platform was migrated to using the Persona Bar, starting with version 9.0.0, the older Dashboard extension point was not brought forward.  

However, all of the dashboard API's, methods, and implementation remain part of the DNN API and could be used by developers with no real results 

## Steps to reproduce
Create a new Dashboard Extension and notice that it is not displayed anywhere.

## Current behavior
Developers can build a Dashboard Extension without any warnings, and the functionality will not work.

## Expected behavior
Developers should get a build warning and notice that the API's will be removed.

## Discussion Point
Traditionally, these API's would be something that should be flagged for removal in version 11.0.0 given the current version.  However, since this functionality is not working now, I would propose that we flag for removal in 10.0.0 to coincide with all other breaking changes already planned.  

## Affected version

* [x] 09.07.01 latest supported release

**Comment by valadas** [comment]
I agree with this special case and removing it in 10.

**Comment by mitchelsellers** [comment]
Just updating the history here, this was actually removed in 8.0.7
