### ISSUE TITLE
Current develop branch builds but won't install

### ISSUE THREAD

**Issue by valadas** [dnnsoftware/Dnn.Platform#4135]
## Description of bug
Current develop branch does build and test fine but when installing Dnn, there is a error related to no root node in xml file.

## Steps to reproduce
List the precise steps to reproduce the bug:
1. Build current develop branch using `.\build.ps1`.
2. Try to install using the produced install package.

## Current behavior
Install errors out with an error about not having an xml root node.

## Expected behavior
Should install fine.

## Additional context
I think I found the cause, an empty 09.07.03.config file that was committed in #4121 
I will test this theory and submit a PR shortly.

## Affected version

* [ ] 10.00.00 alpha build
* [x] 09.07.03 alpha build
* [ ] 09.07.02 latest supported release

**Comment by david-poindexter** [comment]
Great catch @valadas!  🎉
