### ISSUE TITLE
Renaming PortalSettings.PortalAlias.HTTPAlias to HttpAlias crashes VB extensions

### ISSUE THREAD

**Issue by Timo-Breumelhof** [dnnsoftware/Dnn.Platform#4138]
## Description of bug
VB Skin object breaks in DNN 9.7.2

## Steps to reproduce
List the precise steps to reproduce the bug:
1. Download and tnstall Style Helper or any other VB based extension that uses PortalSettings.PortalAlias.HTTPAlias
https://www.40fingers.net/Portals/0/Downloads/Releases/40Fingers-StyleHelper-02.15.00-SKO-Install.zip

2. Open the site, the extension crashes the site.
Works in 9.7.0 crashes in 9.7.2

## Current behavior
Error

## Expected behavior
No Error ;-)

## Error information

Error: 
'HttpAlias' is ambiguous because multiple kinds of members with this name exist in class 'DotNetNuke.Entities.Portals.PortalAliasInfo'.

IMO this is due to the fact that DNN now has both and VB cannot handle this obviously
PortalSettings.PortalAlias.HTTPAlias
and
PortalSettings.PortalAlias.HttpAlias

PR:
https://github.com/dnnsoftware/Dnn.Platform/pull/4021

Code:
https://github.com/dnnsoftware/Dnn.Platform/blob/bcf5fb7e912461b2f613e3c0e88226d7c1b8c938/DNN%20Platform/Library/Entities/Portals/PortalAliasInfo.cs#L41

## Additional context
AFAIK the only option around this is to either create a 9.7.2 specific version of the extension, or convert it to c#.
For the SH conversion to c# is on the backlog, but I didn't expect a change like this in a minor version TBH.
This should effect any other VB extension using the httpalias too IMO.

## Affected version

* [x] 09.07.02

**Comment by bdukes** [comment]
Ah, I see the issue.  Yup definitely a breaking change for VB, sorry we missed that!

**Comment by Timo-Breumelhof** [comment]
Tested in 09.08.00 RC1 and issue is fixed. Can one of you assign the 09.08.00 milestone to this issue? @valadas ?

**Comment by valadas** [comment]
It is not a big deal, but we have changed how we manage milestones.

We now use major, minor, path for issues and specific version numbers on pull requests. No issue with this change, but just setting expectations, we won't always come back to issues to mark in which version they where fixed, the pull request that closed it is now the reference to find out in which version it got fixed.
