### ISSUE TITLE
Column for note in IP filter

### ISSUE THREAD

**Issue by Tychodewaard** [dnnsoftware/Dnn.Platform#4140]
## Description of problem
If you add IP addresses to the IP filter you can not add a note why you added that IP. So, after a couple of months, there is a bunch of IP's and you have no idea if they are still needed. For instance an IP from someone's home address but they have moved. 

## Description of solution
When adding an IP address I'd like te add a note which will be visible in the IP filter list.

**Comment by jeremy-farrance** [comment]
As an active agency with a lot of projects, I would rate this as a VERY HIGH need and requirement. Thank you in advance to the person that adds this!!

**Comment by Tychodewaard** [comment]
@skamphuis : What does it cost if you would fix this one?

**Comment by Tychodewaard** [comment]
unstale
________________________________
Van: stale[bot] ***@***.***>
Verzonden: woensdag 2 juni 2021 19:05
Aan: dnnsoftware/Dnn.Platform ***@***.***>
CC: Tycho de Waard ***@***.***>; Author ***@***.***>
Onderwerp: Re: [dnnsoftware/Dnn.Platform] Column for note in IP filter (#4140)


We have detected this issue has not had any activity during the last 90 days. That could mean this issue is no longer relevant and/or nobody has found the necessary time to address the issue. We are trying to keep the list of open issues limited to those issues that are relevant to the majority and to close the ones that have become 'stale' (inactive). If no further activity is detected within the next 14 days, the issue will be closed automatically.
If new comments are are posted and/or a solution (pull request) is submitted for review that references this issue, the issue will not be closed. Closed issues can be reopened at any time in the future. Please remember those participating in this open source project are volunteers trying to help others and creating a better DNN Platform for all. Thank you for your continued involvement and contributions!

**Comment by Tychodewaard** [comment]
Waiting for estimate
________________________________
Van: stale[bot] ***@***.***>
Verzonden: vrijdag 3 september 2021 03:13
Aan: dnnsoftware/Dnn.Platform ***@***.***>
CC: Tycho de Waard ***@***.***>; Author ***@***.***>
Onderwerp: Re: [dnnsoftware/Dnn.Platform] Column for note in IP filter (#4140)


We have detected this issue has not had any activity during the last 90 days. That could mean this issue is no longer relevant and/or nobody has found the necessary time to address the issue. We are trying to keep the list of open issues limited to those issues that are relevant to the majority and to close the ones that have become 'stale' (inactive). If no further activity is detected within the next 14 days, the issue will be closed automatically.
If new comments are are posted and/or a solution (pull request) is submitted for review that references this issue, the issue will not be closed. Closed issues can be reopened at any time in the future. Please remember those participating in this open source project are volunteers trying to help others and creating a better DNN Platform for all. Thank you for your continued involvement and contributions!

**Comment by skamphuis** [comment]
Still relevant.

**Comment by Tychodewaard** [comment]
Still a great idea. Hope yo get a quote

Outlook voor iOS<https://aka.ms/o0ukef> downloaden
________________________________
Van: stale[bot] ***@***.***>
Verzonden: Wednesday, March 30, 2022 7:31:06 AM
Aan: dnnsoftware/Dnn.Platform ***@***.***>
CC: Tycho de Waard ***@***.***>; Author ***@***.***>
Onderwerp: Re: [dnnsoftware/Dnn.Platform] Column for note in IP filter (#4140)


Closed #4140<https://github.com/dnnsoftware/Dnn.Platform/issues/4140>.

**Comment by Tychodewaard** [comment]
@valadas Did you get a chance to take a look at this one?

**Comment by valadas** [comment]
Not yet but I pinned it higher up my open source priorities list, so I'll get to it soonish...

**Comment by valadas** [comment]
I'll handle this shortly, been kinda busy on the open-source side of things with the new resource manager...
