### ISSUE TITLE
Extension info not completed deleted on deletion of extension

### ISSUE THREAD

**Issue by EPTamminga** [dnnsoftware/Dnn.Platform#4146]
## Description of bug
Installed Language Pack as extension, deleted it (with file removal) and installed it again: it mentioned that I will do a repair, which is not corect

## Steps to reproduce
List the precise steps to reproduce the bug:
1. Go to Extension
2. Install a LP as an extension
3. Delete the LP extension with the removal of files
4. Install the same LP again

## Current behavior
It tells me in 4. that I am doing a repair

## Expected behavior
No repair, a normal install

## Screenshots

![image](https://user-images.githubusercontent.com/5859855/94996020-5bec8480-05a2-11eb-80db-f6fac9ed0485.png)

![image](https://user-images.githubusercontent.com/5859855/94996043-7de60700-05a2-11eb-99c7-daa763046138.png)

![image](https://user-images.githubusercontent.com/5859855/94996003-437c6a00-05a2-11eb-84c0-e12b45c0a64d.png)

## Error information
Provide any error information (console errors, error logs, etc.) related to this bug.

## Additional context
Provide any additional context that may be helpful in understanding and/or resolving the bug.

## Affected version

* [ ] 10.00.00 alpha build
* [x] 09.07.02 release candidate
* [ ] 09.07.01 latest supported release

## Affected browser

* [x] Chrome
* [x] Firefox
* [x] Safari
* [x] Internet Explorer 11
* [x] Microsoft Edge (Classic)
* [x] Microsoft Edge Chromium

**Comment by TopCat6** [comment]
I believe this is related to the dll files not being deleted because they are "in use" by w3wp.exe.
Please see my comments in these other posts:
[https://github.com/dnnsoftware/Dnn.Platform/issues/4205](https://github.com/dnnsoftware/Dnn.Platform/issues/4205)
[https://github.com/DNNCommunity/DNN.Blog/issues/174](https://github.com/DNNCommunity/DNN.Blog/issues/174)

**Comment by sleupold** [comment]
@TopCat6 
no, there are no .dll files in language packs.
Obviously, the package info or extension info is not properly deleted.

@EPTamminga 
have you been able to identify remaining records in any of the database metadata tables (Packages, Extensions) after deletion of the LP?

**Comment by TopCat6** [comment]
@sleupold Good point. However, I think I have traced the problem to a bug in the DNN Telerik Identifier module that I was using. It was holding file locks:
https://github.com/IowaComputerGurus/DnnTelerikIdentifier/releases/tag/V1.0.2

**Comment by sleupold** [comment]
@TopCat6 ,
I agree, that's a valid issue.
However, this item here is specifically about DNN Language Packs.

**Comment by TopCat6** [comment]
@sleupold Got it. DnnTelereikIdentifier should only be looking at .dll files. Presuming that is true, my point is not relevant.

**Comment by EPTamminga** [comment]
@sleupold I did not test it specifically for LP's. but I remember that the Delete Files option (in general) did not delete files as expected. I am not sure if this has been fixed,
