### ISSUE TITLE
Config is lowercased when save google analytics ID

### ISSUE THREAD

**Issue by ufoloko** [dnnsoftware/Dnn.Platform#4154]
I have saved google id in upper case 

![image](https://user-images.githubusercontent.com/1165122/95240796-891f7980-07d2-11eb-9e7a-b52047f09c42.png)

This should be rendered with siteanalytics.config file

Then i noticed, scripts are rendered but Google Analytics Id is changed to lowercase

![image](https://user-images.githubusercontent.com/1165122/95241143-fe8b4a00-07d2-11eb-9d45-29adf41e70e8.png)

This causes errors in google analytics code load, is not working

## Steps to reproduce
1.- Open Conectors, enable google analytics and place a value like  GT-0398HN3 in ID.
2.- Save the value
3.- Refresh site and open again Connectors, and edit google analytics
4.- You now can see gt-0398hn3, all in lower case

## Current behavior
Google Analytics Id, is saved in lowercase even if you place upper case values

## Expected behavior
Google Analytics Id should be saved in same lower or uppercase status.

* [X ] 09.04.01 latest supported release and future versions

* [X ] Chrome
* [ X] Firefox
* [ X] Safari
* [ X] Internet Explorer 11
* [ X] Microsoft Edge (Classic)
* [ X] Microsoft Edge Chromium

**Comment by sleupold** [comment]
Which exact DNN version are you using - latest ist DNN Platform 9.7.2

**Comment by ufoloko** [comment]
Sorry, version im using is 9.4.1

**Comment by sleupold** [comment]
I strongly suggest upgrading to DNN 9.7.2 - for safety of your DNN instance and for us to verify, the issue still exists.

**Comment by valadas** [comment]
I cannot reproduce in 9.7.2, please upgrade as this is probably already fixed. After upgrade you may need to resave the setting with the proper casing but other than that it looks already fixed.
