### ISSUE TITLE
Website with multiple aliases create infinite redirect loop on mobile

### ISSUE THREAD

**Issue by valadas** [dnnsoftware/Dnn.Platform#4157]
On a website with multiple aliases, navigating to the site in Chrome simulating a mobile device, we get an infinite redirect loop.

Thanks to @patrickryan79 I was able to reproduce the issue with the following steps.

Here you go @valadas.

Steps to reproduce in a local environment.

1. Edit hosts file and add two domains pointing to 127.0.0.1 (e.g. mobiletest.com, sub.mobiletest.com)
2. Setup site files and configure in IIS, adding the two bindings for mobiletest.com, sub.mobiletest.com
2. Install DNN (I used 9.7.2) by loading mobiletest.com
3. Add sub.mobiletest.com as portal alias
4. Leave all other settings as default
5. Using Chrome, test the second alias
6. With developer tools, trigger mobile view and reload

Worth mentioning here that there is no SSL certificate, no redirects, etc.

_Originally posted by @patrickryan79 in https://github.com/dnnsoftware/Dnn.Platform/discussions/4137#discussioncomment-91870_

Versions affected:
[x] 9.7.2
Maybe others ? did not try.

**Comment by patrickryan79** [comment]
Fantastic. You're a machine @valadas!

**Comment by valadas** [comment]
@patrickryan79 Clear steps to reproduce on current version is really the key here, so thank you for making that obvious. It often takes more time to make the bug happen then to identify why and implement a fix.
