### ISSUE TITLE
New Resource Manager: change folder permission

### ISSUE THREAD

**Issue by wbonekamp** [dnnsoftware/Dnn.Platform#4190]
In the old File Manager you had the right mouse option to change folder permissions

## Steps to reproduce
1. Go to resourcemanager (Site Assets);
2. Click on folder.

## Current behavior
You can't change folder permissions

## Expected behavior
Option to change folder permissions

## Affected version
* [ ] 09.08.00 release candidate

**Comment by valadas** [comment]
This is still possible, but differently:

1. Hover a folder
2. Click the pencil icon
3. It will expand the folder properties where both the folder info and it's permissions can be edited

![image](https://user-images.githubusercontent.com/6371568/96025316-efd01300-0e22-11eb-95e5-85e2f5bff6ff.png)

![image](https://user-images.githubusercontent.com/6371568/96025350-fc546b80-0e22-11eb-8e2d-4d4fe9c58e2a.png)


I am closing this issue, but if I misunderstood something, please comment and I'll be glad to reopen

**Comment by wbonekamp** [comment]
In my website it didn't show the icons, that;s why:

![image](https://user-images.githubusercontent.com/7567981/96092860-b8697100-0ecb-11eb-938f-918112c26bde.png)

**Comment by valadas** [comment]
Ha, that would explain it...

I see 3 possibilities for this:
1. There is something preventing serving SVG icons, you could check if there are any errors in the console maybe for that.
2. A custom theme is interfering with the Css, can you reproduce this issue using the default theme and container ?
3. This happens on some browser we did not test on, can you share that information on which browser this was tested on.

Thanks.

**Comment by valadas** [comment]
Also another thing that comes to mind would be custom site css or another module on the same page, if you can take a look at that to rule out possibilities.

**Comment by wbonekamp** [comment]
No other modules and default DNN skin Xcillion... maybe because it's localhost

**Comment by wbonekamp** [comment]
it's latest chrome

**Comment by wbonekamp** [comment]
yes problem is in localhost path 404

![image](https://user-images.githubusercontent.com/7567981/96094479-b1436280-0ecd-11eb-8673-364089d57652.png)

**Comment by wbonekamp** [comment]
you can close this issue. thanks!

**Comment by valadas** [comment]
Hmm, that matches my testing environment... Can you check in IIS for that site, in MimeTypes if you have SVG set to image/svg+xml like so:

![image](https://user-images.githubusercontent.com/6371568/96094582-85a78480-0e9b-11eb-988a-c78ad7061777.png)

**Comment by valadas** [comment]
The next thing that comes to mind is looking if those files are actually there by hovering the link in those broswer console lines, you should see a url and that should match the filesystem path on the site.

**Comment by wbonekamp** [comment]
website is http://localhost/dnn9

path is:

![image](https://user-images.githubusercontent.com/7567981/96094998-50685a00-0ece-11eb-975d-5d93e64fc7d0.png)

so the problem is in how I added the website entry in IIS

**Comment by valadas** [comment]
Oh, hmm, yeah, that is odd. in IIS you should either setup the site as localhost and then in Dnn create a child portal called dnn9. 

But I would recommend instead to use one local root domain for the installation like dnn9.localhost instead. You just have to edit c:\windows\system32\drivers\etc\HOST file and add a line like:
`dnn9.localtest   127.0.0.1`

Or even better, use https://www.nvquicksite.com/ which does it all for you, it's a really great tool to install Dnn quickly. it will take care of setting up the IIS site, the database and the HOST file all in one go and prepare the web.config in advance so when you get to the UI for installing Dnn in the browser it already knows where to find the database.

**Comment by bdukes** [comment]
I believe installing in a virtual directory is still a supported scenario (right, @mitchelsellers @donker?).

**Comment by valadas** [comment]
@bdukes I think so but I believe the HostHeader needs to be set in the web.config, there is a comment in there about it...
