### ISSUE TITLE
Implement Deterministic Builds and Code Signing

### ISSUE THREAD

**Issue by bdukes** [dnnsoftware/Dnn.Platform#4191]
Referencing https://github.com/dotnet-foundation/projects/issues/43, as a .NET Foundation, we need to implement [Deterministic Builds](https://github.com/clairernovotny/DeterministicBuilds) and [Code Signing](https://github.com/novotnyllc/CodeSigningDemo).

**Comment by mitchelsellers** [comment]
Yes, this is on my list to work with

**Comment by mitchelsellers** [comment]
I will get a PR in for this later this week!  Thanks @bdukes
