### ISSUE TITLE
Create multiple pages validation allow ">pagename" but no page created

### ISSUE THREAD

**Issue by tauqeer-haider** [dnnsoftware/Dnn.Platform#4196]
## Description of bug
When using Add Multiple Pages option, page name with ">" in it passes validation but no page is created.

## Steps to reproduce
1. Login as host user
2. Go to Persona Bar -> Content -> Pages
3. Click "Add Multiple Pages"
4. Enter page name with symbol ">" e.g, >page1
5. Click Validate Page(s)

## Current behavior
1 pages were validated message shown

## Expected behavior
Validation should fail and appropriate failure message shown.

## Screenshots
![image](https://user-images.githubusercontent.com/22594255/96145784-19596f00-0ef5-11eb-8e8e-62bb6fd343c3.png)
After clicking "Add Page(s)
![image](https://user-images.githubusercontent.com/22594255/96145952-46a61d00-0ef5-11eb-9f87-bc4202e6c797.png)

## Error information
Provide any error information (console errors, error logs, etc.) related to this bug.

## Additional context
Provide any additional context that may be helpful in understanding and/or resolving the bug.

## Affected version

* [x] 10.00.00 alpha build
* [x] 09.08.00 release candidate
* [x] 09.07.02 latest supported release

## Affected browser

* [x] Chrome
* [x] Firefox
* [x] Safari
* [x] Internet Explorer 11
* [x] Microsoft Edge (Classic)
* [x] Microsoft Edge Chromium

**Comment by valadas** [comment]
I believe it needs a parent page to then use > to create sub-pages relative to it.
