### ISSUE TITLE
9.8 Release Instructions - Troubleshoot sql script to enable interface uninstall of drepeciated.web dll

### ISSUE THREAD

**Issue by moorecreative** [dnnsoftware/Dnn.Platform#4199]
## Description of bug
Following the instructions in the release text, the user cannot uninstall the depreciated.web DLL because it is not enabled within the database for uninstalling
![image](https://user-images.githubusercontent.com/5497943/96198504-05c4fd00-0f23-11eb-872c-166892881aef.png)

## Steps to reproduce
I ran the script several times...

UPDATE {databaseOwner}{objectQualifier}Packages
SET IsSystemPackage = 0
WHERE Name IN ('DigitalAssetsManagement', 'DotNetNuke.Telerik.Web', 'DotNetNuke.Web.Deprecated', 'DotNetNuke.Website.Deprecated')

I was able to successfully uninstall the other depreciated.website dll and was able to uninstall the DigitalAssetManager, but I WAS NOT able to uninstall the depreciated.web dll (see screenshot above). Even though I've run the script, the trash icon does not appear next to the pencil icon for me.

## Screenshots
When I run sql to review the record in the DB:
WHERE Name IN ('DigitalAssetsManagement', 'DotNetNuke.Telerik.Web', 'DotNetNuke.Web.Deprecated', 'DotNetNuke.Website.Deprecated')
SELECT PackageID, PortalID, Name, FriendlyName,Description,IsSystemPackage FROM Packages WHERE Name IN ('DigitalAssetsManagement', 'DotNetNuke.Telerik.Web', 'DotNetNuke.Web.Deprecated', 'DotNetNuke.Website.Deprecated')

I can see that it is properly set to false
![image](https://user-images.githubusercontent.com/5497943/96199633-f5625180-0f25-11eb-97df-d96538ea5aa8.png)

however even after a full application restart, I do not have a trashcan icon.

## Affected version

* [ ] 10.00.00 alpha build
* [X] 09.08.00 release candidate
* [ ] 09.07.02 latest supported release

**Comment by moorecreative** [comment]
@valadas here are further notes after our SouthernFried DNN User Group conversation about this

**Comment by moorecreative** [comment]
I can obviously delete it manually in the db and in the bin folder, but I was trying to follow the steps exactly

**Comment by valadas** [comment]
Thanks for spotting that, I am looking into it right now

**Comment by mitchelsellers** [comment]
@moorecreative Have you used my Telerik Identifier module to see if you have anything with a dependency.

It seems like you might have a dependency holding you back

**Comment by valadas** [comment]
I have tried the sql script again as in the release notes and did not run into this issue...

**Comment by zyhfish** [comment]
You need to uninstall the package "Digital Assets Management" module first. if you still can't see the trash icon after the DAM module removed, please run the script "EXEC GetPackageDependencies" to check whether have other packages is dependent on it.

**Comment by valadas** [comment]
Oh, that might be it, the order of operations is important in those notes.

@moorecreative Please double-check that and let us know.

**Comment by allanedk** [comment]
I'm having similar issues with removing the "DNN Deprecated Web Controls Library"

I ran the GetPackageDependencies script and it seems that the HTML module (DNN_HTML) is dependent on the package. Is it safe to just manually remove the relevant record in the table "PackageDependencies"?

**Comment by mitchelsellers** [comment]
HTML shouldn’t. Was your site upgraded from an early version, say 7.3 or earlier.

**Comment by allanedk** [comment]
I didn't upgrade from 7 to 9.8, if that's what you mean. But years ago the site did run on dnn7 (and older).

Maybe it's a legacy record from "back in the days"?

**Comment by allanedk** [comment]
Update: I manually deleted the record in PackageDependencies and was able to remove "DNN Deprecated Web Controls Library" afterwards without issues.

**Comment by tpperlman** [comment]
I also upgraded to DNN v9.8 and am having the same problem with the DNN HTML Module v9.8.0 having a dependency on DotNetNuke.Web.Deprecated. My initial DNN install was v9.2.2 if that matters.

Here is what I get when running EXEC dbo.GetPackageDependencies:

![Screenshot 2020-11-13 110123](https://user-images.githubusercontent.com/1871915/99092786-9aad2b80-259f-11eb-8eea-c2262ad5807c.jpg)

I suppose I can manually remove the dependency, but would like further guidance before I do so to avoid issues on our production server.

**Comment by mitchelsellers** [comment]
This is very odd, and inconsistent across upgrades.

You are safe to manually remove the dependency.

**Comment by TopCat6** [comment]
Many people, including me, are having this issue. I think we should amend the script to cover this situation. See:
[https://dnncommunity.org/forums/aft/1529#5313](https://dnncommunity.org/forums/aft/1529#5313)

**Comment by mitchelsellers** [comment]
@TopCat6 I'm considering this, if the dependency is HTML module then it is safe.  if it isn't, then it might not be safe.

**Comment by TopCat6** [comment]
@mitchelsellers If it is the HTML module (111 in example above, 110 in my case), then that dependency should be removed by script, IMO. If not, then just leave dependency in place.
I think that would solve many situations, especially after people have run your [Dnn Telerik Identitier module](https://github.com/IowaComputerGurus/DnnTelerikIdentifier) and routed out all the independent 3rd party modules.

**Comment by mitchelsellers** [comment]
Yup - let me get a modified query whipped up that would handle this on a global basis

**Comment by valadas** [comment]
@david-poindexter is working on this now 😄

**Comment by valadas** [comment]
I think this is now resolved, if there is anything more to it, please comment and I'll be glad to reopen.

**Comment by david-poindexter** [comment]
Yes, the 9.8.0 release notes have been updated to be more clear and to account for this situation.  Thanks!
