### ISSUE TITLE
Search folders in new Resource Manager appears not work

### ISSUE THREAD

**Issue by david-poindexter** [dnnsoftware/Dnn.Platform#4200]
## Description of bug
The search folders feature in the new Resource Manager does not seem to work.

## Steps to reproduce
1. Install Resource Manager module
2. Place Resource Manager module on a page
3. Type something in the search field of the folders dropdown

## Current behavior
All folders disappear from view.

## Expected behavior
Resulting folders should match search term by name of folder.

### Before
![image](https://user-images.githubusercontent.com/4568451/96200907-33ad4000-0f29-11eb-94f3-a8e9c39df400.png)

### After
![image](https://user-images.githubusercontent.com/4568451/96200985-60f9ee00-0f29-11eb-8d30-1a32f00c6c4b.png)

## Error information
No errors displayed in dev tools console or Admin Logs.

## Additional context
n/a

## Affected version
* [ ] 10.00.00 alpha build
* [x] 09.08.00 release candidate
* [ ] 09.07.02 latest supported release

## Affected browser
* [x] Chrome
* [ ] Firefox
* [ ] Safari
* [ ] Internet Explorer 11
* [ ] Microsoft Edge (Classic)
* [ ] Microsoft Edge Chromium

**Comment by valadas** [comment]
Merged into release branch so was not closed automatically here
