### ISSUE TITLE
Dll files are not removed after upgrade

### ISSUE THREAD

**Issue by trouble2** [dnnsoftware/Dnn.Platform#4205]
## Description of bug
After upgrading to DNN 9.6.2 from a previous version (I think 9.3.1, or something like that) it seems a lot of dll files which are apparently not necesarry anymore are still in the bin folder. At first I didn't notice until after a while the pages-page didn't work anymore, which led me to: https://github.com/dnnsoftware/Dnn.AdminExperience/issues/1027
So this issue said I had to remove Dnn.PersonaBar.Pages.dll .
However when I compare a clean DNN 9.6.2 with my upgraded version I stil see a lot of Dnn.PersonaBar. ... . dll files are still present in the bin folder.
So I guess the cleanup process for the upgrades is not working properly in all cases

## Current behavior
Dll files are still presenr

## Expected behavior
Dll files should be removed

## Screenshots
![image](https://user-images.githubusercontent.com/1827559/96237672-e28b6380-0f9d-11eb-8e98-287807117492.png)
Upgraded to DNN9.6.2 - a lot of personabar dll files.

![image](https://user-images.githubusercontent.com/1827559/96237744-f59e3380-0f9d-11eb-9e31-01d605844062.png)
Clean DNN9.6.1 folder - just 3 personabar dll files

## Affected version
Can't really say...

## Affected browser
Not broswer specific

**Comment by mitchelsellers** [comment]
Did you follow the upgrade path recommended?  What exact prior version was this?  Can you post the install log?

**Comment by trouble2** [comment]
Here you go (changed the site to websitename.com):

08/03/2020 11:30:51 [INFO] DotNetNuke.Services.Upgrade.Upgrade Start UpgradeDNN:09.06.02
08/03/2020 11:30:51 [INFO] DotNetNuke.Services.Upgrade.Upgrade Start UpgradeVersion:C:\Inetpub\vhosts\websitename.com\httpdocs\Providers\DataProviders\SqlDataProvider\09.04.00.SqlDataProvider
08/03/2020 11:30:51 [INFO] DotNetNuke.Services.Upgrade.Upgrade Start ExecuteScript:C:\Inetpub\vhosts\websitename.com\httpdocs\Providers\DataProviders\SqlDataProvider\09.04.00.SqlDataProvider
08/03/2020 11:30:53 [INFO] DotNetNuke.Services.Upgrade.Upgrade End ExecuteScript:C:\Inetpub\vhosts\websitename.com\httpdocs\Providers\DataProviders\SqlDataProvider\09.04.00.SqlDataProvider
08/03/2020 11:30:53 [INFO] DotNetNuke.Services.Upgrade.Upgrade Start UpgradeVersion:C:\Inetpub\vhosts\websitename.com\httpdocs\Providers\DataProviders\SqlDataProvider\09.04.00.SqlDataProvider
08/03/2020 11:30:53 [INFO] DotNetNuke.Services.Upgrade.Upgrade Start UpgradeVersion:C:\Inetpub\vhosts\websitename.com\httpdocs\Providers\DataProviders\SqlDataProvider\09.04.01.SqlDataProvider
08/03/2020 11:30:53 [INFO] DotNetNuke.Services.Upgrade.Upgrade Start ExecuteScript:C:\Inetpub\vhosts\websitename.com\httpdocs\Providers\DataProviders\SqlDataProvider\09.04.01.SqlDataProvider
08/03/2020 11:30:53 [INFO] DotNetNuke.Services.Upgrade.Upgrade End ExecuteScript:C:\Inetpub\vhosts\websitename.com\httpdocs\Providers\DataProviders\SqlDataProvider\09.04.01.SqlDataProvider
08/03/2020 11:30:53 [INFO] DotNetNuke.Services.Upgrade.Upgrade Start UpgradeVersion:C:\Inetpub\vhosts\websitename.com\httpdocs\Providers\DataProviders\SqlDataProvider\09.04.01.SqlDataProvider
08/03/2020 11:30:53 [INFO] DotNetNuke.Services.Upgrade.Upgrade Start UpgradeVersion:C:\Inetpub\vhosts\websitename.com\httpdocs\Providers\DataProviders\SqlDataProvider\09.04.02.SqlDataProvider
08/03/2020 11:30:53 [INFO] DotNetNuke.Services.Upgrade.Upgrade Start ExecuteScript:C:\Inetpub\vhosts\websitename.com\httpdocs\Providers\DataProviders\SqlDataProvider\09.04.02.SqlDataProvider
08/03/2020 11:30:53 [INFO] DotNetNuke.Services.Upgrade.Upgrade End ExecuteScript:C:\Inetpub\vhosts\websitename.com\httpdocs\Providers\DataProviders\SqlDataProvider\09.04.02.SqlDataProvider
08/03/2020 11:30:53 [INFO] DotNetNuke.Services.Upgrade.Upgrade Start UpgradeVersion:C:\Inetpub\vhosts\websitename.com\httpdocs\Providers\DataProviders\SqlDataProvider\09.04.02.SqlDataProvider
08/03/2020 11:30:53 [INFO] DotNetNuke.Services.Upgrade.Upgrade Start UpgradeVersion:C:\Inetpub\vhosts\websitename.com\httpdocs\Providers\DataProviders\SqlDataProvider\09.04.03.SqlDataProvider
08/03/2020 11:30:53 [INFO] DotNetNuke.Services.Upgrade.Upgrade Start ExecuteScript:C:\Inetpub\vhosts\websitename.com\httpdocs\Providers\DataProviders\SqlDataProvider\09.04.03.SqlDataProvider
08/03/2020 11:30:53 [INFO] DotNetNuke.Services.Upgrade.Upgrade End ExecuteScript:C:\Inetpub\vhosts\websitename.com\httpdocs\Providers\DataProviders\SqlDataProvider\09.04.03.SqlDataProvider
08/03/2020 11:30:53 [INFO] DotNetNuke.Services.Upgrade.Upgrade Start UpgradeVersion:C:\Inetpub\vhosts\websitename.com\httpdocs\Providers\DataProviders\SqlDataProvider\09.04.03.SqlDataProvider
08/03/2020 11:30:53 [INFO] DotNetNuke.Services.Upgrade.Upgrade Start UpgradeVersion:C:\Inetpub\vhosts\websitename.com\httpdocs\Providers\DataProviders\SqlDataProvider\09.04.04.SqlDataProvider
08/03/2020 11:30:53 [INFO] DotNetNuke.Services.Upgrade.Upgrade Start ExecuteScript:C:\Inetpub\vhosts\websitename.com\httpdocs\Providers\DataProviders\SqlDataProvider\09.04.04.SqlDataProvider
08/03/2020 11:30:53 [INFO] DotNetNuke.Services.Upgrade.Upgrade End ExecuteScript:C:\Inetpub\vhosts\websitename.com\httpdocs\Providers\DataProviders\SqlDataProvider\09.04.04.SqlDataProvider
08/03/2020 11:30:53 [INFO] DotNetNuke.Services.Upgrade.Upgrade Start UpgradeVersion:C:\Inetpub\vhosts\websitename.com\httpdocs\Providers\DataProviders\SqlDataProvider\09.04.04.SqlDataProvider
08/03/2020 11:30:53 [INFO] DotNetNuke.Services.Upgrade.Upgrade Start UpgradeVersion:C:\Inetpub\vhosts\websitename.com\httpdocs\Providers\DataProviders\SqlDataProvider\09.05.00.SqlDataProvider
08/03/2020 11:30:53 [INFO] DotNetNuke.Services.Upgrade.Upgrade Start ExecuteScript:C:\Inetpub\vhosts\websitename.com\httpdocs\Providers\DataProviders\SqlDataProvider\09.05.00.SqlDataProvider
08/03/2020 11:30:53 [INFO] DotNetNuke.Services.Upgrade.Upgrade End ExecuteScript:C:\Inetpub\vhosts\websitename.com\httpdocs\Providers\DataProviders\SqlDataProvider\09.05.00.SqlDataProvider
08/03/2020 11:30:53 [INFO] DotNetNuke.Services.Upgrade.Upgrade Start UpgradeVersion:C:\Inetpub\vhosts\websitename.com\httpdocs\Providers\DataProviders\SqlDataProvider\09.05.00.SqlDataProvider
08/03/2020 11:30:53 [INFO] DotNetNuke.Services.Upgrade.Upgrade Start UpgradeVersion:C:\Inetpub\vhosts\websitename.com\httpdocs\Providers\DataProviders\SqlDataProvider\09.05.01.SqlDataProvider
08/03/2020 11:30:53 [INFO] DotNetNuke.Services.Upgrade.Upgrade Start ExecuteScript:C:\Inetpub\vhosts\websitename.com\httpdocs\Providers\DataProviders\SqlDataProvider\09.05.01.SqlDataProvider
08/03/2020 11:30:54 [INFO] DotNetNuke.Services.Upgrade.Upgrade End ExecuteScript:C:\Inetpub\vhosts\websitename.com\httpdocs\Providers\DataProviders\SqlDataProvider\09.05.01.SqlDataProvider
08/03/2020 11:30:54 [INFO] DotNetNuke.Services.Upgrade.Upgrade Start UpgradeVersion:C:\Inetpub\vhosts\websitename.com\httpdocs\Providers\DataProviders\SqlDataProvider\09.05.01.SqlDataProvider
08/03/2020 11:30:54 [INFO] DotNetNuke.Services.Upgrade.Upgrade Start UpgradeVersion:C:\Inetpub\vhosts\websitename.com\httpdocs\Providers\DataProviders\SqlDataProvider\09.06.00.SqlDataProvider
08/03/2020 11:30:54 [INFO] DotNetNuke.Services.Upgrade.Upgrade Start ExecuteScript:C:\Inetpub\vhosts\websitename.com\httpdocs\Providers\DataProviders\SqlDataProvider\09.06.00.SqlDataProvider
08/03/2020 11:30:54 [INFO] DotNetNuke.Services.Upgrade.Upgrade End ExecuteScript:C:\Inetpub\vhosts\websitename.com\httpdocs\Providers\DataProviders\SqlDataProvider\09.06.00.SqlDataProvider
08/03/2020 11:30:54 [INFO] DotNetNuke.Services.Upgrade.Upgrade Start UpgradeVersion:C:\Inetpub\vhosts\websitename.com\httpdocs\Providers\DataProviders\SqlDataProvider\09.06.00.SqlDataProvider
08/03/2020 11:30:54 [INFO] DotNetNuke.Services.Upgrade.Upgrade Start UpgradeVersion:C:\Inetpub\vhosts\websitename.com\httpdocs\Providers\DataProviders\SqlDataProvider\09.06.02.SqlDataProvider
08/03/2020 11:30:54 [INFO] DotNetNuke.Services.Upgrade.Upgrade Start ExecuteScript:C:\Inetpub\vhosts\websitename.com\httpdocs\Providers\DataProviders\SqlDataProvider\09.06.02.SqlDataProvider
08/03/2020 11:30:55 [INFO] DotNetNuke.Services.Upgrade.Upgrade End ExecuteScript:C:\Inetpub\vhosts\websitename.com\httpdocs\Providers\DataProviders\SqlDataProvider\09.06.02.SqlDataProvider
08/03/2020 11:30:55 [INFO] DotNetNuke.Services.Upgrade.Upgrade Start UpgradeVersion:C:\Inetpub\vhosts\websitename.com\httpdocs\Providers\DataProviders\SqlDataProvider\09.06.02.SqlDataProvider
08/03/2020 11:30:55 [INFO] DotNetNuke.Services.Upgrade.Upgrade Start Application Upgrades: 9.4.0
08/03/2020 11:30:55 [INFO] DotNetNuke.Services.Upgrade.Upgrade Start Application Upgrades: 9.4.1
08/03/2020 11:30:55 [INFO] DotNetNuke.Services.Upgrade.Upgrade Start Application Upgrades: 9.4.2
08/03/2020 11:30:55 [INFO] DotNetNuke.Services.Upgrade.Upgrade Start Application Upgrades: 9.4.3
08/03/2020 11:30:55 [INFO] DotNetNuke.Services.Upgrade.Upgrade Start Application Upgrades: 9.4.4
08/03/2020 11:30:55 [INFO] DotNetNuke.Services.Upgrade.Upgrade Start Application Upgrades: 9.5.0
08/03/2020 11:30:55 [INFO] DotNetNuke.Services.Upgrade.Upgrade Start Application Upgrades: 9.5.1
08/03/2020 11:30:55 [INFO] DotNetNuke.Services.Upgrade.Upgrade Start Application Upgrades: 9.6.0
08/03/2020 11:30:55 [INFO] DotNetNuke.Services.Upgrade.Upgrade Start Application Upgrades: 9.6.2
08/03/2020 11:30:55 [INFO] DotNetNuke.Services.Upgrade.Upgrade Start DeleteFiles:09.04.00
08/03/2020 11:30:55 [INFO] DotNetNuke.Services.Upgrade.Upgrade Start DeleteFiles:09.04.01
08/03/2020 11:30:55 [INFO] DotNetNuke.Services.Upgrade.Upgrade Start DeleteFiles:09.04.02
08/03/2020 11:30:55 [INFO] DotNetNuke.Services.Upgrade.Upgrade Start DeleteFiles:09.04.03
08/03/2020 11:30:55 [INFO] DotNetNuke.Services.Upgrade.Upgrade Start DeleteFiles:09.04.04
08/03/2020 11:30:55 [INFO] DotNetNuke.Services.Upgrade.Upgrade Start DeleteFiles:09.05.00
08/03/2020 11:30:55 [INFO] DotNetNuke.Services.Upgrade.Upgrade Start DeleteFiles:09.05.01
08/03/2020 11:30:55 [INFO] DotNetNuke.Services.Upgrade.Upgrade Start DeleteFiles:09.06.00
08/03/2020 11:30:55 [INFO] DotNetNuke.Services.Upgrade.Upgrade Start DeleteFiles:09.06.02
08/03/2020 11:30:55 [INFO] DotNetNuke.Services.Upgrade.Upgrade Start UpdateConfig:09.04.00
08/03/2020 11:30:55 [INFO] DotNetNuke.Services.Upgrade.Upgrade Start UpdateConfig:9.4.0
08/03/2020 11:30:55 [INFO] DotNetNuke.Services.Installer.XmlMerge Start UpdateAttribute:attributeName=targetFramework
08/03/2020 11:30:55 [INFO] DotNetNuke.Services.Installer.XmlMerge Start UpdateAttribute:attributeName=targetFramework
08/03/2020 11:30:55 [INFO] DotNetNuke.Services.Upgrade.Upgrade End UpdateConfig:9.4.0
08/03/2020 11:30:55 [INFO] DotNetNuke.Services.Upgrade.Upgrade End UpdateConfig:09.04.00
08/03/2020 11:30:55 [INFO] DotNetNuke.Services.Upgrade.Upgrade Start UpdateConfig:09.04.01
08/03/2020 11:30:55 [INFO] DotNetNuke.Services.Upgrade.Upgrade Start UpdateConfig:9.4.1
08/03/2020 11:30:55 [INFO] DotNetNuke.Services.Upgrade.Upgrade End UpdateConfig:9.4.1
08/03/2020 11:30:55 [INFO] DotNetNuke.Services.Upgrade.Upgrade End UpdateConfig:09.04.01
08/03/2020 11:30:55 [INFO] DotNetNuke.Services.Upgrade.Upgrade Start UpdateConfig:09.04.02
08/03/2020 11:30:55 [INFO] DotNetNuke.Services.Upgrade.Upgrade Start UpdateConfig:9.4.2
08/03/2020 11:30:55 [INFO] DotNetNuke.Services.Upgrade.Upgrade End UpdateConfig:9.4.2
08/03/2020 11:30:55 [INFO] DotNetNuke.Services.Upgrade.Upgrade End UpdateConfig:09.04.02
08/03/2020 11:30:55 [INFO] DotNetNuke.Services.Upgrade.Upgrade Start UpdateConfig:09.04.03
08/03/2020 11:30:55 [INFO] DotNetNuke.Services.Upgrade.Upgrade Start UpdateConfig:9.4.3
08/03/2020 11:30:55 [INFO] DotNetNuke.Services.Upgrade.Upgrade End UpdateConfig:9.4.3
08/03/2020 11:30:55 [INFO] DotNetNuke.Services.Upgrade.Upgrade End UpdateConfig:09.04.03
08/03/2020 11:30:55 [INFO] DotNetNuke.Services.Upgrade.Upgrade Start UpdateConfig:09.04.04
08/03/2020 11:30:55 [INFO] DotNetNuke.Services.Upgrade.Upgrade Start UpdateConfig:9.4.4
08/03/2020 11:30:55 [INFO] DotNetNuke.Services.Upgrade.Upgrade End UpdateConfig:9.4.4
08/03/2020 11:30:55 [INFO] DotNetNuke.Services.Upgrade.Upgrade End UpdateConfig:09.04.04
08/03/2020 11:30:55 [INFO] DotNetNuke.Services.Upgrade.Upgrade Start UpdateConfig:09.05.00
08/03/2020 11:30:55 [INFO] DotNetNuke.Services.Upgrade.Upgrade Start UpdateConfig:9.5.0
08/03/2020 11:30:55 [INFO] DotNetNuke.Services.Installer.XmlMerge Start RemoveNode:
08/03/2020 11:30:55 [INFO] DotNetNuke.Services.Installer.XmlMerge Start RemoveNode:
08/03/2020 11:30:55 [INFO] DotNetNuke.Services.Installer.XmlMerge Start UpdateNode: keyAttribute=key
08/03/2020 11:30:55 [INFO] DotNetNuke.Services.Upgrade.Upgrade End UpdateConfig:9.5.0
08/03/2020 11:30:55 [INFO] DotNetNuke.Services.Upgrade.Upgrade End UpdateConfig:09.05.00
08/03/2020 11:30:55 [INFO] DotNetNuke.Services.Upgrade.Upgrade Start UpdateConfig:09.05.01
08/03/2020 11:30:55 [INFO] DotNetNuke.Services.Upgrade.Upgrade Start UpdateConfig:9.5.1
08/03/2020 11:30:55 [INFO] DotNetNuke.Services.Upgrade.Upgrade End UpdateConfig:9.5.1
08/03/2020 11:30:55 [INFO] DotNetNuke.Services.Upgrade.Upgrade End UpdateConfig:09.05.01
08/03/2020 11:30:55 [INFO] DotNetNuke.Services.Upgrade.Upgrade Start UpdateConfig:09.06.00
08/03/2020 11:30:55 [INFO] DotNetNuke.Services.Upgrade.Upgrade Start UpdateConfig:9.6.0
08/03/2020 11:30:55 [INFO] DotNetNuke.Services.Installer.XmlMerge Start RemoveNode:
08/03/2020 11:30:55 [INFO] DotNetNuke.Services.Installer.XmlMerge Start UpdateNode: keyAttribute=key
08/03/2020 11:30:55 [INFO] DotNetNuke.Services.Upgrade.Upgrade End UpdateConfig:9.6.0
08/03/2020 11:30:55 [INFO] DotNetNuke.Services.Upgrade.Upgrade End UpdateConfig:09.06.00
08/03/2020 11:30:55 [INFO] DotNetNuke.Services.Upgrade.Upgrade Start UpdateConfig:09.06.02
08/03/2020 11:30:55 [INFO] DotNetNuke.Services.Upgrade.Upgrade Start UpdateConfig:9.6.2
08/03/2020 11:30:55 [INFO] DotNetNuke.Services.Installer.XmlMerge Start UpdateNode: keyAttribute=fileExtension
08/03/2020 11:30:55 [INFO] DotNetNuke.Services.Upgrade.Upgrade End UpdateConfig:9.6.2
08/03/2020 11:30:55 [INFO] DotNetNuke.Services.Upgrade.Upgrade End UpdateConfig:09.06.02
08/03/2020 11:30:55 [INFO] DotNetNuke.Services.Upgrade.Upgrade Performing General Upgrades
08/03/2020 11:30:56 [INFO] DotNetNuke.Services.Upgrade.Upgrade Start InstallPackage:C:\Inetpub\vhosts\websitename.com\httpdocs\Install\Library\DNNCE_Web.Deprecated_09.06.02_Install.zip
08/03/2020 11:30:57 [INFO] DotNetNuke.Services.Upgrade.Upgrade Start InstallPackage:C:\Inetpub\vhosts\websitename.com\httpdocs\Install\Library\DNNCE_Website.Deprecated_09.06.02_Install.zip
08/03/2020 11:30:57 [INFO] DotNetNuke.Services.Upgrade.Upgrade Start InstallPackage:C:\Inetpub\vhosts\websitename.com\httpdocs\Install\Module\Dnn.EditBar.UI_09.06.02_Install.zip
08/03/2020 11:30:57 [INFO] DotNetNuke.Services.Installer.XmlMerge Start RemoveNode:
08/03/2020 11:30:57 [INFO] DotNetNuke.Services.Installer.XmlMerge Start UpdateNode: keyAttribute=name
08/03/2020 11:30:58 [INFO] DotNetNuke.Services.Upgrade.Upgrade Start InstallPackage:C:\Inetpub\vhosts\websitename.com\httpdocs\Install\Module\DDRMenu_09.06.02_Install.zip
08/03/2020 11:30:59 [INFO] DotNetNuke.Services.Installer.XmlMerge Start UpdateNode: keyAttribute=name
08/03/2020 11:30:59 [INFO] DotNetNuke.Services.Upgrade.Upgrade Start InstallPackage:C:\Inetpub\vhosts\websitename.com\httpdocs\Install\Module\Dnn.PersonaBar.UI_09.06.02_Install.zip
08/03/2020 11:31:01 [INFO] DotNetNuke.Services.Installer.XmlMerge Start RemoveNode:
08/03/2020 11:31:01 [INFO] DotNetNuke.Services.Installer.XmlMerge Start AddNode:
08/03/2020 11:31:01 [INFO] DotNetNuke.Services.Installer.XmlMerge Start RemoveNode:
08/03/2020 11:31:01 [INFO] DotNetNuke.Services.Installer.XmlMerge Start AddNode:
08/03/2020 11:31:01 [INFO] DotNetNuke.Services.Installer.XmlMerge Start RemoveNode:
08/03/2020 11:31:01 [INFO] DotNetNuke.Services.Installer.XmlMerge Start AddNode:
08/03/2020 11:31:01 [INFO] DotNetNuke.Services.Installer.XmlMerge Start RemoveNode:
08/03/2020 11:31:01 [INFO] DotNetNuke.Services.Installer.XmlMerge Start AddNode:
08/03/2020 11:31:01 [INFO] DotNetNuke.Services.Installer.XmlMerge Start RemoveNode:
08/03/2020 11:31:01 [INFO] DotNetNuke.Services.Installer.XmlMerge Start UpdateNode: keyAttribute=name
08/03/2020 11:31:01 [INFO] DotNetNuke.Services.Upgrade.Upgrade Start InstallPackage:C:\Inetpub\vhosts\websitename.com\httpdocs\Install\Module\DNNCE_AzureConnector_09.06.02_Install.zip
08/03/2020 11:31:02 [INFO] DotNetNuke.Services.Upgrade.Upgrade Start InstallPackage:C:\Inetpub\vhosts\websitename.com\httpdocs\Install\Module\DNNCE_Console_09.06.02_Install.zip
08/03/2020 11:31:02 [INFO] DotNetNuke.Services.Upgrade.Upgrade Start InstallPackage:C:\Inetpub\vhosts\websitename.com\httpdocs\Install\Module\DNNCE_CoreMessaging_09.06.02_Install.zip
08/03/2020 11:31:02 [INFO] DotNetNuke.Services.Upgrade.Upgrade Start InstallPackage:C:\Inetpub\vhosts\websitename.com\httpdocs\Install\Module\DNNCE_HtmlEditorManager_09.06.02_Install.zip
08/03/2020 11:31:03 [INFO] DotNetNuke.Services.Upgrade.Upgrade Start InstallPackage:C:\Inetpub\vhosts\websitename.com\httpdocs\Install\Module\DNNCE_Journal_09.06.02_Install.zip
08/03/2020 11:31:04 [INFO] DotNetNuke.Services.Upgrade.Upgrade Start InstallPackage:C:\Inetpub\vhosts\websitename.com\httpdocs\Install\Module\DNNCE_MemberDirectory_09.06.02_Install.zip
08/03/2020 11:31:05 [INFO] DotNetNuke.Services.Upgrade.Upgrade Start InstallPackage:C:\Inetpub\vhosts\websitename.com\httpdocs\Install\Module\DNNCE_ModuleCreator_09.06.02_Install.zip
08/03/2020 11:31:06 [INFO] DotNetNuke.Services.Upgrade.Upgrade Start InstallPackage:C:\Inetpub\vhosts\websitename.com\httpdocs\Install\Module\DNNCE_RazorHost_09.06.02_Install.zip
08/03/2020 11:31:07 [INFO] DotNetNuke.Services.Upgrade.Upgrade Start InstallPackage:C:\Inetpub\vhosts\websitename.com\httpdocs\Install\Module\DNNCE_SiteExportImport_09.06.02_Install.zip
08/03/2020 11:31:07 [INFO] DotNetNuke.Services.Upgrade.Upgrade Start InstallPackage:C:\Inetpub\vhosts\websitename.com\httpdocs\Install\Module\DNNCE_SocialGroups_09.06.02_Install.zip
08/03/2020 11:31:08 [INFO] DotNetNuke.Services.Upgrade.Upgrade Start InstallPackage:C:\Inetpub\vhosts\websitename.com\httpdocs\Install\Module\GoogleAnalyticsConnector_09.06.02_Install.zip
08/03/2020 11:31:08 [INFO] DotNetNuke.Services.Upgrade.Upgrade Start InstallPackage:C:\Inetpub\vhosts\websitename.com\httpdocs\Install\Module\Telerik_09.06.02_Install.zip
08/03/2020 11:31:17 [INFO] DotNetNuke.Services.Upgrade.Upgrade Start InstallPackage:C:\Inetpub\vhosts\websitename.com\httpdocs\Install\Skin\Skin_Xcillion_09.06.02_Install.zip
08/03/2020 11:31:17 [INFO] DotNetNuke.Services.Upgrade.Upgrade Start InstallPackage:C:\Inetpub\vhosts\websitename.com\httpdocs\Install\JavaScriptLibrary\jQuery_03.05.01_Install.zip
08/03/2020 11:31:18 [INFO] DotNetNuke.Services.Upgrade.Upgrade Start InstallPackage:C:\Inetpub\vhosts\websitename.com\httpdocs\Install\JavaScriptLibrary\Knockout_03.03.00_Install.zip
08/03/2020 11:31:18 [INFO] DotNetNuke.Services.Upgrade.Upgrade Start InstallPackage:C:\Inetpub\vhosts\websitename.com\httpdocs\Install\JavaScriptLibrary\Selectize_00.12.06_Install.zip
08/03/2020 11:31:18 [INFO] DotNetNuke.Services.Upgrade.Upgrade Start InstallPackage:C:\Inetpub\vhosts\websitename.com\httpdocs\Install\Provider\AspNetClientCapabilityProvider_09.06.02_Install.zip
08/03/2020 11:31:18 [INFO] DotNetNuke.Services.Installer.XmlMerge Start UpdateNode: keyAttribute=name
08/03/2020 11:31:18 [INFO] DotNetNuke.Services.Installer.XmlMerge Start UpdateNode: keyAttribute=name
08/03/2020 11:31:18 [INFO] DotNetNuke.Services.Upgrade.Upgrade Start InstallPackage:C:\Inetpub\vhosts\websitename.com\httpdocs\Install\Provider\DNN_SimpleWebFarmCachingProvider_09.06.02_Install.zip
08/03/2020 11:31:18 [INFO] DotNetNuke.Services.Installer.XmlMerge Start UpdateNode: keyAttribute=name
08/03/2020 11:31:18 [INFO] DotNetNuke.Services.Installer.XmlMerge Start UpdateNode: keyAttribute=name
08/03/2020 11:31:18 [INFO] DotNetNuke.Services.Upgrade.Upgrade Start InstallPackage:C:\Inetpub\vhosts\websitename.com\httpdocs\Install\Provider\DNNCE_FolderProviders_09.06.02_Install.zip
08/03/2020 11:31:19 [INFO] DotNetNuke.Services.Installer.XmlMerge Start UpdateNode: keyAttribute=name
08/03/2020 11:31:19 [INFO] DotNetNuke.Services.Upgrade.Upgrade Start InstallPackage:C:\Inetpub\vhosts\websitename.com\httpdocs\Install\Provider\DNNConnect.CKEditorProvider_01.01.00_Install.zip
08/03/2020 11:31:30 [INFO] DotNetNuke.Services.Installer.XmlMerge Start UpdateNode: keyAttribute=name
08/03/2020 11:31:33 [INFO] DotNetNuke.Services.Upgrade.Upgrade Start InstallPackage:C:\Inetpub\vhosts\websitename.com\httpdocs\Install\Module\Dnn.PersonaBar.Extensions_09.06.02_Install.zip
08/03/2020 11:31:38 [INFO] DotNetNuke.Services.Upgrade.Upgrade Start InstallPackage:C:\Inetpub\vhosts\websitename.com\httpdocs\Install\Module\DNNCE_DigitalAssetsManagement_09.06.02_Install.zip
08/03/2020 11:31:39 [INFO] DotNetNuke.Services.Upgrade.Upgrade Start InstallPackage:C:\Inetpub\vhosts\websitename.com\httpdocs\Install\Module\DNNCE_HTML_09.06.02_Install.zip
08/03/2020 11:31:40 [INFO] DotNetNuke.Services.Upgrade.Upgrade Start InstallPackage:C:\Inetpub\vhosts\websitename.com\httpdocs\Install\JavaScriptLibrary\jQueryMigrate_03.02.00_Install.zip

**Comment by TopCat6** [comment]
I am having the same problem on all servers when updating to a new module version.
The problem seems to be that w3svc has the dll inuse and it cannot be deleted. If I try and delete the module, like Blog, the DotNetNuke.Modules.Blog.dll file is left behind. If I try to delete it through Windows Explorer I get the error:

> The action cannot be completed because the file is open in w3wp.exe.

If I stop SQL Server and World Wide Publishing (w3svc), I am able to delete the dll.

This is also happening on other modules, ever since upgrading to DNN 9.8.0
See:  [https://github.com/DNNCommunity/DNN.Blog/issues/174](https://github.com/DNNCommunity/DNN.Blog/issues/174)

**Comment by sleupold** [comment]
@TopCat6 
you don't need to stop SQL Server or shut down IIS, recycling the Application pool hosting your website should be sufficient to free  any .dll files used by it.

**Comment by TopCat6** [comment]
@sleupold Thanks, should work. However, I think I have traced the problem to a bug in the DNN Telerik Identifier module that I was using. It was holding file locks:
https://github.com/IowaComputerGurus/DnnTelerikIdentifier/releases/tag/V1.0.2

**Comment by sleupold** [comment]
@TopCat6,

**Comment by sleupold** [comment]
@TopCat6 ,
thank you for your reply. 
if @trouble2 agrees, this issue might be closed.

**Comment by trouble2** [comment]
Here we go Sebastian

**Comment by sleupold** [comment]
@trouble2 
Thank you!
