### ISSUE TITLE
IPortalSettings lacking UserMode

### ISSUE THREAD

**Issue by valadas** [dnnsoftware/Dnn.Platform#4213]
While trying to resolve build warnings on DotNetNuke.Common.Globals, I found the method IsEditMode() had a warning about using the deprecated PortalController.Instance.GetCurrentPortalSettings and replaced it with .GetCurrentSettings which returns an IPortalSettings instead of a PortalSettings object.

IPortalSettings is lacking a UserMode property that PortalSettings had.

Should we :
🅰️ Add UserMode to the interface ?
🅱️ Deprecated UserMode in PortalSettings with some suggestion on how to do it the new way ?

Paging @bdukes @ahoefling

**Comment by valadas** [comment]
Oh, and same issue with PortalSettings.ActiveTab too

**Comment by bdukes** [comment]
I think `ActiveTab` should be replaced by `TabController.CurrentPage`.  I'm not familiar with `UserMode`, though.  Adding it to the interface is a breaking change, though.

**Comment by valadas** [comment]
UserMode is for if the user is currently in View or Edit Mode, Layout mode is probably a bit older, but yeah, it is a way to know if the user is in edit mode mainly.

![image](https://user-images.githubusercontent.com/6371568/96376398-bb26c900-114c-11eb-85cf-4ac1ad36bd05.png)

Now I do understand, it's not really a PortalSetting but more of a UserInfo thing, maybe we should move that to IUserInfo or some such ? I'll dig to see what we have in UserInfo or UserController to see if we can at least recommand some replacement in code.

**Comment by valadas** [comment]
Ok, here is how I resolved the ones for TabId https://github.com/dnnsoftware/Dnn.Platform/pull/4215/commits/e2ecfad43ae6affc2a49464f33c3d40380add241

Now we need to decide what we do with the UserMode one... I do believe this is not really a portal setting but rather a current state... I am thinking maybe that belongs in CurrentTab or in ApplicationStatus or UserController, after all it's how the user currently views the current tab within the application 🤷 

I left some TODOs linking to this issue to resolve that when we have a decision about it.

**Comment by bdukes** [comment]
I think `UserMode` should be part of a `Personalization` API
