### ISSUE TITLE
Page with Url and Open Link in New Page doesn't open in a new page.

### ISSUE THREAD

**Issue by jncraig** [dnnsoftware/Dnn.Platform#4237]
## Description of bug
A page with Page Type set to URL and Open Link in New Window turned on doesn't open the link in a new window.

## Steps to reproduce
List the precise steps to reproduce the bug:
1. Add a new page
2. Set the Page Type to URL and switch on Open Link in New Window.
3. Go to a page that shows the menu
4. click the page link and the page opens correctly in the same window.

## Current behavior
The menu link for the page is 

<li class="menuItem ">  
            <a href="https://stores.inksoft.com/bull_falls_brewery/shop/products/all?page=1" target="_blank"><span>test</span>             </a>
        </li>

## Expected behavior
The a tag should include target="_blank"

## Screenshots
If applicable, provide screenshots to help explain the bug.

## Error information
Provide any error information (console errors, error logs, etc.) related to this bug.

## Additional context
Provide any additional context that may be helpful in understanding and/or resolving the bug.

## Affected version

* [ ] 10.00.00 alpha build
* [x] 09.08.00 release candidate
* [ ] 09.07.02 latest supported release

Also happens in 9.6.1 and others have told me this is an older issue.

## Affected browser

* [ ] Chrome
* [ ] Firefox
* [ ] Safari
* [ ] Internet Explorer 11
* [ ] Microsoft Edge (Classic)
* [ ] Microsoft Edge Chromium

All browsers

**Comment by mitchelsellers** [comment]
This  is a theme issue in the DDR template.

**Comment by valadas** [comment]
Yeah, I cannot reproduce on the provided theme

![image](https://user-images.githubusercontent.com/6371568/96925228-d4e44b00-1481-11eb-90ce-8f1ae4b292b3.png)

As discussed in slack, this is probably something with the current theme in use and I also posted you a link to a diff showing how to implement it on your theme.
