### ISSUE TITLE
IEventLogController enforces usage of deprecated enum

### ISSUE THREAD

**Issue by valadas** [dnnsoftware/Dnn.Platform#4242]
Not sure if this should be an issue or a discussion, but since I guess it will involve some coding, let's start it up as an issue.

The IEventLogController has the EventLogType enum that is deprecated, but it also has non-deprecated methods that rely on it.

What should we do with this ? I know some work has been done for DI and logging. should we:

🅰️ Mark the whole interface deprecated and provide some short DI guidance ?
🅱️ Add more overloads so it supports the DotNetNuke.Abstractions.Logging.EventLogType one ?

**Comment by bdukes** [comment]
I vote for :a:, with the new interfaces (`IEventLogger`, `IEventLogService` and `IEventLogConfigService`) we have a supported method for doing everything related to the event log.
