### ISSUE TITLE
Login/logout redirection tabs are defaulting to 0 instead of -1

### ISSUE THREAD

**Issue by daguiler** [dnnsoftware/Dnn.Platform#4260]
## Description of bug
After login/logout redirection settings were migrated to Site Settings (#3845), there is an issue when saving.
When other settings in the panel are changed but `Redirect After Login/Logout` are left untouched, their default values are set to 0, instead of -1. This causes DNN to navigate to tab ID 0 after logout, causing a 404:

http://platform-9-7-1.dnndev.me/tabid/0/Default.aspx

Notice the tabid/0 part of the URL.

Upon further investigation, I noticed that these values are `null` in the front-end, and converted to `0` in the back-end when cast to integers.

## Steps to reproduce
1. Clean DNN 9.7.0 or above
3. Open SETTINGS > Site Settings > Site Behavior > DEFAULT PAGES
4. Click on the **User Profile Page** dropdown (the dropdown expands and the Save button becomes enabled)
6. Click Save
7. Close the Persona Bar
8. Log out

## Current behavior
DNN redirects to `/tabid/0/Default.aspx` after logout, causing a 404.

## Expected behavior
DNN should redirect to the home page.

## Screenshots
![image](https://user-images.githubusercontent.com/30123437/97487707-f76fdb80-193b-11eb-89a1-52d5bf45dd94.png)

## Error information
N/A

## Additional context
N/A

## Affected version
* [X] 10.00.00 alpha build
* [X] 09.08.00 release candidate
* [X] 09.07.02 latest supported release
* [X] 09.07.01 latest supported release
* [X] 09.07.00 latest supported release
* [ ] 09.06.02 latest supported release

## Affected browser
* [X] Chrome
* [X] Firefox
* [X] Safari
* [X] Internet Explorer 11
* [X] Microsoft Edge (Classic)
* [X] Microsoft Edge Chromium

**Comment by tpperlman** [comment]
I can confirm this in v9.8. I had to change the redirect drop-downs to home and then back to <None Specified> to resolve.

**Comment by noahbast** [comment]
We had this happen today on a large ecommerce site.  It was a major issue with no clear cause.  Switching redirects in site settings to home, saving, then switching back to none specified fixed it.

**Comment by sleupold** [comment]
@valadas has this been fixed meanwhile, do you know?

**Comment by valadas** [comment]
I am really not sure, I know I have a strange issue after login/logout on a clean 9.9.1 site but did not have time to dig into the details yet.
