### ISSUE TITLE
Enable SSO across domains for JWT

### ISSUE THREAD

**Issue by bdukes** [dnnsoftware/Dnn.Platform#4270]
> The SSO part of this requires the cookie domain in the web.config to be changed.

The solution I am thinking of does not involve cookies, I want to take jwt and apply in this direction:
https://github.com/Aralink/ssojwt
Using iframe and js postMessage, the session cookie is returned via the webapi: https://github.com/DmitryFillo/AspNet.WebApi.CookiesPassthrough

_Originally posted by @thienvc in https://github.com/dnnsoftware/Dnn.Platform/pull/4266#issuecomment-720916129_

**Comment by thienvc** [comment]
I tested SSO and it works perfectly for multiple domains on the DNN multilingual version, and for whole site groups.
However currently the source code is pure html and js, I am trying to draw a working schema and push the code to the test version, is someone willing to evaluate it? @bdukes

**Comment by bdukes** [comment]
If you have working code, we can definitely evaluate it and see if it's something the platform would want to adopt.
