### ISSUE TITLE
Language flags missing

### ISSUE THREAD

**Issue by Tychodewaard** [dnnsoftware/Dnn.Platform#4273]
## Description of bug
If you have multiple languages for a page, the language switcher (flags) are not present)

## Steps to reproduce
1. Add language
2. Enable language
3. Enable localization
4. Localize page and mark as translated and published
5. Permissions to all users
6. verify the 2 urls (in my case en-us and nl-nl) that both pages are accessible
7. see that the language flags are not present (Xcillion)

## Current behavior
Missing language flags

## Expected behavior
Language flags present when criteria met

## Affected version
* [x] 09.08.00 release candidate

**Comment by valadas** [comment]
- I installed 9.8.0 rc1
- Installed nl-nl language pack
- Went to Site Settings => Languages, reloaded the page to show it, then enabled nl-nl and saved
- Clicked "Allow Content Localization" and saved
- Clicked enable content localization, then "Make All Pages Localizable" and saved
- Created a test page and put some html content in english
- Went to the page setting to enter the following and saved
![image](https://user-images.githubusercontent.com/6371568/98033640-d1d34e00-1de3-11eb-8f7c-84f04a134efe.png)

- Reloaded the site and confirmed those settings all persisted
- Went to the page in nl-NL and edited the module text
- Went back to the page settings and marked everything translated and published and saved.
- Went to the pages localization icon (a tooltip here would be a nice enhancement by the way) 
![image](https://user-images.githubusercontent.com/6371568/98034515-1c08ff00-1de5-11eb-9968-dfb53bbc38ae.png)
- Activated the pages for this language
![image](https://user-images.githubusercontent.com/6371568/98034579-35aa4680-1de5-11eb-8686-1f483e447ccb.png)

- closed the persona bar and went to that page
- While still logged in a host, was able to see the language flags and use them and it switched the menu and content language properly
- Logged out and the language flags show as well as the translated content of the module

Does that look like the steps you took or you missed some part or there is more to setup to make this issue happen ?

**Comment by Tychodewaard** [comment]
I did all that. But when I am not logged in, the flags are not showing. That's why I verified permissions.

**Comment by sleupold** [comment]
Did you check page permission as well?

**Comment by Tychodewaard** [comment]
Yup

Outlook voor iOS<https://aka.ms/o0ukef> downloaden
________________________________
Van: Sebastian Leupold <notifications@github.com>
Verzonden: Tuesday, November 3, 2020 10:08:51 PM
Aan: dnnsoftware/Dnn.Platform <Dnn.Platform@noreply.github.com>
CC: Tycho de Waard <info@tjeps.com>; Author <author@noreply.github.com>
Onderwerp: Re: [dnnsoftware/Dnn.Platform] Language flags missing (#4273)


Did you check page permission as well?

**Comment by weilguny** [comment]
I have the same behavior with a website on version 09.07.02 after turning on "content localization". I got the language switcher (flags) back by switching 

Site Settings > Languages > "Users May Choose Interface Language" to "ON" 

As the tooltip of the switcher says, it should be for something slightly different : Check this box to allow site users to select a different language than the interface than the one used for content. 

I hope this helps to discover the problem, and maybe it is a workaround for you Tycho!?  
![20201130-Screenshot-Language-Settings](https://user-images.githubusercontent.com/71639312/100638919-de8c8880-3334-11eb-97b4-7e2d12fbd786.jpg)

**Comment by Tychodewaard** [comment]
Ok...that's new :-)
Good catch! I'll certainly try this when I get to this point again. Hopefully next week.

**Comment by LukeIT65** [comment]
With versions 9.12, 9.13 and 9.13.1 I still encounter the same problem of the language flags no longer being visible; it happens exactly as soon as I perform step 4:

1. Add New Language;
2. Enable Language;
3. Allow Content Localization;
4. Enable Localized Content.

But, if I "Disable Localized Content" the language flags reappear.

**Comment by valadas** [comment]
If you do not turn on "Users May Choose Interface Language" or you are not on a page with a published localized version, then there is no reason for the language switcher to show.

**Comment by valadas** [comment]
Now as for the purpose of "Users May Choose Interface Language", there was a decision made at some point to make the ThreadCulture always be the same as the UICulture. So this behaviour changed and many people who do localization disagree with that new way (including me). It might be a good thing to change that back in DNN10 to how it used to be, but this will be massive work.
