### ISSUE TITLE
v9.8.0-rc1 : On first run you are taken to the InstallWizard which is not there

### ISSUE THREAD

**Issue by euangordon** [dnnsoftware/Dnn.Platform#4275]
Hi All,

Sorry I am quite new to DNN, but came across this issue.

Installing v9.8.0-rc1 on Azure Web App .Net 4.8, with Azure SQL DB.

On the first load, you are redirected to the Install Wizard, but the resource cannot be found.

/Install/InstallWizard.aspx?culture=en-US&acceptterms=true&executeinstall

![image](https://user-images.githubusercontent.com/32622054/98171383-902bcb80-1ee7-11eb-9792-1fd9db61d11a.png)

From looking at the files on the FTP, I believe it has been renamed to WizardUser.ascx, so probably the first run needs updated?

**Comment by valadas** [comment]
Could there have been an upload issue, I did not run Azure installs but that file is in the install package and local installs work fine for me...

**Comment by euangordon** [comment]
@valadas I think you might be right. Weird that everything else has uploaded except the InstallWizard.aspx and InstallWizard.aspx.cs
