### ISSUE TITLE
ENUM EventLogType changes should be reporting as breaking changes

### ISSUE THREAD

**Issue by patrickryan79** [dnnsoftware/Dnn.Platform#4282]
## Description of bug
It's not a bug. IMO a change in standard publicly exposed ENUM regularly used in module development should be reported as breaking change. Typically we target the minimum version of DNN we want to support and reference the appropriate assemblies in our project. A change between 9.2 and 9.6.2+ (probably more-so related to dependency injection change in... 9.5 or so?) introduced a change in the EventType for the logging controller. 

Possibly discussion related to #4242

An often used log type would be `ADMIN_ALERT`.

e.g. `EventLogController.Instance.AddLog("hello", "world", portalSettings, userID, EventLogController.EventLogType.ADMIN_ALERT)`

What I found is that after upgrading a DNN instance from 9.2.1 to 9.6.2 logging ceased. This is because the ADMIN_ALERT in 9.2.1 lined up in sequence (order) with APPLICATION_SHUTTING_DOWN in 9.6.2. and therefore was never logging.

## Steps to reproduce
List the precise steps to reproduce the bug:
1. Reference Dotnetnuke.dll v9.2.1 (or earlier)
2. Attempt to write an ADMIN_ALERT to the event log in a site on v9.6.2+

## Current behavior
Doesn't log

## Expected behavior
Should log an admin alert to the event viewer.

## Affected version

9.6.2+

## Workaround
For developers that do not want to create additional configurations/builds for their module, you can safely get the proper LogType by 

```
var adminAlert = (EventLogController.EventLogType)Enum.Parse(typeof(EventLogController.EventLogType), "ADMIN_ALERT");
EventLogController.Instance.AddLog("hello", "world", portalSettings, userID, adminAlert)
```

**Comment by valadas** [comment]
yeah, I can confirm the enum changed somewhere in 9. The enum was not numbered (so get's auto-numbered) in 9.0.0 and later both got numbered and items got added before ADMIN_ALERT, so yeah, that's not great. However as far as I know, fixing this will cause a second breaking change for those who have adjusted 😞 

Unless someone has a crazy idea on fixing this another way ?

**Comment by patrickryan79** [comment]
Numbering from hereon out, which looks like that already happened as you stated is the best way forward. Although I'm willing to bet many people are simply not aware just yet if it hasn't been reported because it won't throw an error... it just doesn't log or will log incorrectly.  I made a habit early on to reference earlier versions. I really don't know the answer :( I do know that my client had a requirement to store SAML authentication logs so it was a serious matter for them. 

a. Leave it as is
b. Re-number to match what has been in place for years

Have no clue. anyone else?

**Comment by mitchelsellers** [comment]
I think at this point we have to leave it as-is, but I would agree 100% that all future Enums must be numbered!

**Comment by valadas** [comment]
I am also leaning towards leaving it as it is now, it is unfortunate that have this unknown breaking change but making one more breaking change I think would be worst...

**Comment by ahoefling** [comment]
For what it is worth this is something that has been worked on in the new `DotNetNuke.Abstractions` project. If you look at the new `EventLogType` it is using numbered enums

https://github.com/dnnsoftware/Dnn.Platform/blob/d5d6d2b1c9072e80228e1352de855ab6194aa128/DNN%20Platform/DotNetNuke.Abstractions/Logging/EventLogType.cs#L9-L19
