### ISSUE TITLE
[Issue] Fail to Update Module

### ISSUE THREAD

**Issue by Stvchm9703** [dnnsoftware/Dnn.Platform#4288]
## Description of bug
Currently, me and my co-worker are working on migration from v9.1.1 to v9.7.2, and find that the Extension Installation is not working at all : the DLL file in *_install.zip is not updated during Replace Module 

## Steps to reproduce
List the precise steps to reproduce the bug:
1. login with admin account 
1. Go to 'Settings/Extensions' (by side bar)
2. Click on 'Install Extension'
3. Select an existed extension
4. continue the 5 steps

## Current behavior
Current behavior (v9.7.2)
missing the *.dll file backup process, then the server do not update the `bin\*_module_name_*.dll`
```log 
StartJob Starting Installation

Info Starting Installation - ShoppingCartConfirmation
. . . 
Info Starting Installation - Assembly

Info Assembly already registered - bin\ShoppingCartConfirmation.dll

Info Component installed successfully - Assembly

Info Installation committed

Info Installation successful. - ShoppingCartConfirmation

Info Deleted temporary install folder

EndJob Installation successful.
```

## Expected behavior
Provide a clear and concise description of the expected behavior.
in v9.1.1, it run with this logging, then the server update the `bin\*_module_name_*.dll`
```log 
StartJob Starting Installation
. . . 
Info Starting Installation - Assembly

Info Assembly already registered - bin\ShoppingCartConfirmation.dll

Info Creating backup of previous version - bin\ShoppingCartConfirmation.dll

Info Created - bin\ShoppingCartConfirmation.dll

Info Component installed successfully - Assembly

Info Installation committed

Info Installation successful. - ShoppingCartConfirmation

Info Deleted temporary install folder

EndJob Installation successful.
```

## Affected version

* [ ] 10.00.00 alpha build
* [ ] 09.08.00 release candidate
* [X] 09.07.02 latest supported release

**Comment by sleupold** [comment]
Did you unblock downloaded upgrade package (in file properties), before installing?

**Comment by Stvchm9703** [comment]
you mean unzipping to install the updated library ?

**Comment by sleupold** [comment]
no, right click downloaded package in Windows Explorer and select "File Properties". At the bottom of first tab, unblock the file.

**Comment by Stvchm9703** [comment]
checked with co-worker, it was unblocked

**Comment by valadas** [comment]
I am thinking maybe folder permissions or anti-virus blocking ? I have installed a ton of extensions on 9.7.2 and never had this issue.

I would also maybe verify the module package on https://evs.dotnetnuke.com/ to check for manifest errors maybe...

**Comment by Stvchm9703** [comment]
I may find my co-worker and try the verification, and I close this issue first, but I will keep tracking and reporting for your reference 

anyway, thanks for your answering ;)

**Comment by valadas** [comment]
Yep and participants on the issue keep getting notified about comments on it even if it's closed, so feel free to comment if you need any more advice...

**Comment by VitalyaK** [comment]
How did you solve this problem ?
