### ISSUE TITLE
Install Wizard - No other languages available

### ISSUE THREAD

**Issue by weilguny** [dnnsoftware/Dnn.Platform#4296]
## Description of bug
When you setup a new website with the DNN installation wizard there are no more options than "English (United States)" available now (tested with 9.8.0, v 9.7.1 and v 9.6.1). In earlier versions (eg. 9.5.0) there were "German, French, Italian, Spanish and Dutch" in the dropdown-box available. 

## Steps to reproduce
List the precise steps to reproduce the bug:
1. Install new website with DNN_Platform_Install-Package
2. Run Wizard 
3. Click on Website Language dropdown box

## Current behavior
Only English (United States) appears. 

## Expected behavior
Other languages (like "German") should appear. 

## Screenshots
![Screenshot-DNN-Installwizard-Languages](https://user-images.githubusercontent.com/71639312/98971503-86bae880-2511-11eb-8cf7-13a67f48b1fb.jpg)

## Affected version

* [ ] 10.00.00 alpha build
* [X] 09.08.00 release candidate
* [X] 09.07.02 latest supported release

## Affected browser

* [X] Chrome
* [ ] Firefox
* [ ] Safari
* [ ] Internet Explorer 11
* [ ] Microsoft Edge (Classic)
* [ ] Microsoft Edge Chromium

**Comment by weilguny** [comment]
Wondering that there was no response on that issue, so I would like to bring it back up, before it gets deleted by the bot. IMO  there are only two possibilities: 

1) All other languages were dropped on purpose. 
If so, then please just inform the community, that only the english installation is included anymore (would be sad, but I am sure you will have a reason for it). Just explain it to us and the issue can be closed. 

2) Nobody dropped the feature/languages on purpose. 
So then it's a bug or the language-packs are just missing, or the repository path for them is not accessible,... Whatever the reason is, if it's unwanted the issue should not get lost/closed. 

I think it was a comfortable feature and I am sure it helped the international acceptance and easyness for newcomers to get started with DNN.

**Comment by sleupold** [comment]
AFAIK this is an issue of the backend for the upgrade service. I'l try to have a llok at it

**Comment by valadas** [comment]
I guess there was a temporary outage or some such, it is working again for me, can you guys retry that...

**Comment by weilguny** [comment]
Thanks for the notice, Daniel. I checked it with a new install of version 9.9.0 and the languages are back in the combo box!
