### ISSUE TITLE
Cannot set Cookies from Web API response

### ISSUE THREAD

**Issue by bdukes** [dnnsoftware/Dnn.Platform#4304]
## Description of bug
A web API which worked in 9.7.2 has stopped working in 9.8.0.  This API adds a cookie to the headers of the response, and the received response in 9.8.0 does not include that cookie.

## Steps to reproduce
1. Add [the sample API](https://gist.github.com/bdukes/6e8c5cf394373d84344a765531c43048) (you can add to `App_Code` if you also add two additional elements to the `assemblies` element in the `web.config`)
```xml
        <add assembly="System.Net.Http, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" />
        <add assembly="System.Net.Http.Formatting, Version=5.2.3.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" />
```
2. Send a POST request to https://dnn.v972.local/API/EngageCore/Membership/Membership/SetCookie
3. Inspect the response's `Set-Cookie` header

## Current behavior
`Set-Cookie` contains three cookies:
```
dnn_IsMobile=False; path=/; HttpOnly
.ASPXANONYMOUS=wMcP8uYc0q9JbIm2IBB09u_G9vtzmP5mktGWQPiRg0Qmhxa5uXceJxBjmy_sj0im4K1l2eOqTF0jtnpUMoePJLI_XARk2pPRl_ZRM5nBBK4yL0Qj0; expires=Fri, 22-Jan-2021 03:44:10 GMT; path=/; HttpOnly        
language=en-US; path=/; HttpOnly
```

## Expected behavior
`Set-Cookie` contains new `this-is-a-cookie-name=cookievalue` cookie:
```
this-is-a-cookie-name=cookievalue; expires=Mon, 23 Nov 2020 18:28:01 GMT; path=/; secure; httponly
dnn_IsMobile=False; path=/; HttpOnly
.ASPXANONYMOUS=ArCQ4kjzAgonQVYeo88IylVLdg0epGtYIdT5reUgeuXBSPSvnvpqrAsn7l678Mkv9o9UNLvklYAnGFqjZlqPBGdvDWRwsl2fTyTgYN8WWvpPvDfg0; expires=Fri, 22-Jan-2021 05:08:01 GMT; path=/; HttpOnly        
language=en-US; path=/; HttpOnly
```

## Additional Context
In 9.7.2 the cookie was added, but other cookies were included twice:
```
dnn_IsMobile=False; path=/; HttpOnly
.ASPXANONYMOUS=ArCQ4kjzAgonQVYeo88IylVLdg0epGtYIdT5reUgeuXBSPSvnvpqrAsn7l678Mkv9o9UNLvklYAnGFqjZlqPBGdvDWRwsl2fTyTgYN8WWvpPvDfg0; expires=Fri, 22-Jan-2021 05:08:01 GMT; path=/; HttpOnly        
this-is-a-cookie-name=cookievalue; expires=Mon, 23 Nov 2020 18:28:01 GMT; path=/; secure; httponly
dnn_IsMobile=False; path=/; HttpOnly
.ASPXANONYMOUS=ArCQ4kjzAgonQVYeo88IylVLdg0epGtYIdT5reUgeuXBSPSvnvpqrAsn7l678Mkv9o9UNLvklYAnGFqjZlqPBGdvDWRwsl2fTyTgYN8WWvpPvDfg0; expires=Fri, 22-Jan-2021 05:08:01 GMT; path=/; HttpOnly        
language=en-US; path=/; HttpOnly
```

## Affected version

* [ ] 10.00.00 alpha build
* [x] 09.08.00 latest supported release

**Comment by bdukes** [comment]
I've looked through the release notes and reviewed code changes and haven't found anything obvious that would be affecting cookie values.  Any ideas?

**Comment by bdukes** [comment]
I am able to get the cookie added using `HttpContextSource.Current.Response.AppendCookie` instead of `response.Headers.AddCookies` on the `HttpResponseMessage`, but that's scary (and I'd like to at least understand why the latter code broke).

**Comment by thienvc** [comment]
I tested SSO getting Cookies from WebAPI and it works fine. You try this reference
[https://github.com/DmitryFillo/AspNet.WebApi.CookiesPassthrough](url)

**Comment by mikesmeltzer** [comment]
This issue is affecting my modules too. What's scary, I cannot reproduce this issue on 9.8 RC2... it only seems to be happening to me on 9.8 prod release.

**Comment by mikesmeltzer** [comment]
> I am able to get the cookie added using `HttpContextSource.Current.Response.AppendCookie` instead of `response.Headers.AddCookies` on the `HttpResponseMessage`, but that's scary (and I'd like to at least understand why the latter code broke).

I'm able to use Brian's suggestion as a workaround and get my code working properly again. Thanks @bdukes

**Comment by bdukes** [comment]
I've tracked down the issue to 2435e149b1fd8cf484916dbdedc7d765789e8b02 (part of #4265)

It changed from https://github.com/dnnsoftware/Dnn.Platform/blob/a2f73ac5184c9884ea68139abdeafeadf2e9ebd5/DNN%20Platform/Library/Services/Localization/Localization.cs#L1561-L1598

to https://github.com/dnnsoftware/Dnn.Platform/blob/2435e149b1fd8cf484916dbdedc7d765789e8b02/DNN%20Platform/Library/Services/Localization/Localization.cs#L1561-L1583

@donker do you remember the specifics of why this change was necessary (the commit message says it avoids duplicate language cookies)?

**Comment by donker** [comment]
So the reason I made this change is that I found that "Set" didn't actually *replace* the existing cookie, rather it added a new one and this was screwing up localization. This is really weird and hints at maybe deeper issues in the .net framework. But to resolve this I decided to delete the language cookie (if present) and then add the right one.

**Comment by bdukes** [comment]
I adjusted the logic to wrap the `Remove` call with `if (response.Cookies.Get("language") != null`, and that did _not_ resolve the issue.  Completely reverting this commit _did_ resolve the issue.  In this particular call, it resulted in only one `language` cookie, but two `dnn_IsMobile` cookies being sent (the page request included both cookies twice).  In comparison, both of those scenarios only render one cookie without this change (though the reason behind that is a complete mystery to me).

**Comment by bdukes** [comment]
@dnnsoftware/approvers given that I don't have any idea about the underlying mechanism that is causing cookies to multiply unexpectedly, are we okay reverting this commit, and living with duplicate cookies for 9.8.1?

**Comment by mtrutledge** [comment]
Yes I am ok with that.

**Comment by valadas** [comment]
I am ok with that, better have 2 than none I guess...

Would be nice to fix at some point to avoid the duplication, I have been googling a few minutes and found many different stuff which included differences between IIS versions and differences between .Add and .Set as well as an ASP.Net bug about duplications with a workaround about adding/removing a temporary cookie to force-fix all other cookies duplicates. All that to say, it does not appear to be an obvious one in our own code but some sort of known thing with multiple possibilities.

**Comment by donker** [comment]
We'd need to redo the localization tests as that was the reason this was done in the first place.

**Comment by thienvc** [comment]
On the occasion that I encountered this problem again, I would like to discuss this issue again, currently when I am developing a few APIs, I notice that the APIs return cookies twice.
```
< Set-Cookie: app_IsMobile=False; path=/; HttpOnly
< Set-Cookie: .ASPXANONYMOUS=sevx40CbAfZGR-EcVqTiCJWb0U9GZvHaR9o0usrnF5QWxWWYp_-J8eF0jVbGm3-SGrusUc5dak_HTSGTS7EXdK-h6dyJ2BvPvb_UXJnxQizJA-ck0; expires=Tue, 28-May-2024 11:37:52 GMT; path=/; HttpOnly
< Set-Cookie: app_IsMobile=False; path=/; HttpOnly
< Set-Cookie: .ASPXANONYMOUS=sevx40CbAfZGR-EcVqTiCJWb0U9GZvHaR9o0usrnF5QWxWWYp_-J8eF0jVbGm3-SGrusUc5dak_HTSGTS7EXdK-h6dyJ2BvPvb_UXJnxQizJA-ck0; expires=Tue, 28-May-2024 11:37:52 GMT; path=/; HttpOnly
< Set-Cookie: language=vi-VN; path=/; HttpOnly
```

I tried to find out, and found this:
[https://github.com/dnnsoftware/Dnn.Platform/blob/949cac213d78038539a8359c34667802c6d907ab/DNN%20Platform/Library/Services/Localization/Localization.cs#L1455-L1463](url)

```
// save the page culture as a cookie
HttpCookie cookie = response.Cookies.Get("language");
```
I realized that this error is an asp.net error, **cookie will never be null**
The cookie object in the response will be initialized immediately after access even though it does not exist
So I see just the need `cookie.Value = value;` is enough, without needing  `response.Cookies.Set(cookies);`
I removed that line `response.Cookies.Set(cookies);` and everything still works
I realize the included twice issue has been resolved
I want everyone to analyze and test to see if we can pull PR to solve it or not? Everyone may have more experience than me on which DNN versions this affects, I really hate the cookie duplicate problem in webapi
