### ISSUE TITLE
Portal Alias not enforcing Redirect PortalAliasMapping setting on multi-portal/multi-alias sites

### ISSUE THREAD

**Issue by tpperlman** [dnnsoftware/Dnn.Platform#4306]
## Description of bug
On a multi-portal site with multiple aliases, DNN does not redirect to the primary URL when the PortalAliasMapping is set to Redirect. I have the same domains with and without the www prefix, and I am trying to redirect all traffic to the www one but it does not redirect. I have verified this on two separate DNN v9.8 sites.

I have verified that the aliases are setup properly in the PortalAlias table, the primary domain's IsPrimary column is set to 1, and the primary alias also matches the DefaultPortalAlias in the PortalSettings table.

## Steps to reproduce
Create a multi-portal DNN installation and set multiple aliases for each portal. Set one domain with the www prefix and another without the prefix.

## Current behavior
After setting the aliases, load the www and non-www aliases and notice there is no redirect.

## Expected behavior
When the PortalAliasMapping is set to Redirect, it should always redirect to the primary alias.

## Additional context
This may or may not be related to issue [https://github.com/dnnsoftware/Dnn.Platform/pull/4158](https://github.com/dnnsoftware/Dnn.Platform/pull/4158)

This also may be problematic from an SEO perspective since there is no canonical tag and sites could get indexed using multiple aliases.

## Affected version
* [X] 09.08.00 latest supported release

## Affected browser
* [X] Any

**Comment by tpperlman** [comment]
Can anyone confirm this issue? I am having to use the URL rewriter in web.config to address this.

**Comment by Tychodewaard** [comment]
I have the same issue with canonicals. So, also a problem with SEO.

**Comment by tpperlman** [comment]
Thank you for acknowledging the issue @Tychodewaard. I'm still having it for months now.

**Comment by Tychodewaard** [comment]
Could it be related to #3081? Which would mean that multiple things in that area stopped working.

**Comment by tpperlman** [comment]
@Tychodewaard I don't think it is related to that issue. It is my hunch it is related to #4157 since I was also having that issue and perhaps the fix for that one introduced this issue.

**Comment by skamphuis** [comment]
@tpperlman Is the issue reproducable? I mean, can you set up a clean site and create the problem? Me and my colleagues spent quite some hours to fix #2841 last year, and this looks related, from what I read in this issue.

**Comment by tpperlman** [comment]
@skamphuis It happened on a couple of recent new installs and upgrades. I documented it as best as I can.

**Comment by mitchelsellers** [comment]
I have recreated a similar issue, with a slightly different situation on an 9.8.0 installation as well.  A specific bit of this example.

Primary Alias - Is a child portal

Additional aliases are other domain names

Example:

Primary - mysite.com/child

Additional
MyOtherSite.com
MyOtherSite.org
