### ISSUE TITLE
Response wrong language cookie

### ISSUE THREAD

**Issue by thienvc** [dnnsoftware/Dnn.Platform#4307]
https://github.com/dnnsoftware/Dnn.Platform/blob/6e1385a4a9603ac37a1aa347fdf9edefdf77991e/DNN%20Platform/HttpModules/Membership/MembershipModule.cs#L160-L163
Point of error of ThreadCulture in Web API #3545

**Comment by thienvc** [comment]
When authenticated user is setted PreferredLocale, should have only set the ThreadUICulture = user.Profile.PreferredLocale but i don't know why set the ThreadCulture = user.Profile.PreferredLocale as well

**Comment by valadas** [comment]
@donker indicated that it was decided a long time ago that ThreadCulture and ThreadUICulture should always be both set to the same. Honestly I don't even know the difference myself. You have an input on this @donker ?

**Comment by thienvc** [comment]
ThreadCulture is for Backend: for example select data where lang = 'en-US',
ThreadUICulture is for FrontEnd, after user login some personalization for the language can be reserved for that user but only in the external interface (Localization.GetString)
A specific example is when a website has 3 languages: en-US, en-VN, fr-FR
When the user is on the french language page fr.dnndev.me but if the user is logged in and userprofile.preferedlocale = en-US then the interface after logging in is still in English, but PortalSettings and website content is still the "content of french"

**Comment by thienvc** [comment]
[https://github.com/dnnsoftware/Dnn.Platform/blob/6e1385a4a9603ac37a1aa347fdf9edefdf77991e/DNN%20Platform/Library/Services/Localization/Localization.cs#L1619-L1628](url)
`        /// <summary>
        /// Gets a value indicating whether allows users to select their own UI culture.
        /// When set to false (default) framework will allways same culture for both
        /// CurrentCulture (content) and CurrentUICulture (interface).
        /// </summary>`
[https://github.com/dnnsoftware/Dnn.Platform/blob/d7f7bcc53b9b89d091467b47874053e5fa158c76/DNN%20Platform/DotNetNuke.Abstractions/Portals/IPortalSettings.cs#L48-L54](url)
The summary of this setting says it all @valadas

**Comment by donker** [comment]
There are several problems in supporting differing Thread locales from Thread UI locales.

1. The user is unaware. I.e. we had requests to unify this back in the day because people didn't understand why X was in language Y when they switched languages in the UI. It has never been a good and clear experience.
2. Developers are unaware. Modules use thread locale and thread ui locale interchangeably. Changing this behavior will wreak havoc among those modules.

I remain to be convinced to try separating these. I understand what they were meant for (i.e. I understand what has been written above) but there are many situations where it is imperative that when I change the language I see *everything* in that language, including the static texts. This happens for instance when I need to explain to someone else how to do something and that person has a different language set. The other use case is much more flimsy IMHO. I.e. that I'd need to have the static texts in my own language while editing another language. If I am editing the other language I can presume I'll understand the meaning of the field texts.

I can't explain why the documentation on the property doesn't reflect what is happening.

**Comment by thienvc** [comment]
> There are several problems in supporting differing Thread locales from Thread UI locales.
> 
> 1. The user is unaware. I.e. we had requests to unify this back in the day because people didn't understand why X was in language Y when they switched languages in the UI. It has never been a good and clear experience.
> 2. Developers are unaware. Modules use thread locale and thread ui locale interchangeably. Changing this behavior will wreak havoc among those modules.
> 
> I remain to be convinced to try separating these. I understand what they were meant for (i.e. I understand what has been written above) but there are many situations where it is imperative that when I change the language I see _everything_ in that language, including the static texts. This happens for instance when I need to explain to someone else how to do something and that person has a different language set. The other use case is much more flimsy IMHO. I.e. that I'd need to have the static texts in my own language while editing another language. If I am editing the other language I can presume I'll understand the meaning of the field texts.
> 
> I can't explain why the documentation on the property doesn't reflect what is happening.

@donker This is completely normal. When users log in to administer a multilingual website, for example, that website has 3 languages: English, French and German. He only knows English, but when he is administering the content for the German site, he has the right to choose the language of the menu, the function, and the current help in English to handle the operations on the website.

**Comment by thienvc** [comment]
> Developers are unaware. Modules use thread locale and thread ui locale interchangeably. Changing this behavior will wreak havoc among those modules.

Previously when I first approached DNN, it took a bit of time to think about when to use ThreadCulture, when to use ThreadUICulture, but after digging into Core I have seen clearly which one to use.
Basically a normal Module programmer will not care about ThreadUICulture, because DNN self-identifies and uses in Localization Service when accessing static Resx resource by Localization.GetString (). Programmers just need to manipulate ThreadCulture to access and update the database exactly in the current language of Portal.

**Comment by thienvc** [comment]
Exactly @valadas, that's how DNN and multiple Frameworks were designed, and that's also why ThreadUICulture is required, otherwise why need ThreadUICulture.
This change has resulted in many exceptions #4311

**Comment by donker** [comment]
I'm not fundamentally opposed to this change but it will impact some sites. We'll just have to deal with the fallout from this as there might be angry users who see the current behavior change.

Alternatively we could try to have our cake and eat it and wrap this in a (portal level) setting.

**Comment by donker** [comment]
BTW I foresee quite a bit of work in the Personabar as all that code just uses one language variable to manage things. That could be quite a lot of work to untangle. The big risk is that when you edit stuff you're updating the wrong language all of a sudden.

**Comment by thienvc** [comment]
I think it is important to communicate widely to the community and get community feedback. Also In DNNCore, it is imperative to check where the ThreadUICulture is used incorrectly, because an experienced developer switches to DNN, they will be surprised to merge these two concepts into one.

**Comment by thienvc** [comment]
There are instances where the ThreadUICulture has a different value than the ThreadCulture, they are:

1. When the user identifies the individual language of the profile
2. When allowing DNN to automatically detect the language from the Web Browser (i remember DNN has this option)

So if modifications and restrictions affect customers, just temporarily "Off" 2 cases above in DnnCore to not affect is.

**Comment by donker** [comment]
We discussed this issue in the technical team and decided that we'd move to separate the two cultures again. So this is good news for you, @thienvc . However, we will not do this in a minor or point release as it changes current behavior. Also: it requires quite a bit of programming effort to go through the code base and ensure we're correct everywhere.

**Comment by donker** [comment]
> 
> 
> We discussed this issue in the technical team and decided that we'd move to separate the two cultures again. So this is good news for you, @thienvc . However, we will not do this in a minor or point release as it changes current behavior (so for now slated for DNN 10). Also: it requires quite a bit of programming effort to go through the code base and ensure we're correct everywhere.

**Comment by thienvc** [comment]
> We discussed this issue in the technical team and decided that we'd move to separate the two cultures again. So this is good news for you, @thienvc . However, we will not do this in a minor or point release as it changes current behavior (so DNN 10.0.0 is the current thinking). Also: it requires quite a bit of programming effort to go through the code base and ensure we're correct everywhere.

This is really good news. However, in order to avoid errors in WebAPI, it is still necessary to widely inform the influence of web sites with many members, in which Website allows users to edit the preferred Language property in the Profile.
