### ISSUE TITLE
Duplicate set-cookies in Web API response header

### ISSUE THREAD

**Issue by thienvc** [dnnsoftware/Dnn.Platform#4308]
First language cookie response:
https://github.com/dnnsoftware/Dnn.Platform/blob/8e19f0ed92322dad9433b14e42a526139c19cb51/DNN%20Platform/HttpModules/Localization/LocalizationModule.cs#L50-L54
Duplicate Second language cookie response:
https://github.com/dnnsoftware/Dnn.Platform/blob/1c5b7d86d077023b962a5a099565b7a6ccec2fe4/DNN%20Platform/DotNetNuke.Web/Api/Internal/DnnContextMessageHandler.cs#L27-L33
This causes each API call to be repeated 2 times of set-cookie
Should I remove the SetThreadCulture method in DnnContextMessageHandler?

**Comment by valadas** [comment]
@donker I know you been in that section of code recently, any input on this ? Should we check if there is already the language cookie and replace it instead of adding or some such ?

**Comment by donker** [comment]
I've changed the cookie code to ensure only one goes out. This should be fixed in 9.8.1.
