### ISSUE TITLE
Error save Site Settings

### ISSUE THREAD

**Issue by wbonekamp** [dnnsoftware/Dnn.Platform#4309]
## Description of bug
After upgrade to DNN 9.8.0.

When I try to save the Site Settings I get this error:

System.Data.SqlClient.SqlException (0x80131904): The UPDATE statement conflicted with the FOREIGN KEY constraint "FK_Portals_PortalGroups".

Dnn.PersonaBar.SiteSettings.Services.SiteSettingsController.UpdateDefaultPagesSettings(UpdateDefaultPagesSettingsRequest request)

## Steps to reproduce
List the precise steps to reproduce the bug:
1. Go to Site Settings
2. Click on tab 'Site Behavior'
3. Click on tab 'Default Pages'
4. Scroll to the bottom
5. Klik on 'Save'

## Current behavior
Doens't save the settings

## Expected behavior
Should save the settings

## Screenshots

![image](https://user-images.githubusercontent.com/7567981/99247331-1b219580-2807-11eb-902f-b860f1934ab4.png)

## Error information
Dnn.PersonaBar.SiteSettings.Services.SiteSettingsController - System.Data.SqlClient.SqlException (0x80131904): The UPDATE statement conflicted with the FOREIGN KEY constraint "FK_Portals_PortalGroups". The conflict occurred in database "dnn_xxx", table "dbo.PortalGroups", column 'PortalGroupID'.
The statement has been terminated.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at PetaPoco.Database.ExecuteInternal(CommandType commandType, String sql, Object[] args)
   at DotNetNuke.Data.PetaPoco.PetaPocoHelper.ExecuteNonQuery(String connectionString, CommandType type, Int32 timeoutSec, String sql, Object[] args)
   at DotNetNuke.Data.SqlDataProvider.ExecuteNonQuery(String procedureName, Object[] commandParameters)
   at DotNetNuke.Data.DataProvider.UpdatePortalInfo(Int32 portalId, Int32 portalGroupId, String portalName, String logoFile, String footerText, DateTime expiryDate, Int32 userRegistration, Int32 bannerAdvertising, String currency, Int32 administratorId, Double hostFee, Double hostSpace, Int32 pageQuota, Int32 userQuota, String paymentProcessor, String processorUserId, String processorPassword, String description, String keyWords, String backgroundFile, Int32 siteLogHistory, Int32 splashTabId, Int32 homeTabId, Int32 loginTabId, Int32 registerTabId, Int32 userTabId, Int32 searchTabId, Int32 custom404TabId, Int32 custom500TabId, Int32 termsTabId, Int32 privacyTabId, String defaultLanguage, String homeDirectory, Int32 lastModifiedByUserID, String cultureCode)
   at DotNetNuke.Entities.Portals.PortalController.UpdatePortalInternal(PortalInfo portal, Boolean clearCache)
   at Dnn.PersonaBar.SiteSettings.Services.SiteSettingsController.UpdateDefaultPagesSettings(UpdateDefaultPagesSettingsRequest request)
ClientConnectionId:2c6f9f26-6833-44ce-be4c-741da8f5e511

## Affected version

* [ ] 09.08.00 

## Affected browser
all browsers

**Comment by valadas** [comment]
I had that happen to me on one site, my guess is that somehow there was existing portal groups set manually or using some other tool that was not the built-in support for Portal Groups that is now back into Dnn UI...

To resolve that, I had to edit the database manually. Now it depends on your particular situation but if you don't use PortalGroups, then in the Portals table the PortalGroupId for each row should be -1 (In my case I was not using portal groups but somehow that value was 0 or Null or something other than -1).

If you do use PortalGroups, then that number needs to match with an existing ID in the PortalGroups table.

If you don't know how to try this change, you can run in the Persona Bar SQL Console page the following:

```
SELECT * FROM {databaseOwner}{objectQualifier}PortalGroups
```

To know if you are using portal groups or not, then post back and we can advise on a small sql script you can run to fix this.

**Comment by wbonekamp** [comment]
Thanks Valadas that's the problem... unfortunately you can't manually set portalgroups to -1 because of the foreignkey contraint.
When trying you get this error:  
![image](https://user-images.githubusercontent.com/7567981/99362059-45c92800-28b3-11eb-8926-47d0b74b4b8d.png)

I also wonder if the FK's are correct (default DNN) or should be delete:
![image](https://user-images.githubusercontent.com/7567981/99362181-73ae6c80-28b3-11eb-9884-b4574d9f55de.png)

**Comment by valadas** [comment]
Nope, that was probably not put there by Dnn, this is what I have on a clean 9.8.0
![image](https://user-images.githubusercontent.com/6371568/99427388-5db0a400-28d3-11eb-9d03-e768a68f1bec.png)

**Comment by sleupold** [comment]
Foreign keys are implementing referential integrity, preventing inconsistencies. Unfortunately, DNN is missing a number of necessary FKs. A FK (Portals > PortalGroup on PortalGroupID) makes sure, a portal group cannot be deleted, as long as there is a member portal.  An FK (Portals >_Users on AdministratorID > UserID) makes sure. the user account of the website administrator cannot be deleted, similary prevents FK Portals > Roles, to delete a role, which holds Admins or Registered Users role for a site.

**Comment by sleupold** [comment]
The more important question here. why is FK_Portals_PortalGroups affected when saving site settings? this would only occurring, if 
a)PortalGroupID gets modified in a portals record or 
b) a new Portals record with an invalid portalGroupID is added or 
c) a PortalGrop containing a Portal is deleted. 
Neither shouold happen when saving settings for an existig website

**Comment by sleupold** [comment]
The more important question here. why is FK_Portals_PortalGroups affected when saving site settings? this would only occurring, if a PortalGroupID is modified to an invalid value (like -1) upon update, which should never happen,

**Comment by sleupold** [comment]
@wbonekamp did you install my turbo scripts on this DNN before?

**Comment by wbonekamp** [comment]
Yes we did install your turbo script and we did the uninstall before upgrading to DNN 9.8.0.
So the Foreign Keys are added by the turbo script? 
Can we delete them? or what should we do to fix this issue?

**Comment by wbonekamp** [comment]
FK_Portals_PortalGroups is affected because DNN tries to update the portalinfo.

Probably to set field PortalGroupID in table Portals to a valid value -1 in stead of Null (as Daniel mentioned in his reaction)

**Comment by sleupold** [comment]
Willen,
some background on Turbo scripts: the scripts contain thousands of fixes and improvements of DNN database content, schema (table structure and relations), indexes and code (views, functions and procedures. One key for performance are indexed views, which prevent the definition update of tables included - therefore I added TurboUnSchema to be remove this Schema Binding before performing DNN upgrades This does NOT undo all the other fixes and improvements and you should re-apply updated scrips after the update again to regain a consistent and efficient database.
As stated before, Foreign Key constraints ensure the integrity of data and should get added to any relational database, where appropriate. Unfortunately, DNN is missing numerous of these constrains, which can lead to unexpected situations of inconsistency. Another problem based on the history of .Net is the use of "-1" instead of Null in many columns as equivalent for "not existing" - which is simply wrong. No record in Portals table should contain a PortalGroupID, which doesn't exist - it should be NULL or a PortalgroupID existing in PortalGroups table.
Until I finish the TurboScripts for DNN 9.8.0, you may run the following script as a quick fix for your current issue:
`
IF  EXISTS (SELECT * FROM sys.Procedures WHERE object_id = OBJECT_ID(N'{databaseOwner}[{objectQualifier}UpdatePortalInfo]'))
    DROP PROCEDURE {databaseOwner}[{objectQualifier}UpdatePortalInfo]
GO

CREATE PROCEDURE {databaseOwner}[{objectQualifier}UpdatePortalInfo]
    @PortalID               Int,
    @PortalGroupID          Int,
    @PortalName             nVarChar(128),
    @LogoFile               nVarChar( 50),
    @FooterText             nVarChar(100),
    @ExpiryDate             DateTime,
    @UserRegistration       Int,
    @BannerAdvertising      Int,
    @Currency               CHAR(3),
    @AdministratorId        Int,
    @HostFee                MONEY,
    @HostSpace              Int,
    @PageQuota              Int,
    @UserQuota              Int,
    @PaymentProcessor       nVarChar( 50),
    @ProcessorUserId        nVarChar( 50),
    @ProcessorPassword      nVarChar( 50),
    @Description            nVarChar(500),
    @KeyWords               nVarChar(500),
    @BackgroundFile         nVarChar( 50),
    @SiteLogHistory         Int,
    @SplashTabId            Int,
    @HomeTabId              Int,
    @LogIntabId             Int,
    @RegisterTabId          Int,
    @UserTabId              Int,
    @SearchTabId            Int,
    @Custom404TabId         Int,
    @Custom500TabId         Int,
    @TermsTabId				Int,
    @PrivacyTabId			Int,
    @DefaultLanguage        nVarChar( 10),
    @HomeDirectory          VarChar (100),
    @LastModifiedByUserID   Int,
    @CultureCode            nVarChar( 10)
AS
BEGIN
    SET NOCOUNT ON;
    UPDATE {databaseOwner}[{objectQualifier}Portals]
     SET   PortalGroupID        = CASE WHEN IsNull(@PortalGroupID, 1) <= 0 THEN Null ELSE @PortalGroupID END,
           ExpiryDate           = @ExpiryDate,
           UserRegistration     = @UserRegistration,
           BannerAdvertising    = @BannerAdvertising,
           Currency             = @Currency,
           AdministratorId      = @AdministratorId,
           HostFee              = @HostFee,
           HostSpace            = @HostSpace,
           PageQuota            = @PageQuota,
           UserQuota            = @UserQuota,
           PaymentProcessor     = @PaymentProcessor,
           ProcessorUserId      = @ProcessorUserId,
           ProcessorPassword    = @ProcessorPassword,
           SiteLogHistory       = @SiteLogHistory,
           DefaultLanguage      = @DefaultLanguage,
           HomeDirectory        = @HomeDirectory,
           LastModifiedByUserID = @LastModifiedByUserID,
           LastModifiedOnDate   = GetDate()
    WHERE  PortalId = @PortalID;

    IF EXISTS (SELECT * FROM {databaseOwner}[{objectQualifier}PortalLocalization]
                        WHERE PortalId = @PortalID AND CultureCode = @CultureCode)
        UPDATE {databaseOwner}[{objectQualifier}PortalLocalization]
            SET
                [PortalName]              = @PortalName,
                [LogoFile]                = @LogoFile,
                [FooterText]              = @FooterText,
                [Description]             = @Description,
                [KeyWords]                = @KeyWords,
                [BackgroundFile]          = @BackgroundFile,
                [HomeTabId]               = @HomeTabId,
                [LogIntabId]              = @LogIntabId,
                [RegisterTabId]           = @RegisterTabId,
                [UserTabId]               = @UserTabId,
                [SplashTabId]             = @SplashTabId,
                [SearchTabId]             = @SearchTabId,
                [Custom404TabId]          = @Custom404TabId,
                [Custom500TabId]          = @Custom500TabId,
				[TermsTabId]              = @TermsTabId,
				[PrivacyTabId]            = @PrivacyTabId,
                [LastModifiedByUserID]    = @LastModifiedByUserID,
                [LastModifiedOnDate]      = GetDate()
         WHERE  [PortalId]    = @PortalID
           AND  [CultureCode] = @CultureCode
    ELSE BEGIN
        DECLARE @AdmIntabId Int  = (SELECT AdmIntabId
                                    FROM {databaseOwner}[{objectQualifier}PortalLocalization]
                                    WHERE PortalID = @PortalID AND CultureCode=''en-US'');

        INSERT INTO {databaseOwner}[{objectQualifier}PortalLocalization]
        (   [PortalID],
            [CultureCode],
            [PortalName],
            [LogoFile],
            [FooterText],
            [Description],
            [KeyWords],
            [BackgroundFile],
            [HomeTabId],
            [LogIntabId],
            [UserTabId],
            [AdmIntabId],
            [SplashTabId],
            [SearchTabId],
            [Custom404TabId],
            [Custom500TabId],
			[TermsTabId],
			[PrivacyTabId],
            [CreatedByUserID],
            [CreatedOnDate],
            [LastModifiedByUserID],
            [LastModifiedOnDate]
        ) VALUES
        (   @PortalID,
            @CultureCode,
            @PortalName,
            @LogoFile,
            @FooterText,
            @Description,
            @KeyWords,
            @BackgroundFile,
            @HomeTabId,
            @LogIntabId,
            @UserTabId,
            @AdmIntabid,
            @SplashTabId,
            @SearchTabId,
            @Custom404TabId,
            @Custom500TabId,
            @TermsTabId,
			@PrivacyTabId,
            -1,
            GetDate(),
            -1,
            GetDate()
        );
    END;
    SET NOCOUNT OFF;
END -- PROCEDURE`

**Comment by wbonekamp** [comment]
Thanks a lot Sebastian!!!! 

We successfully upgraded to DNN 9.8 and thanks to your script we have no issues or errors anymore.

I totally agree the need of the fixes and improvements in your turbo script. This actually should have been part of DNN in the beginning.

I think your a better database architect than Shaun.... he didn't follow all the database design guidelines as strictly as you did

**Comment by sleupold** [comment]
thanks for your feedback, @wbonekamp 
The fix will be included in next version of TurboDNN script.

**Comment by valadas** [comment]
So just to confirm, I can close this issue then ?

**Comment by sleupold** [comment]
@valadas yes, it wasn't a core issue

**Comment by valadas** [comment]
Perfect, thanks.
