### ISSUE TITLE
DotNetNuke.UI.Modules.IModuleControlPipeline - Crash

### ISSUE THREAD

**Issue by pkExec** [dnnsoftware/Dnn.Platform#4314]
## Description of bug
After an indeterminate amount of time, site crashes with the following error on log:
```
[ERROR] DotNetNuke.Services.Exceptions.Exceptions - DotNetNuke.Services.Exceptions.PageLoadException: Unhandled error loading page. ---> System.InvalidOperationException: No service for type 'DotNetNuke.UI.Modules.IModuleControlPipeline' has been registered.
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at DotNetNuke.UI.Skins.Skin..ctor()
```

By recycling the IIS application pool, or by forcing a recompilation, the issue is fixed.

Is this a regression on https://github.com/dnnsoftware/Dnn.Platform/issues/2806 maybe?

## Error information
```
[ERROR] DotNetNuke.Services.Exceptions.Exceptions - DotNetNuke.Services.Exceptions.PageLoadException: Unhandled error loading page. ---> System.InvalidOperationException: No service for type 'DotNetNuke.UI.Modules.IModuleControlPipeline' has been registered.
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at DotNetNuke.UI.Skins.Skin..ctor()
   at ASP.portals__default_skins_dnnbootsterv2_home_ascx..ctor()
   at __ASP.FastObjectFactory_app_web_50qugp1r.Create_ASP_portals__default_skins_dnnbootsterv2_home_ascx()
   at System.Web.UI.TemplateControl.LoadControl(IWebObjectFactory objectFactory, VirtualPath virtualPath, Type t, Object[] parameters)
   at System.Web.UI.TemplateControl.LoadControl(VirtualPath virtualPath)
   at DotNetNuke.UI.ControlUtilities.LoadControl[T](TemplateControl containerControl, String ControlSrc)
   at DotNetNuke.UI.Skins.Skin.LoadSkin(PageBase page, String skinPath)
   --- End of inner exception stack trace ---
```

## Affected version
* [ ] 10.00.00 alpha build
* [X] 09.08.00 release candidate
* [ ] 09.07.02 latest supported release

## Affected browser

* [X] Chrome
* [X] Firefox
* [ ] Safari
* [X] Internet Explorer 11
* [X] Microsoft Edge (Classic)
* [ ] Microsoft Edge Chromium

**Comment by bdukes** [comment]
You said "forcing a recompilation" fixes the issue, are you recompiling the platform code?  In general usage, you shouldn't need to adjust the platform code to use DNN.  Leave the platform code as-is, and use the many built-in extension points to adjust the site.  If that's not what you mean, let us know what steps you're taking to get here.

**Comment by pkExec** [comment]
Forcing the recompilation is for example by making a change in web.config: 
`<compilation debug="false" strict="false" targetFramework="4.7.2">`
to
`<compilation debug="true" strict="false" targetFramework="4.7.2">`
and vice-versa

**Comment by valadas** [comment]
Oh, that is not a recompilation, it just causes the site to reload

**Comment by valadas** [comment]
Are you able to make the issue happen also using the default theme, it looks like on you second log it is pointing at the theme.

**Comment by pkExec** [comment]
> 
> 
> Are you able to make the issue happen also using the default theme, it looks like on you second log it is pointing at the theme.

Yes, it happens with the default theme too. Also, the skin doesn't seem to be related, because even if I replace it with an "empty" skin, it still occurs.
This *may* have to do with an App_Code folder of the project that has carried over from previous versions, looking into it.

**Comment by pkExec** [comment]
> This may have to do with an App_Code folder of the project

Indeed this seems to be it: 
If you have custom code in App_Code folder, it will work properly the first time, and then fail on reload with the cryptic "DotNetNuke.UI.Modules.IModuleControlPipeline" message.
If you compile your code into a class library (.dll), paste it into "bin" folder and remove the App_Code folder, it will work properly without crash.

The hint was from this thread: [https://dnncommunity.org/forums/aft/1153](https://dnncommunity.org/forums/aft/1153)

Maybe it's more of a documentation issue than a bug then: It should mention on the installation page not to use App_Code folders any more.

**Comment by pkExec** [comment]
I was wrong, this still occurs even after compiling the code into a class library. It also still occurs on latest version 9.8.1

**Comment by pkExec** [comment]
I think I've narrowed it down: the project used the old translation provider "[BrandonHaynes.DotNetNukeResXBuildProvider.ResXBuildProvider](https://archive.codeplex.com/?p=dnnlocalization)". 
This continued to work normally until version 9.0 of DNN. In version 9.0, it works for a few page loads, and then crashes with the current issue. 
So, I think we can close this as not a DNN issue.
