### ISSUE TITLE
Can't switch between View/Edit of userMode in normal user (non admin)

### ISSUE THREAD

**Issue by thienvc** [dnnsoftware/Dnn.Platform#4320]
## Description of bug
Can't switch between View / Edit of userMode when a normal user (editor / approver) (non Admin)

## Steps to reproduce
List the precise steps to reproduce the bug:
1. Login to Admin
2. Create a regular (non-admin) user, eg testeditor
3. Authorize to modify the text / html module the member testeditor has just created (not Administrator)
3. Sign out
4. Log on to the website with the user testeditor
5. Because cannot be switched to the Edit mode (click Edit icon on PersonalBar not effect), the Module Action is not displayed on that Text / html module

## Affected version

* [x] 10.00.00 alpha build
* [x] 09.08.00 latest supported release
* [x] 09.07.02 latest supported release

## Affected browser

* [x] Chrome
* [x] Firefox
* [x] Safari
* [x] Internet Explorer 11
* [x] Microsoft Edge (Classic)
* [ ] Microsoft Edge Chromium

**Comment by valadas** [comment]
I cannot reproduce on a clean 9.8.0 install. Is there something else out of a plain installation on this instance such as localization or non-default theme or others ?

**Comment by thienvc** [comment]
Oh I'm sorry, It is not possible to switch from Edit mode to View mode, normally when logged in with Admin there will be a Close button on the EditBar to switch back to View Mode, but when logged in as a normal user due to no EditPage permission so the EditBar doesn't need to be displayed. Therefore the Close button does not exist.
Should we fix the EDIT button on the PersonalBar to Tri-state: `VIEW `/ `EDIT `/ `EDIT LOCKED`, represented by 3 styles:

- `VIEW`: No style
- `EDIT`: Green background
- `EDIT LOCKED`: Green background with a lock icon

And when the button is clicked in `EDIT LOCKED` mode, return to View mode (Close Editbar).
