### ISSUE TITLE
Persona Bar Users show Error"Could not find stored procedure Personabar.Getusers " 

### ISSUE THREAD

**Issue by ejazhasnain** [dnnsoftware/Dnn.Platform#4328]
Recently I upgraded from Dnn 9.1.1 to Dnn 9.3.0 . Due to some error we had to rollback to backup taken of website and database earlier. Everything seemed fine except the message "Could not find stored procedure Personabar_Getusers" showing on clicking Users in persona bar.
![Screenshot (249)](https://user-images.githubusercontent.com/36451571/100056238-521d2a00-2e4b-11eb-8b3a-1f6ecff1291b.png)

**Comment by sleupold** [comment]
this stored procedure has been deleted intentionally, as it is not used by DNN anymore.
thus you are using old code to access the database - most likely the new personabar has not properly be installed during upgrade.
In your /bin folder, there should only be a file Dnn.PersonaBar.Extensions.dll, make sure to use all older dnn*.dll files out of the /bin folder.

**Comment by sleupold** [comment]
it is not an issue of the upgrade path. But due to some issue, the code files did not get properly replaced, 
- did you unblock downloaded upgrade package in file properties prior to unzipping the files contained?
- did you make sure, no other background process (virus scan, backup) did block the file from being accessed?
- if you moved the site to a different sever or folder in Windows file system, did you re-apply permissions?

**Comment by jeremy-farrance** [comment]
Also, the official or [recommended upgrade path is here](https://dnndocs.com/content/getting-started/setup/upgrades/suggested-upgrade-path) on the DNNDocs site. I don't think upgrading to 9.03**.00** is a good idea, you should definitely redo and go from 9.01.01 to 9.03.02. Also make sure to unblock your downloads, check your NTFS permissions before and after copying the upgrade files in (don't "move", use copy).

**Comment by valadas** [comment]
Also I am a bit unclear for the steps to reproduce. Did you have this issue after the upgrade or after the rollback ?
If after the rollback than my guess is that something went wrong with the restore like you have not deleted the new files and only replaced the old files. Or the files where restored but not the database. If the issue was after the upgrade then my guess is the upgrade went wrong and the previous suggestions make sense.

**Comment by ejazhasnain** [comment]
> it is not an issue of the upgrade path. But due to some issue, the code files did not get properly replaced,
> 
> * did you unblock downloaded upgrade package in file properties prior to unzipping the files contained?
> * did you make sure, no other background process (virus scan, backup) did block the file from being accessed?
> * if you moved the site to a different sever or folder in Windows file system, did you re-apply permissions?

**Comment by ejazhasnain** [comment]
> Also, the official or [recommended upgrade path is here](https://dnndocs.com/content/getting-started/setup/upgrades/suggested-upgrade-path) on the DNNDocs site. I don't think upgrading to 9.03**.00** is a good idea, you should definitely redo and go from 9.01.01 to 9.03.02. Also make sure to unblock your downloads, check your NTFS permissions before and after copying the upgrade files in (don't "move", use copy).

The upgrade package was provided to us by Evoq support team, and I have already performed same upgradation at staging and production

**Comment by ejazhasnain** [comment]
> Also I am a bit unclear for the steps to reproduce. Did you have this issue after the upgrade or after the rollback ?
> If after the rollback than my guess is that something went wrong with the restore like you have not deleted the new files and only replaced the old files. Or the files where restored but not the database. If the issue was after the upgrade then my guess is the upgrade went wrong and the previous suggestions make sense.

We upgraded from 9.1.1 to 9.3.0**(Evoq_Basic_9.3.0.67-108_Upgrade)**. Transfer of files went well and after that upgrade completed as well. But as I clicked on return to Website button Http 503 error occurred. So we decided to rollback to backup taken, As of now we are told that rollback was done by not deleting the physical folder but instead it was overridden with existing files. Seeing previous comments I believe this might be the issue causing this. Regarding upgrade I am still not sure why Http 503 error happened as the same process I did at staging and it went fine. I even raised this at [https://stackoverflow.com/questions/64909538/http-503-error-occurred-after-completing-upgrade-from-dnn-9-1-1-to-9-3-0/64924345#64924345]

**Comment by valadas** [comment]
Haaa, this is Evoq, I totally missed that in the screenshot. Other than the recommendations here (deleting the folder for the revert is certainly required or you will have stuff that is not supposed to be there and may be your only issue actually).

But yeah, other than this if you have other issues I would certainly check with Evoq support, there are a lot of differences on versions and I think the users module is also different.

For the 503 I would investigate that before reverting. I would start with the logs after that error that are located in /portals/_default/logs if nothing helps in there, then that 503 probably does not come from Dnn but from IIS and I would take a look at the IIS logs. If still nothing helpful found in there, then I would check if you have something else in between the public internet and the server like cloudflare or some such where you may need to clear cache or check logs.

**Comment by ejazhasnain** [comment]
> Haaa, this is Evoq, I totally missed that in the screenshot. Other than the recommendations here (deleting the folder for the revert is certainly required or you will have stuff that is not supposed to be there and may be your only issue actually).
> 
> But yeah, other than this if you have other issues I would certainly check with Evoq support, there are a lot of differences on versions and I think the users module is also different.
> 
> For the 503 I would investigate that before reverting. I would start with the logs after that error that are located in /portals/_default/logs if nothing helps in there, then that 503 probably does not come from Dnn but from IIS and I would take a look at the IIS logs. If still nothing helpful found in there, then I would check if you have something else in between the public internet and the server like cloudflare or some such where you may need to clear cache or check logs.

We have already provided the support team with log files and they are looking into it. Since this error didn`t occur at staging I believe this has something to do with IIS and we should have checked IIS logs before reverting. We are going for upgrade again and this time we will make sure of that. Hopefully this doesn`t happens again

**Comment by jeremy-farrance** [comment]
One thing to double check, I have seen certain FTP services improperly set NTFS permissions. So I doubt this is your fix, but I will still recommend that after you move the upgrade files via FTP in to place, and before you start the upgrade, re-apply you NTFS permissions.
