### ISSUE TITLE
Connectors use black and white icons when they're in disconnected state which is against branding rules

### ISSUE THREAD

**Issue by berkarslan-xo** [dnnsoftware/Dnn.Platform#4353]
## Description of bug
Connectors use black and white icons when they're in disconnected state which is against branding rules. For example; Google has the following rules for Analytics logo branding which explicitly forbids changing the colors of their icons ( https://developers.google.com/analytics/terms/branding-policy#logo-usage ):
![image](https://user-images.githubusercontent.com/45750757/101672728-49417080-3a67-11eb-91bd-e373be0620f2.png)

## Steps to reproduce
1. Log in with a host user
2. Navigate to PB > SETTINGS > Connectors

## Current behavior
Icons are black and white.

## Expected behavior
Icons should be colorful.

## Screenshots
![image](https://user-images.githubusercontent.com/45750757/101673098-bf45d780-3a67-11eb-99fb-f01633b75438.png)

## Additional context
Icons are suggested to be shown in their original colors. When a Connector gets connected, it'll already show a green tick next to the icon as in the following screenshot so that this change won't create any confusion about whether a Connector is connected or not too.
![image](https://user-images.githubusercontent.com/45750757/101673293-09c75400-3a68-11eb-80d9-163d00d21697.png)

## Affected version

* [x] 10.00.00 alpha build
* [ ] 09.08.00 latest supported release

## Affected browser

* [x] Chrome
* [ ] Firefox
* [ ] Safari
* [ ] Internet Explorer 11
* [ ] Microsoft Edge (Classic)
* [ ] Microsoft Edge Chromium

**Comment by jeremy-farrance** [comment]
I'll jump out the window... 1) I disagree with this. It is UI standard and industry-wide accepted usage to dim or greyscale a logo or anything to represent an "off" or disabled state. 2) These are all Evoq, so I don't think its an issue in Dnn Platform.

**Comment by mitchelsellers** [comment]
@jeremy-farrance I have to agree with you on this one

**Comment by ahoefling** [comment]
I agree with @jeremy-farrance and @mitchelsellers that I don't think this should be changed. It is 100% industry accepted standard to dim the icons and unless someone from that company has approached the core team I don't think there is any action we need to take.

Products like font-awesome provide a suite of branded icons that you can color however you want with solid colors.

**Comment by mitchelsellers** [comment]
Per the feedback and standards of UI/UX feedback, we are closing this issue at this time.  

If there is a specific claim from a vendor regarding this pattern it should be discussed and addressed at that time.
