### ISSUE TITLE
DNN ImageHandler is broken in 9.8.0

### ISSUE THREAD

**Issue by roman-yagodin** [dnnsoftware/Dnn.Platform#4355]
## Description of bug

Having clean DNN 9.8.0 install, and the only thing that worked with DNN ImageHandler is `profilepic` mode. Other modes including `securefile`, `file`, `placeholder` produce *403 - Forbidden: Access is denied* HTTP errors, but no errors in the log.

## Steps to reproduce

1. Add the following code to Text/HTML module instance (update the `fileid` if necessary):

```HTML
<p>securefile: <img src="/dnnimagehandler.ashx?mode=securefile&amp;fileid=135&amp;filter=resize&amp;w=100" /></p>
<p>file: <img src="/dnnimagehandler.ashx?mode=file&amp;file=Portals/0/Images/logo.png&amp;w=100" /></p>
<p>placeholder: <img src="/dnnimagehandler.ashx?mode=placeholder&amp;w=200&amp;h=50&amp;backcolor=orange" /></p>
<p>profilepic: <img src="/dnnimagehandler.ashx?mode=profilepic&amp;userId=1&amp;h=32&amp;w=32" /></p>
```

2. See error.

## Current behavior

Generated images (except one for profile picture) are not displayed.

## Expected behavior

All kinds of generated images are displayed.

## Screenshots

From DNN 9.8.0:

![dnn-980](https://user-images.githubusercontent.com/5691178/101764688-c5849400-3af9-11eb-84c5-a9dbbf27bf77.png)

From DNN 8.0.4:

![dnn-804](https://user-images.githubusercontent.com/5691178/101764691-c6b5c100-3af9-11eb-8fa4-a37300e9423f.png)

## Error information

There is no corresponding errors in the site logs.

![403](https://user-images.githubusercontent.com/5691178/101765427-b94d0680-3afa-11eb-9791-5f5d64b06f06.png)
![403-2](https://user-images.githubusercontent.com/5691178/101766678-93286600-3afc-11eb-85fd-9fc2dbe70c35.png)

## Affected version

* [x] 09.08.00 latest supported release

## Affected browser

Checked with three different browsers:

* [x] Firefox
* [x] Chromium
* [x] Opera

**Comment by bdukes** [comment]
This was introduced by #4185 (f2c61004fc683ccc4446cae0b2892f71685cd501), which added a permissions check for profile images, but that permissions check is also being applied to non-profile images.
