### ISSUE TITLE
Facebook Authentication Redirection Error

### ISSUE THREAD

**Issue by chetankdsij** [dnnsoftware/Dnn.Platform#4360]
Now, when anyone tries to login using Facebook, it goes back to the login page and on the second attempt to log in, it stays on the login page and gives the following message; An e-mail with your details has been sent to the website administrator for verification. Once your registration has been approved an e-mail will be sent to your e-mail address. In the meantime you can continue to browse this site by closing the popup.

**Comment by mitchelsellers** [comment]
This is due to the fact that your registration mode is set to "Private".  Typically, if you are using Facebook authentication you will want to use "Public" since Facebook already provides "verification" to the process
