### ISSUE TITLE
Resource Manager - List view option, bulk actions and usability

### ISSUE THREAD

**Issue by Valeria-B** [dnnsoftware/Dnn.Platform#4390]
## Description of problem
The current view of the folders and files in the new RM of DNN 9.8.0 is very difficult to visually navigate and manage. The actions are hidden (and not labeled, see #4384) and even relatively short file names are unnecessarily even more shortened, unless you hover on each one. Plus, every card is very bulky, so even a folder with a dozen files or little more becomes unnecessarily "long".
It doesn't help that files and folders have cards with the same background (and poor contrast with the text), and the image previews are mostly hidden (see screenshot 1). 

## Description of solution
Provide an option to switch to/set a more readable and compact list view, with already visible actions+labels, where the file/folder names are shortened only above 60-100 characters (or so) and the file type always visible. 
Include a checkbox to select files/folders to perform actions, such as move and delete, on multiple files at once.
Ideally, the list view could also include "date added/last modified" columns.

## Description of alternatives considered
Not ideal as a standalone alternative, but the "cards" view could also be improved by:
- improving contrast and information hierarchy (when I have several folders or non-image files of the same type, their name is more important than the icon)
- increasing file name limit before shortening (the font could be also smaller, once contrast is improved)
- making extensions always visible for files
- adding "order by" file type
- making the action icons always visible; they could be moved on top instead of on the right side to make space for the filename and just slightly reduced in size; obviously add labels/tooltips to the actions, as suggested in #4384
- widening the clipping of the file preview, where applicable
- adding a selection checkbox to each card for bulk actions
- taking more advantage of responsive styling and flexbox capabilities instead of absolute positioning and fixed widths/heights for the cards and their contents

(see screenshot 2; it's just a quick edit via browser inspector, I know it's visually more busy and can be improved, but again, I still consider the list view option much better)

## Screenshots
Screenshot 1 (current view)
<img width="1200" alt="Current card view" src="https://user-images.githubusercontent.com/6912412/102939344-6a19b500-44ae-11eb-8743-052e3db66955.png">

Screenshot 2 (modified view)
<img width="1266" alt="Modified card view" src="https://user-images.githubusercontent.com/6912412/102939396-7f8edf00-44ae-11eb-865b-808dc54d5bc1.png">

## Additional context
A use case where all of this becomes a serious hindrance: a content editor, who needs to regularly upload and manage a significant amount of pictures or other files. They might need it for sharing or to perform regular massive content uploads/updates in another extension (eg. news articles or e-commerce catalogs). They realize they erroneously uploaded 100+ files, but all the jpegs should have gone into another folder, others should be deleted and a few should stay where they are. All the file names start with a similar string with an identifier at the end. All the previews look very similar. The editor now has to hover over each box to verify what file it is and perform the appropriate action one by one.

## Affected browser

Doesn't seem to be a browser-related issue

**Comment by jeremy-farrance** [comment]
I would vote that this definitely needs to stay open and get fixed.

**Comment by Tychodewaard** [comment]
I guess this issue doesn't get much traction as it is quite a lot. @donker would it be an idea to create several smaller items for this?

**Comment by valadas** [comment]
If someone wants to split this up into more granular issue it would certainly help for management yeah.

**Comment by jeremy-farrance** [comment]
I'll take a crack at splitting this in to multiple issues... if a) no one else has started already and b) someone does a cleanup so its closer to standards after I am done hacking away.

**Comment by jeremy-farrance** [comment]
@valadas and @Tychodewaard - Okay, done for now. Maybe someone could spend a few minutes to verify that I didn't lose anything in the split? Happy to revise things further if needed. Cheers!

**Comment by sleupold** [comment]
@jeremy-farrance Thank you very much!

**Comment by Tychodewaard** [comment]
@Valeria-B I think @jeremy-farrance did a great job splitting up this issue. I propose to close this one as it has all been accounted for in the issues mentioned.

**Comment by Valeria-B** [comment]
> @Valeria-B I think @jeremy-farrance did a great job splitting up this issue. I propose to close this one as it has all been accounted for in the issues mentioned.

yes absolutely!

**Comment by valadas** [comment]
Awesome, I did not have the time to read all the new issues and their comments but, smaller items are usually better :) Thanks for that splitting up effort.
