### ISSUE TITLE
Security Analyzer: CheckDiskAccess

### ISSUE THREAD

**Issue by trouble2** [dnnsoftware/Dnn.Platform#4394]
Please check: https://github.com/DNNCommunity/DNN.SecurityAnalyzer/issues/24

You closed the issue @valadas but the message is still showing up, so nothing was really solved...
It either can be solved or not.

If it can be solved, then solve it, or at least tell people how to solve it in the message 

If it can't be solved then remove the message from the analyzer since it's kind of useless then and will only cause confusion

Thanks!

**Comment by mitchelsellers** [comment]
The message is valid. You must properly configure the pool

**Comment by trouble2** [comment]
Ok, so where can anyone find HOW to configure the pool?

**Comment by valadas** [comment]
Unfortunately the HOW is a bit beyond the scope of Dnn and relates the the operating system and IIS.

And to make that even more complex, it also depends of versions of that operating system and IIS.
Now as a foreword to what I am going to say, I am no expert in this area and I strongly advise taking backups before trying any of this. But in my case I have solved this in 2 different servers using 2 different ways:
1: Moved the hosting folders to a non-system drive (d:) and removed the role "Users" from that whole drive.
2: Left the hosting folder where it was, but had to remove "Users" from that folder and disable Inheritance on that folder too.

Now be very careful, I am no expert in the mater, if you try any of this, make sure you get a full server backup, make sure while windows is changing permissions (it takes a lot of time) to let it finish or you will end up with an inconsistent state. Or even better if you can try this on a copy of the server if it's a VPS or some such...

If you do use a control panel, some of them create users for that purpose and may get it right or wrong too. So there is no 100% accurate advice here to solve this.

**Comment by jeremy-farrance** [comment]
The main thing I have often seen (on other people's hosting setups) that causes the CheckDiskAccess problem is having the website's root folder inheriting permissions "from above." Once you understand and fix that properly, things get pretty easy if you are following a modern article on the subject AND the article matches your version of IIS. Things are different for IIS 6 and IIS 7 (which you shouldn't be on or using anyhow) and you should really be running on IIS 7.5 or higher.

Its an amazing subject with all kinds of easy to make mistakes and twists and turns. 

This is just one related page of the docs and I do NOT recommend trying to read the MS docs to try and figure this out.

**Default permissions and user rights for IIS 7+, IUSR and IIS_IUSRS**
[https://docs.microsoft.com/en-us/troubleshoot/iis/default-permissions-user-rights](https://docs.microsoft.com/en-us/troubleshoot/iis/default-permissions-user-rights)

**Comment by mitchelsellers** [comment]
@jeremy-farrance's comment is the most detailed example, however, at this time I am closing this issue as it is working as expected and reporting accurate permissions
