### ISSUE TITLE
Admin Logs - Add Log Setting returns 401 for admins

### ISSUE THREAD

**Issue by daguiler** [dnnsoftware/Dnn.Platform#4398]
## Description of bug
`Add Log Setting` option in Admin Logs returns 401 for admins.

## Steps to reproduce
1. Open MANAGE > Admin Logs > Log Settings
2. Click on "Add Log Setting"
3. Enable the `Logging` switch, set `Log Type` to "Application Shutting Down"
4. Click on "Save"

## Current behavior
A "success" notification pops up saying "The log setting could not be added. Please try again later."

## Expected behavior
Log setting should be added without issues, but in case an issue occurs, it should be displayed as an error, not as a successful operation.

## Screenshots
![image](https://user-images.githubusercontent.com/30123437/103678762-b5c66700-4f62-11eb-8b2f-7a743838be76.png)

## Error information
Following error is shown in the browser's console:
```
Failed to load resource: the server responded with a status of 401 (Unauthorized)
```
and occurs when PB issues a POST request to /API/PersonaBar/AdminLogs/AddLogSetting

## Additional context
It seems this behavior was introduced by this PR: https://github.com/dnnsoftware/Dnn.AdminExperience.Extensions/pull/231 three years ago.
Looking in the original ticket, it seems some QA test was expecting Admin users not to be able to add Admin Log settings and therefore this condition was added, although it doens't make any sense to me.
Anyone have a clue why admins should not be able to add admin log settings?? and whether this is a mistake or it is expected behavior?

## Affected version
* [X] 10.00.00 alpha build
* [X] 09.08.01 release candidate
* [X] 09.08.00 latest supported release
and all the way down to 9.2.0

## Affected browser
All browsers.

**Comment by bdukes** [comment]
That doesn't make any sense to me either.  Do you have access to the associated ticket, DNN-10163?

**Comment by daguiler** [comment]
Here's a screenshot of the ticket, but it doesn't help much:

![image](https://user-images.githubusercontent.com/30123437/103682321-81a17500-4f67-11eb-9a9d-2625a21a2ed5.png)
