### ISSUE TITLE
Simpler image upload option than filebrowser

### ISSUE THREAD

**Issue by skamphuis** [dnnsoftware/Dnn.Platform#4404]
## Description of problem
We've run into situations, for example in forums, where we do want non-admin users to be able to upload images, but they find the dialogs to do so, too complicated. We would also like to be able to prevent them from uploading other types of files.

## Description of solution
CKEditor offers the [EasyImage plugin](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_plugins_easyimage.html) to facilitate simpler uploads. The user will then be given a file selection popup straight away, in stead of another dialog, to upload an image.
If we could integrate this plugin in the CKEditor Provider, admin would be able to configure a certain module to use this plugin as the behavior for the Image button on the toolbar.
In the provider settings there could be an "Image Button" option below the "File Browser" option, to set the behavior for the Image button to either standard (as it is now), or Easy Image Upload.

## Description of alternatives considered
Another option would be to create new plugin for this, but since it already exists, in a way that offers quite a few options to build on for the future, the investment would probably be a lot bigger than it would be when using the existing plugin.

## Screenshots
Here's a video of how that works:
https://user-images.githubusercontent.com/4275042/104011782-f9adac00-51ae-11eb-96c5-752be95bc1d9.mp4

## Additional context
setting the FileBrowser to "none" and the ImageButton to "EasyImage" also works. This way we can allow users to upload images, but nothing else.

**Comment by sleupold** [comment]
instead of re-defining existing button, I'd prefer a second one to be used in a different button set (for "all users", while keeping existing one for admins)

**Comment by skamphuis** [comment]
> 
> 
> instead of re-defining existing button, I'd prefer a second one to be used in a different button set (for "all users", while keeping existing one for admins)

That's not possible with this plugin (I tried that at first). CKEditor only supports using one or the other.

**Comment by sleupold** [comment]
thank you for your reply. 
I thought, it was posssible for plugins to have its own button (like SKAYT and  math plugin).

**Comment by sleupold** [comment]
quick question: what dialog is displayed, after inserting the image, on right-click and choosing "image properties"?

**Comment by Timo-Breumelhof** [comment]
> 
> 
> thank you for your reply.
> I thought, it was posssible for plugins to have its own button (like SKAYT and math plugin).

not this one..

**Comment by sleupold** [comment]
thanks, @Timo-Breumelhof 
what a pity...

**Comment by Timo-Breumelhof** [comment]
> 
> 
> thanks, @Timo-Breumelhof
> what a pity...

True, but I think the use case is probably to use this image option for specific modules like a Forum.

**Comment by sleupold** [comment]
> > thanks, @Timo-Breumelhof
> > what a pity...
> 
> True, but I think the use case is probably to use this image option for specific modules like a Forum.

you are correct, I missed that option. Thank you!

**Comment by skamphuis** [comment]
> 
> 
> thank you for your reply.
> I thought, it was posssible for plugins to have its own button (like SKAYT and math plugin).

Well, that's true, but the way the easyimage plugin is implemented in CKEditor, is that they won't work both. Which makes sense given that they implemented the easyimage to allow for uploads to their own CDN. In that case you would want all your images uploaded there.

**Comment by skamphuis** [comment]
> 
> 
> quick question: what dialog is displayed, after inserting the image, on right-click and choosing "image properties"?

You don't have the image properties anymore either. The easyimage plugin allows for some customizations in the toolbar, but that's it. Those would require some more thought to implement. I don't think it will be hard to do, but even more so think about what would be needed and how it could be customized.
