### ISSUE TITLE
DNN 9.8.1 SQL and config manager consoles throw JS errors

### ISSUE THREAD

**Issue by nigelcartviper** [dnnsoftware/Dnn.Platform#4411]
Upgraded a site to DNN 9.8.1 and the sql console and config manager wont allow data input into the UI, the attached JS errors are being logged. 

The same behaviour is observed on a clean install of DNN 9.8.1 using the default Xcillion skin and with no modules etc added to a page.

![Untitled](https://user-images.githubusercontent.com/5084123/104466216-e0d93800-55ac-11eb-8003-8e5cfad2037c.png)

**Comment by bdukes** [comment]
Can you look at the URLs that are giving a 404 response, post the full URL here, and confirm that the files are in fact missing in the file system?

Thanks!

**Comment by nigelcartviper** [comment]
Hi,

The 2 files do exist, its just the url's that are incorrect, its currently generating the below:

http://localhost/Resources/Shared/components/MonacoEditor/loader.js
http://localhost/Resources/Shared/components/MonacoEditor/editor/editor.main.js

However the site is not running as the default site in IIS, so the correct url's need to include the site alias and then they will resolve:

http://localhost/sitename/Resources/Shared/components/MonacoEditor/loader.js
http://localhost/sitename/Resources/Shared/components/MonacoEditor/editor/editor.main.js

**Comment by hismightiness** [comment]
I'm not able to duplicate this on a clean install myself.  Maybe it also needs to be tried in Private/Incognito mode (or a different browser)?  🤔

**Comment by mitchelsellers** [comment]
Sub-folder installations of DNN platform itself is not something that traditionally has been truly supported.  (Granted I know that some have done that)

**Comment by TopCat6** [comment]
Please see https://github.com/dnnsoftware/Dnn.Platform/issues/4538 for more detail. I think it must just be how the module references the root directory.

**Comment by bdukes** [comment]
Fixed via #5328
