### ISSUE TITLE
RFC - Display UserID within User Profile Persona Bar Screen

### ISSUE THREAD

**Issue by moorecreative** [dnnsoftware/Dnn.Platform#4412]
## Description of problem
Enhancement - Display UserID within user details in the Persona Bar screen

## Description of solution
It is often necessary to determine the UserID for a user that you look up through the Persona Bar Users screen. In older DNN's you could look to multiple spots including within URLs to see what the UserID value is for that user, now it's more difficult. Could we add a line to the display which lists the UserID please?

**Comment by allanedk** [comment]
I agree on this.

In addition it would nice if the "Search Users"-bar includes UserID in searching, making it easy to look up a specific user by id.

**Comment by jeremy-farrance** [comment]
And TabID on the page settings and RoleID on the roles and ModuleID on the...

**Comment by moorecreative** [comment]
Refresh please... Does anyone else have interest in this as an enhancement for TabID, UserID, RoleID, ModuleID to be visible in some standard way within the interface?

**Comment by jeremy-farrance** [comment]
Definitely needed. Or at minimum, very nice to have.

**Comment by moorecreative** [comment]
This has been around for a year and I'd still love to see it as a piece of information displayed on the Persona Bar Users screen... perhaps it can be in this area of Account Data
![image](https://user-images.githubusercontent.com/5497943/217640854-ee93747f-e5a3-4418-99bd-f7c7e9da595c.png)

though, that said... we can get the userid from the User Folder that displays here, but it's not quite the same as a nice line in the Account Data of perhaps:
UserID:             1138

**Comment by valadas** [comment]
I'll handle this shortly for the UserID

**Comment by jeremy-farrance** [comment]
So this makes 2 out of 3 so far... Page ID (TabID) is now visible on page settings. User ID is now visible on the user account page, but Role ID still needs to be visible on the Roles page.  :)

**Comment by jeremy-farrance** [comment]
I should probably mention how much I greatly appreciate these little efforts getting done along the way. Little things like this in the UI both improve the usefulness of the UI and save (people like me) lots of time. Thank you!

**Comment by moorecreative** [comment]
Thank you so much @valadas !! stellar!
