### ISSUE TITLE
Fix code in the Synchronize Module

### ISSUE THREAD

**Issue by thienvc** [dnnsoftware/Dnn.Platform#4419]
https://github.com/dnnsoftware/Dnn.Platform/blob/2fccd9d6e39aa0acc3355cb964d500ce6562fa68/DNN%20Platform/Library/Entities/Modules/ModuleController.cs#L352

I think we need to move this line out of the loop

**Comment by mitchelsellers** [comment]
What is the specific issue that is being encountered here?

It does appear that this is something that would be excessive in the number of calls, but is it causing an unexpected behavior?

**Comment by thienvc** [comment]
> What is the specific issue that is being encountered here?
> 
> It does appear that this is something that would be excessive in the number of calls, but is it causing an unexpected behavior?

If module has many instances, too many call update database unnecessary
