### ISSUE TITLE
Invalid image when filepath is lower

### ISSUE THREAD

**Issue by thienvc** [dnnsoftware/Dnn.Platform#4420]
https://github.com/dnnsoftware/Dnn.Platform/blob/a37c4f80c516272c9f4129b1c157920cae95ab14/DNN%20Platform/Library/Services/GeneratedImage/DnnImageHandler.cs#L468
StartsWith at here must IgnoreCase

**Comment by bdukes** [comment]
👍🏻 Can you submit a PR?

**Comment by sleupold** [comment]
@thienvc are you able to submit a pull request with your fix?
