### ISSUE TITLE
new blank website english 'settings' has invalid child element 'sitemapcachedays'.

### ISSUE THREAD

**Issue by ortomind** [dnnsoftware/Dnn.Platform#4423]
## Description of bug
The element 'settings' has invalid child element 'sitemapcachedays'
I cannot create website

## Steps to reproduce
List the precise steps to reproduce the bug:
1. Go to Sites
2. Add New Site
3. Domain
4. New User with credentials

## Current behavior
The element 'settings' has invalid child element 'sitemapcachedays'. List of possible elements expected: 'dataconsentconsentredirect, dataconsentdelay, backgroundfile, paymentprocessor, siteloghistory, enableautosave, currency, enablebrowserlanguage, dataconsentactive, timetoautosave, allowuseruiculture, timezoneoffset, expirydate, dataconsentuserdeleteaction, cookiemorelink, hostfee, dataconsentdelaymeasurement, dataconsenttermslastchange'.

* [ ] 10.00.00 alpha build
* [ x] 09.08.01 latest supported release

## Affected browser

* [ ] Chrome
* [ ] Firefox
* [ ] Safari
* [ ] Internet Explorer 11
* [ ] Microsoft Edge (Classic)
* [ x] Microsoft Edge Chromium

**Comment by valadas** [comment]
Duplicates #4403 and was resolved in #4415

This will be resolved with the new release. In the meantime if you need a quick workaround you could modify your template as in https://github.com/dnnsoftware/Dnn.Platform/pull/4415/files
