### ISSUE TITLE
Some protocol violations are common in application layer attacks. # Validating HTTP requests eliminates a large number of application layer attacks.

### ISSUE THREAD

**Issue by saignus** [dnnsoftware/Dnn.Platform#4436]
#
# Some protocol violations are common in application layer attacks.
# Validating HTTP requests eliminates a large number of application layer attacks.
#
# The purpose of this rules file is to enforce HTTP RFC requirements that state how
# the client is supposed to interact with the server.
# http://www.w3.org/Protocols/rfc2616/rfc2616-sec3.html

in Azure, rules of the WAF , show this issue

**Comment by bdukes** [comment]
Please address security-related questions to security@dnnsoftware.com
