### ISSUE TITLE
Personabar Pages ellipsis and indent

### ISSUE THREAD

**Issue by HenrikSH** [dnnsoftware/Dnn.Platform#4438]
The fact that page names are being truncated in the PersonaBar Pages module treeview can be considered to be a problem. Content editors and managers will in case of multiple titles with say more than 4-5 letters and a deeper page structure consisting of several levels of subpages find this UI interface difficult to navigate. 

To avoid missing out on tabnames in the treview area would it be possible to integrate a more flexible layout in a coming release where a user would have the possibility to enlarge the treeview part of the PersonaBar iframe in the classical Windows fashion by dragging a column to the right or left. 
A simpler alternative could consist in just adding a horizontal scrollbar at the bottom of the pages section.

DNN 9.3

* [Version 87.0.4280.141 (Official Build) (64-bit) ] Chrome
* [ ] Firefox
* [ ] Safari
* [ ] Internet Explorer
* [ Version 88.0.705.50 (Official build) (64-bit)] Edge

![478_personabar_pages_ellipsis](https://user-images.githubusercontent.com/1736459/105907148-eca11180-6024-11eb-884c-0ecf6bd46a49.PNG)

**Comment by valadas** [comment]
This has been resolved already, please upgrade.

![image](https://user-images.githubusercontent.com/6371568/105908518-450beb00-5ff4-11eb-8c7f-623b0fefa549.png)

**Comment by valadas** [comment]
A tooltip also shows for even larger ones when hovered

**Comment by HenrikSH** [comment]
Thanks - much obliged. 
I didn't check the DNN change log before making this request.
