### ISSUE TITLE
Bug in new Resource Manager

### ISSUE THREAD

**Issue by skarpik** [dnnsoftware/Dnn.Platform#4445]
## Description of bug

There might be a small glitch in the implementation of the new resource manager. If I click on "Manage > Site Assets", I get exactly the list of folders and files that I expect. If I then click on "Manage > Global Assets", I get exactly the same list of folders and files (which is not correct).

Selecting "Host Root" from the dropdown gives me the expected list of folders and files. So it seems as if when I click on "Manage > Global Assets" that the Resource Manager is not been told to look at the Global Assets folder (until I directly prod it to do so). Has anyone else run into this problem? (DNN v9.8.1 with Telerik removed)

## Steps to reproduce
1. Create test DNN v9.8.1 website
2. Remove Telerik components and install new Resource Manager according to instructions in the notes for DNN v9.8.0 in the Github Releases page.
3. Click on Manage > Site Assets (you get a list of files and folders)
4. Click on Manage > Global Assets (you get exactly the same list of files and folders which is not right)
5. Selecting "Host Root" from the dropdown refreshes the list of files and folders to the correct view

## Current behavior
Manage > Global Assets not refreshing as expected. Requires prodding as described above.

## Expected behavior
Manage > Global Assets should show correct list of files and folders after invocation of Manage > Site Assets

## Screenshots
None

## Error information
None

## Additional context
Provide any additional context that may be helpful in understanding and/or resolving the bug.

## Affected version

* [ ] 10.00.00 alpha build
* [X] 09.08.01 latest supported release

## Affected browser

* [x] Chrome
* [x] Firefox
* [ ] Safari
* [ ] Internet Explorer 11
* [ ] Microsoft Edge (Classic)
* [x] Microsoft Edge Chromium

**Comment by skrantzman** [comment]
I can confirm this behavior on a clean install of DNN 9.8.1, however, the following resolved this issue for me. 
1. Go to Manage > Global Assets.
2. Enter into Edit Mode.
3. Go to Settings for the Resource Manager module, and select the "ResourceManager Settings" tab.
4. With the "Home Folder" property still set to "Host Root", click on the Update button.
5. Global Assets now defaults to the Host Root folder.

**Comment by skarpik** [comment]
> I can confirm this behavior on a clean install of DNN 9.8.1, however, the following resolved this issue for me.
> 
> 1. Go to Manage > Global Assets.
> 2. Enter into Edit Mode.
> 3. Go to Settings for the Resource Manager module, and select the "ResourceManager Settings" tab.
> 4. With the "Home Folder" property still set to "Host Root", click on the Update button.
> 5. Global Assets now defaults to the Host Root folder.
> 
> The new update persists after clearing cache and restarting the application.

The workaround doesn't seem to work for me. If I apply your solution and then go to Manage > Site Assets and then back to Manage > Global Assets, I am still pointing at the Site Assets. Maybe I'm missing something. It seems that going to Manage > Site Assets messes up what Manage > Global Assets points to.

**Comment by skrantzman** [comment]
@skarpik I received an email of your comment on Saturday, but when I came here to reply the comment was not here.  Did the workaround work for your?  I can't remember, but I may have had to cleared the DNN cache between step 4 and 5.

**Comment by skarpik** [comment]
> @skarpik I received an email of your comment on Saturday, but when I came here to reply the comment was not here. Did the workaround work for your? I can't remember, but I may have had to clear the DNN cache between step 4 and 5.

I tested your workaround and it didn't seem to work. So I posted a reply to you. But after posting my reply, I wasn't 100% sure that I'd followed your steps properly so I tried it again and it worked perfectly. So I deleted my comment. In the end, you've contributed a useful workaround until the problem gets addressed. Sorry for confusing you.
