### ISSUE TITLE
URL Mapping Alias Redirect not Being Enforced

### ISSUE THREAD

**Issue by SpydamonkeyDigital** [dnnsoftware/Dnn.Platform#4446]
**Description of bug**
Similar to issue [#4306](https://github.com/dnnsoftware/Dnn.Platform/issues/4306) created by @tpperlman.

On a single or multi-portal site with multiple aliases, DNN does not redirect to the primary URL when the PortalAliasMapping is set to Redirect.

I have verified that the aliases are setup properly in the PortalAlias table, the primary domain's IsPrimary column is set to 1, and the primary alias also matches the DefaultPortalAlias in the PortalSettings table.

**Steps to reproduce**
Create a DNN installation and set multiple aliases for each portal. Set one domain with the www prefix and another without the prefix.

**Current behavior**
After setting the aliases, load the www and non-www aliases and notice there is no redirect. The same goes for domain alias' that are setup to purely redirect traffic to the correct url (ie: mycontoso.com -> contoso.com)

**Expected behavior**
When the PortalAliasMapping is set to Redirect, it should always redirect to the primary alias.

**Affected version**
 09.08.01 (0) latest supported release

**Affected browser**
All

**Comment by Gilderroot** [comment]
Any updates to this issue? I also have come across this issue
