### ISSUE TITLE
"Install New Theme" feature does not install specified files in correct folder

### ISSUE THREAD

**Issue by skrantzman** [dnnsoftware/Dnn.Platform#4448]
## Description of bug
DNN 9.2? - 9.8.1 
When installing a theme via `Manage > Themes > Install New Theme`, files that are specified in the manifest file to be created in the base path of the theme folder are not actually created. However if you use `Settings > Extensions > Install Extension` to install the same theme, those files are indeed created.  These two install methods appear to use different code to install themes in DNN and the Install New Theme option is not working correctly.

## Steps to reproduce
1. Download the TestTheme_1.0.0_install.zip created with nvQuickTheme 
[TestTheme_1.0.0_install.zip](https://github.com/dnnsoftware/Dnn.Platform/files/5922984/TestTheme_1.0.0_install.zip)

2. Open the zip file and you will see that the zip file contains the following files "default.png", thumbnail_default.png", and "LICENSE", among other files.

![ThemeInstallZip](https://user-images.githubusercontent.com/7874652/106841730-7bcaac80-6657-11eb-80aa-15ca7ee4398d.JPG)

3. Open and view the manifest file and you will see that the manifest file specifically creates those files at the root of the theme folder.

![ManifestFile](https://user-images.githubusercontent.com/7874652/106841805-a1f04c80-6657-11eb-961e-ea47e5a1b870.JPG)

4. In a clean new install of DNN that has the `Install New Theme` feature  (9.2? - 9.8.1) use this feature to install the TestTheme theme, and view the Package Installation Report before clicking on "Done" and closing the install theme window.  You should see that DNN thinks that the files were created successfully.

![InstallConfirmationMessage](https://user-images.githubusercontent.com/7874652/106842370-c567c700-6658-11eb-8931-5508a1d6a19d.JPG)

5. Navigate to the new TestTheme folder in the DNN instances Skin folder.  You can see that the files were not actually created.

![ThemeFolder](https://user-images.githubusercontent.com/7874652/106842545-12e43400-6659-11eb-930c-f581295a3654.JPG)

6. To prove that this is most likely a bug in DNN, and not the attached theme, use `Settings > Extensions` and uninstall the theme and be sure to tick off the "Delete Files?" checkbox.

7.  Use  `Settings > Extensions > Install Extension` to install the same TestTheme theme.

8. Navigate to the new TestTheme folder in the DNN instances Skin folder.  You can see that this time the files were created as expected.

## Affected version
* [ ] 10.00.00 alpha build
* [x] 09.08.01 latest supported release and all previous versions that have the `Manage > Themes > Install New Theme` feature
* [ ] 09.01.01

**Comment by bdukes** [comment]
In the output from step 4, it looks like your screenshot says `Portals\0-System` rather than `Portals\_default`, is that where the files are being created?

**Comment by skrantzman** [comment]
bdukes, 

Good catch.  I was so focused at looking to see if the files were created, I did not look carefully enough at the path. So it appears that if you use `Settings > Extensions > Install Extension` to install the theme, the files are created in the correct location, `Portal_default...`.

![PIR_InstallExtension](https://user-images.githubusercontent.com/7874652/106924016-815ddc00-66c3-11eb-8926-29df46fb6050.JPG)

Yet if you use `Manage > Themes > Install New Theme` to install the theme, the files are created in the wrong location of `Portals\0-default...`. 

![PIR_InstallNewTheme](https://user-images.githubusercontent.com/7874652/106924588-0ea13080-66c4-11eb-8691-71734beb6305.JPG)

If I navigate to that path on the website, those files were indeed created in the 0-default portal folder. Mostly likely a an incorrect path reference for the install script in the code for that method.

**Comment by skrantzman** [comment]
Interestingly, this raises another question. After pouring through the Package Installation Report I see that the following folder is created: `\Portals\0-System\Skins\TestTheme\`, but the following folder is not created `\Portals\_default\Skins\TestTheme\`.  Yet only default.png, thumbnail_default.png, and LICENSE are created in the `\Portals\0-System\Skins\TestTheme` folder and all other files are created in the  `\Portals\_default\Skins\TestTheme` folder.  Just an observation.

**Comment by Timo-Breumelhof** [comment]
Can it be that "Manage > Themes > Install New Theme" was intended to replace the previous "Installing a theme for one specific Portal", but is not implemented correclty?
Like installing a Theme from Admin > Extension in DNN 7?
FYI, a Portal Specific Theme is still very useful IMO, although I would prefer the option to assign a Theme to a portal as we do with modules.

**Comment by sleupold** [comment]
I would assume that the intention of the button was to install the theme in portal folder - any UI accessible by site admins (non-superusers) should affect current site only.
Getting a PR would be great!

**Comment by sleupold** [comment]
I would assume that the intention of the button was to install the theme in portal folder - any UI accessible by site admins (non-superusers) should affect current site only
