### ISSUE TITLE
Remove usage of Response.Flush()

### ISSUE THREAD

**Issue by tonyatl2** [dnnsoftware/Dnn.Platform#4451]
## Description of problem
DNN website suffers intermittent performance sluggishness and slowness in handling IIS/http requests

## Description of solution
Remove all references to Response.Flush()

## Description of alternatives considered
None

## Additional context
I am using a trial version of LeanSentry to monitor website performance and to reduce or eliminate bottlenecks in my primary website. It reports: Most slow requeststs in: IIS flushing response to client (20 6 sec) & 22 others. This number fluctuates. About 10% of my http (or iis) requests are sluggish or slow pages, defined in my case as response times of 1-4 seconds for sluggish, and >4 seconds for slow. time is money as google reports on website performance. My theory is that it may be connected in part to the Response.Flush() calls. This is only a theory.

LeanSentry publishes this very brief article on the issues with using Response.Flush() as it is a blocking process, and if a website is generating errors, it can create havoc. for example, i get a lot of bogus calls which result in 404s. My theory is that UtilsHtml may be invoked and make Response.Flush() calls.
https://www.leansentry.com/HowTo/AspNet-Response-Flush-Poor-Performance

My main point is to raise the question. Maybe it is really an RFC type of issue but it was not clear in your opening comments into precisely which forum/topic i would post something like this.

## Affected browser

* [ ] Chrome
* [ ] Firefox
* [ ] Safari
* [ ] Internet Explorer
* [ ] Edge

**Comment by mitchelsellers** [comment]
There are only a total of 7 references to Response.Flush within the entire DNN Platform.  At least two of those should only occur within the installer.  

The other usages are within error pages, or as part of the file management processes.

I'm totally open to reviewing this, but I would love to see some concrete traces/examples of this causing a problem.  Looking at the locations that it is in use currently it is mostly legacy stuff, so it could be mitigated fairly easily.

**Comment by tonyatl2** [comment]
Unfortunately the trial version of LeanSentry does not provide the detailed information you request, and my budget does not afford the higher end versions which would give you precisely what you seek :-o - down to the line of code causing sluggishness, slowness, or hangs.

on the other hand, I think that it makes a very cogent case that such calls are never needed because HTTP.SYS makes the asynchronous calls to do the same things - rather than using a blocking call such as Response.Flush. Please read their write-up in the link i posted above - it is very brief. 

I realized when initially writing that the references to Flush() are not pandemic, but if errors are pervasive, it can make its way around the code block quickly and cause performance issues. it only takes a little to leaven the lump.

I don't think anything is lost by removing it since there is behavior in iis to do the same thing, and could be a low cost performance enhancement. I am just throwing this item out for discussion as the idea seems meritorious. if it is needed, so be it.

**Comment by mitchelsellers** [comment]
I'm not sure we can remove it from the "errors" portion, as the need of a flush is to "force the content to the browser" and we do have some situations where we need this.

BUT - If you are interested, and available to help with some testing I'd be willing to make a quick PR for the other areas and get it rolled before we RC 9.9.0.  As I do believe it is not necessary in the other places

**Comment by tonyatl2** [comment]
yes - i would be willing to test provided you are confident that there are no risky changes elsewhere. ie i am running a production site. i would use leansentry to see if my slow/sluggish page count declines.

**Comment by mitchelsellers** [comment]
Any ability to do a test copy of he site?  I wouldn't want to run an RC in production due to notices of beta etc.

**Comment by tonyatl2** [comment]
i could rig a copy.

or a possible alternative would be for me to take the master build and i could remove all of the flush references in a test site. would i be able to build with visual studio 2019 pro? or would i need a bunch of other packages to create a deployable release?

**Comment by valadas** [comment]
@tonyatl2 
It's easy to build, just run `./build.ps1` in powershell. Or if you do submit a PR with the changes, CI will generate a PR build (takes about 20 minutes with tests and all) but then you will see in the PR checks one of the steps is the build status and it has a link to our Azure Pipeline where you can download the build artifacts which include the install and upgrade packages for that alpha PR build. Ping me up if you need any help building, I'd be happy to assist.

**Comment by jeremy-farrance** [comment]
> It's easy to build, just ...
 
LOL!!!

**Comment by valadas** [comment]
> LOL!!!

Why the lol ? We worked very hard to go from a super messy process to something anyone can build or just download from CI. We (thanks to @donker awesome work) also have documentation for various workflows here https://github.com/dnnsoftware/Dnn.Platform/blob/develop/.github/BUILD.md

People being able to develop on build is very high on our priorities, if you have any issues, ping me up and I will be happy to help or add more documentation where needed.

**Comment by david-poindexter** [comment]
@jeremy-farrance it really is pretty easy now.  Have you tried it lately?  😉

**Comment by jeremy-farrance** [comment]
My bad, yeah, I have not tried again in modern times and I plan to soon. Please accept my apologies, that was the voice of the past. As you know, I am a huge fan of Dnn and the amazing progress of the last few years.
