### ISSUE TITLE
Google Tag Manager Connector - Delete connection not working

### ISSUE THREAD

**Issue by Navilois** [dnnsoftware/Dnn.Platform#4453]
## Description of bug
When going to Settings -> Connectors -> Google Tag Manager and hitting the "Delete connection" button, nothing happens. A new admin log entry shows up.

## Steps to reproduce
List the precise steps to reproduce the bug:
1. Go to Settings -> Connectors -> Google Tag Manager
2. Delete connection
3. Go to Manage -> Admin Logs

## Current behavior
Can't delete GTM connection

## Expected behavior
Delete GTM connection

## Screenshots
If applicable, provide screenshots to help explain the bug.

## Error information
Analytics.AnalyticsConfiguration:GetConfig Failed
FilePath:D:\websites\sierzega.com\Portals\0\\GoogleAnalytics.config
ExceptionMessage:Object reference not set to an instance of an object.

## Additional context
Note the double backslash in the error file path. Coming from (?) https://github.com/dnnsoftware/Dnn.Platform/blob/399a89c292cc8fe1a3ce66a7c592f15104bfbaae/DNN%20Platform/Library/Services/Analytics/Config/AnalyticsConfiguration.cs#L67 

## Affected version

* [ ] 10.00.00 alpha build
* [ X ] 09.08.01 latest supported release

## Affected browser

* [ ] Chrome
* [ X ] Firefox
* [ ] Safari
* [ ] Internet Explorer 11
* [ ] Microsoft Edge (Classic)
* [ ] Microsoft Edge Chromium

**Comment by skamphuis** [comment]
Considering that I contributed it, I'll look into this, thanks.
