### ISSUE TITLE
BCC and CC are completely ignored when sending email

### ISSUE THREAD

**Issue by vmasanas** [dnnsoftware/Dnn.Platform#4472]
## Description of bug
BCC and CC are not taken into consideration when sending emails. The code for the Mail provider ignores them and don't use.

## Steps to reproduce
Try to send any email with a BCC and CC

## Affected version
9.8.x

**Comment by mitchelsellers** [comment]
I'll look at this later today

**Comment by valadas** [comment]
PR merged
