### ISSUE TITLE
New Google Tag Manager Connection Not Loading

### ISSUE THREAD

**Issue by cklenk** [dnnsoftware/Dnn.Platform#4476]
## Description of bug
Upgraded to latest version 9.8.1. Went to connectors, entered our GTM code in the tag manager. Reloaded site. No tag manager is being loaded. If I look at the install and upgrade packages I see the SiteAnalytics.config looks the same. I don't see any references to the new TagManager config file.
![image](https://user-images.githubusercontent.com/12185742/107435664-77404100-6afa-11eb-82e1-28340a0589f1.png)

## Steps to reproduce
List the precise steps to reproduce the bug:
1. Go to settings
2. Click on connectors
3. Enter gtm id and hit save
4. Refresh site
5. No tag manager code

## Current behavior
Tag manager is not loading on dnn portal

## Expected behavior
Site should load tag manager code

## Screenshots
![image](https://user-images.githubusercontent.com/12185742/107435447-2892a700-6afa-11eb-99eb-34b03cb832dc.png)
![image](https://user-images.githubusercontent.com/12185742/107437307-cbe4bb80-6afc-11eb-8301-98338c36b9d8.png)
![image](https://user-images.githubusercontent.com/12185742/107437227-a8ba0c00-6afc-11eb-9207-00f8dd527180.png)
![image](https://user-images.githubusercontent.com/12185742/107437267-b96a8200-6afc-11eb-965f-85192230057c.png)

## Error information
No error messages

## Affected version

* [X] 09.08.01 latest supported release

## Affected browser

* [X] Chrome
* [ ] Firefox
* [ ] Safari
* [ ] Internet Explorer 11
* [ ] Microsoft Edge (Classic)
* [X] Microsoft Edge Chromium

**Comment by mitchelsellers** [comment]
This issue has already been documented and is fixed in the 9.9.0 release.

**Comment by cklenk** [comment]
Awesome thank you!
