### ISSUE TITLE
​MailKit​ generates error message for changes in the user profile (9.9.0 RC1, MailKit vs CoreMailProvider)

### ISSUE THREAD

**Issue by rthoeni** [dnnsoftware/Dnn.Platform#4485]
## Description of bug
​MailKit​ generates error message
CoreMailProvider function

## Steps to reproduce

​MailKit​
SMTP server settings:
Server name and port:: mail.1234.ch:465 send via SSL: yes, sent with no problem
Profile Settings:
go to the profile settings and change entries there, click save... nothing happens
go to Admin Logs:
02/11/2021 21:56:59 Page Load Exception hans.meier Testportal AbsoluteURL /Default.aspx DefaultDataProvider DotNetNuke.Data.SqlDataProvider
AbsoluteURL:/Default.aspx
DefaultDataProvider:DotNetNuke.Data.SqlDataProvider, DotNetNuke
ExceptionGUID:197513c3-5854-4908-a66c-34b3fceecd57
AssemblyVersion:9.9.0
PortalId:0
UserId:1
TabId:22
RawUrl:/Activity-Feed/ctl/Profile/userId/1/pageno/2
Referrer:.../Activity-Feed/ctl/Profile/userId/1/pageno/2
UserAgent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.3 Safari/605.1.15
ExceptionHash:cTQDKPsKmWPgWq1f6fAyi+UaB0g=
Message:Invalid addr-spec token at offset 0
StackTrace:
InnerMessage:Invalid addr-spec token at offset 0
InnerStackTrace:

   bei MimeKit.InternetAddress.TryParseAddrspec(Byte[] text, Int32& index, Int32 endIndex, Byte[] sentinels, Boolean throwOnError, String& addrspec, Int32& at)
   bei MimeKit.MailboxAddress.set_Address(String value)
   bei DotNetNuke.Services.Mail.MailKitMailProvider.SendMail(MailInfo mailInfo, SmtpInfo smtpInfo)
   bei DotNetNuke.Services.Mail.Mail.SendMail(Int32 portalId, Int32 userId, MessageType msgType, PortalSettings settings)
   bei DotNetNuke.Modules.Admin.Users.EditUser.ProfileUpdateCompleted(Object sender, EventArgs e)
   bei DotNetNuke.Entities.Modules.ProfileUserControlBase.OnProfileUpdateCompleted(EventArgs e)
   bei DesktopModules.Admin.Security.DNNProfile.cmdUpdate_Click(Object sender, EventArgs e)
   bei System.Web.UI.WebControls.LinkButton.OnClick(EventArgs e)
   bei System.Web.UI.WebControls.LinkButton.RaisePostBackEvent(String eventArgument)
   bei System.Web.UI.Page.<ProcessRequestMainAsync>d__523.MoveNext()
Source:
FileName:
FileLineNumber:0
FileColumnNumber:0
Method:
Server Name: Faulhorn

**CoreMailProvider** Works securely with ports (25), 587, 2525 TLS
No error in the event log

## Affected version

* [ ] 10.00.00 alpha build
* [x ] 09.09.00 release candidate
* [ ] 09.08.01 latest supported release

## Affected browser

* [ ] Chrome
* [ ] Firefox
* [x ] Safari
* [ ] Internet Explorer 11
* [ ] Microsoft Edge (Classic)
* [ ] Microsoft Edge Chromium

**Comment by valadas** [comment]
Just to rule out a possibility, did you make sure both the host email and the portal admin email are not set to invalide domains like `.invalid`

**Comment by rthoeni** [comment]
I checked again: Host has test@xyz.ch
for the SMTP settings is: test2@xyz.ch
So not the same address deposited

**Comment by bdukes** [comment]
The error message definitely seems to be related to parsing an email address.  I can verify that there's an error if, for example, there's whitespace at the beginning of the From email address.  However, it's not exactly the same message as you are showing here.

Can you install the [Symbols package](https://github.com/dnnsoftware/Dnn.Platform/releases/download/v9.9.0-rc1/DNN_Platform_9.9.0-rc0001_Symbols.zip) and run through your test again?  That should give you line numbers with the stack trace, so we can be sure which address is causing the issue, and track down possible solutions.

Thanks so much for testing the RC and reporting the issue!

**Comment by rthoeni** [comment]
Please excuse. Now I've loaded the Symbols package, but it no longer shows me an error in the event log at the moment.
I can only find these entries in the server log

2021-02-12 00:02:29.172+01:00 [Faulhorn][D:7][T:34][FATAL] DotNetNuke.Framework.PageBase - An error has occurred while loading page.
MimeKit.ParseException: Invalid addr-spec token at offset 0
   bei MimeKit.InternetAddress.TryParseAddrspec(Byte[] text, Int32& index, Int32 endIndex, Byte[] sentinels, Boolean throwOnError, String& addrspec, Int32& at)
   bei MimeKit.MailboxAddress.set_Address(String value)
   bei DotNetNuke.Services.Mail.MailKitMailProvider.SendMail(MailInfo mailInfo, SmtpInfo smtpInfo)
   bei DotNetNuke.Services.Mail.Mail.SendMail(Int32 portalId, Int32 userId, MessageType msgType, PortalSettings settings)
   bei DotNetNuke.Modules.Admin.Users.EditUser.ProfileUpdateCompleted(Object sender, EventArgs e)
   bei DotNetNuke.Entities.Modules.ProfileUserControlBase.OnProfileUpdateCompleted(EventArgs e)
   bei DesktopModules.Admin.Security.DNNProfile.cmdUpdate_Click(Object sender, EventArgs e)
   bei System.Web.UI.WebControls.LinkButton.OnClick(EventArgs e)
   bei System.Web.UI.WebControls.LinkButton.RaisePostBackEvent(String eventArgument)
   bei System.Web.UI.Page.<ProcessRequestMainAsync>d__523.MoveNext()
-----
2021-02-12 00:07:53.260+01:00 [Faulhorn][D:9][T:5][ERROR] DotNetNuke.Services.Exceptions.Exceptions - ~/Default.aspx?tabid=22&error=Invalid+addr-spec+token+at+offset+0
MimeKit.ParseException: Invalid addr-spec token at offset 0
   bei MimeKit.InternetAddress.TryParseAddrspec(Byte[] text, Int32& index, Int32 endIndex, Byte[] sentinels, Boolean throwOnError, String& addrspec, Int32& at) in D:\src\MimeKit\MimeKit\InternetAddress.cs:Zeile 384.
   bei MimeKit.MailboxAddress.set_Address(String value) in D:\src\MimeKit\MimeKit\MailboxAddress.cs:Zeile 264.
   bei DotNetNuke.Services.Mail.MailKitMailProvider.SendMail(MailInfo mailInfo, SmtpInfo smtpInfo) in D:\a\1\s\DNN Platform\Library\Services\Mail\MailKitMailProvider.cs:Zeile 47.
   bei DotNetNuke.Services.Mail.Mail.SendMail(Int32 portalId, Int32 userId, MessageType msgType, PortalSettings settings) in D:\a\1\s\DNN Platform\Library\Services\Mail\Mail.cs:Zeile 216.
   bei DotNetNuke.Modules.Admin.Users.EditUser.ProfileUpdateCompleted(Object sender, EventArgs e) in D:\a\1\s\DNN Platform\Website\DesktopModules\Admin\Security\EditUser.ascx.cs:Zeile 642.
   bei DotNetNuke.Entities.Modules.ProfileUserControlBase.OnProfileUpdateCompleted(EventArgs e) in D:\a\1\s\DNN Platform\Library\Entities\Modules\ProfileUserControlBase.cs:Zeile 36.
   bei DesktopModules.Admin.Security.DNNProfile.cmdUpdate_Click(Object sender, EventArgs e) in D:\a\1\s\DNN Platform\Website\DesktopModules\Admin\Security\Profile.ascx.cs:Zeile 220.
   bei System.Web.UI.WebControls.LinkButton.OnClick(EventArgs e)
   bei System.Web.UI.WebControls.LinkButton.RaisePostBackEvent(String eventArgument)
   bei System.Web.UI.Page.<ProcessRequestMainAsync>d__523.MoveNext()

**Comment by bdukes** [comment]
Thanks so much for this info, it's very helpful. The issue appears to be that DNN is formatting the From email as `"{name} < {email} >"`, but the MailKit provider is expecting just an email address. I'll submit a fix.

**Comment by valadas** [comment]
Thanks so much for testing this and reporting the details @rthoeni  and for the fix @bdukes 

The pull request is merged and an RC2 should come out shortly....
