### ISSUE TITLE
Security Audit Checks for SQL Server Extra Permission fail (9.9.0 RC1)

### ISSUE THREAD

**Issue by rthoeni** [dnnsoftware/Dnn.Platform#4489]
## Description of bug
The problem is still present in DNN CE 9.9.0 RC1.
[#3817](https://github.com/dnnsoftware/Dnn.Platform/issues/3817) is closed. Maybe it can be opened again? it's about the same mistake.
**If it is not important, please close, thanks.**

## Steps to reproduce
List the precise steps to reproduce the bug:
1) Make sure, the SQL User is granted to use xp_dirtree
2) perform DNN Security Audit from PersonaBar > Security
3) check sitelog
4) See error

## Error information
2021-02-12 01:36:24.759+01:00 [Faulhorn][D:2][T:12][ERROR] DotNetNuke.Data.PetaPoco.PetaPocoHelper - [3] Error executing SQL: DECLARE @Output TABLE(Data NVARCHAR(255), Depth INT)
INSERT INTO @Output EXEC sys.xp_dirtree 'C:\WEB\webtest'
SELECT @@ROWCOUNT

Parameter '@Output' specified but none of the passed arguments have a property with this name (in 'DECLARE @Output TABLE(Data NVARCHAR(255), Depth INT)
INSERT INTO @Output EXEC sys.xp_dirtree 'C:\WEB\webtest'
SELECT @@ROWCOUNT
')

## Affected version

* [ ] 10.00.00 alpha build
* [ x] 09.09.00 release candidate
* [ ] 09.08.01 latest supported release

## Affected browser

* [ ] Chrome
* [ ] Firefox
* [x ] Safari
* [ ] Internet Explorer 11
* [ ] Microsoft Edge (Classic)
* [ ] Microsoft Edge Chromium

**Comment by valadas** [comment]
@sleupold you have any clue on a fix for this check?

**Comment by sleupold** [comment]
@valadas 
I'll try to find a solution - atm I didn't find a quick one, but the test does fail for sure (from DNN SQL console as well due to a different bug)
