### ISSUE TITLE
Module Creator Errors on Configure and Create Package

### ISSUE THREAD

**Issue by james7342** [dnnsoftware/Dnn.Platform#4496]
## Description of bug
Trying to use the Module Creator to make quick test module. 

## Steps to reproduce
1. Create Page
2. Place Module Creator Module on Page
3. Provide required information to create a module. (C#, User-Control)
4. Module is added to page. 
5. Click module gear icon and select develop.
6. Click create package
7. Receive Error message - "A critical error has occurred. Please check the Admin Logs for further details."

## Current behavior
Error Message

## Expected behavior
Install Package is created

## Screenshots
![screenshot_2005](https://user-images.githubusercontent.com/27960723/107988460-ebf4fe80-6f84-11eb-8aa9-a1d83050ecd2.png)

## Error information
AbsoluteURL:/Default.aspx
DefaultDataProvider:DotNetNuke.Data.SqlDataProvider, DotNetNuke
ExceptionGUID:57bfa4bf-fc12-48c4-930a-dfe681c2fbc2
AssemblyVersion:9.8.1
PortalId:0
UserId:1
TabId:1106
RawUrl:/Testing-Pages/User-Reg-Expired/ctl/ViewSource/ModuleId/1451/ctlid/303?ReturnURL=/Testing-Pages/User-Reg-Expired&amp;popUp=true
Referrer:http://dnndev.me/Testing-Pages/User-Reg-Expired/ctl/ViewSource/ModuleId/1451/ctlid/303?ReturnURL=/Testing-Pages/User-Reg-Expired&amp;popUp=true
UserAgent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.150 Safari/537.36 Edg/88.0.705.68
ExceptionHash:eP6xokbN5rU4oR+vp4/9NDeAwbE=
Message:Object reference not set to an instance of an object.
StackTrace:
InnerMessage:Object reference not set to an instance of an object.
InnerStackTrace:
   at Dnn.Module.ModuleCreator.ViewSource.OnPackageClick(Object sender, EventArgs e)
   at System.Web.UI.WebControls.LinkButton.OnClick(EventArgs e)
   at System.Web.UI.WebControls.LinkButton.RaisePostBackEvent(String eventArgument)
   at System.Web.UI.Page.<ProcessRequestMainAsync>d__523.MoveNext()
Source:
FileName:
FileLineNumber:0
FileColumnNumber:0
Method:
Server Name: DESKTOP-ITGOR02

* [ ] 10.00.00 alpha build
* [ ] 09.09.00 release candidate
* [X] 09.08.01 latest supported release

* [ ] Chrome
* [ ] Firefox
* [ ] Safari
* [ ] Internet Explorer 11
* [ ] Microsoft Edge (Classic)
* [X] Microsoft Edge Chromium

**Comment by bdukes** [comment]
The Module Creator was removed from the default install in 9.8.1.  Try installing the latest version from https://github.com/DNNCommunity/Dnn.ModuleCreator/releases/tag/v9.8.1 and see if that works.  You may be using an out-of-date version (what version of DNN did you upgrade to 9.8.1 from?)

**Comment by james7342** [comment]
Upgraded from DNN 9.7.2. Must of over looked or ignored the release notes indicating removal of the module. Found them now. 
Upgraded the Module from prior version of 9.7.2 to the 9.8.1 version from the link you provided. Same error. 

AbsoluteURL:/Default.aspx
DefaultDataProvider:DotNetNuke.Data.SqlDataProvider, DotNetNuke
ExceptionGUID:4c80d9cf-ce6b-40aa-85eb-28ac69780949
AssemblyVersion:9.8.1
PortalId:0
UserId:1
TabId:1106
RawUrl:/Testing-Pages/User-Reg-Expired/ctl/ViewSource/ModuleId/1451/ctlid/303?ReturnURL=/Testing-Pages/User-Reg-Expired&amp;popUp=true
Referrer:http://dnndev.me/Testing-Pages/User-Reg-Expired/ctl/ViewSource/ModuleId/1451/ctlid/303?ReturnURL=/Testing-Pages/User-Reg-Expired&amp;popUp=true
UserAgent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.150 Safari/537.36 Edg/88.0.705.68
ExceptionHash:eP6xokbN5rU4oR+vp4/9NDeAwbE=
Message:Object reference not set to an instance of an object.
StackTrace:
InnerMessage:Object reference not set to an instance of an object.
InnerStackTrace:
   at Dnn.Module.ModuleCreator.ViewSource.OnPackageClick(Object sender, EventArgs e)
   at System.Web.UI.WebControls.LinkButton.OnClick(EventArgs e)
   at System.Web.UI.WebControls.LinkButton.RaisePostBackEvent(String eventArgument)
   at System.Web.UI.Page.<ProcessRequestMainAsync>d__523.MoveNext()
Source:
FileName:
FileLineNumber:0
FileColumnNumber:0
Method:

![screenshot_2006](https://user-images.githubusercontent.com/27960723/107990942-6aa06a80-6f8a-11eb-863f-a5cdd97f13e6.png)

Should I open this in the new GitHub Repo? Since it's been removed from for DNN.

**Comment by bdukes** [comment]
Yes, if you wouldn't mind, this issue should go in that other repo now.  Thanks!

**Comment by james7342** [comment]
Opened in the other repo.
https://github.com/DNNCommunity/Dnn.ModuleCreator/issues/16
