### ISSUE TITLE
Email ReplyTo is ignored when sending Email

### ISSUE THREAD

**Issue by Timo-Breumelhof** [dnnsoftware/Dnn.Platform#4502]
Related to #4472
## Description of bug
When sending an email using the DNN methods a passed ReplyTo address is ignored

## Steps to reproduce
List the precise steps to reproduce the bug:
Send an email (using for instance Open Form) and set a ReplyTo address.
BTW, knowing about #4472 I wonder what other options have not been implemented.
We will try to do a PR today for this

FYI: We noticed that BodyEncoding is also not implemented in the provider.

## Affected version
* [ ] 10.00.00 alpha build
* [x] 09.09.00 release candidate
* [x] 09.08.01 latest supported release

**Comment by valadas** [comment]
PR merged into 9.9.0 RC
