### ISSUE TITLE
Dnn.Sites stays empty and gives Console errors

### ISSUE THREAD

**Issue by skamphuis** [dnnsoftware/Dnn.Platform#4506]
## Description of bug
Personbar Sites item stays empty and gives Console errors in the browser.

## Steps to reproduce
1. Install DNN
2. Open Browser Console
3. Open Personabar...Sites
4. See error in console

## Screenshots
![image](https://user-images.githubusercontent.com/4275042/108479562-2d8fed00-7296-11eb-9521-f803a3a4f1ff.png)

## Error information
09:34:30.156 TypeError: M(...).locale(...).fromNow is not a function
    value http://..../DesktopModules/admin/Dnn.PersonaBar/modules/Dnn.Sites/scripts/exportables/Sites/SitesListView.js?cdv=34:1

Related source file is Dnn.AdminExperience\ClientSide\Sites.Web\src\_exportables\src\Components\ListView\index.jsx
On line 155 it says:
`value: dayjs(portal.LastModifiedOnDate).locale(this.props.culture).fromNow()`
[Here](https://day.js.org/docs/en/display/from-now) it says that the fromNow function is in the RelativeTime plugin of DayJS, but I can't see why they're not available.

## Affected version

* [ ] 10.00.00 alpha build
* [x ] 09.09.00 build from latest develop-branch
* [x ] 09.09.00 release candidate 2
* [ ] 09.08.01 latest supported release

## Affected browser

* [x] Chrome
* [x] Firefox
* [ ] Safari
* [ ] Internet Explorer 11
* [ ] Microsoft Edge (Classic)
* [ ] Microsoft Edge Chromium

**Comment by donker** [comment]
Looks like it's the result of these PRs:
https://github.com/dnnsoftware/Dnn.Platform/pulls?q=is%3Apr+is%3Aclosed++dayjs

**Comment by schotman** [comment]
maybe add someting like this: 

var relativeTime = require('dayjs/plugin/relativeTime')
dayjs.extend(relativeTime)

**Comment by david-poindexter** [comment]
I will get a PR in to fix this ASAP.  I see the issue.  Great catch!

**Comment by david-poindexter** [comment]
By the way @skamphuis - I think this same issue may very well exist in a few other PB modules.  I will try to go through all the modules updated via #3875 and re-test using localization to make sure they are updated as well.

**Comment by skamphuis** [comment]
> By the way @skamphuis - I think this same issue may very well exist in a few other PB modules.  I will try to go through all the modules updated via #3875 and re-test using localization to make sure they are updated as well.

@david-poindexter I ran into an issue with the roles module too, in my latest build from develop (so not the release branch). Not sure if that was the dayjs thing too, though. But the module didn't show up.

**Comment by david-poindexter** [comment]
@skamphuis any issue with `Roles.Web` would be a different issue because `dayjs` is not used there.  It previously referenced `moment`, but it was never used.  So, I simply removed the package.

**Comment by skamphuis** [comment]
> @skamphuis any issue with `Roles.Web` would be a different issue because `dayjs` is not used there.  It previously referenced `moment`, but it was never used.  So, I simply removed the package.

That makes sense then. I'll keep an eye on the issue. Since it's not in the release branch, it's not that urgent yet, I guess.
