### ISSUE TITLE
Nuget packages for 9.8.1 not available?

### ISSUE THREAD

**Issue by rodrigoratan** [dnnsoftware/Dnn.Platform#4511]
I'm using DNN 9.8.1 but when trying to develop a custom module I only find the 9.8.0 dnn nuget package, when I publish my module it replaces the 9.8.1 dnn dll's 😭

**Comment by mitchelsellers** [comment]
We had an issue with those getting unlisted, I'll see if I can grab them and push back out.

BUT - Please note you should NEVER publish dotnetnuke.dll with a module installation

**Comment by rodrigoratan** [comment]
Sure, I'm not publishing dotnetnuke*.dlls to the production website, but on my development environment when I update some code on the module I use the VS publish to my local IIS so I can test my changes. I will only commit my modules dll changes anyway. Tks for the help!

**Comment by valadas** [comment]
For the part about them being included when you build (deploy) locally, for each package you can go in it's properties and change "CopyLocal" to false and they should stop being copied over

**Comment by hismightiness** [comment]
For those looking at and/or more comfortable, the equivalent of what Daniel said is found in the csproj/vbproj as `<Private>False</Private>` (meaning, that's what `CopyLocal` changes).

**Comment by rodrigoratan** [comment]
> For the part about them being included when you build (deploy) locally, for each package you can go in it's properties and change "CopyLocal" to false and they should stop being copied over

Tks! Good idea. It will help!!

**Comment by hismightiness** [comment]
Just a tad more background for anyone reading this in the future... 

If `CopyLocal` is set to `True` (`<Private>True</Private>`), it indicates to most build processes that you intend to distribute that DLL as part of your module.  The build script(s) may then put the DLL(s) into the resulting extension package you've been working on.  When you install that package, you could accidentally break DNN and/or other installed extensions if you're not deliberate about which DLL(s) need to be installed, and declare them correctly in your manifest.
