### ISSUE TITLE
Max file upload 28 Mb

### ISSUE THREAD

**Issue by pnuiten** [dnnsoftware/Dnn.Platform#4534]
We want to upload large files (upto) 80 Mb. In previous versions of DNN you could configure this through the user interface or changing the setting in the web.config. 

In DNN 9 this works uptil a max file size of 28 Mb. Greater numbers are not accepted in the UI but it also doesn't work adding it to the web.config.

It looks like it was created intentionally (look at the code below) but can this be changed?

```
if (httpNode == null && Iis7AndAbove())
{
    const int DefaultMaxAllowedContentLength = 30000000;
    return Math.Min(maxRequestLength, DefaultMaxAllowedContentLength);
}
```

**Comment by valadas** [comment]
Where was this code taken from ?

**Comment by jeremy-farrance** [comment]
That one is in the docs, give it a try. Post Qs if you get stuck.

### How to: Increase the Maximum File Size for Upload in DNN Platform
[https://www.dnndocs.com/content/tutorials/troubleshooting/ts-how-to-increase-max-upload-file-size](https://www.dnndocs.com/content/tutorials/troubleshooting/ts-how-to-increase-max-upload-file-size)

**Comment by bdukes** [comment]
That code's from https://github.com/dnnsoftware/Dnn.Platform/blob/2fccd9d6e39aa0acc3355cb964d500ce6562fa68/DNN%20Platform/Library/Common/Utilities/Config.cs#L270-L304

**Comment by pnuiten** [comment]
Hi Jeremy,

That's how we did it before, but it's not working anymore.

**Comment by valadas** [comment]
Ok, one other thing that comes to mind is that we are lacking steps to reproduce in this issue, how are you uploading, because there are many ways to upload:
File Manager
Html module
Custom module, etc.

**Comment by pnuiten** [comment]
At least the file manager, but I think it is also in the other uploads.

**Comment by david-poindexter** [comment]
@pnuiten the instructions on DNN Docs that @jeremy-farrance referenced above work for us on many instances.  Like @valadas says, there are many ways to upload a file, so the specific solution you are using may be bypassing or limiting the `web.config` settings.

**Comment by jeremy-farrance** [comment]
You are correct, the UI is limited. So to get the result you see in the screenshot below, in <httpRuntime I changed maxRequestLength="655360" (its in MBs).
 
Then also added (its not there by default in <system.webServer>...

```
    </httpProtocol>
    <security>
      <requestFiltering>
        <requestLimits maxAllowedContentLength="671088640" />
      </requestFiltering>
    </security>
  </system.webServer>
```


![image](https://user-images.githubusercontent.com/653301/109542831-34cfab80-7a8b-11eb-8a3f-fb3eb418e9bd.png)

**Comment by jeremy-farrance** [comment]
I guess this is a good candidate [for Dnn Details 004 or 005](https://dnncommunity.org/blogs?author=10)? ;)

**Comment by jeremy-farrance** [comment]
Also, for completeness, give some thought to requestLengthDiskThreshold. This is in MBs and has huge affects on large files. Too small and you get lots of disk overhead, too large and you steal gobs of memory. Basically its the buffer size to store in mem before writing that chunk to disk. I recommend keeping it to multiple of 8MBs and no larger than 32MBs.

**Comment by jeremy-farrance** [comment]
After playing, I recommend NOT using the UI to change any of this. At least two problems I've identified so far on a DNN 9.07.02 install:
- you cannot increase the value until the `maxAllowedContentLength` is added
- even then it doesn't work as expected
- it incorrectly overwrites the `requestLengthDiskThreshold` to be the same as `maxRequestLength` which is wrong and bad on very large maxRequestLengths.

**Comment by pnuiten** [comment]
Hi thanks everyone. I got it to work!!

**Comment by jeremy-farrance** [comment]
Why close? There are real issues here that need to be fixed.

**Comment by pnuiten** [comment]
Hi Jeremy, just because my issue was solved, but you're right there is still somethings that need to be solving.

**Comment by mitchelsellers** [comment]
Changing these values to large amounts is STRONGLY discouraged from a security perspective and opens your sites up to many risks.  

Allowing this to be edited easier in the interface is something most likely worth considering, but, it should be the exception not the norm to change these values to high values and ideally should be changed back to smaller values after the needed operation is completed.

**Comment by pnuiten** [comment]
In this case it's for a intranet solution where users are uploading videos and large documents.

**Comment by mitchelsellers** [comment]
> In this case it's for a intranet solution where users are uploading videos and large documents.

This lowers the risk for sure, especially if limited to your own network/VPN

**Comment by ahoefling** [comment]
I don't think DNN supports file chunking. This means it won't be able to upload any files larger than 4GB even if you update the web.config. It would be nice to have updates in the File APIs for both upload and download to support file chunking. This is a technique where you send the bytes in smaller chunks and then the server puts the file back together on the other side.

If we implement this technique, it would remove this problem from ever coming up again. It would also not open the site up to any security issues that @mitchelsellers was mentioning.

**Comment by jeremy-farrance** [comment]
The chunking part is simple IIS, so I do believe it is happening and working. I certainly could be wrong. Not sure how to test it to prove or disprove.

**Comment by ahoefling** [comment]
Respectfully, I don't think that is right. I deal with large file uploads all the time at work (non-DNN code). We have ran into the IIS limit many times which is 4GB files. I worked on a DNN site several years ago where we had the same issue, we were only able to get files up to 4GB. Even in .NET Core or .NET 5 if you are running IIS you still have this limitation. AFAIK we don't explicitly manage the chunk of bytes with file uploads in DNN, we would need to implement that strategy to support the upload chunking.

**Comment by jeremy-farrance** [comment]
Understood, thanks.

**Comment by davidjrh** [comment]
This is still an issue, reopening.

**Comment by valadas** [comment]
From what I read above this is by design, DNN UI does not allow using a larger file size that would work given the web.config limits. We have docs explaining how to do it and they appear to work. So can you clarify what you mean by "still an issue" ?
