### ISSUE TITLE
9.9.0 CKEditor config: Icon legend image files not found

### ISSUE THREAD

**Issue by TopCat6** [dnnsoftware/Dnn.Platform#4537]
## Description of bug
For CKEditor, in the Editor Config, the Icon Legend images are missing

## Steps to reproduce
List the precise steps to reproduce the bug:
1. Go to 'Site Settings, Site Behavior, More.
2. Click on 'Open HTML Editor Manager'. Ensure DNNConnect.CKE is current Provider.
3. See error:  Left side, under Icon Legend shows that images are missing:
![image](https://user-images.githubusercontent.com/17517455/109703958-ed105900-7b4a-11eb-926f-5a00d353f3e1.png)

## Current behavior
Explain the current behavior.
Images for icons are missing

## Expected behavior
Provide a clear and concise description of the expected behavior.
Images for icons should appear

## Screenshots
If applicable, provide screenshots to help explain the bug.
![image](https://user-images.githubusercontent.com/17517455/109704266-42e50100-7b4b-11eb-8800-e296bb6bca40.png)

## Error information
Provide any error information (console errors, error logs, etc.) related to this bug.

## Additional context
Provide any additional context that may be helpful in understanding and/or resolving the bug.
URL for first missing icon is:
/Providers/HtmlEditorProviders/DNNConnect.CKE/images/HostHasSetting.png
However, the 'images' folder does not exist in that location, and seems to be not found in any part of the tree.
The previous version, 4.5.3 in DNN 9.8.1, looked for the icon images here:
/Providers/HtmlEditorProviders/DNNConnect.CKE/js/ckeditor/4.5.3/images

## Affected version

* [ ] 10.00.00 alpha build
* [X] 09.09.00 latest supported release

## Affected browser

* [X] Chrome
* [X] Firefox
* [ ] Safari
* [ ] Internet Explorer 11
* [ ] Microsoft Edge (Classic)
* [ ] Microsoft Edge Chromium

**Comment by james7342** [comment]
Looking at this I see a couple issues.
1. The folders "icons" and "images are missing "Providers/HtmlEditorProviders/DNNConnect.CKE/js/ckeditor/4.15.1" when compared to 4.5.3
![screenshot_2089](https://user-images.githubusercontent.com/27960723/109719717-e93a0200-7b5d-11eb-8e1a-76ead6bea678.png)

2. The path is incorrect as viewed from the console. 
9.8.1- https://www.example.com/Providers/HtmlEditorProviders/DNNConnect.CKE/js/ckeditor/4.5.3/images/HostHasSetting.png

9.9.0-
https://www.example.com/Providers/HtmlEditorProviders/DNNConnect.CKE/images/PortalHasSetting.png

I'm unable to figure out where this path is being set. So even if I copy the folders to the 4.15.1 folder the issue is still present.

**Comment by james7342** [comment]
I think I have this figured out. 
1. The folders are missing from the 4.15.1 folder structure. 
2. The pathing being incorrect is from file Providers/HtmlEditorProviders/DNNConnect.CKE/Module/EditorConfigManager.ascx

In 9.9.0 version the pathing is:
`<div class="iconLegend">
            <ul>
                <li>
                    <asp:Image ID="HostHasSettingImage" runat="server" ImageUrl="~/Providers/HtmlEditorProviders/DNNConnect.CKE/images/HostHasSetting.png" />&nbsp;
                    <asp:Label runat="server" ID="HostHasSettingLabel"></asp:Label>
                </li>
                <li>
                    <asp:Image ID="HostNoSettingImage" runat="server" ImageUrl="~/Providers/HtmlEditorProviders/DNNConnect.CKE/images/HostNoSetting.png"/>&nbsp;
                    <asp:Label runat="server" ID="HostNoSettingLabel"></asp:Label>
                </li>
                <li>
                    <asp:Image ID="PortalHasSettingImage" runat="server" ImageUrl="~/Providers/HtmlEditorProviders/DNNConnect.CKE/images/PortalHasSetting.png" />&nbsp;
                    <asp:Label runat="server" ID="PortalHasSettingLabel"></asp:Label>
                </li>........`

But in 9.8.1 version the pathing is:
`<div class="iconLegend">
            <ul>
                <li>
                    <asp:Image ID="HostHasSettingImage" runat="server" ImageUrl="~/Providers/HtmlEditorProviders/DNNConnect.CKE/js/ckeditor/4.5.3/images/HostHasSetting.png" />&nbsp;
                    <asp:Label runat="server" ID="HostHasSettingLabel"></asp:Label>
                </li>
                <li>
                    <asp:Image ID="HostNoSettingImage" runat="server" ImageUrl="~/Providers/HtmlEditorProviders/DNNConnect.CKE/js/ckeditor/4.5.3/images/HostNoSetting.png"/>&nbsp;
                    <asp:Label runat="server" ID="HostNoSettingLabel"></asp:Label>
                </li>
                <li>
                    <asp:Image ID="PortalHasSettingImage" runat="server" ImageUrl="~/Providers/HtmlEditorProviders/DNNConnect.CKE/js/ckeditor/4.5.3/images/PortalHasSetting.png" />&nbsp;
                    <asp:Label runat="server" ID="PortalHasSettingLabel"></asp:Label>
                </li>
                <li>
                    <asp:Image ID="PortalNoSettingImage" runat="server" ImageUrl="~/Providers/HtmlEditorProviders/DNNConnect.CKE/js/ckeditor/4.5.3/images/PortalNoSetting.png"/>&nbsp;
                    <asp:Label runat="server" ID="PortalNoSettingLabel"></asp:Label>....`


So some where in the process this file should have been updated with to reflect the new path of "~/Providers/HtmlEditorProviders/DNNConnect.CKE/js/ckeditor/4.15.1/images/......"

**Comment by james7342** [comment]
Looks to be something from this commit and PR.
https://github.com/dnnsoftware/Dnn.Platform/pull/4383

Specifically this commit is the files got edited - "Moved DNN icons and images out of CKE folder"
https://github.com/dnnsoftware/Dnn.Platform/pull/4383/commits/af46ae940c3676fe707ebd98c3c4687738fe55c2

**Comment by bdukes** [comment]
@skamphuis it looks like the new `images` folder isn't getting included in the packaging. I think there needs to be a change in this `build` file https://github.com/dnnsoftware/Dnn.Platform/blob/ec762ba9e38817bd74aa9be1ae144b8bde5a6dee/DNN%20Platform/Providers/HtmlEditorProviders/DNNConnect.CKE/Provider.build#L15-L26

**Comment by skamphuis** [comment]
I think you're right. I'll have a look later on this week.

**Comment by james7342** [comment]
and icons folder..
