### ISSUE TITLE
Error Installing 9.9.0

### ISSUE THREAD

**Issue by dush-a** [dnnsoftware/Dnn.Platform#4542]
## Description of bug
Error at 18% of the installation when I Install in shared hosting.
But in local IIS in Windows 10 installation with the same MSQL server 2017 worked without a problem.
Is this mean we can't install DNN in to shared hosting anymore?

## Steps to reproduce
Clean installation of DNN 9.9.0

## Current behavior
0:49 Minutes   |   18% ERROR occured - System.Data.SqlClient.SqlException (0x80131904): User does not have permission to perform this action. User does not have permission to perform this action. User does not have permission to perform this action. at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction) at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction) at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose) at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady) at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite) at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry) at System.Data.SqlClient.SqlCommand.ExecuteNonQuery() at DotNetNuke.Data.SqlDatabaseConnectionProvider.ExecuteNonQuery(String connectionString, CommandType commandType, Int32 commandTimeout, String query) at DotNetNuke.Data.SqlDataProvider.ExecuteScriptInternal(String connectionString, String script, Int32 timeoutSec) ClientConnectionId:c8466144-2ecd-4474-90c1-d18257039e7c Error Number:15247,State:1,Class:16 /*************************************************************/ /*************************************************************/ -- --Create Membership roles -- IF ( NOT EXISTS ( SELECT name FROM sys.database_principals WHERE [type] = 'R' AND name = N'aspnet_Membership_FullAccess' ) ) CREATE ROLE aspnet_Membership_FullAccess IF ( NOT EXISTS ( SELECT name FROM sys.database_principals WHERE [type] = 'R' AND name = N'aspnet_Membership_BasicAccess' ) ) CREATE ROLE aspnet_Membership_BasicAccess IF ( NOT EXISTS ( SELECT name FROM sys.database_principals WHERE [type] = 'R' AND name = N'aspnet_Membership_ReportingAccess' ) ) CREATE ROLE aspnet_Membership_ReportingAccess System.Data.SqlClient.SqlException (0x80131904): User or role 'aspnet_Membership_FullAccess' does not exist in this database. User or role 'aspnet_Membership_FullAccess' does not exist in this database. at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction) at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction) at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose) at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady) at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite) at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry) at System.Data.SqlClient.SqlCommand.ExecuteNonQuery() at DotNetNuke.Data.SqlDatabaseConnectionProvider.ExecuteNonQuery(String connectionString, CommandType commandType, Int32 commandTimeout, String query) at DotNetNuke.Data.SqlDataProvider.ExecuteScriptInternal(String connectionString, String script, Int32 timeoutSec) ClientConnectionId:c8466144-2ecd-4474-90c1-d18257039e7c Error Number:15410,State:1,Class:11 EXEC sp_addrolemember N'aspnet_Membership_BasicAccess', N'aspnet_Membership_FullAccess' EXEC sp_addrolemember N'aspnet_Membership_ReportingAccess', N'aspnet_Membership_FullAccess' System.Data.SqlClient.SqlException (0x80131904): Cannot find the user 'aspnet_Membership_BasicAccess', because it does not exist or you do not have permission. Cannot find the user 'aspnet_Membership_BasicAccess', because it does not exist or you do not have permission. Cannot find the user 'aspnet_Membership_BasicAccess', because it does not exist or you do not have permission. Cannot find the user 'aspnet_Membership_BasicAccess', because it does not exist or you do not have permission. Cannot find the user 'aspnet_Membership_BasicAccess', because it does not exist or you do not have permission. Cannot find the user 'aspnet_Membership_BasicAccess', because it does not exist or you do not have permission. Cannot find the user 'aspnet_Membership_BasicAccess', because it does not exist or you do not have permission. Cannot find the user 'aspnet_Membership_BasicAccess', because it does not exist or you do not have permission. Cannot find the user 'aspnet_Membership_BasicAccess', because it does not exist or you do not have permission. Cannot find the user 'aspnet_Membership_BasicAccess', because it does not exist or you do not have permission. Cannot find the user 'aspnet_Membership_ReportingAccess', because it does not exist or you do not have permission. Cannot find the user 'aspnet_Membership_ReportingAccess', because it does not exist or you do not have permission. Cannot find the user 'aspnet_Membership_ReportingAccess', because it does not exist or you do not have permission. Cannot find the user 'aspnet_Membership_ReportingAccess', because it does not exist or you do not have permission. Cannot find the user 'aspnet_Membership_ReportingAccess', because it does not exist or you do not have permission. Cannot find the user 'aspnet_Membership_ReportingAccess', because it does not exist or you do not have permission. Cannot find the user 'aspnet_Membership_ReportingAccess', because it does not exist or you do not have permission. Cannot find the user 'aspnet_Membership_ReportingAccess', because it does not exist or you do not have permission. Cannot find the user 'aspnet_Membership_ReportingAccess', because it does not exist or you do not have permission. Cannot find the user 'aspnet_Membership_ReportingAccess', because it does not exist or you do not have permission. Cannot find the user 'aspnet_Membership_FullAccess', because it does not exist or you do not have permission. Cannot find the user 'aspnet_Membership_FullAccess', because it does not exist or you do not have permission. Cannot find the user 'aspnet_Membership_FullAccess', because it does not exist or you do not have permission. Cannot find the user 'aspnet_Membership_FullAccess', because it does not exist or you do not have permission. Cannot find the user 'aspnet_Membership_FullAccess', because it does not exist or you do not have permission. Cannot find the user 'aspnet_Membership_FullAccess', because it does not exist or you do not have permission. Cannot find the user 'aspnet_Membership_FullAccess', because it does not exist or you do not have permission. Cannot find the user 'aspnet_Membership_ReportingAccess', because it does not exist or you do not have permission. Cannot find the user 'aspnet_Membership_ReportingAccess', because it does not exist or you do not have permission. Cannot find the user 'aspnet_Membership_ReportingAccess', because it does not exist or you do not have permission. Cannot grant, deny, or revoke permissions to sa, dbo, entity owner, information_schema, sys, or yourself. at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction) at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction) at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose) at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady) at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite) at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry) at System.Data.SqlClient.SqlCommand.ExecuteNonQuery() at DotNetNuke.Data.SqlDatabaseConnectionProvider.ExecuteNonQuery(String connectionString, CommandType commandType, Int32 commandTimeout, String query) at DotNetNuke.Data.SqlDataProvider.ExecuteScriptInternal(String connectionString, String script, Int32 timeoutSec) ClientConnectionId:c8466144-2ecd-4474-90c1-d18257039e7c Error Number:15151,State:1,Class:16 -- --Stored Procedure rights for BasicAcess -- GRANT EXECUTE ON dbo.aspnet_Membership_GetUserByUserId TO aspnet_Membership_BasicAccess GRANT EXECUTE ON dbo.aspnet_Membership_GetUserByName TO aspnet_Membership_BasicAccess GRANT EXECUTE ON dbo.aspnet_Membership_GetUserByEmail TO aspnet_Membership_BasicAccess GRANT EXECUTE ON dbo.aspnet_Membership_GetPassword TO aspnet_Membership_BasicAccess GRANT EXECUTE ON dbo.aspnet_Membership_GetPasswordWithFormat TO aspnet_Membership_BasicAccess GRANT EXECUTE ON dbo.aspnet_Membership_UpdateUserInfo TO aspnet_Membership_BasicAccess GRANT EXECUTE ON dbo.aspnet_Membership_GetNumberOfUsersOnline TO aspnet_Membership_BasicAccess GRANT EXECUTE ON dbo.aspnet_CheckSchemaVersion TO aspnet_Membership_BasicAccess GRANT EXECUTE ON dbo.aspnet_RegisterSchemaVersion TO aspnet_Membership_BasicAccess GRANT EXECUTE ON dbo.aspnet_UnRegisterSchemaVersion TO aspnet_Membership_BasicAccess -- --Stored Procedure rights for ReportingAccess -- GRANT EXECUTE ON dbo.aspnet_Membership_GetUserByUserId TO aspnet_Membership_ReportingAccess GRANT EXECUTE ON dbo.aspnet_Membership_GetUserByName TO aspnet_Membership_ReportingAccess GRANT EXECUTE ON dbo.aspnet_Membership_GetUserByEmail TO aspnet_Membership_ReportingAccess GRANT EXECUTE ON dbo.aspnet_Membership_GetAllUsers TO aspnet_Membership_ReportingAccess GRANT EXECUTE ON dbo.aspnet_Membership_GetNumberOfUsersOnline TO aspnet_Membership_ReportingAccess GRANT EXECUTE ON dbo.aspnet_Membership_FindUsersByName TO aspnet_Membership_ReportingAccess GRANT EXECUTE ON dbo.aspnet_Membership_FindUsersByEmail TO aspnet_Membership_ReportingAccess GRANT EXECUTE ON dbo.aspnet_CheckSchemaVersion TO aspnet_Membership_ReportingAccess GRANT EXECUTE ON dbo.aspnet_RegisterSchemaVersion TO aspnet_Membership_ReportingAccess GRANT EXECUTE ON dbo.aspnet_UnRegisterSchemaVersion TO aspnet_Membership_ReportingAccess -- --Additional stored procedure rights for FullAccess -- GRANT EXECUTE ON dbo.aspnet_Users_DeleteUser TO aspnet_Membership_FullAccess GRANT EXECUTE ON dbo.aspnet_Membership_CreateUser TO aspnet_Membership_FullAccess GRANT EXECUTE ON dbo.aspnet_Membership_SetPassword TO aspnet_Membership_FullAccess GRANT EXECUTE ON dbo.aspnet_Membership_ResetPassword TO aspnet_Membership_FullAccess GRANT EXECUTE ON dbo.aspnet_Membership_UpdateUser TO aspnet_Membership_FullAccess GRANT EXECUTE ON dbo.aspnet_Membership_ChangePasswordQuestionAndAnswer TO aspnet_Membership_FullAccess GRANT EXECUTE ON dbo.aspnet_Membership_UnlockUser TO aspnet_Membership_FullAccess -- --View rights -- GRANT SELECT ON dbo.vw_aspnet_Applications TO aspnet_Membership_ReportingAccess GRANT SELECT ON dbo.vw_aspnet_Users TO aspnet_Membership_ReportingAccess GRANT SELECT ON dbo.vw_aspnet_MembershipUsers TO aspnet_Membership_ReportingAccess /*************************************************************/ /*************************************************************/ /*************************************************************/ /*************************************************************/ DECLARE @command nvarchar(4000) SET @command = 'REVOKE EXECUTE ON [dbo].aspnet_RegisterSchemaVersion FROM ' + QUOTENAME(user) EXECUTE (@command)

**Comment by sleupold** [comment]
this sounds like missing permission of the installing SQL user, did you make sure to check the "owner" option on the install wizard page?

**Comment by david-poindexter** [comment]
@dush-a In addition to what @sleupold said, please check to make sure the database user has "dbowner" rights to the database.  This can be done via mappings in the user properties is SQL Server Management Studio.

**Comment by david-poindexter** [comment]
Since it is a shared hosting environment, you may have to contact support for this.  When Plesk is used for their control panel, the typical default DB user permissions do not have `dbowner` rights.

**Comment by dush-a** [comment]
> this sounds like missing permission of the installing SQL user, did you make sure to check the "owner" option on the install wizard page?

Yes, I did. It was selected by default as well.

**Comment by dush-a** [comment]
> Since it is a shared hosting environment, you may have to contact support for this. When Plesk is used for their control panel, the typical default DB user permissions do not have `dbowner` rights.

@david-poindexter, OK. This might be the solution, I will contact the support. Thanks

**Comment by dush-a** [comment]
After contacting the hosting support, they added the `dbowner` rights. The issue is now fixed.
