### ISSUE TITLE
DNN PLATFORM v. 09.09.00 (0) New Language Dropdown List Limitation

### ISSUE THREAD

**Issue by DHCuthill** [dnnsoftware/Dnn.Platform#4549]
DNN PLATFORM v. 09.09.00 (0) New Language Dropdown List Limitation to First 5 Languages
**Conditions:**
I have a new, empty instance of DNN.  Full product Install.
I cannot add a New Language from the New Language / Language Dropdown
Reason:
There are only 5 languages from the top of the Alphabetical list.
The Language Dropdown list does not scroll.
Is there something I can do to correct this?  
I have now uploaded the DNN Platform 9.9.0 Upgrade and it made no difference.  It didn't even run the Install Wizard.

Acceptable workaround:
I want to make en-GB available.
Can anyone recommend an en-GBlanguage file? My search has proved fruitless.

**Comment by valadas** [comment]
I can scroll that list myself, can you specify the browsers you have tried this on:

![image](https://user-images.githubusercontent.com/6371568/110251732-e3726100-7f4f-11eb-8a59-adb19922664f.png)

I don't think en-EN is a valid language code, I would think this to be en-UK maybe ?

**Comment by valadas** [comment]
Also, en-US is the default system one and if you setup any other en-xx one it falls back to the system default, then you can customize it if you se want for a specific localized variant of english but I am not aware of any available on, most of the ones I saw where for non-english languages...

**Comment by DHCuthill** [comment]
Valadas
Many thanks for your comment.
You are correct.  I meant en-GB
I have, in the dim past taken an en-US file and converted it to en-GB
I might try that this time.

**Comment by valadas** [comment]
Yeah, many of those controls where not made for accessibility much... Unfortunately.

**Comment by DHCuthill** [comment]
This topic is answered and can close.  It should be kept available for those who have the same problem in finding the scroller for the New Language Dropdown List in DNN.
