### ISSUE TITLE
Bug Report DNN PLATFORM v. 09.09.00 (0) Redirect After Logout/Redirect After Login

### ISSUE THREAD

**Issue by DHCuthill** [dnnsoftware/Dnn.Platform#4551]
Bug Report DNN PLATFORM v. 09.09.00 (0) Redirect After Logout/Redirect After Login
Setup:
I create new pages for "YouLoggedOut" and "Social"
In Site Settings/ Site Behavior/ Default Pages, I set:
 "Redirect After Logout" to "YouLoggedOut"
  "Redirect After Login" to "Social"

Test
1) I log out and the Redirect after logout page appears (YouLoggedOut).  **Test = Pass**
2) I log back in and Redirect After Login page (the "Social" page) fails to appear. 
3) State is: User is logged-in, but the Redirect After Logout page remains on screen. Redirect After Login page does not appear.
**Test = Fail**
_Attempted work-around:-_
I tried to adjust the Permissions such that Registered Users were denied access to the Redirect After Logout page (YouLoggedOut).  However, the (YouLoggedOut) page still appears, but it carries the message "You do not have access to view this page within the site."
**Test = Fail** I expected the YouLoggedOut page not to appear, and the "Social" page to be the redirect.

Any comments?

**Comment by sleupold** [comment]
are you running a single langauge or a multilingual site (#4311) ?

**Comment by DHCuthill** [comment]
Hi Sebastian.  It has en-US and en-GB so, yes.  It's multilingual.  I'll pursue that angle.  Many thanks.
Is there anything specific I should check?  The pages are showing the correct url for en-GB

https://myconstituency.online/en-gb/YouLoggedOut

However the  Home Page shows simply as https://myconstituency.online/en-gb/

If I set permissions on the "YouLoggedOut" page to Block Registered Users, but Allow "All Users" I get this when I log in again:
https://myconstituency.online/en-gb/YouLoggedOut/ctl/Access%20Denied/message/d454797a46b34504a1ed7878f9486172
