### ISSUE TITLE
Create DotNetNuke Library Package for MailKit

### ISSUE THREAD

**Issue by mitchelsellers** [dnnsoftware/Dnn.Platform#4563]
## Description of problem
A new library package should be created to contain the MailKit, MimeKit, and associated references so they can be installed during installation, rather than included during the build process. 

Additionally, the Cake build script should also exclude these files from the Upgrade package

## Description of solution
Creating a package will prevent upgrade issues for those that have existing versions of these dependencies.

## Additional context
This solution was discussed during the TAG meeting as a solution for the current upgrade issues impacting those with certain users of third-party modules

**Comment by sleupold** [comment]
shouldn't both providers be moved into separate packages, allowing admins to select which one to install?

**Comment by mitchelsellers** [comment]
@sleupold At this point, we are working to solve the immediate concern, without breaking existing.
