### ISSUE TITLE
/tabid/0/language/en-US/Default.aspx returning 404 after login and logout

### ISSUE THREAD

**Issue by eXistenZe** [dnnsoftware/Dnn.Platform#4578]
## Description of bug
Multilang site, fresh 9.9 install.

## Steps to reproduce
Login or logout.

## Current behavior
After login or logou, DNN goes to /tabid/0/language/en-US/Default.aspx and returns 404

## Expected behavior
Page resolves.

## Affected version
* [ X ] 09.09.00 latest supported release

## Affected browser
* [ X ] Chrome
* [ X ] Firefox
* [ ] Safari
* [ ] Internet Explorer 11
* [ X ] Microsoft Edge (Classic)
* [ ] Microsoft Edge Chromium

**Comment by valadas** [comment]
I have not experienced this, do you have any steps to get into that situation starting from a clean install ? TabId=0 is definitelly strange as I am pretty sure that ID starts at 1. The fact you see Default.aspx makes me think this is probably an upgrade from an older version. Do you have any clues about what other factors play into this (steps to reproduce) ? Also can you check if you have any interesting logs either in the Admin Logs module or in the Portals\_default\logs folder...

**Comment by eXistenZe** [comment]
Fresh 09.09 install.
After setting a page to redirect after login and logout, and then removing it, I can no longer reproduce this.
There were no errors on the logs.
All I did was activate both languages in alias (/pt-pt and /en-us) and content localization, creating a new home page, localized, setting the new page in site settings, and removing the default one.

Feel free to close this and I'll add new info if this comes up again.

Thanks.

**Comment by sleupold** [comment]
Please run the following SQL code and restart DNN:
DELETE FROM dbo.PortalSettings WHERE SettingName IN (N'Redirect_AfterLogin', N'Redirect_AfterLogout', N'Redirect_AfterRegistration') and SettingValue = 0

**Comment by eXistenZe** [comment]
Those settings do not exist from this portal. Only if I set a page to redirect to.

**Comment by sleupold** [comment]
if you specify one redirect page for a site, it looks like DNN is adding additional other ones with inappropriate values. 
My SQL statement above should fix it.

**Comment by eXistenZe** [comment]
This is what I have.
Portal 0 was the one causing the issues. It's fine now. Portal 1 also seems fine, but the settings are duplicated.

PortalID	SettingName	SettingValue
0	Redirect_AfterLogin	-1
1	Redirect_AfterLogin	66
1	Redirect_AfterLogin	66
1	Redirect_AfterLogout	66
1	Redirect_AfterLogout	66
0	Redirect_AfterLogout	-1
0	Redirect_AfterRegistration	0
1	Redirect_AfterRegistration	0

**Comment by sleupold** [comment]
@eXistenZe ,
please be aware that SiteSettings in multilingual sites exist per language.

**Comment by eXistenZe** [comment]
Ok. This is definitly related to the site settings.
Yesterday I changed the 404 Error Page to none specified so that the crawlers get a proper 404 and remove ancient pages.
Today I get this error during login (after filling the form).

![image](https://user-images.githubusercontent.com/26518879/114009958-8a9e2d00-985b-11eb-9953-25c54c7feaa7.png)

![image](https://user-images.githubusercontent.com/26518879/114010116-af92a000-985b-11eb-9f70-9a792c3b4c98.png)

These are my db values:
![image](https://user-images.githubusercontent.com/26518879/114010633-3c3d5e00-985c-11eb-8b44-7a3d638d622d.png)

If I close the form, it goes to tabid/0/language/pt-PT/Default.aspx and I get the 404. After logout the same thing.

**Comment by sleupold** [comment]
my SQL code above should fix it.

**Comment by eXistenZe** [comment]
It did, but am I supposed to run the query every time I change a setting?

**Comment by sleupold** [comment]
I haven't checked, when the settings are updated, but it looks like everytime the settings are stored, empty values for those special pages are stored as tabid = 0 instead of tabid = Null.
This needs to be fixed  in one of the next udates of DNN.

**Comment by cklenk** [comment]
We have noticed this happening on our dnn sites as well. We will try the above sql fix and report back.

Thanks

**Comment by cklenk** [comment]
Update: That script does fix the issue, but once you make a change to site settings the issue comes back.

Thanks

**Comment by sleupold** [comment]
A pull request had been submitted a few days ago, which should fix it. 
It will be included in next version of DNN Platform.
