### ISSUE TITLE
Site groups not working (personna bar persistence and the second portal not showing if the site group is removed)

### ISSUE THREAD

**Issue by eXistenZe** [dnnsoftware/Dnn.Platform#4580]
## Description of bug
This issue happened to me a while ago, but I thought it was something I misconfigured, and I didn't need site groups that much, so I gave up.

Now I have a fresh 09.09 install, and this still occurs, in a different server, so it should be some issue with site groups itself.

## Steps to reproduce
List the precise steps to reproduce the bug:
1. Install DNN 09.09
2. Not sure if this is related, but I have content localization enabled with /pt-pt and /en-us
3. Create a second portal with a different domain, also content localized
4. Enable site groups and add the second site

The first issue I noticed, is that when I reload a page, the persona bar menu always opens. I can close it, but as soon as I open another page, the menu opens again.

I then removed the site group, and the first issue is solved.
However, I can no longer create a site group again, since the second portal does not show on the list (the top dropdown menu or the selectable list after).

## Affected version

* [ ] 10.00.00 alpha build
* [ X ] 09.09.00 latest supported release

## Affected browser
* [ X ] Chrome
* [ X ] Firefox
* [ ] Safari
* [ ] Internet Explorer 11
* [ X ] Microsoft Edge (Classic)
* [ ] Microsoft Edge Chromium

**Comment by valadas** [comment]
Duplicates #4574

**Comment by valadas** [comment]
Also there is a workaround documented in #4574 until that issue is fixed

**Comment by eXistenZe** [comment]
@valadas please note that this would fix the second issue, but not the first.

**Comment by valadas** [comment]
Hmm, the first issue is not happening to me, would you mind opening a new issue just for that situation with a very clear step by step to go from clean install into this situation... Just to keep it clean and separate from the duplicate issue and so a developer car clearly make it happen to troubleshoot...
