### ISSUE TITLE
Improve the Security Analyzer

### ISSUE THREAD

**Issue by eXistenZe** [dnnsoftware/Dnn.Platform#4581]
## Description of problem
I will try to explain this as simply as I can.
My site was hacked. I have no idea how. I don't have file upload anywhere. I don't have public user registration. My passwords are changed frequently. Nevertheless, my site was hacked.

After seeing the first signs (webmaster tools adding admins to my sites), I searched my files and noticed quite a few unexpected root files (fast.aspx, google.asp, jcss.aspx, ror.xml, sitemap.xml, x.asp, etc.).

Since they kept my sites fully functional, I have no way to pinpoint a good backup date. I have no idea when this started, or what else they accessed. I had no other way than to perform a clean install and start importing everything, page by page, checking everything in the process. This will take months.

## Description of solution
Running the Security check obviously returned the file extension issues. But how frequently do you actually should run the check?
And is this check enough? There is so much more the tool could do, namely:
- Run through the scheduler, let's say daily;
- Send the report through e-mail;
- Search changed core DNN files (hash, size, whatever);
- Search added files to the root folder (or other folders that should not have them);
- Report these files in the log sent by e-mail;
- And probably so much more, like searching common attack vectors (allowed file extensions, DB settings, super users actions, changed settings, etc).

I'm not an expert on security (or anything else, I'm a nurse), so these are just my 5cents contribution to something that could help the community.

Thanks.

**Comment by jeremy-farrance** [comment]
Just my 2 cents...
 
This is sounding more like an opportunity for an external module by a vendor. I am kinda surprised we haven't seen this already at least in a rudimentary form. WordPress has an amazing set of these add-ons; has a look at Wordfence, WPMU Defender Pro, Securi, BulletProof, etc.
 
However, 

- I do believe the built in security analyzer needs some TLC 
- and your idea about having it run on a schedule and send the result to the site administrator is **OUTSTANDING** and very much needed.

**Comment by miguelvaz78** [comment]
Hi @eXistenZe,

I also have been hacked somehow. Most of my sites (different hosting accounts and different domains) have been showing new files appearing (same files as you mention).
One thing I noticed was a 404.asp file in all of my sites that allows code execution from a querystring parameter.
Also was able to find that this file exists in other domains that use DNN and are not managed by me in any way. They just share the same hosting provider.
In some of my hosting accounts I have sites that use other CMS technologies and this does not seem to be affected.

Have you figured out any point of compromise?

I will followup on this if I find more related info.

Cheers
Miguel Vaz

**Comment by eXistenZe** [comment]
These sites were like 2 years old.
Who knows what kind of vulnerabilities it had from so many extensions installed and removed.
I have a feeling about a certain company from which I installed some modules, but I can not point a finger with no proof.
There are also many other possibilities. Perhaps some DNN vulnerability now yet disclosed?
Sory if I cannot help @miguelvaz78
