### ISSUE TITLE
Disabling password strength meter does not disable it in the password reset form

### ISSUE THREAD

**Issue by lanthonyneville** [dnnsoftware/Dnn.Platform#4595]
## Description of bug
If the Enable Password Strength Checking setting is disabled, this implies the meter is not used anywhere in DNN. It is disabled in the user registration form however it is NOT disabled in the password reset form.

## Steps to reproduce
1. Go to Settings > Security > Member Accounts > MEMBER MANAGEMENT
2. Set Enable Password Strength Checking to OFF
3. Click SAVE
4. Log out and generate a password reset email
5. Follow the password reset link and enter a new password in the password reset form
6. The password strength meter (and Password Policy popup) is displayed

## Screenshots
![image](https://user-images.githubusercontent.com/22200046/113777104-8cb0a080-9722-11eb-9155-9e2cef701c79.png)

## Affected version
* [ X ] 09.08.01

**Comment by lanthonyneville** [comment]
I am assuming this is fixed, given the PR from @yog-it . Thanks!

**Comment by valadas** [comment]
Correct
