### ISSUE TITLE
If Password Strength Regular Expression used, Password Policy popup is unintelligible to average user

### ISSUE THREAD

**Issue by lanthonyneville** [dnnsoftware/Dnn.Platform#4596]
## Description of problem
If a Password Strength Regular Expression is used (set in web.config, and visible under Settings > Security > Member Accounts > REGISTRATION SETTINGS), and Enable Password Strength Checking is enabled (under Settings > Security > Member Accounts > MEMBER MANAGEMENT), then this expression is shown on the Password Policy popup (e.g. on user registration form). A regular expression is meaningless to 99.9% of end users and causes confusion.

## Description of solution
The solution is not obvious, because if a Password Strength Regular Expression is used, there needs to be some kind of notification that "advanced" password checking is enabled, but there is nothing in regular language that can be said.
Suggested solution - in addition to the indication of Min Password Length and Min Non Alphanumeric Characters, state "Additional password complexity checks are in effect - please contact your site administrator if you have questions"

## Screenshots
![image](https://user-images.githubusercontent.com/22200046/113778187-0301d280-9724-11eb-94f2-05b9b58836a7.png)

## Affected version
* [ X ] 09.08.01

**Comment by bdukes** [comment]
This text is controlled by a localized resource, which includes a placeholder for the regular expression. You can (and should) override that text using the Languages editor (there's a nice blog post about using the language editor at https://dnncommunity.org/blogs/Post/6945/DNN-Details-003-Editing-DNN-Emails-Privacy-Terms-and-UI-Labels), to remove the regex placeholder and add a meaningful description. That text is in https://github.com/dnnsoftware/Dnn.Platform/blob/9f83285a15d23203cbaad72d62add864ab5b8c7f/DNN%20Platform/Website/App_GlobalResources/WebControls.resx#L168-L170.

We can still discuss changing that text by default, or providing other ways to manage this, but I think this is the best solution for you right now.

**Comment by lanthonyneville** [comment]
> This text is controlled by a localized resource, which includes a placeholder for the regular expression. You can (and should) override that text using the Languages editor (there's a nice blog post about using the language editor at https://dnncommunity.org/blogs/Post/6945/DNN-Details-003-Editing-DNN-Emails-Privacy-Terms-and-UI-Labels), to remove the regex placeholder and add a meaningful description. That text is in
> 
> https://github.com/dnnsoftware/Dnn.Platform/blob/9f83285a15d23203cbaad72d62add864ab5b8c7f/DNN%20Platform/Website/App_GlobalResources/WebControls.resx#L168-L170
> 
> .
> We can still discuss changing that text by default, or providing other ways to manage this, but I think this is the best solution for you right now.

That's great! I have done as you suggested.
I do think the out-of-the-box text ought to be more friendly - even the most hard-core developer would have a hard time interpreting a regular expression.

**Comment by lanthonyneville** [comment]
The workaround from @bdukes worked well for me, so closing this.
