### ISSUE TITLE
Tooltip site groups not visible

### ISSUE THREAD

**Issue by Tychodewaard** [dnnsoftware/Dnn.Platform#4600]
Provide a clear and concise description of the bug.
The tooltip for 'authentication  domain' falls behind the row above

## Steps to reproduce
- go to site groups
- click on the information icon

## Expected behavior
to be able to see the text

## Screenshots
If applicable, provide screenshots to help explain the bug.
![image](https://user-images.githubusercontent.com/9091997/113985961-ffb63600-984c-11eb-9bca-a5f5dbd6ee5c.png)

## Affected version
* [x] 09.09.01RC

**Comment by Mhtshum** [comment]
@valadas @bdukes  please assign `type` and `milstone` . As it is failing manageable action.
