### ISSUE TITLE
Site group not visible until reloading the page

### ISSUE THREAD

**Issue by Tychodewaard** [dnnsoftware/Dnn.Platform#4601]
## Description of bug
If you create a site group, the page remains empty. If you refresh the page, you see that the page group has been created.

## Expected behavior
After creating, I expect to show the site group. Pretty much like you create a page or a user.

[x ] 09.09.01RC

**Comment by valadas** [comment]
I did not experience this, do you mean if you go to site groups, then you go to sites to create a site and then come back to the site groups it's not listed until a refresh. If it's that it's a more widespread issue, basically the data get's fetched on load of a persona bar module, when switching from module to module, the one you leave stays there and does not get unloaded, just hidden. This is overall true in all the persona bar modules.

**Comment by Tychodewaard** [comment]
Yeah, I expected the same behaviour as 'new site'. So, after adding a site the list of sites refreshes and shows the new site. 
I just wanted to replicate and record this for 'site groups' but this time it worked as expected...

So, I'll close this issue and check in whgen/if it happens again.
