### ISSUE TITLE
Improve logged details for password sent failure event

### ISSUE THREAD

**Issue by jcmrva** [dnnsoftware/Dnn.Platform#4605]
## Description of problem
Our site uses the standard DNN Authentication module. After a recent upgrade to Evoq 09.06.04, we began experiencing some issues related to user logins.

The most puzzling of those is the PASSWORD_SENT_FAILURE event, which appears to occur in the DNN Platform code.

- The message suggests possible success but the user does not receive the email.
- No corresponding entries are found in the DNN exception log.
- The SMTP server is confirmed to be working and has no additional information corresponding to the logged timestamps.
- If the user's email is known (sometimes they contact support), we're able to look at their account details, but a comparison of those vs. another account (which has no problems logging in) reveals nothing. It's not a simple issue of the email being entered incorrectly.

## Description of solution
Include, at minimum, the email address that was used in the request, but anything that would indicate the root cause would helpful.

## Screenshots
![DNN password sent failure](https://user-images.githubusercontent.com/20140997/114589609-d4b95100-9c55-11eb-9f42-a3734441809f.png)

## Affected browser
All, probably.

**Comment by valadas** [comment]
Are you able to reproduce the issue on the latest platform version (please follow the issue template)

**Comment by jcmrva** [comment]
I wouldn't know where to begin (and I used the enhancement template because that's what I'm looking for).

**Comment by valadas** [comment]
Oh, just realized this may have been so old that it was before we had templates. So basically does this happen on the latest Dnn Platform release ?

**Comment by jcmrva** [comment]
We just recently upgraded (with a great deal of difficulty) to Evoq 09.06.04.

**Comment by valadas** [comment]
Yes, but what we are looking for here is to know if this happens on the currently latest published version of DNN Platform. Evoq is based on earlier versions for one and also they have some things different regarding users. So first step is to know if it happens on Platform and exact steps to reproduce the issue on it. Then a developer can pick it up and easily make it happen and move the issue forward into a solution. If it only happens on Evoq then that should be an Evoq support request instead of an issue here...

**Comment by sleupold** [comment]
what are your settings for password format and retrieval?
If passwords are stored as hash value (they should be), retrieval is not supported - only an email with password reset link.

**Comment by jcmrva** [comment]
They are stored as a hash & the email only has a reset link.

**Comment by jcmrva** [comment]
The source of these log entries turned out to be simple once I traced it all the way through: an email address was submitted that does not match a user in the current portal.

https://github.com/dnnsoftware/Dnn.Platform/blob/6d9b526b481decc7d156cc621e8dbd0913b70c7c/DNN%20Platform/Website/admin/Security/SendPassword.ascx.cs#L311

After the lookup above, `arrUsers` is empty and `_user` is null, so it reaches the else block.

https://github.com/dnnsoftware/Dnn.Platform/blob/6d9b526b481decc7d156cc621e8dbd0913b70c7c/DNN%20Platform/Website/admin/Security/SendPassword.ascx.cs#L273-L281

...but _userCount is not greater than 1, so it fails to send without explaining why.

For admins for a multi-portal instance, it would be useful to know if someone is trying to reset their password from the "wrong" form, or is missing profile data. For a user who just typo'd their email, having it appear in the message gives them a chance to realize their mistake.
