### ISSUE TITLE
Add ability to set max upload size in the UI

### ISSUE THREAD

**Issue by donker** [dnnsoftware/Dnn.Platform#4609]
## Description of problem
IIS limits the maximum upload size that a user can upload to a site. This is set in the web.config. I still get support requests from people who are confused by the error message they get when trying to upload something too big and find the documentation about fixing this too technical.

## Description of solution
It would be fairly simple to surface the current set MaxRequestLength to the UI under Servers > Server Settings > Other (new tab).

**Comment by mitchelsellers** [comment]
Although I understand the request, I am not a fan of exposing this as an easy-to-change configuration element for a number of reasons as I've documented in prior issue reports.

1. Changing this value will result in an application restart, which has two ramifications.  (A; We would ONLY want to persist the value if the value had changed, which is not our standard.  B: The user experience and impact to making this change will impact site performance and could cause outages.)
2. There are security implications of expanding this value, and long-term high values is strongly discouraged.
