### ISSUE TITLE
Resource Manager Enhancement - Add Alternate List View

### ISSUE THREAD

**Issue by jeremy-farrance** [dnnsoftware/Dnn.Platform#4611]
_Note that this is 1 of 3, split from the original Issue #4390 after the suggestion by @valadas._

## Description of problem
The current view of the folders and files in the new RM of DNN 9.08.00 (thru 9.09.01 so far) is very difficult to visually navigate, especially when there are large numbers of files and folders.

## Description of solution
Provide an option to switch to/set a more readable and compact list view, with full filenames visible including the extension. 

## Description of alternatives considered
For "round one" I would like to encourage this feature to happen sooner and use a rudimentary or simple implementation. There are a lot of industry standard examples out there. Using the old file manager as a basic starting point would be reasonable too? Just listing the files and folders in rows with a few basic click actions would help. Ideally, the list view could also include the "date last modified" column.

## Screenshots

Screenshot 1 - Resource Manager (current view)
![image](https://user-images.githubusercontent.com/653301/115085098-80b9a100-9ecf-11eb-8be6-ea3b39323b27.png)

Screenshot 2 - Existing Dnn File Manager 
![image](https://user-images.githubusercontent.com/653301/115086530-0cccc800-9ed2-11eb-8ab9-f8574ddcd4ac.png)
  
## Additional context
A use case where the current "Tile View" is a serious hinderance is when you have a large site with a lot of content. Just a few dozen rows of giant Tiles becomes difficult to navigate, especially with the currently truncated filenames.

## Affected browsers
* [x] All

**Comment by sleupold** [comment]
There should be at leat an option to choose the columns to be displayed in list view.
Ideal would be an option to use customizable templates.

**Comment by jeremy-farrance** [comment]
That is a really great example of things that could come later. Right now the need for a basic list view - IMHO - is very important. Adding these (and many other useful UI enhancements) will only slow down things by adding more work. Getting list view in place with the basics should really be the first, soonest-possible milestone.

**Comment by sleupold** [comment]
@jeremy-farrance 
I agree, but we should try to complete the desigred feature list now, because some of the mprovements might be much easier to add later, if prepared in the design now.

**Comment by jeremy-farrance** [comment]
Some bot calls it stale. I say it is both urgent and important. Who ya gonna listen to, me or the bot? :)

**Comment by valadas** [comment]
Well, stalebot does not say it is not important or urgent, it says it is stale (which it is).

But this will only happen if someone contributes it. This project is open source and driven by volunteers. This is a major time investment, so unless someone gets enough free time to tackle it or gets some serious sponsorship, we can just wait.

**Comment by jeremy-farrance** [comment]
## Looking for comments and feedback on this experiment. 

Side-stepping the List View for now, what about taking those giant Cards and reworking them - optionally - as small Tiles keeping all the other functionality in place?

**VIDEO**: [Dnn's Resource Manager with a Tiles Concept](https://accuraty-my.sharepoint.com/:v:/p/jfarrance/EaIZMY2JEsBBjx03LEGQZZsBhiPaMXs53Y_Yl6scjScU1Q?e=WusoIe)

![image](https://user-images.githubusercontent.com/653301/126096938-338c8964-b42a-463b-95b6-939eb5128d53.png)

**Comment by psmithson1** [comment]
We really need a basic list view for the new Resource Manager because we have tons of folders and files across many sites. It was the first thing I noticed and the first thing our customers noticed when we looked at the new functionality..."where is the list view". Kudos for removing the Telerik in the old file manager and getting to this point. Please don't stop investing in the new resource manager. It is a critical component and content administrators need usability. I've been supporting my clients using DNN since 2007 and was surprised this wasn't an original feature of the new Resource Manager. I think it's so important that I created a GitHub account just to make this comment. I really appreciate this community. You are an amazing group.

**Comment by mitchelsellers** [comment]
@psmithson1 Thanks for the feedback, we do know that this is a priority item

**Comment by valadas** [comment]
This has been delivered with v9.11.0
