### ISSUE TITLE
Resource Manager Enhancements - More Nice to have Features

### ISSUE THREAD

**Issue by jeremy-farrance** [dnnsoftware/Dnn.Platform#4613]
_Note that this is 3 of 3, split from the original Issue #4390 after the suggestion by @valadas._

## Description of problem
The Resource Manager, added as a "De-Teleriked" file management option in Dnn 9.08.00 is usable, but a lot of users quickly highlighted various deficiencies... or obvious opportunities for improvement. 

Assuming #4611 is a high priority to get delivered in some basic form soon, **_once that is complete,_** here are some additional feature suggestions to get the RM closer to being a first class, modern manager of files, folders, assets, and resources in Dnn.

## Description of solution

1. The List View could include the option to add/remove columns;  date added, last modified, size, properties, etc
2. The List View could add small helpful icons based on the file extension; these would just be typical things like PDF or an image for PNG, JPG... Dnn still has icons/symbols that could be used? (see below)
3. Add multi-select option for all/some/none selection of files and folders for batch options (like Move)
4. Add a click (not hover) activated Action dropdown menu for Move, Rename, Copy, Download
5. Add more actions like View, Edit, Get Link, Sluggify, etc
6. Allow for metadata management for both files and folders and have a standardized way for the info to be accessed and used elsewhere programmatically; simple things like Category (using Dnn Lists?), Title, Alt, and other things that could be used to enhance the file's SEO automagically when used
7. Option to show dimensions for images; width, height
8. A "details" view for a file should display additional info (created by/at, last updated by/at, file size, image dimensions, video/audio length, (editable) title, (editable) description and tags (thanks @sleupold)

## More Ideas?

Note that if you have additional ideas, please comment below and we can add to the list above. Especially if your suggestion make me #FACEPALM grumbling, "Why didn't I think of that?"

## Description of alternatives considered
I think a review of other popular File Management projects is in order. Take Material UI guidelines in to consideration and have a close look at what is useful about the various File Managers in projects like Joomla, SolidCP, etc. Projects like [FileBrowser ](https://github.com/filebrowser/filebrowser) could be a good reference point for both visual and functional ideas.

### Screenshot(s)

For 2, just keep it simple like the previous File Manager:
![image](https://user-images.githubusercontent.com/653301/115094235-6fc65b00-9ee2-11eb-9481-f988adf96e66.png)

## Affected browsers
* [x] All

**Comment by sleupold** [comment]
what icons are you looking for in your 2nd point?

**Comment by sleupold** [comment]
regarding the 3rd point, I would just ask for a multi-select option.
Implementation should depend on UI concept impemented, chackboxes are for sure one valid option

**Comment by sleupold** [comment]
a "details" view for a file should display additional info (created by/at, last updated by/at, file size, image dimensions, video/audio length, (editable) title,  (editable) description and tags.

**Comment by jeremy-farrance** [comment]
All 3 of your comments above are now added to the original issue. Thanks!!

**Comment by cgentryls** [comment]
Can you please read the #4573 issue I submitted? I believe the Resource Manager has a bug/issue. After you read #4573 can you test your DNN site, using my scenario, to see if you can replicate the issue?
