### ISSUE TITLE
CkEditor extraAllowedContent being ignored

### ISSUE THREAD

**Issue by Timo-Breumelhof** [dnnsoftware/Dnn.Platform#4620]
## Description of bug
The way to allow HTML that's not within the scope of the CkEditors toolbars does not seem to work any more.
Procedure: https://dnncommunity.org/blogs/Post/2841

## Steps to reproduce
List the precise steps to reproduce the bug:
1. Go an HTML module
2. Edit content
3. Switch the editor to Basic in the editor config
4. follow: https://dnncommunity.org/blogs/Post/2841
5. Try adding a table and save, open the Editor.

## Current behavior
The Table has been stripped form the HTML

## Expected behavior
One should be able to override de default editor behavior

## Affected version

* [ ] 10.00.00 alpha build
* [x] 09.09.00 latest supported release

@skamphuis Can you have a look at this please?

**Comment by skamphuis** [comment]
I'll have a look at that when I get a chance. From the work I did to upgrade CKE to the most recent version, I know there already were some options in the custom editor settings that were not actually used by the provider, and it could be very well possible that the upgrade to the newer CKEditor added more of those issues (where the option in custom editor config doesn't work).

**Comment by cklenk** [comment]
Related to https://github.com/dnnsoftware/Dnn.Platform/issues/4553 ?

**Comment by Timo-Breumelhof** [comment]
needs fixing, don't close :-)

**Comment by valadas** [comment]
I am not super familiar with this feature, is anyone working on this ?

**Comment by valadas** [comment]
As far as I know, the editor does not allow including any HTML that could not have been injected using the configured toolbar, so this may be by design ?

**Comment by skamphuis** [comment]
I'm not working on this, but I intend to. An option of CK Editor is to be able to allow certain HTML tags to be used. This option has been working (and used)  before, but stopped working with the upgraded CK Editor. This needs fixing. It's not even a hard one, but I got carried away by checking all other options too, because there seem to be a few more issues like this (options that work a little different in the newer CKE, and thus no longer work in DNN)

**Comment by valadas** [comment]
Cool, triaged and assigned

**Comment by Timo-Breumelhof** [comment]
@valadas We had a look and it's not a bug (I forgot to report that). There's just something that has changed, I adjusted my blog post accordingly
