### ISSUE TITLE
.DOTNETNUKE Cookie cleared on log in other browser/device (Active Directory Auth)

### ISSUE THREAD

**Issue by inu-web** [dnnsoftware/Dnn.Platform#4625]
### Describe the bug
If a AD User is logged in via AD on one device - lets say his Laptop via e.g. Chrome browser on the DNN Instance and the same user is connecting to the same DNN instance via an other device e.g. Tablet or Workstation (or even just another browser on the same device) - The User is logged off on the first device ...

### Software Versions
DNN: 09.06.01
DNN_ActiveDirectoryAuthentication Extension: 07.00.00
.NET FW: 4.7
### To Reproduce

Go to the webpage via webbrowser (e.g. Chrome) - User is logged in via AD on this device - OK ->Username is shown - User is logegd in
Open an other browser (e.g. edge chromium or firefox) - User is logged in via AD on this device - OK -> Username is shown - User is logged in
Open first browser (Chrome in this example) - NOK -> User is no more logged in in this browser / on this device - LoginLink is shown instead of username

### Expected behavior
The user should be still logged in in the other browser / on the other device - even if he/she logs in on an other device too...

### What we already tried/found out
This issue can be reproduced each time we try that on the client site.

We already posted this in the community forums - no response for weeks now (see: https://dnncommunity.org/forums/aft/2317) 

We also posted this as a AD-Module Github issue but after finding out the root of the problem we got the advise to post it here because the .DOTNETNUKE cookie is not deleted by AD-Module (see:  https://github.com/DNNCommunity/DNN.ActiveDirectory/issues/79) 

Sent an email to security@dnnsoftware.com but didnt get any response on this ...

...please help us to solve this 
thanks and kind regards
Don

**Comment by mitchelsellers** [comment]
This would most likely be due to the fact that the AD provider is resetting or otherwise adjusting the password and that act triggers a log out of the user in other locations.  User configuration settings as well with multiple webkit based browsers (Chrome/Edge) can sometimes result in odd behaviors.

Can you confirm, the behavior without AD in the mix?  The behavior will be slightly different if the users are "Administrator" or "Super User" level as well.  There is no custom code in the core that handles the AD provider, and the current AD provider was released well before the recent changes to user account management etc.

Lastly, I'm the one that monitors the security email, and I have no email in the inbox there, so not sure what happened with the email.

**Comment by inu-web** [comment]
Hi Mitchel
thank you very much for your answer. 
I tried the folllowing things now, to get closer to the problem, based on your advise:
- cleared cookies and everything in both browsers (saved/cached passwords, history, ...)
- closed both browsers (chrome and edge-chromium)
- deactivated the AD-Auth module via the "Enabled" checkbox in the module's configuration
- opened both browsers and log in in both via the standard dnn-login (.../login) with the same user account (no admin, no host roles ... just a couple of "normal" roles assigned - no AD User either for this useraccount - just a standard DNN user that was manually created in DNN )

**Result: The user keeps logged in in both browsers**
- cleared cookies and cache again and closed both browsers again
- re-activated AD-Auth on the server
- Go to the website again in both browsers on the client ... auto login from AD took place in both browsers ...

**Result: The user gets logged out in the first browser approximately 2 seconds after logging in on the second browser**
So I think we proved now it has something to to with the AD Module or configuration - right?

Just to I deactivated the "synchronize role on each login" setting in AD-Module config  
- again cleared cookies and cache
- cleared server cache and restarted application
- opened both browsers ... go to website ...

**Result: Same as above ... logged out again in first browser after logging in in second browser**
So: it has nothing to do with this setting too...

If I understand your answer right, I have to post this again to the AD-Modules Github-issues and try to find more help there

Thank you very much again for your advise
kind regards

**Comment by mitchelsellers** [comment]
Yes, based on this, it would be due to something that the AD Provider is doing with the accounts etc that trigger a change in the user account.  Most likely adding or removing roles, or something else that would adjust the cookie structure.

Closing this for now.

**Comment by inu-web** [comment]
Hi Mitchel
thank you for your efforts and responses!
regards
Gerald
