### ISSUE TITLE
fb share not working properly

### ISSUE THREAD

**Issue by e1-sistemi** [dnnsoftware/Dnn.Platform#4628]
## Description of bug
When writing meta tags (facebook fe.), closing tag (slash) has been stripped. This results with facebook being unable to see any of its meta tags, and proper social sharing is impossible.

## Steps to reproduce
1. Enter this in head `<meta property="og:title" content="title" />`
2. Result in sourcecode is: `<meta property="og:title" content="title">`

## Error information
This happens in version 9.9 while version 9.8 works as expected.
As much as I gathered, this affects also modules: StyleHelper from 40FINGERS and EeasyDnnNews.

## Affected version

* [ ] 10.00.00 alpha build
* [x] 09.09.00 latest supported release
* [ ] 09.08.00 latest supported release

## Affected browser
all

**Comment by bdukes** [comment]
How are you entering this tag in the head? Via the _Page Header Tags_ setting? Directly in `Default.aspx`? Or some other way?

Unless you're serving your site with an XHTML doctype (which would be unusual), having a `meta` element without a closing slash is completely valid HTML.

Perhaps you added the Open Graph attributes to the `html` element in `Default.aspx` and that change was overwritten by upgrading?

**Comment by e1-sistemi** [comment]
I am adding it in directly my header.ascx file (custom skin) using HtmlMeta object. I did tried that manually too and throught StyleHelper object and also OpenGraph - VDWWD plugin.
Nothing passes FB Sharing debugger.

I have other site example, with same site is on 9.8 (production) and 9.9 (test env). On production site stripping issue happened to also to those other 3rd party modules I mentioned (EDN and StyleHelper).

I understand it is valid, but for some reason, facebook debugger doesn't recognize them correctly.

Maybe I am missing something, I'll look deeper into it.
I'll check better mac/win combinations with various browsers.

So nobody else has issue with fb sharing on 9.9. You get your picture, description, titles all fine? Fb Sharing Debugger all clear?

**Comment by e1-sistemi** [comment]
If you care, try sharing these links on facebook (preview should be enough):
(9.9) https://hhi.test.sistemi.hr/vijesti/novo-izdanje-publikacija-adriatic-sea-pilot-volume-i-i-adriatic-sea-pilot-volume-ii
(9.8) https://www.hhi.hr/vijesti/novo-izdanje-publikacija-adriatic-sea-pilot-volume-i-i-adriatic-sea-pilot-volume-ii

In my case, 9.8 results with image, title, description ... but 9.9 with some weird data and no image. Those are two same sites, just different DNN version.

**Comment by e1-sistemi** [comment]
I renamed issue, as I am not sure any more it is because of closing tags.
I compared sources for both test and production site and they (except site name) seems identical.

However, when you try to share each of them I get this as a result
![compare](https://user-images.githubusercontent.com/70143983/116368278-6ef9c700-a808-11eb-93fa-90b76dc05112.jpg)

facebook debugger for hhi.test site report this error:
Missing properties: The following required properties are missing: og:url, og:type, og:title, og:image, og:description, fb:app_id

... I am completely lost now.

**Comment by bdukes** [comment]
I did have to bypass the invalid certificate to view your test site, that may be the difference.

**Comment by e1-sistemi** [comment]
@bdukes seems you are right. This could be issue. Seems like fb/debugger ignores and reports meta tags missing if there is an issue with SSL certificate.
I would expect it to find them and inform they won't be shared but ...

Thank you very much man. I consider this "issue" solved.
