### ISSUE TITLE
Underconstruction page still shows old Dotnetuke logo

### ISSUE THREAD

**Issue by Timo-Breumelhof** [dnnsoftware/Dnn.Platform#4650]
## Description of problem
With autoupgrade turned off in web.config, you will be redirected to /Install/UnderConstruction.htm after you copied the upgrade files over the site.
This page shows the old DotNetNuke logo

## Description of solution
Change the log to the DNN logo

## Description of alternatives considered
Provide a clear and concise description of any alternative solutions considered.
The screenshot is from an upgrade to 9.9.1

## Screenshots
![image](https://user-images.githubusercontent.com/8999382/117133375-6ecb6f80-ada4-11eb-94f9-63f93d7efbe6.png)

**Comment by sleupold** [comment]
Ideally, the page should use the site logo, not any product specific icon or layout,

**Comment by sleupold** [comment]
btw. I don't think, an error page is a great place for product place,emt :D

**Comment by valadas** [comment]
Yes and from a security perspective I would not even display anything DNN specific (removing the logo completelly), using the site logo would probably not be possible considering we support multiple sites per instance. So my vote would be to just remove it IMO

**Comment by sleupold** [comment]
usually, it should be possible to derive logo from domain address (i.e. alias bount to a portal)

**Comment by valadas** [comment]
True

**Comment by joshgk00** [comment]
Do we want to try to derive the logo or just remove it?

**Comment by mitchelsellers** [comment]
I think we should just remove the logo, this is an under construction page that could show up for a number of issues, no need for a logo IMHO.

**Comment by jeremy-farrance** [comment]
I hate to introduce more work, but just an additional thought which I hope is a simple enough change/addition with huge RIO:.

Add this file to the list of files editable via Settings / Configuration Manager - that way it becomes a feature and setting that will "surface itself" and people can then edited as needed as well as become aware of the case(s) in which the files might be displayed.
 
In the updated version of the .htm file, include some HTML comments that self-document things. Even just a simple, `<!-- this page only displays when ... --!>` would prevent a lot of future questions and discussions.
 
And yeah, I agree with leaving the logo out. The page should be site and cms agnostic and state why you are seeing it as simply as possible.

**Comment by mitchelsellers** [comment]
This page has to be static, without any dynamic bits

**Comment by sleupold** [comment]
we might still include a static image, which might easily be replaced by the host user (for all sites of the DNN installation though).

**Comment by Timo-Breumelhof** [comment]
> @mitchelsellers 
> 
> This page has to be static, without any dynamic bits

Agreed, don't over complicate things just add the path to the correct "new" logo.
If a company does not want that, they can remove / replace it as @sleupold suggested

**Comment by jeremy-farrance** [comment]
And more work, while you are in there, add a /Humans.txt file and hook it up for editing via Settings / Configuration Manager. :)
 
[The Humans.txt Initiative](Settings / Configuration Manager)
