### ISSUE TITLE
Sitemap placeholders in robots.txt in multisite scenario

### ISSUE THREAD

**Issue by Tychodewaard** [dnnsoftware/Dnn.Platform#4651]
## Description of problem
The robots.txt expects a sitemap: https://www.domain.com/sitemap.aspx
And the default robots.txt also has a placeholder for this.
But if you have multiple sites in a DNN, you want to include multiple sitemaps. If I am understand https://www.sitemaps.org/protocol.html#submit_robots correctly, this is ok. 

## Description of solution
I think it could be an idea to include a second sitemap placeholder to make it more explicit that you can use those in multi site scenarios

**Comment by sleupold** [comment]
@Tychodewaard 
Are you talking about multi-domain sites (where each domain needs its own stemap) or a site group with sub-websites (eg. domain.com/marketing, domain.com/sales, domain.com/resellers...)?

**Comment by Tychodewaard** [comment]
www.domaina.com/sitemap.aspx
www.domainwooha.org/sitemap.aspx

can be from the same DNN.
In the examples they show multiple sitemaps on the same site so not 100% sure whether it is also allowed on seperate sites.

**Comment by jeremy-farrance** [comment]
For those reading this that need a current solution, IIS rewrite rules in web.config are an easy (depending on your skillset) solution and covered both well and recently by Will, here; [Robots.txt & Multi-Site Dnn Instances](https://upendoventures.com/Blog/dnn-summit-session-multi-site-dnn-instances-and-robotstxt) (from the recent Dnn Summit 2021).

**Comment by sleupold** [comment]
@jeremy-farrance 
That's fine for robots.txt, but DNN generates /sitemap.aspx for any site in a multisite DNN nstallation with appropriate content.
@Tychodewaard 
support for multiple sitemaps is helpful, if you need additional pages being crawled - either .html files or dynamic content not included in DNN sitemap for any reason, e.g. rom 3rd party modules without a search index provider.
