### ISSUE TITLE
why Request.IsAuthenticated is false in callback gateway?

### ISSUE THREAD

**Issue by mansourn** [dnnsoftware/Dnn.Platform#4652]
hi
When the user logs in dnn, the value of the Request.IsAuthenticated is true
As soon as the user connects to the banking portal gateway and returns to the site from the gateway again, the value of Request.IsAuthenticated becomes false!
And it causes the user's DNN and anonymity and again display login  button.

Changing the page also solves the problem and again the value of Request.IsAuthenticated becomes true

**Comment by mitchelsellers** [comment]
Can we get a code example of what you are doing?

**Comment by mansourn** [comment]
There is no code!
just post user to gateway and user after pay , return to callback address.

**Comment by mansourn** [comment]
after user callback to dnn display again  login button!
While the user had logged in before going to the gateway

**Comment by jeremy-farrance** [comment]
Is it possible that you have multiple Alias variations? Maybe both root and `www` available? This might happen if you are authenticated on the `www` alias and then the callback address is to the root (no www).

**Comment by mansourn** [comment]
my address 
http://localhost:7263/en-us/

**Comment by soheilkheiri** [comment]
We have the same problem.

Authentication is lost after the callback. But once refreshed, it is authenticated.

**Comment by mansourn** [comment]
Cookie ".DOTNETNUKE" is not in the list of C # cookies in callback!
