### ISSUE TITLE
CKEditor is not defined in 9.9.1

### ISSUE THREAD

**Issue by Ceten** [dnnsoftware/Dnn.Platform#4656]
## Description of bug
Since upgrading our website earlier this week from DNN 9.8.1 to 9.9.1 the CKEditor no longer works.
When editing a html module the editor doesn't load anymore. I checked the console and saw some errors mentioned below.
I think the Uncaught SyntaxError in ckeditor.js is causing the other errors.

## Steps to reproduce
Click on 'edit content' to edit a html module.

## Current behavior
The html editor doesn't load.

## Expected behavior
The html editor loads and allows editing of the html module.

## Screenshots
![afbeelding](https://user-images.githubusercontent.com/1673675/117470389-08d31980-af57-11eb-8ac0-6b2650de4b0a.png)

## Error information
![afbeelding](https://user-images.githubusercontent.com/1673675/117470298-f062ff00-af56-11eb-8c12-903434b66eb1.png)

## Affected version

* [ ] 10.00.00 alpha build
* [x] 09.09.01 latest supported release

## Affected browser

* [x] Chrome
* [x] Firefox
* [ ] Safari
* [x] Internet Explorer 11
* [ ] Microsoft Edge (Classic)
* [x] Microsoft Edge Chromium

**Comment by Ceten** [comment]
Thanks for leaning in. I should have mentioned I've read the thread from that issue before creating a new one but I only had 'dnnpages' for the ExtraPlugins setting in both the GUI and /portals/0/Dnn.CKEditorSettings.xml so I'm afraid there is something else going on here.

**Comment by james7342** [comment]
Ok. Just wanted to make sure they weren't related.

**Comment by Ceten** [comment]
Anyone has any clue on what could fix this?
I already tried replacing the files in /Providers/HtmlEditorProviders/DNNConnect.CKE/js/ckeditor/4.15.1 with those in /Providers/HtmlEditorProviders/DNNConnect.CKE/js/ckeditor/4.5.3 and tried reinstalling the plugin with the zip file from the install folder of the DNN 9.9.1 plugin (DNNConnect.CKEditorProvider_09.09.01_Install.zip) but both didn't fix the issue...

**Comment by Navilois** [comment]
Possible correlation to #4520 ?

**Comment by ChrisHammond** [comment]
I was able to fix my install by uploading the iframedialog and newsarticlelinks directories, afterwards I had to clear the server cache to get them to load properly

**Comment by james7342** [comment]
I think this one is/was related also. These all seem to be related to the "ExtraPlugins" settings and the actual plugins code folders. If the plugin is defined in ExtraPlugins setting and the folder doesn't exist you'll get the error(s).
https://github.com/dnnsoftware/Dnn.Platform/issues/4536

**Comment by Ceten** [comment]
I'm not sure this is related to the extraplugins setting as our install only had the 'dnnpages' plugin. For now we have reverted to the previous version.

**Comment by james7342** [comment]
Ok. I think Chris's issue though is/was related.

**Comment by Ceten** [comment]
The pas weeks I did some more digging into this as I need to update this site to the latest version.
I traced the errors to the ckeditor.js file in Providers/HtmlEditorProviders/DNNConnect.CKE/js/ckeditor/4.15.1 .
Apparently this file was different from the one in the installer package for both 9.9.1 and 9.10.1.

I fixed this by replacing the file with the one in \DNN_Platform_9.10.1_Upgrade\Install\Provider\DNNConnect.CKEditorProvider_09.10.01_Install.zip\Resources.zip\js\ckeditor\4.15.1 yesterday evening at 22:40, clearing the cache on the website, restarting the application and clearing the local cache in my browser as well.
![afbeelding](https://user-images.githubusercontent.com/1673675/133386842-30258b8e-bf95-44f8-987b-fd5df8a8e07e.png)

This morning I noticed the html editor no longer works and the file was minified again. The las modified timestamp is at 23:17, although I haven't modified the file after 22:40.
![afbeelding](https://user-images.githubusercontent.com/1673675/133386968-e561e7f7-e032-4ca0-8000-fdcc12a594fe.png)

Is there some mechanism in DNN which minifies source files or could this be related to the website running on an Azure App Service?

**Comment by EPTamminga** [comment]
@Ceten Minification of .js and .css is an option that is set in the HOST settings, Server, Server settings, Performance settings: **Client Dependency Framework**.
I do not know if the Azure instal makes a difference.

**Comment by Ceten** [comment]
@EPTamminga thanks for the hint. I found these settings but all are disabled so it shouldn't change the original file I think?
![afbeelding](https://user-images.githubusercontent.com/1673675/133416287-3b5a5a1c-5fd9-432b-b06b-1e48fe17a0ae.png)

**Comment by bdukes** [comment]
There's nothing in DNN itself that would change that file (the minification controlled by those settings doesn't happen in place). Azure App Service can have multiple physical servers and would need to sync changes across those servers, but that would only apply if something is putting that "old" version out after the "new" version (in which case it's no longer the "new" version from Azure App Service's perspective). Is there any other file system syncing or anything?

**Comment by Ceten** [comment]
@bdukes, I thought it would be strange for DNN to modify the file itself. It's just a regular Azure App Service (pcaweb (P1v2) running the DNN website. I uploaded the update files with FileZilla and replaced the ckeditor.js in the same way after finding the file had been changed. There is only 1 instance for the App Service and scale out is set to manual.
Every time I replace the file, it is modified within the hour to a different ckeditor.js which has the SyntaxError.
I really have no idea what is changing the file.

**Comment by valadas** [comment]
I have had similar issues with ascx files getting modified by some global token module (I can't remember the name now). It was a nightmare to figure it out. Can those experiencing the issue share what modules are in use to see if maybe there is some in common ?

**Comment by Ceten** [comment]
I've kept digging into it yesterday and finally found what was causing the ckeditor file being modified. Apparently the Azure App Service had a WebJob running which minifies and replaces .js and .css files.
No idea why the minification resulted in syntax errors though, we haven't had any issues with it for years.
![afbeelding](https://user-images.githubusercontent.com/1673675/133742229-913b4a50-8aa9-4496-a6bc-61f7e708698a.png)
I had no idea this even existed but since turning it off the ckeditor.js file hasn't changed again so the html editor keeps working.

**Comment by valadas** [comment]
I have seen minification issues in the past with missing `;` in the past for the end of statements. They are optional in javascript (when you have newlines) but with minification, the engine is sometimes not intelligent enough to add them when making it all single line.

If you can click on the link on the right in the browser console it should bring you to the place it fails and if you can pinpoint in between what and what it chokes, maybe we can figure out that missing `;`

**Comment by valadas** [comment]
As this appears to not be a DNN issue, I am closing this issue.
