### ISSUE TITLE
Send Admin Log Notifications via Email is Not Working

### ISSUE THREAD

**Issue by jeremy-farrance** [dnnsoftware/Dnn.Platform#4657]
Notes: 

- @meetmandeep confirmed this also on a 9.9.1 install
- I used to use this feature a lot, but have not in years, so the problem could go back affecting quite a few versions of Dnn; seems like its been broke for a few versions at least and went unnoticed 

## Description of bug
The Send Log Notification scheduled task is not sending out emails as expected.

## Steps to reproduce
List the precise steps to reproduce the bug:
1. Settings/Scheduler; Enable "Send Log Notifications" (1 or 2 mins)
2. Verify SMTP send is working
3. Manage/Admin Logs, switch to Log Settings tab; pick one you can easily make happen (e.g. 404, Superuser Login, etc), edit, Enable, add email, Save, etc

## Current behavior
The Scheduler task runs (every 2 mins in my case); says succeeded and duration zero seconds. I never get any emails. And there are no errors in the admin logs or in the /Portals/_detault/Logs/2021.05.xx.log.resources happening in the same time range.

## Expected behavior
Assuming I setup to send an email on a 404 error or a Superuser Login (both are easy to trigger), within 2 mins I should get an email with the details of the event as recorded in the Admin Logs.

### Screenshots
1. Manage/Admin Logs, Log Settings tab... HTTP 404 event
![image](https://user-images.githubusercontent.com/653301/117589217-e4f60c00-b0ed-11eb-9636-2a0f56c16227.png)

2. Settings/Scheduler 
![image](https://user-images.githubusercontent.com/653301/117589286-3ef6d180-b0ee-11eb-8079-2b560482988f.png)

### Error information
As noted above, I cannot find any related errors being logged.

### Affected version
* [x] 09.09.01 clean install
* [x] 09.09.01 upgraded and Telerik removed (tested site started life at 7.03.04)
* [?] 09.03.02 see first comment below

### Affected browser
* [x] All/any

**Comment by jeremy-farrance** [comment]
I did one additional test on a Dnn 9.0302 (yeah, I hear ya, upgrade, I know).
 
It worked on the first try with an HTTP 404 >>> **but NOT as expected.** 

The email appears to have been send as HTML, but not encoded:

```
From: DNN Corp < ============@accuraty.com> 
Sent: Sunday, May 9, 2021 5:54 PM
To: Jeremy Farrance < ====@accuraty.com>
Subject: Event Notification

<log LogGUID="6edcc195-1573-4253-a4c7-597b42ab3456" LogFileID="" LogTypeKey="PAGE_NOT_FOUND_404" LogUserID="-1" LogEventID="40818" LogUserName="" LogPortalID="0" LogPortalName="=== =======" LogCreateDate="5/9/2021 5:53:14 PM" LogCreateDateNum="0" BypassBuffering="False" LogServerName="======" LogConfigID="117">
<LogProperties>
<LogProperty><PropertyName>TabId</PropertyName><PropertyValue /></LogProperty>
<LogProperty><PropertyName>PortalAlias</PropertyName><PropertyValue>http://www.nnnndomain.com</PropertyValue></LogProperty>
<LogProperty><PropertyName>OriginalUrl</PropertyName><PropertyValue>/page-exists-not</PropertyValue></LogProperty>
<LogProperty><PropertyName>Url</PropertyName><PropertyValue>https://www.nnnndomain.com/page-exists-not</PropertyValue></LogProperty>
<LogProperty><PropertyName>UserAgent</PropertyName><PropertyValue>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36</PropertyValue></LogProperty>
<LogProperty><PropertyName>HostAddress</PropertyName><PropertyValue>192.==.==.==</PropertyValue></LogProperty>
<LogProperty><PropertyName>HostName</PropertyName><PropertyValue>192.==.==.==</PropertyValue></LogProperty>
</LogProperties>
</log>
```

**Comment by sleupold** [comment]
is your 404 error being handled by DNN or IIS?

**Comment by jeremy-farrance** [comment]
> is your 404 error being handled by DNN or IIS?

It is being handled by Dnn and there is a log event getting written for it (example in comment above actually). Also, I tried multiple events including Superuser Login, General Exception, Admin Alert, and others. All of them have logged their events in to the Admin Logs without sending emails.

**Comment by meetmandeep** [comment]
@jeremy-farrance My team provided the following error which occurs when you manually try to email the logs. Not sure if this is related or not. 

```
Request URL: http://www.dnndevsites.com/dev990/2/API/PersonaBar/AdminLogs/EmailLogItems
ExceptionMessage: "Cannot import nodes of type 'Document'."
ExceptionType: "System.InvalidOperationException"
Message: "An error has occurred."
StackTrace: "   at System.Xml.XmlDocument.ImportNodeInternal(XmlNode node, Boolean deep)\r\n   at Dnn.PersonaBar.AdminLogs.Components.AdminLogsController.GetExceptions(IEnumerable`1 logIds)\r\n   at Dnn.PersonaBar.AdminLogs.Components.AdminLogsController.EmailLogItems(String subject, String fromEmailAddress, String toEmailAddress, String message, IEnumerable`1 logItemIds, String& error)\r\n   at Dnn.PersonaBar.AdminLogs.Services.AdminLogsController.EmailLogItems(EmailLogItemsRequest request)"
```
