### ISSUE TITLE
Invalid Breadcrumb Metadata for Disabled Pages

### ISSUE THREAD

**Issue by Andy9999** [dnnsoftware/Dnn.Platform#4667]
BreadCrumb.ascx.cs generates invalid meta data for disabled pages and Google Search Console complains about it. The disabled page is rendered as an "itemListElement" and those need to have at least one "item", which is not the case.

Instead of this (sorry but Github seems to minify the XML):
`<span itemscope itemtype="http://schema.org/BreadcrumbList">
   <span itemprop="itemListElement" itemscope itemtype="http://schema.org/ListItem">
      <span itemprop="name">Disabled Page</span>
      <meta itemprop="position" content="1" />
   </span>
   <span class="fas fa-angle-right"></span>
   <span itemprop="itemListElement" itemscope itemtype="http://schema.org/ListItem">
      <a href="https://www.mydomain.com/Page1" class="eds_breadCrumb" itemprop="item"><span itemprop="name">Page1</span></a>
      <meta itemprop="position" content="2" />
   </span>
   <span class="fas fa-angle-right"></span>
   <span itemprop="itemListElement" itemscope itemtype="http://schema.org/ListItem">
      <a href="https://www.mydomain.com/Page1/Page2" class="eds_breadCrumb" itemprop="item"><span itemprop="name">Page2</span></a>
      <meta itemprop="position" content="3" />
   </span>
</span>`

It should probably render that (notice that the disabled page is just a span not a itemListElement anymore:
`<span itemscope itemtype="http://schema.org/BreadcrumbList">
   <span">Disabled Page</span>
   <span class="fas fa-angle-right"></span>
   <span itemprop="itemListElement" itemscope itemtype="http://schema.org/ListItem">
      <a href="https://www.mydomain.com/Page1" itemprop="item"><span itemprop="name">Page1</span></a>
      <meta itemprop="position" content="1" />
   </span>
   <span class="fas fa-angle-right"></span>
   <span itemprop="itemListElement" itemscope itemtype="http://schema.org/ListItem">
      <a href="https://www.mydomain.com/Page1/Page2" itemprop="item"><span itemprop="name">Page2</span></a>
      <meta itemprop="position" content="2" />
   </span>
</span>`

To do that I changed in BreadCrumb.ascx.cs this:
```
...
                // Begin breadcrumb
                this._breadcrumb.Append("<span itemprop=\"itemListElement\" itemscope itemtype=\"http://schema.org/ListItem\">");

                // Is this tab disabled? If so, only render the text
                if (tab.DisableLink)
                {
                    this._breadcrumb.Append("<span class=\"" + this._cssClass + "\" itemprop=\"name\">" + tabName + "</span>");
                }
                else
                {
                    this._breadcrumb.Append("<a href=\"" + tabUrl + "\" class=\"" + this._cssClass + "\" itemprop=\"item\"><span itemprop=\"name\">" + tabName + "</span></a>");
                }

                this._breadcrumb.Append("<meta itemprop=\"position\" content=\"" + position++ + "\" />"); // Notice we post-increment the position variable
                this._breadcrumb.Append("</span>");
...
```

Into this:
```
...
                // Is this tab disabled? If so, only render a span
                if (tab.DisableLink)
                {
                    this._breadcrumb.Append("<span class=\"" + this._cssClass + "\">" + tabName + "</span>");
                }
                else
                {
                    // Begin breadcrumb
                    this._breadcrumb.Append("<span itemprop=\"itemListElement\" itemscope itemtype=\"http://schema.org/ListItem\">");
                    this._breadcrumb.Append("<a href=\"" + tabUrl + "\" class=\"" + this._cssClass + "\" itemprop=\"item\"><span itemprop=\"name\">" + tabName + "</span></a>");
                    this._breadcrumb.Append("<meta itemprop=\"position\" content=\"" + position++ + "\" />"); // Notice we post-increment the position variable
                    this._breadcrumb.Append("</span>");
                }
...
```

Any thoughts on that? If you like it you can keep it. :)

Andy

**Comment by sleupold** [comment]
Thank you, I noticed the same last week at a client site.
would you mind to create a pull request, that would be great 
and increase chance for this fix to be included in next DNN release.

**Comment by Andy9999** [comment]
You are welcome. I will create a pull request later (my first ever pull request on GitHub)....

**Comment by sleupold** [comment]
Great! I'm looking forward to it :)

**Comment by Andy9999** [comment]
Please ignore the first attempt to commit my changes. I tried to use the in-browser editor and somehow it was complaining about the source have mixed line endings. The 2nd one is the right one (done from GitHub Desktop/Notepad++). I had some problem to assign a label and milestone. Is this supposed to be done during the pull request?
