### ISSUE TITLE
Login.ascx & User.ascx Should Use noindex and nofollow

### ISSUE THREAD

**Issue by Andy9999** [dnnsoftware/Dnn.Platform#4668]
Since the 14th of April we were seeing some warnings in Google Search Console for our site about the registration & login links.

The warning is "Indexed, Though, blocked by robots.txt".

Before we simply had the registration and login pages blocked in robots.txt.

In Login.ascx and User.ascx the links are rel="nofollow". I thought this was enough.

Google wants noindex as documented here: [https://support.google.com/webmasters/answer/7440203#indexed_though_blocked_by_robots_txt](url)

This can be easily changed in both files by replacing rel="nofollow" with rel="nofollow,noindex".

If others agree, I can submit a pull request later.

Seems this is just a warning, not impacting SEO most likely, but I want to keep warnings and errors as low as possible.

**Comment by Andy9999** [comment]
Here is some more info and it seems Google would potentially index a page if the link is coming from another site (not using nofollow): [https://www.deepcrawl.com/blog/best-practice/noindex-disallow-nofollow/](url)

**Comment by Andy9999** [comment]
Eventually rel="noindex" is enough + removing it from robots.txt. Am not 100% sure, it is kind of confusing.

**Comment by sleupold** [comment]
I noticed this problem a few days ago as well.
I'd assume, we should add login register pages to default robots.txt or add the meta tag to the page, whenever the register or login module is added.

**Comment by sleupold** [comment]
thank you for your investigations.
Any input from our SEO experts - @Tychodewaard, @Timo-Breumelhof ?

**Comment by Tychodewaard** [comment]
I agree that there is most of the time no value in having the login page indexed. And I don't know where the user.ascx is involved but I have a checklist for setting up DNN installs where 'switch SEO page settings to noindex on activity feed page' is one of the default actions. 
So, anything that can be done to create a better default install is great!

As logins can be on pages that contain useful info/links, I would use noindex and not add the nofollow.

**Comment by Andy9999** [comment]
Am now waiting for the validation result in Google Search Console.  I am using custom login and registration pages and I have now set the "Allow Indexing" option on both pages to off. According to what Google wrote, this should prevent the pages from being indexed, no matter if referenced by internal or external links. I rolled back the changes made to Login.Ascx and User.Ascx again, because I think having noindex in there as well is redundant and not really needed.

Additionally I removed the entries for both pages from robots.txt. It seems they are not really useful in there if it does not guarantee the link to be indexed if referenced by external pages. Even though if I understand Google correctly with less information & nothing taken from the pages themselves.

I am not sure if a default DNN install has the default login & registration pages set to noindex. I can try that out later and update again.

**Comment by Andy9999** [comment]
Am done testing and the default login and the default registration page of a fresh install both have "noindex, nofollow" in the robots page header as it should be imo. Under those conditions Search Console should not complain. It will only complain if it finds a robots.txt entry excluding them (since recently).

Will now wait to see if removing the entries from robots.txt + disabling the "Allow Indexing" options fixes my configuration issue.
