### ISSUE TITLE
Cache-Setting 'NoCaching' not saved

### ISSUE THREAD

**Issue by weilguny** [dnnsoftware/Dnn.Platform#4672]
## Description of bug
It is not possible to turn Caching off (set Caching to 'NoCaching') in the Server-Settings of the PersonaBar (DNN GUI). 

## Steps to reproduce
List the precise steps to reproduce the bug:
1. Go to 'Settings > Server-Settings > Performance'
2. Click on 'Cache-Settings' dropdown
3. Select 'NoCache' and 'Save' settings
4. Reload page (or restart app to be sure) or check database: the setting is not stored. Value in database should be '0'. This only happens when selecting 'NoCache", all other options of the dropdown box are stored correctly. 

## Current behavior
When selecting 'NoCache' value is not set in the database. Changing setting to 'Light/Moderate/Heavy Caching' works fine. 

## Expected behavior
Caching should be turned off. 
SettingValue of SettingName 'PerformanceSetting' in Table HostSettings should be set to '0' (zero). 

## Screenshots
Screenshot of the dropdown attached.
![image](https://user-images.githubusercontent.com/71639312/119126221-0a124500-ba33-11eb-9184-893cac855435.png)

## Error information
Provide any error information (console errors, error logs, etc.) related to this bug.

## Additional context
Provide any additional context that may be helpful in understanding and/or resolving the bug.

## Affected version
* [X] 09.09.00 
* [X] 09.09.01 latest supported release

## Affected browser
* [X] Chrome
* [X] Firefox
* [X] Microsoft Edge Chromium

**Comment by sleupold** [comment]
I just tested on DNN 9.9.0 (new install) and can confirm this bug.

**Comment by jeremy-farrance** [comment]
Yeah, been like this a while, I just tried it on a local 9.03.02 site.

**Comment by manojattal** [comment]
I intend to work on this ticket and I can submit pull request in a day.
