### ISSUE TITLE
SQL Console raises error for variable declarations with "@" character

### ISSUE THREAD

**Issue by berkarslan-xo** [dnnsoftware/Dnn.Platform#4673]
## Description of bug
Executing queries in SQL Console raises an error since the "@" character is a special character in PetaPoco to pass arguments to the queries. The queries have to contain double "@" characters for escaping purposes in order for the PetaPoco library to not raise any errors.

## Steps to reproduce
1. From the article https://dnnsupport.dnnsoftware.com/hc/en-us/articles/360011483340 , copy the query in Step 3.1 in the Solution section and paste it into the SQL Console. Or just use a simple query text like "declare @test INT = 0"
2. Run the query.

## Current behavior
It returns an error - "System.ArgumentException: Parameter '@parameterNameHere' specified but none of the passed arguments have a property with this name."

## Expected behavior
The query should work with single "@" character.

## Screenshots
![image](https://user-images.githubusercontent.com/45750757/119174660-89266e00-ba71-11eb-92a2-8fdbfbad3d0c.png)

## Additional context
I need confirmation from the community to fix this behavior by replacing all of the passed "@" characters with "@@" so that the queries can work just like in SSMS (SQL Server Management Studio).

## Affected version

* [x] 10.00.00 alpha build
* [ ] 09.09.00 latest supported release

## Affected browser

* [x] Chrome
* [ ] Firefox
* [ ] Safari
* [ ] Internet Explorer 11
* [ ] Microsoft Edge (Classic)
* [ ] Microsoft Edge Chromium

**Comment by bdukes** [comment]
I would like to see this change, my only concern would be any saved scripts that have the escaping already in place…

And, as a note, the double `@` is only required for queries without `GO` (which adds to the confusion)

**Comment by berkarslan-xo** [comment]
Even if they have the escape characters, I believe the queries will continue to work just fine because SQL Server doesn't complain about multiple "@" characters in variable declarations. For example, the following query will work fine:
```
declare @@@@portalid INT = 0    --REPLACE THIS NUMBER WITH YOUR PORTALID
, @@@@menuid INT = 0    --REPLACE THIS NUMBER WITH YOUR MENUID
, @@@@roleid INT = 0    --REPLACE THIS NUMBER WITH YOUR ROLEID

select MenuPermissionID
, RoleName
,(select top 1 httpalias 
from portalalias pa 
where pmp.portalid=pa.portalid 
order by case when isprimary=1 then 0 else 1 end, portalaliasid) as Portal
, ModuleName as MenuName
, PermissionName
, case when AllowAccess=1 then 'Yes' else 'No' end as HasAccess

from PersonaBarMenuPermission pmp 
left join personabarpermission pp on pp.permissionid=pmp.permissionid
left join personabarmenu pm on pm.menuid=pmp.menuid
left join roles on roles.roleid=pmp.roleid
WHERE 1=1
AND pmp.RoleID = @@@@roleid
AND pmp.MenuID = @@@@menuid
AND pmp.PortalID = @@@@portalid
```

**Comment by berkarslan-xo** [comment]
Please also note that the functionality works fine with single "@" character in <=9.2.1 versions:

![image](https://user-images.githubusercontent.com/45750757/119178809-dce78600-ba76-11eb-8988-99bf8b0dc77b.png)

Please let me know if you agree with changing the "@" characters with "@@" so that I continue with the fix.

**Comment by sleupold** [comment]
IMO DNN SQL console should treat SQL as much as possible like SQL server itself.
There is a difference between local variables (starting with @) and global variables (starting with @@)
I would prefer a different escape character for DNN parameters instead of escaping variables inside of scripts.
One option would be enclosing them by "{" and "}" like we are doing with databaseOwner and ObjectQualifier.

**Comment by bdukes** [comment]
@sleupold as far as I know there isn't support for any DNN-specific parameters, it's just that we're using code that expects that there could be external variables.

**Comment by sleupold** [comment]
@bdukes 
What would be the difference to [dataabseOwner} and [objectqualifier} - htose external variables would be replaced by their value prior to executing the script. Or am I misunderstanding the purpose here?

**Comment by bdukes** [comment]
I think we're on the same page here. The SQL should work like plain SQL. We support `{databaseOwner}` and `{objectQualifier}` tokens that are processed before sending the script to the SQL engine, but otherwise there's nothing else extra that should be happening.

**Comment by sleupold** [comment]
but how are the parameters with single @ being passed to the script - where do they get the values from?

**Comment by bdukes** [comment]
The SQL Console component in the Persona Bar does not support passing external data into the script. AFAIK it has never supported that feature, and we're not discussing adding that feature (at least not in this particular issue).

The scripts we're talking about are defining variables within the script itself, or using `@` in a text value, for example:

```sql
DECLARE @portalId int = SELECT MAX(PortalID) FROM Portals;

INSERT INTO MyTable(ID, email)
VALUES (@portalId, 'bdukes@example.com`);
```

**Comment by sleupold** [comment]
I just reread the original text and noticed, it's a workaround for a PetaPoco limitation.

**Comment by jeremy-farrance** [comment]
These scripts have always been self-contained and seemingly plain text. So I think any use of params would be declared WITHIN the same script before being used. This is a convenience tool and doesn't seem to me that it warrants any fancy features. There should not be much difference between running a script in the PB SQL console and running a script in a script/query in SQL management studio. 

So maybe the real fix is an option to run the script/query "plain" vs "PetaPoco" and when you choose PetaPoco, which (IMHO) should not be the default, you will be responsible for know about solutions like `@@` and `@@@`.
 
Again, this is a simple convenience tool and needs to keeps its emphasis on Simple. I am sure there is more to it, but I see no benefit to PetaPoco being involved at all in "running a SQL script."

**Comment by bdukes** [comment]
@jeremy-farrance I believe the issue is that PetaPoco is involved with _all_ DNN data access at this point. It's not giving us any useful features in this scenario.

But if @berkarslan-xo can implement a fix so that an end user doesn't have to worry about it, I'm for it.

**Comment by berkarslan-xo** [comment]
Hi, so is replacing "@" character with "@@" ok? If not, what's the suggested solution? Or should we close this issue if this is working as expected?

**Comment by bdukes** [comment]
I'd like to see this implemented. Any concerns @dnnsoftware/approvers?

**Comment by mitchelsellers** [comment]
I would like this also

**Comment by berkarslan-xo** [comment]
Ok, implementing the change then.
