### ISSUE TITLE
Default Install Always Loads jQuery and jQuery Migrate

### ISSUE THREAD

**Issue by Andy9999** [dnnsoftware/Dnn.Platform#4681]
I was under the assumption, that if you set "EnablePopups" to "False" in the "PortalSettings" table, jQuery would not be loaded.

Am currently looking for performance improvements and was wondering why it's being loaded on the production site, so I installed a fresh DNN and disabled popups + cleared the cache. And to my surprise it is loading jQuery and jQuery Migrate.

Is this normal now? This seems to contradict this info for example (from version 9.1): [https://www.dnnsoftware.com/forums/threadid/537645/scope/posts/disable-support-for-popups-in-dnn-91](url)

Or is this because of the default skin being used?

Is there some way to turn it off? How can I find out what is causing DNN to load it? Can I trace that somehow?

Thanks for any additional info in advance!

Andy

**Comment by sleupold** [comment]
jQuery and jQuerryUI are loaded, whenever DNN Platform itself, a module, skin or container on the page requests it. 
Did you check source of the skin?

**Comment by Andy9999** [comment]
It's with the default skin after a fresh install. Will check it later and update.

**Comment by sleupold** [comment]
Yes, AFAIK, Xcillion skin uses jQuery.

**Comment by Andy9999** [comment]
Yes, the skin has an AddFiles.ascx and it has DnnJsInclude loading scriptJS and bootstrapJS. Is it possible to have a bootstrap based site without jQuery? Bootstrap itself supports running without jQuery. Am not sure which of the DnnJsInclude's is actually loading jQuery.

Our production site for example is based on bootstrap as well and it seems the search, which is implemented as a popup would explain the use of jQuery. I have, however, eliminated the jQuery migrate with a dirty hack (IIS outbound url rewrite). 3.5KB saved. LOL.

**Comment by bdukes** [comment]
It looks like the [Search](https://github.com/dnnsoftware/Dnn.Platform/blob/e4e69ba08390bfb439ba9e0320534d1662a1fb0d/DNN%20Platform/Skins/Xcillion/Skin/Inner.ascx#L43) skin object [requests the AJAX Anti-Forgery support](https://github.com/dnnsoftware/Dnn.Platform/blob/e4e69ba08390bfb439ba9e0320534d1662a1fb0d/DNN%20Platform/Website/admin/Skins/Search.ascx.cs#L451), which in turn [requests jQuery](https://github.com/dnnsoftware/Dnn.Platform/blob/e4e69ba08390bfb439ba9e0320534d1662a1fb0d/DNN%20Platform/Library/Framework/ServicesFrameworkImpl.cs#L54).

**Comment by Andy9999** [comment]
Thanks for the additional info Brian and Sebastian. I think this is not really a bug or an improvement request then at this point and I will close it.

**Comment by valadas** [comment]
Yeah, on a default install the following needs jQuery:
1. The default theme
2. The search skinObject
3. The popups are enabled by default.

I do plan at some point in time to rewrite the popup and search part in vanilla javascript one day so at least with a custom theme, one could avoid loading jQuery altogether...

**Comment by valadas** [comment]
And I would not be opposed to have popups disabled by default on a clean install too 😉

**Comment by jeremy-farrance** [comment]
I think this could be emphasized a bit more...
 
# And I would not be opposed to have popups disabled by default on a clean install too
-- valadas

**Comment by jeremy-farrance** [comment]
Also, some interesting commentary, history, and how-to are [here.](https://docs.2sxc.org/js-code/dnn/jquery.html)
