### ISSUE TITLE
Module Load Exception after site transfer

### ISSUE THREAD

**Issue by msr930** [dnnsoftware/Dnn.Platform#4682]
After transferring a dnn 9.9 site from local server to a host, I get the following error in the logs:
Any ideas how to fix it?

ModuleId:-1

ModuleDefId:-1

FriendlyName:

ModuleControlSource:

AbsoluteURL:/Default.aspx

DefaultDataProvider:DotNetNuke.Data.SqlDataProvider, DotNetNuke

ExceptionGUID:cb885872-f94c-4a15-9035-63cf2cf6fb9b

AssemblyVersion:

PortalId:-1

UserId:-1

TabId:-1

RawUrl:

Referrer:

UserAgent:

ExceptionHash:C2TFrDiuaeD5xzZB8wFGdLQ+8qM=

StackTrace:

InnerMessage:The file '/Portals/_default/Containers/Mytheme/No Title.ascx' does not exist.

InnerStackTrace:

   at System.Web.UI.Util.CheckVirtualFileExists(VirtualPath virtualPath)
   at System.Web.Compilation.BuildManager.GetVPathBuildResultInternal(VirtualPath virtualPath, Boolean noBuild, Boolean allowCrossApp, Boolean allowBuildInPrecompile, Boolean throwIfNotFound, Boolean ensureIsUpToDate)
   at System.Web.Compilation.BuildManager.GetVPathBuildResultWithNoAssert(HttpContext context, VirtualPath virtualPath, Boolean noBuild, Boolean allowCrossApp, Boolean allowBuildInPrecompile, Boolean throwIfNotFound, Boolean ensureIsUpToDate)
   at System.Web.UI.TemplateControl.LoadControl(VirtualPath virtualPath)
   at DotNetNuke.UI.ControlUtilities.LoadControl[T](TemplateControl containerControl, String ControlSrc)
   at DotNetNuke.UI.Skins.Pane.LoadContainerByPath(String containerPath)
Source:

FileName:

FileLineNumber:0

FileColumnNumber:0

Method:

**Comment by sleupold** [comment]
The error is clear: _The file '/Portals/_default/Containers/Mytheme/No Title.ascx' does not exist._
Did you move your site from the root of a domain to a subfolder of localhost or sth like this?
To avoid this, I am using local URLs like http://dnn991 and add the domain to local hosts file.

**Comment by msr930** [comment]
> The error is clear: _The file '/Portals/_default/Containers/Mytheme/No Title.ascx' does not exist._
> Did you move your site from the root of a domain to a subfolder of localhost or sth like this?
> To avoid this, I am using local URLs like http://dnn991 and add the domain to local hosts file.

Thank you Sebastian, Yes I moved my site from root of my local development server to a commercial host which is a subfolder of localhost. But, I didn't get your point, Could you please let me know what exactly I should do?

**Comment by sleupold** [comment]
f you move from hosted domain to a subfolder of localhost, domain relative paths like '/portals/_default/container/myTheme/no Title.ascx" won't point to the correct file anymore as the path resolves to "http://localhost/portals/_default/container/myTheme/no Title.ascx" - which is missing subfolder. If you instead create a local IIS website with binding "dnn991" (or whatever name you prefer) and add the name to your C:\Windows\System32\drivers\etc\hosts file, the path will resolve correctly to http://dnn991/portals/_default/container/myTheme/no Title.ascx

**Comment by msr930** [comment]
> f you move from hosted domain to a subfolder of localhost, domain relative paths like '/portals/_default/container/myTheme/no Title.ascx" won't point to the correct file anymore as the path resolves to "http://localhost/portals/_default/container/myTheme/no Title.ascx" - which is missing subfolder. If you instead create a local IIS website with binding "dnn991" (or whatever name you prefer) and add the name to your C:\Windows\System32\drivers\etc\hosts file (see e.g. https://helpdeskgeek.com/networking/edit-hosts-file/), the path will resolve correctly to http://dnn991/portals/_default/container/myTheme/no Title.ascx

So is there any way I can point to the right path in the new host? In the web.config

**Comment by sleupold** [comment]
no, domain relative paths will fail. Even if DNN would be resolving properly, you would notice missing images, css and js files, which are loaded by IIS directly.

**Comment by msr930** [comment]
> no, domain relative paths will fail. Even if DNN would be resolving properly, you would notice missing images, css and js files, which are loaded by IIS directly. Using a local domain (from hosts file) is best practice for testing and development scenarios.

didn't know that's necessary! Thanks

**Comment by sleupold** [comment]
You are welcome :)
