### ISSUE TITLE
DNN Connect CKEditor Provider: Link Dialogue Window displays orphaned Telephone Number textbox

### ISSUE THREAD

**Issue by mayaco** [dnnsoftware/Dnn.Platform#4689]
## Description of bug
On a clean DNN 9.9.1 installation, using the default DNN Connect CKEditor Provider if you click on the Link option in the toolbar, a Telephone Number textbox appears by default for all Link Type options.

## Steps to reproduce
List the precise steps to reproduce the bug:
1. Switch to Edit Mode
2. On any HTML module, hover over the pencil icon in the top-right corner and select the Edit Content option
3. With the CKEditor open, click on the Link icon in the toolbar
4. By default, the Link Info tab is selected and the Link Type is Portal file or other URL. Towards the bottom of the Link Info tab, right above the OK / Cancel button, you will see the Phone Number textbox.

## Current behavior
No matter what Link Type option (Portal file or other URL, Portal Page, Link to anchor in the text, Email) is selected the Phone Number textbox remains visible.

## Expected behavior
There should either be an additional Link Type option for Telephone Number or add an additional Protocol option for the Link Type 'Portal file or other URL' with the value 'tel:'

## Screenshots
https://www.screencast.com/t/QzfEimHQbw
https://www.screencast.com/t/Q4STTuAmeWj3
https://www.screencast.com/t/sbnrHgafuYG
https://www.screencast.com/t/QYUq2LKrz3Jq

## Error information
No errors.

## Additional context
I doesn't appear to be browser specific.

## Affected version
* [ ] 10.00.00 alpha build
* [X] 09.09.01 latest supported release

## Affected browser
* [X] Chrome
* [X] Firefox
* [X] Safari
* [X] Internet Explorer 11
* [X] Microsoft Edge (Classic)
* [X] Microsoft Edge Chromium

**Comment by james7342** [comment]
Can confirm I've noticed this also.

**Comment by sleupold** [comment]
I can confirm as well on a new install of DNN 9.9.0
The issue doesn't seem to occur on upgraded sites with same version of DNN CKeditor provider and same version of CKEditor itself.

**Comment by james7342** [comment]
@sleupold My site was upgraded to 9.9.1 from 9.8.1 and I'm seeing it. Not sure if there is/was a CKeditor version update between those 2 or not. Along with this site has been upgraded through the years starting with version 6.x if I'm not mistaken. So not sure I agree or understand the comment.

**Comment by jeremy-farrance** [comment]
Adding  notes from a discussion with @sleupold on [openhelp.slack.com](https://app.slack.com/) (Dnn Open Help).
 
Possibly or likely related, [pull request #2214](https://github.com/ckeditor/ckeditor4/pull/2214)?
 
I did some testing and found that a clean/new install of Dnn 9.09.01 exhibited the problem, but an upgraded site, from 2015 v7.03.x and now running Dnn 9.09.01 does NOT exhibit the problem. Both show the same version of the Provider and CKEditor as you can see in the screenshots below.

![image](https://user-images.githubusercontent.com/653301/120050887-0f97fe00-bfe4-11eb-9db1-83ec70c842d5.png)
 
![image](https://user-images.githubusercontent.com/653301/120050896-19b9fc80-bfe4-11eb-83b1-75479a06b5d9.png)

**Comment by jeremy-farrance** [comment]
CK Editor is also throwing this error to the console, though it doesn't look related.
![image](https://user-images.githubusercontent.com/653301/120050991-7b7a6680-bfe4-11eb-9f67-d0d344d836d4.png)

And finally, an additional interesting note. The Phone Number field comes and goes as you switch Link Type. It only shows Phone Number for file/URL or Email, but hides it for Portal Page and Link to anchor.
 
![image](https://user-images.githubusercontent.com/653301/120051035-ad8bc880-bfe4-11eb-9c51-9ac047915567.png)

**Comment by jeremy-farrance** [comment]
Is it possible that CK Editor supports links that use `tel:` and the Dnn provider is just not handling that type so it becomes visible by default? Wild guess, but...

**Comment by sleupold** [comment]
> @sleupold My site was upgraded to 9.9.1 from 9.8.1 and I'm seeing it. Not sure if there is/was a CKeditor version update between those 2 or not. Along with this site has been upgraded through the years starting with version 6.x if I'm not mistaken. So not sure I agree or understand the comment.

Information was from another user (see the thread in DNN OpenHelp). I just checked on a client site upgraded from DNN 7 to 9.9.0 and it displays Phone Number field as well.

**Comment by sleupold** [comment]
@james7342 
I found this PR for CKEditor 4, added two years ago (DNN provider was recently upgraded to include a recent version):
https://github.com/ckeditor/ckeditor4/pull/2214

**Comment by bdukes** [comment]
Here's the commit that apparently fixed it in the other CKEditor Provider project: 
https://github.com/w8tcha/dnnckeditor/commit/2be5a27ee6497b8589874871d878a984046d7e60
