### ISSUE TITLE
Line of code is using obsolete function to get client Ip Address

### ISSUE THREAD

**Issue by ufoloko** [dnnsoftware/Dnn.Platform#4701]
In this line of code

https://github.com/dnnsoftware/Dnn.Platform/blob/9f83285a15d23203cbaad72d62add864ab5b8c7f/DNN%20Platform/Website/DesktopModules/Admin/Authentication/Login.ascx.cs#L1310

You have 

var clientIp = NetworkUtils.GetClientIpAddress(this.Request);

It should be 

var clientIp = userRequestIpAddressController.GetUserRequestIPAddress(new HttpRequestWrapper(this.Request));

NetworkUtils.GetClientIpAddress(this.Request) is obsolete and is using X-Forwarder-For header, userRequestIpAddressController function allows to customize header for other kind of load balancers.

You should change this.

**Comment by valadas** [comment]
What about sending a PR instead of an issue ?

**Comment by sleupold** [comment]
@valadas instead?

**Comment by ufoloko** [comment]
Sorry Im not familiar with github and PR, but is a good Idea, I will try to do that .

**Comment by valadas** [comment]
@sleupold I was referring to "You should change this" where the solution is right there and the reported is a developer I know has done PRs on other projects :)

@ufoloko thanks for the PR, looks ok from a quick look, I will review later. Looks like you got the hang of it.

Just advice for the future (no need to redo anything on this one)
I would suggest you create a branch to isolate PR changes on your end before doing commits, this allows you to work on different things in parallel and have a branch in case changes are required, etc. When you do it on develop you are kinda stuck on it until you PR get's merged, and then should it not get merged for some reason then you need to revert your commit, etc. On a branch you keep your develop one clean and ready to go no matter what happens :)

**Comment by ufoloko** [comment]
I created a PR but Im receiving some errores

PR is https://github.com/dnnsoftware/Dnn.Platform/pull/4702

I dont know if i need to do something else

Thanks

**Comment by ufoloko** [comment]
> @sleupold I was referring to "You should change this" where the solution is right there and the reporter is a developer I know has done PRs on other projects :)
> 
> @ufoloko thanks for the PR, looks ok from a quick look, I will review later. Looks like you got the hang of it.
> 
> Just advice for the future (no need to redo anything on this one)
> I would suggest you create a branch to isolate PR changes on your end before doing commits, this allows you to work on different things in parallel and have a branch in case changes are required, etc. When you do it on develop you are kinda stuck on it until you PR get's merged, and then should it not get merged for some reason then you need to revert your commit, etc. On a branch you keep your develop one clean and ready to go no matter what happens :)

Thanks for your comment, I forget you really advice me this when created a PR for DNNFormAndList, I will do what you recommend next time.

Regards

**Comment by valadas** [comment]
It looks good to me (did not review the details yet)
But it is building in CI and the mergeable error is for reviewers to assign it a milestone and type, etc. On your end until it's reviewed in more details, it looks ok, no extra files or anything that looks wrong with the PR itself.

**Comment by ufoloko** [comment]
Great !!
