### ISSUE TITLE
DNN Tracking DLL Dependencies fails when multiple Versions are in Use

### ISSUE THREAD

**Issue by iJungleboy** [dnnsoftware/Dnn.Platform#4704]
## Description of bug

Two modules using the same DLL in different versions can easily do so by placing them in a subfolder in the bin and setting the Web.Config rules for version redirects. This works at runtime, but fails on module installs and updates. Here's a real example where 2sxc and DnnSharp run into a problem (see also the [issue on 2sxc](https://github.com/2sic/2sxc/issues/2437):

1. 2sxc uses EF 1.1 and the MS Dependency Injection 1.1 and places all this in bin/2sxc
2. PlantAnApp (DnnSharp) uses EF 2.1 and places all this in bin/PlantAnApp

Because the web.config redirects manage all this, it's not a problem. But on Module-Install and Upgrade it fails. The reason is that DNN tries to help by tracking installed DLLs, but doesn't keep track of the folder. So even though the files don't conflict, DNN checks the DB and assumes a newer version has already been installed (Table: `Assemblies`):

![image](https://user-images.githubusercontent.com/5321186/120822617-e4b72800-c556-11eb-959f-54f730d64f70.png)

_Note: for historic reasons the EF in 2sxc has the wrong version (it believes it's EF v11 or 12 because that's the 2sxc version). This may lead to more confusion, because actually installing 2sxc after PlantAnApp works, but updating PlantAnApp will fail then. But the core problem is that the version ignores the folder it's in._

## Current behavior

This leads to the following problems:

1. If PlantAnApp is installed first, 2sxc with EF v1.1 wouldn't install, because DNN believes it already has a newer version. 
2. If 2sxc with EF 1.1 is installed first, the entry would say v1.1 and Would allow PlantAnApp to install it as well. That would bump the version to 2.1. After that updating 2sxc with a newer EF (say 1.2) would fail, because DNN believes it already has a newer version. 

## Expected behavior

DLL Versions in `Assemblies` should include the folder they are in, as the same DLL can be installed in different versions. 

## Affected version
* [x] All DNN versions as of now up and till v09.09.01

**Comment by bdukes** [comment]
If you're maintaining your own collection of DLLs in its own folder, and managing your own binding redirects, etc., then I'm not sure that you're getting any value out of using the [`Assembly` component](https://dnndocs.com/content/tutorials/extensions/dnn-manifest-schema/index.html#components), rather than just a simple `File` component. Are there features of the `Assembly` component you're looking to keep?

**Comment by iJungleboy** [comment]
@bdukes I'm not sure what you mean. We're just listing our DLLs in our Dnn Manifest since we assume that well-behaved modules should do this, and I think it's necessary that they get installed within the bin (sub) folder. 

What features would `Assembly` components have? I'm not really aware of any features in this scope.

**Comment by bdukes** [comment]
Using an `Assembly` component (as opposed to a `File` component) provides the following features:

* Registers the assembly in the `Assemblies` table (records what version of an assembly each package installed)
* Creates a binding redirect for strong-named assemblies
* Checks the version of installed assemblies to avoid overwriting newer assemblies with older assemblies

It doesn't seem to me that any of those features are of use to these assemblies that are installed to an alternate folder. Certainly a well-behaved module should declare their _shared_ assemblies that are going into the `bin` folder using the `Assembly` component, but assemblies that you're managing and that are not shared probably don't benefit by using the `Assembly` component.

**Comment by bdukes** [comment]
I just looked at the `.dnn` file in your latest install package and wanted to respond to the comments 🙂 

The `File` component will report file extensions that are not on the allowed list. However, the `ResourceFile` component will not.
https://github.com/2sic/2sxc/blob/9ba57100fa532aef41ec96a9bb0f347ac89aeb73/Src/Dnn/ToSic.Sxc.Dnn.Main/DnnPackageBuilder/2sic_2SexyContent.dnn#L266-L275

It looks like this is what you're doing now for `pdb` files, you could do the same for your `bin/2sxc/*.dll` files.
https://github.com/2sic/2sxc/blob/9ba57100fa532aef41ec96a9bb0f347ac89aeb73/Src/Dnn/ToSic.Sxc.Dnn.Main/DnnPackageBuilder/2sic_2SexyContent.dnn#L286-L293

Regarding PDB files, it looks like [you implemented support for `pdb` files in the `Assembly` component](https://github.com/dnnsoftware/Dnn.Platform/pull/1769) in DNN 9.1.1.
https://github.com/2sic/2sxc/blob/9ba57100fa532aef41ec96a9bb0f347ac89aeb73/Src/Dnn/ToSic.Sxc.Dnn.Main/DnnPackageBuilder/2sic_2SexyContent.dnn#L145-L148

**Comment by mitchelsellers** [comment]
I have to say that I agree with @bdukes on this one. 

The nested/sub-folder approach is not necessarily an approach that is truly publicized, and requires additional work (config section additions, etc). 

I think that the usage of the file component is a better option for these.

**Comment by iJungleboy** [comment]
@bdukes and @mitchelsellers thanks for your insights. 

Note that even though we contributed the `.pdb` fix we cannot use it ourselves, because 2sxc can still be installed on Dnn 7.4.2.

@bdukes From what I understand this is what would resolve the issue:

1. We could change our DLLs which are in a subfolder should become `ResourceFile` dependencies and not `Assembly` dependencies
2. DnnSharp should do the same - this would be important for @rezagarrow

I assume this would look like this:

```xml
<component type="ResourceFile">
  <resourceFiles>
	<basePath>bin\2sxc</basePath>
	<resourceFile>
	  <name>Microsoft.Extensions.DependencyInjection.Abstractions.dll</name>
          <name>Microsoft.Extensions.DependencyInjection.dll</name>
          <name>Microsoft.Extensions.Logging.Abstractions.dll</name>
          <name>...</name>
	</resourceFile>
  </resourceFiles>
</component>


```

I think this would be simple to do for both of us, but there is a problem making the change. I assume we should somehow tell the installer that the old `Assembly` entries should be cleared, even though we're still including the file. So it's a kind of `CleanUp` but then again the files should stay there. 

Do you have a suggestion how we could add this to the manifest and not break new installs or upgrades? I simply have no clue on this. Many thanks!

**Comment by bdukes** [comment]
The Resource File component takes a zip file and unzips it into a given folder:

```
        <component type="ResourceFile">
          <resourceFiles>
            <basePath>bin/2sxc</basePath>
            <resourceFile>
              <name>2SxcBinResources.zip</name>
            </resourceFile>
          </resourceFiles>
        </component>
```

(or you can remove the `basePath` element and include that path in the `zip` file itself, which is what you're doing for the PDB files).

For clearing out the `Assemblies` table, I don't think there's a good way other than running your own SQL script.  Something like this:
```
DELETE a
FROM {databaseOwner}[{objectQualifier}Assemblies] a
JOIN Packages p ON a.PackageID = p.PackageID
WHERE p.Name = '2SexyContent'
```

**Comment by iJungleboy** [comment]
@bdukes ok, I was a bit afraid that it would need SQL 😢. Thx for the update.

**Comment by iJungleboy** [comment]
ok, we can close this for now.
