### ISSUE TITLE
Breadcrumb Fails HTML Validation Because of Invalid itemprop for Root Element

### ISSUE THREAD

**Issue by Andy9999** [dnnsoftware/Dnn.Platform#4705]
Hi!

I did some tests with validator.w3.org on some pages having the breadcrumb.

It seems this part being rendered is invalid:
<span id="dnn_ctr99999_dnnBreadcrumb_lblBreadCrumb" itemprop="breadcrumb" itemscope="" itemtype="https://schema.org/breadcrumb">

Error reported by validator: The itemprop attribute was specified, but the element is not a property of any item.

It seems, the specified item type breadcrumb, does not have a breadcrumb property itself (https://schema.org/breadcrumb). A web page has one for example: [https://schema.org/WebPage](url) 

I found this related discussion where only the breadcrumb list is used: [https://stackoverflow.com/questions/10120096/how-to-implement-schema-org-markup-for-a-breadcrumb](url)

It would need to get fixed in breadcrumb.ascx.

The current version passes Google's rich [results test](https://search.google.com/test/rich-results) is only the validator complaining about it (when checking against the specified schema).

I will perform some experiment and simply remove itemprop="breadcrumb" and test if it then passes both tests.

Any thoughts or insights on this?

Andy

**Comment by Andy9999** [comment]
Seems like removing itemprop="breadcrumb" fixes it. Shall I do a PR?

**Comment by sleupold** [comment]
AFAIK, this has already been fixed in DNN 9.9.1 or for 9.9.2

**Comment by Andy9999** [comment]
In the "develop" branch and it still has the itemprop:
https://github.com/dnnsoftware/Dnn.Platform/blob/develop/DNN%20Platform/Website/admin/Skins/breadcrumb.ascx

**Comment by sleupold** [comment]
sorry, I might have mixed it up with your previous PR #4671

**Comment by Andy9999** [comment]
No problem.
