### ISSUE TITLE
CKEditor disappears on Postback

### ISSUE THREAD

**Issue by mouserdeveloper** [dnnsoftware/Dnn.Platform#4709]
## Description of bug
Rich Text Editor(CKEditor) disappears after the page performs a postback.

## Steps to reproduce
1. From a fresh install, edit content on a HTML module on the default home page
2. Click on the combobox at the bottom to select Basic Text Box.
3. Click on the same combobox to choose Rich Text Editor.

## Current behavior
The Rich Text Editor is there when the page first loads, but disappears and will not reload after a postback was triggered.

## Expected behavior
When Rich Text Editor is selected from the combobox, the Rich Text Editor is expected to load and be usable.

## Screenshots
![image](https://user-images.githubusercontent.com/85902034/121948057-6576e080-cd1c-11eb-9fec-6ecc9db665c5.png)

## Error information
No errors seen in logs or console

## Additional context
https://dnncommunity.org/forums/aft/2502

## Affected version

* [ ] 10.00.00 alpha build
* [X] 09.09.00 latest supported release

## Affected browser

* [X] Chrome
* [X] Firefox
* [ ] Safari
* [ ] Internet Explorer 11
* [ ] Microsoft Edge (Classic)
* [ ] Microsoft Edge Chromium

**Comment by jeremy-farrance** [comment]
Probably not much help, but I just also verified this problem on a site upgraded from 7.x in 2015 to 9.09.01 and also with Popups turned **off**. Same problem:

> [Video Demo of the problem](https://accuraty-my.sharepoint.com/:v:/p/jfarrance/EQTxkot1Cb5BmPqVD0z-OwcBT0QMd8QUz-Ck3ZbG9_hjRg?e=0ffNA9)

**Comment by matt-frank** [comment]
Confirmed I am experiencing this as well.  From my experience if editing a module defaults to the HTML module, switching, to basic text box, then attempting to go back to the HTML editor this is when it fails to load.  Started seeing this issue on 9.9.1 after upgrading from 9.5 and is also still present in 9.10.

**Comment by valadas** [comment]
Confirmed on 9.10.1 too.
