### ISSUE TITLE
https://dnncommunity.org is very slow  / down according to CloudFlare.

### ISSUE THREAD

**Issue by improwise** [dnnsoftware/Dnn.Platform#4713]
Not sure where to post this but here goes...

https://dnncommunity.org is very slow currently  if you ever manage to get to the site, often it times out with CloudFlare reporting it as unreachable.

**Comment by david-poindexter** [comment]
While I'm not seeing any issues with the site at the moment, I have let the website admins know.

Since this issue is not related to the DNN Platform codebase, we'll go ahead and close this issue.  Thanks for letting someone know!

**Comment by david-poindexter** [comment]
Oh yeah, there is unfortunately not great way to inform in these scenarios, so you did fine!  😊👍🏼

Thanks again!
