### ISSUE TITLE
Add the UnderConstruction.htm page to Settings / Configuration Manager

### ISSUE THREAD

**Issue by jeremy-farrance** [dnnsoftware/Dnn.Platform#4723]
## Description of problem
The UnderConstruction.htm page is a mystery to most when it appears.

## Description of solution
/robots.txt was recently added as an editable file under Settings / Configuration Manager. This was a fantastic addition with huge RIO (IMHO): and the UX/UI benefit of awareness and discovery in a logical place.

By the same token, it seems like we should also add the UnderConstruction.htm file - that way it becomes a feature and setting that will "surface itself" and people can then edited as needed as well as become aware of the case(s) in which the files might be displayed. (rather than being surprised by its existence after the fact and then having to track it down)

Also, in the updated version of the .htm file, include some HTML comments that self-document things. Even just a simple, <!-- this page only displays when ... --!> would prevent a lot of future questions and discussions in the forums and elsewhere.

## Screenshots
![image](https://user-images.githubusercontent.com/653301/123472174-734e2080-d5bc-11eb-9ad1-2fba51ed9858.png)

## Additional context
Inspired by this recent discussion, #4722 

## Affected browsers = all

**Comment by bdukes** [comment]
This makes sense to me. From an implementation standpoint, we need to make sure we aren't overwriting customized versions of the file (which may already be happening). If the default upgrade package overwrites it, it doesn't do much good, since it's a feature that's only used during upgrade.
