### ISSUE TITLE
Removal of SharpZipLib

### ISSUE THREAD

**Issue by mitchelsellers** [dnnsoftware/Dnn.Platform#4739]
## Description of problem
DNN Platform is currently using SharpZipLib for some Zip operations.  The usage of this should be reviewed and replaced with standard .NET Zip functionality if possible.

## Description of solution
Remove third-party dependency

## Description of alternatives considered
Leave the third-party solution

**Comment by valadas** [comment]
Unstaled, we do need to tackle this, this would also close several dependabot PRs

**Comment by mitchelsellers** [comment]
Duplicate of #2735
