### ISSUE TITLE
Security Analyzer reports missing Telerik Vulnerability patch on sites with Telerik removed

### ISSUE THREAD

**Issue by EPTamminga** [dnnsoftware/Dnn.Platform#4757]
## Description of the bug
The security analyzer reports that the Telerik has not been patched on an install where the Telerik components have been removed

## Steps to reproduce
List the precise steps to reproduce the bug:
1. Install DNN 9.10.0
2. Remove the Telerik components as mentioned in 
https://dnndocs.com/content/getting-started/setup/telerik-removal/index.html
3. Log in as Host
4. PB Security/Security Analyzer
5. Last line

## Current behaviour
Mentions that the Telerik patch is missing.

## Expected behaviour
Nothing to display.

## Screenshots
![image](https://user-images.githubusercontent.com/5859855/126998044-e9a2ab48-b7bb-4221-8f4f-25e7a773804f.png)

## Affected version

* [X] 09.10.00 latest supported release

## Affected browser

* [X] Chrome
* [X] Firefox
* [X] Safari
* [X] Internet Explorer 11
* [X] Microsoft Edge (Classic)
* [X] Microsoft Edge Chromium

**Comment by valadas** [comment]
@mitchelsellers @bdukes @david-poindexter what do you guys think if we change this to be a warning instead of a fail and changing the message to point to https://docs.dnncommunity.org/content/getting-started/setup/telerik-removal/ and in there we document that this is a "normal" warning on a de-teleriked instance. Then in DNN v10, well we kill this check completely anyway.

**Comment by david-poindexter** [comment]
@valadas I agree with that approach.

**Comment by mitchelsellers** [comment]
I thought we discussed in the approvers group that we would change this to be an error for any inclusion of Telerik, OR inclusion of Telerik without the security patch, and an all-clear if there is no Telerik found.

**Comment by bdukes** [comment]
Yes, there should be no warning or error if Telerik isn't present
