### ISSUE TITLE
Allow use of PNG / SVG files as Favicon

### ISSUE THREAD

**Issue by Timo-Breumelhof** [dnnsoftware/Dnn.Platform#4758]
## Description of problem
Is is very common to use a PNG / SVG as a Favicon instead of an *.ICO file, but DNN does not allow this.

## Description of solution
Change the check of the favicon to allow both PNG and SVG files

## Screenshots
![image](https://user-images.githubusercontent.com/8999382/127129717-8287f5ee-befa-47c1-8d84-808abdd0900d.png)

## Affected browser

* [x] Chrome
* [x] Firefox
* [x] Safari
* [x] Internet Explorer
* [x] Edge

**Comment by valadas** [comment]
PNG should be supported by most browsers (not IE <= 10), for SVG I am not sure.

**Comment by Timo-Breumelhof** [comment]
@valadas sure, but DNN does not allow you to use a PNG..

**Comment by valadas** [comment]
correct

**Comment by Timo-Breumelhof** [comment]
...
