### ISSUE TITLE
Upgraded from 9.8.1 to 9.10.0 and now have broken image icon for profile avatar

### ISSUE THREAD

**Issue by budhoward** [dnnsoftware/Dnn.Platform#4759]
I recently upgraded from 9.8.1 to 9.10.0 and now the profile avatars (on home page in upper right, and on profile page itself) do not display the actual profile avatar, but instead the broken image link and the alternate text of "Profile Avatar" are displayed.

The html source shows the img src is /DnnImageHandler.ashx?mode=profilepic&amp;userId=587&amp;h=32&amp;w=32&amp;cdv=637583215027800000

If I apply that link to the domain address I receive the following error message

<span style="color: rgb(0, 0, 0); font-family: Verdana; font-size: 11.2px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><h1 style="font-family: Verdana; font-weight: normal; font-size: 18pt; color: red;">Server Error in '/' Application.<hr width="100%" size="1" color="silver"></h1><h2 style="font-family: Verdana; font-weight: normal; font-size: 14pt; color: maroon;"><i>Value of 'null' is not valid for 'stream'.</i></h2></span><span style="color: rgb(0, 0, 0); font-family: Verdana; font-size: 11.2px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;"></span><font face="Arial, Helvetica, Geneva, SunSans-Regular, sans-serif " style="color: rgb(0, 0, 0); font-size: 11.2px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><b style="font-family: Verdana; font-weight: bold; color: black; margin-top: -5px;">Description:<span> </span></b>An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code.<br><br><b style="font-family: Verdana; font-weight: bold; color: black; margin-top: -5px;">Exception Details:<span> </span></b>System.ArgumentException: Value of 'null' is not valid for 'stream'.<br><br><b style="font-family: Verdana; font-weight: bold; color: black; margin-top: -5px;">Source Error:</b><br><br>

An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.
--
</font>

The stack trace is as follows:

[ArgumentException: Value of 'null' is not valid for 'stream'.]
   System.Drawing.Bitmap..ctor(Stream stream) +237
   DotNetNuke.Services.GeneratedImage.ImageTransform.CopyImage(Stream imgStream) +49
   DotNetNuke.Services.GeneratedImage.StartTransform.UserProfilePicTransform.ProcessImage(Image image) +112
   DotNetNuke.Services.GeneratedImage.ImageHandlerInternal.GetImageThroughTransforms(Image image) +110
   DotNetNuke.Services.GeneratedImage.ImageHandlerInternal.GetImageThroughTransforms(Byte[] buffer) +74
   DotNetNuke.Services.GeneratedImage.ImageHandlerInternal.HandleImageRequest(HttpContextBase context, Func`2 imageGenCallback, String uniqueIdStringSeed) +3551
   DotNetNuke.Services.GeneratedImage.ImageHandler.ProcessRequest(HttpContextBase context) +78
   DotNetNuke.Services.GeneratedImage.ImageHandler.ProcessRequest(HttpContext context) +44
   System.Web.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +814
   System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step) +132
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +73

**Comment by bdukes** [comment]
It looks like this is related to this section of code: https://github.com/dnnsoftware/Dnn.Platform/blob/746498be089bedcb0e70d8ffaa0c4eb67de7fbbe/DNN%20Platform/Library/Services/GeneratedImage/StartTransform/UserProfilePicTransform.cs#L48-L125

The two scenarios are where a user has a valid photo file and `FileManager.Instance.GetFileContent` is called on it to get a `Stream` which is passed to `CopyImage`, or there isn't a valid photo file, and `File.OpenRead(Globals.ApplicationMapPath + @"\images\no_avatar.gif")` is called to get a `Stream` which is passed to `CopyImage`.

Can you validate that `/images/no_avatar.gif` is accessible and can be read by the application? Can you validate whether there's a valid photo file for the user? Are you using a folder provider other than Standard (e.g. are your files stored in the database or on a third party storage system like AWS S3 or Azure)?

**Comment by budhoward** [comment]
Thank you.  I have reapplied permissions on all folders which has resolved the issue.
