### ISSUE TITLE
Cookie Consent may cause JavaScript error

### ISSUE THREAD

**Issue by bdukes** [dnnsoftware/Dnn.Platform#4762]
## Description of bug
DNN's cookie consent script uses `dnn.getVar` to read its options. However, it does not ensure that `dnn.js` is included on the page, so in scenarios where nothing else on the page requests `dnn.js` the functionality will fail.

## Steps to reproduce
1. Use a minimal theme
2. Turn on cookie consent
3. See error

## Affected version

* [ ] 10.00.00 alpha build
* [x] 09.09.00 latest supported release

**Comment by Tychodewaard** [comment]
@bdukes Great one! Do you know of a workaround until it is released? How do I request dnn.js for instance?
Just adding 
<script src="/js/dnn.js"></script> to the page header is not enough.

**Comment by bdukes** [comment]
I added this to a control that was included in all of the theme controls:

```
<script runat="server">
Protected Overrides Sub OnLoad(ByVal e As EventArgs)
    MyBase.OnLoad(e)
    DotNetNuke.Framework.JavaScriptLibraries.JavaScript.RegisterClientReference(Page, DotNetNuke.UI.Utilities.ClientAPI.ClientNamespaceReferences.dnn)
End Sub
</script>
```

**Comment by Tychodewaard** [comment]
Yeah, I created a work around in the past as well, involving registry of a component in the theme.
Thing is that for this particular client, I don't have FTP access and they use a commercial theme. 
So, was hoping to include some script in the head of a module... Just for a temp fix because we will be upgrading before the end of the year.

**Comment by bdukes** [comment]
I would think just including `/js/dnn.js` should work, maybe it needs to be included earlier than via a module header (e.g. in the page header)?

**Comment by Tychodewaard** [comment]
I tried <script src="/js/dnn.js"></script>
in the page header and in a module header...neither revives the cookie consent
