### ISSUE TITLE
Sign-out admin user during uploading file by html editor

### ISSUE THREAD

**Issue by arminrahimian** [dnnsoftware/Dnn.Platform#4767]
## Description of bug
Add Sub-Portal in DNN 09.09.00 or 09.10.00. When in dnn one or more sub-portals are defined and in that sub-portal a user with admin access (Not the super user, only Administrators) when he wants to edit the html module feed, or upload an image in that module the current user will logs out and has to log in again. 

## Steps to reproduce
List the precise steps to reproduce the bug:
1. Add Sub-Portal in DNN 09.09.00 or 09.10.00
2. Login as Administrator into sub-portal (Not Super User)
3. Edit Content an HTML module
4. try to edit or upload an image
5. See you will Log out

## Current behavior
Log out when you edit content or upload image in HTML module by Administrator user access. (No Super User Access)

## Expected behavior
Should be edit content or upload image and save changes without log out in HTML module by Administrator user access. (No Super User)

## Screenshots
[https://www.ecb.ir/logout-save-html-editor-dnn-9-9-and-9-10.mp4](url)

## Error information
no error

## Additional context
----
## Affected version
* [x] 09.10.00 latest supported release
* [x] 09.09.00 latest supported release

## Affected browser
* [x] Chrome
* [x] Firefox

**Comment by valadas** [comment]
I think this duplicates #4791 and was resolved in #4828 
We should be releasing a v9.10.2 RC very shortly if you can test that out when it does get out. If it's still an issue after that, please comment back and I'll reopen the issue.
