### ISSUE TITLE
Styling missing for personabar in IE11 

### ISSUE THREAD

**Issue by schotman** [dnnsoftware/Dnn.Platform#4787]
## Description of bug
Because of the use of CSS variables the personabar looks pretty bad. I do encourage the use of modern tech, this issue could be easily have been prevented.

## Steps to reproduce
open de site as an admin, you'll see

## Current behavior
styling issues, most obvious, missing backgrounds

## Expected behavior
What we had...

## Affected version
version 09.10.00 

## Affected browser
* [ ] Internet Explorer 11
![ie11-issue-personabar](https://user-images.githubusercontent.com/2582737/130201892-3ceb544a-6417-45ed-b5f0-c9d2dc9b229d.jpg)

**Comment by mitchelsellers** [comment]
Support for IE 11 is ending, Can you provide examples of what your are seeing

**Comment by bdukes** [comment]
See https://docs.microsoft.com/en-us/lifecycle/announcements/internet-explorer-11-support-end-dates and https://docs.microsoft.com/en-us/lifecycle/announcements/internet-explorer-11-end-of-support, among others

**Comment by bdukes** [comment]
That said, I don't think we've officially declared that the DNN Platform doesn't support IE 11. And we're certainly not opposed to PRs that add a better experience for IE 11 (so long as they don't significantly detract from the experience on newer browsers, e.g. due to performance issues)

**Comment by schotman** [comment]
I will add a pull request with some non-interfering styles

**Comment by hismightiness** [comment]
Ah... Mitch and Brian beat me to it.  😃

**Comment by Timo-Breumelhof** [comment]
> 
> 
> That said, I don't think we've officially declared that the DNN Platform doesn't support IE 11. And we're certainly not opposed to PRs that add a better experience for IE 11 (so long as they don't significantly detract from the experience on newer browsers, e.g. due to performance issues)

I hate IE just a much as most of you, but using HTML/CSS not supported by IE would probably be better for a major version. :-)
I have logged issues before where a minor change of (incorrect) HTML was seen as a breaking change.

**Comment by schotman** [comment]
just added an image to the issue of what you get when using IE11 (a not uncommon scenario when updating a site on a webserver)

**Comment by schotman** [comment]
> Ah... Mitch and Brian beat me to it. 😃

I was kind of reluctant to post this issue because it is obvious that IE11 is old crap, but on a server it is often the only browser, and when you update there e.g. from 9.9 to 9.10 you get a nasty surprise, and you might even think the update went wrong. 
We should not want the average IT Joe to think that...

**Comment by hismightiness** [comment]
> I was kind of reluctant to post this issue because it is obvious that IE11 is old crap, but on a server it is often the only browser  

Yes. That's the app you use to download an actual web browser.  😉😆
