### ISSUE TITLE
DNN9.10.0 Calling API/CKEditorProvider/CloudServices/GetToken results in user being logged out

### ISSUE THREAD

**Issue by ggiordan** [dnnsoftware/Dnn.Platform#4791]
## Description of bug
If a user in a portal other than the root portal calls API/CKEditorProvider/CloudServices/GetToken, the user will be logged out.  The user must not be a member of the root portal and from what I can see must not be a super user.

I think this is a different manifestation of the same problem:
[https://github.com/dnnsoftware/Dnn.Platform/pull/4773](https://github.com/dnnsoftware/Dnn.Platform/pull/4773)
In this case, fixing the javascript on the site doesn't help (it's an API call)

## Steps to reproduce
List the precise steps to reproduce the bug:
1. Create a new user in a portal that  is not the root portal.  this user must not exist in the root portal 
2. Log the user into the portal
3. Access url `https://<host>/API/CKEditorProvider/CloudServices/GetToken`
4. The response will be a 302 and the user is logged out (the cookie is wiped)

## Current behavior
The response will be a 302 and the user is logged out (the cookie is wiped)

## Expected behavior
A 200 response that does not log the user out

## Screenshots
![Capture](https://user-images.githubusercontent.com/3812056/130243287-fceb0832-6e33-4f51-bd2e-ca53fe676076.PNG)

## Error information
No errors other than the 302 response

## Additional context
In chasing this down, in the call to Authenticate in (MembershipModule.cs:99) request, this code returns the portal settings for portal 0, not the current portal:
```
// Obtain PortalSettings from Current Context
PortalSettings portalSettings = PortalController.Instance.GetCurrentPortalSettings();

```
So unless the logged in user is a user in portal 0, this results in a NULL being returned:
`var user = UserController.GetCachedUser(portalSettings.PortalId, context.User.Identity.Name);`

To see this happen do the following:

have a user who is not a member of portalid = 0
log that user in
from the current tab or another tab in your brower hit the URL: https://<host>/API/CKEditorProvider/CloudServices/GetToken
At this point the user is logged out... web server will return with a 302 and a delete the session login cookie

if you grab the process in the debugger, you will see that portalSettings.PortalId == 0 for the API call, but it's correct for all the other activity loading the page.

## Affected version

* [ ] 10.00.00 alpha build
* [x] 09.10.00 latest supported release

## Affected browser

* [x] Chrome
* [x] Firefox
* [x] Safari
* [x] Internet Explorer 11
* [x] Microsoft Edge (Classic)
* [x] Microsoft Edge Chromium

**Comment by valadas** [comment]
@ggiordan do you have steps to reproduce this other than "accessing that URL", I am not sure how to make this happen here. I am guessing it is with maybe some specific CKEditor Plugin maybe ?

**Comment by ggiordan** [comment]
Hi @valadas , it seems that the logout is caused when this is hit:
`https://<machine>/API/CKEditorProvider/CloudServices/GetToken`

The problem is that the user's current portal is getting lost and the API looks for the user in portal 0.  The API needs to look for the user in the correct portal.

**Comment by valadas** [comment]
Yeah, the thing is that I cannot get DNN to call that API, can you look into Site Settings -> Site Behaviour -> More -> Open HTML Editor Manager Then in that panel, go to the Editor Config tab and search for the word "Plugin", you should see a field with a list of plugins, can you put this list here...

![image](https://user-images.githubusercontent.com/6371568/132565600-702258f3-921f-4341-87c7-2c098608b78f.png)

**Comment by bdukes** [comment]
Are you using the Easy Image plugin? That's configuring in the _File Browser Settings_ tab.
![File Browser Settings tab with Easy Image Upload selected](https://user-images.githubusercontent.com/59507/132566836-f69070f4-ce8a-475b-a8f1-038453bf40f0.png)

**Comment by valadas** [comment]
Haaa, that was the missing piece, cool, I get it accessing that endpoint, I'll look into this
