### ISSUE TITLE
Google Tag Manager Connector not rendering on 404 Page

### ISSUE THREAD

**Issue by 10PoundGorilla-ChrisBehling** [dnnsoftware/Dnn.Platform#4793]
## Description of bug
When you attempt to visit a 404 page you will notice that the Google Tag Manager connector will not render. This prevents all connected properties in Tag Manager to not render on the page. This occurs only when you access a true 404 page. If you try to access the "physical" 404 page, you will notice the connector renders.

I am defining a "true" 404 page as a page that has not been created and that is dynamically being routed to the DNN set 404 page.

I am defining a "physical" 404 page as the official 404 page configured in DNN. This is a page that can be visited and edited. In this case we have a handful of modules on the "physical" 404 page. 

## Steps to reproduce
List the precise steps to reproduce the bug:
1. Go to: [https://www.tdicinsurance.com](https://www.tdicinsurance.com)
2. Inspect the dom and see that Tag Manager is being configured (search for GTM-5V3JNDK).

3. Go to: [https://www.tdicinsurance.com/test](https://www.tdicinsurance.com/test)
4. Inspect the dom and see that Tag Manager is not being configured (search for GTM-5V3JNDK).

5. Go to: [https://www.tdicinsurance.com/404](https://www.tdicinsurance.com/404) 
6. Inspect the dom and see that Tag Manager is being configured (search for GTM-5V3JNDK).

## Current behavior
The Google Tag Manager connector does not render on a true 404 page. The "physical" 404 page will render Tag manager.

## Expected behavior
Whenever a user lands on a 404 page, either a true 404 page or the "physical" 404 page, Tag Manager should load.

## Screenshots
[Home Page](https://www.dropbox.com/s/avu2l7hsawdepol/home.png)
[True 404 Page](https://www.dropbox.com/s/11qmfw6sn8kmzes/true-404.png)
[Physical 404 Page](https://www.dropbox.com/s/93ipthknw2rgjvd/404-page.png)

## Affected version
DNN Version: 09.08.00 

## Affected browser
[x] Chrome
[x] Firefox
[x] Safari
[x] Internet Explorer 11
[x] Microsoft Edge (Classic)
[x] Microsoft Edge Chromium

**Comment by valadas** [comment]
Hmm, the steps to reproduce are intended for a developer to be able to reproduce the issue to tackle it, here we have a specific site in production and it is a bit cryptic to talk about true vs physical 404 pages. Can you please create a new issue showing exactly how to make this happen from scratch. Thanks.
