### ISSUE TITLE
DNN Admin Logs do not send email notifications as expected

### ISSUE THREAD

**Issue by 10PoundGorilla-ChrisBehling** [dnnsoftware/Dnn.Platform#4794]
## Description of bug
We are not receiving email notifications for admin logs that are configured to send email notifications after a specific occurrence threshold. In an example **_HTTP Error Code 404 Page Not Found_** event, we configured the email notification to send after 1 occurrence, in 1 minute. After a few tests on a few different days we have never been able to receive these notification reports. 

## Steps to reproduce
List the precise steps to reproduce the bug:
1. Go to the DNN Admin Log
2. Click on Log Settings Tab
3. Scroll to "HTTP Error Code 404 Page Not Found" and click the pencil icon 
4. Make sure logging for this report is enabled
5. Enable email notifications
6. Set your desired frequency (in this case we used 1 occurrence, 1 minute)
7. Set the email address the report should be sent to
8. Save the settings
9. Visit a true 404 page

## Current behavior
When you visit a true 404 page, you should see the Admin Logs updated reporting the occurrence. With email notifications emailed, you will not receive an email of the event.

## Expected behavior
When email notifications are enabled you should receive an email when the event fires. In the case described above, if at least one 404 page error is logged within a minute, the email should be sent out.

## Screenshots
[Screen-shot of settings](https://www.dropbox.com/s/gtbtd4ds3inubsh/Admin-Log-Notifications.png?dl=0)

## Affected version
DNN Version: 09.08.00

## Affected browser
This is application level and not related to a browser.

**Comment by sleupold** [comment]
AFAIR this had been reported before, however, I am not sure, whether it has been already fixed in a later version of DNN 9.

**Comment by 10PoundGorilla-ChrisBehling** [comment]
@sleupold, that is correct. Issue #4657, showing it as an issue in even newer versions of DNN (9.9.1 in #4657) than what we are running on this example (9.8.0). We can close this issue if it makes sense to just reopen the other. It looks like it was closed automatically due to being stale.

**Comment by 10PoundGorilla-ChrisBehling** [comment]
After taking a closer look at #4657, it looks like my issue was with the Scheduler. By default, the Send Log Notifications scheduled task is disabled. Once enabled I was able to start receiving email notifications.

**Comment by sleupold** [comment]
@10PoundGorilla-ChrisBehling 
thank you for reporting back your findings :)

**Comment by shamimgkp** [comment]
Hello @sleupold Can you check this please.
I have same issue. Not able to share admin logs via email.
https://github.com/dnnsoftware/Dnn.Platform/issues/5024

**Comment by jeremy-farrance** [comment]
If it helps, possibly related: #4657
