### ISSUE TITLE
Upgrade to latest jQuery UI

### ISSUE THREAD

**Issue by bdukes** [dnnsoftware/Dnn.Platform#4816]
## Description of problem
https://blog.jqueryui.com/2021/09/jquery-ui-1-13-0-rc-2-released/ indicates that this next release is focused on compatibility with newer versions of jQuery. It seems good to adopt this version (even while the core is reducing its usage of jQuery UI) so that we don't prevent updates for folks.

## Description of solution
Update the JS Library (ensure jQuery Migrate is also up-to-date).

## Description of alternatives considered
Remove jQuery UI altogether (should those APIs be marked as deprecated?)

**Comment by Xand0r** [comment]
It may be worth noting that version 1.12 has known vulnerabilities with its datepicker:
https://snyk.io/test/npm/jquery-ui/1.12.1

**Comment by valadas** [comment]
Is #5114 a duplicate of this one or a bigger proposition?
