### ISSUE TITLE
Language skin object has current language in culture tokens

### ISSUE THREAD

**Issue by dieterdtx** [dnnsoftware/Dnn.Platform#4820]
## Description of bug
When adding the dnn Language skin object, you can provide values for ItemTemplate, AlternateTemplate, SelectedTemplate.
see https://www.dnnsoftware.com/wiki/language-skin-object or https://www.dnnsoftware.com/community-blog/cid/134633/the-language-skinobject-explained

The values of these attributes could be something like this:
<a href="[URL]">[CULTURE:TWOLETTERISOCODE]</a>

However, in DNN 9.10.1, everything that starts with CULTURE: holds the current language, instead of the language of the item.

See current behavior and expected behavior.

## Steps to reproduce
1. create an .ascx skin
2. add`
<%@ Register TagPrefix="dnn" TagName="LANGUAGE" Src="~/Admin/Skins/Language.ascx" %>`
3. add
```
<dnn:LANGUAGE runat="server" ID="dnnLANGUAGE" ShowLinks="True" ShowMenu="False"
SeparatorTemplate='&nbsp;'
ItemTemplate='<a href="[URL]">[CULTURE:TWOLETTERISOCODE]</a>'
AlternateTemplate='<a href="[URL]">[CULTURE:TWOLETTERISOCODE]</a>'
SelectedItemTemplate='<a href="[URL]">[CULTURE:TWOLETTERISOCODE]</a>' /> 
```
4. See behavior

## Current behavior
Renders this html (portal with 3 languages, I removed the domain names for readability, please note the "nl" 3 times.
```

<a href="http://www.mysite.com/nl/">nl</a>&nbsp;
<a href="http://www.mysite.com/fr/">nl</a>&nbsp;
<a href="http://www.mysite.com/en/">nl</a>
```

## Expected behavior
This is the expected result, with the item language. This worked in DNN 8.4
```

<a href="http://www.mysite.com/nl/">nl</a>&nbsp;
<a href="http://www.mysite.com/fr/">fr</a>&nbsp;
<a href="http://www.mysite.com/en/">en</a>
```

## Additional context
Content localization is enabled.

All these tokens appear to work: [URL] [FLAGSRC] ...
**The ones starting with CULTURE don't**: [CULTURE:TWOLETTERISOCODE] [CULTURE:NAME] ...

## Affected version
* [x] 09.10.01 latest supported release

## Affected browser
(NA)
* [x] Chrome

**Comment by valadas** [comment]
It appears to be working fine for me, did you get that just from a clean install or is there something more to it maybe causing it ?

**Comment by dieterdtx** [comment]
After comparing installations it could be a 3rd party module (I thought the installation was clean).

I will investigate further and close this issue soon if this is the case.

**Comment by dieterdtx** [comment]
It was after 3rd party software was installed.

I didn't expect this to influence core DNN tokens.
