### ISSUE TITLE
Resource Manager module in Group mode allows user to navigate outside of their Group folder

### ISSUE THREAD

**Issue by puresystems** [dnnsoftware/Dnn.Platform#4825]
## Description of bug
ResourceManager module in Group mode allows the user to navigate back up the folder tree. I would expect it to not allow this so the user can only see what's in their group folder.

## Steps to reproduce
1. Add the Resource Manager onto the Group Activity page of a DNN install.
2. Via the Resource Manager module settings, set the Mode to "Group" and save.
3. Visit the page via the Groups Directory and it will set the default folder of the Resource Manager to the appropriate Groups folder.
4. Via the Folder tree control in the header of the Resource Manager module, you can navigate back up the folder tree.

## Current behavior
Allows a group user to navigate outside of their group folder.

## Expected behavior
Lock the user into the Group folder

## Affected version

* [ ] 10.00.00 alpha build
* [x] 09.10.01 latest supported release

**Comment by cgentryls** [comment]
I wonder if this is related to my open issue #4573 ?

**Comment by valadas** [comment]
Can you expand a bit on the steps to reproduce, many developers out here almost never use the social features. I think you need to setup a group and then create a folder and set the permissions for the groups, etc.

**Comment by david-poindexter** [comment]
@puresystems you may be interested in testing the new Resource Manager.  For a test you can take the install package from the build artifacts on #5240 and see if this issue still exists.

**Comment by bdukes** [comment]
The latest build artifacts can be downloaded from https://artprodwus21.artifacts.visualstudio.com/Ad394b248-b709-4c8a-9adc-6ed9de8c8163/9defc7c7-d48d-4a8b-9f46-fd11ba3c5aad/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL2RvdG5ldC9wcm9qZWN0SWQvOWRlZmM3YzctZDQ4ZC00YThiLTlmNDYtZmQxMWJhM2M1YWFkL2J1aWxkSWQvNzczNjYvYXJ0aWZhY3ROYW1lL0FydGlmYWN0czE1/content?format=zip

To get there yourself, go to https://dev.azure.com/dotnet/DNN/_build, click on the [_dnnsoftware.Dnn.Platform_ pipeline](https://dev.azure.com/dotnet/DNN/_build?definitionId=145) and select the most recent pipeline run (this part can be tricky to know what's a "good" build and what's a PR build, but generally if a build is green it's okay. If it says it's for the `release/9.11.0` branch then that's the best sign that it'll have the latest Resource Manager). Once you click on the pipeline run, the header will have a link the _Artifacts_, and from there you can download what the pipeline run generated, including the Install and Upgrade packages.

Hope it helps!

**Comment by puresystems** [comment]
Thanks, we'll test this out on a new install.
