### ISSUE TITLE
Better default Scheduler settings

### ISSUE THREAD

**Issue by EPTamminga** [dnnsoftware/Dnn.Platform#4832]
## Description of problem
The default scheduler settings on a clean install are not good for development and not for production.

## Description of solution
The default scheduler settings should be set for best practices for production so that new sites get the best setting for runtime. E.g. site export/import should be OFF, site crawler less frequent, ...
Of course, settings can be different for sites and purposes, but the default should be mainstream correct out-of-the-box.

## Description of alternatives considered
Create documentation in the DNN.DOCS and/or improve the help labels so that host/admins can make the right decision.
Currently, there is no documentation, 

## Screenshots
Default settings on a clean install
![image](https://user-images.githubusercontent.com/5859855/133765682-6b66d005-aed1-4e8c-b24c-3c2190af5dff.png)

## Additional context
There is a reference on DNNSoftware.com:
http://www.dnnsoftware.com/Content/Dnn.Platform/Documentation/Using%20the%20Control%2[…]/Host%20Console/Schedule/List%20of%20Scheduler%20Tasks.html

## Affected browser

* [X] Chrome
* [X] Firefox
* [X] Safari
* [X] Internet Explorer
* [X] Edge

**Comment by hismightiness** [comment]
Nice issue!  Thanks for creating it, @EPTamminga!  :)

**Comment by WillStrohl** [comment]
Still relevant.
