### ISSUE TITLE
Remove the use of "Whitelist" Terminology

### ISSUE THREAD

**Issue by mitchelsellers** [dnnsoftware/Dnn.Platform#4835]
## Description of problem
A number of locations within the DNN Platform use the term Whitelist to represent "allowed" actions.  This should be updated to become an "Allowed List" or similar.

## Description of solution
Rename of all existing references to whitelist.

## Description of alternatives considered
N/A

## Additional context
This is part of an ongoing effort to provide a supportive and inclusive open-source project environment.

**Comment by mitchelsellers** [comment]
@dnnsoftware/approvers I would like to make this change, but looking at the surface areas of this we will need to make a number of renames to public API's such as the "FileExtensionWhitelist" and other API's.  Following current policies this is then not possible to remove until version 11.0.

Do we have any thoughts on how we might address this sooner?

**Comment by david-poindexter** [comment]
@mitchelsellers how are other major open-source projects handling this?  Do we have any to cite or that provide some precedent?

**Comment by mitchelsellers** [comment]
There is a pretty big mass push to get rid of the terms such as: Whitelist, Blacklist, Master/Slave, etc.  There is no standard.

**Comment by bdukes** [comment]
I think the most we can do is deprecate the API we don't want and add the API that'll replace it.

**Comment by mtrutledge** [comment]
I agree with this.

**Comment by hismightiness** [comment]
I'm in full support of this change overall, but isn't the API side of things is far less important for this kind of update?  Especially for the reason it's being made?  

Perhaps this could be two different updates...?  One for the API and another for the static/UI/localized text.

**Comment by david-poindexter** [comment]
There seems to be an active push in open-source for not only visible (think UI) changes, but also at the core of the codebase (think APIs and such).  In reviewing our [versioning policy](https://github.com/dnnsoftware/Dnn.Platform/blob/develop/.github/VERSIONING_POLICY.md), it seems we can do as @bdukes stated and mark the appropriate APIs for remove and include the new ones.  If we get this done in v9, then they can be removed in v10.

**Comment by hismightiness** [comment]
@david-poindexter I completely understand and fundamentally agree.  I'm only suggesting that as a question to the approach since I think this appears to be a much larger effort and impact than it may seem to be here.  Breaking it out could use different people and timelines.  Either way, both should be done.  :)

**Comment by mitchelsellers** [comment]
The effort and initiatives I’m seeing are more involved with the code than the actual UI in importance actually as the concern is about the project supporting diversity and inclusion at a fundamental level.
