### ISSUE TITLE
RFC / Story: Preserve Login on Portal Switches

### ISSUE THREAD

**Issue by iJungleboy** [dnnsoftware/Dnn.Platform#4841]
## Description of problem

Imagine a site with this setup:

1. www.company.com - the global website with many pages
2. www.company.com/partners - a separate site for partners only
3. www.company.com/shop - a separate site containing the shop application

As of now, we often have the problem that in such a scenario, a partner will log in on `/partners` and work a bit, then because of normal clicking, the user goes to to the main portal www.company.com. At this moment the user is not known on that site, and will be logged off instantly. If the user now returns to `/partners` he will have to log on again. This is very confusing and neither the affected users (the partners) nor the owner of the site feel like this behavior should be this way.

The reason is that Dnn of course only has 1 login-state cookie and if it determines a login of an unknown user (the main portal doesn't know the users of the sub-portal) it will flush the login.

## Description of solution

I see two possible solutions:

### Solution 1: Don't flush the Login-Cookie (not recommended)

Here we could ignore the invalid logins and don't flush it. This is probably not ideal, because it may have unexpected side-effects

### Solution 2: Store each Login in a backup-Cookie (recommended)

We could store logins as two cookies:

1.  one for current-user-use - just like is the case now
2. Another one which is portal (or portal-group specific) which is for later when the primary login isn't valid

The behavior would then be as such

1. If the user is known, use that identity (just like is now)
2. If the user is not known, flush the primary identity (just like now), BUT in addition, check if there is another login in the backup-cookie for this portal-group. If yes, restore that identity for the user.

Your thoughts?

**Comment by mitchelsellers** [comment]
At this point in time, I believe that we should leave this functionality as-is.  The current model discards any login cookie that is not valid, and in the situation above a user that doesn't have access to site 1, but does to site 2, will have their cookie removed when they visit Site 1.

Although for some this default behavior is a bit unwanted, it is defaulting the platform to SECURE first, which is something I believe we should always consider. 

There are currently a number of workarounds for this situation, including the usage of Portal Groups that would allow the user to seamlessly transition across the sites.  Or by setting the cookie domain with common usernames.

The addition of an additional security cookie/token would be an incredibly invasive change and would introduce a large security vector that would very strong review.

**Comment by valadas** [comment]
I agree with this, we recently fixed an issue regarding child portals which helps some scenarios, we have portal groups in place too and support out-of-the-box a common auth-domain for scenarios like products.mydomain.com vs services.mydomain.com

I am not against some sort of opt-in sso solution but I believe for security reasons it would be best to be an add-on and not something we make part of the core, just thinking about people simply configuring it wrong and exposing other sites to security issues.
