### ISSUE TITLE
add nonce or hash to all inline JavaScript code so we can add "Content-Security-Policy" header to improve site security

### ISSUE THREAD

**Issue by lisaied** [dnnsoftware/Dnn.Platform#4850]
We added "Content-Security-Policy" header into web.config as below
<add name="Content-Security-Policy" value="default-src 'self';" />

-> 1) then got many errors in console,
Refused to execute inline script because it violates the following Content Security Policy directive: "default-src 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-61pmiHV+Vocw495XPQ8NZfL3oVPgWETwwMYt7YuilsU='), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'script-src' was not explicitly set, so 'default-src' is used as a fallback.

-> 2) search box is not working

**Comment by valadas** [comment]
I don't know how we could implement this given we are a platform and any page can have 3rd party extension...

**Comment by bdukes** [comment]
We could :one: add hashes to script tags that we introduce and :two: provide helper methods to generate hashes for script tags that 3rd party extensions introduce. But I don't have a sense of how close that would get us towards the goal. Is that a 50% solution or a 99% solution?

**Comment by valadas** [comment]
Now if there are multiple scripts, is it one hash for all the scripts concatenated or 1 hash per script?

**Comment by bdukes** [comment]
I just [looked up the details](https://web.dev/strict-csp/) and it works differently than I was thinking.

## Nonce-based CSP

Add `script-src 'nonce-{RANDOM}'` as a value in the `Content-Security-Policy` HTTP header and then include the `{RANDOM}` value in each script tag, e.g.

```http
Content-Security-Policy: script-src 'nonce-xyz123'
```

```html
<script nonce="xyz123">1</script>
<div></div>
<script nonce="xyz123">2</script>
```

The nonce value needs to change for each request.

## Hash-based CSP

Include the hash of the contents each script on the page in the `Content-Security-Policy` HTTP header, e.g.

```http
Content-Security-Policy: script-src 'sha256-a4ayc/80/OGda4BO/1o/V0etpOqiLx1JwB5S3beHW0s=' 'sha256-1HNeOiZeFu7gP1lxi5tdAwGcB9i2xR+Q2jpmbuwTqzU='
```

```html
<script>1</script>
<div></div>
<script>2</script>
```

So, either way, we need to be adding or updating a `Content-Security-Policy` header. The nonce seems like the simpler option of the two, though mildly less secure.

**Comment by valadas** [comment]
Hmm, the nonce could not be too crazy maybe, still does not handle 3rd party modules unless they use CDF.

**Comment by lisaied** [comment]
Yes @bdukes, nonce simpler, and per request. I would think about an option in web.config, it adds the CSP to the header with a generated nonce. Also DNN developers should have access to the current request CSP nonce so they can use it to register there JS code with the current nonce.

**Comment by bdukes** [comment]
@lisaied to be clear, I think we believe this is an idea worth exploring, but no one has committed to developing this functionality. Let us know if you want direction on implementing this change as a pull request.
