### ISSUE TITLE
MVC module gives exception on attempt to access css or js files. Including default module.css.

### ISSUE THREAD

**Issue by Constantine-Ketskalo** [dnnsoftware/Dnn.Platform#4869]
## Description of bug
MVC module can't use neither css nor js files. 

P.S. I've also reported this bug to [DotNetNuke Module and Theme Development Template](https://github.com/ChrisHammond/DNNTemplates/issues/67). Not sure which repo is a correct one to report this one. If I should delete one of them - please let me know.

## Steps to reproduce
1. Create DAL2 MVC Module
2. Compile and install that module
3. Make sure you're logged in as superuser to see details of all errors
4. Open dev tools and see error in console
5. Look for module.css link in a source tab of dev tools and try to open link to module.css of your module in a new tab and see detailed error message

## Current behavior
Assets files (css, js) are not able to be used in an MVC module.

## Expected behavior
Assets files (css, js) should be available for usage in an MVC module.

## Error information
For default module.css dev tools' console has this error:
`Failed to load resource: the server responded with a status of 500 (Internal Server Error) module.css`

And when I try to open link to module.css of my module in a separate tab I get this error text:
```Server Error in '/desktopmodules/mvc/ModuleName' Application.
Could not load file or assembly 'DotNetNuke.HttpModules' or one of its dependencies. The system cannot find the file specified.
Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code.

Exception Details: System.IO.FileNotFoundException: Could not load file or assembly 'DotNetNuke.HttpModules' or one of its dependencies. The system cannot find the file specified.

Source Error:

An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.

Assembly Load Trace: The following information can be helpful to determine why the assembly 'DotNetNuke.HttpModules' could not be loaded.


WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

Stack Trace:


[FileNotFoundException: Could not load file or assembly 'DotNetNuke.HttpModules' or one of its dependencies. The system cannot find the file specified.]
   System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMarkHandle stackMark, IntPtr pPrivHostBinder, Boolean loadTypeFromPartialName, ObjectHandleOnStack type) +0
   System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean loadTypeFromPartialName) +96
   System.Type.GetType(String typeName, Boolean throwOnError, Boolean ignoreCase) +65
   System.Web.Compilation.BuildManager.GetType(String typeName, Boolean throwOnError, Boolean ignoreCase) +62
   System.Web.Configuration.ConfigUtil.GetType(String typeName, String propertyName, ConfigurationElement configElement, XmlNode node, Boolean checkAptcaBit, Boolean ignoreCase) +50

[ConfigurationErrorsException: Could not load file or assembly 'DotNetNuke.HttpModules' or one of its dependencies. The system cannot find the file specified.]
   System.Web.Configuration.ConfigUtil.GetType(String typeName, String propertyName, ConfigurationElement configElement, XmlNode node, Boolean checkAptcaBit, Boolean ignoreCase) +572
   System.Web.Configuration.ConfigUtil.GetType(String typeName, String propertyName, ConfigurationElement configElement, Boolean checkAptcaBit) +31
   System.Web.Configuration.Common.ModulesEntry.SecureGetType(String typeName, String propertyName, ConfigurationElement configElement) +59
   System.Web.Configuration.Common.ModulesEntry..ctor(String name, String typeName, String propertyName, ConfigurationElement configElement) +59
   System.Web.HttpApplication.BuildIntegratedModuleCollection(List`1 moduleList) +221
   System.Web.HttpApplication.GetModuleCollection(IntPtr appContext) +1103
   System.Web.HttpApplication.RegisterEventSubscriptionsWithIIS(IntPtr appContext, HttpContext context, MethodInfo[] handlers) +122
   System.Web.HttpApplication.InitSpecial(HttpApplicationState state, MethodInfo[] handlers, IntPtr appContext, HttpContext context) +173
   System.Web.HttpApplicationFactory.GetSpecialApplicationInstance(IntPtr appContext, HttpContext context) +255
   System.Web.Hosting.PipelineRuntime.InitializeApplication(IntPtr appContext) +347

[HttpException (0x80004005): Could not load file or assembly 'DotNetNuke.HttpModules' or one of its dependencies. The system cannot find the file specified.]
   System.Web.HttpRuntime.FirstRequestInit(HttpContext context) +552
   System.Web.HttpRuntime.EnsureFirstRequestInit(HttpContext context) +122
   System.Web.HttpRuntime.ProcessRequestNotificationPrivate(IIS7WorkerRequest wr, HttpContext context) +737
```

## Additional context
* [ ] Windows 10
* [ ] Visual Studio Community 2019  v16.11.2
* [ ] DNN Project Templates 10.2

## Affected version

* [ ] 09.10.00 one of latest supported release

## Affected browser

* [ ] Chrome 94.0.4606.71

**Comment by WillStrohl** [comment]
@david-poindexter @mitchelsellers @bdukes I'm guessing we should close this since the other noted issue is closed and there are no responses on either issue.

**Comment by david-poindexter** [comment]
> @david-poindexter @mitchelsellers @bdukes I'm guessing we should close this since the other noted issue is closed and there are no responses on either issue.

Your comment removed the `stale` label, which will prevent the automatic closing of the issue for this period of time.  I agree with you though and will manually close the issue.

**Comment by Constantine-Ketskalo** [comment]
> Are you able to see the `module.css` in the file system when this occurs? This could simply be a deployment/build issue.

Of course I'm able to see it in the file system. Otherwise I wouldn't be able to edit it. But I checked the file in an explorer for you just in case and yes, it's there.

**Comment by Constantine-Ketskalo** [comment]
And sorry for the delay. Please, reopen it.

**Comment by WillStrohl** [comment]
This appears to be an issue with the project.  I personally have numerous MVC modules on all recent versions of DNN Platform and don't have this issue.  You'll want to continue troubleshooting with Chris Hammond.  The project packaging and source code for your project/solution is the most likely cause unless you have a different set of steps to reproduce.  Sorry.

**Comment by Constantine-Ketskalo** [comment]
I've tried to create a new MVC project and it has the same issue with this file. Just an empty MVC module.

**Comment by WillStrohl** [comment]
That's 100% not a DNN issue.  I'm sorry.  :(

**Comment by Constantine-Ketskalo** [comment]
> 

I've stumbled upon this issue that there was virtual folder instead of a real one in IIS. Chris Hammond mentioned it in his video instructions of DNN setup. So I handled that already. And I didn't see any additional virtual folders there. But I'll double check that next time I have access there. Thanks for the tip.

And regarding affecting the whole site - other non-MVC modules have no such issue. Whole website works perfectly. The only thing is that it can't add local css or js files from inside of an MVC DNN module.

**Comment by bdukes** [comment]
Yes, that's what leads me to believe that there's an issue with a subfolder application or virtual directory, which would only affect requests to that path. Another option is that the `web.config` file in the `DesktopModules/MVC` folder has some strange configuration in it which is causing the error only for that path.
