### ISSUE TITLE
Unable to Edit Default Pages

### ISSUE THREAD

**Issue by cklenk** [dnnsoftware/Dnn.Platform#4877]
## Description of bug
Unable to edit default pages under site behavior in 9.10.2. Displaying "There was an error retrieving your content. Please check your internet connection."

## Steps to reproduce
List the precise steps to reproduce the bug:
1. Log into site
2. Go to settings => site settings

## Current behavior
Unable to edit the settings. Receiving error.

## Expected behavior
Able to edit the default pages under site behavior.

## Screenshots
![image](https://user-images.githubusercontent.com/12185742/137555061-d5101069-2458-4127-9dab-b54f3645e48d.png)
![image](https://user-images.githubusercontent.com/12185742/137555340-dcbbebc8-aa4b-4f55-b81c-dd796de8d37a.png)

## Error information
reducers.ts:107 Uncaught TypeError: c is not a function
    at u (reducers.ts:107)
    at v (reducers.ts:107)
    at exports.unstable_runWithPriority (reducers.ts:107)
    at cg (reducers.ts:107)
    at Jj (reducers.ts:107)
    at yj (reducers.ts:107)
    at Ig (reducers.ts:107)
    at bk (reducers.ts:107)
    at reducers.ts:107
    at Nj (reducers.ts:107)

GET http://dnn9102.dnndev.me/API/PersonaBar/SiteSettings/GetDefaultPagesSettings?portalId=undefined&cultureCode= 500 (Internal Server Error)

## Additional context
Set up brand new test site, used NVQuickSite to create it. No errors in admin logs.

## Affected version

* [ ] 10.00.00 alpha build
* [X] 09.10.02 release candidate
* [ ] 09.10.01 latest supported release

## Affected browser

* [X] Chrome
* [X] Firefox
* [ ] Safari
* [ ] Internet Explorer 11
* [ ] Microsoft Edge (Classic)
* [X] Microsoft Edge Chromium

**Comment by david-poindexter** [comment]
Thanks for reporting this issue.  It was already resolved via #4851 so we'll go ahead and close this issue.
