### ISSUE TITLE
Account login module not respecting site behavior settings

### ISSUE THREAD

**Issue by cklenk** [dnnsoftware/Dnn.Platform#4881]
## Description of bug
Account login module redirects to home page.

## Steps to reproduce
List the precise steps to reproduce the bug:
1. Go to add module
2. Click on account login
3. Scroll to add to any pane on page
4. Set modules to be visible by registered users only

## Current behavior
After the user logs in using the account login module on the page, the user is redirect back to the home page.

## Expected behavior
After the user is authenticated I would think it would just refresh the page and not redirect to the home page. This adds extra steps in the authentication process.

## Screenshots
![image](https://user-images.githubusercontent.com/12185742/137801600-8c3401b5-937a-4f5e-bc12-4ea3b44d276b.png)
Account login setup
![image](https://user-images.githubusercontent.com/12185742/137801734-0859bd7f-66b6-4a5a-b756-8a6f7ddd8acc.png)
Site behavior setup

## Error information
N/A

## Additional context
N/A

## Affected version

* [ ] 10.00.00 alpha build
* [ ] 09.10.02 release candidate
* [X] 09.10.01 latest supported release

## Affected browser

* [X] Chrome
* [X] Firefox
* [ ] Safari
* [ ] Internet Explorer 11
* [ ] Microsoft Edge (Classic)
* [X] Microsoft Edge Chromium

**Comment by valadas** [comment]
Is this on the registration page, on the login page or on another page.
If it's on the login or registration page, then this is by design.

**Comment by cklenk** [comment]
This is on another page different from registration or login page.

Thanks
-Cameron

**Comment by cklenk** [comment]
Due to no response from anyone else I will close this. It seems like I resolved my problem (read previous comment for solution).

Thanks
Cameron
