### ISSUE TITLE
Version 9.11.0 Upgrade/Install Changes

### ISSUE THREAD

**Issue by mitchelsellers** [dnnsoftware/Dnn.Platform#4887]
## Description of problem

Current versions of the DNN Platform are distributed with Telerik installed and optional steps are necessary to disable Telerik after an installation or upgrade.  The behavior of the DNN Platform should be changed in 9.11.0 to achieve the following goals.

* New Installations of DNN Platform should be Telerik-Free By Default
* Upgraded installations should be prompted with a suggestion of removal of Telerik, if they opt-in, Telerik should be removed
  * Best efforts should be made to try and validate that the Telerik removal can be done safely (Telerik Identifier source could be used for this)
* Auto-Upgraded installations (using `/install/install.aspx?mode=upgrade`) will retain Telerik

These changes will result in the DNN Platform being secure by default, and only allowing users to opt-out of security if needed

## Description of solution

The following changes will be needed to complete the above-listed goals.

### Install-Package Changes

- [x] #4895
- [x] #4894
- [x] #4893 
- [x] #4943
       - `DotNetNuke.Telerik.Web` (DotNetNuke Telerik Web Components)
       - `DigitalAssetsManagement` (Digital Asset Management)
       - `DotNetNuke.Web.Deprecated` (DNN Deprecated Web Controls Library)
       - `DotNetNuke.Website.Deprecated` (DNN Deprecated Website Codebehind files)
- [x] #4944
- [x] #4945
- [x] #4942

### Upgrade Experience Changes

- [x] #4946
- [x] #4888

### Security Analyzer Changes

- [x] #4947
        - Fail if Telerik Installed & Used - Give warning about 10.x upgrade issue
        - Fail if Telerik Installed & Not-Used - Give message about the removal
        - Pass if Telerik Not Installed
- [x] #4948
       - If User Registration = `None` or `Private` and Either of these pages are visible to all users, warn that user profile information is displayed publicly
       - For all other user registration values, show an informational message if user profiles are public

**Comment by david-poindexter** [comment]
I have the template changes on my list of TODOs.  Are you wanting separate tasks to be created for each?

**Comment by mitchelsellers** [comment]
@david-poindexter Most likely it woudl be easier, can convert one/all to individual tasks for tracking

**Comment by david-poindexter** [comment]
Thanks @mitchelsellers - I just converted those three items to issues and linked for tracking.

**Comment by daguiler** [comment]
Hi @mitchelsellers
I'm working on #4946 and I'm not clear about the difference with #4888.
Isn't #4888 actually included in #4946 ?

**Comment by bdukes** [comment]
Yes, they're connected. #4946 is primarily about adding the prompt. #4888 is about what happens when you make the choice via that prompt to remove Telerik.

**Comment by valadas** [comment]
I believe we have it all covered here 😄 
<img src="https://media4.giphy.com/media/ZmuUzqOIEojjnd4tN8/giphy.gif"/>

**Comment by david-poindexter** [comment]
<img src="https://media0.giphy.com/media/xTiTnBMEz7zAKs57LG/giphy.gif"/>
