### ISSUE TITLE
Update Upgrade Process to remove Telerik

### ISSUE THREAD

**Issue by mitchelsellers** [dnnsoftware/Dnn.Platform#4888]
The process to remove Telerik during DNN 9.11.0 upgrade should include the following actions

* Install Resource Manager
* Update all Digital Asset Manager modules to be Resource Manager modules
* Uninstall DigitalAssetsManagement (Digital Asset Management)
* Uninstall DotNetNuke.Web.Deprecated (DNN Deprecated Web Controls Library)
* Uninstall DotNetNuke.Website.Deprecated (DNN Deprecated Website Codebehind files)
* Uninstall DotNetNuke.Telerik.Web (DotNetNuke Telerik Web Components)
* Uninstall DNNSecurityHotFix20171 (DNN Security HotFix 2017.1)
* Remove SiteUrls.config entries for Telerik
* Remove packages from App_Data\ExtensionPackages for all above uninstalled packages

**Comment by daguiler** [comment]
I'm scratching my head with this one.
Any ideas on how to go about it @mitchelsellers @valadas @david-poindexter @bdukes ?

**Comment by valadas** [comment]
This has been done in https://github.com/dnnsoftware/Dnn.Platform/pull/5212
