### ISSUE TITLE
Existing Website Templates should be updated to make `Activity Feed`, `My Profile`, `Friends`, and `Messages` pages visible to `Registered Users` only by default

### ISSUE THREAD

**Issue by david-poindexter** [dnnsoftware/Dnn.Platform#4894]
## Description of problem
Currently `Activity Feed`, `My Profile`, `Friends`, and `Messages` pages are visible to `All Users`.  These pages should be visible only to `Registered Users` by default.

## Description of solution
The website templates need to be updated to implement this change.

## Description of alternatives considered
n/a

## Screenshots
![image](https://user-images.githubusercontent.com/4568451/143727256-761f8c61-13de-490f-98ea-40cc6d6307b2.png)

## Additional context
n/a

## Affected browser
* [x] Chrome
* [x] Firefox
* [x] Safari
* [x] Internet Explorer
* [x] Edge

**Comment by armaganpekatik** [comment]
This change doesn't effect anything.
https://github.com/dnnsoftware/Dnn.Platform/compare/develop...armaganpekatik:bugfix/Issue-4894?expand=1
Is there any other places that change the behavior?
