### ISSUE TITLE
Scheduled tasks can never retrieve value of IsOverridingDefaultSettingsEnabled()

### ISSUE THREAD

**Issue by robsiera** [dnnsoftware/Dnn.Platform#4900]
## Description of bug
Issue #4489 brought to light that Scheduled tasks can never retrieve the value for clientResourcesSettings.IsOverridingDefaultSettingsEnabled, as this will return **false** because the portalId cannot be determined.

## Steps to reproduce
Setup a debug environment with some scheduled tasks and start running debug mode.
Once one of the scheduled tasks start, it will hit an error in GetPortalIdThroughReflection().

## Current behavior
Because the portalId cannot be determined, IsOverridingDefaultSettingsEnabled() will always return false.

## Expected behavior
Return the correct setting value.

## Affected version
* [x] 10.00.00 alpha build
* [x] 09.10.02 release candidate
* [x] 09.10.01 latest supported release

**Comment by bdukes** [comment]
Resolved via https://github.com/dnnsoftware/Dnn.Platform/pull/4901
