### ISSUE TITLE
v9.10.1 404 pages do not load CSS when composite files is enabled.

### ISSUE THREAD

**Issue by Afacts** [dnnsoftware/Dnn.Platform#4908]
## Description of bug
If composite files are enabled for the site and utilized in the skin file that is used for the 404 page, the composited files don't load. They give a 404 error in development tools

## Steps to reproduce
List the precise steps to reproduce the bug:
1. Go to 'Server Settings' > 'Performance'
2. Enable composite files for both js and css > Hit 'Save'
3. Click the 'Increment Version' button
4. Be sure that under 'Site Settings' > 'Site Behavior' > 'Default Pages' that your 404 page is set for the '404 error page'
5. Go to your url specifying a page that doesn't exist to trigger the 404 page (www.mysite.com/pagedoesntexist)

## Current behavior
The 404 page will come up with no css loaded so it will display strangely

## Expected behavior
Should load with the specified styles in the css file

## Error information
Provide any error information (console errors, error logs, etc.) related to this bug.
Failed to load resource: the server responded with a status of 404 () - https://www.mysite.com/DependencyHandler.axd/559dd8d42b38e9b71e7434a66803d144/663/js

Failed to load resource: the server responded with a status of 404 () - 
https://www.mysite.com/DependencyHandler.axd/33070d2c2d728077238656610b0357a8/663/css

## Workaround
Create a skin for the 404 page that doesn't need or utilize the CRM control:
<%@ Register TagPrefix="dnn" Namespace="DotNetNuke.Web.Client.ClientResourceManagement" Assembly="DotNetNuke.Web.Client" %>

## Affected version
* [ ] 10.00.00 alpha build
* [ ] 09.10.02 release candidate
* [X] 09.10.01 latest supported release

## Affected browser
* [X ] Chrome
* [X] Firefox
* [X] Opera
* [Not Tested] Safari
* [Not Tested] Internet Explorer 11
* [Not Tested] Microsoft Edge (Classic)
* [Not Tested] Microsoft Edge Chromium

**Comment by trouble2** [comment]
Still happening on DNN 9.11.0

**Comment by MarNothing** [comment]
This is still happening.
When you activate the CRM on a child or sub portal, so:

https:// www.website.com/child

The CRM gives a 404 error like stated above.

**Comment by josey-baker** [comment]
Is this going to be fixed? We still see this happening on 404 pages.  Or is there a way to exclude a page from Composite Files?

**Comment by valadas** [comment]
I cannot reproduce this in 10.0.1

<img width="1165" height="1013" alt="Image" src="https://github.com/user-attachments/assets/b64bae1e-0a13-4fd5-b636-a7429b9363bc" />

Ca you guys try on a clean new install of 10.0.1 to see if it could be something environmental?

**Comment by josey-baker** [comment]
Thanks, I'll take a look.  We are just starting to upgrade all our 9.11 sites to 10.
