### ISSUE TITLE
Static Code Analysis Suggestions for Resolution

### ISSUE THREAD

**Issue by VasilievSerg** [dnnsoftware/Dnn.Platform#4918]
My apologies in advance for an unusual bug-report. I guess it’s not the best idea to open dozen of issues for the code. 
So, I’ll describe the problem here.

I checked the source code with the PVS-Studio static analyzer and found several suspicious fragments. I listed and described those fragments [here](https://pvs-studio.com/en/blog/posts/csharp/0890/).

For each warning there is a file and the line that triggered the analyzer. Since I checked the project a month ago, some positions might have shifted (but not much, I think).

You can ignore Issue 10 and Issue 21 - these are false positives

I hope this article would make a small contribution to the project’s code quality and enhance it a little. :)

**Comment by mitchelsellers** [comment]
@VasilievSerg We appreciate all contributions that work towards the improvement of the code quality for the DNN Platform project.

In a cursory review of your article, there are items that have been noticed in prior analysis that has been completed on the codebase with tools such as NDepend or SonarCloud, and some new items.  As you can imagine given the 20+ year history of the DNN Platform not all of these have been addressed yet, and some of these changes although "simple" could result in breaking changes to users which will have to be considered.

Given that it appears you have used your own commercial product to analyze our project and post the results, it would be helpful if you could provide a listing of the impacted code files, with full paths  if possible.  As although helpful, the snippets provided here are not an actionable resolution for the project aside from attempted "find" operations across the codebase.

**Comment by thienvc** [comment]
Omg 😱😱😱, too many bad code

**Comment by VasilievSerg** [comment]
@mitchelsellers
> Given that it appears you have used your own commercial product to analyze our project and post the results, it would be helpful if you could provide a listing of the impacted code files, with full paths if possible. As although helpful, the snippets provided here are not an actionable resolution for the project aside from attempted "find" operations across the codebase.

Yes, of course, I can provide you full paths to files with the problems found.

I can also provide you with the PVS-Studio trial license (for 2 weeks, for example). This may make it easier to find and handle these and other warnings. Besides, I could have missed something important. I am not a DNN developer, after all. :)

I checked the project (solution) with a plugin for Visual Studio. To start the analysis, you just need a couple of clicks: Extensions -> PVS-Studio -> Check -> Solution.

Would this option make it easier to work with warnings?

**Comment by liffeyd** [comment]
@VasilievSerg 
DNN is an Open Source project and according to [https://pvs-studio.com/en/blog/posts/0600/](url) and [https://pvs-studio.com/en/order/open-source-license/](url) qualifies for a FREE licence so no need for "I can also provide you with the PVS-Studio trial license (for 2 weeks, for example)." Or, have I missed something?

**Comment by VasilievSerg** [comment]
@liffeyd  yes, sure.

The DNN developers can request the license this way.
I just suggested using a temporary license to work with the warnings I mentioned above.

Of course, regular use of the analyzer is better than one-time use. :)

**Comment by EPTamminga** [comment]
Interesting tool and results for DNN sourcecode. 

The "free" version for OS projects has a catch: you have to add 2 lines of comment in each source code file.
Ssee https://pvs-studio.com/en/blog/posts/0457/ .
```
// This is an open source non-commercial project. Dear PVS-Studio, please check it.
// PVS-Studio Static Code Analyzer for C, C++, C#, and Java: http://www.viva64.com
```
So in essence: each OS code file will have some kind of advertisement for PVS if you are going to continue to use the free OS version of PVS. I a not sure if this is wanted for DNN source.

The free trial will work for 2 weeks, it could be enough for handling the issues mentioned in the analysis from @VasilievSerg.

**Comment by VasilievSerg** [comment]
I’m sorry, this was a misunderstanding. PVS-Studio provides free license to non-commercial open source projects.

However, the options described by @liffeyd and @EPTamminga are a bit different: 

- The first option does not require comments in code. 
- The second option doesn’t require the project to be open source but requires adding comments.

I hope everything’s clear now. Once again, my apologies for such a misunderstanding. :(

Here’s the trial key for two weeks:
```
Name: DNNSoftware
Key: 5XNG-56XX-203H-0581
License type: Team
License Valid Thru: 9 Dec 2021
```

**Comment by EPTamminga** [comment]
@VasilievSerg Your reaction is in line what I wrote: 
* 2 weeks trial: no comment lines in the code, but only 2 weeks use: _could be enough for now_
OR
* Continuous use in OS: advertisement comment lines in the code: _I am not in favour of this_
