### ISSUE TITLE
RadEditor Still fallback editor for web.config

### ISSUE THREAD

**Issue by Timo-Breumelhof** [dnnsoftware/Dnn.Platform#4919]
## Description of bug
When you switch an updated installation to DNNConnect.CKE and uninstall the previous editor the value in web.config reverts to DotNetNuke.RadEditorProvider.
Even if you just removed Telerik in DNN 9.10
 
## Steps to reproduce
List the precise steps to reproduce the bug:
1. On an installation with another editor than DNNConnect.CKE set as the editor in web.config.
As an example the Watchers CKEditor: https://github.com/w8tcha/dnnckeditor
In that case web.config will contain this:  ` <htmlEditor defaultProvider="CKHtmlEditorProvider">`
2. Now switch the editor to the Core Ck Editor, by setting this in the web.config 
` <htmlEditor defaultProvider="DNNConnect.CKE">`
3. Now uninstall the Previous editor provider (the Watchers one)

## Current behavior
DNN reverts the defaultProvider to the RAD Editor which does not exist any more.

```
    <htmlEditor defaultProvider="DotNetNuke.RadEditorProvider">
      <providers>
        <clear />
        <add name="DNNConnect.CKE" type="DNNConnect.CKEditorProvider.CKHtmlEditorProvider, DNNConnect.CKEditorProvider" providerPath="~/Providers/HtmlEditorProviders/DNNConnect.CKE/" settingsControlPath="~/Providers/HtmlEditorProviders/DNNConnect.CKE/Module/EditorConfigManager.ascx" />
      </providers>
    </htmlEditor>
```

## Expected behavior
As DNNConnect.CKE exist leave that in place

## Additional context
Although this is not a very annoying issue IMO we should make sure we get rid of Rad everywhere, so I log this as a suggestion :-)

## Affected version

* [ ] 10.00.00 alpha build
* [x] 09.10.02 release candidate
* [x] 09.10.01 latest supported release

**Comment by mitchelsellers** [comment]
Just to make sure that I understand this correctly.

You set the default to be RadEditorProvider, then removed it, and it didn't change the default?

**Comment by Timo-Breumelhof** [comment]
@mitchelsellers hmm, I see now I copied the wrong web.config lines in there, I fixed that now.
Thanks for the head-sup.
In short, I had Ingo's provider, switched to the DNN connect one, uninstalled Ingo's provider and DNN reverted back to RAD which wasn't even installed any more.

**Comment by mitchelsellers** [comment]
Perfect I’ll go digging!

**Comment by mitchelsellers** [comment]
@Timo-Breumelhof I did some digging on this one, and I don't believe that this is a "bug" necessarily, or something that we can actually address on the platform side.

What happened is that as part of the un-install process the module included a configuration merge statement that needed to be completed, and DNN executed that statement.  

The DNNConnect.CKE editor has a similar item: https://github.com/dnnsoftware/Dnn.Platform/blob/37a767c6cf45f6c3813b225793e35875455f9989/DNN%20Platform/Providers/HtmlEditorProviders/DNNConnect.CKE/DNNConnect.CKEditorProvider.dnn

As you can see, once removed it will fallback to RadEditorProvider.

@dnnsoftware/approvers any thoughts on this?  Without lots of other stuff, and breaking changes I don't know that we can fix this?

**Comment by Timo-Breumelhof** [comment]
@mitchelsellers thanks for looking at this. :-)
I didn't realize that could be the issue, not really a DNN issue as you wrote.
I would not spend more time on it, I just logged this because I suspected that somewhere there might still be some default setting left in DNN.

**Comment by bdukes** [comment]
I think we should change the uninstall script for our version of the CKEditor provider, I don't think there's anything we can do about Ingo's provider.

**Comment by mitchelsellers** [comment]
What should we do on uninstall?  There is nothing to fall back to?

**Comment by bdukes** [comment]
I'd just remove the line to set the `defaultProvider` attribute. I think it's better than setting it to `RadProvider`

**Comment by sleupold** [comment]
IMO the provider should be marked as "system" to avoid it from being uninstall accidentally, if there is no fallback.

**Comment by valadas** [comment]
Yeah I agree, the one we provide should probably be system and have no fallback, for 3rd parties we can just hope they realize this and change their uninstall to match this...
