### ISSUE TITLE
SEO tab in Pages panel doesn't update correctly after deleting a URL

### ISSUE THREAD

**Issue by daguiler** [dnnsoftware/Dnn.Platform#4924]
## Description of bug
After deleting a page URL in the SEO tab, the view doesn't update correctly.
Navigating to another tab and then back to S.E.O. forces the view to update correctly.

## Steps to reproduce
1. Open PB > CONTENT > Pages
2. Click on **[EXPAND ALL]**
3. Click on **My Profile** page
4. Click on **Advanced** > **S.E.O.**. There is only one URL in the table: **/Activity-Feed/My-Profile Active (200) Automatic**.
5. Click on **+Add URL**
6. Type **test** in the URL Path field (rendered value will be **/test**)
7. Click on **Save**. The new URL is created (replacing the original URL) and 2 additional 301 automatic URLs are created.
8. Click on the delete icon next to the **/test** URL
9. Confirm the delete operation

## Current behavior
The **/test** URL is deleted but the 2 automatic URLs remain.

## Expected behavior
All 3 URLs should be gone and the original **Active (200) Automatic** URL should be reinstated.

## Screenshots
1) Before creating the /test URL
![image](https://user-images.githubusercontent.com/30123437/144163439-b3b73c47-2c7b-470f-9b15-0e3966759bda.png)

2) After creating the /test URL
![image](https://user-images.githubusercontent.com/30123437/144163470-a9c9724f-65ef-49de-8ba9-4239a8cd9732.png)

3) After deleting the /test URL (notice the other 2 URLs remain)
![image](https://user-images.githubusercontent.com/30123437/144163501-ea5fee2b-a7aa-4135-b3f9-884a565b019d.png)

4) After navigating to APPEARANCE and then back to S.E.O. (the view shows updated now)
![image](https://user-images.githubusercontent.com/30123437/144163582-6b84f9eb-2f34-4853-a76f-81a702b36e1e.png)

## Error information
N/A

## Additional context
N/A

## Affected version
* [X] 10.00.00 alpha build
* [X] 09.10.02 release candidate
* [X] 09.10.01 latest supported release

## Affected browser
* [X] Chrome
* [X] Firefox
* [X] Safari
* [X] Internet Explorer 11
* [X] Microsoft Edge (Classic)
* [X] Microsoft Edge Chromium

**Comment by thienvc** [comment]
I also had to manually delete the Seo Url via Sql
