### ISSUE TITLE
Adding a new page URL type is saved as FILE type 

### ISSUE THREAD

**Issue by Scippy** [dnnsoftware/Dnn.Platform#4935]
If you try to add a new page of type URL, it will be added of type FILE instead

## Steps to reproduce
Go to Pages and click on Add Page button
Select Page Type URL
Fill empty fileds URL and NAME
Click on Save button
Refresh the page and click on the page just created and you can see that it was saved as File and not as URL

## Current behavior
Page URL type is saved as FILE type

## Expected behavior
Page URL type must be saved as URL type

## Screenshots
Add new page type URL:
![Screenshot_1](https://user-images.githubusercontent.com/16607338/144702931-01f0ca47-38ac-4432-aeda-5cd6947969e6.jpg)

After saved you have type FILE:
![Screenshot_2](https://user-images.githubusercontent.com/16607338/144702939-d0789076-8905-4f2e-b8dc-92147ff07c32.jpg)
## Error information
Provide any error information (console errors, error logs, etc.) related to this bug.

## Additional context
Provide any additional context that may be helpful in understanding and/or resolving the bug.

## Affected version
* [ ] 09.10.02 release candidate
* [ ] 09.10.01 latest supported release

I've not tested on 10.00.00 alpha build

**Comment by mitchelsellers** [comment]
Looking at your posted screnshot a value of #test is not a valid page URL.

Do you experience the same behavior if you have a valid URL such as

https://www.google.com
or
/TestPage

It doesn't seem to be an issue in those circumstances for me.

**Comment by Scippy** [comment]
You're not correct, in the oldest DNN version it worked fine, it is a simple page anchor. In what other way you set page anchor if not in page type URL?
However I've tried also with simple url like www.test.it and it don't work with the same issue

**Comment by mitchelsellers** [comment]
Page anchor without any page in the menu isn’t something I would expect to work at all though. 

/mypage#something

would be more likely as a menu. 

Regardless we will review

**Comment by Scippy** [comment]
It is simple fired #anchor_name in the page where you're. It is typically used in onepage skin

**Comment by jeremy-farrance** [comment]
Scippy, I am really interested in this functionality and curious about your use-case. One thing people overlook is that in Dnn, the home page is special and is "tied to" the site root, so if you look in Pages Settings, Advanced, SEO, you'll probably see the URL is just "/". However, it does have a page name (whatever you put in Details, Name), usually Home or Welcome. 
 
If you go in the database you'll see that the TabPath is "//Home" - so mydomain.com/home#test
 
So to accomplish what you are trying to do - which is, in essence, to have (non-page) navigation links on a existing that appear in the menus - you do need to use the page name, so "home#anchor" will save as a URL type like you want. For all other pages you will just enter the (200) SEO URL like normal, only the home page needs this exception. 
 
Now you have a new problem (bug in Dnn), what is now stored in the field (dbo.Tabs.Url) has unfortunately got http(s) prepended, sp "https://home#anchor". Unexpected.
 
Possible solutions?
 
Code for this in your DDR Menus (Razor) using something like 
```
    node.Url.Replace("http:///", "/").Replace("https:///", "/")
```

But you'll need to be careful to detect and not modify valid URLs.
 
Or, if your site is rarely modified, manually modify the field in the Table (or use a SQL script). It will remain working until someone resaves the page, at which point Dnn will add back the unwanted prepend.

**Comment by Scippy** [comment]
Thanks Jaremy but the problem seems to be that DNN is not more able to recognize any type of URL as page type URL.
I've tried to modify in DB as you suggest but it is always retrieved as page type file and it just seems a DNN issue.

**Comment by mitchelsellers** [comment]
This one is for sure a very unique use-case.  I can see what @Scippy is trying to accomplish, however, at the same time this 100% violates all of the benefits of using a menu system, as every link added as # style links if stored would be useless on any other page, or any other theme configuration, including the login page or similar.

I will try to review the history with page management on this.

@Scippy do you happen to know the last version of DNN that this worked in?

**Comment by Scippy** [comment]
@mitchelsellers I've solved entering full url before anchor, for example for anchor name #test you must enter http://mytesturl.com/pagetes#test
It seems that it is recognized as url only if I enter http:// or https:// in first as suggested by @jeremy-farrance 
In oldest DNN versions if it was not entered in page settings it was added automatically by DNN, but you don't think that anything indicated in the url field for a page of type url should be treated as such?

**Comment by jeremy-farrance** [comment]
Am I correct that Dnn does not have a Type field for the dbo.Tabs (or related) record that defines whether it is a page or URL or file (type)? And that instead, the various pieces of code working with the Tab (TabInfo) and related are just figuring it out based on what was saved?

**Comment by Scippy** [comment]
Yes, you're correct.
