### ISSUE TITLE
Install Build Process needs to not longer include- `DotNetNuke.Telerik.Web` (DotNetNuke Telerik Web Components)- `DigitalAssetsManagement` (Digital Asset Management)- `DotNetNuke.Web.Deprecated` (DNN Deprecated Web Controls Library)- `DotNetNuke.Website.Deprecated` (DNN Deprecated Website Codebehind files)

### ISSUE THREAD

**Issue by david-poindexter** [dnnsoftware/Dnn.Platform#4943]

**Comment by bdukes** [comment]
Those are checking that Telerik isn't installed, they already support the scenario where Telerik isn't there.

**Comment by bdukes** [comment]
@dnnsoftware/approvers are we removing these packages altogether, or only for installs?

**Comment by david-poindexter** [comment]
@bdukes this task is for the install build process, for which we are removing these pages altogether.

Are you asking about the build process for the upgrade package?  If so, good question.  My vote would be to also not have these packages in the upgrade package.  For those upgrading and wishing to keep Telerik, then they would already have it and would need these to be reinstalled or upgraded (as nothing would change).  That said, I do see a scenario where this could be problematic for those upgrading from older versions of DNN to 9.11.0.  They could potentially not get these upgraded if something has changed within them between their existing version and 9.11.0.  So, perhaps this is worth a deeper conversation?

**Comment by bdukes** [comment]
Yeah, we should see when was the last time there was a meaningful change made to any of these packages, if our standard upgrade path would necessarily include that upgrade or not.

**Comment by bdukes** [comment]
Our [recommended upgrade path](https://docs.dnncommunity.org/content/getting-started/setup/upgrades/suggested-upgrade-path/index.html) would have us upgrading from 9.3.2 to 9.11.0.

9.2.1 includes [a change](https://github.com/dnnsoftware/Dnn.Platform/commit/5c96c8a130c6bfb3c3c715f5eb6f5a3747e1df3f) for Telerik, this is the last meaningful change I see for the DotNetNuke.Telerik.Web package.

9.8.0 includes [a change](https://github.com/dnnsoftware/Dnn.Platform/commit/f086bc324214c4be2a92d9c680d8aaed567d2dbd) to remove the improvement program beacon from the old Control Bar (DotNetNuke.Website.Deprecated).

9.8.0 includes [a change](https://github.com/dnnsoftware/Dnn.Platform/commit/d7c6afa0f783da3ef30c7747f8e3882b79a3d809) to mark the web controls as `Obsolete`/deprecated (DotNetNuke.Web.Deprecated)

9.8.1 includes [a change](https://github.com/dnnsoftware/Dnn.Platform/commit/37c119a94ffb77880e8765d22e07bc360f33ef31) for a move in the personalization API that touches the old Control Bar (DotNetNuke.Website.Deprecated).

Do we want to update the recommended upgrade path to include 9.10.2 before 9.11.0 and go ahead and completely remove all of these packages?

**Comment by david-poindexter** [comment]
Thanks so much for the research @bdukes - upon further thought, I am thinking we do not remove these from the `Upgrade` package.  If the user chooses to remove Telerik, this will be a moot point.  If they chose to NOT remove Telerik, then we can ensure they get the changes you have referenced.

The major point of 9.11.0 was to ensure a clean install was forced to be Telerik-free.  For upgrades, it should be optional so we do not introduce breaking changes.

**Comment by valadas** [comment]
I would be of the opinion that we remove that (from upgrade package) on 10.0 IMO

**Comment by bdukes** [comment]
@mitchelsellers I know you had talked about a desire to say that DNN was "vulnerability-free" and weren't distributing Telerik at all. Does only distributing it via the Upgrade package meet that expectation?

**Comment by mitchelsellers** [comment]
Yes I believe that meets the requirement as the upgrade is different.

**Comment by valadas** [comment]
Done in #5212
