### ISSUE TITLE
Password Reset Page Password Field Form Size Style Issue

### ISSUE THREAD

**Issue by thabaum** [dnnsoftware/Dnn.Platform#4952]
## Description of bug
Provide a clear and concise description of the bug.

## Steps to reproduce
List the precise steps to reproduce the bug:
1. Have a password reset link sent to your address from www.dnncommunity.org
2. Click on the link provided in the password reset email
## Current behavior
The first password field is smaller than the second and not big enough for longer passwords to show characters being typed

## Expected behavior
Both fields are big enough to type into and same size.

## Screenshots
<img width="898" alt="image" src="https://user-images.githubusercontent.com/13577556/145125301-439637a9-d4c3-47a6-bcdf-af1c8e4157d4.png">

## Additional context
Not sure the USERNAME field needs to be shown here.  It would be nicer if the form was centered in the page layout as well similar to login and registration.

## Affected version

* [ ] 10.00.00 alpha build
* [ ] 09.10.02 release candidate
* [ ] 09.10.01 latest supported release

## Affected browser

* [ ] Chrome
* [ ] Firefox
* [ ] Safari
* [ ] Internet Explorer 11
* [ ] Microsoft Edge (Classic)
* [ ] Microsoft Edge Chromium

**Comment by valadas** [comment]
This needs to be handled on the theme for that site, please post in the forums there. Thanks.
