### ISSUE TITLE
MVC ValidateAntiForgeryTokenAttribute does case sensitive checks.

### ISSUE THREAD

**Issue by dimarobert** [dnnsoftware/Dnn.Platform#4958]
## Description of bug
The logic that checks for the AntiForgery header/form keys does case sensitive checks, but as per [RFC 7230](https://datatracker.ietf.org/doc/html/rfc7230#section-3.2) and [RFC 7540](https://datatracker.ietf.org/doc/html/RFC7540#section-8.1.2) they are case-insensitive.

The issue reproduces (for me at least, in Edge Chromium 96 and Chrome) when the requests are done with http2. When that happens the headers are sent all lowercase. In http 1.1 looks like they are sent as set in JavaScript, so the issue does not reproduce.

## Steps to reproduce
1. Setup a http2 instance in IIS (needs https binding)
2. Create an MVC view that supports POST and has the ValidateAntiForgeryToken Attribute.
3. Make an XHR request to the MVC view URL (with $.ServicesFramework headers set)
4. 401 will be thrown.

## Current behavior
Request fails with 401.

## Expected behavior
Request should succeed.

## Screenshots
If applicable, provide screenshots to help explain the bug.

## Error information
Provide any error information (console errors, error logs, etc.) related to this bug.

## Additional context
Provide any additional context that may be helpful in understanding and/or resolving the bug.

## Affected version

* [ ] 10.00.00 alpha build
* [x] 09.10.02 release
* [x] 09.10.01 latest supported release

## Affected browser

* [x] Chrome
* [ ] Firefox
* [ ] Safari
* [ ] Internet Explorer 11
* [ ] Microsoft Edge (Classic)
* [x] Microsoft Edge Chromium

**Comment by dimarobert** [comment]
@bdukes @mitchelsellers I've found another discrepancy between the MVC attribute and the WebApi one. In the MVC one the `AntiForgery.Instance.Validate` is called only after checking for the `Thread.CurrentPrincipal.Identity.IsAuthenticated`, while in the WebApi one it is called either way.
I've looked through what `AntiForgery.Instance.Validate` does (even in the ASP.NET code with ILSpy) and it looks like there is logic for validation when no user is authenticated.

I wanted to ask here first before opening an Issue and a PR with a fix.
Do any of you know if the change for MVC was deliberate or in support for a certain scenario?

**Comment by bdukes** [comment]
I'm not aware of a reason, it seems like `IsAuthenticated` is unrelated to the anti-forgery token

**Comment by dimarobert** [comment]
@bdukes I know that there were some discussions about [AntiForgery and page caching](https://github.com/dnnsoftware/Dnn.Platform/issues/4005) that ended with the decision to not support it for unauthorized users.
The issue is that there is no way to enforce the attribute on an MVC action when a user is authenticated, but somehow skip/ignore it when the user is unauthenticated. Which in my opinion makes it unusable. 

In my case there is a form module, that needs to work on public pages as well, that needs to do a POST request to a MVC action to retrieve some additional HTML when a button is clicked. I could not use WebApi for it because I wanted to use the Razor engine to render that HTML. (something in between a partial view render and WebForms post-back request :smile:)
