### ISSUE TITLE
Journal:  Automatic formatting of hyperlinks functionality

### ISSUE THREAD

**Issue by thabaum** [dnnsoftware/Dnn.Platform#4961]
## Description of problem
web addresses typed into input fields like in the journal are not being created as links on forms you wish it could.

## Description of solution
I am all ears.  Update this when I have one if no one else can supply or I get a feeling any solution would get shot down due to complications or we just don't need this we can close this.

## Description of alternatives considered
Provide a clear and concise description of any alternative solutions considered.

## Screenshots
If applicable, provide screenshots to help explain the problem and/or enhancement.

## Additional context
Can we make this a reusable block available to any module that wants to include this module creator feature running DNN?  Maybe a turn on/off setting can be introduced?

Or is there already a way to perform this easily without having to re-invent the wheel here?  Maybe this is already in the DNN Library.  It would be nice to include a setting `AutomaticUrls="True/False"` into an input field on any form desired with this automatic formatting of hyperlinks functionality.  This could apply to mailto: email@domain.com website url starting with www. https//: and ftp:// along with others depending on which case is needed to create the proper url format located in the `href=""` element of an anchor.  Will be using regex to check words created after each space after a post is made.  Similar to what just happened here.

## Affected browser

* [ ] Chrome
* [ ] Firefox
* [ ] Safari
* [ ] Internet Explorer
* [ ] Edge

**Comment by in8dna** [comment]
This is an issue with YouTube links pasted into the Journal. The link to the UserProfile is applied to the pulled video title, but not a link to the YouTube video.
![image](https://user-images.githubusercontent.com/13932030/149605262-a7c5ed5d-014a-46e8-a9b3-f9fc1ecf41b8.png)
