### ISSUE TITLE
Updates to Default MachineKey Handling

### ISSUE THREAD

**Issue by mitchelsellers** [dnnsoftware/Dnn.Platform#4966]
## Description of problem
Now that DNN Platform requires .NET Framework 4.7.2 or later, new options exist for machineKey storage.  

DNN Defaults should be reviewed and updated to current best practices.

## Description of solution
Suggested upgrade to HMACSHA256 and AES from the current defaults.

## Description of alternatives considered
Leave the default as-is

## Additional context
This is something that needs to be tested and validated to not impact DNN Operations, and would be a change for ONLY new installations as changing of the MachineKey for existing installations is problematic.

**Comment by valadas** [comment]
Yeah, probably a good idea to be careful on upgrades, I know a lot of 3rd party modules rely on this value for licensing

**Comment by thabaum** [comment]
For upgraded versions could there can be a process to upgrade a site if desired manually?

**Comment by mitchelsellers** [comment]
At this point I don't believe.  Swapping machine key will break stuff
