### ISSUE TITLE
Journal: Journal item type templates enhancement with updates like an additional link and title.

### ISSUE THREAD

**Issue by thabaum** [dnnsoftware/Dnn.Platform#4967]
## Description of problem
For some journal items you need two links instead of just one to help a user get to the place where the item was created.  For example a "Group" related journal item with a "Link" journal type will be using the only allowed place for link Json formatted `ItemData` setting `Url:`.  If a link is created in a group using the new logic for an issue like #3035. 

## Description of solution
We need more `ItemData` settings we can pass such as `Url2` and `Title2` with as many as the community feels is desired.

The default URL will stay in place so no breaking changes, just allow second or third URL and Title and?  This will add new tokens to be used in the Journal templates resx files to create additional links for journal items.

## Description of alternatives considered
Add another column to the `Journal` database entry instead of adding to `ItemData`.

## Screenshots
If applicable, provide screenshots to help explain the problem and/or enhancement.

## Additional context
While I am working in this area what other tokens or template adjustments (like a link from the user photo to the user profile?) do you think we should make here.  The template files are in the `SharedResources` language file for the Journal Module to show some example code if desired.  These examples for resx journal template entries such as `journal_link.Text` as well those for the Blog, Forum, Group, Link and other posts get displayed from groups should be uniform with all other issues mentioned below fixed around the same time.

I would like to make the templates all look and flow the same along with adding any new functionality to the other modules as discussed in #3035.  I broke this down from that issue as it opens up a new discussion beyond just the scope of that issue it was brought up in.  I would like to see if there is any community feedback related to this area.  @Timo-Breumelhof and few others may be interested in some feedback here.  I also see his other two issues with the journal I feel I have had an issue within the past as well.  I want to get these Journal Module pet peeves of ours off the platform then focus on the platform itself. 

Other similar enhancement issue in the same area would be issue #4568 issue #4962.

[Location for the language files with the templates to be modified.](https://github.com/dnnsoftware/Dnn.Platform/blob/a2b6b513ee4b05d36ed777cc02a4efdf6b0e8906/DNN%20Platform/Modules/Journal/App_LocalResources/SharedResources.resx#L305)

## Affected browser

* [ ] Chrome
* [ ] Firefox
* [ ] Safari
* [ ] Internet Explorer
* [ ] Edge

**Comment by Timo-Breumelhof** [comment]
Why not a JSON field (so it's expandable by nature)?

**Comment by Timo-Breumelhof** [comment]
BTW, when you make changes in the area, please consider accessibility too :-)
See also https://github.com/dnnsoftware/Dnn.Platform/issues/4568

**Comment by thabaum** [comment]
@Timo-Breumelhof the journal database has an entry for JSON which is `ItemData` so expansion should be made here if we use more JSON.  I was laying out a few options.  The question is now if we like to use more JSON is naming the fields for the purpose such as `Url2:` and `Title2` or any suggestions here? 

`{"Cacheability":10,"Url":"http://www.adomainname.com","Title":null,"Description":"","ImageUrl":""}` 
as you can see below:
![image](https://user-images.githubusercontent.com/13577556/146620161-65654c37-8ff5-46cd-9905-2fc98f1c137f.png)

**Comment by thabaum** [comment]
> Why not a JSON field (so it's expandable by nature)?



> BTW, when you make changes in the area, please consider accessibility too :-) See also #4568

I have reviewed that issue.  Are you going to resolve it or would you like me to while I am working this area?  I have seen a few other things missing in the templates parsed by the journal so to speak.

**Comment by thabaum** [comment]
I will try to re-write the journal to follow these rules as shown in [Web Accessibility Tutorials](https://www.w3.org/WAI/tutorials/forms/) on the w3c website.  Unless directed otherwise this is what I will do to help with Journal accessibility and seo.
