### ISSUE TITLE
Journal: Add new type of journal entry for YouTube video links with "journal_youtubevideo" and "journal_groupyoutubevideo" template files.

### ISSUE THREAD

**Issue by thabaum** [dnnsoftware/Dnn.Platform#4968]
## Description of problem
Posts made with a video link do not show a way to play the video.

## Description of solution
If a link has to do with a video the journal will use a template that includes a way to view playing the video in a small window you can expand if you like.

Links are already detected, if they look for a little more information about the link the journal can then determine what journal item type it is.

The feature to allow or not allow this type would need to be enhanced along with the logic submit and view new journal item types.

Different cases:

- Journal link contains YouTube video information
- Could be extended to handle links that end with an extension to use an HTML5 player
- Depending on final solution the `Journal_Type - JournalType` created can be `youtubelink` or `videolink` and a `videofile` potentially to handle them independently.  
- File types with video extensions uploaded could also use a similar feature with `JournalType = videofile` and get a player in another template.

## Screenshots
If applicable, provide screenshots to help explain the problem and/or enhancement.

## Additional context
For now just simply adding YouTube links would be cool! I am working in this area for the next month I am guessing until I get a final PR together for some previous issues.  I may include this issue with the others if I can get to it, or it may come later if at all as a contribution from me.  I wont get in the way of someone else diving into this showing me how it is done 👍 My gut tells me if I can get this other issue a 100% workable community solution this should be a breeze...  

I am about 70% done with the other issues.   I have a hacked up version I need to finalize and make one more thing work as desired.  This issue is in the same realm while I am working here I might be able to slip this enhancement request in myself.
This can be done for any YouTube links but can also be done for other links that end with `.mpeg4` or other acceptable video extensions.  We may need another `Journal_Type` for this to display in a similar way using an HTML5 player.

Allow `JournalType = link` from database `Journal_Type` handle the logic switching on a `linkyoutube` template.  However a new `Journal_Type` `Video` and `YouTubeVideo` could be created giving the other settings that go with each.  Ability to enable/disable these types of link templates is something to consider and this is what would need done most likey for that to happen here.  I can see a couple possibilities.

When a journal has contact information such as a phone number, address or email a vCard and proper way to display an email most securely over the internet to avoid most spam.  PDF file links can be handled differently as well possibly.  I don't mind taking the journal to more options available for the "business class" rather than just a social module or activity feed.  Any feedback in respect to this would be nice.

## Affected browser

* [ ] Chrome
* [ ] Firefox
* [ ] Safari
* [ ] Internet Explorer
* [ ] Edge

**Comment by in8dna** [comment]
I'm supportive of the YouTube link function. Our experience is that links pasted from YouTube pull a thumbnail and the video title as expected, but the link applied to the video title is linked to the User Profile, not to the video. Has there been progress on this?

**Comment by thabaum** [comment]
> I'm supportive of the YouTube link function. Our experience is that links pasted from YouTube pull a thumbnail and the video title as expected, but the link applied to the video title is linked to the User Profile, not to the video. Has there been progress on this?

@in8dna [Issue #4960](https://github.com/dnnsoftware/Dnn.Platform/pull/4960) and [Issue #4956](https://github.com/dnnsoftware/Dnn.Platform/pull/4956)

These will resolve the issue with links not going to website urls entered.  I need to create the user interface in the persona bar for turning links on and off per DNN Instance by host only.  I may also add other ways for admins to turn it on and off as well if host has it on.  Maybe one site wants this feature off...  But per request top level host will be able to turn off this feature which then it will use the regular post template and not collect link data when it is set `off` I believe is the desired result.

An issue in the same area involving switching templates for group posts is issue #3035 which is going to be my next direction once I can put another day to it.  My plan is to also add an option to turn on/off automatic HTML formatting of links typed. #4961 

Limited time and I have to learn as I go but I am picking it apart and I believe I am heading in the right direction.  I wish I had more time to spare.  I should get faster at doing these types of requests in the near future.  I have yet to venture into the persona bar but it is my next task at hand to get the links working.  

Since I see there is support for YouTube template I will add it as an ItemType, detect `youtube.com/` in links and have them use a youtube template if enabled.  You know the drill ;)

_____________________________________________________________________

If Links enabled and `www.youtube.com/watch?v=` or `https://youtu.be/` is in the URL it will assign the `journal_youtubevideo` template which will display as an embedded video post in the journal.   A checkbox selection created in the journal module settings for displaying only YouTube video posts.

I will attempt this for the community.
