### ISSUE TITLE
Security Analyser triggers potentially unsafe action

### ISSUE THREAD

**Issue by JRPonte** [dnnsoftware/Dnn.Platform#4970]
Hi all,

I have a DNN installation on azure and when I access and use the Security Analyser tab I get an email from Microsoft Defender for Cloud <DefenderCloudnoreply@microsoft.com> describing a potentially unsafe action attempted on my SQL server.
The suspicious statement is this one:

DECLARE @Output TABLE(Data NVARCHAR(255))
INSERT INTO @Output EXEC master..xp_cmdshell 'net user'
SELECT @@ROWCOUNT

Azure SQL Server doesn't have access to the file system, and that's the reason, I suppose, that this security trigger is set off.

In the log file there are other errors that I believe are related with the same problem:

- Error executing SQL: DECLARE @Output TABLE(Data NVARCHAR(255), Depth INT)
INSERT INTO @Output EXEC sys.xp_dirtree 'D:\home\site\wwwroot'

- Error executing SQL: EXEC sys.xp_fileexist 'D:\home\site\wwwroot\web.config'

- Could not find stored procedure 'sys.xp_fileexist'

- Error executing SQL: DECLARE @OS VARCHAR(1000)
EXECUTE xp_regread 'HKEY_LOCAL_MACHINE', 'SOFTWARE\Microsoft\Windows NT\CurrentVersion', 'ProductName', @OS OUTPUT

- Parameter '@OS' specified but none of the passed arguments have a property with this name (in 'DECLARE @OS VARCHAR(1000)
EXECUTE xp_regread 'HKEY_LOCAL_MACHINE', 'SOFTWARE\Microsoft\Windows NT\CurrentVersion', 'ProductName', @OS OUTPUT
SELECT 1')

I'm using DNN 9.8.0, running in an app service on azure. Database is in an SQL Server on the same resource group.

Thank you.

**Comment by sleupold** [comment]
DNN Security Analyzer tries actions to check for security issues - these should fail in secure environments like Azure. I fear, this is by design.

**Comment by valadas** [comment]
Yes, it is by design, it needs to try stuff that may trigger some other warnings and errors in some places like the logs and this azure notification. closing this issue.
