### ISSUE TITLE
CkEditor Link Popup crashes in French

### ISSUE THREAD

**Issue by Timo-Breumelhof** [dnnsoftware/Dnn.Platform#4971]
## Description of bug
With a French locale, clicking the link icon in the toolbar 
![image](https://user-images.githubusercontent.com/8999382/146931072-b0192c78-6fd1-43c3-a4cc-c4e51d5e85b6.png)
 does not work as expected. The screen gets a white overlay and there's an error in the console regarding DNN Pages.
This is not the case in the other languages I tested:

en, nl & it

## Steps to reproduce
List the precise steps to reproduce the bug:
1. Make sure you are on a "French" page.
2. Place the HTML editor, 
3. Select a text and Click the Link icon
4. See error :-)

## Current behavior
No link popup

## Expected behavior
The link popup should work..

## Error information
Uncaught TypeError: editor.lang.dnnpages is undefined
   

## Affected version

* [ ] 10.00.00 alpha build
* [x] 09.10.02 release candidate
* [x] 09.10.01 latest supported release

**Comment by Timo-Breumelhof** [comment]
ok already logged and fixed.. 
https://github.com/dnnsoftware/Dnn.Platform/issues/4801
While logging this I was surprised @valadas did not noticed this, but is looks like he did :-)
Must be something with the upgrade that I see this @ the clients site.

**Comment by valadas** [comment]
Yeah, it was fixed in 9.10.2

**Comment by Timo-Breumelhof** [comment]
Right, I think I missed that because the issue was closed on aug 30 :-)

**Comment by Timo-Breumelhof** [comment]
I just compared the two zips :-)
