### ISSUE TITLE
Resource Manager injects CSS inline in Head

### ISSUE THREAD

**Issue by Timo-Breumelhof** [dnnsoftware/Dnn.Platform#4974]
## Description of problem
We have been looking at improving the resource manager.
Currently the Module uses Module.css for a few lines of CSS and the rest of the CSS is rendered in a <style> tag in the head of the page. As the is a DNN Module, IMO styling should be in Module.css and thus the Less should just be parsed to Module.css
That way all CSS is in one place and it allows users to not load Module.css as an option and in general it will make adding your own styling more easy.
This would also make improving the Styling of the Module (for a PR) easier.

This is related to #4612 and #4390

## Description of solution
A. Move the content of [the current ](https://github.com/dnnsoftware/Dnn.Platform/blob/develop/DNN%20Platform/Modules/ResourceManager/module.css) to https://github.com/dnnsoftware/Dnn.Platform/blob/develop/DNN%20Platform/Modules/ResourceManager/ResourceManager.Web/app/less/styles.less
B. Parse the Less above to Module.css

**Comment by jeremy-farrance** [comment]
Its separation of concerns. The backend module vs. the front-end (the part that runs in the PB). I understand your desire to move the modules's CSS in to one place, but given the full context I am not sure it makes sense or would be worth the effort.

**Comment by Timo-Breumelhof** [comment]
> The backend module vs. the front-end (the part that runs in the PB). 

@jeremy-farrance is there a part of th emodule running in the PB? AFAIK, the PB shows a DNN page for Assets (?)

**Comment by Timo-Breumelhof** [comment]
@david-poindexter  OK, good to know :-) I'll focus on something else then..
