### ISSUE TITLE
Purge expired AuthCookies

### ISSUE THREAD

**Issue by donker** [dnnsoftware/Dnn.Platform#4982]
## Description of problem

It appears AuthCookies stay in the database forever, leading some users to see millions of records.

## Description of solution

There is a [DeleteExpiredCookies on AuthCookieController](https://github.com/dnnsoftware/Dnn.Platform/blob/develop/DNN%20Platform/Library/Security/Cookies/AuthCookieController.cs#L58) but that doesn't appear to be used anywhere. It seems obvious we should call it from a scheduled task or similar.

**Comment by WillStrohl** [comment]
Do we need a note to remind us to put an FYI in the release notes for people with larger numbers of expired cookies to delete?  The upgrade could potentially have an initially poor performance impact, and cause some perception issues on DNN.  Maybe even a query to help people determine how to clean things up ahead of time?

**Comment by donker** [comment]
In light of the potential of having many undeleted cookies, the SPROC was changed so it would only delete 10K at a time. This should prevent any such issues. Having said that, it could be useful for people to know that this table can have grown out of proportions and that it's a good idea to manually purge records once.

**Comment by mitchelsellers** [comment]
Will I agree. Let’s try to call this out. As even with a 10k limit if the table is large, in excess of say 40-50k or more it will have performance impacts.

**Comment by sleupold** [comment]
there shouldn't be a perf issue, unless there are millions of records in this table

**Comment by donker** [comment]
> there shouldn't be a perf issue, unless there are millions of records in this table

We know for a fact that some have millions of records

**Comment by sleupold** [comment]
in this case it would be useful to clear all records via "TRUNCATE TABLE" prior to the upgrade

**Comment by WillStrohl** [comment]
If it's a truncate command, then it's even more reason to call it out via the release notes, but that's far too destructive to do automatically, in my opinion.  It could be one of the options described in the release notes, though.  That's only my $0.02.  :)

**Comment by donker** [comment]
You're probably not going to get a lot of backing for having a TRUNCATE statement in an upgrade script. I agree with Will that it's better to call it out in release notes.

**Comment by donker** [comment]
Implemented with PR #5001
