### ISSUE TITLE
Deleted or inactive Tab is not being removed from search index

### ISSUE THREAD

**Issue by ufoloko** [dnnsoftware/Dnn.Platform#4983]
I have a site in a webfarm (2 servers) with shared folder for both servers. I changed some pages to inactive and run manually SearchEngineScheduler task, but pages still are appearing in search results. I  don't want to delete search index files manually yet, because i would like to understand why this scenario is not working in a web farm.

Anybody have any idea about ?

**Comment by mitchelsellers** [comment]
Do you have Caching setup with the SimpleWebFarmCachingProvider?

Do you have any search index errors?  Shared server situations can cause problems with the Indexer unable to update the search index due to locking

**Comment by ufoloko** [comment]
Hi Michael, yes, I have set the webfarmcachingprovider

I tested in a local environment with one server and the problem remains

I just noticed that the only way to delete page from search index is delete page from site including from recycle bin, just in that way  is solved the search issue 

I thing Search module have an issue that needs to be revised

For now problem is solved but indexing have a glitch

Thanks

**Comment by mitchelsellers** [comment]
Ok that was going to be my next question, I believe it is a known behavior that deleted pages are still indexed

**Comment by ufoloko** [comment]
Ok, I just noticed i was testing in an old version of DNN (9.8.2), i cloned and updated to last version 9.10.2 and in that version search is working as expected. is just needed to disable a page to remove from search results. anyway scenarios tested into a new page are:

1.- "allow indexing" disabled, page is not being considered for search indexing task, so still appearing in search results

2.- "allow indexing" enabled and "disable page" enabled, page is being considered in search indexing task but is still appearing in search results for admin and visitors

3.- same scenario as 2, but i removed all users permissions, page is being considered in search indexing task and is appearing in search results just form admin, not for visitors.

4.- same scenario as 2 but deleting page (recycle bin), page is being considered in search indexing task but is still appearing in search results for admin and visitors

5.- page deleted from recycle bin. page is not being considered in search indexing and is not appearing in search results anymore for admin and visitors.

Thanks anyway
