### ISSUE TITLE
htmlCompatibility="html5" doesn't remove type when using the LazyLoadRenderer

### ISSUE THREAD

**Issue by andersbrohall** [dnnsoftware/Dnn.Platform#4990]
When using 1.9.10, with htmlCompatibility set to "html5" the output in the view still contains type="text/javascript" in the script tags rendered as a compliment to /WebResource.axd. 

Example: 

StandardRenderer:
`<script src="/Scripts/blocking.js?cdv=123" ></script>`

LazyLoadRenderer:
`<script src="/WebResource.axd?d=zwknGD9um8nJ5iro3fpcG6bP2uF2y04XGbo_kIftxgePzGwzeshejCqMB8cS1HzSGnFy8XC_FwwsdTjCXr93L7CZirYmQHdnVXsyZQaaAgvbNxmmOF0IktRA-cyRKfds_yH9ij26fEtQug7rP96QCdpLt8-YwLyrldbrOM2vkTY1&t=637570492660000000" ></script><script type="text/javascript">CDLazyLoader.AddJs('/Scripts/lazy.js?cdv=123');</script>`

**Comment by bdukes** [comment]
We're going to need some more details to understand what this issue is. Where are you setting `htmlCompatibility` to `html5`? Can you give an example with some context? What issue are you seeing when `type="text/javascript"` is rendered?

**Comment by andersbrohall** [comment]
The htmlCompatibility-switch is in the clientDependency element in web.config (or /config/ClientDependency.config to be precise since we're using Umbraco 8.13.0)
_<clientDependency htmlCompatibility="html5" version="123" fileDependencyExtensions=".js,.css" loggerType="Umbraco.Web.CdfLogger, Umbraco.Web">_

The issue is that type is rendered in the script tag, when using the LazyLoadRenderer. Which it shouldn't be. 

Works: 
`Html.RequiresJs(new JavascriptFile("~/Scripts/blocking.js") {ForceProvider = "StandardRenderer"});`
`@Html.Raw(Html.RenderJsHere("StandardRenderer"))`

Not working: 
`Html.RequiresJs(new JavascriptFile("~/Scripts/lazy.js") {ForceProvider = "LazyLoadRenderer"});`
`@Html.Raw(Html.RenderJsHere("LazyLoadRenderer"))
`

**Comment by bdukes** [comment]
If you're using Umbraco, then you probably don't want this issue to be in DNN Platform. Do you want to move it to the [Umbraco repository](https://github.com/umbraco/Umbraco-CMS) or maybe the [ClientDependency repository](https://github.com/Shazwazza/ClientDependency)?

**Comment by andersbrohall** [comment]
Haha, just realized i reported it in the wrong repo. You had an issue with the htmlCompatibility referring to https://github.com/Shazwazza/ClientDependency/. I got mixed up.

Sorry about that :D
