### ISSUE TITLE
Edit bar not loading on some pages

### ISSUE THREAD

**Issue by Timo-Breumelhof** [dnnsoftware/Dnn.Platform#4995]
## Description of bug
On some DNN 09.10.02 installations we found an issue; 
the Edit bar at the bottom does not load when you click the Edit pen in the Persona Bar. 
We have been unable to reproduce this on a clean installation, but we did find something that fixed it on the affected installations. 
I know this is an impossible issue to fix without being able to reproduce it, but I hope this will help others that have this issue.
Or maybe someone will find the missing part of what's causing this as I suspect it to be a combination of two things.

## Steps to reproduce
As stated before I was unable to reproduce this on a clean install, but on the affected installations a 404 for an Image, so just an image on that page that could not be found made the Edit bar not pop out.
Fixing the non extant src of the IMG tag made the Edit bar appear again.
But I'm convinced there's another factor at play.

BTW, when you fix the Edit bar (click the edit pen twice) on another page and visit the affected page, the Edit bar does show up.

## Current behavior
Edit bar does not show up

## Expected behavior
Edit bar does show up

## Error information
The difference between a page with an without this issue is that the page with the issue shows a 302 to the current page after clicking the edit pen. I did not find out why. This is probably why double-clicking the edit pen does make the Edit bar show up.
We did test moving the module to another page and it caused the same issue on that page so it's not likely an issue with the page.
There were no errors in the JS Console in the Browser

## Additional context
We had this on two installations, one where an open content module had an 404 image and one where this was inside an HTML module. Removing the 404 causing IMG tag solved the issue.

## Affected version
 [x] 09.10.02

**Comment by valadas** [comment]
I have no clue how this is even possible but I can confirm I had that issues on a CSS background image property on one site, I was kind of flabbergasted and did not report the issue as I thought it was a fluke., but funny to see someone else experiencing this issue..

**Comment by Timo-Breumelhof** [comment]
I have no clue either, and at first decide not to log it, but when we experienced it on two sites at the same time...
But I wonder if we ever find the real cause of this..
