### ISSUE TITLE
Cake build tools no longer work for VS 2022

### ISSUE THREAD

**Issue by donker** [dnnsoftware/Dnn.Platform#4996]
## Description of bug
When using VS 2022 the current Cake version (1.2.0) can't build the solution.

## Steps to reproduce
1. Install VS 2022
2. UnInstall previous versions of VS
3. Run .\build.ps1 --target=resetdevsite
4. See errors

## Current behavior
Cake 1.2.0 supports up to version 2019 of VS

## Expected behavior
That it builds without errors

## Error information
You'll see every project build fail with an error that is not relevant (namespace of build XML is incorrect)

## Additional context
You'll find that updating Cake to 2.0.0 for VS 2022 support necessitates a cascade of changes. First, the build project will need to change to a .net core 3.1 at the very least. Framework 4.8 is not supported. This is a trivial change. But then we have a dependency on Cake.Frosting.Issues.Recipe which will not currently work with Cake 2.0.0. This is a bigger problem.

## Affected version
* [x] 10.00.00 alpha build
* [x] 09.10.02 release candidate
* [x] 09.10.01 latest supported release

**Comment by valadas** [comment]
Cake version was bumped and I have no issues building in VS2022, assuming this is resolved here...
