### ISSUE TITLE
CurrentCulture/CurrentUICulture are not set when rendering a partial MVC view.

### ISSUE THREAD

**Issue by dimarobert** [dnnsoftware/Dnn.Platform#5003]
## Description of bug
When a MVC view is called using it's endpoint (e.g. `/DesktopModules/MVC/<ModuleFolder>/<Controller>/<Action>`) the `Localization.SetThreadCultures` method is never called to set CurrentCulture and CurrentUICulture properly.

It is however set in all other situations (MVC module rendering through Default.aspx, WebAPI).

I found two ways to fix this:
1. Add an ActionFilter in the GlobalFilters that sets up localization ([link](https://stackoverflow.com/a/11726897))
2. Use the existing DnnMvcHandler to setup localization.

Please let me know how do we want to do this and I will create a Pull Request.

## Steps to reproduce
List the precise steps to reproduce the bug:
1. Create a MVC view and register it.
2. Call it with the URL scheme `/DesktopModules/MVC/<ModuleFolder>/<Controller>/<Action>`.
3. The `CultureInfo.CurrentCulture` will always be `en-US` and the `CultureInfo.CurrentUICulture` will be `en` (no region).

## Affected version
* [ ] 10.00.00 alpha build
* [x] 09.10.02 release candidate
* [x] 09.10.01 latest supported release

## Affected browser
* [ ] Chrome
* [ ] Firefox
* [ ] Safari
* [ ] Internet Explorer 11
* [ ] Microsoft Edge (Classic)
* [ ] Microsoft Edge Chromium

**Comment by bdukes** [comment]
I'm open to either approach. Updating `DnnMvcHandler` sounds like the simpler solution to me, without looking into it more deeply. Thanks!
