### ISSUE TITLE
PersonaBar Error (reducers.ts)

### ISSUE THREAD

**Issue by skarpik** [dnnsoftware/Dnn.Platform#5039]
## Description of bug
Opening the Servers control panel causes an error to appear in the JavaScript console. The error is in the code reducers.ts. No error shows up in the Admin Log.

## Steps to reproduce
List the precise steps to reproduce the bug:

1) "Inspect" a page and select the Console tab.
2) Click on the Servers in the admin settings.
3) JavaScript error appear in the Console window.

## Current behavior
Explain the current behavior.

Clicking on "Servers" causes the errors to be logged in the JavaScript console.

## Expected behavior

The error either should not occur or it should be caught.

## Screenshots
If applicable, provide screenshots to help explain the bug.

Opening the "Servers" control panel generates these errors:

![Screenshot 2022-03-08 012230](https://user-images.githubusercontent.com/3846223/157179130-f30cab7c-d997-439f-8102-4f4ce49ab077.jpg)

Pressing "Restart" generates more errors.

![Screenshot 2022-03-08 012640](https://user-images.githubusercontent.com/3846223/157179529-bfe0740a-286b-4b87-95e0-19cd1078a005.jpg)

## Error information
Provide any error information (console errors, error logs, etc.) related to this bug.

reducers.ts:107 
        
    Uncaught TypeError: c is not a function
    at u (reducers.ts:107:2)
    at v (reducers.ts:107:2)
    at exports.unstable_runWithPriority (reducers.ts:107:2)
    at cg (reducers.ts:107:2)
    at Jj (reducers.ts:107:2)
    at yj (reducers.ts:107:2)
    at Ig (reducers.ts:107:2)
    at bk (reducers.ts:107:2)
    at reducers.ts:107:2
    at Nj (reducers.ts:107:2)

## Additional context

Edge, Chrome and Firefox all report the same error with Firefox providing more detail.

## Affected version

* [ ] 10.00.00 alpha build
* [X] 09.10.02 release candidate
* [ ] 09.10.01 latest supported release

## Affected browser

* [X] Chrome
* [X] Firefox
* [ ] Safari
* [ ] Internet Explorer 11
* [ ] Microsoft Edge (Classic)
* [X] Microsoft Edge Chromium

**Comment by joeinIL0405** [comment]
confirmed/duplicated on 9.10.02 / chrome

**Comment by valadas** [comment]
Fixed in #5490 so should no longer be a problem with the upcoming v9.11.1
