### ISSUE TITLE
support async attribute 

### ISSUE THREAD

**Issue by anajgroup** [dnnsoftware/Dnn.Platform#5041]
hi. im using dnn for web designing about 12 year, but there is problem with gtmetrix. 

its better to adding async and defer to dnn dependency handlers and etc.

this is very big problem for developers and designers! all websites with dnn platform have grade E or F on gt metrix

**Comment by jeremy-farrance** [comment]
There are a number of ways to link to scripts and styles. Dnn does support getting the async and defer attributes in place. It is probably most commonly done from your theme/skin.

**Dnn Docs, Client Resources**
[https://docs.dnncommunity.org/content/tutorials/client-resources/index.html](https://docs.dnncommunity.org/content/tutorials/client-resources/index.html)

In particular you need to use the HtmlAttributesAsString to get those set.
 
This recent Blog also shows another way to add a CDN asset to the page in code that sets async and defer.
[https://dnncommunity.org/blogs/Post/12141/DNN-Details-004-Using-the-New-Dnn-Elements-in-a-2sxc-View](https://dnncommunity.org/blogs/Post/12141/DNN-Details-004-Using-the-New-Dnn-Elements-in-a-2sxc-View)

**Comment by anajgroup** [comment]
hello jeremy. 
thanks for reply bur i mean a css and js links that related to a dnn not about module or skins!

there is 3 files that need to have async attribute and no way to change them for end users!

for example:
```
/DependencyHandler.axd
/ScriptResource.axd
/WebResource.axd
```
these file depends on the dnn source and i cant find any way to solve the problem!

**Comment by anajgroup** [comment]
> There are a number of ways to link to scripts and styles. Dnn does support getting the async and defer attributes in place. It is probably most commonly done from your theme/skin.
> 
> **Dnn Docs, Client Resources** https://docs.dnncommunity.org/content/tutorials/client-resources/index.html
> 
> In particular you need to use the HtmlAttributesAsString to get those set.
> 
> This recent Blog also shows another way to add a CDN asset to the page in code that sets async and defer. https://dnncommunity.org/blogs/Post/12141/DNN-Details-004-Using-the-New-Dnn-Elements-in-a-2sxc-View
> 
> So depending on your skills and needs, for each asset that is missing one of those attributes, you will need to see if you can modify the theme or module so that you get what you need. I don't think Dnn (or any CMS) would be able to determine whether or not to set those things automatically and its up to the designer and/or developer to get them set as needed.

hello jeremy. 
thanks for reply bur i mean a css and js links that related to a dnn not about module or skins!

there is 3 files that need to have async attribute and no way to change them for end users!

for example:
```
/DependencyHandler.axd
/ScriptResource.axd
/WebResource.axd
```
these file depends on the dnn source and i cant find any way to solve the problem!

**Comment by anajgroup** [comment]
> @anajgroup it would break those scripts to add `async` and/or `defer` to them. Those attributes require the script to be able to run in any order, but DNN's scripts (not to mention those of 3rd party extensions) are written in a way that requires them to run in a particular order.

Ok. But whats the solution for this problem?
This is no small problem!
The ranking of DNN sites in GT Metrics is very low.
A DNN site with a default or even empty format in GT Metrics can not get a even D ranking!

**Comment by jeremy-farrance** [comment]
I understand what you are claiming, but you are not separating your concerns or providing any details we can test or constructively respond to with a solution.  Dnn is a very large codebase with a LOT of moving parts. Many of the things that result in a poor scores have a lot to do with the theme (skin) as well as how the page/content is constructed and how the assets get on the page. If you are talking about a site using the old (still default) Xcillion theme or one of the many older template out there, yes, you are going to get **bad** results with modern testing tools.
 
However, if you build your theme well, understand the Dnn page-lifecycle, how to get control over what is emitted, and what the Dnn settings do (especially Client Resource Management) - you can easily address things one by one. We (my company) are an agency and use our own customized Bootstrap-based theme as a starting point for our custom designed sites built on Dnn. We have NEVER spent any time optimizing it again speed tests other than occasionally playing with the Lightwave thing built in to Chrome. Without any settings changes I just did a test an a page from one of our recently deployed projects on Dnn 9.10.x and as you can see, the results are not embarrassing.
 
![image](https://user-images.githubusercontent.com/653301/157994824-381a52ac-eabb-4cd3-b3ac-d4b8e86bb1ea.png)

Again, this is our own custom theme base kit, built with a lot of TLC over the last 3+ years. There is a lot to learn to do things well or right. But I think you will find there is a great community of people here willing to help. So I can tell you from experience, Dnn is perfectly capable of outputting a well-crafted page end to end that will test well if needed.
 
I recommend you narrow your question down to one small thing that you can identify and be specific about with an example. Pick something that is getting output in the theme you are are working on, show your code or page source fragment, and also share what you would like Dnn to emit instead - the better result that you want. I am pretty sure there will be a good solution. Sometimes it will be settings, sometimes it will be code changes or different ways to build your theme or page.

**Comment by jeremy-farrance** [comment]
I understand what you are claiming, but you are not separating your concerns or providing any details we can test or constructively respond to with a solution. Dnn is a very large codebase with a LOT of moving parts. Many of the things that result in a poor scores have a lot to do with the theme (skin) as well as how the page/content is constructed and how the assets get on the page. If you are talking about a site using the old (still default) Xcillion theme or one of the many older templates out there, yes, you are going to get bad results with modern testing tools.

However, if you build your theme well, understand the Dnn page-lifecycle, how to get control over what is emitted, and what the Dnn settings do (especially Client Resource Management) - you can easily address things one by one. We (my company) are an agency and use our own customized Bootstrap-based theme as a starting point for our custom designed sites built on Dnn. We have NEVER spent any time optimizing it again speed tests other than occasionally playing with the Lightwave thing built in to Chrome. Without any settings changes I just did a test an a page from one of our recently deployed projects on Dnn 9.10.x and as you can see, the results are not embarrassing.

![image](https://user-images.githubusercontent.com/653301/157997145-094c23f6-635d-4b43-82c7-cce40669a840.png)

Again, this is our own custom theme base kit, built with a lot of TLC over the last 3+ years. There is a lot to learn to do things well or right. But I think you will find there is a great community of people here willing to help. So I can tell you from experience, Dnn is perfectly capable of outputting a well-crafted page end to end that will test well if needed.

I recommend you narrow your question down to one small thing that you can identify and be specific about with an example. Pick something that is getting output in the theme you are are working on, show your code or page source fragment, and also share what you would like Dnn to emit instead - the better result that you want. I am pretty sure there will be a good solution. Sometimes it will be settings, sometimes it will be code changes or different ways to build your theme or page.

**Comment by david-poindexter** [comment]
As @jeremy-farrance mentioned, it is quite possible to achieve very high scores with a properly developed theme for DNN.

**Comment by EPTamminga** [comment]
Why don't we include 2 or 3 new theme packs that perform better than XCillion? XCillion is several years old. 
I have seen excellent examples with nvQuickTheme, people here using Tailwind. and other frameworks. 
Surely creating and including 2 or 3 new themes should not be that difficult?
First look of a newbie on DNN  should impress. A theme forms a large portion of that first look.

**Comment by anajgroup** [comment]
> There are a number of ways to link to scripts and styles. Dnn does support getting the async and defer attributes in place. It is probably most commonly done from your theme/skin.
> 
> **Dnn Docs, Client Resources** https://docs.dnncommunity.org/content/tutorials/client-resources/index.html
> 
> In particular you need to use the HtmlAttributesAsString to get those set.
> 
> This recent Blog also shows another way to add a CDN asset to the page in code that sets async and defer. https://dnncommunity.org/blogs/Post/12141/DNN-Details-004-Using-the-New-Dnn-Elements-in-a-2sxc-View
> 
> So depending on your skills and needs, for each asset that is missing one of those attributes, you will need to see if you can modify the theme or module so that you get what you need. I don't think Dnn (or any CMS) would be able to determine whether or not to set those things automatically and its up to the designer and/or developer to get them set as needed.

<dnn:DnnCssExclude runat="server" Name="dnndefault" />

i have seen this but i dont know how to exclude another css files from dnn?

**Comment by anajgroup** [comment]
> I understand what you are claiming, but you are not separating your concerns or providing any details we can test or constructively respond to with a solution. Dnn is a very large codebase with a LOT of moving parts. Many of the things that result in a poor scores have a lot to do with the theme (skin) as well as how the page/content is constructed and how the assets get on the page. If you are talking about a site using the old (still default) Xcillion theme or one of the many older templates out there, yes, you are going to get bad results with modern testing tools.
> 
> However, if you build your theme well, understand the Dnn page-lifecycle, how to get control over what is emitted, and what the Dnn settings do (especially Client Resource Management) - you can easily address things one by one. We (my company) are an agency and use our own customized Bootstrap-based theme as a starting point for our custom designed sites built on Dnn. We have NEVER spent any time optimizing it again speed tests other than occasionally playing with the Lightwave thing built in to Chrome. Without any settings changes I just did a test an a page from one of our recently deployed projects on Dnn 9.10.x and as you can see, the results are not embarrassing.
> 
> ![image](https://user-images.githubusercontent.com/653301/157997145-094c23f6-635d-4b43-82c7-cce40669a840.png)
> 
> Again, this is our own custom theme base kit, built with a lot of TLC over the last 3+ years. There is a lot to learn to do things well or right. But I think you will find there is a great community of people here willing to help. So I can tell you from experience, Dnn is perfectly capable of outputting a well-crafted page end to end that will test well if needed.
> 
> I recommend you narrow your question down to one small thing that you can identify and be specific about with an example. Pick something that is getting output in the theme you are are working on, show your code or page source fragment, and also share what you would like Dnn to emit instead - the better result that you want. I am pretty sure there will be a good solution. Sometimes it will be settings, sometimes it will be code changes or different ways to build your theme or page.

It would be better to take a look at the link as well, maybe we can take a pattern from the template

**Comment by bdukes** [comment]
> `<dnn:DnnCssExclude runat="server" Name="dnndefault" />`
> 
> i have seen this but i dont know how to exclude another css files from dnn?

The `DnnCssInclude` and `DnnJsInclude` controls can have a `Name` property set, and that's what will be used by the corresponding `Exclude` control. If a resource is included without a name, I don't believe there is a way to exclude it.

**Comment by mitchelsellers** [comment]
> Why don't we include 2 or 3 new theme packs that perform better than XCillion

I think it would be great to have more themes available that are downloadable outside of the installation package.  However, the items included in the base installation should be limited in my opinion, as anything distributed with the platform comes with a support expectation.

**Comment by anajgroup** [comment]
> 

but at the dnn docs website default.css named "dnndefault" i think there is a name to other css files for example: skin.css, portal.css, module.css or searchskinobject and etc...

but there is nothing in the dnn docs!

**Comment by EPTamminga** [comment]
@mitchelsellers I understand that. 
So the one that we include in the distribution should be a 99% example of how things can work at best. Xcillion is not that (anymore).

**Comment by valadas** [comment]
Closing this as async is supported, just not used in the default theme (which is a task bigger than this issue)
