### ISSUE TITLE
DNN Platform\Website\admin\Skins\Privacy.ascx.cs & Terms.ascx.cs 

### ISSUE THREAD

**Issue by Andy9999** [dnnsoftware/Dnn.Platform#5047]
By default the links to privacy and terms pages are getting a rel="nofollow" added from the CS code. There are mixed opinions on having it set to nofollow (pro and contra). Some say having it set to nofollow could look kind of shady to Google.

To change this, one currently has to recompile DNN and use a custom build.

To improve this I would suggest to remove it from the CS code and put the rel="nofollow" into the ascx files instead, where one could customize the behavior without recompiling.

I could submit this change and would be glad not having to make custom builds anymore.

Best regards & happy DNNing
Andy9999

**Comment by bdukes** [comment]
Yes, this would be a welcome change. We would want the skin object to still default to `rel=nofollow` if there's nothing specified, but allow overriding that.

**Comment by Andy9999** [comment]
Thank you for the feedback! I will work on this issue (and the other 3 ones) on the side line so it may take a while.

Best regards & happy DNNing
Andy9999
