### ISSUE TITLE
HTML Lang Attribute

### ISSUE THREAD

**Issue by Andy9999** [dnnsoftware/Dnn.Platform#5048]
By default the <html> tag is rendered having the lang attribute set to language and location for example "en-us" for US English.

We don't want to differentiate between en-us and en-en for example, or de-de and de-au so we cut the location off leaving the two letters of the language code in the rendered <html lang="en"> tag. We are not big enough of a site to have individual pages for each location and language is enough. 

I could submit this as a change if there is any interest in this and would be glad not having to make a custom build anymore.

What are your thoughts?  Should this somehow be enabled/disabled? What would be the best way? Maybe the HostSetting or PortalSetting table? Would that be a good place to add a new setting? For example LanguageCodeWithoutLocation Y/N with the default being 'N'.

Here is some more info about the lang attribute: https://www.w3schools.com/tags/att_lang.asp

Best regards & happy DNNing
Andy9999

**Comment by bdukes** [comment]
I'd think a portal setting, maybe something like `ExcludeRegionFromLanguageAttribute`

**Comment by Andy9999** [comment]
That is a great name for the setting! Thank you.
