### ISSUE TITLE
Localization of DNN Search Categories

### ISSUE THREAD

**Issue by Andy9999** [dnnsoftware/Dnn.Platform#5049]
I think I have found a strange bug (tested up to 9.10.2) preventing you from translating the DNN search categories.

I have not yet analyzed the problem in depth but it seems to be a caching issue where DNN caches the current languages category name and then has problems retrieving the setting.

We have a multi-lingual site and I tried to translate the names. For example the category "Pages" should show up translated into German, so I created a DesktopModules\Admin\SearchResults\App_LocalResources\SearchableModules.de-DE.resx with the corresponding translation.

Next I had to add the new category in the module settings of the German instance of the search module. So it seems each instance stores this list of categories using the translated name.

After making this change you will see that a search for that newly translated category will not produce search results anymore.

I think I saw a hard coded Module-Name.resx somewhere in the code path (without the language/location code added) and I am not sure if .Net is automatically using the right resx file.

I have not yet fixed this issue and currently we simply left the category names untranslated.

If there is enough interest I could debug what the root cause of this issue is and fix it.

Best regards & happy DNNing
Andy9999

**Comment by bdukes** [comment]
We would appreciate a fix if you're able to track it down. Thanks!

**Comment by Andy9999** [comment]
Here is a first update. It was indeed a caching issue (but there is a 2nd one that is less grave but still annoying).

Am happy I got a debugging environment now. The last time I debugged something in DNN it was still written in VB.NET, so a long time has passed. ;)

I changed the GetSearchContentSourceList method and added Thread.CurrentThread.CurrentCulture to the caching key.

```
public IEnumerable<SearchContentSource> GetSearchContentSourceList(int portalId)
{
   var searchableModuleDefsCacheArgs = new CacheItemArgs(
   string.Format(SearchableModuleDefsKey, SearchableModuleDefsCacheKey, portalId, Thread.CurrentThread.CurrentCulture),
         120, CacheItemPriority.Default);

   var list = CBO.GetCachedObject<IList<SearchContentSource>>(
          searchableModuleDefsCacheArgs, this.SearchContentSourceCallback);

   return list;
}
```

Now I could successfully translate "Pages" into the German "Seiten" in my SearchableModules.de-DE.resx file enable Pages for the English instance of the search result module and Seiten for the German one.

Searching works as well.

As long as you do not have the "Show source" option enabled in the search result modules settings this is already enough.

But, unfortunately there must be some other similar caching issue, because then it would cache the localized source name. So if you visit the English page first, you would see Pages as source. If you then change to German, it would still display Pages instead of Seiten.

Will dig some more to find this one as well.

Seems like for this reason, there are no localized SearchableModules.xx-XX.resx files included, right?

Best regards & happy DNNing
Andy9999

**Comment by Andy9999** [comment]
OK, another update.

There were actually two additional similar location where I had to add the CurrentCulture to the cache key.

1) GetSearchDocumentTypeDisplayName

`var key = string.Format("{0}-{1}-{2}", searchResult.SearchTypeId, searchResult.ModuleDefId, Thread.CurrentThread.CurrentCulture) ;`

2) SearchDocumentTypeDisplayNameCallBack

`var key = string.Format("{0}-{1}-{2}", searchContentSource.SearchTypeId, searchContentSource.ModuleDefinitionId, Thread.CurrentThread.CurrentCulture);`

I think I could wrap it up now. The localization could then be done separately in a 2nd step/issue if there is a demand for that.

Best regards & happy DNNing
Andy9999

**Comment by Andy9999** [comment]
By the way, is Thread.CurrentThread.CurrentCulture OK? I have seen the current culture being accessed in different ways. Even though I worked with .Net since the very beginning (here and there), I am a C++ dev in real life, so if it should be done differently would be great if someone could let me know. :)

Best regards & happy DNNing
Andy9999

**Comment by Andy9999** [comment]
I have initiated a pull request for this issue: https://github.com/dnnsoftware/Dnn.Platform/pull/5053

Best regards & happy DNNing
Andy9999

**Comment by Andy9999** [comment]
I have no idea why the dnnsoftware.Dnn.Platform test failed:

https://dev.azure.com/dotnet/DNN/_build/results?buildId=68115&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=1a5cc010-7735-550a-9d76-c0b745122dab&l=2665

Best regards & happy DNNing
Andy9999

**Comment by Andy9999** [comment]
Seems like the tests need some adjustment as well as they use the caching key without culture.

For example in DNN Platform\Tests\DotNetNuke.Tests.Web\InternalServices\SearchServiceControllerTests.cs:
...
            var tabKey = string.Format("{0}-{1}", TabSearchTypeId, 0);
            var userKey = string.Format("{0}-{1}", UserSearchTypeId, 0);
...

Best regards & happy DNNing
Andy9999

**Comment by Andy9999** [comment]
Updated the test and now it passed. :)

Best regards & happy DNNing
Andy9999
