### ISSUE TITLE
JQuery not injected when popups turned off.

### ISSUE THREAD

**Issue by leedavi** [dnnsoftware/Dnn.Platform#5060]
## Current behavior
Turn popups off, JQuery not injected.

```asp
<%@ Register TagPrefix="dnn" Namespace="DotNetNuke.Web.Client.ClientResourceManagement" Assembly="DotNetNuke.Web.Client" %>
<%@ Register TagPrefix="dnn" TagName="jQuery" Src="~/Admin/Skins/jQuery.ascx" %>
```

is included in the skin.

## Expected behavior

JQuery UI should not be injected. But JQuery still should be.

This is how it worked before.

## Affected version
* [X] 09.10.02 release candidate

## Workaround

Add JQuery CDN to the "HTML Header Tag" of all the Page.

**Comment by bdukes** [comment]
DNN only includes jQuery if something on the page asks for it. If your theme or modules require jQuery they need to request it (via the jQuery theme object).  You've registered the jQuery theme object in your example, but if you don't have `<dnn:jQuery runat="server" />` somewhere in the markup, then the registration doesn't do anything.

**Comment by leedavi** [comment]
OK, That token was missing on the skin.  It fixes the problem.
 But the designer is still going to go with his work around because of the JQuery Migrate that gets injected.

Thanks for your help.

**Comment by bdukes** [comment]
Yes, the jQuery theme object does request jQuery Migrate.

https://github.com/dnnsoftware/Dnn.Platform/blob/87d23d3be194037ef7caba540ae6c31003522f46/DNN%20Platform/Website/admin/Skins/jQuery.ascx.cs#L19-L38

As does requesting jQuery without a version

https://github.com/dnnsoftware/Dnn.Platform/blob/87d23d3be194037ef7caba540ae6c31003522f46/DNN%20Platform/Library/Framework/JavaScriptLibraries/JavaScript.cs#L81-L103

However, if you request jQuery with a version, then only that library gets requested. I would suggest using `JavaScriptLibraryInclude` in the theme so you don't run into a scenario where something on a page (e.g. a module) requests DNN's jQuery and then you have two copies overwriting each other.

```
<%@ Register TagPrefix="dnn" TagName="JavaScriptLibraryInclude" Src="~/Admin/Skins/JavaScriptLibraryInclude.ascx" %>

<dnn:JavaScriptLibraryInclude runat="server" Name="jQuery" Version="3.0.0" SpecificVersion="LatestMajor" />
```
