### ISSUE TITLE
HTML editor upload file: doesn't show subfolders

### ISSUE THREAD

**Issue by wbonekamp** [dnnsoftware/Dnn.Platform#5095]
## Description of bug
When recently upgraded DNN from DNN 9.3.2. to 9.10.2
File upload in HTML Editor doesn't show the subfolders. Only the root folder

## Steps to reproduce
List the precise steps to reproduce the bug:
1. TEXT/HTML Module
2. Edit content
3. Upload file
4. Browse on server

## Current behavior
Doesn't show the subfolders

## Expected behavior
Should show tree with subfolders

##Screenshot
![image](https://user-images.githubusercontent.com/7567981/164467324-6a434fd0-0859-45b5-aa3b-ce463ad587f0.png)

##Errors
No errors found in log or console

## Affected version
* [ ] 09.10.02 release candidate
* [ ] 09.10.01 latest supported release

## Affected browser
All

**Comment by joeinIL0405** [comment]
First-time commenter here! is it a permission error? Are you signed in as host or an authorized user?

**Comment by wbonekamp** [comment]
checked permissions on root folder on server. they are correct.
checked permissions in DNN File manager. They are correct. I can see al subfolders in the File Manager... no problem
Did a sync of all folders including subfolders

No luck. HTML editor and documents module won't show subfolder when trying to upload a file...

**Comment by wbonekamp** [comment]
Doesn't make a different which user you are signed in.. admin, host, content manager doesn't show subfolders

**Comment by wbonekamp** [comment]
It was a permissions issue... you have to remove them, add them again and do a resync...

**Comment by wbonekamp** [comment]
When you have more than one super user account (host) the subfolders are not visible for all the host accounts.
The original "host" account can't see the subfolders even if you resync all the permissions on the subfolders.

**Comment by cklenk** [comment]
> It was a permissions issue... you have to remove them, add them again and do a resync...

@wbonekamp What permissions did you remove? File permissions or user permissions? Did you have to do anything with the file permissions table? We have this same issue and haven't been able to fix it.
