### ISSUE TITLE
CKEditor option to resize images on upload

### ISSUE THREAD

**Issue by skamphuis** [dnnsoftware/Dnn.Platform#5101]
## Description of problem
Administrators still used to the RadEditorProvider are missing the option to specify a maximum size for images in the Editor Provider Settings. Since images from phones are getting larger and larger, and users tend to upload images straight from their device, people are very much used to the convenience of the RadEditor to resize the images to a certain maximum size on upload.
This is keeping sites from being upgraded to the latest version of DNN, with CKEditorProvider, or at least keeps them from removing Telerik.

## Description of solution
The CKEditor Provider settings should get an extra option for maximum height and width of images being uploaded. On upload images larger than these dimensions need to be automatically resized to fit within those dimensions.

## Description of alternatives considered
It would also be possible to check for maximum dimensions and present the user with an error, but that would be inacceptable from a UX point of view. Users should not have to worry about the resizing for a maximum size. Users needing more control (e.g. on quality) will know how to resize themselves, but most users won't care.

## Screenshots
![image](https://user-images.githubusercontent.com/4275042/165172204-9243d462-d3d0-41af-9b97-af68148cdcd8.png)

## Additional context
A PR is being worked on

## Affected browser
Not browser related

**Comment by valadas** [comment]
This has been done in #5128
