### ISSUE TITLE
Is Dnn.React.Common still published somewhere?

### ISSUE THREAD

**Issue by v-karbovnichy** [dnnsoftware/Dnn.Platform#5104]
[Dnn.React.Common (src)](https://github.com/dnnsoftware/Dnn.Platform/tree/develop/Dnn.AdminExperience/ClientSide/Dnn.React.Common/src) is used in some of Evoq UIs, and there are some things to fix there. But the package in npmjs is outdated: 
https://www.npmjs.com/package/@dnnsoftware/dnn-react-common

Are there any CI pipeline with packages that we can grab?

**Comment by valadas** [comment]
We have stopped publishing this package as we no longer recommend 3rd parties to consume it due to some maintenance and reusability issues. For that reason it is only part of this repository and consumed locally by the platform.
