### ISSUE TITLE
Update Jquery-UI version from 1.12.1 to latest 1.13.1

### ISSUE THREAD

**Issue by armaganpekatik** [dnnsoftware/Dnn.Platform#5115]
## Description of problem
DNN is using an old version of jquery-ui 1.12.1

## Description of solution
Upgrade jquery-ui to newer version from 1.12.1 to latest 1.13.1

## Description of alternatives considered
I will create a new PR including a solution

## Affected browser

* [X] Chrome
* [X] Firefox
* [X] Safari
* [X] Internet Explorer
* [X] Edge

**Comment by valadas** [comment]
Duplicates #4816, if you do send a PR, can you refer to the existing issue please. Thanks.
