### ISSUE TITLE
Get PortalId of childportal

### ISSUE THREAD

**Issue by wbonekamp** [dnnsoftware/Dnn.Platform#5117]
## Description of bug
We are building a custom module with different settings per portal.
The settings are stored in a module table. A different record per portal.

I'm trying to get the portalId of a childportal: domain.nl/test

When I use PortalController.Instance.GetCurrentSettings().PortalId; it returns the portalId of the parent portal domain.nl and not the portalid of the child portal domain.nl/test

Looks like a bug? is there a fix or workaround

## Current behavior
Returns portalid of parentportal domain.nl

## Expected behavior
Should return portalid of chilcportal domain.nl/test

## DNN Versions
* [ ] 09.10.02 
* [ ] 09.10.01 

## Affected browser
All

**Comment by wbonekamp** [comment]
It's a dynamic path so you don't have control of the url...

**Comment by bdukes** [comment]
How are you calling the API? The simplest way to get the right path is to use `jQuery.ServicesFramework` and call `getServiceRoot` on it:

https://github.com/dnnsoftware/Dnn.Platform/blob/9f83285a15d23203cbaad72d62add864ab5b8c7f/DNN%20Platform/Modules/CoreMessaging/Scripts/LocalizationController.js#L12

https://github.com/dnnsoftware/Dnn.Platform/blob/9f83285a15d23203cbaad72d62add864ab5b8c7f/DNN%20Platform/Modules/CoreMessaging/Scripts/LocalizationController.js#L41-L48

**Comment by Tychodewaard** [comment]
@wbonekamp Does the replies answer your question / issue? If so, we can close this one. If not, please elaborate so we can move forward.

**Comment by wbonekamp** [comment]
didn't answer the question, our developer used another workaround
