### ISSUE TITLE
Telerik removal results in erros when loading the Resource manager

### ISSUE THREAD

**Issue by eXistenZe** [dnnsoftware/Dnn.Platform#5135]
## Steps to reproduce
List the precise steps to reproduce the bug:
1. Follow the guide to remove the old DAM and telerik: https://docs.dnncommunity.org/content/getting-started/setup/telerik-removal/index.html
2. Open any of the pages containing the RM module.

## Current behavior
The module does not load and the persona bar shows no icons.

## Screenshots
![image](https://user-images.githubusercontent.com/26518879/172473067-7b3d5522-e3ab-4dcf-ace6-f8e1cd1b47a3.png)

## Error information
Following errors on log:
```
Uncaught SyntaxError: invalid regular expression flag v [js:1586:17](https://a.b/DependencyHandler.axd/2316ea21dbd5369ed8a85a9893712190/43/js)
Uncaught SyntaxError: invalid regular expression flag v[js:1586:17](https://a.b/DependencyHandler.axd/2316ea21dbd5369ed8a85a9893712190/43/js)
TypeError: can't access property "MenuItems", menuStructure is undefined [main.js:52:21](https://a.b/DesktopModules/admin/Dnn.PersonaBar/scripts/main.js?cdv=43)
Uncaught TypeError: can't access property "MenuItems", menuStructure is undefined [util.js:364:21](https://a.b/DesktopModules/admin/Dnn.PersonaBar/scripts/util.js?cdv=43)
```

## Affected version

* [ X ] 09.10.02 

## Affected browser
* [ ] Chrome
* [ X ] Firefox
* [ ] Safari
* [ ] Internet Explorer 11
* [ ] Microsoft Edge (Classic)
* [ ] Microsoft Edge Chromium

**Comment by valadas** [comment]
Is it possible that page has some custom javascript on it that expects the file manager to be there. I am curious what throws the very first error in the console, if you click on the link, it should point you to that place...

**Comment by david-poindexter** [comment]
Thanks @eXistenZe - closing per above and referencing #4885
