### ISSUE TITLE
Add OAuth 2.0 token-based support for sending emails

### ISSUE THREAD

**Issue by Timo-Breumelhof** [dnnsoftware/Dnn.Platform#5139]
## Description of problem
As reported here: https://dnncommunity.org/forums/aft/3003
MS is ending support for basic authentication see:

In September 2021, we announced that effective October 1, 2022, we will begin disabling Basic authentication for Outlook, EWS, RPS, POP, IMAP, and EAS protocols in Exchange Online. SMTP Auth will also be disabled if it is not being used. See full announcement: [Basic Authentication and Exchange Online – September 2021 Update](https://techcommunity.microsoft.com/t5/exchange-team-blog/basic-authentication-and-exchange-online-september-2021-update/ba-p/2772210).

This will mean that sending emails from DNN using an Office 365 / Exchange  / Outlook account would no longer be possible.

## Description of solution
To be discussed..

**Comment by rodrigoratan** [comment]
Google will also stop allowing SMTP 
https://support.google.com/accounts/answer/6010255?hl=en#:~:text=To%20help%20keep%20your%20account,only%20your%20username%20and%20password.

**Comment by Timo-Breumelhof** [comment]
More info: https://techcommunity.microsoft.com/t5/exchange-team-blog/announcing-oauth-2-0-client-credentials-flow-support-for-pop-and/ba-p/3562963

**Comment by jasclar** [comment]
I wish I had more time to delve into this and assist.
Please look at how Duplicati deals with this - see https://www.duplicati.com/articles/OAuth/
There is a service to handle OAuth - https://duplicati-oauth-handler.appspot.com/

**Comment by v-karbovnichy** [comment]
Tomorrow is the planned day for Exchange Online

But deadline was extended, Oct 1 2022 MS will disable support with an option to enable it back manually by tenant admin.

It will be finally disabled in Jan 2023 -- this is the final deadline.

https://techcommunity.microsoft.com/t5/exchange-team-blog/basic-authentication-deprecation-in-exchange-online-september/ba-p/3609437

**Comment by Timo-Breumelhof** [comment]
@mitchelsellers @WillStrohl @david-poindexter @donker @valadas 
Sorry for the Github Spam..
First of all, I logged because  a community member pointed me to the possible implications of this issue, not because it's an issue for us.
I would like to know if this is somehow on the Radar as not being able to send emails  from office 365  in the near future sounds like a serious dealbreaker for a lot of DNN users.

**Comment by Timo-Breumelhof** [comment]
@mitchelsellers ok thank you for the feedback.

**Comment by bdukes** [comment]
We'd need some way for the SMTP provider to have its own settings screen (either plugging into what's there or redirect to a separate page). Typically it would open the 3rd party site in a popup and then have an endpoint setup to handle the 3rd party redirect and record the token. I'm assuming this would be a long-lived token, not something that needs to happen on a regular basis.

**Comment by WillStrohl** [comment]
Honestly, should we support connecting directly to something like O365 for relaying email?  This isn't really a best practice.  You lack all of the tooling to know if email is consistently being sent, reviewing any exceptions, etc.  We should be encouraging people to use an actual SMTP service, right?

**Comment by sleupold** [comment]
IMO it depends on the size of the user base and the number of emails being sent out.
Some sites just send out a couple of administrative mails per year.

**Comment by Timo-Breumelhof** [comment]
@WillStrohl Well I think we might have quite a lot of Users that use an office 365 email account and if it does work with other email providers and not with the MS service that's going to be difficult to explain to the non tech / nerd user IMO.

**Comment by valadas** [comment]
https://github.com/dnnsoftware/Dnn.Platform/pull/5460 was submitted to support this scenario but unfortunately we don't have any testable implementation. Would be nice if we can resolve that last part.

**Comment by valadas** [comment]
@fablaser 2 implementations were submitted after my previous message and the Pull Request was merged.

The documentation to setup for Microsoft is in the https://github.com/jstedfast/MailKit/blob/master/ExchangeOAuth2.md

I was able to get to the authentication part but then could not send emails. My Microsoft account is all whacked though. If you want to give 9.13.0 a try, it is currently in RC (Release Candidate) stage but unless any big issue comes up we are doing the official release tonight...

**Comment by fablaser** [comment]
Thank you, 
I have some question about oauth implementation in DNN. In the past, I wrote some .NET apps that supports oauth2.0 in both "delegated" and "Application" permissions .

Using Application permissions, you need to set: TenantID, ClientID and Secret. In this case, no need to "authorize"
Using Delegated permissions, you only need to set TenantiID and ClientID. In this case application  needs to "authorize".

In DNN I see that, when I set TenantID, ClientID and Secret, authorize button is shown and it asks for admin password. This sounds strange to me... what is the permission implemented in DNN? Delegated or Application?

Thanks

**Comment by fablaser** [comment]
> @fablaser 2 implementations were submitted after my previous message and the Pull Request was merged.
> 
> The documentation to setup for Microsoft is in the https://github.com/jstedfast/MailKit/blob/master/ExchangeOAuth2.md
> 
> I was able to get to the authentication part but then could not send emails. My Microsoft account is all whacked though. If you want to give 9.13.0 a try, it is currently in RC (Release Candidate) stage but unless any big issue comes up we are doing the official release tonight...

Thank you,
I have some question about oauth implementation in DNN. In the past, I wrote some .NET apps that supports oauth2.0 in both "delegated" and "Application" permissions .

Using Application permissions, you need to set: TenantID, ClientID and Secret. In this case, no need to "authorize"
Using Delegated permissions, you only need to set TenantiID and ClientID. In this case application needs to "authorize".

In DNN I see that, when I set TenantID, ClientID and Secret, authorize button is shown and it asks for admin password. This sounds strange to me... what is the permission implemented in DNN? Delegated or Application?

Thanks

**Comment by valadas** [comment]
I am not sure... @zyhfish can you shed some light on this ?

**Comment by dowdian** [comment]
> This sounds strange to me... what is the permission implemented in DNN? Delegated or Application?

I believe it's Application permission based on the Microsoft documentation I've read and the code that @zyhfish wrote. I have been trying for weeks in both the RC and now in the release version of 9.13 to send an email without success. I've flipped a thousand switches, and I still can't make it work.

I've used the following as the primary guideline: https://learn.microsoft.com/en-us/exchange/client-developer/legacy-protocols/how-to-authenticate-an-imap-pop-smtp-application-by-using-oauth.

If _anyone_ has been successful in getting this to work, I am desperate for assistance. I'm working for a brand-new client, and I can't release the application (nor invoice them) until this is resolved.

**Comment by mitchelsellers** [comment]
@dowdian I am working to try and get some input from @zyhfish as sadly I cannot test this with my O365 client due to permissions issues that limit policies

**Comment by valadas** [comment]
For what it's worth, I use services specializing in sending emails for all my sites. Something like sendgrid.

**Comment by dowdian** [comment]
@valadas I looked into SendGrid actually. Is that something I can set up on my Azure account to send emails through my clients O365 Exchange instance? I gave up trying to get that set up because the folks managing the client's Exchange instance had difficulty setting up the account with Twilio.

Also, if it's of any use, the failure is happening at line 142 of ExchangeOnlineOAuthProvider.cs.
`smtpClient.Authenticate(username, accessToken);`

**Comment by valadas** [comment]
Yes sendgrid is pretty easy to setup, it is a proxy for sending emails out (could be marketing platform but can actu also just as a proxy). You set it up for the "from" address you will be using. You can verify just that address by replying to their email and then you can use plain smtp configuration and your api key is your password.

Now if you need to send emails "from" multiple people from a certain domain, you may want to do a domain verification instead of an email address verification. This will require you to enter some dns entries for verification of ownership of that domain but then you can send from any inbox on that domain.

If you need some help, join us on discord here https://discord.gg/USQSR3KA and ping me up `danielvaladas` I'll be glad to help you, this is like 10 minutes to setup...

**Comment by dowdian** [comment]
That sounds like the solution I’ve been searching for! I’ll reach out to you on Discord tomorrow. Thank you!!!

Michael Dowd
Sent from my phone
________________________________

**Comment by david-poindexter** [comment]
Same here - SendGrid is our "go to".

**Comment by WillStrohl** [comment]
> Same here - SendGrid is our "go to".

Same.

**Comment by Jc885** [comment]
In the DNN v.9.13 OAuth option, I entered the Auth provider as Exchange Online along with the Tenant ID, Client ID, and Client Secret. Upon clicking the Authorize button, it redirected me to the Outlook login page. After completing the 2FA, I encountered the error message "Original exception: AADSTS700025: Client is public so neither 'client_assertion' nor 'client_secret' should be presented."

I believe the issue doesn't lie with the IDs, keys, or application registration settings, as I am successfully using them in my own code to send emails. Since the only option available to me is to use the Office 365, I would appreciate any assistance. Thanks.

**Comment by fablaser** [comment]
> In the DNN v.9.13 OAuth option, I entered the Auth provider as Exchange Online along with the Tenant ID, Client ID, and Client Secret. Upon clicking the Authorize button, it redirected me to the Outlook login page. After completing the 2FA, I encountered the error message "Original exception: AADSTS700025: Client is public so neither 'client_assertion' nor 'client_secret' should be presented."
> 
> I believe the issue doesn't lie with the IDs, keys, or application registration settings, as I am successfully using them in my own code to send emails. Since the only option available to me is to use the Office 365, I would appreciate any assistance. Thanks.

Did you configured web authentication url? You need to set https://YOURDOMAIN/Providers/SmtpOAuthProviders/ExchangeOnline/Authorize.aspx URL. 

In my case I can successfully authenticate, but I cannot send emails: it continue using SMTP address: 
![oauth dnn](https://github.com/dnnsoftware/Dnn.Platform/assets/52076393/3bd46405-5870-4b68-82ca-eb0ae24f7f9d)

**Comment by Jc885** [comment]
> > In the DNN v.9.13 OAuth option, I entered the Auth provider as Exchange Online along with the Tenant ID, Client ID, and Client Secret. Upon clicking the Authorize button, it redirected me to the Outlook login page. After completing the 2FA, I encountered the error message "Original exception: AADSTS700025: Client is public so neither 'client_assertion' nor 'client_secret' should be presented."
> > I believe the issue doesn't lie with the IDs, keys, or application registration settings, as I am successfully using them in my own code to send emails. Since the only option available to me is to use the Office 365, I would appreciate any assistance. Thanks.
> 
> Did you configured web authentication url? You need to set https://YOURDOMAIN/Providers/SmtpOAuthProviders/ExchangeOnline/Authorize.aspx URL.
> 
> In my case I can successfully authenticate, but I cannot send emails: it continue using SMTP address: ![oauth dnn](https://user-images.githubusercontent.com/52076393/282717957-3bd46405-5870-4b68-82ca-eb0ae24f7f9d.png)

Yes, I did add the redirect URL. Before adding the URL, the error was" The redirect URL https://YOURDOMAIN/Providers/SmtpOAuthProviders/ExchangeOnline/Authorize.aspx specified in the request does not match the redirect URLs configured for the application <Client ID>. I am using the application permissions. Thanks.
