### ISSUE TITLE
Enhance cookie consent for GDPR compliance (cookie type individual accept/reject and cookie declaration)

### ISSUE THREAD

**Issue by eXistenZe** [dnnsoftware/Dnn.Platform#5140]
## Description of problem
DNN cookie consent is still very limited when it comes to GDPR compliance (and other legislation too).

## Description of solution
DNN should inform the type of cookies in use (own cookies, third party cookies, necessary, performance, ad related, etc) and allow the user which types they want.

## Description of alternatives considered
One icon for accept and one for settings:
![image](https://user-images.githubusercontent.com/26518879/174671622-afcb9593-5a0d-4baa-89fb-58ba256fff14.png)

One icon for Deny all, one for allow all, one for settings:
![image](https://user-images.githubusercontent.com/26518879/174671823-24f8867f-df35-4249-81b1-ded618cc6570.png)
![image](https://user-images.githubusercontent.com/26518879/174671899-a25bc20a-b801-48a8-a108-d388bdbd6747.png)

![image](https://user-images.githubusercontent.com/26518879/174671986-366cf315-1b21-4d29-aa76-c418c3cef71d.png)

## Additional context
Native cookies would be declared by default.
External cookies scripts (GA for example) would need to be wrapped for inclusion inside the cookie script, loaded according to the setting.

**Comment by donker** [comment]
The cookie consent implementation in DNN was kept minimal on purpose. It is very hard to serve all markets and every possible scenario. Especially when things are subject to change. We need to maintain all the code in the core, so the focus is to not add code unless it is absolutely necessary.

Having said that: the cookie consent implementation in DNN is extensible. It allows you to branch off into your own page where you manage the exact settings you want in your own cookie consent module.

Maybe someone will create a community module for this one day. For now this is not what we'll be devoting our time and effort to to implement in the core.
