### ISSUE TITLE
CDV feature has conflict with google search rich results test, which says it can't load resources with query string parameters.

### ISSUE THREAD

**Issue by Constantine-Ketskalo** [dnnsoftware/Dnn.Platform#5180]
Steps to reproduce:

1. Go to https://search.google.com/test/rich-results
2. Enter any DNN website url
3. Click "View tested page"
4. Click "more info"
5. Unfold "Page resources" section

It says that google robot couldn't load resources and it lists resources with query string parameters in a url (css, js and ScriptResource.axd). Looks like it's because of query string parameters. So could this feature be removed somehow? Probably some setting in a PersonaBar? Or is it google robot who is broken in this case?

P.S. I've checked those files manually and google chrome loads successfully all of those files.

**Comment by bdukes** [comment]
I think Google Bot is broken here. Can you give an example URL? The two I tried didn't demonstrate this issue

**Comment by Constantine-Ketskalo** [comment]
> I think Google Bot is broken here. Can you give an example URL? The two I tried didn't demonstrate this issue

https://netls.com.ua/

**Comment by valadas** [comment]
Yeah, looks like a bot issue. querystring parameters for cache-busting is a totally valid thing.
