### ISSUE TITLE
An error occurred when executing task 'Build'

### ISSUE THREAD

**Issue by mnouraei** [dnnsoftware/Dnn.Platform#5182]
Hi, 
An error occurred when executing task 'Build'.

`"E:\DevDnn\DNN_Platform.sln" (Rebuild target) (1) ->
       "E:\DevDnn\Dnn.AdminExperience\Library\Dnn.PersonaBar.UI\Dnn.PersonaBar.UI.csproj.metaproj" (Rebuild target) (15) ->
       "E:\DevDnn\Dnn.AdminExperience\Dnn.PersonaBar.Extensions\Dnn.PersonaBar.Extensions.csproj" (Rebuild target) (19) ->
       "E:\DevDnn\Dnn.AdminExperience\Dnn.PersonaBar.Extensions\Dnn.PersonaBar.Extensions.csproj" (RunYarnWorkspace target) (19:2) ->
       (RunYarnWorkspace target) ->
         E:\DevDnn\Build\BuildScripts\AEModule.build(49,5): error MSB6006: "yarn" exited with code 1. [E:\DevDnn\Dnn.AdminExperience\Dnn.PersonaBar.Extensions\Dnn.PersonaBar.Extensions.csproj]`

![Error](https://user-images.githubusercontent.com/9780304/177078626-70e75b82-5f9b-420a-92f7-58342bae5af8.png)

Please help me.

**Comment by valadas** [comment]
Can you try to open a terminal and manually running
`yarn install`
followed by (if install works)
`yarn build`

**Comment by jeremy-farrance** [comment]
What version on DNN? What version of Visual Studio? Was this a working setup or new? If this is a new development setup, what instructions are you following?

**Comment by mnouraei** [comment]
> Can you try to open a terminal and manually running `yarn install` followed by (if install works) `yarn build`

`yarn install` and `yarn build` Works

![yarnInstall](https://user-images.githubusercontent.com/9780304/177240220-ef77ac62-cd44-4df2-84bd-fe35f3acf04e.png)

**Comment by mnouraei** [comment]
> What version on DNN? What version of Visual Studio? Was this a working setup or new? If this is a new development setup, what instructions are you following?

DNN: 9.10.2
Visual Studio: 2007 and 2019 last version
Instructions: 
Opening a terminal and running
1. run script `.\Build.ps1 --target=CreateSettings`
2. Change version to 9.10.2 in _settings.local_
3. run script `.\Build.ps1`

**Comment by mnouraei** [comment]
Please guide me, which version of Visual Studio with what features should I use?

**Comment by valadas** [comment]
I _think_ it should work with 2019 but I use 2022 (free edition is fine), 2007 is pretty outdated

**Comment by mnouraei** [comment]
> I _think_ it should work with 2019 but I use 2022 (free edition is fine), 2007 is pretty outdated

What version of Nodejs and Yarn?
I use nodejs v16.16.0 and yarn v3.2.1.
I have not found a solution to fix it.
![Error](https://user-images.githubusercontent.com/9780304/179346197-ae532082-564f-4948-8abe-a54056000a56.png)

**Comment by valadas** [comment]
Can you try running `yarn install` then `yarn build` in a terminal to see if you get a more detailed error...

**Comment by mnouraei** [comment]
> Can you try running `yarn install` then `yarn build` in a terminal to see if you get a more detailed error...

I tried this, the result was like this:

Error: `lerna ERR! yarn run build exited 1 in '@dnnsoftware/dnn-react-common'`

Steps in the console:

`PS E:\DevDnn> git clean -dxf`
`PS E:\DevDnn> yarn install`
`➤ YN0000: ┌ Resolution step`
`➤ YN0060: │ @dnnsoftware/dnn-react-common@workspace:Dnn.AdminExperience/ClientSide/Dnn.React.Common provides eslint (p02f35) with version 7.32.0, which doesn't satisfy what eslint-plugin-react requests`
`➤ YN0060: │ @dnnsoftware/dnn-react-common@workspace:Dnn.AdminExperience/ClientSide/Dnn.React.Common [2b405] provides eslint (p32f75) with version 7.32.0, which doesn't satisfy what eslint-plugin-react requests`
`➤ YN0060: │ @dnnsoftware/dnn-react-common@workspace:Dnn.AdminExperience/ClientSide/Dnn.React.Common [c72b6] provides eslint (pf0f95) with version 7.32.0, which doesn't satisfy what eslint-plugin-react requests`
`➤ YN0060: │ @dnnsoftware/dnn-react-common@workspace:Dnn.AdminExperience/ClientSide/Dnn.React.Common [d2a2b] provides eslint (pb09ff) with version 7.32.0, which doesn't satisfy what eslint-plugin-react requests`
`➤ YN0060: │ @dnnsoftware/dnn-react-common@workspace:Dnn.AdminExperience/ClientSide/Dnn.React.Common [e0e5e] provides eslint (p62dee) with version 7.32.0, which doesn't satisfy what eslint-plugin-react requests`
`➤ YN0002: │ @emotion/styled@npm:10.0.10 doesn't provide @emotion/core (pbc15c), requested by @emotion/styled-base`
`➤ YN0002: │ @emotion/styled@npm:10.0.10 doesn't provide react (pc8442), requested by @emotion/styled-base`
`➤ YN0002: │ @storybook/client-api@npm:5.0.11 doesn't provide react (p0dd39), requested by @storybook/router`
`➤ YN0002: │ @storybook/client-api@npm:5.0.11 doesn't provide react-dom (p6fcc9), requested by @storybook/router`
`➤ YN0002: │ @storybook/core@npm:5.0.11 [1d828] doesn't provide @babel/core (pe2e13), requested by @babel/plugin-proposal-object-rest-spread`
`➤ YN0002: │ @storybook/core@npm:5.0.11 [1d828] doesn't provide @babel/core (p83f75), requested by @babel/plugin-proposal-class-properties`
`➤ YN0002: │ @storybook/core@npm:5.0.11 [1d828] doesn't provide @babel/core (p899ee), requested by @babel/plugin-syntax-dynamic-import`
`➤ YN0002: │ @storybook/core@npm:5.0.11 [1d828] doesn't provide @babel/core (pf7e6b), requested by @babel/plugin-transform-react-constant-elements`
`➤ YN0002: │ @storybook/core@npm:5.0.11 [1d828] doesn't provide @babel/core (p9f4f8), requested by @babel/preset-env`
`➤ YN0002: │ @storybook/core@npm:5.0.11 [547ac] doesn't provide @babel/core (pcdd96), requested by @babel/plugin-proposal-object-rest-spread`
`➤ YN0002: │ @storybook/core@npm:5.0.11 [547ac] doesn't provide @babel/core (p5a375), requested by @babel/plugin-proposal-class-properties`
`➤ YN0002: │ @storybook/core@npm:5.0.11 [547ac] doesn't provide @babel/core (p50c32), requested by @babel/plugin-syntax-dynamic-import`
`➤ YN0002: │ @storybook/core@npm:5.0.11 [547ac] doesn't provide @babel/core (p35df5), requested by @babel/plugin-transform-react-constant-elements`
`➤ YN0002: │ @storybook/core@npm:5.0.11 [547ac] doesn't provide @babel/core (pb2c03), requested by @babel/preset-env`
`➤ YN0002: │ @storybook/core@npm:5.0.11 [89a7c] doesn't provide @babel/core (pfb30a), requested by @babel/plugin-proposal-object-rest-spread`
`➤ YN0002: │ @storybook/core@npm:5.0.11 [89a7c] doesn't provide @babel/core (p03ad7), requested by @babel/plugin-proposal-class-properties`
`➤ YN0002: │ @storybook/core@npm:5.0.11 [89a7c] doesn't provide @babel/core (pe1e46), requested by @babel/plugin-syntax-dynamic-import`
`➤ YN0002: │ @storybook/core@npm:5.0.11 [89a7c] doesn't provide @babel/core (p07cf3), requested by @babel/plugin-transform-react-constant-elements`
`➤ YN0002: │ @storybook/core@npm:5.0.11 [89a7c] doesn't provide @babel/core (p1da8c), requested by @babel/preset-env`
`➤ YN0002: │ @storybook/core@npm:5.0.11 [b7017] doesn't provide @babel/core (pefb14), requested by @babel/plugin-proposal-object-rest-spread`
`➤ YN0002: │ @storybook/core@npm:5.0.11 [b7017] doesn't provide @babel/core (p0f9cf), requested by @babel/plugin-proposal-class-properties`
`➤ YN0002: │ @storybook/core@npm:5.0.11 [b7017] doesn't provide @babel/core (pf8706), requested by @babel/plugin-syntax-dynamic-import`
`➤ YN0002: │ @storybook/core@npm:5.0.11 [b7017] doesn't provide @babel/core (p154a5), requested by @babel/plugin-transform-react-constant-elements`
`➤ YN0002: │ @storybook/core@npm:5.0.11 [b7017] doesn't provide @babel/core (pfe96e), requested by @babel/preset-env`
`➤ YN0002: │ @storybook/core@npm:5.0.11 [fa3f7] doesn't provide @babel/core (p4d1fb), requested by @babel/plugin-proposal-object-rest-spread`
`➤ YN0002: │ @storybook/core@npm:5.0.11 [fa3f7] doesn't provide @babel/core (p86dbf), requested by @babel/plugin-proposal-class-properties`
`➤ YN0002: │ @storybook/core@npm:5.0.11 [fa3f7] doesn't provide @babel/core (pbe744), requested by @babel/plugin-syntax-dynamic-import`
`➤ YN0002: │ @storybook/core@npm:5.0.11 [fa3f7] doesn't provide @babel/core (p464e3), requested by @babel/plugin-transform-react-constant-elements`
`➤ YN0002: │ @storybook/core@npm:5.0.11 [fa3f7] doesn't provide @babel/core (p8ed4c), requested by @babel/preset-env`
`➤ YN0002: │ @storybook/react@npm:5.0.11 [04bfc] doesn't provide @babel/core (p9887e), requested by @babel/plugin-transform-react-constant-elements`
`➤ YN0002: │ @storybook/react@npm:5.0.11 [04bfc] doesn't provide @babel/core (p99e29), requested by @babel/preset-flow`
`➤ YN0002: │ @storybook/react@npm:5.0.11 [04bfc] doesn't provide @babel/core (pc994e), requested by @babel/preset-react`
`➤ YN0002: │ @storybook/react@npm:5.0.11 [04bfc] doesn't provide @babel/core (p412a8), requested by babel-plugin-named-asset-import`
`➤ YN0002: │ @storybook/react@npm:5.0.11 [31134] doesn't provide @babel/core (p7666b), requested by @babel/plugin-transform-react-constant-elements`
`➤ YN0002: │ @storybook/react@npm:5.0.11 [31134] doesn't provide @babel/core (p0f21a), requested by @babel/preset-flow`
`➤ YN0002: │ @storybook/react@npm:5.0.11 [31134] doesn't provide @babel/core (p84f11), requested by @babel/preset-react`
`➤ YN0002: │ @storybook/react@npm:5.0.11 [31134] doesn't provide @babel/core (p0f9a9), requested by babel-plugin-named-asset-import`
`➤ YN0002: │ @storybook/react@npm:5.0.11 [40bce] doesn't provide @babel/core (p112e5), requested by @babel/plugin-transform-react-constant-elements`
`➤ YN0002: │ @storybook/react@npm:5.0.11 [40bce] doesn't provide @babel/core (pc3799), requested by @babel/preset-flow`
`➤ YN0002: │ @storybook/react@npm:5.0.11 [40bce] doesn't provide @babel/core (pa53be), requested by @babel/preset-react`
`➤ YN0002: │ @storybook/react@npm:5.0.11 [40bce] doesn't provide @babel/core (p9c3e0), requested by babel-plugin-named-asset-import`
`➤ YN0002: │ @storybook/react@npm:5.0.11 [9c393] doesn't provide @babel/core (p11f23), requested by @babel/plugin-transform-react-constant-elements`
`➤ YN0002: │ @storybook/react@npm:5.0.11 [9c393] doesn't provide @babel/core (p1e620), requested by @babel/preset-flow`
`➤ YN0002: │ @storybook/react@npm:5.0.11 [9c393] doesn't provide @babel/core (p45a43), requested by @babel/preset-react`
`➤ YN0002: │ @storybook/react@npm:5.0.11 [9c393] doesn't provide @babel/core (pdb779), requested by babel-plugin-named-asset-import`
`➤ YN0002: │ @storybook/react@npm:5.0.11 [c1dc0] doesn't provide @babel/core (pe6ac1), requested by @babel/plugin-transform-react-constant-elements`
`➤ YN0002: │ @storybook/react@npm:5.0.11 [c1dc0] doesn't provide @babel/core (pb9059), requested by @babel/preset-flow`
`➤ YN0002: │ @storybook/react@npm:5.0.11 [c1dc0] doesn't provide @babel/core (p3bd27), requested by @babel/preset-react`
`➤ YN0002: │ @storybook/react@npm:5.0.11 [c1dc0] doesn't provide @babel/core (pe3a27), requested by babel-plugin-named-asset-import`
`➤ YN0002: │ admin_logs@workspace:Dnn.AdminExperience/ClientSide/AdminLogs.Web doesn't provide @types/react (p21885), requested by redux-devtools-dock-monitor`
`➤ YN0060: │ admin_logs@workspace:Dnn.AdminExperience/ClientSide/AdminLogs.Web provides eslint (pea1fb) with version 7.32.0, which doesn't satisfy what eslint-plugin-react requests`
`➤ YN0002: │ babel-preset-react-app@npm:7.0.2 doesn't provide webpack (p3a524), requested by babel-loader`
`➤ YN0060: │ dnn-sitegroups@workspace:Dnn.AdminExperience/ClientSide/SiteGroups.Web provides eslint (p5f50f) with version 7.32.0, which doesn't satisfy what eslint-plugin-react requests`
`➤ YN0060: │ dnn-sitegroups@workspace:Dnn.AdminExperience/ClientSide/SiteGroups.Web provides react (p91e3c) with version 16.8.6, which doesn't satisfy what @dnnsoftware/dnn-react-common and some of its descendants request`
`➤ YN0060: │ dnn-sitegroups@workspace:Dnn.AdminExperience/ClientSide/SiteGroups.Web provides react-dom (p678c6) with version 16.13.0, which doesn't satisfy what @dnnsoftware/dnn-react-common and some of its descendants request`
`➤ YN0060: │ dnn-sites-list-view@workspace:Dnn.AdminExperience/ClientSide/Sites.Web/src/_exportables provides eslint (p06e23) with version 7.32.0, which doesn't satisfy what eslint-plugin-react requests`
`➤ YN0060: │ dnn-sites-list-view@workspace:Dnn.AdminExperience/ClientSide/Sites.Web/src/_exportables provides react-hot-loader (p5cc15) with version 4.3.5, which doesn't satisfy what @dnnsoftware/dnn-react-common requests`
`➤ YN0060: │ dnn-users-exportables@workspace:Dnn.AdminExperience/ClientSide/Users.Web/src/_exportables provides eslint (p03e09) with version 7.32.0, which doesn't satisfy what eslint-plugin-react requests`
`➤ YN0002: │ export-bundle@workspace:Dnn.AdminExperience/ClientSide/Bundle.Web doesn't provide @types/react (p6c2b4), requested by redux-devtools-dock-monitor`
`➤ YN0060: │ export-bundle@workspace:Dnn.AdminExperience/ClientSide/Bundle.Web provides eslint (p8a9ec) with version 7.32.0, which doesn't satisfy what eslint-plugin-react requests`
`➤ YN0060: │ export-bundle@workspace:Dnn.AdminExperience/ClientSide/Bundle.Web provides react (p3d039) with version 16.8.6, which doesn't satisfy what @dnnsoftware/dnn-react-common and some of its descendants request`
`➤ YN0060: │ export-bundle@workspace:Dnn.AdminExperience/ClientSide/Bundle.Web provides react-dom (pcfa7f) with version 16.13.0, which doesn't satisfy what @dnnsoftware/dnn-react-common and some of its descendants request`
`➤ YN0060: │ extensions@workspace:Dnn.AdminExperience/ClientSide/Extensions.Web provides eslint (p9e5a8) with version 7.32.0, which doesn't satisfy what eslint-plugin-react requests`
`➤ YN0060: │ extensions@workspace:Dnn.AdminExperience/ClientSide/Extensions.Web provides react (pd704b) with version 16.8.6, which doesn't satisfy what @dnnsoftware/dnn-react-common and some of its descendants request`
`➤ YN0060: │ extensions@workspace:Dnn.AdminExperience/ClientSide/Extensions.Web provides react-dom (pdfd74) with version 16.13.0, which doesn't satisfy what @dnnsoftware/dnn-react-common and some of its descendants request`
`➤ YN0060: │ licensing@workspace:Dnn.AdminExperience/ClientSide/Licensing.Web provides eslint (pd52f4) with version 7.32.0, which doesn't satisfy what eslint-plugin-react requests`
`➤ YN0002: │ licensing@workspace:Dnn.AdminExperience/ClientSide/Licensing.Web doesn't provide react (p178cf), requested by react-hot-loader`
`➤ YN0002: │ licensing@workspace:Dnn.AdminExperience/ClientSide/Licensing.Web doesn't provide react (p268c2), requested by react-modal`
`➤ YN0002: │ licensing@workspace:Dnn.AdminExperience/ClientSide/Licensing.Web doesn't provide react-dom (p39c87), requested by react-hot-loader`
`➤ YN0002: │ licensing@workspace:Dnn.AdminExperience/ClientSide/Licensing.Web doesn't provide react-dom (pce307), requested by react-modal`
`➤ YN0060: │ pages@workspace:Dnn.AdminExperience/ClientSide/Pages.Web provides eslint (p02c75) with version 7.32.0, which doesn't satisfy what eslint-plugin-react requests`
`➤ YN0002: │ pages@workspace:Dnn.AdminExperience/ClientSide/Pages.Web doesn't provide eslint-plugin-import (p6054e), requested by eslint-import-resolver-webpack`
`➤ YN0060: │ pages@workspace:Dnn.AdminExperience/ClientSide/Pages.Web provides react (pc7aa2) with version 16.8.6, which doesn't satisfy what @dnnsoftware/dnn-react-common and some of its descendants request`
`➤ YN0060: │ pages@workspace:Dnn.AdminExperience/ClientSide/Pages.Web provides react-dom (p4a0c2) with version 16.13.0, which doesn't satisfy what @dnnsoftware/dnn-react-common and some of its descendants request`
`➤ YN0002: │ prompt@workspace:Dnn.AdminExperience/ClientSide/Prompt.Web doesn't provide @types/react (pfd23c), requested by redux-devtools-dock-monitor`
`➤ YN0060: │ prompt@workspace:Dnn.AdminExperience/ClientSide/Prompt.Web provides eslint (p7fb28) with version 7.32.0, which doesn't satisfy what eslint-plugin-react requests`
`➤ YN0060: │ prompt@workspace:Dnn.AdminExperience/ClientSide/Prompt.Web provides react (p25de9) with version 16.8.6, which doesn't satisfy what @dnnsoftware/dnn-react-common and some of its descendants request`
`➤ YN0060: │ prompt@workspace:Dnn.AdminExperience/ClientSide/Prompt.Web provides react-dom (pfb1f4) with version 16.13.0, which doesn't satisfy what @dnnsoftware/dnn-react-common and some of its descendants request`
`➤ YN0060: │ prompt@workspace:Dnn.AdminExperience/ClientSide/Prompt.Web provides webpack (pcae53) with version 4.31.0, which doesn't satisfy what extract-text-webpack-plugin requests`
`➤ YN0002: │ redux-devtools-log-monitor@npm:1.4.0 [8d411] doesn't provide react-dom (p64e20), requested by react-json-tree`
`➤ YN0002: │ redux-devtools-log-monitor@npm:1.4.0 [ad1d6] doesn't provide react-dom (p60bbd), requested by react-json-tree`
`➤ YN0002: │ redux-devtools-log-monitor@npm:1.4.0 [c0f06] doesn't provide react-dom (pb1e36), requested by react-json-tree`
`➤ YN0002: │ redux-devtools-log-monitor@npm:1.4.0 [c72b6] doesn't provide react-dom (p5545e), requested by react-json-tree`
`➤ YN0060: │ resource-library@workspace:DNN Platform/Modules/ResourceManager/ResourceManager.Web provides react (p7ca20) with version 16.8.6, which doesn't satisfy what @dnnsoftware/dnn-react-common and some of its descendants request`
`➤ YN0060: │ resource-library@workspace:DNN Platform/Modules/ResourceManager/ResourceManager.Web provides react-dom (p7136c) with version 16.13.0, which doesn't satisfy what @dnnsoftware/dnn-react-common and some of its descendants request`
`➤ YN0060: │ roles@workspace:Dnn.AdminExperience/ClientSide/Roles.Web provides eslint (p4d000) with version 7.32.0, which doesn't satisfy what eslint-plugin-react requests`
`➤ YN0060: │ roles@workspace:Dnn.AdminExperience/ClientSide/Roles.Web provides react (pdf5b2) with version 16.8.6, which doesn't satisfy what @dnnsoftware/dnn-react-common and some of its descendants request`
`➤ YN0060: │ roles@workspace:Dnn.AdminExperience/ClientSide/Roles.Web provides react-dom (p7032c) with version 16.13.0, which doesn't satisfy what @dnnsoftware/dnn-react-common and some of its descendants request`
`➤ YN0060: │ security_settings@workspace:Dnn.AdminExperience/ClientSide/Security.Web provides eslint (pe25c0) with version 7.32.0, which doesn't satisfy what eslint-plugin-react requests`
`➤ YN0060: │ security_settings@workspace:Dnn.AdminExperience/ClientSide/Security.Web provides react (p3cb81) with version 16.8.6, which doesn't satisfy what @dnnsoftware/dnn-react-common and some of its descendants request`
`➤ YN0060: │ security_settings@workspace:Dnn.AdminExperience/ClientSide/Security.Web provides react-dom (ped922) with version 16.13.0, which doesn't satisfy what @dnnsoftware/dnn-react-common and some of its descendants request`
`➤ YN0060: │ seo@workspace:Dnn.AdminExperience/ClientSide/Seo.Web provides eslint (p1e98d) with version 7.32.0, which doesn't satisfy what eslint-plugin-react requests`
`➤ YN0060: │ seo@workspace:Dnn.AdminExperience/ClientSide/Seo.Web provides react (p8874a) with version 16.8.6, which doesn't satisfy what @dnnsoftware/dnn-react-common and some of its descendants request`
`➤ YN0060: │ seo@workspace:Dnn.AdminExperience/ClientSide/Seo.Web provides react-dom (p1a0ad) with version 16.13.0, which doesn't satisfy what @dnnsoftware/dnn-react-common and some of its descendants request`
`➤ YN0060: │ servers@workspace:Dnn.AdminExperience/ClientSide/Servers.Web provides eslint (pd939d) with version 7.32.0, which doesn't satisfy what eslint-plugin-react requests`
`➤ YN0060: │ servers@workspace:Dnn.AdminExperience/ClientSide/Servers.Web provides react (pf5bf9) with version 16.8.6, which doesn't satisfy what @dnnsoftware/dnn-react-common and some of its descendants request`
`➤ YN0060: │ servers@workspace:Dnn.AdminExperience/ClientSide/Servers.Web provides react-dom (pa23ea) with version 16.13.0, which doesn't satisfy what @dnnsoftware/dnn-react-common and some of its descendants request`
`➤ YN0002: │ site_import_export@workspace:Dnn.AdminExperience/ClientSide/SiteImportExport.Web doesn't provide @types/react (p69af6), requested by redux-devtools-dock-monitor`
`➤ YN0060: │ site_import_export@workspace:Dnn.AdminExperience/ClientSide/SiteImportExport.Web provides eslint (p26491) with version 7.32.0, which doesn't satisfy what eslint-plugin-react requests`
`➤ YN0060: │ site_import_export@workspace:Dnn.AdminExperience/ClientSide/SiteImportExport.Web provides react (p9e93d) with version 16.8.6, which doesn't satisfy what @dnnsoftware/dnn-react-common and some of its descendants request`
`➤ YN0060: │ site_import_export@workspace:Dnn.AdminExperience/ClientSide/SiteImportExport.Web provides react-dom (pff8cb) with version 16.13.0, which doesn't satisfy what @dnnsoftware/dnn-react-common and some of its descendants request➤ YN0060: │ site_settings@workspace:Dnn.AdminExperience/ClientSide/SiteSettings.Web provides eslint (p1e39d) with version 7.32.0, which doesn't satisfy what eslint-plugin-react requests`
`➤ YN0060: │ site_settings@workspace:Dnn.AdminExperience/ClientSide/SiteSettings.Web provides react (p35b15) with version 16.8.6, which doesn't satisfy what @dnnsoftware/dnn-react-common and some of its descendants request`
`➤ YN0060: │ site_settings@workspace:Dnn.AdminExperience/ClientSide/SiteSettings.Web provides react-dom (p6ceb1) with version 16.13.0, which doesn't satisfy what @dnnsoftware/dnn-react-common and some of its descendants request`
`➤ YN0060: │ sites@workspace:Dnn.AdminExperience/ClientSide/Sites.Web provides eslint (p67ff8) with version 7.32.0, which doesn't satisfy what eslint-plugin-react requests`
`➤ YN0060: │ sites@workspace:Dnn.AdminExperience/ClientSide/Sites.Web provides react (p01ecb) with version 16.8.6, which doesn't satisfy what @dnnsoftware/dnn-react-common and some of its descendants request`
`➤ YN0060: │ sites@workspace:Dnn.AdminExperience/ClientSide/Sites.Web provides react-dom (p4717d) with version 16.13.0, which doesn't satisfy what @dnnsoftware/dnn-react-common and some of its descendants request`
`➤ YN0002: │ svg-url-loader@npm:2.3.2 doesn't provide webpack (p07783), requested by file-loader`
`➤ YN0060: │ task_scheduler@workspace:Dnn.AdminExperience/ClientSide/TaskScheduler.Web provides eslint (p2907c) with version 7.32.0, which doesn't satisfy what eslint-plugin-react requests`
`➤ YN0060: │ task_scheduler@workspace:Dnn.AdminExperience/ClientSide/TaskScheduler.Web provides react (p12ed3) with version 16.8.6, which doesn't satisfy what @dnnsoftware/dnn-react-common and some of its descendants request`
`➤ YN0060: │ task_scheduler@workspace:Dnn.AdminExperience/ClientSide/TaskScheduler.Web provides react-dom (pb9f2a) with version 16.13.0, which doesn't satisfy what @dnnsoftware/dnn-react-common and some of its descendants request`
`➤ YN0060: │ taxonomy@workspace:Dnn.AdminExperience/ClientSide/Vocabularies.Web provides eslint (pe1bac) with version 7.32.0, which doesn't satisfy what eslint-plugin-react requests`
`➤ YN0060: │ taxonomy@workspace:Dnn.AdminExperience/ClientSide/Vocabularies.Web provides react (pfc89b) with version 16.8.6, which doesn't satisfy what @dnnsoftware/dnn-react-common and some of its descendants request`
`➤ YN0060: │ taxonomy@workspace:Dnn.AdminExperience/ClientSide/Vocabularies.Web provides react-dom (p55bef) with version 16.13.0, which doesn't satisfy what @dnnsoftware/dnn-react-common and some of its descendants request`
`➤ YN0060: │ themes@workspace:Dnn.AdminExperience/ClientSide/Themes.Web provides eslint (pf4756) with version 7.32.0, which doesn't satisfy what eslint-plugin-react requests`
`➤ YN0060: │ themes@workspace:Dnn.AdminExperience/ClientSide/Themes.Web provides react (p42c1f) with version 16.8.6, which doesn't satisfy what @dnnsoftware/dnn-react-common and some of its descendants request`
`➤ YN0060: │ themes@workspace:Dnn.AdminExperience/ClientSide/Themes.Web provides react-dom (p15a0a) with version 16.13.0, which doesn't satisfy what @dnnsoftware/dnn-react-common and some of its descendants request`
`➤ YN0060: │ users@workspace:Dnn.AdminExperience/ClientSide/Users.Web provides eslint (p6aff3) with version 7.32.0, which doesn't satisfy what eslint-plugin-react requests`
`➤ YN0060: │ users@workspace:Dnn.AdminExperience/ClientSide/Users.Web provides react (p88ba9) with version 16.8.6, which doesn't satisfy what @dnnsoftware/dnn-react-common and some of its descendants request`
`➤ YN0060: │ users@workspace:Dnn.AdminExperience/ClientSide/Users.Web provides react-dom (p05ef1) with version 16.13.0, which doesn't satisfy what @dnnsoftware/dnn-react-common and some of its descendants request`
`➤ YN0000: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code`
`➤ YN0000: └ Completed in 0s 690ms`
`➤ YN0000: ┌ Fetch step`
`➤ YN0013: │ yargs-parser@npm:13.1.2 can't be found in the cache and will be fetched from the remote registry`
`➤ YN0013: │ yargs@npm:12.0.2 can't be found in the cache and will be fetched from the remote registry`
`➤ YN0013: │ yargs@npm:12.0.5 can't be found in the cache and will be fetched from the remote registry`
`➤ YN0013: │ yargs@npm:13.2.4 can't be found in the cache and will be fetched from the remote registry`
`➤ YN0013: │ yargs@npm:13.3.2 can't be found in the cache and will be fetched from the remote registry`
`➤ YN0000: └ Completed in 7s 21ms`
`➤ YN0000: ┌ Link step`
`➤ YN0007: │ core-js@npm:3.18.1 must be built because it never has been before or the last one failed`
`➤ YN0007: │ webpack-cli@npm:3.3.2 [31134] must be built because it never has been before or the last one failed`
`➤ YN0007: │ fetch-mock@npm:7.3.3 must be built because it never has been before or the last one failed`
`➤ YN0000: └ Completed in 57s 670ms`
`➤ YN0000: Done with warnings in 1m 6s`
`PS E:\DevDnn> yarn build`
`lerna notice cli v3.16.4`
`lerna info versioning independent`
`lerna info Executing command in 22 packages: "yarn run build"`
`@dnnsoftware/dnn-react-common: Browserslist: caniuse-lite is outdated. Please run next command "yarn upgrade"`
`@dnnsoftware/dnn-react-common: Hash: a30a578607ae68dec1b6`
`@dnnsoftware/dnn-react-common: Version: webpack 4.31.0`
`@dnnsoftware/dnn-react-common: Time: 20573ms`
`@dnnsoftware/dnn-react-common: Built at: 2020/07/19 8:35:54`
`@dnnsoftware/dnn-react-common:  3 assets`
`@dnnsoftware/dnn-react-common: Entrypoint main = dnn-react-common.min.js`
`@dnnsoftware/dnn-react-common:   [6] ./src/SvgIcons/index.jsx 18.5 KiB {0} [built]`
`@dnnsoftware/dnn-react-common:   [7] ./src/GridCell/index.jsx 4.74 KiB {0} [built]`
`@dnnsoftware/dnn-react-common:  [10] ./src/Tooltip/index.jsx 7.86 KiB {0} [built]`
`@dnnsoftware/dnn-react-common:  [13] ./src/Label/index.jsx 5.51 KiB {0} [built]`
`@dnnsoftware/dnn-react-common:  [15] ./src/Button/index.jsx 1.82 KiB {0} [built]`
`@dnnsoftware/dnn-react-common:  [16] ./src/Dropdown/index.jsx 18.4 KiB {0} [built]`
`@dnnsoftware/dnn-react-common:  [17] ./src/IconButton/index.jsx 6.73 KiB {0} [built]`
`@dnnsoftware/dnn-react-common:  [22] ./src/TextOverflowWrapperNew/index.jsx 5.82 KiB {0} [built]`
`@dnnsoftware/dnn-react-common:  [39] ./src/BackToLink/index.jsx 1.97 KiB {0} [built]`
`@dnnsoftware/dnn-react-common:  [40] ./src/MultiLineInputWithError/index.jsx 9.13 KiB {0} [built]`
`@dnnsoftware/dnn-react-common:  [41] ./src/MultiLineInput/index.jsx 5.92 KiB {0} [built]`
`@dnnsoftware/dnn-react-common:  [42] ./src/SingleLineInputWithError/index.jsx 9.46 KiB {0} [built]`
`@dnnsoftware/dnn-react-common:  [43] ./src/SingleLineInput/index.jsx 6.42 KiB {0} [built]`
`@dnnsoftware/dnn-react-common:  [44] ./src/SearchBox/index.jsx 6.93 KiB {0} [built]`
`@dnnsoftware/dnn-react-common: [181] ./src/index.js 2.7 KiB {0} [built]`
`@dnnsoftware/dnn-react-common:     + 648 hidden modules`
`@dnnsoftware/dnn-react-common: WARNING in ./src/Sortable/index.jsx`
`@dnnsoftware/dnn-react-common: Module Warning (from E:/DevDnn/node_modules/eslint-loader/dist/cjs.js):`
`@dnnsoftware/dnn-react-common: E:\DevDnn\Dnn.AdminExperience\ClientSide\Dnn.React.Common\src\Sortable\index.jsx`
`@dnnsoftware/dnn-react-common:    74:26  warning  Expected '===' and instead saw '=='  eqeqeq`
`@dnnsoftware/dnn-react-common:   129:51  warning  Expected '===' and instead saw '=='  eqeqeq`
`@dnnsoftware/dnn-react-common:   130:53  warning  Expected '===' and instead saw '=='  eqeqeq`
`@dnnsoftware/dnn-react-common:   142:41  warning  Expected '===' and instead saw '=='  eqeqeq`
`@dnnsoftware/dnn-react-common:   164:35  warning  Expected '===' and instead saw '=='  eqeqeq`
`@dnnsoftware/dnn-react-common:   169:42  warning  Expected '===' and instead saw '=='  eqeqeq`
`@dnnsoftware/dnn-react-common:   192:46  warning  Expected '!==' and instead saw '!='  eqeqeq`
`@dnnsoftware/dnn-react-common:   192:67  warning  Expected '===' and instead saw '=='  eqeqeq`
`@dnnsoftware/dnn-react-common:   192:99  warning  Expected '===' and instead saw '=='  eqeqeq`
`@dnnsoftware/dnn-react-common:   221:29  warning  Expected '!==' and instead saw '!='  eqeqeq`
`@dnnsoftware/dnn-react-common: ✖ 10 problems (0 errors, 10 warnings)`
`@dnnsoftware/dnn-react-common:  @ ./src/index.js 41:0-34 50:0-683`
`@dnnsoftware/dnn-react-common: ERROR in E:/DevDnn/node_modules/react-widgets/lib/SlideDownTransition.js`
`@dnnsoftware/dnn-react-common: Module not found: Error: Can't resolve 'react-transition-group/Transition' in 'E:\DevDnn\node_modules\react-widgets\lib'`
`@dnnsoftware/dnn-react-common:  @ E:/DevDnn/node_modules/react-widgets/lib/SlideDownTransition.js 20:42-86`
`@dnnsoftware/dnn-react-common:  @ E:/DevDnn/node_modules/react-widgets/lib/Popup.js`
`@dnnsoftware/dnn-react-common:  @ E:/DevDnn/node_modules/react-widgets/lib/Combobox.js`
`@dnnsoftware/dnn-react-common:  @ ./src/PermissionGrid/Suggestion/index.jsx`
`@dnnsoftware/dnn-react-common:  @ ./src/PermissionGrid/GridCaption.jsx`
`@dnnsoftware/dnn-react-common:  @ ./src/PermissionGrid/Grid.jsx`
`@dnnsoftware/dnn-react-common:  @ ./src/PermissionGrid/index.jsx`
`@dnnsoftware/dnn-react-common:  @ ./src/index.js`
`lerna ERR! yarn run build exited 1 in '@dnnsoftware/dnn-react-common'`
`PS E:\DevDnn>`

![RunBuild](https://user-images.githubusercontent.com/9780304/179658549-e5e2d9c7-73df-4913-a1f1-c5e6e898a0aa.png)

**Comment by mnouraei** [comment]
I found the problem.
This error occurred because the module `react-transition-group` was not installed
