### ISSUE TITLE
HTML Editor - Cannot Switch Between Preview and Edit Mode

### ISSUE THREAD

**Issue by josey-baker** [dnnsoftware/Dnn.Platform#5192]
In a fresh install of DNN 9.10.02 you cannot switch between the preview and edit mode in the HTML module.

Navigate to any HTML module and Edit Content.
In the modal that opens, select the Preview button in the footer.
Select the Edit button in the footer.
The HTML editor is not gone.  The Preview and Version History buttons still work but you cannot get back into Edit mode.

![html editor](https://user-images.githubusercontent.com/12897321/179784229-a2c03e1e-e8cc-4c5a-a2e4-5ef56ebf6185.JPG)

The only console errors I see are:
ckeditor.js:21 [CKEDITOR] Error code: exportpdf-no-token-url.

I tried to fix this in the config.js file but it does not go away.
If I inspect the HTML it seems the HTML for the editor never gets put back in.

**Comment by valadas** [comment]
I cannot reproduce this issue. Do you maybe have some custom editor plugins relating to pdf creation ?

**Comment by josey-baker** [comment]
No, it was a fresh install using nvQuickSite.  I just tested on 9.11 and the issue seems to be fixed.  You can close as we are upgrading everyone to 9.11.
