### ISSUE TITLE
Null throwing a error on PurgeDeletedUsers

### ISSUE THREAD

**Issue by leedavi** [dnnsoftware/Dnn.Platform#5196]
I don't have a full test system setup.  I only have the symbols,  The scheduler seems to throw an error that is not reported.

![Screenshot 2022-07-21 134327](https://user-images.githubusercontent.com/5583141/180209376-bb018aca-6326-4e91-8931-679ffd21ed2e.png)

![Screenshot 2022-07-21 134304](https://user-images.githubusercontent.com/5583141/180209451-a45a72df-7ead-4405-82ea-839295ab99b0.png)

![Screenshot 2022-07-21 134242](https://user-images.githubusercontent.com/5583141/180209495-9eed1c99-d85c-4a89-b442-4fb0f2120dd6.png)

![Screenshot 2022-07-21 134223](https://user-images.githubusercontent.com/5583141/180209531-9c8c508f-f4e1-4d0b-b5ad-d8fd519c03e8.png)

Maybe the null returned could be an issue on the return test.  But like I said, I don't have a full test system.  I'm not sure if anyone has reported a problem with purging users, I've not seen a problem.  I just wanted to report this, in case it is a problem for someone.

**Comment by valadas** [comment]
It is not failing here for me and on multiple running sites. I am guessing something might be wrong on that specific instance that returns a null... If you find out more details that may help a resolution, please comment those details and I'll reopen the issue.
