### ISSUE TITLE
Cookie Consent Customization 

### ISSUE THREAD

**Issue by jncraig** [dnnsoftware/Dnn.Platform#5210]
## Description of problem
Cookie Consent customization is stored in GlobalResources.resx.  This has several problems.

1. There is only one customization per installation, not per site.
2. If a DNN upgrade replaces GlobalResources.resx, customisation is lost.

## Description of solution
Cookie Consent needs to have site specific settings, like some of the language resx files.  It should also handle localization.

## Description of alternatives considered
Provide a clear and concise description of any alternative solutions considered.

## Screenshots
If applicable, provide screenshots to help explain the problem and/or enhancement.

## Additional context
Add any other context about the enhancement that may be helpful with implementation.

## Affected browser

* [ ] Chrome
* [ ] Firefox
* [ ] Safari
* [ ] Internet Explorer
* [ ] Edge

**Comment by bdukes** [comment]
The localization system always supports overriding per portal. When in the language editor, at the top there's a _Mode_ set of radio buttons to select whether to edit at the _Global_ level (which, as you note, will be overridden by upgrades and shouldn't really be supported at all), at the _Host_ level, or at the site level. Does switching to the site mode resolve your issue, or is there something that makes that not work as expected?

**Comment by jncraig** [comment]
Thank you, Brian!

I guess I should have actually dug into this a bit before creating this issue.  It was a "friend of a friend" report, and I really didn't dig into it.  I glad to have folks like you around to protect me from myself.
