### ISSUE TITLE
Resource Manager Installer Deploys Un-Needed Files

### ISSUE THREAD

**Issue by mitchelsellers** [dnnsoftware/Dnn.Platform#5227]
## Description of bug
The Resource Manager module when installed includes three web.config files within the working directory of the solution..

* Web.config
* Web.Debug.Config
* Web.Release.Config

These files are un-necessary on a production environment, at a minimum the second two should not be included in the sites.

## Steps to reproduce
List the precise steps to reproduce the bug:
1. Install Resource Manager
2. Look at the /DesktopModules/ResourceManager folder

## Current behavior
Files are included

## Expected behavior
Files should not be.

## Affected version

* [ ] 10.00.00 alpha build
* [ X ] 09.10.02 release candidate
* [ ] 09.10.01 latest supported release

**Comment by valadas** [comment]
Yeah, the 3 of them can be skipped... Good catch

**Comment by valadas** [comment]
This is fine with the new one, closing
