### ISSUE TITLE
Can't change HTML Editor settings due to jQueryUI

### ISSUE THREAD

**Issue by valadas** [dnnsoftware/Dnn.Platform#5246]
## Description of bug
Can't change HTML Editor settings due to jQueryUI

## Steps to reproduce
List the precise steps to reproduce the bug:
1. Go to site settings
2. Go to more settings
3. Open HTML Editor manager

## Screenshots
![image](https://user-images.githubusercontent.com/6371568/187811062-4825b057-6487-4de7-979a-2ad2c044b5cf.png)

## Error information
jquery-ui.js was renamed during some upgrade to jquery-ui.min.js

## Additional context
I believe it would be safe to keep the .min.js and the .js files around to prevent such issues in other places.
I'll take a look at this now...

## Affected versions
* [ ] 10.00.00 alpha build
* [x] 09.11.00 release candidate
* [ ] 09.10.02 latest supported release

**Comment by david-poindexter** [comment]
Good find!

**Comment by valadas** [comment]
This was already fixed but on develop only, I just updated release/9.11.0 with it and retesting now, but should be fine...
