### ISSUE TITLE
Resource manager not showing up in rc0001 (dutch)

### ISSUE THREAD

**Issue by trouble2** [dnnsoftware/Dnn.Platform#5250]
## Description of bug
Resource manager missing some file
GET http://dnn9110rc0001/DesktopModules/ResourceManager/Scripts/dnn-resource-manager/dnn-resource-manager.esm.js?cdv=39 net::ERR_ABORTED 404 (Not Found)

## Steps to reproduce
1) Go to the file manager page (either portal, or host files)
2) Resource manager is not showing up
3) look in dev. tool (F12) and see that it gives a 404 on the mentioned file.

## Screenshots
![image](https://user-images.githubusercontent.com/1827559/187872230-779f04d3-4af8-41b8-9446-f04c9f0f1cb3.png)

## Affected version
9.11.0 rc0001
Using dutch version...

**Comment by bdukes** [comment]
Thanks for the report, I'm going to close this issue in favor of #5251, please follow that issue and report any additional details there.
