### ISSUE TITLE
DependencyHandler.axd may return wrong Content-Type (Resource Manager broken in 9.11.0 RC2)

### ISSUE THREAD

**Issue by BeniFreitag** [dnnsoftware/Dnn.Platform#5262]
## Description of bug
If _Client Resource Management_ is enabled (Compose files, minify CSS, minify JS), the new Resource Manager doesn't load. Some HTTP responses via DependencyHandler.axd have a wrong content-type, so the browser doesn't process the JavaScript/CSS.

## Steps to reproduce
1. Setup new DNN 9.11.0 RC2
2. Resource Manager (/Host/Global-Assets/portalid/0) will work
3. Enable _Client Resource Management_ (Compose files, minify CSS, minify JS)
4. Reload the page containing the Resource Manager.
5. Resource Manager is not shown anymore, browser console has error because of invalid Content-Type.

## Current behavior
Resource Manager is not shown anymore, once _Client Resource Management_ is enabled.
Some responses from DependencyHandler.axd have a wrong _Content-Type_ header (see screenshot). Browser-console has error:

`Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/css". Strict MIME type checking is enforced for module scripts per HTML spec.`

## Expected behavior
Resource Manager should be shown and work, also when _Client Resource Management_ is enabled.
Responses from DependencyHandler.axd must have the correct _Content-Type_ header, so browsers process the responses.

## Screenshots
![image](https://user-images.githubusercontent.com/6669093/188179415-beabaefa-1805-4784-a5ce-4adc5598e794.png)

## Error information

Request to GET /DependencyHandler.axd/3fbadd4c9a9a365925513c8fba5b61d5/39/p-f7e975c5.js (initiated via **script**-tag) returns http 200 with JavaScript code in the body, but with a wrong http header: Content-Type: **text/css**.

Error in Browser Console (Chrome 104):
`Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/css". Strict MIME type checking is enforced for module scripts per HTML spec.`

## Additional context
There are also other errors in the browser console, as soon as _Client Resource Management_ is enabled.

It affects new DNN Installation and also Upgrades from older DNN Version (e.g. 9.6.0)

## Affected version

* [x] 09.11.00 release candidate 2

## Affected browser

* [x] Chrome 104

**Comment by BeniFreitag** [comment]
It already breaks if _Enable Composite Files_ is checked, but _Minify CSS_ and _Minify JS_ unchecked.

**Comment by valadas** [comment]
Ok, please try https://github.com/dnnsoftware/Dnn.Platform/releases/tag/v9.11.0-rc3 it should be resolved in it. Thanks for the testing too!

**Comment by BeniFreitag** [comment]
Just tested Resource Manager successfully in RC4.

There's another warning in the browser console that [/Host/Global-Assets/portalid/pages-bundle.js.map](http://freitags2022-06.60.2sic.net/Host/Global-Assets/portalid/pages-bundle.js.map) is missing (http 404).

And there's an `Uncaught TypeError: r is not a function at c [export-bundle.js?cdv=169:381:347]` (http://freitags2022-06.60.2sic.net/DesktopModules/admin/Dnn.PersonaBar/scripts/exports/export-bundle.js?cdv=169). It seems to be from the page manager and occours when I just open the pages-management in PersonaBar.

The warning and error are there regardless whether Client Resource Management is enabled or not. So far I don't know if something is broken or if it's uncritical.

@valadas could you check these or should I create a new issue? Thank you for your commitment!

![image](https://user-images.githubusercontent.com/6669093/188596835-7f345ffb-3cd7-4c84-9ba1-d04b0e73cebf.png)

**Comment by valadas** [comment]
So for those .js.map things, they are not critical, there is some issue we need to look at at some point but:
1. .map files are to help troubleshooting issues with minified files (they map the minified stuff to the original source code)
2. They do not load unless you open devtools
3. They do not affect visitors

For the error with `r` this is one example where such map file would help as we would know where in the original (unmodified) code this happens. It's been there for a couple of versions, so it's not a 9.11.0 regression, and so far I did not find anything broken because of it.
