### ISSUE TITLE
Still an issue with the resourcemanager on 9.11.0 rc0003

### ISSUE THREAD

**Issue by trouble2** [dnnsoftware/Dnn.Platform#5265]
## Description of bug
Issue with the new resourcemanager on fresh install on 9.11.0 rc0003 (dutch)

## Steps to reproduce
Install and go to the host or site files

## Current behavior
Module not showing, F12 (developer tools) gives an error  seems like a wrong path...
it tries to load the scripts from http://desktopmodules/blablabla...

![image](https://user-images.githubusercontent.com/1827559/188390432-48beeee9-6c3b-4670-a246-f0348f4a670c.png)

## Expected behavior
Would like the resourcemanager to work :-)

## Affected version
* [x] 09.11.00 RC003 latest supported release

## Affected browser
all

**Comment by david-poindexter** [comment]
I have been able to reproduce this issue on a fresh install in a "normal" IIS environment (not a virtual directory).

**Comment by wbonekamp** [comment]
Did the RC4 upgraded and tried to install/repair the resourcemanager again but still no Resource Manager.
How can I get it back.

![image](https://user-images.githubusercontent.com/7567981/188580415-a1209691-8a67-40df-8e24-32e122784817.png)

**Comment by Plumifrons** [comment]
the RC4 didn't work for me either, but then I copied the DNNCE_ResourceManager_09.11.00_Install.zip from the RC4 and reinstalled it. Now it works

**Comment by wbonekamp** [comment]
thanx! did the trick

**Comment by valadas** [comment]
Oh, fyi, there are no upgrades from rc1 => rc2 etc. Basically it needs to be retested as it was the only 9.11.0 version existing...
