### ISSUE TITLE
RC4 RM upload API call does not respect virtual root.

### ISSUE THREAD

**Issue by donker** [dnnsoftware/Dnn.Platform#5271]
When using the new resource manager uploading a file results in a call to the absolute root of the site. This should be relative to the DNN installation.

![Screenshot 2022-09-06 at 09 01 34](https://user-images.githubusercontent.com/3319692/188568484-19b2aa12-483a-4d20-899f-d175fc34958c.png)

**Comment by valadas** [comment]
Good catch, this one has the relative path hardcode and needs to use ServicesFramework instead.

Just dumping the line here to take a better look (maybe tomorrow)...
https://github.com/dnnsoftware/Dnn.Platform/blob/636532726d9dda574abc1179a0d4df0bc574231e/DNN%20Platform/Modules/ResourceManager/ResourceManager.Web/src/components/dnn-rm-queued-file/dnn-rm-queued-file.tsx#L139

**Comment by Plumifrons** [comment]
I don't know if it has to do with this but not all files are uploaded.

<img width="1823" alt="image" src="https://user-images.githubusercontent.com/5980007/188636000-7a9a5f8e-3b99-41f9-8910-c99aea704ac0.png">

**Comment by valadas** [comment]
@Plumifrons it is probably not related. This issue is for when a site is not hosted on the root of the IIS site, like in https://www.mysite.com/dnn for the root.
Not sure what's up with http2 protocol error... It may have something to do with https which had maybe less testing done. Do you get any more information if you click the magnifying glass next to those errors ?
Also, which browser is that ?

**Comment by Plumifrons** [comment]
The magnifying glass only indicates Failed to load resource. Both on IE and Chrome. 14 files (70mb) of different sizes uploaded simultaneously. Some go well, others give the error message.

**Comment by Plumifrons** [comment]
Another thing the upload icon is not always visible. Only after a refresh of the page.

<img width="1037" alt="image" src="https://user-images.githubusercontent.com/5980007/188710507-6db99c57-5141-49b2-bb12-18fbe82ed416.png">

**Comment by valadas** [comment]
Should be resolved in RC5, please comment if you can still reproduce the issue and we'll be happy to reopen
https://github.com/dnnsoftware/Dnn.Platform/releases/tag/v9.11.0-rc5
