### ISSUE TITLE
Persona Bar 404 errors loading js.map files

### ISSUE THREAD

**Issue by lanthonyneville** [dnnsoftware/Dnn.Platform#5272]
## Description of bug
After installing v9.11.0-rc4, 404 errors logged in DNN event log for various js.map files

## Steps to reproduce
1. Log in as administrator user
2. Open a Persona Bar page, e.g. Extensions
3. Open Admin Logs
4. Note errors for Log Type: HTTP Error Code 404 Page Not Found, for example:

TabId:
PortalAlias:www.mysite.dev
OriginalUrl:/themes-bundle.js.map
Url:https://www.mysite.dev/themes-bundle.js.map
UserAgent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36 Edg/105.0.1343.27
HostAddress:127.0.0.1
HostName:127.0.0.1
Server Name: Laurence

## File requests failing with 404 (this may not be an exhaustive list)
- /extensions-bundle.js. 
- /extensions-bundle.js.map
- /adminLogs-bundle.js.map
- /themes-bundle.js.map

## Expected behavior
404 errors should not occur

## Affected version
[ X ] 09.11.00 release candidate 4

**Comment by valadas** [comment]
This one was present before 9.11.0. Not saying it is not valid, just that we are focusing right now on releasing 9.11.0 soon so will remove that part of the title.

.map files are used to help with troubleshooting and don't affect the site operation, need to look at the issue but just FYI that does not load unless you open up devtools, won't affect the site operation or affect users.

**Comment by valadas** [comment]
Fixed in #5488
