### ISSUE TITLE
File manager upload file issue (DNN 9.11 RC4)

### ISSUE THREAD

**Issue by wbonekamp** [dnnsoftware/Dnn.Platform#5275]
## Description of bug
I try to upload a file in the file manager (site assets) but the file isn't visible after the upload.
Can't find the file in the portal root so looks like it isn't uploaded at all.

## Steps to reproduce
List the precise steps to reproduce the bug:
1. Go to Site Assets
2. Click on folder
3. Upload a file
4. See error in console (screenshot below)

## Screenshots
![image](https://user-images.githubusercontent.com/7567981/188651805-9a27816d-198e-4a3f-8f6f-22b647d22b41.png)

## Affected version

* [ ] 09.11.00 (237) 

## Affected browser
all

**Comment by valadas** [comment]
Anything else special vs a normal install or hosting environment. Is this HTTP or https? Folder permissions are ok? Are you able to upload content from elsewhere like the HTML editor?

Sorry for all the questions, but need to find some clues. In this screenshot, which browser was it?

**Comment by valadas** [comment]
I was not able to make this one happen, any new details can help here...

**Comment by donker** [comment]
I am assuming this is the virtual root issue in RC4 which was fixed in RC5.
@wbonekamp Please resubmit if you have this issue again in RC5 or later.
