### ISSUE TITLE
Cannot open folders in new Resource Manager module via right-hand panel

### ISSUE THREAD

**Issue by lanthonyneville** [dnnsoftware/Dnn.Platform#5276]
## Description of bug
The new Resource Manager module shows files and folders in the right-hand panel. However folders cannot be opened via the right-hand panel. Clicking a folder (anywhere in the row) only marks it as selected with the radio button control in the left column. After that, there seems to be no way to open the folder (nothing appear in the toolbar above, also nothing in the right-click menu).

## Steps to reproduce
List the precise steps to reproduce the bug:
1. Go to the new Resource Manager module
2. Click a folder in the right-hand panel (anywhere in the row).
3. The folder is marked selected, not opened and no option appears to open the folder

## Expected behavior
There should be an intuitive way to open folders via the right-hand panel (as well as selecting them for editing). Only being able to navigate folders via the left-hand panel is restrictive. In the old Digital Asset Management (Telerik) module files and folders could be selected for edit operation by checking the checkbox, and opened by clicking the file/folder name - this was very intuitive.

## Screenshots
New Resource Manager module:
![image](https://user-images.githubusercontent.com/22200046/188654879-1c96083b-bc2a-42ea-a087-0811d4b0ce79.png)
Old Digital Asset Management (Telerik) module
![image](https://user-images.githubusercontent.com/22200046/188654692-a094a6be-046d-41b7-9a1b-4f8b041cffd1.png)

## Affected version
* [ X ] 09.11.00 release candidate 4

**Comment by valadas** [comment]
Would double-click to open work ? I can do that for the next RC...

**Comment by lanthonyneville** [comment]
> Would double-click to open work ? I can do that for the next RC...

Yes, that would work well I think

**Comment by valadas** [comment]
I took a look at this and to do this properly will require a bit more time than I have available for the 9.11.0 release. We'll keep this issue as an enhancement for another release, I'll remove the 9.11.0 part of the title and we can get back to this at a later time...
