### ISSUE TITLE
Bumpy road upgrading to DNN 9.11.00 RC0004

### ISSUE THREAD

**Issue by skarpik** [dnnsoftware/Dnn.Platform#5278]
## Description of bug
Provide a clear and concise description of the bug.

I started with a DNN 9.10.2 website with 2sxc v13.12.1 and Evotiva Backup v8.8.5.

Executed 

http://rcemeborv13rc.dnndev.me/install/install.aspx?mode=upgrade

Upgrade failed with multiple errors:

## Steps to reproduce
List the precise steps to reproduce the bug:

See above description

## Current behavior

See attached PDF

[DNN Upgrade - v9.11.00 RC0004pdf.pdf](https://github.com/dnnsoftware/Dnn.Platform/files/9501693/DNN.Upgrade.-.v9.11.00.RC0004pdf.pdf)

## Expected behavior
Provide a clear and concise description of the expected behavior.

## Screenshots
If applicable, provide screenshots to help explain the bug.

## Error information
Provide any error information (console errors, error logs, etc.) related to this bug.
Error Text (in case PDF is not readable)

Upgrading DNN
Current Assembly Version: 09.11.00
Current Database Version: 09.10.02
Upgrade Status Report
00:00:00.132 - Upgrading to Version: 09.11.00
00:00:00.147 - Executing Script:09.10.03.SqlDataProvider
Success
00:00:00.302 - Executing Script:09.11.00.SqlDataProvider
Success
00:00:00.445 - Application Upgrades : 09.10.03
Success
00:00:00.446 - Application Upgrades : 09.11.00
Success
00:00:00.447 - Cleaning Up Files: 09.10.03
Success
00:00:00.448 - Cleaning Up Files: 09.11.00
Success
00:00:00.449 - Updating Config Files: 09.10.03
Success
00:00:00.452 - Updating Config Files: 09.11.00
Success
00:00:00.489 - Performing General Upgrades
00:00:00.960 - Installing Package File AspNetMvc_5.2.61129.10_Install:
Error!
00:00:01.082 - Installing Package File AspNetWebApi_5.2.61129.10_Install:
Error!
00:00:01.124 - Installing Package File AspNetWebPages_3.0.61129.10_Install:
Error!
00:00:01.186 - Installing Package File MailKit_2.15.0.0_Install:
Error!
00:00:01.257 - Installing Package File DDRMenu_09.11.00_Install:
Error!
00:00:01.335 - Installing Package File MicrosoftGlobbing_5.0.20.51904_Install:
Error!
00:00:01.363 - Installing Package File WebFormsMvp_1.4.5.0_Install:
Error!
00:00:01.396 - Installing Package File Dnn.EditBar.UI_09.11.00_Install:
Error!
00:00:01.428 - Installing Package File Dnn.PersonaBar.UI_09.11.00_Install:
Error!
00:00:01.479 - Installing Package File DNNCE_AzureConnector_09.11.00_Install:
Error!
00:00:01.507 - Installing Package File DNNCE_Console_09.11.00_Install:
Error!
00:00:01.538 - Installing Package File DNNCE_CoreMessaging_09.11.00_Install:
Error!
00:00:01.574 - Installing Package File DNNCE_HTML_09.11.00_Install:
Error!
00:00:01.628 - Installing Package File DNNCE_HtmlEditorManager_09.11.00_Install:
Error!
00:00:01.658 - Installing Package File DNNCE_Journal_09.11.00_Install:
Error!
00:00:01.691 - Installing Package File DNNCE_MemberDirectory_09.11.00_Install:
Error!
00:00:01.723 - Installing Package File DNNCE_RazorHost_09.11.00_Install:
Error!
00:00:01.804 - Installing Package File DNNCE_ResourceManager_09.11.00_Install:
Error!
00:00:01.840 - Installing Package File DNNCE_SiteExportImport_09.11.00_Install:
Error!
00:00:01.895 - Installing Package File DNNCE_SocialGroups_09.11.00_Install:
Error!
00:00:01.930 - Installing Package File DNNCE_TelerikRemoval_09.11.00_Install:
Error!
00:00:01.967 - Installing Package File GoogleAnalyticsConnector_09.11.00_Install:
Error!
00:00:01.990 - Installing Package File GoogleTagManagerConnector_09.11.00_Install:
Error!
00:00:02.014 - Installing Package File Newtonsoft.Json_13.0.1.25517_Install:
Error!
00:00:02.038 - Installing Package File Skin_Xcillion_09.11.00_Install:
Error!
00:00:02.066 - Installing Package File Knockout_03.05.01_Install:
Error!
00:00:02.094 - Installing Package File AspNetClientCapabilityProvider_09.11.00_Install:
Error!
00:00:02.119 - Installing Package File DNN_SimpleWebFarmCachingProvider_09.11.00_Install:
Error!
00:00:02.162 - Installing Package File DNNCE_FolderProviders_09.11.00_Install:
Error!
00:00:02.196 - Installing Package File DNNConnect.CKEditorProvider_09.11.00_Install:
Error!
00:00:02.241 - Installing Package File Dnn.PersonaBar.Extensions_09.11.00_Install:
Error!
00:00:02.364 - Installing Package File jQueryMigrate_03.04.00_Install:
Error!
00:00:02.390 - Installing Package File jQueryUI_01.13.02_Install:
Error!
00:00:02.423 - Replacing Digital Assets Manager with the new Resource Manager:
Success
Checking Security Aspects
We have confirmed that you have removed Telerik, which makes your site ready for DNN 10.0.0.
Upgrade Complete
Click Here To Access Your Site
Server Error in '/' Application.
The process cannot access the file 'D:\Websites\rcemeBoRv13RC\Website\installBlocker.lock'because it is being used by another process.
Description:
An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where itoriginated in the code.
Exception Details:
System.IO.IOException: The process cannot access the file 'D:\Websites\rcemeBoRv13RC\Website\installBlocker.lock' because it is being used by anotherprocess.
Source Error:
An unhandled exception was generated during the execution of the current web request. Information regarding the origin andlocation of the exception can be identified using the exception stack trace below.
Stack Trace:
[IOException: The process cannot access the file 'D:\Websites\rcemeBoRv13RC\Website\installBlocker.lock' because it is being used by another process.]
System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath) +935
System.IO.File.InternalDelete(String path, Boolean checkHost) +14434145
DotNetNuke.Services.Installer.Blocker.InstallBlocker.<RegisterInstallEnd>b__4_0() +86
DotNetNuke.Common.Utilities.Internal.RetryableAction.TryIt() +373
DotNetNuke.Services.Installer.Blocker.InstallBlocker.RegisterInstallEnd() +186
DotNetNuke.Services.Install.Install.UpgradeApplication() +3476
DotNetNuke.Services.Install.Install.OnLoad(EventArgs e) +535
System.Web.UI.Control.LoadRecursive() +154
System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint) +4082
Version Information:
Microsoft .NET Framework Version:4.0.30319; ASP.NET Version:4.8.4494.0

## Additional context
Provide any additional context that may be helpful in understanding and/or resolving the bug.

## Affected version

* [ ] 10.00.00 alpha build
* [X] 09.11.00 release candidate
* [ ] 09.10.02 release candidate
* [ ] 09.10.01 latest supported release

## Affected browser

* [ ] Chrome
* [ ] Firefox
* [ ] Safari
* [ ] Internet Explorer 11
* [ ] Microsoft Edge (Classic)
* [X] Microsoft Edge Chromium

**Comment by david-poindexter** [comment]
@skarpik this is most likely related to #5266

**Comment by valadas** [comment]
Either that or some anti-virus or backup solution locking the lock file is my guess. A fix already came in for #5266 and we are working on a few more items and will release another RC to re-test... Will keep you posted.

**Comment by skarpik** [comment]
My website includes a custom app written using 2sxc v13 LTS. Do you think it would be helpful for me to attempt the upgrade on a test DNN website that just includes "out of the box" 2sxc components like Basic Content, image galleries, etc. and none of my custom 2sxc code?

As far as anti-virus, I am just using the default Microsoft Defender that comes with Windows 11 Pro. I have a feeling there is some sort of 2sxc connection here. My guess is that if try to upgrade a DNN v9.10.2 website with no 2sxc, that it will work fine. Maybe that is a test that I should try. That should largely eliminate any involvement of antivirus.

Or should I wait until the next RC?

**Comment by mitchelsellers** [comment]
This issue seems to be something different, are you sure that there is not an Evotia backup running, or any similar process?

**Comment by skarpik** [comment]
@mitchelsellers - I will re-trace my steps and make sure that nothing is confounding the situation.

**Comment by skarpik** [comment]
I did the upgrade again. This time I created the target website, rebooted and then attempted the upgrade. Same result as before.

Upgrading DNN
Current Assembly Version: 09.11.00
Current Database Version: 09.10.02


Upgrade Status Report
00:00:00.149 - Upgrading to Version: 09.11.00
00:00:00.162 -   Executing Script:09.10.03.SqlDataProvider Success
00:00:00.325 -   Executing Script:09.11.00.SqlDataProvider Success
00:00:00.432 -   Application Upgrades : 09.10.03 Success
00:00:00.433 -   Application Upgrades : 09.11.00 Success
00:00:00.435 -   Cleaning Up Files: 09.10.03 Success
00:00:00.436 -   Cleaning Up Files: 09.11.00 Success
00:00:00.437 -   Updating Config Files: 09.10.03 Success
00:00:00.441 -   Updating Config Files: 09.11.00 Success
00:00:00.483 - Performing General Upgrades
00:00:00.879 -   Installing Package File AspNetMvc_5.2.61129.10_Install:  Error!
00:00:01.005 -   Installing Package File AspNetWebApi_5.2.61129.10_Install:  Error!
00:00:01.039 -   Installing Package File AspNetWebPages_3.0.61129.10_Install:  Error!
00:00:01.103 -   Installing Package File MailKit_2.15.0.0_Install:  Error!
00:00:01.168 -   Installing Package File DDRMenu_09.11.00_Install:  Error!
00:00:01.271 -   Installing Package File MicrosoftGlobbing_5.0.20.51904_Install:  Error!
00:00:01.295 -   Installing Package File WebFormsMvp_1.4.5.0_Install:  Error!
00:00:01.330 -   Installing Package File Dnn.EditBar.UI_09.11.00_Install:  Error!
00:00:01.361 -   Installing Package File Dnn.PersonaBar.UI_09.11.00_Install:  Error!
00:00:01.409 -   Installing Package File DNNCE_AzureConnector_09.11.00_Install:  Error!
00:00:01.435 -   Installing Package File DNNCE_Console_09.11.00_Install:  Error!
00:00:01.461 -   Installing Package File DNNCE_CoreMessaging_09.11.00_Install:  Error!
00:00:01.490 -   Installing Package File DNNCE_HTML_09.11.00_Install:  Error!
00:00:01.551 -   Installing Package File DNNCE_HtmlEditorManager_09.11.00_Install:  Error!
00:00:01.580 -   Installing Package File DNNCE_Journal_09.11.00_Install:  Error!
00:00:01.613 -   Installing Package File DNNCE_MemberDirectory_09.11.00_Install:  Error!
00:00:01.642 -   Installing Package File DNNCE_RazorHost_09.11.00_Install:  Error!
00:00:01.728 -   Installing Package File DNNCE_ResourceManager_09.11.00_Install:  Error!
00:00:01.763 -   Installing Package File DNNCE_SiteExportImport_09.11.00_Install:  Error!
00:00:01.813 -   Installing Package File DNNCE_SocialGroups_09.11.00_Install:  Error!
00:00:01.847 -   Installing Package File DNNCE_TelerikRemoval_09.11.00_Install:  Error!
00:00:01.903 -   Installing Package File GoogleAnalyticsConnector_09.11.00_Install:  Error!
00:00:01.927 -   Installing Package File GoogleTagManagerConnector_09.11.00_Install:  Error!
00:00:01.951 -   Installing Package File Newtonsoft.Json_13.0.1.25517_Install:  Error!
00:00:01.975 -   Installing Package File Skin_Xcillion_09.11.00_Install:  Error!
00:00:02.004 -   Installing Package File Knockout_03.05.01_Install:  Error!
00:00:02.030 -   Installing Package File AspNetClientCapabilityProvider_09.11.00_Install:  Error!
00:00:02.057 -   Installing Package File DNN_SimpleWebFarmCachingProvider_09.11.00_Install:  Error!
00:00:02.088 -   Installing Package File DNNCE_FolderProviders_09.11.00_Install:  Error!
00:00:02.122 -   Installing Package File DNNConnect.CKEditorProvider_09.11.00_Install:  Error!
00:00:02.166 -   Installing Package File Dnn.PersonaBar.Extensions_09.11.00_Install:  Error!
00:00:02.310 -   Installing Package File jQueryMigrate_03.04.00_Install:  Error!
00:00:02.334 -   Installing Package File jQueryUI_01.13.02_Install:  Error!
00:00:02.364 -   Replacing Digital Assets Manager with the new Resource Manager:  Success

Checking Security Aspects
We have confirmed that you have removed Telerik, which makes your site ready for DNN 10.0.0.

Upgrade Complete


Click Here To Access Your Site


 

Server Error in '/' Application.
The process cannot access the file 'D:\Websites\rcemeborv13ltsrc4\Website\installBlocker.lock' because it is being used by another process.
Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code.

Exception Details: System.IO.IOException: The process cannot access the file 'D:\Websites\rcemeborv13ltsrc4\Website\installBlocker.lock' because it is being used by another process.

Source Error:

An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.

Stack Trace:


[IOException: The process cannot access the file 'D:\Websites\rcemeborv13ltsrc4\Website\installBlocker.lock' because it is being used by another process.]
   System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath) +935
   System.IO.File.InternalDelete(String path, Boolean checkHost) +14434145
   DotNetNuke.Services.Installer.Blocker.InstallBlocker.<RegisterInstallEnd>b__4_0() +86
   DotNetNuke.Common.Utilities.Internal.RetryableAction.TryIt() +373
   DotNetNuke.Services.Installer.Blocker.InstallBlocker.RegisterInstallEnd() +186
   DotNetNuke.Services.Install.Install.UpgradeApplication() +3476
   DotNetNuke.Services.Install.Install.OnLoad(EventArgs e) +535
   System.Web.UI.Control.LoadRecursive() +154
   System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint) +4082

**Comment by jasclar** [comment]
Are you using an AMD Ryzen processor? I have had some odd timing issues with file locks in software other than DNN.

**Comment by valadas** [comment]
Is it possible in IIS for that application pool that it is set to use more than one worker process?

![image](https://user-images.githubusercontent.com/6371568/189242225-482552f7-9fcc-4241-99fe-8a78c876fee2.png)

**Comment by skarpik** [comment]
@jasclar - no, the CPU is 11th Gen Intel(R) Core(TM) i7-11700KF @ 3.60GHz   3.60 GHz.

**Comment by skarpik** [comment]
@valadas - I go with the vanilla settings that nvQuickSite uses. Here's a screen shot:

![Process Model](https://user-images.githubusercontent.com/3846223/189265417-7514effc-5fac-4665-9807-48672d97f36f.jpg)

**Comment by skarpik** [comment]
Tomorrow I will create a brand new DNN 9.10.2 website. Install 2sxc v13.10.1 LTS with a couple of demo pages (text and image content, photo gallery). And then try the upgrade. That will take things back to something that anyone can create for themselves to see if they have the same problem. To keep things simple, I won't include Evotiva backup.

**Comment by mitchelsellers** [comment]
Can you also try using the wizard rather than silent upgrade.

**Comment by skarpik** [comment]
@mitchelsellers - My instincts were completely wrong on this one. I did an "out-of-the-box" install of DNN v9.10.2. Then installed Evotiva Backup v8.08.05 and the upgrade fails. Based upon this most recent test of mine, I'd say there is some sort of problem with Evotiva Backup and the DNN 9.11.00 RC0004 upgrade. 2sxc isn't involved at all.

**Comment by mitchelsellers** [comment]
@skarpik that was where I was leaning.  I don't know much about how that tool works as I don't use it, but I'm guessing they are keeping some sort of file system watcher to help with backups, and those catch a file that is written by the upgrade process.

I'd be curious if the wizard based installation process has the same issue.

**Comment by skarpik** [comment]
@mitchelsellers - I'm trying the Wizard approach and it is stuck on "Checking security aspects of this installation" (spinning wheel of death)

So there seems to be some sort of incompatibility between DNN 9.11.00 RC0004 and Evotiva Backup. Is this something that I should contact Evotiva about or is the DNN RC needing more attention first?

**Comment by mitchelsellers** [comment]
@skarpik It would be great if you could contact Evotiva about this one.  I'm not sure what would/could have changed as that lock concept has been around for a long time, so getting some input from them would be great.

**Comment by valadas** [comment]
Not sure if it fixes your issue, but I just published RC5 which resolves some unwanted dll removals. I have no reason to believe the fixed on RC5 solve this issue, but worth a try:

https://github.com/dnnsoftware/Dnn.Platform/releases/tag/v9.11.0-rc5

**Comment by skarpik** [comment]
Same problem with RC5. I've sent a report to Evotiva. Hopefully they can shed some light on the situation.

**Comment by skarpik** [comment]
To provide Evotiva with hopefully helpful information, I ran the upgrade twice - once with an "out-of-the-box" DNN v9.8.2 and once with Evotiva Backup installed and then sent the upgrade logs to Evotiva. 

Here are the log files in case they are help to anyone:

**Upgrade - no Evotiva Backup**
[DNN Upgrade Log - no Evotiva.pdf](https://github.com/dnnsoftware/Dnn.Platform/files/9541400/DNN.Upgrade.Log.-.no.Evotiva.pdf)

**Upgrade - with Evotiva Backup**
[DNN Upgrade Log - Evotiva installed.pdf](https://github.com/dnnsoftware/Dnn.Platform/files/9541401/DNN.Upgrade.Log.-.Evotiva.installed.pdf)

**Comment by skarpik** [comment]
Good news. Evotiva has reproduced the error and is working on a fix for it.

**Comment by valadas** [comment]
Closing as per last comment
