### ISSUE TITLE
[v9.11.0-rc5] Resource Manager dialogs not showing in many skins because backdrop has just z-index 1

### ISSUE THREAD

**Issue by BeniFreitag** [dnnsoftware/Dnn.Platform#5290]
## Description of bug
If a DNN skin has any DOM-element with a z-index 2 or higher, dialogs in the Resource Manager are not visible. The DNN-Modal Backdrop has a -z-index of 1, but it should have a z-index of 1000 or even higher.

## Steps to reproduce
1. Setup DNN 9.11.0 RC5
2. Adapt any Element in the DNN-Skin with a z-index greater than 1. E.g. apply this CSS-Rule: `#dnn_ContentPane { z-index: 11; }`
3. Open Resource Manager
4. Open any dialog (e.g. add folder)
5. The dialog is not visible and not usable

## Current behavior
Dialogs in the Resource Manager are not working.

## Expected behavior
Dialogs in the Resource Manager should be visible in common DNN skins.

## Screenshots
![image](https://user-images.githubusercontent.com/6669093/189676527-a5fe1659-97d0-40a6-9fc7-3aa3fcbfd978.png)

## Additional context
This affect lots of our DNN-skins. We use z-indexes between 1 and 100 for our own DOM-elements.

`<dnn-modal><div id="backdrop">` must have a z-index of 1000 to overlap all elements on the page.

[Bootstrap Modal](https://getbootstrap.com/docs/5.0/components/modal/#live-demo) and [Angular Material Dialog](https://material.angular.io/components/dialog/overview) use a z-index of 1000 or above for the backdrop. So 1000 is a common best practice.

The fix will be:
```css
:host .overlay
{
  z-index: 1000
}
```

## Affected version

* [x] 09.11.00 release candidate 5

## Affected browser

* [x] Chrome

**Comment by valadas** [comment]
Should be fixed in https://github.com/dnnsoftware/Dnn.Platform/releases/tag/v9.11.0-rc6 if you can test it out, feel free to open a new issue if you notice any other problems
