### ISSUE TITLE
Publish Personabar sourcemaps on sources.dnncommunity.org

### ISSUE THREAD

**Issue by iJungleboy** [dnnsoftware/Dnn.Platform#5301]
## Description of problem

When opening F12 in the browser, it will report a bunch of warnings that source maps are missing. This has 2 concerns:

1. Many confusing warnings filling up the screen
2. Impossible to debug issues on production (like the latest issue in RC 5/6 with the persona bar not working)

I assume this is done to keep the installation package small, but it will constantly cause challenges - especially since the persona bar is so critical. It mainly affects `export-bundle.js` and also other files. 

## Description of solution

In 2sxc we solved the problem as follows:

1. On dev-builds we include the source maps of course, just as expected
2. On production builds we publish the source maps to a special website
    1. for example, the sources would then be on `https://sources.2sxc.org/14.08.00/ng-edit/vendor.e0928a10b973aef7.js.map`
    2. for 2sxc we use a github repo which is published as a static site, but this could be anything
3. The build process ensures that on production builds, the source map will point to this file, so everything just magically works

2sxc has many separate source projects, but here's a link to one of these which adjusts the source maps no production: https://github.com/2sic/2sxc-ui/blob/master/projects/%242sxc/webpack.config.js

## Description of alternatives considered

* I don't think we want to include the maps in the distribution, because it makes the distribution larger
* I don't think we want to create more distributions, because if things break, it should be debuggable right away, and not require another install

## Affected browser
* [x] all

**Comment by mitchelsellers** [comment]
I think that including this can be helpful, but I would argue sending in the package is a better choice, given our infrastructure abilities/requirements as well as the user base that cannot always access the public internet

**Comment by bdukes** [comment]
Agreed, I don't have significant concerns about the size of the install/upgrade packages (though open to hearing details about others' concerns).

**Comment by valadas** [comment]
Yeah, the size is not a worry, just to be clear, they are supposed to be there, there is just a problem, they are not missing on purpose.

**Comment by valadas** [comment]
#5488 fixed the sourcemaps, they are local though. If there is any interest in putting them elsewhere, please comment and I'll reopen but I think this is good this way.

**Comment by iJungleboy** [comment]
@valadas just for scope: we removed the source maps in 2sxc because they made the ZIP ca. 4MB larger. That's why we moved all the sources to sources.2sxc.org and host them from there (as a git-repo/git pages on https://github.com/2sic/2sxc-sources), but there is some overhead in release management.

For us it was worth it, but I'll assume the priority isn't high enough here to make the changes. This is what we did

1. Special Webpack configuration
    1. On dev build the sources are local
    2. On production it adds the URL to the final location
2. Special build steps
    1. On dev leave as is
    2. On prod only bundle the real files (filter out the .map files)
    3. Push the repo with sources

**Comment by mitchelsellers** [comment]
We don't have a viable publish location to publish without distribution at this time.

**Comment by iJungleboy** [comment]
@mitchelsellers So 2sxc didn't have one either. We just did this:

1. New github repo
2. Activated github publishing features
3. Set domain sources.2sxc.org to github

That was all ;)

**Comment by mitchelsellers** [comment]
Given our installation base for DNN Platform my guess is that this rule - https://docs.github.com/en/site-policy/acceptable-use-policies/github-acceptable-use-policies#9-excessive-bandwidth-use would be an issue for us

**Comment by iJungleboy** [comment]
@mitchelsellers that should not be a problem. 

Sourcemaps are only loaded if F12 is on, so that's certainly less that 1 in 10'000 page views of the total installation base. Plus IMHO it's all behind a CDN, so I believe Github doesn't even feel the strain. 

And if for whatever reason it is, then a cheap hosting + a free CloudFlare should do the trick as well.
