### ISSUE TITLE
[v9.11.0-rc7] Make it possible to override 400px height of new Resource Manager module

### ISSUE THREAD

**Issue by lanthonyneville** [dnnsoftware/Dnn.Platform#5316]
## Description of problem
The new Resource Manager module height defaults to 400px. Users may want to increase the height to make more content available in the left/right panes. The height however is set using a "constructed stylesheet", which seems to make it not possible to override using regular CSS, e.g. in a theme or portal CSS file.

## Description of solution
EITHER make it possible to override container heightwith CSS file,
OR create a module setting to set height with

## Screenshots
![image](https://user-images.githubusercontent.com/22200046/192336978-4c74357c-c5e4-4af9-90e7-5a70fbafe36f.png)

**Comment by david-poindexter** [comment]
Closing in favor of duplicate #5361 

Thanks for reporting this @lanthonyneville
