### ISSUE TITLE
Ressource Manager: Limit Base Folder in Group Mode

### ISSUE THREAD

**Issue by sleupold** [dnnsoftware/Dnn.Platform#5318]
## Description of bug
When using new resource manager module (DNN 9.11.0 RC7) in Group Mode, the base folder in module settings is not taken into account for the folder selector above the list.

## Steps to reproduce
List the precise steps to reproduce the bug:
1. install module
2. place module on a child page for groups
3. in Settings specify a base folder
4. check the list of folders available

## Current behavior
lists all folders

## Expected behavior
should list child folders of [GroupdID] subfodler of specified base folder only

## Affected version

* [ ] 10.00.00 alpha build
* [X] 09.11.00 release candidate 7
* [ ] 09.10.02 release candidate
* [ ] 09.10.01 latest supported release

## Affected browser

* [ ] Chrome
* [ ] Firefox
* [ ] Safari
* [ ] Internet Explorer 11
* [ ] Microsoft Edge (Classic)
* [X] Microsoft Edge Chromium

**Comment by lanthonyneville** [comment]
I don't think this issue is limited to "group mode". I have a module instance on a page, and in the module settings Mode is set to Normal, and Home Folder is set to a sub-folder. The module displays the Site Root as the default folder.

**Comment by mortezakermani** [comment]
I see the same issue on my website. 

I upgraded my DNN

 from 9.10.2 to 9.11.00 and all the resource manager modules I've used within the pages stop working.

They show from root folders for administrators and a JavaScript error with empty module for anonymous users.

May you guys fix this issue soon as I've upgraded a production website?

![Untitled](https://user-images.githubusercontent.com/10972990/195614023-49095f70-292b-4d7c-b1eb-a588c5278871.png)

**Comment by valadas** [comment]
This as been fixed and will be released in 9.11.1 but it was done against another issue that duplicated this one

**Comment by mortezakermani** [comment]
I got DNN 9.11.1 RC earlier than it's formal release from @valadas and I noticed this issue still persists.

I installed DNN 9.11.1 on a local machine and I created a blank page. then I added Resource Manager module to this page and I set "Home Folder" to "Images" folder; I opened up this page as a anonymous user and I faced to a JavaScript error which you can see in attached picture. When I click on OK button, the modal window goes and If I click on Images folder then just module starts working and shows the folder content.

![11](https://user-images.githubusercontent.com/10972990/213913284-42773395-0bdd-4f2e-9909-da4b2663c185.PNG)

**Comment by sleupold** [comment]
did you sync the folder upfront (as admin or host) and adjust folder permission (in folder Edit dialog)?

**Comment by mortezakermani** [comment]
Yes @sleupold, I did it; and I am sure this issue exists.

**Comment by mortezakermani** [comment]
This issue persists in DNN v9.11.1-rc1.

Also, I can see "Copy URL" option when I select a file in Resource Manager.

**Comment by mitchelsellers** [comment]
@mortezakermani Just to make sure that I understand what you are trying.

1. You set the root folder to something other than the portal root
2. You set permissions on that folder to a limited set of access, even possibly "Registered Users"
3. You then made this module visible to ALL users

I do not believe this has ever been an intended use case for the Resource Manager?

**Comment by mortezakermani** [comment]
Yes, That's right.

I created a new tab and then I added a resource manager to this page. I set "Images" folder as "Home Folder" via module settings.


Although every one has view permission but module show a javascript error. pls see following screenshots.
![Capture](https://user-images.githubusercontent.com/10972990/216902058-a0403792-0567-442f-a9b9-886b47961203.PNG)
![Capture2](https://user-images.githubusercontent.com/10972990/216902063-4a1a4304-395d-479e-a767-90aa4d9ed735.PNG)

**Comment by mortezakermani** [comment]
Another issue of Resource Manager is that I can see "Copy Address" or "Copy URL" icon to obtain a file relative url when I click on a file.
![Capture3](https://user-images.githubusercontent.com/10972990/216902699-db11e520-01bd-41de-9b02-3dd7dee7c4d1.PNG)

**Comment by mitchelsellers** [comment]
@valadas can you confirm, I believe you MUST be at least logged in right?

**Comment by valadas** [comment]
Well, that is my assumption, I have never ever made this sort of module visible to all users (not logged in), what this a valid use case before this rewrite ?

**Comment by mortezakermani** [comment]
Thanks for your message @valadas,

The "Digital Assists Management" and old "Resource Manager" module both had this option to be used as a file viewer or simple document manager for anonymous users.

**Comment by Xand0r** [comment]
> Thanks for your message @valadas,
> 
> The "Digital Assists Management" and old "Resource Manager" modules both had this option to be used as a file viewer or simple document manager for anonymous users.

Yes. This is a use case that is now broken for me. I'm patiently waiting for the fix. 😅👍
