### ISSUE TITLE
[v9.11.0] Creating language pack failed

### ISSUE THREAD

**Issue by uzmannazari** [dnnsoftware/Dnn.Platform#5321]
Hi
I ran into a problem with version 9.11.00.
When we want to export a language pack or create a language pack, in the path of the Install/Language folder there is only a broken zip file with a size of 0 KB.

## Screenshots
![error](https://user-images.githubusercontent.com/52697118/193913605-fc9ea933-bbfd-4992-bf45-aa327e1f0e7a.PNG)

## Description of problem
AbsoluteURL:/API/PersonaBar/SiteSettings/CreateLanguagePack

DefaultDataProvider:DotNetNuke.Data.SqlDataProvider, DotNetNuke

ExceptionGUID:4a198918-4c55-4a66-b6ba-df94c04a4f0c

AssemblyVersion:

PortalId:-1

UserId:-1

TabId:-1

RawUrl:

Referrer:

UserAgent:

ExceptionHash:RZtXK2N4ELvbDovBleRLgMh08MQ=

Message:Central Directory corrupt.

StackTrace:

   at System.IO.Compression.ZipArchive.ReadEndOfCentralDirectory()
   at System.IO.Compression.ZipArchive.Init(Stream stream, ZipArchiveMode mode, Boolean leaveOpen)
   at DotNetNuke.Services.Installer.Writers.PackageWriterBase.CreateZipFile(String zipFileName)

InnerMessage:An attempt was made to move the file pointer before the beginning of the file.

InnerStackTrace:

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.SeekCore(Int64 offset, SeekOrigin origin)
   at System.IO.FileStream.Seek(Int64 offset, SeekOrigin origin)
   at System.IO.Compression.ZipArchive.ReadEndOfCentralDirectory()

Source:System.IO.Compression

FileName:

FileLineNumber:0

FileColumnNumber:0

Method:

Server Name: `srv68467`
## Affected version

* [ ] 10.00.00 alpha build
* [x] 09.11.00 release 
* [ ] 09.10.02 release

**Comment by uzmannazari** [comment]
How can this problem be solved? Does anyone have any comments?

**Comment by uzmannazari** [comment]
Hi @sleupold 
If didn't have permssion, he couldn't create even a 0 KB file!


> I just tested creating a core language file without issues. Did you ensure, the windows account used by ASP.Net has write permission for the target folder?

**Comment by sleupold** [comment]
my problem is, I can't reproduce.

**Comment by uzmannazari** [comment]
> I just tested creating a core language file without issues. Did you ensure, the windows account used by ASP.Net has write permission for the target folder?

Hi @sleupold
If didn't have permssion, he couldn't create even a 0 KB file!
![Uploading error.PNG…]()

**Comment by uzmannazari** [comment]
> 

I have also tested in another portal which used to work correctly in version 9.10.2

> my problem is, I can't reproduce.

I have also tested in another portal which used to work correctly in version 9.10.2

**Comment by sleupold** [comment]
did you make sure, the target folder is not empty?

**Comment by uzmannazari** [comment]
No there is not.

**Comment by sleupold** [comment]
the target folder should contain at least a placeholder.txt.

**Comment by uzmannazari** [comment]
@sleupold  Have you tested this with the installed version or the upgraded version?

**Comment by sleupold** [comment]
@uzmannazari I used an upgraded site

**Comment by uzmannazari** [comment]
> @uzmannazari I used an upgraded site

me too. but i cant understand what is the problem!

**Comment by dnnsmuggler** [comment]
Hi!
I have a site recently updated from DNN 9.10.2 to 9.11.0. This site has an english part and a localized swedish part.

I found your reported issue when I was looking for problems close to the problems I have seen. On my site I have problems with uploading files from both Global Assets and Site Assets.
Look  here: Cannot upload file using the Site Assets in the localized site #5345

I can reproduce the same problem in my site as you have reported. DNN reports in my site that the languagepack is created but only a file with the size 0kb is created. 
Apart from the languagepack file of 0kb I also got message in a logfile, as below:




AbsoluteURL:/sv-se/API/PersonaBar/SiteSettings/CreateLanguagePack

DefaultDataProvider:DotNetNuke.Data.SqlDataProvider, DotNetNuke

ExceptionGUID:9699359b-1b89-4e1f-8c78-eb427332910c

AssemblyVersion:

PortalId:-1

UserId:-1

TabId:-1

RawUrl:

Referrer:

UserAgent:

ExceptionHash:RZtXK2N4ELvbDovBleRLgMh08MQ=

Message:Central Directory corrupt.

StackTrace:

   at System.IO.Compression.ZipArchive.ReadEndOfCentralDirectory()
   at System.IO.Compression.ZipArchive.Init(Stream stream, ZipArchiveMode mode, Boolean leaveOpen)
   at DotNetNuke.Services.Installer.Writers.PackageWriterBase.CreateZipFile(String zipFileName)
InnerMessage:An attempt was made to move the file pointer before the beginning of the file.

InnerStackTrace:

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.SeekCore(Int64 offset, SeekOrigin origin)
   at System.IO.FileStream.Seek(Int64 offset, SeekOrigin origin)
   at System.IO.Compression.ZipArchive.ReadEndOfCentralDirectory()
Source:System.IO.Compression

FileName:

FileLineNumber:0

FileColumnNumber:0

Method:

Server Name: server_x1

//Peter

**Comment by avvweb** [comment]
I have a similar situation. On a fresh DNN 9.11.0 install, I cannot create a module package. I get this error:

**Comment by uzmannazari** [comment]
Can anyone figure out where the problem is?

**Comment by avvweb** [comment]
I've solved it by additionally editing the file FileSystemUtils.cs:

Add:

zipFile.CreateEntryFromFile(FixPath(filePath), Path.Combine(folder, fileName));

Comment:

//var entry = zipFile.CreateEntry(Path.Combine(folder, fileName));
                //entry.LastWriteTime = DateTime.Now;
                //using (var zipStream = entry.Open())
                //{
                //    fs.CopyToStream(zipStream, len);
                //}

                //fs.Close();

Compile and copy the DotNetNuke.dll file and it works like a charm!

**Comment by valadas** [comment]
That's nice but a pull request would be nicer

**Comment by avvweb** [comment]
I would gladly do that, but I don't know how. What branch or version to suggest. Maybe you can point me in the right direction?

**Comment by valadas** [comment]
We have plenty of documentation about building and submitting fixes right on the home of this repository, a good place to start is https://github.com/dnnsoftware/Dnn.Platform/blob/develop/CONTRIBUTING.md and if you get stuck on anything, we are here to help out.

**Comment by jasclar** [comment]
I have just encountered same issue when creating a module package on 9.11.0.
Is anyone handling the pull request?
(I'd do it but I don't have a dev environment at the moment)

**Comment by valadas** [comment]
@jasclar you need to understand that this is an open source project driven by volunteers. We know about the issue but it will only be handled if and when someone submits a pull request. I am not aware at the moment of anyone working on this, it is open for anyone to tackle.
