### ISSUE TITLE
Error When Trying to Insert an Image from the Server Via "Browse Server" on CE 9.11

### ISSUE THREAD

**Issue by salemkh** [dnnsoftware/Dnn.Platform#5325]
I have upgraded from 9.10.2 to 9.11 and when using the Editor and if I want to insert an image from the server I get this message

AbsoluteURL /Providers/HtmlEditorProviders/DNNConnect.CKE/Browser/Browser. 
AbsoluteURL:/Providers/HtmlEditorProviders/DNNConnect.CKE/Browser/Browser.aspx

DefaultDataProvider:DotNetNuke.Data.SqlDataProvider, DotNetNuke

ExceptionGUID:40246ed6-f275-4512-8a92-aac97147994c

AssemblyVersion:9.11.0

PortalId:12

UserId:1

TabId:1914

RawUrl:/Providers/HtmlEditorProviders/DNNConnect.CKE/Browser/Browser.aspx?Type=Image&amp;tabid=1914&amp;PortalID=12&amp;mid=8016&amp;ckid=txtTabContent&amp;mode=Portal&amp;lang=en-US&amp;CKEditor=dnn_ctr8016_EditContent_txtTabContent_txtTabContent&amp;CKEditorFuncNum

Referrer:http://mysite.com/mypage/ctl/EditContent/mid/8016/tci/-1

UserAgent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36

ExceptionHash:yZPrNxBaOiRNLOPC8YORUfP2PL4=

Message:A self closing tag cannot have child controls and/or content

StackTrace:

InnerMessage:A self closing tag cannot have child controls and/or content

InnerStackTrace:

   at DNNConnect.CKEditorProvider.Controls.HtmlGenericSelfClosing.get_Controls()
   at ClientDependency.Core.ControlExtensions.FlattenChildren(Control control)
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Linq.Enumerable.<ConcatIterator>d__59`1.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Linq.Enumerable.<ConcatIterator>d__59`1.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Linq.Enumerable.<ConcatIterator>d__59`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at ClientDependency.Core.Controls.ClientDependencyLoader.FindDependencies(Control control)
   at ClientDependency.Core.Controls.ClientDependencyLoader.RegisterClientDependencies(WebFormsFileRegistrationProvider provider, Control control, IEnumerable`1 paths)
   at ClientDependency.Core.Controls.ClientDependencyLoader.OnPreRender(EventArgs e)
   at DotNetNuke.Web.Client.ClientResourceManagement.ClientResourceLoader.OnPreRender(EventArgs e)
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
Source:

FileName:

FileLineNumber:0

FileColumnNumber:0

Method:

Server Name: MyServer

**Comment by skarpik** [comment]
I encountered the same problem. I tracked it down to a problem with the .ico file for the website.

If you leave the .ico file just as it comes out of the box, browsing to insert an image or link to a file works perfectly. If you change the .ico file from DNN.ico to anything else, the error that you report above appears. I have no idea why changing the .ico file causes any troubles.

**Comment by salemkh** [comment]
Thanks Steve for the feedback, I realize on one of the other portals (on the same installation) the issues does not exist, let me check the size and properties of ico file on the working portal and do some testing and will revert back soonest!
Thanks again

**Comment by skarpik** [comment]
I am curious whether the .ico file has been assigned for the portal that still works properly.

Here's an odd fact: if I assign the .ico file to a specific favicon file in the "Site Settings" control panel, the ability to browse the server is broken. If I try to reverse things by undoing the assignment (i.e. set the file to none in the "Site Settings" control panel, the server browsing is still broken. That makes no sense at all to me. I was expecting that it would work and the webserver would use whatever was in the favicon.ico file in the root folder of the website. Something seems to get messed up when one assigns the .ico file and it is not easily reversed.

**Comment by skarpik** [comment]
I tried your solution and it did not work. I must be doing something wrong. I will investigate more tomorrow...

**Comment by salemkh** [comment]
hmm, I used the resource manager to upload the ico file to the subfolder, made sure the ico is in a subfolder of the portal root.  Cleared the cache and restarted the app.

**Comment by skarpik** [comment]
Did you use the "Site Settings" control panel to point at the .ico file? Or did you depend on the webserver finding it?

**Comment by salemkh** [comment]
After uploading by the ico file by resource manager, i used the site settings to select the file from the subfolder  from browser file system 
![image](https://user-images.githubusercontent.com/25274446/195687209-ddf2d1f6-33ae-4f4e-bb4f-dc4c863d5f4f.png)
![image](https://user-images.githubusercontent.com/25274446/195687604-dee0e902-4ad2-41cc-a685-532a91f4d8b3.png)

**Comment by josey-baker** [comment]
It breaks because of the LoadFavIcon method in \Providers\HtmlEditorProviders\DNNConnect.CKE\Browser\Browser.aspx.cs
It checks if the following file exists and then tries to add it to the controls collection: File.Exists(Path.Combine(this.portalSettings.HomeDirectoryMapPath, "favicon.ico"))
So I think the workaround is to not have it in the portal root or not have it named favicon.ico.  
I have not been able to track down the breaking change yet.

**Comment by skamphuis** [comment]
I'm fixing a few other issues in CKE Provider this week anyway, so I'll see if I can fix this too. I guess that using FavIcon.GetHeaderLink() should do the trick.
