### ISSUE TITLE
Persona Bar > SEO > Sitemap priorities revert to 1

### ISSUE THREAD

**Issue by Timo-Breumelhof** [dnnsoftware/Dnn.Platform#5330]
## Description of bug
When editing the SEO settings, the minimum Sitemap priority settings revert 1 even after you saved another value.
I noticed this on an "nl-nl" site, it's not an issue on an "en-us" site.

## Steps to reproduce
List the precise steps to reproduce the bug:
1. Create a multi language site with en-us and "nl-nl" (I guess fr-fr or de-de will work the same)
2. Open the "nl-nl" home page
3. Open PB > SEO > Site map settings.
4. See that both drop-downs contain the value "1"
![image](https://user-images.githubusercontent.com/8999382/193582075-e1ed1644-53c4-496e-b633-5b207c571511.png)
5. Set these values to 0.1 and [SAVE]
6. Refresh the page 
7. The values are back to "1"

I tested the behavior and the saving works fine, but the wrong value is loaded when refreshing in the edit interface.
I guess due to the the difference between 0.1 and 0,1 over languages?

## Current behavior
Wrong values shown

## Expected behavior
When you save a 0.1 value, that should also be visible after a refresh.

## Affected version

* [ ] 10.00.00 alpha build
* [x] 09.11.00 latest supported release 
* [x] 09.10.02 release 
* [x] 09.10.01 release

**Comment by sleupold** [comment]
It could be an issue with decimal point (Comma in Dutch and most European languages)

**Comment by Timo-Breumelhof** [comment]
@sleupold yes it was see the commit by @skamphuis

**Comment by sleupold** [comment]
sorry, noticed immediately afterwards. 
Thanks a lot for your contribution!
