### ISSUE TITLE
Resource Manager not saving permission changes on root folder

### ISSUE THREAD

**Issue by deskpal** [dnnsoftware/Dnn.Platform#5335]
## Description of bug
The Resource Manager gives an error when trying to save permissions to the root folder.

## Steps to reproduce
1. Go to Site Assets
2. Right click on the root folder of the Resource Manager module
3. Change any of the folder permissions.
4. Try to save it
5. See a message that says the newFolderName cannot be empty

## Current behavior
Show a message that says the newFolderName cannot be empty

## Expected behavior
Save permission changes

## Screenshots
If applicable, provide screenshots to help explain the bug.

## Affected version
* [X] 09.11.00

**Comment by erw13n** [comment]
Root folder seems cannot update permission.
Got the same error message.

If `name` entered (ex: root) it will create so many folders & sub folders inside and move all files under root folder into the sub folders, took so long when saving it.
