### ISSUE TITLE
Cannot upload file using the Site Assets in the localized site

### ISSUE THREAD

**Issue by dnnsmuggler** [dnnsoftware/Dnn.Platform#5345]
## Description of bug
After updating a website from DNN version 9.10.2 to 9.11.0 we can not upload files using the Site Assets in the localized part of the site.

## Steps to reproduce
1. Update a website from DNN version 9.10.2 to 9.11.0. The site has one localized part in Swedish language and one part in English language.

2. Use the Site Assets and upload a file in the English part of the site, this works just fine. 

3. Use the Site Assets and try to upload a file in the localized Swedish part of the site. Then no file is uploaded and instead the message "Bad Request" is displayed in red colour.

4. In the logfile: website-directory\Portals\_default\Logs\2022.10.18.log.resources
we could then read the following:

2022-10-18 17:59:56,353 [server_x][Thread:43][ERROR] DotNetNuke.Web.InternalServices.FileUploadController - System.InvalidOperationException: Bad Request
   at DotNetNuke.Web.InternalServices.FileUploadController.UploadFile(Stream stream, Int32 portalId, UserInfo userInfo, String folder, String filter, String fileName, Boolean overwrite, Boolean isHostPortal, Boolean extract, String validationCode)

## Current behavior
It is not possible to upload a file using the Site Assets in the localized part of the site.

## Expected behavior
We do expect that it should be possible to upload a file also in the localized part of the site using the Site Assets.

## Screenshots
--

## Error information
As above

## Additional context
--

## Affected version
9.11.0 latest

## Affected browser
OS on the client is Windows 11
Edge Version 106.0.1370.47 (Officiell version) (64 bitar)
I have only tested this on Edge
OS on the server is Windows 2012 Standard

**Comment by sleupold** [comment]
Which module is installed on that admin page - old Digital Assets Manager or Ressource Manager?

**Comment by dnnsmuggler** [comment]
It is the new Resource Manager.
I have removed Telerik when updating to 9.11.0.

**Comment by sleupold** [comment]
did you check and re-save permission for the upload folder in the resource manager?

**Comment by dnnsmuggler** [comment]
Sebastian, I have tested this too but no change.
I did now see that the problem is bigger that I thought.

When uploading files using the Global Assets the files shall be stored on the path: ...\portals\_default\

When uploading files using the Local Assets the files shall be stored on the path: ...\portals\_0\

I tried to upload a file using the Global Assets in the localised part of the site. Then I got the error "Bad request" and no file was uploaded.

Next I tried to upload a file using the Global Assets in the English part of the site. Then I got the message "File uploaded" but the file could not be seen in the Global Assets. Instead I found the file was uploaded to the path: ...\portals\_0\  and it could be seen in the Site Assets.

//Peter

**Comment by dnnsmuggler** [comment]
**I have made some more tests to better understand and to clarify**

When uploading files using the "Global Assets", the files shall be stored on the path: ...\portals_default\ 
below called "Host root".

When uploading files using the "Local Assets", the files shall be stored on the path: ...\portals\0\
below called "Site root".
 
 
**I have tried to upload a file to Host root, using the Global Assets and had the follwing results:**

**In the localized part of site (swedish):**
The result was the text "Bad request". 
No file was uploaded, same text in the logfile as mentioned above.

**In the english part of site:**
The result was the text "File uploaded".
The file was uploaded but to the Site root instead of to Host root, nothing was found in the logfile regarding this.
 
 
**I have tried to upload a file to Site root, using the Site Assets and had the follwing results:**

**In the localized part of site (swedish):**
The result was the text "Bad request". 
No file was uploaded, same text in the logfile as mentioned above.

**In the english part of site:**
The result was the text "File uploaded".
The file was uploaded to the Site Root which is correct.

//Peter

**Comment by sleupold** [comment]
Thank you for your investigation and report!

**Comment by valadas** [comment]
I have just tried this with current codebase and could not reproduce the issue
@dnnsmuggler Can you try this build on a test instance to see if you can still make it happen... https://artprodwus21.artifacts.visualstudio.com/Ad394b248-b709-4c8a-9adc-6ed9de8c8163/9defc7c7-d48d-4a8b-9f46-fd11ba3c5aad/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL2RvdG5ldC9wcm9qZWN0SWQvOWRlZmM3YzctZDQ4ZC00YThiLTlmNDYtZmQxMWJhM2M1YWFkL2J1aWxkSWQvODU2MzgvYXJ0aWZhY3ROYW1lL0FydGlmYWN0czE1/content?format=zip

If you still have issues using that build, please comment again with more details and I'll re-open the issue...

**Comment by dnnsmuggler** [comment]
Hi Daniel,
Thanks for all your work!

Unfortunately I do not have a development setup/environment and a couple of weeks ago I did reinstall the backup of version 9.10.2. 

Can I still use the build you sent to me? 
If so, can you please descibe how i  shall use it?

Thanks!
Best regards,
Peter

**Comment by dnnsmuggler** [comment]
I did look in the zip file which you sent and found the directory "DNN_Platform_9.11.1-alpha0253_Upgrade.zip".

Can I use the and upgrade to version 9.11.2-alpha0253? If so, shall I the first upgrade to version 9.11.0 from my version 9.10.2?

/Peter

**Comment by valadas** [comment]
You can unzip the upgrade package over that instance and then visit the site, this will fire up the upgrade wizard. I would backup that site (even though it is a copy) just in case you would find something wrong with that upgrade, so you can redo it if needed... You don't need to upgrade to 9.11.0 first.

**Comment by dnnsmuggler** [comment]
Daniel,
I am sorry for the long delay.
I have now been able to upgrade from my installation with DNN 9.10.2 to the version 9.11.2-alpha0253.

The upgrade worked fine without issues. The result when trying to upload files is as follows:

**I have tried to upload a file to Host root, using the Global Assets and had the follwing results:**

**In the localized part of site (swedish):**
The result was the text "Bad request".
No file was uploaded, look in file log_1.txt for the result in the logfile.

**In the english part of site:**
The result was the text "File uploaded".
The file was uploaded to the Host root, all ok!

**I have tried to upload a file to Site root, using the Site Assets and had the follwing results:**

**In the localized part of site (swedish):**
The result was the text "Bad request".
No file was uploaded, look in file log_2.txt for the result in the logfile.

**In the english part of site:**
The result was the text "File uploaded".
The file was uploaded to the Site Root, all ok!

**I have also seen another problem:**
Site settings - Site behavior - More - Open Html Editor Manager:
The Html Editor Manager: tries to open and then I com back to the Site Settings again.
Look in file log_3.txt for the result in the logfile.

**Comment by valadas** [comment]
Can you put some snippets of those log files here ? Also, can you make this happen from scratch, cause I was not able to reproduce the issue, so wondering if there is more to setup a scenario to make it happen...

**Comment by dnnsmuggler** [comment]
Daniel,
I am sorry, I forgot the log-file-snippets. They are now supplied.

In the version 9.10.2 I could not see the problems I have described here. The problems came after upgradeing to 9.11.0 and also when after upgrading from 9.10.2. to 9.11.2-alpha0253.
[log_1.txt](https://github.com/dnnsoftware/Dnn.Platform/files/10529395/log_1.txt)
[log_2.txt](https://github.com/dnnsoftware/Dnn.Platform/files/10529396/log_2.txt)
[log_3.txt](https://github.com/dnnsoftware/Dnn.Platform/files/10529397/log_3.txt)

**Comment by dnnsmuggler** [comment]
To be clear, the version I am using now is the version 9.11.2-alpha0253

**Comment by mitchelsellers** [comment]
@dnnsmuggler Can you check this possibly with RC2 to see if this is still an issue.  We have not be able to recreate

**Comment by dnnsmuggler** [comment]
Mitchel and Daniel,
I have now also tried an upgrade from 9.10.2 to 9.11.1-rc3.
Unfortunately I am still not able to upload files in the Swedish part of the site to "Site Assets" or "Global Assets". Supplied is a logfile. When trying in the English part of the site it works perfectly.

I do not understand what can cause the problem.

If I can supply any information you would like, I am happy to assist!
/Peter

**Comment by dnnsmuggler** [comment]
[log_20230208.txt](https://github.com/dnnsoftware/Dnn.Platform/files/10684003/log_20230208.txt)

**Comment by valadas** [comment]
These logs have a lot of unrelated stuff, can you make this happen from scratch on a clean install and if so, give us the steps to reproduce this problem from 0

**Comment by dnnsmuggler** [comment]
I have not yet tried to set up a new site in a new install of DNN 9.11.1 where at least two languages are enabled, like in the site where I could not upload files to the site when the Swedish language was choosen.

But I have now upgraded seven differnt sites from version 9.10.2 to 9.11.1 without any problems.
These upgraded sites have only the swedish language enabled.

**Comment by valadas** [comment]
Ok, if you find any way to reproduce this, let us know and I can reopen...
