### ISSUE TITLE
Cannot delete too many files at once in new Resource Manager 

### ISSUE THREAD

**Issue by david-poindexter** [dnnsoftware/Dnn.Platform#5349]
## Description of bug
When attempting to delete many files in the new Resource Manager, the UI does not allow for scrollable content.

## Steps to reproduce
1. Go to 'Site Assets' or `Global Assets`.
2. Upload a lot of files into the 'Images' folder.
3. Select a significant number of the files and click `Delete`.
4. See UI problem in screenshot below.

## Current behavior
The content is too tall for the page and the buttons are no longer viewable.

## Expected behavior
Content should be scrollable within the modal and limited to a percentage of the view height, allowing room for buttons.

## Screenshots
![image](https://user-images.githubusercontent.com/4568451/197083823-aa4eb5cd-afb0-4e83-a9c5-b6b1fac31681.png)

## Error information
n/a

## Additional context
n/a

## Affected version
* [ ] 10.00.00 alpha build
* [x] 09.11.00 release candidate
* [ ] 09.10.02 release candidate
* [ ] 09.10.01 latest supported release

## Affected browser
* [x] Chrome
* [x] Firefox
* [x] Safari
* [x] Internet Explorer 11
* [x] Microsoft Edge (Classic)
* [x] Microsoft Edge Chromium

**Comment by jeremy-farrance** [comment]
Noticed this in the DNN Community Forums, related.

**Version 9.11 - vertical scroll in site assets changed**
https://dnncommunity.org/forums/aft/3171
