### ISSUE TITLE
Login Page not working

### ISSUE THREAD

**Issue by mikecy** [dnnsoftware/Dnn.Platform#5356]
## Description of bug
When redirected to login page you cannot login to the system.
From the same page if Login link pressed from the menu is pressed and a popup opens it works perfect..

## Steps to reproduce
List the precise steps to reproduce the bug:
1. Go to '/login'
2. Click on ' enter credentials and click on Login'
3. See error

## Affected version

* [ ] 10.00.00 alpha build
* [x] 09.11.00 release candidate
* [ ] 09.10.02 release candidate
* [ ] 09.10.01 latest supported release

## Affected browser

* [x] Chrome
* [x] Firefox
* [x] Safari
* [x] Internet Explorer 11
* [x] Microsoft Edge (Classic)
* [x] Microsoft Edge Chromium

**Comment by mikecy** [comment]
The error comes with custom theme..

**Comment by sleupold** [comment]
are you using DNN default user login module on the page?
would you mind to add details of the error message - from /portals/default/logs or event log.

**Comment by mikecy** [comment]
I am using Default DNN user login and the strange thing is that the log files from /portals/default/logs are empty.
also the event log is empty
![dnnError](https://user-images.githubusercontent.com/9496639/197687078-e7644e9b-2f50-4fa5-9d4f-e4257349510e.png)
I did a new compile theme with Chris Charmond Templates and i install it. After switching to this theme the in page login does not work. If i switch back to Xcillion it works. From the custom theme When you login from the popup it works..
Thanks..

**Comment by sleupold** [comment]
Do you mean, logs don't have an associated entry or are they completely empty?
The second would indicate a significant setup issue.

**Comment by mikecy** [comment]
Hi. No associated errors are generated in the in the folder for this event and also the weird thing is that on the event log it does not record login failed.
It's very strange.

**Comment by mikecy** [comment]
When you don't wrap the content page inside a div you get this error.
