### ISSUE TITLE
New Resource Manager Needs Setting(s) for Height and Some Way to also Control the Height via CSS

### ISSUE THREAD

**Issue by jeremy-farrance** [dnnsoftware/Dnn.Platform#5361]
## Description of problem
 
There is no way to set or adjust the height of the new resource manager. On sites with lots of folders and files and a large monitor to work on, this reduces productivity significantly. My case is a somewhat extreme example, but presents the issue succinctly. :)
 
I included a screenshot below of what it looks like on a vertical QHD monitor with the browser full screen. Even though there is plenty of screen real estate to expand, the module appears to have it's height fixed at just 400px. 
 
After a little investigating to see if I could fix this (the usual way?) with CSS, I was unable to come up with a way to set or override the elements height without having to (manually, each time the page loads) inspect and drill into the DNN Vertical Splitview (DNN Element). Because this element with this setting is a web component, the shadow (dom, root, scope?) prevents page or module level CSS from overriding the height.

Once you are drilled in the Inspector to the Vertical Splitview, you can apply this simple CSS fix:
```
.container dnn-vertical-splitview {
    height: 75vw !important;
}
```

## Description of solution
For the Resource Manager, I am hoping that this can become a setting that we can control as well as have a better default.
 
For the Vertical-Splitview component, I am hoping this gets added as both a CSS setting and an attribute.
 
In both cases, it seems most flexible and useful to allow people to set the "height:" to any valid CSS (e.g. "400px", "80vh", "64rem", or even a calc, "calc(32rem + 60vh").

## Description of alternatives considered
If a quick fix is needed because there is no time for a well-thought out solution, then at least simply update the default so that height is something like "calc(20rem + 40vh)". This will give it a minimum height and provide some expansion when its on a taller page.

## Screenshots
![image](https://user-images.githubusercontent.com/653301/198590698-8dfa8435-d2ac-46b3-aa76-86cd35b977ba.png)

## Additional context
This only applies to the newer Resource Manager introduced in DNN v9.11.00.

Affects all modern browsers.

**Comment by jeremy-farrance** [comment]
Me? More details? I prefer to call it OCD. :)

**Comment by valadas** [comment]
Done as part of the duplicate issue.
