### ISSUE TITLE
Request IP address not being handled correctly when using ARR (i.e. Azure App Service)

### ISSUE THREAD

**Issue by davidjrh** [dnnsoftware/Dnn.Platform#5371]
## Description of bug
When hosting a DNN website on a platform using a load balancer that forwards the requests with the header "X-Forwarded-For" (i.e. the ARR used by Azure App Service), the remote IP Address in the header comes in the format "WWW.XXX.YYY.ZZZ:Port". The current logic validates this header to a v4 IP Address and returns an empty string because the port is not correctly handled. 

This causes lot of DNN features based on the Remote IP Address not working properly, like: 
- storing the LastIPAddress field on Users table 
- use of "Security > Login IP Filters" feature
- storing the IP Address on the event log properties on some type of requests
- and many more locations where the ```UserRequestIPAddressController.GetUserRequestIPAddress``` method is used (counting 23 references on the DNN Platform solution)

## Steps to reproduce
1. Install a DNN Platform website on Azure App service
2. Login into the website
3. Explore the Users table
4. Note that the LastIPAddress field is empty

## Current behavior
Any functionality based on the ```UserRequestIPAddressController.GetUserRequestIPAddress``` method doesn't work because the function returns an empty string.

## Expected behavior
The method ```UserRequestIPAddressController.GetUserRequestIPAddress``` should return the IP address part.

## Additional context
Reproduced on any version of DNN Platform hosted on Azure App Service.

## Affected version
* [X] 10.00.00 alpha build
* [X] 09.11.00 release candidate
* [X] 09.10.02 release candidate
* [X] 09.10.01 latest supported release

**Comment by valadas** [comment]
Implemented in #5371
