### ISSUE TITLE
Resource Manager Module is not working correctly

### ISSUE THREAD

**Issue by D-a-v-e-h** [dnnsoftware/Dnn.Platform#5376]
Hello @all,

I upgraded my DNN website from **9.10.2 version to 9.11.0 version** and found that one of the module i.e. **Resource Manager** is not working correctly. I found that when I set the Home Folder from Resource Manager Settings, still showing the Site Root folder. Below are the screenshots:

First see the module in extension section:

![image](https://user-images.githubusercontent.com/47249061/200334498-d5b2bfa0-9a07-44a8-864d-a96fdd9cc6ac.png)

I set the Home folder to Infoskriv:

![image](https://user-images.githubusercontent.com/47249061/200334791-6d75c760-6ce5-4d92-bc00-f34a94d5f79b.png)

But when I saved it, still it is showing me Site Root Folder things instead of Infoskriv folder:

![image](https://user-images.githubusercontent.com/47249061/200335012-c54b6522-4ce7-401e-94ed-13fe7d16efa9.png)

Previously in older version of DNN, we were not faced this issue, but after upgrading DNN, we are getting this. Please help, so that we can resolve it ASAP as it belongs to security thing in website.

Thanks,

Shivam S

**Comment by david-poindexter** [comment]
This has been resolved via #5351
