### ISSUE TITLE
DNN v9.11 "forgets" SMTP password

### ISSUE THREAD

**Issue by skarpik** [dnnsoftware/Dnn.Platform#5391]
## Description of bug

In the Servers / SMTP server control panel, DNN "forgets" the SMTP password.

## Steps to reproduce
List the precise steps to reproduce the bug:

1. Start at the Servers / SMTP server control panel
2. Fill in correct information about the SMTP server (URL, port, etc.)
3. Select "Basic" authentication
4. Enter the SMTP username and password.
5. Click save and the "Test SMTP Settings" and **everything works perfectly**.

Log off or do some other stuff. Go back to the Servers / SMTP Server control panel.

1. Under the label, "SMTP Password", there will be a link "change" - **do not click on it**.
2. Click on "Test SMTP Settings" - **now you get an error message** (something about the SMTP configuration)
3. Now click on the "change" link and re-enter the password and then test again. Everything works perfect.

If you go away to do some other stuff and return to "Test SMTP Settings", you get the same error message about the SMTP conifguration.

## Current behavior
Explain the current behavior.

I think that DNN is "forgetting" the SMTP server password.

## Expected behavior
Provide a clear and concise description of the expected behavior.

It looks like the SMTP Server password is not being properly stored.

## Screenshots
If applicable, provide screenshots to help explain the bug.

Nothing interesting to see.

## Error information
Provide any error information (console errors, error logs, etc.) related to this bug.

**The error message suggests a SPAM filter. I do not believe that because if I re-enter the SMTP password, everything works again.**

AbsoluteURL:/API/PersonaBar/ServerSettingsSmtpHost/SendTestEmail
DefaultDataProvider:DotNetNuke.Data.SqlDataProvider, DotNetNuke
ExceptionGUID:be06e929-cc34-4cae-a350-c5792b2deaeb
AssemblyVersion:
PortalId:-1
UserId:-1
TabId:-1
RawUrl:
Referrer:
UserAgent:
ExceptionHash:XeM+9gaTul8GqBXJo45Q9k3uDfk=

Message:Transaction failed. The server response was: Sending address not accepted due to spam filter

StackTrace:
   at System.Net.Mail.MailCommand.CheckResponse(SmtpStatusCode statusCode, String response)
   at System.Net.Mail.MailCommand.Send(SmtpConnection conn, Byte[] command, MailAddress from, Boolean allowUnicode)
   at System.Net.Mail.SmtpTransport.SendMail(MailAddress sender, MailAddressCollection recipients, String deliveryNotify, Boolean allowUnicode, SmtpFailedRecipientException& exception)
   at System.Net.Mail.SmtpClient.Send(MailMessage message)
   at DotNetNuke.Services.Mail.CoreMailProvider.SendMail(MailInfo mailInfo, SmtpInfo smtpInfo)
InnerMessage:
InnerStackTrace:
Source:System
FileName:
FileLineNumber:0
FileColumnNumber:0
Method:
Server Name: OMEN2

## Additional context
Provide any additional context that may be helpful in understanding and/or resolving the bug.

Nothing useful

## Affected version

* [X] 09.11.00 latest supported release

## Affected browser

* [X] Chrome
* [X] Firefox
* [ ] Safari
* [ ] Internet Explorer 11
* [ ] Microsoft Edge (Classic)
* [X] Microsoft Edge Chromium

**Comment by tvatavuk** [comment]
Today, colleagues reported the same problem with incorrect SMTP configuration for every website updated to v9.11.0.

**Comment by Mike35538** [comment]
I've had trouble with DNN forgetting the SMTP password since v.9.06.01, still see it occasionally on 9.10.02, I haven't tried v9.11 yet. 

I have no idea why it happens but it is pretty random and happens between once every 1-2 months. I just go into server settings and re-add and save the smtp password. From what I can tell, when DNN "looses" the password, the password doesn't actually become NULL or change in the SMTPPassword SettingValue under HostSettings in the database, DNN just can't see it anymore until you re-save through the interface.

I wish I could provide more info. Typically happens using global smtp mode with basic authentication.

**Comment by valadas** [comment]
I was able to reproduce the issue on current codebase and have a clue on how to resolve it. I'll try to tackle that on our next open-source co-coding session next Saturday 7 PM https://discord.gg/m4RaJWd8
