### ISSUE TITLE
Adding SEO URL's to pages causes extra 'automatic' rows to be added to grid

### ISSUE THREAD

**Issue by mwigley-trilogy** [dnnsoftware/Dnn.Platform#5401]
## Description of bug

Whenever a URL is added using the 'pages => advanced => S.E.O.' dialog it addes duplicate copies of the existing 'Automatic' rows. Also, duplicate copies of 'Automatic' rows exist for each language that is enabled for the page regardless of any manually added URLs.

![image](https://user-images.githubusercontent.com/116310985/203433366-67e04bcb-bd3e-4242-8b9b-d5c37db6dd51.png)

## Steps to reproduce

Prerequisite:
Have the languages feature enabled and enable multiple languages for a non-home page:
![image](https://user-images.githubusercontent.com/116310985/203432024-e89d7129-c02b-41ac-b54c-144d4b1101b2.png)

1. Open the Pages -> Avanced -> SEO page for a non-home page
![image](https://user-images.githubusercontent.com/116310985/203430357-332d0d2c-7759-4b88-917a-13fdad3a8bdd.png)
2. Note the number of 'Automatic' URL's - there will be one per language.  This is the first issue - if multiple languages are enabled on the site you will see repeated indiscernable rows:
![image](https://user-images.githubusercontent.com/116310985/203432109-124f41ac-d7c6-40d5-83dc-a7a431c85b57.png)
3. Add a new URL
![image](https://user-images.githubusercontent.com/116310985/203430663-4c722141-1809-4627-ba8a-e957ab44ff84.png)

An extra version of the automatically generated URL appears:

![image](https://user-images.githubusercontent.com/116310985/203430773-20aa966b-cb5e-43c1-9629-b83c592dd5b4.png)

And new ones keep appearing as you add more SEO Urls:

![image](https://user-images.githubusercontent.com/116310985/203437173-25ffa439-a1ee-4c23-81aa-0c8c12fbb83a.png)

## Current behavior

1. Currently when there are multiple languages for a page, extra identical looking SEO URL rows are displayed for a page.

This appears to be because an 'automatic' page URL is generated for each language, and these are all displayed in the UI:
![image](https://user-images.githubusercontent.com/116310985/203432414-5fb1b103-dcd9-4654-8220-89b77153320d.png)

2. Currently when a new SEO URL is added existing rows get duplicated.

This appears to be because 'automatic' URL's are keyed by index, and this can cause issues in React:
C:\work\DNN\src\Dnn.Platform\Dnn.AdminExperience\ClientSide\Pages.Web\src\components\Seo\PageUrls\Table.jsx
![image](https://user-images.githubusercontent.com/116310985/203432679-a5826d92-cfe8-451a-894d-895e428e10a0.png)

## Expected behavior
1. Only one URL row should be displayed for each identical-looking 'automatic' SEO URL.
2. Adding new SEO URL's should not cause duplicate 'automatic' rows to appear in the UI

I have a fix for these issues, I'll put up a PR shortly.

## Affected version

* [X] 10.00.00 alpha build
* [X] 09.11.00 release candidate
* [X] 09.10.02 release candidate
* [X] 09.10.01 latest supported release

Reproducible in any version

## Affected browser
* [X] Chrome
* [X] Firefox
* [X] Safari
* [X] Internet Explorer 11
* [X] Microsoft Edge (Classic)
* [X] Microsoft Edge Chromium

Reproducible in any browser

**Comment by valadas** [comment]
This may explain how to reproduce #3097 thanks!

**Comment by mwigley-trilogy** [comment]
Oh cool, yeah similar issue. My fix will definitely fix at least some of the issues you came across in that ticket too!
