### ISSUE TITLE
Save hash CookieValue in AuthCookies

### ISSUE THREAD

**Issue by Mostafa-Moafi** [dnnsoftware/Dnn.Platform#5405]
In my opinion, saving hashed CookieValue in the AuthCookies table is better. 
Because no one with access database can not log in to the DNN portal. 

I can work on this issue.

**Comment by Mostafa-Moafi** [comment]
Please check this issue @valadas 
thanks

**Comment by mitchelsellers** [comment]
@Mostafa-Moafi or @valadas can one of you reach out to me directly regarding this issue?

**Comment by Mostafa-Moafi** [comment]
@mitchelsellers Can you say and help me?

**Comment by mitchelsellers** [comment]
Can you email me about this, with notes of the intended change

**Comment by valadas** [comment]
After some internal discussions, this change would have the potential to break many 3rd party solutions
