### ISSUE TITLE
CKEditor drag&drop files

### ISSUE THREAD

**Issue by FRMN-FRE** [dnnsoftware/Dnn.Platform#5415]
Drag&Drop files on the CKEditor provide an "Internal Server Error"
![image](https://user-images.githubusercontent.com/114243427/204884134-15991d95-90d8-4231-9652-d7c43d46b05f.png)

## Steps to reproduce
-Open an HTML Module
-Drag&drop a picture on it
- the image is well uploaded on the good folder but an issue stop the process to import it on the editor.

## Error information
![image](https://user-images.githubusercontent.com/114243427/204884960-ab5eb1d2-1b14-40e9-a32a-e5fa6a254d2c.png)

## Additional context
How to fix this bug
Modify the file D:\dnn\dnnsources\Dnn.Platform-9.11.0\DNN Platform\Providers\HtmlEditorProviders\DNNConnect.CKE\Browser\Browser.aspx.cs
Find the procedure UploadFile, replace the script by a json response.
private void UploadFile(HttpPostedFile file, string command)
...
```
               if (command == "EasyImageUpload")
                {
                    var fileUrl = string.Format(!MapUrl(uploadPhysicalPath).EndsWith("/") ? "{0}/{1}" : "{0}{1}", MapUrl(uploadPhysicalPath), fileName);
                    this.Response.ClearContent();
                    this.Response.ContentType = "application/json";
                    this.Response.Write($"{{\"default\": \"{fileUrl}\"}}");
                }
                else
                {
                    var fileUrl = string.Format(!MapUrl(uploadPhysicalPath).EndsWith("/") ? "{0}/{1}" : "{0}{1}", MapUrl(uploadPhysicalPath), fileName);
                    this.Response.ClearContent();
                    this.Response.ContentType = "application/json";
                    this.Response.Write($"{{\"uploaded\": 1, \"fileName\": \"{fileName}\", \"url\": \"{fileUrl}\"}}");
                    //this.Response.Write("<script type=\"text/javascript\">");
                    //this.Response.Write(this.GetJsUploadCode(fileName, MapUrl(uploadPhysicalPath)));
                    //this.Response.Write("</script>");
                }
                this.Response.End();
```

## Affected version
All DNN versions since introduction of DNNConnect.CKEditorProvider.dll which replace the DNNConnect.CKEditorProvider_01.00.04.zip extension.

**Comment by FRMN-FRE** [comment]
Hello @Timo-Breumelhof, the solution is on the issue [#5416](https://github.com/dnnsoftware/Dnn.Platform/pull/5416) then you have to recompile the DNNConnect.CKEditorProvider.dll file and put it on the bin folder

**Comment by Timo-Breumelhof** [comment]
@FRMN-FRE your fix might be released with DNN 09.11.01 (not 100% sure though). Thank you for this great PR :-)

**Comment by donker** [comment]
@FRMN-FRE Thanks for this. We can include this today. But you'll need to sign the CLA. It's the only thing holding up merging this in.

**Comment by Timo-Breumelhof** [comment]
Great :-)
