### ISSUE TITLE
Username does not allow backslashes

### ISSUE THREAD

**Issue by MaiklT** [dnnsoftware/Dnn.Platform#5422]
## Description of bug
In an intranet environment using AD Authentication it is necessary to create usernames having a backslash to separate the domain name from the login name, as "MYDOMAIN\MaiklT". When creating such a user using the Persona Bar interface an error appears (invalid username).

## Expected behavior
A backslash should be a valid character in a username.

## Workaround(s)
- Wait until the user logs in the Windows domain and navigates to the website, if the AD Provider has set the autocreate option the user will be created automatically. This is not optimal when the user should be assigned to a group _before_ he or she logs in for the first time.
- Create the user without the backslash (random password) and change the appropriate fields manually in the database (table aspnet_Users and Users). This requires clearing the cache.

## Affected version
* [X] 09.11.00
* [X] 09.10.02
* [X] 09.10.01

Afair this bug appeared with the Persona Bar, so all versions since 9.0.0 are affected.

## Affected browser
Not a browser issue,

**Comment by MaiklT** [comment]
Still an issue

**Comment by valadas** [comment]
Oh good catch @bdukes . @MaiklT I'll close this issue as this appears to be the solution. Feel free to comment if you still have issues after adding this to the web.config.

**Comment by MaiklT** [comment]
Thanks, yes that solves it. Would be nice to have a UI for that...
