### ISSUE TITLE
UrlControl issue: cannot upload for any role (Only works for admin/Superuser)

### ISSUE THREAD

**Issue by erw13n** [dnnsoftware/Dnn.Platform#5423]
## Description of bug
Upgraded to DNN 9.11
***Form & List module*** still using `UrlControl` on one of their field, and it seems there's an issue on field with type "URL".
It doesn't allow users who is not "Admin" or "Superuser" to Upload file.

This is not an issue with Form & List module, because the issue within `UrlControl`
It happen even if the User `Role` have "Browse, View & Write" permission to folder.
Whenever press "Upload New File" it throw error "You don't have permission to upload files to this site."
This is not happen for "Admin" or "Superuser"

After browsing through the source code, this line seems check if user has "ADD" permission on the folder
https://github.com/dnnsoftware/Dnn.Platform/blob/c7b04652d214bd40a8ee6c36f133f7054ae70017/DNN%20Platform/Library/UI/UserControls/URLControl.cs#L923
Don't know if this is the cause of the issue.
But somehow it always throw "You don't have permission to upload files to this site." on every folder, even if it was "My Folder"

I check table "Permission" and I don't see any PermissionKey "ADD" for SYSTEM_FOLDER, it only have "READ, WRITE & BROWSE"
![image](https://user-images.githubusercontent.com/792847/205655266-f8b19c1c-aead-44e8-a396-e4f7bb3552e1.png)

So whenever it call SP `GetFoldersByPermissions` it always return NULL, because there's no "ADD" permission.

## Steps to reproduce
1. Using "Form & List" module, create a new form
2. At least one field type set to "URL"
3. Set module permission "Create Record/ Submit Form" for certain role 
4. Set the same role to have "Browse, View & Write" permission to folder.
5. "Add new Record", and change Link Type to "File", change folder and press "Upload new file"
6. It throw "You don't have permission to upload files to this site." immediately

![image](https://user-images.githubusercontent.com/792847/205656988-616907cb-5d82-48d7-960a-be058f38b6fe.png)

**Comment by MaiklT** [comment]
This seems to be an issue of the UrlControl - I have the same behaviour in the Links and Documents module.

**Comment by skamphuis** [comment]
Found this too. Submitting a PR for it.

**Comment by skamphuis** [comment]
Also: 1[U bent niet bevoegd om bestanden te uploaden. in DNNCommunity/DNN.Documents](https://github.com/DNNCommunity/DNN.Documents/issues/21)
