### ISSUE TITLE
Remove "Settings" From Resource Manager Display for Users Without Permission

### ISSUE THREAD

**Issue by mitchelsellers** [dnnsoftware/Dnn.Platform#5437]
Per the below linked discussion, we need to stop the HTTP 401 errors that appear with the file manager whenever it is granted access for users that do not have access to add/edit folder types etc.

_Originally posted by @DNNMonster in https://github.com/dnnsoftware/Dnn.Platform/discussions/5436_

**Comment by DNNMonster** [comment]
I am testing in a non standard fashion by compiling the develop branch and installing the DNNCE_ResourceManager_09.11.00_Install module manually.  Test environment only. 

I believe I am still seeing an http 401.

When authenticated as a non admin and the RM in user mode, the dnn-rm-folder-mappings component is calling out to the GetAddFolderTypeUrl endpoint which returns a 401.  It's DnnAuthorize attribute access level is set to Admin so this make perfect sense.  

I think we may need to prevent this request from being made by non admins or find an alternate solution..??

https://github.com/dnnsoftware/Dnn.Platform/blob/295a0ecc28aa34a8c8455dc5d8c72a3dd700812d/DNN%20Platform/Modules/ResourceManager/ResourceManager.Web/src/components/dnn-rm-folder-mappings/dnn-rm-folder-mappings.tsx#L28
![RM_screenshot](https://user-images.githubusercontent.com/12777553/208582387-eeeabd67-9a8f-4d4f-b8b7-9d1d5cd0fc3c.png)

**Comment by valadas** [comment]
It was no longer calling that API when we tested during development. Did you pull develop branch after this PR got merged ?

**Comment by valadas** [comment]
There should now be a call to `CanManageFolderTypes` before that component even renders and it does not render and not call `GetAddFolderTypeUrl` if the user is not an admin or host.

**Comment by DNNMonster** [comment]
You are right...  I did a yarn build on the web folder and then I compiled the install.  I am now seeing it's glory. Doh.
