### ISSUE TITLE
GetPropertyValue("LastName") return null

### ISSUE THREAD

**Issue by Dicky-arch** [dnnsoftware/Dnn.Platform#5438]
Some users is unable access my website after logging in to our website. We are on 9.6.19.
I tried to access the property of user UserInfo.Profile.GetPropertyValue("LastName") by code. It returns null.
Some people have the same issue before. https://www.dnnsoftware.com/forums/threadid/266701/scope/posts/userinfoprofilegetpropertyvalue-returning-null-values
How could we fix this?

**Comment by mitchelsellers** [comment]
Do you hae the LastName field on the registration form?  Do you require a valid profile for login

**Comment by valadas** [comment]
I am closing this issue due to lack of response for more than 30 days and because it was only tested in 9.6.19 which is not a published version...
