### ISSUE TITLE
Add "new image formats" like webp to Allowable File Extension list

### ISSUE THREAD

**Issue by Timo-Breumelhof** [dnnsoftware/Dnn.Platform#5444]
## Description of problem
Currently a Host as to edit the "Allowable File Extension list" to b able to use newer image formats like webp.

## Description of solution
IMO we should facilitate these by default, by adding these extensions to the default list.
And add an entry in web.config

## Description of alternatives considered
None

## Screenshots
![image](https://user-images.githubusercontent.com/8999382/208113524-55240774-fd97-4ace-a186-b429cc4edb07.png)

Related to: #5360

**Comment by valadas** [comment]
Closing this one in favor of #5360 

I know they are not exactly the same but if we add webp support, we need to make it available everywhere including the web.config, multiple places in the UI, etc. 

#5365 implements part of this but not completely. I am closing this one as the pull request refers to the other "duplicate" issue...
