### ISSUE TITLE
Resource Manager - Error on root.

### ISSUE THREAD

**Issue by leedavi** [dnnsoftware/Dnn.Platform#5448]
## Description of bug
You are unable to apply any permissions to the root folder.  A warning apears that there is no newFolder name.

## Steps to reproduce
- Open resource Manager,
- Right click and edit root
- goto permissions
- add any permissiosn  and save.
 
## Expected behavior
Permissiosns should be able to be added to the root folder.

## Screenshots
![image](https://user-images.githubusercontent.com/5583141/208658186-dce865dd-076b-42ae-a6c7-cf319e4d57d1.png)

![image](https://user-images.githubusercontent.com/5583141/208658330-9ad6245c-ae84-4e50-a72b-76e80774598e.png)

## Affected version
* [ ?] 10.00.00 alpha build
* [X ] 09.11.00 release candidate

**Comment by DNNMonster** [comment]
This may be already documented #5335

**Comment by leedavi** [comment]
Ah... Thanks, I don't know how I missed that. :-)

[Closed as duplicate]
