### ISSUE TITLE
Resource Manager user directory child folders not accessible

### ISSUE THREAD

**Issue by DNNMonster** [dnnsoftware/Dnn.Platform#5449]
## Description of bug
As an authenticated non admin user with access to the RM you are able to upload a zip file.  If you include a directory in the zip file it will upload but you cannot access the files in it.

## Steps to reproduce
List the precise steps to reproduce the bug:
1. Go to a page with the RM module and it's settings enabled for user mode and the default directory set to the users directory.
2. As a non admin user upload a zip file with a directory of some type of image or just a .txt file.
3. Once uploaded you should see the newly created folder in the user's directory.
4. Click on the folder
5. There is no error but you cannot drill down into the folder to view it's contents.

## Current behavior
Use can upload zip files with folders with show in the RM but the user cannot access it's contents.

## Expected behavior
A user should be able to access the contents of their uploaded zip files which can include a child directory.

## Error information
No error.

## Additional context
I am assuming that allowing users to create folders in this fashion is acceptable but this may be wrong.

## Affected version

* [ ] 10.00.00 alpha build
* [X ] 09.11.00 release candidate
* [ ] 09.10.02 release candidate
* [ ] 09.10.01 latest supported release

## Affected browser

* [X ] Chrome
* [ ] Firefox
* [ ] Safari
* [ ] Internet Explorer 11
* [ ] Microsoft Edge (Classic)
* [ X] Microsoft Edge Chromium

**Comment by DNNMonster** [comment]
After looking a bit more I believe that the RM in user mode should be rendering the tree menu for non admin users.  The folder mapping gear icon would be host/admin only.   It is via the tree menu that users can drill down but if it is not visible they will probably click on the main display folder which doesn't do anything.  This issue may be irrelevant once the tree menu is restored to non admins.

**Comment by valadas** [comment]
> should be rendering the tree menu
This has been fixed but not yet released

> mapping gear icon would be host/admin only
Same, has been fixed but not yet released

The rest of this bug report needs to be tested against current codebase

**Comment by DNNMonster** [comment]
These are looking installation specific so this should be closed.  The GetFolders call is not returning folders for certain installations I am looking at.  I am not sure why yet but it is a non issue for everyone else.  The default installation for DNN doesn't allow .zip files but when I enable it and check on a cleaner install and the updated RM it works as expected.
