### ISSUE TITLE
Resource Manager dont allow to upload files to manually created folders

### ISSUE THREAD

**Issue by ufoloko** [dnnsoftware/Dnn.Platform#5462]
I have installed 9.11 DNN version with Resource Manager Version 9.11 and after you create manually a folder and sync is not allowed to upload file into that new folder.

## Steps to reproduce
Create manually a subfolder in global assets, in skins folder for example. Sync that folder and you will see new folder, then try to upload files into that folder and you receive an error

## Current behavior
Resources manager dont allow to upload files

## Expected behavior
Resources Manager should allow to upload files in new sync folders

## Screenshots
<img width="418" alt="image" src="https://user-images.githubusercontent.com/1165122/210102576-5357e377-d43d-476c-bed9-e4b347922271.png">

* [X] 09.11.00 release candidate

## Affected browser

* [X ] Chrome
* [ X] Firefox
* [X ] Safari

**Comment by DNNMonster** [comment]
May be related to #5456

**Comment by valadas** [comment]
I tested this with current codebase and it appears to work. I know Brian send a fix for something else regarding folders and uploads some weeks ago that probably also fixed this. Keep an eye out for 9.11.1 RC to re-test this but should be good now.
