### ISSUE TITLE
Resource Manager Popup issue with long list

### ISSUE THREAD

**Issue by FRMN-FRE** [dnnsoftware/Dnn.Platform#5477]
## Description of bug
I want to move a file. The popup window is displayed. But if I try to open a folder with a lot of elements (like Users), the treeview is out of the window and bottom buttons are out

## Screenshots
When opening the popup all is OK
![2023-01-12_11h15_21](https://user-images.githubusercontent.com/114243427/212044663-3d517cd8-cb12-4ba6-a2cc-ac55d96434b3.png)

When the subfolder is too long,
![2023-01-12_11h15_40](https://user-images.githubusercontent.com/114243427/212044695-0ac82d1b-0580-4610-94f2-bb8057471608.png)

## Affected version
Tested only on 9.11.0

## Affected browser
All

**Comment by valadas** [comment]
It appears this has already been resolved in the current codebase, so it should be fixed with 9.11.1

![image](https://user-images.githubusercontent.com/6371568/212500003-57352bf6-44bf-465f-9c1d-fcf7ee6b7ffb.png)
