### ISSUE TITLE
HTML Editor - Can't browser server

### ISSUE THREAD

**Issue by dhassall** [dnnsoftware/Dnn.Platform#5478]
## Description of bug
I recentlly upgraded to 9.11.1 and performed the Telerik removal
When using the HTML Editor (or a module that includes hte HTML Editor - for me DataSprings Dynamic Forms) when you try to insert an image using the Browse Server option you get a "page view", I went back to a 9.8.1 install and all is fine.

## Steps to reproduce
1. HTML Editor - Edit Content
2. Select Image Icon
3. Choose Browse Server option

## Current behavior
Older versions of DNN use the previous Asset Manager
The popup window exhibits the following URL / Error https://MyDomain.com/Default.aspx?tabid=347&error=A+self+closing+tag+cannot+have+child+controls+and%2for+content

## Work around
If you choose the Source button you can enter the HTML content e.g. (left arrow)img alt="smiley" src="/Portals/_default/Smileys/smile.gif" style="height:23px; width:23px" title="smiley" /(right arrow) which is fine if you are a "developer" but a nightmare for clients who you have given editing rights to :-(

## Affected version
9.11.0

**Comment by sleupold** [comment]
- please note: DNN 9.11.1 has not been released yet, I assume, you are using DNN 9.11.0
- Ressource Manager module is a new file management module, accessible via PersonaBar. HRML Editors are using its own routines to access files. Please check for CKEditor issues, whether this has already been addressed for DNN 9.11.1 (I know, there had been some activity). Some 3rd party modules might use different HML editors.

**Comment by valadas** [comment]
This issue involves a third party module that is not open source. If you can submit some minimum reproducible scenario (some open source module) having the same issue, please comment back and I'll re-open this issue...

**Comment by dhassall** [comment]
Hi Daniel

Thanks for the feedback, I hadn't realised the HTML module wasn't part of DNN.

Do you know who has produced it so they can be made aware?

I will reach out to DataSprings as the HTML aspect of their module is affected, although I suspect it is "shared" code.

Thanks

Dave

**Comment by valadas** [comment]
Well, it's a bit more complex. The HTML module is a DNN module and it loads the configures HTML Editor Provider (the default being DNNConnect.CKEditorProvider), then it uses an editor component called CkEditor.

In all that only CkEditor is not in our source-code.
To add to this complexity, CkEditor will load up a file browser but because it can be used in multiple environments, the consumer of that component needs to provide that browser component for CkEditor to display. Dnn has one which is in this codebase.

Now each of these layers has configurations and in a custom module, there are ways to interact at any of these levels and there are a lot of possible configurations.
So for an issue like this we really need something very very clear to reproduce if we want to have any hopes of solving it. It may or may not be a problem in this codebase.

**Comment by dhassall** [comment]
Hi Daniel, thanks for the feedback. Give me a little time and I will provide a "side-by-side" of the process as was in an older version  and the same in 9.11.0

Dave

**Comment by dhassall** [comment]
Hi Daniel

The plot thickens, good for DNN but bad for me.

I was preparing the step by step process on 9.8.0 and 9.11.0 in parallel on what is "clean installs" (9.11.0 was upgraded from 9.9.0 with Telerik removal) both installed on my local PC.

To my surprise, pleasure, it works perfectly.

I then tried the same on my live, online installation which is at 9.11.0 and gone from a older version of DNN through to 9.11.0 with Telrik removal)

This DNN installation does have more than the standard set of Extensions so I now have the challenge of going through a process of installing a clean DNN 9.11.0 onto my online solution and repeating the test and possiblly doing a one by one install of my extensions.

Just to throw something else into the pot, on my online platform which has multiple Portals a small number of those refuse to open the HTML module. So it could come down to something as simple as a CSS or possible as Page Theme or Layout.

If I get to the bottom of this I will update this thread.

**Comment by valadas** [comment]
One possibility would be that you had custom HTML Editor plugins on that instance. CkEditor won't migrate those automatically and the old plugins might not work with the new version too. Sooo, you could try comparing the Providers\HtmlEditorProviders\DNNConnect.CKE\js\ckeditor\x.x.x\plugins folder for both (if you have more than one version where the x.x.x is in that path)...
