### ISSUE TITLE
Messaging Schedule Message Dispatch issue

### ISSUE THREAD

**Issue by amedhatreda** [dnnsoftware/Dnn.Platform#5492]
## Description of the bug
Too many messages did not get sent by the messaging schedule; it sometimes succeeded and many times failed!
This is a new bug starting to happen a month ago before it wasn't, we think it started to happen due to the huge size of the [CoreMessaging_MessageRecipients] table

## Steps to reproduce
No particular scenario to see the error, it is just we have too many records in the [CoreMessaging_MessageRecipients] table, the records count is more than 7 million records and it seems this affects the schedule performance.

## Current behavior
We have many not-sent messages in the [CoreMessaging_MessageRecipients] table, the schedule is running every 1 min but it fails too many times!

## Expected behavior
The schedule should run every 1 min and complete its job, sending the 50 messages, 50 is the batch size, updating their records in the database, and updating the schedule history, as it was done before.

## Screenshots
This is the error caught from the Admin Logs
![image](https://user-images.githubusercontent.com/20756524/213209107-c587afbd-397a-467a-aaeb-bb3d2de771a1.png)

## Error information
In the [ScheduleHistory] table, there are some different details, we found this error logged too many times
> <br>Messaging Scheduler Failed: System.Data.SqlClient.SqlException (0x80131904): Snapshot isolation transaction aborted due to update conflict. You cannot use snapshot isolation to access table 'dbo.CoreMessaging_MessageRecipients' directly or indirectly in database 'XXX' to update, delete, or insert the row that has been modified or deleted by another transaction. Retry the transaction or change the isolation level for the update/delete statement.     at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)     at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)     at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)     at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()     at System.Data.SqlClient.SqlDataReader.get_MetaData()     at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)     at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)     at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)     at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)     at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)     at DotNetNuke.Data.PetaPoco.PetaPocoExt.ExecuteReader(Database database, String sql, Object[] args)     at DotNetNuke.Data.PetaPoco.PetaPocoHelper.ExecuteReader(String connectionString, CommandType type, Int32 timeoutSec, String sql, Object[] args)     at DotNetNuke.Data.SqlDatabaseConnectionProvider.ExecuteReader(String connectionString, CommandType commandType, Int32 commandTimeout, String procedureName, Object[] commandParameters)     at DotNetNuke.Data.SqlDataProvider.ExecuteReader(String procedureName, Object[] commandParameters)     at DotNetNuke.Services.Social.Messaging.Data.DataService.GetNextMessagesForInstantDispatch(Guid schedulerInstance, Int32 batchSize)     at DotNetNuke.Services.Social.Messaging.Internal.InternalMessagingControllerImpl.GetNextMessagesForInstantDispatch(Guid schedulerInstance, Int32 batchSize)     at DotNetNuke.Services.Social.Messaging.Scheduler.CoreMessagingScheduler.HandleInstantMessages(Guid schedulerInstance)     at DotNetNuke.Services.Social.Messaging.Scheduler.CoreMessagingScheduler.DoWork()  ClientConnectionId:4b99fe8b-a371-4996-bd86-66403c0272c8  Error Number:3960,State:3,Class:16

## Additional context

- We use the default isolation level on our database and didn't change it
- By checking the SSMS > "Activity Monitor" > "Active Expensive Queries", we found some expensive queries related to this schedule's tables, here are the caught queries

`UPDATE TOP (@BatchSize) R
     SET   [EmailSchedulerInstance] = @SchedulerInstance,
           [LastModifiedOnDate]     = GetDate()
     FROM       dbo.[CoreMessaging_MessageRecipients] AS R 
     INNER JOIN dbo.[CoreMessaging_Messages]          AS M ON R.MessageID = M.MessageID
     LEFT  JOIN dbo.[CoreMessaging_UserPreferences]   AS P ON R.UserID    = P.UserID    AND M.PortalID = P.PortalID
     WHERE R.[EmailSent] = 0 AND R.[Read] = 0 AND R.[Archived] = 0 AND EmailSchedulerInstance IS NULL
       AND CASE 
            WHEN M.NotificationTypeID IS Null 
            THEN IsNull(P.[MessagesEmailFrequency],      0) -- direct mails are sent immediately by default
            ELSE IsNull(p.[NotificationsEmailFrequency], 2) -- notifications are sent as daily digest by default
           END = 0`

`SELECT M.[PortalID],
           M.[NotificationTypeID],
           M.[To],
           M.[From],
           M.[Subject],
           M.[Body],
           M.[SenderUserID],
           M.[ExpirationDate],
           M.[Context],
           R.[RecipientID],
           R.[MessageID],
           R.[EmailSent],
           R.[Read],
           R.[Archived],
           R.[EmailSchedulerInstance],
           R.[UserID],
		   R.[CreatedByUserID],
		   R.[CreatedOnDate],
		   R.[LastModifiedByUserID],
		   R.[LastModifiedOnDate],
		   R.[SendToast]
     FROM  dbo.[CoreMessaging_MessageRecipients] R
     JOIN  dbo.[CoreMessaging_Messages]          M ON R.MessageID = M.MessageID
     WHERE [EmailSent] = 0 -- Filter these columms 4 to use proper index
       AND [Read]      = 0
       AND [Archived]  = 0
       AND [EmailSchedulerInstance] = @SchedulerInstance
     ORDER BY --[PortalID],
              [UserID],
              [RecipientID]`

## Affected version
* [ ] 10.00.00 alpha build
* [ ] 09.11.00 release candidate
* [X] 09.10.02 release candidate
* [ ] 09.10.01 latest supported release

## Affected browser
* [X] Chrome
* [X] Firefox
* [X] Safari
* [X] Internet Explorer 11
* [X] Microsoft Edge (Classic)
* [X] Microsoft Edge Chromium

**Comment by mitchelsellers** [comment]
@amedhatreda are you using Evoq by chance?  

This article seems to outline the exact issue you are having - https://dnnsupport.dnnsoftware.com/hc/en-us/articles/360018622480-Core-Messaging-Scheduler-creating-errors-after-upgrade

This is the recommended solution if you are NOT on evoq, you can reopen this ticket, but the above should get you going.
