### ISSUE TITLE
Registration None causes unclear UI in Users module

### ISSUE THREAD

**Issue by valadas** [dnnsoftware/Dnn.Platform#5495]
## Description of bug
When user registration is set to none, the users module still has a "Add User" button, but clicking it causes an error in the browser console only. This is not a great UX and the "Add Users" button should probably just not be displayed at all.

**Comment by david-poindexter** [comment]
The purpose of `Registration = None` is to prevent anyone from being able to self-register on the site.  Site admins may still have the need to add users, even when self-registration is not possible.

**Comment by valadas** [comment]
Yeah, I was confused, my issue was something else fixed here https://github.com/dnnsoftware/Dnn.Platform/commit/520d8d2bf4ff88be6b78067e290ff19d3c88ac80

Closing
