### ISSUE TITLE
Fresh install 9.11: User Is Online always false

### ISSUE THREAD

**Issue by erw13n** [dnnsoftware/Dnn.Platform#5506]
## Description of bug
On a fresh installation of DNN 9.11 the status of "User is Online" always false at user page.
This is not happening when Upgrade DNN from 9.10

Also `UserInfo.Membership.IsOnLine` returning `False`

## Steps to reproduce
List the precise steps to reproduce the bug:
1. Fresh install DNN 9.11 (use nvQuickSite)
2. Login with multiple account
3. On Persona bar > Users
4. all users that sign-in, their online status is False

## Screenshots
On Fresh Install 9.11:
![image](https://user-images.githubusercontent.com/792847/215288574-6998cb30-dfbb-4c44-be85-fa091b6234d4.png)

Upgraded from 9.10:
![image](https://user-images.githubusercontent.com/792847/215288669-eb0df875-0dc5-4726-99db-66820f08ea26.png)

## Affected version
* [x] 09.11.00

**Comment by mitchelsellers** [comment]
This feature is disabled by default and has since I believe 9.8.0. Upgrades keep the set values.

**Comment by erw13n** [comment]
Indeed,
Looks like this HostSettings is not set to DB on fresh installation.

https://github.com/dnnsoftware/Dnn.Platform/blob/12a0c880fe961f751b0964671e8f8eaba425e5ee/DNN%20Platform/Library/Entities/Host/Host.cs#L456-L462

Adding it to table, was solve the issue.

**Comment by bdukes** [comment]
Note the deprecation warning on that property, the Users Online feature will be removed altogether in DNN 11
https://github.com/dnnsoftware/Dnn.Platform/blob/12a0c880fe961f751b0964671e8f8eaba425e5ee/DNN%20Platform/Library/Entities/Host/Host.cs#L455

**Comment by erw13n** [comment]
Hi @bdukes 
We do notice it.
Is there a better approach to know if there's someone still using the website?
We always do a weekly maintenance, and check the user online status before bring it offline.

**Comment by mitchelsellers** [comment]
Google analytics. IIS logs, etc.
