### ISSUE TITLE
DNN v9.11.1 RC1 installation error

### ISSUE THREAD

**Issue by skarpik** [dnnsoftware/Dnn.Platform#5522]
## Description of bug
Provide a clear and concise description of the bug.

I used nvQuickSite v2.2.0 to facilitate the installation of DNN v9.11.1 RC1. The installation gets part way through the process and then suffers an error.

## Current behavior
The first few lines of the error are:

Application Error
DNN Configuration Error
Could not find a part of the path 'D:\Websites\dnn-9-11-1\Website\Config\Backup_202302022357\web_.config'.

(see screen shot below)

It is interesting to note that the folder "Backup_202302022357" does not exist in "Config".

## Expected behavior
Normally installs without trouble.

## Screenshots

![DNN v9 11 11 RC1 installation error](https://user-images.githubusercontent.com/3846223/216516885-bd692b40-3b8d-487e-846c-b22484910d02.jpg)

## Error information
Nothing additional.

## Additional context
I checked file permissions for the ApplicationPoolIdentity account. They were lacking "full control".

![DNN v9 11 11 RC1 installation error - 2](https://user-images.githubusercontent.com/3846223/216517318-3b20f0f0-92a6-479d-b3d8-3286aabde898.jpg)

I tried adding "full control" but it didn't improve the situation.

## Affected version

* [X] 09.11.01 release candidate

## Affected browser

* [X] Chrome
* [X] Firefox
* [ ] Safari
* [ ] Internet Explorer 11
* [ ] Microsoft Edge (Classic)
* [X] Microsoft Edge Chromium

**Comment by valadas** [comment]
I can confirm, will try to take a look at that this weekend

**Comment by bdukes** [comment]
`Config.UpdateMachineKey`, `Config.UpdateValidationKey`, `Config.UpdateInstallVersion`, and the HTML Editor Manager's `UpgradeController.UpdateTelerikEncryptionKey` methods all try to write `web_.config` to the backup folder and were adjusted in 43868a7977b2e6351cde9df1a9cf77fa9d763c7a. I don't immediately see any reason there'd be different behavior there, though.  Those methods do call `Config.BackupConfig`, which was changed a little more than the others, but the logic that creates the backup folder if it doesn't exist looks solid.

**Comment by bdukes** [comment]
Resolved in #5526, included in 9.11.1-RC2
