### ISSUE TITLE
Options for resources are not cleaned after select another resource

### ISSUE THREAD

**Issue by ufoloko** [dnnsoftware/Dnn.Platform#5532]
## Description of bug
The new resource manager keep options for selected file or resource even if you change to other folder. If you return back to the initial folder, file is not selected but options are still showed.

## Steps to reproduce

1.- Open File Management page.

2.- Select any file on root folder, then you will see options like Edit, Move, Delete, Copy Url and Download in toolbar.

<img width="437" alt="image" src="https://user-images.githubusercontent.com/1165122/216992015-f448c160-268a-4834-9226-d1caa4513087.png">

3.- Change to another folder without deselecting file, and options Edit, Move, Delete, Copy URL and Download keep showed. If you make click on Copy Url for example you will see information for last option selected on root folder.

4.- Return back to root folder, and initial file now is deselected but file options Edit, Move, etc, are still showed. If you select again the same file, options disappear, because is like 2 files are selected.

## Current behavior
Files being selected in any folder are saved in some array, and are keeped if you change between folders.

## Expected behavior
Array for files selected should be cleaned every time you change between folders.

## Affected version
[X ] 09.11.00 release candidate with new Resources Manager

## Affected browser
Any browser

**Comment by jeremy-farrance** [comment]
I was just about to report this. I can confirm it is still an issue in 9.11.02.  If there is any confusion about what is wrong or how to reproduce, hit me up and I will explain more or add a demo video. Cheers!!

**Comment by valadas** [comment]
Should be fixed as part of  #5892
