### ISSUE TITLE
DNN v9.11.1-rc2 file browsing bug

### ISSUE THREAD

**Issue by skarpik** [dnnsoftware/Dnn.Platform#5533]
## Description of bug

While editing an HTML module, file browsing fails with the message: "A critical error has occurred. Please check the Admin logs for further details."

## Steps to reproduce
Precise steps to reproduce the bug:

1. Installed DNN 9.11.1-rc2 using nvQuickSite v2.3.3
2. Once nvQuickSite was done its work, I continued the installation choosing an "empty website". The installation appeared to proceeded properly.
3. Uploaded a test image to the Site Assets folder to a newly created Images folder.
4. Started to edit the website. Began by going to site Site Settings. Dragged a DNN logo to the Site Logo box. Dragged a favicon.ico file to the Favicon box. All still seems OK.
5. Opened an HTML module for editing on the home page and browsed for an image.

## Current behavior

Instead of being allowed to browse for my image, I get a pop-up window  with the message: "A critical error has occurred. Please check the Admin logs for further details."

## Expected behavior

I should be able to browse for my image file.

## Screenshots

![Screenshot 2023-02-06 235257](https://user-images.githubusercontent.com/3846223/217151907-3484c6e7-d5d9-4774-8def-216322cf4603.jpg)

## Error information

AbsoluteURL:/Providers/HtmlEditorProviders/DNNConnect.CKE/Browser/Browser.aspx
DefaultDataProvider:DotNetNuke.Data.SqlDataProvider, DotNetNuke
ExceptionGUID:80f85105-f890-42ad-a1c3-324161dff88b
AssemblyVersion:9.11.1
PortalId:0
UserId:1
TabId:21
RawUrl:/Providers/HtmlEditorProviders/DNNConnect.CKE/Browser/Browser.aspx?Type=Image&amp;tabid=21&amp;PortalID=0&amp;mid=355&amp;ckid=txtContent&amp;mode=Default&amp;lang=en-US&amp;CKEditor=dnn_ctr355_EditHTML_txtContent_txtContent&amp;CKEditorFuncNum=3&amp;langCode=

Referrer:http://dnn-9-11-1.dnndev.me/Home/ctl/Edit/mid/355?popUp=true
UserAgent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36 Edg/109.0.1518.78
ExceptionHash:9RfniXuyZHlmwTaPQw8zurMmK/U=
Message:Object reference not set to an instance of an object.
StackTrace:
InnerMessage:Object reference not set to an instance of an object.
InnerStackTrace:

   at DNNConnect.CKEditorProvider.Utilities.SettingsUtil.LoadEditorSettingsByKey(IPortalSettings portalSettings, EditorProviderSettings currentSettings, List`1 editorHostSettings, String key, IList`1 portalRoles)
   at DNNConnect.CKEditorProvider.Browser.Browser.Page_Load(Object sender, EventArgs e)
   at System.Web.UI.Control.OnLoad(EventArgs e)
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
Source:

FileName:
FileLineNumber:0
FileColumnNumber:0
Method:
Server Name: OMEN2

## Additional context
This seems very reminiscent of the bug in v9.11.0 where uploading a favicon.ico file messed up file browsing.

## Affected version

* [ ] 10.00.00 alpha build
* [X] 09.11.00 RC2
* [ ] 09.11.00 release candidate
* [ ] 09.10.02 release candidate
* [ ] 09.10.01 latest supported release

## Affected browser

* [ ] Chrome
* [ ] Firefox
* [ ] Safari
* [ ] Internet Explorer 11
* [ ] Microsoft Edge (Classic)
* [X] Microsoft Edge Chromium

**Comment by erw13n** [comment]
I'm able to reproduce this error.
Not only happen on Upgrade version but also Install version.

**Comment by erw13n** [comment]
Also happen when trying top open `Editor Manager`

**Comment by valadas** [comment]
I tested and can also confirm this. Thanks for testing the RC and for the detailed issue...

**Comment by mitchelsellers** [comment]
@skamphuis Do you possibly have any idea what might cause this one?

**Comment by bdukes** [comment]
I've recreated the issue with a PDB to get line numbers.

Firstly, this issue is _not_ related to the favicon. I can replicate the issue without doing anything related to the favicon.

Secondly, here's the stack trace:
```
   at DNNConnect.CKEditorProvider.Utilities.SettingsUtil.LoadEditorSettingsByKey(IPortalSettings portalSettings, EditorProviderSettings currentSettings, List`1 editorHostSettings, String key, IList`1 portalRoles) in \DNN Platform\Providers\HtmlEditorProviders\DNNConnect.CKE\Utilities\SettingsUtil.cs:line 179
   at DNNConnect.CKEditorProvider.Browser.Browser.Page_Load(Object sender, EventArgs e) in \DNN Platform\Providers\HtmlEditorProviders\DNNConnect.CKE\Browser\Browser.aspx.cs:line 789
   at System.Web.UI.Control.OnLoad(EventArgs e)
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
```

[Line 179 in `SettingsUtil.cs`](https://github.com/dnnsoftware/Dnn.Platform/blob/v9.11.1-rc2/DNN%20Platform/Providers/HtmlEditorProviders/DNNConnect.CKE/Utilities/SettingsUtil.cs#L179) is reading the CodeMirror settings.
https://github.com/dnnsoftware/Dnn.Platform/blob/683ba7d87b835a26c3e81b47f712d12738a397e9/DNN%20Platform/Providers/HtmlEditorProviders/DNNConnect.CKE/Utilities/SettingsUtil.cs#L174-L179

[Line 789 in `Browser.aspx.cs`](https://github.com/dnnsoftware/Dnn.Platform/blob/v9.11.1-rc2/DNN%20Platform/Providers/HtmlEditorProviders/DNNConnect.CKE/Browser/Browser.aspx.cs#L786-L794) was introduced in #5409 by @skamphuis for the host-level settings. It would seem there are missing fallbacks or something like that.
https://github.com/dnnsoftware/Dnn.Platform/blob/683ba7d87b835a26c3e81b47f712d12738a397e9/DNN%20Platform/Providers/HtmlEditorProviders/DNNConnect.CKE/Browser/Browser.aspx.cs#L786-L794

**Comment by erw13n** [comment]
I debug it and stopped in here, when trying to read `CodeMirror` settings.
![image](https://user-images.githubusercontent.com/792847/217375031-be46abb2-2bd2-4af0-a496-41a95d69a84d.png)

Like what @bdukes said, it throw error during this process
https://github.com/dnnsoftware/Dnn.Platform/blob/683ba7d87b835a26c3e81b47f712d12738a397e9/DNN%20Platform/Providers/HtmlEditorProviders/DNNConnect.CKE/Browser/Browser.aspx.cs#L786-L794

And for Editor Manager, it throw error during this process:
https://github.com/dnnsoftware/Dnn.Platform/blob/683ba7d87b835a26c3e81b47f712d12738a397e9/DNN%20Platform/Providers/HtmlEditorProviders/DNNConnect.CKE/CKEditorOptions.ascx.cs#L771-L775

**Comment by valadas** [comment]
Actually @erw13n did the work, I just published RC3 with his fix. Thansk @erw13n
