### ISSUE TITLE
File download in Resource Manager

### ISSUE THREAD

**Issue by ssanscar** [dnnsoftware/Dnn.Platform#5551]
## Description of bug
We can download files with the Resource Manager that names contains spaces, accents or special characters like parenthesis but the names of the downloaded files are renamed with underscore at the beginning and at the end of files.

Files without spaces, accents or special characters are downloaded successfully with the same name.

For the files with accents, the downloaded names is really weird like this: 
_=_utf-8_B_UmFwcG9ydCBkdSBqdXJ5IHNvdXRlbmFuY2UgZGUgdGjDqHNlLnBkZg==_=_.pdf

But, file name will always start with **_=utf-8**

## Steps to reproduce
List the precise steps to reproduce the bug:
1. Go to 'Persona Bar'.
2. Click on 'Manage' and 'Site Assets'.
3. Scroll folders to find file with spaces, accents or special characters. If you can't find files like that, just rename an existing file with the 'Edit' option of the 'Resource Manager' by a right-click on the existing file.
4. After that, download the file with the 'Download' option on the 'Resource Manager' tools bar or by a right-click on the file.

## Current behavior
The downloaded file can be open on the desktop but we need to rename it if we would like that Windows recognize the type of file for open the good associated application of the downloaded file.

## Expected behavior
Conserve the name of the file.

## Screenshots
![image](https://user-images.githubusercontent.com/42035097/221006839-1912e262-631c-48ab-a93d-87cb02ffcb7b.png)

## Error information
No errors.

## Additional context
I tried with a lot of files.

If I have accents, spaces, or special characters, I have the issue. But if my files are no spaces, etc. the file name downloaded is right.

If I rename the file under the Resource Manager without spaces, etc. the file name downloaded is right. Conversely, if I rename the file under the Resource Manager with a space, etc. the file name downloaded has the issue.

I also tried with a new Uploaded file, and I have the same issue.

## Affected version
* [X] 09.11.01 latest supported release

## Affected browser
* [X] Chrome
* [X] Firefox: names are good with spaces and special characters but the issue exist with weird name for a file with accents
* [X] Microsoft Edge (Classic)

**Comment by mitchelsellers** [comment]
I believe this might be by design.  Spaces, special characters, etc are NOT supported by all browser types and are not supported consistently across the board.

@valadas any thoughts?

**Comment by ssanscar** [comment]
FYI, I know that the Resource Manager module with v9.11.0 is new but I don't have this issue with the Resource Manager of the DNN v9.10.2.

**Comment by david-poindexter** [comment]
Very interesting.  We may need to look into this one a bit further.  Thanks so much for the detailed issue @ssanscar

**Comment by WillStrohl** [comment]
Hello... Just an FYI, that this is also discussed briefly in the [DNN forums](https://dnncommunity.org/forums/aft/3607).

**Comment by valadas** [comment]
I am not aware off-the-cuff of the code that might be adding those. In theory it should be able to download filenames with spaces in them. We'lll have to put a breakpoint and see why that is happeneing...

**Comment by JeffFrick** [comment]
Firefox doesn't add the underscores when downloaded. In my option, it would be nice if this behavior was consistent across the major browsers. My co-worker believes the issue is related to SSL authentication within the browsers. Safari also works fine on my iPhone. Edge and Chrome add the underscores. In Edge & Chrome you can get around this by using the "Copy URL" function and pasting the link in a new tab. (we had to add a certificate to our internal intranet in order to get the "Copy URL" function to appear.
