### ISSUE TITLE
DNN 9.11 CK Editor cannot select text or set cursor in text

### ISSUE THREAD

**Issue by wbonekamp** [dnnsoftware/Dnn.Platform#5559]
## Description of bug
Cannot select text or set cursor in CK Editor 

## Steps to reproduce
List the precise steps to reproduce the bug:
1. Open page;
2. Go to Edit mode;
3. Open Rich text editor;
4. Try to select text or set cursor

## Current behavior
doesn't select text

## Expected behavior
should selece text.. make selected text blue

## Screenshots
![image](https://user-images.githubusercontent.com/7567981/221533366-4de10b3a-869c-41c1-9832-e3072399e713.png)

## Error information
no errors in log

## Affected version
* [ ] 09.11.00 
* [ ] 09.11.01 latest supported release

## Affected browser
All browsers

**Comment by wbonekamp** [comment]
It is a multilanguage portal: 
![image](https://user-images.githubusercontent.com/7567981/221537855-a402f351-3c62-49c0-a97e-1ccfe869bb65.png)

**Comment by sleupold** [comment]
is this a new site or an upgrade?
did you clear local browser cache?
Are there any issues listed in browser console (F12)?

**Comment by wbonekamp** [comment]
it is an issue/conflict with the theme css... loading body background

**Comment by wbonekamp** [comment]
Its a clean install 9.11.0

**Comment by wbonekamp** [comment]
The editor is caching a lot... clear browser cache did the trick...
