### ISSUE TITLE
29% ERROR occured - Installing PersonaBar - Dnn.PersonaBar.Extensions_09.11.01_Install.zip

### ISSUE THREAD

**Issue by huyenbv** [dnnsoftware/Dnn.Platform#5561]
Install DNN_Platfrom_9.11.1 SQL2012 to 29% ERROR occured - Installing PersonaBar - Dnn.PersonaBar.Extensions_09.11.01_Install.zip
But successfull when Install DNN with SQL2016

**Comment by valadas** [comment]
Duplicates #5554
