### ISSUE TITLE
Build error  MSB3021 & MSB3027 when build in Debug mode

### ISSUE THREAD

**Issue by sriwantha** [dnnsoftware/Dnn.Platform#5562]
## Description of bug
\build.ps1" --target=ResetDevSite --Configuration=Release works
build log is given in BuildLog-Successful-Release-build-DevDNN.zip
But ....

\build.ps1" --target=ResetDevSite --Configuration=Debug fails
build log is given in BuildLog-DevDNN-1.zip

## Steps to reproduce
List the precise steps to reproduce the bug:
A fresh copy of DNN version 9.11 in a fresh computer.  When I try to build with following configuration it works.
\build.ps1" --target=ResetDevSite --Configuration=Release

I can create the site and get it working. I want to develop the DNN platform and make some modification (not a module)

But when I do a Debug built it fails. 
\build.ps1" --target=ResetDevSite --Configuration=Debug 

Entire verbose build log is attached herewith. 

The same thing happens when you do a following approach
First do a default Release built
\build.ps1"  --target=ResetDevSite --Configuration=Release   

Then do a Debug build without site reset. 
\build.ps1" --Configuration=Debug      
I want a debug built to get the PDB files working. 

Error message is
  73>C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(5150,5): error MSB3027: Could not copy "C:\Dev\DNN\Source\Build\obj\Debug\netcoreapp3.1\apphost.exe" to "bin\Debug\netcoreapp3.1\Build.exe". Exceeded retry count of 10. Failed. The file is locked by: "Build (5592)" [C:\Dev\DNN\Source\Build\Build.csproj]
    73>C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(5150,5): error MSB3021: Unable to copy file "C:\Dev\DNN\Source\Build\obj\Debug\netcoreapp3.1\apphost.exe" to "bin\Debug\netcoreapp3.1\Build.exe". The process cannot access the file 'bin\Debug\netcoreapp3.1\Build.exe' because it is being used by another process. [C:\Dev\DNN\Source\Build\Build.csproj]
    73>Done Building Project "C:\Dev\DNN\Source\Build\Build.csproj" (Rebuild target(s)) -- FAILED.

## Current behavior
Debug built fails. 

## Expected behavior
 Debug built should be successful. 

## Screenshots
check the built error. 

## Error information
        Creating "C:\Dev\DNN\Source\Build\obj\Debug\netcoreapp3.1\Build.csproj.CopyComplete" because "AlwaysCreate" was specified.
       _CopyOutOfDateSourceItemsToOutputDirectory:
         Copying file from "C:\Dev\DNN\Source\Build\obj\Debug\netcoreapp3.1\apphost.exe" to "C:\Dev\DNN\Source\Build\bin\Debug\netcoreapp3.1\Build.exe".
    73>C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(5150,5): warning MSB3026: Could not copy "C:\Dev\DNN\Source\Build\obj\Debug\netcoreapp3.1\apphost.exe" to "bin\Debug\netcoreapp3.1\Build.exe". Beginning retry 1 in 1000ms. The process cannot access the file 'bin\Debug\netcoreapp3.1\Build.exe' because it is being used by another process. The file is locked by: "Build (5592)" [C:\Dev\DNN\Source\Build\Build.csproj]
         Copying file from "C:\Dev\DNN\Source\Build\obj\Debug\netcoreapp3.1\apphost.exe" to "C:\Dev\DNN\Source\Build\bin\Debug\netcoreapp3.1\Build.exe".
    73>C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(5150,5): warning MSB3026: Could not copy "C:\Dev\DNN\Source\Build\obj\Debug\netcoreapp3.1\apphost.exe" to "bin\Debug\netcoreapp3.1\Build.exe". Beginning retry 2 in 1000ms. The process cannot access the file 'bin\Debug\netcoreapp3.1\Build.exe' because it is being used by another process. The file is locked by: "Build (5592)" [C:\Dev\DNN\Source\Build\Build.csproj]
         Copying file from "C:\Dev\DNN\Source\Build\obj\Debug\netcoreapp3.1\apphost.exe" to "C:\Dev\DNN\Source\Build\bin\Debug\netcoreapp3.1\Build.exe".
    73>C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(5150,5): warning MSB3026: Could not copy "C:\Dev\DNN\Source\Build\obj\Debug\netcoreapp3.1\apphost.exe" to "bin\Debug\netcoreapp3.1\Build.exe". Beginning retry 3 in 1000ms. The process cannot access the file 'bin\Debug\netcoreapp3.1\Build.exe' because it is being used by another process. The file is locked by: "Build (5592)" [C:\Dev\DNN\Source\Build\Build.csproj]
         Copying file from "C:\Dev\DNN\Source\Build\obj\Debug\netcoreapp3.1\apphost.exe" to "C:\Dev\DNN\Source\Build\bin\Debug\netcoreapp3.1\Build.exe".
    73>C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(5150,5): warning MSB3026: Could not copy "C:\Dev\DNN\Source\Build\obj\Debug\netcoreapp3.1\apphost.exe" to "bin\Debug\netcoreapp3.1\Build.exe". Beginning retry 4 in 1000ms. The process cannot access the file 'bin\Debug\netcoreapp3.1\Build.exe' because it is being used by another process. The file is locked by: "Build (5592)" [C:\Dev\DNN\Source\Build\Build.csproj]
         Copying file from "C:\Dev\DNN\Source\Build\obj\Debug\netcoreapp3.1\apphost.exe" to "C:\Dev\DNN\Source\Build\bin\Debug\netcoreapp3.1\Build.exe".
    73>C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(5150,5): warning MSB3026: Could not copy "C:\Dev\DNN\Source\Build\obj\Debug\netcoreapp3.1\apphost.exe" to "bin\Debug\netcoreapp3.1\Build.exe". Beginning retry 5 in 1000ms. The process cannot access the file 'bin\Debug\netcoreapp3.1\Build.exe' because it is being used by another process. The file is locked by: "Build (5592)" [C:\Dev\DNN\Source\Build\Build.csproj]
         Copying file from "C:\Dev\DNN\Source\Build\obj\Debug\netcoreapp3.1\apphost.exe" to "C:\Dev\DNN\Source\Build\bin\Debug\netcoreapp3.1\Build.exe".
    73>C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(5150,5): warning MSB3026: Could not copy "C:\Dev\DNN\Source\Build\obj\Debug\netcoreapp3.1\apphost.exe" to "bin\Debug\netcoreapp3.1\Build.exe". Beginning retry 6 in 1000ms. The process cannot access the file 'bin\Debug\netcoreapp3.1\Build.exe' because it is being used by another process. The file is locked by: "Build (5592)" [C:\Dev\DNN\Source\Build\Build.csproj]
         Copying file from "C:\Dev\DNN\Source\Build\obj\Debug\netcoreapp3.1\apphost.exe" to "C:\Dev\DNN\Source\Build\bin\Debug\netcoreapp3.1\Build.exe".
    73>C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(5150,5): warning MSB3026: Could not copy "C:\Dev\DNN\Source\Build\obj\Debug\netcoreapp3.1\apphost.exe" to "bin\Debug\netcoreapp3.1\Build.exe". Beginning retry 7 in 1000ms. The process cannot access the file 'bin\Debug\netcoreapp3.1\Build.exe' because it is being used by another process. The file is locked by: "Build (5592)" [C:\Dev\DNN\Source\Build\Build.csproj]
         Copying file from "C:\Dev\DNN\Source\Build\obj\Debug\netcoreapp3.1\apphost.exe" to "C:\Dev\DNN\Source\Build\bin\Debug\netcoreapp3.1\Build.exe".
    73>C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(5150,5): warning MSB3026: Could not copy "C:\Dev\DNN\Source\Build\obj\Debug\netcoreapp3.1\apphost.exe" to "bin\Debug\netcoreapp3.1\Build.exe". Beginning retry 8 in 1000ms. The process cannot access the file 'bin\Debug\netcoreapp3.1\Build.exe' because it is being used by another process. The file is locked by: "Build (5592)" [C:\Dev\DNN\Source\Build\Build.csproj]
         Copying file from "C:\Dev\DNN\Source\Build\obj\Debug\netcoreapp3.1\apphost.exe" to "C:\Dev\DNN\Source\Build\bin\Debug\netcoreapp3.1\Build.exe".
    73>C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(5150,5): warning MSB3026: Could not copy "C:\Dev\DNN\Source\Build\obj\Debug\netcoreapp3.1\apphost.exe" to "bin\Debug\netcoreapp3.1\Build.exe". Beginning retry 9 in 1000ms. The process cannot access the file 'bin\Debug\netcoreapp3.1\Build.exe' because it is being used by another process. The file is locked by: "Build (5592)" [C:\Dev\DNN\Source\Build\Build.csproj]
         Copying file from "C:\Dev\DNN\Source\Build\obj\Debug\netcoreapp3.1\apphost.exe" to "C:\Dev\DNN\Source\Build\bin\Debug\netcoreapp3.1\Build.exe".
    73>C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(5150,5): warning MSB3026: Could not copy "C:\Dev\DNN\Source\Build\obj\Debug\netcoreapp3.1\apphost.exe" to "bin\Debug\netcoreapp3.1\Build.exe". Beginning retry 10 in 1000ms. The process cannot access the file 'bin\Debug\netcoreapp3.1\Build.exe' because it is being used by another process. The file is locked by: "Build (5592)" [C:\Dev\DNN\Source\Build\Build.csproj]
         Copying file from "C:\Dev\DNN\Source\Build\obj\Debug\netcoreapp3.1\apphost.exe" to "C:\Dev\DNN\Source\Build\bin\Debug\netcoreapp3.1\Build.exe".
    73>C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(5150,5): error MSB3027: Could not copy "C:\Dev\DNN\Source\Build\obj\Debug\netcoreapp3.1\apphost.exe" to "bin\Debug\netcoreapp3.1\Build.exe". Exceeded retry count of 10. Failed. The file is locked by: "Build (5592)" [C:\Dev\DNN\Source\Build\Build.csproj]
    73>C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(5150,5): error MSB3021: Unable to copy file "C:\Dev\DNN\Source\Build\obj\Debug\netcoreapp3.1\apphost.exe" to "bin\Debug\netcoreapp3.1\Build.exe". The process cannot access the file 'bin\Debug\netcoreapp3.1\Build.exe' because it is being used by another process. [C:\Dev\DNN\Source\Build\Build.csproj]
    73>Done Building Project "C:\Dev\DNN\Source\Build\Build.csproj" (Rebuild target(s)) -- FAILED.
     1>Project "C:\Dev\DNN\Source\DNN_Platform.sln" (1) is building "C:\Dev\DNN\Source\DNN Platform\Skins\Xcillion\DotNetNuke.Skins.Xcillion.csproj" (54) on node 1 (Rebuild target(s)).
    54>RestorePackages:

## Additional context
I have tried restarting the machine, restarting Visual Studio, even running the build.ps1 script as a background worker. Nothing works. 
It seems like a parallel build (started by the DNN itself) is holding a lock on a file. I can consistently reproduce this bug. 

## Affected version

* [ ] 10.00.00 alpha build
* [X] 09.11.01 latest supported release

## Affected browser

This is not a browser issue. This is a build issue. 
* [X ] Chrome
* [ X] Firefox
* [ ] Safari
* [ ] Internet Explorer 11
* [ ] Microsoft Edge (Classic)
* [ ] Microsoft Edge Chromium
[BuildLog-DevDNN-1.zip](https://github.com/dnnsoftware/Dnn.Platform/files/10892824/BuildLog-DevDNN-1.zip)
[BuildLog-Successful-Release-build-DevDNN.zip](https://github.com/dnnsoftware/Dnn.Platform/files/10892834/BuildLog-Successful-Release-build-DevDNN.zip)

**Comment by mitchelsellers** [comment]
What version/edition of Visual Studio

**Comment by sriwantha** [comment]
**OS Info ===================================**
OS Name	Microsoft Windows Server 2022 Datacenter
Version	10.0.20348 Build 20348

**Visual Studio Info ==========================================================**

Microsoft Visual Studio Community 2022
Version 17.4.4
VisualStudio.17.Release/17.4.4+33213.308
Microsoft .NET Framework
Version 4.8.04161

Installed Version: Community

ASP.NET and Web Tools   17.4.326.54890
ASP.NET and Web Tools

Azure App Service Tools v3.0.0   17.4.326.54890
Azure App Service Tools v3.0.0

Azure Functions and Web Jobs Tools   17.4.326.54890
Azure Functions and Web Jobs Tools

C# Tools   4.4.0-6.22608.27+af1e46ad38d900023f8b1a2839484e471ece1502
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

NuGet Package Manager   6.4.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

Razor (ASP.NET Core)   17.0.0.2246202+61cc048d36a3fc9246d2f04625988b19a18ab8f0
Provides languages services for ASP.NET Core Razor.

SQL Server Data Tools   17.0.62207.28050
Microsoft SQL Server Data Tools

TypeScript Tools   17.0.10921.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   4.4.0-6.22608.27+af1e46ad38d900023f8b1a2839484e471ece1502
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   17.4.0-beta.22512.4+525d5109e389341bb90b144c24e2ad1ceec91e7b
Microsoft Visual F# Tools

Visual Studio IntelliCode   2.2
AI-assisted development for Visual Studio.
===============
If you want I can even share an Amazon machine image with all the configuration in place. Let me know any other info you need.

**Comment by valadas** [comment]
So, build.ps1 was made mainly for release/packaging/configuration. I am not saying it should not work for debug mode but most of us build in visual studio for debug, specially since then you can build just the project you are working on instead of the whole solution. As long as the proper config files are set (as documented in this repo build instructions) the debug DLLs should end up in the bin folder of the configured site path.

**Comment by sriwantha** [comment]
What’s the workflow you use to debug DNN.platform. For example, imagine the following situation. 
I got DNN development environment ready by running the build as follows. 
1.	.\build.ps1 --target=ResetDevSite --Configuration=Release
2.	I then open visual studio and change the configuration to Debug
3.	Back in visual studio I make a modification to the file 
Let’s say C:\Dev\DNN\Source\DNN Platform\Library\Security\Membership\AspNetMembershipProvider.cs
(In the C# project DotNetNuke.Library.)
4.	Then what’s the next step to get break points hits?
**A: **Am I supposed to just build the C# project C:\Dev\DNN\Source\DNN Platform\Library\ DotNetNuke.Library.csproj with visual studio (right click the project and build)? Will the newly build Debug Dll files with pdb files end up in IIS development site folder so that I can attach the Visual studio debugger to IIS worker processor (w3wp) and start debugging?
Or
**B:**Am I supposed to build the project C:\Dev\DNN\Source\Build\Build.csproj and it knows I made a modification to C:\Dev\DNN\Source\DNN Platform\Library\Security\Membership\AspNetMembershipProvider.cs and make the changes appear in IIS development site? I then attach the Debugger to IIS worker processor w3wp?

Or
**C:** Some other workflow?

**Comment by valadas** [comment]
So the `build` project has the code to build everything and package the artifacts. I usually set that as my startup project, running `debug` on that project allows you to debug build/packaging issues by putting a breakpoint in the build code.

If you have already ran a full build (by the method above or running build.ps1), then you need to first make sure the system knows where your test site is at (by setting up your `settings.local.json` and `DNN_Platform.local.build` files as described at https://github.com/dnnsoftware/Dnn.Platform/blob/develop/.github/BUILD.md

I theory this allows building any project and it will spit out its debug dll in the proper bin folder of your test site and you can attach to the process to hit breakpoints.

We do some open-source co-coding on Discord on Saturdays if you need more hands-on help, you are welcome to join us next session... https://discord.gg/wJRzggWt?event=1082330629322051595

**Comment by ValentinGradia** [comment]
In my case insted of solving the problem i just undo the app and clone again the repo of github.
