### ISSUE TITLE
DotNetNuke.Bundle 9.11.1 depends on DotNetNuke.Web.Deprecated (>= 9.11.1) but its latest version is 9.10.2

### ISSUE THREAD

**Issue by ricardotejo** [dnnsoftware/Dnn.Platform#5580]
## Description of bug
I'm trying to update DNN dependencies from 9.11.0 using nuget and it is not possible because [DotNetNuke.Bundle 9.11.1](https://www.nuget.org/packages/DotNetNuke.Bundle#dependencies-body-tab) depends on [DotNetNuke.Web.Deprecated](https://www.nuget.org/packages/DotNetNuke.Web.Deprecated/) (>= 9.11.1) but its latest version is 9.10.2

## Steps to reproduce
List the precise steps to reproduce the bug:
1. In a project that depends on DotNetNuke.Bundle, execute `nuget update mysolution.sln -Id DotNetNuke.Core -Version 9.11.1` 
4. See the warning message `WARNING: Unable to resolve dependencies. 'DotNetNuke.Web.Deprecated 9.10.2' is not compatible with 'DotNetNuke.Bundle 9.11.1 constraint: DotNetNuke.Web.Deprecated (>= 9.11.1)'.`

## Current behavior
DotNetNuke.Core version is not updated

## Expected behavior
DotNetNuke.Core version should be 9.11.1 in package.config

## Screenshots
N/A

## Error information
https://github.com/dnnsoftware/Dnn.Platform/blob/develop/Build/Tools/NuGet/DotNetNuke.Bundle.nuspec#L23

## Additional context
Latest publish version in nuget.org for DotNetNuke.Web.Deprecated is 10.10.2
https://www.nuget.org/packages/DotNetNuke.Web.Deprecated/#versions-body-tab

## Affected version
* [ ] 10.00.00 alpha build
* [X] 09.11.01 latest supported release

## Affected browser
* [ ] Chrome
* [ ] Firefox
* [ ] Safari
* [ ] Internet Explorer 11
* [ ] Microsoft Edge (Classic)
* [ ] Microsoft Edge Chromium

**Comment by mitchelsellers** [comment]
As a workaround you can use the inidividual packages such as .Core .Web as needed.  We will need to update the manifest to remove the reference to this.  However, not 100% sure that we can re-publish an existing package
