### ISSUE TITLE
Allow registration of custom control factories

### ISSUE THREAD

**Issue by GerardSmit** [dnnsoftware/Dnn.Platform#5605]
## Description of problem
It's not possible to register or override a custom [IModuleControlFactory](https://github.com/dnnsoftware/Dnn.Platform/blob/421210f9a20d1c272db77e7208f7a5e960011534/DNN%20Platform/Library/UI/Modules/IModuleControlFactory.cs#L11) in DNN. This is because the extensions are hard-coded in [ModuleControlPipeline](https://github.com/dnnsoftware/Dnn.Platform/blob/develop/DNN%20Platform/DotNetNuke.ModulePipeline/ModuleControlPipeline.cs#L55-L62).

## Description of solution
1. Move the extension check out of the pipeline and into the factory.
2. Add a Priority property, which the pipeline will use to determinate which factory to use.
    By default, DNN control factories have a priority of 100. If you register a custom control factory (for example for `.html` to modify the content) you can give it a priority of 200 to overrule the DNN factory.

The new factory would look like this:

```cs
public interface IModuleControlFactory
{
    /// <summary>
    /// Gets the priority of the factory.
    /// The factory with the highest priority will be used.
    /// </summary>
    /// <remarks>
    /// DNN Control factories (WebForms, Razor, HTML, MVC) have a priority of 100
    /// and the default factory (Reflected) has a priority of -1.
    /// </remarks>
    int Priority { get; }

    /// <summary>Validates if the factory supports the given configuration and <see cref="controlSrc"/>.</summary>
    /// <param name="moduleConfiguration">Module configuration.</param>
    /// <param name="controlSrc">Control source.</param>
    /// <returns><c>true</c> if the factory supports the control; otherwise, <c>false</c>.</returns>
    bool SupportsControl(ModuleInfo moduleConfiguration, string controlSrc);

    // CreateControl and CreateSettingsControl are unchanged.
}
```

The pipeline will be changed that it'll resolve all `IModuleControlFactory` and get the first supported factory.

## Description of alternatives considered
While it is currently possible to override the [IModuleControlPipeline](https://github.com/dnnsoftware/Dnn.Platform/blob/421210f9a20d1c272db77e7208f7a5e960011534/DNN%20Platform/Library/UI/Modules/IModuleControlPipeline.cs#L11) in the service collection:

```cs
public class Extension : IDnnStartup
{
    public void ConfigureServices(IServiceCollection services)
    {
        services.AddSingleton<IModuleControlPipeline>()
    }
}

public class NewModuleControlPipeline : ModuleControlPipeline
{
    // ...
}
```

This brings two problems:

1. If multiple extensions are changing the `IModuleControlPipeline`, the last one will be used. All other pipelines will be ignored.
2. The default IModuleControlPipeline of DNN (`ModuleControlPipeline`) is in a class library (`DotNetNuke.ModulePipeline`) which is not in NuGet. So you'll have to add a DLL-reference. 😔

**Comment by GerardSmit** [comment]
I've created a PR (#5606) with the proposed solution.

**Comment by bdukes** [comment]
I don't have an issue with these changes, thought I am curious what your use case is for needing a custom module control factory.

**Comment by GerardSmit** [comment]
I'm prototyping a cross-platform CMS in ASP.NET Core that runs as the same database as DotNetNuke. My end goal is where you can make modules for both .NET Framework and .NET (Core).

I have a prototype working with the alternative solution (overriding IModuleControlPipeline) but this is quite hacky. 😅

**Comment by GerardSmit** [comment]
Closing as this is merged in the DNN 10 branch 🎉 

Thanks!
