### ISSUE TITLE
Simple web farm caching only syncs for a short time

### ISSUE THREAD

**Issue by reece-bartholomew** [dnnsoftware/Dnn.Platform#5607]
## Description of bug
The simple web farm caching provider currently checks for web servers that have been active recently before syncing the cache. The check for this is any web servers with a [last activity date in the last hour](https://github.com/dnnsoftware/Dnn.Platform/blob/421210f9a20d1c272db77e7208f7a5e960011534/DNN%20Platform/Providers/CachingProviders/DotNetNuke.Providers.Caching.SimpleWebFarmCachingProvider/SimpleWebFarmCachingProvider.cs#L107). 

It seems however that the last acitivty date for a server is only set when the application starts on each server. This means that after an hour of the site running on a given web server, it will no longer be included in the cache syncing.

## Steps to reproduce

1. Set up a DNN site on a web farm with at least two web servers.
2. Configure the simple web farm caching provider.
3. After 1 hour of the site running, make a change that would require the cache to be synced.
4. See that the cache is not cleared across the other web server(s).

## Current behavior
Web server cache syncing only functions for the first hour of the site running.

## Expected behavior
Web server cache syncing continues to run for the entire time that the web server(s) are in use. Perhaps instead of checking the last activity date, it could use the enabled boolean.

## Affected version

* [ ] 10.00.00 alpha build
* [ ] 09.11.02 release candidate
* [X] 09.11.01 latest supported release

## Affected browser

* [X] Chrome
* [X] Firefox
* [X] Safari
* [X] Internet Explorer 11
* [X] Microsoft Edge (Classic)
* [X] Microsoft Edge Chromium

**Comment by bdukes** [comment]
#5575 introduced a new scheduled task in 9.11.2 which sets the last activity date while the server is running, not just on startup, so this issue should be resolved. Let us know if you still see an issue after upgrading. Thanks!
