### ISSUE TITLE
Add API tokens

### ISSUE THREAD

**Issue by donker** [dnnsoftware/Dnn.Platform#5611]
## Description of problem
Most complex modern online solutions offer an API to manage your data. Typically you'd access these by creating an API token that then gives access to specific features. Think Github, InfluxDb and many more. Building such systems on DNN is a great idea but we lack the ability to create such API tokens.

## Description of solution
An additional authentication mechanism that can be leveraged by your DNN WebAPI endpoints. The core of this should be part of our core API. That is: the management of these tokens and the security decorators for endpoints. A PersonaBar module for the management of this and maybe some global settings. The tokens can be tied to a user or not. The tokens can be decorated with having specific access. The latter should be extensible by module developers. E.g. the Github tokens give access to reading and/or writing to repos. Or: The InfluxDb tokens give access to a set of buckets. Tokens have an expiry date and can be revoked at any time.

## Description of alternatives considered
The JWT tokens we already have. The problem with leveraging those is that it is a hack. API tokens are designed to have a long life and cannot be renewed. JWT tokens should not live longer than a session timeout. JWT tokens are designed to identify a specific user. API tokens are designed to give access to a subset of the API.

**Comment by mitchelsellers** [comment]
I like this idea, I do think at some capacity to try and help make this valuable to consumers there should be a concept of 

* User API Tokens - This provides the caller with a user context of who it is, allowing the developer to act as the user
* Portal API Token - Not tied to a user, but tied to a specific portal
* Host/SuperUser API Token - Not limited to a particular portal

How a developer users it would be up to them I believe, but the system could do the following.

* User Tokens
  * Must track to a user account that is not locked-out or disabled
  * Must track to a user that has access to the requested portal based on the incoming URL/ALias
* Portal Tokens
  * Must track to a portal based on the incoming URL/ALias
* Host/Superuser API Tokens
 * No special validation

I'm not 100% sure if we need this, as really the "behavior" is downstream, but I think this would make it usable.

**Comment by donker** [comment]
The simplest implementation uses a token to identify a user in the same way as JWT does. The advantage of this approach is that we now have a CurrentUser which makes it super easy to integrate for module developers as this what they're used to.

The question then becomes: do we add a mechanism to pair down the API access for such a token or not?

1. Do not restrict API access
The implementation will be super easy. But a long lived token will have access to everything the user has access to in DNN. While this may seem disconcerting, keep in mind that DNN has a strong mechanism to limiting what a user can do through the API through our own permission system. In other words, if we consider this a security risk are we not saying we find the API itself insecure?

2. We restrict API access
This will require one of two things or both: (a) a way for the framework to manage the token's access settings or (b) an addition to the authorize attribute on API methods to specify whether they can be accessed through the tokens. Especially the first part opens a can of worms. Modules will need to announce themselves that they have available API and DNN then needs to manage each token's access to these APIs.

I am of the opinion that 2a takes us down a rabbit hole we should probably avoid. Potentially I can see 2b being implemented where the default behavior of API tokens is to not have access, but only when explicitly set through a new tweak of the Authorize attribute. Having said that, I think nr 1 is also a valid approach. We could have a master switch which allows API keys to be generated and then any key is valid for whatever the user has access to.

**Comment by bdukes** [comment]
1. The difference between the existing user permissions and security is that these tokens will be long-lived in a way that a session cookie would not typically be. A mechanism for expiring and rotating these keys seems like an important aspect we'd need to consider. Limiting the scope of a key is an additional defense we can provide against a key ending up in the wrong hands.
2. Are we thinking that these tokens would primarily be used in a context where they aren't tied to a module instance, so that module permissions would not be a straightforward mechanism for applying security? We added `PortalPermissions` in 9.11.0, perhaps tying into that would give us a simple mechanism for defining and checking permissions? One issue I see with using permissions is that we want to be able to limit a token assigned to a superuser, but superusers bypass permissions checks.

**Comment by mitchelsellers** [comment]
A few notes from me on this discussion.  It is my understanding that the generated tokens here would be ONLY utilized by third-party custom solutions that elect to utilize this mechanism for security?  Is this correct?  More specifically, NO existing DNN process/api would be updated to be decorated or secured via this new system.

If my assumption is correct, then I would not consider a long-lived user-based security token as a "real" risk right now, however, I do think it would have the possibility to become a problem, especially as I consider how the current JWT and otherwise grant widespread access to API's based on the general account.  (For example if two module vendors create API's secured by JWT, a user with a JWT token can call EITHER)

To this point, I'm thinking that we might want to employ a "two step" process here.

## Step 1 - Developers Identify an Intent/Context

In this situation individual developers would make a request to DNN, at module installation or via API later.  This would tell DNN that they want to allow users to create API tokens to interact with their application.  This would include at minimum.

* Intent Name - This would be the individual name of the intent
* Intent Scope - The Scope (User, Portal, Host)
* Intent Purpose - What can be done

This would allow for example the definition of things such as

| Name | Scope | Purpose |
|--------|--------|--------|
| MyCompany.Blog | Portal | Provides access to interact with the My Company Blog module  |
| MySpecial.Code | Portal | Provides access to the API's created by My Special code that was created for my very sensitive application |

The usage within the custom code might be something similar to adding the attribute `[DnnApiAuthorize("MySpecial.Code")]`

This would ensure that an API token created for `MyCompany.Blog` couldn't be utilized to access `MySpecial.Code` or otherwise

## Step 2 - Manage Keys

This process then would be only exposed if at least 1 Intent has been registered within the installation.  Users would be able to list the API keys and I think at this stage a few things would exist for each of the keys.

* Intent
* Scope
* Created Date

There would need to be actions to revoke/delete the API key, and we should NOT allow these API keys to be viewed again.

The "Scope" would need to identify the specific scope such as `User (jsmith@company.com)` or `Portal (15)`.

If we follow something like this, we could actually utilize the BulkDeploy process as a really cool way to integrate this into the platform.

Thoughts?

**Comment by david-poindexter** [comment]
> A few notes from me on this discussion. It is my understanding that the generated tokens here would be ONLY utilized by third-party custom solutions that elect to utilize this mechanism for security? Is this correct? More specifically, NO existing DNN process/api would be updated to be decorated or secured via this new system.
> 
> If my assumption is correct, then I would not consider a long-lived user-based security token as a "real" risk right now, however, I do think it would have the possibility to become a problem, especially as I consider how the current JWT and otherwise grant widespread access to API's based on the general account. (For example if two module vendors create API's secured by JWT, a user with a JWT token can call EITHER)
> 
> To this point, I'm thinking that we might want to employ a "two step" process here.
> 
> ## Step 1 - Developers Identify an Intent/Context
> In this situation individual developers would make a request to DNN, at module installation or via API later. This would tell DNN that they want to allow users to create API tokens to interact with their application. This would include at minimum.
> 
> * Intent Name - This would be the individual name of the intent
> * Intent Scope - The Scope (User, Portal, Host)
> * Intent Purpose - What can be done
> 
> This would allow for example the definition of things such as
> 
> Name	Scope	Purpose
> MyCompany.Blog	Portal	Provides access to interact with the My Company Blog module
> MySpecial.Code	Portal	Provides access to the API's created by My Special code that was created for my very sensitive application
> The usage within the custom code might be something similar to adding the attribute `[DnnApiAuthorize("MySpecial.Code")]`
> 
> This would ensure that an API token created for `MyCompany.Blog` couldn't be utilized to access `MySpecial.Code` or otherwise
> 
> ## Step 2 - Manage Keys
> This process then would be only exposed if at least 1 Intent has been registered within the installation. Users would be able to list the API keys and I think at this stage a few things would exist for each of the keys.
> 
> * Intent
> * Scope
> * Created Date
> 
> There would need to be actions to revoke/delete the API key, and we should NOT allow these API keys to be viewed again.
> 
> The "Scope" would need to identify the specific scope such as `User (jsmith@company.com)` or `Portal (15)`.
> 
> If we follow something like this, we could actually utilize the BulkDeploy process as a really cool way to integrate this into the platform.
> 
> Thoughts?

@mitchelsellers I really like this idea.  It keeps things clean.  And, as an opportunity for a nice example implementation via `Bulk Install`.

**Comment by bdukes** [comment]
@mitchelsellers in your example, what's the difference between a token scoped to a superuser and a host-scoped token? I agree with @donker's point that our code expects a current user, so having a portal or host scope that's divorced from a user seems like it could make things more difficult. Maybe there could be a mechanism to auto-create an API user for those scopes?

**Comment by mitchelsellers** [comment]
@bdukes That's the one concept that is possibly lost, or cloudy as I look at this.  The concept that I was anticipating would be.

* User - I want to act LIKE I am this particular user
* Portal - I want to act at the portal level, ONLY within this portal, and not as a specific user
* Host - I want to act at the host level, and not as a specific user

Using the example of bulk deploy, I would require "Host" access for the API key, which just further explains the intent/purpose of what is being done.

Internal security permissions, restrictions, etc don't really apply on complete "roll your own" identities as it is.

**Comment by donker** [comment]
At DNN Connect we got positive feedback for this feature. How about the following design.

## Data Model

ApiTokens

|Column|Type|Notes|
|-----|-----|-----|
|TokenId|int|Autoincrement|
|TokenHash|string||
|Scope|int|Host, Portal, User|
|PortalId|int|Only -1 if host scope|
|AllowPersonaBar|bool|If true the personabar API can be accessed|
|CreatedByUserId|int|This binds the user to the token. Do not support creating a token for someone else.|
|CreatedOnDate|datetime||

ApiTokenModules

|Column|Type|Notes|
|-----|-----|-----|
|TokenId|int||
|DesktopModuleId|int|We don't support other extensions than modules for this feature|

## Authentication

1. Check if ApiTokens feature is switched on
2. Look up token and add to the thread
3. If user scoped SetCurrentPrincipal with username
4. If not user scoped do not set thread principal

## Membership Module

No changes are needed as far as I can see. With user scoped tokens, the CurrentUser will be set. With host and admin tokens the thread user will not be set and the thread will remain unauthenticated but with a token added to it which can be picked up later.

## Authorization

We have various attributes derived from AuthorizeAttributeBase

### DnnAuthorizeAttribute and DnnModuleAuthorizeAttribute

These can only work with user scope. A check is added to DnnModuleAuthorizeAttribute to check the DesktopModuleId. The DnnAuthorizeAttribute can now take in the new AuthType as well.

### MenuPermission (PersonaBar)

This can be extended to allow ApiTokens with host or portal level access. The AllowPersonaBar is checked in the token. This is not more finegrained because in the request it is unknown exactly which component it is. This is different from the DnnModuleAuthorizeAttribute which has a ModuleInfo in the request.

### New ApiTokenAuthorizeAttribute

This can be used with the host and portal scoped tokens.

**Comment by mitchelsellers** [comment]
All of that sounds good, except for the "allow persona bar" bit.

Does this mean that ALL persona bar API's would be updated in the core to allow these tokens to use them?

**Comment by WillStrohl** [comment]
If we have a status for tokens, such as `IsRevoked`, `IsDeleted`, etc., this would mean that we could potentially end up with a bunch of orphaned/unusable data in some cases.  We should also consider whether or not a deleted token needs to remain in the database at all.  ;)

**Comment by donker** [comment]
> All of that sounds good, except for the "allow persona bar" bit.
> 
> Does this mean that ALL persona bar API's would be updated in the core to allow these tokens to use them?

Just the ones we decide are necessary. Right now none of them would work. ut every method that we feel should be accessible through tokens should be changed to allow this. I envision that this would be on bases of requests from the community and not "hey we can do this, so let's do this".

**Comment by donker** [comment]
> For `DnnModuleAuthorizeAttribute`, would this only work if a tab ID and module ID were also passed? There's just an extra check to ensure the token applies to that module? I think we typically apply permissions at the Module Definition level, rather than the Desktop Module level, but I don't have a strong opinion, just considering consistency.

Yes. DnnModuleAuthorize can only work with a pointer to a module which comes from ModuleId and TabId in the request.

As to the DesktopModules thing: I don't think it's practical to have a user plough through (a) all modules on a site or (b) various methods in a module when creating a token. Then it becomes more or less unusable. But a developer can chose which methods are open to Api Tokens and they become available to the user in one go by opting in for that module. So as an example the Blog module. The user would indicate "yes, the blog module is for this token" and then all the methods that the Blog module developer has allowed for Api Token access would be available with that token.

**Comment by donker** [comment]
> If we have a status for tokens, such as `IsRevoked`, `IsDeleted`, etc., this would mean that we could potentially end up with a bunch of orphaned/unusable data in some cases. We should also consider whether or not a deleted token needs to remain in the database at all. ;)

Good point. I was thinking about this when Mitch mentioned he wanted the ability to add to the audit log if a token was used when accessing a method. This could be done very simply by adding TokenId to the audit fields where you want to do this. But this should then not be keyed to the ApiTokens table if we are to delete them.

**Comment by donker** [comment]
New auth type "APITOKEN"

After discussions in the DNN git approvers meeting of 4 June, the ability to access existing WebAPI endpoints has been rejected and with it the idea of user based tokens. 
At this stage only portal wide or installation wide tokens should be possible which can access only designated endpoints carrying a new authorization attribute.
The scenarios that are supported are those where a coupling of external systems with DNN are required that need access to the entire portal or installation.
What is not supported is a coupling of DNN with external systems where the individual user grants rights to access his/her data within DNN.

## Data Model

ApiTokens

|Column|Type|Notes|
|-----|-----|-----|
|TokenId|int|Autoincrement|
|TokenHash|string||
|Scope|int|Host, Portal, User|
|PortalId|int|Only -1 if host scope|
|IsRevoked|bit||
|CreatedByUserId|int|This binds the user to the token. Do not support creating a token for someone else.|
|CreatedOnDate|datetime||

## Authentication

1. Check if ApiTokens feature is switched on
2. Look up token and add to the thread
Note the thread remains without thread principal

## Authorization

### New ApiTokenAuthorizeAttribute

Pick up token from thread and evaluate accordingly.

**Comment by donker** [comment]
# Update 12 June

After discussions in the DNN git approvers meeting of 4 June, the ability to access existing WebAPI endpoints has been rejected. What follows is a new proposal.

## Data Model

ApiTokens

|Column|Type|Notes|
|-----|-----|-----|
|TokenId|int|Autoincrement|
|TokenHash|string||
|Scope|int|User, Portal, Host|
|PortalId|int|Only -1 if host scope|
|IsRevoked|bit||
|RevokedOnDate|datetime||
|CreatedByUserId|int|This binds the user to the token. Do not support creating a token for someone else.|
|CreatedOnDate|datetime||

ApiTokenKeys

|Column|Type|Notes|
|-----|-----|-----|
|TokenId|int||
|TokenKey|string|Ties the token to specific parts of the API|

## Authentication

1. Check if ApiTokens feature is switched on
2. Look up token and add to the thread
3. If the token is user scoped then set the thread principal

## Authorization

### New ApiTokenAuthorizeAttribute

Takes three parameters:

1. Key. This uniquely identifies part of the API. The common form will be {MyComponentNameSpace}.{ApiSegment}
2. ResourceFile. The {Key.Text} will resolve to an explanatory text for the end user as to the purpose of the API. If empty or unresolved, then Key will be returned as purpose.
3. Scope. User, Portal or Host.

### Authorization Process

1. Find token and check for validity (if user, does user still exist)
2. Match endpoint attribute scope to token scope. Host scope can also match portal scope but not user scope because there is no identity.
3. Match endpoint attribute key to one of token keys
4. Check portal if not host level token

**Comment by mitchelsellers** [comment]
I think this works!  Love it
