### ISSUE TITLE
CKEditor Upload Issue

### ISSUE THREAD

**Issue by WasherFluid** [dnnsoftware/Dnn.Platform#5645]
## Description of bug
After upgrading to 9.11.2 when I select a file to upload and click "Send it to the Server" I get a JSON response where the choose file was.  In version 9.10.2 when you click "Send it to the Server" it would automatically take you back to Link Info with the URL filled out with the new file you uploaded.

I downloaded a fresh, new 9.11.2 install and tested on that and got the same issue.

The file is getting uploaded but you have to go back to the Link Info and Browse server to get the file and the JSON response is confusing for users.

## Steps to reproduce
When editing content within CKEditor
1. Click Image or Link icon within the menu
2. Click the Upload tab
3. Click "Choose File"
4. Browse for file and open, the file name should display next to choose file
5. Select "Send it to the Server"
6. A JSON response will appear where "Choose File" was

## Current behavior
File is uploaded but user gets a JSON response.

## Expected behavior
File is uploaded and user is automatically take back to Link Info with URL filled out with new file you uploaded as was the case in 9.10.2

## Screenshots
![download](https://github.com/dnnsoftware/Dnn.Platform/assets/134531462/ef82b78c-c6b0-4e9e-a225-bb6a1d6ec391)

## Affected version

* [ ] 10.00.00 alpha build
* [X] 09.11.02 latest supported release

**Comment by skamphuis** [comment]
So, indeed #5416 fixed an issue where the script was returned  when dragging/dropping an image into the editor, but the upload button still needs that script. I'll make a PR this week.
