### ISSUE TITLE
Bug when saving analytics connector settings when `Track for Administrators` checkbox is unchecked

### ISSUE THREAD

**Issue by david-poindexter** [dnnsoftware/Dnn.Platform#5667]
## Description of bug
There is currently a bug when attempting to save any of the analytics connectors settings when "Track for Administrators" is unchecked.

## Steps to reproduce
1. Go to `Settings > Connectors`
2. Edit settings for `Google Analytics`, `Google Analytics 4`, or `Google Tag Manager` connector
3. Ensure `Track for Administrators` is unchecked
4. Click `Save
5. See console error

## Current behavior
Will not save settings and throws console error.

## Expected behavior
Provide a clear and concise description of the expected behavior.

## Screenshots
<img width="959" alt="image" src="https://github.com/dnnsoftware/Dnn.Platform/assets/4568451/2c3ec438-8e31-4737-84c4-65e64a47c7dd">

## Error information
See screenshot.

## Additional context
This seems to have surfaced in DNN 9.11.0.  It was working in DNN 9.10.2.

## Affected version
* [x] 10.00.00 alpha build
* [x] 09.11.00
* [x] 09.11.01
* [x] 09.11.02 latest supported release

## Affected browser
* [x] Chrome
* [x] Firefox
* [x] Safari
* [x] Internet Explorer 11
* [x] Microsoft Edge (Classic)
* [x] Microsoft Edge Chromium

**Comment by Timo-Breumelhof** [comment]
This fix is not part of 09.12.00 is it? We used the "old analytics" connector for a lot of our clients...

**Comment by bdukes** [comment]
Yes, this fix is part of 9.12.0

**Comment by Timo-Breumelhof** [comment]
@bdukes ok thank you :-)
