### ISSUE TITLE
[Enhancement]: Upgrade CodeDOM provider by default

### ISSUE THREAD

**Issue by bdukes** [dnnsoftware/Dnn.Platform#5689]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of problem

The ASP.NET runtime compiler defaults to an older version of the C# and VB.NET compilers. DNN includes a package which updates the compilers, but it isn't installed by default.

### Description of solution

Install the CodeDOM provider package by default on installs and upgrades.

### Description of alternatives considered

Continue to provide it as an optional package.

### Anything else?

With the provider installed, this Razor script renders correctly, `<h1>@(Dnn?.ActiveModule?.ModuleID)</h1>`, whereas it gives an error without the provider being installed (because [the `?.` operator](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/operators/member-access-operators#null-conditional-operators--and-) was [introduced in C# 6](https://learn.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-version-history#c-version-60), and the ASP.NET compiler only supports C# 5 by default).

This package is currently optional because previous versions of DNN found examples of installations failing on GoDaddy hosting, since the package installs `csc.exe` and `vbc.exe` into the `bin` folder. Our expectation is that testing for DNN 10 will reveal any incompatibilities with currently used hosting providers.

### Do you be plan to contribute code for this enhancement?

- [X] Yes

### Would you be interested in sponsoring this enhancement?

- [ ] Yes

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jeremy-farrance** [comment]
This is fantastic! I am strongly in favor of this and looking forward to no longer having to do this additional setup step after every DNN install. Cheers!!

**Comment by valadas** [comment]
Merged into v10 branch.

Yes, the few in odd hosting environments that can't allow this, users can just delete that zip or rename to .resoruces as a workaround...

The needs of the many outweigh the needs of the few....
