### ISSUE TITLE
[Bug]: Delete site icon does not show

### ISSUE THREAD

**Issue by enfJoao** [dnnsoftware/Dnn.Platform#5699]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

There is supposed to be a delete icon here (personna bar "sites" menu).
There are no site groups (I checked the database for remnant entries and it's empty).
The icon fails to load on all sites, so it's not an active site issue.

![image](https://github.com/dnnsoftware/Dnn.Platform/assets/26518879/d54eefed-e7d7-428b-98d2-4d6dafc2048c)

### Steps to reproduce?

Personna bar => sites

### Expected Behavior

The icon should show on all non-active sites.

### Relevant log output

```shell
No errors on browser log.
```

### Affected Versions

9.11.2 (latest release)

### What browsers are you seeing the problem on?

Firefox, Microsoft Edge

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bdukes** [comment]
I'm not seeing this behavior, so we'll need to track down what's different.

If you inspect the HTML of the icons, is there a `div` for the icon that's just not rendering, or is it missing altogether?

[The logic to determine whether deleting is allowed](https://github.com/dnnsoftware/Dnn.Platform/blob/46643bf3e02cf358b255e56d0124dafb2551f764/Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Services/SitesController.cs#L371-L373) is only checking whether it's the current portal or whether it's in a site group. The site group logic is checking whether the `PortalGroupID` is set for the `Portal`, is that what you checked in the database?

https://github.com/dnnsoftware/Dnn.Platform/blob/46643bf3e02cf358b255e56d0124dafb2551f764/DNN%20Platform/Library/Entities/Portals/PortalController.cs#L320-L325
