### ISSUE TITLE
[Enhancement]: Update Old Google Analytics Connector, Add "(Legacy)" to Title

### ISSUE THREAD

**Issue by jeremy-farrance** [dnnsoftware/Dnn.Platform#5700]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of problem

With the addition in DNN 9.12.00 (RC1) of the GA4 connector, for some users, the list of Connectors could present confusion and mistakes in getting their analytics setup. 
 
As we transition from the old "Google Analytics" Connector to both the new "Google Analytics 4" Connector and the option to use the "Google Tag Manager" to setup GA4, it seems likely many (some?) people might not be aware of which connector to choose to do things right or better. This could waste time, frustrate people, and give a negative impression of setting up and going live with a DNN website.

### Description of solution

As a very simple solution, it would be helpful and time-saving to many people to improve the title of the existing (old) connector to discourage people from accidentally doing new setups by adding "(LEGACY)" to the title. Example below. 

![image](https://github.com/dnnsoftware/Dnn.Platform/assets/653301/91175ab6-f6c9-461b-ab37-08b4733016f1)

### Description of alternatives considered

Would a word beside "legacy" communicate better? Others that were discussed: "deprecated," "old," "not recommended," "Captain Dunsel" and others,. Another thought was to highlight it in the color red or maybe orange for warning? But just "(LEGACY)" at the end of the title seems like it would do the job well and be worthwhile. 

### Anything else?

This was discuss briefly in a recent "meetup" and [the video is here, discussion starts at around 11:50 mins in](https://www.youtube.com/watch?v=PU0Na45JldY&t=707s). 

### Do you be plan to contribute code for this enhancement?

- [ ] Yes

### Would you be interested in sponsoring this enhancement?

- [ ] Yes

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by valadas** [comment]
According to google it will stop working in about 10 days, so we need to actually remove this connector from the codebase entirely. We just have to double-check that unused configs don't crash anything and if so plan accordingly.

**Comment by jeremy-farrance** [comment]
Removing it seems to be inviting unexpected behavior(s). I don't claim to have any insight based in fact, but scheduling this for "removal" in DNN v10 seems more appropriate.

**Comment by valadas** [comment]
I would gladly welcome a PR to change the name (should be probably just a localization key). That being said, this configures an external service that was announced to no longer work on July 1st. My main concern (that needs to be tested) is if removing the implementation for a config that exists causes any errors or not. If not, then all is good, but if so, we need to act accordingly to not cause issues.
