### ISSUE TITLE
[Bug]: Compile error in 9.11.1 through 9.12.0

### ISSUE THREAD

**Issue by mikaelljunghorn** [dnnsoftware/Dnn.Platform#5735]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

In 9.11.1 and up to 9.12.0 there is a compile error when compiling in Visual Studio 2022.
I expect no compile time errors.

### Steps to reproduce?

Vanilla installation of DNN Platform 9.12.0.
Open http://localhost/DNN_Platform_9.12.0_Install in Visual Studio 2022 (Community).
Build Web Site.
8 errors are present when the build is complete.

### Current Behavior

Severity	Code	Description	Project	File	Line	Suppression State
Error		'ASP.providers_folderproviders_azurefolderprovider_settings_ascx' does not contain a definition for 'valContainerName_ServerValidate' and no extension method 'valContainerName_ServerValidate' accepting a first argument of type 'ASP.providers_folderproviders_azurefolderprovider_settings_ascx' could be found (are you missing a using directive or an assembly reference?)		C:\inetpub\wwwroot\DNN_Platform_9.11.1_Install\Providers\FolderProviders\AzureFolderProvider\Settings.ascx	26	

Error		'ASP.providers_folderproviders_azurefolderprovider_settings_ascx' does not contain a definition for 'ddlContainers_SelectedIndexChanged' and no extension method 'ddlContainers_SelectedIndexChanged' accepting a first argument of type 'ASP.providers_folderproviders_azurefolderprovider_settings_ascx' could be found (are you missing a using directive or an assembly reference?)		C:\inetpub\wwwroot\DNN_Platform_9.11.1_Install\Providers\FolderProviders\AzureFolderProvider\Settings.ascx	16	

Error		'ASP.providers_folderproviders_azurefolderprovider_settings_ascx' does not contain a definition for 'btnSelectExistingContainer_Click' and no extension method 'btnSelectExistingContainer_Click' accepting a first argument of type 'ASP.providers_folderproviders_azurefolderprovider_settings_ascx' could be found (are you missing a using directive or an assembly reference?)		C:\inetpub\wwwroot\DNN_Platform_9.11.1_Install\Providers\FolderProviders\AzureFolderProvider\Settings.ascx	24	

Error		'ASP.providers_folderproviders_azurefolderprovider_settings_ascx' does not contain a definition for 'btnNewContainer_Click' and no extension method 'btnNewContainer_Click' accepting a first argument of type 'ASP.providers_folderproviders_azurefolderprovider_settings_ascx' could be found (are you missing a using directive or an assembly reference?)		C:\inetpub\wwwroot\DNN_Platform_9.11.1_Install\Providers\FolderProviders\AzureFolderProvider\Settings.ascx	20	

### Expected Behavior

None of the above errors to be reported.

### Relevant log output

```shell
I think the problem is because of a capitalized letter in the beginning of the function names in the source code.
```

### Anything else?

Below are the current incorrect function names, from 9.11.1 up until 9.12.0.

DdlContainers_SelectedIndexChanged
BtnNewContainer_Click
BtnSelectExistingContainer_Click
ValContainerName_ServerValidate

These function names should all start with a lower case letter:

ddlContainers_SelectedIndexChanged
btnNewContainer_Click
btnSelectExistingContainer_Click
valContainerName_ServerValidate

### Affected Versions

9.12.0 (latest release)

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bdukes** [comment]
This was broken by [my StyleCop auto-fix commit](https://github.com/dnnsoftware/Dnn.Platform/commit/72337e99cf83c72675f6ce5c0913417b8e28738a), which confirms that this was working in 9.11.0 and was first broken in 9.11.1. I'll submit a fix. Thanks!

At present, when trying to setup an Azure Folder Provider, the settings screen comes back blank, because of this error:
![Screenshot of AzureFolderProvider setup with a blank settings section, dev tools shows an error partial-postback response](https://github.com/dnnsoftware/Dnn.Platform/assets/59507/2bff77bc-7f4a-483a-957f-5958b9922c45)
