### ISSUE TITLE
[Bug]: SettingsRepository pattern clearing cache not always working

### ISSUE THREAD

**Issue by valadas** [dnnsoftware/Dnn.Platform#5739]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Having a class with [PortalSettings] attributes for the settings but calling SaveChanges(moduleInfo) does not clear the portal level cached settings.

### Steps to reproduce?

1. Create a settings class that has a mix of [PortalSetting] and [ModuleSetting] attributes.
2. Call the SaveSettings by using the overload that takes a moduleInfo
3. On another request, call GetSettings and notice all portalSettings reflect the old settings but the new settings where actually saved to the databse
4. Clear cache and everything is back to normal.

### Current Behavior

Saving the settings does not clear all the appropriate caches for the settings that have changed.

### Expected Behavior

New settings should be available right after saving them without having to clear cache

### Anything else?

I will send a PR to fix that shortly. It may fix #3692 in a better way than the #3756

### Affected Versions

9.12.0 (latest release)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by david-poindexter** [comment]
Great catch @valadas 🎉
