### ISSUE TITLE
[Bug]: Accidental deletion of folder in ResourceManager when drilling down in the items view

### ISSUE THREAD

**Issue by coretoco** [dnnsoftware/Dnn.Platform#5758]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When on the new resource manager to select a folder in the items view the user can doubleclick to open the folder.
If this doubleclick happens after a single click on the folder, the folder will not only be opened, but also selected.
This because every click executes a select / unselect of the clicked item.

Users drilling down to a file might therefore accidentally also select a folder.
If the user wants to delete the file also the folder is deleted.

### Steps to reproduce?

1. Go to {website}Admin/File-Management
2. SingleClick on a folder in the items view
3. Doubleclick on same folder to drill down
4. Repeat until a file is available
5. Select the file and click on delete

### Current Behavior

Drilling down in the items list leads to accidental selection of folders. (not good)
In this case the delete confirmation popup shows the folder and the file to be deleted (correct), confirming the deletion deletes the file and the selected folder. (also correct)

### Expected Behavior

Double clicking a folder should not select/deselect the folder. The behaviour should be like it was in Version 9.11.00: only drilldown happens..

### Anything else?

This is not a real "bug" as the files as well as the selected folders are clearly visible on the delete confirmation dialog.
But, as the users tend not to read the beaviour leads to the deletion of whole folders.
As those files are hard deleted, they have to be restored from backups.

This behaviour was different on Version 9.11.00 where the double click does not work on the items pane.

### Affected Versions

9.12.0 (latest release)

### What browsers are you seeing the problem on?

Chrome, Microsoft Edge

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mitchelsellers** [comment]
@valadas I believe this is the same as we documented before, grated this one is written with better details.

Thank you @coretoco for documenting

**Comment by coretoco** [comment]
related enhancement: #5352, added in 9.11.01

**Comment by meffj00** [comment]
DNN versie 9.11.0 got the same problem. Why is there no trash-tray?

**Comment by mitchelsellers** [comment]
@meffj00 This is a known item, currently affecting versions through 9.12.0
