### ISSUE TITLE
[Bug]: Setting the `Max Upload Size (MB)` results in unexpected `web.config` values for `requestLengthDiskThreshold`

### ISSUE THREAD

**Issue by david-poindexter** [dnnsoftware/Dnn.Platform#5778]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Currently, updating the `Max Upload Size (MB)` pictured below results in the `maxRequestLength` and `requestLengthDiskThreshold` values being the same.

<img width="404" alt="image" src="https://github.com/dnnsoftware/Dnn.Platform/assets/4568451/9a3f446b-dd5e-451e-850b-4459ac11b70e">

The default for DNN is as follows:
```xml
    <httpRuntime targetFramework="4.7.2" shutdownTimeout="120" executionTimeout="1200" useFullyQualifiedRedirectUrl="true" maxRequestLength="29296" requestLengthDiskThreshold="81920" maxUrlLength="2048" requestPathInvalidCharacters="&lt;,&gt;,*,%,:,\,?" enableVersionHeader="false" requestValidationMode="2.0" fcnMode="Single" />
```

Updating the value for `Max Upload Size (MB)` to `12` in the UI results in the following
```xml
    <httpRuntime targetFramework="4.7.2" shutdownTimeout="120" executionTimeout="1200" useFullyQualifiedRedirectUrl="true" maxRequestLength="12288" requestLengthDiskThreshold="12288" maxUrlLength="2048" requestPathInvalidCharacters="&lt;,&gt;,*,%,:,\,?" enableVersionHeader="false" requestValidationMode="2.0" fcnMode="Single" />
```

Updating the value for `Max Upload Size (MB)` back to `28` in the UI results in the following
```xml
    <httpRuntime targetFramework="4.7.2" shutdownTimeout="120" executionTimeout="1200" useFullyQualifiedRedirectUrl="true" maxRequestLength="28672" requestLengthDiskThreshold="28672" maxUrlLength="2048" requestPathInvalidCharacters="&lt;,&gt;,*,%,:,\,?" enableVersionHeader="false" requestValidationMode="2.0" fcnMode="Single" />
```

For those that don't know, here is the math for calculating:  

```
1 Megabyte = 1024 Kilobyte
```

The result for a value of `28` (MB) in the UI, should translate to a value of `28672` in the `maxRequestLength` value, and it does when saved.  

However, this shows that the default value of `29296` does NOT in fact translate to `28` (MB).  It would translate to approximately `28.61` (MB).  So, if `28` (MB) is our desired default value, we need to update the default `web.config` value accordingly, and ensure the math for the PersonaBar UI is correct in reading/displaying it.

Microsoft default values are as follows: 
* `maxRequestLength` = `4096` (KB)
* `requestLengthDiskThreshold` = `81920` (B)

```
Note: Thank you Microsoft for not making the unit of measurement the same for both of these.  🤦🏼 
```

Based on the default values by Microsoft, it can be implied (as a general rule of thumb) to set the `requestLengthDiskThreshold` to 1.95% of the `maxRequestLength` value.  However, the value of `requestLengthDiskThreshold` should never exceed that of `maxRequestLength` (when converted for the unit of measurement).

So, our calculated values for `maxRequestLength` and `requestLengthDiskThreshold` should be proportionate to the default values set originally by Microsoft.

That said, I believe we should also add another field to the PersonaBar UI to allow manual changes to `requestLengthDiskThreshold` proportionate defaults (calculated when entering `maxRequestLength`), as there are situations where changing this value is warranted and there is currently no way of making these changes in the UI.  A value exceeding `maxRequestLength` should not be allowed.

### Steps to reproduce?

1. Go to `web.config` and note default values for `httpRuntime`
2. Go to `Settings` > `Security` > `More` > `More Security Settings`
3. Change value for `Max Upload Size (MB)`
4. Go to `web.config` and note new values for `maxRequestLength` and `requestDiskThresholdLength` in `httpRuntime`

### Current Behavior

Values for `maxRequestLength` and `requestDiskThresholdLength` in `httpRuntime` are the same after saving in UI.

### Expected Behavior

Values for `maxRequestLength` and `requestDiskThresholdLength` in `httpRuntime` should be based proportionately according to the defaults established by Microsoft.

### Relevant log output

```shell
n/a
```

### Anything else?

We have never, by default, added the following to the `web.config`.  Should we consider adding this?  It is required for working with large files in IIS 7+.  Please note the unit of measurement for `maxAllowedContentLength` is in Bytes (not KB).  🤦🏼 

```xml
<system.webServer>
    <security>
      <requestFiltering>
        <requestLimits maxAllowedContentLength="28672000" />
      </requestFiltering>
    </security>
</system.webServer>
```

### Affected Versions

9.12.0 (latest release), 10.0.0 (alpha)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by david-poindexter** [comment]
@dnnsoftware/approvers let me know your thoughts on this one.  I chose to create only one issue but this is a mix of what I believe is a bug and an enhancement.  We can discuss this at our next meeting if you'd like.

**Comment by jeremy-farrance** [comment]
Two things. Both may be contentious and you should research or test them to your satisfaction.

First, read this about the values in maxRequestLength vs. requestLengthDiskThreshold 
[https://stackoverflow.com/questions/69491511/is-httpruntimes-requestlengthdiskthreshold-in-bytes-or-kilobytes](https://stackoverflow.com/questions/69491511/is-httpruntimes-requestlengthdiskthreshold-in-bytes-or-kilobytes)

Second, my understand (10+ years ago) was that requestLengthDiskThreshold, for small maxRequestLength values should probably be the same. However, once the values get large it is important to allow a smaller, reasonable value for requestLengthDiskThreshold. So I max the rLDT at 64 MBs usually, and below that keep the values the same.

"The RequestLengthDiskThreshold property specifies the input-stream buffering threshold limit in number of bytes. Its value should not exceed the MaxRequestLength property value. After a request entity exceeds this threshold, it is buffered transparently onto disk." (docs at .NET Framework 4.8.1)
 
The thinking is simple, once the mRL value is large, you need to tell/allow IIS to split the upload in to chunks which it writes to disk transparently in the background. In other words, maxRequestLength is the total limit, but while the (large) uploads are in progress, requestLengthDiskThreshold is a buffer size, once reached, it will then write to disk. If you leave the values on large mRL sizes the same, IIS does a very poor job with resources (the upload > memory > temp > final disk storage (the file)).
 
Also, I have been told I am wrong about this nowadays, but I recently needed to allow 2 GB uploads for a client running IIS 10.0. So I set mRL to what I needed and rLDT to 64 MBs. Then on the server you can watch the file size value in explorer going up by 64 MB chunks (with a refresh). Which seemed like pretty good confirmation to me. 
[https://learn.microsoft.com/en-us/dotnet/api/system.web.configuration.httpruntimesection.requestlengthdiskthreshold](https://learn.microsoft.com/en-us/dotnet/api/system.web.configuration.httpruntimesection.requestlengthdiskthreshold)

**Comment by valadas** [comment]
If I understand correctly the requestDiskThresholdLength defines how much is kept in ram until it starts getting moved to disk. So a large value will consume more RAM, and a small value will cause more frequent disk access. I guess it is a trade-off, a tuning value if you need to improve performance regarding limited RAM resources or slow busy spinner disks...
If multiple users can have uploads at the same time, having a large value may huge amounts of RAM.

I don't think this value should be affected by another value so my vote would be to create a new field for it.

**Comment by GerardSmit** [comment]
> If I understand correctly the requestDiskThresholdLength defines how much is kept in ram until it starts getting moved to disk.

Correct.

Noteworthy, `requestLengthDiskThreshold` is also the amount of RAM that's allocated if the `Content-Length` of the file is unknown:

The `_expectedLength` is set to 0 (or -1, not sure), so you'll get an empty array:

https://github.com/microsoft/referencesource/blob/51cf7850defa8a17d815b4700b67116e3fa283c2/System.Web/HttpInputStream.cs#L47-L50

And when bytes are being received, the array is created with the value in `requestDiskThresholdLength`:

https://github.com/microsoft/referencesource/blob/51cf7850defa8a17d815b4700b67116e3fa283c2/System.Web/HttpInputStream.cs#L73-L84

This means, if you have a high value in `requestLengthDiskThreshold` you can run into OutOfMemoryExceptions if a bad actor doesn't send the length.
