### ISSUE TITLE
[Bug]: Can't install current develop branch artifact (clean install)

### ISSUE THREAD

**Issue by valadas** [dnnsoftware/Dnn.Platform#5785]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Doing a full build and using the install zip to install a new site is failing on the installer.

### Steps to reproduce?

1. Clone current develop branch
2. Run a full build (build.ps1)
3. Use nvQuickSite or a manual process to put the files in the hosting folder and create an empty database
4. Visit the site

### Current Behavior

The install fails

### Expected Behavior

The install should work

### Relevant log output

```shell
System.IO.FileNotFoundException: Could not load file or assembly 'System.Web.Http, Version=5.2.9.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies.

and

2023-08-08 13:09:31.748-04:00 [ERROR] DotNetNuke.Data.PetaPoco.PetaPocoHelper - [1] Error executing SQL: ;Exec dbo.GetDatabaseVersion
```

### Affected Versions

9.12.1 (alpha)

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by david-poindexter** [comment]
Did you mean 9.12.1 for the affected version?

**Comment by valadas** [comment]
Yes, but it's not in the options :)

**Comment by valadas** [comment]
Fixed, looks like I can edit the comment after using the form...

**Comment by david-poindexter** [comment]
> Yes, but it's not in the options :)

Well...I guess I need to fix that.  LOL
