### ISSUE TITLE
[BUG]: The persona bar platform menu (1st menu) stays open when moving to another menu option.

### ISSUE THREAD

**Issue by leedavi** [dnnsoftware/Dnn.Platform#5800]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The persona bar platform menu (1st menu) stays open when moving to another menu option.

for mw this happens on Edge and Chrome.  NOT on FireFox.

### Steps to reproduce?

1 Login as HOST
2 Move mouse over 1st persona bar menu (the correct menu appear.)
3.  MOve the mouse down the menu (without moving off it) and the 2nd menu options ontop of the first.  ()

![image](https://github.com/dnnsoftware/Dnn.Platform/assets/5583141/ada45156-33e9-4362-aa1d-ae2fe97c72b7)

### Current Behavior

1st menu stays open

### Expected Behavior

1st menu should close.

### Anything else?

This is not a major issue is you don't go into a menu, but going into a menu opens the persona bar correctly, but the first menu stays open.  You need to refresh the page to work on it.

I did not see this happening on DNN v9.11

### Affected Versions

9.12.0 (latest release)

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mitchelsellers** [comment]
This was addressed in #5771 and will be in the next release

**Comment by leedavi** [comment]
OK, thx.  Sorry I missed the issue.
