### ISSUE TITLE
[Bug]: v9.13.0-rc1 has System.Runtime.CompilerServices.Unsafe in bin folder of upgrade zip

### ISSUE THREAD

**Issue by valadas** [dnnsoftware/Dnn.Platform#5815]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Upgrading a site that had a module using System.Runtime.CompilerServices.Unsafe properly defined it manifest, I got a binding redirect error. The dll got replaced by DNN upgrade zip.

### Steps to reproduce?

1. Install a clean DNN v9.12.x
2. Install a module with System.Runtime.CompilerServices.Unsafe properly defined in its manifest
3. Confirm the binding redirect works in the web.config after installing the module
4. Upgrade to DNN v9.13.0
5. Notice the installer does not fire and a binding redirect error regarding that dependency

### Current Behavior

The DNN v9.13 upgrade.zip has System.Runtime.CompilerServices.Unsafe in its bin folder

### Expected Behavior

Either that file is there by mistake (I only saw that dependency on DNN side of things in tests)

or

We should have a package for it so binding redirects are updated.

### Affected Versions

9.13.0 (release candidate)

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bdukes** [comment]
I've got a fix for this, PR soon

**Comment by valadas** [comment]
Awesome, thanks!
