### ISSUE TITLE
[Bug]: Clean install of dnn913rc2 throws debugger errors

### ISSUE THREAD

**Issue by schotman** [dnnsoftware/Dnn.Platform#5818]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

getting on every page load
![image](https://github.com/dnnsoftware/Dnn.Platform/assets/2582737/7100474a-ac4c-46ed-a10b-079bbfebc054)

### Steps to reproduce?

install dnn 
add pages
switch from one to another

### Affected Versions

9.13.0 (release candidate)

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by valadas** [comment]
It looks like this code relies on Ajax and it is not (or not yet) loaded. I have not seen this being a problem for normal usage of the site though, more of a log annoyance. We should though check if Sys is available before calling upon it...

**Comment by WillStrohl** [comment]
I'm seeing this on a clean installation of Platform 9.13.0 too (today).

**Comment by valadas** [comment]
Should get fixed in 9.13.1 when it releases
