### ISSUE TITLE
[Bug]: Im receiving error "Sys is not defined"

### ISSUE THREAD

**Issue by ufoloko** [dnnsoftware/Dnn.Platform#5839]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Im viewing error "Sys is not defined" on console, for file dnn.jquery.js?cdv=47 line 4319

### Steps to reproduce?

Install last version of DNN 9.13.0, then login as super admin and show development tools, you should see on console the mentioned error

### Relevant log output

```shell
Uncaught ReferenceError: Sys is not defined
    at dnn.jquery.js?cdv=47:4319:5
    at dnn.jquery.js?cdv=47:4323:3
(anónimas) @ dnn.jquery.js?cdv=47:4319
(anónimas) @ dnn.jquery.js?cdv=47:4323
```

### Affected Versions

9.13.0 (latest release)

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jeremy-farrance** [comment]
I have seen this too on 9.13.00. Though I have done nothing to investigate yet, I just wanted to mention that the above is not a one-off. If its any help, here is a screenshot showing the line throwing the error. BTW, this is from a quick install using (the amazing and wonderful) nvQuickSite.

![image](https://github.com/dnnsoftware/Dnn.Platform/assets/653301/bc8641b5-4938-4d85-bea4-af9252445c6b)

**Comment by valadas** [comment]
Yes it duplicates #5818 I'll close this one to keep the oldest existing one. They are linked so it is easy to see both from the oldest.
