### ISSUE TITLE
[Bug]: Replace Tokens in HTML module settings gets Unchecked after upgrade

### ISSUE THREAD

**Issue by Mike35538** [dnnsoftware/Dnn.Platform#5844]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

During a test upgrade from DNN 9.10.02 to 9.13.00 any module that had Replace Tokens enabled (check marked) in the HTML Module Settings was changed to disabled (or no longer check marked) after the upgrade. This occurred in every html module across every portal in the DNN installation that had the Replace Tokens enabled under HTML Module Settings. Which caused the token to display on the website since it was no longer parsed.

### Steps to reproduce?

Have a html module using a token before upgrade with Replace Tokens enabled (check marked) in the HTML Module Settings. Upgrade to 9.13.00 and the Replace Tokens box is unchecked.

### Affected Versions

9.13.0 (latest release)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Mike35538** [comment]
Additional information...
Looks to have something to do with clearing the cache.

If you have a module with Replace Tokens enabled (check marked) in the HTML Module Settings and it is correctly parsing the tokens, then you go to Servers and hit the Clear Cache button, it actually removes the checkmark from Replace Tokens in the HTML Module Settings and then the tokens are no longer parsed in the html content.

**Comment by GerardSmit** [comment]
Maybe this is caused by https://github.com/dnnsoftware/Dnn.Platform/pull/5742?

I'm not experienced with the caching of modules, so this is just a guess: the cache key is now set to the portal ID. Doesn't this mean 2 modules can get the same cache (since they are both in the same portal)?

**Comment by bdukes** [comment]
@valadas That makes sense to me, that the change introduced cache conflicts between modules in the same portal. I think the right approach is to include both the portal ID and tab module ID in the cache key, and then clear anything with the portal ID prefix whenever there's a change. Does that sound like it would work better? Are we missing something that is preventing conflicts?

**Comment by valadas** [comment]
@bdukes did you intend to ping me about this or someone else ?

**Comment by bdukes** [comment]
Sorry, wasn't clear about that. I did intend to ping you b/c #5742 was your PR.

**Comment by valadas** [comment]
Ok, good point, let me put my thinking hat here...

**Comment by valadas** [comment]
@bdukes I think your suggestion makes sense. We also have hostGuid and portalGuid we could leverage potentially... Unfortunately we don't have guids on the lower levels for modules and tabModules... But yeah, I feel like we probably need a compount cache-key here is some fashion.

**Comment by Mike35538** [comment]
@bdukes thanks for helping with this bug. Is there a patch that I can apply now, or do I just wait until 9.13.01 comes out? This bug is a pretty big hindrance to upgrading to 9.13.00. Thanks

**Comment by valadas** [comment]
Well if you just want to test it out you can download a "nightly build" from here: https://dev.azure.com/dotnet/DNN/_build/results?buildId=99491&view=artifacts&pathAsName=false&type=publishedArtifacts

However this is not an official release yet, so for production use I would wait on 9.13.1, which I believe could be done quickly...

**Comment by Mike35538** [comment]
@valadas ok thanks for the info, I'll wait for the official 9.13.1. Thanks for your contributions to the platform!
