### ISSUE TITLE
[Bug]: Resource manager stopped loading after 9.13 upgrade

### ISSUE THREAD

**Issue by enfJoao** [dnnsoftware/Dnn.Platform#5862]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Resource manager does not load after upgrading a 9.11 install to 9.13.

### Steps to reproduce?

1. Open any page with resource manager module.

### Relevant log output

```shell
Uncaught ReferenceError: Sys is not defined
    <anonymous> https://a.b.pt/DependencyHandler.axd/4441d4162baee209bf0fce4aefed650d/257/js:361
    <anonymous> https://a.b.pt/DependencyHandler.axd/4441d4162baee209bf0fce4aefed650d/257/js:361
js:361:2071
GET
https://a.b.pt/DesktopModules/ResourceManager/Scripts/dnn-resource-manager/p-d40a4dd7.entry.js

Loading module from “https://a.b.pt/DesktopModules/ResourceManager/Scripts/dnn-resource-manager/p-d40a4dd7.entry.js” was blocked because of a disallowed MIME type (“text/html”).
File-Management
Loading failed for the module with source “https://a.b.pt/DesktopModules/ResourceManager/Scripts/dnn-resource-manager/p-d40a4dd7.entry.js”. File-Management:238:117
TypeError: error loading dynamically imported module: https://a.b.pt/DesktopModules/ResourceManager/Scripts/dnn-resource-manager/p-d40a4dd7.entry.js undefined p-7f611392.js:1:10722
Uncaught (in promise) TypeError: can't access property "isProxied", o is undefined
    rt p-7f611392.js:1
    ut p-7f611392.js:1
    connectedCallback p-7f611392.js:1
    jmp p-7f611392.js:1
    connectedCallback p-7f611392.js:1
    dt p-7f611392.js:1
    dt p-7f611392.js:1
    <anonymous> patch-browser.js:65
    promise callback* patch-browser.js:65
p-7f611392.js:1:8676
Some cookies are misusing the recommended “SameSite“ attribute 13
Source map error: Error: request failed with status 404
Resource URL: https://a.b.pt/DesktopModules/ResourceManager/Scripts/dnn-resource-manager/p-7f611392.js
Source Map URL: p-7f611392.js.map
```

### Affected Versions

9.13.0 (latest release)

### What browsers are you seeing the problem on?

Firefox

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bdukes** [comment]
Is this a duplicate of https://github.com/dnnsoftware/Dnn.Platform/issues/5818 & #5839? Those were resolved by #5845, which will be included in the 9.13.1 release.

**Comment by enfJoao** [comment]
Could be.
But no one described implications on resource manager. Nor the other errors no log.

**Comment by bdukes** [comment]
If you follow that link, do you get an error page (maybe a 404)?

**Comment by enfJoao** [comment]
The file returns 404 on website.
Browsing the server files, /DesktopModules/ResourceManager/Scripts/dnn-resource-manager/p-d40a4dd7.entry.js actually does not exist also.

My IIS .js mime type is application/javascript

This is the only this I could find in IIS logs.
2023-11-07 22:54:27 192.168.1.150 GET /DesktopModules/ResourceManager/Scripts/dnn-resource-manager/p-d40a4dd7.entry.js - 443 - 77.54.153.194 Mozilla/5.0+(Windows+NT+10.0;+Win64;+x64;+rv:120.0)+Gecko/20100101+Firefox/120.0 - 404 0 2 49

**Comment by valadas** [comment]
Does it exist on disk ?
Did you try clearing browser cache ?
Do you have something in between like cloudflare that may need its cache cleared ?

**Comment by enfJoao** [comment]
This is turned to be an weird issue. I can replicate it always in one pc, randomly on a second pc and never on a third. It's also inconsistent between browsers. I'll close it for now since it is probably related to client side issues.
