### ISSUE TITLE
[Bug]: Unable to delete Legacy UA connection

### ISSUE THREAD

**Issue by cklenk** [dnnsoftware/Dnn.Platform#5867]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Upgrade DNN site to 9.13.0
Went to connections
Tried to delete Legacy UA connection
Does not delete connection
Console error
![image](https://github.com/dnnsoftware/Dnn.Platform/assets/12185742/ad814be7-f958-492b-a56c-ee114fbfb639)
![image](https://github.com/dnnsoftware/Dnn.Platform/assets/12185742/18e4e661-8486-4ab2-9a45-11b889f12cb3)

### Steps to reproduce?

1. Go to settings
2. Go to connections
3. Try to delete existing Legacy UA connection

### Current Behavior

Unable to delete connection

### Expected Behavior

Delete legacy UA connection

### Relevant log output

```shell
jquery.js?cdv=595:2  Uncaught Error: Syntax error, unrecognized expression: #connector-GoogleAnalytics(LegacyUA)
    at I.error (jquery.js?cdv=595:2:11769)
    at Y (jquery.js?cdv=595:2:17234)
    at re (jquery.js?cdv=595:2:20008)
    at Function.I [as find] (jquery.js?cdv=595:2:7520)
    at ce.fn.init.find (jquery.js?cdv=595:2:21991)
    at new ce.fn.init (jquery.js?cdv=595:2:22483)
    at ce (jquery.js?cdv=595:2:1077)
    at Connectors.js?cdv=595:181:45
```

### Affected Versions

9.13.0 (latest release)

### What browsers are you seeing the problem on?

Microsoft Edge

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by valadas** [comment]
Good catch, the element ID is probably driven by the module name and parenthesis can't be used for an element id.

**Comment by X3Technology** [comment]
Also cannot update an existing Connector.  I cant change the value for Google Tag Manager

**Comment by david-poindexter** [comment]
Ah - great catch!  I'll see if I can look into this during tomorrow's co-coding session on Discord if nobody else has addressed it by then.

**Comment by david-poindexter** [comment]
Closing per #5972
