### ISSUE TITLE
[Bug]: DNN Azure Connected File Uploads Very Slowly, Multiple Files Queued: Uploads Fail

### ISSUE THREAD

**Issue by dgingold** [dnnsoftware/Dnn.Platform#5877]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Using the Resource Manager to upload files into an Azure folder, or using the CKEditor [Browse Server] to upload files into the Azure folder, or using PlantAnApp File Upload fieldtype to upload a file to an Azure folder, in all cases, the action takes 45-60 seconds and longer for even the smallest files. Also, in any of the same scenarios, when files are queued up to upload, they fail ("provider reported an error"). 

### Steps to reproduce?

1. running on 9.11.2 (the latest DNN version supported by PlantAnApp)
2. installed and connected the DNN Azure Connector to an Azure blob.
3. Use any file functions (ckeditor, resource manager) to upload one or more files
4. the upload returns only after a very long time (45-70 seconds for 100K pdf, for example)

### Current Behavior

when i upload a file via resource manager or ckeditor into an Azure Connected folder, the operation takes a very long time to finish. when I queue several files for upload in either resource manager or ckeditor, the first in the queue will finish successfully after the 45-70 seconds, and the rest will fail.

### Expected Behavior

once a file is uploaded to the Azure connected folder, it can be downloaded at speeds similar to files stored on the site. Also, using the Mac desktop app Microsoft Azure Storage Explorer, the files can be uploaded at speeds similar to any remote storage, so I expect that the upload through the website should be executed at similar speeds.

### Relevant log output

```shell
no log output.
```

### Anything else?

The site exhibiting the issue is a production site for a county government. A department within the county is consolidating - they were their own (non-DNN) site, now they are a submenu of the main site. They are the clerk's office and have 30GB of files to store, hence the choice of offsite storage. We are about to launch the new consolidated site and the client is complaining of the slow speed of uploads. We are willing to assist if desired and definitely to sponsor the effort, and are willing to work with a patched version of the connector while any correction is blended back into the project.

### Affected Versions

9.13.0 (latest release)

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dgingold** [comment]
I appreciate it! I’ll see you on discord tomorrow.

Don

**Comment by david-poindexter** [comment]
Awesome, here's the link to the Discord event tomorrow:  https://discord.com/channels/706654343176126496/1037703726196068355/1179970755543437352

@valadas and I did some testing on this tonight for ya, so we are ready to discuss.

**Comment by david-poindexter** [comment]
Based on testing, we'll go ahead and close out this issue, as it seems to be outside of the DNN purview.  The out of box experience seems good from a DNN Platform perspective.
