### ISSUE TITLE
[Bug]: Losing all the styling if edited from Html editor

### ISSUE THREAD

**Issue by sanjayy-metasyssoftware** [dnnsoftware/Dnn.Platform#5882]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Hi,
My Name is Sanjay Yadav, i am a dot net nuke developer.

I am using DNN version 09.13.00, while editing the contents through text editor used in html module we are losing all the styling of html inside text editor.

I have attached two images for your reference image1 is original html with style, when i try to edit it looks like image 2 which is without the styling.
![1](https://github.com/dnnsoftware/Dnn.Platform/assets/153734517/472f0689-d5cd-407f-a1a1-278baddb069e)
![2](https://github.com/dnnsoftware/Dnn.Platform/assets/153734517/dcd5b952-ef63-410d-b9b9-aca6b4759849)

Regards,
Sanjay Yadav  

### Steps to reproduce?

I have attached two images for your reference image1 is original html with style, when i try to edit it looks like image 2 which is without the styling.

### Affected Versions

9.13.0 (latest release)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by valadas** [comment]
The idea is that the editor will only accept html that could have been generated by its toolbar settings and the tool bar would not have used color names (I guess here). In other words, it's not a great code editor and if you want to write your own html, it is recommended to use pain editing (not wysiwyg).

To do so you want to change the dropdown to "Basic textbox" which will then allow to do plain text, html or raw:
![image](https://github.com/dnnsoftware/Dnn.Platform/assets/6371568/5c0b543b-ced3-4c35-ba56-8176dad0d9b9)
