### ISSUE TITLE
[Enhancement]: Open file in Resource Manager

### ISSUE THREAD

**Issue by HenrikSH** [dnnsoftware/Dnn.Platform#5885]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of problem

The users of a company intranet site have been used to opening files from the Digital Assets Manager folder just by doubleclicking af file item from the list. 
It appears that this isn't possible when you are using Resource Manager. 

### Description of solution

Open files from files list just by doubleclicking an item.  Image and pdf files can open directly in the browser and files in other formats will just be downloaded.

### Description of alternatives considered

Add an icon like the current ones for Download and Copy url (to clipboar) for opening files. Image and pdf files can open directly in the browser and files in other formats will just be downloaded.

### Anything else?

![Open_file_in_Resource_Manager](https://github.com/dnnsoftware/Dnn.Platform/assets/1736459/dec0a307-e5ab-4598-ab4f-b502cbca6262)
I might be able to contribute with code for this enhancement but as haven't done it before it might require too many steps and delivery therefore take too long.

### Do you be plan to contribute code for this enhancement?

- [ ] Yes

### Would you be interested in sponsoring this enhancement?

- [ ] Yes

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by WillStrohl** [comment]
FYI - This is related to [a community conversation in the DNN Community Forums](https://dnncommunity.org/forums/using-dnn/extensions/1-resource-manager/).

**Comment by stetard** [comment]
In my point of view, it could make sense.
If the community members are OK with this suggestion, I think I can do the modification.

**Comment by valadas** [comment]
Yeah, the logic is already there to copy url, so that url can just be used to add a button to open a file (and a double-click handler that does the same).

**Comment by valadas** [comment]
@stetard that project should work with the documented `yarn watch --scope {packageName}` thing, if you get confused in there I can help in our co-coding sessions we do almost weekly on discord https://discord.gg/NRa6t8Af

**Comment by stetard** [comment]
I think I'd prefer to implement the double click solution which I think it's more efficiently.
Is it ok for you?

**Comment by valadas** [comment]
I would prefer there be an accessible way too because all the rest of the module is.

**Comment by HenrikSH** [comment]
Yes, the doubleclick solution is good because it is kind of intuitive and at the same time it is a nice thing to keep the Copy url button significantly in the tab bar above with the Download option.Sendt fra min Galaxy
-------- Oprindelig besked --------Fra: Stéphane Tétard ***@***.***> Dato: 18.12.2023  20.22  (GMT+01:00) Til: "dnnsoftware/Dnn.Platform" ***@***.***> Cc: HenrikSH ***@***.***>, Author ***@***.***> Emne: Re: [dnnsoftware/Dnn.Platform] [Enhancement]: Open file in Resource
  Manager (Issue #5885) 
I think I'd prefer to implement the double click solution which I think it's more efficiently.
Is it ok for you?
