### ISSUE TITLE
Language Flags missing (if you are logged out) after: Enable Localized Content.

### ISSUE THREAD

**Issue by LukeIT65** [dnnsoftware/Dnn.Platform#5896]
With versions 9.12, 9.13 and 9.13.1 I still encounter the same problem of the language flags no longer being visible (when you are logged out) ; it happens exactly as soon as I perform step 4 :

1. Add New Language;
2. Enable Language;
3. Allow Content Localization;
4. Enable Localized Content.

But, if I "Disable Localized Content" the language flags reappear.

_Originally posted by @LukeIT65 in https://github.com/dnnsoftware/Dnn.Platform/issues/4273#issuecomment-1870078839_

**Comment by valadas** [comment]
Closing as it duplicates #4273 and it was not reproducible, make sure you follow all the steps I mentioned in that issue.

If you do not turn on "Users May Choose Interface Language" or you are not on a page with a **published** localized version, then there is no reason for the language switcher to show.
