### ISSUE TITLE
[Bug]: Cannot "unselect" Google Analytics (Legacy UA) connector

### ISSUE THREAD

**Issue by skarpik** [dnnsoftware/Dnn.Platform#5900]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I have a website that had the Google Analytics (Legacy UA)  connector enabled. I wanted to use the Google Tag Manager connector. I set that connection up with no problem. But then I cannot delete the Google Analytics (Legacy UA)  connector - a JavaScript error results.

### Steps to reproduce?

1. Started with an older website that has been upgraded to DNN v9.13.1.
2. Successfully added the Google Tag Manager connector.
3. Failed at deleting the Google Analytics (Legacy UA) connector.
4. Found a JavaScript error (see below).
5. Now it looks like both the Google Analytics (Legacy UA) and Google Tag Manager connectors are enabled.

<img width="722" alt="Screenshot 2024-01-01 004150" src="https://github.com/dnnsoftware/Dnn.Platform/assets/3846223/c3b7fa3f-2f9a-45de-983d-6341f7d9dd78">

### Current Behavior

JavaScript error after clicking "Delete Connection".

jquery.js?cdv=216:2  Uncaught Error: Syntax error, unrecognized expression: #connector-Google Analytics (Legacy UA)
    at I.error (jquery.js?cdv=216:2:11769)
    at Y (jquery.js?cdv=216:2:17234)
    at re (jquery.js?cdv=216:2:20008)
    at Function.I [as find] (jquery.js?cdv=216:2:7520)
    at ce.fn.init.find (jquery.js?cdv=216:2:21991)
    at new ce.fn.init (jquery.js?cdv=216:2:22483)
    at ce (jquery.js?cdv=216:2:1077)
    at saveConnection (Connectors.js?cdv=216:305:34)
    at Object.save (Connectors.js?cdv=216:132:21)
    at Object.action (connector.js?cdv=216:107:30)

### Expected Behavior

The delete button should delete the legacy connector when clicked on.

### Affected Versions

9.13.0 (latest release)

### What browsers are you seeing the problem on?

Firefox, Chrome, Microsoft Edge

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by david-poindexter** [comment]
@skarpik thanks for logging this issue.

@bdukes I took a quick look and see this is related to that code section that we had some trouble with a while back (not able to save when tracking for admins).  I didn't have time to dig too deep, but thought I would mention you just in case you have time before me.
