### ISSUE TITLE
[Bug]: `Manage` > `Users` > `Profile Settings` uses site default theme layout and container when popups are disabled

### ISSUE THREAD

**Issue by david-poindexter** [dnnsoftware/Dnn.Platform#5946]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When popups are disabled...

![image](https://github.com/dnnsoftware/Dnn.Platform/assets/4568451/1f62a8d1-3e8a-4998-8dac-e54e3a4ece09)

The wrong theme layout and container is used for `Manage` > `Users` > `Profile Settings`.  It should use the fallback `_default` theme popup layout and container regardless of whether or not popups are enabled.

### Steps to reproduce?

1. Login as a super user (or administrator)
2. Disable popups in `Settings` > `Site Settings` > `Site Behavior` > `More`
3. Refresh page
4. Go to `Manage` > `Users`
5. Click `Profile Settings` for any user

### Current Behavior

![image](https://github.com/dnnsoftware/Dnn.Platform/assets/4568451/e9dd579f-11d3-4759-8e04-d9a2ccceaa91)

### Expected Behavior

![image](https://github.com/dnnsoftware/Dnn.Platform/assets/4568451/96be3ca8-74c0-4e4b-9c2b-ebb399a1d43e)

### Affected Versions

9.13.2 (latest release), 9.13.3 (alpha), 10.0.0 (alpha)

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jeremy-farrance** [comment]
I doubt its relevant to solving the issue, but for the sake of any future searches, in PortalSettings this is EnablePopUps.
