### ISSUE TITLE
[Quickie/Minor]: DNN v10's Aperture Theme Still Has "gulpfile.js" on Line 5 of package.json

### ISSUE THREAD

**Issue by jeremy-farrance** [dnnsoftware/Dnn.Platform#5963]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Though Gulp was removed, I noticed a reference still existing in package.json to "gulpfile.js" - needs to be removed or replaced with whatever is more appropriate or correct now for "main".

### Steps to reproduce?

Here a link to the file in the v10 branch 
[https://github.com/dnnsoftware/Dnn.Platform/blob/release/10.0.0/DNN%20Platform/Skins/Aperture/package.json](https://github.com/dnnsoftware/Dnn.Platform/blob/release/10.0.0/DNN%20Platform/Skins/Aperture/package.json)

### Affected Versions

10.0.0 (alpha)

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by david-poindexter** [comment]
Closing per #5965
