### ISSUE TITLE
[Bug]: Sorting (A-Z) members of roles

### ISSUE THREAD

**Issue by meffj00** [dnnsoftware/Dnn.Platform#5994]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

We manage a very large DNN site with different role groups and roles. The members of a role are now shown interchangeably. It would be nice if these were shown alphbetic (A-Z).

### Steps to reproduce?

1. Log in as Administrator
2. Choose in the admin personabar for Roles
3. Select a role with a lot of members

### Current Behavior

Notes that the members of the group are not shown to be alphabetic.

### Expected Behavior

Notes that the members of the group must be shown alphabetic (A-Z).

### Affected Versions

9.13.2 (latest release)

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aspelt** [comment]
This should be marked as an enhancement.
