### ISSUE TITLE
CodeDom installation PR got somehow undone

### ISSUE THREAD

**Issue by valadas** [dnnsoftware/Dnn.Platform#5999]
https://github.com/dnnsoftware/Dnn.Platform/pull/5690 was done and merged to install CodeDOM by default but apparently this got somehow undone in the release/10.0.0 branch and it is still distributed as a .resources file. My guess is that was some bad rebase....

**Comment by david-poindexter** [comment]
CC @bdukes - fyi

**Comment by bdukes** [comment]
Pushed a fix

**Comment by david-poindexter** [comment]
Closing issue per https://github.com/dnnsoftware/Dnn.Platform/pull/6002
