### ISSUE TITLE
[Bug]: User Role from one site is wrongly propogated to other sites

### ISSUE THREAD

**Issue by anurag-singh-df** [dnnsoftware/Dnn.Platform#6004]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

This issue is reported by EVOQ customer - https://github.com/trilogy-group/eng-maintenance/issues/7339
There's an issue with how user permissions are managed. Users assigned as Content Editors on one site are wrongly getting access to edit content on other sites too in the same Site Group.

### Steps to reproduce?

- Install a 9.13.2 version software
- Create a new site named "portal1" on the instance.
- Create a site group, keeping the original site (portal0) as the master. Remember to assign the other site (the non-master) to the group.
- Create a new user named "new_user".
- In portal1 site, Grant "new_user" the Content Editor role, allowing them to edit content and access the persona bar. 
- Log in as new_user. They erroneously have Content Editor access on both sites (Portal1) and Portal0, although they should only have Content Editor access to Portal1.

### Current Behavior

As long as the sites are in the same site group, a user assigned the Content Editor role on one portal will have the same access to other portals

### Expected Behavior

A user assigned the Content Editor role on one portal should only access to that specific portal.

### Affected Versions

9.13.3 (latest release)

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by anurag-singh-df** [comment]
This issue is a copy of https://github.com/trilogy-group/eng-maintenance/issues/7339

**Comment by aaiordac** [comment]
@zyhfish says this issue is already solved by PR https://github.com/dnnsoftware/Dnn.Platform/pull/5976 . @anurag-singh-df can you please check and update our Tempo ticket accordingly?

**Comment by anurag-singh-df** [comment]
@aaiordac , this is correct. PR closed - https://github.com/dnnsoftware/Dnn.Platform/pull/6005#issuecomment-2023252009
