### ISSUE TITLE
[Bug]: In pagemenu Open link in new window doesn't work to a PDF-file

### ISSUE THREAD

**Issue by meffj00** [dnnsoftware/Dnn.Platform#6008]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Open the pagemenu and create a page to a pdf file. I have selected the Open Link in new window.  The PDF-file opens in the menu but not in a new window.

### Steps to reproduce?

open pagemenu
create a page to a pdf file
Open Link  in new window is selected
PDF-file open in the menu but not in a new windows

### Current Behavior

  PDF file doesn't open in a new window

### Expected Behavior

PDF file should open in a new window

### Affected Versions

9.13.3 (latest release)

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jeremy-farrance** [comment]
What theme (or skin) are you using? 
 
I just tried it in v9.13.03 and made sure the current page was using Xcillion and it worked as expected; opened in a new tab which Chrome then switched to a download and closed the new tab. 

My test settings on a clean-new DNN instance.
![image](https://github.com/dnnsoftware/Dnn.Platform/assets/653301/c3ed584f-eae0-40b0-ad09-42f965ae2cbe)

**Comment by valadas** [comment]
I have seen this often. That checkbox only provides the information to the menu system. If the site is using a theme where that property is not implemented properly then it will not open in a new tab or window. I will close this as it is not reproducible with the provided theme. 

If you need an example to fix your theme/menu implementation it is the `[?TARGET]` property that makes it open in a new tab/window here https://github.com/dnnsoftware/Dnn.Platform/blob/develop/DNN%20Platform/Skins/Xcillion/Skin/Menus/MainMenu/MainMenu.txt

**Comment by meffj00** [comment]
Thanks for your answers. I will look in our 'custom made' skin.
