### ISSUE TITLE
[Bug]: Cannot use Office365 OAUT2 

### ISSUE THREAD

**Issue by fablaser** [dnnsoftware/Dnn.Platform#6037]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The configuration of oauth2 has been completed, anyway I cannot send emails from DNN

### Steps to reproduce?

1. Configure oauth2 filling tenantid, appid and secrets
2. Authenticate
3. Send test email

### Current Behavior

Emails are not sent. An authentication failure error occurs. If you change SMTP address with another one, the error will be different, so DNN continues to use SMTP address instead of Exchange connection. 
![oauth dnn 2](https://github.com/dnnsoftware/Dnn.Platform/assets/52076393/c5a04c76-3ce9-48ab-997c-cd1a1e707947)

### Affected Versions

9.13.3 (latest release)

### What browsers are you seeing the problem on?

Firefox, Chrome, Microsoft Edge

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by fablaser** [comment]
wrong info, configuration is working

**Comment by adamsadler** [comment]
Hi @fablaser - sorry for commenting on a closed issue, but I've seen a few posts from you on various related issues and wanted to know if you could share details about how you resolved this.

As you're no doubt aware, there is a lack of any documentation out there for setting DNN up to use Office 365 OAuth, and plenty of people are experiencing the same 5.7.3 issue when attempting to send an email.

I assume I've set my Entra app okay as I can complete the authorisation step, but I just don't know how to troubleshoot the sending error. I've tried various combinations of API permissions, including those that work in an equivalent Entra app used by a desktop app, but still had no luck.

As a minimum, I've added the _Office 365 Exchange Online_ -> _SMTP.SendAsApp_ Application permission and granted access for the entire tenant.

If you have any details at all that might help, I'd very much appreciate hearing them. Even just a confirmation that the API permission is correct or incorrect would be a step further than where I am!

**Comment by fablaser** [comment]
Hello, 
you should add your website url under "authentication" (ie https://yourwebsiteurl/Providers/SmtpOAuthProviders/ExchangeOnline/Authorize.aspx).

The authorization should be: 
Office365 Exchange online:  full_access_as_app  (application)
Microsoft Graph: User.Read.All and  EWS.AccessAsUser.All (both delegate)

Then try to authenticate in DNN. I hope it will help you

**Comment by jeremy-farrance** [comment]
@fablaser - can you add a screenshot? I can't figure out where you are entering this info.

**Comment by fablaser** [comment]
> @fablaser - can you add a screenshot? I can't figure out where you are entering this info.

![App_2](https://github.com/user-attachments/assets/d2378e8b-9a30-4760-8ffb-9a36badd760e)
![app_1](https://github.com/user-attachments/assets/e9977a4e-dd00-4fe6-af64-384e2e8a8180)

**Comment by adamsadler** [comment]
Thanks @fablaser, I really appreciate you taking the time to respond.

I've tried using those API permissions and then successfully re-authorising, but we still receive the same error when attempting to send.

For completeness, this is our setup:

### Entra App

Web app with a Redirect URI in the correct form - https://oursite.com/Providers/SmtpOAuthProviders/ExchangeOnline/Authorize.aspx - and a client secret has been generated.

![entra-001](https://github.com/user-attachments/assets/27e6136e-caa0-4329-90aa-8a0b9cd68a31)

#### API Permissions

We have tried adding just the Office 365 Exchange Online -> SMTP.SendAsApp Application permission and granted access for the entire tenant, along with various combinations of other SMTP and Mail permissions, and we have also tried adding the ones you previously suggested.

The current permissions are as follows:

![entra-002](https://github.com/user-attachments/assets/d4d714d5-da75-40cd-ae8e-f903f01bf3c9)

I've checked the latest DNN source code and it uses ```https://outlook.office.com/.default``` as the scope when requesting tokens, so as per my understanding, it just uses whatever permissions are configured in the Entra app upfront.

### DNN

The email settings have been configured as shown below, using the correct Tenant Id, Client Id and Client Secret for the Entra app.

![dnn-email-settings](https://github.com/user-attachments/assets/3e0f9825-8042-4b40-9130-f51b4f54743c)

The Host email matches the email address of the host user, which is the user used for testing.

I can also confirm that ```MailKitMailProvider``` is the default provider in web.config.

As you can see, we have been able to complete the authorisation, however, we receive the following error when testing the configuration:

```535: 5.7.3 Authentication unsuccessful [LO4P123CA0363.GBRP123.PROD.OUTLOOK.COM 2024-10-02T14:19:32.999Z 08DCE1C9CF0E8B18]```


Bizarrely (well, to me anyway) we have a similar integration working in a .NET Framework desktop app that also uses MailKit (with a suitably different Entra app) without any issues at all; and that Entra app doesn't have any API permissions configured beyond ```https://graph.microsoft.com/User.Read``` - which I think is just there by default when you create the app.

If either you or @jeremy-farrance can see anything in the above that appears incorrect or problematic, or if you have any suggestions at all, then I would be very grateful.

**Comment by fablaser** [comment]
> Thanks @fablaser, I really appreciate you taking the time to respond.
> 
> I've tried using those API permissions and then successfully re-authorising, but we still receive the same error when attempting to send.
> 
> For completeness, this is our setup:
> ### Entra App
> 
> Web app with a Redirect URI in the correct form - https://oursite.com/Providers/SmtpOAuthProviders/ExchangeOnline/Authorize.aspx - and a client secret has been generated.
> 
> ![entra-001](https://private-user-images.githubusercontent.com/12512426/372940183-27e6136e-caa0-4329-90aa-8a0b9cd68a31.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc4ODc3NDksIm5iZiI6MTcyNzg4NzQ0OSwicGF0aCI6Ii8xMjUxMjQyNi8zNzI5NDAxODMtMjdlNjEzNmUtY2FhMC00MzI5LTkwYWEtOGEwYjljZDY4YTMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDAyVDE2NDQwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdmNzVmY2ViOTExZjc2NzMyNjNhMDI1N2QwYjQ5M2I0NWY0OTY2OWY3ZTY5NjY5M2NlMTkyOGU2NzdkMzNhZGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ivi7UHWx9gLZpaz7Rf5dx0Ty0Sa6kXcOxE2brUvjdzg)
> #### API Permissions
> 
> We have tried adding just the Office 365 Exchange Online -> SMTP.SendAsApp Application permission and granted access for the entire tenant, along with various combinations of other SMTP and Mail permissions, and we have also tried adding the ones you previously suggested.
> 
> The current permissions are as follows:
> 
> ![entra-002](https://private-user-images.githubusercontent.com/12512426/372940397-d4d714d5-da75-40cd-ae8e-f903f01bf3c9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc4ODc3NDksIm5iZiI6MTcyNzg4NzQ0OSwicGF0aCI6Ii8xMjUxMjQyNi8zNzI5NDAzOTctZDRkNzE0ZDUtZGE3NS00MGNkLWFlOGUtZjkwM2YwMWJmM2M5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDAyVDE2NDQwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQwMTM4ZmMzODhlYjJjNDlmODM3NDk2OWI3ZWZlYWRkZjRhZmY4N2RkYjFjODgyNWFjZDhkNzNlZWZjNjQyMWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.3Ai0XargOnDVUJJFgcTQsa0y7c8uvGNqnQRQGjCRg1I)
> 
> I've checked the latest DNN source code and it uses `https://outlook.office.com/.default` as the scope when requesting tokens, so as per my understanding, it just uses whatever permissions are configured in the Entra app upfront.
> ### DNN
> 
> The email settings have been configured as shown below, using the correct Tenant Id, Client Id and Client Secret for the Entra app.
> 
> ![dnn-email-settings](https://private-user-images.githubusercontent.com/12512426/372941480-3e0f9825-8042-4b40-9130-f51b4f54743c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc4ODc3NDksIm5iZiI6MTcyNzg4NzQ0OSwicGF0aCI6Ii8xMjUxMjQyNi8zNzI5NDE0ODAtM2UwZjk4MjUtODA0Mi00YjQwLTkxMzAtZjUxYjRmNTQ3NDNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDAyVDE2NDQwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUyYzU2MTUyMTc5M2FiYTIyNTFmYWE3NmQxOTZmNGZkZjhiODM1NDQxYTkzMjhmMGU0ZWFkMjUzMDAwNDdjYTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.3JqcK02QoAgOT4j8PP0GdenCswQZVvsuKZYWQLw5fkY)
> 
> The Host email matches the email address of the host user, which is the user used for testing.
> 
> I can also confirm that `MailKitMailProvider` is the default provider in web.config.
> 
> As you can see, we have been able to complete the authorisation, however, we receive the following error when testing the configuration:
> 
> `535: 5.7.3 Authentication unsuccessful [LO4P123CA0363.GBRP123.PROD.OUTLOOK.COM 2024-10-02T14:19:32.999Z 08DCE1C9CF0E8B18]`
> 
> Bizarrely (well, to me anyway) we have a similar integration working in a .NET Framework desktop app that also uses MailKit (with a suitably different Entra app) without any issues at all; and that Entra app doesn't have any API permissions configured beyond `https://graph.microsoft.com/User.Read` - which I think is just there by default when you create the app.
> 
> If either you or @jeremy-farrance can see anything in the above that appears incorrect or problematic, or if you have any suggestions at all, then I would be very grateful.

I think you are using a wrong DNN configuration. Try Outlook.office.com without any port. I cannot check right now (David Gilmour concert! 😁) but the server address you used is indeed wrong.

**Comment by jeremy-farrance** [comment]
> 
> I think you are using a wrong DNN configuration. Try Outlook.office.com without any port. I cannot check right now (David Gilmour concert! 😁) but the server address you used is indeed wrong.


Off topic, but "Gilmour!" - I have tix for MSG, NYC in Nov!!

**Comment by moorecreative** [comment]
Hi @adamsadler, it's not as helpful as an "shovel-ready perfect answer" for your troubles. I can confirm that Office 365 and MS Office email is eventually able to be configured correctly to allow email sending from a DNN instance. I can confirm, though, that it is often difficult to properly configure because of the different overlapping permissions and settings which must be in place within those Office configurations.

Additionally, with our clients who can only use Office365 and MicrosoftOffice email for their DNN instances, there is once or twice a year times when their email will stop working. Tracing back the problem, we find that an administrator has clicked a button to "fix and apply all security updates" and that process removes the configurations which allowed email to send correctly.

SO, my advice to you is to, if possible, move to use a POP3/IMAP email address for sending, Or look to connecting with a service in the middle such as SendGrid which can make the email process work and will alert you when email is not sending correctly because of the Office side.

But, again, my experience has been that Office 365, and MicrosoftOffice Exchange online email addresses do work successfully within DNN. It often just takes more effort on the configuration of the Office365 side to get it working successfully.

**Comment by jeremy-farrance** [comment]
> 
> Additionally, with our clients who can only use Office365 and MicrosoftOffice email for their DNN instances, ...
> 

_This might not be helpful, but my curiosity is high gear..._ What conditions would result in this requirement? Why is that there only option?  What makes a SMTP drop service like Sendgrid, Sparkpost, or similar to be **not** an option?

**Comment by moorecreative** [comment]
Hi @jeremy-farrance , For those clients where their corporate or IT teams require that they use the Office365 for everything, it can sometimes be hard for us to get their IT to set up a traditional POP3/IMAP account either within their domain, or within another domain (sometimes we'll suggest having a domain such as "xyz-online.com or xyz-messages.com" just for server-based messages). In those situations, many times they struggle with having the correct IT person in place to help set the configurations correctly. Often they are familiar with settings for traditional Email Account usage such as Outlook or Phones which can "check messages before sending" and other features like that, or simply getting external systems marked as allowed to send out mail via their smtp.

In those situations, we either have to help set up external POP3/IMAP or use things like SendGrid in connection with their Office365.

For us, SendGrid is a GREAT option, and we will sometimes bring it into play when the Office365 client has trouble getting things configured correctly on their side... this helps as a middle-step because SendGrid can provide a traditional POP3/IMAP connection for use within DNN, but then within SendGrid has additional options for how to connect Office365 to SendGrid which include MFA login for the system.

But ultimately, SendGrid is most useful to us because they have more complete logging of the email sending actions and we use these to help troubleshoot with more robust information for the settings which are incorrect in Office365.

**Comment by mitchelsellers** [comment]
This is one of the reasons why I refuse to work with O365 for a web application delivery, too many times that it just fails

**Comment by adamsadler** [comment]
> I think you are using a wrong DNN configuration. Try Outlook.office.com without any port. I cannot check right now (David Gilmour concert! 😁) but the server address you used is indeed wrong.

Thanks @jeremy-farrance - I hope the gig was as good as it sounds!

I've given that a try and found the same error arises when sending a test email from the DNN UI.

In our standalone desktop app I mentioned, we use the standard Office 365 SMTP details (smtp.office.com, port 587) for sending and this works fine, so I assume the same can be used here.

I also appreciate the points from @moorecreative and @mitchelsellers about not using Office 365 and going with something like SendGrid - we've sometimes used Mailgun in the past too - but even if there *are* alternatives, if the system supports Office 365 with OAuth then we should be able to actually use it. It shouldn't be this difficult, and even a quick Google shows that plenty of systems now support O365 OAuth for emailing, and I assume they can't all be this "flakey".

I've got to say I'm amazed that DNN has included this feature in its current state, including the lack of documentation; unless that's indicative of the lack of faith in the integration.

Rant over!

> This might not be helpful, but my curiosity is in high gear... What conditions would result in this requirement? Why is that there only option? What makes a SMTP drop service like Sendgrid, Sparkpost, or similar to be -not- an option?

And to add to the above - we do a lot of work with small charities who often use Microsoft's NFP scheme to cover their costs of Office 365 and more. They don't have the budget to sign up for further services just to send some emails from a website - and frankly, they shouldn't have to.

**Comment by fablaser** [comment]
> > I think you are using a wrong DNN configuration. Try Outlook.office.com without any port. I cannot check right now (David Gilmour concert! 😁) but the server address you used is indeed wrong.
> 
> Thanks @fablaser - I hope the gig was as good as it sounds!
> 
> I've given that a try and found the same error arises when sending a test email from the DNN UI.

Hello, I checked right now: my actual server address is outlook.office365.com, without any port. Try it...

**Comment by adamsadler** [comment]
> Hello, I checked right now: my actual server address is outlook.office365.com, without any port. Try it...

Sadly, I received the same error. I'd also removed the extra permissions we had so that it matched the list you previously sent.

**Comment by fablaser** [comment]
> > Hello, I checked right now: my actual server address is outlook.office365.com, without any port. Try it...
> 
> Sadly, I received the same error. I'd also removed the extra permissions we had so that it matched the list you previously sent.

Did you configured delegated auth as described here? I mean the change to manifest file.

https://learn.microsoft.com/en-us/exchange/client-developer/exchange-web-services/how-to-authenticate-an-ews-application-by-using-oauth#register-your-application

**Comment by adamsadler** [comment]
> In addition to the manifest config, try also to set "admin consent" to yes to permissions (in your screenshot I see many "no" )

Admin consent has been granted on them all, yes. Where you see "No", that indicates that admin consent is not required, not that it hasn't been granted.

> Did you configured delegated auth as described here? I mean the change to manifest file.

> https://learn.microsoft.com/en-us/exchange/client-developer/exchange-web-services/how-to-authenticate-an-ews-application-by-using-oauth#register-your-application

I'll take a look at this, but given that DNN uses Mailkit's SmtpClient to send via SMTP, I'm not sure where EWS comes into play?

**Comment by fablaser** [comment]
> I'll take a look at this, but given that DNN uses Mailkit's SmtpClient to send via SMTP, I'm not sure where EWS comes into play?
Since you are using oauth with exchange, you will completely bypass SMTP protocol, so EWS will be used to grant authentication to send. It is why you should not use at all 587 port number.

**Comment by adamsadler** [comment]
> Since you are using oauth with exchange, you will completely bypass SMTP protocol, so EWS will be used to grant authentication to send. It is why you should not use at all 587 port number.

I don't believe that's entirely correct.

From my understanding, DNN uses MailKit (see MailKitMailProvider.cs), which uses SASL XOAUTH2 for authentication and SMTP for sending. There are no MS-specific APIs, such as EWS or Microsoft Graph, used for the send, so the standard Microsoft 365 SMTP details should be applicable here. In fact, we have used these standard details in our own separate OAuth integration without issue.

The ExchangeOnlineOAuthProvider is used for the authentication, both in the original authorisation step and for the authentication during a send, and whilst this does use MS APIs, this does not mean that the send is not using SMTP.
