### ISSUE TITLE
[Bug]: Resource manager permissions not being saved properly

### ISSUE THREAD

**Issue by Adeoluwa-Simeon** [dnnsoftware/Dnn.Platform#6045]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

On attempting to save permissions from the resource manager there are 3 issues:
1. Updated permissions do not reflect on the UI after they are saved
2. The saved permissions do not always update the right details in the database
3. Extra permissions (Asides read, browse, write) do not save when the write permission is checked

### 1st issue
1. Access the menu Persona Bar > Manage > Global Assets
2. Right-click the Templates folder > Edit > Go to the Permissions tab
3. Add the "Write to folder" permission to "registered users" and save
![image](https://github.com/dnnsoftware/Dnn.Platform/assets/167082920/81d4ea74-50b9-41a5-b453-a9549472b2f5)

4. Right-click the Templates folder > Edit > Go to the Permissions 
![image](https://github.com/dnnsoftware/Dnn.Platform/assets/167082920/326226ab-5321-424b-abfe-47786fcf2cc7)
Note that updated permissions do not reflect on the UI

5. Check the data in the db, there should be records saved
![image](https://github.com/dnnsoftware/Dnn.Platform/assets/167082920/e6755c29-315b-4051-aedd-8fafa1deae32)

### 2nd issue
1. Access the menu Persona Bar > Manage > Global Assets
2. Right-click the Templates folder > Edit > Go to the Permissions tab
3. Deny the "View Folder" permission then Add the "Browse Folder" permission and then save
![image](https://github.com/dnnsoftware/Dnn.Platform/assets/167082920/2cc29273-b855-4669-9a4b-d009a502bcc7)

4. Check the data is saved in the db, it does not reflect the UI, as all reflect as AllowAccess=0, while one of them should be AllowAccess=1
![image](https://github.com/dnnsoftware/Dnn.Platform/assets/167082920/f2f7ff68-e9d2-415f-bbfa-fabedb7dfc33)

### 3rd issue
1. Add an extra permission to the permissions table on the database, you can use this query
`INSERT INTO [dbo].[Permission]([PermissionCode],[ModuleDefID],[PermissionKey],[PermissionName],[ViewOrder]) VALUES ('SYSTEM_FOLDER',-1,'COPY','Copy',1)`

2. Restart the app on iis to reload the cache
3. Access the menu Persona Bar > Manage > Global Assets
4. Right-click the Templates folder > Edit > Go to the Permissions tab
5. Add all permissions and save
![image](https://github.com/dnnsoftware/Dnn.Platform/assets/167082920/34976bcd-dd00-4bcc-bfd1-91fe597ebc05)

6. Check the data is saved in the db, it does not reflect the UI, as only 3 permissions are saved, instead of 4
![image](https://github.com/dnnsoftware/Dnn.Platform/assets/167082920/de6b8253-13bd-4754-82a8-bb58aa83b41b)

### Current Behavior

Permissions not being saved properly and not being shown when saved

### Expected Behavior

Permissions being saved properly and shown when saved

### Affected Versions

9.13.3 (latest release)

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Adeoluwa-Simeon** [comment]
I would like to work on a fix for this issue, I already have a fix ready to go, so ETA can be an hour

**Comment by jeremy-farrance** [comment]
This has some (obvious?) overlap with #5857, "[Bug]: Resource Manager Error: cannot Remove Permissions on Folders" that I posted with a lot of details and easy to reproduce steps last Nov.

**Comment by Adeoluwa-Simeon** [comment]
@jeremy-farrance You are right it does, I assumed from the title and did not check to see that you reported saving issue as well.
I have a PR to fix what I have reported.

**Comment by Adeoluwa-Simeon** [comment]
## Root Cause
1. For the first issue with not returning valid permissions from the Database, the issue is with the [dbo].[GetFolderPermissionsByPortalAndPath] looking for a default -1 value for the PortalId field in the view dbo.[vw_FolderPermissions]
 
> CREATE PROCEDURE [dbo].[GetFolderPermissionsByPortalAndPath]
> @PortalId int,
>     @FolderPath nvarchar(300)
> AS
> BEGIN
>     SET @PortalId = IsNull(@PortalId, -1)
> 
>     SELECT *
>     FROM   dbo.[vw_FolderPermissions]
>     WHERE  PortalID = @PortalId AND (FolderPath = @FolderPath OR @FolderPath IS NULL)
> END

But the view dbo.[vw_FolderPermissions] provides null as the value for PortalId for these saved permissions. And then when permissions are saved, it would not load the saved permissions on the UI.

2. For the other 2 issues, they are from the front-end, there is an [adjustRelatedPermissions function](https://github.com/dnnsoftware/Dnn.Platform/blob/develop/DNN%20Platform/Modules/ResourceManager/ResourceManager.Web/src/components/dnn-rm-edit-folder/dnn-rm-edit-folder.tsx#L141-L253) used to trigger some permissions on and off when a particular permission is selected. 

Example: when 'Read' is disabled, both 'Browse' and 'Write to folder' are disabled if enabled previously.
This is called when a new selection is made and right before saving the records, the problem is:
- It does not keep track of new selections and applies the same rules to whatever check boxes are checked, such that if the rules state, when 'Read' is disabled 'Write to Folder' must  be disabled and when 'Write to Folder' is enabled, 'Read' must be enabled. If we enter a disabled 'Read' first and try to enable 'Write to Folder', both rules get applied at the same time and 'Read' stays disabled, and 'Write to Folder' may appear to be enabled but actually submits as disabled.
- Whenever write is selected only 'Read', 'Browse' and 'Write to Folder' can be submitted.

This causes the view and saved data discrepancies.

## Fix
1. Update dbo.[vw_FolderPermissions] to provide a default value -1 for portalID if it is null
![image](https://github.com/dnnsoftware/Dnn.Platform/assets/167082920/057f9b4b-6a2b-4168-b311-64ac7e1781e6)

2. Fixed the [adjustRelatedPermissions function](https://github.com/dnnsoftware/Dnn.Platform/blob/develop/DNN%20Platform/Modules/ResourceManager/ResourceManager.Web/src/components/dnn-rm-edit-folder/dnn-rm-edit-folder.tsx#L141-L253) to work properly, taking note of the new permissions and applying the adjustments also allowing other permissions save when the 'Write to Folder' is allowed.

**Comment by valadas** [comment]
#5867 has some similarities but must be slightly different issue as #6046 does fix everything mentioned here but not the other issue...
