### ISSUE TITLE
[Bug]: Suddenly "Web Server Updated" every few minutes on all sites

### ISSUE THREAD

**Issue by MarNothing** [dnnsoftware/Dnn.Platform#6113]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Admin log shows a lot of entries with Web Server Updated in DNN 9.11.2.
Cause seems to be the new "Monitor Web Servers" task.

### Steps to reproduce?

Basically just look at the admin logs page.

### Current Behavior

Lot's of entries in the admin log saying "Web Server Updated"
Even though there is a setting which says to only keep the last 10 records of this type, I can see a couple of hundreds, so there are actually 2 thing going on.
1) I don't think this should be logged so many times.
2) The cleanup function in the admin log to only keep the last XX records for this type is not really functioning.

### Expected Behavior

1) not log "Web server updated" since I don't think it really updated anything.
2) if the setting in the admin log says "keep the 10 most recent log entries, then it should only keep 10 entries, and not hundreds...

### Anything else?

See this thread in the forum:
https://dnncommunity.org/forums/using-dnn/admin-and-config/suddenly-web-server-updated-every-few-minutes-on-all-sites/2/
Related to: 
https://github.com/dnnsoftware/Dnn.Platform/issues/5575
https://github.com/dnnsoftware/Dnn.Platform/pull/5586

### Affected Versions

9.13.3 (latest release)

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by valadas** [comment]
Was this tested on 9.11.2 I am pretty sure this got fixed already in 9.13.x. If not, please report back after upgrading and I'll re-open the issue.

**Comment by valadas** [comment]
Also duplicates #5634 which was already fixed
