### ISSUE TITLE
[Bug]: Add icon is huge in pages SEO tab

### ISSUE THREAD

**Issue by ufoloko** [dnnsoftware/Dnn.Platform#6116]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

After install or upgrade last version 9.13.4, SEO section inside Advanced tab is showing in this way.

![image](https://github.com/user-attachments/assets/f3014aad-fbe0-4584-afc8-fa5b096d0283)

Icon and link for Add URL are not taking any style, so button is displaying very big.

### Steps to reproduce?

1.- Install last version 9.13.4 or simple update any site to this last version.

2.- Edit any page settings

3.- Click on Advanced tab, then SEO tab.

### Current Behavior

Button for Add URL is being showed very big, specially for the svg icon

### Expected Behavior

Button for Add URL should be displayed in this way

![image](https://github.com/user-attachments/assets/343d548b-4f6a-43c1-b8a6-92e27adf150f)

### Anything else?

This happen with last version 9.13.4, even if you install from zero or if you update a site.

### Affected Versions

9.13.4 (alpha)

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by valadas** [comment]
Hmm, that probably got missed in this update:
https://github.com/dnnsoftware/Dnn.Platform/pull/6099

The fix should be similar than what was done everywhere else but a file got somehow missed.

**Comment by ufoloko** [comment]
Hi @valadas digging a little i found something.

<img width="338" alt="image" src="https://github.com/user-attachments/assets/ca470719-ffd3-4fd5-a90d-a506cb26911a">

For some reason, that className is not being  rendering in Pages.Web client component, that should be automatically generated by webpack.

Looking a little bit webpack settings, the only difference is Pages.Web component is to have those additional config lines on css-loader plugin

<img width="712" alt="image" src="https://github.com/user-attachments/assets/c2fe99af-3179-4e26-8778-9ba4e77544d7">

I checked all other client components and don´t have those lines, so probably there can be the issue.

Sadly i was not able to run webpack because im receiving a lot of issues or warnings when running yarn install, so im not able to check if removing the lines solve the problem

**Comment by bdukes** [comment]
You may want to try running `corepack enable` to make sure the correct version of Yarn is setup.

**Comment by ufoloko** [comment]
I already tried that, but it appears is not a yarn issue, is more related with node packages

**Comment by jeremy-farrance** [comment]
I figured this out. I cannot explain why it is happening, but I would like to learn. In src\components\Seo\PageUrls\ **Table.jsx**, if you added console logging after the imports:

`console.log('styles: ', styles);`

Here is the output, notice the "AddItemRow"... the "A" is getting lowercased.

Which then requires that when you assign the className, its now `styles.addItemRow`, so:
```
        return (
            <div>
                <div className={styles.addItemRow}>
                                      ^^
```

Should I still do a fix/pull or is there an easier way to get this updated and regenerated?

After removing the console log and recompiling:
![image](https://github.com/user-attachments/assets/b6da0592-1c95-40f6-9b29-7b21af63b17a)

"No biggie!"
![image](https://github.com/user-attachments/assets/b8ea252f-ac89-4316-9693-3756da8578fe)

**Comment by david-poindexter** [comment]
Thank you @jeremy-farrance - looking forward to your PR!
