### ISSUE TITLE
[Bug]: Stupid cms project not start after build in VS 2022

### ISSUE THREAD

**Issue by ednsinf** [dnnsoftware/Dnn.Platform#6141]
Stupid cms not start after build in VS 2022

[NullReferenceException: Referência de objeto não definida para uma instância de um objeto.]
   DotNetNuke.Application.ApplicationStatusInfo.get_Status() in C:\Users\xxx\Downloads\Dnn.Platform-9.13.4\DNN Platform\Library\Application\ApplicationStatusInfo.cs:52
   DotNetNuke.Common.Initialize.Init(HttpApplication app) in C:\Users\xxx\Downloads\Dnn.Platform-9.13.4\DNN Platform\Library\Common\Initialize.cs:44
   DotNetNuke.Web.Common.Internal.DotNetNukeHttpApplication.Application_BeginRequest(Object sender, EventArgs e) in C:\Users\xxx\Downloads\Dnn.Platform-9.13.4\DNN Platform\DotNetNuke.Web\Common\DotNetNukeHttpApplication.cs:231
   System.Web.SyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +136
   System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step) +171
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +92

**Comment by jeremy-farrance** [comment]
Sounds like you are new here. Please read the documentation starting here. The first sentence addresses what you have encountered. https://github.com/dnnsoftware/Dnn.Platform/blob/develop/.github/BUILD.md

The README on the DNN Platform landing page has links to everything you might need.
![image](https://github.com/user-attachments/assets/718791b6-5f44-4853-87f1-a43cd9d2c069)

**Comment by david-poindexter** [comment]
Please review our [CODE OF CONDUCT](https://github.com/dnnsoftware/Dnn.Platform/blob/develop/CODE_OF_CONDUCT.md).  You have already been warned in another community GitHub repo.  This community is more than happy to help those in need.  However, communications need to have kindness and respect at their core.  

All issue reports that do not follow the issue template will be closed.  This will ensure the appropriate information is provided for someone to hopefully be able to help.

That said, you do not need to "build" DNN in order to install and use it.  However, if you are needing to build it, you can follow the wonderful guidance from @jeremy-farrance above.

**Comment by ednsinf** [comment]
"The project in Visual should be self-managing and allow execution without relying on external tools (SOLID principle). This clearly indicates an architectural and development error in the project."

**Comment by ednsinf** [comment]
Erro continues after run powershell script
uested by redux-devtools-dock-monitor.
➤ YN0002: │ licensing@workspace:Dnn.AdminExperience/ClientSide/Licensing.Web doesn't provide react (p209cb), requested by react-modal.
➤ YN0002: │ licensing@workspace:Dnn.AdminExperience/ClientSide/Licensing.Web doesn't provide react (pc89de), requested by react-hot-loader.
➤ YN0002: │ licensing@workspace:Dnn.AdminExperience/ClientSide/Licensing.Web doesn't provide react-dom (p5cd28), requested by react-modal.
➤ YN0002: │ licensing@workspace:Dnn.AdminExperience/ClientSide/Licensing.Web doesn't provide react-dom (pd9347), requested by react-hot-loader.
➤ YN0002: │ pages@workspace:Dnn.AdminExperience/ClientSide/Pages.Web doesn't provide eslint-plugin-import (p34223), requested by eslint-import-resolver-webpack.
➤ YN0002: │ prompt@workspace:Dnn.AdminExperience/ClientSide/Prompt.Web doesn't provide @types/react (p01734), requested by redux-devtools-dock-monitor.
➤ YN0002: │ prompt@workspace:Dnn.AdminExperience/ClientSide/Prompt.Web doesn't provide @types/react (p484ea), requested by redux-devtools-log-monitor.
➤ YN0002: │ site-import-export@workspace:Dnn.AdminExperience/ClientSide/SiteImportExport.Web doesn't provide @types/react (p13645), requested by redux-devtools-log-monitor.
➤ YN0002: │ site-import-export@workspace:Dnn.AdminExperience/ClientSide/SiteImportExport.Web doesn't provide @types/react (pe7297), requested by redux-devtools-dock-monitor.
➤ YN0002: │ users@workspace:Dnn.AdminExperience/ClientSide/Users.Web doesn't provide @types/react (p58d32), requested by redux-devtools-dock-monitor.
➤ YN0002: │ users@workspace:Dnn.AdminExperience/ClientSide/Users.Web doesn't provide @types/react (p86b65), requested by redux-devtools-log-monitor.
➤ YN0086: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code.

**Comment by ednsinf** [comment]
More erros after install and run power shell script

Linha 50:                 // first call GetProviderPath - this insures that the Database is Initialised correctly
Linha 51:                 // and also generates the appropriate error message if it cannot be initialised correctly
Linha 52:                 string strMessage = DataProvider.Instance().GetProviderPath();
Linha 53: 
Linha 54:                 // get current database version from DB

Arquivo de Origem: C:\Users\xxx\Downloads\Dnn.Platform-9.13.4\DNN Platform\Library\Application\ApplicationStatusInfo.cs    Linha: 52

Rastreamento de Pilha:


[NullReferenceException: Referência de objeto não definida para uma instância de um objeto.]
   DotNetNuke.Application.ApplicationStatusInfo.get_Status() in C:\Users\xxx\Downloads\Dnn.Platform-9.13.4\DNN Platform\Library\Application\ApplicationStatusInfo.cs:52
   DotNetNuke.Common.Initialize.Init(HttpApplication app) in C:\Users\xxx\Downloads\Dnn.Platform-9.13.4\DNN Platform\Library\Common\Initialize.cs:44
   DotNetNuke.Web.Common.Internal.DotNetNukeHttpApplication.Application_BeginRequest(Object sender, EventArgs e) in C:\Users\xxx\Downloads\Dnn.Platform-9.13.4\DNN Platform\DotNetNuke.Web\Common\DotNetNukeHttpApplication.cs:231
   System.Web.SyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +136
   System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step) +171
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +92
