### ISSUE TITLE
[Enhancement]: PersonaBar, Manage Roles - Add Role ID to Visible Information

### ISSUE THREAD

**Issue by jeremy-farrance** [dnnsoftware/Dnn.Platform#6153]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of problem

Needing Role ID while managing a DNN site is common for administrators or developers. Currently, the only ways to get this detail is to use the SQL Console or go directly digging in the database.

### Description of solution

As with previous enhancements that added User ID to the User Management page (see Issue #4412) and Page ID to Pages, we simply need to surface the Role ID on the Manage Roles page.

Visual for my proposed solution.
![image](https://github.com/user-attachments/assets/29807b7a-8b03-46dd-8f41-631b6ef80150)

### Description of alternatives considered

Might be better to move it up to the Role row so its visible in the immediate list w/o clicking edit?

### Anything else?

I plan to submit code and a pull request for this.

### Do you be plan to contribute code for this enhancement?

- [X] Yes

### Would you be interested in sponsoring this enhancement?

- [ ] Yes

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by david-poindexter** [comment]
Closed per #6154
