### ISSUE TITLE
[Enhancement]: PersonaBar, Settings, Servers, System Info, Web subtab that adds the .NET Framework Product Version

### ISSUE THREAD

**Issue by jeremy-farrance** [dnnsoftware/Dnn.Platform#6155]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of problem

On the Server Info panel under Web, only the .NET Framework CLR version is visible.

### Description of solution

After recently adding the enhanced NETFrameworkVersion in #6143, seemed like a reasonable idea to also add it to the PersonaBar details panel for the Web info. And also better label the CLR vs Product versions (including tooltip).
 
My proposed solution looks like this:
![image](https://github.com/user-attachments/assets/de0a4491-0553-456b-8fb4-ab4bd9675321)

### Anything else?

This is not a very exciting enhancement, but was a good learning experience in figuring out how to work on PersonaBar stuff. Huge thanks to @valadas for re-teaching me how to build the client side (React) components!

### Do you be plan to contribute code for this enhancement?

- [X] Yes

### Would you be interested in sponsoring this enhancement?

- [ ] Yes

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Timo-Breumelhof** [comment]
Nice :-)
