### ISSUE TITLE
[Enhancement]: DNN 10 Theme > Module Settings Active Tab Background

### ISSUE THREAD

**Issue by Timo-Breumelhof** [dnnsoftware/Dnn.Platform#6159]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of problem

In the current version of DNN 10 the Active Tab in the Module settings is white on white and thus unreadable.
See:
![image](https://github.com/user-attachments/assets/7a33089d-2da8-48ac-aeb5-9e42af24240d)

### Description of solution

Make the Tab background Blue

### Description of alternatives considered

None

### Do you be plan to contribute code for this enhancement?

- [ ] Yes

### Would you be interested in sponsoring this enhancement?

- [ ] Yes

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Timo-Breumelhof** [comment]
@david-poindexter As communicated.

**Comment by david-poindexter** [comment]
Thank you for documenting this @Timo-Breumelhof

**Comment by david-poindexter** [comment]
Closing per #6215
