### ISSUE TITLE
[Bug]: disproportionate dimension for plus icon inside of SEO settings at page level

### ISSUE THREAD

**Issue by warkhos** [dnnsoftware/Dnn.Platform#6160]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

After a clean installation several times I noticed the "plus" icon sign way too big in the SEO tab at page level

### Steps to reproduce?

1. Install the latest version 9.13.04
2. Go to page settings, SEO settings
3. You'll find the plus sign with a big dimension

### Current Behavior

The plus sign works correctly, the layout seems to have a problem.

### Expected Behavior

The icon plus sign should have the same size as the rest of icons on the page.

### Relevant log output

```shell
n/a
```

### Anything else?

![image](https://github.com/user-attachments/assets/fddb285b-68a3-4f28-85da-fd115a28ab3f)
![image](https://github.com/user-attachments/assets/3276a721-9dfe-46f5-b9b0-cde01b983d9d)

### Affected Versions

9.13.4 (alpha)

### What browsers are you seeing the problem on?

Firefox, Chrome, Microsoft Edge

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by warkhos** [comment]
I just found this problem already logged #6116; I apologize for the inconvenience. Regards.

**Comment by valadas** [comment]
I'll close this one in favor of  #6116
