### ISSUE TITLE
[Enhancement]: Use message Subject as subject of DNN Messaging Notification Emails

### ISSUE THREAD

**Issue by Timo-Breumelhof** [dnnsoftware/Dnn.Platform#6176]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of problem

When a module uses DNN messaging, the email being sent out always have a generic subject.
See: 

![image](https://github.com/user-attachments/assets/b7e251df-9ab6-4db5-aa6b-d8bcb14b0a55)

Although DNN messaging is a great way to notify users and also send out email notifications, the fact that the subject is always the same is not ideal. 
As an example the forum on DNN Community.
I get a lot of emails sent out by the community site.
During a busy period I prefer to only open the messages that are Forum replies to a thread I contributed to.
Currently you have to open an email to see what it's about, which is not very efficient.

### Description of solution

IMO if a message has a subject, we should also use that as the Subject for the email notification.

### Description of alternatives considered

I have been thinking of reasons why you would not want this behavior but I cant think of any TBH..

### Anything else?

We would really like this change for the Community Forums Module :-)

### Do you be plan to contribute code for this enhancement?

- [ ] Yes

### Would you be interested in sponsoring this enhancement?

- [ ] Yes

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Timo-Breumelhof** [comment]
@johnhenley Issue :-)

**Comment by MarietteNL** [comment]
A daily or weekly digest of messages would be nice.

**Comment by Timo-Breumelhof** [comment]
@MarietteNL do you mean for DNN or the Forums?

**Comment by johnhenley** [comment]
> @johnhenley Issue :-)

@Timo-Breumelhof I can do the code changes and put in a pull request. However, I'd like to get agreement beforehand that this enhancement is acceptable to the community. We would like it so we can enhance forums notifications at some point to use DNN notifications rather than direct emails.

**Comment by johnhenley** [comment]
> A daily or weekly digest of messages would be nice.

@MarietteNL if you're speaking about forums, we've had a long-standing request to revive that feature which was part of the "enterprise" forums I think. https://github.com/DNNCommunity/Dnn.CommunityForums/issues/163

If you're speaking about a general digest of DNN notifications/messages, that is already available in the platform if I remember correctly. And that is likely what we want to leverage for forums to provide a digest rather than reinventing our own.

**Comment by Timo-Breumelhof** [comment]
@johnhenley speaking of digest.. You can only replace the title when there's only one message included..

**Comment by johnhenley** [comment]
> @johnhenley speaking of digest.. You can only replace the title when there's only one message included..

Yes I realize that.
